[translation]
10129-StatusMessageJp = "今日は平穏な一日でありますように……"
10129-FullNameJp = "守月スズミ"
10129-FamilyNameJp = "守月"
10129-PersonalNameJp = "スズミ"
10129-SchoolYearJp = "2年生"
10129-CharacterAgeJp = "16歳"
10129-BirthdayJp = "8月31日"
10129-HobbyJp = "巡回、散策"
10129-WeaponNameJp = "セーフティー"
10129-WeaponDescJp = "スズミが持っているアサルトライフル。\n\n潜入任務のために可愛く飾られている。スズミにとっての大切なパートナー。"
10129-ProfileIntroductionJp = "トリニティ総合学園所属、自警団の潜入任務を遂行すべく、魔法少女のコスチュームを着ることになった少女。\n\n魔法少女モノに疎く、あまりコスチュームへの理解が深くない。人前に立つのも苦手ではあるが、持ち前の誠実さで逆境に立ち向かうと決めている。"
10129-CharacterSSRNewJp = "せ、先生……！\nこ、この格好は……その……違うんです！"
