[translation]
10132-BirthdayJp = "4月5日"
10132-CharacterAgeJp = "15歳"
10132-CharacterSSRNewJp = "わ、私が本当にモデルを……？"
10132-FamilyNameJp = "大野"
10132-FullNameJp = "大野ツクヨ"
10132-HobbyJp = "身代わりの術、息を潜めること"
10132-PersonalNameJp = "ツクヨ"
10132-ProfileIntroductionJp = "百鬼夜行連合学院所属、忍術研究部の部員。\n\nファッションショーの警備員として雇われたものの、モデルとしてデビューすることに。コンプレックスだった身長がモデル業界では大きな強みとなった。本人としてはモデルと部活の両立に悩んでいる模様。"
10132-SchoolYearJp = "1年生"
10132-StatusMessageJp = "立派な忍者を目指して修行中、です！"
10132-WeaponDescJp = "ツクヨが大事にしているサブマシンガン。\n\n舞台上に持っていく時も特別飾ったりはしていない。以前、ミチルとイズナに飾りつけてもらった姿が、ツクヨにとって最高の状態だからなのだろう。"
10132-WeaponNameJp = "ツクヨ流サブマシンガン"
