[translation]
101350001-BirthdayJp = "3月25日"
101350001-CharacterAgeJp = "??歳"
101350001-CharacterSSRNewJp = "な、なんですか……？\n何かあるなら言ってくださいよ！"
101350001-FamilyNameJp = "天童"
101350001-FullNameJp = "天童ケイ"
101350001-HobbyJp = "アリスのお世話、おしゃれ、ゲーム（本人は否定）"
101350001-PersonalNameJp = "ケイ"
101350001-ProfileIntroductionJp = "自身を自身として定義したケイ。\n\n人工知能からAMASへ、欠陥がある生贄から今の身体へ。紆余曲折を経てここにいる。\n\nミレニアムサイエンススクールは部活動の掛け持ちが可能な学園のため、特異現象捜査部所属ではあるものの、ゲーム開発部にいることが多い。\n\n事実上、ゲーム開発部の新任プロデューサーをしているが……本人は否定している模様。"
101350001-SchoolYearJp = "1年生"
101350001-StatusMessageJp = "ケイです。よろしくお願いします"
101350001-WeaponDescJp = "ケイ専用のレールガン。\n\n新たな一歩を踏み出した彼女に相応しい逸品となっている。"
101350001-WeaponNameJp = "ルミナス・ノヴァ"
