[translation]
10133-BirthdayJp = "6月6日"
10133-CharacterAgeJp = "17歳"
10133-CharacterSSRNewJp = "電子戦なら任せてちょうだい。\n最も合理的な解を見せてあげる。"
10133-FamilyNameJp = "調月"
10133-FullNameJp = "調月リオ"
10133-HobbyJp = "デザイン"
10133-PersonalNameJp = "リオ"
10133-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、生徒会「セミナー」の会長。\n\n未曾有の危機に対応すべく特殊スーツを身に纏った。後方支援から現場対応まで可能な合理を追求したスーツとなっている。"
10133-SchoolYearJp = "3年生"
10133-StatusMessageJp = "Tasklist /S"
10133-WeaponDescJp = "リオの護身用拳銃。\n\n特殊スーツのサポート性能によって、より正確な射撃が可能となった模様。"
10133-WeaponNameJp = "立案者"
