[translation]
10135-BirthdayJp = "3月25日"
10135-CharacterAgeJp = "??歳"
10135-CharacterSSRNewJp = "な、なんですか……？\n何かあるなら言ってくださいよ！"
10135-FullNameJp = "ケイ"
10135-HobbyJp = "アリスのお世話、おしゃれ、ゲーム（本人は否定）"
10135-PersonalNameJp = "ケイ"
10135-ProfileIntroductionJp = "新たな身体となったケイ。\n\n普段よりもややテンションが高くなっているが、本人は自覚していない模様。"
10135-SchoolYearJp = "1年生"
10135-StatusMessageJp = "ケイです。よろしくお願いします"
10135-WeaponDescJp = "ケイ専用のレールガン。\n\n新たな一歩を踏み出した彼女に相応しい逸品となっている。"
10135-WeaponNameJp = "ルミナス・ノヴァ"
