[translation]
10130-StatusMessageJp = "毎日、一歩ずつ"
10130-FullNameJp = "梯スバル"
10130-FamilyNameJp = "梯"
10130-PersonalNameJp = "スバル"
10130-SchoolYearJp = "3年生"
10130-CharacterAgeJp = "17歳"
10130-BirthdayJp = "3月9日"
10130-HobbyJp = "ハーモニカ演奏"
10130-WeaponNameJp = "Anomoios"
10130-WeaponDescJp = "スバルが使用するアサルトライフル。\n\n機能面を考慮し、スバル自身でカスタムした銃。一見して、大きな差は無いように見えるが、細かいこだわりが随所に見受けられる。"
10130-ProfileIntroductionJp = "アリウス分校所属、アリウスに残っている生徒たちを導いている少女。\n\n優しく、誰にでも親切で人当たりが良い。後輩からの信頼も厚い。後輩のためであれば、いつでも容赦なく引き金を引く覚悟ができている。"
10130-CharacterSSRNewJp = "アリウスへようこそ。"
