[translation]
10134-BirthdayJp = "3月25日"
10134-CharacterAgeJp = "??歳"
10134-CharacterSSRNewJp = "アリス、もっと世界を見てみたいです！"
10134-FamilyNameJp = "天童"
10134-FullNameJp = "天童アリス"
10134-HobbyJp = "ゲーム（特にRPG）"
10134-PersonalNameJp = "アリス"
10134-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、ゲーム開発部の部員。\n\nゲームが大好きで、少し変わったところのある少女。今は世界の運命を背負っている。"
10134-SchoolYearJp = "1年生"
10134-StatusMessageJp = "こんにちは！アリスです！"
10134-WeaponDescJp = "レールガンを軽量化し、連続射撃が可能なようにカスタマイズされたアサルトライフル。\n\n伝説の剣を手にすることで、少女は勇者となった。そう、アリスの冒険もここから始まったのだ。"
10134-WeaponNameJp = "光の剣：スーパーノヴァ for アビ・エシュフ"
