[translation]
10136-BirthdayJp = "5月1日"
10136-CharacterAgeJp = "15歳"
10136-CharacterSSRNewJp = "和泉元エイミ、現場から報告。"
10136-FamilyNameJp = "和泉元"
10136-FullNameJp = "和泉元 エイミ"
10136-HobbyJp = "ボーっとすること、音楽鑑賞"
10136-PersonalNameJp = "エイミ"
10136-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、特異現象捜査部のスペシャリスト。\n\nマークスマンとして後方支援をすべく着替えている。できるだけ肌の露出を抑えた方が支援に適していると思ったものの……暑さに耐えられなかったのか、ケープを脱いで腰に巻いている。\n\nトキと同様メインの武器をエネルギーライフルに変更した。狙撃サポート用のバイザーを装着しているため、バックパックもトキのものより遥かに大型のものとなっているのだとか。"
10136-SchoolYearJp = "1年生"
10136-StatusMessageJp = "いま対応中"
10136-WeaponDescJp = "新しく作られたエイミのエネルギーライフル。\n\n後方支援のために用意された、スペシャリスト用の武器だ。"
10136-WeaponNameJp = "マルチサポート"
