[translation]
10131-StatusMessageJp = "★★★★☆"
10131-FullNameJp = "三善タカネ"
10131-FamilyNameJp = "三善"
10131-PersonalNameJp = "タカネ"
10131-SchoolYearJp = "2年生"
10131-CharacterAgeJp = "16歳"
10131-BirthdayJp = "6月18日"
10131-HobbyJp = "読書、写真撮影、アイスホッケー観戦"
10131-WeaponNameJp = "シュヴィーブジク"
10131-WeaponDescJp = "タカネがデコレーションした拳銃。\n\n戦闘に用いるだけでなく、タカネ自身の怒りの表現にも使われることがあるのだとか……。"
10131-ProfileIntroductionJp = "レッドウィンター連邦学園所属、出版部の部員。\n\n上品で優雅、礼節を重んじるお嬢様。評論家としての腕前はたしかだが、主観が強すぎてトラブルに発展することもしばしば。「知識解放戦線」とはライバル関係にある模様。"
10131-CharacterSSRNewJp = "ごきげんよう。\nオススメの作品があるのですが、読んでみませんか？"
