[translation]
16018-BirthdayJp = "5月6日"
16018-CharacterAgeJp = "16歳"
16018-FamilyNameJp = "河駒風"
16018-FullNameJp = "河駒風ラブ"
16018-HobbyJp = "ヘルメット拭き、自販機の下を漁ること"
16018-PersonalNameJp = "ラブ"
16018-ProfileIntroductionJp = "ジャブジャブヘルメット団の隊長。\n\n部下からの信頼も厚く、姉御肌。ただ、運だけはあまり良くない模様。"
16018-SchoolYearJp = "中退"
16018-StatusMessageJp = "ジャブジャブヘルメット団、団員募集中！"
16018-WeaponDescJp = "ラブのショットガン。\n\nバットのように使われることが多いものの、丁寧に手入れされている。"
16018-WeaponNameJp = "ピンチヒッター"
