[translation]
16019-BirthdayJp = "8月16日"
16019-CharacterAgeJp = "16歳"
16019-FamilyNameJp = "飛鳥馬"
16019-FullNameJp = "飛鳥馬トキ"
16019-HobbyJp = "配信視聴（仮）、ゲーム（仮）、漫画（仮）"
16019-PersonalNameJp = "トキ"
16019-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、C&Cのエージェント兼、特異現象捜査部の現場担当。\n\n偵察任務のために着替えた姿。本人曰く、「機動力に優れた新生・飛鳥馬トキ」とのこと。また、仮ではあるが趣味を見つけることができた模様。"
16019-SchoolYearJp = "1年生"
16019-StatusMessageJp = "作戦遂行、準備完了"
16019-WeaponDescJp = "トキ専用のエネルギーピストル。\n\n本人曰く、コンセプトと雰囲気を一新したとのこと。これも新生・飛鳥馬トキの必須アイテムなのだろう。"
16019-WeaponNameJp = "サーチ＆リコン"
