[translation]
20051-BirthdayJp = "5月31日"
20051-CharacterAgeJp = "15歳"
20051-CharacterSSRNewJp = "マジカル自警団、参上です！"
20051-FamilyNameJp = "宇沢"
20051-FullNameJp = "宇沢レイサ"
20051-HobbyJp = "決闘申込み、自己紹介"
20051-PersonalNameJp = "レイサ"
20051-ProfileIntroductionJp = "トリニティ総合学園所属、自警団の潜入任務を遂行すべく、魔法少女のコスチュームを着ることになった少女。\n\n幼い頃から、魔法少女モノが大好きだったからか、とても浮かれている模様。"
20051-SchoolYearJp = "1年生"
20051-StatusMessageJp = "\"The ♡ of the Magical Girl\""
20051-WeaponDescJp = "レイサの大切なショットガン。\n\n音と光、そして火力があるから魔法の杖である、と彼女はそう主張している。"
20051-WeaponNameJp = "シューティング☆スター"
