[translation]
20050-BirthdayJp = "3月6日"
20050-CharacterAgeJp = "15歳"
20050-CharacterSSRNewJp = "ボク、遊びに来たよ！"
20050-FamilyNameJp = "薄葉"
20050-FullNameJp = "薄葉リツ"
20050-HobbyJp = "密輸、採石"
20050-PersonalNameJp = "リツ"
20050-ProfileIntroductionJp = "ワイルドハント芸術学院所属、非公認サークル特殊交易部の実務担当。\n\n現在の特殊交易部をつくった生徒であり、その怪力を活かして部の力仕事を担当している。楽観的で純粋なため、部活動そのものを楽しんでいる。"
20050-SchoolYearJp = "1年生"
20050-StatusMessageJp = "縞模様の大理石どこー！"
20050-WeaponDescJp = "リツがいつも携帯するサブマシンガン。\n\n石材に向けて引き金を引き、穴を開ける用途としてよく使うのだとか。"
20050-WeaponNameJp = "携帯用穿孔機"
