[translation]
20053-BirthdayJp = "2月22日"
20053-CharacterAgeJp = "17歳"
20053-CharacterSSRNewJp = "潜入任務も忍者の花形、ってね！\nドレス姿でいざ参らん！"
20053-FamilyNameJp = "千鳥"
20053-FullNameJp = "千鳥ミチル"
20053-HobbyJp = "新しい忍術の考案、動画作り"
20053-PersonalNameJp = "ミチル"
20053-ProfileIntroductionJp = "百鬼夜行連合学院所属、忍術研究部の部長。\n\nファッションショーの潜入警備員として雇われ、ドレスに袖を通すことに。色々と初めての経験が多い中、忍者らしくどうあるかを考えている模様。"
20053-SchoolYearJp = "3年生"
20053-StatusMessageJp = "「少女忍法帖ミチルっち」ドレス特集アップしたよ！"
20053-WeaponDescJp = "ミチルが愛用しているショットガン。\n\nなんだか今回は、持ち主と同じく少しお淑やかになっている模様。"
20053-WeaponNameJp = "ミチル流オーバーフローショットガン"
