[translation]
20052-StatusMessageJp = "出版、重版、流通"
20052-FullNameJp = "荒槇ヤクモ"
20052-FamilyNameJp = "荒槇"
20052-PersonalNameJp = "ヤクモ"
20052-SchoolYearJp = "3年生"
20052-CharacterAgeJp = "17歳"
20052-BirthdayJp = "5月18日"
20052-HobbyJp = "事業企画書の作成、鉄道路線の分析"
20052-WeaponNameJp = "プラウダ"
20052-WeaponDescJp = "ヤクモが常備している拳銃。\n\nヤクモは「銃には様々な使い道がある」と口癖のように言っている。その使い道の中には、怠けた作家に「締切を守らせる」こともあるのだとか。"
20052-ProfileIntroductionJp = "レッドウィンター連邦学園所属、出版部の部長。\n\n「レッドベア」の編集長も兼任している。一度決めると曲げない頑固な一面があり、出版部の利益のためなら手段を選ばず、無敵の行動力を発揮する。しかしそんな彼女にも、ひたむきな一面があるようで……？"
20052-CharacterSSRNewJp = "本にご興味は……ありませんかぁ？\nまぁまぁそう言わず、まずはお話だけでも。"
