[translation]
20055-BirthdayJp = "8月12日"
20055-CharacterAgeJp = "16歳"
20055-CharacterSSRNewJp = "逃げちゃ……ダメだから……！"
20055-FamilyNameJp = "花岡"
20055-FullNameJp = "花岡 ユズ"
20055-HobbyJp = "ゲーム制作"
20055-PersonalNameJp = "ユズ"
20055-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、ゲーム開発部の部長。\n\n未曾有の事態に備えて、特殊スーツに身を包んでいる。スーツの仕様はリオの強い要望によって決まったのだとか。当の本人は穴があったら入りたいほど恥ずかしがっている模様。"
20055-SchoolYearJp = "1年生"
20055-StatusMessageJp = "500 Internal Server Error"
20055-WeaponDescJp = "ユズが普段から携帯しているグレネードランチャー。\n\n色々なことが変わったけれど、これだけはずっと変わらない。"
20055-WeaponNameJp = "にゃん's ダッシュ"
