[translation]
20054-BirthdayJp = "12月10日"
20054-CharacterAgeJp = "17歳"
20054-CharacterSSRNewJp = "超天才清楚系病弱美少女のやることは変わりません。\n優雅に冷静に、一つずつ対処しましょうか。"
20054-FamilyNameJp = "明星"
20054-FullNameJp = "明星ヒマリ"
20054-HobbyJp = "今日の運勢の確認、オカルト全般"
20054-PersonalNameJp = "ヒマリ"
20054-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、ハッカー集団「ヴェリタス」の元部長で、現特異現象捜査部の部長。\n\n未曾有の危機に対応すべく、特殊スーツを身に纏った。また、新たな「車椅子」のおかげで、縦横無尽に駆けることが可能となった模様。\n\n本人は車椅子であると主張しているが、どう見てもバイクだ。"
20054-SchoolYearJp = "3年生"
20054-StatusMessageJp = "超天才清楚系美少女の活躍にご期待ください"
20054-WeaponDescJp = "ヒマリが所持している拳銃。\n\n車椅子、もといバイクに乗るようになったため、普段以上に彼女が銃を使う姿が見られるかもしれない。"
20054-WeaponNameJp = "高嶺の花"
