[translation]
1145119466 = "メールボックスに同じ商品があるため、購入できません。受け取った後、再度お試しください。"
1552023844 = "業務日報は終了しました。"
1803503960 = "このユーザーは配置コピーを許可していません。"
2938963751 = "すでに購入した商品です。"
3146430479 = "異常なログが検出されたため、{0}日間コンテンツの利用が制限されます。制限期間：{1}～{2}"
3447961601 = "受け取れる業務日報の報酬はありません。"
3696114145 = "業務日報の情報が見つかりません。"
