[translation]
2552765017-NameJP = "カノエ"
2552765017-NicknameJP = "オカルト研究会"
952072385-NameJP = "ヤクモ＆タカネ"
952072385-NicknameJP = "出版部"
1568486361-NameJP = "イズナ"
1568486361-NicknameJP = "忍術研究部"
2236098080-NameJP = "イズナ"
2236098080-NicknameJP = "忍術研究部"
4056509762-NameJP = "ミチル"
4056509762-NicknameJP = "忍術研究部"
3091219447-NameJP = "ミチル"
3091219447-NicknameJP = "忍術研究部"
2783063589-NameJP = "ツクヨ"
2783063589-NicknameJP = "忍術研究部"
3718160358-NameJP = "ツクヨ"
1339731053-NameJP = "ツクヨ"
1339731053-NicknameJP = "シャインキャットエージェンシー"
1216244885-NameJP = "ミチル＆イズナ"
1216244885-NicknameJP = "忍術研究部"
234734809-NameJP = "イズナ＆ツクヨ"
234734809-NicknameJP = "忍術研究部"
2272647969-NameJP = "リオ"
2272647969-NicknameJP = "セミナー"
74548664-NameJP = "リオ"
74548664-NicknameJP = "セミナー"
1423982009-NameJP = "トキ"
1423982009-NicknameJP = "C&C"
3614138862-NameJP = "トキ"
3614138862-NicknameJP = "C&C"
2714160656-NameJP = "アリス"
2714160656-NicknameJP = "ゲーム開発部"
1875765686-NameJP = "アリス"
1875765686-NicknameJP = "ゲーム開発部"
2286957398-NameJP = "ユズ"
2286957398-NicknameJP = "ゲーム開発部"
2716558319-NameJP = "ユズ"
2716558319-NicknameJP = "ゲーム開発部"
1451921119-NameJP = "エイミ"
1451921119-NicknameJP = "特異現象捜査部"
999629596-NameJP = "エイミ"
999629596-NicknameJP = "特異現象捜査部"
520975289-NameJP = "ヒマリ"
520975289-NicknameJP = "特異現象捜査部"
173973871-NameJP = "ケイ"
1647715460-NameJP = "ケイ"
1647715460-NicknameJP = "特異現象捜査部"
830237550-NameJP = "ケイ"
2064008127-NameJP = "ケイ"
2064008127-NicknameJP = "特異現象捜査部"
271391397-NameJP = "アリス&ケイ"
3050021557-NameJP = "モモイ"
3050021557-NicknameJP = "ゲーム開発部"
588403976-NameJP = "モモイ"
588403976-NicknameJP = "ゲーム開発部"
3621431876-NameJP = "ミドリ"
3621431876-NicknameJP = "ゲーム開発部"
3179475860-NameJP = "ミドリ"
3179475860-NicknameJP = "ゲーム開発部"
3721379331-NameJP = "ケイ"
3700647472-NameJP = "ヒマリ"
3700647472-NicknameJP = "特異現象捜査部"
510608759-NameJP = "ヒマリ"
510608759-NicknameJP = "特異現象捜査部"
1162219369-NameJP = "ヒマリ"
1162219369-NicknameJP = "特異現象捜査部"
3287782288-NameJP = "アリス"
3287782288-NicknameJP = "ゲーム開発部"
4138490498-NameJP = "マルクト"
48056105-NameJP = "デカグラマトン"
1806943221-NameJP = "アイン"
854279058-NameJP = "ソフ"
3946031200-NameJP = "オウル"
542354905-NameJP = "デカグラマトン"
543508239-NameJP = "気弱な声"
1820392486-NameJP = "落ち着いた声"
2103316679-NameJP = "はっちゃけた声"
1319864298-NameJP = "アイン"
2879153603-NameJP = "ソフ"
3975097123-NameJP = "オウル"
4152021873-NicknameJP = "玄武商会"
4262917580-NameJP = "トリニティの生徒A"
1268023238-NameJP = "トリニティの生徒B"
255403252-NameJP = "トリニティの生徒C"
1075528254-NameJP = "トリニティの生徒D"
3531421350-NameJP = "こっそり訪ねてきた生徒"
834761151-NameJP = "積極的な生徒"
75094637-NameJP = "正義実現委員会部員A＆B"
75094637-NicknameJP = "正義実現委員会"
3315771075-NameJP = "ティーパーティーの行政官"
3315771075-NicknameJP = "ティーパーティー"
4262440800-NameJP = "怒りに満ちた観客"
77123755-NameJP = "事務局放送"
405691509-NameJP = "演算科学研究部長"
1559217225-NameJP = "SEN9000"
3617955346-NameJP = "RFC9001"
1237736635-NameJP = "観客A"
1249383929-NameJP = "観客B"
2853596581-NameJP = "親衛隊員"
1803045768-NameJP = "お直し屋"
1915808128-NameJP = "怪しげな司会"
2889318663-NameJP = "怪しげなスタッフ"
1502579790-NameJP = "スタッフ"
1100690660-NameJP = "ショーの主催"
4016371047-NameJP = "講師"
4209303481-NameJP = "予備校生A"
911640099-NameJP = "予備校生B"
3718627969-NameJP = "予備校生C"
3723494323-NameJP = "予備校生D"
2670890413-NameJP = "女の子A"
3995044760-NameJP = "女の子B"
4167289789-NameJP = "トリニティの生徒B"
2485195942-NameJP = "ミレニアムの生徒B"
2808619144-NameJP = "シャインキャット"
3922698421-NameJP = "スタッフ"
1038489227-NameJP = "マネージャー"
1038489227-NicknameJP = "シャインキャットエージェンシー"
4103239362-NameJP = "店長"
3572457962-NameJP = "ラーメン同好会のメンバーA"
4281966476-NameJP = "ラーメン同好会のメンバーB"
2766602551-NameJP = "ヘルメット団幹部"
2766602551-NicknameJP = "ダダイスチック・ヘルメット団"
37543489-NameJP = "ヘルメット団"
37543489-NicknameJP = "ダダイスチック・ヘルメット団"
652069197-NameJP = "正体不明の生徒"
1026912369-NameJP = "倒れていたモデル"
4222435212-NameJP = "魑魅一座A"
2872911327-NameJP = "魑魅一座B"
1563436442-NameJP = "呉服屋の店主"
3199008718-NameJP = "救助隊員"
2098162414-NameJP = "無線"
2510180498-NameJP = "ミレニアムのセキュリティシステム"
1740254648-NameJP = "写真館の店主"
3871158668-NameJP = "職員"
864566838-NameJP = "新素材開発部員A"
864566838-NicknameJP = "新素材開発部"
3503339198-NameJP = "新素材開発部員B"
3503339198-NicknameJP = "新素材開発部"
3145778661-NameJP = "疑似科学部員"
3145778661-NicknameJP = "疑似科学部"
1538867974-NameJP = "レイバー"
3081901788-NameJP = "社会科講師"
2900052986-NameJP = "数学講師"
263915734-NameJP = "ミレニアムの生徒C"
1965217876-NameJP = "ソフ&オウル"
2591057778-NameJP = "ミレニアムの生徒A&B"
2160871802-NameJP = "盛り上がる見物客"
265913969-NameJP = "研究熱心な見物客"
2787578992-NameJP = "ゲームマニアの見物客"
174228875-NameJP = "興奮した見物客"
164561377-NameJP = "SFマニアの見物客"
409601636-NameJP = "大会の司会者"
2014783175-NameJP = "観客A"
3747013299-NameJP = "観客B"
2764576644-NameJP = "観客C"
8489425-NameJP = "対戦相手A"
4047789016-NameJP = "対戦相手B"
3187236889-NameJP = "ミレニアムの生徒A"
629383206-NameJP = "ミレニアムの生徒B"
3441854897-NameJP = "声"
3374254957-NameJP = "無名の司祭たち"
