[translation]
10129-CVGroup_UITitle_Idle1-1 = "ブルーア、アーカイ……ブ。"
10129-CVGroup_CharacterGet_Idle1-1 = "こ、これも自警団任務の延長……です。\nトリニティと先生の安全のために、尽力いたします。"
10129-CVGroup_Cafe_Idle1-1 = "ここは平和ですね……とても良いことです。"
10129-CVGroup_Cafe_Idle2-1 = "（あの方、もしかして話しかけようとしてくださっているのでは？）"
10129-CVGroup_Cafe_Idle3-1 = "（な、何か話題を……出てこない……昨晩、考えておいたのに……！）"
10129-CVGroup_Cafe_Idle4-1 = "（やはり、着替えてくるべきだったのでしょうか……）"
10129-CVGroup_Cafe_Idle5-1 = "避難経路は把握しています。"
10129-CVGroup_WeaponGet_Idle1-1 = "ええと……こういうグッズ自体は可愛いと思いますが……。\n果たして、私に似合うのでしょうか？"
10129-CVGroup_UIEventLobby_Enter1-1 = "そ、そんなに見つめられると、緊張します……。"
10129-CVGroup_UIEventLobby_Enter2-1 = "あくまで捜査のために着ているだけです。"
10129-CVGroup_UIEventLobby_Enter2-2 = "可愛い衣装だとは思いますが……。"
10129-CVGroup_UIEventLobby_Enter3-1 = "どんどん観客が増えているような……。"
10129-CVGroup_UIEventLobby_Enter4-1 = "皆さん喜んでいますね。"
10129-CVGroup_UIEventLobby_Enter4-2 = "形は何であれ、お役に立てているようで良かったです。"
10129-CVGroup_UIEventLobby_Enter5-1 = "自分のやっていることに、ちゃんと自信を持てるようになりました。"
10129-CVGroup_UIEventLobby_Enter5-2 = "ありがとうございます、先生。"
10129-CVGroup_UIEventLobby_Enter5-3 = "潜入捜査は終わりましたが、これからもパトロールは続きます。"
10129-CVGroup_UIEventLobby_Enter5-4 = "今後ともよろしくお願いいたします。"
10129-CVGroup_UIEventLobby_Idle1-1 = "ひ、引っ張ってはいけません！\n飾りではありません！"
10129-CVGroup_UIEventLobby_Idle2-1 = "6条右回りの魔法は、うーん……えっと……。"
10129-CVGroup_UIEventLobby_Idle2-2 = "慣れないセリフが多く……覚えづらいです。"
10129-CVGroup_UIEventLobby_Idle3-1 = "きゃっ！ひ、ひゃはっ！ひゃぁっ……！\nくすぐったいです……！"
10129-CVGroup_UIEventLobby_Idle3-2 = "私、本当にくすぐられるのに弱くて……！"
10129-CVGroup_UIEventLobby_Idle4-1 = "遊園地の空気が、とても好きなんです。"
10129-CVGroup_UIEventLobby_Idle4-2 = "とても……平和なので。"
10129-CVGroup_UIEventShop_Enter1-1 = "い、いらっしゃいませ。先生……。"
10129-CVGroup_UIEventShop_Enter2-1 = "お探しのものはありますか……？"
10129-CVGroup_UIEventShop_Enter3-1 = "思い出に残る任務でしたね。\nありがとうございました。"
10129-CVGroup_UIEventShop_Idle1-1 = "探しているものが見つかると良いのですが。"
10129-CVGroup_UIEventShop_Idle2-1 = "コンビニでのことを思い出しますね。"
10129-CVGroup_UIEventShop_Buy1-1 = "はい、こちらですね。"
10129-CVGroup_UIEventShop_Buy2-1 = "はい、どうぞ。"
10129-CVGroup_UIEventShop_Buy3-1 = "いつも協力してくださりありがとうございます。"
10129-CVGroup_UIEventShop_Buy4-1 = "先生のお役に立ちますよう。"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter1-1 = "古いマシンですね。ちゃんと動くのでしょうか……？"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter1-2 = "これを投入すれば動くようです。"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter2-1 = "レイサさん、楽しんでいるみたいでよかったです。"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter2-2 = "レア度が高い？カードが出るといいですね。"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter3-1 = "もう閉園時間ですね。残った分がないか確かめてみましょう。"
10129-CVGroup_UIEventFortuneGachashop_Card_Idle1-1 = "なんだか周囲からの視線を感じるのですが……。"
10129-CVGroup_UIEventFortuneGachashop_Card_Idle2-1 = "人目を集めてしまう前に、早く引きましょう……！"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck4-1 = "虹色ですね。これは良いものなのでしょうか？"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck3-1 = "ピンク色……ですね。"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck2-1 = "金色ですね。"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck1-1 = "水色ですか。爽やかですね。"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck0-1 = "黒……少し不吉ですね。"
