[translation]
10136-CVGroup_Cafe_Idle1-1 = "うう……カフェインが\n足りない。"
10136-CVGroup_Cafe_Idle2-1 = "次は先生と二人で\n来たいなぁ。"
10136-CVGroup_Cafe_Idle3-1 = "あそこで一休み……。"
10136-CVGroup_Cafe_Idle4-1 = "このバックパック、\nなんか熱い……。"
10136-CVGroup_Cafe_Idle5-1 = "平和だなぁ……。"
10136-CVGroup_CharacterGet_Idle1-1 = "この状況下……私も、着替えないとね。\nどうかな、先生。似合ってる？"
10136-CVGroup_UICarrierLobby_Enter1-1 = "居心地が良くて、効率的な場所、だけど……。"
10136-CVGroup_UICarrierLobby_Enter2-1 = "戦闘食糧って、効率は良い、けどさ……。"
10136-CVGroup_UICarrierLobby_Enter3-1 = "なんだか、無性に厨房に行きたい気分。"
10136-CVGroup_UICarrierLobby_Enter4-1 = "先生もなにか冷たいもの、飲む？"
10136-CVGroup_UICarrierLobby_Idle1-1 = "エアコンつけていい？部長が嫌がるかな？"
10136-CVGroup_UICarrierLobby_Idle2-1 = "食事って、みんなで食べたほうが効率的なのかな？"
10136-CVGroup_UICarrierLobby_Idle3-1 = "合理的じゃないけど効率的なことが、世にはあるよね。"
10136-CVGroup_UICarrierLobby_Idle4-1 = "思考がまとまらない……"
10136-CVGroup_UICarrierLobby_Idle4-2 = "身体じゃなくて、頭の中が熱いときって、"
10136-CVGroup_UICarrierLobby_Idle4-3 = "どうしたらいいのかな……。"
10136-CVGroup_UIEventMission_Buy1-1 = "やっぱり先生と話すの、\n楽しい。"
10136-CVGroup_UIEventMission_Buy2-1 = "はい、お疲れ様。"
10136-CVGroup_UIEventMission_Enter1-1 = "やっほー先生、聞こえる？"
10136-CVGroup_UIEventMission_Enter2-1 = "緊急事態だからね、\n通信で繋げてるの。"
10136-CVGroup_UIEventMission_Enter2-2 = "回線越しでも、\n顔が見れて嬉しいな。"
10136-CVGroup_UIEventMission_Idle1-1 = "通気性は確保したけど……"
10136-CVGroup_UIEventMission_Idle1-2 = "まだ暑い。\nもう一枚脱いでもーー"
10136-CVGroup_UIEventMission_Idle1-3 = "え？やめて？そう……。"
10136-CVGroup_UIEventMission_Idle1-4 = "まあ、先生が\nそう言うなら……。"
10136-CVGroup_UIEventMission_Idle2-1 = "今の私はスナイパーというより\nマークスマンなんだ。"
10136-CVGroup_UIEventMission_Idle2-2 = "移動するときは、\nチームと一緒。"
10136-CVGroup_UIEventMission_Idle2-3 = "……涼しいところに\n移動してもらえて、助かったよ。"
10136-CVGroup_UIEventMission_Interaction1-1 = "ミッションコンプリート。\n次もよろしくね。"
10136-CVGroup_UITitle_Idle1-1 = "ブルー、アーカイブ。"
10136-CVGroup_WeaponGet_Idle1-1 = "こんな形の武器は初めて、\nだけど……作戦のためにも、\n早く使いこなせるようになるね。\n……先生のためにも。"
