[translation]
10133-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ。"
10133-CVGroup_CharacterGet_Idle1-1 = "電子の領域を制する最も合理的な答えを、\n貴方に見せてあげる。"
10133-CVGroup_Cafe_Idle1-1 = "ここも概念空間の一種……要分析ね。"
10133-CVGroup_Cafe_Idle2-1 = "片づけが上手くできるようになりたい……。"
10133-CVGroup_Cafe_Idle3-1 = "……どうやら、先生の感性は私と近いようね。"
10133-CVGroup_Cafe_Idle4-1 = "「アバンギャルド君Type.メイド」を作ったら、ここに置こうかしら。"
10133-CVGroup_Cafe_Idle5-1 = "できる限り……きれいに使うわ。"
10133-CVGroup_WeaponGet_Idle1-1 = "みんなを守って見せる……\nその強い意志が、私に引き金を引かせるの。"
10133-CVGroup_UICarrierHangar_Enter1-1 = "この結果を、どう解釈すれば……。"
10133-CVGroup_UICarrierHangar_Enter2-1 = "ここは格納庫……だったのだけれど。"
10133-CVGroup_UICarrierHangar_Enter2-2 = "多目的室のようになってきたわね。"
10133-CVGroup_UICarrierHangar_Enter3-1 = "アップグレードの準備が完了したわ。"
10133-CVGroup_UICarrierHangar_Idle1-1 = "何か、打開策を……。"
10133-CVGroup_UICarrierHangar_Idle2-1 = "預言者のコアは、ここで分析しましょう。"
10133-CVGroup_UICarrierLobby_Enter1-1 = "（私はいま、ここにいる……)"
10133-CVGroup_UICarrierLobby_Enter1-2 = "(これは合理的な行動なのかしら……？）"
10133-CVGroup_UICarrierLobby_Enter2-1 = "（こういう状況だからこそ)"
10133-CVGroup_UICarrierLobby_Enter2-2 = "(ゲームをするのは合理的なのかもしれないわね……）"
10133-CVGroup_UICarrierLobby_Enter3-1 = "ここは、あらゆる可能性に備えて……。"
10133-CVGroup_UICarrierLobby_Enter4-1 = "（厨房を作っておいたのだけれど……)"
10133-CVGroup_UICarrierLobby_Enter4-2 = "(やはり非合理的だったかしら……）"
10133-CVGroup_UICarrierLobby_Enter5-1 = "（会話を上手に切り出すには、どうしたら……）"
10133-CVGroup_UICarrierLobby_Idle1-1 = "念のため、モニタリングを続けているわ。"
10133-CVGroup_UICarrierLobby_Idle2-1 = "ゲーム機……単純な装置とプログラムに過ぎないのに……。"
10133-CVGroup_UICarrierLobby_Idle3-1 = "（ゲーム開発部……ずっと思っていたのだけれど)"
10133-CVGroup_UICarrierLobby_Idle3-2 = "(予測の難しい子たちね……）"
10133-CVGroup_UICarrierLobby_Idle4-1 = "実は私……。"
10133-CVGroup_UICarrierLobby_Idle4-2 = "レトルト食品の調理にも失敗することがあるの……。"
10133-CVGroup_UICarrierLobby_Idle5-1 = "（他人と会話をする方法……)"
10133-CVGroup_UICarrierLobby_Idle5-2 = "（やはり、先生に相談を……）"
