[translation]
10130-CVGroup_Cafe_Idle1-1 = "カフェ……なんだか高そうな場所。"
10130-CVGroup_Cafe_Idle2-1 = "（なんだか……ウォータータイムを思い出す）"
10130-CVGroup_Cafe_Idle3-1 = "あれは……なんだろう。"
10130-CVGroup_Cafe_Idle4-1 = "（あまりこういうところには来られなかったなぁ……）"
10130-CVGroup_Cafe_Idle5-1 = "カフェのアルバイト……\n募集してたりするかな？"
10130-CVGroup_CharacterGet_Idle1-1 = "梯スバルです。\nお困りの際には、あなたの力になりましょう。\nまぁ……あくまで、「アリウス流」ですが。"
10130-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ、です。ふふ。"
10130-CVGroup_WeaponGet_Idle1-1 = "まだ、全然実感が湧きません……。\n朝、目が覚めるたびに夢だったんじゃないかと不安になるほどに……。\n本当に、ありがとうございます、先生。大切にします。"
