[translation]
10135-CVGroup_UITitle_Idle1-1 = "言わなきゃいけないんですよね……？\nブルー、アーカイブ。"
10135-CVGroup_CharacterGet_Idle1-1 = "こんにちは、ケイです。\n何をそんなに慌てているんですか……？\nはぁ……これから、先生のことを見守らせていただきますね。"
10135-CVGroup_Cafe_Idle1-1 = "（私だって「生徒」ですから……カフェくらい……！）"
10135-CVGroup_Cafe_Idle2-1 = "あれは……どんな味なんでしょう？"
10135-CVGroup_Cafe_Idle3-1 = "なるほど……これが、まったりするということ……。"
10135-CVGroup_Cafe_Idle4-1 = "自分の身体を持つのは……。\n不便なことでもあるんですね……。"
10135-CVGroup_Cafe_Idle5-1 = "ふふ……こうして立っているだけでも、なんだか楽しいです……。"
10135-CVGroup_WeaponGet_Idle1-1 = "遠き地の星明かり……という意味です。\nそれだけ昔のことを言っているのだと思います。\n座標によると、過去と未来は同時に存在するとも言いますから。"
10135-CVGroup_UICarrierLobby_Enter1-1 = "最初の目標に向けて、まず一歩、ですね。"
10135-CVGroup_UICarrierLobby_Enter2-1 = "皆さん、どんな飲み物がお好きでしょうか……。"
10135-CVGroup_UICarrierLobby_Enter3-1 = "この身体……結構よくできた気がします。"
10135-CVGroup_UICarrierLobby_Enter4-1 = "皆さん、お疲れ様でした。"
10135-CVGroup_UICarrierLobby_Enter5-1 = "アリスは寝に行きました。"
10135-CVGroup_UICarrierLobby_Enter6-1 = "休息が大事、という言葉が少し分かってきたかも……。"
10135-CVGroup_UICarrierLobby_Enter7-1 = "もう、あの真っ白3人組っ……！"
10135-CVGroup_UICarrierLobby_Idle1-1 = "アリスも、皆さんも、絶対に怪我はさせません。"
10135-CVGroup_UICarrierLobby_Idle2-1 = "この自販機にお金を入れる意味はあるのでしょうか……？"
10135-CVGroup_UICarrierLobby_Idle3-1 = "あの子たちの工学の腕前だけは評価しましょう。"
10135-CVGroup_UICarrierLobby_Idle4-1 = "エイミとトキは輸送船の点検に行きました。"
10135-CVGroup_UICarrierLobby_Idle5-1 = "先生も休憩を忘れずに！"
10135-CVGroup_UICarrierLobby_Idle5-2 = "あと歯磨きも！"
10135-CVGroup_UICarrierLobby_Idle6-1 = "どこも悪いところはありませんね？"
10135-CVGroup_UICarrierLobby_Idle7-1 = "……私がお姉さんなので。我慢します。"
10135-CVGroup_UIEventShop_Enter1-1 = "これは緊急時の総力戦……のようなものです。"
10135-CVGroup_UIEventShop_Enter1-2 = "せめて支援だけでも、と店舗の管理をしています。"
10135-CVGroup_UIEventShop_Enter2-1 = "急いでください先生！こっちだってギリギリなんです！"
10135-CVGroup_UIEventShop_Idle1-1 = "マルクト……そしてあの3人組……。"
10135-CVGroup_UIEventShop_Idle1-2 = "もう！誰も言うことを聞かないんですから！"
10135-CVGroup_UIEventShop_Idle2-1 = "これが終わったら……帰れるのでしょうか？"
10135-CVGroup_UIEventShop_Buy1-1 = "そこにあるはずです！急いで！"
10135-CVGroup_UIEventShop_Buy2-1 = "早く選んで指揮に戻ってください！"
10135-CVGroup_UIEventShop_Buy3-1 = "えっ？優しい言葉がほしい……？"
10135-CVGroup_UIEventShop_Buy3-2 = "寝言は時と場所を選んでください！"
10135-CVGroup_UIEventShop_Buy3-3 = "本当に……先生がいないと、ダメなんですよ、私たち。"
10135-CVGroup_UIEventShop_Buy4-1 = "他に必要な物はありませんか？"
10135-CVGroup_UIEventShop_Buy4-2 = "あまり悩む時間は残されていません。"
10135-CVGroup_UIEventMission_Enter1-1 = "継続は力なり、ですよ。"
10135-CVGroup_UIEventMission_Enter1-2 = "聞いてますか先生？"
10135-CVGroup_UIEventMission_Enter1-3 = "誠実でありなさい、と言っているのですよ？"
10135-CVGroup_UIEventMission_Enter2-1 = "こんにちは、先生。"
10135-CVGroup_UIEventMission_Enter2-2 = "今日のやることをまとめました。"
10135-CVGroup_UIEventMission_Idle1-1 = "どうかしました？"
10135-CVGroup_UIEventMission_Idle1-2 = "えっ？呼んでみただけ……ですか？"
10135-CVGroup_UIEventMission_Idle1-3 = "特に用がないなら呼ばないでください！"
10135-CVGroup_UIEventMission_Idle1-4 = "……たまになら、いいですけど。"
10135-CVGroup_UIEventMission_Idle2-1 = "わ、私はくすぐったいとか、ないですから！"
10135-CVGroup_UIEventMission_Idle2-2 = "くすぐったいとか、別に……。"
10135-CVGroup_UIEventMission_Idle2-3 = "うあ～～っ！！くらえ、こちょこちょ攻撃！！"
10135-CVGroup_UIEventMission_Buy1-1 = "……はい、どうぞ。持っていってください。"
10135-CVGroup_UIEventMission_Buy1-2 = "な、なんですか！？何か言ってほしいんですか！？"
10135-CVGroup_UIEventMission_Buy1-3 = "……よくできました、先生。"
10135-CVGroup_UIEventMission_Buy2-1 = "そろそろ来る頃だと思っていました。"
10135-CVGroup_UIEventMission_Buy2-2 = "な、なんでいきなり撫でるんですか！？"
10135-CVGroup_UIEventMission_Buy2-3 = "……やめて、とは言っていません。"
10135-CVGroup_UIEventMission_Interaction1-1 = "ほら、やればできるじゃないですか。"
10135-CVGroup_UIEventMission_Interaction1-2 = "次も頑張ってくださいね。"
10135-CVGroup_UIEventMission_Interaction1-3 = "……ねっ？"
