[translation]
10132-CVGroup_Cafe_Idle1-1 = "ううぅ……私、すごく見られてませんか……？"
10132-CVGroup_Cafe_Idle2-1 = "服に染みがついたら、大変、ですから……慎重に……。"
10132-CVGroup_Cafe_Idle3-1 = "うぅ……いっそ、あそこの家具に、紛れて……。"
10132-CVGroup_Cafe_Idle4-1 = "ドレスを着ているときは、歩き方も……気にしないと……。"
10132-CVGroup_Cafe_Idle5-1 = "（みなさん……個性的な格好を、されていますね）"
10132-CVGroup_CharacterGet_Idle1-1 = "大野ツクヨ、です！\nドレスを着てはいますが……正真正銘、忍術研究部の一員、です……！"
10132-CVGroup_UIEventLobby_Enter1-1 = "先生……！？\nこのドレス……やっぱり、変、でしょうか……？"
10132-CVGroup_UIEventLobby_Enter2-1 = "おかえりなさい、先生……。"
10132-CVGroup_UIEventLobby_Enter2-2 = "ええと、この格好は、その……。"
10132-CVGroup_UIEventLobby_Enter3-1 = "一体……何が起きてるんですか……？"
10132-CVGroup_UIEventLobby_Enter4-1 = "ステージの上は……不思議、です。"
10132-CVGroup_UIEventLobby_Enter4-2 = "たくさんの方に、見られてる、のに……。"
10132-CVGroup_UIEventLobby_Enter4-3 = "孤独、だと思う瞬間が、あります……。"
10132-CVGroup_UIEventLobby_Enter5-1 = "みなさん……！\n私……帰って、きました……！"
10132-CVGroup_UIEventLobby_Idle1-1 = "私は……この衣装に、相応しいのでしょうか……。"
10132-CVGroup_UIEventLobby_Idle2-1 = "やっぱり、目立ってます、よね……？"
10132-CVGroup_UIEventLobby_Idle2-2 = "うぅ……私、忍者なのに……。"
10132-CVGroup_UIEventLobby_Idle3-1 = "き、き、ききキレイ、ですか……！？"
10132-CVGroup_UIEventLobby_Idle3-2 = "ひゃうううぅ……。"
10132-CVGroup_UIEventLobby_Idle4-1 = "この服も――"
10132-CVGroup_UIEventLobby_Idle4-2 = "変装の術だと、思えば……。"
10132-CVGroup_UIEventMission_Buy1-1 = "さすが、です……！"
10132-CVGroup_UIEventMission_Buy1-2 = "先生ならできるって、信じてました……！"
10132-CVGroup_UIEventMission_Buy2-1 = "すごいです……！\n先生にも、忍者の才能が……！？"
10132-CVGroup_UIEventMission_Enter1-1 = "やることを、まとめて、みました……。"
10132-CVGroup_UIEventMission_Enter2-1 = "どれも簡単ではない、ですが……。"
10132-CVGroup_UIEventMission_Enter2-2 = "先生なら、きっと……！"
10132-CVGroup_UIEventMission_Idle1-1 = "えっと……私のまとめたものに……問題でも、ありましたか……？"
10132-CVGroup_UIEventMission_Idle2-1 = "先生……？どうか、しましたか……？"
10132-CVGroup_UIEventMission_Interaction1-1 = "お疲れ様、です……！\n素晴らしいフィナーレ、でした！"
10132-CVGroup_UITitle_Idle1-1 = "ブルー、アーカイブ。"
10132-CVGroup_WeaponGet_Idle1-1 = "私……これからも精一杯、頑張り、ます。\nみなさんと、立派な忍者になる、ために……！"
