[translation]
10131-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ、ですわ。"
10131-CVGroup_CharacterGet_Idle1-1 = "ごきげんよう、先生。\nレッドウィンター連邦学園、出版部所属の三善タカネと申します。\nよろしくお願い致しますわね。"
10131-CVGroup_Cafe_Idle1-1 = "ふむ……ここは、雰囲気が良いですわね。"
10131-CVGroup_Cafe_Idle2-1 = "Wi-Fi、ちゃんと繋がりますかしら？\n早く批評をアップロードしなくては……。"
10131-CVGroup_Cafe_Idle3-1 = "お茶をしながら物語を語える時間……素敵ですわね。\n本当に。"
10131-CVGroup_Cafe_Idle4-1 = "（この空間……どのように評を書けば良いのでしょう……）"
10131-CVGroup_Cafe_Idle5-1 = "写真を撮っても良いのでしょうか……？"
10131-CVGroup_WeaponGet_Idle1-1 = "ペンは銃よりも強し、という格言をご存じですか？\nええ、その通りです。\nふふっ……私の批評に心ない言葉を寄せた方々へ――\n思慮深い……「対話」をするといたしましょう。"
10131-CVGroup_UIEventLobby_Enter1-1 = "トリニティに来たのは初めてですわ……。"
10131-CVGroup_UIEventLobby_Enter1-2 = "ご、ご迷惑をおかけしないようにいたしますわね。"
10131-CVGroup_UIEventLobby_Enter2-1 = "トリニティという場所――そしてそこで生まれる物語。"
10131-CVGroup_UIEventLobby_Enter2-2 = "ふふ、私、どちらもとても気に入りましたわ。"
10131-CVGroup_UIEventLobby_Enter3-1 = "もっとも……あまりに全てが上手くいき過ぎて。"
10131-CVGroup_UIEventLobby_Enter3-2 = "少し不安にもなってしまいますが……。"
10131-CVGroup_UIEventLobby_Enter3-3 = "物語の一幕であれば、"
10131-CVGroup_UIEventLobby_Enter3-4 = "こういったシーンから波乱が生まれるものですから。"
10131-CVGroup_UIEventLobby_Enter4-1 = "やはり……そうなる気がしていましたわ。"
10131-CVGroup_UIEventLobby_Enter4-2 = "ええ……私くらいは、しっかりしませんと……。"
10131-CVGroup_UIEventLobby_Enter5-1 = "よかった……本当に、よかったですわ。"
10131-CVGroup_UIEventLobby_Enter5-2 = "心から感謝いたしますわ、先生。"
10131-CVGroup_UIEventLobby_Enter5-3 = "そして……申し訳ありません、先生。"
10131-CVGroup_UIEventLobby_Idle1-1 = "皆さんがとても親切にしてくださって、安心できました。"
10131-CVGroup_UIEventLobby_Idle1-2 = "……ですがやはり私は、ただの一生徒に過ぎませんのに。"
10131-CVGroup_UIEventLobby_Idle2-1 = "お呼びですか、先生？"
10131-CVGroup_UIEventLobby_Idle2-2 = "え？高笑い？"
10131-CVGroup_UIEventLobby_Idle2-3 = "そんなはしたない真似、こんな場所ではいたしませんわ！"
10131-CVGroup_UIEventLobby_Idle2-4 = "……私たち二人きりの場でしたら、お話は別ですが。"
10131-CVGroup_UIEventLobby_Idle3-1 = "そんな風に何度もからかうのはおやめになってください。"
10131-CVGroup_UIEventLobby_Idle3-2 = "さもないと――"
10131-CVGroup_UIEventLobby_Idle3-3 = "先生の様子を一つ残らず記録して……。"
10131-CVGroup_UIEventLobby_Idle3-4 = "評を書かせていただきますわよ？"
10131-CVGroup_UIEventLobby_Idle3-5 = "「先生は今日も三善タカネにちょっかいをかけていた」"
10131-CVGroup_UIEventLobby_Idle3-6 = "「私はこの事実をキヴォトス全土に公表することを決意した」"
10131-CVGroup_UIEventLobby_Idle3-7 = "ふふっ。そうですわよね？ご理解いただけて何よりです。"
10131-CVGroup_UIEventLobby_Idle4-1 = "見識を深めるということは、世界を見る視野を広げること。"
10131-CVGroup_UIEventLobby_Idle4-2 = "それは、自分自身の世界を拡張することでもありますわ。"
10131-CVGroup_UIEventLobby_Idle4-3 = "ですが……そう考えるうちに、"
10131-CVGroup_UIEventLobby_Idle4-4 = "ふと、気になったのです。"
10131-CVGroup_UIEventLobby_Idle4-5 = "先生の見ている世界というのは、"
10131-CVGroup_UIEventLobby_Idle4-6 = "いったいどのようなものなのでしょう……？"
10131-CVGroup_UIEventMission_Enter1-1 = "たとえトリニティにいても、日課を怠ってはなりません。"
10131-CVGroup_UIEventMission_Enter1-2 = "……好き勝手に振る舞っていては。"
10131-CVGroup_UIEventMission_Enter1-3 = "我が部長のようになってしまいますもの。"
10131-CVGroup_UIEventMission_Enter2-1 = "チェックリストを用意いたしましたわ。"
10131-CVGroup_UIEventMission_Enter2-2 = "大したものではありませんが……。"
10131-CVGroup_UIEventMission_Enter2-3 = "評の構成を考えたりするのとほとんど同じようなものですから。"
10131-CVGroup_UIEventMission_Idle1-1 = "物語というものは、小さな章の積み重ねに過ぎません。"
10131-CVGroup_UIEventMission_Idle1-2 = "執筆過程では、"
10131-CVGroup_UIEventMission_Idle1-3 = "必ずしも物語の順序通りに作られているとは限りませんが。"
10131-CVGroup_UIEventMission_Idle1-4 = "ですが、最終的に何らかの形としてまとまり、"
10131-CVGroup_UIEventMission_Idle1-5 = "表出するという意味では――"
10131-CVGroup_UIEventMission_Idle1-6 = "こうした課題を着実にこなすことと、似ているのかもしれませんわね。"
10131-CVGroup_UIEventMission_Idle2-1 = "繰り返されることは、軽んじられがちですわ。"
10131-CVGroup_UIEventMission_Idle2-2 = "だって、退屈だから……？"
10131-CVGroup_UIEventMission_Idle2-3 = "小さな積み重ねを疎かにしていては、"
10131-CVGroup_UIEventMission_Idle2-4 = "いずれ足元をすくわれますわよ。"
10131-CVGroup_UIEventMission_Idle2-5 = "優しい小言だね……？"
10131-CVGroup_UIEventMission_Idle2-6 = "え、ええ……説教くさいのは自覚しておりますとも。"
10131-CVGroup_UIEventMission_Idle2-7 = "評論家なんて所詮、重箱の隅をつつく小言屋ですもの。"
10131-CVGroup_UIEventMission_Buy1-1 = "5点満点！\nお見事ですわ！"
10131-CVGroup_UIEventMission_Buy2-1 = "誠実に課題をやり遂げた方には、"
10131-CVGroup_UIEventMission_Buy2-2 = "報酬があって然るべきですから。"
10131-CVGroup_UIEventMission_Buy2-3 = "はい、こちらをどうぞ。私のポケットマネーですわ。ふふ。"
10131-CVGroup_UIEventMission_Interaction1-1 = "今日のお仕事はこれにて終了、ですわね。"
10131-CVGroup_UIEventMission_Interaction1-2 = "では、明日もよろしくお願いいたしますわ。"
