[translation]
10134-CVGroup_UITitle_Idle1-1 = "ブルー、アーカイブ！"
10134-CVGroup_CharacterGet_Idle1-1 = "アリス、行きます！"
10134-CVGroup_Cafe_Idle1-1 = "これ……ケイにそっくりですね！"
10134-CVGroup_Cafe_Idle2-1 = "アリス、ちょっとだけ眠くなってきました……。"
10134-CVGroup_Cafe_Idle3-1 = "ここはＰＫ禁止エリアですよ！"
10134-CVGroup_Cafe_Idle4-1 = "（スキャン完了。敵性反応……無し）"
10134-CVGroup_Cafe_Idle5-1 = "充電器はどこにあるんでしょう？"
10134-CVGroup_WeaponGet_Idle1-1 = "光の剣は、いつだってアリスに進む道を示してくれました。\nそう……まるで、先生みたいに！"
10134-CVGroup_UICarrierLobby_Enter1-1 = "アリス……なんだか、ワクワクしてきました！"
10134-CVGroup_UICarrierLobby_Enter2-1 = "ゲーム機を持ってきました！"
10134-CVGroup_UICarrierLobby_Enter2-2 = "先生も一緒にいかがですか？"
10134-CVGroup_UICarrierLobby_Enter3-1 = "みんな、すごかったです！"
10134-CVGroup_UICarrierLobby_Enter4-1 = "みなさん、本当に立派でした！尊敬します！"
10134-CVGroup_UICarrierLobby_Enter5-1 = "アリスはまだ、もっと頑張れます。先生っ！"
10134-CVGroup_UICarrierLobby_Enter6-1 = "モモイもミドリも、部屋で休むって言ってました……。"
10134-CVGroup_UICarrierLobby_Idle1-1 = "……これが、世界を救うための第一歩なんですね。"
10134-CVGroup_UICarrierLobby_Idle1-2 = "アリス、頑張ります！"
10134-CVGroup_UICarrierLobby_Idle2-1 = "こういうときこそ、休息は大切です！"
10134-CVGroup_UICarrierLobby_Idle3-1 = "自由でいられるのは、いいことですね……！"
10134-CVGroup_UICarrierLobby_Idle4-1 = "勇気……それこそが、本当の力なんです！"
10134-CVGroup_UICarrierLobby_Idle5-1 = "元気を出すにはやっぱり。"
10134-CVGroup_UICarrierLobby_Idle5-2 = "何か食べたり飲んだりした方がいいですよね……。"
10134-CVGroup_UICarrierLobby_Idle6-1 = "アリスは……みんなが無事でいてくれたら。"
10134-CVGroup_UICarrierLobby_Idle6-2 = "それだけで十分なんです。"
10134-CVGroup_UIEventMission_Enter1-1 = "先生！ミッションです、ミッション！"
10134-CVGroup_UIEventMission_Enter2-1 = "今日の任務は、なんでしょう？"
10134-CVGroup_UIEventMission_Enter2-2 = "あっ、お片づけは、アリスの担当でしたね……。"
10134-CVGroup_UIEventMission_Enter3-1 = "通信で失礼します！先生！アリスです！"
10134-CVGroup_UIEventMission_Enter4-1 = "大変な状況になりましたが……。"
10134-CVGroup_UIEventMission_Enter4-2 = "一緒に乗り越えていきましょう！"
10134-CVGroup_UIEventMission_Idle1-1 = "ふっ、ふっ、ふっ……。"
10134-CVGroup_UIEventMission_Idle1-2 = "どうですか、先生、アリスの新しいアーマーは！"
10134-CVGroup_UIEventMission_Idle2-1 = "アーマーがなくても……。"
10134-CVGroup_UIEventMission_Idle2-2 = "たとえ、光の剣を失っても……。"
10134-CVGroup_UIEventMission_Idle2-3 = "それでも、アリスはアリスです。"
10134-CVGroup_UIEventMission_Idle2-4 = "みんながいてくれるなら……そして。"
10134-CVGroup_UIEventMission_Idle2-5 = "先生がいてくれるなら！"
10134-CVGroup_UIEventMission_Idle3-1 = "マルクト……。"
10134-CVGroup_UIEventMission_Idle3-2 = "すごくラスボスって感じがします！"
10134-CVGroup_UIEventMission_Idle3-3 = "倒したら……裏ボスが出てきたりとかは、しませんよね……？"
10134-CVGroup_UIEventMission_Idle4-1 = "無事に帰れたら……。"
10134-CVGroup_UIEventMission_Idle4-2 = "みんなに、ケイのことを紹介したいです！"
10134-CVGroup_UIEventMission_Buy1-1 = "ぱんぱかぱーん！"
10134-CVGroup_UIEventMission_Buy1-2 = "先生が報酬を獲得しました！"
10134-CVGroup_UIEventMission_Buy2-1 = "すごいです、先生！"
10134-CVGroup_UIEventMission_Buy2-2 = "この調子で一歩ずつ、進んでいきましょう！"
10134-CVGroup_UIEventMission_Buy3-1 = "うぅ……アリスも先生のそばで、お祝いしたいです！"
10134-CVGroup_UIEventMission_Buy4-1 = "はい！アリスは、いつも変わらない先生が、大好きです！"
10134-CVGroup_UIEventMission_Interaction1-1 = "わぁっ！アリスも嬉しいです！"
10134-CVGroup_UIEventMission_Interaction2-1 = "今回もお疲れさまでした、先生！"
