[translation]
16018-CVGroup_Cafe_Idle1-1 = "ヘルメットをかけるとこってないかしら？"
16018-CVGroup_Cafe_Idle2-1 = "どこかで……見たことがあるような……？"
16018-CVGroup_Cafe_Idle3-1 = "（話しかけてもいいのかしら……？）"
16018-CVGroup_Cafe_Idle4-1 = "ここ、なかなかいいじゃない。雨もしのげるし。"
16018-CVGroup_Cafe_Idle5-1 = "ヘルメット団のみんなも連れてきてあげればよかったわね……。"
16018-CVGroup_CharacterGet_Idle1-1 = "ジャブジャブヘルメット団のリーダー、河駒風ラブよ。\nちょ、先生！！近いってば！離れて！！"
16018-CVGroup_UIEventFortuneGachashop_Card_Enter1-1 = "ねぇ先生、これって何かわかる？"
16018-CVGroup_UIEventFortuneGachashop_Card_Enter1-2 = "……自販機、に見えるんだけど。"
16018-CVGroup_UIEventFortuneGachashop_Card_Enter2-1 = "専用のやつしか使えないみたいね。"
16018-CVGroup_UIEventFortuneGachashop_Card_Enter2-2 = "まあ、これにしか使わないだろうし……試しに一回入れてみなさいよ。"
16018-CVGroup_UIEventFortuneGachashop_Card_Enter3-1 = "あら、閉店時間みたい。残ってるやつは全部使っちゃいましょ。"
16018-CVGroup_UIEventFortuneGachashop_Card_Idle1-1 = "横に貼ってあるこの絵……あの子たちと同じ服じゃない？"
16018-CVGroup_UIEventFortuneGachashop_Card_Idle2-1 = "まさか中から不意打ちされたりとかしないわよね……？"
16018-CVGroup_UIEventFortuneGachashop_Card_Luck0-1 = "あっ、黒！うちの好きな色よ！"
16018-CVGroup_UIEventFortuneGachashop_Card_Luck1-1 = "うぅ〜ん、どれがレアでどれがハズレなのか……全然分からないわ。"
16018-CVGroup_UIEventFortuneGachashop_Card_Luck2-1 = "金色……ふふっ、なんか当たりっぽいわね！もっとあるかしら？"
16018-CVGroup_UIEventFortuneGachashop_Card_Luck3-1 = "あんまり見かけないヤツね。レアなのかしら？"
16018-CVGroup_UIEventFortuneGachashop_Card_Luck4-1 = "うわ、キラキラしてる……これって超レアってことかしら？"
16018-CVGroup_UIEventMission_Buy1-1 = "これくらいもらわないと、割に合わないわよね！"
16018-CVGroup_UIEventMission_Buy2-1 = "すごいじゃない！こういうのを待ってたのよ！"
16018-CVGroup_UIEventMission_Enter1-1 = "はぁっ、はぁっ……ちょっと、あんたら何者なのよ！？"
16018-CVGroup_UIEventMission_Enter2-1 = "魔法少女って……まさかホントに魔法を使えるとか言わないでしょうね！？"
16018-CVGroup_UIEventMission_Idle1-1 = "……って、何やってんのよ！さっさと自分の仕事しなさいっての！"
16018-CVGroup_UIEventMission_Idle1-2 = "（まったくもう……先生って人が良すぎるのが玉にキズなのよね……）"
16018-CVGroup_UIEventMission_Idle2-1 = "はぁ……知らないだろうから一応言っとくけど。"
16018-CVGroup_UIEventMission_Idle2-2 = "ヘルメットを触られると、音が反響してすごくうるさいの。"
16018-CVGroup_UIEventMission_Idle2-3 = "……"
16018-CVGroup_UIEventMission_Idle2-4 = "ちょっとだけよ……まったく。"
16018-CVGroup_UIEventMission_Interaction1-1 = "はいっ、今日のノルマ終了！楽勝だったわね。"
16018-CVGroup_UIEventMission_Interaction1-2 = "この程度、うちにかかれば朝飯前よ♪"
16018-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ！"
16018-CVGroup_WeaponGet_Idle1-1 = "あら！これほしかったのよ！ありがとね、先生♪"
