[translation]
16019-CVGroup_UITitle_Idle1-1 = "ブルー、アーカイブ。"
16019-CVGroup_CharacterGet_Idle1-1 = "パーフェクトメイド、パーフェクトリコン。\n飛鳥馬トキです。\n大船に乗ったつもりでお任せください。"
16019-CVGroup_Cafe_Idle1-1 = "休息は重要です。週休4日くらいが適切かと。"
16019-CVGroup_Cafe_Idle2-1 = "身体を休められるところはないでしょうか。"
16019-CVGroup_Cafe_Idle3-1 = "カフェインと糖分は欠かせません。"
16019-CVGroup_Cafe_Idle4-1 = "このカフェのレシピは……及第点です。"
16019-CVGroup_Cafe_Idle5-1 = "次回の任務のために休憩しておきましょう。"
16019-CVGroup_WeaponGet_Idle1-1 = "武器の変更には、思い切った決断が求められます。\n朝食のメニューを、トーストからパンケーキに変えるほどの一大事です。\nですが、先生からいただいたものなら……話は変わってきます。"
16019-CVGroup_UICarrierLobby_Enter1-1 = "カモミールティーをどうぞ。"
16019-CVGroup_UICarrierLobby_Enter1-2 = "緊張をほぐす効果があると言います。"
16019-CVGroup_UICarrierLobby_Enter2-1 = "私の活躍は、先生に見ていただければ十分です。"
16019-CVGroup_UICarrierLobby_Enter3-1 = "退屈しています。遊んでください。"
16019-CVGroup_UICarrierLobby_Enter4-1 = "最近、趣味（仮）ができました。"
16019-CVGroup_UICarrierLobby_Enter5-1 = "偵察ですか？ご指示を。"
16019-CVGroup_UICarrierLobby_Idle1-1 = "パーフェクトメイドかつベストエージェントとして。"
16019-CVGroup_UICarrierLobby_Idle1-2 = "お手伝いできることがありましたら、おっしゃってください。"
16019-CVGroup_UICarrierLobby_Idle2-1 = "軽量スーツのおかげで、より軽やかな動作が可能になりました。"
16019-CVGroup_UICarrierLobby_Idle3-1 = "もっと漫画を持ってくれば良かったです。"
16019-CVGroup_UICarrierLobby_Idle4-1 = "配信のアーカイブがあります。"
16019-CVGroup_UICarrierLobby_Idle4-2 = "私と一緒に見ませんか？"
16019-CVGroup_UICarrierLobby_Idle5-1 = "私が任務に励むのは、皆様のためです。"
16019-CVGroup_UICarrierLobby_Idle5-2 = "……と同時に、褒められるためです。"
16019-CVGroup_UIEventShop_Enter1-1 = "ようこそ、飛鳥馬トキのお店へ。"
16019-CVGroup_UIEventShop_Enter1-2 = "……嘘をつきました。みんなのお店です。"
16019-CVGroup_UIEventShop_Enter2-1 = "あまり品数は用意できませんでしたが……。"
16019-CVGroup_UIEventShop_Enter2-2 = "先生のお役に立てればと思います。"
16019-CVGroup_UIEventShop_Enter3-1 = "飛鳥馬トキです。画面越しにご挨拶いたします。"
16019-CVGroup_UIEventShop_Enter3-2 = "直接伺うべきところ、緊急事態につき通信にて失礼します。"
16019-CVGroup_UIEventShop_Enter4-1 = "緊急事態であっても、飛鳥馬トキのお店は営業しています。"
16019-CVGroup_UIEventShop_Idle1-1 = "はい、先生。私はここです。"
16019-CVGroup_UIEventShop_Idle1-2 = "逃げも隠れもしませ――"
16019-CVGroup_UIEventShop_Idle1-3 = "いえ……姿を消したら、\n先生は血眼になって探してくれますか？"
16019-CVGroup_UIEventShop_Idle2-1 = "いかがでしょうか。"
16019-CVGroup_UIEventShop_Idle2-2 = "保温性と安定性、そして心身のリラックス効果もある――"
16019-CVGroup_UIEventShop_Idle2-3 = "まるで私のような、優秀な戦闘服です。"
16019-CVGroup_UIEventShop_Idle2-4 = "先生、私と一緒にスーツの機能を確認しましょう。"
16019-CVGroup_UIEventShop_Idle2-5 = "好きなだけ私にくっついていて構いませんので、ご遠慮なく。"
16019-CVGroup_UIEventShop_Idle3-1 = "少々お待ちを。"
16019-CVGroup_UIEventShop_Idle3-2 = "パーフェクトメイドの記憶力で、在庫の場所を思い出してみせます。"
16019-CVGroup_UIEventShop_Idle4-1 = "やむを得ずオンライン対応中ですが、営業に支障はありません。"
16019-CVGroup_UIEventShop_Idle4-2 = "ベストエージェントは、活躍の場を選びませんので。"
16019-CVGroup_UIEventShop_Buy1-1 = "ご購入、ありがとうございます。"
16019-CVGroup_UIEventShop_Buy1-2 = "ちなみに、一言いただければ私も購入できます。"
16019-CVGroup_UIEventShop_Buy2-1 = "そちらの商品ですね、承知しました。"
16019-CVGroup_UIEventShop_Buy2-2 = "再入荷が完了するまで、私と遊んで待ちませんか？"
16019-CVGroup_UIEventShop_Buy3-1 = "こういうものがお好きなのですね、分かりました。"
16019-CVGroup_UIEventShop_Buy4-1 = "はい、どうぞ。\nまたのご利用をお待ちしております。"
16019-CVGroup_UIEventShop_Buy4-2 = "何度でも、私に会いに来てください。"
16019-CVGroup_UIEventShop_Buy5-1 = "はい、良いと思います。"
16019-CVGroup_UIEventShop_Buy6-1 = "その商品は、後ろの棚からお取りください。"
16019-CVGroup_UIEventShop_Buy7-1 = "買い間違えた場合には返品が可能です。"
16019-CVGroup_UIEventShop_Buy7-2 = "……すみません。できませんでした。"
16019-CVGroup_UIEventShop_Buy8-1 = "ご希望であれば、私との通話券をオマケで付けておきます。"
16019-CVGroup_UIEventShop_Buy8-2 = "もちろん、ご希望ですよね？"
