[translation]
20053-CVGroup_Cafe_Idle1-1 = "ふふ……私に気がつく人がいたらどうしよう……？"
20053-CVGroup_Cafe_Idle2-1 = "このドレス……ここで着るのはやり過ぎ……？"
20053-CVGroup_Cafe_Idle3-1 = "（ドレスと、コーヒー……あっ！このネタ使えるかも……！）"
20053-CVGroup_Cafe_Idle4-1 = "いつか絶対……！ここでファンミーティングを……！"
20053-CVGroup_Cafe_Idle5-1 = "（よし！とりあえず……人目につかない場所はどこだろ？）"
20053-CVGroup_CharacterGet_Idle1-1 = "先生殿～調子はどう？今回は潜入任務だよ！\nよろしくね！"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter1-1 = "あ、先生殿も来たんだね！"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter1-2 = "……私？どれにするか悩んでたとこ。"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter2-1 = "んん～いい匂い――"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter2-2 = "だけでもないけど！まあ、いってみよー！"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter3-1 = "ごちそうさまでした……もう何も入んない……。"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Idle1-1 = "麺とスープ……それはまさに忍者と忍術……。"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Idle2-1 = "先生殿はどんなラーメンが好き？"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck0-1 = "えっ……これ、ラーメンなの……？"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck1-1 = "悪くないけど……悪くはない……ほんと、それだけ……。"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck2-1 = "んっ、なかなかやるじゃん……？"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck3-1 = "うにゃっ……！？こ、この味は……！ "
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck4-1 = "おぉ……！"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck4-2 = "新しい忍術をひらめけそうな味だよ……！！"
20053-CVGroup_UIEventLobby_Enter1-1 = "潜入任務に持って行くなら、おにぎりか兵糧丸か――"
20053-CVGroup_UIEventLobby_Enter1-2 = "ん？\n先生殿！いらっしゃい！"
20053-CVGroup_UIEventLobby_Enter2-1 = "先生殿……良い格好じゃん。"
20053-CVGroup_UIEventLobby_Enter2-2 = "こういう感じも新鮮だね。"
20053-CVGroup_UIEventLobby_Enter3-1 = "だ～～っ！\nなんでファッションショーで戦い始めるのさっ！？"
20053-CVGroup_UIEventLobby_Enter4-1 = "ツクヨに会いたい……。"
20053-CVGroup_UIEventLobby_Enter4-2 = "元気かな……ラーメン、ちゃんと食べれてるといいけど……。"
20053-CVGroup_UIEventLobby_Enter5-1 = "忍術研究部、完全復活！"
20053-CVGroup_UIEventLobby_Enter5-2 = "先生殿も！こっちこっち！"
20053-CVGroup_UIEventLobby_Idle1-1 = "なんかヒマだなぁ……。"
20053-CVGroup_UIEventLobby_Idle1-2 = "ん？こういうこと言うと絶対何か起きるって？"
20053-CVGroup_UIEventLobby_Idle2-1 = "うぅ……これ、キツくて動きにくい……。"
20053-CVGroup_UIEventLobby_Idle2-2 = "みんなこれの何がいいの！？"
20053-CVGroup_UIEventLobby_Idle3-1 = "服装は忍者の条件にあらず……。"
20053-CVGroup_UIEventLobby_Idle3-2 = "なれば、忍者を忍者たらしめるものは何か……！？"
20053-CVGroup_UIEventLobby_Idle4-1 = "とくと見よ……！\nドレスごとき――"
20053-CVGroup_UIEventLobby_Idle4-2 = "忍者にとって何の障害でもない、ということを……！"
20053-CVGroup_UIEventShop_Buy1-1 = "おぉ～それかぁ。良い選択じゃん？"
20053-CVGroup_UIEventShop_Buy2-1 = "そう！忍者ならそれを選ばなくっちゃね！"
20053-CVGroup_UIEventShop_Buy3-1 = "こちら、温めま……。"
20053-CVGroup_UIEventShop_Buy3-2 = "あっ、間違えた。"
20053-CVGroup_UIEventShop_Buy4-1 = "おお……！それはまさに！イチオシ商品！"
20053-CVGroup_UIEventShop_Buy4-2 = "まあ、全部イチオシなんだけど！"
20053-CVGroup_UIEventShop_Enter1-1 = "いらっしゃい、先生殿！\nゆっくり見てってね。"
20053-CVGroup_UIEventShop_Enter1-2 = "あ！でも、この商品なんだけど、私が思うには―― "
20053-CVGroup_UIEventShop_Enter2-1 = "無い物以外、ぜーんぶあるよ！ふっふっふ！"
20053-CVGroup_UIEventShop_Enter3-1 = "ふっふん～早く閉めて、新しい忍者定食を食べに行こーよ！"
20053-CVGroup_UIEventShop_Idle1-1 = "選択は慎重に、購入は大胆に……！"
20053-CVGroup_UIEventShop_Idle1-2 = "それがグッズを買う時の掟……！"
20053-CVGroup_UIEventShop_Idle2-1 = "いつかここに、少女忍法帖ミチルっちのグッズを……！ "
20053-CVGroup_UITitle_Idle1-1 = "ブルゥ～！こほん……アーカイブ？"
20053-CVGroup_WeaponGet_Idle1-1 = "いいの……？私に、こんな……！\nでも、先生殿の判断なら！うん！ありがとう！"
