[translation]
20050-CVGroup_UITitle_Idle1-1 = "ブルー！アー、カイ、ブッ！"
20050-CVGroup_CharacterGet_Idle1-1 = "ボク、ワイルドハント芸術学院の薄葉リツ！\nよろしくねっ！"
20050-CVGroup_Cafe_Idle1-1 = "あのへんに作品置けるかな～？"
20050-CVGroup_Cafe_Idle2-1 = "ここ、もうちょっと風通しよくならないかな～？\nあ！……あそこ、穴あけられるかも！"
20050-CVGroup_Cafe_Idle3-1 = "コーヒーのいい匂い……表現できないかなぁ。"
20050-CVGroup_Cafe_Idle4-1 = "うーん、次の輸入品は～っと……。"
20050-CVGroup_Cafe_Idle5-1 = "ここのケーキを持って帰ったら……\nきっと、学院のみんなも喜んでくれるよね！"
20050-CVGroup_WeaponGet_Idle1-1 = "わぁ！これ、ずーっと欲しかったんだ！\nありがとね、先生！うれしい！"
20050-CVGroup_UIEventLobby_Enter1-1 = "先生！こっちこっち～！"
20050-CVGroup_UIEventLobby_Enter2-1 = "なんだか話がごちゃごちゃしちゃってるね……\nま、やるだけやってみるよ！"
20050-CVGroup_UIEventLobby_Enter3-1 = "こういう依頼は初めてだけど……\nミヨちゃんの作戦なら、きっと大丈夫！"
20050-CVGroup_UIEventLobby_Enter4-1 = "今回の依頼……\n割と面白いかも？"
20050-CVGroup_UIEventLobby_Enter5-1 = "ひゃあ～終わった終わった～\n……あれ？みんなヘロヘロ？"
20050-CVGroup_UIEventLobby_Idle1-1 = "ん、先生？ボクの顔、粉でもついてる？"
20050-CVGroup_UIEventLobby_Idle2-1 = "あは！あははっ！\nも～！そんなにつっつくなら……お返しだ～っ！"
20050-CVGroup_UIEventLobby_Idle3-1 = "み、みんな、どんよりしないで～……。"
20050-CVGroup_UIEventLobby_Idle4-1 = "どんなピンチでも大丈夫！特殊交易部は……\nいつだって、抜け道を見つけ出すんだよ！"
20050-CVGroup_UIEventMission_Enter1-1 = "楽しいことがいっぱいだよ～！\nへへ、期待しててね先生！"
20050-CVGroup_UIEventMission_Enter2-1 = "難しいことはあっても、\n不可能はな～い！"
20050-CVGroup_UIEventMission_Buy1-1 = "すっご～い！先生、なんでもできるんだね～！"
20050-CVGroup_UIEventMission_Buy2-1 = "ご褒美は忘れちゃダメだよ～"
20050-CVGroup_UIEventMission_Idle1-1 = "うん？どしたの？"
20050-CVGroup_UIEventMission_Idle2-1 = "大変だったけど、楽しかった？\nえへへ、ボクと一緒だねっ！"
20050-CVGroup_UIEventMission_Interaction1-1 = "今日はもう扉閉めちゃったんだ！また明日ね！"
