[translation]
20052-CVGroup_Cafe_Idle1-1 = "さて……新たな販路は……。"
20052-CVGroup_Cafe_Idle2-1 = "ここ、暖かくて落ち着きますねぇ……。"
20052-CVGroup_Cafe_Idle3-1 = "あそこに売り場を作ったら……ムフフ。"
20052-CVGroup_Cafe_Idle4-1 = "最近の文学は、プラットフォームビジネスのようなものでしてぇ。"
20052-CVGroup_Cafe_Idle5-1 = "さて、本日の売上は……？"
20052-CVGroup_CharacterGet_Idle1-1 = "印刷、製本、管理、流通――本に関してのご相談はレッドウィンター出版部部長、\n荒槇ヤクモまでお気軽にどうぞ。ムフフ。"
20052-CVGroup_UIEventLobby_Enter1-1 = "リスクなくしてリターンなし。"
20052-CVGroup_UIEventLobby_Enter1-2 = "さて、事業を始めましょうかぁ。"
20052-CVGroup_UIEventLobby_Enter2-1 = "今こそ、お見せしましょう。"
20052-CVGroup_UIEventLobby_Enter2-2 = "不毛の地・レッドウィンターで生き残った、我が出版部の手腕をっ！"
20052-CVGroup_UIEventLobby_Enter2-3 = "……手腕というより、"
20052-CVGroup_UIEventLobby_Enter2-4 = "サバイバル力、のほうがあってるかもしれませんがねぇ。"
20052-CVGroup_UIEventLobby_Enter3-1 = "来てますねぇ……流れが、来てますねぇ！"
20052-CVGroup_UIEventLobby_Enter3-2 = "出版部長として、これはなんとしてでもモノにしてみせますよぉ！"
20052-CVGroup_UIEventLobby_Enter4-1 = "どうしてこんなことに……。"
20052-CVGroup_UIEventLobby_Enter4-2 = "いえまあ……原因は特定できそうな気が、しますけど……。"
20052-CVGroup_UIEventLobby_Enter4-3 = "まだまだ諦めるわけにはいきませんよ……！"
20052-CVGroup_UIEventLobby_Enter5-1 = "いやぁ～一時はどうなることかと……。"
20052-CVGroup_UIEventLobby_Enter5-2 = "うまくいって良かったです～……って、反省会、ですかぁ？"
20052-CVGroup_UIEventLobby_Enter5-3 = "えっと……それはまた今度……じゃダメ、ですかねぇ……？"
20052-CVGroup_UIEventLobby_Idle1-1 = "クリエイターの皆さんは……。"
20052-CVGroup_UIEventLobby_Idle1-2 = "何かを生み出す力はあるのに、"
20052-CVGroup_UIEventLobby_Idle1-3 = "それを広めることに関しては――"
20052-CVGroup_UIEventLobby_Idle1-4 = "興味を示さないケースが、多いんですよねぇ……。"
20052-CVGroup_UIEventLobby_Idle2-1 = "本……文章とは大切なもの。"
20052-CVGroup_UIEventLobby_Idle2-2 = "それは最小限のインプットで最大限のアウトプットを引き出す――"
20052-CVGroup_UIEventLobby_Idle2-3 = "「可能性」を秘めている商品、なのですから……！"
20052-CVGroup_UIEventLobby_Idle3-1 = "何かをゼロから作り出せるということは、素晴らしいことです。"
20052-CVGroup_UIEventLobby_Idle3-2 = "それを可能にさせる才能もまた。"
20052-CVGroup_UIEventLobby_Idle3-3 = "……。"
20052-CVGroup_UIEventLobby_Idle3-4 = "良いですよねぇ、そういう才能。"
20052-CVGroup_UIEventLobby_Idle3-5 = "心から……そう思いますよぉ。"
20052-CVGroup_UIEventLobby_Idle4-1 = "トリニティの生徒の皆さんには、心から感謝しているんですよぉ？"
20052-CVGroup_UIEventLobby_Idle4-2 = "……そんな目でみないでくださいって。"
20052-CVGroup_UIEventLobby_Idle4-3 = "ちゃ～んと、本心から思っていますとも。"
20052-CVGroup_UIEventShop_Buy1-1 = "おおっ！お目が高いですねぇ先生！"
20052-CVGroup_UIEventShop_Buy1-2 = "でしたらこちらも、よろしければいかがですか？"
20052-CVGroup_UIEventShop_Buy2-1 = "ここだけの話ですが……。"
20052-CVGroup_UIEventShop_Buy2-2 = "私は成果物をこの目で確かめる瞬間が……\n一番、興奮するんですよぉ……！"
20052-CVGroup_UIEventShop_Buy3-1 = "良いですか？先生。文化とは、お金なのです。"
20052-CVGroup_UIEventShop_Buy3-2 = "すなわち、購入という行為は――"
20052-CVGroup_UIEventShop_Buy3-3 = "文化的な活動と言えるでしょう。"
20052-CVGroup_UIEventShop_Buy4-1 = "品質は保証いたしますよぉ？"
20052-CVGroup_UIEventShop_Enter1-1 = "事業の基本はなんだと思いますぅ？\n物品……？交換……？"
20052-CVGroup_UIEventShop_Enter1-2 = "もちろん、お金、ですよねぇ！"
20052-CVGroup_UIEventShop_Enter2-1 = "よくぞ来てくださりました！"
20052-CVGroup_UIEventShop_Enter2-2 = "資金と商品の行き交う、事業の現場へ！"
20052-CVGroup_UIEventShop_Enter2-3 = "ムフフ、では、どうぞごゆっくり。"
20052-CVGroup_UIEventShop_Enter3-1 = "棚の奥にお宝が眠ってることもありますから。"
20052-CVGroup_UIEventShop_Enter3-2 = "最後までよ～くみていってくださいねぇ、先生。"
20052-CVGroup_UIEventShop_Enter3-3 = "ああ、もちろん私をじっくり見ても構いませんよ？"
20052-CVGroup_UIEventShop_Idle1-1 = "私に話しかけたところで、安くなることは絶対にないですよぉ？"
20052-CVGroup_UIEventShop_Idle1-2 = "割引が一つ決定するまで、裏では数えきれないほどの交渉と……。"
20052-CVGroup_UIEventShop_Idle1-3 = "……政治的な取引が、行われているんですからぁ。"
20052-CVGroup_UIEventShop_Idle2-1 = "想像もしませんでしたよ、先生相手に事業をする日がくるだなんて。"
20052-CVGroup_UIEventShop_Idle2-2 = "いや～長生きしてみるもんですねぇ。"
20052-CVGroup_UITitle_Idle1-1 = "ブルー、アーカイブ、ムフフ。"
20052-CVGroup_WeaponGet_Idle1-1 = "馬鹿と鋏は使いよう……。\nこれからは契約を「きちんと」守らせることが\nできそうですねぇ……ムフフ。"
