[translation]
20054-CVGroup_Cafe_Idle1-1 = "（冷房の設定温度が、低すぎるのではないでしょうか）"
20054-CVGroup_Cafe_Idle2-1 = "ひと息つくにはちょうど良い場所ですね。"
20054-CVGroup_Cafe_Idle3-1 = "適度なカフェイン摂取は、メリットが多いのですよ。"
20054-CVGroup_Cafe_Idle4-1 = "リラックスできる場、というのは重要ですね。"
20054-CVGroup_Cafe_Idle5-1 = "冷たい飲み物は遠慮しておきます。"
20054-CVGroup_CharacterGet_Idle1-1 = "部長、潜入、後方支援。\n全てをこなせる超天才清楚系病弱万能美少女ハッカーこと、\n明星ヒマリ――満を持して登場です。\n先生、お待たせいたしました。"
20054-CVGroup_UICarrierBridge_Enter1-1 = "状況の把握と分析が先決です。"
20054-CVGroup_UICarrierBridge_Enter1-2 = "それさえも容易ではありませんが。"
20054-CVGroup_UICarrierBridge_Enter2-1 = "鋼鉄大陸……まさに「特異現象」ですね。"
20054-CVGroup_UICarrierBridge_Enter2-2 = "私が期待していたものとは、些か趣が異なりますけれど。"
20054-CVGroup_UICarrierBridge_Enter3-1 = "先生。最後の一撃をお願いします。"
20054-CVGroup_UICarrierBridge_Enter4-1 = "ここでできることを、探さなくては。"
20054-CVGroup_UICarrierBridge_Enter5-1 = "（先生が輸送船に戻るよう言ったのは)"
20054-CVGroup_UICarrierBridge_Enter5-2 = "(理由があるはずです）"
20054-CVGroup_UICarrierBridge_Enter6-1 = "全てを終わらせる時です。"
20054-CVGroup_UICarrierBridge_Enter6-2 = "私たちも全力を尽くします。"
20054-CVGroup_UICarrierBridge_Enter7-1 = "長い旅路も、いよいよクライマックスですね。"
20054-CVGroup_UICarrierBridge_Idle1-1 = "ついに、ここまで来ましたね。"
20054-CVGroup_UICarrierBridge_Idle2-1 = "私たちは……必ず、道を見つけ出します。"
20054-CVGroup_UICarrierBridge_Idle3-1 = "（いざという時には……と、先生はおっしゃっていました)"
20054-CVGroup_UICarrierBridge_Idle3-2 = "(それはつまり……）"
20054-CVGroup_UICarrierBridge_Idle4-1 = "皆さん……どうかご無事で……。"
20054-CVGroup_UICarrierBridge_Idle5-1 = "ご存じですか？占星術に終わりはありません。"
20054-CVGroup_UICarrierBridge_Idle5-2 = "すべては循環しているのです。"
20054-CVGroup_UICarrierLobby_Enter1-1 = "大事を成す時ほど、冷静さが肝要です。"
20054-CVGroup_UICarrierLobby_Enter2-1 = "甘いものはストレスを軽減してくれるんですよ。"
20054-CVGroup_UICarrierLobby_Enter3-1 = "息抜きに……。"
20054-CVGroup_UICarrierLobby_Enter3-2 = "何か温かい飲み物でもお作りしましょうか？"
20054-CVGroup_UICarrierLobby_Enter4-1 = "良かった……皆さんよくご無事で。"
20054-CVGroup_UICarrierLobby_Idle1-1 = "未来について、占星術で占ってみましょうか……。"
20054-CVGroup_UICarrierLobby_Idle2-1 = "今日のラッキーカラーと同じ色の飲み物は……。"
20054-CVGroup_UICarrierLobby_Idle3-1 = "コーヒーでも占いができるそうですよ。"
20054-CVGroup_UICarrierLobby_Idle4-1 = "心配は無用です。私はまだまだ元気です。"
20054-CVGroup_UITitle_Idle1-1 = "ブル～アーカイブ～"
20054-CVGroup_WeaponGet_Idle1-1 = "ありがとうございます。\n本当は、武器なんて使わずに済むのが一番なのですが……\n備えは、やはり大切ですから。"
