[translation]
20055-CVGroup_UITitle_Idle1-1 = "ブルー……すぅ……！アーカイブ！ "
20055-CVGroup_CharacterGet_Idle1-1 = "ミレニアムサイエンススクール……\nゲーム開発部の花岡ユズ、です……。\nこ、こんな格好ですが……\nよろしく、お願いします……。"
20055-CVGroup_Cafe_Idle1-1 = "（平和な日常……\n今はその\n大切さが、\nよく分かります） "
20055-CVGroup_Cafe_Idle2-1 = "ソファ……\n突然発射したり、\nしませんよね……？"
20055-CVGroup_Cafe_Idle3-1 = "あたたかくて、\nいい匂い……\nいいですね。\nえへへっ。"
20055-CVGroup_Cafe_Idle4-1 = "ロッカーには……\nしばらく、入りたく\nありません……うぅ。"
20055-CVGroup_Cafe_Idle5-1 = "やっぱり、これ……\n少し派手過ぎ\nませんか……？\nうぅぅ……。"
20055-CVGroup_WeaponGet_Idle1-1 = "練習は本番のように。\n本番はゲームのように……！\nわたし、最善を尽くします……！ "
20055-CVGroup_UICarrierLobby_Enter1-1 = "隠れられる場所……ないかな……？"
20055-CVGroup_UICarrierLobby_Enter2-1 = "ここにもゲーム機が……。"
20055-CVGroup_UICarrierLobby_Enter3-1 = "もう……降りるのは、いやです……。"
20055-CVGroup_UICarrierLobby_Enter4-1 = "先生は……こんな敵と、戦ってきたのですね……。"
20055-CVGroup_UICarrierLobby_Enter5-1 = "リオ会長も、ヒマリ先輩も……すごいです……。"
20055-CVGroup_UICarrierLobby_Idle1-1 = "や、やっぱり、ロッカーの外は危険……。"
20055-CVGroup_UICarrierLobby_Idle2-1 = "（どんなゲームがダウンロードされてるんだろ……？）"
20055-CVGroup_UICarrierLobby_Idle3-1 = "先生……一緒にいて、くれますよね……？"
20055-CVGroup_UICarrierLobby_Idle4-1 = "なんだか先生といると……怖くありません……えへへ……。"
20055-CVGroup_UICarrierLobby_Idle5-1 = "いろいろ、教えてもらっていますが……"
20055-CVGroup_UICarrierLobby_Idle5-2 = "分かるような、分からないような……。"
20055-CVGroup_UIEventShop_Enter1-1 = "い、いらっしゃいませ、\n先生……。"
20055-CVGroup_UIEventShop_Enter2-1 = "お店みたいな場所……にしては、\nどこかさみしいような。"
20055-CVGroup_UIEventShop_Idle1-1 = "うぅ……なんだか怖いです……\nううう……。"
20055-CVGroup_UIEventShop_Idle1-2 = "先生……\nわたしのこと、\n忘れませんよね……？"
20055-CVGroup_UIEventShop_Idle2-1 = "わたしにできることを、\nしたいのに……。"
20055-CVGroup_UIEventShop_Idle2-2 = "みなさん、\nすごい方ばかりで……。"
20055-CVGroup_UIEventShop_Buy1-1 = "あっ、はい……！\nそちら、ですね……！"
20055-CVGroup_UIEventShop_Buy2-1 = "店員さんっぽく……\n店員さんっぽく……。"
20055-CVGroup_UIEventShop_Buy2-2 = "いつもありがとうございます！"
20055-CVGroup_UIEventShop_Buy3-1 = "は、はい……こちら、\nどうぞ……。"
20055-CVGroup_UIEventShop_Buy4-1 = "ど、どうかこれが……。"
20055-CVGroup_UIEventShop_Buy4-2 = "みなさんの……\n役に立ちますよう、に……。"
20055-CVGroup_UIEventMission_Enter1-1 = "大丈夫です……\nわたしは大丈夫ですから……！"
20055-CVGroup_UIEventMission_Enter2-1 = "逃げちゃダメ、\n逃げちゃダメ……"
20055-CVGroup_UIEventMission_Enter2-2 = "逃げちゃ、ダメ……！"
20055-CVGroup_UIEventMission_Idle1-1 = "どんな時でも……ミッションは\n大事、ですから……。"
20055-CVGroup_UIEventMission_Idle2-1 = "どうして、こんなことに……。"
20055-CVGroup_UIEventMission_Idle3-1 = "もう少し、話せたら……。\nよかったのに……。"
20055-CVGroup_UIEventMission_Idle4-1 = "わたしに\nできることがあれば……。"
20055-CVGroup_UIEventMission_Idle4-2 = "いつでも、\n言ってください……！"
20055-CVGroup_UIEventMission_Buy1-1 = "ゲームシステムだったら、\nこう言うと思います。"
20055-CVGroup_UIEventMission_Buy1-2 = "ミッションクリア！"
20055-CVGroup_UIEventMission_Buy1-3 = "えへへっ……\nこれを言ったら、"
20055-CVGroup_UIEventMission_Buy1-4 = "少し緊張が\n解けた気がします。"
20055-CVGroup_UIEventMission_Buy2-1 = "先生は……\n怖くないですか？"
20055-CVGroup_UIEventMission_Buy2-2 = "……"
20055-CVGroup_UIEventMission_Buy2-3 = "わたしは、先生がいるから……"
20055-CVGroup_UIEventMission_Buy2-4 = "もう少し頑張ってみます。"
20055-CVGroup_UIEventMission_Interaction1-1 = "お疲れ様、でした……！\nさすが先生です……！"
