[translation]
20051-CVGroup_Cafe_Idle1-1 = "きょ、今日も……人が多い……。"
20051-CVGroup_Cafe_Idle2-1 = "な、なるべく、普段どおりに……。"
20051-CVGroup_Cafe_Idle3-1 = "（あっ！今の……知ってる話だ！）"
20051-CVGroup_Cafe_Idle4-1 = "みなさん、楽しそうですね！"
20051-CVGroup_Cafe_Idle5-1 = "（ああっ……席、取られてる……）"
20051-CVGroup_CharacterGet_Idle1-1 = "呼ばれて飛び出て！再び参りました！\n魔法少女、マジカル宇沢レイサ、登場です！"
20051-CVGroup_UIEventFortuneGachashop_Card_Enter1-1 = "わあっ！これは！カードが引けるやつですね！\nすごく懐かしいです！"
20051-CVGroup_UIEventFortuneGachashop_Card_Enter1-2 = "こう！ガコガコッ！と回せばいいんですよ！"
20051-CVGroup_UIEventFortuneGachashop_Card_Enter2-1 = "こういうの、まだ残っていたんですね！"
20051-CVGroup_UIEventFortuneGachashop_Card_Enter2-2 = "さあ先生！早く回しましょう！"
20051-CVGroup_UIEventFortuneGachashop_Card_Enter3-1 = "さあ、残った分ぜ～んぶ使って回しましょう！"
20051-CVGroup_UIEventFortuneGachashop_Card_Idle1-1 = "何が出るんでしょう！楽しみです！"
20051-CVGroup_UIEventFortuneGachashop_Card_Idle2-1 = "ここ、すごく素敵ですね！\nここが私の家だったらいいのに……！"
20051-CVGroup_UIEventFortuneGachashop_Card_Luck0-1 = "それはハズレカードですね！\n私も実物は初めて見ます！"
20051-CVGroup_UIEventFortuneGachashop_Card_Luck1-1 = "ああっ、ああ……。"
20051-CVGroup_UIEventFortuneGachashop_Card_Luck2-1 = "ゴールド！！いいですね！キラキラしています！"
20051-CVGroup_UIEventFortuneGachashop_Card_Luck3-1 = "おおっ！スーパーレア！\nあまり見かけないんですよ！"
20051-CVGroup_UIEventFortuneGachashop_Card_Luck4-1 = "ああっ！それは！ウルトラレア！？"
20051-CVGroup_UIEventFortuneGachashop_Card_Luck4-2 = "私も一度しか引いたことがない、超！レアカードですよ！？"
20051-CVGroup_UIEventLobby_Enter1-1 = "先生！こっちです！こっち！"
20051-CVGroup_UIEventLobby_Enter1-2 = "ふふっ、私の速さに目が追いつかなかったんですね？"
20051-CVGroup_UIEventLobby_Enter2-1 = "自警団のスーパーマジカルウォーリアー！"
20051-CVGroup_UIEventLobby_Enter2-2 = "テルミット～……ピンク！です！"
20051-CVGroup_UIEventLobby_Enter3-1 = "うわあ！お客さんがいっぱいですね！"
20051-CVGroup_UIEventLobby_Enter4-1 = "ふっふっふ……誰も気づいていないようですね……。"
20051-CVGroup_UIEventLobby_Enter4-2 = "平凡な私が、実は自警団のスーパーエースであり、"
20051-CVGroup_UIEventLobby_Enter4-3 = "魔法少女であることをっ……！"
20051-CVGroup_UIEventLobby_Enter5-1 = "変身は解けちゃいましたけど……"
20051-CVGroup_UIEventLobby_Enter5-2 = "魔法は終わりません！\nえへへっ！"
20051-CVGroup_UIEventLobby_Idle1-1 = "はい！テルミットピンクです！\n宇沢レイサでもあります！"
20051-CVGroup_UIEventLobby_Idle2-1 = "ふふっ、ずっと練習してきた変身のポーズを……"
20051-CVGroup_UIEventLobby_Idle2-2 = "ここでお見せしましょう！\nまずは……"
20051-CVGroup_UIEventLobby_Idle2-3 = "ひゃあっ！？"
20051-CVGroup_UIEventLobby_Idle2-4 = "い、いま……知り合いと目があった気が……。"
20051-CVGroup_UIEventLobby_Idle3-1 = "これですか？テルミットピンクのステッキです！"
20051-CVGroup_UIEventLobby_Idle3-2 = "公式のステッキはちょっと高くて……"
20051-CVGroup_UIEventLobby_Idle3-3 = "なので、自前のものをデコってみました！"
20051-CVGroup_UIEventLobby_Idle4-1 = "テルミットピンク！変身！"
20051-CVGroup_UIEventLobby_Idle4-2 = "さあ！平和を守りに行きましょう！"
20051-CVGroup_UIEventShop_Buy1-1 = "取引……すなわち、契約を交わすということ！"
20051-CVGroup_UIEventShop_Buy2-1 = "これが大人の財力……！ヒーローみたいです！"
20051-CVGroup_UIEventShop_Buy3-1 = "それ、なんだかマジカルアイテムみたいです！"
20051-CVGroup_UIEventShop_Buy4-1 = "マジカル・ショッピング！ですね！"
20051-CVGroup_UIEventShop_Enter1-1 = "シュルル～シャキーンシャキーン！！キラッ！"
20051-CVGroup_UIEventShop_Enter2-1 = "ようこそ！マジカル市場へ！"
20051-CVGroup_UIEventShop_Enter3-1 = "半額シールはないですよ！？\nここはスーパーじゃありませんから！"
20051-CVGroup_UIEventShop_Idle1-1 = "あ、この服は売り物じゃないですよ！\n一着しかないので！"
20051-CVGroup_UIEventShop_Idle2-1 = "お土産屋さんみたいで、楽しいですね！"
20051-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ！！"
20051-CVGroup_WeaponGet_Idle1-1 = "先生は、いつも優しくしてくださるんですね……。\nこうして一緒にいると……私、最強になれる気がしますっ……！"
