[translation]
10129-CVGroup_Battle_Buffed_1-1 = "支援、受け取りました！"
10129-CVGroup_Battle_Covered_1-1 = "隠れます！"
10129-CVGroup_Battle_Defense_1-1 = "抵抗をやめてください！"
10129-CVGroup_Battle_In_1-1 = "ボルトキャッチ。テ、テルミットホワイト！"
10129-CVGroup_Battle_In_2-1 = "マジカルパワー、装填完了！"
10129-CVGroup_Battle_Move_1-1 = "人目につかないといいのですが……。"
10129-CVGroup_Battle_Move_2-1 = "次の場所へ移動します。"
10129-CVGroup_Battle_Recovery_1-1 = "治癒の光、ありがとうございます！"
10129-CVGroup_Battle_TacticalAction_1-1 = "進みます！"
10129-CVGroup_Battle_Victory_1-1 = "私にとっては、正義でありつづけること……それが報酬です。"
10129-CVGroup_Battle_Victory_2-1 = "誰かを守れる力が……まだ私にもあったんですね。"
10129-CVGroup_CommonSkill-1 = "魔法を前方へ！"
10129-CVGroup_ExSkill_1-1 = "こ、これどうやってオフにするんですか！？"
10129-CVGroup_ExSkill_2-1 = "へ、変身するんですか！？え、えい！"
10129-CVGroup_ExSkill_3-1 = "ゆ、友情と！愛と！え、えっと……火力！？"
10129-CVGroup_ExSkill_Level_1-1 = "照明弾を、真上へ！"
10129-CVGroup_ExSkill_Level_2-1 = "輝かせます！"
10129-CVGroup_ExSkill_Level_3-1 = "ま、魔法の光を！"
10129-CVGroup_Formation_In_1-1 = "次のパトロール任務……ですね。"
10129-CVGroup_Formation_In_2-1 = "はっ……はい！よろしくお願いします！"
10129-CVGroup_Formation_Select-1 = "この高さがあれば、観測がスムーズにできそうです。"
10129-CVGroup_Growup_1-1 = "あ、ありがとうございます、先生……その、あまり見られると、少し恥ずかしいのですが。"
10129-CVGroup_Growup_2-1 = "私なりの正義を見守ってくださり、ありがとうございます。\nいつも感謝しています。"
10129-CVGroup_Growup_3-1 = "誰かを守り抜く力を、ずっと求めていたんです。"
10129-CVGroup_Growup_4-1 = "こうやって見守っていてくださり、ありがとうございます。"
10129-CVGroup_Relationship_Up_1-1 = "いつも一緒にいてくださり、ありがとうございます。先生。"
10129-CVGroup_Relationship_Up_2-1 = "頼ってくださること……こうして会いに来てくださることを本当にうれしく思っております。"
10129-CVGroup_Relationship_Up_3-1 = "幸せとは、案外身近にあるものなのですね。"
10129-CVGroup_Relationship_Up_4-1 = "もし許されるのでしたら……これからもずっと、先生をお守りしたいです。"
10129-CVGroup_Tactic_In_1-1 = "マジカルパトロール、開始します！"
10129-CVGroup_Tactic_In_2-1 = "只今より任務を……ひ、人が多すぎる……！"
10129-CVGroup_Tactic_Victory_1-1 = "退避完了。任務を続行します。"
10129-CVGroup_Tactic_Victory_2-1 = "安全、確保しました。先生、指示を。"
