[translation]
10134-CVGroup_Battle_Buffed_1-1 = "補給、ありがとうございます！"
10134-CVGroup_Battle_Defense_1-1 = "回避します！"
10134-CVGroup_Battle_In_1-1 = "全速前進、行きます！"
10134-CVGroup_Battle_In_2-1 = "ラジャー！出撃準備、完了です。"
10134-CVGroup_Battle_Move_1-1 = "ステージクリア！移動します！"
10134-CVGroup_Battle_Move_2-1 = "ミッションコンプリート！次のレベルへ進みます！"
10134-CVGroup_Battle_Recovery_1-1 = "装備の耐久度が回復しました！"
10134-CVGroup_Battle_TacticalAction_1-1 = "座標、確認しました！"
10134-CVGroup_Battle_Victory_1-1 = "オールクリア……先生！どうでしたか？"
10134-CVGroup_Battle_Victory_2-1 = "着陸許可を確認……ただいま戻りました！"
10134-CVGroup_CommonSkill-1 = "全弾発射！"
10134-CVGroup_ExSkill_1-1 = "これがアリスの、全力……！光よ！"
10134-CVGroup_ExSkill_2-1 = "アリスには見えます……！これが、マッハの世界……！"
10134-CVGroup_ExSkill_3-1 = "行きましょう、アビ・エシュフ……光よ！"
10134-CVGroup_ExSkill_4-1 = "アリスの魔力は……100%です！"
10134-CVGroup_ExSkill_5-1 = "アビ・エシュフ……システム、オールグリーン！"
10134-CVGroup_ExSkill_6-1 = "リミッター解除……アリス、出撃します！"
10134-CVGroup_ExSkill_Level_1-1 = "ここからは、アリスのターンです！"
10134-CVGroup_ExSkill_Level_2-1 = "暗雲を貫く、光の一撃を！"
10134-CVGroup_ExSkill_Level_3-1 = "最大火力展開！目標、制圧します！"
10134-CVGroup_ExSkill_Level_4-1 = "オーバードライブ！"
10134-CVGroup_ExSkill_Level_5-1 = "エナジーブースト！"
10134-CVGroup_ExSkill_Level_6-1 = "みんなの勇気を、ひとつに……。"
10134-CVGroup_Formation_In_1-1 = "はい、アリスはいつでも行けます！"
10134-CVGroup_Formation_In_2-1 = "システム、オンライン。"
10134-CVGroup_Formation_Select-1 = "先生も、一緒に空を飛んでみませんか？"
10134-CVGroup_Growup_1-1 = "先生は、いつだってアリスを守ってくれました。\n今度は、アリスが先生を守る番です。"
10134-CVGroup_Growup_2-1 = "アリスはもっとたくさん学びたいです！\nもっと、色んなことを知りたいです！"
10134-CVGroup_Growup_3-1 = "この世界には、アリスよりも強い冒険者がたくさんいます。\nだから、アリスはもっと強くなりたいんです！"
10134-CVGroup_Growup_4-1 = "どんな世界でも、勇者は魔王と戦うものです。\nでも……戦わずに済む方法は、ないんでしょうか？"
10134-CVGroup_Relationship_Up_1-1 = "先生、これからもずっと、アリスのそばにいてくださいね！"
10134-CVGroup_Relationship_Up_2-1 = "やっぱり、アリスは先生が大好きです！"
10134-CVGroup_Relationship_Up_3-1 = "アリス、先生と一緒にいろんな世界を冒険してみたいです！"
10134-CVGroup_Relationship_Up_4-1 = "今この瞬間、アリスは先生と一緒にいられて、すごく幸せな気持ちです。\n先生も、同じ気持ちですか？"
10134-CVGroup_Tactic_In_1-1 = "スキャン完了。このエリアをアリスの管理下に置きました。"
10134-CVGroup_Tactic_In_2-1 = "新たなステージへ突入しました。"
10134-CVGroup_Tactic_Victory_1-1 = "作戦成功。アリス、基地へ帰還します！"
10134-CVGroup_Tactic_Victory_2-1 = "ミッションクリア！敵性反応は消失しました。"
