[translation]
10136-CVGroup_Battle_Buffed_1-1 = "ありがとう、このあともよろしくね。"
10136-CVGroup_Battle_Defense_1-1 = "攻撃、無効化。"
10136-CVGroup_Battle_In_1-1 = "後方は任せて。"
10136-CVGroup_Battle_In_2-1 = "異常信号を確認。"
10136-CVGroup_Battle_Move_1-1 = "次のエリアへ行くよ。"
10136-CVGroup_Battle_Move_2-1 = "エリア占領、成功。"
10136-CVGroup_Battle_Recovery_1-1 = "戦術支援を確認。"
10136-CVGroup_Battle_TacticalAction_1-1 = "戦術移動、開始。"
10136-CVGroup_Battle_Victory_1-1 = "見てくれた？先生。私、やれたよ。"
10136-CVGroup_Battle_Victory_2-1 = "もう大丈夫だよ先生。敵はいない。"
10136-CVGroup_CommonSkill-1 = "これはちょっと熱いかも？"
10136-CVGroup_ExSkill_1-1 = "対象を消去。"
10136-CVGroup_ExSkill_2-1 = "次のターゲット。"
10136-CVGroup_ExSkill_3-1 = "やっぱ、ちょっと暑いね。"
10136-CVGroup_ExSkill_Level_1-1 = "うん、頑張ってみる。"
10136-CVGroup_ExSkill_Level_2-1 = "ターゲットを指定。"
10136-CVGroup_ExSkill_Level_3-1 = "あそこだよ。"
10136-CVGroup_Formation_In_1-1 = "ターゲットを教えて。"
10136-CVGroup_Formation_In_2-1 = "今日の私はマークスマンだよ。"
10136-CVGroup_Formation_Select-1 = "先生のハートにロックオン。\n……やっぱ、あんま慣れないね。"
10136-CVGroup_Growup_1-1 = "ちょっとは成長できたのかな。"
10136-CVGroup_Growup_2-1 = "成長してるなら良かったかも。作戦の効率的にも。"
10136-CVGroup_Growup_3-1 = "ありがとう、先生。\nおかげで私、強くなれた。"
10136-CVGroup_Growup_4-1 = "変われたのかな？\n接することで変わっていく、とはいうけど。"
10136-CVGroup_Relationship_Up_1-1 = "その……今さら、かもしれないけど。\nマイペースすぎるっていう自覚はあるの。\nだから、いきすぎないように、先生に見守っててほしいな。"
10136-CVGroup_Relationship_Up_2-1 = "もうちょっとこっち、来て。\nほら、くっついたらちょうどよくなった。\n互いの体温を分け合うのって、効率的でしょ？"
10136-CVGroup_Relationship_Up_3-1 = "改めて振り返ると、不思議でいっぱいだなぁって思うんだ。\nその中でも私にとって一番不思議な存在は……先生、かな。\nふふ、先生って本当に面白いから。"
10136-CVGroup_Relationship_Up_4-1 = "何かあったらすぐ呼んで。\n絶対、私が守るから。\nそのためなら……どんな代償を支払うことになっても、構わないよ。"
10136-CVGroup_Tactic_In_1-1 = "威力偵察、始めるよ。"
10136-CVGroup_Tactic_In_2-1 = "目標は、サーチアンドデストロイ、だよ。"
10136-CVGroup_Tactic_Victory_1-1 = "どう先生？良い感じだったでしょ？"
10136-CVGroup_Tactic_Victory_2-1 = "ここはもう安全。"
