[translation]
10130-CVGroup_Battle_Buffed_1-1 = "ありがとうございます。精進いたします。"
10130-CVGroup_Battle_Covered_1-1 = "遮蔽します。支援をお願いします。"
10130-CVGroup_Battle_Defense_1-1 = "まだまだです！"
10130-CVGroup_Battle_In_1-1 = "突入します。私に続いてください。"
10130-CVGroup_Battle_In_2-1 = "大丈夫です。私を信じて。"
10130-CVGroup_Battle_Move_1-1 = "クリア。"
10130-CVGroup_Battle_Move_2-1 = "前進します。"
10130-CVGroup_Battle_Recovery_1-1 = "ありがとうございます、助かりました。"
10130-CVGroup_Battle_TacticalAction_1-1 = "移動します。"
10130-CVGroup_Battle_Victory_1-1 = "ご満足いただけたでしょうか？それなら何よりです。"
10130-CVGroup_Battle_Victory_2-1 = "制圧完了です。これで解決してほしいのですが。"
10130-CVGroup_CommonSkill-1 = "何点満点中、どのくらいでしょうか？先生。"
10130-CVGroup_ExSkill_1-1 = "……みんなが、待っているんです。"
10130-CVGroup_ExSkill_2-1 = "……仕事、ですから。"
10130-CVGroup_ExSkill_3-1 = "……早く終わらせましょうか。"
10130-CVGroup_ExSkill_Level_1-1 = "リロード、完了。"
10130-CVGroup_ExSkill_Level_2-1 = "戦闘を続けます。"
10130-CVGroup_ExSkill_Level_3-1 = "制圧射撃、開始。"
10130-CVGroup_Formation_In_1-1 = "はい、先生。"
10130-CVGroup_Formation_In_2-1 = "分かりました、準備します。"
10130-CVGroup_Formation_Select-1 = "わあっ！？\nお、驚いてなんかいません……ほ、本当です。"
10130-CVGroup_Growup_1-1 = "不思議な感覚がします……。\nこれが外でいうところの「成長」なのでしょうか。"
10130-CVGroup_Growup_2-1 = "これが成長の実感、なのでしょうか。\n私もこうして前に進むことができるのですね。"
10130-CVGroup_Growup_3-1 = "私、変わりたいと思っているんです。\n……他のみんなには、内緒にしててくださいね？"
10130-CVGroup_Growup_4-1 = "「私を信じてついてきて」……？\nはぁ……その自信は一体どこから湧いて来るんですか？\nまぁでも……一回くらいなら、信じても構いませんが。"
10130-CVGroup_Relationship_Up_1-1 = "改めて言葉にするのは少し照れ臭いですね。\nどう伝えるのが一番良いのか、迷ったのですが……\nやっぱり、シンプルなものが一番かな、と。\nその……先生が居てくださって、本当に良かったです。"
10130-CVGroup_Relationship_Up_2-1 = "本当は、まだ先生のことを100％信用しているわけじゃないんです。\nでも……95％くらいは、信じていますよ。"
10130-CVGroup_Relationship_Up_3-1 = "どの生徒も、先生にとっては大切な存在だと言っていましたよね。\nはじめはよく理解できてなかったのですが……最近、その意味が分かるようになったんです。\n同時に、少しだけ残念にも思ってしまうのですが……。"
10130-CVGroup_Relationship_Up_4-1 = "よく先生は頼ってほしい、と言ってくださりますが……\n私としてはそれだけではなんだか申し訳ないというか……物足りないというか。\nふ、深い意味はないです！\nただ、その……私も恩返しがしたいな、と。助けてもらった分だけ返すのがアリウス流ですから。"
10130-CVGroup_Tactic_In_1-1 = "さて、どのような場所なのでしょうか。"
10130-CVGroup_Tactic_In_2-1 = "なるほど、こういう感じなのですね。"
10130-CVGroup_Tactic_Victory_1-1 = "手ごたえのある戦いでした。"
10130-CVGroup_Tactic_Victory_2-1 = "これがアリウス流、です。"
