[translation]
10131-CVGroup_Battle_Buffed_1-1 = "ご厚意、感謝いたします。"
10131-CVGroup_Battle_Covered_1-1 = "時には筆を置くことも肝要です。"
10131-CVGroup_Battle_Defense_1-1 = "その程度なのですか？"
10131-CVGroup_Battle_In_1-1 = "視線を前に、歩みは堂々と。\n姿勢にこそ人柄がでるものですから。"
10131-CVGroup_Battle_In_2-1 = "良い始まりは、良い結末を導くもの。\n物語がそうであるように。"
10131-CVGroup_Battle_Move_1-1 = "終わりとはすなわち、新たな始まりを意味します。"
10131-CVGroup_Battle_Move_2-1 = "次の段落へ進みましょう。"
10131-CVGroup_Battle_Recovery_1-1 = "感謝いたしますわ。"
10131-CVGroup_Battle_TacticalAction_1-1 = "あちら、でしょうか……？"
10131-CVGroup_Battle_Victory_1-1 = "ふぅ……星5……少なくとも星4のレビューは固いですわね。"
10131-CVGroup_Battle_Victory_2-1 = "最善を尽くした皆さんに、賛辞と栄光を。"
10131-CVGroup_CommonSkill-1 = "こちらをお使いになって。"
10131-CVGroup_ExSkill_1-1 = "まったく……！\n気をつけてください！"
10131-CVGroup_ExSkill_2-1 = "いつでも余裕をお忘れなく。"
10131-CVGroup_ExSkill_3-1 = "気品を胸に。\n前を向くのですわ。"
10131-CVGroup_ExSkill_Level_1-1 = "さあ、こちらを。"
10131-CVGroup_ExSkill_Level_2-1 = "返さなくて構いませんわ。"
10131-CVGroup_ExSkill_Level_3-1 = "次からは気をつけてくださいね。"
10131-CVGroup_Formation_In_1-1 = "評論とは――文の本質を見極める行為ですわ。"
10131-CVGroup_Formation_In_2-1 = "私にできることでしたら、何なりと。"
10131-CVGroup_Formation_Select-1 = "ひゃっ……！？\nああ、もう……！\n後でお話、よろしいでしょうか？"
10131-CVGroup_Growup_1-1 = "人間とは、より良い明日へと進み続ける存在。\n私が日々研鑽を怠らず、自分自身を見つめ直す理由は……そこにこそあります。"
10131-CVGroup_Growup_2-1 = "可能性が残されている限り、歩みを止めるべきではありませんわ。\nさあ、お手をどうぞ、先生。共に進みましょう。"
10131-CVGroup_Growup_3-1 = "案外、己の事を熟知している者は多くありません。\n評論家である私とて……。\nですが、己を知る事で、また新たな一歩を踏み出すことができるのです。\n成長とはその中にこそあるものですから。"
10131-CVGroup_Growup_4-1 = "運命の相手……いささか陳腐で使い古されたクリシェですけれど。\nその言葉に縋ってみたい気分の時だってあるのですわ。\nふふっ、それはきっと、私たちが前へと歩み続けるための道標なのですから。"
10131-CVGroup_Relationship_Up_1-1 = "ふと、思ったのですが……\n私、こうして批評を書くことは多いですけれど、\n私の批評に対しての講評はほとんどいただいたことがないのです。\nええ、そうです。その……先生であれば、きっと素敵な講評を書いてくださる、と信じております。"
10131-CVGroup_Relationship_Up_2-1 = "色々目にしていると、心の底から気に入るものなんて、なかなか見つかりません。\nですが……やはり何事にも例外はあるというもので それが何かは……秘密ですわ。\nええ、今は……まだ。"
10131-CVGroup_Relationship_Up_3-1 = "素晴らしい物語に出会ったときほど\n心が躍ることはありませんわ。\n私にとっては、ですけれど。\nそして私にとって素晴らしい人とは……物語と同じようなもの。\nどういう意味か、分からない？\nふふ……今は、それで構いません。"
10131-CVGroup_Relationship_Up_4-1 = "時々、先生に出会わなかったら、というもしもを考える時があるのです。\nそれはきっと灰色の……\n起伏のない物語だったのかもしれませんわね。\nどういう意味か、ですって？\nふふ……特に意味などありませんわ。\n……多分、おそらく。"
10131-CVGroup_Tactic_In_1-1 = "さて、踏み出すといたしましょう。"
10131-CVGroup_Tactic_In_2-1 = "ごきげんよう、皆さん。"
10131-CVGroup_Tactic_Victory_1-1 = "批評のし甲斐がある物語でしたね。"
10131-CVGroup_Tactic_Victory_2-1 = "ハッピーエンド……ありきたりではありますが、誰もが望むものこそ名作足りえるのですわ。"
