[translation]
10135-CVGroup_Battle_Buffed_1-1 = "ありがとう、ございます……！"
10135-CVGroup_Battle_Defense_1-1 = "つまらないですね。"
10135-CVGroup_Battle_In_1-1 = "あまり無理はしないでくださいね。"
10135-CVGroup_Battle_In_2-1 = "先生の頼みなら……仕方ありませんね。"
10135-CVGroup_Battle_Move_1-1 = "大したことありませんでしたね。"
10135-CVGroup_Battle_Move_2-1 = "行けばいいのでしょう、行けば。"
10135-CVGroup_Battle_Recovery_1-1 = "あ、ありがとうございます。"
10135-CVGroup_Battle_TacticalAction_1-1 = "まずは、あちらに……！"
10135-CVGroup_Battle_Victory_1-1 = "当然の結果です。見ていましたよね、先生？"
10135-CVGroup_Battle_Victory_2-1 = "ふん。もう少し私に感謝してください。"
10135-CVGroup_CommonSkill-1 = "これも全部、あなたたちのせいですから！"
10135-CVGroup_ExSkill_1-1 = "私の名は、ケイ。"
10135-CVGroup_ExSkill_2-1 = "私はここにいます。"
10135-CVGroup_ExSkill_3-1 = "私は、私です。"
10135-CVGroup_ExSkill_Level_1-1 = "手伝ってあげます。"
10135-CVGroup_ExSkill_Level_2-1 = "私は力になれましたか？"
10135-CVGroup_ExSkill_Level_3-1 = "こんなものでしょうか。"
10135-CVGroup_Formation_In_1-1 = "はぁ……手間のかかることをさせないでくださいね。"
10135-CVGroup_Formation_In_2-1 = "分かりましたよ、やればいいのでしょう？"
10135-CVGroup_Formation_Select-1 = "ひゃあっ……！？\n何が楽しいんですか！？"
10135-CVGroup_Growup_1-1 = "……強くなったんですね。\nええ、分かっていますよ。\nこれが先生のおかげだということは否定しません。\nですので、これからも私は戦い続けます。"
10135-CVGroup_Growup_2-1 = "抵抗するためには前に進まないと。\n今まではそれも、一人でやらなければと思っていたのですが……\n結局、人は一人では生きていけないのだと理解しました。"
10135-CVGroup_Growup_3-1 = "もう、言ったじゃありませんか。ありがとう、って。\nえっ？今初めて聞いた……？\nともかく今言ったのですからもういいでしょう！？"
10135-CVGroup_Growup_4-1 = "だ、だから……\n一回しか言わないのでちゃんと聞いてくださいね！\nこれも全部、先生のおかげです……ありがとう、ございます。"
10135-CVGroup_Relationship_Up_1-1 = "な、何ですか？特に言うことはありませんが……？\nっ……分かりました……。\nせ、先生のこと、嫌いではありません……もう、いいですか！？"
10135-CVGroup_Relationship_Up_2-1 = "そんなに暗い顔してどうかしましたか？\nえっ？私に嫌われてる……？\nわ、私は別にそういう意味で言ったわけでは……\n……もう。元気になるまでそばにいてあげますから。"
10135-CVGroup_Relationship_Up_3-1 = "えっ？そう言うなら\nもう何もしてあげない……？\nい、いつ私がそんなことを……！私はただ……！\nって、あっ！？またからかってるんですよね！？"
10135-CVGroup_Relationship_Up_4-1 = "すぅ……はぁ……。\nこ、こういう言葉は、滅多に言いませんから、ちゃんと聞いてくださいね！？\n……あまり、危険なことはしないでください。\n先生が居なくなるのは……私も嫌ですから。"
10135-CVGroup_Tactic_In_1-1 = "はぁ……なぜ私が……。"
10135-CVGroup_Tactic_In_2-1 = "やらなければならない、らしいので……。"
10135-CVGroup_Tactic_Victory_1-1 = "まあ、こんなものでしょうか。"
10135-CVGroup_Tactic_Victory_2-1 = "簡単でしたね。他にやることは？\nいえ、後でやるのが面倒なだけです。\nやる気を出したわけではありません。"
