[translation]
10132-CVGroup_Battle_Buffed_1-1 = "ありがとう、ございます……！"
10132-CVGroup_Battle_Covered_1-1 = "ツクヨ流、隠れ身の術……！"
10132-CVGroup_Battle_Defense_1-1 = "させま、せん……！"
10132-CVGroup_Battle_In_1-1 = "進み、ましょう……勝利へのランウェイを……！"
10132-CVGroup_Battle_In_2-1 = "みなさん、本番、です……！"
10132-CVGroup_Battle_Move_1-1 = "次のステージに、進みます……！"
10132-CVGroup_Battle_Move_2-1 = "まだ、残ってるんですか……？"
10132-CVGroup_Battle_Recovery_1-1 = "助かり、ました……！"
10132-CVGroup_Battle_TacticalAction_1-1 = "こっちで、あってますか……？"
10132-CVGroup_Battle_Victory_1-1 = "フィナーレですね。お疲れ様でした……！"
10132-CVGroup_Battle_Victory_2-1 = "打ち上げで、ラーメン、いきませんか……？"
10132-CVGroup_CommonSkill-1 = "うぅ……ラーメンが食べたい、です……。"
10132-CVGroup_ExSkill_1-1 = "忍者は、窮地に立たされても、諦めないもの……！"
10132-CVGroup_ExSkill_2-1 = "こういうとき、忍者、なら……！"
10132-CVGroup_ExSkill_3-1 = "ドレスが、破けたとしても……！"
10132-CVGroup_ExSkill_Level_1-1 = "私が、止めます……！"
10132-CVGroup_ExSkill_Level_2-1 = "私の後ろに、下がってください……！"
10132-CVGroup_ExSkill_Level_3-1 = "ツクヨ流、新・変わり身の術、です……！"
10132-CVGroup_Formation_In_1-1 = "えっ！スカウト……？私を、ですか？"
10132-CVGroup_Formation_In_2-1 = "最後まで……歩ききって、みせます……！"
10132-CVGroup_Formation_Select-1 = "う～ん……ひゃっ！？うぅぅ……。"
10132-CVGroup_Growup_1-1 = "私、すごく注目されてる、ような……。\n気のせい、ですよね……？"
10132-CVGroup_Growup_2-1 = "成長……？\n本当に、私にも才能が……？"
10132-CVGroup_Growup_3-1 = "こんなに……私には、もったいないです……。"
10132-CVGroup_Growup_4-1 = "私のステージは、これから、です。\n忍者ツクヨの新しい姿を、みて、ください……！"
10132-CVGroup_Relationship_Up_1-1 = "ドレス、似合って、ますか……？本当、ですか？えへへ……。"
10132-CVGroup_Relationship_Up_2-1 = "先生が、見守ってくれるなら……私は、どんな道でも……。"
10132-CVGroup_Relationship_Up_3-1 = "ステージに、一人で立つより……先生のおそばに……。"
10132-CVGroup_Relationship_Up_4-1 = "得意、なことと、好き、なこと……\nどちらかを選ぶなら、私は……好きなこと、がいいです。"
10132-CVGroup_Tactic_In_1-1 = "足元に、気をつけて、ください……！"
10132-CVGroup_Tactic_In_2-1 = "モデル……いえ、忍者、ツクヨ……行きます！"
10132-CVGroup_Tactic_Victory_1-1 = "無事に終わって、よかった、です……！"
10132-CVGroup_Tactic_Victory_2-1 = "みなさん、お怪我は、ありませんか……？"
