[translation]
10133-CVGroup_Battle_Buffed_1-1 = "合理的ね。"
10133-CVGroup_Battle_Covered_1-1 = "無駄よ。"
10133-CVGroup_Battle_Defense_1-1 = "通らないわ。"
10133-CVGroup_Battle_In_1-1 = "現場対応も問題ないわ。"
10133-CVGroup_Battle_In_2-1 = "リソースを総動員しましょう。"
10133-CVGroup_Battle_Move_1-1 = "戦況予測を続けるわ。"
10133-CVGroup_Battle_Move_2-1 = "次の概念空間へ。"
10133-CVGroup_Battle_Recovery_1-1 = "負荷が軽くなったわ。"
10133-CVGroup_Battle_TacticalAction_1-1 = "戦術的優位性の確保を。"
10133-CVGroup_Battle_Victory_1-1 = "芸術的な勝利ね。"
10133-CVGroup_Battle_Victory_2-1 = "これは貴方と見つけた、無限の可能性。"
10133-CVGroup_CommonSkill-1 = "最適化、完了。"
10133-CVGroup_ExSkill_1-1 = "敗北は――\n決定事項よ。"
10133-CVGroup_ExSkill_2-1 = "スキャン開始。\nお見通しよ。"
10133-CVGroup_ExSkill_3-1 = "仮説の未来を――\n合理的な現実に。"
10133-CVGroup_ExSkill_Level_1-1 = "ターゲットとして最適ね。"
10133-CVGroup_ExSkill_Level_2-1 = "制圧するわ。"
10133-CVGroup_ExSkill_Level_3-1 = "これが電子の力よ。"
10133-CVGroup_Formation_In_1-1 = "電子戦が必要なのね？"
10133-CVGroup_Formation_In_2-1 = "このスーツの力、見せてあげる。"
10133-CVGroup_Formation_Select-1 = "少し……しめつけが苦しいのだけれど……。"
10133-CVGroup_Growup_1-1 = "装備のアップグレードに成功したわ。\n先生のおかげよ。"
10133-CVGroup_Growup_2-1 = "私たちは相互補完的関係。\nそう解釈して良いのかしら？"
10133-CVGroup_Growup_3-1 = "私にこれだけのリソースを投じるなんて……\nええ、その意味は理解しているわ。"
10133-CVGroup_Growup_4-1 = "先生のおかげで……「感謝」という感情に気づけたの。\n……話は、それだけよ。"
10133-CVGroup_Relationship_Up_1-1 = "突然、体が火照ってきたのだけれど……。\nスーツの保温機能のせい、かしら。"
10133-CVGroup_Relationship_Up_2-1 = "これが……不確かなものが輪郭を持つ瞬間、なのね。"
10133-CVGroup_Relationship_Up_3-1 = "このやり取りに感じる既視感は……\n概念空間でシミュレーションしていたから……かもしれないわね。"
10133-CVGroup_Relationship_Up_4-1 = "先生はスーツ姿のほうが好き、なのかしら？\n……いえ、質問に深い意味は……ないわ。"
10133-CVGroup_Tactic_In_1-1 = "貴方の指揮と私の分析。合理的な組み合わせね。"
10133-CVGroup_Tactic_In_2-1 = "観測対象の分析は終わっているわ。あとは実戦だけ。"
10133-CVGroup_Tactic_Victory_1-1 = "合理的な指揮だったわね。"
10133-CVGroup_Tactic_Victory_2-1 = "概念空間の合理性が立証できたわね。"
