[translation]
16018-CVGroup_Battle_Buffed_1-1 = "あら、悪いわね。"
16018-CVGroup_Battle_Covered_1-1 = "撃ちたきゃ撃ってみなさいよ！"
16018-CVGroup_Battle_Defense_1-1 = "ヘルメットは飾りじゃないのよ！"
16018-CVGroup_Battle_In_1-1 = "受けて立つわよ！"
16018-CVGroup_Battle_In_2-1 = "順番にかかってきなさい！こっちはヒマじゃないのよ！"
16018-CVGroup_Battle_Move_1-1 = "どいたどいた！"
16018-CVGroup_Battle_Move_2-1 = "ちゃっちゃと終わらせるわよ！"
16018-CVGroup_Battle_Recovery_1-1 = "ひゅ～っ、ギリギリだったわ……ありがとう！"
16018-CVGroup_Battle_TacticalAction_1-1 = "あっちに行くわよ！"
16018-CVGroup_Battle_Victory_1-1 = "次は仲間も連れてきなさいよね！"
16018-CVGroup_Battle_Victory_2-1 = "ま、うちらと同じくらいの働きはしてるんじゃない？"
16018-CVGroup_CommonSkill-1 = "行け！嚙みちぎってきなさい！"
16018-CVGroup_ExSkill_1-1 = "ヘルメット団！準備はいい？"
16018-CVGroup_ExSkill_2-1 = "ちゃーんと、見てなさいよ！"
16018-CVGroup_ExSkill_3-1 = "ヘルメット団もナメられたものね、面白いじゃないの！！"
16018-CVGroup_ExSkill_Level_1-1 = "オーバーハンド！"
16018-CVGroup_ExSkill_Level_2-1 = "いくわよ！ドッカーン！"
16018-CVGroup_ExSkill_Level_3-1 = "スパッと決めてやるわよ！"
16018-CVGroup_ExSkill_4-1 = "ヘルメット団、突撃！"
16018-CVGroup_ExSkill_5-1 = "ヘルメット団！準備はいい？"
16018-CVGroup_ExSkill_6-1 = "ぶっ潰してやるわよ！"
16018-CVGroup_ExSkill_Level_4-1 = "敵はボコボコにしていいわよ！でもケガすんじゃないわよ！"
16018-CVGroup_ExSkill_Level_5-1 = "手加減なんかしないで思いっきり行きなさいよ！"
16018-CVGroup_ExSkill_Level_6-1 = "うちを信じなさい！"
16018-CVGroup_Formation_In_1-1 = "ふーん、暴れてもいいってことよね？"
16018-CVGroup_Formation_In_2-1 = "あんた達が味方なのって、なんか変な感じするわね……あはは……。"
16018-CVGroup_Formation_Select-1 = "ちょっ、降ろしなさいってばー！周りに人がいるでしょ！"
16018-CVGroup_Growup_1-1 = "えっ、これをうちに？そう……ありがとね！"
16018-CVGroup_Growup_2-1 = "ほんとにくれるの……？\n後から返せって言われてもダメだからね！"
16018-CVGroup_Growup_3-1 = "うちをこんなに強くしてどうすんのよ？\n取り返しがつかなくなっても知らないわよ！"
16018-CVGroup_Growup_4-1 = "ふふっ、成長っていいものよね♪"
16018-CVGroup_Relationship_Up_1-1 = "ちょっと……うちが問題児なことくらい、分かってたんじゃないの？"
16018-CVGroup_Relationship_Up_2-1 = "あんまり馴れ馴れしくしないでよね……ちょっと困るのよ。"
16018-CVGroup_Relationship_Up_3-1 = "生徒扱いなんて、久しぶりすぎて……もう……。"
16018-CVGroup_Relationship_Up_4-1 = "ちょっと！周りに人がいるでしょうが！今は頭撫でないで！"
16018-CVGroup_Tactic_In_1-1 = "うちに任せなさい！"
16018-CVGroup_Tactic_In_2-1 = "軽い準備運動ってとこかしらね。"
16018-CVGroup_Tactic_Victory_1-1 = "調子乗ってんじゃないわよ！一昨日来なさいっての！"
16018-CVGroup_Tactic_Victory_2-1 = "なにこれ、手ごたえがないわねぇ。"
