[translation]
16019-CVGroup_Battle_Buffed_1-1 = "支援、ありがとうございます。"
16019-CVGroup_Battle_Covered_1-1 = "安全、確保。"
16019-CVGroup_Battle_Defense_1-1 = "その程度では効きません。"
16019-CVGroup_Battle_In_1-1 = "先頭はお任せください。"
16019-CVGroup_Battle_In_2-1 = "二丁拳銃はカッコいいだけではありません。"
16019-CVGroup_Battle_Move_1-1 = "セクション、クリア。"
16019-CVGroup_Battle_Move_2-1 = "偵察を再開します。"
16019-CVGroup_Battle_Recovery_1-1 = "補給、感謝します。"
16019-CVGroup_Battle_TacticalAction_1-1 = "ポジション、移動。"
16019-CVGroup_Battle_Victory_1-1 = "失敗という選択肢はありませんので。やっほー。"
16019-CVGroup_Battle_Victory_2-1 = "任務を遂行したまでです。ブイっ。"
16019-CVGroup_CommonSkill-1 = "おっと。\nこれで問題ありません。"
16019-CVGroup_ExSkill_1-1 = "パーフェクトリコン、飛鳥馬トキ。\n出ます。"
16019-CVGroup_ExSkill_2-1 = "すべては、この手からはじまります。"
16019-CVGroup_ExSkill_3-1 = "支援も制圧も、お手の物です。"
16019-CVGroup_ExSkill_Level_1-1 = "銃の扱いも、完璧です。"
16019-CVGroup_ExSkill_Level_2-1 = "二丁拳銃は万能です。"
16019-CVGroup_ExSkill_Level_3-1 = "銃と装備は使いようです。"
16019-CVGroup_Formation_In_1-1 = "お呼びでしょうか。"
16019-CVGroup_Formation_In_2-1 = "いつでも出動できます。"
16019-CVGroup_Formation_Select-1 = "ウェポンチェンジ。\n完璧です。"
16019-CVGroup_Growup_1-1 = "飛鳥馬トキ、レベルアップです。\n先生への想いもレベルアップしました。\n裏返せば、私への先生の想いもレベルアップです。"
16019-CVGroup_Growup_2-1 = "これでもっと強くなりました。\n……よく考えてみたら、まだまだな気がします。\nですので、もう少し一緒にいてください。"
16019-CVGroup_Growup_3-1 = "人は、強くなるだけでは成長できません。\nだからこそ、互いに寄り添い合うべきなのです。\n……私はいつでも準備ができていますよ。先生。"
16019-CVGroup_Growup_4-1 = "成長を遂げた私は、パーフェクトトキです。\n……いえ、訂正します。\n先生がそばにいるとき限定です。"
16019-CVGroup_Relationship_Up_1-1 = "なるほど。\nこれで、先生の中の私の存在感が、一段と増したのですね。\n……逆？そんなはずありません。"
16019-CVGroup_Relationship_Up_2-1 = "ご心配なく。\n幸運のメイド・エージェント・リコンがついている以上、\n私たちの進む先に邪魔は入りません。"
16019-CVGroup_Relationship_Up_3-1 = "好感度というものがあるのなら、こういう時に上がるのでしょう。\n体感、今ので1万ポイントほど上昇しました。"
16019-CVGroup_Relationship_Up_4-1 = "先生、寒くありませんか？\n私は少し……いえ、とても寒いです。\nですので、もう少し近くに来てください。"
16019-CVGroup_Tactic_In_1-1 = "偵察開始します。"
16019-CVGroup_Tactic_In_2-1 = "ミッション内容は頭に入っています。"
16019-CVGroup_Tactic_Victory_1-1 = "目標達成。迅速に褒めてください。"
16019-CVGroup_Tactic_Victory_2-1 = "エリアクリア。"
