[translation]
20053-CVGroup_CommonSkill-1 = "秘儀を伝授して進ぜよう！"
20053-CVGroup_ExSkill_1-1 = "これがミチル流……うにゃああっ！？ "
20053-CVGroup_ExSkill_2-1 = "とくと見よ！これが最新のカメ、らぁ～～っ！？ "
20053-CVGroup_ExSkill_3-1 = "少女忍法帖ミチルっち、スタ～とぉぉおっ！？"
20053-CVGroup_ExSkill_Level_1-1 = "キャッ、チ……うにゃああっ！？ "
20053-CVGroup_ExSkill_Level_2-1 = "ふぅ……めっ、目が～っ！？ "
20053-CVGroup_ExSkill_Level_3-1 = "ふぅ……オフショットはだめぇ！"
20053-CVGroup_Formation_In_1-1 = "あ、あー。こちらアンダーカバーゼロワン。\n……ってこれでいいんだっけ？"
20053-CVGroup_Formation_In_2-1 = "私たちの作戦場所は……ここだね！"
20053-CVGroup_Formation_Select-1 = "このドレスは任務のためで……！\nで、でも……その、先生殿は、どう思う？"
20053-CVGroup_Growup_1-1 = "この感覚……これが、シンデレラフィット……！"
20053-CVGroup_Growup_2-1 = "服装が変わっても、心持ちまで変わるわけじゃないよ！"
20053-CVGroup_Growup_3-1 = "こんな珍しい物をくれるってことは……\n先生殿も、忍者の道を行きたくなったの？"
20053-CVGroup_Growup_4-1 = "ふふっ、どう？\n私……可愛いく……いや、強くなった？  "
20053-CVGroup_Relationship_Up_1-1 = "これはちょっと恥ずかしい、かも……。"
20053-CVGroup_Relationship_Up_2-1 = "この髪型、どうかな？\n結構頑張って、セットしたんだけど……。"
20053-CVGroup_Relationship_Up_3-1 = "えっ、可愛い……？\n先生殿ってば、またまたぁ……ふ、ふへへっ……。"
20053-CVGroup_Relationship_Up_4-1 = "この格好なら、先生殿のボディガードとして……\nそばにいてもいい……？"
