[translation]
20051-CVGroup_CommonSkill-1 = "愛と！勇気と！友情パワーで！"
20051-CVGroup_ExSkill_1-1 = "フィードランプよりチャンバーへ……6条右回りの魔法……！"
20051-CVGroup_ExSkill_2-1 = "揺るぎなき力をっ！"
20051-CVGroup_ExSkill_3-1 = "これが、私です！"
20051-CVGroup_ExSkill_Level_1-1 = "ボルトフォワード！テルミットピンク！"
20051-CVGroup_ExSkill_Level_2-1 = "正義の味方、降臨！です！"
20051-CVGroup_ExSkill_Level_3-1 = "キラーン！バーン！ババババン！"
20051-CVGroup_Formation_In_1-1 = "テルミットピンク！出ます！"
20051-CVGroup_Formation_In_2-1 = "正義のマジカル自警団、いきます！"
20051-CVGroup_Formation_Select-1 = "宇沢レイサ！またの名を～テルミットピンク！"
20051-CVGroup_Growup_1-1 = "これ……私が受け取っても大丈夫なのでしょうか？\nありがとうございます！"
20051-CVGroup_Growup_2-1 = "先生にいただいたこの力で、絶対成長してみせます！"
20051-CVGroup_Growup_3-1 = "宇沢レイサは、さらなる高みを目指していきますよ！"
20051-CVGroup_Growup_4-1 = "先生のためなら私！\n二段変身……いえ、十七段変身だってしますので！！"
20051-CVGroup_Relationship_Up_1-1 = "絆の力は強いんです！ええ、それはもう！\n最強なんですよ！"
20051-CVGroup_Relationship_Up_2-1 = "ヒーローの強さにも憧れていますが……\nその……先生の優しさにも、とても憧れています。"
20051-CVGroup_Relationship_Up_3-1 = "先生はよく私のことを褒めてくださるでしょう？\nそれがすごく……嬉しいんです。"
20051-CVGroup_Relationship_Up_4-1 = "世界の平和と先生、両方を……守ってみせます！"
