[translation]
20050-CVGroup_CommonSkill-1 = "えいやっ！"
20050-CVGroup_ExSkill_1-1 = "ふふっ、ちょうどいいのがあるんだ～♪"
20050-CVGroup_ExSkill_2-1 = "すっごいの、持ってきたよ！"
20050-CVGroup_ExSkill_3-1 = "たしかこの辺に……！"
20050-CVGroup_ExSkill_Level_1-1 = "はい、これ食べて！張り切ってこ～！"
20050-CVGroup_ExSkill_Level_2-1 = "元気出して！えいえいおー！"
20050-CVGroup_ExSkill_Level_3-1 = "ほら、まだいけるよね！"
20050-CVGroup_Formation_In_1-1 = "なになに～？なんかやるの～？"
20050-CVGroup_Formation_In_2-1 = "おもしろそう！ボクも混ぜてよ！"
20050-CVGroup_Formation_Select-1 = "ふんふふ～ん♪……あっ、先生だ！"
20050-CVGroup_Growup_1-1 = "えっ！ボクにくれるの！？ホントに～？"
20050-CVGroup_Growup_2-1 = "これで、どんなおっきい岩でも運べるね！"
20050-CVGroup_Growup_3-1 = "ありがと先生！ボク、もっと頑張るね！"
20050-CVGroup_Growup_4-1 = "みてみて！こ～んなに強くなったんだよ～！"
20050-CVGroup_Relationship_Up_1-1 = "ねね、先生の顔の彫像、作ってもいい？"
20050-CVGroup_Relationship_Up_2-1 = "……これが先生の肌の感触。\nうん！再現できるかも！"
20050-CVGroup_Relationship_Up_3-1 = "最近、なんか彫るぞ！ってとき、\n先生の顔しか浮かんでこないんだよ～……なんでかなぁ？"
20050-CVGroup_Relationship_Up_4-1 = "なんかさ？先生を見てると……\n胸がギュ～ってなるんだよね。"
