[translation]
20054-CVGroup_CommonSkill-1 = "ふふ、お待たせしました。"
20054-CVGroup_ExSkill_1-1 = "見惚れてしまいましたか？"
20054-CVGroup_ExSkill_2-1 = "スピードなら、負けませんよ。"
20054-CVGroup_ExSkill_3-1 = "あなたにも作って差し上げましょうか？"
20054-CVGroup_ExSkill_Level_1-1 = "これは車椅子です。"
20054-CVGroup_ExSkill_Level_2-1 = "さあ、始めましょうか？"
20054-CVGroup_ExSkill_Level_3-1 = "私の助けが必要なのですね？"
20054-CVGroup_Formation_In_1-1 = "私の助けが必要？\nええ、そうだろうと思っておりましたとも。"
20054-CVGroup_Formation_In_2-1 = "さて、何から始めましょうか。"
20054-CVGroup_Formation_Select-1 = "はい、先生。私はここにおります。"
20054-CVGroup_Growup_1-1 = "どんな状況であれ成長できる……\n先生は、そうおっしゃるのでしょうね。"
20054-CVGroup_Growup_2-1 = "独学での成長は、とても難しいことです。\n今の私があるのは、先生がいてくださったおかげかもしれませんね。"
20054-CVGroup_Growup_3-1 = "分かっています、先生。\n気を抜いてはいけませんが、\nかといって緊張しすぎるのも、良くありませんね。"
20054-CVGroup_Growup_4-1 = "成長とは、喜ばしいことである……そう、理解はしているのですが。\n同時に、先生がどれほど私のためにリソースを割いてくださったのかと思いを馳せるのです。\n無理だけは、しないでくださいね。"
20054-CVGroup_Relationship_Up_1-1 = "私の新しいスーツ、いかがでしょうか？\n……似合ってる？ええ、そうでしょうとも。"
20054-CVGroup_Relationship_Up_2-1 = "人は、一人では生きていけない……とよく言われます。\n最近、その言葉の意味を私も実感しているところでして。\n……先生はまさか、私を一人になんてしませんよね？"
20054-CVGroup_Relationship_Up_3-1 = "先生と出会ってから起きたことは、\n「全知」の学位を持つこの私でも予測できないものばかりでした。\nそして……きっと、これからも。"
20054-CVGroup_Relationship_Up_4-1 = "少しだけ、弱音を吐いてもよろしいですか……？\nそばにいてください、今だけで構いませんから。\nありがとうございます、先生。\n……とても、嬉しいです。"
