[translation]
20052-CVGroup_CommonSkill-1 = "こちらにサインをお願いします。"
20052-CVGroup_ExSkill_1-1 = "お買い上げありがとうございますぅ。ムフフ♪"
20052-CVGroup_ExSkill_2-1 = "さあ寄ってらっしゃい見てらっしゃい。"
20052-CVGroup_ExSkill_3-1 = "毎度ありがとうございますぅ。"
20052-CVGroup_ExSkill_Level_1-1 = "はい～是非是非！\nムフフ……。"
20052-CVGroup_ExSkill_Level_2-1 = "これは儲かりますねぇ……。"
20052-CVGroup_ExSkill_Level_3-1 = "売上は上々……ムフフ。"
20052-CVGroup_Formation_In_1-1 = "販路の開拓と参りましょうか。"
20052-CVGroup_Formation_In_2-1 = "これは……大儲けの予感……！"
20052-CVGroup_Formation_Select-1 = "おっと、お呼びですかぁ？\n契約？事業拡大？どちらでしょう？"
20052-CVGroup_Growup_1-1 = "昨日より今日、今日より明日……\n日々の成長が我々をより明るい稼ぎへ……おっと失礼。\n未来へと導いてくれることでしょう。"
20052-CVGroup_Growup_2-1 = "出版部存続のためにも、部長の私がもっと強くならなければ……\nどこかにおいしい契約が転がってたりとか……しないですかねぇ……？"
20052-CVGroup_Growup_3-1 = "あれぇ、なんだか頭の回転が速くなった気がしますねぇ。\n先生、有能な契約代理人をお探しでしたら……\nはいはい、ここにいますよぉ、ムフフ。"
20052-CVGroup_Growup_4-1 = "日頃の感謝を込めまして、私の気持ちをこちらの紙に綴ってみました～\nあ、ここに受け取りのハンコを押してもらいたいんですけどぉ～\n……文章が契約書風？き、気のせいですよぉ～！"
20052-CVGroup_Relationship_Up_1-1 = "ふむ……先生と私の「好感度」が上がった、ということですかね？\n……感想？\nううん……答えにくいことを聞きますねぇ。"
20052-CVGroup_Relationship_Up_2-1 = "出版部の部長たる者、言語化に苦しむなど……\nええと、ですから、その……\nこんな気持ちは、はじめてなんですよ……。"
20052-CVGroup_Relationship_Up_3-1 = "はぁ……\nいっそのこと、ズバっと言っちゃってスッキリしちゃいましょうか！\nということで、先生、ちょっと……\nあ、うぅ……なんでもありません、もう少し、時間をいただけますと……。"
20052-CVGroup_Relationship_Up_4-1 = "契約書に穴は作れど虚偽は言語道断……はぁ、正直に申し上げましょう。\n先生の生徒になれて、本当によかったと思っています。\nおかげさまで、私の文は驚くほど美しくなったのです。\n……なのでこれからも……添削と校正のほど、よろしくお願いしますよ？"
