[translation]
20055-CVGroup_CommonSkill-1 = "タイミングを、合わせて……！"
20055-CVGroup_ExSkill_1-1 = "大丈夫です。前にもやったこと、あります……！ "
20055-CVGroup_ExSkill_2-1 = "今度は、わたしがみんなを……！"
20055-CVGroup_ExSkill_3-1 = "体が、覚えてる……！いける！"
20055-CVGroup_ExSkill_Level_1-1 = "え、援護します！"
20055-CVGroup_ExSkill_Level_2-1 = "ううううぅぅぅう……！！"
20055-CVGroup_ExSkill_Level_3-1 = "怖いです……\nで、でも……！"
20055-CVGroup_Formation_In_1-1 = "どうしてここに……！？ "
20055-CVGroup_Formation_In_2-1 = "き、聞いてないです！？"
20055-CVGroup_Formation_Select-1 = "お、おお落とさないでくださいね……！"
20055-CVGroup_Growup_1-1 = "コツを掴んできました……！"
20055-CVGroup_Growup_2-1 = "もっと、もっと強くならないと……！\nい、いつ呼び出されるか、分からないですし……うぅぅ……。"
20055-CVGroup_Growup_3-1 = "怖いけど……緊張は、していません……。\nこれが、勇気の力、なのでしょうか……？"
20055-CVGroup_Growup_4-1 = "たとえ前に進めなくても、\n絶対に退いたり、しません……！"
20055-CVGroup_Relationship_Up_1-1 = "その……先生の前なら、恥ずかしく、ないです……。 "
20055-CVGroup_Relationship_Up_2-1 = "先生……あ、あの……一緒にゲームしませんか？"
20055-CVGroup_Relationship_Up_3-1 = "あの……っ……手、また繋いでいただけませんか？"
20055-CVGroup_Relationship_Up_4-1 = "外はやっぱり怖いけど……\nでも、そこに先生がいるならわたし……。"
