[translation]
40015-CVGroup_Battle_Buffed_1-1 = "パワーアップ！"
40015-CVGroup_Battle_Defense_1-1 = "華麗に回避、です！"
40015-CVGroup_Battle_Recovery_1-1 = "回復魔法、ありがとうございます！"
40015-CVGroup_Summon_Retreat_02-1 = "こ、これで終わりだと思わないでください～っ！！"
40015-CVGroup_CommonSkill_2-1 = "必殺魔法いきます！痛いですよ～！"
40015-CVGroup_Summon_Retreat_01-1 = "さらば！です！ヒュウウ～！シュバババ！"
