[translation]
10018-100180620 = "失くしたものって"
10018-100180630 = "探し回った結果"
10018-100180640 = "予想外の場所にあるんですよね……"
10018-100180650 = "分かるー！"
10018-100180660 = "リモコンとかね……"
10018-100180670 = "実際には"
10018-100180680 = "どこに置いたか忘れただけ"
10018-100180690 = "なんでしょうけど……"
10018-100180700 = "みんな同じ経験をしがちだからか"
10018-100180710 = "昔の方はこういう時"
10018-100180720 = "「いたずら好きな妖精さん」"
10018-100180730 = "……に盗まれてしまった、と"
10018-100180740 = "考えたそうです"
10018-100180750 = "面白い話だね"
10018-100180760 = "もしかして……"
10018-100180770 = "何か物でも失くしちゃった？"
10018-100180780 = "い、いえ"
10018-100180790 = "何も忘れてません"
10018-100180800 = "……多分"
