[translation]
10015-1001500670 = "先生"
10015-1001500680 = "今って忙しいですか？"
10015-1001500690 = "全然大丈夫！"
10015-1001500700 = "良かったです！"
10015-1001500710 = "実はアリス"
10015-1001500720 = "先生に見せたいものがあります！"
10015-1001500730 = "見せたいもの……？"
10015-1001500740 = "はい！"
10015-1001500750 = "ゲーム開発部の部室で、待ってますね！"
