[translation]
10129-101290010 = "こんにちは、先生。スズミです"
10129-101290020 = "お変わりなくお過ごしでしょうか？"
10129-101290030 = "スズミ！元気してる？"
10129-101290040 = "はい、おかげさまで"
10129-101290050 = "ひとつ、お聞きしたいのですが……"
10129-101290060 = "シャーレの休憩施設は、何時まで利用可能でしょうか"
10129-101290070 = "特に決まってないよ"
10129-101290080 = "好きなだけいて大丈夫だよ"
10129-101290090 = "承知しました"
10129-101290100 = "利用にあたって、何か注意点はありますか？"
10129-101290110 = "帰るときは電気を消す、ぐらいかな"
10129-101290120 = "承知しました"
10129-101290130 = "ありがとうございます"
10129-101290140 = "先生、その"
10129-101290150 = "繰り返しになりますが……"
10129-101290160 = "あの格好は、私個人の好みとは無関係です！"
10129-101290170 = "私は好きだよ、あれ！"
10129-101290180 = "えfs#'8k6avb$"
10129-101290190 = "すみません"
10129-101290200 = "スマホを落としました"
10129-101290210 = "あくまでも自警団任務の延長ですので！"
10129-101290220 = "誤解しないでくださいね！"
10129-101290230 = "分かった！"
10129-101290240 = "……あと"
10129-101290250 = "褒めてくださり、ありがとうございました"
10129-101290260 = "では、また……"
10129-101290270 = "先生、スズミです"
10129-101290280 = "お聞きしたいことがありまして……"
10129-101290290 = "服がすこし、破れてしまったのですが"
10129-101290300 = "先生がよく使われるお直し店などありましたら、教えていただけますか？"
10129-101290310 = "シャーレの近くにいいお店があるよ！"
10129-101290320 = "お世話になってるお店があるよ！"
10129-101290330 = "ありがとうございます"
10129-101290340 = "先生のおすすめなら、間違いないですね"
10129-101290350 = "また今度、お会いできたら嬉しいです"
10129-101290360 = "先生"
10129-101290370 = "さきほどの動画"
10129-101290380 = "まだ残ってますでしょうか"
10129-101290390 = "消そうとしていたところだけど"
10129-101290400 = "消さないでおく？"
10129-101290410 = "いえ！そうではなく！"
10129-101290420 = "もちろん、消していただきたいのですが！"
10129-101290430 = "ただその……服の欠陥は"
10129-101290440 = "動画のほうが、見つけやすいかなと"
10129-101290450 = "着用時に気づけなかったところも"
10129-101290460 = "一目でわかりますから"
10129-101290470 = "それだけですので"
10129-101290480 = "さきほどの動画を、送っていただけますでしょうか"
10129-101290490 = "私に送った後は、消してください！"
10129-101290500 = "絶対にです！"
10129-101290510 = "先生、スズミです"
10129-101290520 = "先生は「同人イベント」というものをご存知ですか？"
10129-101290530 = "専門分野だよ"
10129-101290540 = "得意分野だよ"
10129-101290550 = "ええと、つまり"
10129-101290560 = "お詳しいのですね"
10129-101290570 = "自警団に通報が入っていまして"
10129-101290580 = "同人イベントを荒らす不良たちがいると"
10129-101290590 = "それで是非アドバイスをいただけないかと思い"
10129-101290600 = "それなら目立たないほうがいいね"
10129-101290610 = "現場に合った服装かな"
10129-101290620 = "なるほど"
10129-101290630 = "参考になりました"
10129-101290640 = "私も行くよ！"
10129-101290650 = "先生も同行されますか？"
10129-101290660 = "心強いです"
10129-101290670 = "では、のちほど"
10129-101290680 = "つかぬことをお聞きしますが……"
10129-101290690 = "私は、顔が怖いのでしょうか"
10129-101290700 = "先ほどの制圧の際に"
10129-101290710 = "周りの方々が、怯えていたような気がして……"
10129-101290720 = "スズミはカッコよかったよ！"
10129-101290730 = "みんな、少しびっくりしただけ"
10129-101290740 = "なるほど"
10129-101290750 = "あの時は、他に手が思いつかず……"
10129-101290760 = "安全ピンを差し直せばよかったんじゃない？"
10129-101290770 = "あ"
10129-101290780 = "たしかに"
10129-101290790 = "次回の参考にします"
10129-101290800 = "先生、スズミです"
10129-101290810 = "今週末のご予定をうかがっても良いでしょうか"
10129-101290820 = "特にないかな"
10129-101290830 = "そうなのですね"
10129-101290840 = "もしよろしければ、私と一緒に"
10129-101290850 = "遊園地に行きませんか？"
10129-101290860 = "よろこんで！"
10129-101290870 = "そう言っていただけて嬉しいです"
10129-101290880 = "いつもご快諾くださりありがとうございます"
10129-101290890 = "それでは、集合場所は後ほど改めて"
10129-101290900 = "先生、スズミです"
10129-101290910 = "改めて。いつも温かいお言葉をくださり本当にありがとうございます"
10129-101290920 = "とても励みになりました"
10129-101290930 = "……"
10129-101290940 = "これからもよろしくお願いします"
10129-101290950 = "こちらこそよろしくね、スズミ！"
10129-101290960 = "これからも、守ってくれる？テルミットホワイト！"
10129-101290970 = "せ、先生！それは任務で仕方なく言っているだけで……！"
10129-101290980 = "……"
10129-101290990 = "もちろん、いついかなる時でも"
10129-101291000 = "先生は私がお守りしますが"
10129-101291010 = "……またお会いしましょう"
