[translation]
10133-101330010 = "輸送船での暮らしはどうかしら"
10133-101330020 = "不便なことがあれば言ってちょうだい"
10133-101330030 = "可能な範囲で改善するわ"
10133-101330040 = "すごく快適だよ！"
10133-101330050 = "何不自由なく過ごしてるよ！"
10133-101330060 = "それなら良いのだけれど"
10133-101330070 = "要望はいつでも受け付けているから"
10133-101330080 = "遠慮は不要よ"
10133-101330090 = "リオは大丈夫？"
10133-101330100 = "私？"
10133-101330110 = "私も特に問題はないわ……"
10133-101330120 = "メイドロボットの件よ"
10133-101330130 = "結果を報告するわ"
10133-101330140 = "結論を言うと"
10133-101330150 = "メイド服は"
10133-101330160 = "借りられなかった"
10133-101330170 = "とはいえ改めて考えてみたのだけれど"
10133-101330180 = "家事手伝いのアバンギャルド君を"
10133-101330190 = "メイドロボット「ではない」と"
10133-101330200 = "定義することは難しいのではないかしら"
10133-101330210 = "家事を職業にしているのがメイドである"
10133-101330220 = "アバンギャルド君は家事をするロボットである"
10133-101330230 = "つまりアバンギャルド君は"
10133-101330240 = "メイドの役割を担うロボットである"
10133-101330250 = "三段論法に照らし合わせてみても"
10133-101330260 = "多くの要素が共通しているとは考えているわ"
10133-101330270 = "私の負けだよ……"
10133-101330280 = "気づいているかしら"
10133-101330290 = "今日この船にいるのは私たちだけよ"
10133-101330300 = "みんな用事で外しているみたい"
10133-101330310 = "どうりで静かだと思った"
10133-101330320 = "良い機会だから"
10133-101330330 = "溜まっていた作業を進めようと思うの"
10133-101330340 = "集中が必要な作業は後回しにしていたから"
10133-101330350 = "システムに再起動が入るかもしれないのだけれど"
10133-101330360 = "エラーではないから驚かないでちょうだい"
10133-101330370 = "何をするつもりなの？"
10133-101330380 = "詳細は伏せさせてもらうわ"
10133-101330390 = "伝えておくべきことは以上よ"
10133-101330400 = "今日もよろしく"
10133-101330410 = "先生、お礼を言うわ"
10133-101330420 = "おかげで輸送船のアップグレードを無事に終えられた"
10133-101330430 = "想定よりも性能はアップしなかったのだけれど……"
10133-101330440 = "こういった積み重ねが後から効いてくるのよ"
10133-101330450 = "本当にお疲れ様！"
10133-101330460 = "それと、さっき先生が誤魔化した件について"
10133-101330470 = "1人で考えてみたのだけれど"
10133-101330480 = "もしかして……"
10133-101330490 = "仮想空間で誰かとコミュニケーションを取っている、と"
10133-101330500 = "先生は誤解したのかしら？"
10133-101330510 = "そ、そんなところかな！"
10133-101330520 = "そういうことだったのね"
10133-101330530 = "ただ、まだそれを試みたことは無いの"
10133-101330540 = "興味本位でアバターだけは作ってみたのだけれどね"
10133-101330550 = "お、どんなのにしたの？"
10133-101330560 = "気になるの？"
10133-101330570 = "これでも自信作なのよ"
10133-101330580 = "メイド服を着ている"
10133-101330590 = "おお……！"
10133-101330600 = "アバンギャルド君よ"
10133-101330610 = "そっかぁ……"
10133-101330620 = "今日はAMASの大規模な整備があるから"
10133-101330630 = "格納庫が少し騒がしくなるわ"
10133-101330640 = "施設を使うのなら承知しておいてちょうだい"
10133-101330650 = "見学してもいい？"
10133-101330660 = "見学？"
10133-101330670 = "面白い作業ではないと思うのだけれど……"
10133-101330680 = "それでも良ければ、私としても助かるわ"
10133-101330690 = "単純作業の繰り返しだから"
10133-101330700 = "誰か話し相手がいると気が紛れるの"
10133-101330710 = "どう考えても不足しているの"
10133-101330720 = "もっと完璧に仕上げたいのだけれど……"
10133-101330730 = "アバンギャルド君の話？"
10133-101330740 = "それも悪くないわね"
10133-101330750 = "けれど今回は私のスーツに関することよ"
10133-101330760 = "今のスーツに発熱機能をつければ"
10133-101330770 = "もっと色々な状況に対応できるはず"
10133-101330780 = "ええ"
10133-101330790 = "やはりその方が合理的"
10133-101330800 = "今すぐ取りかかるわ"
10133-101330810 = "先生、その……"
10133-101330820 = "変なところを見せてしまったわね"
10133-101330830 = "ごめんなさい"
10133-101330840 = "気にしてないよ！本当に！"
10133-101330850 = "……本当？"
10133-101330860 = "……"
10133-101330870 = "それならいいのだけれど……"
10133-101330880 = "あんな姿"
10133-101330890 = "他の誰にも見せたことがなかったから……"
10133-101330900 = "とにかく、今日は手伝ってくれてありがとう"
10133-101330910 = "ゆっくり休んでちょうだい"
