[translation]
10135-101350010 = "先生、少しよろしいですか？"
10135-101350020 = "どうしたのケイちゃん？"
10135-101350030 = "ケイちゃんじゃありません"
10135-101350040 = "まったく……それはともかく"
10135-101350050 = "無機物を器としている意識体において"
10135-101350060 = "ストレス解消はどのように行うべきでしょうか？"
10135-101350070 = "いきなり難しい質問をするね……"
10135-101350080 = "そうですよね"
10135-101350090 = "先生に期待した私がバカでした"
10135-101350100 = "ひどいよぉ……"
10135-101350110 = "先生、本気ですか？"
10135-101350120 = "どうしたのケイちゃん？"
10135-101350130 = "ケイちゃんじゃありません"
10135-101350140 = "それはともかく"
10135-101350150 = "本当に来るんですか？"
10135-101350160 = "ケイちゃんと約束したからね"
10135-101350170 = "しましたけど！"
10135-101350180 = "どうしてそこまで授業の様子を観に来たいんですか！？"
10135-101350190 = "生徒の学力向上を見守るのは"
10135-101350200 = "教師としての責務だからね"
10135-101350210 = "こういう時ばっかり正論を言うんですから！"
10135-101350220 = "なんだか"
10135-101350230 = "結果的に"
10135-101350240 = "いろんな人からお誘いを受けました……"
10135-101350250 = "先生は嬉しいよ"
10135-101350260 = "はあ"
10135-101350270 = "そんなに嫌だった……？"
10135-101350280 = "うっ"
10135-101350290 = "いや"
10135-101350300 = "うーん"
10135-101350310 = "……"
10135-101350320 = "嫌なわけじゃないです"
10135-101350330 = "せんせ"
10135-101350340 = "た"
10135-101350350 = "すけて"
10135-101350360 = "どうしたの！？"
10135-101350370 = "いま"
10135-101350380 = "ちょとこまって"
10135-101350390 = "ああ"
10135-101350400 = "もう"
10135-101350410 = "なんですか"
10135-101350420 = "このバグは"
10135-101350430 = "バグ？"
10135-101350440 = "こっちの話です"
10135-101350450 = "ん？"
10135-101350460 = "待ってください"
10135-101350470 = "んー"
10135-101350480 = "先生"
10135-101350490 = "いま暇してますよね？"
10135-101350500 = "ちょっと来てください"
10135-101350510 = "えっ？私は予定が……"
10135-101350520 = "無いのは知っています"
10135-101350530 = "それくらい簡単に調べられますから"
10135-101350540 = "私のプライベートは！？"
10135-101350550 = "生徒が第一なんですよね？"
10135-101350560 = "くっ……"
10135-101350570 = "はああ……"
10135-101350580 = "どうしたの？"
10135-101350590 = "いえ"
10135-101350600 = "3日と経っていないのにまた部室掃除と思うと"
10135-101350610 = "気が滅入ってしまって"
10135-101350620 = "掃除？"
10135-101350630 = "まあこっちの話です"
10135-101350640 = "シャーレの前に着きました"
10135-101350650 = "今日の当番はケイちゃん！！"
10135-101350660 = "はぁ、本当にもう"
10135-101350670 = "寮に着きました"
10135-101350680 = "それはよかった"
10135-101350690 = "はい"
10135-101350700 = "あ！"
10135-101350710 = "どうかした？"
10135-101350720 = "デイリーやるの忘れてました！"
10135-101350730 = "あ、うん……大事なことだからね"
