[translation]
10134-101340010 = "知っていますか？"
10134-101340020 = "防具はきちんと装備しなければ意味がありません"
10134-101340030 = "そうなの？"
10134-101340040 = "どうしたの？"
10134-101340050 = "RPGの常識です！"
10134-101340060 = "そしてアリスは思い出しました！"
10134-101340070 = "装備するだけではまだ足りないのだと！"
10134-101340080 = "先生"
10134-101340090 = "帰り道、すごい揺れでした"
10134-101340100 = "ごめん、想像より重くて……"
10134-101340110 = "一応頑張ったんだけど……"
10134-101340120 = "いえ、楽しかったので気にしないでください！"
10134-101340130 = "アトラクションに乗っているみたいでした！"
10134-101340140 = "それならよかった……"
10134-101340150 = "先生、アリスとパーティーを組んでください！"
10134-101340160 = "今日も勇者修行です！"
10134-101340170 = "勇者よ、本当にそれで良いのか？"
10134-101340180 = "先生？"
10134-101340190 = "アリスのための秘密特訓を用意したよ！ "
10134-101340200 = "短時間でレベルアップする特訓をしよう！"
10134-101340210 = "そんな特訓があるのですか！？"
10134-101340220 = "アリス、知りたいです！"
10134-101340230 = "先生！"
10134-101340240 = "本当にすごいです！"
10134-101340250 = "勇者のアーマーを着ても全然緊張しなくなりました！"
10134-101340260 = "特訓の成果が出たんだね！"
10134-101340270 = "アリスが頑張ったからだね！"
10134-101340280 = "アリスだけではあのような特訓は思いつかなかったと思います！"
10134-101340290 = "やっぱり先生はすごいです！"
10134-101340300 = "ううう"
10134-101340310 = "アリスは勇者失格かもしれません"
10134-101340320 = "アリス？"
10134-101340330 = "何かあった？"
10134-101340340 = "アリスは見習い勇者に戻ります……"
10134-101340350 = "今どこにいるの？"
10134-101340360 = "すぐ行くから待っててね"
10134-101340370 = "先生！"
10134-101340380 = "まだ起きていたのですね！"
10134-101340390 = "そうだけど……"
10134-101340400 = "どうして分かったの！？"
10134-101340410 = "ふっふっふ！"
10134-101340420 = "窓の外を見てください！"
10134-101340430 = "窓の外？"
10134-101340440 = "先生！"
10134-101340450 = "HELP！"
10134-101340460 = "助けが必要かな？"
10134-101340470 = "今日も冒険中？"
10134-101340480 = "緊急事態です！"
10134-101340490 = "ここに来てください！"
10134-101340500 = "先生！"
10134-101340510 = "またアリスと冒険してくださいね！"
10134-101340520 = "もちろん！"
10134-101340530 = "冒険は始まったばかりだからね"
10134-101340540 = "はい！アリスの冒険はまだまだこれからです！"
10134-101340550 = "それに、新しい仲間も一緒です！"
