[translation]
10131-101310010 = "ごきげんよう、先生"
10131-101310020 = "今日はシャーレ当番の日ですので"
10131-101310030 = "失礼のないよう、まずはこうしてご挨拶のメッセージをいたしました"
10131-101310040 = "そんなにかしこまらなくていいのに……"
10131-101310050 = "ご負担でしたでしょうか……？"
10131-101310060 = "いや、そこまでじゃないけど、もっと気軽に話して欲しいかな"
10131-101310070 = "承知いたしました"
10131-101310080 = "それでは今日一日、どうぞよろしくお願いいたしますわね"
10131-101310090 = "先生のご予定を伺っても良いでしょうか？"
10131-101310100 = "もうすぐアイスホッケーカップの準決勝があるのです！"
10131-101310110 = "よろしければその日にご一緒できればと思うのですが……"
10131-101310120 = "あっ"
10131-101310130 = "申し訳ございません"
10131-101310140 = "先生のご都合も伺わずに勝手に……"
10131-101310150 = "気にしないで！タカネが嬉しそうで安心したよ"
10131-101310160 = "そ"
10131-101310170 = "そ、そうでしたか"
10131-101310180 = "よかったですわ……"
10131-101310190 = "日程をもらったら調整するね。あとで送ってほしいな"
10131-101310200 = "それって……"
10131-101310210 = "はい、ありがとうございます！"
10131-101310220 = "先生！"
10131-101310230 = "本日、ですわ"
10131-101310240 = "お忘れではありませんわよね？"
10131-101310250 = "私もすごく楽しみにしていたよ"
10131-101310260 = "はい！"
10131-101310270 = "それでは、出版部の部室でお待ちしておりますわね"
10131-101310280 = "先日はアイスホッケーを一緒に鑑賞してくださり、ありがとうございました"
10131-101310290 = "ですが"
10131-101310300 = "あの日いろいろとあったことについては"
10131-101310310 = "私……本当に申し訳なく思っております……"
10131-101310320 = "気にしなくていいよ。私も楽しかったし"
10131-101310330 = "そ、そうですか？"
10131-101310340 = "それで、なのですが！お詫びも兼ねて"
10131-101310350 = "今日は私からお昼をご馳走したいと思いまして"
10131-101310360 = "タカネの手料理！？"
10131-101310370 = "ええ"
10131-101310380 = "ちょうど今日は「もやし祭」の日でもありますし"
10131-101310390 = "もやし……まつり？"
10131-101310400 = "ごきげんよう、先生！"
10131-101310410 = "なんだかご機嫌だね、タカネ"
10131-101310420 = "ええ！とても良いことがありまして……"
10131-101310430 = "先生、ご存じですか？"
10131-101310440 = "今夜、オーロラが見られるらしいのです！"
10131-101310450 = "なので、風景写真を撮りに行こうかと"
10131-101310460 = "その……もしよろしければ……"
10131-101310470 = "ご一緒に、いかがでしょう？"
10131-101310480 = "オーロラの風景写真？"
10131-101310490 = "ええ"
10131-101310500 = "もちろん、お忙しいのは重々承知ですので……"
10131-101310510 = "ご無理はなさらず……"
10131-101310520 = "断っていただいても構いませんわ"
10131-101310530 = "タカネのお願いだもん、行かないとね！"
10131-101310540 = "合法的に残業抜け出せるし、行こうかな！"
10131-101310550 = "そ"
10131-101310560 = "そんな風に仰っていただけるなんて……"
10131-101310570 = "少し……恥ずかしいですけれど"
10131-101310580 = "本当に、感謝いたしますわ"
10131-101310590 = "ふふっ"
10131-101310600 = "その気持ち、少しわかりますわ"
10131-101310610 = "締切前になると散歩にでかけたくなりますものね"
10131-101310620 = "それでは、お待ちしておりますわ"
