[translation]
10132-101320010 = "ごめんなさい、部長……"
10132-101320020 = "次の動画撮影なのですが……"
10132-101320030 = "日程を調整してもらえますか……？"
10132-101320040 = "いつの間に私が部長に……！？"
10132-101320050 = "先生！？"
10132-101320060 = "ごめんなさい！！"
10132-101320070 = "送信先を間違えてしまいました！"
10132-101320080 = "なにか急用でも入ったの？"
10132-101320090 = "実は……"
10132-101320100 = "ちょうどその日"
10132-101320110 = "ファッションモデルのアルバイトをすることになりまして……"
10132-101320120 = "先生"
10132-101320130 = "美術はお好きですか？"
10132-101320140 = "急にどうしたの……？"
10132-101320150 = "もしよろしければ"
10132-101320160 = "お願いがありまして……"
10132-101320170 = "何でも言って！"
10132-101320180 = "私……"
10132-101320190 = "美術予備校へ行くことになったんです……！"
10132-101320200 = "絵に目覚めた！？"
10132-101320210 = "先生も無事に帰られましたか？"
10132-101320220 = "今日の食事、とても美味しかったです！"
10132-101320230 = "考えてみたら"
10132-101320240 = "何だか、奢っていただいてばかりで……"
10132-101320250 = "次は、必ず私が……！"
10132-101320260 = "先生"
10132-101320270 = "お昼ご飯、もう食べましたか……？"
10132-101320280 = "ま、まだ朝の8時だから……"
10132-101320290 = "つまり、食べてないと……！"
10132-101320300 = "では"
10132-101320310 = "お昼は二人で"
10132-101320320 = "食べに行きませんか……？"
10132-101320330 = "先生"
10132-101320340 = "これが最後です……！"
10132-101320350 = "えっ？"
10132-101320360 = "その……"
10132-101320370 = "本当の本当の最後に"
10132-101320380 = "ファッションショーへ出ようと思います……！"
10132-101320390 = "それで……"
10132-101320400 = "一緒に行っていただきたくて……"
10132-101320410 = "行こう！"
10132-101320420 = "先生"
10132-101320430 = "先ほどは失礼しました……"
10132-101320440 = "大丈夫だよ、気にしないで"
10132-101320450 = "どんな服装でも"
10132-101320460 = "フェンスを越えられるように"
10132-101320470 = "もっと修行します……！"
10132-101320480 = "うん、応援してるね！"
10132-101320490 = "はい、先生！"
