[translation]
10130-101300010 = "こちらの番号……"
10130-101300020 = "先生のもので合っていますか？"
10130-101300030 = "確認のために、ご連絡しました"
10130-101300040 = "合ってるよ、大丈夫"
10130-101300050 = "よかったです"
10130-101300060 = "近況をご報告します"
10130-101300070 = "色々あって"
10130-101300080 = "アリウスの見回りをすることになりました"
10130-101300090 = "見回り？"
10130-101300100 = "はい"
10130-101300110 = "取り急ぎ、ご報告までに"
10130-101300120 = "そっか"
10130-101300130 = "じゃあ早速"
10130-101300140 = "アリウスに行かないとね！"
10130-101300150 = "え？"
10130-101300160 = "どうしてですか？"
10130-101300170 = "おはようございます、先生"
10130-101300180 = "今日はスバルが当番の日だね！"
10130-101300190 = "そうですね"
10130-101300200 = "シャーレでのお仕事について"
10130-101300210 = "事前にいろいろ調べておきました"
10130-101300220 = "準備はできています"
10130-101300230 = "ちょっと緊張してる？"
10130-101300240 = "いいえ"
10130-101300250 = "全くしていませんよ"
10130-101300260 = "緊張なんてするわけないじゃないですか"
10130-101300270 = "私のこと、見くびってませんか？"
10130-101300280 = "そっか"
10130-101300290 = "そういうことにしとくね！"
10130-101300300 = "先生……？"
10130-101300310 = "学園の方針といいますか……"
10130-101300320 = "アルバイトをすることになりました"
10130-101300330 = "スバルがアルバイト！！？"
10130-101300340 = "驚きすぎですって！"
10130-101300350 = "恥ずかしいからやめてください！"
10130-101300360 = "当たり前のことをやっただけなのに、追加で報酬を頂いてしまいました"
10130-101300370 = "外の世界ってよく分かりません……"
10130-101300380 = "ああいうことができる子は、なかなかいないから……"
10130-101300390 = "……それでちゃんと回ってるんですか？世の中って"
10130-101300400 = "……そうだね、意外と"
10130-101300410 = "ま、ますますよく分からなくなりました……"
10130-101300420 = "こんにちは、先生"
10130-101300430 = "今日は休日ですが、いかがお過ごしでしょう？"
10130-101300440 = "昨日なんとか仕事片づけたから……"
10130-101300450 = "今日は休めるんだ……"
10130-101300460 = "大人は仕事を終わらせないと休めないんですね……"
10130-101300470 = "つらい……子供になろうかな"
10130-101300480 = "スバルせんぱーい、おやつちょーだい"
10130-101300490 = "何言ってるんですか！？もう……"
10130-101300500 = "私の方はですね"
10130-101300510 = "この間のバイト代のおかげで"
10130-101300520 = "ちょっと余裕ができたのですが"
10130-101300530 = "何に使えばいいのかと"
10130-101300540 = "何かしたいこととか、欲しいものはない？"
10130-101300550 = "え？"
10130-101300560 = "あー"
10130-101300570 = "うーん"
10130-101300580 = "んー……"
10130-101300590 = "ないことも"
10130-101300600 = "ないんですが"
10130-101300610 = "しばらく風に当たっていたせいか"
10130-101300620 = "体が冷えた気がします"
10130-101300630 = "責任とってください、先生"
10130-101300640 = "どのように責任を取りましょう！？"
10130-101300650 = "冗談です"
10130-101300660 = "その代わり"
10130-101300670 = "またショッピングに付き合ってくださいね"
10130-101300680 = "今度は別の曲を練習しておくので"
10130-101300690 = "こんにちは、先生"
10130-101300700 = "見回り中ですが、連絡してみました"
10130-101300710 = "今日も頑張ってるんだ？"
10130-101300720 = "大事なことですから"
10130-101300730 = "後輩たちを "
10130-101300740 = "見てあげないといけませんし"
10130-101300750 = "スバル自身のことは？"
10130-101300760 = "え？"
10130-101300770 = "あまり考えたことがありませんでした"
10130-101300780 = "少し考えてみたのですが"
10130-101300790 = "ハーモニカでヘビーメタルは吹けないんでしょうか"
10130-101300800 = "えっと、教師たるもの"
10130-101300810 = "できないことはない、と言いたいところだけど……"
10130-101300820 = "なるほど"
10130-101300830 = "先生がそう言うなら……"
10130-101300840 = "いつか絶対、ハーモニカでヘビーメタルを吹いてみせます！"
