[translation]
10136-101360010 = "おはよう、先生"
10136-101360020 = "……先生？"
10136-101360030 = "起きてる？"
10136-101360040 = "わあっ"
10136-101360050 = "起こしてくれてありがとう、エイミ……"
10136-101360060 = "よく眠れたみたいだね"
10136-101360070 = "また後で"
10136-101360080 = "夕飯どうだった？"
10136-101360090 = "普通……かな"
10136-101360100 = "カロリーも栄養バランスもバッチリだと思ったけど……"
10136-101360110 = "これから運動するし……"
10136-101360120 = "何かするの？"
10136-101360130 = "うん。今から"
10136-101360140 = "夜間の偵察に出ようと思って"
10136-101360150 = "なんで？"
10136-101360160 = "せんせ#@$%!^?"
10136-101360170 = "エイミ？"
10136-101360180 = "よか@^#*&った"
10136-101360190 = "こ~-@+;れ"
10136-101360200 = "さい*&ご#SA~バッテリー"
10136-101360210 = "座標&@ad*&転送"
10136-101360220 = "今日もお疲れ様、先生"
10136-101360230 = "一日が早いね……"
10136-101360240 = "本当にあっという間だね"
10136-101360250 = "特にここだと時間の感覚がおかしくなっちゃう"
10136-101360260 = "今日はほとんど室内にいたからね"
10136-101360270 = "うん、それでなんだけど……"
10136-101360280 = "ちょっと気分転換しようかなって"
10136-101360290 = "先生？"
10136-101360300 = "大丈夫？"
10136-101360310 = "大丈夫だよ。どうしたの？"
10136-101360320 = "風邪とか引いてないかなって"
10136-101360330 = "心配になって"
10136-101360340 = "そこまで弱くないよ……"
10136-101360350 = "そっか"
10136-101360360 = "ちょっと残念"
10136-101360370 = "うそ"
10136-101360380 = "よかった"
10136-101360390 = "なんか言おうとした？"
10136-101360400 = "素直に白状しなさい！"
10136-101360410 = "何でもない"
10136-101360420 = "ただ"
10136-101360430 = "温めるのに一番効率的なのは"
10136-101360440 = "体温っていうからね"
10136-101360450 = "……それって？"
10136-101360460 = "……エイミ！？エイミさん！？"
