[translation]
16009-160090760 = "先生殿"
16009-160090770 = "遠い昔の古文書や"
16009-160090780 = "古代の記録媒体に "
16009-160090790 = "興味はお有りだろうか……"
16009-160090800 = "まさか、エンシェント忍者の……！"
16009-160090810 = "あの古代の巻物が！？"
16009-160090820 = "さっすが先生殿！"
16009-160090830 = "良い反応～！"
16009-160090840 = "でもそれじゃない"
16009-160090850 = "この流れで！？"
16009-160090860 = "正確に言うと"
16009-160090870 = "半分は正解なんだけどねー"
16009-160090880 = "もし気になるなら"
16009-160090890 = "商店街まで来て！"
16009-160090900 = "待ってるよー、先生殿！"
16009-160090910 = "（シュバババッ）←素早く走る音"
16009-160090920 = "う、うん……"
