[translation]
16019-160190010 = "おはようございます"
16019-160190020 = "おはよう……の割には少し早いね……"
16019-160190030 = "ですが状況が状況ですので"
16019-160190040 = "それはそうだね……"
16019-160190050 = "では、お待ちしております"
16019-160190060 = "飛鳥馬トキ、ただいま偵察を終えて復帰いたしました"
16019-160190070 = "この後、報告に伺います"
16019-160190080 = "怪我とかなかった？"
16019-160190090 = "心配してくださりありがとうございます"
16019-160190100 = "幸い、本日も無事でした"
16019-160190110 = "お聞きしたいことがあるのですが"
16019-160190120 = "アップグレードについてどう思いますか"
16019-160190130 = "リソースに余裕があれば強化していくもの、かな"
16019-160190140 = "他を少し諦めてでも強化していくもの、かな"
16019-160190150 = "なるほど"
16019-160190160 = "良い考え方です"
16019-160190170 = "先生はリソース配分を重視しているのですね"
16019-160190180 = "なるほど"
16019-160190190 = "良い考え方です"
16019-160190200 = "私も似たようなことを考えています"
16019-160190210 = "そして今回のお話はまさしく"
16019-160190220 = "アップグレードに関するご相談です"
16019-160190230 = "夜分遅くに失礼いたします"
16019-160190240 = "明け方の偵察を終えて復帰いたしました"
16019-160190250 = "……？"
16019-160190260 = "早すぎじゃない？まだ暗いけど……"
16019-160190270 = "はい、だからこそです"
16019-160190280 = "今日も忙しないですね"
16019-160190290 = "もうお昼の時間です"
16019-160190300 = "そうだね……"
16019-160190310 = "今は時が進むのを楽しむことにします"
16019-160190320 = "ですが先生の「最後」になることは諦めていません"
16019-160190330 = "うん……？"
16019-160190340 = "覚えておいてください"
16019-160190350 = "先生のおそばには"
16019-160190360 = "パーフェクトメイドであり、パーフェクトリコンである"
16019-160190370 = "飛鳥馬トキが居るということを"
