[translation]
20050-200500010 = "やっほ！"
20050-200500020 = "薄葉リツだよ！"
20050-200500030 = "明日の当番はリツだったね！"
20050-200500040 = "そういうこと！"
20050-200500050 = "よろしくね！先生！"
20050-200500060 = "せんせーせんせーせんせー"
20050-200500070 = "先生は何色が好き？"
20050-200500080 = "なにの色か、によるかな……？"
20050-200500090 = "おっけー！"
20050-200500100 = "じゃあボクが決めちゃうね！"
20050-200500110 = "え？何を？"
20050-200500120 = "リツ？"
20050-200500130 = "シャーレの前ついたよー！"
20050-200500140 = "何してる？"
20050-200500150 = "いきなりどうしたの！？"
20050-200500160 = "服買いにいこって話したじゃん？"
20050-200500170 = "もしかして忙しい？"
20050-200500180 = "忙しい……"
20050-200500190 = "だからこそ、行くよ。"
20050-200500200 = "えっ？"
20050-200500210 = "ねね、先生"
20050-200500220 = "ボク、すごく変なとこ見つけたの！"
20050-200500230 = "変なとこ···…?"
20050-200500240 = "ワイルドハントまで来てくれる？"
20050-200500250 = "先生にも見せたい！"
20050-200500260 = "悲しいニュース"
20050-200500270 = "あそこ、輸入には使えないかも"
20050-200500280 = "学院内につながる道がなかったの……"
20050-200500290 = "そっか、残念……"
20050-200500300 = "でもいいんだ！"
20050-200500310 = "先生とボクだけの秘密基地ができたから！"
20050-200500320 = "また遊ぼ！先生！"
