[translation]
20053-200530010 = "ドーモ、先生殿 "
20053-200530020 = "ドーモ、ミチル殿"
20053-200530030 = "おぉっ！"
20053-200530040 = "先生殿も忍者らしくなってきたね～"
20053-200530050 = "そろそろ忍術研究部に入りたくなった？"
20053-200530060 = "ところで今日はどうしたの？"
20053-200530070 = "スルー！？"
20053-200530080 = "うぅ、忍者にも心というものがあるのに……"
20053-200530090 = "……えっと、新しい忍術を研究してるんだけど"
20053-200530100 = "上手く行かないんだよねー……"
20053-200530110 = "ちょっと負傷しちゃって"
20053-200530120 = "負傷！？"
20053-200530130 = "あ"
20053-200530140 = "いや別に大したことないっていうか"
20053-200530150 = "すぐ向かう"
20053-200530160 = "え？"
20053-200530170 = "先生殿"
20053-200530180 = "その"
20053-200530190 = "ありがとね"
20053-200530200 = "買ってもらったのも、大事にするから"
20053-200530210 = "あと、さっきはごめん"
20053-200530220 = "……いや、やっぱり私は悪くないよね！？"
20053-200530230 = "（ボンッ！）←煙幕弾の効果音"
20053-200530240 = "ドーモ、先生殿"
20053-200530250 = "知らせが舞い込んできた……"
20053-200530260 = "傷が完治した、とのこと"
20053-200530270 = "……預けたドレスの話？"
20053-200530280 = "ふっふっふ！察しが良いね、先生殿！"
20053-200530290 = "さぁ、回収に行こーっ！"
20053-200530300 = "気をつけてね"
20053-200530310 = "何言ってるの？"
20053-200530320 = "始まりから終わりまで完璧に"
20053-200530330 = "それが忍者の鉄則！"
20053-200530340 = "それに、一緒に預けたんだから"
20053-200530350 = "受け取る時も一緒！"
20053-200530360 = "どういうこと！？"
20053-200530370 = "1時間後、お店の前で待ってるよー！"
20053-200530380 = "先生殿"
20053-200530390 = "その、急に逃げちゃってごめん……"
20053-200530400 = "ミチルに捨てられた……"
20053-200530410 = "！？！？"
20053-200530420 = "なにいっねゆの！？！？"
20053-200530430 = "ついに"
20053-200530440 = "見つけてしまった"
20053-200530450 = "チャンネルを大きくする秘訣を"
20053-200530460 = "そして、その秘訣を手にする方法を……！"
20053-200530470 = "急にどうしたの……？"
20053-200530480 = "ふっふっふ"
20053-200530490 = "なんとなんと"
20053-200530500 = "ある説明会の、参加資格を貰ったの！"
20053-200530510 = "それに参加するとね"
20053-200530520 = "再生数と登録者数を増やす"
20053-200530530 = "その秘訣を伝授してくれるんだって！"
20053-200530540 = "……な、なるほど"
20053-200530550 = "秘訣は自身の手で、とっておきのを生み出して見せる！"
20053-200530560 = "こうご期待！"
20053-200530570 = "お待ちしておりますぞ、ミチル殿"
20053-200530580 = "にゃははっ、ありがとー先生殿！"
20053-200530590 = "ふふっ"
20053-200530600 = "ふっふっふっふっふ"
20053-200530610 = "ついに分かっちゃったよ、先生殿！"
20053-200530620 = "\"な、何のこと？\""
20053-200530630 = "それはねー"
20053-200530640 = "ううん"
20053-200530650 = "やっぱりモモトークじゃなくて "
20053-200530660 = "直接話したほうが良いかも！"
20053-200530670 = "すぐにそちらへ参ろう！"
20053-200530680 = "待っておれ！"
20053-200530690 = "先生殿……"
20053-200530700 = "安易に流行を取り入れるのはやめるよ……"
20053-200530710 = "真剣に、忍者の道を歩んでいくね……"
