[translation]
20055-200550010 = "先生、わたし……もう"
20055-200550020 = "ロッカーに、入れなくなっちゃいました……"
20055-200550030 = "本当は入りたいのに"
20055-200550040 = "でも、身体が……"
20055-200550050 = "ユズがロッカーに入れなく……？"
20055-200550060 = "ちょっとそっちに行くね！"
20055-200550070 = "え？"
20055-200550080 = "い、いえ、来ていただくほどの……"
20055-200550090 = "うう……"
20055-200550100 = "……お願い、します"
20055-200550110 = "ゲームって……"
20055-200550120 = "こんなに難しいものだったんですね……"
20055-200550130 = "ユズがそんなことを言うなんて……"
20055-200550140 = "ちょっとそっち行くね！"
20055-200550150 = "えっ？"
20055-200550160 = "ま、待ってください！"
20055-200550170 = "わ、わたし本当に大丈夫ですから！"
20055-200550180 = "今度発売された最新のVRゲーム機"
20055-200550190 = "「バーチャルボス4.0」……"
20055-200550200 = "先生は、ゲットできましたか……？"
20055-200550210 = "私もダメだったよ……"
20055-200550220 = "カートに入れることすらできなかった……"
20055-200550230 = "ひぇ……"
20055-200550240 = "わたしも買えませんでした……"
20055-200550250 = "新作のたびに入手困難になりますけど……今回は本当にすごい人気みたいで……"
20055-200550260 = "でも、まったく入手方法がないわけじゃないんだ！"
20055-200550270 = "えっ？"
20055-200550280 = "この状況からでも手に入れられる方法が！？"
20055-200550290 = "うん、あるよ……"
20055-200550300 = "本当に、とんでもないことになっちゃいました……"
20055-200550310 = "変な誤解が広まらなければいいんですが……"
20055-200550320 = "それだけみんながユズの才能に驚いたってことじゃないかな？"
20055-200550330 = "そんなことないです！変な噂が広まってしまったら……"
20055-200550340 = "あ、そうだ……ゲーム開発部の部室に「バーチャルボス4.0」の本体が送られてきました"
20055-200550350 = "あの日はバタバタしすぎて、景品を受け取れなかったので……"
20055-200550360 = "もしよかったら"
20055-200550370 = "今度「バーチャルボス」で一緒に遊びませんか？"
20055-200550380 = "ソフトも用意しておきますので！"
20055-200550390 = "うん。何があっても行くよ"
20055-200550400 = "はい！お待ちしています！"
20055-200550410 = "最近はVRゲームにもだんだん慣れてきました"
20055-200550420 = "だいぶ身体もスムーズに動くようになってきて……"
20055-200550430 = "もうUZQueenを止められるゲームジャンルは、なくなってしまったね……"
20055-200550440 = "そ"
20055-200550450 = "そんな"
20055-200550460 = "もう……からかわないでください！"
