[translation]
20051-200510010 = "先生、レイサです！"
20051-200510020 = "お小遣いを賢く使うには、どうしたらいいですか？"
20051-200510030 = "予算を決めて使うようにすると良いよ"
20051-200510040 = "優先順位をつけて、無駄遣いを防ごう"
20051-200510050 = "なるほど！"
20051-200510060 = "必要なものだけ買う！ってことですね！"
20051-200510070 = "レイサは飲み込みが早いね"
20051-200510080 = "えへへ"
20051-200510090 = "じゃあ、これは必要なものでいいですよね？"
20051-200510100 = "「まほリバ　テルミットピンク　フレンドシップフュージョンコスチューム」"
20051-200510110 = "相場の半額で出てました！"
20051-200510120 = "相場の半額！？！？！？"
20051-200510130 = "実質タダじゃん！！買いだよ！！！！"
20051-200510140 = "そうですよね！先生に相談してよかったです！"
20051-200510150 = "マジカル賢い～！です！"
20051-200510160 = "先生、レイサです"
20051-200510170 = "家についた？"
20051-200510180 = "はい、おかげさまで！"
20051-200510190 = "上着は洗ってからお返しします！"
20051-200510200 = "急がなくて大丈夫だからね"
20051-200510210 = "先生はいつも優しいです！"
20051-200510220 = "変身の呪いを解いてくださり、ありがとうございます！"
20051-200510230 = "へへへっ"
20051-200510240 = "66307366979"
20051-200510250 = "レイサ？"
20051-200510260 = "はっ"
20051-200510270 = "あっ"
20051-200510280 = "すみません！間違えました！"
20051-200510290 = "先生のモモトークに送ってしまいました！"
20051-200510300 = "週末のイベントの予約番号を"
20051-200510310 = "自分に送るつもりが……"
20051-200510320 = "お！何のイベント？"
20051-200510330 = "魔法少女のオンリーイベントです"
20051-200510340 = "魔法少女モノのファンが集まってグッズを売ったり、コスプレをする"
20051-200510350 = "そんなイベントです！"
20051-200510360 = "自警団として、パトロールに行かねばと思いまして！"
20051-200510370 = "私も行きたいな！"
20051-200510380 = "今からでも間に合う？"
20051-200510390 = "！！"
20051-200510400 = "もちろんです！"
20051-200510410 = "先生も行きますか！"
20051-200510420 = "「行く」じゃない。"
20051-200510430 = "「参戦」……するとしようか！"
20051-200510440 = "カッコいい！！"
20051-200510450 = "いいですね！！"
20051-200510460 = "私も完全武装で向かいます！！"
20051-200510470 = "先生！"
20051-200510480 = "今日はとても楽しかったです！"
20051-200510490 = "先生が背中を押してくださったから"
20051-200510500 = "私も勇気を出すことができました！"
20051-200510510 = "レイサのためなら、なんでもするからね！"
20051-200510520 = "えへへ"
20051-200510530 = "またお会いしましょう！"
20051-200510540 = "先生"
20051-200510550 = "「ドレスコード」って何でしょう？"
20051-200510560 = "時と場所に合わせた服を着ること、かな？"
20051-200510570 = "ということは"
20051-200510580 = "ある目的のために着ている服も"
20051-200510590 = "ドレスコードに沿っていることになりますか？"
20051-200510600 = "なるんじゃないかな"
20051-200510610 = "なるほど"
20051-200510620 = "分かりました……"
20051-200510630 = "？"
20051-200510640 = "完璧だったのに！"
20051-200510650 = "最後で台無しでした！"
20051-200510660 = "それくらい大丈夫だよ！"
20051-200510670 = "すっごくカッコよかったよ！"
20051-200510680 = "でも、パーフェクトに活躍したかったです"
20051-200510690 = "次こそ！"
20051-200510700 = "スーパーパーフェクトな活躍をおみせします！"
20051-200510710 = "先生、レイサです"
20051-200510720 = "先日ファスナーを直していただいたときの備品"
20051-200510730 = "まだありますか？"
20051-200510740 = "もちろん！どうしたの？"
20051-200510750 = "同じ過ちを繰り返してしまう私って"
20051-200510760 = "バカ……ですよね……"
20051-200510770 = "まさか……？"
20051-200510780 = "またファスナーが……？"
20051-200510790 = "……"
20051-200510800 = "シャーレに伺います……"
20051-200510810 = "先生！"
20051-200510820 = "おかげさまで危機は去りました！"
20051-200510830 = "もうファスナーが壊れることはありません！"
20051-200510840 = "私は無敵です！"
20051-200510850 = "お！どうやったの？"
20051-200510860 = "ふふ、簡単なことです"
20051-200510870 = "ファスナーを外して、全部ボタンにしました！"
20051-200510880 = "それだと、一人で着れなくなるんじゃ……"
20051-200510890 = "え……"
20051-200510900 = "えっ？"
