[translation]
20052-200520010 = "問題："
20052-200520020 = "以下のうち、レッドウィンターで生き残るために"
20052-200520030 = "出版部が取るべき行動は？（4点）"
20052-200520040 = "1.読書啓蒙週間を作る"
20052-200520050 = "2.電子書籍化プロジェクトを進行する"
20052-200520060 = "3.通信線路設備工事をする"
20052-200520070 = "最後は出版部と関係ないんじゃ……？"
20052-200520080 = "ファイナルアンサーですか？"
20052-200520090 = "ええっ……ギブアップ"
20052-200520100 = "ムフフ、そうでしょうとも"
20052-200520110 = "正解は――3番なのですから"
20052-200520120 = "うん……？"
20052-200520130 = "解説をご希望の場合は"
20052-200520140 = "レッドウィンター出版部までお気軽にどうぞ"
20052-200520150 = "『レッドウィンター出版部がシャーレと私的な領域で接触する"
20052-200520160 = "その歴史的出会いについてのダダイズムテーゼ』"
20052-200520170 = "次の記事の題名です。いかがですか？"
20052-200520180 = "重い！"
20052-200520190 = "記念すべきシャーレ訪問日を機に"
20052-200520200 = "大々的な特集を組む予定だったんですけど"
20052-200520210 = "ふつうに当番に来て……"
20052-200520220 = "先生"
20052-200520230 = "レッドウィンターへの出張は、たしか今日まででしたよね？"
20052-200520240 = "うん。列車に乗って帰るところだよ"
20052-200520250 = "はい？"
20052-200520260 = "レッドウィンターの列車、ですか……？"
20052-200520270 = "何か問題でもあるの？"
20052-200520280 = "うーん……"
20052-200520290 = "とりあえず"
20052-200520300 = "私がお送りしましょう"
20052-200520310 = "帰宅されましたか？"
20052-200520320 = "今日は先生のおかげで楽しかったです"
20052-200520330 = "よかった！"
20052-200520340 = "よく考えたら問題の根源は"
20052-200520350 = "ダイヤにある気もするんですが"
20052-200520360 = "おや"
20052-200520370 = "もしレッドウィンターの鉄道が永遠にダメだったら"
20052-200520380 = "先生が列車の旅に永遠に付き合ってくださる、という……？"
20052-200520390 = "さすがにナシ"
20052-200520400 = "ですよね……"
20052-200520410 = "いますか"
20052-200520420 = "先生"
20052-200520430 = "いるよ～"
20052-200520440 = "はい"
20052-200520450 = "事業"
20052-200520460 = "いや"
20052-200520470 = "出版部のことで"
20052-200520480 = "相談といいますか"
20052-200520490 = "第三者の意見も参考にしたく"
20052-200520500 = "出版部に行くね！"
20052-200520510 = "えっ"
20052-200520520 = "はい"
20052-200520530 = "ありがとうございます"
20052-200520540 = "結論を明瞭に伝えるその話法"
20052-200520550 = "私も見習わなければ"
20052-200520560 = "先生"
20052-200520570 = "なんで"
20052-200520580 = "売れてるんですかこれ"
20052-200520590 = "うまくいったね！"
20052-200520600 = "私の予想通り！"
20052-200520610 = "なんだか悔しいですね"
20052-200520620 = "ですが成果は成果です"
20052-200520630 = "うーん"
20052-200520640 = "次は「レッドベア」の特別インタビューとして"
20052-200520650 = "先生との対談特集を組みたいのですが～"
20052-200520660 = "丁重にお断りします、編集長"
20052-200520670 = "そういうと思ってました"
20052-200520680 = "まあこれからもお世話になります"
20052-200520690 = "事業相談でも"
20052-200520700 = "それ以外でも"
20052-200520710 = "いつでも遊びにきてね"
20052-200520720 = "ええ、文字通りそうさせていただきますとも。ムフフ"
