[translation]
10129-10 = "ブルーア、アーカイ……ブ。"
10129-100 = "お忙しい中、\nお越しいただき\nありがとうございます。"
10129-110 = "自警団任務、\nいつでもいけます。"
10129-120 = "ど、どうでしょうか？"
10129-130 = "この衣装……\n変じゃないですか？"
10129-140 = "い、いえ。褒めて\nほしかったわけでは……！"
10129-150 = "自警団の近況……ですか。"
10129-160 = "そうですね、\n今のところ順調です。"
10129-170 = "あ、その……\nこれが自警団の\n制服になったわけでは\nありませんからね！"
10129-180 = "ボルトキャッチ！\nテルミットホワイト！"
10129-190 = "せ、先生！？\nいつからそこに！？"
10129-20 = "こ、これも自警団任務の延長……です。\nトリニティと先生の安全のために、尽力いたします。"
10129-200 = "研究のために、\n魔法少女作品を\n見ているのですが……。"
10129-210 = "火力が高ければ\nそれは魔法になる……\nという作品を見かけて、\n大変興味深かったです。"
10129-220 = "執務室のあの壁……\n仮設のものですね。"
10129-230 = "貫通射撃を行うのに\nちょうどよさそうです。"
10129-240 = "お誕生日\nおめでとうございます。\nよろしければ、一緒に\n散歩などいかがでしょう？"
10129-250 = "え、プレゼントに……\nま、魔法少女のセリフを\n言ってほしい！？"
10129-260 = "い、いくらなんでも、\nそれは……っ！"
10129-2600 = "ええと……\nこういうグッズ自体は\n可愛いと思いますが……。\n果たして、私に\n似合うのでしょうか？"
10129-270 = "う、うぅ……"
10129-280 = "まじかる、りりかる……\nてるみっとほわいと！"
10129-290 = "……これでいいでしょうか？"
10129-30 = "ここは平和ですね……\nとても良いことです。"
10129-300 = "私の誕生日、ですか？"
10129-310 = "ああ、もうそんな\n日なのですね。"
10129-320 = "意識から\n抜け落ちていました。\n祝ってくださり、\nありがとうございます。"
10129-330 = "ほしいプレゼント、ですか？\nうーん……。"
10129-340 = "特にないです。\nすでに十分、\nいただいていますから。"
10129-350 = "明けまして\nおめでとうございます。\n今年もよろしく\nお願いします。"
10129-360 = "新年の願い事、\nでしょうか……。"
10129-370 = "また来年も、こうやって\nご挨拶できると嬉しいです。"
10129-380 = "街に人が多く\nなる時期ですね。\n浮かれてしまう\n気持ちも分かります。"
10129-390 = "その平穏を守れること……\n守れていることを、\n嬉しく思います。"
10129-40 = "（あの方、もしかして\n話しかけようと\nしてくださって\nいるのでは？）"
10129-400 = "ここまで来る間、\n多くの方からお菓子を\nいただいたのですが……"
10129-410 = "いたずらをしないで、\nとも言われまして……。"
10129-420 = "そんなに、いたずらを\nする方だと思われて\nいるのでしょうか？"
10129-440 = "せ、先生！？"
10129-450 = "な、なにかご用件でも！？"
10129-460 = "というか、いつから\nいらしてたんですか！"
10129-470 = "音楽に集中していたので\n全然気づいておらず……。"
10129-480 = "でも、相手が先生で\n良かったです。"
10129-490 = "あっ、こ、この衣装は、\nその……！"
10129-50 = "（な、何か話題を……\n出てこない……\n昨晩、考えて\nおいたのに……！）"
10129-500 = "自警団の潜入捜査の\nため、でして……。"
10129-510 = "わ、私の趣味と\nいうわけでは……！\n違います！本当に！"
10129-520 = "サイズが合うか\n事前に確認しようと\n思って着ただけで……！"
10129-530 = "（か、可愛いと言って\nくださりました……）"
10129-540 = "（いきなり\n褒められると……\nうぅ……！）"
10129-550 = "（褒められるのは、\nまだ慣れません。）"
10129-560 = "（嬉しくは\nありますが……！\nでも……！）"
10129-570 = "今日見たことは、\n他の方には内緒に\nしてくださいね！"
10129-580 = "これは、\n機密事項……なので！"
10129-60 = "（やはり、着替えて\nくるべきだったの\nでしょうか……）"
10129-70 = "避難経路は\n把握しています。"
10129-80 = "お帰りなさい、先生。\nお待ちしておりました。"
10129-90 = "お呼び出し、感謝します。\nいつでも出動できますよ。"
