[translation]
10135-10 = "言わなきゃいけないんですよね……？\nブルー、アーカイブ。"
10135-20 = "こんにちは、ケイです。\n何をそんなに慌てているんですか……？\nはぁ……これから、先生のことを\n見守らせていただきますね。"
10135-30 = "（私だって\n「生徒」ですから……\nカフェくらい……！）"
10135-40 = "あれは……\nどんな味\nなんでしょう？"
10135-50 = "なるほど……これが、\nまったりすると\nいうこと……。"
10135-60 = "自分の身体を\n持つのは……。\n不便なことでも\nあるんですね……。"
10135-70 = "ふふ……\nこうして立っている\nだけでも、\nなんだか楽しいです……。"
10135-80 = "もう、何してたんですか？\n遅いですよ！"
10135-90 = "準備は済ませておいたので……\nはい、座ってください。"
10135-100 = "あっ、いらしたのですね。\nでは始めましょうか。"
10135-110 = "……何を\nニヤニヤしてるんですか！"
10135-120 = "可愛いって\n言うのやめてください！"
10135-130 = "い、嫌なのかって……？\nと、というより……！"
10135-140 = "……。"
10135-150 = "可愛い以外も言ってください、\nという意味です……。"
10135-160 = "どうしていつも\n怒ってばっかりなのか……？"
10135-170 = "……失礼ですね。別に\n怒っているわけじゃないです。"
10135-180 = "でもまあ……\n世の理を知ってしまえば。"
10135-190 = "怒らないでいるのは難しい、\nと思っているのですが。"
10135-200 = "これを機に\n言わせてもらいますが。"
10135-210 = "食事はちゃんと取っていますか？\n適度な運動も必要です。"
10135-220 = "早寝早起きが良いのは、\n大人にも当てはまる\nことなんですよ。"
10135-230 = "仕事はほどほどに。\nとはいえ怠けるのもほどほどに。"
10135-240 = "……本当にもう、\n手が焼けるんですから。"
10135-250 = "ああ、もう！\nだからそんな風に子ども\n扱いしないでください！"
10135-260 = "……私、そこまで\n幼くないですから。"
10135-270 = "笑いました！？\n今笑いましたね！？\n私ちゃんと見たんですから！"
10135-280 = "覚えててくださいよ！？\nいつかその身にしかと\n分からせてやるんですから！！"
10135-290 = "何ですか？\n用がないなら\n呼ばないでください。"
10135-300 = "えっ？\n私がちゃんといるのか\n確認するのが仕事？"
10135-310 = "本当にこの人は！\nいっつも\n適当なことばっかり言って！"
10135-320 = "でもまあ……\nこういうやりとりも、\n嫌いではありません。"
10135-330 = "こんにちは、先生。"
10135-340 = "えっ？\n何か言いたいことはないか？"
10135-350 = "……。"
10135-360 = "ないです。"
10135-370 = "ないったらないと\n言っているでしょう！"
10135-380 = "……。"
10135-390 = "お誕生日おめでとうございます、\n先生。"
10135-400 = "えっ！？\n私の誕生日ですか？\nそ、それよりアリスの\n誕生日を……！"
10135-410 = "えっ、同じ日だから\nいいじゃないかって……。\nそ、それはそうですが……！"
10135-420 = "……ありがとうございます。"
10135-430 = "あけまして\nおめでとうございます。\nお正月……\n新年の初日ですが……。"
10135-440 = "いえ、私もそろそろ\n慣れないといけませんね。"
10135-450 = "もう立派な\n「生徒」なのですから。"
10135-460 = "別にプレゼントとか\n求めていません。"
10135-470 = "もちろん、\n頂けるならちゃんと\n頂きますが。"
10135-480 = "……。"
10135-490 = "ほ、本当に\n何もないんですか……？"
10135-500 = "……！！\nあ、ありがとうございます……！"
10135-510 = "霊が帰ってくる日……だなんて、\n迷信深い祝祭ですね……。"
10135-520 = "……。"
10135-530 = "私に、飴はないんですか？"
10135-550 = "心配しないでください。"
10135-560 = "私が消えることはありません。"
10135-570 = "むしろ、その逆ですね。"
10135-580 = "私は、どんな手を使ってでも\n生き残ってやるつもりですから。"
10135-590 = "先生がこの世界を\n見捨てないというのなら。"
10135-600 = "私だって最後まで、\n絶対に諦めたりしません。"
10135-610 = "だから大丈夫……\n絶対、大丈夫です。"
10135-620 = "私はずっとここにいます。"
10135-630 = "ここだけの話ですけど……\n私は――"
10135-640 = "先生のこと、\n嫌いじゃありませんから。"
10135-2600 = "遠き地の星明かり……という意味です。\nそれだけ昔のことを言っているのだと\n思います。座標によると、過去と未来は\n同時に存在するとも言いますから。"
