[translation]
10130-10 = "ブルーアーカイブ、です。ふふ。"
10130-100 = "えっ？\n「まずは力を抜いて」……？"
10130-110 = "お菓子も自由に\n食べていい……？"
10130-120 = "そ、そういうわけには\nいきません！いくら\n当番といっても……。"
10130-130 = "……。"
10130-140 = "では、少しだけ……。"
10130-150 = "これはここだけの話ですが――"
10130-160 = "アリウス「分校」と\n呼ばれるの……\nあまり好きではないんです。"
10130-170 = "「分校」と言われると、\n本校よりも格下というか……\n隔離された場所、という\n印象になるじゃないですか。"
10130-180 = "……すみません、\nアリウスにいるみんなのことを\n考えていました。"
10130-190 = "あの子たちのためにも、\n頑張らないと。"
10130-20 = "梯スバルです。\nお困りの際には、あなたの力になりましょう。\nまぁ……あくまで、「アリウス流」ですが。"
10130-200 = "……えっ？「自分のためにも\n頑張って」？"
10130-210 = "あ……ありがとう、\nございます……。"
10130-220 = "へっ？勉強……？ちゃ、\nちゃんとやってますよ。"
10130-230 = "はぁ……でも、\n何でこんな役に\n立ちそうにもないものを……。"
10130-240 = "「今は理解できなくても、\nいつか役に立つ時がくる」\n……ですか。"
10130-250 = "ああ、もう……はいはい、\n分かりましたから！"
10130-260 = "その……先生に会うと、\n不思議な気持ちになります。"
10130-2600 = "まだ、全然実感が湧きません……。朝、目が覚めるたびに夢だったんじゃないかと不安になるほどに……。本当に、ありがとうございます、先生。大切にします。"
10130-270 = "今まで、こんなに\n良くしてくださった大人は……\nいなかったので。"
10130-280 = "お誕生日おめでとうございます、\n先生。"
10130-290 = "その、私にできることが\nあまりないので、\nお祝いの言葉だけに\nなってしまうんですが……。"
10130-30 = "カフェ……\nなんだか\n高そうな場所。"
10130-300 = "えっ？今度ハーモニカを\n聞かせてほしい……？\nそ、それは……。"
10130-310 = "はぁ……分かりました。\n先生にだけ、ですよ？"
10130-320 = "誕生日……祝ってくださって、\nありがとうございます。先生。"
10130-330 = "アリウスでは、\n誕生日を大切にしているんです。"
10130-340 = "それさえやめてしまったら\n本当に大切な何かまで、\nなくなってしまうような\n気がして。"
10130-350 = "まあでも……怒られるので、\nあまり盛大に祝ったりは\nできなかったんですけどね。"
10130-360 = "一年が終わり、\n新しい年が始まる日――"
10130-370 = "不思議なものです……\n今は、悪くないと\n思っているんですよ。"
10130-380 = "あけましておめでとう\nございます、先生。"
10130-390 = "クリスマスですね。\n一応、知ってますよ。"
10130-40 = "（なんだか……\nウォータータイムを\n思い出す）"
10130-400 = "その昔――\nトリニティとゲヘナに……。"
10130-410 = "銃弾の雨をプレゼントする\nサンタにでもなろうか、\nと冗談めかして\n言ったことがあるので。"
10130-420 = "ハロウィンのことはよく\n知らないのですが……"
10130-430 = "お祭りに乗じて\nお菓子をねだらなかったら、\n特に何もない日ですよね。"
10130-440 = "なんだか昔のアリウス\nみたいだなって思いました。\n……恐怖しか残っていなかった、\nあの頃の。"
10130-460 = "なんだか、新鮮な気持ちです。"
10130-470 = "こうして誰か一人のために\n演奏するのは初めてで……。"
10130-480 = "どう、でしたでしょうか？"
10130-490 = "変じゃ、なかったですか……？"
10130-50 = "あれは……\nなんだろう。"
10130-500 = "それって……その、本心、\nと受け取っていいんですよね？"
10130-510 = "……ありがとうございます。"
10130-520 = "本当は、他に何かできることが\nあればよかったのですが……。"
10130-530 = "今の私には、\nこれくらいしかなくて……。"
10130-540 = "えっ？「また練習したら\n聞かせてほしい」……？"
10130-550 = "「楽譜もたくさん\n買ったから」……？"
10130-560 = "そ、それは……。"
10130-570 = "また……その時になったら、\n考えさせてください。"
10130-60 = "（あまりこういう\nところには\n来られなかった\nなぁ……）"
10130-70 = "カフェのアルバイト……\n募集してたりするかな？"
10130-80 = "おかえりなさい、先生。　\n今日の当番を務めます、\n梯スバルです。"
10130-90 = "待機しておりました。\nご指示はありますか？"
