[translation]
10133-10 = "ブルーアーカイブ。"
10133-100 = "仕事を始めるのね。\n何でも言ってちょうだい。"
10133-110 = "時間は流れていない……\nという話があるのだけれど。"
10133-120 = "過去、現在、未来が全て同じ\n瞬間に存在するという説よ。"
10133-130 = "その理論なら……"
10133-140 = "今も、あの大きな事件の渦中に\nあるということになるわね。"
10133-150 = "正直、貴方のPCの\n中身に興味があるの。"
10133-160 = "このスーツがあれば、\n先生のデバイス程度、\n容易にハッキングできる。"
10133-170 = "……安心してちょうだい。\nそういったやり方は……\n好まないから。"
10133-180 = "観測可能な世界の向こうには、\n何があるのかしら。"
10133-190 = "私はその答えが知りたい。"
10133-20 = "電子の領域を制する最も合理的な答えを、\n貴方に見せてあげる。"
10133-200 = "……貴方と一緒に、よ。"
10133-210 = "先生のスーツも\n用意すれば良かったわね。"
10133-220 = "そうしたら、一緒に概念空間を\n楽しむことができたのに。"
10133-230 = "……現実でこのまま\n出かければ良い？"
10133-240 = "この格好ではダメよ。"
10133-250 = "重力は、どこにでも存在する。"
10133-260 = "……そう、貴方と私の間にも。"
10133-2600 = "みんなを守って見せる……\nその強い意志が、\n私に引き金を引かせるの。"
10133-270 = "私たちは無意識に、\n互いの方向へ落ちているのよ。"
10133-280 = "お誕生日おめでとう、先生。"
10133-290 = "プレゼントに、\n業務サポート特化型の\nアバンギャルド君を用意したわ。"
10133-30 = "ここも概念空間の\n一種……要分析ね。"
10133-300 = "……えっ？サポートなら\n私から直接、受けたい……？"
10133-310 = "そ、それは……困るわ……。"
10133-320 = "ああ、今日は私の誕生日……\nだったのね。"
10133-330 = "任務に没頭していたから、\n忘れていたわ。"
10133-340 = "何かに集中すると……他に\n気が回らなくなってしまうの。"
10133-350 = "先生のおかげで、\n良い思い出ができたわ。\nありがとう。"
10133-360 = "先生、明けましておめでとう。"
10133-370 = "お正月には、\n適した服装があるのでしょう？"
10133-380 = "……これで大丈夫かしら。"
10133-390 = "大歓迎……？\nなら……良いのだけれど。"
10133-40 = "片づけが上手く\nできるように\nなりたい……。"
10133-400 = "今日は、ある人の\n誕生を祝う日らしいわね。"
10133-410 = "あまりそういったものは\n理解できないのだけれど、"
10133-420 = "この時間を作ってもらえた\nことには……お礼を言うわ。"
10133-430 = "幽霊？私は信じていないわ。"
10133-440 = "重力や電磁気力と\n相互作用できない存在は、"
10133-450 = "私たちの目では\n捉えられないもの。"
10133-460 = "……よく分からない？どうして？"
10133-480 = "ふぅ……落ち着いたわ。"
10133-490 = "室内温度を\n考慮していなかったの。"
10133-50 = "……どうやら、\n先生の感性は\n私と近いようね。"
10133-500 = "私としたことが……\n目の前の結果に、気を\n取られてしまったみたい……。"
10133-510 = "……少し、休ませてちょうだい。"
10133-520 = "暑さで、思考があまり……。"
10133-530 = "……先生？\nどうしてそんな顔で……。"
10133-540 = "……あ！！"
10133-550 = "（わ、私は……なにを……！？）"
10133-560 = "こ、これは\nわざとじゃないの……！\nごめんなさい……！"
10133-570 = "わ、私はもう、\n大丈夫だから……！"
10133-60 = "「アバンギャルド君\nType.メイド」を\n作ったら、ここに\n置こうかしら。"
10133-70 = "できる限り……\nきれいに使うわ。"
10133-80 = "待っていたわ、先生。"
10133-90 = "効率的な業務サポートを\n提供してあげる。\n合理的でしょう？"
