[translation]
10136-10 = "ブルー、アーカイブ。"
10136-20 = "この状況下……私も、着替えないとね。\nどうかな、先生。似合ってる？"
10136-30 = "うう……カフェインが\n足りない。"
10136-40 = "次は先生と二人で\n来たいなぁ。"
10136-50 = "あそこで一休み……。"
10136-60 = "このバックパック、\nなんか熱い……。"
10136-70 = "平和だなぁ……。"
10136-80 = "スコープでこっちに来るの、\n見てたよ。\n今日もよろしくね。"
10136-90 = "ホットコーヒー、どう？\n私のはアイスだから、\n間違えないようにね。"
10136-100 = "暑くないのかって？\nうーん、どうだろう。\nまだ大丈夫、かな。"
10136-110 = "まあ暑くても、\n先生と一緒にいられるなら……。"
10136-120 = "いくらでも、\n我慢できるかも。"
10136-130 = "もっと当番に呼んでほしいな。"
10136-140 = "私の効率のためにも。"
10136-150 = "うーん、シャーレにいると\n勉強が捗るという\nわけじゃないんだけど……。"
10136-160 = "先生の隣に、いたいんだ。"
10136-170 = "はい先生、できたよ。"
10136-180 = "ふふ、\n早く終わった方じゃないかな？"
10136-190 = "こんなに有能な生徒……\n他にいないんじゃないかなぁ？\n先生はどう思う？"
10136-200 = "他人の気持ちを考えて\n話しなさいーって\nよく言うじゃない？"
10136-210 = "そんなの、\n非効率的だと思ってたんだ。"
10136-220 = "今は……ちょっとだけ、\n理由が分かってきたかも。"
10136-230 = "先生がどう感じるのか、\n何を考えてるのか……\n気になるから。"
10136-240 = "みんなと仲良くしなさいって"
10136-250 = "先生は私によく言うけど……"
10136-260 = "……やっぱ、面倒くさいかな。"
10136-270 = "先生さえいれば、十分だもん。"
10136-280 = "忘れてないよ。\n今日は先生の誕生日だよね。"
10136-290 = "周囲の安全確保は\nしているから――"
10136-300 = "よかったら、出掛けない？"
10136-310 = "二人きりで、ね。"
10136-320 = "私の誕生日……\n祝ってくれてありがとう。"
10136-330 = "うん？プレゼントに欲しいもの？"
10136-340 = "大丈夫、もうもらったから。"
10136-350 = "先生というプレゼントを、ね。"
10136-360 = "新年……。"
10136-370 = "前なら、\n365日のうちの一日としか\n思わなかったのに。"
10136-380 = "今はちょっと、違うかも。"
10136-390 = "ふふっ、\nあけましておめでとう、先生。"
10136-400 = "私、クリスマスは好きなんだ。"
10136-410 = "涼しいからね。"
10136-420 = "え？涼しくない\nクリスマスもある……？\nそれは嫌だなぁ。"
10136-430 = "ハロウィンのこと、手っ取り早く\nカロリーが摂れる日、\nくらいに思ってきたけど。"
10136-440 = "今回はちゃんと\n行事を楽しもうかな。"
10136-450 = "もちろん、イタズラもするし\nお菓子ももらうよ。\n遠慮はしないつもり。"
10136-470 = "ようこそ、先生。"
10136-480 = "なんだか不思議な空だよね。"
10136-490 = "私たちの知っている\n夜空と似ているようで……。"
10136-500 = "よく見ると、ぜんぜん違う。"
10136-510 = "今の私みたい。"
10136-520 = "今まであんまり\nこうやって見上げる\nことなかったんだけど……"
10136-530 = "最近、好きなんだ。"
10136-540 = "でもどうしてかな。"
10136-550 = "見上げる度に、\n先生の顔が浮かぶの。"
10136-560 = "ふふっ、なんでだろうね。"
10136-570 = "先生。"
10136-580 = "私、先生に会えて、\n本当によかった。"
10136-590 = "うん、本当に。\nそう、思ってるよ。"
10136-2600 = "こんな形の武器は初めて、\nだけど……作戦のためにも、\n早く使いこなせるようになるね。\n……先生のためにも。"
