[translation]
10131-10 = "ブルーアーカイブ、ですわ。"
10131-100 = "お会いできてとても\n嬉しく思っておりますわ。"
10131-110 = "あら、\n少々堅苦しかったでしょうか。"
10131-120 = "ええと……それでは……。"
10131-130 = "こんにちは、先生！"
10131-140 = "雪合戦はルール無用のもの。\nレッドウィンターでは\nよくするのですが……。"
10131-150 = "ただ一つだけ、\n石を入れることだけは\n禁じられているのです。"
10131-160 = "だって、\n当たったら痛いでしょう……？"
10131-170 = "え？「例の笑い方」を\n聞いてみたい……？\nえ、ええと……それは……。"
10131-180 = "う、うぅ……\nわ、わかりましたわ。\nそこまで仰るのなら……"
10131-190 = "オーホホホホ！"
10131-20 = "ごきげんよう、先生。レッドウィンター連邦学園、\n出版部所属の三善タカネと申します。\nよろしくお願い致しますわね。"
10131-200 = "……もう\n二度といたしませんわ！"
10131-210 = "先生、アイスホッケーは\nお好きですか？\n私は大好きですわ！"
10131-220 = "連携の取れたスケーティング、\nスティックの動き……。"
10131-230 = "ボディチェックに\nショルダータックル、\nそして乱闘……！"
10131-240 = "結果に納得のいかない\nオーディエンスによる\nクーデター……！"
10131-250 = "あっ……\n最後のは\n聞かなかったことに……。"
10131-260 = "批評とは……物語を切り取り、\nその感情を自身の言葉で\n残す行為ですわ。"
10131-2600 = "ペンは銃よりも強し、という格言を\nご存じですか？ええ、その通りです。\nふふっ……私の批評に心ない言葉を\n寄せた方々へ――思慮深い……\n「対話」をするといたしましょう。"
10131-270 = "そういう意味では、写真と\n似ているかもしれませんわね。"
10131-280 = "ふふ、\nですから……その。"
10131-290 = "先生のお写真を、\n撮らせていただいても\nよろしいでしょうか？"
10131-30 = "ふむ……\nここは、雰囲気が\n良いですわね。"
10131-300 = "時折、私を良家のお嬢様だと\n仰られる方もいますが……。"
10131-310 = "勘違いも甚だしいものです。"
10131-320 = "私は三善タカネ。\nそれ以上でも以下でも\nありませんわ！"
10131-330 = "え……？\n「承知いたしました。\n雪の国の姫君」……？"
10131-340 = "もう、先生……！"
10131-350 = "……？本日、ですか。\n何かありましたか？"
10131-360 = "何の変哲もない、\n365日のうちの1日かと。"
10131-370 = "ふふ。冗談ですわ、先生。"
10131-380 = "お誕生日、\nおめでとうございます。"
10131-390 = "それでは、これより……\n先生と先生が\n生まれた日についての――"
10131-40 = "Wi-Fi、ちゃんと\n繋がりますかしら？\n早く批評をアップロー\nドしなくては……。"
10131-400 = "私なりの評を\n述べさせていただきますわね。"
10131-410 = "本日、ですか？"
10131-420 = "何の変哲もない、\n365日のうちの1日かと。"
10131-430 = "ええ……\nそう……ですわね……。"
10131-440 = "うぅぅぅぅぅ……。"
10131-450 = "も、もうっ！\n先生もお人が悪いですわ！"
10131-460 = "私の誕生日……\n本気で忘れられたのかと\n思いましたわよ！？"
10131-470 = "誤解させた責任は、\nきっちりと\n取っていただけるのでしょうね？"
10131-480 = "明けましておめでとう\nございます、先生。"
10131-490 = "本年も\nよろしくお願いいたしますわ。"
10131-50 = "お茶をしながら物語を\n語らえる時間……素敵\nですわね。本当に。"
10131-500 = "物語の冒頭が肝心なように、\nお正月の過ごし方ひとつで――"
10131-510 = "その一年が\n決まってしまうものですわ。"
10131-520 = "ですから……\nおみかんを一つ、\nいかがでしょう？"
10131-530 = "レッドウィンターのお正月では、\nこたつにみかんと\n相場が決まっておりますから。"
10131-540 = "クリスマス……"
10131-550 = "サンタクロースの\n物語は様々な場所で\n語り継がれておりますわね。"
10131-560 = "レッドウィンターでは\n「雪のお嬢さん」という、\nサンタクロースの\nパートナーがいるのですわ。"
10131-570 = "ええ、トナカイとは\n別のパートナー……。"
10131-580 = "ですから今日は、\n私が先生の「雪のお嬢さん」に\nなって差し上げますわ。"
10131-590 = "ハロウィンの\n由来を考えれば……。"
10131-60 = "（この空間……\nどのように評を書けば\n良いのでしょう……）"
10131-600 = "ある意味、\nハロウィンこそ。"
10131-610 = "創作者にとって最大の\nインスピレーションを得られる\n日かもしれませんわね。"
10131-620 = "もっとも、\nそんなことはさておき。"
10131-630 = "私はお菓子をいただいても\n悪戯いたしますけれど？"
10131-640 = "えいっ！"
10131-660 = "先生、ご覧ください……\nオーロラですわ。"
10131-670 = "物語では、\n空の守護者の方々が――"
10131-680 = "宴を楽しむ様子が\nそう見えているのだと\n言われております。"
10131-690 = "いつも一緒にいられると\n思っていた方々とは"
10131-70 = "写真を\n撮っても良いの\nでしょうか……？"
10131-700 = "もう……\n二度と会えませんけれど。"
10131-710 = "世界はこれまで通り、\nどこまでも冷たく、\n遠いだけでしょう。"
10131-720 = "それでも私が\nオーロラを見上げ、\n希望を抱くのは――"
10131-730 = "この場所で、\n最後まで私と共にいてくださる"
10131-740 = "「パートナー」が\nいるからなのでしょうね。"
10131-750 = "ふふっ。ええ、\n今はそういう\n設定ですわ、「先生」。"
10131-760 = "お写真、\nよろしくお願いいたしますわね？"
10131-80 = "ごきげんよう、先生。\nふふっ……今日は良い日ですわ。"
10131-90 = "こうして先生と\nお会いできましたもの。"
