[translation]
10132-10 = "ブルー、アーカイブ。"
10132-20 = "大野ツクヨ、です！ドレスを着てはいますが……\n正真正銘、忍術研究部の一員、です……！"
10132-30 = "ううぅ……私、\nすごく見られて\nませんか……？"
10132-40 = "服に染みがついたら、\n大変、ですから……\n慎重に……。"
10132-50 = "うぅ……いっそ、\nあそこの家具に、\n紛れて……。"
10132-60 = "ドレスを\n着ているときは、\n歩き方も……\n気にしないと……。"
10132-70 = "（みなさん……\n個性的な格好を、\nされていますね）"
10132-80 = "こんにちは……。"
10132-90 = "今日の私は、先生だけの\nモデル、です……。"
10132-100 = "お待ちしてました、先生。"
10132-110 = "えっと……ドレス姿、\n驚かせてしまったら、\nごめん、なさい……。"
10132-120 = "一人前のモデル、よりも……\n一人前の忍者を、\n目指したい、です。"
10132-130 = "この服、もう少し近くで、\nご覧になりますか……？"
10132-140 = "よく見ると、\n作りがとても細かくて……\n不思議、なんです！"
10132-150 = "こ、これは……\n私のグラビアが、\nどうしてシャーレに……！"
10132-160 = "食事、ですか？"
10132-170 = "私は……\nサラダ以外、でしたら、\nなんでも……。"
10132-180 = "ファッションショーの\n会場にあったソファより……"
10132-190 = "ここの事務椅子のほうが、\n落ち着き、ます。"
10132-200 = "お誕生日、おめでとう\nございます、先生。"
10132-210 = "先生に、お見せしたくて……\n忍者ウォーキング、\n練習したんです……！\n見て、いただけますか……？"
10132-220 = "私の誕生日……ですか？"
10132-230 = "最近、忙しくて……\nすっかり、\n忘れてました……。"
10132-240 = "ありがとうございます！"
10132-250 = "あけまして、\nおめでとうございます！"
10132-260 = "新年の、お願い……"
10132-270 = "私の、好きな人たちが……\n笑っていてくれること、\nです。えへへ……。"
10132-280 = "先生……！\nもし、よろしければ……\nクリスマスの街を……\n一緒に、歩きませんか？"
10132-290 = "ウォーキングには、\n自信がついてきたん、\nです……！"
10132-300 = "ハロウィーンの仮装、\nにしても……"
10132-310 = "派手すぎ、ますよね？"
10132-320 = "え……もっとすごい\n格好の人がいるから、\n大丈夫……？"
10132-340 = "うぅっ……。"
10132-350 = "なんとか、フェンスは\n越えられました、けど……。"
10132-360 = "服が引っかかって……。"
10132-370 = "動けない、です……。"
10132-380 = "うぅ……ごめんなさい……。"
10132-390 = "私が、近道を\nしようとしたから……。"
10132-400 = "……あれ？\n先生は、どうやって\n向こう側に……？"
10132-410 = "えっ？\nフェンスの横に、\nくぐり戸……！？"
10132-420 = "ううぅ……\nそうとも知らず、\n私は……。"
10132-430 = "……先生……私の服、\n少し引っ張っていただいても、\n良いでしょうか？"
10132-2600 = "私……これからも精一杯、\n頑張り、ます。\nみなさんと、\n立派な忍者になる、ために……！"
