[translation]
10134-10 = "ブルー、アーカイブ！"
10134-100 = "先生、お待ちしていました！"
10134-110 = "大丈夫です！"
10134-120 = "アリスはいくらでも\n待てます！"
10134-130 = "このスーツの飛行方式、\n前にアリスがやったゲームと\n少し似ている気がします。"
10134-140 = "でも、現実はゲームと違って\n一人称視点なので、\nすっごくややこしいんです……！"
10134-150 = "アリスも、TPS視点で\n見てみたいです！"
10134-160 = "先生？\nどうかされましたか？"
10134-170 = "あっ！見ていたんですね？"
10134-180 = "そうです、\nさっきアリスは\n窓から入りました！"
10134-190 = "このモードのアリスは、\n光属性と飛行属性を\n持っているんです！"
10134-20 = "アリス、行きます！"
10134-200 = "……え？\n危ないから普通にドアから\n入ってきてほしい？"
10134-210 = "この装備は不安定なので、\n定期的なメンテナンスが\n必要です。"
10134-220 = "でも安心してください！"
10134-230 = "ヒマリ先輩とリオ先輩、\nそれにウタハ先輩も……"
10134-240 = "いつでも持ってきていいって\n言ってくれましたから！"
10134-250 = "ただ……どなたかに頼むと、\n他の二人の機嫌が\n悪くなっちゃうんです……。"
10134-260 = "アリスは、\nどうしたら……"
10134-2600 = "光の剣は、いつだって\nアリスに進む道を示してくれました。\nそう……まるで、\n先生みたいに！"
10134-270 = "うぅぅぅっ……！"
10134-280 = "うぅぅ……羽が大きくて、\nあちこちに\nぶつかってしまいます。"
10134-290 = "羽がある人って、\n普段どうしてるんでしょう？"
10134-30 = "これ……ケイに\nそっくりですね！"
10134-300 = "アリスの知ってる中で、\n一番羽が大きい人は……。"
10134-310 = "あっ！後で風紀委員長に\n聞いてみますね！"
10134-320 = "ケイに「ゲームばっかり\nやってると、そのうち\nモモイみたいになる」って\n言われました……"
10134-330 = "どういう意味でしょう？"
10134-340 = "アリスはモモイが\n大好きなので……\nモモイみたいになりたいです！"
10134-350 = "……せ、先生まで\nどうしてそんな反応を？\nケイと同じです！"
10134-360 = "先生、お誕生日\nおめでとうございます！"
10134-370 = "先生の誕生日って、\n先生が生まれた日\nなんですよね。"
10134-380 = "まだ先生がいなかった時間が\n存在したなんて……\nなんだか不思議です。"
10134-390 = "えへへ、先生、\n覚えてますか？"
10134-40 = "アリス、ちょっとだけ\n眠くなって\nきました……。"
10134-400 = "今日は、アリスと先生が……\nアリスがみんなと\n出会った日です！"
10134-410 = "アリスは、\n自分がいつ生まれたのか\n覚えていませんが……。"
10134-420 = "でも今日は、\nきっとアリスの\n誕生日です！"
10134-430 = "先生、\nあけまして\nおめでとうございます！"
10134-440 = "残念ですが……\nアリスはこの後の旅には、\nご一緒できません。"
10134-450 = "今年はオンラインゲームで\n仲間たちと初日の出を\n見る約束があるので、"
10134-460 = "今日は徹夜で\nゲームを……。"
10134-470 = "えっ……？\nこれから外出、ですか？"
10134-480 = "うぅぅっ！\nそ、そんなぁ……！"
10134-490 = "ぱんぱかぱーん！"
10134-50 = "ここはＰＫ禁止\nエリアですよ！"
10134-500 = "今日のアリスは\nサンタさんに\nジョブチェンジします！"
10134-510 = "忙しいサンタさんの代わりに、\n空を飛びながら、\nみんなにプレゼントを\n配るんです！"
10134-520 = "あっ、でも先生と離れ離れに\nなっちゃいます……\nうーん。"
10134-530 = "……あっ！\n先生はトナカイのルドルフを\nお願いします！"
10134-540 = "うぁー！\n先生、助けてください！"
10134-550 = "人がいっぱい来て、\n写真撮らせてくださいって\n言われてます！"
10134-560 = "アリス、別に仮装してる\nわけじゃないのに！"
10134-580 = "えへへ。\n先生、驚きましたか？"
10134-590 = "先生と一緒に、\nこの夜空を見たくて……\n呼んだんです。"
10134-60 = "（スキャン完了。\n敵性反応……無し）"
10134-600 = "とても……\n綺麗ですね。"
10134-610 = "アリスの世界にも、\nまだ行ったことのない\n世界にも……"
10134-620 = "きっとこんな綺麗なものが\nたくさんあると思うんです。"
10134-630 = "でも……不思議です。"
10134-640 = "世界って、\nこんなに綺麗なのに……\nどうして人は争うんでしょう？"
10134-650 = "あの星空みたいに、この世界は、\nみんなで分け合っても\n大丈夫なくらい美しいもので\nあふれているのに……。"
10134-660 = "……やっぱり、アリスには\nまだわかりません。"
10134-70 = "充電器はどこに\nあるんでしょう？"
10134-80 = "えへへ、先生が来ること、\nアリスは知っていました。"
10134-90 = "アリスの自動迎撃システムが、\n反応していましたから。"
