[translation]
16018-10 = "ブルーアーカイブ！"
16018-20 = "ジャブジャブヘルメット団のリーダー、\n河駒風ラブよ。ちょ、先生！！\n近いってば！離れて！！"
16018-30 = "ヘルメットをかける\nとこってないかしら？"
16018-40 = "どこかで……\n見たことが\nあるような……？"
16018-50 = "（話しかけても\nいいのかしら……？）"
16018-60 = "ここ、なかなか\nいいじゃない。\n雨もしのげるし。"
16018-70 = "ヘルメット団の\nみんなも連れてきて\nあげれば\nよかったわね……。"
16018-80 = "あら、先生。やっほー。"
16018-90 = "今日は何をするのかしら？野球？"
16018-100 = "いらっしゃい、先生。"
16018-110 = "なんか面白い話とか、\nないの？"
16018-120 = "ヘルメットに\n興味はないかしら？"
16018-130 = "先生なら、\nきっと似合うと思うわよ？"
16018-140 = "ヘルメットって\nかっこいい上に実用的なのよ？"
16018-150 = "頭を守ってくれて\n見た目も良いの。最高でしょ？"
16018-160 = "（……シャーレに来る人、\nほとんどヘルメット\n被ってないのよね）"
16018-170 = "（見てるうちまで\nそわそわしてきちゃう……\nなんだか落ち着かないわ！）"
16018-180 = "先生って……\nそんなに忙しいの？"
16018-190 = "いつも色んなところに\n駆けつけてくるから、\n暇人なのかと思ってたわ。"
16018-200 = "ふふん、ふふーん、\nんふふふーん……。"
16018-210 = "んふーん、\nヘルメットさいっこー！！"
16018-220 = "あら、今日って\n先生の誕生日じゃない？"
16018-230 = "お誕生日おめでとう！\n美味しいもの、\nいっぱい食べなさいよね！"
16018-240 = "なんか……\n昨日からうちの子たちが\nずっとコソコソしてるのよね。"
16018-250 = "真面目な話があるから\n来てくれって……\n何をするつもりなのかしら。"
16018-260 = "新しい年がやってきたわね！\n今年もみんなが健康でいて、\nいっぱい稼げますように！"
16018-270 = "メリークリスマス、先生！"
16018-280 = "まぁ、悪い子にはサンタなんて\nこないんだけど……"
16018-290 = "気分くらいは\n楽しんでもいいじゃない？"
16018-300 = "はぁっはぁっ……"
16018-310 = "つ、疲れたわ……。"
16018-320 = "お菓子くれなきゃ\nイタズラするって言いながら\n来るのよ、あいつら……。"
16018-330 = "でもうち、\nお菓子なんか持ってないし……"
16018-340 = "そうしたら、\nイタズラばっかして！もう！！"
16018-360 = "いち、に、さん、し、ご、ろく。\nよしっ！"
16018-370 = "六羽とも\nちゃんと全員いるわね！"
16018-380 = "ママの言うことはちゃんと\n聞いときなさいよ、あんたたち。"
16018-390 = "母アヒルも\nもう大丈夫そうね。"
16018-400 = "これで一件落着、っと！"
16018-410 = "な、ななな……\nなに言ってんのよ！！"
16018-420 = "先生、\nそれってちょっと失礼じゃない？"
16018-430 = "え？……あっ！？\nえっと……"
16018-440 = "あ、ああっ！\nそ、そういうことね！？"
16018-450 = "も、もちろん！リーダーだもの！\nこの程度できないと\nダメじゃない！"
16018-460 = "（先生ってば、\nホントに言い間違えただけ？\nそれともワザと……？）"
16018-470 = "（どっちにしろ腹立つわね！\nわざとだったら\nもっとムカつくし！！）"
16018-480 = "（まさか、わざとだったり……\nするのかしら……？）"
16018-2600 = "あら！これほしかったのよ！\nありがとね、先生♪"
