[translation]
16019-10 = "ブルー、アーカイブ。"
16019-100 = "はっ！？"
16019-110 = "先生、いらしたのですね。"
16019-120 = "……違います。\n退屈のあまり居眠りを\nしていたわけではありません。"
16019-130 = "私を起こそうと、\n先生が近くに\n来てくださるかも……。"
16019-140 = "なんて下心など、\nありませんので。"
16019-150 = "先生、\nお待ちしておりました。"
16019-160 = "それでは、\n今日の仕事を始めましょう。"
16019-170 = "片づけよし、\nタスクリストよし、\nコーヒーよし、お菓子よし。"
16019-180 = "すべて整えてあります。"
16019-190 = "はい、迅速に\n褒めてください。"
16019-20 = "パーフェクトメイド、パーフェクトリコン。\n飛鳥馬トキです。\n大船に乗ったつもりでお任せください。"
16019-200 = "趣味について\n真剣に考えたところ――"
16019-210 = "楽しいと思うことをすれば良い、\nという結論に至りました。"
16019-220 = "ですので、先生。"
16019-230 = "一緒にマンガを読みませんか？\nそれともゲーム？"
16019-240 = "配信を観るのでもいいですね。"
16019-250 = "装備を一新し、\n軽量化と高速化を実現しました。"
16019-260 = "ですが……\n以前の重量感や火力が\n恋しくなることもあります。"
16019-2600 = "武器の変更には、思い切った決断が\n求められます。朝食のメニューを、\nトーストからパンケーキに変えるほどの\n一大事です。ですが、先生からいただいた\nものなら……話は変わってきます。"
16019-270 = "なぜ人は、\n重ね合わせの状態に\nなれないのでしょう。"
16019-280 = "……とても残念です。"
16019-290 = "先日見かけた\n配信者のライブで、"
16019-30 = "休息は重要です。\n週休4日くらいが\n適切かと。"
16019-300 = "無限弾倉と二丁拳銃について\nコメントを投稿したところ――"
16019-310 = "山海経高級中学校の玄龍門から\n「いいね」を押されました。"
16019-320 = "何故なのでしょうか……？"
16019-330 = "ふと、世界の終わりについて\n考えることがあります。"
16019-340 = "特に意味はありません。"
16019-350 = "ただ、もしもその日が訪れたら、\n何をするだろうか、と。"
16019-360 = "先生ならどうされますか？"
16019-370 = "私は……何をするか、\n決めています。"
16019-380 = "……でも、教えません。"
16019-390 = "秘密の一つや二つ、\nあったほうが良いと\n思いますから。"
16019-40 = "身体を\n休められるところは\nないでしょうか。"
16019-400 = "偵察において重要なことは\nいろいろありますが……。"
16019-410 = "敵を知り、\n己を知ってこそ、"
16019-420 = "作戦の成功は保証されます。"
16019-430 = "つまり私たちは、\n互いのことを深く\n理解しあう必要があるのです。"
16019-440 = "……意味が分からない？"
16019-450 = "私が分かっていますから、\n問題ありません。"
16019-460 = "知っています。"
16019-470 = "今日は、先生が初めて\nこの世の偵察に成功した、\n記念すべき日。"
16019-480 = "偵察記録が\n残っているようでしたら、\n私にもぜひ見せてください。"
16019-490 = "本日の主役として――"
16019-50 = "カフェインと糖分は\n欠かせません。"
16019-500 = "この日に相応しい\nプレゼントを要求します。"
16019-510 = "それは……。"
16019-520 = "愛とご褒美です。"
16019-530 = "新年、明けまして\nおめでとうございます。"
16019-540 = "私の人生の新たな1年が、\nここからスタートします。"
16019-550 = "それでは先生。"
16019-560 = "一緒に人生設計を\nしていきましょう。"
16019-570 = "先生が生徒に\nクリスマスプレゼントを\n贈る……。"
16019-580 = "ですので、\n私からもプレゼントを\nご用意しました。"
16019-590 = "はい。プレゼントは私です。"
16019-60 = "このカフェの\nレシピは……\n及第点です。"
16019-600 = "……冗談ではありませんよ。\nはい。"
16019-610 = "キャンディーやお菓子は、\n優れた戦闘糧食に\nなると聞きました。"
16019-620 = "つまり、ハロウィーンでは\n最も理にかなった食品と\n言えます。"
16019-630 = "ハロウィーンはその状況に\n該当するのか、ですか？"
16019-640 = "それは……。"
16019-650 = "私がそう思ったから、です。"
16019-670 = "綺麗な朝焼けですね。"
16019-680 = "ここでは毎日、\nこの景色が観測できます。"
16019-690 = "といっても、\nここに来てからの数日分しか\n記録はないので……。"
16019-70 = "次回の任務のために\n休憩して\nおきましょう。"
16019-700 = "毎日ではないのかも\nしれませんが。"
16019-710 = "はい。"
16019-720 = "でも、ここからだと全く\n違った色に感じられるんです。"
16019-730 = "空も……\n橙色に輝く大地も……。"
16019-740 = "私は、先生とこうして\n景色を共有する時間が\n好きです。"
16019-750 = "心が動いたものを\nこうして伝えられる\nこのひと時が……。"
16019-760 = "この一瞬は、\nいまこの時間しか\n存在しません。"
16019-770 = "そして、\n二度と戻ってこない。"
16019-780 = "先生。"
16019-790 = "もしも今、「最後」の時が\n訪れたら――"
16019-80 = "うぅん……"
16019-800 = "私は、先生のそばで\nその瞬間を共にする……。"
16019-810 = "「最後」の一人に\nなれますか？"
16019-90 = "んん……"
