[translation]
20051-10 = "ブルーアーカイブ！！"
20051-100 = "自警団の宇沢レイサのことは、\n忘れてください……。"
20051-110 = "今日の私は……\nシュプリームマジカル自警団、\n宇沢レイサですからっ！"
20051-120 = "先生の呼び出しに応え……！"
20051-130 = "テルミットピンク、\nここに参上！です！"
20051-140 = "自警団も、制服を作るのは\nどうでしょう！"
20051-150 = "せっかくならこういう、\nカッコイイのがいいです！"
20051-160 = "ボルトフォワード！\nテルミットピンク……！"
20051-170 = "あ！こんにちは先生！\nちょっとセリフの\n練習をしていまして……。"
20051-180 = "先生は「まほリバ」\n3期4話の名台詞をご\n存知ですか？"
20051-190 = "「友情と火力は熱ければ\n熱いほど良い」、です！\n良い言葉ですよね！"
20051-20 = "呼ばれて飛び出て！再び参りました！\n魔法少女、マジカル宇沢レイサ、登場です！"
20051-200 = "ちょっと小腹が\n空きましたね……そうだ！"
20051-210 = "パンを買ってこようと\n思うんですが、\n先生も食べますか？"
20051-220 = "先生、お誕生日おめでとう\nございます！"
20051-230 = "私に魔法が使えたら、\n先生に祝福魔法を\nかけてあげられたんですけど！\nえへへ。"
20051-240 = "誕生日？\n誰のですか？\n……ああっ！私でした！"
20051-250 = "祝ってくださり\nありがとうございます！\nえへへ……。"
20051-260 = "先生、明けまして\nおめでとうございます！\n今年も、正義が満ちあふれる\n一年となりますように！"
20051-2600 = "先生は、いつも優しく\nしてくださるんですね……。\nこうして一緒にいると……\n私、最強になれる気がしますっ……！"
20051-270 = "マジカル～クリスマ～ス！"
20051-280 = "わっ！マジカルじゃなくて\nメリーでしたっ！"
20051-290 = "トリックオアマジック！\nハッピーハロウィーン、です！"
20051-30 = "きょ、今日も……\n人が多い……。"
20051-300 = "魔女の仮装？いえいえ！\nこれは魔法少女です！"
20051-310 = "魔女と魔法少女は\n全然違うんですよ？"
20051-330 = "セーフッ！"
20051-340 = "ふふ……凧の平和は\n守られました！"
20051-350 = "水に落ちる寸前に！\nこうやって\n捕まえられたのですから！"
20051-360 = "みんなのためでしたら、\n自警団は迷いません！"
20051-370 = "火の中だろうと、\n水の中だろうと！\nどこだって飛び込んで\nみせますから！"
20051-380 = "にへへ……っ！"
20051-390 = "ヒーローの衣装というのは――"
20051-40 = "な、なるべく、\n普段どおりに……。"
20051-400 = "ヒーローとしての\n仕事をするときにこそ\n輝くものっ！"
20051-410 = "あと、これは\n洗濯機オッケーなので\n大丈夫です！"
20051-420 = "それに……先生に、\n教わりましたから。"
20051-430 = "迷わない者こそ――みんなを\n守ることができる、と！\nえへへっ！"
20051-440 = "へへ、え、へえっ……。\nへくしょん！！"
20051-450 = "ううぅ……。"
20051-50 = "（あっ！今の……\n知ってる話だ！）"
20051-60 = "みなさん、\n楽しそうですね！"
20051-70 = "（ああっ……\n席、取られてる……）"
20051-80 = "ふふふ……\n遅かったですね、先生。\nいえいえ、\n気を落とさないでください！"
20051-90 = "正義の味方は、誰よりも早く\n駆けつけるものですから！"
