[translation]
20055-10 = "ブルー……すぅ……！アーカイブ！ "
20055-100 = "お、お待ちしてました、\n先生……！ "
20055-110 = "早く出撃……"
20055-120 = "ち、ちがうっ。\n当番のお仕事を、\n始めましょう……！"
20055-130 = "このスーツ、思ったより\n楽ではあるんですが……"
20055-140 = "それ以上に……恥ずかしい、\nです……。"
20055-150 = "スーツの感触、なんだか\n不思議ですよね。\n弾も弾いてしまいそうです。"
20055-160 = "全身を覆っているはずなのに……\nなんだか落ち着かなくて……\nうう……。"
20055-170 = "このスーツ……パソコンとも\n連動できるんです……。"
20055-180 = "当番の時……\n役に立つでしょうか？ "
20055-190 = "あ、暑いですか……？"
20055-20 = "ミレニアムサイエンススクール……\nゲーム開発部の花岡ユズ、です……。\nこ、こんな格好ですが……\nよろしく、お願いします……。"
20055-200 = "こ、このスーツ……\n表面が冷たくて、\n気持ちいいですよ……？"
20055-210 = "お誕生日、\nおめでとうございます……！"
20055-220 = "あ、あの、\n誕生日プレゼントに……"
20055-230 = "ソフトを、\n用意してみたのですが……。"
20055-240 = "ど、どうでしょう……？"
20055-250 = "あ、ありがとうございます、\n先生……"
20055-260 = "わたしのこと、\n忘れないでくれて……。 "
20055-2600 = "練習は本番のように。\n本番はゲームのように……！\nわたし、最善を尽くします……！ "
20055-270 = "いろんなことがありましたが、\nあっという間に一年が\n過ぎましたね。"
20055-280 = "……あけまして\nおめでとうございます、\n先生。"
20055-290 = "さ、サンタ服じゃないですが……\nあ、赤いですし……に、\n似たような、ものですよね。"
20055-30 = "（平和な日常……\n今はその大切さが、\nよく分かります） "
20055-300 = "め、メリークリスマスです、\n先生！"
20055-310 = "わ、わたしよりすごい格好の\n人たちが、たくさん……！ "
20055-320 = "あっ、い、いや、\nわたしも着たかったとかじゃ、\nなくて……！ "
20055-340 = "見てください、先生。"
20055-350 = "わたしが守り抜いた世界です。"
20055-360 = "……もちろん、分かっています。"
20055-370 = "この光景を見たのは、\nわたしだけじゃないって。"
20055-380 = "大会の時、\nこんなことを仰いましたよね。"
20055-390 = "今この瞬間が、\nゲームが。\nわたしたちの現実だって。"
20055-40 = "ソファ……\n突然発射したり、\nしませんよね……？"
20055-400 = "だから、たとえエンディングの\n決まった世界だとしても……。"
20055-410 = "この世界のみんなが、"
20055-420 = "同じシナリオを\n歩むとしても……。"
20055-430 = "わたしがした選択、\nこの感情は……。"
20055-440 = "間違いなく、本物なんです。"
20055-50 = "あたたかくて、\nいい匂い……\nいいですね。\nえへへっ。"
20055-60 = "ロッカーには……\nしばらく、入りたく\nありません……うぅ。"
20055-70 = "やっぱり、これ……\n少し派手過ぎ\nませんか……？\nうぅぅ……。"
20055-80 = "ふえぇ……！\nこ、この格好は、その……。"
20055-90 = "……お、おかえりなさい、\n先生。"
