[translation]
20050-10 = "ブルー！アー、カイ、ブッ！"
20050-100 = "部活？大好きだよ！\nみんなを幸せにできるもん！"
20050-110 = "岩や粘土を見るとさ、\n中に入ってる子を"
20050-120 = "形にしてあげなきゃ！\nってなるんだ。\n先生はどう？"
20050-130 = "見ただけじゃ大きさ\nわかんないなぁ……"
20050-140 = "先生、ギューってしてもいい？"
20050-150 = "シャーレって居心地いいね～\n大理石に触ってるときみたい！"
20050-160 = "せ～んせ♪\n仕事はそのへんにして、\nボクと遊んでよ～！"
20050-170 = "先生、生まれてきてくれて\nありがとね！"
20050-180 = "ボク、先生がいてくれて、\nホント幸せなんだ！"
20050-190 = "ねね！知ってた？\n今日はボクの誕生日！"
20050-20 = "ボク、ワイルドハント芸術学院の薄葉リツ！\nよろしくねっ！"
20050-200 = "今日はず～っと、\n先生と遊びたいな～！"
20050-210 = "ハッピーニューイヤー先生！\n鐘叩くやつ見に行こ！！"
20050-220 = "……え？もう終わってるの？"
20050-230 = "先生！雪！！お外が真っ白だよ！\nせっかくだし、\n一緒に雪で彫刻しない？"
20050-240 = "先生！早く早く～！"
20050-250 = "今日はキャンディーと\nチョコの争奪戦だよ！"
20050-2600 = "わぁ！これ、ずーっと欲しかったんだ！\nありがとね、先生！うれしい！"
20050-270 = "あー……"
20050-280 = "すずしー……"
20050-290 = "ここ、すごくない？"
20050-30 = "あのへんに\n作品置けるかな～？"
20050-300 = "むかーしからある\n地下貯水槽らしいんだけど……"
20050-310 = "おっきい穴を掘って、\nいっぱい柱を立てて……"
20050-320 = "一つ一つに\n彫刻されてるんだ……"
20050-330 = "……きれいでしょ？"
20050-340 = "どうしても先生に\n見せたかったんだ。"
20050-350 = "ね、こっちきて。"
20050-360 = "ボクと同じ景色、見ようよ。"
20050-40 = "ここ、もうちょっと\n風通しよく\nならないかな～？\nあ！……あそこ、\n穴あけられるかも！"
20050-50 = "コーヒーの\nいい匂い……\n表現できないかなぁ。"
20050-60 = "うーん、次の輸入品は～っと……"
20050-70 = "ここのケーキを持って\n帰ったら……\nきっと、学院のみんなも\n喜んでくれるよね！"
20050-80 = "やっほ～先生、何してた～？"
20050-90 = "いい天気だね！\n遊びにいこうよ先生！"
