[translation]
20053-10 = "ブルゥ～！こほん……アーカイブ？"
20053-20 = "先生殿～調子はどう？\n今回は潜入任務だよ！よろしくね！"
20053-30 = "ふふ……私に気が\nつく人がいたら\nどうしよう……？"
20053-40 = "このドレス……\nここで着るのは\nやり過ぎ……？"
20053-50 = "（ドレスと、コーヒー\n……あっ！このネタ\n使えるかも……！）"
20053-60 = "いつか絶対……！\nここでファン\nミーティングを……！"
20053-70 = "（よし！とりあえず……\n人目につかない\n場所はどこだろ？）"
20053-80 = "先生殿、待ってたよ～！"
20053-90 = "ツクヨがヘアアイロンを\n貸してくれたんだけど……\n使い方知ってる？"
20053-100 = "お待ちしておりました、先生。"
20053-110 = "……違う。\nいくらドレスだからって\nこれは違う気がする。"
20053-120 = "綺麗な服であるほど、\n不便なものなのかなぁ……。"
20053-130 = "この服……動きにくいけど、\n道具を隠せる場所が\n多いのは良いよね。"
20053-140 = "忍者とは、\nその心に宿るもの……！"
20053-150 = "だからドレスを着ていても、\n忍者は忍者なのだっ！"
20053-160 = "ラーメン、食べたいけど……\nこの格好じゃなぁ……。"
20053-170 = "これがミチル流ドレスコード～！\nふっふっふ！"
20053-180 = "ふっふっふ……\n今日は先生殿のために、\nおめかししてきたよ！"
20053-190 = "……ん？私が\nプレゼントなのかって？ "
20053-200 = "ちっ、違ぁう！\nいや、別にそれでも\nいいけど……"
20053-210 = "あっ、そうじゃなくて！\nうにゃああっ……！！"
20053-220 = "あ、先生殿。今日は\n私の誕生日配信があるんだ。"
20053-230 = "誕生日プレゼントってことで……\n先生殿も、スペシャル\nゲストとして出演してくれない？"
20053-240 = "えっ、いいの！？\nじゃあ早く！こっち座って、\nカメラ見て！"
20053-250 = "あけましておめでとう～先生殿♪"
20053-260 = "やっぱお正月と\n言ったら時代劇だよね！"
20053-270 = "というわけで……時代劇の\nリレー上映会、いっしょにどう？"
20053-280 = "先生殿、知ってた！？"
20053-290 = "サンタの正体は……\n変装した忍者なんだって……！"
20053-300 = "ん？このまきびし？"
20053-310 = "もちろん、キャンディを狙う\n者たちへの罠を――"
20053-320 = "……じょ、冗談だよ。\nまきびしの形の\nキャンディだってば。"
20053-340 = "中身は……指輪、だね！？"
20053-350 = "手裏剣の飾りがついてて、\n良い感じ……じゃん！？"
20053-360 = "……え？先生殿、つけるの……？"
20053-370 = "あ、いや、いいんだけど……。"
20053-380 = "（あれ……？指輪を、\n相手に渡す……？）"
20053-390 = "（これって……告白、\nみたいな――！？）"
20053-400 = "ちょっ、ちょっと待って先生殿！"
20053-410 = "別に狙ってた\nわけじゃなくて……！\nでも、えっと……！"
20053-420 = "うぅ……うああぁ～～っ！！"
20053-2600 = "いいの……？私に、こんな……！\nでも、先生殿の判断なら！\nうん！ありがとう！"
