[translation]
20052-10 = "ブルー、アーカイブ、ムフフ。"
20052-20 = "印刷、製本、管理、流通――\n本に関してのご相談はレッドウィンター出版部部長、\n荒槇ヤクモまでお気軽にどうぞ。ムフフ。"
20052-30 = "さて……\n新たな販路は……。"
20052-40 = "ここ、暖かくて\n落ち着き\nますねぇ……。"
20052-50 = "あそこに売り場を\n作ったら……\nムフフ。"
20052-60 = "最近の文学は、\nプラットフォーム\nビジネスのような\nものでしてぇ。"
20052-70 = "さて、本日の\n売上は……？"
20052-80 = "いやあ～、\nいついらっしゃるのかと……"
20052-90 = "首を長くしてお待ちして\nおりましたよ、先生。"
20052-100 = "ではさっそく、\n出版部とシャーレの\n新規合同事業について――"
20052-110 = "じっくり、\n話し合いましょうか。\nムフフ。"
20052-120 = "お待ちして\nおりましたよぉ、先生。"
20052-130 = "ここで待っている間、\nシャーレの本棚に\n必要な良書を――"
20052-140 = "出版部部長として\n厳選し、リストに\nまとめておきました。"
20052-150 = "……お申し付けいただければ、\nすぐにでもお持ちしますよ。\nムフフ。"
20052-160 = "事業計画書の作成は、\n私の趣味みたいな\nものです、ええ。"
20052-170 = "変わってる？\nまぁ、そうでしょうねぇ。"
20052-180 = "可能性を考えるのが\n好きでして。"
20052-190 = "思いつくままに綴るのは、\n存外楽しいものですよぉ？"
20052-200 = "……それは\n計画書じゃなくネタ帳？"
20052-210 = "何を仰るんですか！\nネタ帳ではありませんよぉ？"
20052-220 = "どこがって……\nええと、ですから……。"
20052-230 = "まったく、事務局との\n予算交渉は……\n本当に骨が折れます。"
20052-240 = "ですが……最終的に\n予算を引き出せれば\n良いのです。"
20052-250 = "事務局が喉から手が出るほど\n欲しがるような魅力的な\n事業を提案できれば……"
20052-260 = "部費として確保できなかった\nお金以上の予算を\n得ることができる\nわけです……！ムフフ。"
20052-270 = "シャーレに来るまで、\n色々な交通手段を\n利用したのですが……"
20052-280 = "この辺の鉄道施設は\n本当よくできてて……\n羨ましいですねぇ……"
20052-290 = "……羨ましいのは、\nそれだけでは\nないのですが。"
20052-300 = "近頃、出版業界は\nちょ～っと\n厳しくてですねぇ。"
20052-310 = "文字が動画に\n負けてしまう傾向が\n続いてるんですよ～"
20052-320 = "そこで、我々は\n気づいたのです。"
20052-330 = "出版部が映像を\n手掛けてしまえば、\n一石二鳥だと！"
20052-340 = "はぁ……建前抜きで、\nシャーレはいいところですねぇ。"
20052-350 = "ここに転校\nしたいくらいですよぉ。"
20052-360 = "暖かいし、\n施設は揃ってるし、\n事業のチャンスは多いし……\n先生もいるし。"
20052-370 = "……シャーレは\n学校じゃないから\n転校できない？"
20052-380 = "……こうしてまた、\n現実の厳しさに\n打ちひしがれて\nしまうのです。"
20052-390 = "おやおや、本日の\n主役じゃありませんか。"
20052-400 = "お誕生日おめでとう\nございます先生。\n私から、ささやかな\nプレゼントを一つ。"
20052-410 = "はい、図書券です。\n……ご利用、お待ちして\nおりますよぉ。ムフフ。"
20052-420 = "本日は5月18日ですよぉ～？"
20052-430 = "忘れてませんか～？\n何か私に言うこと\nありませんかぁ？"
20052-440 = "さすが先生！\n私の誕生日をよくご存じで！"
20052-450 = "年が明けましたね、\nうーん……。"
20052-460 = "世の事業の多くは、\n年始商戦といって\n何かしらイベントを\n企画するのですが――"
20052-470 = "これって、\nジレンマの一つでも\nあるんですよね……。"
20052-480 = "みんながやるから大して\n経済効果は見込めないけど、"
20052-490 = "やらないでいると、\nそれはそれで遅れを\n取ってしまう、という……。"
20052-500 = "クリスマス前後は\n書き入れ時、\nとよく言われますねぇ。"
20052-510 = "しかしこのシーズン\n何を出しても\n売れるだろうという――"
20052-520 = "そんな安易で\n軽率で安直な企画が、\n事業をダメにするのです。"
20052-530 = "今日はハロウィーンですか。"
20052-540 = "これは先生と\n知り合ってから\n湧いた疑問なのですが……"
20052-550 = "先生から飴をもらうことと、\n先生にイタズラをする\n権利を得ること。"
20052-560 = "どっちが\nお得なんですかねぇ～？"
20052-580 = "おお……ふかふかですねぇ。"
20052-590 = "意外と良い……\nかもしれません。"
20052-600 = "……と思いましたが、\n寒いですねやっぱ。"
20052-610 = "はくしょん！"
20052-620 = "撮れました？\nでは次は先生の番です。"
20052-630 = "あれ？\n……まさか私にだけ\nやらせるつもりですかぁ？"
20052-640 = "やれやれ、それは\nあまりにも安易だと\n思いますけどねぇ？先生？"
20052-650 = "レッドウィンターの\n冬将軍は、みんなに\n平等ですよぉ？ムフフ。"
20052-2600 = "馬鹿と鋏は使いよう……。\nこれからは契約を「きちんと」守らせることが\nできそうですねぇ……ムフフ。"
