[translation]
9009000-610 = "ハッピー・ハロウィーン！\nお、お菓子は無いのですが……\n先生のために、特別なプレゼントをご用意しましたよ！"
9009000-620 = "トリック・オア・トリート！\nいたずらしちゃいますよ〜！\nあ、その前にこちら、先生へのプレゼントです！"
9009000-630 = "メリークリスマス！\nプレゼントもちゃーんと\n用意しましたよ！"
9009000-640 = "クリスマスですね、先生！\nこれはアロナからの特別な\nプレゼントです！"
9009000-1290 = "5thアニバーサリーです！\n先生、いつも\nありがとうございます！"
9009000-1300 = "これからもずっと一緒ですよ！"
9009000-1310 = "おかえりなさい、先生！\n出張お疲れ様でした！"
9009000-1320 = "久々のシャーレでの業務ですね。\nアロナがサポートします！"
9009000-1330 = "先生！ イベント開催中ですよ！行ってみましょう！"
9009000-1340 = "どんなイベントなんでしょうね〜？"
9009000-1350 = "ワクワクしますね……！"
9009000-1360 = "どんなものでも大丈夫です！全力でお手伝いします！"
9009000-1370 = "イベントが終わったら……イチゴミルクがほしいです！"
