[translation]
10015-10 = "今日の任務は、\nなんでしょう？"
10015-20 = "あっ、お片づけは、\nアリスの\n担当でしたね……。"
10015-30 = "アーマーがなくても……。"
10015-40 = "たとえ、\n光の剣を失っても……。"
10015-50 = "それでも、\nアリスはアリスです。"
10015-60 = "みんなが\nいてくれるなら……\nそして。"
10015-70 = "先生がいてくれるなら！"
10015-220 = "先生！\nミッションです、ミッション！"
10015-230 = "はい！アリスは、\nいつも変わらない先生が、\n大好きです！"
10015-240 = "ぱんぱかぱーん！"
10015-250 = "先生が報酬を獲得しました！"
10015-260 = "すごいです、先生！"
10015-270 = "この調子で一歩ずつ、\n進んでいきましょう！"
