[translation]
10132-180 = "先生……！？\nこのドレス……やっぱり、\n変、でしょうか……？"
10132-190 = "おかえりなさい、\n先生……。"
10132-200 = "ええと、\nこの格好は、\nその……。"
10132-210 = "一体……何が\n起きてるんですか……？"
10132-220 = "ステージの上は……\n不思議、です。"
10132-230 = "たくさんの方に、\n見られてる、のに……"
10132-240 = "孤独、だと思う瞬間が、\nあります……。"
10132-250 = "みなさん……！私……\n帰って、きました……！"
10132-260 = "私は……\nこの衣装に、相応しい\nのでしょうか……。"
10132-270 = "やっぱり、\n目立ってます、よね……？"
10132-280 = "うぅ……\n私、忍者なのに……。"
10132-290 = "き、き、ききキレイ、\nですか……！？"
10132-300 = "ひゃうううぅ……。"
10132-310 = "この服も、"
10132-320 = "変装の術だと、\n思えば……。"
10132-590 = "やることを、\nまとめて、みました……。"
10132-600 = "どれも簡単ではない、\nですが……"
10132-610 = "先生なら、きっと……！"
10132-620 = "えっと……\n私のまとめたものに……\n問題でも、ありましたか……？"
10132-630 = "先生……？\nどうか、しましたか……？"
10132-640 = "さすが、です……！"
10132-650 = "先生ならできるって、\n信じてました……！"
10132-660 = "すごいです……！\n先生にも、忍者の才能が……！？"
10132-670 = "お疲れ様、です……！\n素晴らしいフィナーレ、でした！"
