[translation]
10131-300 = "トリニティに来たのは\n初めてですわ……。"
10131-310 = "ご、ご迷惑を\nおかけしないように\nいたしますわね。"
10131-320 = "トリニティという場所――\nそしてそこで生まれる\n物語。"
10131-330 = "ふふ、私、\nどちらもとても\n気に入りましたわ。"
10131-340 = "もっとも……あまりに\n全てが上手くいき過ぎて"
10131-350 = "少し不安にも\nなってしまいますが……。"
10131-360 = "物語の一幕であれば、"
10131-370 = "こういったシーンから\n波乱が生まれる\nものですから。"
10131-380 = "やはり……そうなる\n気がしていましたわ。"
10131-390 = "ええ……私くらいは、\nしっかりしませんと……。"
10131-400 = "よかった……\n本当に、よかったですわ。"
10131-410 = "心から感謝いたしますわ、\n先生。"
10131-420 = "そして……\n申し訳ありません、先生。"
10131-430 = "皆さんがとても親切に\nしてくださって、\n安心できました。"
10131-440 = "……ですがやはり私は、\nただの一生徒に\n過ぎませんのに。"
10131-450 = "お呼びですか、先生？"
10131-460 = "え？\n高笑い？"
10131-470 = "そんなはしたない真似、\nこんな場所では\nいたしませんわ！"
10131-480 = "……私たち二人きりの\n場でしたら、\nお話は別ですが。"
10131-490 = "そんな風に何度も\nからかうのはおやめに\nなってください。"
10131-500 = "さもないと――"
10131-510 = "先生の様子を\n一つ残らず記録して……"
10131-520 = "評を書かせて\nいただきますわよ？"
10131-530 = "「先生は今日も\n三善タカネに\nちょっかいをかけていた」"
10131-540 = "「私はこの事実を\nキヴォトス全土に\n公表することを決意した」"
10131-550 = "ふふっ。そうですわよね？\nご理解いただけて\n何よりです。"
10131-560 = "見識を深めるという\nことは、世界を見る\n視野を広げること。"
10131-570 = "それは、自分自身の世界を\n拡張することでも\nありますわ。"
10131-580 = "ですが……\nそう考えるうちに、"
10131-590 = "ふと、気になったのです。"
10131-600 = "先生の見ている\n世界というのは、"
10131-610 = "いったいどのような\nものなのでしょう……？"
10131-830 = "たとえトリニティにいても、\n日課を怠ってはなりません。"
10131-840 = "……好き勝手に\n振る舞っていては。"
10131-850 = "我が部長のように\nなってしまいますもの。"
10131-860 = "チェックリストを\n用意いたしましたわ。"
10131-870 = "大したものでは\nありませんが……"
10131-880 = "評の構成を\n考えたりするのとほとんど\n同じようなものですから。"
10131-890 = "物語というものは、\n小さな章の積み重ねに\n過ぎません。"
10131-900 = "執筆過程では"
10131-910 = "必ずしも物語の順序通りに\n作られているとは限りませんが。"
10131-920 = "ですが、最終的に\n何らかの形としてまとまり、"
10131-930 = "表出するという意味では――"
10131-940 = "こうした課題を着実に\nこなすことと、似ているの\nかもしれませんわね。"
10131-950 = "繰り返されることは、\n軽んじられがちですわ。"
10131-960 = "だって、\n退屈だから……？"
10131-970 = "小さな積み重ねを\n疎かにしていては、"
10131-980 = "いずれ足元を\nすくわれますわよ。"
10131-990 = "優しい小言だね……？"
10131-1000 = "え、ええ……\n説教くさいのは\n自覚しておりますとも。"
10131-1010 = "評論家なんて所詮、\n重箱の隅をつつく\n小言屋ですもの。"
10131-1020 = "5点満点！\nお見事ですわ！"
10131-1030 = "誠実に課題を\nやり遂げた方には、"
10131-1040 = "報酬があって\n然るべきですから。"
10131-1050 = "はい、こちらをどうぞ。\n私のポケットマネー\nですわ。ふふ。"
