[translation]
10134-1550 = "先生！\nミッションです、ミッション！"
10134-1560 = "今日の任務は、\nなんでしょう？"
10134-1570 = "あっ、お片づけは、\nアリスの担当でしたね……。"
10134-1580 = "通信で失礼します！\n先生！アリスです！"
10134-1590 = "大変な状況に\nなりましたが……"
10134-1600 = "一緒に乗り越えて\nいきましょう！"
10134-1610 = "ふっ、ふっ、ふっ……"
10134-1620 = "どうですか、先生、\nアリスの新しいアーマーは！"
10134-1630 = "アーマーがなくても……。"
10134-1640 = "たとえ、\n光の剣を失っても……。"
10134-1650 = "それでも、\nアリスはアリスです。"
10134-1660 = "みんながいてくれるなら……\nそして。"
10134-1670 = "先生がいてくれるなら！"
10134-1680 = "マルクト……"
10134-1690 = "すごく\nラスボスって感じがします！"
10134-1700 = "倒したら……\n裏ボスが出てきたりとかは、\nしませんよね……？"
10134-1710 = "無事に帰れたら……"
10134-1720 = "みんなに、\nケイのことを紹介したいです！"
10134-1730 = "ぱんぱかぱーん！"
10134-1740 = "先生が報酬を獲得しました！"
10134-1750 = "すごいです、先生！"
10134-1760 = "この調子で一歩ずつ、\n進んでいきましょう！"
10134-1770 = "うぅ……アリスも先生のそばで、\nお祝いしたいです！"
10134-1780 = "はい！アリスは、\nいつも変わらない先生が、\n大好きです！"
