[translation]
10135-100 = "誠実でありなさい、と\n言っているのですよ？"
10135-110 = "どうかしました？"
10135-120 = "えっ？\n呼んでみただけ……\nですか？"
10135-130 = "特に用がないなら\n呼ばないでください！"
10135-140 = "……たまになら、\nいいですけど。"
10135-150 = "えっ？\n優しい言葉がほしい……？"
10135-160 = "寝言は時と場所を\n選んでください！"
10135-170 = "先生も休憩を\n忘れずに！"
10135-180 = "あと歯磨きも！"
10135-1810 = "これは緊急時の総力戦……\nのようなものです。"
10135-1820 = "せめて支援だけでも、と\n店舗の管理をしています。"
10135-1830 = "急いでください先生！\nこっちだってギリギリなんです！"
10135-1840 = "マルクト……\nそしてあの3人組……。"
10135-1850 = "もう！誰も言うことを\n聞かないんですから！"
10135-1860 = "これが終わったら……\n帰れるのでしょうか？"
10135-1870 = "そこにあるはずです！\n急いで！"
10135-1880 = "早く選んで\n指揮に戻ってください！"
10135-1890 = "えっ？\n優しい言葉がほしい……？"
10135-190 = "どこも悪いところは\nありませんね？"
10135-1900 = "寝言は時と場所を\n選んでください！"
10135-1910 = "本当に……先生がいないと、\nダメなんですよ、私たち。"
10135-1920 = "他に必要な物は\nありませんか？"
10135-1930 = "あまり悩む時間は\n残されていません。"
10135-1940 = "継続は力なり、ですよ。"
10135-1945 = "継続は力なり、ですよ。"
10135-1946 = "継続は力なり、ですよ。"
10135-1947 = "継続は力なり、ですよ。"
10135-1950 = "聞いてますか先生？"
10135-1955 = "聞いてますか先生？"
10135-1956 = "聞いてますか先生？"
10135-1957 = "聞いてますか先生？"
10135-1960 = "誠実でありなさい、と\n言っているのですよ？"
10135-1965 = "誠実でありなさい、\nと言っているのですよ？"
10135-1966 = "誠実でありなさい、\nと言っているのですよ？"
10135-1967 = "誠実でありなさい、\nと言っているのですよ？"
10135-1970 = "こんにちは、先生。"
10135-1975 = "こんにちは、先生。"
10135-1976 = "こんにちは、先生。"
10135-1977 = "こんにちは、先生。"
10135-1980 = "今日のやることを\nまとめました。"
10135-1985 = "今日のやることを\nまとめました。"
10135-1986 = "今日のやることを\nまとめました。"
10135-1987 = "今日のやることを\nまとめました。"
10135-1990 = "どうかしました？"
10135-1995 = "どうかしました？"
10135-1996 = "どうかしました？"
10135-1997 = "どうかしました？"
10135-200 = "他に必要な物は\nありませんか？"
10135-2000 = "えっ？\n呼んでみただけ……ですか？"
10135-2005 = "えっ？\n呼んでみただけ……ですか？"
10135-2006 = "えっ？\n呼んでみただけ……ですか？"
10135-2007 = "えっ？\n呼んでみただけ……ですか？"
10135-2010 = "特に用がないなら\n呼ばないでください！"
10135-2015 = "特に用がないなら\n呼ばないでください！"
10135-2016 = "特に用がないなら\n呼ばないでください！"
10135-2017 = "特に用がないなら\n呼ばないでください！"
10135-2020 = "……たまになら、\nいいですけど。"
10135-2025 = "……たまになら、\nいいですけど。"
10135-2026 = "……たまになら、\nいいですけど。"
10135-2027 = "……たまになら、\nいいですけど。"
10135-2030 = "わ、私はくすぐったいとか、\nないですから！"
10135-2035 = "わ、私はくすぐったいとか、\nないですから！"
10135-2036 = "わ、私はくすぐったいとか、\nないですから！"
10135-2037 = "わ、私はくすぐったいとか、\nないですから！"
10135-2040 = "くすぐったいとか、別に……。"
10135-2045 = "くすぐったいとか、別に……。"
10135-2046 = "くすぐったいとか、別に……。"
10135-2047 = "くすぐったいとか、別に……。"
10135-2050 = "うあ～～っ！！\nくらえ、こちょこちょ攻撃！！"
10135-2055 = "うあ～～っ！！\nくらえ、こちょこちょ攻撃！！"
10135-2056 = "うあ～～っ！！\nくらえ、こちょこちょ攻撃！！"
10135-2057 = "うあ～～っ！！\nくらえ、こちょこちょ攻撃！！"
10135-2060 = "……はい、どうぞ。\n持っていってください。"
10135-2065 = "……はい、どうぞ。\n持っていってください。"
10135-2066 = "……はい、どうぞ。\n持っていってください。"
10135-2067 = "……はい、どうぞ。\n持っていってください。"
10135-2070 = "な、なんですか！？\n何か言ってほしいんですか！？"
10135-2075 = "な、なんですか！？何か言ってほしいんですか！？"
10135-2076 = "な、なんですか！？何か言ってほしいんですか！？"
10135-2077 = "な、なんですか！？何か言ってほしいんですか！？"
10135-2080 = "……よくできました、先生。"
10135-2085 = "……よくできました、先生。"
10135-2086 = "……よくできました、先生。"
10135-2087 = "……よくできました、先生。"
10135-2090 = "そろそろ来る頃だと\n思っていました。"
10135-2095 = "そろそろ来る頃だと\n思っていました。"
10135-2096 = "そろそろ来る頃だと\n思っていました。"
10135-2097 = "そろそろ来る頃だと\n思っていました。"
10135-210 = "あまり悩む時間は\n残されていません。"
10135-2100 = "な、なんでいきなり\n撫でるんですか！？"
10135-2105 = "な、なんでいきなり\n撫でるんですか！？"
10135-2106 = "な、なんでいきなり\n撫でるんですか！？"
10135-2107 = "な、なんでいきなり\n撫でるんですか！？"
10135-2110 = "……やめて、とは\n言っていません。"
10135-2115 = "……やめて、とは\n言っていません。"
10135-2116 = "……やめて、とは\n言っていません。"
10135-2117 = "……やめて、とは\n言っていません。"
10135-80 = "継続は力なり、ですよ。"
10135-90 = "聞いてますか先生？"
