[translation]
10136-3070 = "やっほー先生、聞こえる？"
10136-3080 = "緊急事態だからね、\n通信で繋げてるの。"
10136-3090 = "回線越しでも、\n顔が見れて嬉しいな。"
10136-3100 = "通気性は確保したけど……"
10136-3110 = "まだ暑い。\nもう一枚脱いでもーー"
10136-3120 = "え？やめて？そう……。"
10136-3130 = "まあ、先生が\nそう言うなら……。"
10136-3140 = "今の私はスナイパーというより\nマークスマンなんだ。"
10136-3150 = "移動するときは、\nチームと一緒。"
10136-3160 = "……涼しいところに\n移動してもらえて、助かったよ。"
10136-3170 = "やっぱり先生と話すの、\n楽しい。"
10136-3180 = "はい、お疲れ様。"
