[translation]
16019-2150 = "ようこそ、\n飛鳥馬トキのお店へ。"
16019-2160 = "……嘘をつきました。\nみんなのお店です。"
16019-2170 = "あまり品数は\n用意できませんでしたが……。"
16019-2180 = "先生のお役に\n立てればと思います。"
16019-2190 = "ようこそ、\n飛鳥馬トキのお店へ。"
16019-2200 = "……嘘をつきました。\nみんなのお店です。"
16019-2210 = "あまり品数は\n用意できませんでしたが……。"
16019-2220 = "先生のお役に\n立てればと思います。"
16019-2230 = "飛鳥馬トキです。\n画面越しにご挨拶いたします。"
16019-2240 = "直接伺うべきところ、\n緊急事態につき通信にて\n失礼します。"
16019-2250 = "緊急事態であっても、\n飛鳥馬トキのお店は\n営業しています。"
16019-2260 = "はい、先生。\n私はここです。"
16019-2270 = "逃げも隠れもしませ――"
16019-2280 = "いえ……姿を消したら、\n先生は血眼になって\n探してくれますか？"
16019-2290 = "いかがでしょうか。"
16019-2300 = "保温性と安定性、そして\n心身のリラックス効果もある――"
16019-2310 = "まるで私のような、\n優秀な戦闘服です。"
16019-2320 = "先生、私と一緒にスーツの\n機能を確認しましょう。"
16019-2330 = "好きなだけ私にくっついていて\n構いませんので、ご遠慮なく。"
16019-2340 = "はい、先生。\n私はここです。"
16019-2350 = "逃げも隠れもしませ――"
16019-2360 = "いえ……姿を消したら、\n先生は血眼になって\n探してくれますか？"
16019-2370 = "いかがでしょうか。"
16019-2380 = "保温性と安定性、そして\n心身のリラックス効果もある――"
16019-2390 = "まるで私のような、\n優秀な戦闘服です。"
16019-2400 = "先生、私と一緒にスーツの\n機能を確認しましょう。"
16019-2410 = "好きなだけ私にくっついていて\n構いませんので、ご遠慮なく。"
16019-2420 = "少々お待ちを。"
16019-2430 = "パーフェクトメイドの記憶力で、\n在庫の場所を\n思い出してみせます。"
16019-2440 = "やむを\n得ずオンライン対応中ですが、\n営業に支障はありません。"
16019-2450 = "ベストエージェントは、\n活躍の場を選びませんので。"
16019-2460 = "ご購入、\nありがとうございます。"
16019-2470 = "ちなみに、一言いただければ\n私も購入できます。"
16019-2480 = "そちらの商品ですね、\n承知しました。"
16019-2490 = "再入荷が完了するまで、\n私と遊んで待ちませんか？"
16019-2500 = "こういうものが\nお好きなのですね、\n分かりました。"
16019-2510 = "はい、どうぞ。またのご利用を\nお待ちしております。"
16019-2520 = "何度でも、\n私に会いに来てください。"
16019-2530 = "ご購入、\nありがとうございます。"
16019-2540 = "ちなみに、一言いただければ\n私も購入できます。"
16019-2550 = "そちらの商品ですね、\n承知しました。"
16019-2560 = "再入荷が完了するまで、\n私と遊んで待ちませんか？"
16019-2570 = "こういうものが\nお好きなのですね、\n分かりました。"
16019-2580 = "はい、どうぞ。またのご利用を\nお待ちしております。"
16019-2590 = "何度でも、\n私に会いに来てください。"
16019-2600 = "はい、良いと思います。"
16019-2610 = "その商品は、\n後ろの棚からお取りください。"
16019-2620 = "買い間違えた場合には\n返品が可能です。"
16019-2630 = "……すみません。\nできませんでした。"
16019-2640 = "ご希望であれば、私との通話券を\nオマケで付けておきます。"
16019-2650 = "もちろん、\nご希望ですよね？"
