[translation]
20052-10 = "リスクなくして\nリターンなし。"
20052-100 = "いえまあ……原因は\n特定できそうな気が、\nしますけど……"
20052-110 = "まだまだ諦めるわけには\nいきませんよ……！"
20052-120 = "いやぁ～一時は\nどうなることかと……。"
20052-130 = "うまくいって\n良かったです～……って、\n反省会、ですかぁ？"
20052-140 = "えっと……それは\nまた今度……じゃダメ、\nですかねぇ……？"
20052-150 = "クリエイターの\n皆さんは……"
20052-160 = "何かを生み出す力は\nあるのに、"
20052-170 = "それを広めることに\n関しては――"
20052-180 = "興味を示さないケースが、\n多いんですよねぇ……。"
20052-190 = "本……\n文章とは大切なもの。"
20052-20 = "さて、事業を\n始めましょうかぁ。"
20052-200 = "それは最小限のインプット\nで最大限のアウトプットを\n引き出す――"
20052-210 = "「可能性」を\n秘めている商品、\nなのですから……！"
20052-220 = "何かをゼロから\n作り出せるということは、\n素晴らしいことです。"
20052-230 = "それを可能にさせる\n才能もまた。"
20052-240 = "……。"
20052-250 = "良いですよねぇ、\nそういう才能。"
20052-260 = "心から……\nそう思いますよぉ。"
20052-270 = "トリニティの生徒の\n皆さんには、心から\n感謝しているんですよぉ？"
20052-280 = "……そんな目でみないで\nくださいって。"
20052-290 = "ちゃ～んと、本心から\n思っていますとも。"
20052-30 = "今こそ、\nお見せしましょう。"
20052-40 = "不毛の地・レッド\nウィンターで生き残った、\n我が出版部の手腕をっ！"
20052-50 = "……手腕というより、"
20052-60 = "サバイバル力、のほうが\nあってるかも\nしれませんがねぇ。"
20052-620 = "事業の基本は\nなんだと思いますぅ？\n物品……？交換……？"
20052-630 = "もちろん、\nお金、ですよねぇ！"
20052-640 = "よくぞ\n来てくださりました！"
20052-650 = "資金と商品の行き交う、\n事業の現場へ！"
20052-660 = "ムフフ、では、\nどうぞごゆっくり。"
20052-670 = "棚の奥にお宝が眠ってる\nこともありますから。"
20052-680 = "最後までよ～く\nみていってくださいねぇ、先生。"
20052-690 = "ああ、もちろん私を\nじっくり見ても構いませんよ？"
20052-70 = "来てますねぇ……\n流れが、来てますねぇ！"
20052-700 = "私に話しかけたところで、\n安くなることは\n絶対にないですよぉ？"
20052-710 = "割引が一つ決定するまで、\n裏では数えきれないほどの\n交渉と……"
20052-720 = "……政治的な取引が、\n行われているんですからぁ。"
20052-730 = "想像もしませんでしたよ、\n先生相手に事業を\nする日がくるだなんて。"
20052-740 = "いや～長生きして\nみるもんですねぇ。"
20052-750 = "おおっ！\nお目が高いですねぇ先生！"
20052-760 = "でしたらこちらも、\nよろしければ\nいかがですか？"
20052-770 = "ここだけの話ですが……。"
20052-780 = "私は成果物をこの目で\n確かめる瞬間が……一番、\n興奮するんですよぉ……！"
20052-790 = "良いですか？先生。\n文化とは、お金なのです。"
20052-80 = "出版部長として、\nこれはなんとしてでも\nモノにしてみせますよぉ！"
20052-800 = "すなわち、\n購入という行為は――"
20052-810 = "文化的な活動と\n言えるでしょう。"
20052-820 = "品質は\n保証いたしますよぉ？"
20052-90 = "どうして\nこんなことに……。"
