[translation]
20053-10 = "潜入任務に\n持って行くなら、\nおにぎりか兵糧丸か――"
20053-20 = "ん？先生殿！\nいらっしゃい！"
20053-30 = "先生殿……\n良い格好じゃん。"
20053-40 = "こういう感じも\n新鮮だね。"
20053-50 = "だ～～っ！なんで\nファッションショーで\n戦い始めるのさっ！？"
20053-60 = "ツクヨに会いたい……。"
20053-70 = "元気かな……ラーメン、\nちゃんと食べれてると\nいいけど……。"
20053-80 = "忍術研究部、\n完全復活！"
20053-90 = "先生殿も！\nこっちこっち！"
20053-100 = "なんかヒマだなぁ……。"
20053-110 = "ん？こういうこと言うと\n絶対何か起きるって？"
20053-120 = "うぅ……これ、\nキツくて動きにくい……。"
20053-130 = "みんなこれの\n何がいいの！？"
20053-140 = "服装は忍者の\n条件にあらず……"
20053-150 = "なれば、忍者を忍者たら\nしめるものは何か……！？"
20053-160 = "とくと見よ……！\nドレスごとき、"
20053-170 = "忍者にとって\n何の障害でもない、\nということを……！"
20053-330 = "いらっしゃい、先生殿！\nゆっくり見てってね。"
20053-340 = "あ！でも、この商品なんだけど、\n私が思うには―― "
20053-350 = "無い物以外、\nぜーんぶあるよ！ふっふっふ！"
20053-360 = "ふっふん～早く閉めて、\n新しい忍者定食を\n食べに行こーよ！"
20053-370 = "選択は慎重に、\n購入は大胆に……！"
20053-380 = "それが\nグッズを買う時の掟……！"
20053-390 = "いつかここに、\n少女忍法帖ミチルっちの\nグッズを……！ "
20053-400 = "おぉ～それかぁ。\n良い選択じゃん？"
20053-410 = "そう！忍者なら\nそれを選ばなくっちゃね！"
20053-420 = "こちら、温めま……"
20053-430 = "あっ、間違えた。"
20053-440 = "おお……！それはまさに！\nイチオシ商品！"
20053-450 = "まあ、全部\nイチオシなんだけど！"
20053-460 = "あ、先生殿も来たんだね！"
20053-470 = "……私？どれにするか\n悩んでたとこ。"
20053-480 = "んん～いい匂い――"
20053-490 = "だけでもないけど！\nまあ、いってみよー！"
20053-500 = "ごちそうさまでした……\nもう何も入んない……。"
20053-510 = "麺とスープ……\nそれはまさに忍者と忍術……。"
20053-520 = "先生殿はどんなラーメンが好き？"
20053-530 = "おぉ……！"
20053-540 = "新しい忍術を\nひらめけそうな味だよ……！！"
20053-550 = "うにゃっ……！？\nこ、この味は……！ "
20053-560 = "んっ、なかなかやるじゃん……？"
20053-570 = "悪くないけど……悪くはない……\nほんと、それだけ……。"
20053-580 = "えっ……これ、\nラーメンなの……？"
