[translation]
20055-2660 = "い、いらっしゃいませ、\n先生……。"
20055-2670 = "お店みたいな場所……にしては、\nどこかさみしいような。"
20055-2680 = "うぅ……なんだか怖いです……\nううう……。"
20055-2690 = "先生……\nわたしのこと、\n忘れませんよね……？"
20055-2700 = "わたしにできることを、\nしたいのに……。"
20055-2710 = "みなさん、\nすごい方ばかりで……。"
20055-2720 = "あっ、はい……！\nそちら、ですね……！"
20055-2730 = "店員さんっぽく……\n店員さんっぽく……。"
20055-2740 = "いつもありがとうございます！"
20055-2750 = "は、はい……こちら、\nどうぞ……。"
20055-2760 = "ど、どうかこれが……。"
20055-2770 = "みなさんの……\n役に立ちますよう、に……。"
20055-2780 = "い、いらっしゃいませ、\n先生……。"
20055-2781 = "い、いらっしゃいませ、\n先生……。"
20055-2790 = "お店みたいな場所……にしては、\nどこかさみしいような。"
20055-2791 = "お店みたいな場所……にしては、\nどこかさみしいような。"
20055-2800 = "うぅ……なんだか怖いです……\nううう……。"
20055-2801 = "うぅ……なんだか怖いです……\nううう……。"
20055-2810 = "先生……\nわたしのこと、\n忘れませんよね……？"
20055-2811 = "先生……\nわたしのこと、\n忘れませんよね……？"
20055-2820 = "わたしにできることを、\nしたいのに……。"
20055-2821 = "わたしにできることを、\nしたいのに……。"
20055-2830 = "みなさん、\nすごい方ばかりで……。"
20055-2831 = "みなさん、\nすごい方ばかりで……。"
20055-2840 = "あっ、はい……！\nそちら、ですね……！"
20055-2841 = "あっ、はい……！\nそちら、ですね……！"
20055-2850 = "店員さんっぽく……\n店員さんっぽく……。"
20055-2851 = "店員さんっぽく……\n店員さんっぽく……。"
20055-2860 = "いつもありがとうございます！"
20055-2861 = "いつもありがとうございます！"
20055-2870 = "は、はい……こちら、\nどうぞ……。"
20055-2871 = "は、はい……こちら、\nどうぞ……。"
20055-2880 = "ど、どうかこれが……。"
20055-2881 = "ど、どうかこれが……。"
20055-2890 = "みなさんの……\n役に立ちますよう、に……。"
20055-2891 = "みなさんの……\n役に立ちますよう、に……。"
20055-2900 = "大丈夫です……\nわたしは大丈夫ですから……！"
20055-2910 = "逃げちゃダメ、\n逃げちゃダメ……"
20055-2920 = "逃げちゃ、ダメ……！"
20055-2930 = "どんな時でも……ミッションは\n大事、ですから……。"
20055-2940 = "どうして、こんなことに……。"
20055-2950 = "もう少し、話せたら……。\nよかったのに……。"
20055-2960 = "わたしに\nできることがあれば……。"
20055-2970 = "いつでも、\n言ってください……！"
20055-2980 = "ゲームシステムだったら、\nこう言うと思います。"
20055-2990 = "ミッションクリア！"
20055-3000 = "えへへっ……\nこれを言ったら、"
20055-3010 = "少し緊張が\n解けた気がします。"
20055-3020 = "先生は……\n怖くないですか？"
20055-3030 = "……"
20055-3040 = "わたしは、先生がいるから……"
20055-3050 = "もう少し頑張ってみます。"
