[translation]
1001515-1 = "アリスの花丸シール"
1001515-10 = "本物の先生です！"
1001515-101 = "これを着けると、遠赤外線とマイナスイオンで血行が良くなります！"
1001515-102 = "銃の汚れを減らしたり、弾詰まりをなくしたりする効果まで！"
1001515-103 = "その名も、げるげるゲルマニウム・ブレスレット！！！"
1001515-107 = "……。"
1001515-108 = "はぁ、全然売れないな……。"
1001515-109 = "こんにちは！何か困ってるんですか？"
1001515-111 = "えっ？"
1001515-112 = "特に無……くもないかな。"
1001515-113 = "ではこちらを！"
1001515-114 = "「よくできましたシール」です！幸運値のステータスを上げてくれます！"
1001515-115 = "ちょっ、押し売り！？"
1001515-116 = "いえ、プレゼントです！"
1001515-117 = "みなさんに、幸せになってほしいので！"
1001515-121 = "な、何なんだ……？"
1001515-125 = "……ん？"
1001515-126 = "……ず、ずっと詰まってた薬莢が、勝手に排出された！？"
1001515-130 = "おかしいな。#nげるげるゲルマニウム・ブレスレットには、何の効果も無いはずだし……。"
1001515-135 = "（アリスと一緒に、よくできましたシールを配り終え……）"
1001515-136 = "（部室に戻って、二人でゲームをすることに）"
1001515-143 = "ありがとうございます、先生。"
1001515-144 = "[s] \"ん？\""
1001515-145 = "今日、アリスと一緒にいてくれたこと。"
1001515-146 = "それに今こうして、一緒にゲームをしてくれることも！"
1001515-147 = "ゲーム開発部でも、よく一緒にゲームはしますが……。"
1001515-148 = "先生と二人で遊べる時間は、珍しいですから。"
1001515-149 = "アリスにとってこれは、大事な経験値獲得チャンスです！"
1001515-15 = "（アリスは いきおいよく とびついた！）"
1001515-150 = "[s] \"なるほど……？\""
1001515-151 = "なのでアリスは、こうして先生と一緒に過ごせて、とっても嬉しいです！"
1001515-152 = "どれくらい嬉しいかと言うと……。"
1001515-153 = "二人でパーティーを組んで、この「花丸シール」を装備すれば……。"
1001515-154 = "三日間徹夜で、ゲームができそうなくらいです！"
1001515-155 = "[s5] \"そ、それはあんまり良くないかな……？\"\n[s6] \"三日の徹夜はもう厳しい……。\""
1001515-158 = "そ、そうでしたか……。"
1001515-159 = "ですが、この「花丸シール」の効き目は本当にすごいんです！#nアリスもそうでした！"
1001515-16 = "（せんせいは たおれそうになった！）"
1001515-160 = "格闘ゲームで体力が1ドットしか残っていない時に、#n相手の必殺技をジャストガードして――"
1001515-161 = "レイジ状態から逆転、一撃の超必殺技を決められましたから！"
1001515-162 = "[s] \"それはすごい！？\""
1001515-163 = "はい！#nモモイとの試合で、一度だけですが！"
1001515-164 = "その日の部室は――"
1001515-165 = "それは、それはもう……！"
1001515-166 = "爆発寸前の盛り上がりでした！"
1001515-167 = "[s]\"私も見てみたかったなぁ……。\""
1001515-168 = "……あっ。"
1001515-169 = "思えば、先生にシールを渡しそびれていました！"
1001515-170 = "[s] \"あ、そういえば？\""
1001515-176 = "[ns7] \"でも、貰っちゃって良いの？\"\n[ns8] \"これ「先生のよくできましたシール」じゃ……？\""
1001515-179 = "確かにそうかもしれませんが……。"
1001515-180 = "……大丈夫です！"
1001515-181 = "実はアリス、先生専用の「アリスのよくできましたシール」を作っておいたんです！2枚だけ！"
1001515-182 = "[s] \"「アリスのよくできましたシール」？\""
1001515-19 = "待ってましたよ！"
1001515-190 = "はい！#nこれは――"
1001515-191 = "アリスが先生を褒めるための「よくできましたシール」です！"
1001515-192 = "先生のシールほど万能ではないですし、幸運値も上がらないかもしれませんが……。"
1001515-193 = "それでも、受け取ってもらえたら嬉しいです！"
1001515-194 = "これがあると、いつも繋がってるような気がします。"
1001515-2 = "（アリスと会うために、ゲーム開発部の部室へ向かった）"
1001515-20 = "[s] \"私も会いたかったよ。それで見せたいものって……？\""
1001515-200 = "[ns] \"ありがとね、アリス。\""
1001515-201 = "はい、先生。"
1001515-202 = "やっぱりアリスは、先生のことが大好きです。"
1001515-203 = "[s] \"私も大好きだよ。\""
1001515-204 = "ありがとうございます！"
1001515-205 = "そしてこの隙に！二連続で葉蛾扇、そしてジャンプ強キックからの強パンチスタン……！"
1001515-206 = "そしてスペシャルアーツ、レベル3です！！！"
1001515-21 = "ふっふっふ、それは……。"
1001515-210 = "[ns9] \"や、やられた！！！\"\n[ns10] \"感動してる間にウルトラコンボが！？\""
1001515-213 = "ふっふっふ、血も涙も師弟の情も通じない修羅の道――"
1001515-214 = "――これこそ、格ゲーの世界です！"
1001515-216 = "（その後も、二人で仲良くゲームを続けた）"
1001515-217 = "（アリスは対戦の合間、「アリスのよくできましたシール」を宝物のように見つめていた）"
1001515-22 = "こちらです！"
1001515-24 = "（アリス は バッジのようなものを さしだした！）"
1001515-26 = "[ns1] \"……バッジ？\"\n[ns2] \"「Good job」……って書いてある。\""
1001515-29 = "バッジではなく、「花丸シール」です！"
1001515-3 = "（到着した途端……）"
1001515-30 = "どこから説明しましょうか……。"
1001515-31 = "以前、みんなでローグライクゲームを作りました。"
1001515-32 = "その中には滅多に手に入らない、とても運気の上がるアイテムがあったんです。"
1001515-33 = "それがこの「先生の花丸シール」です！"
1001515-34 = "持っているだけで強くなり、幸運値のステータスも上がる……。"
1001515-35 = "とってもすごいアイテムなんです！"
1001515-36 = "[s3] \"なるほど……。\"\n[s4] \"それをこうして、実際に作ってみたと。\""
1001515-39 = "その通りです！"
1001515-40 = "というわけで先生、アリスと冒険に出ましょう！"
1001515-41 = "このシールを沢山配らないと！"
1001515-43 = "（元気いっぱいのアリスに手を引かれ、外へ向かった）"
1001515-45 = "こんにちは！"
1001515-46 = "やっ、アリス。#nそれに先生も、こんにちは。"
1001515-47 = "今日はどうしたの？"
1001515-48 = "「よくできましたシール」です！"
1001515-49 = "「Good job」……へぇ、何だか嬉しいね。"
1001515-50 = "要するに、褒めてくれてるってこと？"
1001515-51 = "先生も、ありがとうございます。"
1001515-52 = "[s] \"うん、何か理由があったわけじゃないんだけど。\""
1001515-53 = "ふふっ。それでも、ありがとうございます。"
1001515-54 = "大切にするね、アリス。"
1001515-55 = "はい、絶対に良いことが起こるはずです！#nゲームでも幸運値が上がるので！"
1001515-56 = "なるほど……ま、運に頼りたくなる時はあるよね。"
1001515-57 = "新素材の開発なんてのは、運次第みたいなところもあるし。"
1001515-58 = "乳鉢に素材を入れて、一つひとつ丁寧に擦って、焼いて――"
1001515-59 = "それを今度は砕いて、混ぜて、回して、振って……。"
1001515-60 = "どれだけ考えても、何度繰り返しても……最後は祈るしかない。"
1001515-61 = "というわけで……次こそお願いします、「よくできましたシール」様！！！"
1001515-62 = "[s] \"い、色々と大変なんだね……。\""
1001515-63 = "アリスも詳しくは知りませんが……。"
1001515-64 = "きっと大丈夫です！"
1001515-65 = "さあ、どんどん行きましょう！"
1001515-69 = "みんな、ちょっと来て！#n今、新しい数値が出た！"
1001515-70 = "嘘！？"
1001515-71 = "本当だってば！"
1001515-76 = "まさか……。"
1001515-77 = "……あのシールの効果？"
1001515-8 = "先生――！！！"
1001515-80 = "では、アリスはそろそろ行きます！#n上手くいきますように！"
1001515-81 = "ありがとね、アリス。#nサーバーの相手してると、祈ることが多くて……。"
1001515-85 = "あれ……？"
1001515-86 = "サーバーエラーが直ってる……！？"
1001515-89 = "お、これが例の「よくできましたシール」？"
1001515-9 = "[s] \"アリス～～！！！\""
1001515-90 = "アリスと先生からのプレゼントです！#n大切にしてくれると嬉しいです！"
1001515-91 = "勿論だよ、ありがとう。"
1001515-96 = "っ……学食の抽選当たった！3等賞！"
1001515-97 = "……。"
1001515-98 = "よっしゃ、今日は唐揚げも追加で！"
