[translation]
1001815-1 = "輝かしい思い出"
1001815-100 = "（ユズの素早い対処でデータは消えずに済んだが……)"
1001815-101 = "（『テイルズ・サガ・クロニクル・プロトタイプ』のプレイは、またの機会になった……）"
1001815-12 = "[ns] \"それにしても、すごい量のソフトだね。\""
1001815-13 = "は、はい……。"
1001815-14 = "ゲーム開発の資料として集めていたら、いつの間にか……。"
1001815-15 = "ほとんどが、古いゲーム機のソフトですけど……。"
1001815-2 = "（ユズと二人で、古いゲーム雑誌について話していたはずが……）"
1001815-20 = "[ns] \"……ん？\""
1001815-21 = "ど、どうかしましたか？"
1001815-22 = "[ns1] \"これ、何だろう……？\"\n[ns2] \"ゲームのディスク？\""
1001815-25 = "……？"
1001815-26 = "ケースには、何か書かれてますか？"
1001815-27 = "[s] \"……「ユズ」って書いてあるね。\""
1001815-28 = "え、えっ？#nわ、わたしの名前……！？"
1001815-29 = "な、なんだろう……。"
1001815-3 = "（気づけば本棚の整理に手を着け、最終的には部室全体の掃除をしていた)"
1001815-30 = "……あっ。"
1001815-31 = "[s3] \"覚えてないとすると……。\"\n[s4] \"じゃあ、パソコンで確認を――\""
1001815-34 = "ちょ、ちょっと待ってください！"
1001815-35 = "わたしが、先に確認しますっ……！"
1001815-36 = "[s] \"ど、どうかしたの？\""
1001815-37 = "それは、ええと……。"
1001815-38 = "な、何が入ってるか、わかりませんし……。"
1001815-39 = "うぅ、ちゃんと覚えていれば……。"
1001815-43 = "す、すみません、その……#n確認している間、部室の外で待っていただくことは……？"
1001815-44 = "[s] \"ちゃんと後ろ向いてるよ？\""
1001815-45 = "だ、ダメですっ……！"
1001815-48 = "（追い出されるように部室を出た）"
1001815-5 = "ゲーム開発部・部室"
1001815-50 = "（10分後……）"
1001815-51 = "お、お待たせしました……。"
1001815-52 = "……もう、大丈夫です。"
1001815-54 = "さ、さっきはその、ごめんなさい……。"
1001815-55 = "[s5] \"ううん、プライベートな物かもだし。\"\n[s6] \"ところで中身は……？\""
1001815-58 = "あ、慌てるほどのものではなかったです。"
1001815-59 = "大事なものでは、ありましたが……。"
1001815-6 = "雑誌の内容を、確かめたかっただけなのに……。"
1001815-60 = "[s] \"大事なもの？\""
1001815-61 = "あれは初めて作ったゲーム……#n『テイルズ・サガ・クロニクル・プロトタイプ』のゴールデンマスターディスクでした。"
1001815-62 = "……ゴールデンマスターについて、ですか？"
1001815-63 = "あっ、すみません……。"
1001815-64 = "ええっと……完成版が入った[ruby=マスターディスク]原盤[/ruby]を、ゴールデンマスターと言うんです。"
1001815-65 = "昔はレコードディスクを製造する時、#n耐久度を高めるために、円盤の上に金箔を貼っていたので――"
1001815-66 = "そこから、ゲームの最終バージョンが入ったマスター版を#n「ゴールデンマスター」と呼ぶようになりました。"
1001815-67 = "もちろん今ですと、金箔はつけませんが……。"
1001815-68 = "『テイルズ・サガ・クロニクル・プロトタイプ』をネットにアップする前……#n最後にデータをコピーしたのが、このディスクなんです。"
1001815-69 = "あの時は、これが目に入るだけで恐ろしくて……箱の奥に仕舞おうと必死だったのに……。"
1001815-7 = "いつの間にかここまで……#nすみません、付き合わせてしまって……。"
1001815-70 = "今となっては……存在すら、忘れちゃってました。"
1001815-71 = "[s] \"……もう大丈夫？\""
1001815-72 = "……はい。"
1001815-73 = "悪評や批判の声が……平気になったわけでは、ありません。"
1001815-74 = "ですが、それ以上に……良い思い出が、いっぱいできましたから。"
1001815-75 = "今のメンバーが集まったのも、プロトタイプを公開したおかげです。"
1001815-76 = "もしゲームを作っていなければ、#nこんなきらきらと輝いた毎日は、過ごせてなかったと思いますし……。"
1001815-77 = "なので今は、このディスクに……まっすぐ向き合える、と思っています。"
1001815-78 = "[s7] \"……そっか。\"\n[s8] \"大切な思い出になったんだね。\""
1001815-8 = "[s] \"大丈夫だよ、ちょうど時間あったし。\""
1001815-81 = "……はい、たったひとつの[ruby=輝かしい思い出]ゴールデンマスター[/ruby]です。"
1001815-82 = "先生は『テイルズ・サガ・クロニクル』のプロトタイプを触ったこと、ありませんよね？"
1001815-83 = "良かったら……プレイ、してみませんか？"
1001815-84 = "[s] \"良いの！？\""
1001815-85 = "じゃあ、早速……。"
1001815-90 = "あ、あはは……#n最適化できてないので、遅いですね……。"
1001815-94 = "エラー！？#nど、どうして……。"
1001815-95 = "<警告：CPUに異常な負荷が発生しています>"
1001815-96 = "<スキャン中……詳細不明のデータを確認しました>"
1001815-97 = "<該当部分をデリートします>"
1001815-98 = "わ、わたしの思い出、消さないで――！"
