[translation]
10049090-1 = "第9話;最初で最後のチャンス"
10049090-2 = "マシロさん、何か動きはありましたか？"
10049090-3 = "ターゲットを捜索中ですが、めぼしい成果はありません。#n視界が悪くなってしまっているので……。"
10049090-4 = "販売スタッフを探してください。風船とポップコーンを売っているはずです！"
10049090-5 = "ステージの近くを重点的にお願いします。"
10049090-6 = "どうしてそれが分かるんですか？"
10049090-7 = "午前中、ステージに上がる前に、落ち込んでいる子供を見かけたんです。"
10049090-8 = "不良品を交換してほしいともお願いしていました。"
10049090-9 = "もう移動してるんじゃない？"
10049090-10 = "いえ、おそらくですが、まだ留まっています。"
10049090-11 = "あそこはゲヘナとトリニティの境目に近い。"
10049090-12 = "つまり、逃げるのに都合がいい場所ですから。"
10049090-13 = "なにより、ステージの近くだからこそ、人の往来が多い場所でもあります。"
10049090-14 = "商売が目的なら、最適なはずです。"
10049090-15 = "[s] \"スズミ、鋭いね！\""
10049090-16 = "自警団の勘です。それより時間が……。"
10049090-17 = "これ以上遅れると、パレードが終わってターゲットも帰ってしまいます。"
10049090-18 = "そうはさせないわ！入園するのにすっごい苦労したんだから！"
10049090-19 = "ワニに嚙まれるところだったんだ！"
10049090-21 = "ワニ、ですか……？"
10049090-22 = "見つけました！観客席から見て、ステージの左側に店を構えています！"
10049090-26 = "向かいます！"
10049090-30 = "さぁさぁ皆さん！この風船は空気が抜けたわけじゃありませんよ～？"
10049090-31 = "皆さんの体内にある有害な気が、風船の中のハイパーマイナスイオンと結びついたんです！"
10049090-32 = "つまり風船がしぼんだのはラッキー！元気になったってことですから！"
10049090-34 = "このお姉ちゃん、むずかしいことばっか言ってる。"
10049090-35 = "元気になったの？じゃあ、もう病院でチューシャしなくていいの？"
10049090-37 = "え、あ、でも体調が悪いときは注射を打ってもらったほうがいいですよ？"
10049090-38 = "ちゃんと病院に行って、お医者さんの言うとおり#nお薬をちゃんと飲みましょうね？"
10049090-39 = "そこまでです！"
10049090-40 = "え？"
10049090-41 = "お伺いしたいことがあります。"
10049090-42 = "ご協力、いただけますか？"
10049090-43 = "あ～、なるほどぉ……！えぇ、えぇ、もちろんですとも～"
10049090-44 = "では、ちょ～っと待ってくださいね～いやいや怪しいことだなんて、そんなそんな。#n荷車の車止めをちょちょっと――"
10049090-49 = "――外して今日は閉店！さようなら～！！！！"
10049090-50 = "ピンク、撃ってください！"
10049090-51 = "えへへっ！そう呼んでくださり、ありがとうございます！"
10049090-60 = "いたたっ！"
10049090-61 = "褒賞金――確保ぉっ！"
10049090-62 = "なっ！？"
10049090-63 = "皆さん！取り締まりです！お店を片づけて、全員集まってください！！"
10049090-65 = "仲間を呼んでいます！！"
10049090-70 = "部長はあそこだ！援護射撃するよ！"
10049090-71 = "撃て！部長を守れーっ！！"
10049090-79 = "なに？最後のショーなの？"
10049090-80 = "ぽいね？全員集合してるし！"
10049090-82 = "ジャブジャブヘルメット団、準備はいい？#nあの褒賞金を取り逃がしたら……当然、今日の焼肉はパーよ。"
10049090-86 = "それが嫌なら――"
10049090-91 = "絶対に捕まえなさい！！！"
