[translation]
10049020-1 = "第2話;週末の予定"
10049020-10 = "それは、どういう……？#n現場に放置というのは――"
10049020-100 = "自警団のスーパースター……？#nあれ？そういえば、自警団ってどういう組織なんですか？"
10049020-101 = "いえ、そもそも組織ではありません。#nそれに正義実現委員会と違って、あくまで自称です。"
10049020-102 = "ですが、レイサさんがいてくだされば大きな助力になると思います。"
10049020-103 = "ぜひ、力を貸してください。"
10049020-104 = "もちろんです！！"
10049020-105 = "シミコさんも、図書委員会の仕事で忙しい中、ありがとうございます。"
10049020-106 = "いえ、そんな！"
10049020-107 = "最初に言い出したのは私ですから！"
10049020-108 = "精一杯、頑張りますね！"
10049020-109 = "では、作戦会議を始めましょう！"
10049020-11 = "違います。対象と交戦していません。"
10049020-111 = "まずは現時点で分かっている情報ですが……。"
10049020-112 = "正義実現委員会いわく、ジャブジャブヘルメット団は、河駒風ラブを筆頭に集まった小規模組織です。"
10049020-113 = "そしてシミコさんの情報によれば、「ボーダーランド遊園地」には、他にもいくつかのヘルメット団が招集される予定とのこと。"
10049020-114 = "これがどれほどの規模になるか……事前に把握するのは難しいでしょうね。"
10049020-115 = "つまり、どれぐらい隠れているか分からないんですね！"
10049020-116 = "はい。この点も含め、正義実現委員会からは、状況の確認だけを要請されています。#n重ねて、直接的な戦闘は回避するように、と。"
10049020-117 = "このことから、潜伏が一番望ましいのですが……。"
10049020-118 = "週末の遊園地は多くの来場者が予想されます。#n来場客に変装したら、私たち同士の識別が難しくなってしまうでしょう。"
10049020-12 = "介入しませんでしたので……こちらには気づいていないはずです。"
10049020-120 = "では、スタッフに変装するのはどうですか？"
10049020-121 = "それも難しいです。#n正規のスタッフに見咎められてしまう可能性がありますから。"
10049020-122 = "もっと策を練るべきですが……使える時間は多くありません。#n早く方針を決めないと……。"
10049020-123 = "とりあえず、遊園地のパンフレットをお渡ししておきます。#n裏面に地図が載っていますので、覚えておいてください。"
10049020-124 = "ありがとうございます。近くに動物園と……湖もあるんですね。#n敷地は城壁に囲まれていて、出入り口が決まっているみたいです。"
10049020-125 = "ふふっ、まるで童話の世界みたいですね。"
10049020-127 = "おぉ……おぉぉ……！"
10049020-13 = "……？"
10049020-131 = "レイサさん？地図はパンフレットの裏面ですよ？"
10049020-132 = "これです！！"
10049020-133 = "これ……？"
10049020-134 = "はい？"
10049020-138 = "ボーダーランド遊園地・トリニティエリア"
10049020-14 = "体調が優れないのでしたら、救護騎士団をお呼びしましょうか？"
10049020-140 = "風船、つぶれちゃった……#n買ってもらったばっかなのに……。"
10049020-141 = "うわぁーん！ポップコーンバケットの蓋……壊れちゃったぁー！"
10049020-142 = "うわぁーん！"
10049020-143 = "店員さん！これ！新しいのに交換してよぉー！"
10049020-146 = "わーっ！！"
10049020-147 = "お客さんがいっぱいです！"
10049020-148 = "早く行きましょう！"
10049020-149 = "ま、まだ……心の準備が……。"
10049020-15 = "体調、ですか？特に問題はありません。"
10049020-150 = "ほらほら、早くしないと逃げられちゃうかもしれませんよ！"
10049020-151 = "さあ！出動です！"
10049020-158 = "スズミさん！似合ってますから、恥ずかしがる必要なんてありません！"
10049020-159 = "（うぅ……）"
10049020-16 = "……これは正義実現委員会の役割であると判断し、通報に来ました。"
10049020-160 = "（どうしてこんなことに……）"
10049020-17 = "はい？"
10049020-2 = "――なるほど。それでは、話を整理します。"
10049020-22 = "どうしてカレンダーを？"
10049020-23 = "あ、いえ。お気になさらず。"
10049020-24 = "（エイプリルフールでは……ありませんよね……）"
10049020-25 = "状況は理解しました。ただ……。"
10049020-26 = "大変申し上げにくいのですが、今回の件を正義実現委員会が対応することはできません。"
10049020-27 = "それは……どうしてですか……？"
10049020-28 = "……。"
10049020-29 = "ご報告いただいたことは感謝しております。#nただ……場所が問題なのです。"
10049020-3 = "まず、図書委員会の[ruby=えんどう]円堂[/ruby]シミコさんが、夜勤中に偶然ヘルメット団の密会現場を目撃した。"
10049020-30 = "「ボーダーランド遊園地」は、少々厄介な立地をしておりまして……。"
10049020-31 = "あそこは、トリニティ自治区の遊園地ですよね？"
10049020-32 = "ええ。遊園地の正門と敷地の半分はトリニティに属します。#nですが、裏門と敷地のもう半分はゲヘナ自治区でして……。"
10049020-33 = "あの遊園地は、トリニティとゲヘナの境界線上に存在しているのです。"
10049020-34 = "私たちは、トリニティの正義実現委員会。#nゲヘナ側に逃げられたが最後、打つ手がありません。"
10049020-35 = "中には、それを悪用して、良からぬことを行う輩もいるのだとか。"
10049020-36 = "……私たちの情報そのものを疑っているのですか？"
10049020-37 = "まさか。類似の通報は他にも届いています。"
10049020-38 = "それに「河駒風ラブ」が関与しているという点も気になります。#n私たちにとって、彼女の存在は大きいので。"
10049020-39 = "驚きました。正義実現委員会がヘルメット団のリーダーを気にしているとは。"
10049020-4 = "はい、その通りです。"
10049020-40 = "どう転ぶか心配でならない、放っておけない存在とでも言いましょうか。"
10049020-41 = "……。"
10049020-43 = "……？"
10049020-44 = "それはそれとして……通報いただいた内容は、本当に懸念しています。"
10049020-45 = "トリニティ側であれば、まだ対処は可能ですが……。"
10049020-46 = "正義実現委員会は人手不足なのが実情でして……大人数を動員することが難しいのです。"
10049020-47 = "そこで一つ、ご提案があります。"
10049020-48 = "シミコさんは、例のヘルメット団の声や外見を覚えていますか？"
10049020-49 = "あ、はい！"
10049020-5 = "そして……[ruby=こまかぜ]河駒風[/ruby]ラブ率いるジャブジャブヘルメット団が、遊園地で何かを企んでいるかのような話を聞いた。"
10049020-50 = "良かったです。#nスズミさんの実力は私も信頼しております。"
10049020-51 = "……。"
10049020-53 = "ですので、お二人で遊園地の状況を見てきてはいただけないでしょうか？"
10049020-54 = "え？"
10049020-55 = "交戦や制圧は極力控え……現場の状況だけ確認をお願いできればと思います。"
10049020-56 = "とはいえ、目標が実際に現場にいることを確認し、#n対応が必要な場合には、委員会が介入させていただきます。"
10049020-57 = "……つまり、正義実現委員会は表に出ない、という意味でしょうか？"
10049020-58 = "はい。委員会が巡回をしては、ターゲットが逃げる恐れがあります。"
10049020-59 = "さらにその過程で、ゲヘナとの不必要な衝突が生じる可能性も拭いきれません。"
10049020-6 = "シミコさんが現場を離れようとしたタイミングで自警団の[ruby=もりづき]守月[/ruby]スズミさんに遭遇。#nこれらの内容を報告した……と。"
10049020-60 = "そこで、お二人の力をお借りしたいのです。"
10049020-61 = "機密保持に留意してくだされば、どなたかに協力を仰いでいただいても構いません。"
10049020-63 = "いきなりそう言われましても……。"
10049020-64 = "……なるほど。"
10049020-65 = "もちろん、委員会からも可能な限りの支援をさせていただきます。"
10049020-66 = "今回のお願いは、あくまで状況の確認だけ。#nお二人はご自身の安全を最優先に考え、直接的な介入はお控えください。"
10049020-7 = "スズミさん。その二人は救護騎士団に搬送されていますか？"
10049020-71 = "あっ！スズミさん！"
10049020-76 = "シミコさんも！"
10049020-77 = "えっ……正義実現委員会の教室から出てくるなんて……！#nなにか……カッコいい会議でしょうか！？"
10049020-79 = "……。"
10049020-8 = "意識が戻り次第、委員会で取り調べをしようかと。"
10049020-80 = "……。"
10049020-82 = "あ、あれ……？"
10049020-88 = "図書委員会・休憩室"
10049020-89 = "えっ！？そんなのおかしいですよ！"
10049020-9 = "いいえ、搬送されてはいません。"
10049020-90 = "いえ、向こうの言い分も理解できます。"
10049020-91 = "正義実現委員会は、立場上あまり表立って動けない組織ですから。"
10049020-92 = "このような形は珍しいですが、今までも細かな協力要請はありましたし。"
10049020-93 = "それだけ、重要な事案なのでしょう。"
10049020-94 = "でも、いきなり戦闘になったら……。"
10049020-95 = "向こうが何人いるかも分からないのに、2人で相手するなんて無謀です。"
10049020-97 = "[ruby=・]3[/ruby]人です！"
10049020-98 = "はい？"
10049020-99 = "自警団のスーパースター、[ruby=うざわ]宇沢[/ruby]レイサがここにいますから！"
