[translation]
10049060-1 = "第6話;守月スズミ"
10049060-2 = "……。"
10049060-3 = "ぁいたっ！……あはは。"
10049060-4 = "すみません、しみますよね……。"
10049060-5 = "こんなに怪我をしても立ち向かうなんて……レイサさんは強いですね。"
10049060-6 = "えへへ！これくらい慣れてますから！"
10049060-7 = "自警団のスーパースター、[ruby=うざわ]宇沢[/ruby]レイサにはなんてことありません！"
10049060-8 = "それに、今は正義の魔法少女、テルミットピンク！ですから！"
10049060-9 = "……レイサさんからは、学ぶことばかりです。"
10049060-10 = "……。"
10049060-11 = "なんだか、めちゃくちゃでした。"
10049060-12 = "ふさわしくない場で、ふさわしくない行動をしてしまいました。"
10049060-13 = "[s1] \"演技と戦闘、両方やるのは難しいよね。\"\n[s2] \"今日みたいな日もあるよ。\""
10049060-16 = "いえ……今日のことを言っているわけではありません。"
10049060-17 = "……私が自警団の活動を始めてから――"
10049060-18 = "いや、その前から……[ruby=もりづき]守月[/ruby]スズミは、めちゃくちゃだったのかもしれません。"
10049060-20 = "スズミさん……？"
10049060-21 = "……少しだけ、昔話をしてもいいでしょうか。"
10049060-22 = "他人の過去なんて、相手をただ暗い気持ちにさせるだけですが……。"
10049060-23 = "それでも……よろしければ……。"
10049060-24 = "[s3] \"そんなことないよ。\"\n[s4] \"聞かせてくれる？スズミのこと。\""
10049060-27 = "自警団は「他人」じゃないです！"
10049060-28 = "この宇沢レイサが、スズミさんの心を軽くしてあげます！"
10049060-29 = "ありがとうございます……。"
10049060-33 = "よく、噂話が聞こえてくるんです。"
10049060-34 = "守月スズミは、なぜ正義実現委員会ではなく……自警団として活動しているのか。#n正義実現委員会を嫌っているのか、と……。"
10049060-35 = "そういう話は……たくさんありました。"
10049060-36 = "……。"
10049060-40 = "もしかして……#n入りたくても、正義実現委員会には入れなかったのか？"
10049060-45 = "……。"
10049060-46 = "私は……1年生の時、正義実現委員会に所属していたんです。"
10049060-50 = "スズミさんが……ですか？"
10049060-51 = "……入会して間もなく、辞めてしまいましたが。"
10049060-52 = "隠すつもりがなかったと言えば嘘になります。"
10049060-53 = "自分なりに折り合いをつけたつもりでしたが……ままならないものです。"
10049060-54 = "マシロさんも……ご存じだったのでは？"
10049060-55 = "……はい。噂程度ですが。"
10049060-56 = "かつて、正義実現委員会に所属していた、と。"
10049060-57 = "……やはり、そうでしたか。"
10049060-58 = "人の口に戸は立てられません。私に関する噂が流れてもおかしくはないでしょう。"
10049060-59 = "とはいえ、委員会そのものに不満があっただとか、誰かと喧嘩をして退会しただとか……そういった噂は、事実ではありません。"
10049060-60 = "辞めたのは、ただ――"
10049060-61 = "――誰とも馴染めず一人でいることが恐ろしくて……逃げただけなんです。"
10049060-62 = "[ns] \"正義実現委員会に、馴染めなかった……？\""
10049060-63 = "はい。"
10049060-64 = "正義実現委員会は大きな組織です。#nそれゆえに上下関係が厳しく、集団生活を重んじています。"
10049060-65 = "当たり前のように、同じ学年、同じ立場の生徒が生活を共にするんです。"
10049060-66 = "食事も一緒で、些細なことで話に花を咲かせて、交流を深める……。"
10049060-67 = "私は……それが苦手でした。"
10049060-68 = "話題が途切れた瞬間、その沈黙がとても怖くて……。"
10049060-69 = "……私のせいで、会話が途切れてしまったのではないか、と。"
10049060-70 = "それで、無理に話を続けようとしたことも、たくさんありました。"
10049060-71 = "そんなことがあったなんて、初めて知りました……。"
10049060-72 = "委員会を離れて以降は、気楽でしたから。"
10049060-73 = "でも、委員会にいた間は――そういうのが辛かったんです。誰かに興味を持たれることも、持たれないことも……どちらも心が落ち着かなくて……。"
10049060-74 = "注目されたり、期待されたりするのが怖かった……。#nかといって、非難されたり、がっかりされたりするのは、もっと怖かったです。"
10049060-75 = "街のスケバンと戦うことよりも――"
10049060-76 = "他人の目に、自分がどう映っているかの方が恐ろしくて……。"
10049060-77 = "だから……私は、正義実現委員会を辞めました。"
10049060-78 = "……これが、守月スズミという臆病者の物語です。"
10049060-79 = "[ns5] \"……私は、スズミを臆病者だとは思わないかな。\"\n[ns6] \"私がキヴォトスに来たあの日から、君はいつも勇敢だった。\""
10049060-82 = "[ns7] \"ちゃんと覚えてるよ。私が初めて指揮を執った時の事。\"\n[ns8] \"スズミは迷いなく、勇敢に戦ってくれた。\""
10049060-85 = "先生……。"
10049060-86 = "先生の仰る通りです！"
10049060-87 = "私が知っている中で……スズミさんが一番勇敢で、一番カッコいいんです！"
10049060-88 = "だってスズミさんは、どんなにつらい任務だって黙々とこなしちゃうじゃないですか。"
10049060-89 = "それってすっごく素敵なことだと思います！"
10049060-90 = "……街の治安を守るのは「誰かがやるべきこと」だから、と。私もその役を担っているつもりでした。"
10049060-91 = "だというのに、明確な「誰か」である正義実現委員会からは逃げ出して……。"
10049060-92 = "「守月スズミ」がその「誰か」になることも、ずっと怖がったままです。"
10049060-93 = "「トリニティの走る閃光弾」……その呼び方はやめてほしいと、言ったことがありましたね。"
10049060-94 = "ですが……。"
10049060-95 = "案外、気に入っているんです。"
10049060-96 = "気恥ずかしくはありますが……「守月スズミ」という名前を、覆い隠すことができますから。"
10049060-97 = "同じ理由で……「テルミットホワイト」という呼び名も、悪くはありませんでした。"
10049060-98 = "[s9] \"閃光弾……良いあだ名だと私は思うよ！\"\n[s10] \"守月スズミって名前も、綺麗だと思ってるよ！\""
10049060-101 = "……。"
10049060-102 = "先生はいつだってお優しいですね。"
10049060-103 = "ですが……もう自警団は辞めようと思います。"
10049060-104 = "……自警団の活動と言っても、所詮は一般人によるもの。"
10049060-105 = "正義実現委員会のように、公認の組織でもなく……。"
10049060-106 = "ただの一般人が、勝手に暴力を振るっているに過ぎません。"
10049060-107 = "資格もないのに、治安維持という名目だけは掲げて。"
10049060-108 = "こんなのは――ただの自己満足です。私がただ、勝手にやっているだけにすぎません。"
10049060-109 = "そういう意味では、スケバンと同じなのでしょうね。"
10049060-110 = "違います！！"
10049060-114 = "そんなの全っ然！違います！！"
10049060-115 = "レイサさん！？"
10049060-116 = "たとえスズミさんであっても、スズミさん自身を悪く言うのは許せません！"
10049060-117 = "初めて助けられたときから……スズミさんは私のヒーローなんです！"
10049060-118 = "スズミさんは決して！自己満足でパトロールする人じゃありません！"
10049060-119 = "雨が降っても、風が強くても、足を怪我していても……スズミさんは欠かさずパトロールを続けていました！そんなの……自己満足でできることじゃないんですっ！"
10049060-120 = "正義実現委員会に所属してるかどうかなんて関係ありません！"
10049060-121 = "スズミさんとスケバンは全然違います！#n資格がないだなんて考えないでください！"
10049060-122 = "私は……スズミさんと一緒にパトロールするのが楽しいんです……！"
10049060-123 = "イヤホンを分け合って音楽を聴いたり、お喋りもしたりして――！"
10049060-125 = "…………。"
10049060-126 = "[ruby=・   ・   ・   ・   ・   ・]レイサさんが[/ruby]そんな風に思ってくれているのでしたら、よかったです。"
10049060-132 = "それだけじゃありません！雨が降ったら、綿菓子屋さんだってお店を閉めるし、#nスケバンは公園に来ません。"
10049060-133 = "でも、スズミさんは違うじゃないですか！"
10049060-134 = "雨の日だって関係ない。治安を守るために、いつだってパトロールしてます。#nそれが、スズミさんとスケバンの違いなんです！"
10049060-135 = "スズミさんは、いつも正義の味方なんです！#n――魔法少女みたいに！"
10049060-136 = "いつも……正義の味方。"
10049060-137 = "そう言ってくれて、ありがとうございます。"
10049060-138 = "とても、嬉しいですが――"
10049060-143 = "――申し訳なくも……思っています。"
10049060-144 = "スズミさん……。"
10049060-145 = "自警団……辞めないですよね……？"
10049060-146 = "…………。"
10049060-148 = "[ns] \"レイサ。\""
10049060-149 = "先生？"
10049060-150 = "[s] \"ちょっと、こっちに……。\""
10049060-155 = "どうしたんですか？"
10049060-156 = "[s] \"少し、スズミに考える時間をあげよう。\""
10049060-157 = "ですが……スズミさんが自警団を辞めちゃうかもって考えたら――"
10049060-158 = "胸が……チクチクするんです。"
10049060-159 = "私は、スズミさんに助けてもらったのに……。"
10049060-160 = "まだ、何の力にもなれてないから……。"
10049060-161 = "これじゃあ、借りを返せないままで……。"
10049060-162 = "[ns] \"スズミは、それを貸しだとは思ってないはずだよ。\""
10049060-164 = "[ns] \"今は、スズミのことを信じてあげよう。\""
10049060-170 = "…………。"
10049060-178 = "[ns] \"スズミ。\""
10049060-179 = "……先生。"
10049060-181 = "ずずっ……すんっ……。#nマシロです。皆さん、聞こえますか？"
10049060-185 = "……はい、聞こえています。"
10049060-186 = "……もしかして、塔の上は寒いのでしょうか？いま、鼻をすする音が聞こえたような。"
10049060-187 = "大丈夫です。……すんっ。"
10049060-188 = "それよりも、近くにターゲットを発見しました。"
10049060-189 = "[ruby=こまかぜ]河駒風[/ruby]ラブ……らしきものを捕捉しています。"
10049060-190 = "[s11] \"ラブ――\"\n[s12] \"――らしきもの？\""
10049060-193 = "詳細までは不明です。現場での確認をお願いします。"
10049060-198 = "スズミさん……。"
10049060-199 = "……。"
10049060-200 = "……はい。#n準備は……できました。"
10049060-201 = "[ns] \"スズミ。\""
10049060-203 = "[ns13] \"正義実現委員会も、自警団も関係ないよ。\"\n[ns14] \"私はスズミとレイサを信じてるよ。\""
10049060-206 = "……。"
10049060-207 = "……はい。"
10049060-208 = "ひとまず、請け負った任務は全うしないといけませんね。"
10049060-209 = "対象の確認に向かいます。"
