[translation]
10049055-12 = "[ns] \"マシロ、威嚇射撃ならできる？\""
10049055-13 = "……申し訳ありません。"
10049055-14 = "まだ発砲許可が下りていません。"
10049055-15 = "それに、いま皆さんがいるのはゲヘナのエリアです。"
10049055-16 = "私にはどうすることも……本当に、申し訳ありません……。"
10049055-17 = "正義は……負け、ません……もう一度……！"
10049055-2 = "はぁ……はぁ……。"
10049055-25 = "もう……やめてください……！"
10049055-27 = "こいつら、何なの？全然相手にならないじゃない。"
10049055-28 = "強そうに見えたけど……警戒して損したわ。"
10049055-29 = "じゃ、これでおしまい。"
10049055-3 = "うっ……はぁ……。"
10049055-30 = "……！"
10049055-34 = "え？魔法少女が負けたのか？"
10049055-35 = "まっさか～それだとショーがおかしくなっちゃうじゃん？"
10049055-36 = "うーん、そうかな？#nそれより、さっきのアクション見た？超リアルだったよね！"
10049055-37 = "……ん？"
10049055-38 = "ショー……？これが……？"
10049055-4 = "（レイサさんのショットガンも、私の閃光弾も……まともに使えませんでした）"
10049055-40 = "テルミットホワイト！ピンク！"
10049055-41 = "負けるなー！がんばえー！うわぁーん！"
10049055-42 = "魔法少女はせいぎの味方、って言ってたじゃん！負けるなー！うわぁーん！"
10049055-43 = "うわぁーん！悪いヤツ大っ嫌い！！"
10049055-45 = "うぅっ……はぁ……。"
10049055-46 = "少し……確認したいことがあるだけだと……言ったじゃないですか……。"
10049055-47 = "魔法少女のスーパースター、テルミットピンクは負けません……！"
10049055-49 = "（えー、なによこれ……）"
10049055-5 = "（子供がいる状況では、とても……）"
10049055-50 = "（子供らは泣くし、あいつらはまだ立ち上がるし）"
10049055-51 = "（それに、うちが悪いヤツ……？さっぱり状況が分かんないんだけど……）"
10049055-55 = "ぐぬ……ぐぬぬ……！"
10049055-56 = "ぐあーっ！ヤーラーレーター！"
10049055-58 = "隊長！？"
10049055-6 = "（なにより……迷いがあるせいで、戦闘に集中できませんでした……）"
10049055-60 = "や、やっぱり、強いなぁ！なんとかホワイト！ピンク！"
10049055-61 = "あ、あんたらがいるなら……えっと……。"
10049055-62 = "――遊園地は安全だな！"
10049055-68 = "い、いきなりどうしたんですか！？"
10049055-69 = "勝ったのはうちらですよね！？"
10049055-7 = "（こんな調子では、何も守れませんね……）"
10049055-73 = "バカ！空気読みなさいよ！#nうちらは目的さえ達成すればいいんだから！"
10049055-74 = "早くあれ持って逃げて。お前たちはターゲットに集中しなさい！"
10049055-75 = "は、はいっ！"
10049055-76 = "あんたらの勝ちだー！"
10049055-8 = "（やはり、私は……）"
10049055-83 = "わっ――"
10049055-84 = "わああぁぁぁ！！！"
10049055-85 = "勝ったぁ！"
10049055-87 = "[ns1] \"ここでいったん休憩でーす！\"\n[ns2] \"二人とも、立てる？\""
10049055-91 = "先生……。"
