[translation]
10049100-1 = "第10話;フィナーレ"
10049100-107 = "我が眷属にして忠実[ruby=しもべ]な僕、[/ruby]悪の商人「シルバープレート」！"
10049100-108 = "人混みに紛れて暗躍するとは、驚きの計画だわ！"
10049100-109 = "ヘヴィキャリバーズ！これで勝負は決まったも同然ね！"
10049100-11 = "[ns] \"マシロ！支援はできそう？\""
10049100-110 = "この私――悪の幹部エラと、悪の商人シルバープレートが「悪の騎士団」を結成した以上、お前たちに勝ち目はない！"
10049100-111 = "我々を倒すには、多くの者の助力が必要でしょうね……。"
10049100-112 = "オーッホッホッホ！！我ら悪の騎士団の勝利よ！"
10049100-113 = "え……？"
10049100-114 = "シルバープレートって、今の……私に言ってました……か？"
10049100-118 = "えー、こほん。"
10049100-119 = "ショーの途中ですが、ここでちょっとだけご案内いたします！"
10049100-12 = "状況報告はしていますが、まだ許可が下りていません。"
10049100-121 = "シミコさん？なにを……。"
10049100-122 = "いつものシミコさんに戻りました！"
10049100-124 = "いま、悪の商人シルバープレートが皆さんの周りに隠れています！"
10049100-125 = "ヘヴィキャリバーズは、シルバープレートを見失っているみたいです！"
10049100-126 = "そこで――"
10049100-127 = "皆さんの力を貸していただきたいんです！"
10049100-128 = "シルバープレートは、銀髪で白い服を着ています！"
10049100-129 = "見つけたら、お手持ちのサイリウムか#nスマホのフラッシュライトで教えてください！"
10049100-13 = "介入については、委員会で協議中とのことです。"
10049100-130 = "皆さんの応援で、ヘヴィキャリバーズを、シルバープレートのところまで導きましょう！"
10049100-131 = "え、ええ……！？"
10049100-132 = "あっ、ここにいるよ！"
10049100-133 = "しーっ！"
10049100-134 = "あははっ！ポップコーンのフクシューだ！"
10049100-136 = "さあ、力を合わせてください！！"
10049100-14 = "引き続き、ターゲットの追跡を続けます！"
10049100-143 = "あっ、こっち来た！"
10049100-144 = "面白いね！通ったところが全部光ってる！"
10049100-145 = "これなら、位置が分かります……！"
10049100-146 = "良いアイデアじゃない。"
10049100-147 = "まるで魔法みたいです！みんなの力が起こした奇跡ですね！"
10049100-148 = "……あっ、つい見入ってしまいました。#n人混みを抜ける前に捕まえましょう！"
10049100-15 = "しつこいですねっ！！"
10049100-152 = "じゃあ、うちはこっちから行くわ！"
10049100-153 = "では私はこちらを担当します！"
10049100-158 = "ぜぇ、ぜぇ！何なんですか、もう！"
10049100-159 = "完璧な計画だったのに！#n言葉一つで数百人を動かすなんて想定外です！"
10049100-16 = "こうなったら……[ruby=いんようすい]陰陽水[/ruby]入りの閃光弾をお見舞いしちゃいますっ！！"
10049100-163 = "広場！"
10049100-164 = "あの境目を越えれば――"
10049100-172 = "あぅっ！？"
10049100-173 = "ここまでです！"
10049100-174 = "大人しく投降してください！"
10049100-175 = "まだ――！"
10049100-179 = "うっ！"
10049100-180 = "なぜ私の邪魔をするんですか！？"
10049100-181 = "粗悪品を売って、子供を騙して。"
10049100-182 = "さらに、嘘の商品をつかまされて被害が出ています。"
10049100-183 = "そもそも、遊園地でそういった爆発物は売ってはいけません。"
10049100-188 = "ぎゃぁあっ！"
10049100-193 = "！！"
10049100-194 = "これはただの爆発物じゃありません！ゲルマニウム手榴弾です！血行促進にもってこいなんですから！"
10049100-195 = "あっ、なるほど！もしかして……商品が気に入らなかったとか？"
10049100-196 = "困るんですよねぇ……納得して購入いただいてるのに……。#nですが、分かりました。分かりましたよ！今回だけ特別に返金してあげますから！"
10049100-197 = "あなたからは何も買っていません。"
10049100-198 = "だったらどうして！？なんでこんなことするんですか！#nまさか、誰かの指金ですか！？"
10049100-199 = "いいえ。自分の正義に従っているだけです。"
10049100-200 = "あなたは、なにを言ってるんですか……！？#nそんなの、何の利益にもならないじゃないですか！"
10049100-201 = "んん？よーく見れば、トリニティの生徒さんっぽいですけど……気づいてます？"
10049100-202 = "ここはゲヘナのエリアです！他の自治区で騒ぎを起こすつもりですか？"
10049100-203 = "それに、もう弾切れなんでしょう？全部お見通しですから！"
10049100-205 = "……。"
10049100-209 = "スズミさん！"
10049100-21 = "閃光弾！？"
10049100-210 = "マシロさん、支援をお願いできませんか……？"
10049100-212 = "ごめんなさい。#n現状、ターゲットはゲヘナのエリアにいるため、交戦規定に反しています。"
10049100-213 = "現在発砲許可の確認を行っています。少々お待ち下さい。"
10049100-214 = "そんな……！"
10049100-215 = "正義実現委員会なら引っ込んでてもらえますか？#nこっちは真っ当なビジネスをやっているんですから！"
10049100-216 = "……。"
10049100-217 = "私は、正義実現委員会ではありません。"
10049100-218 = "え、そうなんですか？"
10049100-219 = "なーんだ、それならそうと早く言ってくださいよ。#nそういうことなら、私も暇ではありませんので。これで失礼し――"
10049100-22 = "（っ！先生のほうへ！？）"
10049100-220 = "3つ、最後にお伝えします。"
10049100-224 = "1つ、先生のほうへ閃光弾を投げないでください。危険でしょう。#nもしも当たったら、どうするつもりなのですか。"
10049100-228 = "2つ、私は正義実現委員会ではありません。正義実現委員会になれなかったのも事実です。"
10049100-23 = "[ns] \"え、ええ！？\""
10049100-232 = "そして、3つ。"
10049100-234 = "もしかして……#n入りたくても、正義実現委員会には入れなかったのか？"
10049100-236 = "私は、集団に馴染めず逃げてしまった……正義実現委員会、失格です。"
10049100-238 = "いきなり何の話ですか！？"
10049100-239 = "では、より分かりやすく言ってあげましょう。"
10049100-240 = "今、あなたの目の前にいるのは――"
10049100-242 = "お前だって、うちらと一緒じゃんか！"
10049100-244 = "……。"
10049100-249 = "……不良も同然の存在ですよ。"
10049100-250 = "はい！？"
10049100-254 = "いたっ！"
10049100-260 = "これは、どういう……？"
10049100-261 = "ですが、今回の件で分かったことがあります。"
10049100-264 = "誰かを守る力がこの手にあって、たとえそれが正義ではなくとも。#nその力を私が私の手で正しく使うことができるのであれば――"
10049100-267 = "それだけで十分なんです。"
10049100-27 = "[ns] \"スズミ！？大丈夫！？\""
10049100-271 = "結果として――正義は後からついてくるもの、ですから。"
10049100-272 = "あ、これ閃光――"
10049100-279 = "ひっぎゃぁぁああぁぁぁあああっー！"
10049100-28 = "先生こそ、大丈夫ですか？"
10049100-280 = "め、目がぁぁあああぁぁ！"
10049100-281 = "うああぁぁあああぁぁ！！"
10049100-283 = "えっ、何！？どういう状況！？"
10049100-288 = "あっ、そこは境界線ですよ！"
10049100-289 = "ようこそ！トリニティ自治区へ！"
10049100-29 = "お怪我は……ないみたいですね。良かったです。"
10049100-291 = "え、ええぇっ！？"
10049100-292 = "ターゲットの、トリニティ自治区への進入を確認。#n――発砲許可、下りました。いつでも撃てます。"
10049100-293 = "スズミさん、必殺技のセリフ！まだ覚えてますか！？"
10049100-294 = "もちろんです。"
10049100-296 = "ちょっ、ちょっと待ってくださいっ！！"
10049100-298 = "みんなの平和のために！#n誰ひとり分かってくれなくても！どんなときだって！"
10049100-299 = "私たちは……今日も守ってみせる！"
10049100-3 = "み、道を空けて下さーいっ！！"
10049100-30 = "[s] \"スズミが守ってくれたおかげだよ！\""
10049100-304 = "マジカル――テラマキナ！！"
10049100-31 = "私が……先生を守ったおかげ。"
10049100-313 = "狙撃は反則ですよぉぉぉぉぉぉぉ！！"
10049100-322 = "あっ！花火！"
10049100-323 = "綺麗だね……。"
10049100-324 = "良いショーだったね。こんなの初めてだよ。"
10049100-326 = "今日、すっごく楽しかった！！"
10049100-327 = "ね、ね、ヘヴィキャリバーズごっこしよ？"
10049100-328 = "いいよ！やろやろ！"
10049100-329 = "正義は、勝ちます！"
10049100-330 = "皆さん、お疲れ様でした！"
10049100-334 = "レイサさん、シミコさん、マシロさん、ヘルメット団の皆さん……。"
10049100-335 = "……先生。"
10049100-336 = "[ns] \"スズミ！\""
10049100-340 = "自警団――本日のパトロールを完了しました！"
10049100-35 = "誰かを守れる力が……まだ私にもあったんですね。"
10049100-353 = "ちょっと！うちの褒賞金ふっ飛んだじゃない！！！！！！"
10049100-354 = "魔法少女ヘヴィキャリバー～エラの野望と正義の資格～"
10049100-36 = "てー、て……なんとかホワイト！先生も！このままじゃ逃げられるわよ！"
10049100-37 = "あと……いい加減、先生から離れたら？"
10049100-38 = "！！"
10049100-43 = "た、ターゲットを追いかけます！"
10049100-53 = "部長！こっちです！早くゲヘナ側に――"
10049100-60 = "ぐあっ！！"
10049100-62 = "思ったよりも数が多いです。#n戦闘が長引くと、周りにも被害が……！"
10049100-67 = "ホワイト！もう弾切れです！"
10049100-68 = "私も、これが最後の弾倉です……！"
10049100-69 = "ちっ、うちも弾切れ。もっと持ってくるんだったわね……。"
10049100-70 = "ふふ……ふふふ……これは大ピンチ！#n――ですが！"
10049100-76 = "この程度で……[ruby=あづま]吾妻[/ruby]ミライを仕留められると思わないでください！#n私の華麗な動きで――！"
10049100-78 = "ああっ！！それは自警団専用のセリフですよ！勝手に使わないでください！！"
10049100-79 = "おっ！良いところに人混みが！ちょーっと失礼しますよ！"
10049100-8 = "ちょっと、押さないでよ！"
10049100-85 = "いたっ！足踏んだの誰！？"
10049100-86 = "しーっ！居場所がバレちゃうじゃないですか！騒がないでください！"
10049100-87 = "この人もショーのキャストなの？"
10049100-89 = "人混みに紛れて……どこにいるか分かりません！"
10049100-9 = "な、なに？魔法少女に追われてる？"
10049100-90 = "身をかがめて移動しているようですね……。"
10049100-91 = "この先はゲヘナのエリア……困りました。"
10049100-95 = "……あれ？シミコさんは今どちらに……。"
10049100-99 = "ついに来たか、我が眷属よ！"
