[translation]
10049075-11 = "違うわよ！うちが言ってるのは魔法少女のほう！！"
10049075-12 = "仲間なのに攻撃してきてるじゃない！"
10049075-17 = "ぎゃあっ！"
10049075-19 = "テルミットホワイト！スタナグちゃんに回復魔法をかけてあげてください！"
10049075-2 = "マスコットを攻撃するなんて、あんたら正気か！？"
10049075-20 = "わ、分かりました！"
10049075-27 = "回復魔法！？[ruby=えいこうだん]曳光弾[/ruby]とナパーム弾でしょうが！！"
10049075-28 = "安心してください！#n[ruby=回復魔法]スラッグ弾[/ruby]をありったけ撃ち込んであげますから！"
10049075-29 = "がんばれ、スタナグちゃん！"
10049075-36 = "味方役なんじゃないの！？"
10049075-38 = "これでとどめよ！！"
10049075-39 = "ヒーリングドラゴンブレス！"
10049075-4 = "それが……むしろ攻撃されるのが正しいと言いますか……。"
10049075-45 = "ぐあっ……！"
10049075-5 = "あの怖そうなやつは敵役なので……うわああっ！"
10049075-50 = "スタナグちゃん！！"
10049075-51 = "大丈夫だよ！倒れたって……スタナグちゃんはすぐ立ち上がるもん！"
10049075-52 = "そうそう！毎回ボコボコにされて、いっつも回復してもらってるよね！"
10049075-54 = "そんな……マスコット……いない、わよ……。"
10049075-59 = "マジカル・キュア・ロープで縛って――"
10049075-63 = "マジカル・キュア・テープで口を塞いでおきました！"
10049075-64 = "エラ！スタナグちゃんの仇は、必ず取ってみせます！"
10049075-65 = "――スタナグちゃんを治療したら、また戻ってきますからね！"
10049075-69 = "[ns5] \"みんなー！休憩時間だよ！\"\n[ns6] （シミコもついて来てね！）"
10049075-75 = "結局あんたら、何のつもりなのよ。"
10049075-76 = "変な格好だし、うちらにこんなことして……。"
10049075-85 = "それ……車のバッテリーじゃないわよね！？"
10049075-86 = "隊長！うちら、もしかして……白状するまで電流を……！"
10049075-87 = "白状することもないのに！？"
10049075-88 = "待て待て待て待て！！"
10049075-93 = "ぎゃあああぁぁぁっ！！"
