[translation]
10049010-1 = "第1話;自警団の資格"
10049010-10 = "お前、あれだろ？"
10049010-100 = "他からも支援がくるって話だ。それもあわせれば十分じゃねぇかな。"
10049010-101 = "ならいい。#n……そろそろ行こう。誰かに聞かれちゃマズいしな。"
10049010-103 = "（こ、こっちに来る……！？）"
10049010-104 = "（早く逃げないと……！）"
10049010-11 = "[ruby=・   ・   ・]自警団[/ruby]とかってやつの、「トリニティの走る閃光弾」。"
10049010-111 = "はぁ……はぁ……。"
10049010-112 = "あの二人の話……本当なんでしょうか。"
10049010-113 = "今週末、「ボーダーランド遊園地」で……怪我人が出る……。"
10049010-114 = "ラブ隊長の指示……とも言っていましたし……。"
10049010-115 = "放っておくわけにはいきませんよね。まずは通報を……。"
10049010-119 = "ひゃうっ！"
10049010-120 = "……。"
10049010-121 = "すっ、すみません……って、スズミさん？"
10049010-122 = "ちょうどよかったです！"
10049010-123 = "旧図書館の倉庫裏で、ヘルメット団が悪巧みをしているんです！"
10049010-124 = "自警団にお願いできませんか？"
10049010-125 = "えっ？#n……あっ、はい。"
10049010-126 = "であれば――"
10049010-130 = "だから、うちらと一緒だって言ってんだよ。"
10049010-134 = "[log=불량배 스케반 A]もしかして……入りたくても、#n正義実現委員会には入れなかったのか？[/log]"
10049010-137 = "……。"
10049010-138 = "スズミさん？"
10049010-139 = "一緒に、通報しに行きましょうか。"
10049010-140 = "おそらくこれは……正義実現委員会の仕事ですから。"
10049010-141 = "え……？そう、なんですね……？"
10049010-142 = "わ、分かりました！行きましょうか。"
10049010-143 = "……。"
10049010-16 = "……そうとも呼ばれていますね。"
10049010-17 = "お前にこんなことする資格あんのか？"
10049010-18 = "黒くねぇってことは、正義実現委員会ってわけでもないみてぇだし。"
10049010-19 = "自警団ってのも、勝手に名乗ってるだけなんだろ？"
10049010-2 = "トリニティ付設幼稚園・旧校舎"
10049010-20 = "たしかに、私は正義実現委員会ではありません。"
10049010-21 = "ですが、治安を守る行為に資格が必要なのですか？"
10049010-22 = "だから、うちらと一緒だって言ってんだよ。"
10049010-23 = "関係ねぇ事に首突っ込んで、暴力で邪魔をする。#nしかも、うちらと違って正義面してるだけ質が悪ぃ。"
10049010-24 = "なんで自警団なんかやってんだ？誰も分かっちゃくれねぇだろ？"
10049010-25 = "もしかして……#n入りたくても、正義実現委員会には入れなかったのか？"
10049010-26 = "！！"
10049010-27 = "資格もねぇのに暴力を振るう……これって犯罪だと思うんだけどな。"
10049010-28 = "まぁ、もういいよ。こんなとこ、二度と来ねぇから。"
10049010-3 = "お前だって、うちらと一緒じゃんか！"
10049010-32 = "え？えぇ……？"
10049010-36 = "……。"
10049010-41 = "お、おい。いいのか？あんなこと言っちゃって……。"
10049010-42 = "気にするこたぁねぇ。"
10049010-43 = "ほら、あれ見ろよ。"
10049010-45 = "……。"
10049010-47 = "あいつにはもう、何もできやしねぇ。"
10049010-48 = "図星ってことさ。うちの言葉、相当効いたみたいだぜ？"
10049010-49 = "い、今のうちに逃げるぞ！"
10049010-5 = "え？"
10049010-55 = "誰も分かってくれない……。"
10049010-56 = "正義実現委員会に入れなかった……。"
10049010-57 = "今までやってきたことは、犯罪……。"
10049010-58 = "……そう、なんですか？#n私の行いは――"
10049010-6 = "おいバカやめろ！また閃光弾投げられるぞ！"
10049010-63 = "トリニティ旧図書館"
10049010-64 = "新刊はこっちで……。"
10049010-65 = "他の図書館に寄贈する本はこっち……。"
10049010-7 = "いえ……既に無力化した相手にまで、わざわざ攻撃はしません。"
10049010-70 = "よし！これで整理は終わりですね！"
10049010-71 = "あっ、もうこんな時間……早く帰らないと。"
10049010-75 = "……あれ？話し声が……倉庫の裏手から……？"
10049010-79 = "じゃあ、今週末でいいんだな？"
10049010-8 = "それより、今なんと？"
10049010-80 = "ああ。その日にしようって、ラブ隊長が。"
10049010-81 = "集合場所は……「ボーダーランド遊園地」だっけ。"
10049010-85 = "（ヘルメット団？どうしてこんな場所に？）"
10049010-86 = "（そういえば……人通りが少ないから、密会に使われているって噂がありましたね）"
10049010-87 = "（バレないうちに退散しないと……）"
10049010-89 = "こりゃあ、遊園地がめちゃくちゃになりそうだな。"
10049010-9 = "「うちらと一緒」……？"
10049010-90 = "！"
10049010-94 = "逃すわけにはいかないんだ。仕方ないさ。"
10049010-95 = "怪我人もそうとう出るだろうな。"
10049010-96 = "まあ、向こうの出方次第だろ。"
10049010-98 = "（怪我人？いったい何を企んでいるのでしょう……？）"
10049010-99 = "でも、うちらだけで足りるのか？"
