[translation]
10049050-1 = "第5話;追跡！ヘルメット団！"
10049050-10 = "！！"
10049050-100 = "うわっ、いつの間に！？"
10049050-101 = "追い越されたってこと！？"
10049050-103 = "退路はテルミットピンクが塞ぎました！#n大人しくヘヴィキャリバーズに投降してください！"
10049050-105 = "ヘヴィキャリバーズ……？"
10049050-106 = "街の子供らが遊んでるおもちゃだっけ？"
10049050-107 = "あんたらって……あれなの？何かに熱中してる――"
10049050-109 = "マニアですよ。いや、オタク……かも？"
10049050-11 = "身元の特定と、脅威の有無について確認をお願いします。"
10049050-110 = "それより、なんでピンクなんだ？紫色だし、パープルじゃない？"
10049050-112 = "理由を説明したらネタバレになってしまいますので、本編を見るのをおすすめします！"
10049050-113 = "（私たちの正体には気づいていないようですね。それは助かりますが……）"
10049050-117 = "あっ！イマーシブ・シアターが始まったみたい！"
10049050-118 = "何それ？"
10049050-119 = "ステージを飛び出して、色んな場所を舞台にするショーだよ！"
10049050-12 = "現在は荷車を引きながら移動中です。"
10049050-120 = "あ！ピンクとホワイト！ここにいた！"
10049050-121 = "悪いヤツとたたかってる！"
10049050-125 = "（困りました……観客がどんどん集まってきていますね……）"
10049050-126 = "（子供もいる状況では、閃光弾を使えません）"
10049050-127 = "（ひとまず、話し合いでなんとかするしか……）"
10049050-128 = "少々確認したいことがありますので、ご同行願えますか？"
10049050-129 = "[s] \"ちょっとお話しない？\""
10049050-13 = "積荷には……ポップコーンバケットと、手榴弾のようなものが見えます……！"
10049050-131 = "げっ、シャーレの先生！？"
10049050-132 = "そこまでして邪魔したいってこと？#nそれなら――"
10049050-133 = "お前ら！準備はいいか？"
10049050-135 = "はい！隊長！"
10049050-136 = "いつでも！"
10049050-138 = "じゃあ――"
10049050-139 = "攻撃、開始！"
10049050-15 = "[ns] \"手榴弾！？\""
10049050-16 = "ここからでは不明瞭で、たしかなことが言えません。"
10049050-17 = "接近し、現場での確認をお願いします。"
10049050-2 = "……。"
10049050-21 = "隊長、これで全部ですか？"
10049050-22 = "そんなわけないじゃない。やるからには徹底的にやるわよ。"
10049050-23 = "さすが隊長！これで大儲けですね！"
10049050-24 = "次はこの辺のはずだけど……なんか急に混んできてない？"
10049050-25 = "ですね。#n……おい、道を塞ぐなよ！"
10049050-3 = "はぁ……はぁ……。"
10049050-30 = "あ……。"
10049050-31 = "え……？"
10049050-32 = "隊長？どうかしました？"
10049050-33 = "いや、その……。"
10049050-34 = "ステージに立ってる、あのピンク色の服を着たやつ。"
10049050-35 = "え？ただのキャストじゃないですか？子供向けのショーだし。"
10049050-36 = "たぶん会ったことはないんだけど……。"
10049050-37 = "ここからでも分かる。"
10049050-38 = "強いわね、あいつ。"
10049050-45 = "逃げろ！！"
10049050-49 = "はい！？"
10049050-59 = "河駒風ラブを確認しました！その他に、ヘルメット団が2名！"
10049050-60 = "ゲヘナエリアのほうへ逃走しました。追跡を開始します！"
10049050-64 = "スズ――テルミットホワイト！ショーはまだ……！"
10049050-66 = "ステージから飛び降りた！？"
10049050-67 = "どういうこと！？"
10049050-69 = "テルミットホワイト！"
10049050-7 = "ステージから観客席を基準に2時の方向、見えますか？"
10049050-70 = "こ、これも演出なのか！？"
10049050-75 = "[ns] \"ついて行こう！\""
10049050-76 = "はい！"
10049050-78 = "スズミさん！確認だけで十分です！"
10049050-79 = "ゲヘナエリアに入られたら、正義実現委員会は支援をできません！"
10049050-8 = "[ruby=こまかぜ]河駒風[/ruby]ラブを始め、ジャブジャブヘルメット団と推定される3人組を発見しました。"
10049050-80 = "分かっていますが……事態は一刻を争います。"
10049050-81 = "積荷に、大量の手榴弾……のような物が見えました。"
10049050-82 = "支援は大丈夫です。"
10049050-83 = "私が、なんとかします。"
10049050-84 = "ピンクもいますよ！"
10049050-88 = "ぜぇ……ぜぇ……！"
10049050-89 = "隊長！あいつら何者なんですか！？"
10049050-90 = "知らないわよ！でも、追ってくるってことは敵なんでしょ！"
10049050-91 = "ステージの上でショーをやってたみたいですし……。"
10049050-92 = "もしかして、これも演出なのかも……？"
10049050-93 = "そんな危ないこと、子供向けでやる！？"
10049050-94 = "止まってください。"
