[translation]
10049070-1 = "第7話;スタナグちゃん頑張る"
10049070-3 = "35度の方向、ゆっくりと移動しています。"
10049070-4 = "推定相対距離は70ヤード。"
10049070-5 = "ターゲットの目印は黄色です。"
10049070-7 = "[ns1] \"黄色？\"\n[ns2] \"ラブの服ってそんな色だったっけ？\""
10049070-10 = "う～ん……白と赤に、黒とグレーがちょっと混じった――"
10049070-11 = "いちご大福みたいな見た目でしたよね？"
10049070-12 = "それはこの目で確かめましょう。#n黄色……あの方ですね。"
10049070-16 = "隊長！またあいつらです！"
10049070-17 = "げっ、あんたらも懲りないわね……。"
10049070-19 = "……なぜそのような格好を？"
10049070-20 = "あんたらも大概だと思うけど！？"
10049070-21 = "ってか、これ知らないの……？"
10049070-23 = "おかしいですね……シリーズを間違えたかもしれません……。"
10049070-24 = "そ、それは……まほリバのマスコット、「スタナグちゃん」ですね！"
10049070-25 = "力は弱いけど、ホワイトとピンクを助ける優しい子です！"
10049070-26 = "ふっふっふ。その通りよ！"
10049070-27 = "あんたらがやってるショーの内容は調べさせてもらったわ！"
10049070-28 = "これでもう邪魔できないでしょ？#nまさか、仲間を攻撃したりしないわよね？"
10049070-32 = "おっ、午後のショーが始まるみたいだよ！"
10049070-33 = "なんか増えてない？"
10049070-35 = "また会ったね！テルミットホワイト！ピンク！"
10049070-36 = "スタナグちゃんもいる！"
10049070-38 = "これでもう、手も足も出ないでしょ？"
10049070-39 = "大人しく引っ込んでるのが身のためよ！"
10049070-41 = "オーッホッホッホ！"
10049070-42 = "ヘヴィキャリバーズと、その他の雑魚よ！"
10049070-49 = "この声……聞き覚えが――"
10049070-50 = "あるような気も……ないような気も……。"
10049070-51 = "[ns] \"これは……？\""
10049070-55 = "よくもまあ、好き勝手暴れてくれたわね。"
10049070-56 = "今度は何！？"
10049070-58 = "誰ですか！？"
10049070-60 = "[ns3] \"あれは……！図書委員会のシミコ！\"\n[ns4] \"あれは……！悪の幹部、エラ！\""
10049070-63 = "シミコさん……なんですか！？"
10049070-64 = "今まで連絡も取れなかったのに……まさか、ここで！？"
10049070-66 = "テルミットホワイト、テルミットピンク。それに……憎たらしいスタナグ。"
10049070-67 = "全員同じ場所にいてくれて助かったわ。"
10049070-68 = "この私――エラの力の前にひれ伏すがいい！"
10049070-70 = "悪の幹部のエラだ！"
10049070-71 = "ホワイトとピンク、勝てるかな……。"
10049070-73 = "悪の……幹部？"
10049070-75 = "スタナグちゃん、今日もボコボコにされちゃうのかな……。"
10049070-76 = "え……？"
10049070-77 = "まさか……。"
10049070-78 = "スタナグちゃん、がんばれー！"
10049070-79 = "冗談でしょ――"
10049070-80 = "私の魔法と踊りなさい！"
10049070-81 = "どうしてこうなるのよ！！！"
