[translation]
10049120-1 = "後日談その2;未来は明るい"
10049120-10 = "あっぷあっぷ！私！金づち……なのに！"
10049120-11 = "このままじゃ……あっぷ！魚の餌に……ぶくぶく……。"
10049120-12 = "ごぼぼぼぼ……。"
10049120-16 = "なんだ、浅いじゃん。"
10049120-18 = "まったく、溺れるところでしたよ……。"
10049120-28 = "私のゲルマニウム爆弾が……！？#nそんな……預金残高がどんどん爆発していって……。"
10049120-29 = "もうおしまいだ……明日からどうやって生きていけば――"
10049120-3 = "ああああぁぁぁ――"
10049120-33 = "そんなぁっ……！ブレスレットまで切れちゃうなんて……！いよいよ、私……。"
10049120-34 = "……あれ？でも、前からずっとつけてたのに、よりによって今……？"
10049120-35 = "運気を上げるゲルマニウムブレスレット……。"
10049120-36 = "まるで……今まで私を守ってくれてたみたいに……。"
10049120-4 = "ああああああぁぁぁぁぁ――"
10049120-41 = "今月のイチオシはこれでいきましょう！！"
10049120-5 = "ああああああああ――っ！！"
10049120-9 = "うぼあっ！"
