[translation]
10049110-1 = "後日談その1;お元気ですか？"
10049110-10 = "次のニュースです。"
10049110-103 = "待ってください。"
10049110-104 = "なに？"
10049110-105 = "ちゃんとゴミ箱に捨ててください。"
10049110-106 = "えっ、めんど……#nちょっとジュースが飛んじゃってるし、触りたくないんだけど……。"
10049110-107 = "掃除する方も同じことを思うはずです。"
10049110-108 = "さあ、ちゃんと捨ててください。"
10049110-11 = "連邦生徒会は偽物や誇大広告を防止する条例案を――"
10049110-110 = "まぁ、じゃあ……。"
10049110-111 = "おい、それって隊長に命令してんのか？"
10049110-112 = "隊長！ここらで目にもの見せてやりましょう！"
10049110-113 = "え？いや……は……？"
10049110-114 = "（ちゃんと捨てとくつもりだったのに……）"
10049110-115 = "仕方ありませんね。レイサさん？"
10049110-116 = "はい！マジカル――！！！"
10049110-117 = "もう魔法少女はこりごりよ！！"
10049110-13 = "えっ、これだけですか？#nもっとこう……色々あるじゃないですか！"
10049110-14 = "「ホワイトがカッコよかった」とか、「ピンクが可愛かった」とか、#n「エラが怖かった」とか！"
10049110-15 = "いえ、あれで良かったと思いますよ。"
10049110-16 = "知らないままでいた方が幸せなこともありますから。"
10049110-17 = "はっ！たしかに！魔法少女の正体も、謎に包まれているもの……。"
10049110-18 = "魔法少女として有名にはなれませんでしたが……大丈夫です！#n私は、自警団のスーパースター[ruby=うざわ]宇沢[/ruby]レイサですから！"
10049110-19 = "レイサさんは元気いっぱいですね。"
10049110-20 = "あっ。こんにちは。"
10049110-21 = "お二人とは、ついさっきまで一緒にいた気がするのですが……最後にお会いしてから、もう3日も経ってるんですよね。"
10049110-22 = "ええ、３日前にお会いしましたね……？"
10049110-23 = "えっと……シミコさん、お疲れですか……？"
10049110-24 = "冗談です、冗談！"
10049110-25 = "シミコさんも冗談を言うんですね……！"
10049110-26 = "『これを読めばできる！ユーモアの鍛え方』という本を読んでいるところでして。"
10049110-27 = "買ったばかりなので、まだ数ページだけですが……この調子なら、すぐに読み終わりそうです。"
10049110-28 = "シミコさんは何事も丁寧に取り組まれますよね。"
10049110-29 = "まずは取扱説明書を読め、と言いますから。まさに本こそ、何かをするための説明書だと思うんです。"
10049110-30 = "もしかして……悪の幹部になるための勉強もしたんですか！？"
10049110-31 = "もちろんです。でも……時間がなくて、最低限になってしまいましたが。"
10049110-32 = "魔法少女を題材にした作品には触れてこなかったのですが、とても面白かったです。"
10049110-33 = "私も今、ヘヴィキャリバーズのアニメを観ているところでして。"
10049110-34 = "昨日、3期7話まで観たので、ホワイトの衣装がピンクである理由が分かりました。"
10049110-35 = "……正義に関する、とても良い話でした。"
10049110-36 = "おぉっ！"
10049110-37 = "ではぜひ、劇場版も必見ですよ！最近公開された『ヘヴィキャリバーズ・ブロークンアロー』も、とっても良かったですから！"
10049110-38 = "皆さんが見終わったら、私が解説しますね！"
10049110-4 = "次のニュースです。"
10049110-40 = "楽しみにしています。またいつでも図書館にいらしてくださいね！"
10049110-44 = "今日のパトロールは平和ですね。"
10049110-45 = "いつもの些細なトラブル以外は、穏やかなほうだと思います。"
10049110-46 = "スズミさんが元気になって、すーっごく嬉しいです！"
10049110-47 = "誰かを助けて、お礼を言われたときのスズミさんの顔が、一番カッコいいんですから！"
10049110-48 = "だから、スズミさんのいるこの町が大好きなんです！"
10049110-49 = "普段どんな表情をしていたか、自分でも分かっていませんでした。"
10049110-5 = "先週末、ボーダーランド遊園地のイベントが大盛況のうちに終わりました。"
10049110-50 = "教えてくれて、ありがとうございます。"
10049110-54 = "……。"
10049110-55 = "自警団……辞めないですよね？"
10049110-6 = "「魔法少女ヘヴィキャリバー・ボーダーランドスペシャル」と題されたこのイベントは、キャストによる公演が大変好評だったとのことです。"
10049110-60 = "ふふっ……。"
10049110-61 = "スズミさん？"
10049110-62 = "あれほど熱弁されて、辞めるわけがないじゃないですか。"
10049110-63 = "続けます。私はもう――迷いません。"
10049110-68 = "はー、美味しかったわね。"
10049110-69 = "お腹いっぱいですね！"
10049110-7 = "あまりに迫真の演技だったことから、キャストの正体について数々の憶測が飛んでおり――"
10049110-70 = "ちょっと食べ過ぎたかも……。"
10049110-71 = "食べられる時にはたくさん食べておけばいいのよ。"
10049110-75 = "げっ、あの時の変なやつら……！"
10049110-76 = "べ、別にうちらは何も悪いことしてないわよ！？"
10049110-77 = "いま攻撃されたらお腹がはち切れちゃう……。"
10049110-78 = "まだ何も言っていませんが……。"
10049110-79 = "……先日はありがとうございました。"
10049110-8 = "この件について遊園地の関係者は「個人情報のため、お答えすることはできない」と回答を避けた他、「次の公演をお楽しみください」と語りました。"
10049110-80 = "それと、褒賞金の件……台無しにしてしまい、すみません。"
10049110-81 = "飛んでいくの、カッコよかったです！ロケットみたいでした！"
10049110-82 = "ですが、事態を収められたのは皆さんのお陰です。本当にありがとうございました。"
10049110-83 = "別に、手伝ったつもりはないわ。"
10049110-84 = "それに褒賞金はパーになったけど、焼肉はたくさん食べられたし。もういいわよ。"
10049110-85 = "焼肉ですか！？"
10049110-86 = "先生が奢ってくれたの。この前のご褒美ってことで。"
10049110-87 = "めっちゃ食べましたねー。"
10049110-88 = "先生、お会計のときはちょっと悲しそうな顔してましたけど……。"
10049110-89 = "皆さんが報われて……良かったです。"
10049110-9 = "また、「公演の監督としてシャーレの先生が関わっていた」という噂もありますが、現時点においてシャーレからの正式な声明は出ていません。"
10049110-90 = "自警団にそんなこと言われるなんて、珍しいこともあるもんね。"
10049110-91 = "……ん。もう飲み終わっちゃった。"
10049110-92 = "シュート！"
10049110-96 = "あー、惜しい。"
10049110-97 = "入ってたらスリーポイントシュートでしたね。"
10049110-98 = "んじゃ、もう行くわよ。あんたらも元気でね。"
