[translation]
10049080-1 = "第8話;良いことをする資格"
10049080-2 = "わあぁ！う、うちらが悪かったから！！"
10049080-3 = "ゆ、許してぇ！隊長の弱点は全部言うからぁ！！"
10049080-4 = "た、隊長は握力が弱くて……瓶のフタを開けられないんだ！！"
10049080-5 = "あ、あと！二段ベッドの上だと怖くて眠れないんだ！！"
10049080-6 = "ちょっと！！！"
10049080-14 = "おぉー！"
10049080-15 = "ふぅ……。"
10049080-16 = "車のバッテリーがあって良かったです。"
10049080-17 = "まさか、電気が通っていないとは思いませんでした。"
10049080-18 = "……ところで、さっきは何のお話でしたか？"
10049080-19 = "[s1] \"ラブは瓶の蓋を開けられないんだって。\"\n[s2] \"ラブは二段ベッドの上が怖いんだって。\""
10049080-22 = "先生！！！"
10049080-23 = "そうでしたか。"
10049080-24 = "とりあえず、情報を整理させてください。"
10049080-25 = "まずシミコさん、その格好は一体……？"
10049080-26 = "これは、魔法少女ヘヴィキャリバーの悪の幹部「エラ」です。"
10049080-27 = "たしかに……そのようですが……。"
10049080-28 = "今まで、どこにいらしたんですか？"
10049080-29 = "えっと……私は悪役ですよね？"
10049080-30 = "そうですね。"
10049080-31 = "だとすれば、最初から一緒では話がおかしくなってしまうので……タイミングを見計らっていました。"
10049080-33 = "なるほど！完璧な登場でしたよ！"
10049080-34 = "[ns] \"思い返せばたしかに！\""
10049080-36 = "……。"
10049080-37 = "期せずして、奇襲に繋がりましたし……。"
10049080-38 = "一番必要なときに来てくれました。ありがとうございます。"
10049080-42 = "次は、[ruby=こまかぜ]河駒風[/ruby]ラブさん。"
10049080-43 = "ここまで長かったですが……やっとお話を聞けます。"
10049080-44 = "いくつか、伺いたいことがあります。"
10049080-45 = "この遊園地で何を企んでいたのですか？"
10049080-46 = "企む？だから何の話よ。"
10049080-48 = "3日前……トリニティの倉庫裏で話していましたよね？"
10049080-49 = "「遊園地がめちゃくちゃになって、怪我人が出る」って！"
10049080-50 = "現に、あんなにたくさんの手榴弾を持ち歩いていたわけですし。"
10049080-52 = "き、聞かれてたぁ！？"
10049080-53 = "だから、ああいうのはモモトークでって言ったのに！"
10049080-55 = "それ、どういうこと？"
10049080-56 = "遊園地をめちゃくちゃにする？怪我人を出す？"
10049080-57 = "うちはそんなこと指示してないわよ！？"
10049080-59 = "誤解です！そんなことするわけないじゃないですか！"
10049080-60 = "めちゃくちゃにできるだけの爆弾があるなら、撤去工事のバイトやってますって！"
10049080-61 = "ご飯もちゃんと食べれてないのに、そんな無茶できないですよ！"
10049080-63 = "じゃあ、あいつらが言ってるのは何なのよ？"
10049080-65 = "「ターゲット」のことを勘違いしてるんじゃないですか？"
10049080-66 = "たしか……ターゲットが抵抗したら戦闘になって、遊園地がめちゃくちゃになる……みたいな話はしたような……。"
10049080-68 = "待ってください。「ターゲット」とは誰ですか？"
10049080-69 = "誰を、なぜ狙っているのか。説明してください。"
10049080-71 = "教えてやれば、もう邪魔しないでくれるわけ？"
10049080-72 = "もちろんです。#n……悪いことをしているのでなければ、ですが。"
10049080-74 = "[ns] \"私からも保証するよ。\""
10049080-75 = "ちっ、先生まで……。"
10049080-76 = "分かった、分かった。はぁ……。"
10049080-77 = "今のうちらは、取り締まりの手伝いをやってるの。"
10049080-78 = "ヘルメット団がですか？#nそれはまた、どういう権限で？"
10049080-79 = "別にいいでしょ？良いことするのに権限なんて要る？"
10049080-83 = "うちらだって、稼げるんだったら良い仕事がしたいのよ。"
10049080-84 = "ヴァルキューレも、風紀委員会も、正義実現委員会にも、面倒をかけない仕事をね。"
10049080-85 = "で、仕事の内容なんだけど……最近、変なパチモンが出回ってるらしいの。"
10049080-86 = "その犯人を捕まえれば、褒賞金が出るって話。"
10049080-87 = "だから、うちらもひと稼ぎさせてもらおうと思ったわけ。"
10049080-89 = "パチモン……ですか？"
10049080-90 = "そう。うちらの荷車に積んである手榴弾みたいにね。"
10049080-91 = "なんか……よく分からない謳い文句だったわよ。ゲルマニウム手榴弾だ、とか。安全ピンの形が三角形だからトライアングルフォースで健康にいい、とか……。"
10049080-92 = "他に、安っぽいガラクタもいっぱいあったわ。"
10049080-93 = "空気が抜ける風船とか、作りの甘いポップコーンバケットとか。"
10049080-94 = "手榴弾とポップコーンバケットは押収したけど、まだ犯人は捕まえられてない。"
10049080-95 = "遊園地は広いし……このまま取り逃がしそうだけどね……。"
10049080-96 = "空気が抜ける風船……作りが甘いポップコーンバケット……？"
10049080-98 = "風船、つぶれちゃった……買ったばっかりなのに……。"
10049080-99 = "うわぁーん！ポップコーンバケットの蓋……壊れちゃったぁー！"
10049080-100 = "うわぁーん！"
10049080-101 = "店員さん！これ！新しいのに交換してよぉー！"
10049080-109 = "何？縄解いてくれるの？"
10049080-110 = "……ヘルメット団の皆さん。"
10049080-111 = "私の勘違いで、ご迷惑をおかけしてすみませんでした。"
10049080-113 = "はぁ？ここまで邪魔しておいて、謝って済むとは思わ――"
10049080-118 = "本当に、申し訳ございませんでした。"
10049080-122 = "え、ええっ！？……ああ、そう？"
10049080-123 = "誰だって勘違いくらいするもんでしょ？"
10049080-124 = "ちゃんと謝ってもらったし。はい、終わり！"
10049080-126 = "誤解をしてしまい、私もすみませんでした。"
10049080-127 = "ど、どうやってお詫びすれば……！"
10049080-129 = "もういいからっ！！！"
10049080-130 = "……改めて、事情は分かりました。"
10049080-131 = "もしよければ、私たちにもお手伝いさせていただけないでしょうか？"
10049080-132 = "え？急にどうしたのよ。"
10049080-133 = "仕事を邪魔したことに対して、行動でお詫びしたいのです。"
10049080-134 = "……そのターゲットは正義に反していると、ラブさんは思いますか？"
10049080-135 = "少なくとも、良いヤツではないでしょ。うちが言うのもなんだけど。"
10049080-136 = "では、善良な市民に被害を与えたのも事実ですね？"
10049080-137 = "あんな物買わされたら、うちだって怒ると思うわよ？"
10049080-138 = "……分かりました。"
10049080-139 = "犯人がいるであろう場所に、目星はついています。"
10049080-140 = "ここからは、[ruby=・   ・   ・]自警団[/ruby]がお手伝いします。"
10049080-142 = "……！"
10049080-143 = "はい！"
10049080-144 = "図書委員会も、全力でサポートしますね！"
10049080-146 = "[ns3] \"私も準備できたよ！\"\n[ns4] \"「シャーレの走る先生」も準備できたよ！\""
10049080-150 = "タダで手伝ってくれるっていうなら、断る理由はないわね。"
10049080-151 = "やつらの人数も分からないし。"
10049080-155 = "あんたら自警団と図書委員会だったの！？"
