[translation]
10049140-1 = "後日談その4;悪の幹部、誕生"
10049140-2 = "[log]3日前[/log]"
10049140-4 = "ここには、この子で。"
10049140-5 = "この子は……ここに。"
10049140-6 = "ふぅ……復元した子の整理も、これで一段落。"
10049140-7 = "ここも、この時間なら誰もいなくて快適なんだけど……。"
10049140-8 = "さて、古書館に戻――"
10049140-9 = "魔法少女……悪の幹部……。"
10049140-10 = "魔法少女は、世界の平和を守る……。"
10049140-11 = "ひっ――"
10049140-12 = "ひえぇぇっ……。"
10049140-16 = "悪の幹部は、悪役……。"
10049140-17 = "（なんだ……シミコか）"
10049140-18 = "（こんな時間に何を……寄贈する子の整理は終わっているはずでは……）"
10049140-19 = "悪役の悪の幹部は……魔法少女を断罪する……。"
10049140-20 = "！？"
10049140-21 = "（だ、断罪……？悪の幹部……？）"
10049140-22 = "（シミコに一体何が……？）"
10049140-23 = "（この手のことは放っておくに限るけど……）"
10049140-24 = "（シミコのことだし……もう少し様子を見よう……）"
10049140-28 = "（漫画を台車いっぱいに……？）"
10049140-29 = "（シミコはほとんどの本に目を通しているはず……どうして今更？）"
10049140-30 = "（しかも、軽く見積もって200冊はある……）"
10049140-34 = "……ぶつぶつ。"
10049140-35 = "ぶつぶつ……ぶつぶつ……。"
10049140-36 = "（目が怖い……！）"
10049140-37 = "（1冊読み終えるのに1分もかかってない……）"
10049140-38 = "（速読をできるのは知ってたけど……まさかここまでとは）"
10049140-39 = "（持ってきた子たちは……すべて魔法少女関連……？最近のお気に入り……？）"
10049140-41 = "……ぶつぶつ……この町ごと……吹き飛ばしてやる……。"
10049140-42 = "……よっし。"
10049140-46 = "（よっし！？なにが！？）"
10049140-47 = "（……よく見れば、魔法少女の漫画以外もある……）"
10049140-48 = "（『現代の犯罪心理学』……『大衆扇動術』……『衣類製造2級実技』……？）"
10049140-49 = "（どういう基準なんだろう……？）"
10049140-53 = "（結局、全部読み終わるまで見守ってしまった……）"
10049140-54 = "（今度は……視聴覚室？）"
10049140-55 = "（魔法少女モノのアニメがあんなに……）"
10049140-56 = "（映像となると、本の速読のようにはいかないのでは……？）"
10049140-61 = "（あ、始まった）"
10049140-62 = "（まあ……なんとかするか）"
10049140-63 = "（シミコがこの手の作品に興味を示すというのは新しい発見だったかも）"
10049140-64 = "（そろそろ古書館に戻ろう……）"
10049140-68 = "？"
10049140-69 = "（……倍速？）"
10049140-74 = "ひぇっ……。"
10049140-75 = "（な、なに……？どんどん早回しに……？）"
10049140-82 = "（30倍速！？）"
10049140-83 = "（おかしくないか！？）"
10049140-84 = "（1話がたったの50秒に……）"
10049140-85 = "（内容は全然入ってこないし……）"
10049140-86 = "（しかも画面の点滅で、目が……）"
10049140-87 = "（一旦帰って、明日聞いてみるか…···…)"
10049140-92 = "……。"
10049140-93 = "……。"
10049140-95 = "……。"
10049140-96 = "もう朝……結局、気になって一睡もできなかった……。"
10049140-97 = "シミコはもう帰ったのかな。"
10049140-98 = "……確かめないと。"
10049140-100 = "……。"
10049140-101 = "（まだいる！？）"
10049140-102 = "（8時間、ずっと……？）"
10049140-103 = "（徹夜で600話近くも！？）"
10049140-104 = "（わ、私は……どうすれば……）"
10049140-105 = "ふっ、この程度か。"
10049140-106 = "（シミコ！？）"
10049140-107 = "ついに、闇[ruby=とばり]の帷を[/ruby]手に入れる時が来た。"
10049140-108 = "（闇……？な、なんて？）"
10049140-110 = "0"
10049140-112 = "（これ以上はさすがに……あまり口出しする気はなかったけど……！）"
10049140-113 = "（シミコを止めなければ。事情は追って聞こう）"
10049140-114 = "（斯くなる上は、気絶させてでも……）"
10049140-117 = "（今度はなんだ……？）"
10049140-118 = "（あれは……遮光カーテンと、黒いクッションフロア？）"
10049140-119 = "（図書館の修理用資材で一体何を……？）"
10049140-120 = "（もしかして……徹夜で補修作業をしていたとか……？）"
10049140-121 = "（夜の間、ずっとアニメを観ていたとも限らないし……）"
10049140-122 = "（まぁ、それなら……私もこれで――）"
10049140-126 = "（ハサミで……切った？）"
10049140-127 = "え？"
10049140-128 = "（カーテンとクッションフロアを切って……縫っている……？）"
10049140-132 = "？？？"
10049140-137 = "（あ、あれは――！）"
10049140-140 = "（いや、本当に何！？）"
10049140-141 = "（し、シミコがこんなことするはずない……）"
10049140-142 = "（そう、きっとシミコは悪い夢でも見ているだけで）"
10049140-143 = "（やっぱり、目を覚まさせないと……）"
10049140-147 = "ひぇっ――"
10049140-148 = "何者だ！！"
10049140-150 = "ひえぇぇっ！！！"
10049140-156 = "……。"
10049140-157 = "う～ん……もっと声を張ったほうがいいでしょうか。"
10049140-158 = "悪の幹部なら……。"
10049140-159 = "こほん……あー、あー！"
10049140-160 = "何者だーっ！！！"
