[translation]
10049040-1 = "第4話;ステージショー開演！"
10049040-2 = "控え室"
10049040-3 = "わぁっ！！ここが控え室！！"
10049040-4 = "キャストさんになった気分です！！"
10049040-5 = "レイサさん！"
10049040-7 = "ふーむ……。"
10049040-8 = "あなた達、本当にキャストですか？"
10049040-9 = "名簿に載ってなかったような……#nあー、ったく、名簿持ってくるの忘れたな……。"
10049040-10 = "！！"
10049040-15 = "（よくないですね……もし正体がバレてしまえば……）"
10049040-16 = "（潜入もバレて……ターゲットに気づかれてしまうかも……）"
10049040-17 = "（どうしましょう……？）"
10049040-18 = "（なにか……打開策を考えなければ……）"
10049040-22 = "フィードランプよりチャンバーへ……6条右回りの魔法よ！揺るぎなき力をっ！"
10049040-28 = "ボルトフォワード！テルミットピンク！"
10049040-29 = "これで準備完了です！"
10049040-30 = "レイサさん！？"
10049040-31 = "自然にポーズをとれば大丈夫です！"
10049040-32 = "っ……うぅ……。"
10049040-38 = "まじかる、りりかる……#nてるみっとほわいと！"
10049040-42 = "心配しすぎか……#nショーは10分後から始めますので、よろしくお願いしますね。"
10049040-46 = "はあぁ……。"
10049040-47 = "なんとか誤魔化せましたね！"
10049040-48 = "ひとまずは切り抜けられましたが……問題はこれからです。"
10049040-49 = "まさかこんな事になるだなんて……このままでは、10分後にはステージの上ですよ！"
10049040-50 = "[s1] \"むしろ好都合じゃないかな？\"\n[s2] \"ステージの上だと、見晴らしが良くなるし。\""
10049040-53 = "そ、そうでしょうか……。"
10049040-54 = "ですが、私……魔法少女の作品は子供のころに観たっきりですし……。"
10049040-55 = "なにより、大勢の前に立つのは……想像するだけで怖いです……。"
10049040-56 = "スズミさんはカッコいいですから！心配する必要なんてありません！"
10049040-57 = "自警団として、いつも堂々としてるじゃないですか！"
10049040-58 = "それとこれとは別問題です！"
10049040-59 = "私はどうしたら……。"
10049040-61 = "[ns3] \"それっぽいセリフを言うのはどう？\"\n[ns4] \"時間稼ぎだと思ってさ。\""
10049040-64 = "ですが、どんなセリフを言えばいいか……。"
10049040-65 = "ふふん、テルミットホワイトのセリフですね！"
10049040-66 = "私にお任せください！"
10049040-73 = "それは……ペンですか？"
10049040-74 = "「ペン」ではありません！"
10049040-75 = "「マジカル・カンニング」です！"
10049040-76 = "今からこれで――"
10049040-77 = "スズミさんの手のひらにセリフを書いてあげます！"
10049040-82 = "ま、待ってください！そんないきなり――きゃっ！"
10049040-87 = "くっ、ふふっ……くすぐったいです！あははっ！！"
10049040-89 = "[ns] （スズミってあんな笑い方もするんだ）"
10049040-95 = "準備オッケーです！"
10049040-96 = "はぁ、はぁ……。"
10049040-97 = "私、くすぐりには弱くて……。"
10049040-98 = "手のひらは特に……！！"
10049040-99 = "でも、これでなんとかなると思います！"
10049040-100 = "なんとかって……。"
10049040-105 = "さぁ、ショーが始まりますよ！"
10049040-107 = "はい！！"
10049040-108 = "ま、まだセリフの確認が……！もう少し時間を……！"
10049040-109 = "それに、敵役のシミコさんがいなくていいんですか！？"
10049040-110 = "スケジュールだと……今は私たちだけでいいみたいです！"
10049040-112 = "[ns5] \"がんばれ！\"\n[ns6] \"ファイト！テルミットホワイト！\""
10049040-115 = "う、うわあぁぁああ！！"
10049040-121 = "テルミットホワイトだ！"
10049040-122 = "テルミットピンクもいる！"
10049040-123 = "かわいいね！お姫さまみたい！！"
10049040-125 = "（さっきよりも観客が増えていませんか！？）"
10049040-126 = "（みなさん、私を見て、歓声を……）"
10049040-127 = "（怖い……どうしよう、足がすくむ。指先の感覚がない、こわい）"
10049040-128 = "（私には……できません。こんな風に、期待されてしまうのは……）"
10049040-129 = "ボルトフォワード！テルミットピンク！"
10049040-130 = "わあああっ！！！"
10049040-131 = "レイサさん！？"
10049040-132 = "スズミさんの番ですよ！"
10049040-133 = "最高にカッコいい姿を見せてくださいっ！！"
10049040-134 = "（レイサさんは、どうして平気なんでしょうか……）"
10049040-135 = "……ふぅ。"
10049040-139 = "ボルトキャッチ！テルミットホワイト！"
10049040-140 = "わあああああぁぁぁぁぁぁ！！！"
10049040-142 = "ホワイト！！ホワイト！！"
10049040-143 = "わあああぁぁ！！"
10049040-147 = "[ns] \"テルミットホワイト！！最高だぁーっ！！！\""
10049040-149 = "あははっ！先生の声、ここまで聞こえてますよ！！"
10049040-150 = "先生……！"
10049040-151 = "こほん……。#n大変です！この遊園地に……エラとその手下たちが隠れているみたいです！"
10049040-152 = "えっ、あ、それは本当ですか？"
10049040-153 = "はい！きっと、友情エネルギーを奪おうとしているんです！"
10049040-168 = "（良かった……なんとか乗り切れそうですね……）"
10049040-169 = "（先生の言う通り、ステージの上からだと周りがよく見えます……これなら……）"
10049040-170 = "（あっ、汗が……）"
10049040-175 = "（あっ……つい手で汗を……！）"
10049040-176 = "（書いてもらった字が滲んで……！）"
10049040-177 = "テルミットホワイト！これからどうしますか？"
10049040-182 = "……スズミさん！次のセリフです！"
10049040-184 = "[ns] \"スズミ……？\""
10049040-185 = "あ、え、えっと……。"
10049040-186 = "ケーキには、バターが必要……ですよね……？"
10049040-187 = "え……？"
10049040-189 = "[ns] （どういうセリフだろう……？）"
10049040-191 = "テルミットホワイト？"
10049040-192 = "どういう意味……？"
10049040-193 = "あの子ほんとにテルミットホワイトなの？"
10049040-195 = "な、なるほど！ホワイトは「シュガーマジカルパワー」を使うつもりですね！"
10049040-196 = "よーっし、ピンクも準備します！"
10049040-197 = "ちょっと、必殺技の練習をしておきましょう！"
10049040-198 = "みんなー！力を貸してくださいねー！"
10049040-200 = "はーいっ！！"
10049040-201 = "するー！！"
10049040-203 = "[ns7] \"レイサがアドリブでフォローした！\"\n[ns8] \"すごいよ、レイサ！\""
10049040-207 = "（必殺技のセリフ、これはまだ滲んでいません。それなのに……）"
10049040-212 = "（どうしましょう……声が、出ません……）"
10049040-213 = "（レイサさんがフォローしてくれたのですから……早く、次のセリフを言わないと……）"
10049040-218 = "み、みんなの平和のために……。"
10049040-219 = "誰ひとり……分かってくれなくても……。"
10049040-223 = "なんで自警団なんかやってんだ？誰も分かっちゃくれねぇだろ？"
10049040-224 = "……そう、なんですか？#n私の行いは――"
10049040-228 = "やはり……。"
10049040-229 = "私、は……。"
10049040-233 = "私には……できません……。"
10049040-239 = "[ns] \"スズミ……！\""
10049040-241 = "……。"
