[translation]
10049005-1 = "プロローグ"
10049005-13 = "治癒の光に、愛を込めて！"
10049005-16 = "[log]それは――[/log]"
10049005-21 = "テルミットホワイト！ピンク！がんばえー！！"
10049005-22 = "やっつけろー！！"
10049005-26 = "魔法少女、ヘヴィキャリバーズ――参上！"
10049005-29 = "[log]すっごく強くて、カッコいいので！[/log]"
10049005-3 = "[log]魔法少女に――なってください！[/log]"
10049005-33 = "あんたら、正気！？"
10049005-7 = "インセンディアリー……フルチャージ！"
10049005-9 = "[log]どうして……魔法少女なんですか？[/log]"
