[translation]
10049030-1 = "第3話;魔法少女ヘヴィキャリバーとは！"
10049030-2 = "[log]3日前、図書委員会・休憩室[/log]"
10049030-4 = "これです！！"
10049030-5 = "これ……？"
10049030-6 = "はい？"
10049030-10 = "魔法少女に――なってください！"
10049030-11 = "えへへっ……このセリフを言える日がくるとは思いませんでした……！"
10049030-12 = "この……「魔法少女ヘヴィキャリバー・ボーダーランドスペシャル」……ってなんですか？"
10049030-13 = "魔法少女ヘヴィキャリバーが、ボーダーランド遊園地で特別なショーをするんです！"
10049030-14 = "えっと、具体的には……？"
10049030-16 = "キャラクターに扮したキャストが遊園地内の各所で行うショーです。"
10049030-17 = "敷地が広いため、複数のチームに分かれているようですが……。"
10049030-18 = "レイサさん、それと任務に一体何の関係が……？"
10049030-19 = "潜伏する際に、魔法少女に変装してみるのはどうでしょうか！"
10049030-20 = "チームが複数あるなら、一組くらい増えてもバレないはずです！"
10049030-21 = "それに、遊園地のどこにいても違和感はないと思います！"
10049030-23 = "キャストさんは外部から招待されることも多いですし……#n初対面でも、遊園地のスタッフさんに疑われる心配は少ないかもしれませんね。"
10049030-24 = "なるほど……。"
10049030-25 = "まだ小さかった頃、似たようなアニメを見た記憶があります。#nたしか、朝の時間に放送されていたような……それと一緒ですか？"
10049030-26 = "違います！！#nあ、いえ、朝のテレビアニメではあるのですが！"
10049030-27 = "魔法少女ヘヴィキャリバーは、悪の幹部「エラ」の侵略からキヴォトスを守る――#n選ばれし少女たちの物語なんです！"
10049030-28 = "な、なるほど……。"
10049030-29 = "ですがこの衣装は、戦闘には不向きだと思います。"
10049030-30 = "装備を整えるのも難しくなるでしょうし……。"
10049030-31 = "なにより、私はこういったジャンルのことはほとんど分かりません。"
10049030-32 = "私も、全く触れてこなかったので……。"
10049030-33 = "それに……少し恥ずかしいと言いますか……。"
10049030-34 = "あっ……。#nそう、ですよね。"
10049030-35 = "すみません……その、私なりに力になれるかなって思って、つい。"
10049030-36 = "えへへ、で、では、別の方法を考えてみますね！"
10049030-40 = "い、いえ！ですから、私が言いたいのは……。"
10049030-41 = "逆に、こういう衣装なら相手の油断を誘えますし――"
10049030-42 = "せ、潜入に適しているのではないでしょうか！"
10049030-43 = "スズミさん……？"
10049030-45 = "ですが、魔法少女ってやっぱ子供っぽいですし……。"
10049030-46 = "そんなことはありません。#n魔法少女ハッピー……カリバー？はとても良いと思います。"
10049030-48 = "「ヘヴィキャリバー」では？"
10049030-49 = "と、とにかく。遊園地という場所柄にもあっているかと。"
10049030-50 = "ただ……変装するなら、それ相応の知識が必要になります。"
10049030-51 = "レイサさんはその作品について、お詳しいのでしょうか？"
10049030-52 = "はい！大好きです！"
10049030-53 = "世界の平和を守る姿が自警団みたいで――"
10049030-54 = "今までで一番好きな作品と言ってもいいくらいです！！"
10049030-55 = "最近公開された劇場版も観てきました！"
10049030-56 = "誰かとヘヴィキャリバーの話をしたりは……できないんですけど……。"
10049030-57 = "……。"
10049030-62 = "ええと、今すぐ衣装の手配をお願いしてもいいでしょうか？"
10049030-63 = "どれにするのかはレイサさんにお任せします。"
10049030-65 = "スズミさん！？"
10049030-69 = "いいんですか！？すぐ用意しますね！！"
10049030-74 = "（なぜ、あんなことを言ってしまったのでしょうか……）"
10049030-75 = "（レイサさんがやる気になっていますし、潜入にも適しているとは思いますが……）"
10049030-76 = "（やはり、恥ずかしいですね……）"
10049030-77 = "似合ってますよ！恥ずかしがる必要なんてありません！"
10049030-78 = "主役を譲って正解でした！主人公としての貫禄がありますよ、スズミさん――"
10049030-79 = "――いえ、「テルミットホワイト」！"
10049030-80 = "テ、テルミットホワイト……？"
10049030-81 = "スズミさんが担当する役の名前です！#n本名を言ったら、正体がバレてしまいますから！"
10049030-82 = "そして私は「テルミットピンク」です！#n「テルミットホワイト」をサポートする相棒ですね！"
10049030-83 = "そ、そうですか。レイ――"
10049030-89 = "いえ、テルミットピンク……。"
10049030-93 = "ところで……なぜテルミット[ruby=・   ・   ・]ピンク[/ruby]なのでしょうか？"
10049030-94 = "レイサさんの衣装は紫色ですから、「パープル」では？"
10049030-95 = "あっ！それはですね！"
10049030-101 = "[log=레이사 매지컬]魔法少女ヘヴィキャリバーの本編のお話になるのですがもともと#nテルミットピンクは名前の通りハートのジュエルやピンクのドレスが[/log]"
10049030-102 = "[log=레이사 매지컬]メインのデザインだったんです。でもエラの忠実な[ruby=しもべ]僕[/ruby]「シルバープレート」#nとの決戦があった「ボルトキャッチ！ヘヴィキャリバー！」の回で危機に[/log]"
10049030-103 = "[log=레이사 매지컬]陥ってしまって！そこでホワイトと共に力を合わせた際に新たな能力に#n目覚めたんですが、それでもシルバープレートを倒すことは叶わずそ#nのまま二人は倒れてしまうんです宿敵を倒したシルバープレートは――[/log]"
10049030-107 = "あ、あの……。"
10049030-109 = "[log=레이사 매지컬]――友情エネルギーを憎悪の星へ送ろうとしたその瞬間！#nこの姿のピンクが現れて敵を制圧するんです！それで――[/log]"
10049030-117 = "――ということがありまして！そのときピンクが特殊変身した姿がこれでして私はその回がとても大好きなのでこの衣装にしたんです！なのでこれは通常形態のピンクではなく真の力を解放した姿なんですよ！"
10049030-118 = "そ、そうですか……参考になりました……。"
10049030-119 = "ところで、レイ――テルミットピンク。シミコさんと連絡は取れましたか？"
10049030-120 = "悪の幹部「エラ」です！"
10049030-121 = "……あ、エ、エラは今どこに？"
10049030-122 = "それが……私にも分からなくて……。"
10049030-123 = "もしかして、寝坊でしょうか……？"
10049030-124 = "私たちだけでも現場はなんとかできると思いますが……。"
10049030-125 = "少し心配ですね。"
10049030-130 = "皆さん、聞こえますか？正義実現委員会のマシロです。ただいま配置につきました。"
10049030-132 = "はい、聞こえます。"
10049030-133 = "テルミットピンク、問題ありません！"
10049030-135 = "こちらも感度良好です。#n支援が必要な時は、このチャンネルでご連絡ください。"
10049030-136 = "ちなみに、私の現在位置はトリニティ側の展望塔です。"
10049030-138 = "分かりました。視野の確保にも注意しておきます。"
10049030-140 = "……先生も、ちゃんと聞こえていますか？"
10049030-141 = "[s] \"うん、ばっちり。\""
10049030-142 = "私が必要な時は、先生もご遠慮なくお呼びください。"
10049030-144 = "ひとまず、通信状態に問題はありませんね。"
10049030-145 = "支援、ありがとうございます。マシロさん。"
10049030-150 = "せ、先生！？"
10049030-151 = "先生！"
10049030-152 = "[s1] \"おはよう。スズミ、レイサ。\"\n[s2] \"やあ、テルミットホワイト、ピンク。\""
10049030-156 = "せ、先生！？？いっ……一体いつから！？"
10049030-160 = "あっ、こ、この衣装は、えっと、その……！"
10049030-161 = "[s3] \"心の準備が……ってあたりかな。\"\n[s4] \"大丈夫。よく似合ってるよ。\""
10049030-165 = "話はハスミ先輩から聞いています。"
10049030-166 = "今日の支援要員は、私と先生の2名です。"
10049030-167 = "先生がいらっしゃるとは聞いていないのですが……。"
10049030-168 = "あれ？スズミさんも知らなかったんですか？"
10049030-169 = "知っていれば、もっと色々と……！"
10049030-171 = "ハスミ先輩は「可能な限りの支援」として、先生に協力を仰いだと言っていました。"
10049030-172 = "私も詳しいことまでは知りませんが。"
10049030-173 = "なるほど……まさかシャーレの支援を受けることになるとは……。"
10049030-174 = "[s5] \"助けが必要みたいだったからね！\"\n[s6] \"面白そうだったからね！\""
10049030-177 = "（久々に先生とご一緒できるのは嬉しいですが……）"
10049030-178 = "（でも、この格好はさすがに……）"
10049030-179 = "待機に入る前に、一つお聞きしたいことがあります。"
10049030-180 = "お二人の衣装、ずいぶん独特ですが――"
10049030-181 = "それは自警団のユニフォームでしょうか？"
10049030-182 = "正義実現委員会の制服とは違って、派手で素敵だと思います。"
10049030-183 = "いえ、違います。#n自警団はそもそも組織ではないので、当然、指定のユニフォームはありません。"
10049030-184 = "これは、えっと……現場をパトロールするための、潜入衣装です……。"
10049030-186 = "「魔法少女ヘヴィキャリバー」の仲良し主人公！テルミットホワイトとピンクの衣装です！"
10049030-187 = "世界の平和を守り、正義を貫く魔法少女なんです！"
10049030-188 = "……。"
10049030-189 = "……。"
10049030-193 = "……なるほど、理解しました。"
10049030-194 = "正義を貫くための衣装……とても良いですね。"
10049030-195 = "……。"
10049030-196 = "あれ？コールサイン上、スズミさんは「テルミットホワイト」となっていますが……#n「ピンク」の間違いでは？こちらからはピンク色に見えますが……。"
10049030-197 = "あ！その理由はですね！まず3期7話を観る必要がありまして！簡単に説明すると――"
10049030-199 = "こ、コールサインに問題はありません！ご確認くださりありがとうございます！"
10049030-200 = "レイサさん。せっかくですから、後で映像を一緒に観ませんか？#nそれまでは、ネタバレ禁止ということで。"
10049030-201 = "おぉっ！いいですね！今度、円盤を全部持ってきますね！"
10049030-202 = "では、現時刻より待機に入ります。"
10049030-203 = "見張りや狙撃は私にお任せください。"
10049030-204 = "ただ、狙撃については正義実現委員会の発砲許可が必要なことをご留意ください。"
10049030-208 = "はぁ……。"
10049030-209 = "今からでも普段着に着替えるべきでしょうか……。"
10049030-210 = "ええっ！？せっかく似合ってるのに！"
10049030-211 = "ですが、やはり恥ずかしくて……。"
10049030-212 = "お二人とも、何やってるんですか！"
10049030-213 = "そろそろ開演なんですから、控え室で待機しててもらわないと！"
10049030-214 = "わ、私たちですか？"
10049030-215 = "はい？"
10049030-216 = "まったく困りますよ。列車の乗務員がどうのこうのって、時間に間に合わないって連絡を寄こしておいて。"
10049030-217 = "まぁ、ちゃんと間に合ってるので、もういいですが。さあ、早く始めますよ！"
10049030-218 = "始める……何をですか？"
10049030-223 = "「魔法少女ヘヴィキャリバー」のショーですよ！"
10049030-224 = "あなた達、キャストなんでしょう？早く準備してください！"
10049030-225 = "キャ、キャスト！？"
