[translation]
10049130-1 = "後日談その3;ヘルメット団ブルース"
10049130-2 = "[log]5日前[/log]"
10049130-4 = "じゃあ、もう一度整理するわよ。"
10049130-5 = "うちらは今週末、「ボーダーランド遊園地」で詐欺まがいの行商人を捕まえる。"
10049130-6 = "そのためなら、どんな手を使っても構わないわ。#n……何か質問ある？"
10049130-7 = "はい、隊長！"
10049130-8 = "はい、言ってみなさい。"
10049130-9 = "入園料はどうしますか？遊園地に入らないと話が始まりません！"
10049130-10 = "たしかに……うちらの財布事情じゃ、一番安いチケットも無理ですよ。"
10049130-11 = "今から自販機を蹴って回っても、大したお金にならないですし……。"
10049130-12 = "遊園地の食べ物とかも、高くて買えないんじゃ……。"
10049130-13 = "あれ？そもそもうちらの人数で、どうやってあんなに広い場所から探し出せばいいの……？"
10049130-14 = "どうしよう……。"
10049130-15 = "無理だぁ……。"
10049130-16 = "ふっ。"
10049130-20 = "ふっふっふ……。"
10049130-21 = "今回は……いつもとは違うわよ？"
10049130-22 = "なんと……依頼主がチケットを用意してくれたわ！"
10049130-23 = "しかも、助っ人で他のヘルメット団からも応援が来る！"
10049130-24 = "た、隊長！！"
10049130-25 = "それ、本当ですか！？どこでこんな良い依頼を……！"
10049130-26 = "うちらだって、たまには「良い仕事」をしたっていいでしょ？"
10049130-27 = "それに、驚くのはまだ早いわよ。なんと――"
10049130-28 = "チケットはフリーパス！"
10049130-29 = "フリーパス！！"
10049130-30 = "あそこのアトラクション、全部乗れるってことですか？一日中！？"
10049130-31 = "しかも、ただのフリーパスじゃないわ！週末のフリーパスよ！"
10049130-32 = "隊長！一生ついて行きます！！"
10049130-33 = "応援が来て、しかも入園はタダ！こんなん勝ち確ですよ！"
10049130-34 = "一番乗りで入らないと！"
10049130-35 = "や、ほら、いつターゲットが現れるか分かりませんからね！"
10049130-36 = "お弁当の用意しないとね！ターゲットを捜すのに時間かかるかもしれないし！"
10049130-37 = "手がかりも必要だから……いっぱい写真撮りましょう！"
10049130-38 = "へへっ！"
10049130-39 = "遊ぶことばっか考えてないで、ちゃんと仕事しなさいよね。"
10049130-40 = "捕まえられたら、褒賞金で焼肉パーティーよ！"
10049130-41 = "やったぁ！"
10049130-42 = "隊長サイコー！"
10049130-45 = "うーん……。"
10049130-46 = "うーーん……？"
10049130-47 = "隊長、もう入園時間ですよ？"
10049130-48 = "入らないんですか？"
10049130-49 = "遅れたら、アトラクションの列長くなっちゃいますよ……。"
10049130-50 = "応援に来るはずのやつらがまだなのよ。"
10049130-51 = "うちらの分のチケットも、そいつらが持ってるのに！"
10049130-52 = "もしかして、裏切られた！？"
10049130-53 = "なんで！？まだお金が動いたわけでもないのに……。#nまさか、依頼を横取りするつもり！？"
10049130-54 = "いま連絡してみるから。もし裏切ってたら、ただじゃ置かないわよ！"
10049130-55 = "はい！"
10049130-61 = "ねぇ、今どこにいるのよ！？本当に来るんでしょうね？"
10049130-62 = "もし裏切ったんなら――"
10049130-63 = "す、すまん！うちらだってそっちに向かってるんだ！でも……！"
10049130-64 = "全員やられちまったんだよ！！"
10049130-65 = "は？どこで？ターゲットから奇襲でもされたの？"
10049130-66 = "列車だよ！列車に乗ってたのに、途中でいきなり乗務員が！"
10049130-67 = "ハイランダーは狂ったのか！？"
10049130-68 = "お、おい！やめろ！！"
10049130-69 = "――しません！"
10049130-70 = "定時運行を邪魔する乗客は許しません！"
10049130-71 = "うわあああっ！！"
10049130-78 = "隊長……？"
10049130-79 = "何が起きてるんですか……？"
10049130-80 = "列車に乗ってたら、乗務員が狂ったって……。"
10049130-81 = "は？"
10049130-82 = "え、なんで？"
10049130-83 = "分かんないけど……。"
10049130-84 = "これって、裏切られたってことでいいの……？"
10049130-86 = "隊長、これ、どこに向かってるんですか？"
10049130-87 = "遊園地の入場ゲートはこっちじゃないですよ？"
10049130-89 = "はぁ、はぁ……地図によれば、この遊園地には動物園があるみたいなの。"
10049130-90 = "動物園ってのは、中にいる動物が外に出ないように力を入れてる場所。#nつまり、外部からの侵入には脆いのよ。"
10049130-91 = "それに、動物が警報器を触るからって、電源を切ってるところも多い。"
10049130-92 = "で、さっき調べてみたら、今日の動物園は臨時休館中。"
10049130-93 = "潜入するのにピッタリってわけ！"
10049130-94 = "すげぇ……どうしてそんなことまで知ってるんですか？"
10049130-95 = "うちらと違って、隊長は勉強が嫌いで逃げたわけじゃないんだよ！"
10049130-96 = "隊長、そうですよね？しかも、前は成績良かったって聞きましたよ。"
10049130-97 = "うるさい。あんな学園、好きで通ってたわけじゃないの。"
10049130-98 = "最初は我慢しようと思ったけど……。#nやっぱり息が詰まって無理だったわ。"
10049130-99 = "でも[ruby=カーニバル]謝肉祭[/ruby]は、一回くらい参加しといても良かったかもしれないわね。#nその前に中退しちゃったから。"
10049130-100 = "ほんと、隊長の昔話はいつ聞いても不思議ですね。"
10049130-101 = "何か文句でもあるの？"
10049130-103 = "って、無駄話はおしまい。#n――ここにするわよ。"
10049130-104 = "今は手元にないだけで、ちゃんとうちらの分のチケットは用意されてるはず。だから、これは不法侵入じゃないわ。"
10049130-106 = "言われてみれば！一応、チケットはあるし……？"
10049130-107 = "隊長、やっぱ頭いいですね！"
10049130-108 = "いいから！あんたらも早くこっちきなさい！"
10049130-111 = "ビンゴ！警報器はないみたいね。"
10049130-112 = "なんか、野生っぽく作られてるんですね。"
10049130-113 = "野生？"
10049130-114 = "よっし、このまま遊園地まで行くわよ！"
10049130-115 = "応援もチケットもないけど、心配ないわ！#nだってこんなところに――"
10049130-116 = "ワニなんか現れるはずないんだから！"
10049130-121 = "ちょっと、どうしたの？#n急に震えて……。"
10049130-122 = "隊長……！心配ないとか言えないっすよ！"
10049130-123 = "え？"
10049130-125 = "だって、ここ……ワニの檻です……！"
10049130-129 = "本物のワニ……？#n動物園だから？"
10049130-130 = "まぁ、そりゃそうよね。"
10049130-134 = "うわあああぁぁぁああああっ！"
