[translation]
10052065-10 = "はい。ではお願いします、ヒマリ。"
10052065-11 = "確認しました。いま座標を送りますね。"
10052065-12 = "降下開始ぃ！"
10052065-16 = "お姉ちゃん、お願いだから慎重に……って、もうやってる……。"
10052065-2 = "ケテルの沈黙、確認しました。"
10052065-23 = "ふぅ……本当に迅速で[ruby=野蛮]直感的[/ruby]な合流方法ですね……。"
10052065-24 = "激しく同意……。"
10052065-25 = "エリアの掌握はほぼ完了しています。#nケイ、コアの確保はできそうですか？"
10052065-26 = "ええ、問題ありません。ただその間……。"
10052065-28 = "[ns] \"敵襲があるかもしれないから、護衛をお願い。\""
10052065-29 = "お任せください。得意分野です。"
10052065-3 = "うぅっ……うぅぅ……。"
10052065-30 = "……あなた、何でもかんでも得意分野って言ってませんか……？"
10052065-31 = "その通りです。#n完璧で最高なメイドかつエージェントならば、それこそが到達すべき姿ですので。"
10052065-32 = "（ヒマリの変な癖が移っているようですね……）"
10052065-33 = "今度はアリスがケイを守るターンですね……アリス、頑張ります！"
10052065-34 = "アリス、よろしくお願い、します……。"
10052065-35 = "はい！アリスにお任せください！"
10052065-36 = "そういえば、ケテルの研究地区は、ダムの決壊による洪水で完全閉鎖されたと聞きました。"
10052065-37 = "そうですね。結局あの時点で分かったことは、デカグラマトンの本体は自販機のAIだったということくらい。"
10052065-38 = "あとは、幻聴をきっかけに、自ら超AIになったって話だったよね。"
10052065-39 = "ええ、そうでしたね。"
10052065-4 = "ユズ、よく頑張ったね。"
10052065-40 = "部長さ、あの時……デカグラマトンのことを誇大妄想者って呼んでたよね。"
10052065-41 = "事実ですから。なにか問題でも？"
10052065-42 = "まるで人間みたいに表現するんだなって思って。"
10052065-43 = "ほら、部長って言葉選びに厳しいから。"
10052065-44 = "それは……。"
10052065-45 = "……私たちの仲間に、線を引きたくはありませんから。"
10052065-46 = "つ、つまり、分類基準は可能な限り絞り込んだほうが良いということで……！"
10052065-47 = "？"
10052065-48 = "……。"
10052065-49 = "なるほど、合理性の観点における分類基準ね。参考になるわ。"
10052065-5 = "はぃぃ……。"
10052065-50 = "少なくともあなただけは、そのように受け止めてはいけないと思いますよ……。"
10052065-51 = "そ、そう？"
10052065-52 = "……雑談は終わりです。無事にコアを確保しました。"
10052065-53 = "輸送船のディスプレイに映している「生命の樹」に共有しておきますので、確認してください。"
10052065-54 = "……反映を確認できたわ。みんな、お疲れ様。"
10052065-55 = "パンパカパーン！ケイのレベルが10アップしました！#nこの勢いでどんどんレベルアップしていきましょう！"
10052065-56 = "そうですね。"
10052065-6 = "ケイ！こちらです！"
10052065-61 = "……先生、その、少しお願いが……あります。"
10052065-62 = "[s] \"なにかな？\""
10052065-63 = "しーっ！静かに！声が大きいです！"
10052065-64 = "その……後で、ヒマリに――"
10052065-65 = "ありがとうって、伝えておいてください。"
10052065-66 = "[ns] \"……。\""
10052065-68 = "[ns] \"うん！ちゃんと伝えておくね！\""
10052065-69 = "だから声が大きいですって！"
10052065-70 = "ケイ、先生？何かありましたか？"
10052065-71 = "な、なななな、なんでもありませんよ！ねえ、先生！？"
10052065-75 = "[ns] \"それがねー！ケイちゃんがさぁー！\""
10052065-77 = "先生――！！！！！！"
