[translation]
10050080-1 = "第8話;古書館戦争"
10050080-103 = "黙って聞いていれば……何ですか！？#nうちの子たちを連れていく？"
10050080-104 = "ここがどこだか分かって言っているんですか！？"
10050080-105 = "よく聞いてください。ここにあるモノに指一つ触れたら、誰だろうと手首を――"
10050080-106 = "い、いけません！今の発言は正義実現委員会を脅す発言で……！"
10050080-107 = "ふさわしくない言動です！決して許されない――"
10050080-108 = "それはこっちのセリフですよ！バックに誰がついてるのかも全部分かっているんですから！"
10050080-109 = "ティーパーティー……権力を振りかざし、隠ぺいと陰謀だらけの組織……。"
10050080-110 = "ついには本の調査を口実に、古書館まで自分たちのものにしようって魂胆なのでしょう！？"
10050080-111 = "……へっ？えっ、いや、そういうつもりでは……！"
10050080-112 = "失礼ですが、こちらは公務を行っているだけです！！"
10050080-113 = "そうです！そういう態度で出るならこっちも力で……！！"
10050080-125 = "皆さんよく聞いた上で、お伝えください……。"
10050080-126 = "私の許可なく、この子たちを外に持ち出してはいけません。#n1ページたりとも、です。"
10050080-127 = "つまり――"
10050080-128 = "どうしても持って行きたいというなら、私を倒してから持っていくがいい！"
10050080-13 = "……それで先生に連絡したの……。"
10050080-133 = "……分かりました。"
10050080-134 = "協力する意志はないこと、たしかに理解しました。"
10050080-135 = "同時に、ティーパーティーの命令および正義実現委員会への脅迫と見受けましたので。"
10050080-136 = "これより正義実現委員会は、正義執行へと移らせていただきます。"
10050080-137 = "へえ、そうですか。そうこなくちゃね。"
10050080-138 = "……[ruby=・]久[/ruby][ruby=・]し[/ruby][ruby=・]ぶ[/ruby][ruby=・]り[/ruby]ですね。どんなもんかやってみましょうか。"
10050080-14 = "[s] \"ありがとうコハル！コハル最高！\""
10050080-149 = "……いきます！！"
10050080-15 = "そ、そうかな？えへへ……。"
10050080-154 = "[ns] \"やめてぇぇええええっ！\""
10050080-155 = "やめてください！！"
10050080-156 = "シミコ？"
10050080-157 = "先生？"
10050080-158 = "みなさん、誤解です！一つ一つちゃんと話し合いませんか！？"
10050080-159 = "……そ、そうなんですか？"
10050080-16 = "い、いや喜んでる場合じゃなくて！どうするの先生！？"
10050080-164 = "先生？シミコさん？みんな大丈夫！？"
10050080-165 = "あれ？コハルさん……？どうしてここにコハルさんが。"
10050080-166 = "避難して、と言ったはずですが……。"
10050080-167 = "で、でも……ダメでしょ！ダメなもんはダメなの！"
10050080-168 = "また人……？いったい何人来るつもりですか……？"
10050080-169 = "というか、シミコ！そっち側だったんですか！？"
10050080-17 = "ん？シミコさんにも連絡……？そ、そうだ！図書委員会の仕事でもあったんだった。"
10050080-170 = "内通者がいるかもと思ってたけど、あんただったとはね！ほんと、人間は誰ひとり信じちゃいけないと言うけど……。"
10050080-179 = "ぎぃやっ……！し、シミコ……！！"
10050080-180 = "先輩！！またやらかしたんですね！？#n内通者って……人の気も知らないで……！！"
10050080-181 = "というか、いきなり人を撃っちゃダメなのは常識ですよね！？#n今度は何人病院送りにするつもりですか……！？"
10050080-182 = "い、いやっ、私はただ……！！"
10050080-183 = "問答無用です！！"
10050080-192 = "ぎぃあぁぁぁっ！！"
10050080-194 = "あ……ええっと……。"
10050080-195 = "なんだか困った状況になりましたが、正義実現委員会の目的はまだ達成できていません。"
10050080-196 = "私たちは非公認書籍を調べなくてはいけません。ここにある可能性が高いと判断しています。"
10050080-197 = "非公認の書籍がトリニティで出回るのは看過できない事態……。"
10050080-198 = "はい、その件に関しては同意です。みなさんのことを止めたいわけではありません。"
10050080-199 = "つまりこれは――"
10050080-2 = "[ns] \"えっ？正義実現委員会がどうしてここを！？\""
10050080-205 = "皆さん、申し訳ございませんでした。"
10050080-206 = "か、隠れているようにと言ったはず、ですが……！？"
10050080-207 = "はい、そうですが……やはり筋ではないと思いまして。#n結局は私たちのせいでこうなったのですから。"
10050080-208 = "助けていただいたのは大変感謝しておりますが、同じ学園内で争うのは求めておりませんわ。"
10050080-209 = "さあ、部長もこちらへ。ちゃんとお伝えすべきかと。"
10050080-210 = "あーあ。適当に忍び込めたんだし、帰りも楽できるかなと思ったんですが。"
10050080-211 = "……部長？"
10050080-212 = "……申し訳ございませんでした。"
10050080-213 = "初めまして、トリニティのみなさん。レッドウィンター連邦学園から参りました、出版部と申しますわ。"
10050080-214 = "出版？"
10050080-215 = "部？"
10050080-216 = "ええ。今回の経緯を説明した方がよさそうですわね。"
10050080-217 = "実は私たち――"
10050080-219 = "あ……えっと……つまり。"
10050080-22 = "はやく……はやく出て……！"
10050080-220 = "出版部のみなさんは、餓死寸前の知識解放戦線の生徒さんたちを救うために――"
10050080-221 = "新しい販路を開こうと、トリニティに来た、と……？"
10050080-222 = "まあ……別にあの子たちを助けたいとかじゃなく、ただお金が――"
10050080-223 = "部長？"
10050080-224 = "すみません……。"
10050080-225 = "しかし何といいますか、他にも……。"
10050080-226 = "我々レッドウィンターが作った文化媒体を、より多くの方々に紹介できたらな、という気持ちもありました。"
10050080-227 = "あれ、レッドウィンターではもう擦り尽くした内容だし、需要もなくて。"
10050080-228 = "それが幸運にも、トリニティで少なくない人気を博したわけで。"
10050080-229 = "そうですね……。"
10050080-230 = "私たちと図書委員が協力して出動せざるを得ないくらいの規模でしたから……。"
10050080-231 = "まさか、トリニティのみなさんが、あなた方を助けていたなんて……。"
10050080-232 = "調査が難航したのも納得しました。"
10050080-233 = "……そんなことがあったんだ？"
10050080-234 = "そうですよ、委員長。もう少し外のことにも興味を持ってください。"
10050080-235 = "これだって本当は、委員長の仕事だったんですから。"
10050080-236 = "い、いいいや……そ、そんなの、私にはちょっと荷が重すぎる……。"
10050080-237 = "ともかく。文化は巡るべきだと思っております。"
10050080-238 = "停滞した文化は、最終的に集団の足を引っ張る害悪となることでしょう。"
10050080-239 = "純粋に、稼げないですしね。"
10050080-240 = "まあ最初からそんな大義を掲げてトリニティに来たわけじゃありませんが……。"
10050080-241 = "喜んでくれる生徒さんを見て、いろいろ思うことがありましてね。"
10050080-242 = "あら、そうだったのですね？"
10050080-243 = "ええ……あえて話さないことで、完成に近づく物語もあるというものですし？"
10050080-244 = "うっ、それをここで……！"
10050080-245 = "部長の名は伊達じゃありませんので。ムフフ。"
10050080-247 = "しかし、許可されていない書籍、という事実に変わりはありませんが……。"
10050080-251 = "[ns] \"図書委員会が許可しちゃダメなのかな？\""
10050080-252 = "図書委員会が……？"
10050080-253 = "……そうですね。トリニティで流通されるあらゆる書籍の責任は、図書委員会にあります。"
10050080-254 = "出版部のみなさんが持ち込んだこの本が、図書委員会によって許可されればもう非公認書籍ではなくなります。"
10050080-255 = "ただ、トリニティに合うよう多少内容の調整が入ると思いますが。"
10050080-256 = "やはり……そのレベルでしたか。"
10050080-257 = "薄々感じてはいましたが……。"
10050080-26 = "こんにちは、コハルさん。どうかしましたか？"
10050080-262 = "[ns] \"そういった手順を踏むのも「正義」じゃないかな？\""
10050080-263 = "なるほど、たしかにその通りですね。"
10050080-264 = "正義が崩壊したような場でも、過程を踏むことで新たな「正義」を築く……。"
10050080-265 = "さすが先生です！勉強になりました！"
10050080-266 = "[s] \"あっ、う、うん！そういうこと！\""
10050080-267 = "そういえば、委員長はどうでしたか？あの本。"
10050080-268 = "えっ、な、なんで私に……。"
10050080-269 = "もう読まれたんですよね？全部。"
10050080-27 = "シミコさん！たいへん！！"
10050080-270 = "なんで、知ってるんです……。"
10050080-271 = "ふふ、どれだけ委員長と一緒にいると思ってるんですか。"
10050080-272 = "ったく、噓もつけないんだから……。"
10050080-273 = "ふぅ……まあ、良い本でしたよ。私からしたら。"
10050080-274 = "出版部の方の本気も、作り手のみなさんの熱意もちゃんと伝わってきました。"
10050080-275 = "……最近は太く短い商売ばかりで、利益を追及する本が多かったのですが。#nまぁ……そういうのよりは、よかったですよ。"
10050080-276 = "それで、結論は？"
10050080-277 = "私は……いいと思う。調整も別に、いらないとは思うけど……。"
10050080-278 = "他の人のことは分からないから……そこはシミコに任せます。"
10050080-279 = "はい、分かりました。"
10050080-28 = "えっ？"
10050080-280 = "ありがとうございます、図書委員会の皆さん。では今回の件はそのように報告させていただきます！"
10050080-281 = "[s] \"じゃあ私も一緒に行くね。ひと言添えておく。\""
10050080-282 = "では私も。委員長はたぶん行かないと思うので。"
10050080-283 = "行かない。"
10050080-284 = "先生やシミコさんにまでご迷惑をかけるわけには……。"
10050080-285 = "……。"
10050080-286 = "いや、では最後までどうぞよろしくお願いします。"
10050080-287 = "本来この件は、正義実現委員会と図書委員会、先生を含めたみんなで協力する任務でしたね。"
10050080-288 = "無事に終わってよかった。えへへ。"
10050080-289 = "では解決したことですし、図書委員長公認の書籍を一読してみましょうか。"
10050080-290 = "はい！私たちも読んでみたいです！"
10050080-291 = "（ごくっ……）"
10050080-292 = "[s] （これは、もしかすると……）"
10050080-296 = "……！"
10050080-297 = "これはまたずいぶん……！"
10050080-3 = "詳しくは分からないけど、どっかで尻尾をつかんだんじゃないの！？"
10050080-30 = "本当に大変なことに！？"
10050080-304 = "……。"
10050080-305 = "ひゃぁぁっ！？！？"
10050080-307 = "エッチなのはダメ！禁止！死刑！！！"
10050080-31 = "だから言ったでしょ！？"
10050080-32 = "いえ、これはコハルさんが思っているようなレベルではありません！"
10050080-33 = "へ？"
10050080-34 = "説明する時間はありません。とにかく、私は急いで古書館に向かいますので……。"
10050080-35 = "コハルさんはどこかに避難しててください。"
10050080-36 = "正義実現委員会とウイ先輩は、相性最悪そのものですから！"
10050080-37 = "えっ？なんで私まで……？"
10050080-38 = "……コハルさんまで古書館に行けば巻き添えになると思います。"
10050080-4 = "先生に言われた通り、委員会の子たちと一緒に行動してたんだけど……。"
10050080-40 = "それに最悪、密告者と思われかねません！"
10050080-41 = "いいですね？全部終わるまで、できるだけこの件から離れててください！"
10050080-45 = "巻き添えに、密告者……きっと本当のことなんだろうけど……。"
10050080-46 = "……。"
10050080-47 = "……でも行かなきゃ。"
10050080-48 = "だってそれが正しいから。"
10050080-57 = "先生……？どうしました、その顔色は。"
10050080-58 = "[s] \"ウイ！ここにいたんだ！よく聞いて今から――\""
10050080-62 = "……何ですか今度は……。"
10050080-63 = "待ってください、先生……誰だか知りませんが、ひと言言ってきます……。"
10050080-64 = "[s] \"あっいや、そうじゃなくて……！\""
10050080-65 = "[ruby=こぜき]古関[/ruby]ウイさん、いますか？正義実現委員会のマシロです。"
10050080-66 = "……正義実現委員会？どうして……。"
10050080-67 = "こんにちは、ウイ委員長。お久しぶりです。"
10050080-68 = "……なぜここに？"
10050080-69 = "はい、実は……。"
10050080-70 = "ここに、怪しい非公認書籍があるとのタレコミがありました！"
10050080-71 = "……非公認書籍？"
10050080-72 = "……それがどうしたのですか？"
10050080-77 = "はい！そういうわけで……今から古書館内を全数調査すべく、ご協力をお願いします！"
10050080-82 = "……え？"
10050080-83 = "何の調査……？"
10050080-84 = "いや待って……何をするって……？"
10050080-85 = "全数……調査？"
10050080-86 = "……つまり。"
10050080-87 = "この古書館内を？"
10050080-88 = "はい、そうです！"
10050080-89 = "それは……。"
10050080-90 = "今この子たちを……全部、連れていくと？"
10050080-91 = "……えっ？"
10050080-92 = "ああ、そうですね。必要によってはそうなります。"
10050080-93 = "どうかしましたか？"
10050080-97 = "そういうわけなのでご協力をお願いします！"
10050080-98 = "特に後ろめたいことがないのなら、断る理由はないかと――"
10050080-99 = "勝手なこと言うな――！！"
