[translation]
10052130-1 = "イェソド：礎を御する力の浄化者"
10052130-10 = "あの預言者、イェソドだっけ。"
10052130-104 = "私が前に出ます。今回は先鋒を務めますので。"
10052130-105 = "普段より武装が軽くなって、良い感じです。"
10052130-108 = "[ruby=Operation Steel Rain]オペレーション・スティールレイン[/ruby]――"
10052130-109 = "みんなが降下してくるまで、しっかりイェソドの注意を引きつけてね。"
10052130-112 = "エイミは最後方からの火力支援でしたね。"
10052130-113 = "この作戦だと、私の使い方はそれが一番効率的なんだって。"
10052130-114 = "では、よろしくお願いします。ご安全に。"
10052130-115 = "ご武運を。"
10052130-118 = "お互いにね。"
10052130-13 = "私たちが到着するなり、盛大な歓迎をしてくれましたね。"
10052130-14 = "なんとか一度は倒したけど……。"
10052130-17 = "……文字通り、鉄壁の守護者って感じだったよね。"
10052130-18 = "[ruby=path]パス[/ruby]と異名は全然違いますが。"
10052130-19 = "何だったっけ？"
10052130-20 = "パスは「完成に向かい進む真理」。"
10052130-21 = "異名は「礎を御する力の浄化者」、です。"
10052130-22 = "……それ、全部覚えてるの？"
10052130-23 = "他にやることが無かったので。"
10052130-24 = "え……？"
10052130-25 = "……すみません、失言でした。#n皆さん、やることが山積みだというのに。"
10052130-26 = "また反射的に言ったでしょ。#nトキはもうちょっと空気を読めるようになるといいかもね。"
10052130-27 = "そうですか、これから注意します。#nそれと反射的に冗談を言ったのは事実です。"
10052130-28 = "……怖いので。"
10052130-29 = "……トキも、怖いと思う？"
10052130-30 = "エイミは？"
10052130-34 = "私も怖い。"
10052130-35 = "みんなは私を――"
10052130-36 = "私たちを――"
10052130-37 = "どこか変わってる生徒だと思ってるかもしれないけど……。"
10052130-38 = "感じ方は同じだからね。"
10052130-39 = "面倒なものは嫌だし、怠けてたいし。"
10052130-4 = "位置に着いたよ。"
10052130-40 = "できれば私は、先生と一緒にポテチを食べながら実況動画でも観ていたいです。"
10052130-41 = "実況動画？"
10052130-42 = "私、趣味を探している最中ですので。"
10052130-43 = "いわゆる、趣味（仮）というものです。ぶい。"
10052130-44 = "……かっこ仮？"
10052130-45 = "はい。今は実況動画に少し興味がありますが、またすぐ変わるかもしれません。"
10052130-46 = "趣味（仮）って他にもあるの？"
10052130-47 = "うーん、やはりゲームでしょうか。アリスと遊ぶのは楽しいです。#nあとは、漫画もそこそこです。"
10052130-48 = "色々やってみて、少し気づきました。#n楽しさとは、ある程度の非合理性と非効率性を含んでいるのだと。"
10052130-49 = "漫画にゲーム……なるほどね。"
10052130-5 = "あの上に登るのですね。"
10052130-50 = "私だって別に戦うことが好きってわけじゃないよ。#nもっと効率的に解決する方法があるなら、そのほうがいいし。"
10052130-51 = "みんな、仲良くしてくれればいいのに。"
10052130-52 = "この状況も、そうあってくれれば良かったのですが……。"
10052130-53 = "私は今、怖いです。#n万が一何かが起きて、先生や私が明日を迎えられなくなると思うと……。"
10052130-54 = "それだけで、胸が苦しくなります。"
10052130-55 = "私は？"
10052130-56 = "私や先生の次くらいに心配です。"
10052130-57 = "……本気？"
10052130-58 = "冗談です。人の命に上下なんてありません。"
10052130-59 = "……ありがとう。"
10052130-6 = "……。"
10052130-60 = "私は誰も傷つかないでほしいです。"
10052130-61 = "今を生きるすべての人から、苦しみがなくなってほしいです。"
10052130-62 = "それは……ちょっと難しいかな。"
10052130-63 = "だからみんな、せめて手の届く範囲の人だけでも、って無事を祈ってる。#nこの世界は怖いことだらけだからね。"
10052130-64 = "部長だけでも大変なのに、最近は会長まで……。"
10052130-65 = "……先生のことも、すごく……心配だし。"
10052130-66 = "そっか、ミレニアム特製のシェルターに閉じ込めておけばいいのかな。"
10052130-67 = "先生の安全を保障するなら、一番効率的な方法かもね。"
10052130-68 = "キヴォトスを相手に戦争でもするつもりですか？"
10052130-69 = "いいでしょう。その気なら、私は堂々と最前線に立ちます。"
10052130-7 = "あれをなんと呼べばいいのでしょう？"
10052130-70 = "……冗談だって。"
10052130-71 = "私も冗談です。"
10052130-72 = "トキって、冗談か本当か分からないんだよね……。"
10052130-73 = "そうですか。ですがおかげで、1つ学びがありました。"
10052130-74 = "危険で大変な状況だからこそ。"
10052130-75 = "積極的に冗談を言って、他愛もない話で笑うべきだと。"
10052130-76 = "……そうでないと、耐えられませんので。"
10052130-77 = "じゃあトキの普段のやつも、それの延長線上なの？"
10052130-78 = "いえ、あれは思いついたことを適当に言っているだけです。"
10052130-79 = "……ほんと、トキらしいね。"
10052130-8 = "うーん……壁？"
10052130-88 = "トキ、エイミ、聞こえるかしら。こちらの準備は完了したわ。#n動きは合わせるから、突入のタイミングは貴女たちが決めてちょうだい。"
10052130-89 = "いよいよ終わりが見えてきましたね。随分と長い道のりでしたが……。"
10052130-9 = "はい。一番しっくりくる呼び方だと思います。"
10052130-90 = "これが最後の預言者ってことでいいんだよね？"
10052130-91 = "正確にはまだ2体残ってるよ。鋼鉄大陸そのもののネツァクと――"
10052130-92 = "マルクト……。"
10052130-93 = "うぅぅ……わ、わたし達で倒せるのかな……？"
10052130-94 = "大丈夫です、ユズ！私たちみんな新しい武器と鎧を手に入れました！#nケイもたくさんレベルアップしています！"
10052130-95 = "はい……前よりはマシになったかと。#n預言者の力を、多少は活用できるようになったわけですし。"
10052130-98 = "時が来たって感じだね。"
10052130-99 = "はい。"
