[translation]
10051090-1 = "第9話;意図された偶然"
10051090-10 = "あの日以来、何かが変わってしまったんです！"
10051090-100 = "主殿もそう思いますか？"
10051090-101 = "一体、どうしてなんでしょう……？"
10051090-102 = "[s] \"イズナはどう思う？\""
10051090-103 = "……。"
10051090-104 = "多分……理由は分かっている気がします。"
10051090-105 = "ツクヨ殿が、忍術研究部に戻ってこないこと……だと思います……。"
10051090-106 = "部長が気落ちしてしまっているので……イズナは、あえて明るく振る舞おうとしました。"
10051090-107 = "2人とも沈んでいては、前に進めないと思ったんです。"
10051090-108 = "でも……もうどうすればいいのか、イズナには分かりません……！"
10051090-109 = "ツクヨ殿とはいまだに連絡が取れませんし……。#n新年記念ファッションショーの準備映像はずっとアップされているので、#n元気ではあるみたいなのですが……。"
10051090-11 = "[s] \"変わった？\""
10051090-110 = "[s] \"じゃあ、一緒にツクヨの居場所を探してみようか。\""
10051090-111 = "そうしたいのですが……部長は動こうとしないと思います。"
10051090-112 = "ツクヨ殿と会うのを意図的に避けているような気がして……。"
10051090-113 = "それでも、どうにかして2人を会わせなければいけません。"
10051090-114 = "そうしないと、解決の糸口はつかめないと思うんです。"
10051090-115 = "[s3] \"ミチルとツクヨを会わせたいんだよね？\"\n[s4] \"それなら、いいアイデアが思いついたかも。\""
10051090-12 = "上手く言えないのですが……#n目に生気がないというか……やる気を失った……？気弱になった……？"
10051090-121 = "本当ですか！？"
10051090-122 = "[s] \"準備ができたら連絡するから、少し時間をもらえるかな。\""
10051090-123 = "はい！お待ちしております！"
10051090-128 = "なるほど……それであれば、難しくはありませんね。"
10051090-129 = "うまく話をつけておきましょう。"
10051090-13 = "昨日なんて、こんなことがあったんです！"
10051090-130 = "[s] \"急にこんなお願いしてごめんね。\""
10051090-131 = "にゃはは、謝る必要はありません。むしろ、感謝したいくらいですから。"
10051090-132 = "だってこれしきのことで、先生の「1回限定・無制限使用券」を手に入れたようなわけですし？"
10051090-133 = "[s] \"それ、どこで発行されてるの……！？\""
10051090-135 = "にゃはは、何をしていただくか……今から楽しみにしていてくださいね？"
10051090-139 = "それはそれとして。#nそちらでも魑魅一座が騒ぎを起こしていたんですね。"
10051090-140 = "年末に入ってから、ちょ～っとおいたが過ぎるんですよねぇ。#nまぁ、こっちは追々考えることにいたしましょう。"
10051090-141 = "はてさて、先生のお願いを実現するには、どこに連絡したものか……。"
10051090-142 = "う～ん……。"
10051090-143 = "「百鬼夜行新年記念ファッションショー運営委員会」……まずはここですかね。"
10051090-145 = "（数日後、ついに大晦日が目前に迫った）"
10051090-147 = "つまり……ここで忍者のイベントが開かれるってこと？"
10051090-148 = "その通りです！"
10051090-149 = "私たち、わざわざおめかしして来る必要あったのかな……？"
10051090-15 = "百鬼夜行商店街"
10051090-150 = "もうすぐ新年ですから！こぞって綺麗な服を着て来るはずです！#nイズナたちだけ普段着というわけにはいきません！"
10051090-151 = "そう言われればそうかもだけど……。"
10051090-152 = "あれ？でもここって裏口じゃない？#nイベント会場の正門は反対側なんじゃ……？"
10051090-158 = "あぁ、お待ちしてました。"
10051090-159 = "[ruby=ちどり]千鳥[/ruby]ミチルさん、[ruby=くだ]久田[/ruby]イズナさんですね？"
10051090-160 = "はい、そうです！"
10051090-161 = "イズナ、予約までしておいたの？"
10051090-162 = "[s] \"やあ、2人とも。\""
10051090-163 = "ふにゃあっ！？先生殿まで！？"
10051090-164 = "ってことは……相当すごいイベントなんだね……！？"
10051090-165 = "それではまず、こちらのインカムをお付けください。"
10051090-166 = "……うん？インカム？"
10051090-167 = "おぉ、イベントの案内を無線でしてくれるの？"
10051090-168 = "皆さんのお仕事は簡単です。#n人混みの中を巡回して、不審者がいれば報告または制圧してください。"
10051090-169 = "不審者がいたら制圧して……って、ちょっと待って。"
10051090-17 = "ふぅ、ごちそうさまでした！"
10051090-170 = "仕事？制圧！？"
10051090-171 = "イズナ、これってまさか……。"
10051090-175 = "百鬼夜行新年記念ファッションショーへようこそ、警備員の皆さん。"
10051090-18 = "今日も「忍者定食」は期待を裏切らないですね！"
10051090-180 = "な、なにこれーーー！？"
10051090-181 = "警備員！？私たち騙されたってこと！？これ雇用詐欺だよ！主催側の陰謀だ！"
10051090-182 = "陰謀ではありません！"
10051090-183 = "この仕事は、イズナが引き受けたんです！"
10051090-184 = "えっ？それって……どういう意味？"
10051090-185 = "っていうかこの建物――"
10051090-186 = "ツクヨが出るファッションショーの会場じゃない！？"
10051090-187 = "これのどこが忍者イベントなのさ！"
10051090-188 = "忍者が参加するなら、それが何であろうと「忍者イベント」です！"
10051090-189 = "まさか部長……ツクヨ殿は忍者の心を持っていない、と言うつもりではないですよね？"
10051090-19 = "ですよね、部長？"
10051090-190 = "そ、それは違うけど……！"
10051090-191 = "私は……ツクヨを……。"
10051090-192 = "……時間です。行きましょう。"
10051090-193 = "いざ、参りましょう！"
10051090-197 = "く、くうぅぅぅ……！"
10051090-2 = "シャーレ・オフィス"
10051090-20 = "……。"
10051090-21 = "部長？"
10051090-22 = "あ？う、うん。そうだね、美味しかったよ。"
10051090-23 = "何か、あったんですか……？"
10051090-24 = "え？いやいや、何もないって。大丈夫だよ。"
10051090-28 = "（どう見ても大丈夫じゃないです……）"
10051090-29 = "それでは、来週撮影する「少女忍法帖ミチルっち」の内容について話し合いませんか？"
10051090-3 = "あっ、主殿……！"
10051090-30 = "あっ、そうです！あそこの呉服屋さんの隣に、新しいお茶屋さんができてたんです！#nそこで話しましょう！"
10051090-31 = "いや、来週は動画撮るつもりないし……。"
10051090-32 = "ネタがまだなら、相談しなきゃいけませんよね！#nイズナ、アイデア出しでもどんと来いです！"
10051090-33 = "いや、だから私は……。"
10051090-34 = "あのお茶屋さん、お団子のセットがおすすめだって聞きました！"
10051090-35 = "行きましょう、部長！ちょうどあそこに……！"
10051090-4 = "あの……その……。"
10051090-40 = "ちょ、ちょっと待って、イズナ、実は……。"
10051090-45 = "ドカーン！"
10051090-47 = "ええっ……！？"
10051090-48 = "誰かが呉服屋さんの前で煙幕を使ったみたいです！"
10051090-5 = "部長が……部長の様子がおかしいんです……！"
10051090-53 = "よし！煙幕の効果はバッチリだ！"
10051090-54 = "こんな不親切な店に入ったら、客がかわいそうだからな！"
10051090-55 = "そうそう！客の要望を無視して、自分の都合ばっかり押しつけてくるんだもんな！"
10051090-56 = "こんな店、潰れて当然だろ！"
10051090-6 = "[s1] \"イズナ、ひとまず落ち着こう。\"\n[s2] \"それで、ミチルの様子がどうしたの？\""
10051090-60 = "ちょっと！人の店の前で何してるのよ！？"
10051090-61 = "何って、お前が客の要望を無視するからだろ？"
10051090-62 = "私が、無視したって……？"
10051090-63 = "タコ焼きとコーヒーを出せなんて要望、呉服屋にどうやって応えろって言うのよ！？"
10051090-64 = "客が頼んだら出せばいいだけだろ？ガタガタうるさいな！"
10051090-65 = "そんな頭の固いやり方で、商売やってけると思ってんのか？"
10051090-66 = "何言ってんの！？#n商売できてない原因はあなた達なんですけど！？"
10051090-67 = "くっ……論理的に返された……！"
10051090-68 = "怯むな！私たちは報酬だけを考えるんだ！"
10051090-69 = "ちょっと、報酬？それ、誰からもらってるの？"
10051090-70 = "あっ、つい口が……！"
10051090-75 = "部長！魑魅一座が呉服屋さんの前で騒ぎを起こしてます！"
10051090-76 = "イズナたちが行って……って、あれ？部長？"
10051090-79 = "え？なに？"
10051090-80 = "部長！今こそ動く時です！"
10051090-81 = "う、うん？そ、そうかもだけど……。"
10051090-82 = "でもさ、ああいうのって……百花繚乱の担当、じゃないかな……？"
10051090-83 = "それに、今はツクヨもいないし……。"
10051090-84 = "ツクヨ殿がいないからって、忍者の精神まで失われるわけではありません！"
10051090-85 = "ううぅ、それはそうなんだけど……。"
10051090-9 = "先日……一緒にラーメンを食べて別れた時までは元気だったのですが……。"
10051090-90 = "ぶ、部長！"
10051090-95 = "シャーレ・オフィス"
10051090-96 = "……という事があったんです。"
10051090-97 = "部長……すごくしょんぼりしてて、何に対しても自信なさげで……。"
10051090-98 = "イズナ、あんな部長を見るのは初めてで……。"
10051090-99 = "[s] \"たしかに、それはいつものミチルじゃないね……。\""
