[translation]
10051070-1 = "第7話;見知らぬ空白"
10051070-10 = "いえいえ、返却は都合のいい時で構いませんよ。"
10051070-100 = "えっと……ニヤらしくない気配りはありがたいけど……。"
10051070-101 = "でも、ツクヨの代わりって、簡単じゃ――"
10051070-107 = "[ns] \"こんにちは。本日限定の臨時アシスタントです。\""
10051070-108 = "どっひゃぁああ！？"
10051070-109 = "主殿！"
10051070-11 = "それなら、ゲスト出演でしょうか！？"
10051070-110 = "いきなり出てくるなんて心臓に悪いでしょ！"
10051070-111 = "[s1] \"これもアンブッシュかな。\"\n[s2] \"挨拶の前の1度だけなら、許されていたのでは？\""
10051070-114 = "流石は先生殿！私の教えをちゃんと覚えて――"
10051070-115 = "……ってそうじゃなくて！#nニヤ、まさか先生殿を撮影アシスタントにしたの？どうやって！？"
10051070-116 = "にゃはは、細かいことはいいじゃないですか～"
10051070-117 = "では、用事は済みましたので、今度こそ失礼します～"
10051070-12 = "忍の道はいつでも開かれていますよ！にんにん！"
10051070-121 = "主殿！お会いできて嬉しいです！"
10051070-122 = "不意打ちだと感動も一入です！ニンニン！"
10051070-123 = "先生殿が撮影に加わるなんて……。"
10051070-124 = "これは予想外すぎる展開だよ……。"
10051070-125 = "えっと、それじゃあ……撮影を始めてもいいのかな……？"
10051070-126 = "ん？ツクヨ抜きでいいのか、って？"
10051070-127 = "良くは無いけど……電話は繋がらないし、モモトークには返信無いし……#n居場所すら分からないから、どうしようもなくて……。"
10051070-128 = "[s3] \"ツクヨの居場所はわからないけど……。\"\n[s4] \"連絡を取る方法ならあるよ。\""
10051070-13 = "生憎、それもハズレでして……。"
10051070-131 = "ツクヨに連絡取れるの！？"
10051070-132 = "本当ですか！？"
10051070-133 = "ど、どうやって！？"
10051070-134 = "[s] \"ニヤから、マネージャーの連絡先をもらったんだ。\""
10051070-135 = "……！"
10051070-136 = "部長！今すぐ電話しましょう！"
10051070-137 = "もちろん！"
10051070-138 = "その前に……すぅぅ……はぁぁ……。"
10051070-139 = "[s] \"深呼吸してるの？\""
10051070-140 = "知らない人に電話するのって怖いから……じゃなくて、慎重にいかなきゃだから！"
10051070-141 = "それじゃあ……先生殿から教えてもらった番号に電話を……ふぅぅ……。"
10051070-147 = "プルルルル……。"
10051070-148 = "カチッ。"
10051070-15 = "じゃあ陰陽部の部長が何の用なのさ。ただの偶然？"
10051070-151 = "はい、もしもし。"
10051070-152 = "あ……あの、こんにちは！"
10051070-153 = "はい？どちら様ですか？"
10051070-154 = "そ、そうだ！実はその、ツクヨという忍者……じゃなくて、モデルさん、そちらにいますか？"
10051070-155 = "ツクヨですか？"
10051070-159 = "……ああ、また記者か。"
10051070-16 = "まぁ、通りすがり……みたいなものでしょうか。"
10051070-160 = "いいですか？記者会見も行いましたし、プレスリリースも出してますよね？"
10051070-161 = "今は少し手が離せませんので、これで失礼します。"
10051070-162 = "ちょ、ちょっと待って！私は記者じゃないの！"
10051070-163 = "私は[ruby=ちどり]千鳥[/ruby]ミチル！ツクヨの友達だよ！！"
10051070-164 = "あなたが……ミチルさん？"
10051070-165 = "えっ？私のこと知ってるの？"
10051070-167 = "まさか、「少女忍法帖ミチルっち」のチャンネル登録者……！？"
10051070-168 = "にんぽ……なんですって？"
10051070-169 = "すみませんが、そのようなチャンネルは存じ上げません。#nあなたの名前を知ってるのは、ツクヨさんが話してたからです。"
10051070-17 = "それより……やはり、ツクヨさんはいらしていないようですね。"
10051070-170 = "それで、用件は何ですか？"
10051070-171 = "そ、そう！用件！あなた達、ツクヨに何をしたの！？"
10051070-172 = "はい？"
10051070-173 = "電話に出ないし、モモトークも既読にならないんだよ！"
10051070-174 = "ああ、そんなことで……。"
10051070-175 = "そんなこと……？"
10051070-176 = "仕事に集中してもらうために連絡を遮断するのは、プロの世界ではよくあることです。"
10051070-177 = "今は、ツクヨさんのスマートフォンを一時的にお預かりしています。"
10051070-178 = "預かってる！？"
10051070-179 = "それに今、ツクヨさんがどれだけ真剣に撮影に取り組んでるか、わかってますか？"
10051070-18 = "そうなの。しかも、ずっと連絡が取れないんだよね……。"
10051070-180 = "ツクヨが……？"
10051070-181 = "ええ。ですから、お話はここまでにさせていただきます。"
10051070-182 = "ちょっ、ちょっと待って！少しでいいからツクヨと話を――"
10051070-183 = "ツクヨさんについてはご心配なく。今晩、私たちのチャンネルで撮影風景の動画が公開されますので、そちらをご確認ください。"
10051070-184 = "それでは、失礼します。"
10051070-189 = "ぶ、部長……。"
10051070-190 = "……。"
10051070-194 = "よし、もう泣き言はおしまい。"
10051070-195 = "部長！？"
10051070-196 = "ツクヨだって今日、動画をアップするって言ってたじゃん。#nだったら私たちも負けてられない！"
10051070-197 = "ツクヨがいなくても……今の私たちにできることをやろう！"
10051070-198 = "何より、先生殿も手伝ってくれるんだし！#n……ね？"
10051070-199 = "[s] \"もちろん！\""
10051070-2 = "「少女忍法帖ミチルっち」撮影現場"
10051070-200 = "じゃあイズナ……撮影準備だ！"
10051070-201 = "はいっ！部長！"
10051070-205 = "――さて、今日の「少女忍法帖ミチルっち」のテーマは！#n……潜入状況での忍法！"
10051070-206 = "どこにどんな暗器を仕込むべきか、どの流派の技を活用するべきか！"
10051070-207 = "そのすべてを！私が――"
10051070-208 = "私……が……。"
10051070-209 = "……。"
10051070-210 = "[s] \"ミチル、大丈夫？\""
10051070-211 = "部長……やっぱり、今日の撮影は別の日に延期した方が……。"
10051070-215 = "ふぅぅ……。"
10051070-216 = "いや、撮影は……このまま続ける……！"
10051070-22 = "……ん？「やっぱり」ってどういう意味？"
10051070-24 = "ああ、ツクヨさんは忍術研究部を抜けたと伺ったので。"
10051070-29 = "えええぇっ！？"
10051070-3 = "にゃはは～。どうも。"
10051070-30 = "そ、そんなの聞いてないんだけど！？"
10051070-31 = "その反応も予想通りと言いますか……。"
10051070-32 = "みなさん、忍者以外には興味がなさそうですからね……。"
10051070-33 = "えっ？いやいやいや！冗談だよね？"
10051070-34 = "だって私は部長だよ！？部長が知らないってどういうこと！？"
10051070-35 = "ん～、「ron-ro」とか「ハートガールズ」って雑誌、読んでたりします？"
10051070-36 = "何それ？"
10051070-37 = "では「BiBi」もご存じないでしょうね……SNSはやってますか？"
10051070-38 = "「少女忍法帖ミチルっち」チャンネルなら運営してるよ。"
10051070-39 = "つまり、SNSもやってない、と。#nそれなら当然、あの番組もご覧になっていないのでしょうね。"
10051070-4 = "カメラからドレスまで……お貸ししたものがしっかり活用されているのを見ると、こちらとしても嬉しくなりますね。"
10051070-40 = "何の話？"
10051070-41 = "百聞は一見に如かず。こちらは、クロノスチャンネルにアップされた動画です。"
10051070-47 = "では最後の質問です！#nツクヨさんの今後の目標を、一言で教えていただけますか！"
10051070-48 = "あ、あの……これから、か、かっこいいファッションモデルになれるよう、#n頑張り、ます……！"
10051070-49 = "そんなツクヨさんのこれからの活躍、楽しみに――"
10051070-54 = "え……。"
10051070-55 = "こ、これって……。"
10051070-56 = "え……？ツクヨが、モデル……？#nずっと……モデル活動するってこと？"
10051070-57 = "部長……。"
10051070-58 = "……。"
10051070-59 = "なんで……いつからなの……？"
10051070-60 = "先日のファッションショーで、ツクヨさんが代理モデルとして出演したそうですね。"
10051070-61 = "あの時のステージ、ファッション業界では大反響だったそうで～"
10051070-62 = "おそらくはその直後、「シャインキャット・エージェンシー」がスカウトしたようです。"
10051070-63 = "まさか、丸っきりご存知ないとは思いませんでしたが。"
10051070-64 = "……。"
10051070-65 = "全然知らなかった……。"
10051070-66 = "……この話をするには、少し時期が悪かったかもしれませんね。"
10051070-67 = "では、今日はこれで失礼します。"
10051070-71 = "部長……ツクヨ殿は……。"
10051070-72 = "イズナ……あのステージに立ってたツクヨの姿、覚えてる？"
10051070-73 = "……もちろんです。"
10051070-74 = "どうだった？"
10051070-75 = "……綺麗だな、って思いました。"
10051070-76 = "それから？"
10051070-77 = "それから……うぅ……。"
10051070-78 = "まるで、別世界の人みたいだって思わなかった？"
10051070-79 = "……！"
10051070-8 = "ニヤ殿……！"
10051070-80 = "私たちはステージの下、一番暗い隅っこから見上げてて――"
10051070-81 = "ツクヨは、ステージの一番高くて明るい場所に立ってた。"
10051070-82 = "でも部長……忍者とは、一番暗いところで熱い心を灯す存在……ですよね？"
10051070-83 = "うん。だからこそ……ツクヨは、私たちのことを……。"
10051070-87 = "あ、そうそう。1つ言い忘れてました。"
10051070-88 = "うにゃぁっ！？"
10051070-89 = "まだ帰ってなかったの！？"
10051070-9 = "もしやドレスを回収しにいらしたのですか！？"
10051070-90 = "ええ。真の目的を果たしていなかったなと思いまして、にゃはは。"
10051070-91 = "目的？さっき通りすがりって……。"
10051070-92 = "意図された偶然ってあるじゃないですか～"
10051070-93 = "……全然意味わかんない！"
10051070-94 = "意図があるなら、それもう偶然じゃないよね！？"
10051070-95 = "こういう言葉遊びが必要な場もあるというわけでして～"
10051070-96 = "まぁ、今はまったく必要無いので、本題に入りましょうか。#nツクヨさんは今日の撮影を欠席されるみたいですので――"
10051070-97 = "良かれと思って、代わりの撮影アシスタントを手配しておきました！"
10051070-99 = "撮影アシスタント……ですか！？"
