[translation]
10050050-1 = "第5話;冬の国の公女様"
10050050-2 = "どこかの体育館"
10050050-4 = "列はこちらです！まだ在庫は残っていますので！"
10050050-8 = "走らないでください！順番に！#nあと、秘密厳守でお願いします！"
10050050-11 = "トリニティの方々が頒布を手伝ってくださるとは……これもまた「文化」の力なのでしょう。ムフフ。"
10050050-12 = "ええ。文化……ソフト・パワーは、自発的に人を動かすという点に最大の魅力がありますわ。"
10050050-13 = "せっかくですし、キヴォトス最大規模と言われている中央図書館や、古書館も一目見れたらよかったのですが……。"
10050050-14 = "そのうちチャンスが巡ってくるでしょう。評論家のタカネが興味を持つのも理解できます。"
10050050-15 = "部長は違うのですか？"
10050050-16 = "ええ、全く興味がありません。それらを私の好きにできて、売上に繋げられるのならまた話は別ですけどねぇ。"
10050050-17 = "可能性のないものにまで時間を割く暇はないといいますか。"
10050050-18 = "……その割には添削とか、編集に力を入れているように見えますが。"
10050050-19 = "ただの添削や編集じゃありませんよ？原石を磨いているのです。商品価値の再発見というわけです。"
10050050-20 = "そしてその延長線上で……タカネにだって、頑張って頂きたいのですよ！"
10050050-21 = "うっ……！またあれをやるのですか……？"
10050050-22 = "どうしても嫌というなら強制はしません……でも、もう皆さん知っているじゃありませんか。"
10050050-23 = "タ・カ・ネ・姫？"
10050050-24 = "はぅっ！？"
10050050-26 = "ああ、そうでした。タカネ姫！今回の3巻と4巻についてのご感想を伺いたいのですが。"
10050050-27 = "はっ、はぅぅういっ！？わわ、分かりましたわ……私の感想で、よろしければ……。"
10050050-28 = "もちろんです！そもそもこの作品は、トリニティでは珍しい――"
10050050-29 = "レッドウィンター特有の根気強さと野性味があって、とても現実的に描かれていますが……。"
10050050-30 = "最後まで美しさを手放さない、どこか強い意志を感じるのです！#nだからこそ人気があるのでしょう！"
10050050-31 = "作品の「意志」を納得できるよう説明できるお方は、タカネ姫だけなのです！"
10050050-32 = "そ、そそそう言っていただけるのは、嬉しいかぎりですが……。"
10050050-33 = "もう、謙虚なんですから！さすがレッドウィンター……いいえ、冬の国の公女様は、身も心も清らかなのですね！"
10050050-35 = "これ、どうするつもりですか部長！？#n私はレッドウィンターの普通の生徒ですよ！？"
10050050-36 = "どうして私が「レッドウィンターの没落した名家の末っ子」になってしまったのです……！"
10050050-37 = "答えはシンプルです、タカネ。それはもちろん……。"
10050050-38 = "そっちの方が売れるから、です！"
10050050-39 = "タカネ姫はレッドウィンターの名家の末っ子とお聞きしました。"
10050050-40 = "紆余曲折の末、没落の道をたどり……。"
10050050-41 = "一家全員が退学を命じられ、レッドウィンターを追放されたと……胸が痛い話ですわ。"
10050050-42 = "え、ええ。恐れ入ります……。"
10050050-43 = "そんな中、真面目な付き人のおかげで、タカネ姫だけが出身を隠して生き延びられた……本当にすごいですわ！"
10050050-44 = "本の中の物語のような、波乱万丈な人生を歩んだ方と話せるだなんて……。"
10050050-45 = "本当に光栄です！"
10050050-46 = "（だって、本で読んだ話を元にしたのですから……）"
10050050-47 = "お姉さま方の件は残念です……。ええと、3人のお姉さま方とタカネ姫の名前の頭文字を取って、日記に「OAMT」と書かれていましたね……？ですが皆さんは……。"
10050050-48 = "写真が趣味と仰ってましたよね？今度ぜひ見せてくださいね！"
10050050-49 = "（それだけは本当の話ですが……他はもうめちゃくちゃですわ）"
10050050-50 = "実は専門的な評論を聞いたのは初めてなんです。しかも姫君の口から語られるなんて……。"
10050050-51 = "私たちツイてましたね……！ちなみに、評論集の出版のご予定は？"
10050050-52 = "ふむ？これはまた新たなビジネスの予感が。"
10050050-53 = "やめてください！！"
10050050-55 = "あ、あの……友人から、例の話を聞いて来たのですが……。"
10050050-56 = "ささ、どうぞどうぞ。こういうのはまず始めることが肝要です。1冊いかがです？"
10050050-57 = "あ、ありがとうございます……！"
10050050-58 = "……！！"
10050050-59 = "なっ、ななんて破廉恥なっ！？"
10050050-64 = "ど、どうしましょう部長？大丈夫でしょうか……！？"
10050050-65 = "大丈夫大丈夫、そのうち帰ってきますから。これは直感です。"
10050050-66 = "だといいのですが……。"
10050050-73 = "そんな……！？"
10050050-74 = "ムフフフフ。"
10050050-75 = "あの、いや別に次が気になって戻ってきた、とかじゃないんですけど……。"
10050050-76 = "い、一応読み始めたからには、最後までついていくべきじゃないかな、っていう使命感で……。"
10050050-77 = "ええ、ええ！もちろんです。分かっておりますとも。"
10050050-78 = "あ……ありがとうございます。続き……ありますか？"
10050050-79 = "ありますとも。どんなストーリーも次があるべきです。ショーが続いていくようにね。"
10050050-80 = "むしろ感謝するのはこちらです。"
10050050-81 = "そ、そうなんですか？"
10050050-82 = "もしこの本があのままレッドウィンターで眠っていたら、きっと誰にもこの価値を分かってもらえず、ただ忘れ去られてしまったことでしょう。"
10050050-83 = "……売り場というリングで、パンチ一つ残せずに。"
10050050-84 = "負けてこそスッキリするものですが、チャンスさえ与えられないのは悲しき事態です。"
10050050-85 = "たしかに、そうかも……。"
10050050-86 = "ええ！そんなあなたには、3冊ではなく2冊の購入をオススメしましょう。"
10050050-87 = "でも、ここには3冊が暗黙の了解だって……。"
10050050-88 = "ですが、布教はどこか照れくさいのでしょう？2冊で十分では？"
10050050-89 = "じゃ、じゃあ2冊ください……。"
10050050-91 = "――ですから、[ruby=せい]生[/ruby]のとある部分は排除され、とある部分は受け入れられることに矛盾が生じるのは当然です。"
10050050-92 = "羞恥を感じ、話題にしにくいものこそ、私たちの本質を分かりやすく説明しているのではないでしょうか？"
10050050-93 = "たとえば「愛」。これは表立って話すのは難しい話題と扱われがちです。しかし必要不可欠な感情であることを知らぬ者はいません。"
10050050-94 = "愛がなければ……ここに皆さんは存在していないのですから。"
10050050-95 = "私たちのカラダのことも然り。衣服の下の話は口にしないのがレディのたしなみと言われていますが……。"
10050050-96 = "それでも私たちは、カラダとともに生きていく存在です。"
10050050-97 = "そしてこちらは、そんな矛盾と私たちが惹かれる対象について、率直でありながらも、能動的な対話を試みています。"
10050050-98 = "私たちをより良い認識の地平へと導く、純粋な意志が込められた最高傑作といえるでしょう。"
10050050-99 = "きゃ～～っ！！"
10050050-100 = "タカネ姫～～！！"
10050050-101 = "やはり高貴な方は違いますわ！"
10050050-102 = "私たちはもっと、自分に正直になっていいのですね……？"
10050050-103 = "（胃が痛くて倒れそうですわ……）"
10050050-108 = "ほう、大盛況と……。"
10050050-109 = "しかし、ちょっとばかり物足りないような……むむ。"
10050050-110 = "あの……こういう本はないですか？"
10050050-111 = "どういうものでしょうか？"
10050050-112 = "えっと……。"
10050050-116 = "んー……残念ながら、それとピッタリ一致する本はまだ無いものでして……。"
10050050-117 = "そうですか……。"
10050050-118 = "いや……「まだ」ない……ってことは？"
10050050-119 = "少々お待ちを！なんとかなるかもしれません！"
10050050-120 = "本当ですか！？"
10050050-121 = "の前に、企画書を一ついただけません？"
10050050-122 = "企画書……？そ、そういうのは私作ったことが……。"
10050050-123 = "大丈夫ですよ。二行くらいでいいです。こういうキャラがいてほしいとか、こういう内容だといいな、くらいで構いませんので。"
10050050-124 = "わ……分かりました。"
10050050-129 = "今度はなに？ヤクモ。急に売れなくなったとか、そういう話じゃないよね？"
10050050-130 = "まあ、昨日までの分でなんとか一息つけたけどさ。礼は言っとく。"
10050050-131 = "おや？メルが自分から礼を言うようになるなんて。あと、売り上げは変わらず好調ですのでご心配なく。"
10050050-132 = "それより今からカンタンな企画書を送りますので、これをいい感じに作ってください。早ければ早いほどいいです。"
10050050-133 = "えっ？なんで私が？あんたまた変な金稼ぎしようとしてるんでしょ。"
10050050-134 = "よく聞いてくださいよメル。私はいま現場でリクエストを受けているのです。これを速く作れば作るほど、言い値で売れるんですから！？"
10050050-135 = "……要はコミッションでしょ？あれ面倒くさいよ。要求は多いし、完成した後もああだこうだって……。"
10050050-136 = "いいえ、その反対です。だから二行の企画書をもらったんですよ。当然足りない部分だらけってわけで。"
10050050-137 = "その足りない部分は……全部メルの好きにすればよいのです！"
10050050-138 = "それで客が満足するかっ！"
10050050-139 = "するはずです。だってタカネが全部それらしく説得……いえ、評論するのですから。"
10050050-141 = "私ですか！？"
10050050-142 = "メル、これはある意味一次創作ですよ？#n今までずっと一次創作がしたかったのでしょう？"
10050050-143 = "！！！"
10050050-144 = "そ、それは……そう、だけど。"
10050050-145 = "もちろん100%オリジナルではないものの、要求は少ししかありません。#nあとはメルが好きにできるのです……。"
10050050-146 = "これはもうほぼ一次創作と言えるのでは？"
10050050-147 = "もちろん、一朝一夕でうまくいくものではありませんが……。#nこれを機に、目標へ向かって一歩踏み出してみるのはどうでしょう？"
10050050-152 = "やる！"
10050050-153 = "よーし成立。ではなるべく早めにお願いしますね。"
10050050-154 = "ああっもう、今から着手しますから！んじゃ！"
10050050-158 = "こちらもまた一件落着っと……ムフフ。"
10050050-159 = "……改めて、部長を敵に回しちゃいけないと思いましたわ。"
10050050-160 = "ん～？何のことやら？"
10050050-162 = "トリニティ外郭・カフェ"
10050050-163 = "お疲れ様でした、先生。"
10050050-164 = "[s] \"シミコも大変だったでしょ……。\""
10050050-165 = "ふふ、ありがとうございます。ただ、進捗がないのは残念です。"
10050050-166 = "[s] \"何が原因なんだろうね……？\""
10050050-167 = "先生はどう思われますか？"
10050050-168 = "……。"
10050050-169 = "なるほど。「本の販売者をトリニティの生徒たちが守っているみたい」……ですか。"
10050050-170 = "ここだけの話、私もそう思いました。それで正義実現委員会も手こずっているのではと。"
10050050-171 = "それで先生に、わざわざトリニティの外れまでお越しいただいたのです。"
10050050-172 = "[s] \"誰か力になってくれる人でも……？\""
10050050-173 = "はい、おそらく。あと先生もよく知っている方です。#nあっ、ちょうどあちらに……。"
10050050-178 = "こんにちは、コハルさん。"
10050050-179 = "せ、せせせせ先生！？なんでここに先生が！？！？"
10050050-180 = "[s] \"あれ？コハルだ。\""
10050050-181 = "待って、ここに先生がいるってことは……。"
10050050-182 = "やっぱり……。"
10050050-183 = "そうだと思った！全部先生のせいなんでしょ！#n私の目はごまかせないんだから変態！！"
10050050-184 = "[s] \"ちがう！今回は本当に私じゃない！\""
10050050-185 = "こ、ここ今回！？じゃあ他のは全部先生なんだ！？死刑！！！"
10050050-187 = "[ns] \"そっか、それでコハルが……。\""
10050050-188 = "はい、コハルさんが私にサンプルを渡してくださったのです。おかげさまで、少しばかりヒントを得られました。"
10050050-189 = "[s] \"ちなみになんで正義実現委員会じゃなく、図書委員会側に？\""
10050050-190 = "そ、それはっ……！"
10050050-191 = "えっと……。"
10050050-192 = "なんとなく、みんな……悲しむと思ったから……。"
10050050-193 = "他に意味はないよ！？みんな本のことを隠したり、なかったことにしようとしてるのに……。"
10050050-194 = "でも……この本のこと、好きみたいだから……。"
10050050-195 = "せ、正義実現委員会は悪くないから！与えられた仕事をしてるだけだし！"
10050050-196 = "ただそれとは別に、これだけファンがいる本をみんなから奪うのは悲しいと思って……。"
10050050-197 = "[s] \"コハルもこの本のことが好き？"
10050050-198 = "な、なんでそこで私が出るのよ！先生バカ変態死刑！！"
10050050-199 = "わわわ私は、こういうのはまったく！全然！興味ないから！！"
10050050-200 = "ではコハルさん、図書委員会がこちらの全巻を揃えた時、見に来ませんか？"
10050050-201 = "正義実現委員会の「エリート」として、内容は確認すべきかなと思いまして。"
10050050-202 = "……！"
10050050-203 = "分かってるじゃない！仕方ないから特別に確認してあげる！"
10050050-204 = "とんでもありません。大切に扱っていただきありがとうございます。"
10050050-205 = "べ、別に！……というか、図書委員会はみんな、そんな風に本を大事にするの？"
10050050-206 = "はい。みんなそうですよ。#n本は一つのタイムマシンですから。"
10050050-207 = "[s] \"タイムマシン？\""
10050050-208 = "はい。タイムマシン……あくまで比喩としてですけど。"
10050050-209 = "どういう意味？"
10050050-210 = "そうですね……世の中には多くの媒体がありますよね？本以外にも。"
10050050-211 = "動画や映画、ゲーム、音楽……#n他にも挙げきれないほどにたくさん。"
10050050-212 = "それらは、私達に情報や物語、時には感情を伝えてくれます。"
10050050-213 = "その中でも、私が本を好きな理由は……心に余裕をもたらしてくれるからです。"
10050050-214 = "なんか分かんなくなってきた……。"
10050050-215 = "映画やゲーム、動画はそれを見ている間、それに集中しないといけません。"
10050050-217 = "視覚と聴覚、場合によっては触覚を使って、私たちに情報を伝えようとしていますから。"
10050050-218 = "それらは、より物語の世界に没入しやすくしてくれますが……。"
10050050-219 = "だからこそ他の余裕を許してくれません。"
10050050-220 = "でも本は違います。多くの媒体の中で最も制限が多いものです……#n当然ですが本は少しの画像と、文字ですべてを表現しなければならない。"
10050050-222 = "たしかに……。"
10050050-223 = "だからこそ、余白を考える隙間を与えてくれるんです。#n寛大な媒体、といいますか。"
10050050-224 = "私にとって、本を読む行為は、過去との対話でもあります。"
10050050-225 = "全ての書き手は、過去から今に渡ってきた人たちですから……だからタイムマシンに例えてみました。"
10050050-226 = "[s] \"たしかに本は時間をかけて出版されるもんね。\""
10050050-227 = "はい。本を読んでいると、作者が遠い過去から私に話しかけているような気持ちになるんです。"
10050050-228 = "先ほども言ったように、本は「自分で考える余裕」を私たちに与えてくれるのですから……。"
10050050-229 = "作者に、私なりの考えと答えを返したいと思う、そんな自分がいて……。"
10050050-230 = "それって、本当に素晴らしいことだと思っているんです。"
10050050-231 = "[s] \"だからシミコは本を大切にしてるんだね。\""
10050050-232 = "はい。ですので、今トリニティで起きている非公認書籍のことも。"
10050050-233 = "どこか好意的に見ているのかもしれません。"
10050050-234 = "捜査官としては失格ですけどね……。"
10050050-235 = "で、でも私は……それでもいいと、思う。"
10050050-236 = "コハルさん……？"
10050050-237 = "その、厳しい部分は正義実現委員会が担当してるから……一人くらいは、本の味方になってくれてもいいかなって……。"
10050050-238 = "[s] \"そうだね、世の中に悪い人はいない！\""
10050050-239 = "そうそれ！やっぱり先生は分かってる！"
10050050-240 = "ありがとうございます。先生、コハルさん。"
10050050-241 = "ところで、この問題……どのように解決しましょう？コハルさん、あれから何か分かったことなどはありますか？"
10050050-242 = "ない……けど？"
10050050-243 = "そうですよね……申し訳ありません、ご負担をかけてしまったかもしれません。"
10050050-244 = "あ、いや、私はいいけど……。"
10050050-245 = "[s] \"むむ、生徒からの聞き込みがダメなら……。\""
10050050-246 = "どうしたの先生、何か思い出した？"
10050050-247 = "[s] \"コハル、一つお願いしてもいい？\""
10050050-248 = "お願い？別にいいけど……。"
10050050-249 = "で、でもエッチなのはダメだから！絶対やらないから！"
10050050-250 = "おそらく流れ的にそういったことは無いかと……。"
10050050-251 = "とにかく！"
10050050-252 = "え？#n「正義実現委員会の動きが活発になった時、委員会の子たちと仲良くしてみて」……？"
10050050-253 = "で、でも今は私、正義実現委員会所属じゃ、ないけど……？"
10050050-254 = "[s] \"大丈夫、みんなきっと気にしないはず。\""
10050050-255 = "わ、分かった。先生がそう言うなら……。"
10050050-257 = "こんばんは、マシロさん。調査の進捗はどうですか？"
10050050-258 = "……申し訳ありません、思ったよりも難航していて……。"
10050050-259 = "ええ、そのようですね。話は聞いております。"
10050050-260 = "どうしても難しそうでしたら、ティーパーティーからも何か措置をしますので、あまりご負担に思わないでください。"
10050050-261 = "（……！！）"
10050050-262 = "申し訳ありません、ナギサ様！やっぱり不安ですよね！"
10050050-264 = "最善を尽くして、必ず見つけてみせます！！……では、失礼します！"
10050050-268 = "ま、マシロさん……！？"
10050050-272 = "ただの激励のつもり、だったのですが……。"
