[translation]
10052015-10 = "ど、どうしてそんなに落ち着いてるんですか……？"
10052015-11 = "うーん、理由は色々あるけど……。"
10052015-12 = "前にも遭遇したことあるからかな。"
10052015-14 = "[ns] \"ところで、ビナーのコアは？\""
10052015-15 = "そのことなんですが……。"
10052015-16 = "結論から言いますと、穴を降りる必要があります。#n反応からして、コアはこの底にあるみたいです。"
10052015-17 = "ええっ！？降りる！？"
10052015-18 = "もしかして、この先も毎回……？"
10052015-19 = "いえ、先ほども話しましたが、ビナーが特殊なだけだと思います。#nある種のセキュリティ対策なのでしょうね。"
10052015-20 = "ぶ、物理的な対策だね……。"
10052015-21 = "でも、底が見えないのに、ただただ降りるのは非効率的すぎるよ……。"
10052015-22 = "部長、輸送船にある小型の支援機、送ってくれる？"
10052015-23 = "すでに向かわせています。"
10052015-24 = "……ちなみに、リオも一緒です。止めても聞かなかったので。"
10052015-25 = "会長も来るの？"
10052015-26 = "はい。追加の調査で、ネットワーク経由ではファイアウォールを突破できないことが判明しまして……。"
10052015-27 = "現場に出向くのが最も合理的だ、と……。"
10052015-28 = "……リオらしいですね。"
10052015-3 = "……。"
10052015-31 = "（まもなく小型の支援機が到着し、リオが姿を現した）"
10052015-32 = "（みんなの何とも言えない顔に、リオは首を傾げていた）"
10052015-4 = "……。"
10052015-5 = "え、夢じゃないよね……？"
10052015-6 = "うん、現実だと思う。くねくね動いてて……すごかったね……。"
10052015-7 = "私たち、無事に帰れるのかな……。"
10052015-8 = "心配ないよ。先生がいるんだから。"
10052015-9 = "きっと、大丈夫。"
