[translation]
10052095-2 = "コクマー、沈黙を確認。"
10052095-3 = "それにしても……はぁ……。#nここ暑いね……あのときより、もっと……。"
10052095-4 = "[s1] \"今は戦闘服のままで我慢してほしいかな。\"\n[s2] \"エイミが危険にさらされるのは見たくないから。\""
10052095-7 = "……あの、エイミ？#n悪いのですが……お願いがありまして……。"
10052095-8 = "うん？いいよ。ここに長居するって話以外なら。"
10052095-9 = "あ、えっと……ここの気温や気圧は他のエリアと大きく異なっていて――"
10052095-10 = "コアの情報抽出に、もう少し時間がかかりそうです……。"
10052095-16 = "[ns] \"エイミ！？\""
10052095-17 = "すみません……。"
10052095-18 = "ううん……ケイは悪くないよ……。"
10052095-19 = "悪いのは……この世界、なんだから……。"
10052095-20 = "まるで、あの子たちみたいなことを言いますね……。"
