[translation]
10051050-1 = "第5話;花開く時"
10051050-2 = "ファッションショー会場裏庭の森"
10051050-3 = "今回のショーは、もう終わりだ……！"
10051050-4 = "衣装は取り返せてるんだよね……？"
10051050-5 = "そうだね。だけど――"
10051050-7 = "ぜんっぜん、ありがたくなんかない！！"
10051050-8 = "ひ、ひえっ！？"
10051050-9 = "これ！どうするの！？#n衣装があっても、それを着るモデルが倒れてたら意味ないだろう！？"
10051050-10 = "君たちの戦闘のせいだ！！"
10051050-15 = "いやいや、それを私たちのせいにされても……。"
10051050-16 = "も、もしかして……倒れているこの方が……。"
10051050-17 = "今日のファッションショーに出演予定だったモデルさんですか！？"
10051050-18 = "そもそも！なんでこんなとこで倒れてるのさ！"
10051050-19 = "[s] \"戦闘に巻き込まれたんじゃないかな……。\""
10051050-20 = "戦ったのは私たちとヘルメット団だけのはずだよ？#nこの人、どっから出てきたの……？"
10051050-21 = "部長！この方、衣装が入っているカバンに手を伸ばしたまま倒れています！"
10051050-22 = "つまり、倒れる直前までカバンを目指していたということ……！"
10051050-23 = "カバンを取り返そうと戦闘に飛び込んできて、流れ弾に当たったに違いありません！"
10051050-24 = "なるほど、それなら説明がつくね……！"
10051050-25 = "す、すごく論理的な推論です……！"
10051050-26 = "これぞ忍者らしい推理ってやつだよ！"
10051050-27 = "今は推理ごっこをしてる場合じゃない！それに、「忍者らしい」って何！？"
10051050-28 = "とにかく……ほら！起きて！君がこのショーの主役なんだから！#n起きなさい！お願いだから起きてぇぇぇ！！"
10051050-29 = "あの……すみませんが、そこをどいてください。#nその状態じゃあ、いくら揺さぶっても起きませんよ。"
10051050-30 = "何だって！？"
10051050-31 = "脳震盪です。#n見てください。顎と後頭部に、直撃した痕があります。"
10051050-32 = "無理に意識を戻しても、数時間は身体をまともに動かせないでしょう。"
10051050-33 = "そ、そんな……！"
10051050-37 = "それなら、自然に目覚めたとしても……ランウェイは無理ってこと？"
10051050-38 = "この状態の人をランウェイに立たせるつもりですか……？"
10051050-39 = "いいから、できるの？できないの？"
10051050-40 = "……かなりふらつくと思います。"
10051050-41 = "何より、今は安静にさせなければ。"
10051050-42 = "はぁ、そうか……。"
10051050-43 = "分かった。専門家がそう言うなら、それが正しいのだろうね……。"
10051050-44 = "それでは、搬送させていただきます。"
10051050-48 = "でも……私のショーはどうすれば……ああ……。"
10051050-49 = "……仕方ない、他に手が無いのだから。"
10051050-50 = "……君たち。"
10051050-51 = "はい！？"
10051050-52 = "……まあ、努力は認めよう。"
10051050-53 = "……もう少し射撃の腕が良ければ、言うこと無しだったんだけど。"
10051050-54 = "私は先に戻らせてもらうよ。"
10051050-59 = "ファッションショー控室"
10051050-60 = "はぁ……。"
10051050-61 = "はあああぁぁぁぁ……。"
10051050-62 = "どうする……？差し迫ったショーをどうすればいいのか……。"
10051050-63 = "あの、シャインキャット様……急いで、モデルの代役を手配するのはどうでしょうか？"
10051050-64 = "着眼点は悪くない。"
10051050-65 = "だが……ほら、この服、分かるだろうか？これを見て何を感じる？"
10051050-66 = "え、ええと……とても、美しいです……？"
10051050-67 = "違う、サイズを見なさい、サイズを！この大きくて美しいサイズをよく見て！"
10051050-68 = "私は身長180cm級のモデルを想定して、この服をデザインしたんだ。"
10051050-69 = "で？控室に、そんなモデルがいるかい？"
10051050-70 = "い、いませんっ！"
10051050-71 = "そう。180cm超えなんてそうそういない！そんな都合よく――"
10051050-75 = "……待って。1人……いたな。"
10051050-76 = "えっ、誰のことですか？"
10051050-77 = "[ruby=おおの]大野[/ruby]ツクヨ。"
10051050-78 = "誰です？それ。"
10051050-79 = "はぁ！？正面入口にいた警備員だよ！それに、さっきの現場にもいただろう！？"
10051050-80 = "君、ショーのスタッフのくせに、警備員の名前も覚えてないわけか！？"
10051050-81 = "普通は一人ひとりなんて覚えませんよ……！"
10051050-82 = "いいから！あの子を連れてきなさい。今すぐ！！"
10051050-83 = "えっ、本当に……？警備員をモデルにするんですか！？"
10051050-84 = "一目見たときから、私は見抜いていた。あの子には才能がある。#n身長だけじゃない。あの雰囲気、体のバランス……完璧だった。"
10051050-85 = "この服にふさわしいのは、彼女しかいない。"
10051050-86 = "じ、冗談じゃないんですよね！？"
10051050-91 = "冗談を言ってるように見えるのか！？"
10051050-92 = "い、いえ！すぐ連れてきます！！"
10051050-97 = "ファッションショー会場裏庭の森"
10051050-98 = "え、ええっ！？わ、私がモデル……！？"
10051050-99 = "はい、時間がないんです！"
10051050-100 = "で、でも……モデルの勉強なんてしたこと、ないんですけど……！？#n私、なんかが……舞台に立てるはず、ない……です。"
10051050-101 = "私もそう思いますよ！？#nでも、シャインキャット様が「絶対連れてこい！」って……！"
10051050-102 = "ひ、ひえぇ……。"
10051050-103 = "お願いです、人助けだと思って……！#nシャインキャット様はちゃんと報酬もくれますから……！"
10051050-105 = "う、うぅ……で、でも……！"
10051050-106 = "控室の場所はご存知ですよね？#n私はあとで合流しますので、先に行っててください！"
10051050-111 = "ぶ、部長……どうしたらいいんでしょう……！"
10051050-112 = "こんな大きなショーで、私がモデルだなんて……。"
10051050-113 = "みんなきっと、私みたいに背ばっかり大きい子なんて、好きじゃない……。"
10051050-114 = "きっと、たくさんの人がブーイングして……。"
10051050-115 = "それで私は絶望して、部屋にこもって……#n「柴犬ワン蔵」監督の映画を見続けながら……ゆっくりと枯れていくんです……。"
10051050-116 = "いや、そんなことはないよ。"
10051050-120 = "ツクヨ。初めて会ったとき、私がなんて言ったか覚えてる？"
10051050-121 = "……体がすごく大きい、って。"
10051050-122 = "そ、そういうことも言ったけど！"
10051050-123 = "だからこそ、忍者として最強だって言ったじゃん！"
10051050-124 = "……！"
10051050-125 = "最強の忍者にとって、こんな困難なんて何でもないよ！"
10051050-126 = "部長……！"
10051050-127 = "それに、業界トップのデザイナーからのご指名だよ？"
10051050-128 = "胸を張っていこう！"
10051050-129 = "もしも上手くいかないことがあったとしても――"
10051050-130 = "こういうのは全部、主催者側の責任！これは先生殿の名言集にも書いてあるんだから！"
10051050-131 = "[s1] \"そんなこと言ったっけ！？\"\n[s2] \"私の名言集なんて存在してるの！？\""
10051050-134 = "ふぅ……。"
10051050-138 = "……分かりました。私、やってみます！"
10051050-140 = "ファッションショー控室"
10051050-142 = "入りなさい。"
10051050-148 = "来たね。覚悟はできたのかい？"
10051050-149 = "……はい！"
10051050-150 = "君には確かな才能がある。#nだけど、それだけで生きていけるほど、この道は甘くない。"
10051050-151 = "だからこそ、この道を最後まで歩ききることができたなら、栄光は君のものだ。#nこの私が保証しよう。"
10051050-152 = "そ、そんなの……望んでないですけど……。"
10051050-153 = "それより、今の格好……忍者だって言ってたかな。"
10051050-154 = "よく知らないけど、もうお別れだ。"
10051050-155 = "今日、君が輝かせるべき衣装は、私の作品なんだから。"
10051050-156 = "ほら、早く着替えてきなさい。更衣室はあっちだよ。"
10051050-157 = "あの……。"
10051050-158 = "なに？時間がないから、手短にね。"
10051050-159 = "そ……その、モデルをやるのは……今日だけ、です……。"
10051050-160 = "この任務が終わったら、私は忍術研究部に戻りますから……！"
10051050-161 = "……着替えてきます。"
10051050-166 = "ふふ……。"
10051050-168 = "……世間が、それを許すかな？"
10051050-170 = "ファッションショーメインステージ"
10051050-172 = "ツクヨ……上手くやってるかな……。"
10051050-173 = "どんな姿でステージに現れるのでしょうか？"
10051050-174 = "イズナ、ワクワクしてきました！"
10051050-175 = "あ、そろそろ始まるみたい！"
10051050-191 = "……部長。"
10051050-192 = "……うん？"
10051050-193 = "私たち……今、何を見たんでしょう……？"
10051050-194 = "うーん……。"
10051050-196 = "……芸術？"
