[translation]
10052075-9 = "もーっ！キリがない！"
10052075-13 = "ミドリ！まだ弾ある？"
10052075-28 = "もうすぐ尽きそうだけど――"
10052075-29 = "これ！最後の弾倉だから……大事に使ってよ？"
10052075-31 = "ミドリのは！？"
10052075-32 = "私は……まだ半分残ってるから！"
10052075-33 = "大事にって言われても、敵の数が……。"
10052075-34 = "じ、時間稼ぎだけで――"
10052075-38 = "[log]光よ――！！！[/log]"
10052075-44 = "アリス！！！"
10052075-45 = "モモイ、ミドリ！無事ですか？アリス、間に合いましたか？"
10052075-46 = "うん！完璧！"
10052075-47 = "ふふっ、先生。私の車椅子の運転はいかがでしたか？"
10052075-48 = "ヒマリ先輩、それはバイクでは……。"
10052075-49 = "車椅子です。"
10052075-50 = "はい……。"
10052075-54 = "って、先生、大丈夫ですか！？顔色が……！"
10052075-55 = "[s] \"だい、じょう……ぶ……。\""
10052075-56 = "次からは酔い止め薬を持っておきますね……。"
