[translation]
10050090-1 = "第9話;リバー・ランズ・スルー・イット"
10050090-2 = "……それで、チェリノ会長。こちらが私たちからの提案、トリニティとレッドウィンター間の文化交流協定の詳細です。"
10050090-3 = "本協定はシャーレの先生が保証人となり、図書委員会の判断の末進められます。そして私たちティーパーティーもこれに異論はありません。"
10050090-4 = "ただし今回のように、協議が進んでいない状態で、本のような媒体を流通させるのはご遠慮いただきたいです。"
10050090-5 = "問題ありませんね？ヤクモさんの言う通り、文化は巡るべきですから。"
10050090-6 = "う、うむむ……。"
10050090-7 = "めんどくさい……というか、出版部が勝手にしたことだろう。"
10050090-8 = "待て、カムラッドがいると言ったな？そうだ……それだ！"
10050090-9 = "理解した。そして今回の件に限り、シャーレはレッドウィンターに代わって発言するとする。"
10050090-10 = "[s] \"うん？私？\""
10050090-11 = "えっ……？ということは、シャーレの先生に……？"
10050090-12 = "そうだ。つまりシャーレはレッドウィンターの代理人だ、今回だけな！レッドウィンターはシャーレに全決定を委任する！"
10050090-13 = "何よりおいらは、今から大事な用事を済ませなくてはならないのでな！"
10050090-14 = "だ、大事な用事とは……。"
10050090-16 = "それは……昼寝だ！"
10050090-17 = "昼寝……？何かの隠語でしょうか！？"
10050090-18 = "[s] （たぶん違うと思う……）"
10050090-19 = "そ、それにシャーレを文化協定の代理人にするって……。"
10050090-23 = "（そういうことですか！？万一協定が決裂した場合、レッドウィンターの代理人であるシャーレに一定の責任が問われることになる……）"
10050090-24 = "（そして協定に応じたトリニティにも責任の一端が……）"
10050090-25 = "（その場合先生は……仕事という面でも、感情の面でも、トリニティに反感を抱くかもしれない……）"
10050090-26 = "（つまり――これはトリニティへの警告）"
10050090-27 = "（同時に、レッドウィンターはあらゆる責任から逃れられる――なるほど、これがレッドウィンターの外交力！？）"
10050090-28 = "ち、チェリノ会長、お待ちください！"
10050090-33 = "[ns] \"ナギサ、何かあった？\""
10050090-34 = "い、いえ！なんでもありません、先生！私たちがうまくやればいいのです、ええ！"
10050090-35 = "終わったー？ナギちゃん。暇だったんだからーもー。"
10050090-36 = "ミカ。先生もいるのだから、場を弁えたまえ。"
10050090-37 = "そ、そうだった……ごめんね先生。"
10050090-38 = "うん？「そのままのミカでいい」……？先生ありがとう、好き！"
10050090-39 = "ご挨拶申し上げます、ティーパーティーの皆様。#nそして、寛容な対処に厚く御礼申し上げます。"
10050090-40 = "こんにちは、出版部の皆さん。こうしてお会いできて嬉しいです。"
10050090-41 = "私たちトリニティは、本件をきっかけに、これからもレッドウィンターとより良い関係を築いていきたいと思っております。"
10050090-42 = "また良い本がありましたら、みなさんに是非おすすめしていただければと。"
10050090-43 = "はい、そのように。このような場を設けてくださり光栄ですわ。"
10050090-45 = "ねえねえ、ヤクモちゃんだったよね？初めまして！私はティーパーティーのミカ！"
10050090-46 = "その……よかったら、ちょっと二人だけで、話せないかな？"
10050090-47 = "ど、どうも……[ruby=あらまき]荒槇[/ruby]ヤクモです。"
10050090-48 = "（この人がティーパーティーの一人……）"
10050090-49 = "（つまり私は、チェリノ会長を目の前にしている、と）"
10050090-50 = "（いっそチェリノ会長ならば、対処法は100種類くらいあるのですが……）"
10050090-51 = "今回ヤクモちゃんが持ってきた本、さっそく読んでみたよ！"
10050090-52 = "あっ、はい……。"
10050090-53 = "あの、そのさ……これはあくまで、私の考えなんだけどね。"
10050090-54 = "主人公ってなんというか、先生とちょっと似てる部分があると思うの。だから、良かったと思う。"
10050090-55 = "それでその……これは私の個人的なお願い？というか願望？みたいなものなんだけど……。"
10050090-56 = "ヒロインの性格とか、見た目を変えたらもっと良くなるんじゃないかな？って！"
10050090-57 = "……？"
10050090-58 = "ほう……ほうほう、へえ……？ムッフフフフ。"
10050090-59 = "すばらしいご提案ありがとうございます。ミカ様。"
10050090-60 = "そのお話、もう少々詳しくお聞きしたいのですが……どのような変更をご希望で？"
10050090-61 = "うんうん！たとえばね……髪色をもうちょっとピンクっぽくして、くせっ毛にしたらもっとかわいいと思うの！"
10050090-62 = "ちょっと落ち着きはないけど、茶目っ気があって、やるときはやる！そんな子とかどう？"
10050090-63 = "普段は盛り上げ役で、髪は片側をだんごにしてもいいけど、まあそれは別にどっちでも……。"
10050090-64 = "一番好きなのはジャンボパフェ！その次に好きなのは、サミュエラのザ・ビヨンド！"
10050090-65 = "あ、ロールケーキはもういいかな……。"
10050090-66 = "とにかく！そういうのはどうかなーって？"
10050090-67 = "ええ、ええ。理解しましたとも。"
10050090-68 = "ただ、ミカ様のご要望をまとめますと……ほぼ一から作り直しになってしまいますねぇ。"
10050090-69 = "そ、そうなんだ……？"
10050090-70 = "そしておそらく、ミカ様ただ一人のための、1冊になることでしょう。"
10050090-71 = "えっ……？わ、私だけのため？"
10050090-72 = "いいよ！そういうの大好き！"
10050090-73 = "そうですか、私もそちらの方がよりミカ様にピッタリかと。#nただ……一つ問題がありまして。"
10050090-74 = "な、なに……？"
10050090-75 = "出版というものは基本的に、分母に左右される業界でして。"
10050090-76 = "少数のための作品は、あまり売り上げが立たないのです。"
10050090-77 = "特にこのような、一人のために本を作るのは、その希少性から値段の算定が難しく。"
10050090-78 = "結論から申しますと……割高になるということです。"
10050090-79 = "ん……？いくらくらい？"
10050090-83 = "このくらいならどうかな？"
10050090-84 = "！？！？"
10050090-85 = "いっ、いやっ、その半分でも十分ですが……！？"
10050090-86 = "なんだ、高いって言うから緊張した～#nじゃあさ――"
10050090-87 = "ミカさん？"
10050090-92 = "なっ、なに？ナギちゃん。"
10050090-93 = "最後まで言わないと……分かりませんか？"
10050090-94 = "う、うう……わ、分かったってばもう！ナギちゃんのケチー！"
10050090-96 = "出版部のみなさん、本当にお疲れ様でした。"
10050090-97 = "いえ、図書委員会と正義実現委員会の方々に迷惑をかけてしまいましたわ。申し訳ありません。"
10050090-99 = "そうでもないですよ。出版部さんのおかげで、私たち正義実現委員会が図書館に行く機会が増えました。"
10050090-100 = "みんな、本そのものに興味が湧いたみたいなんです。"
10050090-101 = "私も、正義のこと以外にも興味を持つようになりましたし。"
10050090-102 = "それはよかったです。でも、ちゃんと返却はしてくださいね？"
10050090-103 = "は、はい、気をつけます……それでなんですが、タカネさん。"
10050090-104 = "はい。"
10050090-105 = "今回の本のお話って……まだ完結していないですよね？"
10050090-106 = "ええ、そうですが……。"
10050090-107 = "その……もし次が出たら、ご連絡を頂けないかと……。"
10050090-108 = "ふふっ……お気に召されたようで。"
10050090-109 = "はい、すごく。"
10050090-110 = "分かりました。物語が好きな方は、いつだって歓迎ですわ。"
10050090-111 = "あと……これはトリニティのみなさんからの要望ですが……私にはよく分からない話でして。"
10050090-112 = "「いつか必ず、雪の姫君の評論集を発売してほしい」とのことでした。"
10050090-113 = "……。"
10050090-114 = "ま……前向きに、検討いたしますわ。"
10050090-115 = "ありがとうございます、タカネさん。これからもどうぞよろしくお願いします。"
10050090-121 = "部長～～～っ！！！"
10050090-122 = "おや、どうかしましたかタカネ。"
10050090-123 = "聞いていたでしょう！？#nこれどうするおつもりですか！"
10050090-124 = "あっ……ええとぉ……。"
10050090-126 = "これも全部マーケティングですから！"
10050090-127 = "言い訳になりませんよ！？"
10050090-139 = "[ns] \"満足した？ヤクモ。\""
10050090-140 = "そうですねぇ、ええ。かなり。"
10050090-141 = "[s1] \"それならいいんだけど……。\"\n[s2] \"これからも、ヤクモのこと見てるからね？\""
10050090-144 = "おや？それはどうして……？"
10050090-145 = "いろんなことをよく知っているから……ですか？"
10050090-146 = "契約の重さが分かっていて、仕事のためにへりくだることができる生徒……？"
10050090-147 = "[s3] \"そう。すごいスキルだし、うまく生かせばカッコイイけど。\"\n[s4] \"行き過ぎてしまった時に、私が責任をとれなくなるかもしれない。\""
10050090-150 = "……。"
10050090-151 = "はい、分かってますよ。"
10050090-152 = "あまり認めたくありませんが、私ってひねくれているみたいですし。"
10050090-153 = "あと、これからも私のことを見るってことは……。"
10050090-154 = "興味を示し続けてくださるっていう意味でもありますからね。#n悪いこととは限りませんし？"
10050090-155 = "[s] \"またそうやって……。\""
10050090-156 = "そうですわ部長！そういう意味はないかと。#n今回のことだってホントにもう……！はぁ……。"
10050090-157 = "先生、本当にお疲れ様でした。心から感謝申し上げますわ。"
10050090-158 = "[s] \"タカネがいてくれたおかげだよ……。\""
10050090-159 = "そ、そう思ってくださるのは、嬉しいですが……。"
10050090-160 = "はぁ……こうなると分かっていれば、最初から先生に助けを求めていたのに……。"
10050090-161 = "そういえば部長。なんでそうしなかったのですか？"
10050090-162 = "ああ、まあ……それも候補にはあったのですが……。"
10050090-163 = "「が」？"
10050090-168 = "……怒られそうだし？"
10050090-169 = "部長ーっ！！？"
10050090-170 = "[s] \"ヤクモーっ！！\""
10050090-178 = "[ns] \"ふぅ……。\""
10050090-180 = "[ns] \"今日もよく働いたー！\""
10050090-182 = "冬空の文芸復興 ～健全なる文化の交流について～"
