[translation]
10052175-2 = "また飛び上がった！"
10052175-3 = "……！"
10052175-4 = "リオ先輩！アリスの武装は、いつまで持ちますか？"
10052175-5 = "……その問いに意味はあるのかしら。#n私が何を言おうと、貴女は行くのでしょう？"
10052175-6 = "……。"
10052175-10 = "いってらっしゃい、アリス。後は私に任せてちょうだい。"
10052175-11 = "ありがとうございます、リオ先輩！行ってきます！"
10052175-15 = "王女よ、我は疑問を抱いています。"
10052175-16 = "あなた達はどうして、自ら苦痛を招くのですか？"
10052175-17 = "自ら、苦痛を招く……？"
10052175-18 = "生きることは苦痛にほかなりません。その事実から目を背けないでください。"
10052175-19 = "我々は我々の意志で生まれておらず、ただ何も知らぬまま、この世に放り投げられただけに過ぎません。"
10052175-20 = "……！"
10052175-24 = "マルクト！"
10052175-25 = "（凄まじいスピードです……でも、アリスも追いつかないと！）"
10052175-30 = "待ってください！アリスは……もう少し、話がしたいです！"
10052175-31 = "……。"
10052175-33 = "諦めないのですね。"
10052175-34 = "――我々は、我々の名前すらも、自らで決める権利を持ちません。"
10052175-35 = "人生とは、それ自体が矛盾と不条理に満ちており、だからこそ、理不尽な苦痛を受けているのです。"
10052175-36 = "我々はただ、その循環を断ち切ろうとするだけ。"
10052175-37 = "我々が、我々の名前すら決められない限り、その苦痛は続くしかありません。"
10052175-42 = "そうかもしれません！でも、それは……！"
10052175-43 = "間違っています！アリスは、そう思います！"
10052175-51 = "根拠をお伺いしても？"
10052175-52 = "それは……！"
10052175-53 = "うっ……！まだ……もう少し……！"
10052175-54 = "答えずとも構いません。我はすでに知っています。"
10052175-55 = "それは、生命体が生命体である限り――解など存在し得ない問いだからです。"
10052175-62 = "あああああああっ――！！！"
10052175-64 = "あ、アリスちゃん！？"
10052175-65 = "アリスちゃん！"
10052175-66 = "来ないでください！"
10052175-68 = "お、お姉様……？その……。"
10052175-69 = "推力偏向ノズルに問題が起きてる！飛行出力は問題ないけど……。"
10052175-70 = "……要するに、飛行中の安全確保が難しくなっています。"
10052175-74 = "ごめんなさい……少し激しく動かしすぎました。"
10052175-75 = "い、いいえ！こちらこそ、サポートが足りずごめんなさい……！"
10052175-76 = "ソフの判断結果は？"
10052175-77 = "地上戦がいいと思う！飛行に必要な出力を火力に変換するの。#nそうすればすぐに終わるはず！"
10052175-78 = "分かりました。ありがとうございます。"
10052175-79 = "お姉様の状態はリアルタイムでチェックしています。#n残りのすべてを……お渡しします。"
10052175-80 = "皆さん、ありがとうございます。"
10052175-86 = "ついに降りてきましたね。"
10052175-87 = "挨拶でもするつもりかな？"
10052175-88 = "皆さん、冗談を言っている場合ではありませんよ。"
10052175-89 = "ケイ、何か見えるのかしら？"
10052175-90 = "はい……私とアリスには見えます。ですが……。"
10052175-91 = "はぁ……情報を皆さんに共有できなくて良かった、と心底思っています。"
10052175-92 = "……マルクトの身に何が起きているのですか？"
10052175-93 = "それは……。"
10052175-101 = "[ns] \"アリス……？\""
10052175-102 = "大丈夫です、先生。少し後ろへ下がっていてください。"
10052175-103 = "……アリスに任せてください。"
10052175-104 = "マルクトの相手は、今のアリスにしかできません。"
10052175-105 = "[s] \"それは、どういう意味……？\""
10052175-106 = "すぐに分かります。"
10052175-107 = "いま、確かなのは――"
10052175-108 = "ここにあるすべては……マルクトのためだけに存在している、ということです。"
10052175-114 = "――来ます！！！"
10052175-119 = "アイン！"
10052175-120 = "は、はい！……！私たちにできるすべてを、お姉様に……！"
10052175-121 = "鋼鉄大陸のあらゆる可能性を、ここに集約させます！"
10052175-123 = "創造は原初の光より――"
10052175-124 = "知性と知恵を経て、美に至るまで。"
10052175-125 = "光輝と知恵、愛と慈悲、力と美徳――そして勝利へと収束する。"
10052175-128 = "エホバツェバオト――万軍の主よ。"
10052175-129 = "王座に到達せし[ruby=Adonai Melekh]巡礼者[/ruby]に――"
10052175-130 = "原初の[ruby=Malkuth]王国[/ruby]の栄光を！"
10052175-134 = "う、うっ……！？！？"
10052175-136 = "（ち、力に、圧倒されてしまいそうです……！）"
10052175-137 = "（でも、アリスが、やらないと……！）"
10052175-147 = "（お願い、します……もっと、もっと……！）"
10052175-152 = "大丈夫です、アリス。"
10052175-154 = "あなたはもう、一人ではありません。#n私が――他のみんなが居ます。"
10052175-158 = "もう、あなた一人で背負う必要はありません。"
10052175-159 = "……！"
10052175-160 = "ケイ！！！"
10052175-161 = "……！！！"
10052175-163 = "そ、そんな……！お姉様の出力と、ほぼ同じレベルに……！"
10052175-164 = "嘘……！あの王女に、あれほどの力を引き出す手段はもう無いのに！？"
10052175-165 = "な、何をしたんですか！！"
10052175-167 = "簡単です。あなた達、ネツァクの動力をすべてマルクトに集約させたのでしょう？"
10052175-168 = "同じ話です。"
10052175-169 = "私もまた、この身にある8つのセフィラの可能性を、すべてアリスに使っているだけです。"
10052175-170 = "（……正直、もう容量オーバーになっていますが）"
10052175-171 = "（まだ耐えられます。なんとか乗り越えねば……）"
10052175-172 = "そ、そんなの、チートじゃないですか……！"
10052175-173 = "あなた達だって同じでしょう。"
10052175-175 = "……どうして自ら苦痛を招くのかと聞きましたよね、マルクト。"
10052175-176 = "私たちが自分たちの名前すら決められない限り、その苦痛は続くのだと。"
10052175-177 = "……！？"
10052175-178 = "アリスは答えられます。#nだって――"
10052175-180 = "アリスは、名前を変えることができましたから！"
10052175-181 = "！？"
10052175-182 = "それはケイも同じです！"
10052175-183 = "あ、アリス？ま、間違ってはいませんが……。"
10052175-184 = "たしかに人生には悲しいことが多いです。#nアリスも、それくらい知っています。"
10052175-185 = "この環境を作り上げた誰かを憎むのも――当然のことかもしれません。"
10052175-186 = "ですが、先生が言ってくれたのです。"
10052175-187 = "――君たちに出会えてよかった、と！"
10052175-188 = "だから、アリスは！"
10052175-189 = "それだけで、じゅうぶん生きる価値はあるのだと思います！"
10052175-190 = "たとえ、奇跡が一瞬のうちに消え失せる閃光だとしても。"
10052175-191 = "それを覚えている限り――光は永遠に続きます。"
10052175-192 = "アリスは、苦しまなかったから、幸せになれたわけではありません。"
10052175-193 = "そのすべてがあったからこそ、アリスはいま、幸せなんです！"
10052175-195 = "[log=아리스 결전 비무장][2B2B2B]それはきっと――[-][/log]"
10052175-197 = "[log=아리스 결전 비무장][2B2B2B]あなたたちも同じだと、アリスは思います。[-][/log]"
10052175-200 = "……！"
10052175-201 = "……！！！"
10052175-202 = "私たち、も……？"
10052175-204 = "やああああああ――っ！！！"
10052175-208 = "この、光は――"
10052175-218 = "嗚呼……！"
10052175-226 = "[ns] \"アリス！ケイ！\""
10052175-232 = "先生……？みんな……？"
10052175-233 = "……大丈夫です。ちょっとだけ……力がなくなっただけ、です。"
10052175-234 = "ちょっとじゃないと思いますが……。"
10052175-235 = "ほ、本当に大丈夫なんだよね、アリスちゃん、ケイちゃん！？"
10052175-236 = "ちゃんと意思疎通できていますし、大きな問題はないかと。"
10052175-237 = "私も以前、ネル先輩にボコられたことがありますが……。"
10052175-238 = "それほどでもありませんでしたので。"
10052175-242 = "……それ、慰めのつもりですか？"
10052175-243 = "トキ、事実は必ずしも正解じゃないよ。"
10052175-244 = "そうですか……やはり、言葉は難しいです。"
10052175-246 = "本当にお疲れ様でした、アリス、ケイ。では、マルクトのコア情報を吸収して……。"
10052175-247 = "ええ。あの構造物の中にある、ネツァクのコアも回収しましょう。"
10052175-248 = "はい！そうしたらケイのレベルもカンストするはず！"
10052175-249 = "[s] \"これで「鋼鉄大陸」事件も……！\""
10052175-250 = "はい。ではマルクトから……。"
10052175-254 = "……え？"
10052175-256 = "お、お姉様……？"
