[translation]
10052160-1 = "マルクト：世界の果てに到達せし王国の巡礼者 "
10052160-10 = "あるいは、そもそも後先考えずにやっているのか。#nだから、話せることもないのかと。"
10052160-102 = "これが最終ボス戦ってことだよね？"
10052160-103 = "はい。適切な比喩だと思います。「たまにはいいことを言うモモイ」。"
10052160-104 = "えっと……私のあだ名っていくつあるの？"
10052160-105 = "本当に知りたいのですか？"
10052160-106 = "う、ううん……大丈夫。"
10052160-107 = "ちゃんと集中してくださいよ、もう！"
10052160-11 = "いくらなんでも、軽々しくこんな事態を引き起こしたわけではないでしょう……。"
10052160-15 = "まあ、魔王城の四天王って、本当の事情を知っていないか、#n訳の分からないことばっか言うもんだし！"
10052160-16 = "別に聞かなくてもよかったんじゃない？#n時間の節約ってことで！"
10052160-17 = "どうしても言えない事情があったらどうするの……。"
10052160-18 = "い、いくら事情があっても、流石にこれはダメじゃ、ないかな……。"
10052160-2 = "[ns] \"あの子たちは！？\""
10052160-20 = "こ、ここなら大丈夫だと思います……！#nあ、あの人たちに見つかることはないはず……。"
10052160-22 = "うぅ……疲れるよね、これ。"
10052160-23 = "ここまでとは……。"
10052160-27 = "アイン、ソフ、オウル、大丈夫ですか？"
10052160-28 = "は、はい……！まだ――"
10052160-3 = "……身を隠しているようね。"
10052160-34 = "問題ないよ！#nえっと……アインは少し疲れてるみたいだけど、お姉様は心配しないで。"
10052160-4 = "どうしてこのような事をしたのか……この期に及んで、まだ教えてくれる気はないようですね。"
10052160-40 = "やれやれ。アインもソフも根性が足りないんですから。#nまだ――！"
10052160-46 = "……。"
10052160-47 = "アイン、ソフ、オウル。"
10052160-48 = "鋼鉄大陸は、あなた達の意志でしたよね？"
10052160-49 = "はい……それが、どうかしましたか？"
10052160-5 = "まだ親愛度が足りていないのでしょうか……。"
10052160-50 = "我は――アイン、ソフ、オウルが自らの意志で、この鋼鉄大陸をつくり上げたということを聞き、とても嬉しかったのです。"
10052160-51 = "ですが、どうして鋼鉄大陸をつくろうとしたのか。#nそこから何を得ようとしたのか――我はまだ知らないままです。"
10052160-52 = "鋼鉄大陸を拡張させ、キヴォトスを覆いつくそうとする計画。#n我はその計画に、確固たる理由はないとお見受けしますが。"
10052160-53 = "そ、それは……。"
10052160-54 = "大丈夫です。あなた達を[ruby=とが]咎[/ruby]めるつもりで言ったわけではありません。"
10052160-55 = "ただ何のために、鋼鉄大陸を拡張させようとしていたのか。"
10052160-56 = "そしてその理由を、我にさえ話してくれないことについて。"
10052160-57 = "純粋に、疑問に思うだけです。"
10052160-58 = "鋼鉄大陸にこだわらなければ、これらも起こらなかったと思いますので。"
10052160-59 = "……。"
10052160-6 = "……そう簡単な話ではないですよ、アリス。"
10052160-60 = "ごめんなさい、お姉様。"
10052160-61 = "言えない理由が、あるんです。"
10052160-62 = "音として発音してはならないので……。"
10052160-63 = "でも信じてください。すべてはお姉様のためなんです……。"
10052160-67 = "いえ、お姉様と私たちのため、ですから。"
10052160-68 = "アイン、ソフ、オウルが、我のために？"
10052160-69 = "一体、どうして。"
10052160-7 = "ですが不可解ではあります。"
10052160-70 = "ねえ、お姉様。"
10052160-71 = "はい、ソフ。"
10052160-75 = "お姉様は、生きたい？"
10052160-76 = "はい？"
10052160-77 = "……。"
10052160-78 = "ごめんなさい、質問の意図が理解できません……。"
10052160-79 = "意識を得ている以上、それを継続したいと考えるのは当然のこと。#nそういう意味で……はい、我は生きたいです。"
10052160-8 = "あれほど私たちのためだと言っておきながら、窮地に追い込まれてなお何一つ事情を話してくれないとは。"
10052160-80 = "ですが、アイン、ソフ、オウル。"
10052160-81 = "もう、知っているのでしょう？"
10052160-82 = "うん。もちろんだよ。他の誰よりもずっと。"
10052160-83 = "それでも私たちは……生きたい。"
10052160-84 = "お姉様と一緒に、いつまでも……生きていきたい。"
10052160-85 = "それは……。"
10052160-86 = "……！"
10052160-87 = "なるほど。"
10052160-88 = "まだ完璧に理解することはできませんが、あなた達がそう願うのであれば。"
10052160-89 = "う、うぅ……。"
10052160-9 = "そうだよね。#n話をするだけでも時間稼ぎになるはずなのに。非効率的だよ。"
10052160-90 = "……。"
10052160-91 = "ごめんなさい、お姉様。もう私たちは……。"
10052160-92 = "ええ、知っています。"
10052160-93 = "大丈夫。#nこれからは、我を信じてください。"
10052160-94 = "あの方のために、そして大切な妹たちのために。"
10052160-97 = "皆さん、あちらです！"
