[translation]
10050040-1 = "第4話;Covert Ops"
10050040-10 = "おや……？そうですね。制服も黒いですし、ちょっと雰囲気も違うような。"
10050040-100 = "しかし、これはチャンスともいえます。"
10050040-101 = "弾圧される文化ほどお金になるのです！文化においての弾圧は、一種の勲章といえるでしょう！"
10050040-102 = "何でもないシーンに検閲が入れば、検閲されたという事実が宣伝となり、数倍も売上が伸びたりするものです！"
10050040-103 = "勲章といえば……髭勲章を思い出しましたわ。"
10050040-104 = "そういう、形だけのものではなく……。"
10050040-105 = "ともかく、皆さんの言いたいことは分かりました。"
10050040-106 = "ええ、この場を設けてくださり感謝しておりますわ。"
10050040-107 = "それでは本日の……「即売会」を開始いたします！"
10050040-111 = "環境が整ったところで……。"
10050040-112 = "そろそろ次のステップに参りましょうか、タカネ。ムフフ。"
10050040-113 = "……あれ、本当にやらないとダメでしょうか？"
10050040-114 = "もちろん。これも全てマーケティングなのですよ。"
10050040-115 = "想像しただけで恥ずかしくて死にそうですわ……。"
10050040-116 = "こう思ってはいかがです？#nすべては文化活動の宣伝のため！ですよ！"
10050040-117 = "うぅ……わ、分かりました部長……。"
10050040-124 = "コハル！なんだか久しぶりだね。"
10050040-125 = "う、うん……そうだね……#nというか、なんかやけにみんないるけど、何かあったの？"
10050040-126 = "えっと、その……どうやら怪しい本が出回ってる、らしくて……。"
10050040-127 = "本の出どころや流通量、トリニティに与える影響を調べてほしいと言われてるの。"
10050040-128 = "表では図書委員会を手伝うという名目だけど……。"
10050040-129 = "なんでも、ティーパーティー直々の命令らしくて……。"
10050040-130 = "てぃ、ティーパーティー！？そんな規模の話！？"
10050040-131 = "といっても、私たちも詳しくは知らないんだ。"
10050040-132 = "なんか、その本の話私も聞いた気がする……。"
10050040-133 = "本当！？何か手がかりは……！"
10050040-134 = "い、いや本当に、一瞬だけというか……。"
10050040-135 = "そっか……何か分かったことがあったら、教えてね。"
10050040-136 = "これだけ調べて何も出てこないの、委員会に入って以来初めてで……。"
10050040-137 = "も、もちろんまだ1年生だから、経験は少ない方だと思うけど……。"
10050040-138 = "でもなんだか、組織規模で隠ぺいしているような気がして。"
10050040-139 = "う、うん、私も調べてみるね……手がかりはまだないんだ？"
10050040-140 = "一応、1巻のサンプルと、2巻のサンプルを何部か入手してるんだけど……。"
10050040-141 = "ど、どんなやつ！？み、見てみてもいい？"
10050040-142 = "まあ、コハルなら……他の人も知っているだろうし……。"
10050040-143 = "はい、これです。"
10050040-144 = "ありがとう。どれどれ……。"
10050040-148 = "ひゃあっ！？"
10050040-153 = "こ、コハル！？コハル！？！？"
10050040-155 = "こ、これは……その、本当に。私が見たいから見てるんじゃなくて。"
10050040-156 = "本当に純粋に、みんなを助けたいだけなんだけど！"
10050040-157 = "……他のサンプルはないの？"
10050040-158 = "それが、全然見つからなくて……。"
10050040-159 = "必要ならそれは持っていって大丈夫。まだあるし。"
10050040-160 = "あ、ありがとう……じゃあ、また何か出てきたら……私に見せてもらえる？"
10050040-161 = "わ、私も一応がんばって調べるから！"
10050040-162 = "うん。よろしくね。"
10050040-163 = "う、うん。がんばる……！"
10050040-167 = "……。"
10050040-172 = "ほ、本当に深い意味はないし……！#n私は正義実現委員会のエリート……になるんだから！"
10050040-173 = "そ、それより……どうしよう、これ。"
10050040-174 = "たしか、正義実現委員会と図書委員会が協力してるって言ってたから……。"
10050040-176 = "正義実現委員会・教室"
10050040-177 = "ふぅ……。"
10050040-178 = "[s] \"どうしたの？\""
10050040-179 = "先生。申し訳ありません、カッコ悪い姿を見せてしまいましたね。"
10050040-180 = "あまり手がかりをつかめていなくて……。"
10050040-181 = "少し気になるのは、生徒のみなさんが協力的じゃないこと、でしょうか。"
10050040-182 = "事情を聞いても「知らない」だとか、はぐらかすような言葉ばかりで。"
10050040-183 = "とうとうこんなことを思うようになりました……トリニティの純粋な仲間たちが――"
10050040-184 = "――あの本から発散される謎のオーラに惑わされてしまったのでは……？なんて。"
10050040-185 = "[s] \"それは考え過ぎな気が……。\""
10050040-186 = "そうですよね？内部からの情報ばかり聞いているからか、変な考え方になってしまったのかも。"
10050040-187 = "やっぱり体を動かした方がよさそうですね。見回りに行ってきます。"
10050040-19 = "それに……皆さん、彼女たちを避けているような……。"
10050040-191 = "こんにちは、先生。そちらの調子はどうですか？ってあれ？マシロさんは？"
10050040-192 = "あ……見回り、ですか？マシロさんはいつも真面目に頑張ってますね。"
10050040-193 = "あともう少し遅ければよかったのに……続きの本のサンプルを手に入れたんです。"
10050040-194 = "[s] \"え、本当？\""
10050040-195 = "はい。ご覧になってみますか？"
10050040-20 = "この例えが正しいのかは分かりませんが……事務局が来た時の我々を見ているようです。"
10050040-201 = "[ns] \"……あれ？\""
10050040-203 = "[ns1] （どこかで見たことあるような……？）\n[ns2] （この展開とか、登場人物とか……）"
10050040-206 = "どうかされましたか、先生？"
10050040-207 = "何でもない、ですか？"
10050040-208 = "……。"
10050040-209 = "分かりました。ならいいのですが……。"
10050040-21 = "まあトリニティ側のことなんてよく分かりませんが、我々は自分たちの仕事をしましょう。"
10050040-22 = "今日もじゃんじゃん稼ぎますよぉ～"
10050040-28 = "お二人とも、こちらにいたんですね！"
10050040-3 = "では、今日も張り切っていきますかっ！"
10050040-35 = "あら、どうかされましたか……？"
10050040-36 = "しーっ！#n声を小さくして、私についてきてください。"
10050040-37 = "んんっ？一体何でしょう……？"
10050040-42 = "どこかの体育館"
10050040-43 = "はぁ……はぁ……何をそんなに急いで……。"
10050040-44 = "ここはどこですか？それにどうして私たちを……？"
10050040-45 = "それは今に分かりますから。"
10050040-46 = "みんな！連れてきたよ！もう大丈夫です！"
10050040-54 = "これは一体……？"
10050040-55 = "差し支えなければ、説明をお願いしても？"
10050040-56 = "はい。まずはあの黒い制服の皆さんですが……。"
10050040-57 = "あの方々は正義実現委員会。#nトリニティの治安を守る、一種の風紀委員です。"
10050040-58 = "噂によると、正義実現委員会の委員長は、相手をぺしゃんこにしてしまうほどの実力者なんです。"
10050040-59 = "そこに「めちゃくちゃな言いがかりをつける」という点が加われば、[ruby=うち]レッドウィンター[/ruby]の事務局みたいですねぇ。"
10050040-60 = "そのような方々が、どうして今日……？"
10050040-61 = "その……お二人が、正義実現委員会にマークされてしまったからです。"
10050040-62 = "我々が……？"
10050040-63 = "どうして？と言うには、思い当たる節が多いですわね……。"
10050040-64 = "詳しいことはわかりませんが……今朝、正式に調査対象となったようです。"
10050040-68 = "私たちのような一般生徒にまで知らされたわけじゃないですが……。"
10050040-69 = "正義実現委員会のほとんどは皆さんを探していると見ていいはずです。"
10050040-70 = "どうやら正義実現委員会だけでなく、#nティーパーティーも絡んでいるとの噂が……。"
10050040-71 = "ティーパーティー……？"
10050040-72 = "ええと、ティーパーティーは……。"
10050040-74 = "つ、つまり……三頭政治で動いている、トリニティの生徒会が私たちを……？"
10050040-75 = "……チェリノ会長が我々を指名手配した、と。"
10050040-76 = "いや……本当にチェリノ会長が相手なら抜け道は100通りくらいあるけど……。"
10050040-77 = "だから、あれほど他所の自治区は危険だと……！"
10050040-78 = "いや、タカネ……我々にはまだチャンスがあります。"
10050040-79 = "我々は、まだ正義実現委員会に引き渡されていないのですから。"
10050040-80 = "そう、でしょうか……？"
10050040-81 = "お二人が見つかれば……おそらく即追放でしょう。"
10050040-82 = "売上金も没収されるかもしれません。"
10050040-83 = "それは困りますね、もはや経済活動の弾圧では？"
10050040-84 = "そしてお二人から買った本もおそらく全て……。"
10050040-85 = "いけませんわ！そんなの文化活動の弾圧です！"
10050040-86 = "ご安心ください。そのためにお二人にきていただいたのです。"
10050040-87 = "そういえばここは……？"
10050040-88 = " いい質問ですね、ここは――"
10050040-89 = "「お嬢様の隠れ家」です！"
10050040-9 = "なんだか、昨日は見かけなかった方々がいるような……。"
10050040-90 = "自分の口でお嬢様って言ったけど。"
10050040-91 = "ぶ、部長！余計なことを言わないでください！"
10050040-92 = "ここは普段使われていない体育館なんです。"
10050040-93 = "なので、正義実現委員会の目からもしばらく逃れられるかと。"
10050040-94 = "そして――ここに集まっているのは、秘密を守り通す覚悟を持っている方のみ。"
10050040-98 = "同じ学園内でこれだけの秘密や争いがあるだなんて……#nトリニティ総合学園、恐ろしい場所です……。"
10050040-99 = "私たちが言うのも自虐っぽいですけどね……。"
