[translation]
10050005-1 = "プロローグ;No Risk, No Return."
10050005-10 = "……一つ分かったことがあるんだ。"
10050005-100 = "やろうと思えばいくらでも手段はあったはずでしょう？"
10050005-101 = "い、いい作品は自然とファンが見つけてくれるものだから！"
10050005-102 = "あまったれてんじゃないですよっ！そもそも、マーケティングという概念が存在する理由はお分かりで？"
10050005-103 = "物の出来はよくても、宣伝がめちゃくちゃだったせいで倉庫行きになった商品がいくつあると？#nいや正確には私も知りませんけども！"
10050005-104 = "少なくとも、知識解放戦線の図書館分程度はあるでしょう！"
10050005-105 = "盛ってない！？"
10050005-107 = "いえ、これでも規模を少なく見積もってる方ですよ……。"
10050005-108 = "これだから作家ってやつは……作ってばっか、その後のことなんかまるで興味がないんだから！"
10050005-109 = "なんか今日やけに興奮してない！？"
10050005-11 = "あまり聞きたくはないですが……何ですか？"
10050005-110 = "……それは貴女が部長の逆鱗に触れたから、ですわ。"
10050005-112 = "ともかく状況は理解しました。この在庫が捌けなければ……印刷費が払えないということも。"
10050005-113 = "ふむふむ……しかし……。"
10050005-114 = "部長？何か嫌な予感がするのですが。"
10050005-115 = "気のせいですよぉ……ムフフ。"
10050005-116 = "メル、取引しませんか？"
10050005-117 = "取引……？できるなら、あんたとはそんな話したくないんだけど。#nまぁ、今はそんなことも言ってらんないけどさぁ。"
10050005-118 = "そうですよぉ？今、メルに選択権があるとお思いで？"
10050005-119 = "ぐぅ……。"
10050005-12 = "三日くらい何も食べてないと……逆にお腹って減らなくなるんだね。"
10050005-120 = "今すぐ、耳を揃えて印刷費を支払ってくださるなら#n聞かなくても構いませんよぉ～？"
10050005-121 = "くっ……分かったよ、手短にね。"
10050005-122 = "話が早くて助かります。#n我々に委託販売を任せてみませんか？"
10050005-124 = "えっ……？"
10050005-125 = "……はい？"
10050005-126 = "もちろん無料ではありませんよ。要は役割分担です。#nあなた方の同人誌の宣伝や通販の代行をうちがやって差し上げましょうということです。"
10050005-127 = "その代わり収益の一部……手数料を頂戴します。いかがでしょう？"
10050005-128 = "い、嫌っ！あんたと組んでまともだったことなんて一度たりともないんだけど！？"
10050005-129 = "ま、待ってくださいメル先輩！これはヤクモ部長の話も一理あるかと……！"
10050005-13 = "力も入りませんけどね……。"
10050005-130 = "現状、自家通販だってほとんど動いていないですし……手を借りるのはアリだと思うんです。"
10050005-131 = "在庫を抱えて共倒れになるよりはマシじゃないでしょうか？"
10050005-132 = "それに、置き場所どうするんですか……本って重いですし、かさばるんですよ……？"
10050005-134 = "おや、話が通じる人だ。いやぁ、こんな風に提案できる取引相手は貴重なんですよぉ？"
10050005-135 = "ぐっ……悔しい……。でもたしかにモミジの言う通り、他に手はない……#nはぁ、分かった……やってやろうじゃないの！"
10050005-136 = "よしよし、では契約書を作りましょうか。取り分は……9:1でいかがでしょう？"
10050005-137 = "……念のため聞くけど、こっちが9だよね？"
10050005-138 = "まさか？"
10050005-139 = "だと思ったよ！このドロボー！！"
10050005-14 = "それも多分今だけですよ。そのうち、食べ物のことしか考えられなくなるのでは？"
10050005-141 = "部長！？いくらなんでもそれはやりすぎでは！？"
10050005-143 = "レッドウィンターの通り"
10050005-144 = "はぁ……なんとか契約できましたわね。"
10050005-145 = "私たちは売上に応じて所定額を送る、と。"
10050005-146 = "とはいえなかなかの量ですねぇ。まったく、どうするつもりだったんだか。"
10050005-147 = "さて行きましょうかタカネ。我々出版部の底力を、見せつけてやりますよぉ！"
10050005-15 = "もうなってるしいいんじゃない……？"
10050005-152 = "そんな、まさか……！"
10050005-157 = "1冊も売れませんでしたわね。"
10050005-158 = "どうしてっ！？間違いなく、パーフェクトな戦略だったはずなのに！"
10050005-159 = "私の所感ですが……メルリーさんの本は、それなりに面白いものの……。"
10050005-16 = "なってるんじゃないですか……。"
10050005-160 = "レッドウィンターにおいては、目新しさに欠けるのでしょう。"
10050005-161 = "特に今回はマニアックでもなければ大衆性にも欠けた、半端なものでしたから。"
10050005-162 = "いくら面白い話でも3回聞けば飽きるものです。#nそれに多くの作家が扱えるテーマは1つと言われています。"
10050005-163 = "優秀な人は二つのテーマを、天才は三つ以上のテーマをと。メルリーさんがこれまでいろんな味変を加えてきたのは間違いないでしょうが……。"
10050005-164 = "少なくともレッドウィンターでは、それさえも慣れてしまった、といいますか……。"
10050005-165 = "……ええ、いい指摘ですね。しかし、ここで根本的な問題が一つ。"
10050005-166 = "？なんでしょうか？"
10050005-168 = "レッドウィンターの生徒らの懐事情がキビシイということですっ！"
10050005-169 = "そ、それを言っては元も子もないのでは？"
10050005-17 = "それで……給食所の工事っていつ終わるの？"
10050005-170 = "ですが、人はお金がない時、まず文化生活から切り捨てていくものです。"
10050005-171 = "部長……それでも出版部の人間ですか！？"
10050005-172 = "理解しているからこそ！出版業をしているんじゃありませんか！"
10050005-173 = "で、ですがそんな状況でも、なんとか活路を見い出すのが私たちの使命では……。"
10050005-174 = "どうせ部費の半分以上は、チェリノ会長の宣伝と「レッドベア」の印刷費に回される運命ですよ！？"
10050005-175 = "自分たちで言うことではありませんわね。#n「レッドベア」の編集長だって、粛清されてからまだ姿を見せておりませんし。"
10050005-176 = "そうですね……「レッドベア」編集部の方々を出版部で拾ったりもしました。"
10050005-177 = "はぁ……あの一件があるまでは、出版部もそこそこ回っていたはずなのですが……。"
10050005-178 = "いえ、編集部を受け入れたことで、財政はぐんとよくなりましたよ？"
10050005-179 = "その一方で、事務局の干渉を受けるようにはなってしまいましたが……。"
10050005-18 = "一応明日、らしいですけど……。"
10050005-180 = "ムフフ。タカネはそうかもしれませんね、評論家ですから。"
10050005-181 = "ですが、出版部の経営を担っている私としては、現状もそんなに悪くありません。"
10050005-182 = "まあそれはともあれ、問題の原因が判明したわけですし。"
10050005-183 = "なんでしょうか？"
10050005-184 = "それは――"
10050005-185 = "余裕のない方々しかいない場所で稼ごうとしたことです！"
10050005-186 = "レッドウィンターの財政状態が他学園より悪いのは、火を見るよりも明らか！"
10050005-187 = "辛抱する木に金がなるとはいえ、我らに当てはまるとは限りません！"
10050005-188 = "た、たしかにそうですが他にできることもあるのでは……。"
10050005-189 = "ええ、ありますとも。"
10050005-19 = "じゃあ明日にはご飯が食べられる……よかった……。"
10050005-190 = "それは……？"
10050005-191 = "商売とは第一に立地。第二に立地。第三に立地と言われてます。"
10050005-192 = "つまるところ、余裕のある方の場所へ行けば良いのです。#n読書習慣があるなら尚良い。"
10050005-193 = "そんな場所があるのですか？"
10050005-194 = "ええ、もちろん。それは――"
10050005-196 = "――トリニティ総合学園です。"
10050005-199 = "待ってください部長！？トリニティで商売をするおつもりですか！？#n他自治区ですよ！？"
10050005-2 = "レッドウィンター連邦学園・図書館"
10050005-20 = "昨日も同じこと言ってましたけどね……。"
10050005-200 = "リスクなくしてリターンなし！ほら、ついてきてくださいタカネ。#n遅れたら置いていきますよぉ。"
10050005-205 = "部長……？部長！！？"
10050005-21 = "……またストライキ？"
10050005-22 = "おそらく……。"
10050005-23 = "……あと1週間はかかりそうだね。"
10050005-24 = "私たちも、そろそろ何か行動しないといけないのでは……？"
10050005-25 = "みんな、血走った目で食べ物を探し始めましたし……。"
10050005-26 = "行動したからこうなったんでしょ？"
10050005-27 = "これも全部、本が売れないからだよ！"
10050005-28 = "あぅ……大声出しすぎた……。"
10050005-33 = "うぅ……事務局が部費を支給しないから……！"
10050005-34 = "本を売って捻出しようとしたけど全然……。"
10050005-35 = "このままでは知識解放戦線の未来は……。"
10050005-36 = "こうして文明は闇に埋もれ、人類は衰退の一途を辿るわけです……。"
10050005-42 = "知識解放戦線の皆さん、ご機嫌よう。#n出版部の責任者、[ruby=あらまき]荒槇[/ruby]ヤクモが参りましたよぉ。ムフフ。"
10050005-43 = "相変わらず品のないお姿ですこと、メルリーさん。#nいうまでもないかとは思いますが……図書館の床はベッドではありませんよ？起きてくださいな。"
10050005-44 = "はいはい……何とでも言って……。"
10050005-45 = "あら、メルリーさんがこんな素直に聞くなんて。#nどこか具合でも悪いのですか？本当に大丈夫です？"
10050005-47 = "大丈夫じゃないかもしれません……ヤクモ部長、タカネ先輩。"
10050005-48 = "ふむ……一体何があったんですか？"
10050005-49 = "えっと……その、すみません。#nなにか、食べ物はありませんか？"
10050005-50 = "……はい？"
10050005-52 = "うぎゃーーっ！！お腹痛いよぉ！！"
10050005-53 = "三日間何も食べてないのに一気に食べるからですよ。胃に負担がかかったのでしょう。#nはい、お水。"
10050005-54 = "ありがとうございます、ヤクモ部長、タカネ先輩……。#n一時はどうなることかと。"
10050005-55 = "どういたしまして。困った時にはお互い様ですから。#nもちろん代金はちゃんと請求しますけどね？ムフフ。"
10050005-57 = "ちょっと怖いんだけど……いやまぁ、死にかけのところを助けてくれたんだし、仕方ないか……。"
10050005-58 = "あなた方の状況が、部費の支給が遅れているせいだということは理解しました。#nそれにしては事態が少々深刻なようですが。"
10050005-59 = "えっと……色々と日程を前倒しにしてみたりしてもみたんですが……少々無理がたたってしまって……。"
10050005-60 = "ああ、先週急に持ってきた原稿の件ですね？#n印刷費を後払いで、とおっしゃっていたのはまさか……。"
10050005-61 = "あんなこと、しちゃいけなかった……。"
10050005-62 = "なるほど……まあでもそれは理由になりませんから。"
10050005-63 = "はい、とっとと印刷費を支払ってください。"
10050005-64 = "この状況を見てそれ言えるの！？この人でなし！#nそこらにあるもの何でも持ってけば！？"
10050005-65 = "おや、いいんですか？"
10050005-66 = "……本気？"
10050005-67 = "ええ。そしてちゃんと代金も頂きます。"
10050005-68 = "悪魔……！悪魔がいるよ！？"
10050005-7 = "メル先輩、大丈夫ですか……？"
10050005-70 = "しかしそれにしても妙ですね、メルリーさん。"
10050005-71 = "いくらあなたが好き勝手に描いていて、需要なんて気にも留めないとはいえ……。"
10050005-72 = "ねえちょっと、バカにしに来たの！？なんなの！？"
10050005-73 = "話は最後まで聞くものですわ。その分、コアなファンがいるということです。#nそれに優秀な編集者であるモミジさんがいるというのに、食費が賄えないほどだなんておかしいですわ。"
10050005-74 = "その、私たちも……ここまで部数が出ないとは思わなくて……。"
10050005-75 = "まだ在庫はありますか？少し拝見しても？"
10050005-8 = "大丈夫そうに見える……？"
10050005-80 = "ど、どう……？"
10050005-81 = "……ひとまず、原因は分かりました。"
10050005-82 = "な、なんでしょう……？"
10050005-83 = "メルリーさん。あなたの原稿は、基本的に傍若無人で、読み手よりも自分のことを優先している傾向が強いです。"
10050005-84 = "だからこそコアなファンがいるとも言えるのですが……#n大衆性はほとんどありません。"
10050005-85 = "で……これは何ですか！？メルリーさん特有の味が薄れ、半端に大衆性を取り入れましたね？#n何もかもが中途半端ですわ！"
10050005-86 = "これでは今まで読んでくれていたコアなファンも、大衆にも刺さりません！#n5段階評価として2点……いいえ、1.5点ですわ！"
10050005-87 = "で、一体何があったんですか？モミジさん。"
10050005-88 = "そ、その……今回は違う路線で行こう、って……今度こそ、一般ウケする作品を、と……。"
10050005-89 = "締切もかなり前倒しにしたので、メル先輩が暴走して……編集や添削の時間もあまり取れず……。"
10050005-9 = "いえ……。"
10050005-90 = "ふむ……他にも問題がありそうですね。"
10050005-92 = "どういうこと……？"
10050005-93 = "我々出版部の目から見て――"
10050005-94 = "そのやり方には、異を唱えざるを得ない！"
10050005-95 = "ひっ！？"
10050005-96 = "ぐぁっ！？"
10050005-97 = "なんですかこれ、なにもかも中途半端な原稿ですし……というか、どこで新刊の告知してるんですか。"
10050005-98 = "そ、その、あんまり宣伝する時間がなくて……。"
10050005-99 = "甘えるんじゃないですよ！！いくらファンでも告知不足では足を運ぶわけないじゃないですかぁ！？"
