[translation]
10052190-10 = "ま、周りが……。鋼鉄大陸が……？"
10052190-11 = "慌てないでください！"
10052190-12 = "これはデカグラマトンがエネルギーを展開して作った「仮想領域」のようなものです！"
10052190-13 = "あいつさえ倒せば、すべて元通りになります！"
10052190-14 = "つまりこの「領域」の中は、デカグラマトンのために構築された空間とも言えますね。"
10052190-15 = "そ、そうですが……どうして分かったんですか？"
10052190-16 = "マンガかゲームで見たんでしょ？"
10052190-17 = "その通りです。私は完璧なメイドでエージェントですから。"
10052190-18 = "この先は真面目にやってくださいね！？"
10052190-25 = "……せっ、先生！"
10052190-26 = "[s] \"どうしたの？\""
10052190-27 = "輸送船との通信が途切れたわ！"
10052190-28 = "はい！？"
10052190-29 = "絶対制圧装置「アツィルトの帯」――起動。"
10052190-3 = "……なぜだ。"
10052190-34 = "宙に浮いていた機械の構造物が……？"
10052190-36 = "[ns] \"あれは何……？\""
10052190-39 = "その命を召すことはしない。"
10052190-4 = "なぜ無駄な抵抗を繰り返す。"
10052190-40 = "自ら跪き、醜き姿を見せた汝に免じて、それだけは約束しよう。"
10052190-41 = "鍵の身体を通じて8つのセフィラの力が集まった。"
10052190-42 = "これより――無機物に限られていた「変換」を、すべての元素に拡張する。"
10052190-43 = "このアツィルトの帯のもと、お前たちは鋼鉄大陸の一部となり。"
10052190-44 = "新しい身体と魂を授かり、私の使徒として生まれ変わるだろう。"
10052190-5 = "足掻ければ足掻くほど、汝らの苦痛が増えるだけだというのに。"
10052190-9 = "[ns] \"えっ……？\""
