[translation]
10052030-18 = "[ns] \"ヒマリ！リオ！大丈夫？\""
10052030-19 = "あら、先生。ここまで心配してくださるだなんて。#n多少なり無理をした甲斐がありましたね。"
10052030-2 = "なっ、なっ、ななっ……なああああっ！！"
10052030-20 = "ご心配には及びませんよ♪"
10052030-21 = "なんなら、毎回この手を使うのもありだと思うくらい♪"
10052030-22 = "それは良くない気がするわ……。"
10052030-23 = "[ns] \"そうだよ。リオの言う通り。\""
10052030-24 = "しょぼーん。"
10052030-25 = "……何をわざとらしく落ち込んでいるのですか。"
10052030-26 = "とにかく、2人とも無事でよかったです。"
10052030-27 = "ケイも心配してくれるんですか？#nふふっ、なんだか元気が戻ってきました！"
10052030-28 = "そういうのはいいですから！まったく！"
10052030-3 = "これで勝ったと思わないでくださいね！！"
10052030-32 = "部長、会長。ちょっといい？#nコアみたいなのを発見したよ。"
10052030-37 = "これが……コア？"
10052030-39 = "ケイ、確認できるかしら？"
10052030-40 = "やってみます……。#nエイミ、それを地面に下ろしてくれますか？"
10052030-41 = "うん？分かった。"
10052030-45 = "……。"
10052030-46 = "理解……観察者……[ruby=JEHOVAH ELOHIM]エホバ・エロヒム[/ruby]……#n沈黙と貪欲、豊かさと悲しみ……。"
10052030-47 = "……！"
10052030-48 = "確認しました。ビナーのコアで間違いありません。"
10052030-49 = "現物を見なくても分かるのですか？"
10052030-50 = "はい、今なら。"
10052030-51 = "……なるほど。#nこの穴の付近は、もう私たちの占領下にあるから……。"
10052030-52 = "それに加えて、ここは鋼鉄大陸のネットワークにとって玄関口のような場所です。#nこれくらいはどうとでもなりますよ。"
10052030-53 = "そして……預言者のコアに関して、新しく分かったことがあります。"
10052030-54 = "なんでしょうか？"
10052030-55 = "まずは、前にお伝えしたことの復習から。#nコアが持つ情報は、私の身体にインストールすることができます。"
10052030-56 = "それはつまり、ネットワークの上位権限と神威……各セフィラの位格を、私が継承するということです。"
10052030-57 = "そしてさらに……。"
10052030-58 = "預言者のコアを組み込んで応用すれば、輸送船そのものを強化することができるかもしれません。"
10052030-59 = "どんな風に……？"
10052030-60 = "そうですね……ビナーのコアを輸送船に組み込めば、ビナーの能力や出力の一部を、輸送船が使用できるようになります。"
10052030-61 = "他の預言者のコアも、同様であるはずです。"
10052030-66 = "ってことはまさか！！"
10052030-67 = "やっぱりあれですね、ケイ！敵の能力を利用する生命体！"
10052030-68 = "いえ、例えるなら、その……。"
10052030-69 = "せめて、別のものにしてください……。"
10052030-8 = "では、戻りましょうか。"
10052030-9 = "……ええ。"
