[translation]
10052090-1 = "コクマー：王国を守りし古代の守護者 "
10052090-3 = "[ns] \"ねぇ、ケイちゃん。\""
10052090-4 = "なんですか？"
10052090-5 = "[s] \"ケイちゃんを戦闘に参加させていいのかな……。\""
10052090-6 = "今さらですか？"
10052090-7 = "[s] \"だって心配で……。\""
10052090-8 = "またからかっているなら、怒りますよ。"
10052090-9 = "大丈夫だよ、先生。いざとなったら私に任せて。"
10052090-10 = "[s] \"エイミは最高のエージェントだもんね。\""
10052090-14 = "今、最高のエージェントと言いましたか。"
10052090-15 = "[s] \"あ、えっと、もちろんトキもだよ！うん！\""
10052090-16 = "満足したので、これで失礼します。"
10052090-22 = "私は何を見せられているんですか……。"
10052090-23 = "そういえば、コクマーを発見したのってリオ会長だったよね。"
10052090-24 = "え？ええ……そうね。"
10052090-25 = "地面から急に工作船が現れるのだもの。あれには驚かされたわね。"
10052090-26 = "まさに「特異現象」って感じだね。"
10052090-27 = "……。"
10052090-28 = "リオ。特異現象捜査部を立ち上げた張本人として、今の状況についてどう思いますか？"
10052090-29 = "あれ？ケイもそれ知ってるの？"
10052090-30 = "まあ……今までのデータやヒストリーは、おおよそ学習していますので。"
10052090-31 = "これ、言ってませんでしたっけ……？"
10052090-33 = "そうだったのね……。"
10052090-34 = "えっと、今の状況について、だったわね。#n感慨深い……という表現は、こういうときに使うのかしら？"
10052090-36 = "……！"
10052090-37 = "……！"
10052090-38 = "なぜ、そんな表情を？"
10052090-39 = "あ……いえ、その。"
10052090-42 = "なぜ、そんな表情を？"
10052090-44 = "あ……いえ、その。"
10052090-45 = "会長も、昔に比べて変わったなって思って。"
10052090-46 = "ド直球に言いますね！？"
10052090-48 = "それは……良い意味と受け取っていいのかしら？それとも……。"
10052090-50 = "急に判断力落ちてませんか！？"
10052090-51 = "ケイ、落ち着いて。いちいち怒ってたら、感情回路にエラーが生じちゃうかもよ？"
10052090-53 = "否定はできないわ。貴女の身体は、まだ完全には分析できていないのだから。"
10052090-54 = "致命的なエラーが生じたら対処できないかもしれないわ。"
10052090-61 = "あー……、もう……っ！"
10052090-62 = "[s] \"……ケイちゃん、大丈夫？\""
10052090-63 = "私がストレスで倒れてしまったら、あなた達のせいですからね……。"
10052090-67 = "ケイ！？ダメです！アリス、そんなの嫌です！"
10052090-68 = "いえ……言ってみただけですよ……。"
10052090-69 = "[s] \"苦労が多いね……。\""
10052090-70 = "分かってくれてありがとうございます、先生……。"
10052090-76 = "さあ、仕事の時間だよ、ケイ。先生は安全な場所を探して。"
10052090-77 = "仕事をしていたほうが、余計なことを考えずに済みますね……。"
10052090-78 = "じゃあ、始めよっか。"
