[translation]
10051005-1 = "プロローグ;ラーメンと陰謀"
10051005-101 = "ふっふっふ、相手の注意を引いて、背後を取る。これこそが――"
10051005-102 = "『忍法・キラキラファイアーの術！』の真の使い方！"
10051005-103 = "さすが部長！#n「忍者三人寄れば虎をも制す」戦略とはこれなのですね！"
10051005-104 = "もっちろん！"
10051005-105 = "……あれ、そうだっけ？"
10051005-106 = "あ、あの……。"
10051005-107 = "ツクヨ？どうしたの？"
10051005-108 = "かかったスープは、拭き取ったんですが……。"
10051005-110 = "カメラの電源が……入りません……！"
10051005-111 = "……。"
10051005-112 = "……。"
10051005-114 = "えええぇぇぇっ！？"
10051005-118 = "ふむ……。"
10051005-119 = "機敏で無駄のない動き……さらに店主の安全にまで気を使える……。"
10051005-12 = "[log]仕上げにラー油を一回し！[/log]"
10051005-120 = "にゃはは。これなら、護衛任務も任せられるかもしれませんねぇ……。"
10051005-121 = "前々から忍術研究部の腕前は存じておりましたが……まだ新たな発見があるとは。"
10051005-122 = "……これなら。"
10051005-123 = "「あの任務」に抜擢するのも……悪くないかも？"
10051005-15 = "百鬼夜行某所のラーメン屋"
10051005-16 = "これぞ忍者流！ラーメンを嗜む新作法！"
10051005-17 = "し、「新・忍者定食」です！"
10051005-18 = "みなさん、お待たせしました！ニンニン！"
10051005-19 = "「少女忍法帖ミチルっち」！忍者とラーメン編！"
10051005-20 = "始まります！！！"
10051005-21 = "……あっ、ちょっと待った！"
10051005-22 = "カメラ、なんか傾いてない？"
10051005-23 = "三脚のせいかな……？"
10051005-24 = "えっ！？ご、ごめんなさい……。#n私がもっと、気をつけておけば……。"
10051005-25 = "いやいや、セッティングしたのは私なんだから。"
10051005-26 = "心配ご無用！もう一度撮り直せば大丈夫です！"
10051005-27 = "それでは気を取り直して――"
10051005-29 = "ガシャーン！"
10051005-3 = "[log]忍者たる者、忘るべからず。[/log]"
10051005-32 = "店長！このスープどうなってんの！？#nゆるすぎて麺に絡まないだろ！"
10051005-33 = "麺の茹で加減も足りないな！"
10051005-34 = "麺とスープの一体感が失われてるじゃんか！"
10051005-35 = "いや、ウチのラーメンはもう何年もこのレシピで……。"
10051005-36 = "ってそれより！#n味が気に入らないからって、テーブルをひっくり返されては困ります！"
10051005-37 = "他のお客様にもご迷惑ですから！"
10051005-42 = "らっ……ラーメンが直撃して、カメラが……！"
10051005-43 = "うっ……うぅっ……。"
10051005-44 = "終わった……！"
10051005-45 = "ぶ、部長……これからどうすれば……。"
10051005-46 = "……。"
10051005-50 = "（ああ、もうっ！！あの厄介客め……！このまま引き下がるわけには――）"
10051005-51 = "（でも……私、あいつらに勝てるのかな？）"
10051005-55 = "（いや、私は1人じゃない……）"
10051005-56 = "（ツクヨとイズナがいる……！）"
10051005-57 = "……忍者たる者、いかなる窮地にあっても――"
10051005-58 = "不義に背を向けることはない……！"
10051005-59 = "お？なんだぁ？"
10051005-6 = "[log]麺は極太！[/log]"
10051005-60 = "部長……？"
10051005-64 = "くらえ！忍法・キラキラファイアーの術！"
10051005-72 = "ぐあああっ……あ？何とも……ない？"
10051005-73 = "……花火？"
10051005-74 = "なんか……ピカピカするだけで痛くもかゆくもないし？"
10051005-75 = "なんにせよ、ケンカを売ってきたってことだよな……！"
10051005-76 = "てか、忍法って何なんだ？"
10051005-77 = "それはわから――"
10051005-8 = "[log]背脂追加！[/log]"
10051005-85 = "後ろに下がっていて……ください！"
10051005-86 = "あ、ありがとうございます！"
10051005-95 = "ぐぅっ……！"
10051005-96 = "注意を逸らしておいて、後ろから不意打ちとは卑怯な……。"
