[translation]
10051030-1 = "第3話;才能との邂逅"
10051030-10 = "ツクヨさんのサイズとなると、オーダーメイドじゃないと厳しいみたいでして。"
10051030-105 = "はあ……もったいない。"
10051030-106 = "その体格、その資質……それで警備とはね……。"
10051030-107 = "はい……？"
10051030-108 = "ただの独り言だよ。"
10051030-109 = "気にしないでほしい。"
10051030-11 = "じゃあ、今すぐ注文を――！"
10051030-110 = "才能があるからといって、その道に進む必要があるわけじゃないからな。"
10051030-111 = "とはいえ……ふむ……。"
10051030-112 = "……？"
10051030-113 = "やっぱり、見逃すには惜しいね。"
10051030-114 = "君、名前は？"
10051030-115 = "はい！？"
10051030-116 = "お、[ruby=おおの]大野[/ruby]ツクヨ、です……。"
10051030-117 = "忍術研究部所属で、年齢は――"
10051030-118 = "ああ、所属なんてどうでもいい。"
10051030-119 = "大野ツクヨ。覚えておこう。"
10051030-12 = "イベント開始は1時間後なのに？"
10051030-120 = "君も、私のことを覚えておくといい。"
10051030-121 = "……はい、これ。"
10051030-122 = "め、名刺……！"
10051030-123 = "じゃあ、私はこれで。"
10051030-127 = "（い、今のは何だったんでしょう……？）"
10051030-128 = "（あんなすごい人が、私の名前を……？しかも名刺まで……？）"
10051030-129 = "（な、何を考えているのかまったく分かりません……）"
10051030-13 = "はっ……！"
10051030-130 = "（うぅ……）"
10051030-131 = "（だ、ダメダメ、気にしちゃダメ！）"
10051030-132 = "（私は自分の任務をきっちり果たせばいいだけ……！）"
10051030-133 = "……よし！大野ツクヨ、外部警備作戦を開始します！"
10051030-135 = "ファッションショー控室"
10051030-136 = "準備は順調？"
10051030-137 = "もちろんです！すべて滞りなく！"
10051030-138 = "当然、衣装はちゃんと保管されてるだろうね？"
10051030-139 = "どれもこの世に1着しかない……替えが利かないのだから。"
10051030-14 = "仕方ありません。"
10051030-140 = "はいっ！奥の部屋にしっかりと！"
10051030-141 = "直射日光が入らず、除湿・消臭も万全の環境です！"
10051030-142 = "一度、確認されますか？"
10051030-143 = "あぁ、そうしよう。"
10051030-144 = "そろそろモデルたちが着替える時間だからね。"
10051030-145 = "衣装がある部屋はどこだ？"
10051030-146 = "ご案内します。"
10051030-147 = "こちらへどうぞ！"
10051030-15 = "こうなってしまった以上、手は1つだけです。"
10051030-151 = "こちらが……あれっ？"
10051030-152 = "鍵が……開いてる……？"
10051030-153 = "どうしたんだ？"
10051030-154 = "い、いえ……なんでもありません！"
10051030-155 = "衣装はこの部屋に……。"
10051030-159 = "ひ、ひえええええっ……！"
10051030-16 = "方法があるの！？"
10051030-160 = "な、何ごと！？"
10051030-161 = "そ、そんなはずは……！"
10051030-162 = "しゃっ、しゃっ、シャインキャット様ぁ……！"
10051030-163 = "も、も、申し訳ございませんっ！！"
10051030-164 = "大変です！！"
10051030-165 = "要領を得ないな……ちゃんと説明しなさい！"
10051030-166 = "そ、それが……。"
10051030-167 = "シャインキャット様の作品が……全部……！！"
10051030-168 = "い、いや……これは夢だ、夢に違いない……！"
10051030-169 = "いいから、どきなさい！"
10051030-17 = "もちろん。"
10051030-173 = "この部屋で、あってるんだよね……？"
10051030-174 = "私の作品はどこ……！？"
10051030-175 = "も、申し訳ございません！#nついさっきまでは確かに……！"
10051030-176 = "つべこべ言わない！"
10051030-178 = "今すぐ犯人を捕まえてきなさい！！"
10051030-179 = "はいっ！？"
10051030-18 = "ただ……ちょっと胸が痛むやり方ではありますが……。"
10051030-180 = "言ってる意味がわからないのか！？#n私の作品を盗んだ犯人を！今すぐ！目の前に連れてこいと言っているんだ！！"
10051030-181 = "それができなければ、全員クビだ！分かった！？"
10051030-182 = "ひ、ひぃっ！分かりました！！"
10051030-19 = "うん……？"
10051030-2 = "陰陽部・部室"
10051030-21 = "（1時間後……）"
10051030-22 = "（忍術研究部の護衛任務が始まった）"
10051030-24 = "ファッションショー宴会会場内部"
10051030-26 = "わっ、人がいっぱい……頭がクラクラする……。"
10051030-27 = "でも、やることやらないと！"
10051030-28 = "応答せよ、アンダーカバー02。聞こえてる？"
10051030-3 = "なるほど。昨日の今日でそんなことが。"
10051030-32 = "はいっ！こちらアンダーカバー02、よく聞こえます！"
10051030-33 = "現在位置は？"
10051030-34 = "指示通り、宴会場の東側で待機中です！"
10051030-35 = "了解、引き続きよろしく！"
10051030-39 = "イズナは大丈夫そうだね。次は……。"
10051030-4 = "うん……成り行きで……。"
10051030-40 = "アンダーカバー03、聞こえるかな？"
10051030-42 = "ファッションショー宴会会場正面玄関"
10051030-44 = "は、はい、アンダーカバー03です……聞こえて、ます……。"
10051030-45 = "か、会場の正面入口で待機中です……。"
10051030-46 = "ツクヨ、ごめんね……。"
10051030-47 = "1人だけ会場の外になっちゃって……。"
10051030-48 = "ドレスを着てないと会場内には入れない、って主催側が言ってて……。"
10051030-49 = "ぶ、部長が謝ることじゃ、ありません！"
10051030-5 = "ドレスは修理していただいたので、問題ありませんが……。"
10051030-50 = "私が、大きすぎただけ、ですから……。"
10051030-51 = "ふ、普段着のほうが落ち着きますし……！"
10051030-52 = "そう言ってくれてありがとね。"
10051030-53 = "よしっ！任務が無事に終わったら、ラーメン食べに行こう！"
10051030-54 = "この前の撮影のリベンジもしないとだし！"
10051030-55 = "は、はい！"
10051030-56 = "麺は極太！背脂追加！仕上げにラー油を――"
10051030-57 = "あっ！"
10051030-58 = "どうしたの！？"
10051030-59 = "し、シャインキャットさんが到着しました！"
10051030-6 = "ですが困りましたね……#n陰陽部には、あれより大きいドレスはもう無いんですよ。"
10051030-67 = "VIP到着確認！各自、配置につけ！"
10051030-68 = "……これで合ってるよね？"
10051030-7 = "ええっ！？"
10051030-72 = "（落ち着いて、落ち着いて……！）"
10051030-73 = "（怪しい人がいないかだけ、ちゃんと見ていれば大丈夫……！）"
10051030-79 = "君。"
10051030-8 = "[s] \"近くのお店で買ったりはできないの？\""
10051030-80 = "は、はい！？"
10051030-81 = "ここで何をしているのかな？"
10051030-82 = "え、えっと……け、警備を……。"
10051030-83 = "もうすぐショーが始まるというのに？#nどうしてモデルが会場の外でうろうろしてるんだ？"
10051030-84 = "えっ！？"
10051030-85 = "驚いてる暇があるなら、さっさと控室に戻りなさい！"
10051030-86 = "あ、あ、あの……！"
10051030-88 = "わ、私はモデルじゃ、ないんです……けど！！"
10051030-9 = "既にブティックには連絡したんですけど……。"
10051030-93 = "そうなのかい？"
10051030-94 = "どう見てもモデルにしか見えないけど……。"
10051030-95 = "わ、私はただの警備担当で……。"
10051030-96 = "……そうか。"
10051030-97 = "私の勘違いだったのなら、すまなかった。"
10051030-98 = "でも……。"
