[translation]
10052115-10 = "推測ですが……ティファレトという預言者が、ソフにとって大事だったのだと思います。"
10052115-100 = "はい？これはそういうのではない、ですか？"
10052115-101 = "人は誰かの幸せな姿を見ていると、自分も幸せな気分になれて――"
10052115-102 = "誰かの苦しい姿を見ていると、自分もその苦痛に共感できるから……？"
10052115-103 = "誰かが泣いているとき、隣で一緒に泣いてくれる誰かがいるだけで――"
10052115-104 = "その人は、悲しみに打ち勝てる力を得るから……？"
10052115-105 = "ですが、必ずしもそうだとは言い切れないのでは？#nただの誤解や錯覚かもしれませんよ。"
10052115-106 = "いえ、それならまだマシな表現ですね。#nある意味それは……偽善ではありませんか。"
10052115-107 = "あの3人も言っていましたね……。#n生命も、絆も、社会も――錯覚の上に建つ、砂上の楼閣に過ぎない、と。"
10052115-108 = "[s15] \"別にいいんじゃないかな。\"\n[s16] \"偽善だったとしても。\""
10052115-11 = "ティファレトは自分より種を優先した、とソフは言っていました。"
10052115-111 = "はい！？！？"
10052115-112 = "……！"
10052115-113 = "[s17] \"最初から善良なまま生まれるのと、本性を努力で克服するのと。\"\n[s18] \"どっちがよりカッコいいのかって話でしょ？\""
10052115-116 = "そういう問題ではないと思いますが……。"
10052115-117 = "はい？それが大事……？#nどういうことですか？"
10052115-118 = "一度きりの人生、カッコよく生きること以外、他に道はない……と？"
10052115-119 = "先生らしいですね……。"
10052115-12 = "他の預言者とは、行動パターンが異なるような気がします。"
10052115-120 = "まだよく分かりませんが……。"
10052115-121 = "それでも、アリス、分かったような気がします！#nアリスは……今のままで良いのですね！"
10052115-122 = "[s] \"うん！その通り！\""
10052115-123 = "ありがとうございます、先生！#nアリスは先生のおかげで、やりたいことが見つかったような気がします！"
10052115-124 = "それは何ですか？"
10052115-128 = "はい！アリスはみんなと友達になりたいです！"
10052115-13 = "……。"
10052115-132 = "アイン、ソフ、オウルに、マルクト、そして他の預言者も！"
10052115-133 = "話し合うだけで、すべての問題が解決できるとは限りませんが……。"
10052115-134 = "少なくとも、試すくらいはできると思います。"
10052115-135 = "たとえそれが偽善だとしても、やらないよりはずっと良いはずですから！"
10052115-136 = "[s] \"うん。そうなるといいね。\""
10052115-137 = "はい！"
10052115-14 = "[s] \"アリス？どうしたの？\""
10052115-15 = "先生……まだ覚えていますか？"
10052115-16 = "第一防御線を突破した時、アリスが……。"
10052115-17 = "[s] \"言いたいときが来たら、また話そう、だね。\""
10052115-18 = "はい……。#nアリスは今、あの時と同じ気持ちになっています……。"
10052115-19 = "……。"
10052115-20 = "生きるのは苦痛に過ぎないと言うソフに、アリスはどう答えればいいのでしょうか？"
10052115-21 = "誰かにとって、世界はただ悲劇で、誕生は呪いに過ぎなくて……。"
10052115-22 = "いっそ生まれないほうが良かったと、話す人がいたら……。"
10052115-23 = "アリスはその人に対して、どんな言葉をかけることができるのでしょうか……？"
10052115-24 = "アリスには……よく、分かりません。#n胸の奥が苦しくなって、息がしづらくなるような気分です……。"
10052115-25 = "[s] \"実はソフの話も、完全に間違ってはないよ。\""
10052115-26 = "はい！？！？"
10052115-27 = "[s1] \"明日はおそらく、何かを失う日で。\"\n[s2] \"良いことなんて、そうそう起きない。\""
10052115-3 = "なんとかなりましたね。#nエリアの掌握と、コアのデータ回収が完了しました。"
10052115-30 = "[ns] \"あの3人が話してたよね。\""
10052115-31 = "それ、認めていいんですか……？"
10052115-32 = "はい？認めないと前に進めない……？"
10052115-33 = "先生らしいですね……。"
10052115-38 = "それならアリスは……どこで生きる意味を見つければいいのでしょうか……？"
10052115-39 = "アリスは今まで、こんなふうに考えたことはありません。#nだから……怖いです。なぜだか……ただ、怖いんです。"
10052115-40 = "[s] \"その答えを、アリスは知ってるはずだよ。\""
10052115-41 = "……え？"
10052115-42 = "……さっき、アリスはこう言いました。"
10052115-43 = "生きてきた時間が無意味だとは思わない。"
10052115-44 = "ただ……みんなと一緒に居たいだけ、と。"
10052115-45 = "ですが……いいのでしょうか？#n本当に、それだけで……。"
10052115-46 = "[s3] \"むしろ、それで良いと思うよ。\"\n[s4] \"人生は元々、大きな意味や目的があるわけじゃないからね。\""
10052115-49 = "はい！？"
10052115-50 = "えぇっ！？"
10052115-51 = "人生には、意味も目的もない……？"
10052115-52 = "……あ。"
10052115-53 = "もしかして、逆……なんですか……？#nもしも人生に意味や目的があったなら、それを見つけられなかった人生は、#n価値のないものになってしまうから……？"
10052115-54 = "……！"
10052115-55 = "[s5] \"だから……ありのままでいいと思うよ。\"\n[s6] \"私は、みんなに出会ったことが、何より嬉しいんだから。\""
10052115-58 = "あ、アリスも一緒です！先生がいなかったら、アリスは……！"
10052115-59 = "……。"
10052115-60 = "私も、ですか？"
10052115-61 = "[s] \"もちろん。\""
10052115-62 = "まあ、それなら……いいです。"
10052115-63 = "[s7] \"やりたいようにやったらいいんだよ。\"\n[s8] \"人生は不条理な事ばかりだからね。\""
10052115-68 = "[ns] \"どのみち、人生の選択肢は2つだけだから。\""
10052115-69 = "不条理を受け入れるか……。"
10052115-70 = "……最後まで戦うか、ですね。"
10052115-71 = "ですが、受け入れてしまったら、その先はもう……。"
10052115-72 = "……。"
10052115-73 = "なるほど。だから、進む道は1つだけなんですね。"
10052115-74 = "[s9] \"うん。私たちは戦って――\"\n[s10] \"最後にみんなで幸せになるべきなんだ。\""
10052115-77 = "……闘争こそ幸福、ということですか。"
10052115-78 = "[s11] \"そうだよ。\"\n[s12] \"怒りを持ってでも、理不尽なことに声を上げてでも。\""
10052115-81 = "[ns] \"ケイが話していたようにね。\""
10052115-82 = "なぜ急に私の話を！？"
10052115-89 = "あ、頭を撫でないでください！#nそんなことされたって……！"
10052115-9 = "……どうして、ソフは連絡してきたのでしょうか？"
10052115-90 = "……こ、今回だけですからね。"
10052115-91 = "……。"
10052115-92 = "私たちが幸せになるべき理由は、それが生に対する最大の闘争であるからだと、そう言いたいのですね。"
10052115-93 = "[s13] \"うん。だから私は、君たちに幸せになってほしいんだ。\"\n[s14] \"そうしたら、私もついでに幸せになれるし。\""
10052115-98 = "ついでに、ですか……？"
10052115-99 = "アリスは……先生にも、先生の幸せがあってほしいです！#n先生の言い方は、どこか悲しく聞こえます……。"
