[translation]
10050020-1 = "第2話;本を大切に"
10050020-100 = "ですので、図書委員会にお願いしようと思った次第です。トリニティ内の書籍の管理は、図書委員会の仕事ですから。"
10050020-101 = "それでウイさんとお話ができればと思っていたのですが……そうですね。"
10050020-102 = "あらためて、よろしくお願いしますね。シミコさん。 "
10050020-103 = "承りました。それで……私たちは具体的に何をしたらいいのでしょうか……？"
10050020-104 = "お話したようにこの書籍の出どころ、流通量、トリニティに与える影響等を調査し……。"
10050020-105 = "この件を、「やさしく穏やかに」解決していただけますか？"
10050020-106 = "……。"
10050020-107 = "なんというか、ナギサ様らしいお言葉ですね。"
10050020-108 = " ……それは、どのような意味で？"
10050020-109 = "あっ、いえ。特に深い意味はありません。"
10050020-110 = "……？ともかく、図書委員会だけでは大変ですので――"
10050020-111 = "正義実現委員会との協力を、許可いたします。"
10050020-112 = "なるほど……本格的に正義実現委員会を動かすのは難しいけど……。"
10050020-113 = "図書委員会と協力するやり方なら#n「不要な誤解」は避けられる、ということですね。"
10050020-114 = "その通りです。ご理解くださり感謝いたします。"
10050020-115 = "先生とシミコさんに、私たちティーパーティーが[ruby=・]正[/ruby][ruby=・]式[/ruby][ruby=・]か[/ruby][ruby=・]つ[/ruby][ruby=・]秘[/ruby][ruby=・]密[/ruby][ruby=・]裏[/ruby][ruby=・]に[/ruby]お願いする案件となります。"
10050020-116 = "使えそうな手は自由に使っていただいて構いません。#nそして「秘密」は、秘密のままに。"
10050020-117 = "分かりました、ナギサ様。"
10050020-118 = "今この瞬間をもって、シミコさんを臨時外部顧問として正義実現委員会にご招待します。"
10050020-119 = "あ、ありがとうございます……。"
10050020-127 = "やっほーナギちゃん、お茶しに来たよ！#nって……あれ、先生！？"
10050020-128 = "ミカさん？"
10050020-129 = "[s] \"こんにちは、ミカ。\""
10050020-13 = "これは一体！？"
10050020-130 = "あっ、うん！こ、こんにちは先生！……来るって分かってたらもうちょっと色々、きれいにしてきたのに。"
10050020-131 = "[s] \"今のミカも好きだよ？\""
10050020-132 = "っ！！？そ、そんなこと言ってもらえるのは、胸がはじけそうなくらい、嬉しいけど……。"
10050020-133 = "（そ、そんな意味なわけないでしょ、しっかりして私！）"
10050020-134 = "やあ、先生。#nはぁ……その言葉に深い意味などないはずだ、それくらい理解しているだろう？ミカ。"
10050020-135 = "セイアちゃんってばもう☆"
10050020-136 = "それよりこの本なあに？初めて見た！"
10050020-137 = "いけません！！！"
10050020-14 = "どど、どうされました！？"
10050020-143 = "[ns] \"な、ナギサ！？\""
10050020-145 = "ビックリしたぁ！？どうしたのナギちゃん、ただの本でしょ！？"
10050020-146 = "し、失礼いたしました、ミカさん。#nですが、この本はその……こ、困りますので！"
10050020-147 = "どうして？"
10050020-148 = "で、ですから……ええと……。"
10050020-149 = "こちらはシスターフッドからティーパーティーを経て、#n図書委員会に依頼された「外典」の一つなのです。"
10050020-15 = "……まだ読んでいないのでしたね。#nまず、お互いの認識を合わせるところから始めましょうか。"
10050020-150 = "ん？シスターフッド……？なら仕方ないかぁ。"
10050020-151 = "あの子たちが関わると色々とややこしいんだよねぇ。"
10050020-152 = "……だが、今のは些か度が過ぎていたのではないか？ナギサ。"
10050020-153 = "ミカさんにこの本は早すぎます！"
10050020-154 = "……過保護もすぎれば毒となるものだよ。"
10050020-155 = "もー！ナギちゃんもセイアちゃんも、なに二人でこそこそしてるの？"
10050020-156 = "というかナギちゃん……今のは流石に品がなかったんじゃないかな？"
10050020-157 = "ミカさんにそれを言われるなんて……なんだかめまいがしてきました……。"
10050020-158 = "ナギちゃん？"
10050020-159 = "[s] \"えっと……たしかに今のはやり過ぎだったかな？\""
10050020-16 = "は、はい……。"
10050020-160 = "そう思うよね！#nやっぱり先生って最高☆"
10050020-161 = "っ……分かりました……申し訳ありませんでした。"
10050020-163 = "ティーパーティーの全員がいらっしゃるとは……#n最後のあれは、私もヒヤヒヤしてしまいました……。"
10050020-164 = "あれ、先生大丈夫ですか？顔色が……。"
10050020-165 = "[s] \"なんというか、胃がチクチクするやりとりだった……。\""
10050020-166 = "ああ……トリニティでは日常茶飯事なので、そのうちに慣れますよ。"
10050020-167 = "もちろん、先生に慣れてください、と言いたいわけではありませんが。"
10050020-168 = "[s] \"あの本のこと、シミコは本当に何も知らないの？\""
10050020-169 = "ええと、それってつまり……。"
10050020-170 = "……。"
10050020-171 = "お察しの通りです。#nこれでも図書委員ですので。"
10050020-172 = "図書委員会は、トリニティで出回るすべての本を把握していますから。"
10050020-173 = "あ、強制されているわけではないんですけどね。"
10050020-174 = "[s] \"どこまで読んだのか聞いてもいい？\""
10050020-175 = "最後までです。"
10050020-176 = "[s] \"潔いっ！？\""
10050020-177 = "まぁ、別に先生にまで隠す必要はないと思いますので……。"
10050020-178 = "……えっ？あれをどう思っているのか、ですか……？#nこれはあくまで、私見ですが……。"
10050020-179 = "「グレーゾーン」の作品だと思っています。#n堂々と人に勧められるようなものではないです。"
10050020-180 = "だからといって盲目的に規制すべきでもないのですが……。"
10050020-181 = "[s] \"そうだね、私もそう思う。\""
10050020-182 = "はい……正直なところ、こういう内容に全く興味がない年頃ではありませんので。"
10050020-183 = "ただ図書委員として感動したのは……そうですね、あの検閲……いえ、編集力でしょうか。"
10050020-184 = "あんなにうまく「切り取る」なんて……本当に感動しました。"
10050020-185 = "ん？すごく落ち着いているように見える、ですか……？"
10050020-186 = "……。"
10050020-187 = "先生。トリニティの「古書館」にはとてもたくさんの本が保管されています。"
10050020-188 = "[s] \"たしかにそうだね。\""
10050020-189 = "その中に……いわゆる「健全ではない本」は、どれくらいあると思いますか？"
10050020-190 = "[s7] \"……？\"\n[s8] \"……なるほど。\""
10050020-193 = "はい、お察しの通りです。"
10050020-194 = "じゃあ図書委員は全員慣れているのか、ですか？"
10050020-195 = "皆さんの名誉のためにも、詳細を話すのは難しいですが……。"
10050020-196 = "少なくとも私は、それなりに。"
10050020-197 = "本という媒体は、情報伝達のために存在します。"
10050020-198 = "果たして、私たちがその情報の伝達価値や資格を評し、等級分けしてよいものでしょうか？#nその権利は一体誰から与えられたのでしょう。"
10050020-199 = "「人」にも権利や資格があるのなら、私は「本」にだってそうあるべきだと思っています。"
10050020-2 = "！？！？！？"
10050020-20 = "なっ、ななっ……！？"
10050020-200 = "だから本も、人と同じだと思えるのだとも。"
10050020-201 = "[s] \"だから本を雑に扱う人は……。\""
10050020-202 = "はい。ムチを打ってでも反省させたほうがいいです。"
10050020-203 = "過ちを犯した人には罪を償わせる必要がありますから。"
10050020-205 = "（……改めてシミコを怒らせてはいけないと実感したのだった）"
10050020-21 = "……これであなたも事の重大さを理解していただけたかと思います。"
10050020-22 = "私が今から話すことを、そのまま実行していただけますか？"
10050020-24 = "先生には私から連絡いたします。"
10050020-25 = "は、はいっ、かしこまりました！"
10050020-29 = "（私は結構好きだったんだけどなぁ……）"
10050020-30 = "（特にあのシーンとか、その後の展開とか……）"
10050020-34 = "[ns1] \"重要なお願い、って言われて来たんだけど……。\"\n[ns2] \"何かあったの？すごい剣幕だけど……。\""
10050020-37 = "ようこそお越しくださいました、先生。#nご多忙のところお時間を頂戴して申し訳ありません。"
10050020-38 = "[s] \"いや、それは別にいいんだけど……。\""
10050020-39 = "本題、ですが……。"
10050020-40 = "トリニティはいま、未曾有の危機にさらされております！"
10050020-41 = "[s] \"なに！？襲撃！？\""
10050020-42 = "ええ、いっその事それならよかったのでしょう。#n自分たちで解決できるのですから。"
10050020-43 = "そう……武力による攻撃ならまだ良いのです。対処法が分かっておりますので。"
10050020-44 = "しかし。内部からトリニティの風紀を乱す攻撃には、対抗手段がありません。"
10050020-45 = "こちらをご覧ください。"
10050020-50 = "[ns3] \"ふつうの本に見えるけど……。\"\n[ns4] \"素朴な表紙のマンガだね。\""
10050020-53 = "はい。どんな本にも言えることですが、重要なのはその中身でしょう。"
10050020-54 = "どうぞ、その手でご覧になってください。"
10050020-59 = "[ns5] （……？特に気になるところはない……）\n[ns6] （トリニティではこういう内容も刺激的なのかな）"
10050020-62 = "これは紛れもなくトリニティの精神と校風を乱し――"
10050020-63 = "逸脱行為を扇動する意図で作られた、非公認の書籍です！"
10050020-70 = "こんにちは、ナギサ様……って、あっ！先生もいらしたのですね！"
10050020-71 = "[s] \"シミコ、こんにちは！\""
10050020-72 = "こんにちは、シミコさん……？#nええと、ウイさんをお呼びしたはずでは……。"
10050020-73 = "……。"
10050020-74 = "いえ、理解しました。シミコさんも大変なのですね。"
10050020-75 = "はい、ナギサ様。ご理解くださりありがとうございます。そういうことです……#nところで、どうかされましたか？"
10050020-76 = "ああ、そうでした。#nこちらの本はご存じですか？"
10050020-77 = "これは……最近トリニティで流行していると噂のものですね。"
10050020-78 = "ええ。それなら話は早いです。#n内容についてもご存知でしょうか？"
10050020-79 = "……。"
10050020-80 = "（知ってはいますが……そう答えてはならないような雰囲気がしますね）"
10050020-81 = "いいえ、内容までは知りません。"
10050020-82 = "そうですか。私もさっきまで知らなかったのですから、当然とも言えますが……。"
10050020-83 = "この本……トリニティの外から来たもので間違いないかと。"
10050020-84 = "はい。トリニティで作られたものでしたら、私たち図書委員会が管理していますので。"
10050020-85 = "ええ。しかし残念ながら今この本の出どころは分かっておりません。"
10050020-86 = "つまり……トリニティを内部から崩壊させようとしている、とある勢力によって……！"
10050020-87 = "一種の精神的攻撃を受けているのです！"
10050020-9 = "な、ナギサ様……？#nナギサ様――っ！？！？"
10050020-91 = "少々論理が飛躍しすぎな気が……先生、どう思いますか？"
10050020-92 = "[s] \"私もそう思うけど、こうなってしまったナギサは……。\""
10050020-93 = "そうですね……。"
10050020-94 = "私たちは、この本の出どころを知る必要があります。#n学園の安全がかかっているのです。"
10050020-95 = "しかしここで問題が……この本がトリニティの外から持ち込まれたと分かった以上。"
10050020-96 = "私たちティーパーティーが全面的に関与するわけにはいきません。"
10050020-97 = "最悪の場合、外交問題に発展する可能性がありますから。"
10050020-98 = "秩序という意味では、正義実現委員会に一任しようかとも思いましたが……。"
10050020-99 = "それでは学園内の雰囲気に影響を与えてしまいます。"
