[translation]
10052100-1 = "ゲブラ：合理を越えた勇猛な仲裁者 "
10052100-10 = "ヒマリ部長には悪いですが……私にとっては、懐かしい環境でもあります。"
10052100-11 = "氷海で突然感知されたデカグラマトンの信号を追い……ゲブラと戦うことになりました。"
10052100-12 = "[s] \"トキにとっては初任務だったんだっけ。\""
10052100-13 = "はい。特異現象捜査部のメンバーとして、初めて先生と一緒に遂行したミッションでした。"
10052100-14 = "加えて、あのときは寒さに凍えていました。#nエイミを見て、気合で我慢していましたが。"
10052100-15 = "どうですか、先生。よく頑張った私を見ていると、褒めたくなりませんか？"
10052100-16 = "[s] \"トキはいつも頑張ってくれてるよね。\""
10052100-17 = "ありがとうございます。でもまだ足りないです。#n私は[ruby=あすま]飛鳥馬[/ruby]トキですので、もっと多くのものを先生に要求します。"
10052100-18 = "……先生。甘やかしすぎるのもよくないですよ？"
10052100-19 = "[s] \"……らしいよ？\""
10052100-20 = "そうですか。仕方ありません。では私は、やや離れたところで1人寂しくしょんぼりしておきます。"
10052100-21 = "あ、あの！今は寒くないんですか……？"
10052100-22 = "はい。このスーツは優れた防寒機能が備わっているので、寒さは問題ありません。#nお気遣いありがとうございます、ユズ。"
10052100-23 = "……はっ！防寒機能が無ければ、それを言い訳にして先生にくっつく事もできたのでは……？私としたことが、なんたる不手際を……。"
10052100-25 = "トキ。そろそろ現場調査を再開しますよ。"
10052100-26 = "ゲブラの起源は、極地研究基地に置かれていた無人探査機だと思われます。#n例によって、そのAIがデカグラマトンによってハッキングされました。"
10052100-27 = "デカグラマトン側の表現を使えば、ハッキングではなく「感化」と言うらしいですが……そこは一旦置いておきましょう。"
10052100-28 = "気になるのは、何をどうすればあそこまで変形できたのか――"
10052100-3 = "……。"
10052100-34 = "ひ、ひぃっ……！？"
10052100-35 = "お出ましですね。"
10052100-39 = "では先生、指揮をお願いします。"
10052100-4 = "なぜまた……氷海のような環境に！？"
10052100-5 = "[s] \"きっと、このエリアだけだから……。\""
10052100-6 = "それは分かっています！怒っているのはゲブラに対してです！#nどうしてここまで寒い環境にこだわるんですか！"
10052100-7 = "こ、コクマーのときもそうでしたし……預言者には、それぞれ好きな地形とか環境があるんじゃないでしょうか……？"
10052100-8 = "なるほど。ヒマリ部長がエイミとクーラーの温度で揉めるのと同じですね。"
10052100-9 = "いつも言っていますが、エイミが極端に寒さを感じないだけですからね？"
