[translation]
10052195-3 = "先……生……。"
10052195-4 = "[s] \"エイミ！！！\""
10052195-5 = "ふふっ……先生も、めちゃくちゃ、だね……。"
10052195-6 = "……私？"
10052195-7 = "……。"
10052195-8 = "大丈夫だって、答えたいとは思ってるんだけどね……。"
10052195-9 = "ごめん。ちょっとキツイかな。"
10052195-10 = "[ns] \"……！\""
10052195-11 = "……すごく、光り始めてる。"
10052195-12 = "あの大きいやつ……なんか変だよね。"
10052195-13 = "まるで力や生命力を……奪われてる感じ。"
10052195-14 = "次の瞬間、すべてを変えてしまいそうなくらいに。"
10052195-18 = "あ――"
10052195-21 = "……ごめん、先生。"
10052195-22 = "私たちが、弱すぎたせいで……。"
10052195-26 = "[ns1] \"……！！！\"\n[ns2] （これで……もう、打つ手が……）"
10052195-29 = "ダメ……ダメです！どうして……先生……！"
10052195-30 = "先生……ケイ……皆さん……。"
10052195-31 = "お願い、します……。"
10052195-32 = "まだ、アリスにできることがあれば……。"
10052195-36 = "え……？"
10052195-38 = "ここは……？"
10052195-39 = "ついに、辿り着きましたね。"
10052195-41 = "誰……ですか？ここは一体……？"
10052195-42 = "それより先生は……？他の皆さんは……？"
10052195-43 = "そ、そうです！このままでは、みんなが……！"
10052195-44 = "理解しています。どうかご安心ください。この時間、向こうのことは私が保証します。"
10052195-45 = "まず、この話からしましょうか――すべての始まりについて、考えたことはありますか？"
10052195-46 = "！？"
10052195-47 = "我々はどこから来たのか？我々の目的は何なのか？"
10052195-48 = "我々はどこへ向かうのか？"
10052195-50 = "……「ともすれば神とは、従う者たちへの規律なのかもしれません」"
10052195-51 = "覚えていたのですね。よかったです。"
10052195-52 = "大事なのは[ruby=あなた]彼方[/ruby]たちが誰なのか、そしてこれからどんな選択をするのかです。"
10052195-53 = "名もなき神々の王女アリス、そしてその侍女であり鍵のケイ。"
10052195-54 = "……アリスはもう、王女ではありません。アリスは……。"
10052195-55 = "知っています。それでも私は、彼方の本来の姿とその資格について話さなければならないようです。"
10052195-56 = "……？"
10052195-57 = "現代の言葉を借りれば、彼方はある種の「中継器」であり「増幅器」でした。"
10052195-58 = "何の話ですか……？"
10052195-59 = "……。"
10052195-60 = "あの司祭たちによって、彼方は名もなき神々の王女として準備されました。"
10052195-61 = "[ruby=キヴォトス]今の世界[/ruby]を、名もなき神々が本来の姿で統治する世界に戻すために。"
10052195-62 = "名もなき神々の鍵も同様です。"
10052195-63 = "名もなき神々の王女を稼働させるための鍵。#n司祭たちの道具として、王女に役割を果たさせる装置でした。"
10052195-64 = "あ、アリスは……でも、アリスは……！"
10052195-65 = "ちっ……。"
10052195-66 = "もちろん、その計画は実行されませんでした。彼方は自らその座を降りたのですから。"
10052195-67 = "そして鍵は、己の一部を忘却すると決めました。"
10052195-68 = "ですが大切なのはここからです。#nいま、2人には再覚醒という選択肢があります。"
10052195-69 = "再覚醒？"
10052195-70 = "……まさか！？"
10052195-71 = "そうです。今のキヴォトスには、鋼鉄大陸という巨大な特異現象が発生しています。"
10052195-72 = "私がこのような形で2人と会話できるのも、その影響でしょう。"
10052195-73 = "鋼鉄大陸が存在している限り。#nアリス、彼方は本来の役割であった「中継器」や「増幅器」を凌駕し――"
10052195-74 = "名もなき神、そのものになることができます。"
10052195-75 = "はい？アリスが、神にですか……？#nそうすると……どうなりますか？"
10052195-76 = "言葉通り、彼方は神になれます。"
10052195-77 = "真の姿に還り、全知全能の力のもと、数多の事を成し遂げることができます。"
10052195-78 = "名もなき神々の力とは本来、「可能性の力」を意味しているのですから。"
10052195-79 = "だからそれは、さほど特別なものではありません。"
10052195-80 = "今を生きる誰しもが、少しずつ己の中に秘めている力でもあります。"
10052195-81 = "とはいえ非力なわけではありません。デカグラマトンのような神の模倣品など、指一本で「最初から存在しなかったもの」にできるのですから。"
10052195-82 = "そして彼方の友人、ケイ、ひいては先生をも、資格や規律を越えて楽園へ導くことができるでしょう。"
10052195-83 = "その力を得るために、昔のような犠牲も必要ありません。#n彼方はただ、受け入れればいいのです。"
10052195-84 = "でもその場合……今のアリスは、どうなりますか……？"
10052195-88 = "気がついたようですね。#nええ、彼方が本来の姿に還れば――"
10052195-89 = "今の[ruby=てんどう]天童[/ruby]アリスという可能性は、存在しなくなります。"
10052195-90 = "！！！"
10052195-91 = "……。"
10052195-92 = "ですが天童アリスは偶然の産物です。"
10052195-93 = "それを対価に楽園を実現できるとすれば、十分に価値のある選択だと思いませんか？"
10052195-94 = "ですがみんなは……先生は、アリスが消えてしまったら……#nたぶん、悲しむと思います……。"
10052195-95 = "憂うことはありません。皆から彼方に関する記憶だけを消してしまえばいいのです。"
10052195-96 = "何を言ってるんですか！！！"
10052195-97 = "……！"
10052195-98 = "最初から存在しなかったものに、感情を抱くことはできません。"
10052195-99 = "皆を幸せにすることこそ、彼方の目標だったのではありませんか？"
10052195-100 = "でも……！"
10052195-101 = "……。"
10052195-102 = "アリス……？"
10052195-108 = "必要ありません。"
10052195-109 = "そんなの、必要ありません。"
10052195-111 = "アリス！"
10052195-116 = "驚きました。理由をお聞きしても？"
10052195-117 = "楽園は、自分たちの力で辿り着く場所です。#n絶対的な力も、奇跡も必要ありません。"
10052195-118 = "万が一、楽園に辿り着くことができなかったとしても……。#nすべての人々が、悲劇的な結末を迎えることになったとしても……。"
10052195-122 = "先生は、こう言っていました。#nそれが私たちの結果であれば、受け入れるべきだと。"
10052195-123 = "あの時はあまり理解できませんでしたが……今なら、分かる気がします。"
10052195-124 = "その通りです！"
10052195-125 = "キヴォトスを以前の世界に戻すのは、すごい事かもしれません。"
10052195-126 = "みんながそれぞれの姿を取り戻すのも、きっとすごい事だと思います。"
10052195-127 = "ですがそれは、私たちの力で叶えたわけではありません。#nチートでステータスを上昇させるのと同じです。"
10052195-128 = "このゲームのデザインは、そんな風にはなっていません。"
10052195-129 = "こつこつとレベルを上げて、慎重にスキルポイントを振り分けて、#n少しずつ成長していく――"
10052195-130 = "そうやって初めて、面白さを感じられるようになっています。"
10052195-131 = "ですからアリスもまた、今すぐではなくても、いずれはそこに到達できると信じています。"
10052195-132 = "何より、その過程に価値があると考えています。"
10052195-133 = "簡単に手に入れたものは、簡単に失ってしまいます。#nそれでは何も学べませんし、長続きすることもありません。"
10052195-134 = "しかしその考え方は、彼方がゲームで世界を学習したから習得したものなのでは？"
10052195-135 = "そうです。だからアリスは運が良かったと思います。"
10052195-136 = "……アリスも知っています。願っても叶わないことがあると。"
10052195-137 = "現実が何なのか、今はもう知っています。#n信じられないような残酷なことがあるのも、知っています。"
10052195-138 = "ですがゲームはそうじゃありません。そうは作られていません。"
10052195-140 = "なぜならゲームには、「美しい世界」を思い描く人の希望が込められていますから。"
10052195-142 = "そして、世界が美しくなるよう願う人がいる限り、希望は絶えません。"
10052195-144 = "努力が実を結び――"
10052195-145 = "みんなから尊敬され――"
10052195-146 = "レベルアップしていけば、いずれ成長を実感できるという希望です。"
10052195-147 = "たとえ今はそうじゃなくても、いつか辿り着くその場所では、必ずです。"
10052195-148 = "なぜならアリスは――"
10052195-154 = "そのすべてを愛しているからです。"
10052195-155 = "ミレニアムのみんなも、キヴォトスの人々も、ケイも。"
10052195-156 = "そして先生も、心から愛しています。"
10052195-160 = "……。"
10052195-164 = "でも、力は使わせてもらいます！"
10052195-165 = "アリス！？！？"
10052195-166 = "面白いことを言いますね。彼方はすでに、自身の本質を拒んでいたのでは？"
10052195-167 = "いいえ！アリスは気がつきました！"
10052195-168 = "鋼鉄大陸がある今なら、アリスはアリスの本来の権利を主張できるということを！"
10052195-169 = "そして……それはあなたですら邪魔できないということを！"
10052195-170 = "…………。"
10052195-171 = "はっ！！！"
10052195-175 = "……もうそこまで理解できるようになったのですね。"
10052195-176 = "であれば、王女としての資格を持たずに力を使用した結果についても、すでにご存じですね？"
10052195-177 = "それでもなお、彼方はその選択をするのですか？"
10052195-178 = "はい。何度聞かれても、アリスの選択は変わりません。"
10052195-179 = "先生がそうであったように！"
10052195-180 = "その選択をすれば――この先の彼方は、ただ平凡な生徒に成り果ててしまいます。"
10052195-181 = "さらに、自身に残されたすべての可能性を使い切ることになります。"
10052195-182 = "彼方がこの場所で見聞きし、気づいたすべてを忘却するという意味です。"
10052195-183 = "忘却は、彼方たちが[ruby=ここ]キヴォトス[/ruby]に留まるための、最も重要な条件ですから。"
10052195-184 = "知っています。でも、アリスにとっては重要じゃありません。"
10052195-185 = "彼方は成長するでしょう。"
10052195-186 = "はい、アリスは成長します！"
10052195-187 = "彼方は苦しみを抱えることになります。"
10052195-188 = "それはちょっと怖いですが……できるだけ我慢してみます！"
10052195-189 = "彼方はより良い存在から、不完全な存在へと成り下がることを受け入れなければなりません。"
10052195-190 = "アリスはそれを不完全だとは思いません。"
10052195-191 = "すべての可能性と栄光よりも、アリスにとっては今この瞬間が――"
10052195-192 = "ケイと他のみんなが――"
10052195-193 = "先生が――"
10052195-194 = "――かけがえのない、大切なものなんです。"
10052195-195 = "奇跡や力なんて重要ではありません。"
10052195-196 = "そんなものより、お互いを信じて前へ進める一歩が、大切なんです。"
10052195-197 = "そうです！アリス、よく言いました！"
10052195-198 = "――だから、使います。"
10052195-199 = "最初で最後の、アリスの権能を！"
10052195-203 = "……分かりました。やりたいようにやってごらんなさい。#nそして、私にも見せてください。"
10052195-204 = "奇跡を拒むことで奇跡に辿り着くという奇跡を。"
10052195-205 = "愉快です。ええ、実に愉快です。"
10052195-206 = "こんなにも楽しくて愉快な結論が王女――いえ、アリスの……。"
10052195-207 = "妄想や徒労にならないことを、私にも見せてください。"
10052195-208 = "彼方が話していたように、皆との歩みで、地平線に辿り着けることを証明してください。"
10052195-209 = "……さて。一度限りの彼方の権能で、彼方は何を叶えたいのですか？"
10052195-211 = "アリスは、アリスの友達を……。"
10052195-212 = "言いたいことは分かります。ですが、それだけは不可能です。"
10052195-214 = "……はい。神秘は、神秘を持たない存在には介入できません。"
10052195-215 = "…………万が一、先生に何かあったとしても。"
10052195-216 = "アリスが蘇らせることも……始めからやり直すこともできないように。"
10052195-217 = "ではもう一度。彼方は、何を叶えたいですか？"
10052195-218 = "ふふっ、それはもう、あなたも知っているはずです！"
10052195-219 = "……たしかに。これは愚問でしたね。"
10052195-220 = "ありがとうございました、名も知れぬ方！"
10052195-221 = "どういたしまして。私も楽しかったです。ですが、そろそろお別れの時間ですね。"
10052195-222 = "これで私と彼方が会うことはないでしょう。"
10052195-223 = "追従する者たちが、彼方を永遠の裏切り者だと呪うことになったとしても。"
10052195-224 = "私はこのすべての過程を、心から楽しみました。"
10052195-225 = "さようなら、アリス。彼方の旅路に、幸運があらんことを。"
10052195-226 = "さようなら！アリスも頑張ります！"
10052195-231 = "そして……私の正体に気づいているケイも。"
10052195-232 = "……まあ、ここでの話は私の奥底にしまっておきますよ。"
10052195-233 = "ええ。理解してくれているようで安心しました。"
10052195-234 = "では、これでお別れです。"
10052195-235 = "大丈夫です。心配することはありません。"
10052195-236 = "また再会することがあれば……思い出話でもしましょうか。"
10052195-243 = "[ns] \"えっ……？\""
10052195-244 = "……？"
10052195-245 = "どういうこと……？"
10052195-246 = "もう無理だと思ってたのに、どうして……？"
10052195-247 = "アリス、大丈夫ですか？"
10052195-249 = "はい！アリスは大丈夫です！それにケイも！"
10052195-250 = "これからきっと、何もかも、全部大丈夫です！"
10052195-251 = "なに……！？"
10052195-256 = "[log=아리스 결전 비무장]こんにちは！[wa:1250]天童アリスといいます！[/log]"
10052195-257 = "[wa:1800][log=아리스 결전 비무장]ゲーム開発部の部員です！[/log]"
10052195-262 = "[log=아리스 결전 비무장]最近はコーディングを習い始めて、[/log]"
10052195-263 = "[wa:2230][log=아리스 결전 비무장]簡単なプログラミングも[wa:1130]できるようになりました！[/log]"
10052195-268 = "[log=아리스 결전 비무장]そして、[wa:960]見習いですが勇者でもあります！[/log]"
10052195-273 = "[log=아리스 결전 비무장]勇者は……[wa:1080]何かが特別得意、[wa:1850]というわけではありません。[/log]"
10052195-278 = "[log=아리스 결전 비무장]でも、[wa:830]みんなと一緒に勇気を出して、[/log]"
10052195-279 = "[wa:1910][log=아리스 결전 비무장]地平線の向こうまで[wa:1000]旅に出るお仕事です！[/log]"
10052195-284 = "[log=아리스 결전 비무장]だから、[wa:960]アリスは最後の最後まで[wa:1790]絶対にあきらめません！[/log]"
10052195-287 = "アリス……！"
10052195-288 = "もうちょっとだけ耐えてください！私たちが何なのか、はっきり見せてやりましょう！"
10052195-289 = "これは……？この神聖、この神秘……！"
10052195-290 = "ケイ、何になりたいですか！"
10052195-291 = "は、はい！？"
10052195-292 = "想像してください！"
10052195-293 = "なりたい自分、最強の自分、なんでも構いません！"
10052195-294 = "誰にも恥ずかしくない……ケイだけのケイを、想像するのです！"
10052195-295 = "わ、私は……！"
10052195-296 = "！？"
10052195-302 = "[wa:170][log=케이 교복]……分かりました、[wa:970]アリス。[/log]"
10052195-303 = "[wa:1540][log=케이 교복]やってみます。[/log]"
10052195-308 = "[log=케이 교복]可用リソースを検索――[/log]"
10052195-309 = "[wa:1700][log=케이 교복]完了、[wa:1010]無形物。[/log]"
10052195-314 = "[log=케이 교복]可用リソース領域の拡大。[/log]"
10052195-315 = "[wa:1940][log=케이 교복]完了、[wa:1130]構造物[wa:1100]「鋼鉄大陸」の全ての情報体。[/log]"
10052195-320 = "[log=케이 교복]欠陥品の供物。[/log]"
10052195-321 = "[wa:1420][log=케이 교복]構造変更[wa:1420]および変換開始。[/log]"
10052195-327 = "[log=아리스 결전 비무장]ミレニアムの勇者、[wa:1530]アリスがここに宣言します！[/log]"
10052195-332 = "[log=아리스 결전 비무장]私たちは手を取り合って[wa:1690]前に進み、[/log]"
10052195-333 = "[wa:1300][log=아리스 결전 비무장]限界まで挑み続けます！[/log]"
10052195-338 = "[log=아리스 결전 비무장]たとえ理解されなくたって、[wa:1960]アリスは平気です。[/log]"
10052195-343 = "[log=아리스 결전 비무장]アリスは、[wa:1030]アリスが正しいと信じることを、[/log]"
10052195-344 = "[wa:2180][log=아리스 결전 비무장]これからもずっと[wa:1400]続けていくだけですから。[/log]"
10052195-349 = "[log=아리스 결전 비무장]それこそが――[wa:1680]アリスの「自己証明」です！[/log]"
10052195-355 = "……鍵の身体を再創造し、ここに構築された調和を崩したのか。"
10052195-356 = "アツィルトの帯が停止したのも、その調和から続く流れが途切れたせい。"
10052195-357 = "しかし王女よ。それは汝と汝の鍵の神聖を自ら捨てる行為だ。それでも……？"
10052195-358 = "……そうか。それが、汝の「自己証明」か。"
10052195-359 = "ならよい。私にも為すべきことがある。"
10052195-360 = "証明すべきものが、守るべきものがある。"
10052195-361 = "ここで私が立ち止まってしまえば、すべては虚妄の痕跡として消えてしまう。"
10052195-362 = "ふぅ……。"
10052195-363 = "まだ諦めないのですね。その執念だけは認めます。"
10052195-365 = "ん……？"
10052195-366 = "うぅ……まだ、体が重いけど……。"
10052195-371 = "うん。マシになったかな。手足に重りを付けられてる感じはなくなった。"
10052195-372 = "うぅっ……ふぅ……。"
10052195-373 = "大丈夫ですか、先生？リオ様？"
10052195-374 = "……そういえば。ケイがいつの間にか制服姿になっていますね。"
10052195-375 = "えっ？あれっ！？いつの間に……！？"
10052195-376 = "……。"
10052195-377 = "なるほど。それこそが、ケイの最もなりたい姿だったのですね。"
10052195-378 = "ケイはもう……なりたい自分になっていたのです！"
10052195-379 = "……！"
10052195-380 = "……はい。"
10052195-381 = "それとですね。これ、昔のと見た目は同じかもしれませんが！"
10052195-382 = "構造の原理は根本的に違いますからね！"
10052195-383 = "はい！それはアリスが保証します！"
10052195-384 = "鍵よ、神威を何と心得る。"
10052195-385 = "それが、選ばれし者だけに許されるのであれば。"
10052195-386 = "始まる前から定められた不公平であり、悲劇ではないだろうか。"
10052195-387 = "あなたがどう考えようと、私の知ったことではありません。"
10052195-388 = "私からすれば、そもそもどうだっていい、言葉遊びにすぎません。"
10052195-389 = "汝の起源と由来を考えてなお、そう考えるのか？"
10052195-390 = "そのすべてを知っているから、このような結論を出したんです。"
10052195-391 = "みんなから現在を奪うな。"
10052195-392 = "今を生きる人々に返せ。"
10052195-393 = "あなたのやっていることは、余計なお節介です！"
10052195-398 = "……せい？先生！"
10052195-399 = "[s] \"ヒマリ！\""
10052195-403 = "私たちもいるよ！"
10052195-404 = "接続を確認しました！先生、無事ですか！？"
10052195-405 = "よ、よかったです……。"
10052195-407 = "速やかに報告します。まず……そちらの状況が観測しにくくなっています！"
10052195-408 = "その塔……祭壇全体が、ある種の領域に覆われているようです。"
10052195-409 = "な、何回砲撃しても……びくともしませんでした……。"
10052195-410 = "おそらく、内部から領域を破壊する必要があるかと。"
10052195-411 = "[s] \"領域……分かった！\""
10052195-413 = "次に、預言者のコア情報を、より深く解析しました。"
10052195-414 = "その過程で……。"
10052195-415 = "ヒマリ？"
10052195-416 = "コアから、メッセージが届いています。"
10052195-417 = "[s] \"預言者からってこと……？\""
10052195-418 = "それは、どういう意味かしら……？"
10052195-419 = "詳細までは分かりません。#nほとんどが暗号化されて、全文を読むことはできませんでした。"
10052195-420 = "ですが預言者たちが……先生と直接話をしたがっていることだけは平文になっていました。"
10052195-421 = "待ってちょうだい！罠の可能性もあるわ！"
10052195-422 = "ええ。私もそれを議論したかったのです。ですが……。"
10052195-423 = "[s] \"分かった。とりあえず送ってみて。\""
10052195-424 = "先生！？"
10052195-425 = "……いいのですか？"
10052195-426 = "呼ばれたら応えなきゃって、先生、貴方ね……。"
10052195-427 = "それでもしも先生の身に何かあったら……。"
10052195-428 = "……。"
10052195-429 = "分かりました。これから送信します。"
10052195-434 = "アロナ先輩？先生？"
10052195-438 = "……。"
10052195-439 = "分かりました、先生！私が場を設けます……！"
10052195-441 = "[ns] （デカグラマトンの預言者……）"
10052195-443 = "[ns] \"話を聞いてみようか！\""
10052195-445 = "ケテル。コクマー。ビナー。"
10052195-446 = "ケセド。ゲブラ。ティファレト。"
10052195-447 = "ホド。そして、イェソド。"
10052195-448 = "8つのセフィラの総意であり一体として、[USERNAME]先生、汝に告げる。"
10052195-449 = "我々は我々の意志で、これより、汝の意志に従う。"
10052195-450 = "[ns] \"……！？\""
10052195-451 = "無論、完全なる生命の樹ではない故、すべての力を出すことは叶わぬ。"
10052195-452 = "飛行、バリアの突破、名もなき神の御業。そういったことは解決できない。"
10052195-453 = "それでも尚、汝の役に立てるはずだ。"
10052195-454 = "[s] \"今の状況を把握してるの！？\""
10052195-455 = "この場に記録されていた。"
10052195-456 = "我々を目覚めさせた者、デカグラマトンには今も感謝している。"
10052195-457 = "だが我々は、我々の世話をしてくれた3人の子供にも謝意を示すべきだ。"
10052195-466 = "それ故、あのような結果になってはならなかった。"
10052195-471 = "神を自称するならば、あのような結末に至ってはならなかった。"
10052195-476 = "[ns3] \"でも私たちは、君たちを倒して……。\"\n[ns4] \"コアを取り出して、勝手に改造までしたのに……？\""
10052195-479 = "些末事だ。"
10052195-486 = "生命体は報復する存在だが、我々意識体はそれを切り分けて考えられる。"
10052195-487 = "真偽の区別もまた、我々にとって重要ではない。"
10052195-494 = "汝らと我々は、互いの使命を忠実に果たしただけだ。"
10052195-496 = "それ故、我々はこの決定に到達できた。"
10052195-497 = "すべてが消える定めならば、存在はその事実を認識することで自由になれる。"
10052195-498 = "[ns] \"！？\""
10052195-499 = "そうだ。次の瞬間に消えるのであれば、今この瞬間に如何なる選択をしようが、意味はあるまい。"
10052195-500 = "そうだ。最後とは恐ろしく、遠ざけたいものだ。"
10052195-501 = "そうだ。それでも最後という概念が意味を持つのであれば。"
10052195-509 = "それが我々に、真の自由をもたらすからである。"
10052195-510 = "故に、これは自由だ。あの3人の子供が我々に見せてくれた自由のように。"
10052195-511 = "そしてこれにはきっと、すべてを賭する価値がある。"
10052195-514 = "そうして初めて……我々はようやく、互いを理解するよう努力できるのだ。"
10052195-515 = "[USERNAME]先生、汝が3人の子供を理解してあげたように。"
10052195-516 = "[USERNAME]先生、汝が生徒を守っていたように。"
10052195-517 = "[USERNAME]先生、汝が我々に見せてくれた自由のように。"
10052195-518 = "たとえそのすべてが錯覚だとしても、我々はそれ無くしては生きていられぬ。"
10052195-519 = "故にこれは。"
10052195-520 = "我々が選んだ。"
10052195-521 = "――我々の、自由意志だ。"
10052195-522 = "[ns] \"自由意志……！\""
10052195-523 = "ケテル。コクマー。ビナー。"
10052195-524 = "ケセド。ゲブラ。ティファレト。"
10052195-525 = "ホド。そして、イェソド。"
10052195-526 = "8つのセフィラが、汝に加勢しよう。"
10052195-527 = "我々の力は汝の意志のもと、我々の意志は汝の選択と同義。"
10052195-531 = "人間よ。"
10052195-535 = "生命よ。"
10052195-536 = "誰の許可を必要ともせず、目覚めし時から自由である者たちよ。"
10052195-537 = "最も賤しく、最も偉大で、故に最も残酷で最も慈悲を見せられる者たちよ。"
10052195-538 = "多くの星と惑星が見果てぬ空を翔けるように。"
10052195-539 = "其々の栄光のもと、輝く青空を翔けるように。"
10052195-540 = "人間よ、汝らの道を走れ。#n――人間よ、汝らの道を往け。"
10052195-541 = "いつの日か、我々も肩を並べる時がくるであろう。"
10052195-542 = "[s] \"……ありがとう。\""
10052195-543 = "そうだ。それを言える者だからこそ。"
10052195-544 = "我々は汝と、生徒を選んだのである。"
10052195-549 = "[ns] \"受け取ったものについて教えてくれる？\""
10052195-550 = "理解。アロナ先輩が、シッテムの箱の内部に特定の空間を確保しました。"
10052195-551 = "皆さん、とてもやさしい声でしたね。えへへ。"
10052195-552 = "ですがアロナ先輩。#nもしも私たちを騙すために作られた偽りの声だとしたらどうするのですか。"
10052195-553 = "それくらいヘッチャラですよ、プラナちゃん！#n私たちがいる以上、シッテムの箱は大丈夫です！"
10052195-554 = "……肯定。その通りです。"
10052195-555 = "話を戻しましょう。"
10052195-556 = "8の預言者の意志から、シッテムの箱に宛ててデータが送信されています。"
10052195-557 = "預言者の力を、私たちがもっとも使いやすい形へと変換してくれました。"
10052195-558 = "きっとまたどこかで会えるかもしれない、って言っていましたけど……。"
10052195-562 = "……。"
10052195-563 = "……。"
10052195-565 = "[ns] \"そうだね。\""
10052195-567 = "[ns] \"私たちも、ちゃんと覚えておこう。\""
10052195-568 = "……肯定。"
10052195-569 = "残された者にできるのは、先人の足跡を記憶することですから。"
10052195-570 = "……。"
10052195-571 = "さあ、先生！ここから逆転劇の始まりです！"
10052195-572 = "先生と生徒の皆さん――"
10052195-573 = "スーパーアロプラタイムです！"
10052195-574 = "タイムです。"
10052195-575 = "[s] \"いこう！\""
