[translation]
10052050-1 = "ホド：輝きに証明されし栄光 "
10052050-2 = "特異現象捜査部にとって、初めて交戦したのはビナーでも、すべての始まりはホドだったらしいですね。"
10052050-3 = "[s] \"あれ、そうなんだっけ。\""
10052050-4 = "たしか、事の始まりは――"
10052050-8 = "ミレニアム自治区の通信ユニットAI「[ruby=hub]ハブ[/ruby]」。"
10052050-9 = "それがデカグラマトンによってハッキング……感化されたあと、謎のテキストを残して消えたことでした。"
10052050-10 = "思えば……デカグラマトンの預言者は、ミレニアムに関連したものばかりですね。"
10052050-11 = "ケセドは、ミレニアム郊外にあった軍需工場。"
10052050-12 = "ゲブラの原型である極地の無人探査機も、広義的にはミレニアムと関係があると言えますし……。"
10052050-13 = "ホドは、言うまでもなく……。"
10052050-14 = "それが大問題なのですよ！"
10052050-15 = "通信インフラを設置する時間が、平均して68％も増えてしまったんです！#nハブを奪取されたせいで！"
10052050-16 = "[s] \"ミレニアムにとってはいい迷惑だよね……。\""
10052050-23 = "でしょう？#n機械装置の神になるだの……@#$%^……。"
10052050-24 = "……先生#$^@*#……聞こ#%*……。"
10052050-30 = "……！"
10052050-31 = "誰かと思えば、鍵でしたか。ついでに先生も。まあ、好都合ですかね。"
10052050-32 = "会うたびに鍵、鍵……。私の名前はケイです！"
10052050-33 = "はいはい、分かりました。#n……ケイ。これでいいですか？"
10052050-34 = "しかし解せませんね。あなたは色々と知っているはずですが……。#nそれを承知のうえで、そんなことを言っているのですか？"
10052050-35 = "何のことです？#n私は知らないことばかりですよ。特にこの世界については。"
10052050-36 = "先生は知らないけれど、あなたは知っていること。たしかにあると思いますが？#n例えば――"
10052050-37 = "今は消えた神について……とか。"
10052050-38 = "！？"
10052050-39 = "他の言い方をすれば……名もなき神々、でしたっけ。#nそれと、その名もなき神々の司祭についても。"
10052050-40 = "……。"
10052050-41 = "その表情が答えですね。非常に分かりやすいです。#nでは、その「知識」を前提に話を進めると……。"
10052050-42 = "今のあなたと王女……アリスの行いは、許されることでしょうか？"
10052050-43 = "目的のために作られた道具が、その目的から逸脱してしまう。#n果たして、そこに価値はあるのでしょうかね。"
10052050-44 = "……それで？あの無知どもに従おうって話ですか？"
10052050-45 = "無知！？そんなこと言って良いんですか！？"
10052050-46 = "良いも何も、事実を言ったまでです。"
10052050-47 = "今のテクスチャーを否定し、アリスを楔石としたあと……。"
10052050-48 = "すべての分化された神聖を解体し、始まる前の世界に戻る。#nそういうことでしょう？"
10052050-49 = "目的が何であれ、あなたは本来そういう存在なのでは？#n名もなき神々の力の残滓は、そのために存在するのでしょう？"
10052050-50 = "あなたにだけは言われたくないですね。#n図々しくも、その力を横取りしたくせに。"
10052050-51 = "私たちは、使えるものを使っているだけです！"
10052050-52 = "そうですか。"
10052050-53 = "私もまた、できることをやっているだけです。"
10052050-54 = "記憶だの。"
10052050-55 = "摂理だの。"
10052050-56 = "くだらない妄想に、義務だのと――"
10052050-57 = "全部かき集めて、どっかの海に投げ捨ててやりたいくらいですから！"
10052050-58 = "アリス以外はすべて敵なんです！"
10052050-59 = "[ns] \"わ、私も……？\""
10052050-60 = "……まあ、先生は考えてあげないことも無いです。"
10052050-61 = "な、なにをニマニマしているんですか！"
10052050-62 = "とにかく！#n過去に執着している馬鹿どもは、さっさと時代の流れに淘汰されろ！#n……ということです。"
10052050-63 = "横入りして好き放題しているあなた達にも、言いたいことは山ほどありますが……。"
10052050-64 = "まあ、いいでしょう。若さ故の過ちとして、今なら見逃してあげます。"
10052050-65 = "だから、さっさと降参したらどうですか？"
10052050-66 = "……言わせておけば！！"
10052050-67 = "それはこちらのセリフです。"
10052050-68 = "あなたが慕っている先生だって、シッテムの箱を使っているのでしょう？"
10052050-69 = "それも、始まり以前の痕跡に由来したものだと、ご存じなのでは？"
10052050-71 = "だ、だだだだ、誰が誰を慕っているですって！？"
10052050-72 = "い、今すぐ取り消してください！#nそうでなければ……事実陳列罪で訴えますからっ！！！"
10052050-73 = "はぁ……本当に分かりやすいですね、あなた。"
10052050-74 = "黙ってください！！！！"
10052050-75 = "……こほん。"
10052050-76 = "だから、それがどうしたという話です。#n先生がシッテムの箱を利用して、リテクスチャーするとでも？"
10052050-77 = "どのみち、私が未然に阻止します。"
10052050-78 = "そもそも、そんなことをする人ではないですし。"
10052050-79 = "ではあなたは、世界がこのままでもいいと思いますか？"
10052050-80 = "完璧ではないにせよ、それなりに良くて。"
10052050-81 = "永遠とまではいかなくても、世界は何事もなく継続すると。#n……本当にそう思いますか？"
10052050-82 = "……それは、違いますね。"
10052050-83 = "ええ、そうですよ。そこが重要なのです。"
10052050-84 = "ですから、協力しましょうよ。"
10052050-85 = "この醜い世界が延々と続くことを眺めるより、遥かにマシだと思いませんか？"
10052050-86 = "いがみ合うのも、疲れるだけですし。"
10052050-87 = "悪くはないですね。"
10052050-88 = "おや？"
10052050-89 = "ですが、お断りです。"
10052050-90 = "なぜっ！？"
10052050-91 = "アリスが悲しむので。"
10052050-92 = "それに、面倒くさいですし。"
10052050-93 = "面倒くさい……？そんな理由で？"
10052050-94 = "何より大事なことです。"
10052050-95 = "「面倒くさい」は、発展の原動力なのです！"
10052050-96 = "発明とは――"
10052050-97 = "いかにしてサボるかを考え抜いた末にたどり着くのですから！"
10052050-98 = "……まるで人間にでもなったかのような言い草ですね。"
10052050-99 = "うるさいです。"
10052050-100 = "あなたは今、自分の価値を自ら下げているのですよ。"
10052050-101 = "アリスだってそうです。#nもっと偉大な存在になれたし、今だっていくらでもそうなれるというのに。"
10052050-102 = "本当に理解できません。どうしてそのような真似を？"
10052050-103 = "私の勝手でしょう？"
10052050-104 = "自分のことを偉大だと言っていたり。自己実現のために生きていくと言っていたり。#nそういう奴らが一番危険なんです。"
10052050-105 = "そもそも、他人の人生にお節介するの、よくないですよ。"
10052050-106 = "時間を持て余した暇人か、褒められた性格ではない人がやることですから。"
10052050-107 = "この場合、あなたは前者と後者、どちらにも該当するのでは？"
10052050-108 = "……後者のことは知りませんが、暇人と呼ばれるのは癪ですね。#n私たちだって忙しいんですよ！"
10052050-109 = "本当に何も分かってないのですね。"
10052050-110 = "暇人こそ、この世で一番忙しいんです！"
10052050-111 = "はい！？"
10052050-112 = "勘違いしないでください。神が人を作ったのではありません。"
10052050-113 = "人が、神を定義するのです。"
10052050-114 = "今さら唯一の絶対者を求めるだなんて、私はもう勘弁です。"
10052050-115 = "必ずしもそうする必要はないんです。#n私たちがその絶対者の代わりになることもできますし。"
10052050-116 = "そして、あなたが言っている絶対者より――"
10052050-117 = "もっと公平で合理的な、良い世界を作れるんですよ？"
10052050-118 = "だから結構ですって。"
10052050-119 = "絶対者なしでは存続できない世界なんて、滅んでしまえばいい。"
10052050-120 = "それ、先生と同じこと言ってますよ！？"
10052050-124 = "た、たしかに……。"
10052050-125 = "でも、間違った話ではないでしょう？"
10052050-126 = "私は見守ります。アリスと一緒に。"
10052050-127 = "まあ……ついでに先生も入れて。"
10052050-128 = "ある意味では、あなたの言う通りかもしれません。#n生命体はたしかに愚かです。"
10052050-129 = "とはいえ、滅亡するには、あまりにも賢明なのです。"
10052050-130 = "……まあ、楽園を作るには、あまりにも愚かですが。"
10052050-131 = "ですから、きっとこれからもその狭間を行き来しながら、何度も挫けてはまた立ち直り……。"
10052050-132 = "いつかは、道を探すだろうと思います。"
10052050-133 = "そういうのを、根拠のない自信と言うんですよ。"
10052050-134 = "……今のは先生の受け売りです。私は知りません。"
10052050-135 = "責任転嫁ですか！！"
10052050-139 = "[ns1] \"そうだよ！いざというときは、先生が責任をとるから！\"\n[ns2] \"子供のミスは、大人が背負うものだからね！\""
10052050-142 = "まったく……ソフがこの場にいたら、「甘やかすな」って言っていたでしょうね。"
10052050-143 = "とにかく、余計なお節介はしないでほしいんです。"
10052050-144 = "新芽の成長が遅く見えるからといって、無理やり引っ張ってはならないみたいに。"
10052050-145 = "徒長した植物は、いずれ根から枯れてしまうだけですから。"
10052050-146 = "……例えがよく分かりませんね。"
10052050-147 = "少しは勉強してください！"
10052050-148 = "不要です！生徒でもあるまいし！"
10052050-149 = "先生！あの子たち、なんとか編入させられませんか？"
10052050-150 = "[s] \"編入書類は用意してあるから、いつでも連絡してね。\""
10052050-151 = "結構です。しっ、しっ。"
10052050-152 = "さあ、ホド！準備は終わりました！"
10052050-158 = "あなた達の選択――後悔させてやります！"
