[translation]
10052140-1 = "慈悲"
10052140-10 = "あ、あわ、あわわわ……！！！"
10052140-11 = "う、嘘でしょう……！？そんな……！"
10052140-16 = "……。"
10052140-17 = "警報切って。"
10052140-19 = "警報、出力中止。"
10052140-24 = "ソ、ソフ……？"
10052140-25 = "いいのですか！？"
10052140-27 = "これくらい、何の影響もないよ。"
10052140-28 = "違う？"
10052140-30 = "……。"
10052140-31 = "ま、まあ……。"
10052140-32 = "アイン、準備の進捗はどう？"
10052140-33 = "も、もうすぐ終わります！"
10052140-34 = "お、両方ですか？"
10052140-35 = "はい！"
10052140-37 = "そっか。じゃあ……。"
10052140-38 = "どうするつもりですか？"
10052140-39 = "どうするもなにも。すぐそこまで来てるんだから。"
10052140-40 = "歓迎挨拶くらいはしてあげないとでしょ？"
10052140-41 = "……。"
10052140-42 = "たしかに。まだコアは2つ、こちら側にありますし。"
10052140-43 = "奪われたコアだって、取り戻せます。"
10052140-44 = "そういうこと。"
10052140-45 = "では、ソフ……行くのですね？"
10052140-46 = "直接、顔を拝みに行くよ。"
10052140-48 = "わ、私も行きますか……？"
10052140-49 = "アインはここに残ってて。"
10052140-50 = "私たちのことより、アインの作業のほうが大事だから。"
10052140-54 = "は、はい……！"
10052140-56 = "中央のネツァクのエリアを除く、鋼鉄大陸の全エリアの奪取に成功しました。"
10052140-57 = "まさか……本当にできちゃったね……。"
10052140-58 = "正しく手順を踏めば、概ねは最終目標までたどり着くものよ。#nそこまで驚くことでもないわ。"
10052140-59 = "それって、もしも順番通りに進まなかったら……？"
10052140-60 = "その時は……。"
10052140-61 = "鋼鉄大陸に覆われたキヴォトスで、どうやって生きてくか悩んでたかも？"
10052140-62 = "は、はい……！？"
10052140-63 = "終わりよければすべてよし、という言葉もあります。#n今は上手くいったので、すべてよしです。"
10052140-64 = "そんな大雑把な……。"
10052140-65 = "限りなく不可能に近いことを成し遂げたのですよ？"
10052140-66 = "ゼロではない限り、可能性は閉ざされないわ。"
10052140-67 = "アリスは心配していませんでした！#n先生とみんなが居てくれました！それに、リオ会長も！"
10052140-68 = "わ、私……？"
10052140-69 = "はい！「光落ち」です！"
10052140-70 = "あれ？それだと……リオ先輩はもともと敵だったということになってしまいます……！"
10052140-71 = "ごめんなさい、リオ先輩！そういうつもりでは……！"
10052140-72 = "気にしていないわ。それにあのときの私は……そういう側面もあったもの……。"
10052140-76 = "ありがとうございます、リオ先輩！"
10052140-81 = "すべての始まりについて、考えたことはありますか？"
10052140-82 = "！？"
10052140-84 = "例えば、こういう質問があるとします。"
10052140-85 = "……！"
10052140-90 = "我々はどこから来たのか？"
10052140-91 = "我々の目的は何なのか？"
10052140-92 = "我々はどこへ向かうのか？"
10052140-94 = "ケイ……！"
10052140-95 = "はい、私も聞こえています。"
10052140-97 = "ともすれば神とは、従う者たちへの規律なのかもしれません。"
10052140-101 = "アリス？ケイ？どうかしましたか？"
10052140-105 = "え？あ、そ、それが……！"
10052140-106 = "いえ、何でもありません。大丈夫です。"
10052140-107 = "あ、ありがとうございます、ケイ……。"
10052140-108 = "こういう時のための私ですから。"
10052140-109 = "でも……あれはどういう意味だったのでしょう？#nケイは何か知っていますか？"
10052140-110 = "……詳細までは分かりません。"
10052140-111 = "おそらく、私たちの始まりと……関係しているのだと思います。"
10052140-113 = "みんな、気をつけて。何かが近づいてきてる。"
10052140-120 = "……。"
10052140-121 = "……。"
10052140-122 = "[s1] \"ソフちゃん！オウルちゃん！\"\n[s2] \"アインちゃんは一緒じゃないの？\""
10052140-125 = "……呆れた。"
10052140-126 = "げっ……。"
10052140-128 = "ダメだよ。挨拶には挨拶を返さないと。"
10052140-129 = "のんきに挨拶を交わす仲になった覚えはありませんよ、[ruby=いずみもと]和泉元[/ruby]エイミ。"
10052140-130 = "その呼び方は長すぎて効率的じゃないよ。これからはエイミって呼んで。"
10052140-131 = "……はい？"
10052140-132 = "エイミ。"
10052140-133 = "いや、ですから……。"
10052140-134 = "エイミ。"
10052140-135 = "……分かったよ、エイミ。"
10052140-136 = "うん、よくできました。"
10052140-137 = "……。"
10052140-138 = "8人の預言者に勝って、ネツァクの支配権をほとんど持っていったのは……#n正直、すごいとは思うよ。"
10052140-140 = "……ちっ。"
10052140-141 = "提案があるのですが、過去は水に流して編入して来ませんか？"
10052140-142 = "先生に再確認したところ、今なら選り取り見取りだそうです。"
10052140-143 = "もちろん、どこを選ぶかは皆さんの自由です。#nキヴォトスは数千の学園が集まる、巨大な学園都市――"
10052140-144 = "皆さんには、数千の可能性があるとも言えます。"
10052140-145 = "ですがやはり、私はミレニアムサイエンススクールをおすすめします。"
10052140-146 = "何度言わせれば気が済むんですか。必要ありません。"
10052140-147 = "今なら特別に、リオ様が直々にデザインした記念品ももらえます。"
10052140-148 = "え……？そんなものを準備した覚えはないのだけれど……。"
10052140-149 = "話を合わせてください！"
10052140-150 = "わ、分かったわ……。"
10052140-151 = "とにかく、キヴォトス――特にミレニアムは、どんな生徒でも歓迎しますよ？"
10052140-152 = "いや、本当に要らないんだって。"
10052140-153 = "（こんな会話をしてると情けなくなってくるけど、アインのために時間稼ぎをしなきゃいけないし……）"
10052140-154 = "[s] \"私はみんなのことを諦めないからね。\""
10052140-155 = "私たちも考えは変わりませんよ。#nそもそも毎回その話題じゃないですか。話のレパートリー少なすぎませんか？#nとはいえ、これといって話したい話題なんて、お互い無いと思いますが。"
10052140-157 = "え？じゃあ何しに来たの？"
10052140-158 = "どちらかというと、いつもそちらが話をしに来ているような……。"
10052140-160 = "うっ。"
10052140-162 = "そ、それは、その……！"
10052140-163 = "まあ、ここまで来たんだし？#nだから顔くらい見ておこうかなって。それだけ！"
10052140-164 = "[s] \"そっか、良い子たちだね。偉い偉い。\""
10052140-165 = "ではせっかくですし、もう少し交流を深めてみましょう。"
10052140-166 = "これ以上何をさせようって言うんですか。#n下手なことをして、情が移りでもしたら困るのはあなた方では？"
10052140-167 = "あら、私はすでに移っていますよ？"
10052140-168 = "それ本気？あんた達にとって私たちは、世界を金属で覆いつくそうとする――#n正体不明の悪党なんだよ？"
10052140-169 = "子供のいたずらみたいなものだよ。#n今からでも学園に行って勉強すればいいんだよ。"
10052140-170 = "ええ、その通りです。まだ色々と未熟な時期でしょうからね。"
10052140-171 = "……まあ、年を重ねても未熟なままの人もいますが。"
10052140-172 = "ひ、ヒマリ先輩……！"
10052140-173 = "大丈夫ですよ。"
10052140-179 = "誰の話かしら？あの子たち……ではなさそうだけど……。"
10052140-180 = "……ほら、見ての通り。"
10052140-181 = "は、はい……。"
10052140-182 = "[s] \"とにかく、人は勉強すべきなんだからね。\""
10052140-183 = "そもそも人ではないのですが。"
10052140-184 = "[s] \"人だよ。分別を弁えて、礼儀を知れば、何も違いはない。\""
10052140-185 = "なんか勘違いしてるみたいだから教えてあげるけどさ、私たちは知識なんて最初から全部プログラミングされてるからね？"
10052140-186 = "……どうせ人間じゃないんだから。"
10052140-187 = "[s3] \"全部知ってるつもりになるのは――\"\n[s4] \"まだ知らないことが多い証拠だよ！\""
10052140-191 = "先生のおっしゃる通りです。学びに終わりはないという言葉もあります。"
10052140-192 = "ですので先生。#n学園に帰ったら、ここで過ごした時間分の個別指導をお願いします。"
10052140-193 = "それが、先生としての義務ではありませんか？"
10052140-194 = "それ……本当に勉強のためですか？"
10052140-195 = "アリスも一緒に勉強したいです！"
10052140-196 = "そ、それは……。"
10052140-197 = "分かりました。かわいいアリスの頼みなら仕方ありません。"
10052140-198 = "なに？この茶番……。"
10052140-199 = "……。"
10052140-200 = "とにかく、だからあんた達はいつも後悔するんだよ。"
10052140-201 = "すべてを自分本位に変えておきながら、「こんなことになるとは思わなかった」とか「そんなつもりじゃなかった」とか言って。"
10052140-202 = "その対象が他人であろうが、自然であろうが、世界そのものであろうが。"
10052140-203 = "すべてを滅茶苦茶にしておいて、責任を取る素振りすら見せない。"
10052140-204 = "そんなことやってて、悔いは残らないの？"
10052140-205 = "過去に戻って、もう一度やり直したいとか思わないわけ？"
10052140-206 = "[s] \"……後悔なんてたくさんあるよ。\""
10052140-207 = "……。"
10052140-208 = "[s5] \"もしもチャンスがあれば、次こそは！って。\"\n[s6] \"誰だって思ったことはあるんじゃないかな。\""
10052140-211 = "……。"
10052140-212 = "[s] \"でも後悔は残っても、過去に戻りたいとは思わない。\""
10052140-213 = "……どうしてですか？"
10052140-214 = "[s] \"前へ進むために、過去を顧みるのだから。\""
10052140-215 = "……！"
10052140-216 = "[s7] \"最後まで歩き抜くために。\"\n[s8] \"これまで歩んできた道のりを振り返るんだよ。\""
10052140-220 = "[ns9] \"先人の後を継いで道を切り開くことこそ――\"\n[ns10] \"私たちの生き方だから。\""
10052140-223 = "……！"
10052140-224 = "人間の、生き方……。"
10052140-225 = "じゃあ、私たちは……？"
10052140-226 = "……。"
10052140-231 = "アイン？そこにいますか？"
10052140-235 = "は、はい！お姉様！"
10052140-236 = "ごめんなさい。アインには負担をかけてしまいました。#nですが、我は確かに生まれ変わっています。"
10052140-237 = "こ、こちらこそ、ご、ごめんなさい！私たちが弱いあまり……結局、お姉様の手を借りてしまって……！"
10052140-238 = "いいえ。我も姉として、アイン、ソフ、オウルに頼られて嬉しく思います。"
10052140-239 = "皆の力になれて、本当に、嬉しいのです。"
10052140-240 = "は、はい……！"
10052140-241 = "……。"
10052140-242 = "ソフ、オウル。き、聞こえますか？ま、まだ大丈夫です……。"
10052140-243 = "私たちはまだ――負けません！"
10052140-244 = "[ruby=Daath]ダアト[/ruby]の準備が終わりました！#nもうすぐそちらへ向かいます！"
10052140-251 = "そっか。"
10052140-252 = "じゃあ……！"
10052140-253 = "ええ。"
10052140-254 = "時間稼ぎは十分です。"
10052140-258 = "さあ――聞け！"
10052140-259 = "壊れたものは直せばいい！穢れた神聖には再び光を灯せばいい！"
10052140-260 = "私たちはまだやり直せます！あなた達が諦めないのと同じように！#nえっと、それと――"
10052140-261 = "広がる可能性！"
10052140-262 = "知識を通じた悟り！"
10052140-264 = "コクマーの知恵！ゲブラの勇気！"
10052140-265 = "不離一体から差し込む無形の影！！！"
10052140-270 = "あの子たち、何をやっているのでしょうか？"
10052140-271 = "あれは……まさか！？"
