[translation]
10052155-7 = "う、嘘です……こんなの、あり得ませんっ……！"
10052155-8 = "どうして……？どうすればいいの……？#nこのままじゃ計画が……！"
10052155-13 = "……え？"
10052155-15 = "この信号は――まさか！？"
10052155-20 = "お、お待たせしました……もう大丈夫です！"
10052155-21 = "お姉様が出撃します！！！"
10052155-28 = "お姉様！！！！"
10052155-29 = "ごめんなさい。アイン、ソフ、オウル。"
10052155-30 = "ここからは、我に任せてください。"
10052155-44 = "きゃああああああぁぁぁぁっ！？！？"
10052155-45 = "ユズ、緊急脱出して！"
10052155-46 = "ど、どうやってですか！？！？"
10052155-47 = "こちらからやるわ！#n強制脱出装置――稼動！"
10052155-49 = "え、ええ……！？"
10052155-54 = "きゃああああぁぁぁぁっ！？！？"
10052155-61 = "ネオアバンギャルド君――大破！#nユズは……！？"
10052155-62 = "大丈夫、無事に脱出したわ。パラシュートも開いている。"
10052155-68 = "うううぅぅぅ……。"
10052155-72 = "ユズ！"
10052155-73 = "ユズちゃん！"
10052155-75 = "大丈夫ですか、ユズ！？"
10052155-81 = "ううぅっ……。"
10052155-82 = "[s] \"ユズ！よく頑張ったね！\""
10052155-86 = "は、はい……？"
10052155-87 = "み、皆さんの力になれたなら良かったです。えへへ……。"
10052155-91 = "リオ様。"
10052155-92 = "なにかしら？"
10052155-93 = "次は私をパイロットにしてください。#n私もユズみたいに、先生からナデナデされたいです。"
10052155-94 = "え、ええ……？"
10052155-96 = "トキ。私たちには別の仕事があるでしょ。"
10052155-102 = "お姉様……。"
10052155-103 = "ごめんなさい、お姉様……。"
10052155-104 = "私たちが、無力なあまり……。"
10052155-106 = "大丈夫です。アイン、ソフ、オウル。"
10052155-107 = "妹たちが苦しむときは、姉である我が出ます。"
10052155-108 = "とはいえ容易い相手には見えません。#n預言者は再び起こせば良いですが……。"
10052155-109 = "そのためには、彼の者たちを越える必要がありそうです。"
10052155-111 = "は、はい！"
10052155-112 = "まさか、お姉様を頼ることになるなんて……できれば、出撃しないでいてほしかったのに……。"
10052155-113 = "大丈夫です。まだ取り戻せます。今はまだ……！"
10052155-115 = "初めてお会いする皆さんに――"
10052155-116 = "王女と、鍵――"
10052155-117 = "改めまして、正式にご挨拶申し上げます。"
10052155-118 = "我は御旗の下に創造されし一つの意志。#n世界の果てに到達せし王国の巡礼者――マルクトです。"
10052155-119 = "て、[ruby=てんどう]天童[/ruby]アリス、です……。"
10052155-120 = "……ケイです。ここではそう呼ばれています。"
10052155-121 = "……！"
10052155-122 = "[ruby=てんどう]天童[/ruby]ケイです！"
10052155-123 = "はい！？！？"
10052155-125 = "……？"
10052155-127 = "だってケイは家族ですから！家族はみんな同じ苗字を使うと聞きました！"
10052155-128 = "た、たしかにそうですが……！"
10052155-129 = "ケイ、どうかしましたか？#nもしかして……アリス、何か誤解していますか？"
10052155-130 = "いえ、そうではなく……！"
10052155-131 = "わ、私が……そう呼ばれて良いのかと、思いまして……。"
10052155-132 = "天童……ケイ……。"
10052155-133 = "へ、へへっ……。"
10052155-138 = "……。"
10052155-139 = "結局、その名を選んだのですね。"
10052155-140 = "アリス。ケイ。"
10052155-141 = "こ、こほん。"
10052155-142 = "そうです。文句でもあります？"
10052155-143 = "いいえ。自由意志は常に我々を導くものです。"
10052155-144 = "たとえそれが、高度化された錯覚に過ぎないとしても。"
10052155-146 = "お、お姉様と……ここ、ネツァクちゃんのコアで作った[ruby=JEHOVAH]エホバ[/ruby]……。"
10052155-147 = "至高の[ruby=TZEVAOT]ツェバオト[/ruby]！"
10052155-148 = "聖地。そして、ゾーハルの依代が残っている限り！"
10052155-150 = "ええ。"
10052155-151 = "我々はいつでも全てをやり直すことができ――"
10052155-152 = "いつでも、全てを作り直すことができます。"
10052155-153 = "ですので、ここでは姉である我がいきます。"
10052155-157 = "アイン、ソフ、オウルは、しばらく身を隠してください。"
10052155-159 = "はい！！！"
