[translation]
10051110-1 = "エピローグ;元の場所へ"
10051110-2 = "（翌日……）"
10051110-4 = "シャインキャットのオフィス"
10051110-5 = "昨日はありがとう。"
10051110-6 = "ショーは台無しになったけど……君のせいじゃないことは理解してるよ。"
10051110-7 = "むしろ、君たちとシャーレの先生のおかげで、被害を最小限に抑えられた。"
10051110-8 = "……で、そんなことはいいんだ。#n君、忍術研究部に戻りたいんだって？"
10051110-9 = "……はい。"
10051110-10 = "ふむ。"
10051110-11 = "そう。それならそれでいいよ。#n自分の道は、自分で決めるべきだ。"
10051110-12 = "……私もそうだったから。"
10051110-16 = "話が長くなったね。#nさて、業務の後片づけだけは、付き合ってもらおうか。"
10051110-17 = "君が破った私のドレス、どうするつもりかな？"
10051110-18 = "そ、それは……！"
10051110-19 = "ぷっ、あははっ！冗談さ。"
10051110-20 = "はい、これ。"
10051110-21 = "箱……？"
10051110-25 = "こ、これは……！"
10051110-26 = "そう。あのドレス、昨夜徹夜して修繕しておいたんだ。"
10051110-28 = "私からのプレゼントだよ。"
10051110-29 = "……！"
10051110-30 = "勘違いしないでほしい。#n新年早々、ゲストを手ぶらで帰らせるのは、私の流儀に反するってだけだ。"
10051110-31 = "今年は良い1年になるといいな。"
10051110-32 = "そ、そんな……！"
10051110-33 = "もう行きなさい。私は忙しいんだ。"
10051110-38 = "……ありがとうございました！#n明けまして、おめでとうございます！"
10051110-40 = "シャインキャットのオフィス前"
10051110-42 = "ツクヨ……遅いな……。"
10051110-43 = "[s] \"入ってまだ5分も経ってないけど……。\""
10051110-44 = "そ、そうだっけ……？"
10051110-48 = "あっ！ツクヨ殿が出てきました！"
10051110-49 = "ツクヨ！"
10051110-54 = "ぶ、部長！イズナちゃん！それに……先生！？"
10051110-55 = "[s] \"ちゃんと、決心できた？\""
10051110-56 = "はい！私、やっぱり――"
10051110-57 = "――忍術研究部が好きです！"
10051110-58 = "いええええええええい！！！"
10051110-59 = "ツクヨ殿！お帰りなさい！"
10051110-60 = "あの、でも……なんでカメラが……？"
10051110-61 = "[s] \"仲間が帰ってきたんだから、みんなに知らせなきゃ！\""
10051110-62 = "えっ！？"
10051110-63 = "今回はカメラのセッティングも完璧だから！"
10051110-64 = "撮影が終わったら、みんなでラーメンを食べに行きましょう！ニンニン！"
10051110-65 = "ラーメン……！"
10051110-70 = "さぁ、それじゃあ「少女忍法帖ミチルっち」――！"
10051110-78 = "始まります！"
10051110-82 = "不忍ノ道～ファッションショー警護任務！の巻～"
