[translation]
10052060-1 = "ケテル：最もきらびやかに輝く至高の王冠 "
10052060-15 = "ケテルは1番目の預言者とも言えますが……。"
10052060-16 = "私たちがケテルに遭遇したのは、ずいぶん後になってからでしたね。"
10052060-17 = "覚えていますか？廃墟の水没地区でのこと。"
10052060-18 = "[s] \"うん。鬼ごっこをしたよね。\""
10052060-19 = "ええ。私たちが鬼側でしたね。"
10052060-2 = "ケテルのエリアに進入しました。"
10052060-20 = "[s] \"珍しくヒマリも現場に来てたっけ。\""
10052060-21 = "その話は私も知っています。#nデカグラマトンを直接見たくて、子供のように目を輝かせ、興奮していたと。"
10052060-22 = "私も似たような話を聞きました。"
10052060-23 = "……2人とも、一体誰にそんなデマを吹き込まれたのですか？#nさては、リオですね？"
10052060-24 = "エイミです。"
10052060-25 = "そうでしたか……#nエイミったら、たまに物事を直観的に捉えることができないのですよね。"
10052060-26 = "私は見たままを正直に言っただけだよ？"
10052060-27 = "エイミ！？"
10052060-28 = "（本当だったのね……）"
10052060-29 = "大丈夫です、ヒマリ先輩！#nアリスも新しいゲームの発売前日には、そういう気分になりますから！"
10052060-3 = "未だに意味は分かりませんが、セフィラの数字は1だそうです。"
10052060-30 = "そ、そうですか？#nあ、いえ、別にあの時の私は興奮したり、はしゃいだりしてませんでしたからね？"
10052060-31 = "デカグラマトンという「現象」の1つをこの目で確かめたら、騒動に決着をつけられるかもしれない。そんな期待をしていただけです。"
10052060-32 = "結局、1つ片づいたと思ったら、また別の可能性が広がってしまい……。"
10052060-33 = "気づけば今の状況に至ってしまった、というわけです。"
10052060-34 = "この結果を予測し、備えることができなかったのは、私としては痛恨のミスでした。"
10052060-35 = "ヒマリ部長、私の知らない間に予言能力でも得たのですか？"
10052060-36 = "まさか。#nもちろん、私がオカルトを研究する理由の1つではありますが……。"
10052060-37 = "その領域については、確実な答えを得られていない状況です。"
10052060-38 = "でしたら、どうして予測できなかった結果にまで、わざわざ責任をとろうとしているのですか？"
10052060-39 = "……！"
10052060-4 = "おぉ……すごいです、トキ！アリスはそれすら知りませんでした！"
10052060-40 = "（よく言ってくれたわ、トキ）"
10052060-41 = "よく言ってくれましたね、トキ。"
10052060-46 = "あの……お話し中にごめんなさい……。"
10052060-47 = "また降下するんですか！？"
10052060-48 = "そうよ。それが最も合理的だもの。"
10052060-49 = "ええ。一番戦略的な方法です。"
10052060-5 = "預言者の表記情報を読んだだけですよ。かわいいアリス。"
10052060-50 = "地上ルートで、ケテルの十字砲火を突破するのは困難ですので。"
10052060-51 = "降下時の安全性については心配いりませんよ。"
10052060-52 = "それに、降下作戦はすでに何度も経験しているではないですか。"
10052060-53 = "け、経験が多いからって怖くないわけじゃなくて……！"
10052060-54 = "珍しくユズが積極的に発言していますね。#nこれは本気で怖がっている証拠です。"
10052060-55 = "ですが降下用のポッドは、ゲーム開発部の皆さんの意見を積極的に反映しているのですよ？"
10052060-56 = "わたしが使うことになるとは思わなかったんです！"
10052060-57 = "みんな、降下の時間よ。準備してちょうだい。"
10052060-58 = "ひぃぃっ！？"
10052060-59 = "ユズ、大丈夫ですか？"
10052060-6 = "トキは几帳面なのですね！十分すごいと思います！"
10052060-60 = "や、やっぱり、これは……！"
10052060-61 = "降下チームはポッドに搭乗してください。繰り返します――"
10052060-62 = "降下用ポッド射出準備、完了。"
10052060-69 = "じゃあ、始めよっか。"
10052060-7 = "ありがとうございます。なでなでしてあげます。"
10052060-70 = "先頭はお任せください。"
10052060-72 = "ヒマリ部長、モモイ。フォローはよろしくね。"
10052060-73 = "ひぃぃぃぃぃっ……！"
10052060-75 = "降下開始！"
10052060-77 = "よぉし……このレバーを押せばいいんだよね？"
10052060-78 = "お姉ちゃん……お願いだから慎重にね。"
10052060-79 = "私は大真面目だよ！"
10052060-8 = "はい！"
10052060-86 = "きゃぁぁぁああああぁぁぁ――！！！"
10052060-87 = "（鬼気迫る悲鳴ね……）"
