[translation]
10050060-1 = "第6話;誰もいない場所"
10050060-10 = "な、ナギサ様が直々に……！？"
10050060-100 = "ええ、たしかに見回りが少ない。"
10050060-101 = "というか、そもそも人気がないというか……。"
10050060-102 = "そちらの方が好都合でしょう。"
10050060-11 = "はい……これが私一人の問題なら、甘んじて受け入れたことでしょう。"
10050060-112 = "ここは……図書館？のようですね。"
10050060-117 = "図書館でも、なんだか雰囲気が違うような気がしますわ……。"
10050060-118 = "古い本が多いですが……状態が良いものばかりです。"
10050060-119 = "ということはおそらく、専門の管理人がいるはず……。"
10050060-12 = "しかしもしこれが、我々の「正義を実現しようとする意志」の問題なら……。"
10050060-123 = "あら……？"
10050060-13 = "「トリニティの正義」そのものの根本的な問題ならば！"
10050060-131 = "タカネ？どうかしましたか？"
10050060-138 = "うわあああっ！？"
10050060-139 = "図書館では、静かに。"
10050060-145 = "はぁ……また外の人が……。"
10050060-146 = "……でもこの人たち、トリニティの人ではないような……？"
10050060-147 = "それに本のようなものをたくさん持ってるし……。"
10050060-149 = "えっと……事情はよく分からないし、理解したくもありませんが……。"
10050060-15 = "当然我々は、存在価値を証明すべきだと思いませんか！？"
10050060-150 = "とにかく……出版関係の方々なんですね？"
10050060-151 = "え、ええ……騒ぎを起こしてしまい申し訳ありませんでした、[ruby=こぜき]古関[/ruby]ウイさん。"
10050060-152 = "いえ、分かってるならいいです……それにこちら側の方のようですし。"
10050060-153 = "何より……みんなのこと、大事にしているようだし……。"
10050060-154 = "「みんな」……？"
10050060-155 = "あ……失礼。本のことです。"
10050060-156 = "そういえばウイさんは、古書館を管理している、図書委員会の委員長とおっしゃいましたよね？"
10050060-157 = "トリニティの中央図書館はキヴォトス最大規模で、この世のあらゆる蔵書があると聞いたのですが……。"
10050060-158 = "そんな場所を間近で見られるなんて光栄ですわ。"
10050060-159 = "念願の場所に来られてよかったですねぇ。"
10050060-16 = "は、はいっ！！"
10050060-160 = "その噂は……少々、大げさな気がしますが……でも、できるだけたくさんの子たちを守りたいのは本当です……。"
10050060-161 = "なるほど、そうですか。では本を延滞する人たちを罰しようとして建物一つが消し飛んだという話も、でたらめなんですね？"
10050060-162 = "それは本当です。"
10050060-163 = "！？"
10050060-164 = "あの子たちを大事にできない人たちですから。むしろ優しいくらいだと思いますが。"
10050060-165 = "……とにかく、お二人の子の話は読ませてもらいました。"
10050060-166 = "……よかったと思います。個人的には好きですよ。"
10050060-167 = "えーっと、ちなみにあれは漫画ですが……。"
10050060-168 = "……それがどうかしましたか？漫画も本であることには変わりません。"
10050060-17 = "あの……ところで、何をどうしたら……。"
10050060-170 = "そ、それに一部のシーンとか表現とか、そのあたりがやや気になると言っていた方もいたり、と……。"
10050060-171 = "そうなんですね。まあ、外の人たちからするとそういうこともあるかもしれませんね。"
10050060-172 = "……普段本を読まない人に耐性がないだけと思いますが。"
10050060-173 = "さきほど、正義実現委員会が二人を追っていると言いましたよね？"
10050060-174 = "え、ええ……お恥ずかしながら。"
10050060-175 = "正義実現委員が独断で……。こんな些細な事に、あれほどの人を動かすことはないはず……。"
10050060-176 = "……。"
10050060-177 = "……ティーパーティーですね。"
10050060-178 = "！？それはまだ話してないはず、ですが……。"
10050060-179 = "そのくらいはまあ……。"
10050060-18 = "一つ考えがあります。"
10050060-180 = "これだからお偉いさんは……この子たちの価値も分からないでしょうに。"
10050060-181 = "とにかく。しばらくここで過ごすといいです。"
10050060-182 = "そ、そんな、ご面倒をかけてしまっていいのです……？"
10050060-183 = "……[ruby=・]こ[/ruby][ruby=・]っ[/ruby][ruby=・]ち[/ruby][ruby=・]側[/ruby]の方々のようなので。でもあまり深く考えないでもらえると。長居されても困るといいますか……。"
10050060-184 = "いやぁ、助かりますよウイさん！ではしばらくお世話になりますね。"
10050060-185 = "あと、もう一つ。"
10050060-186 = "ん……？"
10050060-187 = "……3メートル距離を置くように。"
10050060-189 = "えっ……？"
10050060-19 = "他の方も思いついたかもしれませんが、現状を見た感じ、他に方法はないでしょう。"
10050060-190 = "難しいなら出ていっていただきます……。"
10050060-191 = "む……分かりました、それがここのルールなら致し方ない。"
10050060-192 = "ルールといいますか、厳密には私の問題ではありますが……。"
10050060-193 = "ん？今なにかおっしゃいましたか？ウイさん。"
10050060-194 = "……3メートル。"
10050060-195 = "は、はい……。"
10050060-199 = "部長、私たちこれでいいのでしょうか……？"
10050060-20 = "難題にぶつかった時には、奇策より上策を講じろと言いますよね……よって。"
10050060-200 = "冷静に考えれば、よくないのでしょうねぇ……。"
10050060-201 = "ですが、何か試すことも許されない状況ですし。"
10050060-202 = "何かいい案はないのですか？"
10050060-203 = "とりあえずここに居ていいと言われたのですから、しばらくは身を潜めましょう。そしてほとぼりが冷めた頃、レッドウィンターに戻る、と。"
10050060-207 = "そんな目で見ないでくださいよ……私だってこれが一番じゃないことは分かっていますから。"
10050060-208 = "ですが人生には時折、一つしかない選択肢を取らなければならない時がありますよね？"
10050060-209 = "私は奥の方で少し休みますので、何かあれば言ってください。"
10050060-21 = "正義実現委員会のあらゆるヒューマンリソースを、トリニティ全域へと広げます！"
10050060-213 = "と、部長は言いましたが……。"
10050060-214 = "うぅ……こういう話ではなく、もっと褒められるような話をしたかったのに……。"
10050060-22 = "い……いつから、ですか？"
10050060-220 = "[ns] \"あれ、この番号は……？\""
10050060-222 = "こ、こんにちは、先生。"
10050060-223 = "こ、こうして急にご連絡したのは、その……。"
10050060-224 = "うぅ……どこから話したらよいものか……。"
10050060-225 = "[s] \"大丈夫。まず思いついたことから話してみて。\""
10050060-226 = "はい……まず私たちは、なりゆきでトリニティに来ており……。"
10050060-227 = "[s] \"ん？奇遇だね、私もトリニティにいるよ。\""
10050060-228 = "えっ、先生も！！？"
10050060-23 = "今！この瞬間からです！みなさん、無理なお願いというのは分かっています。でもあと少しだけ、もう少しだけ頑張ってもらえませんか？"
10050060-24 = "私も、先頭に立って現場に行って参ります！"
10050060-28 = "ま、待ってくださいマシロさん～～！"
10050060-4 = "皆さんお揃いでしょうか？"
10050060-44 = "……今日は1冊も売れませんでしたわ。"
10050060-45 = "というか、売り場さえ確保できませんでしたね……。"
10050060-46 = "正義実現委員会、でしたでしょうか？あの黒い制服を着た方々。今日はやけによく見ますねぇ。"
10050060-47 = "んん……レッドウィンターを生き抜いたスキルの一つ、出版部部長の危険センサーが強く反応しています。"
10050060-48 = "も、もしかして本当に感付かれたのでは！？"
10050060-5 = "は、はいっ！"
10050060-53 = "タカネ姫！あと侍女の方も！こちらにいらしたんですね！"
10050060-54 = "……！え、ええ……！ごきげんよう。"
10050060-55 = "……私はいつから侍女に？"
10050060-56 = "こんにちは。状況的に駆け足で説明することをお許しください。"
10050060-57 = "か、構いませんわ。どうかされたのです？"
10050060-58 = "ええ……結論から言いますと、正義実現委員会が、お二人を探しております。"
10050060-59 = "……やはりそうでしたか。今日はやけに見回りの方がいると思っていましたわ。"
10050060-6 = "皆さんご存じとは思いますが、トリニティでじわじわ広がっている非公認図書の追跡任務を進行中です。"
10050060-60 = "ええ。そういうことです……#nそのせいかトリニティ全体で不穏な雰囲気が……。"
10050060-61 = "そんな……私たちのせいですわ……まさかこんなことになるなんて、本当に申し訳ございません。"
10050060-62 = "い、いえ！思い返せば、そうでもなかったかも……というか、タカネ姫に非はありませんから！"
10050060-63 = "……ただ、教科書以外の本をすべて回収しようとしているみたいです。"
10050060-64 = "申し訳ありませんが、タカネ姫……これ以上お力になるのは難しそうです。"
10050060-65 = "いいえ、ここまで助けていただいたのですから本当になんとお礼を申し上げるべきか……。"
10050060-66 = "可哀想なタカネ姫……ここでも苦難を強いられるなんて……ぐすっ……。"
10050060-68 = "誰か私のことも慰めてくれませんか？"
10050060-69 = "ともかく、正義実現委員会がいない場所に避難された方がいいかと。"
10050060-7 = "が、数日が経過した今もなお、これといった進捗がありません。"
10050060-70 = "そんな場所があるのです？"
10050060-71 = "ごめんなさい、そこまでは私たちも……。"
10050060-72 = "ですが、外部の方にしか発見できないような、そんな場所があるのかもしれません。"
10050060-73 = "どうかお体に気をつけて。次はトリニティで素敵な思い出が作れますように。"
10050060-74 = "ありがとうございます。素敵な思い出はもうすでにたくさん頂きましたわ。"
10050060-75 = "とんでもないです、それではまたいつの日か！"
10050060-8 = "はい……。"
10050060-80 = "……どこで道を間違えたのでしょう。"
10050060-81 = "……最初からだったのでは？本当にこれでいいのですか部長！？"
10050060-82 = "正直なところ、私もよく分かりませんが……でも最後までいってみることが大事なのでは？"
10050060-83 = "時と場合によっては、最後までいかない方が大事かもしれませんわ。"
10050060-84 = "とにかくさっきの生徒さんが言ってくれたように、正義実現委員会のいない場所を探してみましょう。"
10050060-9 = "そして先日、ナギサ様から懸念の言葉を頂きました。"
10050060-94 = "……まずは身を隠してから。"
10050060-95 = "うぅ……こういう時、先生がいれば……。"
10050060-99 = "部長、あちらが安全なのでは？"
