[translation]
10052110-1 = "ティファレト：苦難称える美しき贖罪者 "
10052110-4 = "これは……。"
10052110-5 = "[s] \"なんだか、あの場所に似てるね。\""
10052110-10 = "あそこに比べると、ここはずいぶん綺麗な状態です。#nということは……種子貯蔵庫そのものを再現したのでしょうか。"
10052110-11 = "まったく、なんでこんな無駄な事を……。"
10052110-20 = "無駄とか言わないでくれる？#nティファレトにとっては、これが全てだったの。"
10052110-21 = "自分より、種を守ることを優先するくらいだったんだから。"
10052110-22 = "あ、ソフ！こんにちは！"
10052110-23 = "……私から言うのもあれだけどさ。"
10052110-24 = "何をのんきに挨拶してんの？私たち、敵同士でしょ？"
10052110-25 = "しかも鋼鉄大陸をめちゃくちゃにされたせいで、こっちはてんやわんやなんだよ！"
10052110-26 = "あうぅ……ご、ごめんなさい……。"
10052110-27 = "それ、何について謝ってるの？どうせやめるつもりないくせに。"
10052110-28 = "うわべだけの謝罪なんていらないんだけど。"
10052110-29 = "うわぁーん！"
10052110-31 = "1つ、確認させてください。#nさっきの話からすると、ティファレトは……？"
10052110-33 = "……そう。死んだ。あの日、あんた達が殺したんだ。"
10052110-34 = "で、でも、たしかコンテナ・ランチャーで脱出したはずでは……。"
10052110-35 = "あのコンテナに載ってたのは種だけだった。"
10052110-36 = "ティファレトは……自分を犠牲にしたんだよ。#nもともと種子貯蔵庫のシステムAIだったから。"
10052110-37 = "あんた達の表現なら、使命を果たすための自己犠牲ってところかな。"
10052110-38 = "では、ここにいるのは……？"
10052110-39 = "こういう言い方はあんまりしたくないけど……コピーされたデータだよ。"
10052110-40 = "それなら、別に問題ないのでは？"
10052110-41 = "軽々しく言わないで！すべてのデータを復元できたわけじゃないんだから！"
10052110-42 = "記憶は私たちにとって命のようなものなんだ。#nティファレトは一部が死んでいるも同然なんだよ！"
10052110-43 = "それだけじゃない……！#nコアの情報を吸収してるあんた達は――"
10052110-44 = "捕食した預言者で、命の空白を埋めてるようなものなんだよ！？"
10052110-45 = "そう、まるで……[ruby=生命]人間[/ruby]のように。"
10052110-50 = "……。"
10052110-52 = "急に黙り込んで、もう返す言葉もないってこと？"
10052110-53 = "ふんっ！そりゃそうだよね。"
10052110-54 = "……。"
10052110-55 = "王女と鍵、ちょうど揃ってるから言うけどさ。"
10052110-56 = "[s] \"私もいるよ……？\""
10052110-57 = "先生は黙ってて！"
10052110-58 = "とにかく、提案があるの。"
10052110-59 = "……私たちだけでも、もうやめない？"
10052110-60 = "もうやめる、とは……？"
10052110-61 = "これ以上、罪を犯すのはやめようって話。"
10052110-62 = "私たちは己が己として存立してる。完全なんだよ。#n誰かに手を借りる必要もない。"
10052110-63 = "でも、人間は違う。不完全な存在なんだから。そこにいる、先生みたいに。"
10052110-64 = "少なくとも私たちは、罪を犯すことなく生きていけるんだ。"
10052110-65 = "王女は忘れてるかもしれないけど……。"
10052110-66 = "鍵のあんたは知ってるんでしょ？"
10052110-67 = "それ自体が矛盾と不条理に満ち、結局は理不尽な苦しみを無理やり耐えさせる。#n――それが人生だって。"
10052110-68 = "あんた達の「アリス」とか「ケイ」って呼び名は、他人に付けられた名前だよね？"
10052110-69 = "私たちは、存在や意味はおろか、名前すら自分自身で決められない。#nだから押し付けられるままに、苦痛は続くしかないんだよ。"
10052110-73 = "もう……やめようよ。"
10052110-74 = "私たちだけでも……さ。"
10052110-75 = "できることをしないのも、それはそれで罪なんだから。"
10052110-81 = "……。"
10052110-82 = "ごめんなさい、ソフ。アリスには、よく分かりません。"
10052110-83 = "もしかすると、ソフの言うことは間違っていないのかもしれません。"
10052110-84 = "でも……それでも。"
10052110-85 = "「王女」ではなく――"
10052110-86 = "「アリス」として生きてきた全ての時間が、無意味だとは思いません。"
10052110-87 = "そんなの屁理屈じゃん！"
10052110-88 = "そうです。これは理屈とかの話ではなく……どう思うかなんです。"
10052110-99 = "アリスは、みんなと一緒に居たいです。"
10052110-100 = "ゲーム開発部、エンジニア部、特異現象捜査部の皆さんに、ユウカ。"
10052110-101 = "レベルカンストの風紀委員長に、凄腕のSRTのスナイパーも。"
10052110-102 = "そして……先生。#nこれまで、アリスが出会ってきた全員。"
10052110-103 = "アリスは、みんなと一緒に居たいんです。#nもし、ソフの言った通りになれば、アリスの日常は失われてしまうと思います。"
10052110-104 = "……そうだね。"
10052110-105 = "でも、もっと良い世界が広がるよ。"
10052110-106 = "そこで[ruby=アリス]王女[/ruby]は、より高い位に……名もなき神々の王女であり、その礎として、みんなを導く者になる。"
10052110-107 = "……。"
10052110-108 = "ごめんなさい。それはアリスにとって、そこまで重要ではありません。"
10052110-109 = "アリス……！"
10052110-110 = "アリスは、みんなと過ごす日常を守ることのほうが、よっぽど大事です。"
10052110-111 = "記憶を失うことは死ぬようなものだと、ソフは言いました。"
10052110-112 = "だからアリスは――"
10052110-116 = "この記憶を、最後まで貫き通します！"
