[translation]
10052020-1 = "JEHOVAH ELOHIM"
10052020-2 = "ポイントオスカー、到着。では……始めるわ。"
10052020-3 = "[s] \"何か手伝えることはある？\""
10052020-4 = "いえ、大丈夫よ。任せておいてちょうだい。#nまず……[ruby=ヘッド・マウント・ディスプレイ]このHMDを使[/ruby]って、このエリアのネットワークに接続するわ。"
10052020-9 = "単なる視覚情報の入出力だけでは足りないと思いますが……ああ、なるほど。#nそのスーツに、生体電流を増幅する装置が搭載されているのですね。"
10052020-10 = "ええ。だからHMDを通じて、このエリアのネットワークを1つの概念空間として認識できるようになるの。"
10052020-11 = "その中のすべてのデータは、3次元の座標を持ったまま可視化され、無限の空間の中で――"
10052020-12 = "だー！分かった！分かんないのが分かったから大丈夫！"
10052020-13 = "え、ええ……？"
10052020-14 = "もっと分かりやすく！3行でまとめて！"
10052020-15 = "うん、今回はお姉ちゃんに賛成。"
10052020-16 = "あ、もちろん、リオ会長が丁寧に説明しようとしてくれてるのは分かってます。#nでも、今はあまり時間が無いので……。"
10052020-17 = "（わたしにはちょうどいい説明だったけど……）"
10052020-22 = "[ns] \"改めて、私たちにもできることあるかな？\""
10052020-23 = "そうね……私が無事に戻ってくるまで、周囲の防衛を頼めるかしら。"
10052020-24 = "ダイブしている間、私は無防備な状態だから。"
10052020-25 = "ケイは、万が一のために私のサポートをしてちょうだい。"
10052020-26 = "じゃあミドリ！ユズ！見回りに行こう！"
10052020-33 = "サポートと言われましても……。"
10052020-34 = "見たところ、HMDはその1つしか用意していませんよね？"
10052020-35 = "ええ。だから――"
10052020-36 = "もしもの時は、貴女が引き継いでほしいの。"
10052020-37 = "はい？それは、どういう……？"
10052020-41 = "……あなた、変なことを考えていませんか？#n生体電流の増幅……もしもの時……。"
10052020-42 = "仮に失敗したら……？#nその影響も増幅されて、リオの身体に跳ね返る……？"
10052020-43 = "ええ、その通りよ。"
10052020-44 = "失敗すれば――私の脳は丸ごと焼かれてしまうでしょうね。"
10052020-45 = "正気ですか！？それ、渡してください。#n万が一の時も、私の身体なら、あなたよりは軽傷で済むでしょうから。"
10052020-47 = "[ns] \"危険すぎることには賛成できないよ。\""
10052020-48 = "いいえ、これが正しいわ。#nもちろん、2人とも失敗する可能性も否めないけれど。"
10052020-49 = "でも……ケイは最後の砦なの。#n少なくとも、最初からケイに任せるべきではないわ。"
10052020-50 = "私だって、失敗を前提に臨んでいるわけでは無いもの。"
10052020-51 = "それに、本当に危険で成功率が低いのなら……#nどんな手を使ってでも、ヒマリが私を止めているはずよ。"
10052020-53 = "くっ、それは……！"
10052020-54 = "[ns] \"……絶対に無事で戻ってくると約束してくれる？\""
10052020-55 = "ええ。善処するわ。"
10052020-60 = "……異常を感じたら、無理やりにでも止めさせてもらいますよ。"
10052020-61 = "分かったわ。"
10052020-62 = "……では、行ってくるわね。"
10052020-67 = "うっ……！"
10052020-68 = "（めまいが……情報量が多すぎて、流されてしまいそう……）"
10052020-69 = "（宙に浮いているような感覚……座標を失って漂流しかねないわね……）"
10052020-70 = "（当座は、仮想重力の値を追加して……）"
10052020-77 = "これで……少しはマシになったかしら。"
10052020-78 = "（それにしても……凄まじい光景ね）"
10052020-79 = "ようやく来ましたか。待ちくたびれましたよ？"
10052020-80 = "！？"
10052020-83 = "ようこそ、[ruby=つかつき]調月[/ruby]リオ。"
10052020-84 = "オウル……！"
10052020-85 = "名前を覚えていてくれたんですか？#nまあ、あまり意味はないんですけどね。だって――"
10052020-86 = "あなたはここで死ぬのですから！"
10052020-87 = "！！！"
10052020-92 = "案外逃げ上手ですね。それなら、これはどうです？"
10052020-96 = "足元が……！？"
10052020-97 = "ほらほら、どこまでも落ちてしまいますよ？"
10052020-101 = "あなたはこの場所にまで、重力に基づいた地形構造を構築しました。"
10052020-102 = "ええ、まさにあなた達らしいです。人間にとっては、それが自然でしょうから。"
10052020-103 = "くっ……！"
10052020-104 = "ですが、私たちはそんなものに囚われません。"
10052020-105 = "ソフの言葉を引用すると――#n重力に魂まで束縛されたあなた達とは、発想そのものが違うんです。"
10052020-106 = "こういうのはどうです？"
10052020-110 = "横向きに……引っ張られる！？"
10052020-111 = "右に落下するのはどういう気分ですか？#n今度は左！おまけに……上！"
10052020-117 = "最後は慈悲をもって……下へ落してあげますよ！"
10052020-124 = "くっ……うぅっ……！"
10052020-126 = "興醒めですね。そろそろ終わりにしましょうか。"
10052020-127 = "あなたも、私も。ここにいる間は実体を持ちません。"
10052020-128 = "再びソフの言葉を借りると――幽霊のような存在です。"
10052020-129 = "ですから、ここでどれほど傷を負っても、実際の肉体には影響しません。"
10052020-131 = "その代わり……精神そのものに作用するんです。"
10052020-132 = "ここでクイズをひとつ。"
10052020-134 = "もしもここで[ruby=・   ・   ・   ・   ・   ・   ・   ・]死んでしまったら[/ruby]、現実のあなたの身には何が起こると思いますか？"
10052020-135 = "……許容範囲を超えた電気ショックで、脳が丸ごと焼かれるでしょうね。"
10052020-136 = "ご存じだったのですね。であれば、少しだけ認めてあげます。"
10052020-137 = "では……。"
10052020-138 = "……。"
10052020-142 = "ほ、本当に大丈夫、でしょうか……？#nあの子に会ったら、いくらあの人たちでも――"
10052020-143 = "し、死んで、しまいますよ……？"
10052020-144 = "うん……まあそうだよね。"
10052020-145 = "私たちは、まだ誰かを傷つけたことも、それを考えたこともなかったからね……。"
10052020-150 = "……ちっ。"
10052020-151 = "覚悟してください――調月リオ！"
10052020-163 = "まだ……諦めないわ！"
10052020-164 = "無駄なんですよ！"
10052020-165 = "……！"
10052020-166 = "隙だらけの、あなたには！"
10052020-181 = "っ……！"
10052020-186 = "何をぼーっとしているのですか？"
10052020-191 = "え……？"
10052020-192 = "は……？"
10052020-193 = "ヒマリ……！？"
10052020-199 = "ふふっ。"
10052020-201 = "やはり、私の思った通りになりましたね。#n超天才病弱美少女ハッカーが助けに来てあげましたよ。"
10052020-202 = "貴女……そのバイク……。"
10052020-203 = "車椅子です。"
10052020-204 = "いえ、どう見ても……。"
10052020-205 = "く・る・ま・い・す、です。"
10052020-206 = "それはバイ――"
10052020-208 = "無駄ですよ。車椅子だと言って聞かないので。"
10052020-209 = "私は基本、後方支援の担当です。#nですが必要であれば、どこにでも[ruby=・   ・   ・]車椅子[/ruby]に乗って駆けつけますよ。"
10052020-210 = "これぞまさに、万能戦闘系美少女の姿。#nなにより、この車椅子には隠された機能として――"
10052020-211 = "……。"
10052020-212 = "ふふっ、この辺りで止めておきましょう。#n秘密は、明かさない方が最も効果的ですし。"
10052020-213 = "超天才清楚系病弱美少女ライダー……#nいえ、超天才清楚系車椅子美少女は、ミステリアスなものですから。"
10052020-214 = "……いま、2回美少女って言いました？"
10052020-215 = "あら、ケイったら。野暮なことを聞くのですね。"
10052020-216 = "雲の上に咲く一輪の花。#n新雪のように高潔で、清水の如く透き通るレディなのですから――"
10052020-217 = "何回「美少女」と形容しても構わないでしょう？"
10052020-218 = "エイミ……助けてください……。"
10052020-222 = "さあ、次は何を見せてくれるんですか？小さなお嬢さん？"
10052020-223 = "今までのパターンは、この超天才病弱美少女であり電脳妖精でもある[ruby=あけぼし]明星[/ruby]ヒマリが全て把握しました。"
10052020-224 = "邪魔者が増えましたね……。"
10052020-225 = "とはいえここは、このオウルが支配する空間。"
10052020-226 = "あなた達が勝つ可能性など、万に一つもありません！！！"
10052020-231 = "（たしかに……言うだけのことはありますね）"
10052020-232 = "（ですが、今はとにかく時間稼ぎを……！！！）"
10052020-233 = "あら、本当にそう思いますか？#n今の攻撃も、さほど大したものではなかったのに？"
10052020-234 = "自信満々ですね。"
10052020-235 = "この空間において、私は何でもできるし、何にでもなれるのです。#nまだ理解できないのでしょうか？"
10052020-236 = "調月リオも、明星ヒマリも、所詮はこの程度に過ぎないということですかね。"
10052020-237 = "まあ、いいです。今度は斜め方向に落としてあげますよ。"
10052020-238 = "ヒマリ！ここの重力はオウルが――！"
10052020-242 = "……？"
10052020-248 = "？"
10052020-249 = "ふふふ。"
10052020-250 = "反応がない……？#nも、もう一度……！"
10052020-257 = "何も、起きないのだけれど……？"
10052020-258 = "なっ、どうしてっ！？"
10052020-259 = "あら、驚きましたか？"
10052020-260 = "私のシグナルが、入力されない……！？"
10052020-261 = "何をしたんですか、明星ヒマリ！！！"
10052020-262 = "ふふふ。"
10052020-267 = "部長、会長。聞こえる？"
10052020-268 = "指示されたとおり――"
10052020-269 = "――全部壊したよ。"
10052020-270 = "ご苦労様でした。ナイスタイミングです。"
10052020-271 = "それは良かった。通信終わり。"
10052020-275 = "……。"
10052020-276 = "…………。"
10052020-277 = "………………。"
10052020-278 = "すべて破壊したって……まさか、通信ハブのシステムをですか！？"
10052020-279 = "最も手っ取り早いクラッキングの方法ね……。"
10052020-280 = "これだから人間は……！！！"
10052020-281 = "……ごめんなさい。"
10052020-282 = "今さらではないですか？"
10052020-283 = "でも……。"
10052020-284 = "さあ、これで対等な条件になりました。#n今なら見逃してあげますよ？"
10052020-285 = "言わせておけば！！"
