[translation]
10051060-1 = "第6話;高まる名声"
10051060-2 = "どこかの裏路地"
10051060-3 = "えへへ……ついに手に入れました！"
10051060-4 = "ファッション雑誌「BiBi」と「ron-ro」の最新号……！"
10051060-5 = "古紙や薬きょうを集めて売って、ご飯は全部コンビニの廃棄弁当でしのいで、水道水だけで喉を潤して……がんばってお金を貯めた甲斐がありました。"
10051060-6 = "……半分は先生が出してくれたんじゃなかったっけ？"
10051060-7 = "で、でも半分は私が払いました！先生も褒めてくれたんですよ！"
10051060-8 = "それより、見てください！#n「BiBi」の今月号は、シャインキャットさんの特集記事が載ってるんです！"
10051060-9 = "キヴォトスのファッション界に革命を起こした、天才デザイナーですよ！"
10051060-10 = "えっと……百鬼夜行でのファッションショーを手がけたみたいですね。"
10051060-11 = "わあ……。"
10051060-12 = "素敵な服がたくさん……。"
10051060-13 = "ファッションモデルになったら、こういう服を好きなだけ着られるんでしょうか？"
10051060-14 = "もちろん、私みたいな身長じゃ……モデルなんて夢のまた夢ですけど……。"
10051060-15 = "うーん……そういう需要もあるんじゃない？"
10051060-16 = "えぇっ！？そ、そうなんですか！？"
10051060-17 = "まぁ、背は高い方がモデルとしてプラスになるんだろうけど。"
10051060-18 = "この「ron-ro」の特集記事に出てる「[ruby=おおの]大野[/ruby]ツクヨ」って新人モデルも、身長180cmだって。"
10051060-19 = "しかも関係者も大絶賛。"
10051060-20 = "あ、「BiBi」にも載ってます！#nモデル界に彗星のごとく現れた新人で、ものすごく注目されてるって……。"
10051060-21 = "評論家のコメントもすごいです。#n「未熟さを遥かに凌駕する才能を持つ」とか、「限りなく宝石に近い原石」とか……。"
10051060-22 = "才能を持っている方は……きっと幸せなんでしょうね……。"
10051060-23 = "必ずしもそうとは限らないよ。"
10051060-28 = "華やかさの裏には、地道な努力があるんだよ。"
10051060-29 = "綺麗な花を咲かせるために、手入れの積み重ねが必要なのと同じでね。"
10051060-30 = "アツコちゃん……。"
10051060-31 = "ところでさ、2人とも。"
10051060-32 = "私が育ててたハーブの葉っぱが無くなってるんだけど、何か知ってる？"
10051060-37 = "傷んだ肉にハーブで下味をつける……みたいな話をしてた気がするんだけど……。"
10051060-43 = "……えっ、あれ！？"
10051060-45 = "トリニティ総合学園広場"
10051060-48 = "今月の「ハートガールズ」、もうお読みになって？"
10051060-49 = "もちろんですわ。"
10051060-50 = "最近はライフスタイルに偏っておりましたので、少々物足りませんでしたが……。"
10051060-51 = "最新号はファッションテーマに戻っていて嬉しいですの。"
10051060-52 = "ええ、評論の深みも増して、ファッションのトレンド分析や業界の話題も濃くなっておりましたわね。"
10051060-53 = "それと、今月デビューした新人モデルのレビューも印象的でしたわ。"
10051060-54 = "百鬼夜行出身のモデルのことですわね？名前は確か――"
10051060-55 = "大野ツクヨさん、ですわ。"
10051060-56 = "そう！グラビアだけでもものすごいオーラでしたし……。"
10051060-57 = "業界人も評論家も、口を揃えて絶賛の嵐ですの。"
10051060-58 = "今後が楽しみですわね。"
10051060-64 = "ミレニアムサイエンススクール"
10051060-68 = "それ、何読んでるの？"
10051060-69 = "学術誌？"
10051060-70 = "いっつも学術誌ばっか読んでるわけじゃないって……。"
10051060-71 = "「ron-ro」の最新号だよ。"
10051060-72 = "トレンドに遅れないための必読書。"
10051060-73 = "「ron-ro」？何それ？"
10051060-74 = "嘘でしょ……？有名なファッション誌だよ？"
10051060-75 = "ファッション誌か……。"
10051060-76 = "服なんて、制服のサイズを測った時以外は、気にしたことなかったな……。"
10051060-77 = "論文読むので精一杯で、他の文字は入らないし。"
10051060-78 = "う、うん……まあ、そういう子もいるよね。"
10051060-79 = "それで？すごく集中して読んでたけど、何か面白いことでも載ってたの？"
10051060-80 = "新人モデルについての評論が良い感じ。"
10051060-81 = "デビューしたばっかでまだキャリアは短いけど、すごく注目されてるみたい。"
10051060-82 = "えーっと……名前は……ツクヨ？"
10051060-83 = "おお……たしかに、ただ者じゃなさそうな雰囲気してるね。"
10051060-89 = "クロノス放送局インタビュールーム"
10051060-91 = "ここまで、インタビューへのご協力ありがとうございました！"
10051060-92 = "は、はい……こちらこそ、ありがとうございます……。"
10051060-93 = "では最後の質問です！#nツクヨさんの今後の目標を、一言で教えていただけますか！"
10051060-94 = "え、ええっ！？"
10051060-95 = "私、これから……その……。"
10051060-99 = "……。"
10051060-100 = "そ、その、その……。"
10051060-102 = "さあ、ツクヨさん！心の中にあることを、ずずいっと、素直にお話しください！"
10051060-103 = "す、素直に……。"
10051060-104 = "（ギロッ）"
10051060-105 = "あ、あの……これから、か、かっこいいファッションモデルになれるよう、#n頑張り、ます……！"
10051060-106 = "（うなずく）"
10051060-107 = "はい！不器用ながらも心のこもったお言葉、確かに受け取りました！"
10051060-108 = "そんなツクヨさんのこれからの活躍、楽しみにしてます！#nではここで一旦CMです！"
10051060-114 = "お疲れさま。初めてのテレビインタビューにしてはよくやったね。"
10051060-115 = "あ、あの……これってどういう状況なんでしょうか……。"
10051060-116 = "まあ、今の状況をすぐに理解しろって方が無理な話かな。"
10051060-117 = "この画面を見て。さっきの生放送を何人が見たか、再生数がどれだけ伸びたか、どんな反応が出ているか……。"
10051060-118 = "……！"
10051060-119 = "こんな数字、初めて見るのではないか？"
10051060-120 = "これは君が生み出した数字。君が引き寄せた視線なんだよ。"
10051060-121 = "君ほどの才能には、時代が応えるってこと。"
10051060-122 = "で、でも、私は忍術研究部に……。"
10051060-123 = "私は忍術とか忍者のことは何も分からない。"
10051060-124 = "だけど、モデルの世界で……君はトップになれる。#nそれは確信してるんだ。"
10051060-125 = "でも私は、忍者が……。"
10051060-126 = "何かを掴むなら、何かを手放さなきゃならない。選ぶのは君だよ。"
10051060-127 = "私は……。"
10051060-128 = "答えが出ないなら、私が教えてあげる。#n……私について来なさい。それが答えだよ。"
10051060-129 = "でも……。"
10051060-134 = "それに、さっき君は宣言したよね？#n大勢の視聴者の前で「モデルになります」って。"
10051060-135 = "……！"
10051060-136 = "その約束を、破るつもり？"
10051060-137 = "お車の準備ができました。"
10051060-138 = "さあ、次の仕事に行くよ。"
10051060-147 = "「少女忍法帖ミチルっち」撮影現場"
10051060-148 = "部長！見てください！#n先週アップした動画、再生数が2回増えましたよ！"
10051060-149 = "おおっ！またしても忍者の魅力に酔いしれる者が増えたか！"
10051060-150 = "ツクヨ！ツクヨもこっち来て見てごらんよ！"
10051060-154 = "部長、ツクヨ殿はまだ来ていません。"
10051060-155 = "え？まだなの？"
10051060-156 = "珍しいね……どうしたんだろう？"
10051060-157 = "先ほどからモモトークでメッセージ送っているのですが、全然既読がつきません……。"
10051060-158 = "この時間に撮影があることは、誰よりも知ってるはずなのに。"
10051060-159 = "まさか、何かあったんじゃ……？"
10051060-160 = "ごめんくださぁい。今日の撮影場所はこちらで合ってますか？"
10051060-161 = "むむ？"
10051060-162 = "そ、その声は……！"
