[translation]
10052080-1 = "公義"
10052080-10 = "えっ、ええっ！？"
10052080-100 = "なのに、押し付けられただけの人生に、何か大きな意味があるのだと考えたがる。"
10052080-102 = "！！！"
10052080-103 = "……！"
10052080-105 = "明日について、真剣に考えたことはある？#n多分、ないよね。だってそんなことしたら、誰も正気を保てなくなるから。"
10052080-106 = "あ、明日は……何かを失う日、なので……。"
10052080-108 = "明日について、確率を考えてみましょう。「良い事」なんてそうそう起こりません。#nなのに必ず――"
10052080-109 = "死へ、一歩近づきます。"
10052080-11 = "嘘……本当に……？"
10052080-111 = "死……！？"
10052080-112 = "そんなに驚くことですか？#n案外、私たちには身近な概念なんですよ。"
10052080-113 = "なにせ私たちには「神秘」が与えられてないのですから。"
10052080-115 = "これに関しちゃ、そこにいる先生も同じだろうけど。"
10052080-116 = "[s] \"……。\""
10052080-117 = "み、皆さんが話しているのは……漠然とした希望で……#n[ruby=明日]静かに迫る未来[/ruby]についてではないと思います……。"
10052080-119 = "苦痛を分かち合い共感すれば、お互いを慰められるとでも？#nはっ、それなら、こう言ってあげましょう。"
10052080-12 = "……アイン、お姉様の様子はどうですか？"
10052080-120 = "傲慢だ、と。"
10052080-121 = "生命も、絆も、社会も……。"
10052080-122 = "うん。錯覚の上に成り立つ、砂上の楼閣にすぎない。"
10052080-123 = "だから、私たちは……。"
10052080-124 = "私たちは……。"
10052080-125 = "……。"
10052080-126 = "私たちばっかり……。"
10052080-127 = "これだけは覚えておいて！#n私たちはいつでもあんた達をぶっ飛ばせるから！"
10052080-128 = "さっさと諦めるか、圧倒的な力の前にひれ伏すか！#n早く選んだ方が身のためだよ。"
10052080-129 = "[s] \"でも、ここまで来たから。\""
10052080-13 = "お、お姉様は……えっと……う、動くだけなら……！"
10052080-131 = "[ns] \"悔いのないよう、できるところまではやってみたい。\""
10052080-132 = "……。"
10052080-133 = "……呆れてものも言えませんね。"
10052080-134 = "ほんと、[USERNAME]先生ってどうしようもないバカだよね！！ "
10052080-135 = "ちゃんと警告はしたからね！あとは勝手にすれば？"
10052080-140 = "……。"
10052080-141 = "……。"
10052080-142 = "言いたいことだけ言って、一方的に切るだなんて……。"
10052080-143 = "わざわざ回線を繋いできてまでやることですか！？"
10052080-144 = "……。"
10052080-145 = "よく分からない話ばかりでしたね。#nそれはそうと、これからどうすればいいでしょうか？"
10052080-146 = "トキはいつだってブレませんね。"
10052080-147 = "まずは現状を整理しましょう。#n幸い、鋼鉄大陸の拡張スピードが明らかに遅くなっています。"
10052080-148 = "預言者同士が緊密に繋がっているという仮説も、ある程度は証明されたと思うわ。"
10052080-149 = "加えて、外郭の預言者を攻略したことで、鋼鉄大陸の内陸まで活動範囲を広げられるようになった。"
10052080-15 = "オウル！第一防御線を突破されたからって、その仮定はやりすぎ！"
10052080-150 = "敵のエリアを確保して、私たちのテリトリーを広めるってことだね。#n基本的だけど効果的な戦略だと思うよ。"
10052080-151 = "では、現場の皆さんは探索を続けてください。#n日が暮れる前には拠点に戻ることをお忘れなく。"
10052080-153 = "先生！私たちにも手伝えることない？"
10052080-157 = "輸送船の防衛、ですか？なるほど、分かりました。"
10052080-159 = "が、頑張ります……。"
10052080-16 = "分かってますよ。でも、私たちは常に最悪のシナリオに備えておくべきでしょう？#n現実は……あまりにも変数が多すぎますから。"
10052080-164 = "……。"
10052080-165 = "（アリス……？）"
10052080-166 = "あの、先生……？"
10052080-167 = "[s] \"どうしたの？\""
10052080-168 = "そ、その……。"
10052080-169 = "……。"
10052080-17 = "ど、どうすれば……。#nま、まずは第二防御線を……！"
10052080-170 = "…………。"
10052080-171 = "………………。"
10052080-172 = "[s] \"……。\""
10052080-174 = "[ns] \"大丈夫だよ、アリス。\""
10052080-178 = "でも、その……。"
10052080-179 = "え？無理に話さなくていい、ですか……？"
10052080-18 = "うん。第二防御線にリソースを集中させよう。#nそれと……。"
10052080-180 = "言いたくなった時で、大丈夫……。"
10052080-181 = "……。"
10052080-182 = "分かりました。では……そうします。"
10052080-183 = "アリスのことを気遣ってくれて……ありがとうございます。"
10052080-187 = "そろそろ輸送船に戻ってきていただけますか？"
10052080-188 = "は、はい！"
10052080-189 = "急ぎましょう。まだ3つしかエリアを占領できていません。"
10052080-191 = "ほら、行くよ。"
10052080-192 = "ではお先に。"
10052080-194 = "あ、アリスも……。"
10052080-199 = "……！？"
10052080-201 = "争いを止める道が[ruby=あなた]彼方[/ruby]に与えられた場合、彼方はその道を選択しますか？"
10052080-202 = "……先生？アリスに……何か言いましたか？"
10052080-203 = "[s] \"え？何も言ってないよ？\""
10052080-204 = "……。"
10052080-205 = "そう、ですよね……たしかに、先生の声ではありませんでした……。"
10052080-206 = "でも、どこか似ていたような……？"
10052080-214 = "自分自身を探すのは大事なことです。"
10052080-215 = "それは――彼方も。"
10052080-216 = "！？"
10052080-217 = "い、今の、ケイには聞こえましたか？"
10052080-218 = "……。"
10052080-219 = "いいえ、私には何も聞こえていません。"
10052080-22 = "……。"
10052080-220 = "――まだ。"
10052080-221 = "まだ……？"
10052080-222 = "はい。ですが……。"
10052080-223 = "アリスが何かを聞いたという事実だけは、なんとなく分かる気がします。"
10052080-224 = "ケイは何か知っているのですか！？"
10052080-225 = "その前に、どんな内容だったか覚えていますか？"
10052080-226 = "あっ……！ご、ごめんなさい……。びっくりしてよく覚えていません。"
10052080-227 = "たしか……自分自身を探すのは大事だと……そんなことを言われたような気がします。"
10052080-228 = "……。"
10052080-229 = "なるほど。でしたら……私もまだはっきりと言えることはありません。"
10052080-23 = "試すくらいなら、いいのではないですか？"
10052080-230 = "ですが、次にまた何か聞こえたら、その時はちゃんと内容を覚えておいてください。"
10052080-231 = "そして何があろうと、これだけは胸に刻んでおいてください。"
10052080-232 = "――アリスには、私がいます。先生がいます。他の皆さんがいます。"
10052080-237 = "私たちはみんな――いつまでも、アリスの味方です。"
10052080-244 = "……はい。"
10052080-245 = "ありがとうございます、ケイ。"
10052080-26 = "第一防御線、突破に成功。なんとかなったね。"
10052080-27 = "ピースピースです。#nさあ、迅速に褒めてください、先生。"
10052080-28 = "[s] \"みんなお疲れ様！\""
10052080-29 = "この勢いで第二防御線まで進撃したいところですが……。"
10052080-30 = "一旦、態勢を整えましょうか。"
10052080-31 = "どうして？私はまだいけるよ？"
10052080-35 = "ヒマリの言う通りにしましょう。#n状況は一刻を争うけれど、焦っても足元をすくわれるだけだわ。"
10052080-40 = "待ってください……外部から通信が入っているようです。"
10052080-46 = "……ひとまず、おめでとうございます。やりやがりましたね。"
10052080-47 = "預言者のみんなには……苦労ばかりかけて……ぐすっ。"
10052080-48 = "これは、最後の警告……。#n引き返して。この先はどうなるか保証できないから。"
10052080-49 = "そ、そうです……お願いですから……帰ってください……。#nわ、私たちは、誰も怪我させたくありません……。"
10052080-50 = "あなた達に……危害を加えるつもりはないんです……。"
10052080-55 = "……あの、自分たちの置かれている状況分かってますか？#nそんなこと言える立場だと思います？"
10052080-56 = "そのセリフ、そっくりそのままお返しします。#nあなた達、お姉様には手も足も出なかったじゃないですか。"
10052080-57 = "だから、脅威ですらないんです。あなた達は。"
10052080-59 = "うっ……。"
10052080-63 = "あれ？そういえば、その身体って……。"
10052080-64 = "捨て置かれていたので、少し借りただけです。何か文句でも？"
10052080-66 = "いえ、それが動いているのが不思議でして。"
10052080-67 = "そ、その身体の情報は、こちらにも共有されているんです……少しだけですけど……。"
10052080-69 = "人間に例えると、とりあえず手足だけくっつけて、無理やり動かしてるようなものだから……。"
10052080-70 = "動いているのだからいいじゃないですか！"
10052080-71 = "ティファレトの時もそうだったけど、本当に理解できないんだよね……。#nどうしてそこまで必死なの？"
10052080-72 = "いい加減、楽な生き方を受け入れたらいいのに。"
10052080-76 = "[ns] \"……。\""
10052080-85 = "[log]生きるって――呪いだと思わない？[/log]"
10052080-87 = "[log]もう十分苦しんだでしょう？[/log]"
10052080-88 = "[log]楽に生きたっていいじゃないですか。[/log]"
10052080-90 = "[log]自由は苦痛です。[/log]"
10052080-91 = "[log]生命体は、自由に伴う責任の重さに耐えられない。[/log]"
10052080-95 = "[ns1] \"まだ、考えは変わってないのかな。\"\n[ns2] \"生きることは、苦しいだけだって思ってる？\""
10052080-98 = "当然です。あなた達は、自らを騙している。"
10052080-99 = "自分の意志で生まれた人はいません。#n何も知らないまま世界に放り投げられて、名前すら自分で決められない。"
