[translation]
10052180-1 = "怒りの日"
10052180-13 = "ええっ！？なにこれ！？"
10052180-14 = "わ、私たち……空に引っ張られてる！！！"
10052180-15 = "鋼鉄大陸のエネルギーが……再び祭壇へ集まり始めたわ……！"
10052180-18 = "この地を渡れば、廃れた山の頂に祭壇を築け。"
10052180-19 = "その炭火が汝の唇に触れ、汝は清められる。"
10052180-2 = "[log][FF6666]新しい天と新しい地とを見た。[/log]"
10052180-20 = "[ruby=CAST IN THE NAME OF GOD]神の名においてこれを行い[/ruby]、[ruby=YE NOT GUILTY]ここに罪はない[/ruby]。"
10052180-25 = "ここは……？"
10052180-26 = "……「祭壇」ね。"
10052180-27 = "先生はさっきこんな場所にいたんだね……。"
10052180-28 = "[s] \"うん……。\""
10052180-30 = "で、でも、どうしてわたしたちをここに……？"
10052180-31 = "おそらく、自分の根城に「招待」してくれたのでしょう。"
10052180-32 = "この表現が正しいかは分かりませんが、とんだ自意識過剰です。"
10052180-33 = "と、トキさん！？そ、そういうのは、あんまりこういう時は……。"
10052180-38 = "[ns] \"ヒマリ！輸送船をここに呼べる？\""
10052180-39 = "ええ……可能です。この近くに駐機させてありますので。"
10052180-4 = "[log][FF6666]先の天と地とは消え去り、[/log]"
10052180-40 = "ですがどうして……？"
10052180-41 = "[ns1] \"とりあえず輸送船に戻って！\"\n[ns2] \"それから、集めた預言者のコアの分析もお願い……！\"\n[ns3] \"あと、遠隔でデータ支援もしてもらえると助かる！\""
10052180-46 = "[ns] （そして、いざとなったら……！）"
10052180-47 = "勢いでされるお願いにしては大仕事ですね。"
10052180-48 = "（まさか、いざというときを見越して……！？）"
10052180-49 = "（ですがその時、先生は……？）"
10052180-50 = "……。"
10052180-51 = "…………。"
10052180-52 = "………………。"
10052180-53 = "……分かりました。"
10052180-54 = "ユズ！モモイ！ミドリ！ついて来てください！"
10052180-55 = "わ、私たち！？"
10052180-56 = "ヒマリ先輩！？"
10052180-6 = "[log][FF6666]海もなくなってしまった。[/log]"
10052180-60 = "きゃっ！？"
10052180-64 = "……。"
10052180-65 = "[ns] \"大丈夫？\""
10052180-66 = "……人の心配している場合ですか。"
10052180-67 = "まぁ、正直に死にそうです。手足に重りをつけているような気分ですよ。"
10052180-68 = "ですがこうしている間にも、あいつは2つ目の神体にエネルギーを集中させようとしています。"
10052180-69 = "エネルギーの柱の中に隠れてコソコソと……もう何なんですか。#n世界が自分を中心に回っていないと気が済まないんですか？"
10052180-70 = "ケイ……？本当に大丈夫ですか……？"
10052180-71 = "大丈夫ですよ。#n……大丈夫じゃないですけど、大丈夫です。"
10052180-72 = "あいつに一発喰らわしてやらなければ……。"
10052180-75 = "……。"
10052180-79 = "…………。"
10052180-83 = "………………。"
10052180-89 = "死んでも！腹の虫が収まりませんから！！"
