[translation]
10051040-1 = "第4話;忍者と泥棒"
10051040-2 = "ファッションショー宴会会場内部"
10051040-4 = "ふふ～ん♪"
10051040-5 = "ふんふんふ～ん♪"
10051040-6 = "（緊張してたけど……案外やることないな……）"
10051040-7 = "（みんなマナーもいいし、特に問題もないし……）"
10051040-8 = "（イズナとツクヨと無線でおしゃべりでもしようかな？）"
10051040-9 = "（お題は……「退屈な潜入任務中に、忍者が守るべき心得」とか？）"
10051040-10 = "（「潜入中の軽食は、おにぎり派か兵糧丸派か」とか？）"
10051040-11 = "（どうせなら時間を有意義に使える話題がいいよね）"
10051040-12 = "[s] \"ミチル、ここにいたんだ。\""
10051040-13 = "うぎゃ！びっくりした！"
10051040-14 = "先生殿も来てたの！？"
10051040-15 = "はっ……さてはあの時みたいに、着替えをのぞきに来たんじゃ……！"
10051040-16 = "[s] \"違うって！\""
10051040-17 = "じゃあ……まさか先生もモデルデビュー！？"
10051040-18 = "先生殿も隅に置けないね！"
10051040-19 = "[s] \"招待状が届いたから来ただけなんだよね……。\""
10051040-20 = "なんだ、招待客だったんだ。"
10051040-21 = "ステージの上を歩く先生殿、ちょっと楽しみだったんだけどな。"
10051040-22 = "[s] \"そのつもりはないかな……。\""
10051040-23 = "ん？モデルの人生は興味ない感じ？"
10051040-24 = "そっかそっか。やっぱり先生殿は、忍者に惹かれてるってことだね！"
10051040-25 = "[s] \"どうしてそうなるの！？\""
10051040-26 = "あはは！でも、先生殿に会えて嬉しいよ。"
10051040-27 = "正直、さっきまで暇で困ってたんだ！"
10051040-28 = "もういっそのこと、誰かにアンブッシュを仕掛けようか迷ってたくらい！"
10051040-29 = "[s] \"忍者がそんなことしていいの！？\""
10051040-30 = "挨拶前の1回だけはアンブッシュが許されてるんだよ。"
10051040-31 = "でも……さすがにここではダメだよね。"
10051040-32 = "そんなわけでここでうろちょろしてたのさ！"
10051040-33 = "格式ある場だからか、本当に何も起きないし。"
10051040-34 = "[s] \"でもそういうこと言った後って、たいてい何か起きるよね？\""
10051040-35 = "先生殿、そういうのを信じるタイプ？"
10051040-36 = "こんなとこで事件が起きたって、どうせ大したこ――"
10051040-38 = "ピピピピッ！"
10051040-41 = "えぇ……？"
10051040-42 = "あれぇっ！？"
10051040-43 = "こ、これは緊急無線……！？"
10051040-44 = "アンダーカバー班、聞こえますか？"
10051040-45 = "あ、アンダーカバー01、聞こえてます！"
10051040-46 = "よく聞いてください。#n先ほど、シャインキャット様の衣装が盗まれました。"
10051040-47 = "このままでは……ファッションショーができません！！"
10051040-48 = "お客様は、シャインキャット様の衣装を見に来ているのですから！"
10051040-49 = "えぇっ！？"
10051040-50 = "現場の状況からして、犯人はまだ遠くには逃げていないはず。#n今も会場内にいる可能性が高いです！"
10051040-51 = "で、でも……どうするのさ……。"
10051040-52 = "どうするも何も、捕まえるしかありません！#nあなた達を雇った理由、忘れたとは言わせませんよ！"
10051040-53 = "そ、それはそうかもしれないけど……！"
10051040-54 = "なんとしてでも捕まえてください！分かりましたね！？"
10051040-55 = "ちょ、ちょっと待って！せめて犯人の見た目とか……！"
10051040-57 = "何を言ってるんですか？#n犯人の特徴を把握してたら、とっくに捕まえてますって！"
10051040-58 = "そ、そうかも！？"
10051040-59 = "りょ、了解です！！"
10051040-63 = "はぁ……。"
10051040-64 = "先生殿の言った通りになっちゃった……。"
10051040-65 = "……ん？先生殿も手伝ってくれるの？"
10051040-66 = "そうと決まれば……。"
10051040-67 = "すー……はー……。"
10051040-68 = "よっし、ここは忍者の本気を見せてやるしかないよね！"
10051040-69 = "アンダーカバー02、アンダーカバー03！応答願う！"
10051040-70 = "アンダーカバー02、いつでも動けます！"
10051040-71 = "アンダーカバー03も、同じく、です！"
10051040-72 = "さっきの無線、聞いてたよね？盗まれた衣装を取り戻すよ！"
10051040-73 = "犯人の特徴とか何も分からないんだけど……でも、必ず見つけ出す！"
10051040-74 = "だって忍者とは、どんな窮地でも……！"
10051040-75 = "どんな困難にも立ち向かい……！"
10051040-76 = "け、決して諦めないもの……ですから！"
10051040-80 = "よし！行動開始！！"
10051040-82 = "ファッションショー会場裏庭の森"
10051040-86 = "無事に会場を出られたな。"
10051040-87 = "配達員に変装すれば疑われない……読み通りだ。"
10051040-88 = "にしてもシャインキャット様……。#nいつもはギリギリに会場入りするのに、どうして今日に限って早く来たんだ？鉢合わせるところだったじゃん。"
10051040-89 = "ま、作品は無事に「救出」できたから良しとするか。"
10051040-90 = "この茂みの中なら、そう簡単に見つかりはしないはず……。"
10051040-91 = "ともかく、やっとシャインキャット様の作品がこの手に……！"
10051040-93 = "ああシャインキャット様……我が人生の光、我が命の焔……！"
10051040-94 = "最も偉大なデザイナーが、ショーのために作った世界でただ1着の服……！"
10051040-95 = "どんな服もいつかは誰かに着られて、そして傷んでいく。"
10051040-96 = "もっと多くの人にインスピレーションを与えられたはずの作品が、#nただの消耗品になり果てる……それこそが最大の悲劇……！"
10051040-98 = "だからこそ、「ダダイスチック・ヘルメット団」が立ち上がるしかない！"
10051040-99 = "真に偉大な服は、誰も着ないことでこそ、不滅の価値を得る……！"
10051040-100 = "この作品は保存処理を施して、永久に我々のアジトに飾っておこう……。"
10051040-101 = "ふふふ、うふふ、ふふふ……。"
10051040-107 = "……ん？ここに木なんてあったっけ？"
10051040-108 = "わ、私……木じゃない、です……。"
10051040-109 = "そりゃそうだよな。木が急に現れて、目の前を塞いだりしないか……。"
10051040-110 = "それじゃ、私はこれで……。"
10051040-111 = "い、行かせません……！"
10051040-112 = "どうして？"
10051040-113 = "服……盗みました、よね……？"
10051040-114 = "盗んだぁ！？"
10051040-116 = "これは……この服の真の価値を引き出せる場所に移してるだけだ！"
10051040-117 = "この作品が損なわれない場所へ……！"
10051040-118 = "考えてもみろよ。この傑作が誰かに着られて、汚れたり擦り切れたりしたら……#nあまりにも悲しすぎるだろ？"
10051040-119 = "ど、どんな理由であれ、窃盗は、窃盗です……！"
10051040-120 = "ちっ、これだから芸術の価値がわからない凡人は……！"
10051040-121 = "芸術とは何かも知らずに人を泥棒呼ばわりするとは……っていうか――"
10051040-122 = "誰だお前！木じゃなかったのか！？"
10051040-127 = "あ、アンダーカバー03より報告！犯人を発見！裏庭の彫像の隣です！！"
10051040-128 = "くそっ、警備だったのか！どけっ！"
10051040-129 = "いや……です！"
10051040-130 = "私……忍者ですから！！"
10051040-131 = "忍者ぁ？"
10051040-142 = "ファッションショー会場内部"
10051040-144 = "イズナ、無線聞いてたよね？犯人は裏庭だよ！"
10051040-145 = "イズナ、出動します！"
10051040-147 = "ファッションショー会場裏庭の森"
10051040-148 = "はぁ、はぁ……こいつ、強い……！"
10051040-159 = "に、忍者は……決して諦めません……！"
10051040-160 = "だからその忍者ってなんなんだよ！？離せよ！"
10051040-161 = "は、離しま、せん！！"
10051040-163 = "[ns] \"ツクヨ、よく頑張ったね。\""
10051040-164 = "ここからは……！"
10051040-165 = "私たちも一緒に戦います！ニンニン！"
10051040-169 = "忍術研究部、推参！"
10051040-170 = "部長……！イズナちゃん……！"
10051040-171 = "3対1だと！？卑怯者！"
10051040-172 = "衣装泥棒に言われたくないんだけど！？"
10051040-173 = "う、うるさい！盗んだんじゃない、ちゃんと扱われる場所に移すだけで――"
10051040-174 = "くっ、もういい！こうなることくらい、最初から想定済みさ！"
10051040-176 = "ダダイスチック・ヘルメット団！集合！！ "
10051040-185 = "同胞たちよ！この作品を無事に運びきるまで――"
10051040-186 = "私を守れええ！！！"
