[translation]
10052120-1 = "儀式"
10052120-100 = "鋼鉄大陸の外側にいた預言者たちは、その残骸が……残りますよね……？"
10052120-101 = "そうだろうけど……それで？"
10052120-105 = "……待って、まさか？"
10052120-106 = "そのまさかです。"
10052120-107 = "できるの！？"
10052120-108 = "ここまで運んでくれば、ですが……。"
10052120-109 = "問題は運搬のほうか……。"
10052120-11 = "うああああああ！？！？"
10052120-111 = "しかも、こっそりやらないといけませんし……。"
10052120-113 = "ただでさえ難しいのに、さらに条件が加わるなんて……。"
10052120-114 = "無謀でしょうか……？"
10052120-115 = "……。"
10052120-116 = "いいや、仕事は難しいくらいがちょうどいいよ。"
10052120-12 = "第二防御線まで……？嘘でしょう……？"
10052120-121 = "おぉ、さすがです、ソフ！"
10052120-123 = "ほ、本当ですか！？"
10052120-124 = "うん。レイバーの生産は、まだ少し余力があるから。"
10052120-125 = "よ、良かったです！じゃあ私も……！"
10052120-126 = "ううん。アインは残ってて。"
10052120-127 = "はい……！？#nや、やっぱり私は頼りないから……。"
10052120-128 = "違う違う。アインが一番重要だからだよ。これからすごく忙しくなるんだから。"
10052120-129 = "……わ、私がですか？"
10052120-130 = "そうです。この先、アインがいないと私たちは何もできませんので。"
10052120-135 = "は、はいぃぃっ！？！？"
10052120-136 = "アイン、よく聞いて。#nやってもらいたいことは大きく分けて2つあって……。"
10052120-144 = "……分かった？"
10052120-149 = "……。"
10052120-150 = "アイン？大丈夫ですか？"
10052120-156 = "アイン！？"
10052120-157 = "やっぱり、プレッシャーが大きすぎましたかね。"
10052120-158 = "ですが……アイン、お願いします。"
10052120-159 = "これの如何によって、私たちの可能性は大幅に減ってしまうんです。"
10052120-160 = "マルクトお姉様の強化は、頑張れば私たちでも何とかできるかもしれません。"
10052120-161 = "ですがもう1つは、アインにしかできないのです。"
10052120-166 = "……。"
10052120-167 = "分かりました。やってみます。#n……いえ、やります。"
10052120-168 = "絶対に、必ず！死ぬ覚悟で！"
10052120-169 = "いえ、死んでも！"
10052120-17 = "……。"
10052120-170 = "落ち着いて、アイン……。#n私たちの中で誰一人そうならないためにやるんだから。"
10052120-171 = "そ、そうですよね……！"
10052120-172 = "でも……それくらい頑張ります！"
10052120-173 = "まあ、流石に例え話で言っているのでしょうけど……。"
10052120-178 = "……。"
10052120-179 = "ありがとうございます、アイン。"
10052120-18 = "状況を整理しよう。"
10052120-180 = "我の身体を、よろしくお願いします。"
10052120-181 = "はい！！！"
10052120-190 = "実在と非実在の区別を問うことは、もう古いでしょう。#n両者の違いは、対象の受け取り方が異なる程度のことですから。"
10052120-191 = "なにせ、両者に大きな違いはありません。"
10052120-192 = "例えば、虚数は存在します。#n左右が反転し、時間が逆行する宇宙が存在する可能性があるのと同じように。"
10052120-196 = "！！！"
10052120-197 = "聞きましたか？"
10052120-198 = "は、はい！今回はその内容をちゃんと……！"
10052120-199 = "内容は……！"
10052120-20 = "は、はい……！#nの、残りの預言者のエリアは……2つだけです。"
10052120-200 = "うわぁーん！覚えているのに説明できません！"
10052120-201 = "大丈夫です。私も聞きましたので。#n多元宇宙に関する比喩でした。"
10052120-202 = "たげん……うちゅう……？"
10052120-203 = "左右が入れ替わり、時間が逆行する宇宙のことです。"
10052120-204 = "おかしく思えますが、存在しないという証拠はありませんので。"
10052120-205 = "……ということは、あの声の主は、まさか……。"
10052120-206 = "ケイ？何か分かりましたか？"
10052120-207 = "実は、まったく見当がつかないわけではありません。#nですが……だからといって、これを説明するわけにはいかないんです。"
10052120-208 = "ごめんなさい、アリス。あなたにだけは隠し事をしたくないのですが……これは、あなたにだけは言えないかもしれません……。"
10052120-209 = "……。"
10052120-21 = "[ruby=ネツァク]鋼鉄大陸[/ruby]は、すでに70％以上を敵に占領されています。"
10052120-210 = "それは、アリスと先生、みんなのやるべきことが変わってしまうような問題ですか？"
10052120-211 = "はい？いいえ……違うと思います。ただ……。"
10052120-212 = "もしも、あれが介入してきたら……。"
10052120-213 = "……分かりました。アリスは、アリスがやるべきことを続けます。"
10052120-214 = "分からないことについて深く考えても、あまり良いことはないので。"
10052120-218 = "……そうしましょう。#n残りのエリアは……あと2つだけですからね。"
10052120-22 = "……残る2つのエリアも、時間稼ぎにしかならないでしょう。"
10052120-24 = "多分、突破されるだろうね。"
10052120-25 = "うぅ……！"
10052120-26 = "アイン、落ち着いて。認めるものは認めないと。善後策を考えるためにも。"
10052120-27 = "ど、どこから……間違ってしまったのでしょう……。"
10052120-28 = "や、やっぱり、私があの人たちを見くびったせいでしょうか……！？"
10052120-29 = "ごめんなさい、ソフ……ごめんなさい、オウル……#nごめんなさい、お姉様、うえぇーん！！"
10052120-34 = "大丈夫ですよ、アイン。アインは何も間違っていません。"
10052120-35 = "[ruby=つかつき]調月[/ruby]リオという、想定外の変数が紛れ込んだのですから。"
10052120-36 = "あるいは、王女と[ruby=侍女]鍵[/ruby]が原因かもしれません。"
10052120-37 = "それを言うなら、先生だって……。"
10052120-38 = "……。"
10052120-39 = "あとは……あっちの戦闘力が想定より高かったからかも……。"
10052120-41 = "わ、私たちが鋼鉄大陸を、予定を早めて展開したせい……でしょうか……？"
10052120-43 = "でも、あのときに展開していなかったら……こうしてお姉様と会うこともなかったと思いますよ。"
10052120-44 = "うん……。"
10052120-46 = "ええ。その点について、アイン、ソフ、オウルに感謝しています。"
10052120-47 = "お姉様……。"
10052120-48 = "ソフもオウルも、こちらへ来てください。#n我が抱きしめてあげます。"
10052120-53 = "え、ええ……？"
10052120-61 = "これは、何かを打開できる行為ではありません。"
10052120-62 = "いわば、意味のない行為なのかもしれません。"
10052120-63 = "ですが……少し、心が落ち着きませんか？"
10052120-64 = "リラックスできれば、良いアイデアが浮かぶかもしれません。"
10052120-68 = "うっ……うえぇぇん……。"
10052120-69 = "思いっきり泣いてください。ここには我々しかいません。"
10052120-70 = "大丈夫です、我がいます。我はアイン、ソフ、オウルに出会えて本当に嬉しく思っています。"
10052120-76 = "私たちは鋼鉄大陸の統制権を奪われ続けてる。"
10052120-77 = "ですが、まだそこまで深刻な問題ではないとも言えます。"
10052120-78 = "あの鍵……ケイが使っている「身体」を取り戻せば、すべて元通りです。"
10052120-79 = "け、結局……セキュリティレベルとアクセス権の問題ですから！"
10052120-80 = "鋼鉄大陸の拡張は止まったけど、それも何とかできるはず。"
10052120-81 = "ネツァクの各エリアの統制権を取り戻せばいいからね！"
10052120-82 = "残りの戦力は2体の預言者。"
10052120-83 = "そして――"
10052120-84 = "我、ですね。"
10052120-85 = "……。"
10052120-86 = "前は、我に与えられた出力が強すぎるが故、身体がもちませんでした。"
10052120-87 = "つまり[ruby=強度]耐久度[/ruby]の問題さえ解決できれば、我はすべての[ruby=出力]可能性[/ruby]を余すことなく発揮できるはずです。"
10052120-88 = "それを解決するのは、私たちの仕事ですね！"
10052120-89 = "か、必ず完全な姿で、お姉様を羽ばたかせてあげます！！！"
10052120-90 = "一応、預言者を活用できる余地も、僅かですが残っています。"
10052120-92 = "そうなの？"
10052120-94 = "アイン、説明をお願いします。"
10052120-98 = "えっと……。"
10052120-99 = "鋼鉄大陸の内側にいた預言者たちは、ネツァクの一部へと戻ることになりますが……。"
