[translation]
10052070-1 = "ケセド： 慈悲深き苦痛をもって断罪する裁定者 "
10052070-2 = "ひーまーすーぎー！！"
10052070-3 = "また始まった。お姉ちゃん、そんなこと言ってる場合じゃないでしょ。"
10052070-4 = "だって私たちだけお留守番なんだよ？先生も行っちゃったし！"
10052070-5 = "遊びに来たわけじゃないんだから。敵地のど真ん中だってこと、忘れてない？"
10052070-6 = "……ここの預言者って名前なんだっけ。ケセド？"
10052070-7 = "うん。"
10052070-8 = "ケセドってどんな子なのかな……。"
10052070-9 = "そんな友達みたいな呼び方して……。#nたしか、何かの工場だったって言ってたよ。"
10052070-10 = "ミレニアムの廃墟にあったんだっけ？#nあそこ、懐かしいよね……。"
10052070-11 = "うん、G.Bibleを探しに廃墟まで行って――"
10052070-13 = "アリスちゃんを見つけたんだよね。"
10052070-16 = "ケセドってもともとは、[ruby=Divi:Sion]ディビジョン[/ruby]……だっけ？#nそれを生産するAIなんだよね？"
10052070-17 = "その名前、あんまりいい思い出ないかも……。#nタコかイカみたいな機械のことだよね？"
10052070-19 = "それがケイとも関係してたし……え、待って。#nってことは、ケセドって、私たちとすっごい縁があるんじゃない！？"
10052070-20 = "それなのに輸送船で待機だなんてー！ひどいよー！"
10052070-21 = "仕方ないよ。ケセドは工場だし、物凄い量の兵力を生産してるんだから。"
10052070-22 = "それに対応するには、こっちも戦力の出し惜しみはできないって話だったし。"
10052070-23 = "私たちは戦力外ってこと！？"
10052070-24 = "お姉ちゃんが居残り組のくじを引いたからでしょ……。"
10052070-25 = "ぐえっ、そ、それは……。"
10052070-26 = "まあ、少しは休憩になるからいいんじゃない？"
10052070-30 = "……私たちさ。"
10052070-31 = "うん？"
10052070-32 = "ほんと、色んなこと経験してるよね。"
10052070-33 = "廃墟に、宇宙に、今度は鋼鉄大陸……。"
10052070-34 = "私たちはゲームを作ろうとしてただけなのに……。"
10052070-35 = "なに言ってんのさ。これも全部ネタになるんだよ！"
10052070-36 = "それ、宇宙に行ったときも言ってたけど、結局活かしてないよね……？"
10052070-47 = "な、なにごと！？"
10052070-51 = "お姉ちゃん、あっち！"
10052070-58 = "えっ！？あれは……レイバー？"
10052070-60 = "他にも兵力が襲ってきてるよ！"
10052070-65 = "輸送船、聞こえますか？"
10052070-66 = "ごめんなさい。レイバーと一部の兵力を取り逃がしました。#nそちらに向かっています！"
10052070-67 = "輸送船の防御システムは貧弱ですが……どうにか、こちらから稼働させます。#nですので――！"
10052070-71 = "……。"
10052070-72 = "心配しないで、ヒマリ先輩。私たちが守り抜くよ。"
10052070-73 = "お、お姉ちゃん！？"
10052070-74 = "このままじっとしてるわけにもいかないでしょ？#n私たちのスーツは安全性重視だし、なんとかなるって！"
10052070-75 = "みんなが頑張ってるのに、私たちだけ遊んでられないもん！"
10052070-76 = "モモイもミドリも、他のエリアでは十分頑張ってくれていましたよ？"
10052070-77 = "今は役割として、輸送船に残ってもらっているだけですから……。"
10052070-78 = "そんなの関係ない！"
10052070-82 = "……。"
10052070-83 = "うん。分かった。"
10052070-84 = "ヒマリ先輩。ここは私たちで何とかします。"
10052070-98 = "ど、どうすれば！？"
10052070-99 = "今からでもモモイとミドリのところに戻るべきでしょうか？"
10052070-100 = "……。"
10052070-101 = "それもありだけど、できればここのエリアを占領してからのほうがいいと思う。"
10052070-102 = "私も同意見です。"
10052070-103 = "いま引き返すと、戦線が二手に分かれてしまう可能性もあります。"
10052070-104 = "ここはモモイとミドリを信じましょう。"
10052070-105 = "他ならともかく、ここはケセドのエリアよ。"
10052070-106 = "多少の消耗戦は仕方ないわ。"
10052070-107 = "だけど万が一のために、ヒマリとアリスはこのエリアを離れる準備をしておいてちょうだい。"
10052070-108 = "なぜ私とアリスを？"
10052070-109 = "この中で、最も機動性に長けているからよ。"
10052070-110 = "合理的ですね。分かりました。"
10052070-112 = "[ns1] \"……なるべく早くケセドを攻略しよう。\"\n[ns2] \"そして、モモイとミドリのところに戻ろう。\""
10052070-115 = "はい。では、先生――お願いします。"
