[translation]
10050070-1 = "第7話;One Last Chance"
10050070-100 = "稼ぎを得られて、宣伝までできればラッキー、ってわけで。"
10050070-101 = "わがままで欲張りで、こじれた人間と思うかもしれません。でも部長はそんなお方です。"
10050070-102 = "他の人の前じゃ絶対に認めようとしないと思いますが。"
10050070-103 = "だってあんな人です。才能だのリングだの言いながら……。"
10050070-104 = "なぜ自分のことを素直に打ち明けたのだと思いますか？"
10050070-105 = "チャンピオンを羨んだのも……才能がないと嘆きたいのも……。"
10050070-106 = "誰なのでしょうね？"
10050070-107 = "[s] \"もしかしてその話は……。\""
10050070-108 = "ふふっ。語らないことで、完成に近づく物語もあるのですから。"
10050070-109 = "……変なこと言わないでください、タカネ。縁起でもない。売り上げに響いたらどうするつもりですか。"
10050070-110 = "はい、はい。分かりましたよ。"
10050070-112 = "[ns9] \"二人の言いたいことは分かったよ。\"\n[ns10] \"でもやっぱり嘘をついてまでやるのは危険だと思う。\""
10050070-115 = "ん？嘘ってどういう……？"
10050070-116 = "[s11] \"タカネが姫君だった、とか……。\"\n[s12] \"他にもいろいろあったでしょう？\""
10050070-119 = "ど、どうして先生がそれを……！もしかして、タカネ！？"
10050070-120 = "反省してください部長！あれはどうみてもやり過ぎだったでしょう？"
10050070-121 = "今だって恥ずかしくてしょうがないんですから……！"
10050070-122 = "[s13] \"とにかく私からも言ってみるから。\"\n[s14] \"今回の件はここまでにしよう。\""
10050070-125 = "はぁい……。"
10050070-132 = "た、たいへん！先生！正義実現委員会が……そっちに向かってる！"
10050070-14 = "こ、こんにちは先生。本当にトリニティにいらしたのですね……。"
10050070-15 = "トリニティで先生を……それもこんな場所でお会いするとは。"
10050070-16 = "[s1] \"緊急事態みたいだからすぐ本題に入るね。\"\n[s2] \"ヤクモ、どうしてこんな事をしたの？\""
10050070-19 = "うっ……雑談とか、アイスブレイクはなしですか……。"
10050070-2 = "あ……先生、こんにちは。"
10050070-20 = "分かりました、分かりましたよ……はぁ。"
10050070-21 = "要は、お金を稼ぐためです。"
10050070-22 = "正直すぎるのでは……。"
10050070-23 = "ですが本当のことですから……。"
10050070-24 = "……えっ？それだけじゃ納得ができない……？ビジネスマンらしくない？"
10050070-25 = "他の自治区で商売するのはリターンに対してリスクが大きすぎる……？"
10050070-26 = "[s] \"ヤクモならそれくらい計算すると思ってた。\""
10050070-27 = "いやいやいや、私の能力はそんなたいしたものじゃありませんよ！？"
10050070-28 = "……ぐっ、そんな疑うような目をしなくても。"
10050070-29 = "……はぁ。"
10050070-3 = "えっと、話はある程度聞いてます……どうぞ中へ。"
10050070-30 = "分かりましたよ、はい。先生もすぐに答えが聞きたいようですし……。"
10050070-31 = "こんなにすぐに本題に入るのは、いささか慣れませんが……あっ、もしかしてこれが大人の会話術ってやつでしょうか。"
10050070-32 = "先生……「文化」は何をエサに大きくなると思いますか？"
10050070-33 = "[s] \"ん……人々の興味と愛？\""
10050070-34 = "そうですか、なるほど……。"
10050070-35 = "それは、間違った考えですね。"
10050070-36 = "文化というのは……お金を食い物にして成長する生き物です。#n本質的に我々と変わりません。"
10050070-37 = "過激な発言、と思いましたか？しかし……これが現実なのです！"
10050070-38 = "文化媒体を享受するということは……言い換えれば、そこに自分の時間とは別の交換価値。つまりお金を消費するという話。"
10050070-39 = "……そして人々は消費行動に対価を求める。楽しさや笑顔、まあそういった類のものです。"
10050070-4 = "[s] \"ごめんね、ウイ。\""
10050070-40 = "もしくは感動や教訓でも構いませんがね。"
10050070-41 = "先生。1日でどれだけの文章が書かれているか、考えてみたことありますか？"
10050070-42 = "良いものを書けば読んでもらえるはず、と思っている方も多いですが……そんなものは幻想です。"
10050070-43 = "なぜなら今この瞬間でさえ……あまりにもたくさんの文章や、情報が溢れています。"
10050070-44 = "「1日で」と言いましたが、実際は1時間――いいえ1分1秒単位でです。"
10050070-45 = "そのほとんどは忘れ去られ、無に帰る。"
10050070-46 = "それってなんだか……悲しくないですか。"
10050070-47 = "[s] \"……。\""
10050070-48 = "せめて市場というリングに上がれたならまだいい方でしょう。"
10050070-49 = "ある人は「次はもっと頑張ろう」と思ったり、ある人は何か学びを得るはず。"
10050070-5 = "い、いえ……先生はここに来ても大丈夫なので……。"
10050070-50 = "もしくは自分の目指す道はこれではなかった、と諦めたり。"
10050070-52 = "しかし大多数はリングにさえ上がれず……。"
10050070-53 = "トロフィーを手にしたチャンピオンを見て羨ましがるだけです。"
10050070-54 = "子供の頃を覚えてますか？子供たちは、いつだって自分ではない何かになりたがります。"
10050070-55 = "ああいうものを作りたい。自分を証明して認められたい……。"
10050070-57 = "まあ、子供に限った話ではありません。誰だってそう思うのは自然なこと。"
10050070-58 = "ですが夢だって、月日が経てば輝きを失ってしまうもの。"
10050070-59 = "夢がないというのも悲しいですが、いつまでも夢に囚われるのは悲劇です……だって。"
10050070-6 = "というか先生と私と……あの二人を合わせたら……全部で4人？"
10050070-60 = "夢を見させるなら――"
10050070-61 = "――才能も与えるべきである、と。そう思いませんか？"
10050070-63 = "[ns3] \"こういうこと言うのもなんだけど……。\"\n[ns4] \"まだ若いでしょ！？\""
10050070-66 = "……そうですねぇ。"
10050070-67 = "でもこう思わざるをえない子どもだって、どこかにいるはずです。"
10050070-68 = "とにかく。私はこれが言いたかったのです。"
10050070-69 = "自分の夢と向き合い、ぶつかったり前に進むためにも、一度リングに上がるべき、と。"
10050070-7 = "う、うう……古書館に4人は、多すぎるような……。"
10050070-70 = "リングに上がるために、宣伝はあるものだ、と。"
10050070-71 = "戦うチャンスも得られずに、敗北宣言をされるんじゃあんまりです。"
10050070-72 = "だからお金は大事です。リングまでの道に繋がるのですから。"
10050070-73 = "文化はお金という土壌で育ち、誰かはその土壌を管理するべきです。"
10050070-74 = "まあそれで……今回の件が起きた、ってことですかね。"
10050070-78 = "[ns5] \"でも、それだけお金が必要なら……。\"\n[ns6] \"出版じゃなく他のことじゃダメなの？\""
10050070-8 = "[s] \"な、なるべく静かにするから！\""
10050070-81 = "……えっ！？"
10050070-82 = "[s7] \"お金になる仕事は他にもたくさんあるはず。\"\n[s8] \"流通や金融関連とかさ。\""
10050070-85 = "ぐふっ！？"
10050070-86 = "するどい……ご指摘……ですね。"
10050070-9 = "はい……それじゃ、こちらへ……。"
10050070-91 = "[ns] \"言い過ぎちゃったかな。\""
10050070-93 = "い、いえ！ごもっともな指摘でしたわ先生！あの状態になった部長は、歯止めが利かないんですから！"
10050070-94 = "ただ……部長の言いたいことも分かります。"
10050070-95 = "先生のおっしゃる通りで……本当にただお金が必要なら、出版業をするはずありません。"
10050070-96 = "[s] \"じゃあヤクモは……？\""
10050070-97 = "ふふっ。どうでしょうね？"
10050070-98 = "そして評論家の私が部長のところに居るのも……。ええ、お察しの通りです。"
10050070-99 = "結局は好きだからこの仕事をしているのです。"
