[translation]
10052055-10 = "どうして……争いが生まれるのでしょうか。"
10052055-11 = "[ns] \"お互い、譲れないものがあるからじゃないかな。\""
10052055-12 = "もちろん、譲れないものは誰しもにあると思います。"
10052055-13 = "ですが……それが何なのかすら、お互いに知らない状況なのに……。"
10052055-17 = "……いつか、生命体は和解できるのでしょうか。"
10052055-18 = "[s] \"私は、できると信じたいよ。\""
10052055-19 = "今は、まだ信じきれていないのですね。"
10052055-2 = "なんとかなりましたね……。"
10052055-20 = "[s1] \"そうとも言えるけど。\"\n[s2] \"それでも、ね。\""
10052055-3 = "……。"
10052055-4 = "[s] \"なにか、気になることでもあるの？\""
10052055-5 = "気になる……というほどではありません。"
10052055-6 = "……そもそも、誰かを気にしている余裕もないですし。"
10052055-7 = "でも……。"
10052055-8 = "先生。"
10052055-9 = "[s] \"うん？\""
