[translation]
10052105-12 = "私からすれば、あなたのほうがより不自然ですが……。"
10052105-2 = "コアのデータを回収しに来たよ。"
10052105-3 = "うん？ああ、部長なら「人選ミスだった」って言って、さっさと輸送船に戻っちゃった。"
10052105-4 = "[s] \"エイミはどう？\""
10052105-5 = "良い感じではあるけど……まだ足りない。本物の氷河なら良かったのに。"
10052105-6 = "作られた環境だと、本物の自然には勝てないのかな……？"
