[translation]
10050010-1 = "第1話;観賞用・保存用・布教用"
10050010-6 = " ……。"
10050010-7 = " ……。"
10050010-8 = "こ……これでいいのでしょうか。"
10050010-9 = "こんなあっさり学園に入れるとは……。"
10050010-10 = "ふむ……検問があったり監視の一人二人つくと思っていたのですが。#nこれでは賄賂による買収もできないじゃないですかぁ。"
10050010-11 = "……そんなこと考えていたんです？"
10050010-12 = "ええ。計画を立てる時は、常に最悪の状況を考えておくものですよぉ。"
10050010-13 = "その意見には同意いたしますが……。"
10050010-14 = "さすがに拍子抜けといいますか……#n現実なのか疑わしいくらいですわね。"
10050010-15 = "現実じゃなくとも我々はこの在庫を処理……頒布しなければなりません。"
10050010-16 = "たとえ仮想空間だとしても、仮想紙幣をたっぷり持ち帰らせてもらいますよぉ！"
10050010-23 = "あら？ごきげんよう。初めまして……ですよね？"
10050010-24 = "ど、どうしましょう部長！？"
10050010-25 = "……。"
10050010-26 = "ごきげんようでございます！いやぁ、これも何かの縁でしょうか。#n我々はレッドウィンター連邦学園から――そう！#nトリニティの見学に参った者です！"
10050010-27 = "そ、そんな堂々と言ってしまってよいのですか！？"
10050010-28 = "落ち着いてくださいタカネ。#n何かあっても自治区から追い出されるだけです。"
10050010-29 = "何かを隠そうとして誤解を招くより、よほどいいのでは？"
10050010-30 = "あら、レッドウィンターからはるばる！そうだったのですね。トリニティへようこそ。#nお噂はかねがね……。"
10050010-31 = "いつも極寒のなか、獰猛な熊を相手に鍛錬されているのですよね？"
10050010-32 = "い、一体何のお話でしょうか……熊？"
10050010-33 = "まぁまぁ、合わせればいいんですよ。"
10050010-34 = "え、ええ……その……。"
10050010-35 = "急な訪問で驚かれたのでは？"
10050010-36 = "いえ、そんなことありませんわ。どうぞごゆっくり見ていかれてくださいな。"
10050010-37 = "ああ、ですがそうですね……トリニティは閉鎖的な面があると言われたりもしますが――"
10050010-38 = "皆がそういうわけではありません。私たちも日々変化しようとしております。"
10050010-39 = "キヴォトス三大学園の名に恥じぬよう、他学園の方々との交流に力を入れているのですよ。"
10050010-40 = "なるほど……ときに、本はお好きですか？"
10050010-41 = "本……？ええ、趣味で少々。#n礼拝の時間には経典を読んでおりますし。"
10050010-42 = "それに、トリニティの中央図書館にはキヴォトスで出版された本のほとんどがありますから。"
10050010-43 = "ふむ、それは良いことを聞きました！#n少々特別な本があるのですが……ご興味はありませんか？"
10050010-48 = "いかがでしょう、一度ご覧になってみませんか？数ページでも構いませんので。"
10050010-49 = "あら、良いのですか？"
10050010-50 = "では拝読しますね……。"
10050010-55 = "こ、これはっ！？"
10050010-56 = "はわわ……。"
10050010-62 = "ぶ、部長一体何をしたのですか！？"
10050010-63 = "こっちが聞きたいくらいですよぉ……。"
10050010-64 = "まずは起きてもらいましょうか。#nはい、こちらのカンポットをどうぞ、227号特製のものです。"
10050010-65 = "うぅっ……！？あ、ありがとうございます。#n目が覚めましたわ……それよりも、そちらの本――"
10050010-66 = "……。"
10050010-67 = "なんといいますかその……イヤ、ではなかったのですが。"
10050010-68 = "むしろ好きといいますか……ですが、その……。"
10050010-69 = "いろいろな意味で、刺激が強すぎるような……。"
10050010-70 = "えっ？これが……？"
10050010-71 = "（ほう……もしやトリニティではこの程度で？）"
10050010-72 = "なるほど、そうですか！とはいえ、さほど問題になるような部分はないはずです。"
10050010-73 = "いえ、問題になるようなシーンは描写されておりません！#nちゃんと検閲――編集しておりますので。"
10050010-74 = "え、ええ……そう、ですね。"
10050010-75 = "だからこそ……より想像がふくらむ、といいますか……。"
10050010-76 = "[ruby=・]お[/ruby][ruby=・]客[/ruby][ruby=・]様[/ruby]はとてもお目が高いですね。"
10050010-77 = "（お客様……？）"
10050010-78 = "やはり、こういうものには適度な「ベール」が大切ですので。"
10050010-79 = "……作家という生き物は、暴走しがちといいますか。#n一を知って二を知らず、といいますか。"
10050010-80 = "物語において、最も大切なのは想像の余白だというのに！！"
10050010-81 = "そ、そうなのですね！？"
10050010-82 = "ええ。なぜなら人の想像力に限界はないのですから！"
10050010-83 = "余白を与えれば与えるほど、読み手側はその先を妄想するというものです！"
10050010-84 = "た、たしかに言われてみれば……！"
10050010-85 = "……さきほど、検閲と言っていませんでした？"
10050010-86 = "編集ですよ？"
10050010-87 = "はぁ……。"
10050010-88 = "まあ、検閲に近しいものは行いましたが、仕方なくですよ。#n事務局に言われちゃあね。"
10050010-89 = "しかし、これだけは知っておいてくださいタカネ。#nモノを売るのであれば……障害を逆に利用してこそ、ですよ！"
10050010-90 = "つまり検閲を盾に、商品性を高めると……？"
10050010-91 = "ご名答。上にはご希望通りに検閲を行ったと言えますからね。"
10050010-92 = "消費者からすれば、満足のいくものを手に入れられるかもしれませんよぉ？"
10050010-93 = "ほら。こちらがいい例です！"
10050010-94 = "は、はわわ……。"
10050010-98 = "……。"
10050010-99 = "さすが部長ですわ！本当にこういう時は頼りになりますわね！"
10050010-100 = "あ、あの……続きの本はないのですか？"
10050010-101 = "もちろんありますとも！もしよろしければ、周りのお友達にもそれとなーく勧めてはいただけませんかぁ？"
10050010-102 = "ひゃ……！？"
10050010-103 = "本は物理的な限界を持つ媒体……1つの本が別の場所に存在することは不可能です。"
10050010-104 = "そういった意味で、もう1冊いかがでしょう？"
10050010-105 = "たしかにそうですが……同じものを2冊も？"
10050010-107 = "1冊は自分用。もう1冊はご友人に貸す用、ですわ。"
10050010-108 = "同じ文化を共有することで、より広く深い交友関係を築くことも可能ですから。"
10050010-109 = "た、たしかに……！"
10050010-110 = "ところで、本当にそれだけでよいのですかぁ？"
10050010-111 = "本は読めば読むほど脆くなり、いつか壊れてしまうもの……。"
10050010-112 = "あっ……！"
10050010-113 = "そんな方々のためにこちらもご用意しました。"
10050010-114 = "万が一に備え、保管用にもう1冊いかがでしょう？"
10050010-115 = "ご存じかもしれませんが、こういうものは観賞用、保存用、布教用と3冊持っておくのが一般常識として知られていますわ。"
10050010-116 = "（そんな常識があったなんて……！）"
10050010-117 = "し、しかしそれでは結局、同じ本を3冊買うということで……？"
10050010-118 = "そんなあなたのためにっ！今だけ3冊お買い上げで！通常価格から15%割引いたします！"
10050010-119 = "買いますわ。"
10050010-120 = "毎度あり！お友達にもぜひオススメしてくださいねぇ。"
10050010-126 = "それで、どうでしたか？タカネ。"
10050010-127 = "ええと、いろいろと申し上げたいことはありますが……。"
10050010-128 = "やはり、こういう時の部長はさすが、といったところでしょうか。"
10050010-129 = "結構結構。ムフフフフ。"
10050010-133 = "では……トリニティを――本格的に我々色に染めて差し上げましょう！"
10050010-135 = "……ねえ知ってる？#n最近流行ってるあれ……。"
10050010-136 = "色々あると思いますが、どれのことですか？"
10050010-137 = "ええと……。"
10050010-138 = "あら、もしや……？"
10050010-139 = "私、続きを持ってるんだけど……読む？"
10050010-140 = "ええ！よければ今日お邪魔しても？"
10050010-141 = "もちろん……！#n「芸術」を分かち合える人が増えて嬉しいわ！"
10050010-143 = "こういうの、大丈夫かしら……？"
10050010-144 = "……幻滅しちゃった？"
10050010-145 = "ううん、「芸術」はあらゆる者に喜びを与えるものだから。"
10050010-146 = "ええ……では、シスターの名に体を預けて……。"
10050010-155 = "これは……？"
10050010-156 = "期待には沿えないかもですが、こんな展開だったらどうだろう……？と想像して作ってみたのです。"
10050010-157 = "も、もちろん原作には到底及ばないと思いますが……。"
10050010-158 = "ありがとう、読んでみる。"
10050010-159 = "ありがとうございます！"
10050010-171 = "……いい茶葉ですね。"
10050010-172 = "はい、今回はかなり気合いを入れました。"
10050010-177 = "ええ。味や香り、どれをとっても素晴らしいです。#nダージリンベースでブレンドしたアールグレイですね？"
10050010-178 = "軽やかなマスカットと、しっかり香るシトラスが印象的です。#nベルガモットが新鮮な証なのでしょう。"
10050010-179 = "改めて、素敵な一杯をありがとうございます。"
10050010-180 = "とんでもありません！お気に召したようでなによりです。"
10050010-183 = "平和ですね……ええ、本当に……#n癒される時間です……。"
10050010-184 = "先生がここに居れば、なお良かったのですが……いえ、足るを知らなくては。"
10050010-186 = "そういえば、最近トリニティで面白い本が流行っているそうですね。"
10050010-187 = "面白い本……ええ、はい！ちょうど私も手に入れまして。"
10050010-188 = "まだ中身は読んでいないのですが、評判が良いみたいですよ。"
10050010-189 = "あら、それは良いニュースですね。"
10050010-190 = "ですが、少々気になるところもありまして……。"
10050010-191 = "その本の話題になると、急に声を潜めたり、席を外す方がいるんです……。"
10050010-192 = "ふふっ。きっと親睦を深めているのでしょう。#n良いことではありませんか？"
10050010-193 = "それだけ面白い本なのですから、通じ合う者同士話したいことがあるのでしょう。"
10050010-194 = "そうですよね……？私もそうだと信じています。"
10050010-195 = "よろしければ、私にも見せていただけませんか？#n少々気になっておりまして。"
10050010-196 = "ええ、どうぞ。こちらです。"
10050010-200 = "ありがとうございます。#nそれでは……。"
10050010-205 = "……？"
10050010-209 = "！？！？！？"
10050010-215 = "な、ナギサ様……？#nナギサ様――っ！？！？"
