[translation]
10050030-1 = "第3話;確定申告"
10050030-10 = "それに……想定以上の部数が出ましたし、これである程度出張費はカバーできたはずですわ。"
10050030-100 = "つまり何が言いたいのです？"
10050030-101 = "要はこういうことです、聞いてください。#nこれも全部宣伝活動の一つとするんです……なので……。"
10050030-106 = "正義実現委員会・教室"
10050030-107 = "こんにちは先生、シミコさん！今日も正義のために前に進みましょう！"
10050030-108 = "[s] \"こ、こんにちはマシロ。元気いっぱいだね。\""
10050030-109 = "すごく気合が入ってますね、マシロさん……。"
10050030-11 = "そうですねぇ。改めて売上を見てみましょうか。"
10050030-110 = "あっ、ビックリさせてしまってすみません。図書委員会との協力、それに先生もいらっしゃるもので、ついはしゃいでしまいました。"
10050030-111 = "なにより、非公認の書籍だなんて。これだけ正義とそぐわない物も他にないはず。"
10050030-112 = "どこからどう見てもいかがわしくて怪しい、そんなものは……！"
10050030-113 = "根絶やしにすべきです！"
10050030-114 = "[s] （情熱がどうやら変な方向に向いているような……）"
10050030-115 = "ところで、内容は読まれましたか？マシロさん。"
10050030-116 = "読む必要はありません。正義に反している事実さえあれば十分ですから。"
10050030-117 = "そ、そうですか……？"
10050030-118 = "それに、私たちの時間は限られています……。"
10050030-119 = "なので、他の正義実現委員会のメンバーを、トリニティ各地に派遣しておきました！"
10050030-12 = "いやぁ、やっぱりこの瞬間が一番ドキドキしますねぇ。どれどれ……。"
10050030-120 = "すぐにでも、非公認書籍が取引される場所が特定されるでしょう。"
10050030-121 = "[s] \"もう！？\""
10050030-122 = "は、はいっ先生！精いっぱい頑張ります……！"
10050030-123 = "ご期待に添えるよう、最善を尽くします！"
10050030-124 = "みなさん、ありがとうございます。それぞれの持ち場で待機をお願いします。"
10050030-125 = "分かりました！"
10050030-13 = "……。"
10050030-130 = "では先に現場へ向かいます。いつでもご連絡くださいね！"
10050030-135 = "すごい情熱です……。"
10050030-136 = "[s] \"そうだね、少し心配になるくらい……。\""
10050030-137 = "マシロさんが心配ですか？先生。"
10050030-138 = "[s1] \"マシロもだけど……。\"\n[s2] \"例の本を売っている子たちもかな。\""
10050030-14 = "……。"
10050030-141 = "なるほど、そちらのことでしたか。実は私も同じことを思っていました。"
10050030-142 = "意外でしたか？でもきっと、委員長も同じことを言うと思いますよ。#n本を愛する人に悪い人はいません。"
10050030-143 = "……本をお金稼ぎに利用しているだけかもしれない、ですか？"
10050030-144 = "……。"
10050030-145 = "……私はそうは思いません。"
10050030-146 = "本は……もう、好きでもない限り、手にすることさえ減ったのですから。"
10050030-147 = "ただお金だけが目当てなら、本にこだわる必要なんてないんです。#nお金を稼ぐ方法なんて、いくらでもあるのですから。"
10050030-148 = "[s] \"たしかに……そうかもね。\""
10050030-149 = "はい。だからこの騒動の中心にいる方々は、きっといい人なんだと思います。"
10050030-150 = "話くらいは通じるはず。#n本好きに、悪い人はいませんから。"
10050030-19 = "た、タカネ！？気をしっかり！"
10050030-2 = "トリニティ生の寮"
10050030-20 = "部長……これって夢なのですよね？#n夢なら全部、理解できますわ……。"
10050030-21 = "いえ、これは紛れもなく現実です。"
10050030-22 = "私たちが……こんなに？いいのですか！？"
10050030-23 = "言いたいことは分かりますが……現実ですってば。"
10050030-24 = "しかしたしかにケタが違いますね。#nゼロ何個だ……？これがトリニティなのですねぇ、実に恐ろしい。"
10050030-25 = "やはりお金を集めるには、お金が集まる場所に行くべきだったのです！"
10050030-26 = "今更かもしれませんが、トリニティの皆さんがレッドウィンターの話を新鮮と思っていただけたのが大きいかと。"
10050030-27 = "ある生徒さんの感想を思い出しましたわ……#n「今まで味わったことのない栄養だ……」と。"
10050030-28 = "レッドウィンターではもう当然のことでも、他では違うのですね。"
10050030-29 = "やはり文化交流は積極的にすべきということでしょう。#nでなければ停滞し、周囲を蝕む病となってしまう。"
10050030-3 = "だはーーっ、流石に疲れましたよぉ……まだ初日ですが。"
10050030-30 = "まるで、ボロボロになり廃れてしまった夢のように……。"
10050030-31 = "部長……。"
10050030-32 = "まあ、基本的に我々の仕事は文化を広め、循環させることです。"
10050030-33 = "文化は、お金という土壌から生まれ育つ生き物ですから。"
10050030-34 = "お金という概念が持つ交換価値そのものが、肥大化した影響もあるのでしょうけれど……。"
10050030-35 = "しかし循環は必要です。我々にとって大事な財産となり得ます。"
10050030-36 = "さびれてしまった夢や文化は、周りをダメにする悲しき遺産でしかない。"
10050030-37 = "何より……その循環の過程でお金も回るのですから。ムフフ。"
10050030-38 = "はいはい、そうですね……。"
10050030-39 = "ともかく、もう一つの精算タイムですね。知識解放戦線に連絡です！"
10050030-4 = "お疲れ様でした、部長。"
10050030-43 = "ふぁぁ……なに？ヤクモ。#n今から寝ようとしてたのに……。"
10050030-44 = "寝てる場合じゃありませんよ？メル。話したいことは山盛りですが……#n言葉よりも数字をお見せしましょうか。"
10050030-45 = "はい、こちら今日一日の精算分。"
10050030-46 = "精算……？#nああ、そうだった……はいよ……。"
10050030-5 = "とはいえさすがトリニティ。学園内にこんなところまであるんですねぇ。"
10050030-53 = "メル先輩？メル先輩っ！？どうしました！！？"
10050030-54 = "モミジ……私目が悪くなったのかも。ちょっと見てくれない？"
10050030-55 = "えっ？ええと……これは、今日の分の精算……？"
10050030-56 = "ひぃぃいいいいっ！？！？"
10050030-57 = "正直に白状しなさいヤクモ。あんたどっかで銀行強盗でもしたんじゃないんでしょうね。#nもしくは金融会社にハッキングとか、犯罪まがいの何かを……。"
10050030-59 = "人をなんだと思っているんですか。"
10050030-6 = "外部と交流の多い学園ですから。これくらいはあってもおかしくないかと。"
10050030-60 = "どんなリスクを呼び寄せるかも分からない出どころ不明のお金など、こちらから願い下げです。"
10050030-61 = "じゃあ、これ……。"
10050030-62 = "本物……なんですか？"
10050030-63 = "やれやれ。これだから作るしか能のない作家は。"
10050030-64 = "まずはご飯でも食べたらどうです？今日も夕食抜きだったのでしょう？"
10050030-65 = "本当に、いいのですか……？"
10050030-66 = "ええ。これはあなた方知識解放戦線の成果なんですから。"
10050030-67 = "そういうことですわ。#nおめでとうございます、お二人とも。"
10050030-68 = "あ……えー……うーん、んんっ……。"
10050030-69 = "だめですよメル先輩。#nこういう時はちゃんとお礼を言わないと。"
10050030-7 = "……それなりの値段でしたけどね。"
10050030-70 = "ありがとうございます、出版部のみなさん！#n本当に……本当におかげさまで、助かりました……！"
10050030-71 = "まあ基本的には本の出来がよかったからでしょう。だから売れたのです。"
10050030-72 = "そもそも見込みのない本を売るスキルは、私にも無いものでして。"
10050030-73 = "……あんたに褒められる日が来るなんてね。#n明日は槍でも降るんじゃない？"
10050030-74 = "あら、そんなにおかしなことです？#nこれも私だから言えるのであって、タカネの口からは決して出ませんよ？"
10050030-75 = "まあ、たしかに……。"
10050030-77 = "……部長？メルリーさん？お二人は何を仲良く話しているのでしょうか。"
10050030-78 = "ひぃっ！？な、なんでもないけどっ！？"
10050030-79 = "そ、そうです！仕事をしていれば自然な話……そうそう、ビジネスの話ですよぉ！"
10050030-8 = "ん～、出張費がこっち持ちだと思うと、流石にもったいない気もしますねぇ。#nやはりあの時、割合を変えるべきだったでしょうか。"
10050030-80 = "ふむ……？"
10050030-81 = "と、とにかく。この調子ならあと数日で完売でしょう！"
10050030-82 = "だから期待していいですよ？どんと任せちゃってくださいな。"
10050030-83 = "う、うん……！信じてはいたけど、今日の話を聞いてもっと信じてみたくなったよ。"
10050030-84 = "あら。部長はさておき、メルリーさんがいつから私のことを……？不思議ですわね。"
10050030-85 = "とにかく、切るね！ありがと！"
10050030-86 = "は、はい！ご飯はしっかり食べてくださいよ？"
10050030-9 = "それでは契約しなかったのでは……？"
10050030-91 = "さ、さあ！我々も行きましょうか！#n明日も元気に働くためにも、疲れを取らなくては！"
10050030-92 = "はいはい。では私たちも休みましょうか。"
10050030-93 = "しかしタカネって、意外とこういう強行にもちゃんとついてきてくれるのですね？見直しましたよ。"
10050030-94 = "当然ですわ。この程度、レッドウィンターの普段と比べれば普通ですし……。"
10050030-95 = "ええ、そうでしたね。でも……タカネにはどこか高貴な雰囲気がするといいますか……。"
10050030-96 = "今日初めて、レッドウィンターにお嬢様みたいな生徒がいると知った――と言われたり。"
10050030-97 = "い、いきなり何をっ……！？レッドウィンターにお嬢様なんてあり得ない話ですわ！"
10050030-98 = "もちろん、事実はそうですが。マーケティングにおいて、100%の事実を扱う必要はないのですよ？"
10050030-99 = "……目にする広告のほとんどは「ウソは言っていない」、という内容ばかりですし。"
