[translation]
10052150-1 = "ダアト：影に隠れし深淵の知恵 "
10052150-3 = "あの子たち、何をやっているのでしょう？"
10052150-4 = "あれは……まさか！？"
10052150-14 = "おー。"
10052150-15 = "ひ、ひいいぃぃぃ！？！？"
10052150-16 = "ユズちゃん大丈夫！？#nって、お姉ちゃんは何してるの！？"
10052150-17 = "ミドリ……私、今まで誤解してたのかもしれない……！"
10052150-18 = "なんの話！？"
10052150-19 = "宇宙戦艦はいけるネタだと思ってた……でもシナリオライターたるもの、あらゆる可能性を超えた、その先を見据えるべきだった……！"
10052150-20 = "巨大変身合体恐竜ロボット！この手があったか！"
10052150-21 = "そんなこと言ってる場合！？"
10052150-22 = "1つだけ、確かなことがあります。"
10052150-23 = "ここにネル先輩がいたら……きっとこう言っていたでしょう。"
10052150-24 = "――「最高にイカしてる」と。"
10052150-25 = "[s1] \"あれは巨大変身合体恐竜ロボットじゃないよ、モモイ！\"\n[s2] \"巨大変身合体「怪獣」ロボットだ！\""
10052150-28 = "……。"
10052150-29 = "その話、いま必要ですか！？"
10052150-36 = "分類学はたしかに大事な学問ですが……それにしたって巨大すぎませんか？#nしかも、こっちへ向かって来ています！"
10052150-41 = "……。"
10052150-42 = "みんな、心配はいらないわ。"
10052150-46 = "リオ？あなた、まさか……。"
10052150-47 = "そうよ。万が一のために、用意したものがあるの。"
10052150-51 = "ネオアバンギャルド君――"
10052150-52 = "――出撃。"
10052150-62 = "これは……！"
10052150-63 = "ネオアバンギャルド君……？"
10052150-70 = "……。"
10052150-71 = "……。"
10052150-72 = "ぷっ！あははははっ！なにそれ！変なの！"
10052150-73 = "小さすぎませんか？とてもダアトの相手にはなりませんよ？"
10052150-75 = "か、かわいいですね……！えへへ……。"
10052150-76 = "多くの場合、大きさは問題になるわね。"
10052150-77 = "だけど、今は違うわ。"
10052150-81 = "はい……？"
10052150-82 = "ケイ、いいかしら？"
10052150-83 = "……まあ、約束したことですからね。#nいいでしょう。さっそく始めますよ。"
10052150-84 = "ああ、その前に1つだけ。#nアイン、ソフ、オウル。あなた達にお礼を言わせてください。"
10052150-85 = "はい！？"
10052150-86 = "どういう意味……？"
10052150-87 = "どうせハッタリです！今のダアトは最強！無敵！ですから！#nあなた達に勝算なんてないんですよ！"
10052150-88 = "[ruby=・]今[/ruby][ruby=・]の[/ruby][ruby=・]条[/ruby][ruby=・]件[/ruby]では、きっとそうね。"
10052150-89 = "でも、打開の策はすべて整っているの。"
10052150-90 = "名もなき神々の力で作られた、この鋼鉄大陸において……！"
10052150-91 = "小細工の跡が見えるようだけれど、その修正にも慣れてきたわ。"
10052150-92 = "名もなき神々の力……。"
10052150-93 = "「王女」と「鍵」がいるからって……。"
10052150-94 = "……。"
10052150-95 = "ま、まさか……！！！"
10052150-96 = "簡単なことです。1度起きたことは2度目だって起こります。#nそして2度目は、1度目よりも容易く進めることができる。"
10052150-97 = "「色彩」がキヴォトスに舞い降りようとした日がありました。"
10052150-98 = "私たちはその力に対抗し、その力の一部を応用した。"
10052150-99 = "選り好みなんてしていられない。#n使えるものはすべて使わないと、生き残れなかったから。"
10052150-100 = "闘争はあなた達の専売特許ではありません。生き物なら、誰だって同じです。"
10052150-101 = "鋼鉄大陸は、名もなき神々の力を活用して作られました。"
10052150-102 = "そして、その地に立つ8の預言者は、いつの間にかその力の影響を受けていた。"
10052150-103 = "そのすべてと戦った末に、ここは名もなき神々の力で充満するようになった。"
10052150-104 = "さらに、その預言者のコアを吸収しているケイが、今ここに居る。"
10052150-105 = "エネルギーが存在し、それを分析できて、ひいては再現できるとすれば――"
10052150-106 = "当然、そのエネルギーを好きなように加工し、応用することもできるということです。"
10052150-110 = "それって、つまり……！"
10052150-111 = "何をうろたえているのですか？#nその力は元々、私とアリスに帰すべきものですよ。"
10052150-112 = "文句は受け付けませんので、悪しからず。"
10052150-114 = "じゃあ、そのネオなんとかを……！"
10052150-115 = "ええ。再び「物質の巨大化」をするわ。"
10052150-129 = "さいっこう！！"
10052150-130 = "うん……すごい！"
10052150-131 = "（でも……デザインはもう少しなんとかならなかったのかな……）"
10052150-132 = "……これが「切り札」ですか。"
10052150-133 = "ごめんなさい。ここは敵地で、迂闊に話しては盗聴されると考えていたわ。"
10052150-134 = "だから、ケイにだけ話していたのですね。"
10052150-135 = "ええ。セキュリティに関しては、ケイが一番安全だもの。"
10052150-136 = "あれ？巨大ネオアバンギャルド君が――"
10052150-143 = "ユズに、[ruby=ジェントルに]丁寧に[/ruby]手を差し伸べています。"
10052150-144 = "え、えええええ！？"
10052150-145 = "当然だわ。だって――"
10052150-146 = "ネオアバンギャルド君を操縦するのは……ユズ、貴女よ。"
10052150-149 = "そんなの聞いてないんですけど！？！？！？"
10052150-150 = "あぁっ！ユズがスラスラと自分の意見を言っています！#nこれは本当にショックだという意味です！"
10052150-151 = "でも、アバンギャルド君を操縦した経験はあるでしょう？"
10052150-152 = "たしかに！UZQueen専用機に改造されたアバンギャルド君がありました！"
10052150-153 = "ええ。私もその記録は把握しているわ。だから、ユズ――"
10052150-157 = "ネオアバンギャルド君に乗ってちょうだい。"
10052150-163 = "う、うううぅぅぅぅぅ……！！！"
10052150-172 = "ど、どうやって操縦すれば……！？"
10052150-173 = "ネオアバンギャルド君は脳波で作動することになっているわ。"
10052150-174 = "……今のところ。"
10052150-175 = "今のところ！？"
10052150-176 = "ええ。ネオアバンギャルド君は今のところ、貴女の思う通りに動くはずよ。"
10052150-177 = "そ、そそそそ、そんなこと言われても……！"
10052150-182 = "いけ、ダアト！蹴っ飛ばせ！"
