[translation]
10052040-1 = "Uniform"
10052040-10 = "心配しすぎですよ。症状は徐々に落ち着いてきていますので。#nとはいえ、コアを回収する度にこうなるなら、どうにも気が重いですね……。"
10052040-100 = "い、いえ……こちらこそ、ありがとうございます……。"
10052040-101 = "しょうがないなぁ！ケイは照れ屋さんだもんね！"
10052040-102 = "モモイ――！！！"
10052040-11 = "もしかしたら、この身体が「[ruby=欠陥あり]Defected[/ruby]」と評されたのは、これが理由なのかもしれません……。"
10052040-12 = "とにかく、コアを活性化する度に、輸送船の出力や機能を再設計できるはずです。"
10052040-13 = "そして、そのエネルギーの流れは私の身体とつながっていて……#nまあ結論だけ言いますと、私が制御できると思います。"
10052040-14 = "[s] \"無理しすぎないでね、ケイちゃん。\""
10052040-15 = "誰がケイちゃんですか、もう。"
10052040-2 = "うぅっ……。"
10052040-24 = "アリス……？#nこれは何ですか……？"
10052040-25 = "制服です！"
10052040-26 = "それは見れば分かりますが、どうしてこれを……。"
10052040-27 = "これは、アリスが初めて着せてもらった服なんです！"
10052040-28 = "アリスは……それが本当に嬉しかったです。だから、ケイにも共有したいんです！"
10052040-3 = "[s] \"大丈夫？\""
10052040-32 = "もしかして……嫌、でしたか……？"
10052040-33 = "まさか！その……むしろ、すごく……。"
10052040-37 = "えへへっ……。"
10052040-38 = "当然よ。ミレニアムの制服こそ、最も合理的な選択だもの。"
10052040-39 = "……ここでひと言加えるのは、実にあなたらしいですね。"
10052040-4 = "思った以上にめまいがします。特に頭の左側が……。"
10052040-41 = "[ns] \"生徒の戦闘服と言ったら、やっぱり制服だよね！\""
10052040-42 = "いきなりなんの話ですか……？"
10052040-43 = "はい？勉強を敵キャラとしたら、それをやっつけるための戦場が教室で、戦闘服は制服……？"
10052040-44 = "……。"
10052040-45 = "とりあえず、それで納得してあげます……。"
10052040-46 = "で、では、私が……これを……。"
10052040-47 = "……。"
10052040-48 = "はい！着てみてください！#nアリスはケイの制服姿が早く見たいです！"
10052040-49 = "……！"
10052040-5 = "[s] \"本当に大丈夫？\""
10052040-55 = "ど、どうですか……？"
10052040-56 = "わあ！"
10052040-57 = "[ns] \"おぉ……。\""
10052040-58 = "な、なんですか、その反応は……！"
10052040-59 = "すごく似合ってるよ、ケイちゃん。"
10052040-6 = "原因は間違いなく、ビナーのコアを持ち帰って活性化させたことですが……。"
10052040-60 = "うん、本当にかわいい。"
10052040-61 = "……！！！"
10052040-62 = "あ、ありがとうございます……ユズ、ミドリ。"
10052040-66 = "大丈夫？暑くない？"
10052040-67 = "あなたじゃないのですから……。"
10052040-68 = "ケイ、とてもよく似合っています。"
10052040-69 = "一瞬、パーフェクトキュートクール系美少女の座を脅かされると思ったくらいに。"
10052040-7 = "……。"
10052040-70 = "……そんなのは狙っていません。"
10052040-71 = "パーフェクトキュートクール系美少女の座は守られました。#nこれで、挫けることなく生きていられます。"
10052040-72 = "話聞いてますか……？"
10052040-8 = "大丈夫です。この身体がエネルギーの流れに慣れれば済む話ですので。"
10052040-82 = "こほん。その……。"
10052040-83 = "ありがとう、ございます。"
10052040-84 = "ん～？よく聞こえなかったなぁ～？"
10052040-85 = "くっ……！"
10052040-89 = "あ、ありがとうございます！これでいいですか！？"
10052040-9 = "[s] \"本当の……本当に、大丈夫なんだよね……？\""
10052040-90 = "そうこなくっちゃ！感謝の気持ちを伝えるのは大事だからね！"
10052040-91 = "[ns] \"そうそう！\""
10052040-92 = "よりによってこの2人がまともな話を……！"
10052040-93 = "と、とにかく！"
10052040-94 = "この制服は……必要な時にだけ着ることにします。"
10052040-95 = "どうしてですか？"
10052040-96 = "それは、その……。"
10052040-97 = "……。"
10052040-98 = "皆さんの思いが込められた服を、大事にしたくて……。"
10052040-99 = "ケイちゃん……ありがとう。"
