[translation]
10052135-3 = "イェソド――撃破！"
10052135-4 = "……あれが崩れるのですね。"
10052135-5 = "見ましたか、先生？アリス、やりました！リターンマッチ成功です！"
10052135-6 = "や、やっぱり降下は怖いです……うぅぅ……。"
10052135-8 = "みんな無事だし、大勝利だよね！えへへ！"
10052135-9 = "ケイちゃん、先生。よろしくお願いします。"
10052135-15 = "[ns] \"私たちも降りようか。\""
10052135-19 = "[ns] \"……ケイちゃん？複雑そうな顔してるよ？\""
10052135-20 = "いえ、ただ……ちょっと生意気だなと思いまして。#n名もなき神々の力を使っておきながらこの程度だなんて……。"
10052135-21 = "私の頃はですね……！"
10052135-22 = "[s] \"出た。「私が若かった頃は」から始まるやつ。\""
10052135-26 = "……先生。"
10052135-27 = "私のことを、自分の武勇伝を語って講釈を垂れるような鬱陶しいヤツだと貶すつもりですか！？"
10052135-28 = "[s] \"そこまでは言ってないよ……。\""
