[translation]
10052010-1 = "ビナー：違いを痛感する静観の理解者 "
10052010-10 = "見ての通り……。"
10052010-11 = "……なんと言えばいいんでしょう。"
10052010-12 = "大きな穴だし……普通に大穴でいいんじゃない？"
10052010-13 = "あまりにも単純すぎませんか、そのネーミング……。"
10052010-14 = "な、名前は分かりやすいほうがいいんだよ、ケイちゃん！"
10052010-19 = "なんだか……鈍い音が聞こえますね……。"
10052010-2 = "モモイ――参上！"
10052010-20 = "人工的な音……何かの駆動音ですね。"
10052010-21 = "[s] \"じゃあ、この下にビナーがいるのかな。\""
10052010-22 = "……おそらくは。"
10052010-27 = "皆さん、穴の下にビナーの反応があります。#nですがこれは……。"
10052010-28 = "何か問題があるんですか？"
10052010-29 = "発せられている信号が、他の預言者に比べて微弱なものになっています。#n原因はいくつか推測できますが――"
10052010-3 = "降下って、すごいね……。"
10052010-30 = "分かった！ビナー、寝てるんじゃない？"
10052010-31 = "その可能性もありますし……。"
10052010-32 = "穴が大きすぎるあまりに、検出できる信号が弱まっているのかもしれません。"
10052010-33 = "[s] \"なんでビナーは穴の中にいるんだろう？\""
10052010-34 = "ハッキリとした理由は分からないわ。#nでもビナーには、他の預言者との明確な違いがあるの。"
10052010-35 = "そうなの？"
10052010-36 = "記録を見る限り、ビナーはずいぶん前から目撃されているみたいです。#nそれこそ、デカグラマトンの活動が本格化するよりもずっと以前から。"
10052010-37 = "アビドス生徒会が研究していたようだけれど、当時の資料は既に散逸してしまっているみたいね……。"
10052010-38 = "そもそも、これがアビドス砂漠を彷徨っていたこと自体が謎めいているのだけれど。"
10052010-39 = "えっと、つまり……ビナーだけが特殊ってことですか？"
10052010-4 = "うぅぅ、怖かった……。#n……あれ？"
10052010-40 = "ええ。ですので、この地形や配置にも、何か理由があるのかもしれません。"
10052010-41 = "何はともあれ、ビナーを呼び出す必要があります。"
10052010-42 = "呼び出す……良い表現ですね。#nちょうど私も、似たようなことを考えていました。"
10052010-43 = "ユズ？今から角度と弾速をお伝えします。#n榴弾をその通りに打ち上げてもらえますか？"
10052010-44 = "は、はい！？わたしですか……？ど、どうして……？"
10052010-45 = "少しばかりビナーを刺激してみようかと思いまして。#nあとついでに、穴の大きさと深さを測定するためです。"
10052010-46 = "ユズ、貴女の銃の性能は把握しているわ。"
10052010-47 = "適切な角度で初速を抑えて射撃した場合、榴弾は自由落下に近い状態にできる。"
10052010-48 = "爆発するまでの時間と、爆発音の反響を計算すれば、穴の規模をおおよそ測定できると思います。"
10052010-49 = "観測用のドローンを向かわせますね。お待たせはしないかと。"
10052010-56 = "で、では……撃ちます！"
10052010-6 = "[ns] \"これは……？\""
10052010-63 = "[ns] \"どう？分かった？\""
10052010-64 = "……想像以上ね。まず、底面近くの幅は――"
10052010-65 = "とりあえず、想像以上の大きさだ。でいいのではないでしょうか。"
10052010-71 = "――っ！？巨大な質量反応を確認！"
10052010-78 = "う、うわあああ！？"
10052010-79 = "下から、すごい音が……！"
10052010-80 = "び、ビナーが上がってきてるみたいです！"
10052010-81 = "寝てたのに、起こしちゃったのかも……。"
10052010-82 = "[s] \"上手くいったね。\""
10052010-83 = "まあ、予定通りです。"
10052010-84 = "[ns] \"このエリアは……私たちがいただいたっ！\""
10052010-85 = "そのセリフはまだ早いですよ……。"
10052010-9 = "これは見ての通り……。"
