[translation]
10052153-12 = "リオ会長！このままじゃユズちゃんが……！"
10052153-13 = "なにか必殺技とかないの！？"
10052153-14 = "必殺技……。"
10052153-18 = "ユズ！今からネオアバンギャルド君のリミッターをすべて解除するわ！#nそれと――"
10052153-19 = "「貴女専用」の[ruby=Battle Gear]戦闘装備[/ruby]を、今インストールするわ！"
10052153-8 = "あ……うぅ……ううぅぅ……。"
10052153-9 = "どっ、どうすれば……！？"
