[translation]
1012903-1 = "目が眩むほどに堂々と"
1012903-10 = "先生！"
1012903-100 = "ひとまず、危険ですので先生は離れていてください。"
1012903-101 = "[s] \"えっと、実は作戦には続きがあって――\""
1012903-109 = "今のところ見てないよな？例のトリニティの制服。"
1012903-11 = "少し、後ろをお借りします！"
1012903-110 = "ああ、でも関係ないやつは外に出してるからな。#n時間の問題だ。"
1012903-111 = "あいつ、絶対捕まえてボコボコに……！"
1012903-117 = "……うん？"
1012903-12 = "[s] \"スズミ！？どうしたの！？\""
1012903-121 = "て、テルミットホワイト、登場～！"
1012903-126 = "？？？？？"
1012903-127 = "あれ、隣にいるのってシャーレの先生じゃね？"
1012903-128 = "スマホで動画撮ってる……？"
1012903-130 = "準備オッケーのシューターから、撃ち方～始め～！☆"
1012903-131 = "[s] \"いいよいいよ！その照れがいい！サイコー！\""
1012903-135 = "あ、あなたの瞳に……フラッシュバ～ン☆"
1012903-137 = "先生って、ああいう趣味なんだ……。"
1012903-138 = "お、おい……こっちに来るぞ。退いてやれ。"
1012903-139 = "……あれが噂の……シャーレの当番の仕事、なんだな。"
1012903-140 = "大変そうだ……。"
1012903-141 = "み、道をあけてくれてありがとうね！妖精さんたち！"
1012903-142 = "あ、はい……。"
1012903-143 = "い、行こうぜ、先生と目合わせんなよ……。"
1012903-149 = "……本当に、うまくいきましたね。"
1012903-150 = "まさか先生もカメラマンに「変身」する作戦とは……。"
1012903-151 = "[s13] \"あ、今のところカットで。\"\n[s14] \"セリフを続けて！テルミットホワイト！\""
1012903-157 = "ほ、本当にカメラを回していたんですか！？"
1012903-159 = "（その後も、スケバンたちは私を避けていき……）"
1012903-160 = "（スズミと無事、公園を抜け出すことができた）"
1012903-18 = "前を向いて、素知らぬ顔をしていてください。"
1012903-19 = "追っ手がいます。"
1012903-20 = "[s] 言う通りにする。"
1012903-25 = "こっちにきたはずだ！"
1012903-26 = "あいつ、捕まえたら倍返しにしてやる！！"
1012903-27 = "絶対逃がすなよ！"
1012903-28 = "全員、公園を包囲しろ！"
1012903-29 = "白い髪で、グレーのトリニティの制服だ。#n見つけたらその場でやっちまえ！"
1012903-3 = "（今日も平和だなぁ……）"
1012903-34 = "[ns1] \"スズミのファン？\"\n[ns2] \"スズミのお友達？\""
1012903-37 = "……ではありません。"
1012903-4 = "（そんなことを思いながら、公園のベンチに座っていると……）"
1012903-41 = "公園の外側の方へ行ったようですね……。"
1012903-42 = "服のお直しに向かう途中で、奇襲を受けたんです。"
1012903-43 = "弾薬が底をついてしまい、正面突破も難しく……。"
1012903-44 = "先生のおかげで危機は脱したものの、これからどうすれば良いか……。"
1012903-45 = "[s] \"相手は何人いるの？\""
1012903-46 = "正確な数はわかりません……。"
1012903-47 = "道中で90人ほど制圧しましたが、まだ2倍以上の人数が残っているようで。"
1012903-48 = "[s3] \"90人！？\"\n[s4] \"あと200人はいるってこと！？\""
1012903-51 = "はい、おそらく。"
1012903-52 = "あの数を正面から相手にするのは難しいでしょう。"
1012903-53 = "……ふぅ。"
1012903-54 = "ですが、先生のおかげで少し休めました。#n包囲が手薄なところをなんとか突破できないか、試してみます。"
1012903-55 = "急いで公園を離れてください。巻き込むわけにはいきません。"
1012903-60 = "うっ……。"
1012903-61 = "[s] \"スズミ！怪我してる？\""
1012903-62 = "少し、足を捻ったみたいです。"
1012903-63 = "走れはしませんが……大丈夫です。"
1012903-64 = "[s5] \"無理しちゃダメ！\"\n[s6] \"何か方法を探そう！\""
1012903-67 = "彼女たちは私の姿を知っています。#n脱出時の衝突は……避けられません。"
1012903-68 = "ここは私に任せて、先生はどうか……。"
1012903-69 = "[s7] \"……良い案を思いついたよ。\"\n[s8] \"私の言う通りにして。\""
1012903-72 = "いえ、先生を危険にさらすなんて……！"
1012903-73 = "[s] \"私はスズミの先生だよ？\""
1012903-77 = "……分かりました。一体、どのような策なのでしょうか？"
1012903-80 = "せ、先生――"
1012903-83 = "この服を着るのが「良い案」なんですか！？"
1012903-84 = "[s] \"直しに行く前でよかった！\""
1012903-85 = "数で勝る相手に、これでは動きづらくて不利です。"
1012903-86 = "もしかして……この状況でご冗談を……！？"
1012903-87 = "[s9] \"さっきの会話、聞こえてたでしょ？\"\n[s10] \"「グレーのトリニティの制服」って。\""
1012903-90 = "！！"
1012903-91 = "そう、でしたね……。"
1012903-92 = "彼女たちの知る私の特徴は、すべて伝聞によるもの。"
1012903-93 = "写真は撮られていないようですので、具体的な見た目までは知らないはず。"
1012903-94 = "変装すれば……衝突なく抜け出せるかもしれません。"
1012903-95 = "でもこの格好は……やはり恥ずかしいです……!"
1012903-96 = "[s11] \"魔法少女は、正義の味方だから……。\"\n[s12] \"まさに、この状況にピッタリだよ。\""
1012903-99 = "そんなことを言われましても……#nはぁ、承知しました。"
