[translation]
1012905-1 = "閃光弾不発事"
1012905-6 = "先生、こちらです。"
1012905-7 = "[s] \"スズミ！もう来てたんだ！\""
1012905-12 = "[ns] \"かわいい！\""
1012905-13 = "か、からかわないでください！"
1012905-14 = "「現場に合わせた服装」とおっしゃっていたので……。"
1012905-15 = "[s1] \"Tシャツとかがいいかな？って思ったんだけど。\"\n[s2] \"むしろ、その格好がベストだね。\""
1012905-18 = "う、うぅぅうう……！"
1012905-23 = "あ、あのすみません……。#n「魔法少女ヘヴィキャリバー」の「テルミットホワイト」……ですよね？"
1012905-27 = "あっ、はい！そう、ですが……。"
1012905-28 = "わ、私っ、ホワイト推しなんです！#n写真……一緒に撮らせてもらっても良いですか！？"
1012905-29 = "しゃ、写真？"
1012905-30 = "[s] \"自然にして、スズミ……！\""
1012905-31 = "ええと、こう、ですか……？"
1012905-36 = "すみません、私もいいですか……！？"
1012905-37 = "こっちもお願いしまーす！"
1012905-51 = "ありがとうございます！家宝にしますね！！"
1012905-56 = "このキャラクター、大人気ですね……。"
1012905-57 = "[s] \"スズミが可愛いからだよ。\""
1012905-58 = "……パトロールに集中します。"
1012905-59 = "（先生はまた……平気でそんなことを……）"
1012905-69 = "おいおい、イケてるカメラじゃねぇか。こっちによこせよ。"
1012905-70 = "借りるだけだよ。#nあとでちゃ～んと郵送してやるからさ。"
1012905-72 = "そんなご[ruby=むたい]無体[/ruby]な！！#nこ、これは拙者の命よりも大事な[ruby=カメラ]神器[/ruby]で……！"
1012905-73 = "いいから貸せって！"
1012905-78 = "イベントを荒らしている不良とは……あの方々のことですね。"
1012905-79 = "先生はこちらでお待ちを。"
1012905-86 = "そこまでです！"
1012905-91 = "ああん？コスプレイヤーか？"
1012905-92 = "撮ってほしいってか？#nいまこいつからカメラ奪うとこだから、待ってな！"
1012905-93 = "なっ……！いま！奪うと言ったでござるか！？"
1012905-94 = "借りるも奪うも似たようなもんだろうが！"
1012905-96 = "二人、ですか。"
1012905-97 = "二人がかりで来ていただいたほうが都合が良いですね。#n手早く済みますので。"
1012905-98 = "あぁん？……閃光弾でも食らっとけ！"
1012905-107 = "く、くぅっ！て、手がっ……！#nこいつ、なんて握力してやがる！"
1012905-108 = "は、放せって！閃光弾が手の中で爆発する……っ！"
1012905-109 = "お手伝いしましょう。"
1012905-116 = "い、いたたたたたっ！！！"
1012905-117 = "うわああ！！手が！！"
1012905-118 = "く、くそっ、覚えてろよ……！"
1012905-126 = "閃光弾は神聖なものです。#nみだりにピンを抜いてはいけません。"
1012905-132 = "いま……閃光弾を素手で潰してたよね……？"
1012905-133 = "うん……爆発する前に、グシャ！って……。"
1012905-134 = "小道具かな……？実はなんかのショーだったとかさ。"
1012905-136 = "目標は達成しました。先生、帰りましょう。"
1012905-137 = "[s3] \"あ……。\"\n[s4] \"は、はい……。\""
1012905-143 = "（スズミとイベント会場を後にした）"
1012905-144 = "（何故かみんなが道をあけてくれて、スムーズに移動できた……）"
