[translation]
1012902-1 = "トリニティのマジカル自警団"
1012902-2 = "（夜勤中、軽い運動も兼ねてシャーレを見回っていたところ……）"
1012902-13 = "（灯りのついてる更衣室を見かけた)"
1012902-14 = "[ns1] （消し忘れ？）\n[ns2] （まだ誰かいるのかな？）"
1012902-19 = "[ns3]（誰もいないみたい）\n[ns4] ゆっくりドアを開く。"
1012902-27 = "[wa:270]― [log=스즈미 매지컬]せ、[wa:430]先生！？[/log]"
1012902-30 = "― [log=스즈미 매지컬]な、[wa:370]なにか[wa:500]ご用件でも！？[/log]"
1012902-32 = "― [log=스즈미 매지컬]というか、[wa:780]いつからいらしてたんですか！[/log]"
1012902-35 = "[ns5] \"ご、ごめん！誰もいないものだとばかり……！\"\n[ns6] \"ノックしたけど、返事がなかったから……！\""
1012902-36 = "[wa:770]― [log=스즈미 매지컬]音楽に集中していたので[/log]"
1012902-37 = "[wa:770]― [log=스즈미 매지컬]音楽に集中していたので[/log]"
1012902-39 = "― [log=스즈미 매지컬]全然気づいておらず……。[/log]"
1012902-42 = "― [log=스즈미 매지컬]でも、[wa:710]相手が先生で[wa:650]良かったです。[/log]"
1012902-45 = "[wa:2300]― [log=스즈미 매지컬]あっ、[wa:630]こ、[wa:450]この衣装は、[wa:1020]その……！[/log]"
1012902-47 = "― [log=스즈미 매지컬]自警団の[wa:800]潜入捜査の[wa:670]ため、[wa:690]でして……。[/log]"
1012902-50 = "― [log=스즈미 매지컬]わ、[wa:250]私の趣味というわけでは……！[/log]"
1012902-52 = "― [log=스즈미 매지컬]違います！[wa:700]本当に！[/log]"
1012902-55 = "[ns] \"似合ってるよ、可愛い。\""
1012902-56 = "[wa:550]― [log=스즈미 매지컬]サイズが合うか[/log]"
1012902-58 = "― [log=스즈미 매지컬]事前に[wa:270]確認しようと思って[wa:1150]着ただけで……！[/log]"
1012902-61 = "― [log=스즈미 매지컬]（か、[wa:850]可愛いと言ってくださりました……）[/log]"
1012902-63 = "― [log=스즈미 매지컬]（いきなり褒められると……[wa:1910]うぅ……！）[/log]"
1012902-66 = "― [log=스즈미 매지컬]（褒められるのは、[wa:1050]まだ慣れません。）[/log]"
1012902-68 = "― [log=스즈미 매지컬]（嬉しくはありますが……！[wa:2500]でも……！）[/log]"
1012902-71 = "[wa:1170]― [log=스즈미 매지컬]今日見たことは、[/log]"
1012902-73 = "― [log=스즈미 매지컬]他の方には[wa:650]内緒にしてくださいね！[/log]"
1012902-76 = "― [log=스즈미 매지컬]これは、[wa:1320]機密事項……[wa:1570]なので！[/log]"
1012902-79 = "ところで、更衣室に何かご用でしたか？"
1012902-80 = "[s7] \"灯りがついてたから。\"\n[s8] \"誰か倒れてるのかなって。\""
1012902-83 = "なるほど。シャーレのパトロールを。"
1012902-84 = "生徒の安全のため……まるで自警団のようですね。"
1012902-85 = "[s] \"うん、スズミを見習ってね。\""
1012902-86 = "！！！"
1012902-87 = "……先生は、いつも勇気をくださりますね。"
1012902-88 = "そんなところが……。"
1012902-92 = "そ、そろそろ、着替えたいのですが……。"
1012902-93 = "[s] \"あ、そうだね！失礼しました！\""
1012902-94 = "またお会いしましょう。"
1012902-98 = "今日のことは、どうか他言無用でお願いします。"
1012902-100 = "（その後、オフィスに戻って仕事を片づけた）"
1012902-101 = "（帰り際に寄ってみると、更衣室の電気はちゃんと消えていた）"
