[translation]
1013206-1 = "た、助けて、ください……！"
1013206-13 = "じ、時間が……！"
1013206-14 = "[s1] \"はぁ、はぁ……。\"\n[s2] \"つ、ツクヨ……待って……！\""
1013206-17 = "ふえぇ……！#nご、ごめんなさい、先生……！"
1013206-18 = "私が、寝坊をした、せいで……！"
1013206-19 = "これで、最後のモデルだと思ったら、緊張して寝られなくて……！"
1013206-20 = "[s] \"た、タクシーに乗るのは……！？\""
1013206-21 = "それだと、遠回り、で……！"
1013206-22 = "そうだ、近道を使えば……。"
1013206-23 = "こ、こちらです、先生！"
1013206-29 = "[ns] \"こんなところに裏道が……。\""
1013206-3 = "（一緒にファッションショーの会場に行く、という話だったはず)"
1013206-30 = "先生、行きましょう……！"
1013206-31 = "パルクールの訓練中に、知ったルートなのですが……。"
1013206-32 = "ここを通れば、会場まで一直線、です！"
1013206-33 = "[s] \"えっと、ツクヨ……。\""
1013206-35 = "[ns] \"フェンスがあって通れないような……。\""
1013206-36 = "だ、大丈夫です……！"
1013206-37 = "[s] \"なるほど、端っこにくぐり戸が……。\""
1013206-38 = "忍者たるもの……これくらい、軽く越えて、みせます！"
1013206-39 = "[s] \"そっち！？\""
1013206-40 = "まずは私が、お手本を……！"
1013206-44 = "こうして、どうにか……！"
1013206-45 = "[s] \"ツクヨ！？\""
1013206-5 = "会場への道"
1013206-51 = "[ns3] \"……！\"\n[ns4] \"本当に、フェンスを越え……！\""
1013206-57 = "[ns] \"……越え、た？\""
1013206-60 = "[wa:470]― [log=츠쿠요 드레스]うぅっ……。[/log]"
1013206-62 = "― [log=츠쿠요 드레스]なんとか、[wa:1570]フェンスは[wa:810]越えられました、[wa:1550]けど……。[/log]"
1013206-65 = "[wa:2990]― [log=츠쿠요 드레스]服が[wa:1250]引っかかって……。[/log]"
1013206-68 = "― [log=츠쿠요 드레스]動けない、[wa:1300]です……。[/log]"
1013206-71 = "[wa:1500]― [log=츠쿠요 드레스]うぅ……[wa:2130]ごめんなさい……。[/log]"
1013206-73 = "― [log=츠쿠요 드레스]私が、[wa:1920]近道を[wa:1240]しようと[wa:1450]したから……。[/log]"
1013206-76 = "[wa:2020]― [log=츠쿠요 드레스]……あれ？[wa:1800]先生は、[wa:1850]どうやって[wa:1000]向こう側に……？[/log]"
1013206-79 = "― [log=츠쿠요 드레스]えっ？[wa:1580]フェンスの横に、[wa:1770]くぐり戸……！？[/log]"
1013206-8 = "（……なのにどうして、全力疾走をしているんだろう？）"
1013206-82 = "[wa:770]― [log=츠쿠요 드레스]う[wa:540]うぅ……[/log]"
1013206-84 = "― [log=츠쿠요 드레스]そうとも知らず、[wa:2060]私は……。[/log]"
1013206-87 = "― [log=츠쿠요 드레스]……先生[wa:2150]……私の服、[/log]"
1013206-89 = "― [log=츠쿠요 드레스]少し[wa:1650]引っ張っていただいても、[wa:2770]良いでしょう[wa:1190]か？[/log]"
1013206-92 = "（……ドレスの生地が破れないよう、慎重に外した）"
1013206-93 = "（途中でお巡りさんに見つかってしまい、少し冷や汗をかいたが……）"
1013206-94 = "（なんとか時間通り、会場に到着できた）"
1013206-96 = "（……会場を出て再びお巡りさんと会った時は、少しドキッとした）"
