[translation]
1013408-1 = "帰ってきた勇者様？"
1013408-100 = "あまりの忙しさで説明を忘れていました！"
1013408-101 = "パンパカパーン！勇者アリス、完全復活です！"
1013408-102 = "――と、言いたいところですが。"
1013408-103 = "これはレプリカです。"
1013408-104 = "オリジナルを忠実に再現してもらいました。"
1013408-105 = "その……鋼鉄大陸を出る前に、アビ・エシュフの残骸を見つけたんです。"
1013408-106 = "残骸といっても、手のひらサイズの破片でしたが……。"
1013408-107 = "[s11] \"連れて帰ってきてあげたんだね。\"\n[s12] \"アビ・エシュフも仲間だからね。\""
1013408-112 = "……はいっ！"
1013408-113 = "それで、もしかしたら……と思ってミレニアムのみなさんに見せてみました。"
1013408-123 = "とはいえ、流石に手のひらサイズからの復元はできないと言われてしまいました。"
1013408-124 = "でもその代わりに、なるべくオリジナルを[ruby=・]再[/ruby][ruby=・]現[/ruby]してくれるということになったんです！"
1013408-125 = "おかげでアビ・エシュフは元の姿を取り戻しました！"
1013408-126 = "……オリジナルのパーツは一部だけですが。"
1013408-127 = "それにあくまでレプリカなので、前に比べれば出力が大幅に減りました。#n長時間の飛行や機動的な動きなどはもうできません。"
1013408-128 = "前ほど耐久度も高くないので、戦闘には使わないようにと念を押されました。"
1013408-129 = "[s13] \"それでレプリカなんだね。\"\n[s14] \"せっかく再現できたのに残念だね。\""
1013408-132 = "？"
1013408-133 = "アリスは少しも残念に思いません！"
1013408-134 = "魔王との戦いが終わったら力が封印されてしまう勇者はたくさんいます。#nむしろよくあるエンディングです。"
1013408-135 = "それに……。"
1013408-142 = "今日、アビ・エシュフを着てたくさんの人の前に立ちました。"
1013408-143 = "そしてみなさんはアビ・エシュフを見て「カッコイイ」と、「好きだ」と言ってくれました。"
1013408-144 = "それは、空を飛んだり、魔王を倒すことよりもずっとずっと、素敵なことです。"
1013408-145 = "だからアリスは今日、すごく幸せでした！"
1013408-147 = "（アリスと手をつないで、ゲーム開発部の部室に戻った）"
1013408-148 = "（帰り道にも、道行く人から何度も写真撮影をお願いされた）"
1013408-16 = "（この人混みからアリスを見つけるのは難しそうだ）"
1013408-17 = "（今いる場所の情報をアリスに連絡した）"
1013408-2 = "（それは鋼鉄大陸の事件を解決してから、しばらく経った頃のこと）"
1013408-22 = "先生、どこですか？"
1013408-23 = "アリスはここにいます！"
1013408-24 = "[ns1] \"アリス？\"\n[ns2] \"ここだよー！\""
1013408-27 = "あっ、先生発見です！"
1013408-28 = "アリスがそちらに行きます！待っていてください！"
1013408-3 = "（アリスが送ってくれた住所に向かった）"
1013408-33 = "パンパカパーン！"
1013408-34 = "先生がパーティーに合流しました！"
1013408-35 = "[s3] \"その姿は……。\"\n[s4] \"アビ・エシュフ！？\""
1013408-38 = "そうです！勇者アリス、完全復か――"
1013408-46 = "今、空飛んでなかった！？"
1013408-47 = "それ構造どうなってるの！？コスプレってレベルじゃないけど！？"
1013408-48 = "それ何のゲームですか？どこのブース？"
1013408-50 = "うわぁん！逃げている途中なのを忘れていました！"
1013408-51 = "先生、説明は後です！逃げましょう！"
1013408-57 = "それで、ゲーム開発部も新作で参加しよう！という流れになったんです。"
1013408-58 = "周りのブースよりも目立つにはどうすればいいかを考えた結果――"
1013408-59 = "作戦は上手くいきました。大成功です！#nただ、ちょっと上手くいきすぎてしまって……。"
1013408-6 = "（すごい人混みだ）"
1013408-60 = "みなさんブースはそっちのけで、アリスにばっかり興味津々なのです！"
1013408-61 = "これでは本末転倒です！"
1013408-62 = "[s5] \"たしかに目立つ上に飛び回るから……。\"\n[s6] \"私もついつい見ちゃうかも。\""
1013408-65 = "先生もですか！？"
1013408-66 = "このままだと永遠に部室に帰れません！"
1013408-67 = "あっ、見つけた！！"
1013408-68 = "あの、もしよければポーズを取っていただけませんか？"
1013408-69 = "ああっ！気づかれてしまいました！"
1013408-7 = "（どうやら有名なゲームイベントが開催されているらしい）"
1013408-76 = "ひ、1人ずつ話してください！！うわぁん！"
1013408-82 = "（イベントが終わるギリギリの時間まで、対応は引っ切り無しに続いた）"
1013408-90 = "なんとか終わりました……。"
1013408-91 = "なんだかもう……記憶も、曖昧です……。"
1013408-92 = "[s7] \"お疲れ様……。\"\n[s8] \"私も、ずっと写真を撮ってた記憶しか……。\""
1013408-97 = "[ns9] \"……あっ、そういえば！\"\n[ns10] \"アビ・エシュフは壊れたんじゃなかったっけ。\""
