[translation]
1013102-1 = "評論の対象"
1013102-2 = "ごきげんよう、先生。#n改めまして、[ruby=みよし]三善[/ruby]タカネ、ご挨拶申し上げますわ。"
1013102-3 = "[s] \"ようこそタカネ、シャーレは初めてだったよね？\""
1013102-4 = "ええ、そうですわ。#n……シャーレって本当に素敵なところなのですね。"
1013102-5 = "レッドウィンターよりも暖かくて……だから、なのかもしれませんわね。"
1013102-6 = "……その、私以前より先生にお願いしたいことがありまして。"
1013102-7 = "[s] \"どうしたの？何でも言って。\""
1013102-8 = "ありがとうございます。"
1013102-9 = "……先生のことを、もっとよく知りたいと思っているのです。#nよろしければ、教えていただけないでしょうか？"
1013102-10 = "[s] \"き、急に……どうして？\""
1013102-11 = "あら、先生は私のこと、もっと知りたいとは思わないのですか？"
1013102-12 = "教師が生徒のことを知りたいと思うのは当然？#nふむ……。"
1013102-13 = "そうですね。これからお互いをじっくりと知っていけば良いだけの話ですわ。"
1013102-14 = "評論家が、その対象について知りたがるのは自然なことですもの。"
1013102-15 = "[s] \"人まで批評の対象になるの！？\""
1013102-16 = "いえ……正確には、対象外ですが。"
1013102-17 = "対象について知り、分析し、#n得た情報を組み合わせて隠された価値を見出すこと――"
1013102-18 = "それって批評でも、人間関係でも大切なことではありませんか？"
1013102-19 = "ですので、人も批評できるのではないかと思っているのです。"
1013102-20 = "もちろん、肯定的な意味で、ですけれど。"
1013102-21 = "[s] \"……言葉選びが本当に上手いね。\""
1013102-22 = "ふふっ、当然です。"
1013102-23 = "……そうでなければ、特にこんなインターネット社会では……文章で生きていくことなんてできませんもの。"
1013102-24 = "ところで先生……この本は何でしょうか？#n先生の机の下から見つけたのですが……。"
1013102-25 = "ああでも。これも本ですから、批評の対象になりますわね。#nとりあえず読んで――"
1013102-26 = "[s] \"そ、それはダメーー！！！！\""
1013102-27 = "え、えぇ……そんなに慌てるようなことなのですか？"
1013102-28 = "とにかくどんなことがあっても、絶対にダメ……？"
1013102-29 = "うぅ……。"
1013102-33 = "分かりましたわ。誰にだって隠したいことの一つや二つ、ありますものね。"
1013102-34 = "でもやっぱりちょっと気になりますわね……。#n私、こう見えて意外と寛容ですのよ？"
1013102-35 = "やっぱり……ダメでしょうか？"
1013102-36 = "[s] \"……いっそ私を殺してからにしてくれ。\""
1013102-37 = "そ、それほどなのですか……？"
1013102-39 = "そういえば……先生のお部屋、本当に色々なものがあるのですね。"
1013102-40 = "あまりに多種多様すぎて、共通点を見つけられませんが……。"
1013102-41 = "え？全部、他の生徒の皆さんが記念にって置いていったものなのですか？"
1013102-42 = "……。"
1013102-43 = "それは結構ですが……せめて先生なりの基準で、少しは分類なさってはいかがでしょう？"
1013102-44 = "分類とは、それそのものが意味を生む行為ですわ。"
1013102-45 = "その過程で、私も先生がどのような方なのか理解することができますし。"
1013102-46 = "そうですね……そういう意味で、こちらを差し上げます。"
1013102-47 = "私たち出版部が発行している、今月のキヴォトス文化評論集です。"
1013102-48 = "あ、22ページから24ページまでは……読まなくて大丈夫ですわ。"
1013102-49 = "そこはメルリーさんが勝手に描き散らした箇所ですので……。"
1013102-50 = "[s] \"タカネは毎月こういう評論集を出してるの？\""
1013102-51 = "私一人で執筆しているわけではありませんが、できる限り自分の担当ページは全部埋めるようにしておりますわ。"
1013102-52 = "……どうしても批評するに値する作品が出てこないときは、諦めるしかないこともありますけど。"
1013102-54 = "……そうですわね。もしもアナログ出版だけに頼っていたなら、私たちなんてもう生き残れませんでしたわ。"
1013102-55 = "実際、出版業界は手をつけられるものすべてに手を出して……なんとか経営を成り立たせている状態ですもの。"
1013102-56 = "なんだか本末転倒になっている気がするので、できれば出版という本来の役割に戻りたいとも思っているのですが……。"
1013102-57 = "はあ……ええ。これも贅沢な悩みなのでしょうね。#nそういう点では部長の経営戦略の手腕は認めざるを得ませんわ。"
1013102-58 = "……結局、私の結論はいつも同じになってしまいます。"
1013102-59 = "贅沢な悩みを抱えられるうちに、一つでも多くの優れた批評を残し、隠された価値を世に示す……それが私の――"
1013102-60 = "「職業的義務」、ですわ。"
1013102-61 = "ですから先生！私にだけ――"
1013102-62 = "先生の隠している部分を見せていただくことは……できませんか？"
1013102-63 = "[s] \"先生は生徒に隠し事なんてございません……。\""
1013102-64 = "あらまぁ……教科書のような模範的な回答。"
1013102-65 = "ですが、既に私はもう2つ知っておりますのよ？"
1013102-66 = "先生は生徒から受け取った物を、何よりも大切にしていること――"
1013102-67 = "――そして、生徒には見せられない何かを隠していること、ですわ！"
1013102-68 = "[s] \"そ、それじゃあタカネの隠れた一面も見せてもらいたいな！\""
1013102-69 = "もちろんですわ。いくらでもご質問ください。"
1013102-70 = "ああ、ですが……あまりデリケートな部分は……。"
1013102-71 = "……。"
1013102-72 = "場合によっては、お答えできかねますが。"
1013102-73 = "[s] \"そ、そんな質問はしないよ！\""
1013102-74 = "あら、そうなのですか？"
1013102-75 = "それでは、何をお知りになりたいのです？"
1013102-76 = "私の趣味……？読書以外の……？"
1013102-77 = "うぅ……見た目通りの生徒と言われた気がして、なんだか悔しいですわね……！"
1013102-78 = "間違っていないのが、なおさらですわ！"
1013102-79 = "ふふっ……ですが、先生が驚かれるような趣味がありますのよ。"
1013102-80 = "それは――アイスホッケーですわ！"
1013102-81 = "[s] \"アイスホッケー！？\""
1013102-82 = "ええ！アイスホッケーこそ真のスポーツと言えるもの！#n先生はどの程度アイスホッケーのことをご存じでしょうか？"
1013102-83 = "[s1] \"まあ、そこそこ……？\"\n[s2] \"ごめん、全然わからない。\""
1013102-84 = "そうなのですね。それではもしかして……。"
1013102-85 = "専用のオンデマンド配信サービスに登録して、ライバルチームの試合まで分析されているとか！？"
1013102-86 = "あ、そこまでじゃありませんのね……。"
1013102-87 = "あ、はい。その方がむしろ自然ですわね。"
1013102-88 = "レッドウィンターは常冬ですから、ウィンタースポーツを年中目にすることができますが、他ではそうとは限りませんし……。"
1013102-89 = "でしたら先生……。"
1013102-90 = "今度レッドウィンターにいらっしゃるときは、私と一緒にアイスホッケーを観に行きませんか？"
1013102-91 = "私が手取り足取り解説――"
1013102-92 = "いえ、「批評」して差し上げますわ！"
