[translation]
1013203-1 = "またモデル、ですか？"
1013203-2 = "美術予備校の教員室"
1013203-3 = "あ、先生……！"
1013203-4 = "[s] \"ツクヨ、何があったの？\""
1013203-5 = "それが……。"
1013203-6 = "美術予備校から、モデルのオファーが来たの、ですが……。"
1013203-7 = "絵画モデルの経験は、無いので……。"
1013203-8 = "先生に見守っていただきたいなと、思いまして……。"
1013203-12 = "……はっ！？#nこれでは、自分の都合で……先生に、迷惑をかけることに……！"
1013203-13 = "す、すみません……！"
1013203-14 = "[s] \"ううん、私は大丈夫だよ。\""
1013203-16 = "[ns] \"でも、モデルは辞めるんじゃなかったっけ……？\""
1013203-17 = "じ、実は……。"
1013203-18 = "『忍者は七度生きる』のパンフレットをくださった、社長さんのこと……覚えて、ますか？"
1013203-23 = "あの方に……もう一度だけ力を貸してほしいと、頼まれまして……。"
1013203-24 = "今朝になって、モデルの方が逃げてしまったそう、なんです……。"
1013203-25 = "それで代役が、見つからず……。"
1013203-26 = "絵画モデルは、じっとしているだけ……とは、言われましたが……。"
1013203-27 = "[s1] \"なるほど……！\"\n[s2] \"てっきり画家を目指すのかと。それも良いんだけどね。\""
1013203-30 = "そ、そんな！"
1013203-31 = "私は、これからも立派な忍者を、目指し、ます……！"
1013203-32 = "……はい？"
1013203-33 = "あ、えっと、ドレスを着てるのは……。"
1013203-34 = "今日のテーマが「ドレスの女性」、らしく……。"
1013203-39 = "あぁ、ツクヨさんですね。今日はありがとうございます。#nさっそくですが、教室に向かっていただけますか？"
1013203-43 = "は、はい……！"
1013203-44 = "それでは、行ってきます……！"
1013203-46 = "美術予備校教室"
1013203-50 = "代役で来てくださった[ruby=おおの]大野[/ruby]ツクヨさん、でしょうか？"
1013203-51 = "は、はい！"
1013203-52 = "引き受けてくださって助かりました。#n最初に軽く説明しますね。"
1013203-53 = "今回お願いするのは、ワイルドハント芸術学院受験コースのクラスです。"
1013203-54 = "ポーズは後ほど、私から指示を出しますので……。"
1013203-55 = "可能な限り、キープしていただければと思います。"
1013203-57 = "わ、分かりました！"
1013203-58 = "絵のモデルは初めてですが、頑張り、ます……！"
1013203-59 = "ははっ、そんなに緊張する必要はありませんよ。"
1013203-64 = "（未経験なら大変だろうなぁ……）"
1013203-65 = "（同じポーズを維持するのは、意外と難しいし……）"
1013203-68 = "（……と、思ったが）"
1013203-69 = "（あれから1時間、まったく動いていないだと！？）"
1013203-75 = "あのモデルさん……ちゃんと生きてるんだよね？"
1013203-76 = "えっ、蝋人形じゃなかったの？"
1013203-77 = "知らない？最近注目の新人モデルの子だよ！"
1013203-78 = "本当だ！よく見たらあの人じゃん！"
1013203-82 = "（……）"
1013203-83 = "（心配でしたが、これならショーのモデル、よりは……）"
1013203-84 = "（じっとしているのは、得意です）"
1013203-85 = "（えへへ、木への変装……練習した甲斐が、ありました……！）"
1013203-86 = "（て、天才だっ……！）"
1013203-87 = "（講師歴10年、ここまで完璧なモデルは初めて見た……）"
1013203-88 = "（蝋人形と言われても納得してしまうほど！）"
1013203-89 = "（それに、あの安らかな表情……）"
1013203-90 = "（こんな逸材が、今までどこにいたんだ……！？）"
1013203-92 = "（そうして時間は流れ、デッサンの授業は無事に終わった）"
1013203-95 = "お疲れ様でした！#nいやあ、大変だったでしょう？"
1013203-96 = "い、いえ……お疲れ様、でした！"
1013203-97 = "それにしても、素晴らしいモデルでした！"
1013203-98 = "本当に絵画モデル、初めてだったんですか……？"
1013203-99 = "は、はい……これが初体験、です。"
1013203-100 = "（やはり、生まれながらの天才だ……！）"
1013203-101 = "ではこれで、失礼、します……。"
1013203-102 = "待ってください！"
1013203-103 = "よろしければ、もう少しモデルをお願いできませんか？"
1013203-104 = "はい……？"
1013203-105 = "それが、彫刻の授業でもモデルが必要で……！"
1013203-107 = "に、2倍の時給をお支払いしますので！"
1013203-108 = "え、えっと……。"
1013203-109 = "これほど完璧に姿勢を保てる方を、私は知りません！"
1013203-110 = "大野さんがモデルになってくだされば……。"
1013203-111 = "生徒たちの実力も、ぐんぐん伸びること間違いないです！"
1013203-112 = "どうか、どうかお願いします！"
1013203-113 = "ええと、ううぅ……。"
1013203-117 = "わ、分かりました。#nよろしくお願い、します……。"
1013203-120 = "（そしてツクヨは、彫刻の授業でも……）"
1013203-121 = "（完璧な姿勢を維持し続けていた）"
1013203-122 = "（数時間後……）"
1013203-125 = "本当に助かりました！#n大野さん、ありがとうございます！"
1013203-126 = "は、はい#nお疲れ様、でした……！"
1013203-131 = "ごめんなさい、先生……お、お待たせ、しました。"
1013203-132 = "[s] \"大丈夫だよ、楽しく見学してたからね。\""
1013203-133 = "先生がいてくださったおかげで、何とか……。"
1013203-134 = "最後まで、頑張れました……。"
1013203-135 = "……はい？#n彫刻の授業の感想、ですか……？"
1013203-136 = "そうですね……#nデッサンの授業と、雰囲気は変わらなかったの、ですが……。"
1013203-137 = "石を削ったり整えたりするせいか、粉が飛んでいたので……。"
1013203-138 = "喉が、ちょっと……。"
1013203-139 = "[s3] \"じゃあ、喉を潤すのも兼ねて――\"\n[s4] \"美味しいご飯でも食べに行こうか！\""
1013203-144 = "あっ……！"
1013203-145 = "でしたら、今度は私が――"
1013203-146 = "[s] \"お店なら、もう予約してあるよ！\""
1013203-147 = "そ、そんな……!"
1013203-148 = "えっと……ありがとう、ございます、先生……！"
1013203-150 = "（ツクヨを連れて向かったのは）"
1013203-151 = "（百鬼夜行にある、野菜のメニューが豊富なレストランだった）"
1013203-155 = "（……何となく、まだモデル活動が続くような気がして）"
