[translation]
1013106-1 = "夜空に佇む姫君"
1013106-3 = "[ns] \"それにしても、オーロラ、かぁ……。\""
1013106-4 = "ええ。レッドウィンターでは、たまに見ることができるのですわ。"
1013106-5 = "こういったオーロラ予報アプリもあるんですのよ？"
1013106-6 = "[s] \"写真撮るの、好きだったんだ？\""
1013106-7 = "そう……ですわね。"
1013106-8 = "写真と言っても、人物よりは風景を好んで撮る方ですわ。"
1013106-9 = "それに……評論と写真には、ある種の共通点があると思っておりますから。"
1013106-10 = "[s] \"そんな風に考えたことなかったな。\""
1013106-11 = "……コホン。それでは、ご説明いたしましょうか。"
1013106-12 = "評論とは、何かしらの文化的創作物を目にしたときに生まれる心象――"
1013106-13 = "それを自らの理論で組み立てて、文字として「現像」するようなものですわ。"
1013106-14 = "言い換えれば、その瞬間に抱いた印象を、自分なりの解釈で「定着」させる行為。"
1013106-15 = "そしてその解釈、すなわち「評論」は、他者に読まれ、受け取られることで――"
1013106-16 = "ある程度の「客観性」を獲得していくもの。"
1013106-17 = "そこに、写真との共通点があるのだと思っておりますわ。"
1013106-18 = "[s] \"つまり、写真もある意味では客観性を持っていると？\""
1013106-19 = "ええ、けれど、それと同時に――"
1013106-20 = "撮る人の技量や感性によって、まったく違う印象になったりもするでしょう？"
1013106-21 = "主観から出発しながら、客観を目指す評論。"
1013106-22 = "客観から始まりながら、主観が滲み出る写真。"
1013106-23 = "この相反するようで、どこか響き合う構造……面白くありませんか？"
1013106-24 = "私は、そう感じておりますの。"
1013106-25 = "創作と評論の関係もまた、きっと同じですわ。"
1013106-26 = "[s] \"創作……か……。\""
1013106-27 = "え？私も創作に挑戦してみたいと、思ったことがあるのかって……？"
1013106-28 = "そ、それは……。"
1013106-29 = "……それは……。"
1013106-30 = "あ……！"
1013106-34 = "先生！オーロラですわ！"
1013106-41 = "……自然って、偉大ですわね。"
1013106-42 = "オーロラを見ていると、人間なんてちっぽけな存在で――"
1013106-43 = "そもそも評論なんて意味があるのかしら、なんてそんなことを思ったりもしますけど……。"
1013106-44 = "それでもやっぱり、創作というのは人が生み出せる、最も美しい成果の一つですから。"
1013106-45 = "……こんな言葉をご存知ですか？#n「人そのものは美しくなくても、人の作り出したものは美しくなり得る」と。"
1013106-46 = "……美しいと思えないものに、創作欲を抱いたりしませんものね。"
1013106-47 = "だから評論は、ある意味で人が生み出した美しさへの――"
1013106-48 = "私なりの敬意の表現……なのかもしれません。"
1013106-49 = "[s1] \"だったらさ。\"\n[s2] \"今度は、タカネの写真を撮ってもいい？\""
1013106-52 = "え、えぇっ？！先生が……！？#nそれは、その……とても光栄ですが……どうして急に……！"
1013106-53 = "えっ！？せっかくならコンセプトを決めて撮ろう……？"
1013106-54 = "そ、それを私自身で「創作」してほしい……！？#n無茶ぶりが過ぎますわよっ！？"
1013106-55 = "[s3] \"でも、考えてみて！\"\n[s4] \"オーロラも創作も綺麗だから、合わせればもっと綺麗になるかも！\""
1013106-58 = "「綺麗」と「綺麗」を足したら、もっと綺麗になる……！？"
1013106-59 = "それではまるで、たこ焼きにチョコミントソースをかけたら美味しい理論じゃないですか！？"
1013106-63 = "何より……創作は……評論家の領分では、ありませんわ。"
1013106-64 = "たしかに、多くの創作物を見てきましたが――"
1013106-65 = "だからといって、自分でもできると思い込むのは創作への軽視に他なりません。"
1013106-66 = "……そんなものは誰かを傷つけて終わるだけ。#nそういった方々を、山ほど見てきましたの。"
1013106-67 = "え？ここだけの秘密の創作、ですか？#n先生だけが観客になってくださると……？"
1013106-68 = "夢でもいいから、なりたい自分を演じてみて……？"
1013106-69 = "[s] \"うん。今は私が「タカネ評論家」になるよ。\""
1013106-70 = "……！"
1013106-71 = "そ、それでは……。"
1013106-72 = "せめてキーワードくらいは……先生が決めてくださいな……。"
1013106-73 = "[s5] \"じゃあ、没落して追放された姫君って設定で！\"\n[s6] \"逃亡の途中でオーロラを見て、感動して泣いちゃうの！\""
1013106-76 = "……どうして私と出会う方は、皆さん一度はその方向に走るのかは本当に分かりませんけれど。"
1013106-77 = "分かりました。先生が決められたキーワードですもの。"
1013106-78 = "ふむ、コホン！"
1013106-79 = "私には、3人の姉がおりました。私は、名家の末娘として生まれ……。"
1013106-80 = "皆さまに可愛がられて育ちました。けれど……幼い頃から、身体はあまり丈夫ではありませんでしたわ。"
1013106-81 = "外で遊べない反動だったのでしょうか……ついつい、周囲にいたずらばかりしてしまって。"
1013106-82 = "姉たちは私を「[ruby=Shvibzik]小さな悪戯っ子[/ruby]」と呼んでいましたわ。#n特に三女のマリア姉様とは、とても仲が良くて――"
1013106-83 = "体調の良い日には一緒の枕で寝て、朝は冷水浴も一緒にしていました。"
1013106-84 = "本当は冷水浴なんてしたくありませんでしたが、#n姉様が健康になると言ってくださったので……。"
1013106-85 = "でも、そんな穏やかな日々にも終わりが訪れました。#n家は没落し、姉様たちはそれぞれの道へ……。"
1013106-87 = "いつかまた巡り会える日を信じて、私たちは散り散りになったのです……。"
1013106-94 = "[wa:320]― [log=타카네]先生、[wa:1290]ご覧ください……[/log]"
1013106-96 = "― [log=타카네]オーロラですわ。[/log]"
1013106-99 = "― [log=타카네]物語では、[/log]"
1013106-101 = "― [log=타카네]空の守護者の方々が――[/log]"
1013106-104 = "― [log=타카네]宴を楽しむ様子が[/log]"
1013106-106 = "― [log=타카네]そう見えているのだと[wa:750]言われております。[/log]"
1013106-109 = "[wa:320]― [log=타카네]いつも一緒にいられると[wa:1000]思っていた方々とは[/log]"
1013106-111 = "― [log=타카네]もう……[wa:1940]二度と会えませんけれど。[/log]"
1013106-114 = "[wa:2130]― [log=타카네]世界はこれまで通り、[/log]"
1013106-116 = "― [log=타카네]どこまでも冷たく、[wa:2100]遠いだけでしょう。[/log]"
1013106-119 = "― [log=타카네]それでも私が[wa:930]オーロラを見上げ、[/log]"
1013106-121 = "― [log=타카네]希望を抱くのは――[/log]"
1013106-124 = "[wa:770]― [log=타카네]この場所で、[wa:1600]最後まで私と[wa:980]共にいてくださる[/log]"
1013106-126 = "― [log=타카네]「パートナー」が[wa:480]いるからなのでしょうね。[/log]"
1013106-129 = "[ns] \"そっか。私は今、タカネの「パートナー」なんだ。\""
1013106-131 = "[wa:280]― [log=타카네]ふふっ。[wa:1530]ええ、[/log]"
1013106-133 = "― [log=타카네]今はそういう[wa:720]設定ですわ、[wa:1550]「先生」。[/log]"
1013106-136 = "― [log=타카네]お写真、[wa:1240]よろしくお願い[wa:520]いたしますわね？[/log]"
1013106-139 = "……。"
1013106-140 = "[s] \"ど、どうしてそんなに拗ねてるんですか、姫君……？\""
1013106-141 = "姫君じゃありません！あのお話はもう終わりです！#n私はただの[ruby=みよし]三善[/ruby]タカネで――これからも、ずっとそうですわ。"
1013106-142 = "まったく……他人が書いた創作物だったなら、最初のページをめくった瞬間に――"
1013106-143 = "「たった一行で私に読書を放棄させる偉業を達成しましたわね」なんて批評を下したくなるような作品でしたわね。"
1013106-144 = "[s] \"でもご自身で書かれたんですよね？\""
1013106-145 = "先生がやれと仰ったからじゃないですか！！！"
1013106-146 = "うぅ……。#nもう……いいですから……お写真、見せてください。"
1013106-147 = "[s] \"どうかな？\""
1013106-148 = "……。"
1013106-149 = "……とても……綺麗に撮れていますわね……。"
1013106-150 = "ありがとうございます、先生。"
1013106-151 = "あの、ひとつだけお願いがあるのですが……。"
1013106-152 = "この写真と……それから、ここでの出来事……。"
1013106-153 = "誰にも……話さないでいて、いただけませんか？"
1013106-154 = "[s] \"そんなに恥ずかしいの？\""
1013106-155 = "それも……もちろん少しはありますが……。"
1013106-160 = "全部……先生と私だけの秘密に、しておきたいのです。"
