[translation]
1013302-1 = "メイドロボットとは"
1013302-2 = "（リオがちゃんと部屋を片づけているか心配になり……）"
1013302-3 = "（少し様子を見に行くことにした）"
1013302-10 = "先生？何か用かしら？"
1013302-11 = "[ns1] \"……お？\"\n[ns2] \"おおお……！！\""
1013302-14 = "……？"
1013302-15 = "[ns3] \"部屋が綺麗だ……！\"\n[ns4] \"やればできるじゃん！\""
1013302-18 = "ああ、それを心配して来てくれたのね。"
1013302-19 = "今はもう平気よ。片づけを手伝ってくれる子がいるの。#n良い機会だから紹介するわ――"
1013302-20 = "家事担当のアバンギャルド君よ。"
1013302-25 = "ベースはそのままに、家事全般をできるよう改造を施したの。"
1013302-26 = "どうかしら？悪くない出来だと思うのだけれど。"
1013302-27 = "[ns] \"自分で片づけてるわけじゃなかったんだ……。\""
1013302-30 = "このアバンギャルド君を作ったのは私よ？#nそれは、私が片づけたのと同義ではないかしら。"
1013302-31 = "今回の試みは大成功と評して申し分ないわ。"
1013302-32 = "学園に戻っても、このままアバンギャルド君に家事をやらせようと思うの。"
1013302-33 = "あわよくば量産して普及させるのも悪くないわね。"
1013302-34 = "[s] \"それなら普通のメイドロボットがいいな！\""
1013302-35 = "メイドロボット……？"
1013302-36 = "家事を手伝ってくれるロボットのことを指すのだったかしら。"
1013302-37 = "であれば、条件はクリアしているわ。"
1013302-38 = "アバンギャルド君もメイドロボットと言えるはずよ。"
1013302-39 = "はい？足りない要素がある？"
1013302-40 = "……ああ、そうね。大事なことを忘れていたわ。"
1013302-41 = "メイド服を着せていなかったわね。"
1013302-42 = "では正式版ではメイド服を着せて普及させましょう。"
1013302-43 = "[s] \"それは考え直してほしいかな！？\""
1013302-44 = "理由が分からないわ。"
1013302-45 = "メイド服を着せれば要素が揃うのではなくて？"
1013302-46 = "[s] \"もっと見た目にこだわって欲しいな！\""
1013302-50 = "もう少し詳しく説明してもらえるかしら。"
1013302-51 = "先生の理想の「メイドロボット」とはどのようなものなの？"
1013302-52 = "[s] \"可愛くて、愛嬌があって！\""
1013302-53 = "アバンギャルド君も……可愛くて愛嬌があると思うのだけれど……。"
1013302-54 = "[s] \"清楚で上品な佇まい！\""
1013302-55 = "アバンギャルド君も……見方によれば、あるいは。"
1013302-56 = "[s] \"何でもできる頼もしい存在！\""
1013302-57 = "アバンギャルド君も……同じね？"
1013302-58 = "[s] \"……あと、可愛いメイド服！\""
1013302-59 = "メイド服の話は既にしたと思うのだけれど……。"
1013302-60 = "とはいえその点においても、やはりアバンギャルド君は優位性を持っているわ。"
1013302-61 = "例えば、C&Cの子たちもメイド服を着ているわ。#nけれど彼女たちはロボットではないから、「メイドロボット」ではない。"
1013302-62 = "たとえアリスに着せたとしても、「メイドロボット」にはならない。#nあの子は、ロボットではなく人間だもの。"
1013302-63 = "けれどアバンギャルド君は正真正銘のロボット。"
1013302-64 = "家事手伝いのアバンギャルド君にメイド服を着せたなら――"
1013302-65 = "立派なメイドロボットよ。"
1013302-66 = "[s] （な、なんだかそんな気がしてきた……けど……！）"
1013302-67 = "……まだ認識に齟齬があるようね。"
1013302-68 = "ここまで意見が割れるとは思わなかったわ。"
1013302-69 = "2人の議論で決着を見ないのであれば、より多くの意見を集めましょう。"
1013302-70 = "差し当たって、メイド服を着せたアバンギャルド君をみんなに見せてくるわ。"
1013302-71 = "メイド服とロボット――"
1013302-72 = "それが合わさってメイドロボット。"
1013302-73 = "この事実の前には、みんな認めざるを得ないはずよ。"
1013302-74 = "[s] \"メイド服はどこで手に入れるつもり……？\""
1013302-75 = "トキなら予備を持っているのではないかしら。"
1013302-76 = "[s] \"絶対サイズ合わないって……！！\""
1013302-77 = "その時はアバンギャルド君を服のサイズに合わせて改造するわ。"
1013302-78 = "ともかく、今からメイド服を借りてくるわね。"
1013302-79 = "では……後ほど。"
1013302-83 = "[ns] \"リオ、本気なんだね……。\""
1013302-85 = "（果たして、結果はいかに……）"
