[translation]
1013505-1 = "クエスト"
1013505-10 = "それとこれとは違うんです……！"
1013505-106 = "楽しくないです！#nそれより、ちょうどよかったです。これを届けてほしいとクエス――お願いされて。"
1013505-107 = "どれどれ……ああ、やっと実験の結果が出たんだね。"
1013505-108 = "そういったものはインターネットで送受信したほうが効率的なのでは？"
1013505-109 = "これに限っては難しいかな。"
1013505-11 = "あっ、照れてるんでしょー？やっぱりアリスとはちょっと違うね！"
1013505-110 = "なぜですか？"
1013505-111 = "セキュリティ上ちょっとね。これも一応は機密情報だから。"
1013505-112 = "インターネットの致命的な短所は、セキュリティの脆弱性と保管期限にあるっ！"
1013505-113 = "たしかに。未だに磁気テープが廃れない理由でもありますね。"
1013505-114 = "まぁ、もっと確実な方法が出てきてくれるのが一番ではあるんだけどね。#n使えるものは使っていかないと。"
1013505-115 = "……よし、それじゃあクエストクリアを祝して一緒にゲーセン行かない？"
1013505-116 = "え、えっと……？"
1013505-117 = "あれ？前は楽しそうにしてたよね？"
1013505-118 = "ま、前はそうですが……！いや、その……。"
1013505-119 = "[s] \"あっ、ケイちゃんもゲーム好きなんだ？\""
1013505-12 = "（なんでアリスはアリスで私はケイ[ruby=・   ・   ・]ちゃん[/ruby]なのか、とても気になります）"
1013505-120 = "そうなんですよ！先生も見たらビックリしますよ？"
1013505-121 = "ちがっ……！いや、だからあれは……！"
1013505-122 = "あれ……じゃああの時は仕方なく付き合ってくれてた感じ……？"
1013505-123 = "そ、それも違います！"
1013505-127 = "[ns] \"ふふっ、素直じゃないなぁ。\""
1013505-128 = "っ……この……。"
1013505-130 = "この白々しい大人が！！！！"
1013505-16 = "[ns1] \"あれ？緊急事態かと思ったのに……。\"\n[ns2] \"みんなの仲が良いのは素敵なことだよね！\""
1013505-19 = "先生！ちょうどいいところに！#nぜひ教師として、助けを求める生徒を――"
1013505-2 = "（急いでミレニアムに向かった）"
1013505-20 = "あっ、先生！こんにちは！"
1013505-21 = "先生も混ざりますか？"
1013505-22 = "[s] \"私は横で見守らせてもらうよ。\""
1013505-23 = "はいぃ！？"
1013505-24 = "……。"
1013505-26 = "こんな大人を信じた私のバカ――！！"
1013505-29 = "そういえばケイちゃんってアリスの双子の妹なんだよね？"
1013505-30 = "えっ？ああ、はい……そんなところです……。"
1013505-31 = "でも髪の色が全然違うよね？色が反対というか。"
1013505-32 = "あっ、言われてみれば！"
1013505-33 = "あ……はは……そういうこともある……んじゃないですかね……。"
1013505-34 = "そっかそっか。#nそれじゃあ……今日のクエストをお願いしたいと思いまーす！"
1013505-35 = "また、ですか……。"
1013505-36 = "あっ、嫌だった……？"
1013505-37 = "えっ、嫌なわけじゃ……！"
1013505-41 = "……。"
1013505-42 = "……嫌じゃ、ないです。"
1013505-43 = "なんというか、その、慣れないというか……ちょっと恥ずかしいというか……。"
1013505-45 = "きゃぁああ！"
1013505-47 = "イヤな予感――！"
1013505-49 = "ケイちゃんっ、か～わ～い～い～～！！！"
1013505-54 = "[ns] \"かわいい～～～！！！\""
1013505-55 = "なんであなたまで！！！"
1013505-56 = "すー、はー、ふぅ……それでなんだけどね。#nこれ、隣の棟の講義室に持っていってほしいんだ。"
1013505-57 = "ああ、はい……いわゆるお届け物クエストですね……。"
1013505-58 = "うん。あと今回は報酬先払いだよ。#nはいこれ、ネックレス。"
1013505-59 = "……！"
1013505-60 = "綺麗……ですね。 "
1013505-61 = "青みがかったクロムメッキと、黄色の混じった宝石……派手すぎない装飾です。"
1013505-62 = "ですがこんなに高級そうなもの……いいのですか？"
1013505-64 = "いいのいいの。[ruby=うち]新素材開発部[/ruby]のあり合わせで作ったやつだから。"
1013505-65 = "その宝石も人工のダイヤモンドで、成分的にはただの炭素だし。"
1013505-67 = "なるほど……たしかに近頃は人工物の方が優れていますからね。"
1013505-69 = "それじゃあお届け物よろしくね！"
1013505-7 = "つーかまえたっ！"
1013505-70 = "クエストが欲しい時はいつでも言ってね！"
1013505-72 = "いえ……今日はもう十分かなと。"
1013505-73 = "……はぁ。"
1013505-74 = "先生はいつまでそんなことをしてるつもりなんですか……。"
1013505-75 = "[s] \"ふふふ～\""
1013505-76 = "なんですか。"
1013505-77 = "[s] \"いいもの見ちゃったな～って。\""
1013505-78 = "どうしていつもいつもこんなタイミングで！！"
1013505-8 = "は、離して……！"
1013505-81 = "本当にもう……なんでみなさん、私にばかり――"
1013505-82 = "――待ってください。いま先生が何を言おうとしているかは全部分かってますから。#n私を大事に思ってるだとか、可愛がっているだけだとか、そんなところですよね？"
1013505-83 = "……先読みされたからって落ち込まないでください。#n大人なんですから……。"
1013505-84 = "[s] \"……学園はどう？\""
1013505-85 = "……。"
1013505-86 = "まあ悪くありません。"
1013505-87 = "[s] \"そっか、気に入ってるんだね。\""
1013505-88 = "話聞いてましたか！？勝手に意訳しないでください！"
1013505-89 = "はぁ……。"
1013505-9 = "ケイちゃん、私たちのこと嫌い？"
1013505-90 = "とにかく。私はクエスト中なので、今はあまり構わないでください。"
1013505-91 = "ん……？だから[ruby=・]ク[/ruby][ruby=・]エ[/ruby][ruby=・]ス[/ruby][ruby=・]ト[/ruby]中だって……。"
1013505-92 = "……！！！"
1013505-93 = "お、おつかいです！ただのおつかい！"
1013505-94 = "あー！またそうやって微笑んで！なんなんですかあなたは！"
1013505-95 = "[s] \"まだ何もしてないよぉ！\""
1013505-96 = "じゃあこれから禁止です！"
1013505-97 = "[s] \"表情の自由を要求する！！\""
1013505-98 = "先生は例外です！"
1013505-99 = "あっ、ケイだ。なんか楽しそうだね？"
