[translation]
1013606-1 = "あなたとココアを"
1013606-10 = "なんて言えばいいんだろ。"
1013606-100 = "……。"
1013606-101 = "………。"
1013606-102 = "…………。"
1013606-103 = "どうだろうね。"
1013606-104 = "[s] \"そこは頷こうよ。\""
1013606-105 = "関わる人が多くなると……面倒くさい。"
1013606-106 = "[s] \"そんな理由なの……。\""
1013606-107 = "大事なことだよ先生。"
1013606-108 = "人が効率を求める理由の一つは、面倒なことから抜け出すため。"
1013606-109 = "[s] \"否定はしないけど……。\""
1013606-11 = "うーん……。"
1013606-110 = "今は先生がいれば十分だし？"
1013606-111 = "[s] \"ええっ！？\""
1013606-112 = "聞こえてないふりをしてもダメだよ、先生。"
1013606-113 = "聞こえるように言ってるんだから。"
1013606-118 = "（そうして、ココアを飲み終わるまでエイミと言葉をかわし、穏やかな時間を過ごした）"
1013606-12 = "先生も来てみる？"
1013606-13 = "ここ、ちょっと不思議なんだ。"
1013606-16 = "（エイミに言われた通り、上に登ると――）"
1013606-21 = "[wa:710]― [log=에이미 결전]ようこそ、[wa:957]先生。[/log]"
1013606-23 = "― [log=에이미 결전]なんだか[wa:1540]不思議な空だよね。[/log]"
1013606-26 = "[ns] \"本当に……すごいね。\""
1013606-27 = "[wa:730]― [log=에이미 결전]私たちの知っている夜空と[wa:2890]似ているようで……。[/log]"
1013606-3 = "一日お疲れ様、先生。"
1013606-30 = "― [log=에이미 결전]よく見ると、[wa:2100]ぜんぜん違う。[/log]"
1013606-32 = "― [log=에이미 결전]今の私みたい。[/log]"
1013606-35 = "[wa:1070]― [log=에이미 결전]今まで[wa:1370]あんまりこうやって[/log]"
1013606-37 = "― [log=에이미 결전]見上げることなかったんだけど……。[/log]"
1013606-4 = "[s1] \"エイミもお疲れ様！\"\n[s2] \"あれ、今どこにいるの？\""
1013606-40 = "― [log=에이미 결전]最近、[wa:1760]好きなんだ。[/log]"
1013606-43 = "[wa:860]― [log=에이미 결전]でも[wa:740]どうしてかな。[/log]"
1013606-45 = "― [log=에이미 결전]見上げる度に、[wa:1940]先生の顔が浮かぶの。[/log]"
1013606-48 = "[ns] \"それは……どうして？\""
1013606-49 = "[wa:1720]― [log=에이미 결전]ふふっ、[wa:1610]なんでだろうね。[/log]"
1013606-51 = "― [log=에이미 결전]先生。[/log]"
1013606-54 = "― [log=에이미 결전]私、[wa:1590]先生に会えて、[wa:1820]本当によかった。[/log]"
1013606-56 = "― [log=에이미 결전]うん、[wa:1130]本当に。[wa:2225]そう、[wa:1288]思ってるよ。[/log]"
1013606-60 = "あれ……ココア？持ってきてくれたの？"
1013606-61 = "気持ちは嬉しいけど、私……熱いのは。"
1013606-62 = "[s] \"エイミの分はアイスココアだよ。\""
1013606-63 = "わぁ、ありがとう先生！"
1013606-64 = "そういうところ……好き。"
1013606-67 = "（エイミの隣に腰を下ろす）"
1013606-7 = "私？"
1013606-70 = "多分ね……。"
1013606-71 = "先生に会う前の私は――"
1013606-72 = "一人でも生きていけるんじゃないかって、本気でそう思っていたんだ。"
1013606-73 = "それを口に出したりすることはなかったんだけど……。"
1013606-74 = "たぶん、無意識のうちに、それが外にも出ていたんだろうね。"
1013606-75 = "私の場合、一人で対応したほうが効率が良かったことが多かったし。"
1013606-76 = "知識だって、自主学習で事足りてたから。"
1013606-77 = "[s] \"今は？\""
1013606-78 = "どうかな。"
1013606-79 = "少なくとも、一人だったら――"
1013606-8 = "上にいるよ。"
1013606-80 = "こうやってアイスココアを渡してもらうなんてこと、起きなかった。"
1013606-81 = "こうして、体温を分け合うこともなかっただろうね。"
1013606-87 = "（触れ合ったところからエイミの体温を感じる）"
1013606-88 = "あったかい？"
1013606-89 = "[s] \"うん、ココアが。\""
1013606-9 = "あ、偵察とかじゃなくて……。"
1013606-90 = "むぅ……。"
1013606-91 = "[s3] \"ごめんごめん。\"\n[s4] \"エイミのおかげで、寒くないよ。\""
1013606-94 = "よかった。"
1013606-95 = "……。"
1013606-96 = "なんだかいいね、こういうの。"
1013606-97 = "本当に。"
1013606-98 = "これから、もっと色んな人たちと関わって――"
1013606-99 = "たくさん変わっていく……そうなのかな？"
