[translation]
1013303-1 = "独り言"
1013303-10 = "あ……そこはダメ。"
1013303-100 = "どうやら私の見当違いだったようね。"
1013303-101 = "ただ、その他の可能性となると……思い当たる節が無いわ。"
1013303-102 = "先生、何か必要な要素を隠しているのではなくて？"
1013303-103 = "要素が欠けていたら、合理的な判断ができないじゃない。"
1013303-104 = "[s] \"あー、えっと……息抜きにコーヒーでも淹れよっか。\""
1013303-105 = "そこまで露骨だと、私だって「誤魔化された」と気がつくわよ？"
1013303-106 = "……まあ、先生のコーヒーで手を打たないこともないけれど。"
1013303-107 = "でも、要求を1つ追加させてもらうわ。"
1013303-108 = "このまま隣で、作業のサポートをしてほしいの。"
1013303-109 = "[ruby=ヘッド・マウント・ディスプレイ]HMDを付け[/ruby]て作業をしていると、周りが見えなくて不便なのよ。"
1013303-11 = "[ns] \"……？\""
1013303-110 = "もちろん、他の用事があればそちらを優先してもらって構わないわ。"
1013303-111 = "[s] \"大丈夫、手伝わせてもらうよ。\""
1013303-112 = "では……よろしくお願いするわね。"
1013303-113 = "先生なら安心してサポートを任せられるから。"
1013303-115 = "（コーヒーを淹れてから、リオの隣で作業を手伝った）"
1013303-116 = "（なんとか誤魔化されてくれてよかった……）"
1013303-12 = "先生に聞こえたら、作業の邪魔をしてしまうわ。"
1013303-13 = "できるだけ静かに……。"
1013303-14 = "[ns] \"……？？\""
1013303-15 = "（気になったので、声がする方へ行ってみる）"
1013303-2 = "（部屋での作業に区切りがついたので、気分転換に外に出てみた）"
1013303-22 = "[ns] \"リオ？\""
1013303-23 = "ん……。"
1013303-24 = "[s] \"リオ……？\""
1013303-25 = "……。"
1013303-26 = "（集中しているようで、こちらには気づいていない様子だ）"
1013303-27 = "（しばらく様子を見ることにした）"
1013303-28 = "ええ、そこよ。"
1013303-29 = "いえ……強すぎるわ、もっと慎重に……。"
1013303-30 = "……良い具合よ。そのまま続けて。"
1013303-31 = "あ、待ってちょうだい。そこは繊細なところだから、優しく……。"
1013303-32 = "そう……その調子よ。"
1013303-33 = "ん……。"
1013303-34 = "……ふう、良い感じだわ。"
1013303-35 = "では今の感覚を思い出して、もう1回やってちょうだい。"
1013303-36 = "[ns] \"……？\""
1013303-37 = "（その後もリオの独り言は止まらなかった）"
1013303-38 = "（他の誰かが帰ってくる前に声をかけておこう）"
1013303-39 = "[ns] \"えっと……リオ？\""
1013303-40 = "次はこちらをやってみましょうか。"
1013303-41 = "もう慣れたはずだし、もっと上手くできるわね？"
1013303-42 = "[s] \"リ、リオ……？\""
1013303-43 = "……？"
1013303-47 = "……！！"
1013303-48 = "せ、先生！？一体、いつから……？"
1013303-49 = "[s] \"何かを真剣に指示してたあたりから……？\""
1013303-50 = "そんな……。"
1013303-51 = "見られていたのね。"
1013303-52 = "……それならそうと早く言ってちょうだい。"
1013303-53 = "[s] \"声はかけてたんだけど……何をやってたの？\""
1013303-54 = "それは、その……。"
1013303-55 = "[s] \"言いにくいなら、無理には聞かないよ？\""
1013303-56 = "……いえ、隠す理由はないわ。"
1013303-57 = "輸送船のアップグレードをしていたの。"
1013303-58 = "このAMASを使って。"
1013303-63 = "[ns] \"なるほど……！\""
1013303-64 = "最近の作戦で、かなり良いパーツが手に入ったのよ。"
1013303-65 = "だからできるだけ人がいない時に、集中して作業をしてしまおうと思っていたの。"
1013303-66 = "あとは、その……。"
1013303-67 = "こっそりアップグレードしておいて、#nみんなを驚かせようと思っていたのだけれど……。"
1013303-68 = "[s3] \"そうだったんだ！\"\n[s4] \"やっぱリオはすごいね！\""
1013303-7 = "[ns1] \"静かだ……。\"\n[ns2] \"リオは何をしてるんだろう？\""
1013303-71 = "ありがとう……。"
1013303-72 = "それはそうと……先生、どうしてそんなに顔が赤いのかしら？"
1013303-73 = "……変な独り言を言っているように聞こえた？"
1013303-74 = "そうかしら？私は命令を出していただけよ。#nたしか――"
1013303-79 = "慎重に。"
1013303-80 = "ゆっくり。"
1013303-81 = "良い感じ。"
1013303-82 = "優しく。"
1013303-83 = "……この辺りは言った記憶があるわね。"
1013303-87 = "……問題があるようには思えないわ。"
1013303-92 = "[ns] \"そ、そうだよね！！\""
1013303-93 = "まだ何か気にかかっているのね？"
1013303-94 = "気になることがあるのなら言ってちょうだい。"
1013303-95 = "この分野についてなら、私のほうが答えられることは多いはずだから。"
1013303-96 = "あるいは……勝手に船のアップグレードをしたことが気にかかっているのかしら。"
1013303-97 = "これでも最低限の分別はわきまえているつもりよ。"
1013303-98 = "さすがの私も度を過ぎたことはしないわ。"
1013303-99 = "[s] \"それは分かってるよ！\""
