[translation]
1013605-1 = "妨害"
1013605-10 = "！？"
1013605-100 = "本当に深い意味はないよ。"
1013605-101 = "……ところで先生、知ってる？"
1013605-107 = "今の先生、もういつもの先生になったんだよ。"
1013605-11 = "ど、どうしたの、先生？"
1013605-12 = "おこって……る？"
1013605-13 = "[s] \"心配したんだよ。\""
1013605-14 = "……。"
1013605-15 = "そう、だったんだ……。"
1013605-16 = "ごめんなさい、先生……。"
1013605-17 = "私……。"
1013605-18 = "[s] \"……帰ろうか。\""
1013605-19 = "……。"
1013605-2 = "（エイミから届いたメッセージを頼りに、座標の位置へと向かう）"
1013605-20 = "うん……。"
1013605-21 = "[s] \"……無事で、よかった。\""
1013605-22 = "うん……。"
1013605-25 = "偵察の帰り道にちょっと交戦することになって……。"
1013605-26 = "その時に使いすぎちゃったみたい。#nバックパックのバッテリーがなくなっちゃったの。"
1013605-27 = "私の装備ってバックパックにあるバッテリーと連動してて。"
1013605-28 = "敵は倒せたんだけど……その結果、ああなっちゃったんだ。"
1013605-29 = "[s1] \"……そうだったんだ。\"\n[s2] \"何かあったんじゃないかって、心配したよ……。\""
1013605-3 = "（最悪の事態になっていないことを祈っていたその時……）"
1013605-32 = "それは……ごめん。"
1013605-33 = "でも、色々考えたんだけど――"
1013605-34 = "あの時、敵を倒したのは効率的な判断だったと思う。"
1013605-35 = "……効率的だとしても、私が安全じゃないと意味がない、か。"
1013605-36 = "……。"
1013605-37 = "……そっか。"
1013605-38 = "そういう考えも……あるんだね。"
1013605-39 = "ごめんなさい、先生。#n私が悪かった。"
1013605-40 = "だから、あんまり怒らないで。#n今の先生の顔、本当に怖い。"
1013605-41 = "絶対に、もうしない。"
1013605-42 = "約束する。"
1013605-45 = "……でもね先生。"
1013605-46 = "私、大丈夫だって思ってたんだ。"
1013605-47 = "一応ベースの近くだったし。#n救援信号も送れたし。"
1013605-48 = "先生が、ちゃんと受け取ってくれるって信じて待ってたし――"
1013605-49 = "……。"
1013605-50 = "……ごめん、全部言い訳になっちゃうね。"
1013605-51 = "……。"
1013605-52 = "変なの。"
1013605-53 = "今まで、言い訳なんて非効率的だと思っていたのに。"
1013605-54 = "そんな事いうくらいなら、さっさと事態を片付けたほうが早いって……そう思ってたのに。"
1013605-55 = "……。"
1013605-56 = "今の私は、もしかしたら……。"
1013605-57 = "先生に、嫌われたくないのかも。"
1013605-58 = "[s3] \"エイミを嫌ったりなんてしないよ。\"\n[s4] \"ただ……心配したんだ。すごく。\""
1013605-6 = "やっほ～#n待ってたよ。"
1013605-61 = "……。"
1013605-62 = "ありがとう、先生。"
1013605-63 = "……もう、先生にとっては今更だろうけど。"
1013605-64 = "私、ちょっとズレているところがあると思うから。"
1013605-65 = "だから、先生にお願いがあるの。"
1013605-66 = "[s] \"お願い？\""
1013605-68 = "（エイミはその場に立ち止まると、そっと目を閉じる）"
1013605-69 = "（そうして、ゆっくりと深く息を吸った）"
1013605-7 = "[ns] \"……！\""
1013605-75 = "私を、守って。"
1013605-76 = "私のことを、見つめていて。"
1013605-77 = "そうして――私が踏み外さないように、ずっと、そばで見守っていてほしいの。"
1013605-78 = "自分勝手なところがある自覚はあるよ。"
1013605-79 = "危なっかしいところがあるって思われてるのも、知ってる。"
1013605-80 = "それでも……。"
1013605-81 = "先生がそばにいるなら、私――"
1013605-82 = "きっと、大丈夫だから。"
1013605-88 = "……分かってるよ。雛はいつか巣立たないといけないってことくらい。"
1013605-89 = "でも、まだ私高校1年生だよ？"
1013605-9 = "[ns] \"エイミ！！\""
1013605-90 = "だから、まだこのままでもいいんじゃないかな。"
1013605-91 = "[s] \"……そうだね。\""
1013605-92 = "ふふっ。"
1013605-93 = "それに、もしもここから羽ばたいたとしても――"
1013605-94 = "……これは、そういう可能性の話、だけど。"
1013605-95 = "残りの時間を過ごすパートナーを探したって、いいじゃない？"
1013605-96 = "[s] \"それはどういう意味？\""
1013605-99 = "ふふっ、何でもない。ただ言ってみただけ。"
