[translation]
1013405-1 = "違いがあるということ"
1013405-11 = "警告。予期せぬトラブルが発生しました。"
1013405-12 = "[ruby=てんどう]天童[/ruby]アリスは直ちに訓練を中断し、輸送船に戻ってください。"
1013405-13 = "（アリスに関するアナウンスが船内に流れた）"
1013405-15 = "あっ、先生。"
1013405-16 = "[s1] \"大丈夫？\"\n[s2] \"怪我してない！？\""
1013405-19 = "アリスは大丈夫です。"
1013405-2 = "（アリスの様子が気になって、探しに行くことにした）"
1013405-20 = "トラブルが起きたのはアリスではなく、勇者のアーマー……アビ・エシュフの方です。"
1013405-21 = "でも……どういうトラブルが起きたのか、アリスはよく分かりません。"
1013405-22 = "ですが原因は聞きました。"
1013405-23 = "アビ・エシュフにとって変化が大きすぎたから、だそうです。#n安定させるための調整が必要だと言っていました。"
1013405-27 = "アビ・エシュフは可哀想です。"
1013405-28 = "[s3] \"可哀想？\"\n[s4] \"それは……どういう意味？\""
1013405-31 = "えっと、その……アリスも分かってはいるんです。"
1013405-32 = "アビ・エシュフは、戦闘のために作られた「兵器」なのだと。"
1013405-33 = "そこに、悲しみや喜びはありません。"
1013405-34 = "アリス、みんなから聞きました。"
1013405-35 = "アビ・エシュフはすごく強かったって。"
1013405-36 = "とてつもなく大きくて、勝ち目なんてない……チート級のアーマーだったと。"
1013405-37 = "でもそれから、戦って壊れてを繰り返して……。"
1013405-38 = "今では、アリスにピッタリになるくらいまで小さくなってしまいました。"
1013405-39 = "……もしかすると、これが最後かもしれないと言われました。"
1013405-40 = "次に壊れてしまった時には……もう、直せないって。"
1013405-41 = "それでもアビ・エシュフは、次の戦いに向けて改造が続けられています。"
1013405-42 = "最後まで、戦って終わるだけの運命だなんて……。"
1013405-43 = "アリスは……アリスはそんなの、あんまりだと思います……。"
1013405-44 = "アビ・エシュフを、ゲーム開発部の部室に連れていきたいです。#nエンジニア部のみなさんにも、見せてあげたいです。"
1013405-45 = "もっといろんな場所に一緒に行って……もっといろんな人たちと出会ってほしいです。#nそうして――"
1013405-46 = "アビ・エシュフも、みんなに愛されたらいいなと思います。光の剣みたいに。"
1013405-50 = "……教えてください、先生。"
1013405-51 = "アビ・エシュフと光の剣は、何が違うのでしょうか？"
1013405-52 = "どちらも「兵器」として作られたのは同じはずなのに……。"
1013405-53 = "始めから決まっていた運命に従うだけだなんて――"
1013405-54 = "正しくない。アリスは……そう教わりました。"
1013405-55 = "決めるのは自分自身だ、って。"
1013405-56 = "でも、アビ・エシュフは……。"
1013405-57 = "だからアリスは……アリスは……。"
1013405-62 = "先生……？"
1013405-65 = "[ns] アリスを抱きしめる。"
1013405-68 = "[ns5] \"その気持ちを忘れないであげて。\"\n[ns6] \"そうすれば、きっとアビ・エシュフも喜んでくれるよ。\""
1013405-71 = "……おかしいです。"
1013405-72 = "先生に抱きしめられると、いつもは幸せな気持ちになっていたのに。"
1013405-73 = "なぜか今は、涙が出てきます。"
1013405-74 = "これがどうしてなのか……アリスにはよく分かりません。"
1013405-75 = "[s7] \"大丈夫だよ。アリスにはまだまだ時間があるからね。\"\n[s8] \"いつか分かるようになる日が来るから。\""
1013405-78 = "……先生は不思議です。"
1013405-79 = "先生が伝えようとしてくれていることが、アリスには全然分かりません。"
1013405-80 = "でも先生がそう言えば、いつか必ずそうなる、って気持ちになります。"
1013405-81 = "だから……やっぱり先生は不思議です。"
1013405-83 = "（しばらくアリスを抱きしめ続けた）"
1013405-84 = "（アビ・エシュフの整備が済むと、アリスはまた訓練に戻っていった）"
