[translation]
1013008-1 = "The Giving Girl"
1013008-3 = "こんにちは、スバル先輩！あっ、先生もこんにちは！"
1013008-4 = "こんにちは。今日も元気そうでなによりです。"
1013008-8 = "あれ？先輩、それってもしかして……！"
1013008-10 = "伝説の、うんめえ棒バーベキューチーズ味ですか！？"
1013008-11 = "えっ、え？"
1013008-12 = "そ、そうですが……。"
1013008-16 = "……。"
1013008-17 = "食べたいですか？"
1013008-22 = "い、いいんですか……！？"
1013008-23 = "ふふっ、どうぞ。"
1013008-24 = "……ありがとうございます！"
1013008-28 = "……。"
1013008-29 = "（あとで食べようと思ってたけど……）"
1013008-30 = "[s] \"大丈夫？スバル。\""
1013008-31 = "あっ、はい！もちろんです！"
1013008-32 = "き、気にしてるように見えましたか？"
1013008-33 = "……考え過ぎですよ！"
1013008-36 = "えっ？カスタードプリン味ジュース！？"
1013008-37 = "あの幻の存在と言われるカスタードプリンの……ジュース版……！？"
1013008-38 = "……そ、そうですね。"
1013008-39 = "……。"
1013008-40 = "あのぉ……先輩。"
1013008-41 = "ひ、一口だけ……その、ダメですか？"
1013008-42 = "……。"
1013008-43 = "いいですよ。全部あげます。"
1013008-44 = "いいんですかっ！？"
1013008-45 = "もちろん。#nでも、もしよかったら他の子たちにも分けてくれると嬉しいかな、なんて。"
1013008-46 = "ありがとうございます！先輩！"
1013008-51 = "（手に入れるの、結構大変だったやつだけど……）"
1013008-52 = "[s] \"……大丈夫？\""
1013008-53 = "へっ！？"
1013008-54 = "……。"
1013008-55 = "も、もちろん！"
1013008-58 = "わあ、ありがとうございます！"
1013008-59 = "よかった。"
1013008-61 = "ありがとうございます、大事にしますね先輩！#n最高です！"
1013008-62 = "は、はい……。"
1013008-64 = "（その後も同じような流れが続き……）"
1013008-65 = "（見回りを終えたスバルの手には、ほとんど何も残っていなかった）"
1013008-67 = "……。"
1013008-68 = "[s] \"……。\""
1013008-69 = "……。"
1013008-70 = "[s] \"……。\""
1013008-71 = "ど、どうしてじっと見ているんです……？"
1013008-72 = "[s] \"私の前では隠さなくていいんだよ……。\""
1013008-73 = "ほ、本当にそういうんじゃないですから！"
1013008-77 = "……でもやっぱり。"
1013008-78 = "さっきのはたしかに、ちょっと残念というか……。"
1013008-79 = "[s1] \"これはいけませんね、スバルさん。\" \n[s2] \"ちょっとこちらへ……。\""
1013008-82 = "……えっ？  "
1013008-84 = "せ、先生？なぜここに……。"
1013008-85 = "まずは食べて……？って。"
1013008-86 = "……。"
1013008-87 = "イヤです。私、先生が何を考えているのか、だいたい分かってますから！#n絶対わたし――"
1013008-89 = "お待たせしました。ごゆっくりどうぞ。"
1013008-94 = "[ns] \"……本当にいいの？\""
1013008-95 = "だ、大丈夫です！私は平気なので！"
1013008-96 = "き、聞いてみただけですから！"
1013008-97 = "でも、なんだか私の好きなものばかり……ですね？"
1013008-98 = "[s3] \"まあね！\"\n[s4] \"この間の初当番記念パーティで、見てたから！\""
1013008-101 = "！！！"
1013008-102 = "あ、あの時はお世話になりました……が！今回はお気持ちだけいただきます！"
1013008-104 = "（意地っ張りだなぁと思いつつ、周りを見渡していると）"
1013008-108 = "（料理の一部が……なくなっていた！）"
1013008-110 = "（その後も何度か、あちこちよそ見をしていると……）"
1013008-114 = "（その都度、料理は着実になくなっていった！）"
1013008-116 = "[ns] \"おかしいなぁ～\""
1013008-117 = "なっ、何ですか。どうかしましたか？"
1013008-118 = "[s] \"なんだか料理が減ってる気がして。\""
1013008-119 = "せ、先生が食べたんじゃないんですか……？"
1013008-120 = "な、なんですかそのお顔は……？"
1013008-121 = "……も、もう！わ、分かりましたよ！"
1013008-122 = "……。"
1013008-123 = "そうです、私が食べました！ "
1013008-124 = "……先生、こんな大食いの生徒は嫌ですよね？"
1013008-125 = "[s] \"……！\""
1013008-129 = "[ns5] \"そんなわけない！たくさん食べて、たくさん大きくならないと！\"\n[ns6] \"食べる姿を見てるだけで幸せ！\""
1013008-132 = "そ、そうなんですか……？"
1013008-133 = "……。"
1013008-134 = "ありがとう、ございます……。"
1013008-135 = "えっ……？スバルにはまだ不器用なところがある……？"
1013008-136 = "素直じゃない……？"
1013008-137 = "……先生。そういうこと、他の子にも言ってませんよね？"
1013008-141 = "あのー、なんで目をそらすんですか？ちゃんとこっちを見てください。"
1013008-143 = "（なんとかスバルの追求をかわしつつ、あちこちに連れ出した！）"
1013008-151 = "[ns] \"どうだった？\""
1013008-152 = "どうと言われましても……うーん。"
1013008-153 = "よく分からない、というよりも……。"
1013008-154 = "経験がなく、慣れていないといった感じでしょうか。"
1013008-155 = "前にも、「学外での活動」はありましたけど……。"
1013008-159 = "こんな「陽の当たる場所」で……。"
1013008-160 = "穏やかな時間を過ごしたことはないので……。"
1013008-161 = "……！？"
1013008-162 = "この音はなんですか先生！？"
1013008-163 = "人間の死こそがエコロジィイイイイ――――！！"
1013008-165 = "（目を輝かせるスバルを連れてCD屋に入った）"
1013008-167 = "へびー、めたる……？これがヘビーメタルというものなんですね！"
1013008-168 = "えっと、なんといいますか……。"
1013008-169 = "強烈ですね！"
1013008-170 = "[ns] \"だ、だよね！\""
1013008-171 = "このスピード感と勢い……まるで成型炸薬弾です！"
1013008-172 = "なにより、「こんな世界ぶっ壊しちまえ」という歌詞が気に入りました！！"
1013008-173 = "[ns] \"実行するのはやめてね！\""
1013008-175 = "ふぅ……すごかったです、先生。 "
1013008-176 = "今もまだ、耳と胸が、ドンドン鳴ってるみたいで……。"
1013008-177 = "えっ？メタラーになる素質がありそう……？"
1013008-178 = "うーん、よく分かりません……ただ、自然と強く惹かれたというか。"
1013008-179 = "……特に歌詞に。"
1013008-180 = "[s] \"……やっぱり、世界が終わってほしい？\""
1013008-181 = "……。"
1013008-182 = "どうでしょう。私にもよく分かりません。 "
1013008-183 = "そんな気持ちがするような、しないような。"
1013008-184 = "でも先生も言っていましたよね。感情は単純なものじゃないって……なら。"
1013008-185 = "……。"
1013008-186 = "先生が私に「この世界はいいものだよ」って、#n確信を持たせてくれればいいんじゃないですか？"
1013008-187 = "[ns] \"くっ……そう来たか……。\""
1013008-188 = "だって先生「大人」じゃないですか。"
1013008-189 = "[s] \"それはね、無敵の言葉じゃないんだよ……？\""
1013008-190 = "ええ？でも、今までご自身で言ってたじゃないですか？"
1013008-191 = "[s] \"確かに否定はできない……。\""
1013008-193 = "（そうしてスバルと話しながら、帰路に就いた）"
