[translation]
1013406-1 = "魔法が始まる時間"
1013406-2 = "――せ。"
1013406-3 = "（……？）"
1013406-4 = "（どこからかアリスの声がする）"
1013406-8 = "せ……せい。"
1013406-9 = "（でも、アリスの姿はどこにもなかった）"
1013406-13 = "先生！こっちです！"
1013406-14 = "[ns1] 声がした方を向く。\n[ns2] 窓の外に目を向ける。"
1013406-19 = "[wa:900]― [log=아리스 결전]えへへ。[wa:1520]先生、[wa:1350]驚きましたか？[/log]"
1013406-21 = "― [log=아리스 결전]先生と一緒に、[wa:1900]この夜空を見たくて……[wa:1880]呼んだんです。[/log]"
1013406-24 = "[wa:2230]― [log=아리스 결전]とても……[wa:1630]綺麗ですね。[/log]"
1013406-27 = "― [log=아리스 결전]アリスの世界にも、[/log]"
1013406-29 = "― [log=아리스 결전]まだ行ったことのない世界にも……[/log]"
1013406-32 = "― [log=아리스 결전]きっと[wa:1140]こんな綺麗なものが[/log]"
1013406-34 = "― [log=아리스 결전]たくさんあると思うんです。[/log]"
1013406-37 = "[wa:2900]― [log=아리스 결전]でも……[wa:1430]不思議です。[/log]"
1013406-40 = "― [log=아리스 결전]世界って、[wa:1790]こんなに綺麗なのに……[/log]"
1013406-42 = "― [log=아리스 결전]どうして人は争うんでしょう？[/log]"
1013406-45 = "[wa:1740]― [log=아리스 결전]あの星空みたいに、[/log]"
1013406-47 = "― [log=아리스 결전]この世界は、[/log]"
1013406-50 = "― [log=아리스 결전]みんなで分け合っても[/log]"
1013406-52 = "― [log=아리스 결전]大丈夫なくらい[wa:1840]美しいもので[wa:780]あふれているのに……。[/log]"
1013406-55 = "[wa:2640]― [log=아리스 결전]……やっぱり、[wa:1880]アリスにはまだわかりません。[/log]"
1013406-60 = "えへへ。アリス、戻りました。"
1013406-61 = "……っくしゅっ！"
1013406-62 = "[s3] \"大丈夫？身体冷やしちゃったんじゃない！？\"\n[s4] \"風邪引いちゃったんじゃない！？\""
1013406-65 = "大丈夫です！アリスはまだ風邪を引いたことがありません！"
1013406-66 = "あっ、先生の手……。"
1013406-71 = "温かくて落ち着きます……。ふふっ。"
1013406-73 = "（温めてあげていたら、そのままアリスは眠ってしまった）"
1013406-74 = "（起こさないように、アリスを部屋まで運んであげた）"
