[translation]
1013105-1 = "もやし祭り"
1013105-10 = "2週間に1度、水曜日にもやし料理を作っておりますの。"
1013105-11 = "……私の得意料理については、聞かないでくださいね。"
1013105-12 = "せっかくですし、今日は「もやし」について批評していきましょうか。"
1013105-13 = "もやしは本当にシンプルで素直な食材ですわ。"
1013105-14 = "もやしの概要については、もう先ほどお話ししましたから、省きますわね。"
1013105-15 = "もやしは、さっと湯通ししただけでも十分美味しくいただける柔らかさが魅力ですわ。"
1013105-16 = "もちろん、温度調節が大事なのですが……間違えると食感を損なってしまいます。"
1013105-17 = "逆にそれを利用すれば、スープにしたりタレをしっかり染み込ませたりするのには最適ですわ。"
1013105-18 = "特にもやしのお味噌汁は、その独特の香りがあって、体調が優れない朝に最適だとも言われておりますの。"
1013105-19 = "[s] \"本当に何でも批評するんだね……。\""
1013105-2 = "第3公共給食所の厨房"
1013105-20 = "先生。ここだけの話ですけれど――"
1013105-21 = "今の時代、評論家はそれくらい何にでも口を出さなくては生活が立ちゆかないのですわ！"
1013105-22 = "そもそも批評というのは、議論を巻き起こしてこそ意味がある職業なのですから。これが正常といえましょう！"
1013105-27 = "……はっ、少し熱くなりすぎました。お見苦しいところを……。"
1013105-28 = "申し訳ございません、先生。"
1013105-29 = "[s] \"気にしないで、大丈夫。\""
1013105-3 = "[ns] \"タカネって、もやし好きなの？\""
1013105-30 = "では改めまして、本日の「もやし祭り」を始めるといたしましょう！"
1013105-31 = "私がいつも作っているのは、もやしと豚肉のオイスター炒めですわ！"
1013105-32 = "軽く火を通したもやしに、調味料をもみこんだ豚肉を乗せて一緒に炒めると――"
1013105-33 = "もやしから出る水分が豚肉に香りを移し、逆に豚肉の脂やタレがもやしに染み込んでいくのです。"
1013105-34 = "寒い日々が続くレッドウィンターでは、手軽にビタミンも食物繊維もエネルギーも摂れる、とっても優秀なお料理なのですわ！"
1013105-35 = "[s] \"おお、なんか楽しみになってきた。\""
1013105-36 = "それでは、少しだけお待ちくださいね！"
1013105-4 = "ええ。もやしは一番シンプルで副菜的なポジションの野菜ですけれど……だからこそ、魅力があると思っているのですわ。"
1013105-40 = "出来上がりましたわ、先生！"
1013105-41 = "ご飯にのせて召し上がっても良いですし、おかずとしていただくのもおすすめですわ。"
1013105-42 = "それともパンの方がお好きですか？即席サンドにしても美味しいですわね。ライ麦パンだとなお格別ですわ。"
1013105-46 = "[ns1] \"美味しいよ！いただきます！\"\n[ns2] \"なんだか心がほっとする……優しい味だな……。\"\n[ns3] \"生徒が作ってくれた、手料理……。\""
1013105-5 = "お値段も控えめですし、それでいてビタミンも食物繊維もちゃんと取れますのよ。"
1013105-50 = "え？そ、それは……私はただ、レッドウィンターのごく普通の生徒ですもの。"
1013105-51 = "それより、おかわりはいくらでもありますから。#nどうぞ遠慮なく、たくさん召し上がってくださいね！"
1013105-53 = "（こうしてタカネと一緒に、心まで温まる食卓を囲んだのだった）"
1013105-6 = "それに、本当に火の通りが早いんです。#nそのおかげで軽く炒めるだけでも十分食べられますが――"
1013105-7 = "あっという間にくたっとしてしまうのが難点なのですよね。#nそこがまた、腕を問われるといいますか。"
1013105-8 = "[s] \"なるほど……。それで「もやし祭り」って？\""
1013105-9 = "……それは、私が勝手に名前をつけただけなんですけど。"
