[translation]
1013403-1 = "始まりの町"
1013403-3 = "あの、先生……これは？"
1013403-4 = "[ns] \"特訓だよ！！\""
1013403-5 = "えっと、でもこれは……。"
1013403-6 = "普通のゲーム……ですよね？"
1013403-7 = "[ns] \"特訓だよ！！\""
1013403-8 = "た、大変です！"
1013403-9 = "先生が壊れてしまいました！"
1013403-10 = "[s1] \"考えてみたんだけどさ。\"\n[s2] \"アリスはまだ勇者のアーマーに慣れてないんだと思うんだ。\""
1013403-15 = "[ns3] \"だから、まずは体に馴染ませるところからかなって。\"\n[ns4] \"緊張せずにアーマーを着られるようになろう！\""
1013403-18 = "体に馴染ませる……？"
1013403-19 = "勇者のアーマーを着用して、ゲームをするだけでいいのですか？"
1013403-23 = "うぅん……。"
1013403-24 = "それがどうして修行になるのか、アリスにはよく分かりません。"
1013403-28 = "先生？なぜ電気を消すのですか？"
1013403-29 = "え……？電気を消した方が、没入感があって面白い……？"
1013403-30 = "それは、アリスもそう思いますが……。"
1013403-31 = "電気を消してゲームをすると目が悪くなる！と、先生はいつも言っていました！"
1013403-32 = "[s5] \"そう、普段はダメだよ。\"\n[s6] \"でも、今日は特訓だから。\""
1013403-35 = "……！"
1013403-36 = "アリス、なんだかドキドキしてきました！"
1013403-37 = "夜遅くまでゲームをしていて、こっそりコンビニに行った時と似た感じです！"
1013403-41 = "……はっ！これは内緒なんでした。"
1013403-42 = "そ、それよりもゲームです！何をプレイしたらいいですか？"
1013403-43 = "えっ、好きなものでいい……？"
1013403-44 = "アリス、好きなゲームはたくさんあります！"
1013403-50 = "……どれも名作ばかりで選べません！"
1013403-54 = "たとえばこれ！"
1013403-55 = "これは、大きな武器でドラゴンを狩るゲームです！"
1013403-56 = "ドラゴンを狩って入手した素材で、もっと強い武器を作って、もっともっと強いドラゴンを狩ります！"
1013403-57 = "もちろん良い装備だからといって、すぐに強くなるわけじゃありません！#nプレイヤー本人が強くならなければ意味がないのです！"
1013403-61 = "まさに、今のアリスにぴったりなゲームかもしれません！"
1013403-62 = "[s] \"じゃあそれにする？\""
1013403-63 = "……たしかに、アリスはこのゲームが好きです。"
1013403-64 = "でも、今はその時ではない気がします。すごくプレイ時間が長いので……。"
1013403-65 = "やっぱりもう少しだけ見てみます。"
1013403-66 = "……あっ、これは！"
1013403-70 = "すごく難しいことで有名なゲームです！"
1013403-71 = "プレイヤーを即死させる罠がフィールドのあちこちにあって……。"
1013403-72 = "なんとかボスにたどり着いても、予備知識がなければ一瞬で負けてしまうんです！#n何度も何度も挑戦して、プレイヤーが成長しないとクリアできないゲームです！"
1013403-73 = "だからこそ、クリアした時の達成感は他とは比べ物になりません！"
1013403-74 = "……これも、今のアリスみたいですね。"
1013403-75 = "[s] \"じゃあそのゲームにする？\""
1013403-76 = "……いいえ。#nたしかに好きなゲームではありますが……。"
1013403-77 = "このゲームをプレイしたら、勇者のアーマーにトラウマができてしまいそうです……。"
1013403-78 = "他に……プレイ時間がちょうどよくて、気持ちが落ち着くようなゲームは……。"
1013403-83 = "……あ。"
1013403-87 = "決めました。アリス、これがいいです。"
1013403-88 = "[s7] \"それは……。\"\n[s8] \"『テイルズ・サガ・クロニクル』？\""
1013403-91 = "はい！無印の『テイルズ・サガ・クロニクル』です！"
1013403-92 = "アリスが入る前のゲーム開発部が作った作品です。"
1013403-93 = "だからアリスは、このゲームの製作に関わっていません。#nですがゲームを進めていくと、みんなの思いがすごく伝わってきます。"
1013403-94 = "そして何よりこのゲームは――"
1013403-95 = "クソゲーです！"
1013403-96 = "[s9] \"アリス！？\"\n[s10] \"だいぶ変わってるゲームだとは聞いてたけど……！\""
1013403-99 = "それが事実なのです！"
1013403-100 = "最初はアリスも分かりませんでしたが、たくさんゲームをプレイしてきた今なら断言できます。"
1013403-101 = "『テイルズ・サガ・クロニクル』はクソゲーです！"
1013403-105 = "……でも、いいんです。"
1013403-106 = "これは……アリスが初めてプレイしたゲームなんです。"
1013403-107 = "このゲームは、アリスのことを初めて「勇者」と呼んでくれました。"
1013403-108 = "……やっぱり、アリスはこのゲームが好きです。"
1013403-109 = "それに、プレイ時間もちょうどいいです！"
1013403-110 = "攻略法さえ分かれば、3時間でトゥルーエンドを見られるのですから！"
1013403-111 = "先生！アリスと一緒にやりましょう！"
1013403-113 = "（勢いに押されて 『テイルズ・サガ・クロニクル』をプレイすることになった）"
1013403-115 = "[56cd7b]コスモス世紀2354年、人類は劫火の炎に包まれた――[-]"
1013403-116 = "正統派ファンタジーRPGなのに、こんなオープニングです！"
1013403-117 = "それに「コスモス世紀」という固有名詞は、ここでしか出てきません！"
1013403-118 = "[56cd7b]チュートリアルを開始します。[-]"
1013403-120 = "[56cd7b]まずはBボタンを押して、目の前の武器を装着してみてください。[-]"
1013403-121 = "あ、これは罠です。ここでBボタンを押したらゲームオーバーです。"
1013403-122 = "Aボタンを押すと進められます。"
1013403-124 = "[ns11] \"想像以上に難しいゲームだね……。\"\n[ns12] \"3時間でクリアできるかな？\""
1013403-127 = "攻略法を知らなければ一生クリアできないかもしれません。"
1013403-128 = "しかしアリスのようなベテランプレイヤーなら余裕です！"
1013403-130 = "あっ。 "
1013403-131 = "敵とエンカウントせずに最初の町に着きました。"
1013403-132 = "序盤は回復手段が限られるので、これはラッキーです！"
1013403-138 = "……この、「始まりの町」のBGM。"
1013403-139 = "アリスはすごく好きです。#n聞いていると、初めてこのゲームと出会った時を思い出します。"
1013403-140 = "……ふふっ。"
1013403-141 = "とても不思議です。あの時のアリスは、まだ何も知りませんでした。"
1013403-142 = "あれから光の剣を手に入れ、仲間と出会い、数々の冒険を経て――"
1013403-143 = "今はこのように、はるか遠くの氷海にまで来ています。"
1013403-144 = "本当に、勇者の冒険みたいです。"
1013403-145 = "……この「始まりの町」は、アリスにとっても始まりの場所なんです。"
1013403-149 = "……あっ！モンスターとエンカウントしました！"
1013403-150 = "ダブルショットガンを使うプニプニです！#n近接では難しいのでここは――"
1013403-152 = "（アリスと『テイルズ・サガ・クロニクル』を進めた）"
1013403-153 = "（しばらくして……）"
1013403-156 = "……ラスボスを倒しました！クリアです！"
1013403-157 = "……先生？どうかしましたか？"
1013403-158 = "悲しそうな子犬みたいな顔をしています！"
1013403-159 = "[s] \"アリス……聞いてもいい？\""
1013403-163 = "[ns13] \"どうして母親がヒロインで、それでいて実は前世の妻で……。\"\n[ns14] \"どうして腹違いの友人がタイムリープしてきてるんだろう？\""
1013403-167 = "アリスにも分かりません！"
1013403-168 = "……でも。"
1013403-169 = "面白いと思いませんか？"
1013403-170 = "[s15] \"……そうだね。\"\n[s16] \"すごく面白かった。\""
1013403-173 = "先生がアリスと一緒で嬉しいです！アリスもすごく楽しかったです！"
1013403-174 = "では次は――"
1013403-176 = "（自然とゲームを続けることになり）"
1013403-177 = "（アリスといろんなゲームをしながら過ごした）"
