[translation]
1013509-1 = "流れる夕暮れ時"
1013509-106 = "[ns] \"あれ……。\""
1013509-107 = "先生……？"
1013509-108 = "どうかしましたか？"
1013509-113 = "[ns] \"……！\""
1013509-114 = "先生？"
1013509-119 = "えっ？私が霞んだり、いなくなったりした……？"
1013509-12 = "いきなり飛びつこうとしないでください！撃ちますよ！？"
1013509-120 = "私はずっとここにいましたよ……？"
1013509-121 = "……。"
1013509-122 = "やっぱり疲れているみたいですね。#n疲れがでると、真っ先に視力がやられますから。 "
1013509-123 = "今日は無理をしないほうがいいでしょうね。"
1013509-126 = "[wa:2180]― [log=케이 교복]心配しないでください。[/log]"
1013509-127 = "[wa:2780]― [log=케이 교복]私が消えることはありません。 [/log]"
1013509-130 = "[wa:560]― [log=케이 교복]むしろ、[wa:1320]その逆ですね。[/log]"
1013509-131 = "[wa:2620]― [log=케이 교복]私は、[wa:1540]どんな手を使ってでも[wa:1130]生き残ってやるつもりですから。[wa:40] [/log]"
1013509-134 = "[wa:3530]― [log=케이 교복]先生がこの世界を[wa:1250]見捨てないというのなら。  [/log]"
1013509-135 = "[wa:3540]― [log=케이 교복]私だって最後まで、[wa:1990]絶対に諦めたりしません。  [/log]"
1013509-138 = "[wa:500]― [log=케이 교복]だから大丈夫……[wa:2360]絶対、[wa:1860]大丈夫です。  [/log]"
1013509-139 = "[wa:2320]― [log=케이 교복]私はずっと[wa:1730]ここにいます。[/log]"
1013509-14 = "そもそもの話。シャーレの仕事って意見の提案だったり仲介の類じゃないですか。"
1013509-142 = "[wa:2730]― [log=케이 교복]ここだけの話ですけど……[wa:2840]私は――[/log]"
1013509-143 = "[wa:2740]― [log=케이 교복]先生のこと、[wa:2280]嫌いじゃありませんから。[/log]"
1013509-15 = "そういうのは当事者たちが話し合って、ルール内でケリをつければいいはずです。#nだというのにわざわざシャーレにまで持ちこんで……。"
1013509-155 = "（いつもより少しだけゆっくりと、ケイをミレニアムまで送った）"
1013509-156 = "（最初はぎごちない距離で歩いていたけれど……）"
1013509-157 = "（気がつくと、小さな手が私の小指を握っていた）"
1013509-16 = "それにセキュリティ上の問題があるからといって、未だに紙を使っているのもどうかと思います。"
1013509-17 = "もちろんネットワークに完璧なセキュリティなんてあり得ませんけど。"
1013509-18 = "それならそれで上位セキュリティを要する案件を、極力減らせばいい話では……？"
1013509-19 = "[s] \"人間の営みってそういうものだから……。\""
1013509-20 = "それで先生が疲弊していたら元も子もないでしょう？"
1013509-21 = "仕事が減ったり、せめて現状維持ができるなら文句は言いません。 "
1013509-22 = "でも分かってますよね？仕事が減ることなんてないって。"
1013509-23 = "それどころかシャーレが問題を解決すればするほど、周りはもっと問題を持ち込んでくるようになるわけです。"
1013509-24 = "というか先生、本来は教育者なんですよね？"
1013509-25 = "生徒にああだこうだと言いつつ、あなた自身の本分をお忘れではないですか？"
1013509-26 = "[s1] \"そう、だね……。\"\n[s2] \"これじゃ教えるべきことも忘れちゃうかも……。\""
1013509-29 = "まったく他人事みたいに……。"
1013509-3 = "[ns] \"シャーレにようこそ！\""
1013509-30 = "一旦この書類は終わってます。"
1013509-31 = "いや、そんなに喜ばれても……当番として当然のことをやっただけで……。"
1013509-32 = "キヴォトスも難儀なものですよね。"
1013509-33 = "生徒たちがやりたい放題。だから毎日意味不明なことばかり起きるんです。"
1013509-34 = "といっても生徒とは、すなわち子供です。"
1013509-35 = "そうそう自己統制ができないのも致し方ありません。"
1013509-36 = "だからこそ、建築業が花形産業なわけですが。"
1013509-37 = "[s] \"キヴォトスは学園都市だからね……。\""
1013509-38 = "それにしたって見てられないんですよ。"
1013509-39 = "こういうのは誰かが倒れてから、やっと周りは気がつくんです。"
1013509-4 = "大げさです！"
1013509-40 = "……はい、これ。#nこの手順で行ってください。統計資料です。"
1013509-41 = "たまには数字が全部証明してくれますから。"
1013509-45 = "[ns] \"ケイちゃん。\""
1013509-46 = "はい？"
1013509-5 = "……というか別に初めてじゃないですよね？"
1013509-51 = "[ns] \"大好き！！\""
1013509-52 = "バカなこと言ってないで仕事を進めてください！！"
1013509-58 = "[ns] \"なんとか今日が終わりそう……。\""
1013509-6 = "[s] \"何度だって私は嬉しいからね！\""
1013509-61 = "……大丈夫ですか？"
1013509-62 = "えっ？心配されて元気になった……？"
1013509-63 = "はぁ……心配して損した。"
1013509-64 = "はい？ごはん、ですか？一緒に……？#nえ、アクセサリーも買いに行く……？"
1013509-65 = "先生、お疲れなんじゃないですか……？#nさっきだって倒れそうになって。"
1013509-66 = "……大丈夫？#nまあ、それなら。そうしましょうか。"
1013509-67 = "……。"
1013509-68 = "そういえば、明日の当番は誰ですか？"
1013509-69 = "[s] \"たしか……。\""
1013509-7 = "……。"
1013509-73 = "[ns] \"あれ？なんかのトラブルで未定みたい。\""
1013509-74 = "……それでいいんですか？"
1013509-75 = "午前中までに声をかければいいから大丈夫……？"
1013509-76 = "……。"
1013509-77 = "じゃあ、私にしませんか？"
1013509-78 = "[s] \"ええっ！？\""
1013509-79 = "なっ、なんでそんな顔をするんですか？"
1013509-8 = "別に私だって嬉しくないわけじゃ……。"
1013509-80 = "こ、これだって言ってしまえば……！"
1013509-81 = "そ、そうです！私のキヴォトス適応訓練だったり、シャーレの業務把握に、対人折衝能力の向上のためで……！"
1013509-82 = "上昇の見込めない部費に、偏り続ける業務負担の問題に、シャーレの未来と、先生のあれそれと――あと、あと……！"
1013509-83 = "とにかく！そういったもののための訓練と、実践……！"
1013509-84 = "つまり先生にとっても私にとっても、合理的な判断ってことです！感謝してください！"
1013509-85 = "[s] \"「合理的」って……まるで……。\""
1013509-86 = "！！"
1013509-87 = "い、今のは言葉のあやで……うう、こ、こんな屈辱……！"
1013509-88 = "とにかく！いいですね！"
1013509-89 = "[s] \"ケイちゃん。\""
1013509-90 = "何ですか。"
1013509-91 = "[s] \"1回だけ、頭を撫でてもいい……？\""
1013509-92 = "もしもそんなことしたら、先生を殺して私も死にます！！"
1013509-94 = "それでは、お疲れ様でした。"
1013509-95 = "どのみち明日も私が当番ですし。残りは明日でもいいでしょう。"
1013509-96 = "……何してるんですか、行きますよ。#n一緒にご飯を食べて、他にもいろいろするのでしょう？"
1013509-97 = "[s] \"うん、ちょっと待ってね。\""
1013509-99 = "（立ち上がろうとしたその時――）"
