[translation]
1013006-1 = "夕暮れのハーモニカ"
1013006-4 = "[ns] \"スバルの欲しいもの探しだ！！！\""
1013006-5 = "こ、声が大きいです！！！"
1013006-6 = "[s] \"せっかくだし、楽しまなきゃ！！\""
1013006-7 = "こういう時の先生は本当に……！"
1013006-9 = "それで……何が欲しかったのか、といいますと。"
1013006-10 = "えっと……。"
1013006-11 = "……。"
1013006-12 = "楽譜、です。"
1013006-13 = "[s] \"ん？ごめん、よく聞こえなかった。\""
1013006-14 = "う、うぅ……だ、だから。"
1013006-15 = "……。"
1013006-16 = "楽譜です、楽譜っ！！できれば、ハーモニカで吹けるやつのっ！"
1013006-18 = "ふぅ……。"
1013006-19 = "[s] \"満足した？\""
1013006-20 = "満足……。"
1013006-21 = "したような、してないような。"
1013006-22 = "初めてのショッピングというものをした割には、楽しめた気がする、といいますか。"
1013006-23 = "[s] \"……また来ようね。\""
1013006-24 = "ショッピングにですか？"
1013006-25 = "無理ですよ。私あまりお金ないですし。"
1013006-26 = "えっ？今日もそんなにお金を使ったわけではない、って……？"
1013006-27 = "それはそうなんですが……。"
1013006-28 = "ただ見て回るだけでも、楽しいけど……。"
1013006-29 = "でも……「いつか手に入れたくなる」じゃないですか。"
1013006-30 = "そんな欲望のおかげで生きる気力が湧く方もいるんでしょうけど……。#n私は、その気持ちを抑えなくては、と思ってしまうんです。"
1013006-31 = "欲望はその場では満たせても、また次の欲望が生まれます……。"
1013006-32 = "結局、満たされるものなんてないんです。悲しいですが。"
1013006-33 = "……。"
1013006-34 = "先生。私はもしかしたら……何事にも完璧な答えを求めているのかもしれません。"
1013006-35 = "「満たされる欲望」と同じくらい、ありえない話かもしれないです。#nでも、もしかしたら、どこかに正解があるのかも、なんて――"
1013006-36 = "そんな期待を、抱いているんです。"
1013006-37 = "解決できない、答えのない問題に、たくさん出会ってきましたから。"
1013006-38 = "[ns1] \"……うん。\"\n[ns2] \"スバルはそれを言う資格があると思う。\""
1013006-41 = "……ありがとうございます。"
1013006-42 = "でも、こんなことを考えたところで、空しいだけですよね。ははっ。"
1013006-43 = "[ns3] \"そんなことないよ。\"\n[ns4] \"たとえそうだとしても、今を頑張らない理由にはならないから。\""
1013006-46 = "……。"
1013006-47 = "[s5] \"スバルがハーモニカを演奏することも。\"\n[s6] \"楽譜を買ったことも。\"\n[s7] \"いつか全部消えたとしても、意味があることだからね。\""
1013006-51 = "……！"
1013006-52 = "……はい。"
1013006-53 = "音は、すぐ消えてしまうけれど……心に刻まれるものですからね。"
1013006-54 = "……私は、ときどき恥ずかしくなりますけど。"
1013006-60 = "趣味を恥ずかしがることない……？わ、分かってますよ、頭では。"
1013006-61 = "私にとっては心が和むものですし、後輩のみんなも喜んでくれます。"
1013006-68 = "でも、それ以前に……。"
1013006-69 = "自分をかっこよく見せるためにやってるんじゃないか？と思う時があるんです。"
1013006-70 = "わーっ……こ、言葉にすると恥ずかしいですね……！"
1013006-71 = "[ns8] \"大丈夫、大丈夫。\"\n[ns9] \"いいんだよそれで。\""
1013006-74 = "もう、他人事みたいに……。"
1013006-78 = "……。"
1013006-79 = "先生。"
1013006-80 = "よかったら川の方に行きませんか？"
1013006-81 = "先生に聞かせたいものがあって。"
1013006-83 = "（スバルに連れられてゆっくり川へ向かった）"
1013006-84 = "（そうこうしているうちに、夕方になっていた）"
1013006-86 = "（スバルは立ち止まると、ハーモニカを吹き始めた）"
1013006-87 = "（夕風が頬を撫でる中、綺麗な音色が響く）"
1013006-91 = "[wa:1890]― [log=니코 스바루]なんだか、[wa:1380]新鮮な気持ちです。[/log]"
1013006-93 = "― [log=니코 스바루]こうして誰か[wa:660]一人のために[wa:820]演奏するのは[wa:1380]初めてで……。[/log]"
1013006-96 = "[wa:770]― [log=니코 스바루]どう、[wa:1440]でしたでしょうか？[/log]"
1013006-98 = "― [log=니코 스바루]変じゃ、[wa:1890]なかったですか……？[/log]"
1013006-101 = "[ns] \"最高の演奏だったよ。\""
1013006-103 = "[wa:1260]― [log=니코 스바루]それって……[wa:1760]その、[/log]"
1013006-105 = "― [log=니코 스바루]本心、[wa:1510]と受け取って[wa:770]いいんですよね？[/log]"
1013006-108 = "― [log=니코 스바루]……ありがとうございます。[/log]"
1013006-111 = "[wa:400]― [log=니코 스바루]本当は、[wa:1440]他に何かできることが[wa:1190]あれば[/log]"
1013006-113 = "― [log=니코 스바루]よかったのですが……。[/log]"
1013006-116 = "― [log=니코 스바루]今の私には、[/log]"
1013006-118 = "― [log=니코 스바루]これくらいしかなくて……。[/log]"
1013006-121 = "[wa:370]― [log=니코 스바루]えっ？[/log]"
1013006-123 = "― [log=니코 스바루]「また練習したら[wa:930]聞かせてほしい」……？[/log]"
1013006-126 = "― [log=니코 스바루]「楽譜も[wa:790]たくさん買ったから」……？[/log]"
1013006-129 = "[wa:360]― [log=니코 스바루]そ、[wa:990]それは……。[/log]"
1013006-132 = "― [log=니코 스바루]また……[wa:1320]その時になったら、[/log]"
1013006-134 = "― [log=니코 스바루]考えさせてください。[/log]"
