[translation]
1013202-1 = "もう一度モデル、に……！"
1013202-10 = "す、すごい方が来られるので、よろしくお願いしますって……。"
1013202-100 = "えへへっ……。"
1013202-101 = "……良かった、です。"
1013202-102 = "無事に終わりましたし、帰りま――"
1013202-104 = "おいおい、ちょっと待ってくれや。"
1013202-108 = "えっ……？"
1013202-109 = "まさか……そのまま帰るわけじゃないよな、ツクヨさん？"
1013202-11 = "[s] \"すごい方！？\""
1013202-110 = "……？"
1013202-111 = "……あの条件はどうした？"
1013202-112 = "まさか、忘れちまったのか？"
1013202-113 = "あっ！#n急いでいたので、つい……。"
1013202-114 = "[s] \"っ、その条件って……！\""
1013202-118 = "……へぇ、あんたも知ってるのか？"
1013202-119 = "ならコソコソする必要も無いな……。"
1013202-12 = "えへへ……#nこうして舞台裏でお話をしていると、不思議な感じが、しますね。"
1013202-120 = "そう、その条件とは――"
1013202-124 = "「柴犬ワン蔵」監督の13作目、『忍者は七度生きる』の試写会パンフレットを渡すことっ！"
1013202-125 = "[s] \"…………え？\""
1013202-126 = "『忍者は七度生きる』……かなりの秀作だが、試写会が極めて小規模だったせいで、パンフレットは今や入手困難。"
1013202-127 = "だがしかし！#n何を隠そう、その試写会の主催者は我が社だったのさ！"
1013202-128 = "社長権限を使って会社の倉庫からパンフレットを回収、通常のギャラに加えてこれを渡すという条件で、ツクヨさんは契約をしてくださった……！"
1013202-129 = "[s] \"そうだったの！？\""
1013202-13 = "こ、こっそり会っているような、感じで……。"
1013202-131 = "はい！すごく、珍しいパンフレットなんです……！#n部室に飾れば、部長もイズナちゃんも喜んでくれると、思います！"
1013202-132 = "ふぅ……このためにモデルを、引き受けたのに……。"
1013202-133 = "うっかり、帰ってしまうところ、でした……えへへ。"
1013202-134 = "ところでツクヨさん。"
1013202-135 = "これもなにかの縁ってことでよ、業界復帰とか考えてみねぇか？"
1013202-136 = "……はい？"
1013202-137 = "実はこの間、ファッションカンファレンスでシャインキャットさんと話す機会があってよ。"
1013202-138 = "まだ、ツクヨさんに未練があるみたいでさ。#n今回も受けてくれたんだ。これを機に、考えてみちゃくれねぇか？"
1013202-139 = "そ、そんな……。"
1013202-14 = "[s1] \"たしかにね。\"\n[s2] \"そういえば、ショーの準備は順調？\""
1013202-140 = "す、すごくありがたいお話、ですけど……。"
1013202-144 = "正直、あの時間に戻るのは、怖いです……。"
1013202-145 = "地獄のトレーニングに……食事制限……ライトの下、歩き出す緊張感……。"
1013202-146 = "まあ、ハイファッションモデルの仕事って、才能だけじゃ耐えられない領域だしな……。"
1013202-147 = "悪い。余計なことを言ったな。"
1013202-148 = "い、いえ！むしろ気をつかっていただいて、ありがとうございます！"
1013202-149 = "じゃあ、しっかり渡したからな。失礼するよ。#n良い仕事だったぜ、あんがとな！"
1013202-153 = "な、なんだか申し訳ないです……。"
1013202-158 = "あっ、え、えっと……実は何日か、食事制限をしていたので……。"
1013202-159 = "[s] \"じゃあ、今日は私がご馳走するよ。\""
1013202-160 = "えっ……？"
1013202-161 = "そんな……い、良いんです、か……？"
1013202-162 = "[s5] \"働かざる者、食うべからず。\"\n[s6] \"つまり、働き者のツクヨはたくさん食べるべし！\""
1013202-165 = "……！"
1013202-166 = "そ、それでしたら……。"
1013202-167 = "お言葉に甘えて……ありがとうございます、先生！"
1013202-169 = "（受け取ったレシートの長さに一瞬驚いたが……）"
1013202-17 = "はい。#n衣装の合わせは、終わったので……リハーサルを、していました。"
1013202-170 = "（ツクヨの笑顔を見ていたら、どうでも良いと思えた）"
1013202-18 = "今はヒールの高さに慣れようと、思って……本番用の靴を履いて、います。"
1013202-19 = "[s] \"流石、プロだね！\""
1013202-2 = "ファッションショー会場・舞台裏"
1013202-23 = "そ、そんな……！"
1013202-24 = "わ、私なんかよりも、経歴の長いプロの方が沢山、いらっしゃいますし……！"
1013202-25 = "それに、モデルの仕事はこれで、最後にしようと……。"
1013202-26 = "あっ……せ、先生から見て、どうでしょうか？"
1013202-32 = "このドレス、着こなせてますで、しょうか……？"
1013202-33 = "[s3] \"似合ってるよ！\"\n[s4] \"ツクヨらしい着こなしだね！\""
1013202-36 = "ふ、ふぇええ……。"
1013202-37 = "あ、あまり持ち上げないで、ください……。"
1013202-38 = "ですが……そう言っていただいて、すごく嬉しい、です。#nえへへっ……。"
1013202-39 = "[s] \"そういえば、どうしてまたモデルの仕事を？\""
1013202-4 = "（モデルの仕事は辞めたはず……ツクヨのことが心配になって、現場見学を申し出た）"
1013202-40 = "実は数日前に、シャインキャットエージェンシーから……オファーを、頂いて。"
1013202-41 = "最初は断ろうと、したのですが……。"
1013202-42 = "話を聞いたところ、一日だけだから、と……。"
1013202-43 = "何より、その……。"
1013202-45 = "主催の方から……ある条件を、提示されて。"
1013202-46 = "[s] \"ある条件……？\""
1013202-47 = "……はい。"
1013202-48 = "私は一度、モデルをやめたわけですし……。"
1013202-49 = "少しだけ抵抗も、ありました、けど……。"
1013202-5 = "あっ、先生……！#nこちら、です！"
1013202-50 = "その条件なら……引き受けよう、と。決めました。"
1013202-51 = "[s] \"……どんな条件なの？\""
1013202-52 = "それは――"
1013202-56 = "開演10分前です、スタンバイお願いします。"
1013202-57 = "あっ、続きは、後ほど……。"
1013202-58 = "では、行ってきますね……先生！"
1013202-6 = "迷いません、でしたか？"
1013202-64 = "（少し嫌な予感がして……）"
1013202-65 = "（できるだけ近くから、ツクヨを見守ることにした）"
1013202-67 = "ファッションショーイベント会場"
1013202-69 = "（しばらく待っていると、本番が始まった）"
1013202-7 = "[s] \"スタッフの方が案内してくれたから。\""
1013202-8 = "よ、良かった、です……。"
1013202-85 = "（ツクヨはモデルの仕事を見事にこなし……）"
1013202-86 = "（ショーは何事もなく進んだ）"
1013202-9 = "実は、事前に言っておいたんです。"
1013202-92 = "ファッションショー会場・外"
1013202-93 = "（終了後、会場の外でツクヨと待ち合わせをした）"
1013202-97 = "先生！"
1013202-98 = "すみません、遅く、なりました……！"
1013202-99 = "[s] \"ううん、お疲れ様。\""
