[translation]
1013602-1 = "効率・非効率"
1013602-10 = "うーん、いいけど……。#n万が一、何かあったら……。"
1013602-100 = "……。"
1013602-101 = "前の私だったら、非効率的だと思ったんじゃないかな。"
1013602-102 = "でも、なんだか不思議。"
1013602-103 = "今は、協力したいって思えるんだ。"
1013602-104 = "[s] \"そう思えるなら良かった。\""
1013602-105 = "うん。"
1013602-106 = "先生の言葉も、ちょっとあるかな。#nふふ。"
1013602-108 = "（その後、エイミと言葉を交わしながらみんなの元へ戻った）"
1013602-14 = "……まあ、いっか。私が守ってあげる。#nどんなことがあっても。"
1013602-17 = "（エイミと一緒に外に出た）"
1013602-20 = "こっちから偵察していくよ。#nだいたい2時間くらいかかるかな。"
1013602-21 = "時速4キロくらいでゆっくり進んでいく予定。"
1013602-22 = "あ、でもそれより遅くても大丈夫だよ。#nゆっくりすぎるとちょっと困っちゃうけど。"
1013602-23 = "ほら、距離が空いちゃったら先生を守れないでしょ？#nあんまり離れすぎないようにね。"
1013602-25 = "（そうして、エイミと一緒に偵察を始めた）"
1013602-29 = "（エイミのペースは速く、ついていくのは大変だった……）"
1013602-32 = "すごいね。先生、ちゃんとついてきてる。"
1013602-33 = "[s] \"お世辞でも、嬉しいよ……というか、これ……ついて、いけてると言えるの、かな……。\""
1013602-34 = "お世辞じゃないよ。#n誰かさんだったらすぐバテてただろうし。"
1013602-35 = "え？うん、ペース配分って大事だよね。先生の言う通り。"
1013602-36 = "私もそうは思うけど……。"
1013602-37 = "……まぁ、慣れもあるからね。難しい。"
1013602-38 = "っ！？"
1013602-39 = "先生、隠れて！"
1013602-4 = "おはよう。お寝坊さんだね、先生。"
1013602-43 = "（突然、エイミの手によって割れた大地の隙間に押し込まれる）"
1013602-44 = "急にごめんね。"
1013602-45 = "私がもう大丈夫って言うまで、そこにいてほしい。"
1013602-46 = "数は――分隊1つくらいか。#nそれなら……！"
1013602-5 = "[s] \"おはよう。朝から元気だね……。\""
1013602-53 = "もう大丈夫だよ先生。"
1013602-54 = "……これで全部じゃないとは思うけどね。"
1013602-56 = "（その後もエイミは――）"
1013602-6 = "まあ、今は普段と状況が違うからね。できることはしないと。"
1013602-60 = "座標確認。距離……427m。#n先手を打つよ……！"
1013602-63 = "（目にも止まらぬ速度で動く敵の軍勢を前に……）"
1013602-66 = "もうちょっと待った方が――"
1013602-67 = "いや、先に処理して移動した方がいいかな。"
1013602-68 = "事態が大きくなってからだと非効率的だし……！"
1013602-7 = "といっても、威力偵察くらいしかないんだけど……。#nあ、そういえば――"
1013602-73 = "こっちの居場所はバレてないみたい……#n敵の装備的に、あれはたぶん輸送隊……。"
1013602-74 = "それなら――[ruby=サーチアンドデストロイ]Search and Destroy[/ruby]！"
1013602-77 = "（エイミは驚くほど上手に威力偵察を進めていった……）"
1013602-8 = "さっき、ちょっと気になる信号を拾ったんだ。#n今から向かうところ。"
1013602-80 = "よし。危険信号はもうないよ。"
1013602-81 = "お疲れ様、先生。そろそろ帰ろう。"
1013602-82 = "[s] \"いつもこんな風にしてるの……？すごい……。\""
1013602-83 = "大したことじゃないよ。いつもこうだし。"
1013602-84 = "人使いが荒いどこかの誰かさんがいるからさ……。"
1013602-85 = "まあ別に本人にも言ってることだけどね。"
1013602-86 = "[s] \"な、仲良くしようね……。\""
1013602-87 = "別に仲は良い方だよ？"
1013602-88 = "……。"
1013602-89 = "……思えば、いつも一人だったから団体行動って初めてかも。"
1013602-9 = "[s] \"私もついて行っていい？\""
1013602-90 = "人数が増えたら効率が落ちるって思ってたし。"
1013602-91 = "……私と一緒に行動するの、怖がる人もいたから。"
1013602-92 = "……私の考えって、あんまり理解してもらえなかったんだよね。"
1013602-93 = "[s] \"今はどう？\""
1013602-94 = "今は……。"
1013602-95 = "なんでだろ。意外と平気。"
1013602-96 = "みんな変わってるからかな？気が合うというか……。"
1013602-97 = "すごく居心地が良いんだ。"
1013602-98 = "[s] \"生徒同士、できるなら仲良くした方が良いからね。他の子とも。\""
1013602-99 = "他の子とも、か……。"
