[translation]
1013003-1 = "最初の一歩"
1013003-10 = "[ns] \"スバルの初当番記念パーティーだよ！\""
1013003-100 = "大事なのは、自分の選択肢に責任をとること――"
1013003-101 = "でも、抱えきれそうにないその時は、いつでも連絡して……ですか？"
1013003-102 = "あははっ、なんですかそれ……。#n結局、何も解決してないじゃないですか。"
1013003-103 = "[s] \"でも、生きるってその繰り返しだから。\""
1013003-104 = "……そうなんですか？"
1013003-105 = "[s] \"うん。\""
1013003-106 = "思ったよりもずっと……めちゃくちゃなんですね。"
1013003-107 = "[s7] \"そうだね、でも……。\"\n[s8] \"みんなそうやって、今を精一杯生きてるみたい。\""
1013003-11 = "ちょっと、大げさですよ先生。#n私、そういうの苦手で……。"
1013003-110 = "……。"
1013003-111 = "そうなんだ。"
1013003-112 = "[s9] \"そうそう。\"\n[s10] \"あと、口がうまい人には騙されないように！\""
1013003-115 = "なっ。それ、先生が言うんですか！？"
1013003-116 = "本当、先生って変な人です。"
1013003-12 = "特別扱いされすぎても、なんだか辛いというか……。"
1013003-120 = "うん……。"
1013003-121 = "本当に。"
1013003-122 = "変な人……。"
1013003-123 = "……ふふ。"
1013003-124 = "[s] \"スバル。\""
1013003-125 = "？"
1013003-126 = "[s] \"大変だったね。\""
1013003-127 = "……え？"
1013003-128 = "……あれ。"
1013003-13 = "……あっ、冷たくされてもそれなりに傷つきますけど。"
1013003-130 = "ちょ、ちょっとあっちを向いててください！"
1013003-131 = "えっ？ティッシュはテーブルにある……？"
1013003-132 = "もう、先生……一言余計です！"
1013003-14 = "[s] \"難しいね……。\""
1013003-15 = "あははっ。私たちくらいの年頃の生徒は、#nこの世で一番難しい生き物らしいですよ？"
1013003-16 = "それでは先生。初めての当番ですが、ご指導よろしくお願いします。"
1013003-31 = "ふぅ……。 "
1013003-32 = "[s1] \"少し休む？\"\n[s2] \"はい、コーヒー。\""
1013003-35 = "あっ。ありがとうございます、先生。"
1013003-36 = "コーヒー……ふふ。"
1013003-37 = "知ってますか？先生。#nアリウスでもコーヒーやお茶「のようなもの」がよく飲まれていたんです。"
1013003-38 = "[s] \"そうなんだ？\""
1013003-39 = "はい。野生種のレタスやタンポポ、枯れたカブの根っこ、#nアザミ、ニガナの葉、余った食材の野菜たち……。"
1013003-4 = "こんにちは、せんせ……ん？"
1013003-40 = "そういったものをローストしてすりつぶすと……。#nコーヒーの色をした何かができました。"
1013003-41 = "成績優秀者が温かい水をもらえる「ウォータータイム」のときに、それを飲むんです。"
1013003-42 = "もちろん、バレたら贅沢をするなと怒られるので……こっそりと。"
1013003-43 = "[s3] \"……他に飲みたいものはない？食べ物でもいいよ！\"\n[s4] \"なんでも買ってあげる！好きなだけ言って！\""
1013003-46 = "さっきも言いましたけど、大げさですってば！"
1013003-48 = "（慌てて食べ物や飲み物を持ってくると……）"
1013003-49 = "（スバルは黙々と、とてもおいしそうに食べていた）"
1013003-51 = "あの……先生？"
1013003-52 = "[s] \"うん？\""
1013003-53 = "この前、相談に乗ってくださるといってましたよね？"
1013003-54 = "[s] \"ええ！なんなりと！！\""
1013003-55 = "だから、それやめてくださいってば！"
1013003-56 = "……。"
1013003-57 = "外の世界は……知らないことばかりで。"
1013003-58 = "当たり前なんでしょうけど。"
1013003-59 = "でも、そのせいか……。"
1013003-60 = "最近なんというか、心が……。"
1013003-61 = "ふわふわ？ソワソワ……？なんだか落ち着かなくて……。#nいろいろなものが、混ぜこぜになっているような……。"
1013003-62 = "そうですね……。"
1013003-63 = "……。"
1013003-64 = "やっぱり、どこか許せないものがあるのでしょう。"
1013003-65 = "トリニティにも、アリウスにも……。"
1013003-66 = "もちろん、自分にも。"
1013003-70 = "とても不思議な気持ちになるんです。"
1013003-71 = "今も心のどこかで、トリニティが痛い目に遭えばいいと思っている私がいます。"
1013003-72 = "でも、アリウスがいつかトリニティに勝つ日まで――"
1013003-73 = "何も起こらず、孤高で在って欲しいとも思います。"
1013003-74 = "トリニティという学園だけでなく、トリニティ生一人一人も、ですね。"
1013003-75 = "私は……自分も含めたアリウスのみんなで、トリニティよりも良い暮らしをするのが目標の一つです。"
1013003-76 = "……でも、過激なことをしてまで、それを達成したいわけではありません。"
1013003-77 = "……えっ？それは、いい意味での「ライバル意識」……？"
1013003-78 = "……。"
1013003-79 = "なんかちょっと今、腹が立ちました……。"
1013003-80 = "いや、先生の言葉は正しいと思いますよ。#nだからこそ、ですね。"
1013003-81 = "はぁ……。"
1013003-82 = "[s] \"年頃の生徒は難しいね……。\""
1013003-83 = "いまさら後悔しているんですか？相談に乗るなんて言ってしまって。"
1013003-84 = "……むしろ素直に言ってくれて嬉しい？いつも後輩たちの前では笑顔だから？"
1013003-85 = "……！"
1013003-86 = "先生って悪い人ですね……。"
1013003-87 = "[s] \"そう、悪いのは先生！\""
1013003-88 = "ほんと、ひどい……。"
1013003-89 = "[ns] \"そう、ひどいのは先生だからね。\""
1013003-9 = "なっ、なんですかこれ！？"
1013003-91 = "[ns] \"あと、複雑な気持ちになるのは、普通のことだよ。\""
1013003-92 = "……？"
1013003-93 = "いろんな感情を同時に抱くのは――"
1013003-94 = "いたって普通のこと……なんでしょうか？"
1013003-95 = "……では、いったい何が正しいのでしょう。"
1013003-96 = "[s5] \"スバルが良いと思ったこと？\"\n[s6] \"スバルが正しいと思ったこと？\""
1013003-99 = "選ばなかった方は、あとでゆっくり考えればいい……？"
