[translation]
1013305-1 = "思考実験"
1013305-101 = "先生！？これはつまり……！"
1013305-102 = "あ、いえ、これは実験……だったわね。"
1013305-106 = "ん……？"
1013305-107 = "……。"
1013305-108 = "……残念。これが先生の本音だったらよかったのに。"
1013305-109 = "どういう意味か、って？"
1013305-110 = "……。"
1013305-111 = "そ、そんなこと言わせないでちょうだい。"
1013305-112 = "[s] \"ご、ごめん、怒らないで……。\""
1013305-113 = "別に……怒っているわけではないわ……。"
1013305-114 = "……ごめんなさい、続きをしましょう。"
1013305-116 = "（その後も「実験」は続いた）"
1013305-123 = "ふふ、そうね。私もそう思うわ。"
1013305-127 = "なるほど……先生はそういうタイプだったのね。"
1013305-132 = "さすがにこれは……少し大胆じゃないかしら。"
1013305-136 = "先生が望むのなら……私は別に、構わないけれど……。"
1013305-138 = "（10回くらいのやりとりをした）"
1013305-14 = "[ns] \"お、動いた！\""
1013305-144 = "（その都度リオは色んな反応を見せてくれた）"
1013305-146 = "先生、お疲れ様。"
1013305-147 = "どんな質問と答えだったのか、って？"
1013305-148 = "……。"
1013305-149 = "…………。"
1013305-155 = "………………。"
1013305-156 = "黙秘させてもらうわ。"
1013305-157 = "[s5] \"なんで！？\"\n[s6] \"私も当事者なのに！？\""
1013305-16 = "まだ終わりじゃないわ。"
1013305-160 = "それはそうなのだけれど……。"
1013305-161 = "……。"
1013305-162 = "願いは心の内に秘めておくものよ。#n先生がカードで答えてくれたことが現実になるまで――"
1013305-163 = "できるだけ、全部秘密にしておきたいの。"
1013305-17 = "追加したデータを正しく認識しているかの検証が必要よ。"
1013305-18 = "決められた命令だけをこなす[ruby=弱い人工知能]WeakAI[/ruby]の限界というものね。"
1013305-19 = "[s] \"[ruby=弱い人工知能]WeakAI[/ruby]？\""
1013305-2 = "（リオのいる格納庫へ向かった）"
1013305-20 = "決まったルールで、決まった作業しかできないAIのことよ。"
1013305-21 = "分野に特化しているからこそ、その範囲内なら人間より優秀なこともあるわ。"
1013305-22 = "けれど……結局は学習したデータの中だけで動くから、人間みたいな「ひらめき」は発生しない。"
1013305-23 = "逆に、人間みたいに自由な思考ができるAIもあるの。"
1013305-24 = "それを[ruby=強い人工知能]StrongAI[/ruby]と言うわ。#nその代表例ともいえるのが――"
1013305-25 = "――アリスよ。"
1013305-26 = "……私も以前は、AIに自我なんてないと思っていたの。"
1013305-27 = "ただ知能を真似しているだけだと考えていたわ。"
1013305-28 = "[s1] \"知能を真似してる……？\"\n[s2] \"それってどういうこと？\""
1013305-31 = "たとえば……全く知らない言語の「質問」と「答え」が示されている部屋があるとしましょう。"
1013305-32 = "その部屋に入れば、まるで「絵」を鑑賞するかのように、「この[ruby=質問]絵[/ruby]にはこういう[ruby=答え]絵[/ruby]を返す」というパターンが分かるようになっているの。"
1013305-33 = "ではこの部屋の中にいる人に、質問が書かれた紙を渡したらどうなるかしら？"
1013305-34 = "紙に書いてある[ruby=質問]絵[/ruby]を見て、部屋の中からそれに合う[ruby=答え]絵[/ruby]を探し出して回答すれば――"
1013305-35 = "部屋の中にいる人が言語を理解していなくとも「会話」が成立してしまう。"
1013305-36 = "部屋の外から質問の受け渡しをしている人からすれば、「部屋の中の人はこの言語が分かる」と思うはず。"
1013305-37 = "けれど実際は、ただ絵合わせをしているだけ。"
1013305-38 = "つまりルールに従って答えているだけで、言語を理解してるわけではないのよ。"
1013305-39 = "この話を拡大して――"
1013305-40 = "[ruby=強い人工知能]StrongAI[/ruby]もこの原理で動いているだけだとしたら？"
1013305-41 = "それに自我があると言い切れるかしら。"
1013305-42 = "[s] \"難しい質問だね……。\""
1013305-43 = "私はずっと……AIには自我がないと思っていたの。"
1013305-44 = "ただ人間を真似しているだけだとね。"
1013305-45 = "それが一番合理的だと信じていたわ。"
1013305-49 = "……アリスに会うまでは。"
1013305-50 = "どうしてアリスみたいな子が生まれたのか、私は未だに理解できていないわ。"
1013305-51 = "だから……正直、怖がっていたのだと思う。"
1013305-52 = "未知の領域に対する恐れとも言えるわね。"
1013305-53 = "でも結局、それも受け入れたらよかっただけのこと。"
1013305-54 = "人間だって個性がバラバラなのだもの。#nアリスもそういう「個性」だと思えばよかったのよ。"
1013305-55 = "論理的に考えるのも大事だけれど、全て論理に従って生きる必要もない。"
1013305-56 = "現実は思考実験ではないのだから。"
1013305-57 = "[s] \"リオ、成長したね！\""
1013305-58 = "……まだスタートラインに立ったばかりよ。"
1013305-59 = "だから……これからもよろしくお願いするわ。"
1013305-6 = "来たのね。"
1013305-60 = "私はもっと成長するつもりだから。"
1013305-61 = "差し当たっては家事手伝いアバンギャルド君の量産計画を進めなければいけないわね。"
1013305-62 = "[s] \"お、応援してるね……。\""
1013305-64 = "（引き続きリオと意見を交わしながら、AMASのアップデートを続けた）"
1013305-68 = "（しばらくして……）"
1013305-7 = "今はAMASのAIアルゴリズムをアップデートしているところよ。"
1013305-73 = "これで予定していた作業は終わりよ。"
1013305-74 = "思ったよりも早く終わったわね。#nこれは先生のおかげよ。感謝するわ。"
1013305-75 = "[s] \"私はただ話し相手になっただけだよ？\""
1013305-76 = "それだけでも効率が上がった気がするわ。"
1013305-77 = "おかげで少しだけ時間が余ったのだけれど……。"
1013305-78 = "もしよければさっき話した思考実験に付き合ってもらえないかしら。"
1013305-79 = "理論の是非は置いておくとしても、やってみると案外楽しいのよ。"
1013305-8 = "ここで仕入れた情報は、未知のものばかりだから。"
1013305-80 = "本物の部屋を用意するのは難しいから、カードと解答集で代用するわ。"
1013305-81 = "こんなこともあろうかと、準備はしておいたの。"
1013305-82 = "[s3] （たぶん、前からやりたかったんだろうな……）\n[s4] \"うん、一緒にやろう！\""
1013305-88 = "では……はい。#nこれが、色々な文字のようなものが書かれたカード。"
1013305-89 = "先生はこの答えの表を見て、合いそうなカードを選んでちょうだい。"
1013305-9 = "こうして新しいデータを更新しなければ、うまく処理ができなくなってしまうの。"
1013305-90 = "始めるわね。"
1013305-95 = "（よく分からない記号や絵が書かれたカードを何枚か渡された）"
1013305-96 = "（さらに、何が書いてあるか分からない解答表と質問カードも受け取る）"
1013305-97 = "（初めて見る文字だったけれど、解答表を見て一番合いそうなのを選んでみた）"
1013305-98 = "（正直、何が正解かは分からなかった……）"
