[translation]
1013103-1 = "アイスホッケー"
1013103-100 = "なあ、今回どれだけ逃げ隠れてりゃ済むと思う？"
1013103-101 = "私は2日と見る"
1013103-102 = "私は3日"
1013103-103 = "賭けるか？"
1013103-104 = "いいね"
1013103-105 = "お前ら、まだマイク切れてないぞ！！！"
1013103-106 = "ピーーーーー"
1013103-111 = "……。"
1013103-112 = "[s] \"……。\""
1013103-113 = "あの、先生？"
1013103-114 = "今日はさすがに……いろいろと危なそうですから……。"
1013103-115 = "少し落ち着くまで、私と一緒にアイスホッケーの名試合集でも、ご覧になりませんか……？"
1013103-117 = "（こうしてタカネと共に、アイスホッケーの名試合集を視聴した……）"
1013103-12 = "[ns] \"えっ……？なんか、すごい設備だね？\""
1013103-13 = "先生がお越しになるのですから。このくらいは当然用意いたしますわ。"
1013103-14 = "[s1] \"気持ちはありがたいけど……。\"\n[s2] \"出版部って、こんな施設まであるの？\""
1013103-17 = "あっ、それはですね……。"
1013103-18 = "その……出版部は名目上こそ出版部ですが……。"
1013103-19 = "これもひとえに部長が少々……お金を好きすぎた結果、といいますか。"
1013103-2 = "ようこそいらっしゃいました、先生！"
1013103-20 = "レッドウィンターのあらゆる文化事業に、かなり積極的に……#nいえ、ほとんどをまとめておりまして。"
1013103-21 = "ですから……はい……。"
1013103-22 = "[s] \"……事務局から何か言われないの？\""
1013103-23 = "レ、レッドウィンターにはレッドウィンターの流儀があるのですわ。#n出版部にも出版部の手順がございますから！"
1013103-24 = "それに、私たちは決して個人的に不当な利益を得たりはしておりません！"
1013103-25 = "そ、それよりも先生！#nホッケーです、アイスホッケーですわ！"
1013103-26 = "先日お伝えした通り、もうすぐ準決勝戦が始まりますの！"
1013103-27 = "レッドウィンターは学園の特性上、ウィンタースポーツが盛んでして……。"
1013103-28 = "アイスホッケーもまた、熱心なファンを抱えているのですわ！"
1013103-3 = "[s] \"お邪魔しま～す！\""
1013103-32 = "大変長らくお待たせいたしました！#nこれよりアイスホッケーリーグ準決勝戦を開始いたします！"
1013103-33 = "始まりましたわね、先生！"
1013103-34 = "既にご存知かもしれませんが、アイスホッケーは１チーム6人構成なのですわ。意外と少ないでしょう？"
1013103-35 = "試合は20分を3回行って、合計60分。#nその20分ずつを「ピリオド」と呼びます。"
1013103-36 = "ルールは至ってシンプルです。スティックでパックを打って、ゴールに入れるだけです。"
1013103-37 = "あ、ちなみにアイスホッケーではゴールキーパーではなく、「ゴールテンダー」と呼ぶのが通例ですわ。"
1013103-38 = "強烈なボディチェック！これは見事！積極的なディフェンスです！"
1013103-39 = "[s] \"今、体当たりで相手を……倒したけど！？\""
1013103-4 = "それでは早速、上映室へ行きましょうか。"
1013103-40 = "ええ、あの程度はレッドウィンターのアイスホッケーでは許容範囲ですわ。"
1013103-41 = "それより、そこの吹っ飛ばされたあなた！早く立ち上がりなさいな！試合の遅延行為はペナルティ対象ですわよ！"
1013103-42 = "[s3] \"乱暴な体当たりはセーフで……。\"\n[s4] \"倒れてる方がファウルって……。\""
1013103-45 = "そう！それがレッドウィンターのアイスホッケーなのです！"
1013103-46 = "[s] \"あ、今スティックで人を殴ったよね。\""
1013103-47 = "いけませんわ！あれは5分退場ものですわよ！"
1013103-48 = "な、何ですって？！審判、一体なにを！？2分で済ませるだなんて！#n審判が袖の下でも受け取っているのではなくて！？"
1013103-49 = "[s5] \"さっきの体当たりの報復かな？\"\n[s6] \"今、体当たり3連続コンボで選手が完全に吹っ飛んだけど……。\"\n[s7] \"観客席のガラスにヒビ入ったけど……これもレッドウィンターのホッケーなの！？\""
1013103-5 = "え？ここで観るんじゃないのかって？#nいえ、ここはあくまで作業場ですわ。"
1013103-53 = "あぁ……少しやり過ぎましたわね。ガラスにヒビが入ってしまえば、それを交換するまで試合は中断されますわ。"
1013103-54 = "それにあんな連続で、しかも故意の激しいボディチェックをすれば、間違いなく非紳士的行為として最低でも10分の退場ペナルティは――"
1013103-55 = "試合再開の合図です！今日の審判は、驚くほど寛大ですね！"
1013103-56 = "審判！？明日の朝日を、もう見たくはないのですか！？！？"
1013103-57 = "[s] \"あ。ケンカ始まった。\""
1013103-58 = "当然ですわ！こういうのは一度、仕切り直すべきですもの！"
1013103-59 = "そもそもアイスホッケーで乱闘が起きない方が不思議なくらいですわ。"
1013103-6 = "何より、こちらには映像を流す設備がありませんし。"
1013103-60 = "ホームチームが大きく負けている時、ファンサービスの一環でわざと乱闘を誘発することすらあるくらいですから。"
1013103-61 = "どうしようもない試合展開になったとき、せめてチケット代を惜しむ観客に見せ場を作るためですわ。"
1013103-62 = "そもそもアイスホッケーの防具は重装甲ですし――"
1013103-63 = "スティックを置いて素手でやり合うのが暗黙のルールですから、#n意外と大ごとには――"
1013103-69 = "[ns8] \"今、観客がリンクに乱入してるような……。\"\n[ns9] \"場外でチームの旗を燃やしてる……。\""
1013103-7 = "さあ！こちらへどうぞ！"
1013103-72 = "……あら。"
1013103-73 = "……ちょっと騒ぎが大きくなりましたわね。"
1013103-74 = "これもよくあることかって？"
1013103-75 = "……。"
1013103-76 = "そうですわね……頻度は高くありませんが。"
1013103-77 = "なかなか見られない光景というわけでも……ないですわね……？"
1013103-81 = "……よって我々は、事務局を糾弾する！"
1013103-82 = "糾弾だ！糾弾だ！"
1013103-83 = "今日も変わらず寒いのも！週3日労働が定着しないのも！プリンの配給がいつも一つだけで、水で薄めたプリンなことも！"
1013103-84 = "アイスホッケーでこんな負け方をしたのも！全部、事務局のせいだ！"
1013103-85 = "そうだ！そうだ！"
1013103-86 = "同志たちよ！事務局へ向かおう！"
1013103-87 = "行こう！行こう！"
1013103-90 = "[ns10] \"これって……まさか……。\"\n[ns11] \"レッドウィンターの……朝の挨拶！？\""
1013103-93 = "そ、そんな表現、一体どこでお聞きになったのです！？"
1013103-94 = "……こう申し上げるのもなんですが、レッドウィンターの生徒として……少し耳が痛いですわね。"
1013103-95 = "あ、あー、マイクテスト、マイクテスト"
1013103-96 = "皆さん、こんにちは。レッドウィンターの生徒諸君、ただいまアイスホッケーメイン競技場より、クーデターが発生したことをお知らせします"
1013103-97 = "我々事務局は、この事態に全力で対処することを約束し、この時間をもって局所的な戒厳令を発令し、秩序維持に万全を期す所存です"
1013103-98 = "生徒の皆さんは動揺せず、各自学業と労働に専念してくださいますようお願い申し上げます"
1013103-99 = "重ねて申し上げます。レッドウィンターは安全です。レッドウィンターは安全です"
