[translation]
1013502-1 = "ストレス解消 "
1013502-3 = "……。"
1013502-4 = "[s] \"……。\""
1013502-5 = "……何ですか、こっちをじろじろ見て。"
1013502-6 = "私の顔に何か？#nいえ、そんなはずありません。鏡は見てきましたので。"
1013502-7 = "[s] \"いや、なんというか……。\""
1013502-8 = "？"
1013502-9 = "[s] \"うまくいったんだなって、思って。\""
1013502-10 = "……そう、ですね。"
1013502-11 = "[s] \"あと……やっぱりケイちゃんは可愛いなぁ……って。\""
1013502-12 = "なんでそういう話になるんですか！？"
1013502-13 = "[s] \"もしかして前の体の方がよかった？\""
1013502-14 = "そんなことはありません！"
1013502-15 = "えっ？じゃあ可愛いのは嫌なのか、って……？"
1013502-16 = "……。"
1013502-17 = "…………。"
1013502-18 = "………………。"
1013502-19 = "嫌なわけじゃ……ないです。"
1013502-20 = "[s] \"好きではないの？\""
1013502-21 = "そ、れは……。"
1013502-22 = "……。"
1013502-23 = "……です。"
1013502-24 = "好き、ですよ……！強いて言えば、ですけどね！"
1013502-25 = "[s] \"ふふっ。\""
1013502-26 = "なんです……？"
1013502-27 = "[s] \"素直じゃないんだから。\""
1013502-28 = "も～～っ！！！！！"
1013502-30 = "この体、前線での活動を想定して作られているようではあるのですが……。"
1013502-31 = "その割にはガチガチなんですよね。"
1013502-32 = "え？関節にWE-40を使えばいいんじゃないかって……？#nなんてこと言うんですか！"
1013502-33 = "それは潤滑油というか、洗浄用に使うものです！#n本来の使い方とは違いますから！！"
1013502-34 = "それに、ガチガチというのは例えですってば！"
1013502-35 = "[s] \"ごめんごめん……。\""
1013502-36 = "……とは言いつつ。"
1013502-37 = "落ちていたのを拾って使っているようなものですから。#nちゃんと動くだけで感謝すべきではあるんですよね。"
1013502-38 = "いえ、別に腹が立つとかそういうのではありません。"
1013502-39 = "どちらかと言えば感謝すべき状況といいますか。"
1013502-40 = "生きていくうえで、すべて満足いくことなんてそうないですし。#n半分でも与えられればマシな方じゃないですか？"
1013502-41 = "だから、まだ燃やせるものがあるのなら、最後まで燃やし切るべきだと思っています。"
1013502-42 = "その炎が、まだ見ぬ何かに届くまで。"
1013502-43 = "なんにせよ、本来この体は処分される運命だったようですし。"
1013502-44 = "……自分で言っておいてなんですが、憂鬱になってきました。"
1013502-45 = "[s] \"やっぱり前の体のほうがいい……？\""
1013502-46 = "それは！死んでも！！あり得ません！！！"
1013502-47 = "まったく……冗談の1つも言えないんですから。"
1013502-48 = "それに、この体は見た目よりもずっと繊細に作られています。"
1013502-49 = "傍から見れば感じ方も違うのでしょうけど……。"
1013502-50 = "だから、何というかその……。"
1013502-51 = "[s] \"みんなケイのことを大事に思ってるよ？\""
1013502-52 = "そ、それは知ってます！#n私が言いたいのはそういうことではなくて！"
1013502-53 = "だから、その……。"
1013502-54 = "リボン、とか……。"
1013502-55 = "……髪を結べるようなのがあればな、と。"
1013502-56 = "[s] \"リボン？\""
1013502-57 = "……！！"
1013502-58 = "やっぱりなんでもないです！聞かなかったことにしてください。#nいいえ、先生は何も聞いていません！"
1013502-59 = "なっ、何ですかそのニヤニヤ顔！本当に怒りますよ！？"
1013502-60 = "えっ？リオにお願いしてみる……？"
1013502-61 = "なぜ、リオに……。"
1013502-62 = "……。"
1013502-63 = "……！！"
1013502-64 = "わざとですよね！？"
1013502-65 = "[s1] \"まさか！リオなら色々と詳しいし……。\"\n[s2] \"これは純粋にケイちゃんを思ってのことで！\""
1013502-70 = "そういうところですよ！！！"
