[translation]
1013205-1 = "今度は私の番、です……！"
1013205-2 = "レストラン"
1013205-3 = "（13時に、デパートの高級レストランで待ち合わせをした）"
1013205-4 = "こ、こんにちは、先生！"
1013205-5 = "お腹……空いてます、よね？"
1013205-6 = "す、空いてないと、ダメです……！"
1013205-7 = "[s] \"ダメなの！？\""
1013205-8 = "お世話になって、ばかりでしたから……。"
1013205-9 = "今度は私が、ご馳走しようと、思いまして……。"
1013205-10 = "なので、今日はこうして……来ていただき、ました！"
1013205-11 = "[s] \"このお店、高そうだけど……。\""
1013205-12 = "えへへ……。"
1013205-13 = "任せてください……アルバイト代が、入ったので！"
1013205-14 = "それに、ランチはバイキング形式で……お手頃、なんです！"
1013205-15 = "口コミを書けば、割引してもらえますし……クーポンも、合わせれば……！"
1013205-19 = "……ご、ごめんなさい。#n先生みたいに格好良く、ご馳走できたら、良かったのですが……。"
1013205-20 = "[s] \"ううん、クーポンは私もよく使うよ！\""
1013205-21 = "ほ、本当ですか……？"
1013205-22 = "で、では……！"
1013205-23 = "まず、飲み物を……。"
1013205-29 = "あっ……すみません……。"
1013205-34 = "も、もしもし……。"
1013205-41 = "はい、はい……その、ごめんなさい。"
1013205-42 = "代表モデル……？"
1013205-43 = "い、いえ……ですが、今回は……。"
1013205-44 = "はい、失礼します……。"
1013205-48 = "[ns] \"今の電話は？\""
1013205-49 = "あ、この前の社長さん、です。"
1013205-50 = "フィッティングモデルのお話を、頂いたのですが……。"
1013205-51 = "……お断り、しました。"
1013205-52 = "えっと……飲み物を取りに行くところ、でしたね。"
1013205-53 = "行きましょう、先生。"
1013205-55 = "（ツクヨと楽しく食事をしてから……）"
1013205-56 = "（散歩を兼ねて、デパートを歩くことにした）"
1013205-58 = "デパート地下のショッピングモール"
1013205-60 = "先生、お口に合いましたか……？"
1013205-61 = "[s1] \"最高だったよ！\"\n[s2] \"どの料理も美味しかったね！\""
1013205-64 = "えへへ……気に入っていただけたなら嬉しい、です……！"
1013205-65 = "次は……デザートもどう、ですか？"
1013205-66 = "先日、自家製アイスクリームのお店がオープン、したんです。"
1013205-67 = "乳脂肪たっぷりで究極の味を追求している有名店、だそうで……！"
1013205-68 = "[s] \"なるほど……それは気になるね！\""
1013205-69 = "実際、すごく美味しいと、評判で――"
1013205-71 = "……もうヤダ。"
1013205-75 = "……？"
1013205-78 = "こんな身長じゃ、可愛い洋服が全然着られない……。"
1013205-79 = "このサイズだと、靴も全然ないし……。"
1013205-80 = "さ、探せば見つかるよ！"
1013205-81 = "でも……。"
1013205-82 = "この身体じゃ、どうせ似合わないもん。"
1013205-83 = "どのマネキンも……私よりずっと背が低いじゃん。"
1013205-84 = "け、けど……。"
1013205-88 = "あの、先生……。"
1013205-89 = "……電話をしてきても、良い、でしょうか？"
1013205-90 = "[s] \"もちろん。\""
1013205-91 = "ありがとう、ございます……。"
1013205-96 = "……はい、ツクヨです。"
1013205-97 = "フィッティングモデルの件、まだ、間に合いますか……？#nはい……よろしくお願いします！"
1013205-101 = "[ns] \"ツクヨ……？\""
1013205-102 = "……先ほどのオファー、受けることにしました。"
1013205-103 = "大きいだけの私、でも……。"
1013205-104 = "……誰かに、勇気を与えられるかもしれないと、思ったんです。"
1013205-105 = "体の大きさなんて気にせずに、ファッションを楽しんで、もらいたくて……。"
1013205-106 = "すみません……その、そこまでの影響があるかは、分かりませんが……。"
1013205-107 = "[s3] \"そんなことないよ！\"\n[s4] \"ツクヨはキヴォトスで、一番のモデルだよ！\""
1013205-110 = "ふええぇ……！"
1013205-111 = "それで、その……ごめんなさい。"
1013205-112 = "アイスクリームは、また今度に……！"
1013205-116 = "（数日後）"
1013205-118 = "デパート地下のショッピングモール"
1013205-121 = "（わ、私の写真が、洋服屋さんの広告、に……！）"
1013205-122 = "（うぅぅ……覚悟はしていましたが、やっぱり、恥ずかしい……！）"
1013205-123 = "（これを見てくれる人、は……）"
1013205-128 = "あっ、ポスター変わってる。"
1013205-134 = "んー？"
1013205-135 = "今回のモデルさん、身長高いね。"
1013205-136 = "……本当だ。"
1013205-137 = "やっぱり身長が高くても、似合う服はいっぱいあるよ。"
1013205-141 = "……うん、そうかも。"
1013205-145 = "……えへへ。"
