[translation]
1013506-1 = "Out Of Control "
1013506-10 = "ここは衝突値の設定で、ここは――"
1013506-100 = "なぜ段階ごとにログを残しているのか、そろそろ理解してほしいです。"
1013506-101 = "ミドリだってそう。何でも「できる」と言っちゃダメなんです！！"
1013506-102 = "今は自分を削ってなんとかできているかもしれませんが、明日もそうとは限りません！"
1013506-103 = "「少しの無理」が前提の開発なんてありえません！そんなのブラックです！"
1013506-104 = "[s] \"ケイがいてくれてよかったよ……。\""
1013506-105 = "私だけ損してる気分なんですよっ！"
1013506-106 = "でもまあ……。"
1013506-107 = "まあ……。"
1013506-108 = "……。"
1013506-109 = "完成した時は、みんな嬉しそうなんですよね。"
1013506-11 = "[s] \"ケイちゃん……？\""
1013506-116 = "ふふっ。"
1013506-117 = "[s] \"あぁっ……。\""
1013506-118 = "今度は何ですか？"
1013506-119 = "[s] \"今の、撮っておけばよかった。\""
1013506-12 = "あっ、先生。いらしたんですね。"
1013506-120 = "そんなことしたらただじゃおかないですからね。"
1013506-122 = "（そうしてケイとゲーム開発部の新作を楽しん――）"
1013506-123 = "（QAに勤しんだ）"
1013506-124 = "（ところどころ記憶が抜け落ちてる気がした）"
1013506-13 = "何をしてるのかって……？#nそれはご覧の通り……。"
1013506-14 = "……。"
1013506-15 = "百聞は一見に如かずです。とりあえずやってみましょうか。"
1013506-16 = "はい、どうぞ！"
1013506-18 = "（ケイが爽やかな笑顔でコントローラーを渡してきた）"
1013506-19 = "（そして……）"
1013506-2 = "（ケイに呼ばれるがまま、ゲーム開発部の部室へ向かった）"
1013506-25 = "……先生？"
1013506-29 = "[ns] \"あ……うん？\""
1013506-30 = "その……大丈夫ですか？"
1013506-31 = "いま意識が飛びそうになってましたよね？"
1013506-32 = "まあ、どうしようもないクソゲーですからね、これ……。"
1013506-33 = "ああ、このゲームですか？"
1013506-34 = "……。"
1013506-35 = "ゲーム開発部の新作……のアルファ版です……。"
1013506-36 = "[s] \"あっ……。\""
1013506-37 = "なんでそんな全てを悟ったような顔をするんですか、もう。"
1013506-38 = "……気持ちは分かりますけど。"
1013506-39 = "[s1] \"ケイちゃん……どうしてこんな苦行を……？\"\n[s2] \"もしかして……人生に飽きちゃった……？\""
1013506-42 = "失礼ですね！QAをしていたんです！"
1013506-43 = "[s3] \"QA？\"\n[s4] \"ああ、なるほど……。\""
1013506-44 = "Quality Assuranceの略で……要はデバッカー兼テスターみたいなものです。"
1013506-45 = "必須な割には……後回しにされがちな仕事ですが。"
1013506-46 = "デバッグもテストも、誰かがやらなければいけません。"
1013506-47 = "他にも手をつけるところは山のようにあるんですけどね。"
1013506-48 = "にしても、バグフィックスのリストがこんなに……はぁ。"
1013506-49 = "いったいどこが問題だったのでしょう……#nアーキテクチャの時点から既にと思えるくらいですが……。"
1013506-50 = "いえ、さすがに違うはず……#nあれを変えるなら、ゲームを1から作り直さなければいけないですし……。"
1013506-51 = "なんとか別の方法を探さなければ……。"
1013506-52 = "[s] \"大変そうだね。\""
1013506-53 = "そうでもないですよ。この作業はまだマシな方です。"
1013506-54 = "……企画案やリソースの段階にまで遡り始めたら、私のロジックは成り立たなくなりますから。"
1013506-55 = "[s] \"そんなこともやるんだ？\""
1013506-56 = "そうですね……。"
1013506-57 = "まあ、なりゆきと言いますか。"
1013506-58 = "見ていたら、居ても立っても居られなくて。"
1013506-59 = "……いったい、どうしてでしょうね？"
1013506-6 = "はぁ……またここですか……。"
1013506-60 = "企画が変わるのはよくある話ですが……。"
1013506-61 = "なぜリソースを減らす方向性ではなく、やり直しになってしまうのでしょうか？"
1013506-62 = "私たちは日常系のクエストをこなしていくゲームを作ろうとしていたはず……。#nなのにどうして――"
1013506-63 = "地下の秘密基地で陸上戦艦を作り、異星人に占領された世界を救う……#nそんなスケールの話になったのですか！？"
1013506-64 = "アート担当はシナリオに口を出せず言われるがまま！"
1013506-65 = "エンジニアは形にしようと頑張るのに最適化のトラブルに巻き込まれる始末！"
1013506-66 = "そして初心者プログラマーはこんな人たちから学ぶしかない！"
1013506-67 = "助けて！Hello World！私はゲームを保存できませんでした！"
1013506-68 = "……失礼。これも全部、対応してしまう側に問題があるんです！#n何でもかんでも受け入れてしまう！だから学ばないのでしょう！？"
1013506-69 = "[s] \"大変そうだね……。\""
1013506-70 = "もっと本気で心配してください！"
1013506-71 = "[s] \"本気だったのにぃ！\""
1013506-72 = "……。"
1013506-73 = "ありがとうございます……。"
1013506-75 = "[ns] \"結局、QA兼プロデューサー兼雑用ってことなんだね。\""
1013506-76 = "この小さな部活でわざわざ肩書きをつけるとしたら、ですが。"
1013506-77 = "……というか、一応私は特異現象捜査部の所属なんですけどね。"
1013506-78 = "[s] \"でも大体ここで過ごしてるよね？\""
1013506-79 = "……。"
1013506-80 = "そうですね。"
1013506-81 = "とにかく、そういうことです。"
1013506-82 = "自分がデバッグをしているのか、はたまた得体の知れないモンスターと戦っているのか、分からなくなる時があります……。"
1013506-83 = "でもまあ、これも結局は誰かがやらなきゃいけないことなので。"
1013506-84 = "とはいえ……どのようにフィードバックを伝えたらいいか、というのがまた問題なんですよね。"
1013506-85 = "[s] \"それすごく難しいよね……分かるよ……。\""
1013506-86 = "本当ですか？"
1013506-87 = "[s5] \"一歩間違えれば「相手のやりたいこと」ではなく、\"\n[s6] \"「自分がやりたいこと」を押しつける羽目になるからね。\""
1013506-90 = "……はい、そうです。"
1013506-91 = "そうなると……こう表現するのは子供っぽいかもしれませんが――"
1013506-92 = "仲が悪くなってしまいますから。"
1013506-93 = "[s7] \"その通りだと思うよ。\"\n[s8] \"仲が悪くなると、他のことも上手くいかなくなっちゃうよね。\""
1013506-96 = "……。"
1013506-97 = "分かってくださるんですね。"
1013506-98 = "ただ幸いなことに、モモイはわりと話を聞いてくれます。"
1013506-99 = "……言ったそばから別のアイデアを提案してくるのが大変なだけで。"
