[translation]
1013306-1 = "想定外の変数"
1013306-2 = "（しばらくして、リオから連絡が来た）"
1013306-5 = "先生、いま大丈夫かしら？"
1013306-6 = "さっき連絡した件、スーツの改造が完了したわ。"
1013306-7 = "ただ、1人ではテストができないの。"
1013306-8 = "家事手伝いのアバンギャルド君もこのテストには向かないし……。"
1013306-9 = "先生、手伝ってもらえないかしら。"
1013306-10 = "[s] \"すぐ行くね！\""
1013306-11 = "ありがとう。"
1013306-12 = "私の部屋で待っているわ。"
1013306-20 = "来たわね。"
1013306-21 = "早速だけれど、これが改造したスーツよ。"
1013306-22 = "……全然変わってないように見える？"
1013306-23 = "そうね。外からだと分からないと思うわ。"
1013306-24 = "新しいパーツは使わずに、元々あった機能を応用しただけだから。"
1013306-25 = "今回改造したのは、発熱機能に関する部分よ。"
1013306-26 = "このスーツには、体内の電気信号を増幅する装置が備わっているの。#nだからそれを応用すれば、体全体に熱を伝えることもできる。"
1013306-27 = "作業自体はコードを数行書き換えるだけだったわ。"
1013306-28 = "それでも何かを変えたからにはテストを行っておく必要があるの。"
1013306-29 = "先生にはそのテストに協力してもらうわね。"
1013306-30 = "[s] \"何を手伝えばいい？\""
1013306-31 = "これからスーツの温度を上げていくわ。#n熱が全体に行き渡っているか、先生はサーモカメラで確認してちょうだい。"
1013306-32 = "[s] \"それは簡単だね！\""
1013306-33 = "もしも熱が漏れている部分があったら、直接触って確かめてもらえるかしら。"
1013306-34 = "手でスーツの表面をなぞる要領よ。"
1013306-35 = "[s] \"それは簡単じゃないね！\""
1013306-36 = "自分の手が届く範囲は自分でやるわ。#n背中側だけでも頼めないかしら。"
1013306-37 = "家事手伝いのアバンギャルド君にやってもらおうと思ったのだけれど、#nあの子には触って温度を測る機能がついていないの。"
1013306-38 = "しっかりスーツの状態を確認するために、お願いしたいのだけれど……。"
1013306-39 = "[s] \"せ、背中だけだよ……！\""
1013306-40 = "ええ、それで構わないわ。"
1013306-42 = "（サーモカメラで温度を測って、時々リオの背中に手を当ててチェックした）"
1013306-47 = "んっ、くふっ……。"
1013306-48 = "[ns] \"ご、ごめん！痛かった？\""
1013306-49 = "気にしないでちょうだい。思ったよりもくすぐったくて……。"
1013306-50 = "それより、想定よりも暑くなってきたわね。"
1013306-51 = "とりあえずその調子で続けてちょうだい。"
1013306-52 = "[s] \"う、うん……！\""
1013306-53 = "（しばらくリオの体温チェックを続けた）"
1013306-59 = "ふぅ……お疲れ様。これでテストは終わりよ。"
1013306-60 = "正常に動作していることを確認できたわ。"
1013306-61 = "……ただ、1つ予想外の変数が出てきたの。"
1013306-62 = "[s] \"どんな変数？\""
1013306-63 = "……暑すぎる。"
1013306-64 = "先生が来るからと部屋を温めておいたのが裏目に出たわね。"
1013306-65 = "これは、熱を逃がさなければ……。"
1013306-68 = "少し……失礼するわ。"
1013306-71 = "[wa:500]― [log=리오 결전]ふぅ……[wa:1570]落ち着いたわ。[/log]"
1013306-74 = "[wa:1610]― [log=리오 결전]室内温度を考慮していなかったの。[/log]"
1013306-77 = "― [log=리오 결전]私としたことが……[wa:1890]目の前の結果に、[/log]"
1013306-79 = "― [log=리오 결전]気を取られてしまったみたい……。[/log]"
1013306-82 = "[wa:930]― [log=리오 결전]……少し、[wa:1560]休ませてちょうだい。[/log]"
1013306-84 = "― [log=리오 결전]暑さで、[wa:1920]思考があまり……。[/log]"
1013306-87 = "[wa:1510]― [log=리오 결전]……先生？[wa:2440]どうしてそんな顔で……。[/log]"
1013306-90 = "[wa:2200]― [log=리오 결전]……あ！！[/log]"
1013306-92 = "― [log=리오 결전]（わ、[wa:320]私は……[wa:1370]なにを……！？）[/log]"
1013306-95 = "[wa:490]― [log=리오 결전]こ、[wa:660]これは[wa:520]わざとじゃないの……！[wa:1320]ごめんなさい……！[/log]"
1013306-97 = "― [log=리오 결전]わ、[wa:810]私はもう、[wa:1180]大丈夫だから……！[/log]"
1013306-101 = "ね、熱はちゃんと逃したわ！"
1013306-102 = "残りはスーツの冷却機能でなんとかなるから……！"
1013306-103 = "ほ、本当にもう大丈夫――"
1013306-111 = "[ns] \"まだおでこ熱いけど？\""
1013306-112 = "……！！"
1013306-117 = "[ns] \"リオ……！？\""
1013306-119 = "（その後、リオの体をうちわで冷ましてあげた）"
1013306-120 = "（幸い何事もなく、リオはすぐに回復した）"
1013306-123 = "本当に……今回の実験は予想外の変数ばかりだったわ……。"
