[translation]
1013002-1 = "みんなの先輩"
1013002-3 = "本当にいらっしゃったんですね、先生……。"
1013002-4 = "[s] \"大分復興が進んだね。\""
1013002-5 = "ええ。少しずつ、ではありますが。"
1013002-6 = "[s] \"こういうことを言っていいのか分からないけど……。\""
1013002-7 = "大丈夫ですよ。何ですか？"
1013002-8 = "[s] \"いい感じ、だね。\""
1013002-9 = "……そうですね。"
1013002-10 = "私もそう思っています。でも、まだどこか慣れないというか。"
1013002-11 = "いまは、変化の時なんですよね。"
1013002-12 = "……ん？見回りですか？"
1013002-13 = "……。"
1013002-14 = "うーん、本当に色々あったとしか……。"
1013002-15 = "他校で言うところの、風紀委員長のような役回りをすることになったんです。"
1013002-16 = "アリウスの秩序を守るという意味では、今までやっていたこととほとんど変わりません。"
1013002-17 = "外部からの攻撃を気にしなくてよくなったので、少し気は楽ですが。"
1013002-18 = "……なぜって？"
1013002-19 = "ふふ、シンプルな話です。"
1013002-20 = "わざわざ外からアリウスに来て騒ぎを起こそうとする者は、そういませんから。"
1013002-21 = "いろいろな意味で。"
1013002-27 = "[ns] \"なんか爆発音したけど！？\""
1013002-28 = "行ってみましょう。"
1013002-32 = "なんの騒ぎですか？"
1013002-37 = "あ、先輩。そんな大したことじゃないですよ。"
1013002-38 = "そうです、私たちは――"
1013002-39 = "アリウス流の「話し合い」をしていただけなので。"
1013002-41 = "ああ……なるほど。"
1013002-45 = "[ns1] \"アリウス流の……。\"\n[ns2] \"話し合い……？\""
1013002-49 = "知らないんですか？先生。"
1013002-50 = "たしかに外部の方ですもんね。"
1013002-51 = "アリウスでは「説得」の時、言葉と行動を重視するんです！"
1013002-55 = "[ns] \"言葉は分かるけど、行動も……？\""
1013002-56 = "ええ！だから私たちは……。"
1013002-57 = "意見がぶつかった時は！"
1013002-58 = "どちらの「行動」に、より「説得力」があるかを話し合うんです！"
1013002-59 = "で、時代は5.56mm弾だって認めた？"
1013002-60 = "そんなわけないでしょ！やっぱりガツンとした7.62mm弾だよ。"
1013002-61 = "はぁ？スクワッドも5.56mm使ってるけど？"
1013002-62 = "あの子たちは特別に支給されてるからでしょ？#nうちらは7.62mmでいいでしょ！"
1013002-63 = "たしかに7.62mmは強いけど、反動のせいで狙いが定まらないじゃん！"
1013002-64 = "もたもた狙う時間がもったいないよ。速射したほうがよくない？"
1013002-65 = "それはあんたみたいな奴らが言ってるだけ！"
1013002-66 = "7.62mmの反動がデカいってのはウソだよ！#n設計と消炎器がちゃんとしてれば――"
1013002-67 = "あと、シンプルに嵩張るよね？7.62mmを300発持ち歩ける？ "
1013002-68 = "照準射撃ができるかどうかも結局状況次第なんだから、持続射撃しちゃった方がいいって！"
1013002-69 = "そんな弾代、私たちにあると思う！？"
1013002-76 = "はい、お二人ともそこまで。"
1013002-78 = "先輩、でもっ！"
1013002-79 = "先輩っ！！"
1013002-81 = "二人の話はよく分かりました。#nどちらの言い分も正しい。難しい問題ですね。"
1013002-82 = "どうしてそんな話になったのか、経緯を聞いても？"
1013002-84 = "そ、それは……。"
1013002-85 = "私たちのアリウスを守るには、どの弾が向いてるかな、って……。"
1013002-87 = "そうですね、みなさんも私も学園を守りたい気持ちは同じ。#n……大切なのはその事実です。"
1013002-88 = "みんな同じ志を持っているはずなのに、考え方が違うからといって……。"
1013002-89 = "過激な「アリウス流の話し合い」をするのは、そろそろ終わりにしませんか？"
1013002-90 = "仲間割れは、身を滅ぼすだけです。"
1013002-92 = "……たしかに。"
1013002-93 = "うん……もう、昔のアリウスじゃないもんね……。"
1013002-95 = "口論になりそうなときは、そのことを思い出してくれると嬉しいです。"
1013002-96 = "それこそ、「話し合い」には弾代もかかりますから。"
1013002-98 = "ごめんなさい、先輩……。"
1013002-100 = "ふふっ。でも、学園を大事に思う二人の気持ちは嬉しいです。"
1013002-101 = "私たちはこれからも試行錯誤を繰り返していくでしょう。#nときに昔のやり方で通したくなることもあるかもしれません。"
1013002-102 = "ですが、できるだけ新しいやり方で、一緒に向き合っていきましょう。#n私も努力しますから。"
1013002-103 = "困った時にはいつでも呼んでください。"
1013002-105 = "……！#nはいっ、先輩……！"
1013002-106 = "分かりました、ありがとうございます先輩！"
1013002-111 = "ふぅ……。"
1013002-112 = "[s] \"いいこと言うね。\""
1013002-113 = "そ、そうですか？"
1013002-114 = "実は、こんな話ができるようになったのも最近で……。"
1013002-115 = "昔は全部見て見ぬふりでしたから。"
1013002-116 = "……でも、たしかに重要な話です。#n両方の弾に互換性はなく、外では5.56mmが主流。"
1013002-117 = "とはいえ、今まで使ってきた7.62mmを廃止するわけにも……。"
1013002-118 = "私の銃も、補給の兼ね合いから7.62mmにカスタムした仕様ですし。"
1013002-119 = "……。"
1013002-120 = "でも、少しほっとしています。"
1013002-121 = "正直、この役回りをすることで、みんなに嫌われると思っていました。"
1013002-122 = "なのに、みんな私についてきてくれて……本当に嬉しいです。"
1013002-123 = "[s3] \"スバルがそれだけ頼れる先輩だってことだよ。\"\n[s4] \"みんなを引っ張ってきたのはスバルだから。\""
1013002-126 = "ふふ。そんなに褒めても何もでませんよ？"
1013002-127 = "……でも、罪悪感や後ろめたさを感じることがあるんです。"
1013002-128 = "話を聞いてあげたり、寄り添ってあげることはいくらでもできるんですが……。"
1013002-129 = "……。"
1013002-130 = "結局、根本的な解決にはなっていない気がして。"
1013002-131 = "ただの気休めにしかなってないと思っているんです。"
1013002-132 = "[s5] \"分かった。\"\n[s6] \"スバルにも、相談する相手が必要なんじゃないかな。\""
1013002-135 = "え？急に一体なにを……。"
1013002-136 = "たしかに、見張りを見張る「誰か」も必要かもしれません。"
1013002-137 = "理解はできますが……でも……。"
1013002-138 = "私の話を聞いてもらうなんて……。"
1013002-139 = "[s7] \"先生はこういう時のためにいるんだからね。\"\n[s8] \"他にも仕事はあるけど……。\""
1013002-142 = "なるほど。これが噂に聞くアレですね。"
1013002-143 = "生徒たちを甘い言葉[ruby=いざな]で誘い[/ruby]、もう昔のようには戻れなくする――という。"
1013002-144 = "ええとたしか……クロノスチャンネルの特集？でそう言っていたような……。"
1013002-145 = "[s] \"い、いや……それ、ほんと誤解だから……。\""
1013002-146 = "そ、そこまで落ち込まれるとは……。"
1013002-147 = "……。"
1013002-148 = "分かりました。では今度、機会があったらお願いしますね。"
1013002-149 = "先生といると、つい色々話してしまうんですよね。"
1013002-150 = "ふふっ……これも、手口の一つなんでしょうか？"
1013002-151 = "[s] \"い、いや……それ、ほんと誤解だから……。\""
1013002-152 = "……あれ？さっきも同じことを聞いたような。"
1013002-154 = "（なんだか負けた気分になりつつ、シャーレに戻った……）"
