[translation]
1013402-1 = "勇者修行"
1013402-2 = "パンパカパーン！"
1013402-3 = "アリスは新装備を手に入れました！"
1013402-7 = "これで[ruby=勇者の武器]光の剣：スーパーノヴァ[/ruby]と[ruby=勇者のアーマー]アビ・エシュフ[/ruby]が揃ったので――"
1013402-8 = "伝説の武具を集めたアリスは、真の勇者になったのです！"
1013402-9 = "[s1] \"おお、おめでとう！\"\n[s2] \"これで最強だね！\""
1013402-13 = "いいえ、まだ違います……アリスは忘れていたのです。"
1013402-14 = "防具は……ただ装備するだけでは意味がないのだということを！"
1013402-15 = "本来の性能を引き出すためには、アリスの熟練度を上げなければいけません！"
1013402-16 = "[s3] \"アビ・エシュフは高機動兵器だもんね。\"\n[s4] \"使いこなすのは大変だよね。\""
1013402-19 = "そうなんです……。"
1013402-20 = "今のアリスは、横スクロールが3Dに変わったようなもの……。"
1013402-21 = "右も左も分からない状態では戦えません！"
1013402-22 = "つまりこの試練を乗り越えるには、勇者修行が必要です！"
1013402-23 = "アーマーの使い方はすでに賢者から教わっています！"
1013402-24 = "あとはマスターするまで修行を繰り返すのみ！"
1013402-25 = "でもこの修行はとても難しいです……#n偏ったジョイスティックでプラットフォームゲームをしているみたいです！"
1013402-26 = "なので、ここからは先生の出番です！"
1013402-27 = "[s5] \"了解！サポートは任せて！\"\n[s6] \"何をしたらいい？\""
1013402-30 = "先生は、隣でアリスを応援していてください！"
1013402-34 = "[ns7] \"……応援？\"\n[ns8] \"……それだけ？\""
1013402-37 = "はい！"
1013402-38 = "先生はマスコットなので、隣にいてくれたら元気が出ます！"
1013402-39 = "どんなに辛い修行でも……#n先生がパーティーにいれば、士気をMAXで保つことができるんです！"
1013402-40 = "……どうかしましたか？"
1013402-41 = "先生、悲しそうな子犬みたいな顔をしています。"
1013402-42 = "えっ？なんでもない、ですか？"
1013402-43 = "……？"
1013402-44 = "とにかく、勇者修行のスタートです！"
1013402-46 = "（こうしてアリスの修行が始まった……！）"
1013402-49 = "ここでこうすれば……。"
1013402-53 = "あっ、逆でした！こういう時はブースターで勢いを相殺して――"
1013402-57 = "あれっ！？こっちは側面ブースターでした！"
1013402-58 = "うわぁーん！ぐるぐる回り始めました！"
1013402-60 = "（いろんなハプニングがあったけど、大きなトラブルもなく修行は続き――）"
1013402-63 = "はぁ……はぁ……。"
1013402-64 = "ここで、もう少し右に回って……。"
1013402-68 = "（――気づけばかなりの時間が過ぎていた）"
1013402-69 = "（アリスはまだ勇者修行を続けるつもりみたいだった）"
1013402-74 = "……あうっ！"
1013402-79 = "さっきまでは上手にできていたのに……。"
1013402-80 = "なぜか何度も失敗してしまいます！"
1013402-81 = "[s9] \"少し休憩しない？\"\n[s10] \"そろそろ疲れてきたんじゃないかな。\""
1013402-84 = "いいえ！大丈夫です！"
1013402-85 = "アリスはまだ元気いっぱいです！"
1013402-86 = "それにアリス、似たようなゲームならたくさんプレイしてきました！"
1013402-91 = "見ていてください……こういう風に――っ！"
1013402-92 = "あっ！"
1013402-97 = "[ns11] \"大丈夫！？\"\n[ns12] アリスに駆け寄る。"
1013402-101 = "先生……。"
1013402-102 = "ちょっとひねっただけなので、大丈夫で――"
1013402-103 = "いたっ。"
1013402-107 = "やっぱり先生の言うことを聞くべきでしたね。"
1013402-108 = "疲労度の管理は育成シミュレーションの基本です！"
1013402-109 = "このまま修行を進めたら、ステータスダウンのイベントが発生してしまいます！"
1013402-110 = "アリスのようなベテランプレイヤーだって、たまにはこんなミスを犯してしまうものです……。"
1013402-111 = "……。"
1013402-114 = "[ns] \"……今日はもう帰ろっか。\""
1013402-117 = "先生……？"
1013402-118 = "どうして膝を地面に……？"
1013402-119 = "[s13] \"おんぶしてあげる。\"\n[s14] \"その足じゃ動けないでしょ？\""
1013402-122 = "えっ？でもこの装備なら飛んで帰れば……。"
1013402-123 = "[s15] \"いいからいいから！\"\n[s16] \"こんな時くらいはさ！\""
1013402-126 = "あっ……じゃあ……。"
1013402-130 = "えへへ。"
1013402-131 = "アリス、先生に毎日おんぶしてもらいたいです。"
1013402-132 = "（背中越しに感じるアリスの体温は少し冷たかった。#nずっと寒空の下を飛び回っていたからだろうか）"
1013402-134 = "（アリスのアーマーは想像以上に重たくて……）"
1013402-141 = "（腰を痛めてしまうかと思った）"
