[translation]
1013005-1 = "社会経験"
1013005-5 = "……。"
1013005-6 = "[s] \"……。\""
1013005-7 = "こ、こんにちは、先生。"
1013005-8 = "そ、その……これは……。"
1013005-13 = "あ、アルバイトです……。"
1013005-14 = "ち、違いますからっ！先生が思ってるようなものじゃないです……！#nみんなで話し合った結果――"
1013005-15 = "この機会に「接客」を体験して、色々な対応を覚え――"
1013005-16 = "己の限界を体で覚えつつ、経済活動をしてみよう、と……。"
1013005-17 = "[ns] \"たしかに、目的と合致してる気も。\""
1013005-19 = "そう、ですよね……？"
1013005-20 = "でも、急に外に出されてしまい……#n私には接客する資格もなかったようです。"
1013005-21 = "この看板を持って立っているように、と……#n絵になるから？よくわかりませんが。"
1013005-27 = "[ns1] \"……たしかにそうかも。\"\n[ns2] \"スバルはもっと自分に自信を持っていいと思う。\""
1013005-30 = "……店長と同じことを言いますね。"
1013005-31 = "どういう意味なのかはよく分かりませんが……。"
1013005-32 = "……なんだかんだ言って頑張ってるスバルがかっこいいよ？"
1013005-33 = "……。"
1013005-34 = "で、では！そんな私たちのためにも！#n売り上げに貢献していただけると……！"
1013005-35 = "[s3] \"ふむ。なかなか筋がいいですね、スバルさん。\"\n[s4] \"では、よろしくお願いします。\""
1013005-38 = "ありがとうございます！ご案内します！"
1013005-40 = "[ns] \"おお……思ったよりも本格的だ。\""
1013005-41 = "どうですか？先生。みんなのこんな姿は、新鮮ですよね？"
1013005-42 = "最初は悩んでいたのですが、制服を見て前向きになってくれて……。"
1013005-43 = "「可愛い」「着てみたい」、って。"
1013005-44 = "……。"
1013005-45 = "私、先輩なのに、後輩の気持ちにも気づけてなくて……情けなく思いました。"
1013005-46 = "[s5] \"そんなことないよ、知らなかっただけだから。\"\n[s6] \"気がつけたなら、大丈夫。\""
1013005-49 = "……そうですよね。"
1013005-50 = "[USERNAME]先生がおかえりになられました！"
1013005-51 = "おかえりなさいませ、ご主人様！"
1013005-53 = "[ns] \"スバルも一緒に行こう。\""
1013005-54 = "わ、私もですか！？でも、看板を持ってないと……。"
1013005-55 = "一人でも多くのお客様をご案内して、売り上げに貢献しないと……。"
1013005-57 = "（その言葉を待っていた私は、会心の笑みを浮かべ……）"
1013005-58 = "（店長に声をかけた）"
1013005-60 = "どうかされましたか？"
1013005-61 = "なるほど。こちらの方が先生の教え子で……。"
1013005-62 = "社会勉強する様子を見に来た、と。#nそれでお話がしたいと。"
1013005-63 = "その代わり、今いるお客様全員に、飲み物と……ケーキを？"
1013005-64 = "支払いは全額、先生が負担……？"
1013005-65 = "そういうことでしたら大歓迎ですとも！#nスバルさん、先生とゆっくりしてきてください！"
1013005-67 = "……いいんですか？"
1013005-68 = "[s] \"ふっ……これが大人ってものさ。\""
1013005-69 = "……勉強になります。すごく。"
1013005-71 = "（そうしてスバルと他愛のない話を交わした）"
1013005-72 = "（日常や学校でのこと、そして、後輩と向き合う中でのこと……）"
1013005-73 = "（ひとつひとつは本当に他愛ない。でも、だからこそ大事な話を）"
1013005-75 = "先生。"
1013005-76 = "[ns] \"うん？\""
1013005-77 = "アリウスのみんな、頑張ってますよね？"
1013005-78 = "[ns7] \"そうだね。\"\n[ns8] \"もちろんスバルも。\""
1013005-81 = "……。"
1013005-82 = "そういうことを言っても、何も出ませんから……。"
1013005-83 = "えっ？素直に思っただけ……？"
1013005-84 = "…………。"
1013005-85 = "私、先生のわる～いウワサ、聞いてるんですよ？"
1013005-86 = "ある日先生の身に何かあっても……全部自業自得！という話です。"
1013005-87 = "なんでその話を今するのか、って？"
1013005-88 = "知りませんっ。先生は頭のいいお方ですから、ご自分で考えてみてください。"
1013005-90 = "なんだこの店！#nサービスでケーキが出るって聞いたのにめちゃくちゃじゃねえか！"
1013005-91 = "ど、どうかされましたかお客様？"
1013005-92 = "姿勢がなってねえんだよ、姿勢が！声もかけてこないしよぉ！#nもっと周りを見たらどうなんだ！"
1013005-93 = "まあ、もう来ねえけどな！ "
1013005-94 = "も、申し訳ございません！どうかまたお越しください……。"
1013005-95 = "はんっ！もうどうでもいいよ！#n大体なんだよ、この服のひらひらは。飾りか？"
1013005-96 = "きゃあっ！？"
1013005-97 = "お、お客様！？キャストに触れるのは……！"
1013005-98 = "……！"
1013005-104 = "ぐあぁっ！なっ、なんだお前！"
1013005-106 = "申し訳ありません。#nご主人様がバランスを崩されたようでしたので――"
1013005-107 = "お支えしようと思った次第です……ご体調でも優れませんか？"
1013005-108 = "（先輩の[ruby=CQB]近接戦闘[/ruby]をこんな間近で！？ラッキー！！）"
1013005-109 = "さ、支えるってこれのどこがっ……！いてててて！#nおっ、おい腕が折れちまうだろ！はっ、離せっ……！ぐあぁ……！"
1013005-110 = "ふふっ、少々お待ちを。#nご自身で立てますか？"
1013005-111 = "……この腕、今まで通りに使いたいだろ？"
1013005-112 = "……ヒィッ！？"
1013005-113 = "私が何を言いたいのか……今のお前がどんな立場か。#n分かるな？"
1013005-114 = "わわ、分かった、分かったからっ……！だ、だからっもう……！"
1013005-115 = "失せろ。"
1013005-119 = "こ、こんな店っ、二度と来るかっ！！"
1013005-125 = "……。"
1013005-126 = "スバルさん、ありがとう！いや……ありがとうございました！#nおかげでみんな無事だったよ！"
1013005-127 = "いえ、やるべきことをやっただけですから。"
1013005-128 = "スバルさん、でしたよね？お写真いいですか……？"
1013005-129 = "別料金が必要でしたらいくらでも……！"
1013005-130 = "いっ、いえ特にそういういったものは……というか店長！？先生！？"
1013005-131 = "なんで二人とも笑顔でサムズアップしてるんですか！！？"
