[translation]
1013503-1 = "Welcome To Kivotos"
1013503-10 = "では授業を始めます。"
1013503-102 = "なんで私がっ！？"
1013503-103 = "え？勇者アリスなら、きっとそうする……？"
1013503-104 = "……。"
1013503-105 = "…………。"
1013503-106 = "………………。"
1013503-107 = "はぁ、本当に……。"
1013503-108 = "口ばっかり上手いんですから。"
1013503-109 = "分かりましたよ……。 "
1013503-11 = "今日の授業は「生活空間と社会」です。"
1013503-110 = "考えてみます。ひとまず。"
1013503-111 = "[s] \"ケイちゃんは本当に優しいね！\""
1013503-112 = "別に、やるとは言ってませんからっ！！"
1013503-12 = "その中でも外せない「都市」の話をしようと思います。"
1013503-13 = "ええと、それでは……ケイさん？"
1013503-14 = "「都市」について知っていることを教えてください。"
1013503-15 = "えっ、私ですか……？"
1013503-16 = "はい、お願いします。"
1013503-17 = "ええと……。"
1013503-18 = "都市とは……自然状態とは最もかけ離れている、文明の象徴です。"
1013503-19 = "文明を意味するCivilizationという単語には、都市――Cityの語源であるCivil、原語のCivitasが含まれています。"
1013503-2 = "（ケイの様子を観るため、ミレニアムに向かった）"
1013503-20 = "都市が存在しなければ。#nつまり、たくさんの人間が集まって生活を営む基盤が存在しなければ。"
1013503-21 = "世界は今のような形にはなれなかったはずです。"
1013503-22 = "人間は集団的思考を通じて、虚構の思想を現実に生み出してしまう生き物ですから。"
1013503-23 = "（えっ……あれっ！？）"
1013503-24 = "（た、たしかにそうだけど……）"
1013503-26 = "――その反面、都市には人が多く集まるがゆえに起こる問題も存在します。"
1013503-27 = "多様な問題が複雑に絡み合っているからこそ、解決は容易ではありません。"
1013503-28 = "それでも例を挙げるのであれば……交通手段の改善などから対処していくべきではないでしょうか。"
1013503-29 = "（今日の授業内容、全部言われちゃった……！）"
1013503-3 = "（こちらに気がついたケイは不機嫌そうな表情を見せた）"
1013503-30 = "（ど、どうしよう……私は何をしたら……）"
1013503-32 = "あの……ベクトルの話からなぜ量子場の話になってしまったのですか……？"
1013503-33 = "結局これは、質量ギャップが0よりも大きいことを数学的に証明せよという問題です。"
1013503-34 = "計算しろという話ではありません。それは簡単ですから。"
1013503-35 = "実際これは経路積分の持つ数学的構造の限界を指していて――"
1013503-36 = "こ、こほん……！"
1013503-37 = "す、少し早いですが、今日の授業はここまでで！"
1013503-43 = "すごーい！"
1013503-44 = "オーラはあったけど、やっぱ転校生めちゃくちゃすごいね！"
1013503-46 = "えっ……？"
1013503-47 = "ねえねえ、ケイちゃんって言ってたよね？#nこれまでどんな勉強してきたの？コツとかあったら教えてよ！"
1013503-48 = "さっきのって方程式と質量ギャップ問題だよね？#nうちって元々、千年難題を解くために作られた学園だもんね！"
1013503-49 = "あ……ええっとその、私は……。"
1013503-51 = "（ケイと目が合った）"
1013503-52 = "（口パクで何かを訴えてきている）"
1013503-53 = "（た・す・け・て・く・だ・さ・い！）"
1013503-55 = "（返事をすべく、こちらも口をパクパクした）"
1013503-57 = "[ns] （だ・い・に・ん・き・だ・ね！）"
1013503-59 = "（今日こそ先生を殺して私も死にます！！）"
1013503-61 = "うぅ……疲れた……。"
1013503-62 = "[s] \"ケイちゃんは物知りだね！\""
1013503-63 = "もう黙っててください！"
1013503-64 = "はぁ……。"
1013503-65 = "良い機会なので先生にはお話しますが……#nお察しの通り、私は大抵のことなら知っています。"
1013503-66 = "……「侍女」だった頃から、必要なものでしたから。"
1013503-67 = "廃墟にミレニアムサイエンススクールの研究施設ができた時なんかは、いろいろ試したりもしました。"
1013503-68 = "だから……。"
1013503-69 = "何が言いたいかといえば、その……。"
1013503-70 = "……。"
1013503-71 = "授業というのは、形式的なものに過ぎないと思っているんです。"
1013503-72 = "[s] \"授業は嫌い？\""
1013503-73 = "……。"
1013503-74 = "嫌い……それ以前に、ただ疑問なんです。"
1013503-75 = "何もかも知っている生徒は、学園に通う必要があるのか、という話です。"
1013503-76 = "[s] \"もちろんあるよ。\""
1013503-77 = "どうして？"
1013503-78 = "[s] \"みんなと遊ぶと楽しいからね。\""
1013503-79 = "……はい？"
1013503-80 = "それだけですか？"
1013503-81 = "[s1] \"もちろん。\"\n[s2] \"生徒は学んで、遊ぶのが仕事だから！\""
1013503-84 = "また適当な……。"
1013503-85 = "……。"
1013503-86 = "それに、誰かといるのが疲れるタイプの人もいるかと。"
1013503-87 = "[s3] \"そうだね。\"\n[s4] \"でもそういう人もたまには……。\"\n[s5] \"人恋しくなる時もあると思うんだ。\""
1013503-91 = "……だからそういう時のためにも、通うべきだ、と？"
1013503-92 = "……う。"
1013503-93 = "でも、すごく気難しくて人を選ぶようなタイプだったら？"
1013503-94 = "えっ？そういう時のために先生がいる……？"
1013503-95 = "……。"
1013503-96 = "言いたいことは分かりますが、先生もいい加減気づいてください。"
1013503-97 = "先生は1人です。キヴォトスに何人の生徒がいるのか分かっているんですか？"
1013503-98 = "ミレニアムの生徒だけでも難しいでしょうに、どこからそんな自信が……。"
1013503-99 = "[s6] \"それもその通り。だからケイちゃんが――\"\n[s7] \"私の代わりに友達になってくれたらいいな！\""
