[translation]
1013508-1 = "生活環境について"
1013508-3 = "あ、いらしたんですね。"
1013508-4 = "本当にここ……人の住む場所なんでしょうか。"
1013508-5 = "[s] \"手伝うよ。\""
1013508-6 = "え？"
1013508-7 = "あ……はい、ありがとうございます。まあ2人の方が早いですからね。"
1013508-12 = "はぁ……モモイは散らかしてばかりで、片づけるはずもなく。"
1013508-13 = "その点ミドリは片づけは上手で、ある程度生活力もありますが――"
1013508-14 = "そもそも掃除の頻度が少ない……。"
1013508-15 = "ユズは……隠れる癖は減りつつあっても、ゲームかコーディングばかり……。"
1013508-19 = "アリスは……アリスが、心配です。"
1013508-20 = "4人の中では2番目に生活力はありますが、結局人間は周りと似ていくもの……#nそして周りにいる人たちといえば……。"
1013508-21 = "いえ、別に悪いと言いたいわけじゃないんです。#nどちらかといえば良い人たちだとは思います。ただ私は普段から――"
1013508-30 = "ふぅ……ようやくマシになりました。"
1013508-31 = "……3日持てば御の字ですが。賭けてもいいです。"
1013508-32 = "[s] \"これで3日か……なるほど……。\""
1013508-33 = "はい。"
1013508-34 = "……。"
1013508-35 = "……？"
1013508-36 = "待ってください、先生。"
1013508-37 = "[s] \"なっ、なにかな？\""
1013508-38 = "なんか今……目をそらしましたよね？"
1013508-39 = "[s] \"ご、誤解ですよケイ様。\""
1013508-40 = "ケイ様……？"
1013508-41 = "……。"
1013508-42 = "先生。"
1013508-43 = "私の目を見てください。"
1013508-44 = "[s] \"い、嫌だ！私は屈しない！！\""
1013508-45 = "ちゃんと見てくださいってば！"
1013508-46 = "[s] \"くうっ……！\""
1013508-47 = "よろしい。では胸に手を当てて答えてください。"
1013508-48 = "普段、ちゃんと掃除してますか？"
1013508-49 = "[s] \"……！\""
1013508-54 = "なっ！？待ちなさい！今ので全部分かりましたから！こらっ！逃げるなーっ！！"
1013508-58 = "……。"
1013508-59 = "[s] \"……。\""
1013508-60 = "先生。"
1013508-61 = "[s] \"うっ、うん？\""
1013508-62 = "ここは……住居ですか？ゴミ屋敷ですか？"
1013508-63 = "前者と答えたらモラル無し、後者と答えたら人間失格です。"
1013508-64 = "10秒差し上げます。言い訳開始。"
1013508-65 = "[s1] \"き、聞いてケイちゃん！全部説明するから！\"\n[s2] \"本来、掃除や家事はキリがないものでね！？\""
1013508-68 = "それで？"
1013508-69 = "[s] \"今日の分を終えたら、明日にはまた明日の分が発生する！\""
1013508-70 = "はい、続けて。"
1013508-71 = "[s3] \"だからその気になった時にまとめて済ませた方が！\"\n[s4] \"気持ちもいいし合理的じゃないかなって！？\""
1013508-77 = "黒ずくめの合理主義者みたいな言い訳をしますね！？"
1013508-78 = "はぁ……言い訳は終わりましたか？#nそれじゃあ――"
1013508-84 = "本当に……どうして私が……。"
1013508-90 = "リオの部屋よりはマシですが……いえ、あれは比べるべくもないですね……。"
1013508-94 = "この埃の量……こんなところで生活していたら体を悪くしますよ……？"
1013508-101 = "ふぅ……。"
1013508-102 = "では先生？"
1013508-103 = "[s] \"はい……。\""
1013508-104 = "何か言うことは？"
1013508-105 = "[s5] \"申し訳ありませんでした。誠にありがとうございます。\"\n[s6] \"申し訳ございません。感謝申し上げます。\""
1013508-108 = "……分かればいいです。"
1013508-109 = "もしもまた散らかっていた時には……。"
1013508-113 = "……。"
1013508-114 = "結局、また散らかすんですよね？"
1013508-115 = "はあ……1人で頑張らないで私を呼んでください。"
1013508-116 = "[s7] \"……！？\"\n[s8] \"助けてくれるの……？\""
1013508-119 = "どうせ先生は1人だとやらないじゃないですか。"
1013508-120 = "それに、2人の方が早いでしょう？"
1013508-124 = "[ns] \"やっぱり……やっぱり……！！\""
1013508-125 = "なんですか、勿体ぶって……。"
1013508-126 = "あ、待ってください、そのニヤニヤ顔……。"
1013508-127 = "また変なこと言ったら本当に――！"
1013508-128 = "[ns9] \"ケイちゃんって可愛い！\"\n[ns10] \"ケイちゃんって可愛い！！\"\n[ns11] \"ケイちゃんって可愛い！！！\""
1013508-132 = "あ\"あ\"～～～～っ！！！！！！！"
