[translation]
1600915-1 = "忍者少女は覚えててほしい！"
1600915-100 = "もっと早くから、多くの人とこの楽しみを分け合えていれば……。"
1600915-101 = "一人で楽しむんじゃなくて、他の人にも教えて、もっと多くの人の記憶に残せていれば――"
1600915-102 = "……そう、思ったんだけど。"
1600915-103 = "[s] ミチルの頭を優しく撫でる。"
1600915-104 = "えへへっ……ありがとー、先生殿。"
1600915-105 = "……。"
1600915-106 = "そういえば2ブロック向こうに、忍具店があるはず！"
1600915-107 = "[s] \"切り替え早くない！？\""
1600915-108 = "だってだって！「妖銃ムラマト」だけじゃなくて、#n呪われた悪の手榴弾「妖弾マサムネ」の本物も入荷したって噂なんだよ！？"
1600915-110 = "でもマサムネはただのオマージュだとか、それどころかムラマトをパクっただけーって批判もあってね。今ではそれなりに知名度があるけど――"
1600915-112 = "（そうして二人で商店街を見て回っている間も……）"
1600915-114 = "（ミチルは大事そうに、ビデオテープを抱きしめていた）"
1600915-12 = "[ns] \"……ビデオテープ！？\""
1600915-13 = "やっぱり知ってたんだね、先生殿～"
1600915-14 = "そう、今となっては忘れられかけた存在……びでお、てーぷっ！"
1600915-15 = "[s1] \"な、懐かしい……。\"\n[s2] \"何のビデオなの？\""
1600915-18 = "ふふっ、気になる？気になるよねー？"
1600915-19 = "このビデオには……。"
1600915-2 = "商店街入口"
1600915-20 = "なんと……！"
1600915-21 = "[s] \"ミチルが初めて歩いた日の記録、とか……！\""
1600915-22 = "うにゃっ！？"
1600915-23 = "違うよ！どうしたらそんな発想になるのさ！？"
1600915-24 = "[s] \"違うんだ……。\""
1600915-25 = "何で残念そうなの！？"
1600915-26 = "と、とにかく、このビデオには……！"
1600915-27 = "忍者の道を歩む者なら、誰でも知っている……。"
1600915-28 = "あの「カラスにゃんにゃん」監督が、駆け出し時代に撮影した白黒映画！ "
1600915-29 = "『隠し教室の三忍者』が入ってるんだよ！"
1600915-3 = "ふっふっふ……やっぱり来たね、先生殿。"
1600915-33 = "[ns] \"……なるほど？\""
1600915-34 = "反応薄い！？"
1600915-35 = "こういう時は、「やはりお前も知ってたか」みたいな熱い眼差しで頷き合う！#nそれが忍者の鉄則でしょぉ！？"
1600915-36 = "……えっ、初めて聞いた？"
1600915-37 = "ま、まぁ確かに？カラスにゃんにゃん監督の作品はちょーっと古いし……#nほとんどが白黒映画で、今では入手するのも難しいけど……。"
1600915-38 = "……でも教科書で習ったでしょ！？"
1600915-39 = "[s] \"載ってなかったかなぁ！？少なくとも私の教科書には！\""
1600915-4 = "忍者を志す者としては、無視できるものじゃないよね！"
1600915-40 = "とにかぁく！#nまさか『隠し教室の三忍者』を観てないなんて……。"
1600915-41 = "先生殿の人生に、まだまだ楽しみが残されてたってことだね。"
1600915-42 = "これを今から初見で楽しめるなんて、羨ましい……！"
1600915-43 = "[s] \"そこまで……！？\""
1600915-44 = "当然っ！"
1600915-45 = "だって私は……この映画を見て、忍者の世界に足を踏み入れたんだし。"
1600915-46 = "[s3] \"そこまでの思い出の映画……。\" \n[s4] \"それは凄い！\""
1600915-49 = "でっしょー！？"
1600915-5 = "[s] \"私は、忍者を志してたのか……！？\""
1600915-50 = "[s] \"じゃあ今日は、このビデオの上映会をするの？\""
1600915-51 = "んー……#nできることなら、商店街の真ん中で上映したいところなんだけどー……。"
1600915-52 = "今日は別の目的があって。"
1600915-53 = "……このビデオテープを、バックアップしたいなって。"
1600915-54 = "[s] \"バックアップ？\""
1600915-55 = "ちょっと前に、商店街の写真館であるサービスが始まったらしくって。"
1600915-56 = "ビデオテープの映像をデジタル化して、#nパソコンにバックアップできるようにしてくれるんだって。"
1600915-57 = "もし上手くいけば、作品の鑑賞が気軽にできるようになる！"
1600915-58 = "だから、このビデオテープを持ってきたってわけ！"
1600915-59 = "大事なものだから、ちゃんと保管しておきたいし……。"
1600915-6 = "何それ、今さら～？"
1600915-60 = "アレだよアレ。忍者がスイーツとか食材の長期保存のために、#n丸薬状にするようなもの！"
1600915-61 = "正式には、兵糧丸って呼ぶんだけど―― "
1600915-62 = "[s] \"それじゃあ出発！\""
1600915-63 = "ちょっとぉ！？#n良いところだったのにぃ！"
1600915-69 = "……これは難しそうだ。"
1600915-7 = "とにかく、私が持ってきた古代の記録媒体とは――"
1600915-70 = "ど、どうして……！？"
1600915-71 = "お金が足りないとか！？"
1600915-72 = "いや、ビデオテープ側の問題だね。"
1600915-73 = "これじゃあ、映像を取り出せそうにない……。"
1600915-74 = "[s] \"何か方法は無いんでしょうか？\""
1600915-75 = "うーん、かなり古いものだからなぁ……。"
1600915-76 = "ご覧、フィルムに傷がいくつも付いてる。"
1600915-77 = "ちょっとウチでは厳しいな。"
1600915-8 = "これっ！"
1600915-81 = "うぐぐ……そっかぁ。"
1600915-82 = "仕方ないね……。#n行こう、先生殿。"
1600915-87 = "んー、やっぱりかぁ……。"
1600915-88 = "[s] \"もしかして、最初から分かってたの？\""
1600915-89 = "うん、ずっと前から壊れちゃってたし。"
1600915-90 = "[s] \"そうだったんだ……。\""
1600915-91 = "何百回も再生してたんだけど……。"
1600915-92 = "ちゃんと回らなくなっちゃって。"
1600915-93 = "専門の業者なら……って思ったけど、やっぱりダメだったかぁ。"
1600915-94 = "[s] \"……大丈夫？\""
1600915-95 = "……ううん、すっごい悲しい！"
1600915-96 = "思い出を、もう取り出せなくなったわけだし……。"
1600915-97 = "それにもう、このビデオは手に入らない。"
1600915-98 = "[s] \"ミチル……。\""
1600915-99 = "……たまに、思うんだ。"
