[translation]
1601803-1 = "隊長の重み"
1601803-2 = "（ラブと一緒に商店街へ向かった）"
1601803-3 = "ん～……ううーーんん……。"
1601803-4 = "悩むなぁ……。"
1601803-5 = "[s1] \"きな粉？みたいに見えるけど……。\"\n[s2] \"何に使うの？\""
1601803-8 = "きな粉じゃないわ。これはクルミの殻を砕いたもの。"
1601803-9 = "ヘルメット団の必需品よ。これを使って磨いていくの。"
1601803-10 = "ヘルメットを塗る時は、まず元の色を紙やすりで全部剥がすんだけど……。"
1601803-11 = "剥がした直後は表面がツルツルで光を反射するから、#n磨いて元のガサガサに戻さないといけないのよ。"
1601803-12 = "[s] \"ツルツルなヘルメットも持ってたよね？\""
1601803-13 = "ええ、使い分けてるわ。"
1601803-14 = "戦闘の時はガサガサのツヤ消しメット、#nカッコつけたい時はツヤツヤメット……みたいにね。"
1601803-15 = "それで、ガサガサにするのにクルミの研磨剤を使うってわけ。"
1601803-16 = "問題は、粗さの番手を30番にするか50番にするかなんだけど……。"
1601803-17 = "[s] \"全部同じじゃないの？\""
1601803-18 = "違うわよ！もっとよく見て！？"
1601803-19 = "んん……今月も金欠だし、一つに絞らないと……。"
1601803-26 = "ん？"
1601803-27 = "あいつ、ジャブジャブヘルメット団のリーダーじゃね？"
1601803-28 = "隣にシャーレの先生もいるな。"
1601803-29 = "おい！そこのオカッパ！"
1601803-30 = "ヘルメット団は引退して、大人とお出かけでちゅか～？"
1601803-34 = "あぁ？"
1601803-35 = "子分はどうしたんだ？"
1601803-36 = "おい、今のうちにやっちまうか？"
1601803-37 = "……はぁ。"
1601803-38 = "先生、ちょっと失礼するわね。"
1601803-39 = "[s] \"なんで靴下を銃に……？\""
1601803-40 = "ん？どうしたアイツ。"
1601803-41 = "ビビって血迷ったか？"
1601803-42 = "お姉さんね、いま弾代も節約しなきゃいけないの。"
1601803-43 = "これはチャンスよ？#n[ruby=・]お[/ruby][ruby=・]買[/ruby][ruby=・]い[/ruby][ruby=・]物[/ruby]が済んだら、とっとと失せな。"
1601803-44 = "ふざけやがって……。"
1601803-45 = "やっちまえ！！"
1601803-60 = "ぐはっ！"
1601803-65 = "銃で殴るたぁ卑怯だぞ……！"
1601803-66 = "よこせ！！"
1601803-77 = "靴下が滑って、銃が掴めない……っ！"
1601803-78 = "この靴下がすっぽ抜けたら、転んじゃうわね。"
1601803-79 = "やっ、やめっ……！"
1601803-80 = "やめない。"
1601803-90 = "あー、めんどくさ。"
1601803-91 = "[ruby=こまかぜ]河駒風[/ruby]ラブ！うちらの縄張りで、よくも……！！"
1601803-92 = "手榴弾でもくらえ！"
1601803-93 = "危ないでしょ！"
1601803-94 = "ふんっ！"
1601803-100 = "ぐあぁっ！！"
1601803-105 = "おっ、綺麗に飛んだわね。"
1601803-106 = "他の奴らも呼んでこい！絶対捕まえてやるっ！！"
1601803-114 = "つ、[ruby=つえ]強[/ruby]え……ぐぅっ。"
1601803-115 = "撤退！てったーい！！"
1601803-119 = "ほんっと、めんどくさい連中……。"
1601803-120 = "一日を棒に振っちゃったじゃない！！"
1601803-121 = "次は足腰立たなくしてやるわよ！"
1601803-122 = "はぁ……もうクタクタ。"
1601803-123 = "先生、大丈夫？怪我は？"
1601803-124 = "[s3] \"大丈夫！なんともないよ！\" \n[s4] \"いつもこんな感じなの？\""
1601803-127 = "今日はやたらと絡んできたけど、まあ、いつも通りかしら。"
1601803-128 = "スケバンもだけど、ヘルメット団の内輪もめもよくあるわね。"
1601803-129 = "まあ、今日みたいにガツンとやっとけば、当分は静かなはずよ。"
1601803-130 = "[s] \"ラブってすごく強いんだね！\""
1601803-131 = "はっ、当たり前でしょ？"
1601803-132 = "ヘルメット団隊長の名は伊達じゃないわ！"
1601803-133 = "[s] \"みんなが頼れるリーダーだね！\""
1601803-134 = "ちょっと褒めすぎじゃない……？#nえへへっ。"
1601803-135 = "[s] \"そして根は優しくて！\""
1601803-136 = "ちょっ……。"
1601803-137 = "[s] \"とげとげの歯も可愛い！\""
1601803-138 = "うるさいっ！！"
1601803-140 = "（その後、ポカポカ殴られながらラブを褒めちぎった）"
