[translation]
1601906-1 = "朝焼けの記憶"
1601906-2 = "――もちろん、私たちの防御システムに隙はありません。#n他でもないリオ様が作りましたので。"
1601906-3 = "ですが想定外の事態には常に備えておくべきです。"
1601906-4 = "ここは、常識が通用しない場所ですから。"
1601906-5 = "[s] \"やっぱりトキは頼もしいね。\""
1601906-6 = "ありがとうございます。"
1601906-7 = "ですが、明け方の偵察には別の理由もあるのです。"
1601906-8 = "[s] \"それは？\""
1601906-9 = "もうすぐ分かります。"
1601906-17 = "……ちょうど良いですね。"
1601906-21 = "先生。あちらをご覧ください――"
1601906-25 = "[wa:2060]― [log=토키 결전]綺麗な朝焼けですね。[/log]"
1601906-27 = "― [log=토키 결전]ここでは毎日、[wa:1670]この景色が[wa:510]観測できます。[/log]"
1601906-30 = "[wa:730]― [log=토키 결전]といっても、[wa:1120]ここに来てからの[/log]"
1601906-32 = "― [log=토키 결전]数日分しか[wa:750]記録はないので……。[/log]"
1601906-35 = "― [log=토키 결전]毎日ではないのかも[wa:920]しれませんが。[/log]"
1601906-38 = "[ns] \"すごく綺麗だね……。\""
1601906-39 = "#wait;1000"
1601906-40 = "[wa:1070]― [log=토키 결전]はい。[wa:1460]でも、[wa:1030]ここからだと[/log]"
1601906-42 = "― [log=토키 결전]全く違った色に[wa:810]感じられるんです。[/log]"
1601906-45 = "― [log=토키 결전]空も……[/log]"
1601906-47 = "― [log=토키 결전]橙色に輝く[wa:1110]大地も……。[/log]"
1601906-50 = "[wa:890]― [log=토키 결전]私は、[wa:1080]先生と[wa:630]こうして景色を共有する[wa:1140]時間が好きです。[/log]"
1601906-52 = "― [log=토키 결전]心が動いたものを[wa:1780]こうして伝えられる[wa:1490]このひと時が……。[/log]"
1601906-55 = "[wa:1900]― [log=토키 결전]この一瞬は、[wa:1410]いまこの時間しか[wa:740]存在しません。[/log]"
1601906-57 = "― [log=토키 결전]そして、[wa:1190]二度と戻ってこない。[/log]"
1601906-60 = "[wa:2510]― [log=토키 결전]先生。[/log]"
1601906-62 = "― [log=토키 결전]もしも今、[wa:1360]「最後」の時が[wa:690]訪れたら――[/log]"
1601906-65 = "[wa:730]― [log=토키 결전]私は、[wa:1270]先生のそばで[wa:1610]その瞬間を共にする……。[/log]"
1601906-67 = "― [log=토키 결전]「最後」の一人に[wa:770]なれますか？[/log]"
1601906-70 = "[ns] \"これが、トキのお気に入りなんだね。\""
1601906-71 = "はい。"
1601906-72 = "もちろん、これが相反する感情だということは分かっています。"
1601906-73 = "どうしたって、ここは敵地です。"
1601906-74 = "良いと思えるものを見つけたとしても……次の瞬間には、致命的な結果を招くきっかけになる可能性があります。"
1601906-75 = "ですが……人は身勝手な生き物なんですよね。"
1601906-76 = "状況に関わらず、自分が良いと感じれば、その状況を良いものだと捉えてしまうのですから。"
1601906-77 = "[s] \"美しいものを美しいと感じるのは良いことだと思うよ。\""
1601906-81 = "[ns1] \"だってそれは――\"\n[ns2] \"希望を失わないという証拠だからね。\""
1601906-84 = "……なるほど。"
1601906-85 = "……はい？#n「最後の時が訪れる」とか「最後の一人」とかの表現は少し怖かった？"
1601906-86 = "……。"
1601906-87 = "たしかに、そうかもしれません。#n「最後」は怖いものです。"
1601906-88 = "でも大丈夫です。先生のそばには私がいます。"
1601906-89 = "何より……その訪れは、絶対に私が阻止します。"
1601906-90 = "そのために、私は武装をしてまでここにいるのですから。"
1601906-94 = "……朝焼けが終わってしまいましたね。#n良い時間はあっという間に過ぎてしまうものです。"
1601906-95 = "……。"
1601906-97 = "このまま、時が止まればいいのに。"
1601906-98 = "大切な記憶を集めて――"
1601906-99 = "ずっと大事にとっておくことができたら。"
1601906-101 = "[ns3] \"そうだね。きっと素敵だと思うよ。\"\n[ns4] \"でも……一緒に居る「今」も素敵じゃない？\""
1601906-104 = "……。"
1601906-105 = "そう、ですね……。"
1601906-106 = "私と、先生と……。"
1601906-107 = "……。"
1601906-108 = "先生。"
1601906-109 = "[s] \"うん？\""
1601906-110 = "少し、じっとしていてください。"
1601906-114 = "（トキはそう言うと――）"
1601906-120 = "（そっと、抱きしめてきた）"
1601906-121 = "[ns] \"トキ！？\""
1601906-122 = "しーっ。誰かが起きてしまうかもしれません。"
1601906-123 = "少しだけ……ほんの少しでいいのです。"
1601906-125 = "……。"
1601906-126 = "時を止めることは叶いませんから……。"
1601906-127 = "深く……記憶に刻ませてください。"
1601906-131 = "……ありがとうございます、先生。"
