[translation]
1601902-1 = "パーフェクトメイド"
1601902-2 = "おはようございます、先生。"
1601902-3 = "それでは本日の業務を始めます。"
1601902-10 = "すでに掃除は終わらせてあります。塵1つありません。#nですが礼には及びません。"
1601902-11 = "私はただ任務を遂行しているだけですので。"
1601902-12 = "はい、コーヒーをどうぞ。"
1601902-13 = "90度に温めたデミタスカップに、ブルボンポワントゥをフルシティローストして、ネルドリップで1.5オンス抽出しました。"
1601902-14 = "豆本来の味と香りを楽しめると思います。"
1601902-15 = "コーヒーのお供としてキルシュトルテのショートケーキもご用意しました。"
1601902-16 = "心配は要りません。こちらはノンアルコールのさくらんぼ酒を使用していますので。"
1601902-17 = "洗濯物がありましたら私にお任せを。"
1601902-18 = "本日の業務リストをまとめてあります。#n私なりに優先順位をつけさせていただきましたが、一度ご覧になってください。"
1601902-22 = "[ns] \"……トキ？\""
1601902-23 = "どうかしましたか？"
1601902-24 = "[s] \"トキって……こんなに敏腕だったの……？\""
1601902-25 = "もちろんです。私は完璧なメイドですので。"
1601902-26 = "ですがこれでもまだ本領を発揮していません。"
1601902-27 = "リオ様とご一緒していた頃は、今よりさらに完璧なハイパーパーフェクトメイドモードでしたので。"
1601902-28 = "[s] \"それなら今まではどうして……？\""
1601902-29 = "先生はご自分で生活できますから。"
1601902-30 = "[s] \"本当にそういう理由だったの！？\""
1601902-31 = "先生、私も人間です。休まないと壊れてしまいます。"
1601902-32 = "ちなみに人が壊れてしまう理由はもう1つあります。#nそれは暇な時間が続いている時です。"
1601902-33 = "ですから先生は、私の暇つぶしに付き合う必要があります。"
1601902-34 = "あ、別に今は大丈夫です。"
1601902-35 = "むしろ軽い緊張感が保たれていてちょうど良いくらいです。"
1601902-36 = "[s] \"つまり今の私は、世話が焼けるってこと……？\""
1601902-37 = "それは違います。私だって時と場所は弁えているという話です。"
1601902-38 = "今は非常事態ですので。"
1601902-39 = "各々が力を合わせて役割を全うすべきです。"
1601902-40 = "そうでなければ、明日を迎えられなくなりますので。"
1601902-41 = "[s] \"これは正真正銘のパーフェクトメイドだね。\""
1601902-42 = "ピース、ピース。"
1601902-43 = "はい？他にも気になることがあるのですか？"
1601902-44 = "リオ様の世話は毎日ちゃんとしていたのではないか、と……？"
1601902-45 = "……。"
1601902-46 = "先生。"
1601902-50 = "あの方は、毎日が非常事態でした。"
1601902-51 = "[s] \"トキもよく頑張ったね。\""
1601902-52 = "ありがとうございます。"
1601902-53 = "……とにかく、そういうことですので。"
1601902-54 = "本来であればパーフェクトメイド服で補佐すべきなのですが……。"
1601902-55 = "このような服装になってしまったこと、お許しください。"
1601902-56 = "[s1] \"その服装だって、トキは立派なメイドだよ。\"\n[s2] \"トキがいてくれると心強いね。\""
1601902-59 = "そういうことでしたら、24時間密着警護はいかがですか？"
1601902-60 = "[s] \"え……？\""
1601902-61 = "たとえば、背中の洗いっことか。"
1601902-62 = "他にも、ベッドを温めてあげることもできます。"
1601902-63 = "ええ、私の体温ならきっと――"
1601902-64 = "[s] \"ちょっと待って！\""
1601902-65 = "はっ！#n大事なことを見落としており申し訳ございません。"
1601902-66 = "この部屋の室温は平均より低いので――"
1601902-67 = "今すぐ肌を合わせて温めるべきですね。"
1601902-68 = "[s] \"き、気持ちだけでいいから！\""
1601902-69 = "遠慮なさらずに。"
1601902-70 = "今の先生は誰よりも大事ですから、これくらい当然です。"
1601902-72 = "（それからしばらくの間、トキと鬼ごっこをする羽目になった）"
1601902-73 = "（トキにとっては十分な暇つぶしになったようで、満足げな顔をしていた）"
