[translation]
1601802-1 = "隊長の訪問"
1601802-3 = "[ns1] \"ラ～ブ～！！\"\n[ns2] \"ウェルカムトゥ、シャーレッ！！！！\" "
1601802-6 = "う、うるさいっ！いちいち声がデカいのよっ！"
1601802-7 = "[s3] \"ラブがシャーレに来てくれた……！\"\n[s4] \"今日はラブ記念日だ！！\""
1601802-10 = "は、はぁっ！？き、記念日って何！！？"
1601802-11 = "というか、なんでロビーに？#nロビーでする仕事でもあったの？"
1601802-12 = "[s] \"ん？オフィスから走ってきたの。\""
1601802-13 = "ワンコかあんたは！"
1601802-14 = "転んでケガしたらどうするのよ！"
1601802-15 = "はぁ……歓迎してくれるのはいいんだけど。"
1601802-16 = "先生って……その。"
1601802-17 = "まわりの視線とか、気にならないわけ？"
1601802-18 = "[s5] \"私、変な格好だったかな？\"\n[s6] \"この服、一番のお気に入りなんだけど……。\""
1601802-21 = "そっ、そうじゃなくて！"
1601802-22 = "先生って、生徒のお手本にならなきゃいけないんじゃない？"
1601802-23 = "生徒会とか、ヴァルキューレとも付き合いがあるでしょ？"
1601802-24 = "だから……。"
1601802-25 = "うちみたいな不良と一緒にいていいのか、って話。"
1601802-26 = "[s] \"それがどうかしたの？\""
1601802-27 = "いやっ、だから……。"
1601802-28 = "はぁ……もういいわ、先生はなんとも思ってないのね。"
1601802-29 = "[s] \"ラブはすごくいい子だよ？\""
1601802-30 = "はぁっ！？"
1601802-31 = "[s7] \"連絡する時、丁寧な言葉を使ってくれるし。\"\n[s8] \"相手の事も考えてくれるし。\"\n[s9] \"転ばないように心配してくれるし！\""
1601802-35 = "いっ、いきなりなにっ！？"
1601802-36 = "それくらい普通でしょ！うち、どれだけ性悪だと思われてるのよ！？"
1601802-37 = "……まあ、先生がいいならいいわ。"
1601802-38 = "でもさすがに、長居するのはちょっとね……。"
1601802-39 = "それじゃ、またね。階段では走らないのよ。"
1601802-40 = "お邪魔したわね。"
1601802-41 = "[ns10] （ラブをシャーレに連れていく）\n[ns11] （シャーレにラブを連れていく）"
1601802-45 = "なっ、何！？"
1601802-46 = "[s12] \"私の自慢の生徒に……。\"\n[s13] \"シャーレを案内してあげるね！\""
1601802-49 = "シャーレ！？い、今！？"
1601802-50 = "[s] \"おんぶしようか？\""
1601802-51 = "何言ってんのバカっ！"
1601802-52 = "普通に案内して！"
1601802-54 = "（そうしてラブにシャーレを案内し……）"
1601802-55 = "（楽しい時間を過ごした）"
