[translation]
1601805-1 = "隊長の強さ"
1601805-2 = "[ns] \"はぁ……はぁ……。\""
1601805-3 = "……。"
1601805-4 = "[s] \"はぁ、はぁ、はぁ……！\""
1601805-8 = "[ns] \"ぜーーはーーぜーーはーー……。\""
1601805-10 = "[ns] \"すぅぅぅぅ～はぁぁぁぁぁ……。\""
1601805-11 = "いつまでそうやってるつもりなのよ……。"
1601805-12 = "どれくらい走ってきたの？"
1601805-13 = "[s] \"シャーレからずっと！\""
1601805-14 = "普通、電車とかタクシー使わない？はぁ……。"
1601805-15 = "ブラックマーケットって言っただけなのに駆けつけて、バカでしょ。"
1601805-16 = "……なんか、ハードル上がるじゃない。"
1601805-17 = "大したものじゃないのに……。"
1601805-18 = "ほらこれ、見て。"
1601805-19 = "[s1] \"自販機？\"\n[s2] \"自販機ごと買ったんだ？すごいね。\""
1601805-20 = "そう、自販機。"
1601805-21 = "って、んなワケないでしょ！"
1601805-22 = "普通の自販機じゃないの。ほら、値段見て？"
1601805-23 = "なんと、一本20円よ！"
1601805-24 = "覚えておいたら、またここに来た時使えるでしょ？"
1601805-28 = "そ、それだけよ。"
1601805-29 = "[s3] \"ラブが教えてくれたブラックマーケットの極秘情報……。\"\n[s4] \"メモしとかなきゃ……。\""
1601805-32 = "ほんっと大げさなんだから！"
1601805-33 = "まあいいわ。ここまで来てくれたんだし、一本おごってあげる。"
1601805-34 = "最近仕事もいい感じだったし、このくらいなら平気よ。"
1601805-35 = "[s] \"ラブの奢ってくれたジュース……博物館に飾りたい。\""
1601805-36 = "おだまり！！"
1601805-41 = "はい。"
1601805-42 = "[s5] \"いただきます！！\"\n[s6] \"骨の髄まで染み渡るっ……！！\""
1601805-45 = "あれだけ走ったんだもの、さぞおいしいでしょうよ。"
1601805-46 = "……ぐ。"
1601805-47 = "ぐぐっ……なにこれ……！んぐぐぐ！"
1601805-48 = "[s7] \"どこか痛い？\"\n[s8] \"もしかして熱でもある？\"\n[s9] \"お腹すいた！？\""
1601805-52 = "先生、過保護って言われない？"
1601805-53 = "ちょっと……開かないだけよ！"
1601805-54 = "んぐぐっ……！！"
1601805-55 = "あーもうムカつく！！一発撃ったら開くかしら！？"
1601805-56 = "[s] \"貸して。\""
1601805-57 = "気をつけてね。硬すぎて怪我しちゃうかも。"
1601805-58 = "ダメだったらゴム手袋で――"
1601805-63 = "[ns] \"はい、どうぞ。\""
1601805-64 = "……。"
1601805-65 = "ばっ、バカにしてっ！？"
1601805-66 = "[s] \"まだ何も言ってな……。\""
1601805-67 = "うぅ……。"
1601805-68 = "うちね、体力には自信あるんだけど。"
1601805-69 = "握力だけは全然ないの。#nだから、[ruby=あのこたち]団員[/ruby]の前じゃあんまりこういうのは飲まなくて。"
1601805-70 = "恥ずかしいわね、先生の前でこんな姿……。"
1601805-71 = "[s] \"私がいつでも代わりに開けてあげるよ。\""
1601805-72 = "なっ、何言ってるのよもう！？"
1601805-73 = "と、とにかく！#nうちがフタを開けられなかったこと、バラしたら分かってるわね！？"
1601805-74 = "返せっ！うちのジュース！"
1601805-75 = "[s] \"あっ……。\""
1601805-80 = "（ラブは逃げるように去っていった）"
1601805-81 = "（私のジュースを奪って……） "
