[translation]
1601806-1 = "隊長の優しさ"
1601806-10 = "「隊長！行くならあたしを倒してからだ！」って。"
1601806-104 = "（ラブは慌ててヘルメットを外し、遠くに消えていった……）"
1601806-11 = "ほんと、あれは誰かに見せたかったわね！"
1601806-13 = "あと、うちのヘルメットが壊れた時さ。"
1601806-14 = "あいつ、みんなでお金出し合って修理してくれたんだよ？"
1601806-15 = "そういう可愛いとこもあるってワケ！"
1601806-17 = "――で、めっちゃボコられて帰って来たの。"
1601806-18 = "それでうちが「そいつら今どこ？ギッタギッタにしてやる」って――"
1601806-19 = "ん？あれって……。"
1601806-2 = "先生さ。いつも走ってきて、疲れない？"
1601806-20 = "[s] \"アヒルだ。\""
1601806-21 = "アヒルかぁ……うち、アヒルとガチョウの違いもあんま分からないけど……。"
1601806-22 = "あの子は、カッコイイわね。"
1601806-23 = "6羽も雛を連れてる。"
1601806-24 = "[s1] \"あの子たち……。\"\n[s2] \"排水溝の上を通ろうとしてるね。\""
1601806-27 = "そうね。"
1601806-28 = "……あっ！！子供たちが落ちちゃった！"
1601806-29 = "もう、みんなまだ小っちゃいんだから！気をつけなきゃ！"
1601806-3 = "ほんとに転んだらどうすんのよ。"
1601806-30 = "はぁ、仕方ないわね。"
1601806-31 = "先生、ちょっと手伝って。"
1601806-4 = "[s] \"大事な生徒を待たせるわけにはいかないからね！\""
1601806-40 = "[wa:1880]― [log=라브]いち、[wa:640]に、[wa:810]さん、[wa:740]し、[wa:810]ご、[wa:780]ろく。[wa:1300]よしっ！[/log]"
1601806-42 = "― [log=라브]6羽ともちゃんと全員いるわね！[/log]"
1601806-45 = "― [log=라브]ママの言うことはちゃんと聞いときなさいよ、[/log]"
1601806-47 = "― [log=라브]あんたたち。[/log]"
1601806-5 = "（大事な生徒……）"
1601806-50 = "[wa:1850]― [log=라브]母アヒルももう大丈夫そうね。[/log]"
1601806-52 = "― [log=라브]これで一件[wa:770]落着、っ[wa:1020]と！[/log]"
1601806-55 = "[ns] \"ラブってあんまり生徒っぽくないよね。\""
1601806-56 = "[wa:700]― [log=라브]な、[wa:590]ななな……[wa:580]なに言ってんのよ！！[/log]"
1601806-58 = "― [log=라브]先生、[wa:960]それってちょっと失礼じゃない？[/log]"
1601806-6 = "ま、まあ別に大した用事じゃないんだけど。"
1601806-61 = "― [log=라브]え？[wa:1580]……あっ！？[wa:2240]えっ[wa:1060]と……。[/log]"
1601806-64 = "[ns] \"ヘルメット団のみんなを引っ張るところとかさ。大人っぽいっていうか。\""
1601806-65 = "[wa:880]― [log=라브]あ、[wa:270]ああっ！[wa:1000]そ、[wa:250]そういうことね！？[/log]"
1601806-68 = "― [log=라브]も、[wa:520]もちろん！[wa:580]リーダーだもの！[/log]"
1601806-7 = "いい天気だし、散歩でもどう……？"
1601806-70 = "― [log=라브]この程度できないとダメじゃない！[/log]"
1601806-73 = "[wa:1540]― [log=라브]（先生ってば、[wa:910]ホントに言い間違えただけ？）[/log]"
1601806-75 = "― [log=라브]（それともワザと……？）[/log]"
1601806-78 = "― [log=라브]（どっちにしろ腹立つわね！）[/log]"
1601806-80 = "― [log=라브]（わざとだったらもっとムカつくし！！）[/log]"
1601806-83 = "― [log=라브]（まさか、[wa:1920]わざとだっ[wa:960]たり[wa:1120]するのかしら……？）[/log]"
1601806-87 = "よいしょ……っと。#nこの辺りならいいかしら。"
1601806-88 = "みんな、足元にはちゃんと気をつけるのよ？"
1601806-89 = "えっとそれで……どこまで話したかしら。"
1601806-9 = "で、あいつ。うちの前に仁王立ちして言ったの。"
1601806-90 = "スケバンと3対100でやりあった話は――"
1601806-91 = "[s] \"ヘルメット、そのまま被って平気？\""
1601806-95 = "[ns3] \"アヒルたちが落ちたところ……。\"\n[ns4] \"排水溝……だよね？\""
1601806-98 = "！！！"
1601806-99 = "先生のバカ！！"
