[translation]
1601905-1 = "アップグレード"
1601905-10 = "先生、ここで何か感じられることはありませんか？"
1601905-11 = "[s1] \"無限弾薬と……二丁拳銃……？\"\n[s2] \"なんのことだろう……？\""
1601905-14 = "これは最高の組合せの1つだと、とある配信者が言っていました。"
1601905-15 = "ということは、パーフェクトな[ruby=あすま]飛鳥馬[/ruby]トキに相応しいアップグレードではないかと思うのです。いえーい。"
1601905-16 = "[s] \"それで……話というのは……？\""
1601905-17 = "大したことではありません。"
1601905-18 = "ただ、ふと思いついたのです。"
1601905-19 = "先生もご存知のとおり、私にはこれまで使用してきた色々な武装があります。"
1601905-2 = "ご存知のとおり、私は新しい武器をいただきました。"
1601905-20 = "そして今の私は、エネルギー武器のシステムを使えるようになりました。"
1601905-21 = "つまり可能な限り多くのもの……例えば、かつて潜入作戦で使用したアームギアなどをアップグレードできれば。"
1601905-22 = "カッコよくて――"
1601905-23 = "面白そう――"
1601905-28 = "……いえ。戦力の強化に役立つと思いました。"
1601905-29 = "[s] \"本音が2つも漏れた！？\""
1601905-3 = "いわば「アップグレード」された状態です。"
1601905-30 = "聞き間違いです。"
1601905-31 = "[s] \"そうかなぁ？\""
1601905-32 = "はい。"
1601905-33 = "……そのため息はどういう意味でしょうか？#nため息をつくと幸せが逃げると言いますよ。"
1601905-34 = "ですが、幸運のウサギメイドでありエージェント偵察隊である私がいますので、#n心配は要りません。"
1601905-35 = "[s] \"……話を戻すけど、どんな風にアップグレードしたいの？\""
1601905-36 = "これは失礼。つい話が逸れてしまいました。"
1601905-37 = "……つまり、こう思ったのです。"
1601905-38 = "アームギアにエネルギー武器のシステムを適用すれば――"
1601905-39 = "ロケットのように、アームギアを発射できるのではないでしょうか？"
1601905-4 = "[s] \"そうだね。\""
1601905-40 = "[s] \"カッコいいね！\""
1601905-41 = "やはり先生も分かってくださるのですね。"
1601905-42 = "どうでしょう、最高のアイデアだと思いませんか？"
1601905-43 = "さあ早く褒めてください。ナデナデもしてください。"
1601905-44 = "私がアームギアを発射する姿、見たいですよね？"
1601905-45 = "先生がそう思わなくても、私は見てみたいです。ですので早く。"
1601905-46 = "[s] \"その前に1つ聞いてもいい？\""
1601905-47 = "なんでしょうか。"
1601905-48 = "[s] \"なんで、わざわざ私の許可を？\""
1601905-5 = "その新しい武器というのが、この2丁のエネルギーピストルです。"
1601905-52 = "……。"
1601905-53 = "…………。"
1601905-54 = "………………。"
1601905-55 = "[s] \"トキ、私の目を見て。\""
1601905-56 = "はい。"
1601905-57 = "[s] \"素直に答えてね。\""
1601905-58 = "……。"
1601905-59 = "[s] \"目を逸らしてもダメ。\""
1601905-6 = "名前の通り、エネルギー武器です。"
1601905-63 = "……分かりました。お答えしましょう。"
1601905-64 = "リオ様とヒマリ部長から、安全上の理由で許可が下りなかったのです。"
1601905-65 = "発射する時に、熱のせいで火傷をする可能性が高いとのことで。"
1601905-66 = "[s] \"それはたしかにダメだね。\""
1601905-67 = "先生。"
1601905-68 = "より大きな目的のためには、些細なことは無視しても良いと思いませんか？"
1601905-69 = "些細なことじゃない、と？"
1601905-7 = "即ちエネルギーさえ供給できれば、耐久性の許す限り、いつまでも使用可能ということです。"
1601905-70 = "……。"
1601905-71 = "先生はそう思っても、私には些細なことです。#nですので、どうか許可を。"
1601905-72 = "[s] \"ダメです。\""
1601905-73 = "先生……。"
1601905-74 = "[s] \"そんな目で見ても、ダメなものはダメです。\""
1601905-75 = "でしたらせめて、高出力ビームを発射できるようなアームギアを……。"
1601905-76 = "3点バーストもできて、補助パーツをつければチャージの容量を増やせるような――"
1601905-77 = "[s] \"却下です。\""
1601905-78 = "先生……。"
1601905-8 = "いわば無限弾薬です。"
1601905-80 = "（その後、少し拗ねてしまったトキを宥めることになった）"
1601905-81 = "（しばらく頭を撫でてあげてようやく、トキは意地を張るのをやめてくれた……）"
1601905-9 = "さらに、二丁拳銃でもあります。"
