[translation]
2005202-1 = "インフラストラクチャー"
2005202-10 = "すなわち……通信線路設備工事です！"
2005202-100 = "もう課金したの！読めるところまで読んじゃって……。"
2005202-101 = "次はいつ更新されるの？サブスク登録するから！早く読ませて！"
2005202-102 = "！？"
2005202-103 = "これは驚きですねぇ……なんと凄まじいコンテンツ消費速度。"
2005202-104 = "では……最新話公開までの間、こちらの小説をコミカライズしたものはいかがでしょう？"
2005202-105 = "文章とはまた違う魅力があると思いますよぉ～？"
2005202-106 = "読む読む！"
2005202-107 = "あれ、漫画の無料分は10話だけ……？"
2005202-108 = "ああ、そこはご了承ください。絵を描くのはかなり工数のかかる作業でして……。"
2005202-109 = "更新を待ちきれないようでしたら、追加課金で作家を直接「応援」することもできますよぉ？"
2005202-110 = "今の世の中……なんだかんだ人を動かすのはお金、ですからねぇ。ムフフフ。"
2005202-111 = "（それにクラファンのプラットフォームも我々出版部が手掛けていますから、#n手数料をいただけてwin-winですとも）"
2005202-112 = "それはいいんだけど……なんで課金上限があるの？"
2005202-113 = "そうだよ！こっちは制限なく課金したいのに！"
2005202-114 = "お気持ちはありがたいのですが……我々出版部の目標は、読者の皆さんの時間を楽しく、豊かにすること。"
2005202-115 = "私どものプラットフォームのせいで、皆さんの日常生活に支障が出てしまっては本末転倒なのです。"
2005202-116 = "（……消費者を破産させては、長期商売は成り立たないんですよねぇ～）"
2005202-117 = "関連コンテンツとして、きっとこちらも気に入っていただけるかと思います。#n私どもが用意した動画なのですが……。"
2005202-122 = "ありゃ～……これは困りましたねぇ……。"
2005202-123 = "えっ何？どうしたの？"
2005202-124 = "……今のネット回線の速度では、高画質の動画がみれない？"
2005202-125 = "残念ながらそのようですねぇ～#nいやあ、事務局がなかなか予算をくれないものでして。ですが――"
2005202-126 = "触れてみていかがでしたか？より多くのweb小説にweb漫画……。"
2005202-127 = "高画質の動画とコンテンツを楽しんでいただくためには、より高速で安定したネット環境が……。"
2005202-128 = "……必要、ですよねぇ？"
2005202-134 = "そうだよ！！"
2005202-135 = "事務局がまた……よし！抗議しにいこう！"
2005202-136 = "寮のみんなも呼ぶ？"
2005202-137 = "他の寮にも声をかけよう！"
2005202-138 = "ムフフ。ついでに私どものプラットフォームの宣伝もすこ～しだけ、お願いできますか～？"
2005202-139 = "コンテンツとはみんなで共有してこそ、楽しみが増えるというものですから。"
2005202-14 = "どうして出版部が？といわんばかりの顔ですねぇ。"
2005202-140 = "ああ、任せて！"
2005202-141 = "ここ、SNSみたいな掲示板もあるんだね！レビュー書いとくよ！"
2005202-142 = "ムフフ。感謝申し上げます。"
2005202-143 = "これからも良質なコンテンツを皆さんに提供できるよう、私どもレッドウィンター出版部は、皆様からの更なるご助力を賜りたく存じます～"
2005202-144 = "（ラインナップの3分の1は、レッドウィンターの外から安価で仕入れたコンテンツですけどねぇ……）"
2005202-145 = "（それでもレッドウィンターでは新作扱いされますし、まあ問題ないでしょう。ムフフフ）"
2005202-147 = "（そうして生徒たちは、高速回線の設置を事務局に訴え――）"
2005202-148 = "（出版部の事業は、勢いよく伸びていくのであった……！）"
2005202-15 = "ムフフ。たしかに通信線路の工事は公共事業にあたるもの。"
2005202-154 = "結果、事務局の財政に少しダメージがあったようですが……。"
2005202-155 = "元はといえば事務局の怠慢が原因だったわけですし、出版部に非はないんじゃないですかねぇ～？"
2005202-156 = "ムフフフ！"
2005202-157 = "[s] \"ちょっと思ったんだけど……。\""
2005202-158 = "はい？"
2005202-159 = "[s] \"ヤクモって、恐ろしい子だね……。\""
2005202-16 = "本来ならば、レッドウィンター事務局が担当しなければなりません。"
2005202-160 = "何をおっしゃるのやら。私ほど無害な生徒はいませんよぉ～？ムフフ。"
2005202-17 = "まあ、あの事務局では、100年経っても工事に着手できないでしょうねぇ～"
2005202-18 = "[s] \"じゃあ出版部は……。\""
2005202-19 = "お察しのとおり。"
2005202-2 = "今日も寒いですねぇ～"
2005202-20 = "事務局に代わって請け負うことになったのですよ。"
2005202-21 = "[s1] \"なるほど……。\"\n[s2] \"事務局の依頼だったんだ……。\""
2005202-24 = "はい、ですから今から私一人で通信線路を全部設置……はいたしません。"
2005202-25 = "設備を設置したという結果さえあればよいので。"
2005202-26 = "は～い、みなさん！こちらですよ～！"
2005202-3 = "ま、いつものことなんですが。"
2005202-34 = "報酬にプリンをくれるって話、本当なんだよな？"
2005202-35 = "予定より早く終わったらおまけに「特製モルス」ももらえるって聞いたけど本当？"
2005202-37 = "もちろんです。雇用関係で大切なのは信頼ですから。"
2005202-38 = "出版部部長の私、[ruby=あらまき]荒槇[/ruby]ヤクモはお金が関わっている以上、いい加減な仕事はいたしません！"
2005202-4 = "[s] \"こんな奥地までくる必要……あった？\""
2005202-42 = "……どうしました先生？驚いた顔して。"
2005202-43 = "[s3] \"いや……下請けの下請けを雇ったヤクモなら――\"\n[s4] \"出版部の利益が最大になるよう、\"\n[s5] \"報酬を最低限にすると勝手に思ってた……。\""
2005202-47 = "あらぁ……心外ですねぇ。私だって鬼じゃないですよぉ？"
2005202-48 = "まあ、もし誰かに代金を横取りでもされたら、鬼より凶悪になれる自信はありますけれども。"
2005202-49 = "……まったく、素人思考ですねぇ先生。ムフフ。"
2005202-5 = "ええ、ありますとも。"
2005202-50 = "[s6] \"し、素人って言われた……。\"\n[s7] \"じゃあ、プロの考えを聞かせて！\""
2005202-53 = "ムフフ、ずばり……。"
2005202-54 = "インフラが安価で整ってこそ、本物の商売ができる、ということです！"
2005202-55 = "分かりますか先生？インフラ構築にかかるコストが上がれば、当然その費用は何らかの方法でユーザー側に請求されます。"
2005202-56 = "しかも、発注の主体はあのケチな事務局ですからねぇ。"
2005202-57 = "そもそもの話、今回は工事ができないようなレベルの予算しかもらってないですし。"
2005202-58 = "かと言って、足りない予算分を上乗せしてユーザーをカモにするだなんて――"
2005202-59 = "目先の利益しか見えていません……そんなの、長期損失に繋がるだけです！"
2005202-6 = "出版部にとっては小さな一歩でも、"
2005202-60 = "互いがリンクし合ってるこの超接続社会に！#n通信回線はもはやライフライン！"
2005202-61 = "そのライフラインを民営化してしまえば、最終的には全員が滅びの道を辿るでしょう！"
2005202-62 = "ですのでここでは、出版部が短期損失を恐れず――#nできる限り安く通信インフラを構築した上で！"
2005202-63 = "その運営権を事務局と交渉したほうが、理にかなった長期事業になる、というわけです。"
2005202-64 = "所有権ではありませんよぉ？運営権ですよ運営権。#n大事なことだから2回いいました。"
2005202-65 = "[s] \"結局、何をどうするの……？\""
2005202-66 = "まあまあ、これから見ていてください。"
2005202-67 = "ムフフフ。"
2005202-7 = "レッドウィンターにとっては大きな一歩となる！"
2005202-70 = "やっと……寮に有線が繋がった！"
2005202-71 = "これで、回線代高い割に遅くて、しょっちゅう切れるポケット無線を使わなくて済むんだ！"
2005202-76 = "ところで皆さん――"
2005202-77 = "安く、速度が出て途切れない安定したネット環境で……何をされるご予定ですか？"
2005202-79 = "えっ？そういえば……。"
2005202-8 = "……かもしれない事業のためです。"
2005202-80 = "考えたことなかったかも……。"
2005202-81 = "ままま、そういう時はまず、楽しいことからはじめませんか？"
2005202-82 = "私ども出版部が手掛けたプラットフォームでは、web小説を100話分、無料で読めちゃうのです。"
2005202-83 = "100話分！？"
2005202-84 = "しかも無料！？"
2005202-85 = "ええ。一定時間が経過しますと、別作品が無料で公開されますよぉ～"
2005202-86 = "もちろん、課金していただければ、人より早く確実に、最新話をお読みいただけますが……。"
2005202-87 = "課金……？"
2005202-88 = "100話分もタダで読めるのに？わざわざ課金する必要なくない？"
2005202-9 = "[s] \"それは一体……？\""
2005202-92 = "（ムフフ……最初は皆さん、そう思いますよねぇ……）"
2005202-93 = "[s]（ヤクモ……おそろしい子……！）"
2005202-96 = "あっ！全部読んじゃった！"
2005202-97 = "次！早く次の話が読みたいー！"
2005202-98 = "おやおや、落ち着いてください。さきほど申し上げたとおり、課金していただければ……。"
