[translation]
2005303-1 = "忍者少女は恥ずかしい！"
2005303-2 = "百鬼夜行商店街"
2005303-3 = "はい、こちらが頼まれていたドレスになります。"
2005303-4 = "おおっ……！"
2005303-5 = "……すごい、綺麗！"
2005303-6 = "破れた部分がどこだったか、全然分かんない！"
2005303-7 = "これがプロの腕前……！"
2005303-8 = "[s] \"良かったね、ミチル。\""
2005303-9 = "ふっふっふ……でも、これで終わりじゃないんだよ。"
2005303-10 = "しばし待たれよ、先生殿！"
2005303-15 = "（5分後……）"
2005303-16 = "先生殿！"
2005303-18 = "さぁ、次行こー！"
2005303-19 = "[ns] \"何で！？\""
2005303-20 = "ふふっ、何でも何も……。"
2005303-21 = "服とはすなわち、「着用する」もの。"
2005303-22 = "つまり、本当に修理できてるかを知るためには、着てみないと！"
2005303-23 = "[s] \"説得力が……ある！？\""
2005303-24 = "ただーし……着るだけじゃダメ！"
2005303-25 = "歩いたり、走ったり、重い物を持ったり！"
2005303-26 = "色んな動きをしてみて初めて……。"
2005303-27 = "完璧に直ってるかが、分かるはず！"
2005303-28 = "[s] \"一理あるけど……。\""
2005303-29 = "でしょー？"
2005303-30 = "ってことで、そのために最適なコースを練ってきたから！"
2005303-31 = "あっちに行くと、各種グッズを売ってるお店があってー。"
2005303-32 = "そっちの方には、前に二人で行ったお店もあるしー。"
2005303-33 = "ショッピングをしながら通りを抜ければ……！"
2005303-34 = "歩く、走る、重い物を持つ！#n全部の動きが入ってるって寸法！"
2005303-35 = "それに新しいグッズ……じゃなくて、忍具が入荷したんだって！"
2005303-36 = "いやー、これでもーっとたくさんの人が忍者の魅力に気づいちゃうね！"
2005303-37 = "[s] \"やっぱりそれが狙い！？\""
2005303-38 = "先生なら来てくれると思ったよ～！"
2005303-39 = "[s] \"まだ何も言ってないけどね！？\""
2005303-40 = "良いの良いの！それじゃあ、レッツゴ～！"
2005303-46 = "百鬼夜行・グッズ商店街"
2005303-47 = "（結局、ミチルに手を引かれるがまま商店街へやって来た）"
2005303-48 = "ほらほら、気合い入れて！"
2005303-49 = "同じグッズでも、お店ごとに値段が違ったりするから……。"
2005303-50 = "ちゃんと気を張って、見極めていかないと！"
2005303-51 = "まぁ、忍者グッ……じゃなくて忍具は、大体同じ値段なんだけどね。"
2005303-52 = "そもそも取り扱いが少ないから、比較対象が……。"
2005303-53 = "……ん？"
2005303-54 = "あぁっ、マトリョーシカ手裏剣！"
2005303-55 = "手裏剣の中に小さな手裏剣が入ってる、特殊な忍具！"
2005303-56 = "飛んできた手裏剣を避けても、#nまた別の手裏剣が現れる不可避の武器！"
2005303-57 = "「甲斐犬グルル」監督の作品で登場して以来、#nあちこちでオマージュされてるんだよ！"
2005303-58 = "あっ、こっちは……忍者用火炎煙幕弾！"
2005303-59 = "爆発させれば煙幕の代わりに炎が出て、#n視界を遮りながら攻撃ができるレアな忍具！"
2005303-60 = "[s] \"それはミサイルと同じでは……？\""
2005303-61 = "まぁまぁ、細かいことは気にしない気にしない。"
2005303-62 = "はっ、これは……古代忍者のホログラム巻物！？"
2005303-63 = "こんなものまで置いてあるの！？"
2005303-70 = "（こうして、ミチルとしばらく忍者グッ……忍具を見て回った）"
2005303-72 = "うにゃ～、楽しかったぁ。"
2005303-73 = "服の修理にお金を使っちゃったから、手裏剣しか買えなかったけどー……。 "
2005303-74 = "一緒に買い物ができて、楽しかったなぁ。"
2005303-75 = "……その、先生殿。"
2005303-76 = "……わがまま聞いてくれて、ありがと。"
2005303-77 = "[s] \"ううん、私も楽しかったから。\""
2005303-78 = "ほ、ほんとぉ……？"
2005303-79 = "ふふっ……ふふんっ！"
2005303-80 = "そ、そうだ……！"
2005303-81 = "これ、先生殿に！ "
2005303-82 = "[s] \"……カプセルトイ？\""
2005303-83 = "さっき回してきたの！"
2005303-84 = "何を隠そう、忍者カプセルトイ！"
2005303-85 = "まぁ中身が何かは分からないけど……。"
2005303-86 = "そのワクワクも含めてプレゼントってことで！"
2005303-87 = "さっ、開けてみよー！"
2005303-89 = "……えっ？"
2005303-92 = "[wa:1250]― [log=미치루 드레스]中身は……[wa:2300]指輪、[wa:1080]だね！？[/log]"
2005303-94 = "― [log=미치루 드레스]手裏剣の飾りがついてて、[wa:2440]良い感じ……[wa:1940]じゃん！？[/log]"
2005303-97 = "[ns] \"せっかくもらったし、つけてみようかな。\""
2005303-98 = "[wa:440]― [log=미치루 드레스]……[wa:890]え？[wa:1210]先生殿、[wa:1800]つけるの……？[/log]"
2005303-100 = "― [log=미치루 드레스]あ、[wa:1010]いや、[wa:960]いいんだけど……。[/log]"
2005303-103 = "[wa:1570]― [log=미치루 드레스]（あれ……？[wa:1250]指輪を、[wa:1180]相手に渡す……？）[/log]"
2005303-105 = "― [log=미치루 드레스]（これって……[wa:1420]告白、[wa:1540]みたいな――！？）[/log]"
2005303-108 = "[wa:380]― [log=미치루 드레스]ちょっ、[wa:400]ちょっと待って[wa:790]先生殿！[/log]"
2005303-110 = "― [log=미치루 드레스]別に[wa:480]狙ってたわけじゃなくて……！[wa:1890]でも、[wa:500]えっと……！[/log]"
2005303-113 = "[ns] \"ど、どうしたの！？\""
2005303-114 = "[wa:2040]― [log=미치루 드레스]うぅ……[wa:840]うああぁ～～っ！！[/log]"
2005303-117 = "っ……！"
2005303-118 = "あ、えっと……！"
2005303-119 = "う～～～、えぇいっ！"
2005303-120 = "ボンッ！"
2005303-121 = "[ns] \"……。\""
2005303-123 = "（煙が消えると、ミチルの姿はなくなっていた）"
2005303-124 = "（……手のひらには、カプセルトイだけが残っていた）"
