[translation]
2005203-1 = "事業計画書"
2005203-2 = "あのですね先生。"
2005203-3 = "[s] \"どうしたの？\""
2005203-4 = "シャーレの言葉は、キヴォトス全域に届きますよねぇ？"
2005203-5 = "[s] \"そりゃ、公的な扱いになるからね。\""
2005203-6 = "私、気づいたのです。"
2005203-7 = "これほど絶大な権力を持つインフルエンサーはそういない、と。"
2005203-8 = "[s] \"ヤクモの話、先生不安になるよ……。\""
2005203-9 = "聞いてください、先生。"
2005203-10 = "先生はご自身の発信力と影響力がもったいないとは思いませんか？"
2005203-11 = "先生が思わなくても、私が思うからそういうことなのです。"
2005203-12 = "例えばですが、シャーレの主導で全キヴォトスに「本を読もう」キャンペーンを展開してみるとか、いかがでしょう？"
2005203-13 = "[s] \"それはいいね！\""
2005203-14 = "そしてそこに、出版部特選図書を添えて……ムフフフ。"
2005203-15 = "[s] \"……自重してください、ヤクモさん。\""
2005203-16 = "ですが本のこととなれば、トリニティ図書館に圧倒されてしまう可能性も……。"
2005203-17 = "いえ、むしろこの機会に出版部の影響力を引き上げることができれば……逆転勝利も夢じゃない？"
2005203-18 = "真の事業家は、危機をチャンスに変えるもの……ならば……！"
2005203-22 = "……先生、出版部の後ろ盾になっていただけませんか？#n顧問とかなんか、そんな感じの。"
2005203-23 = "大義名分が必要でしたら……こういうのどうでしょう。酷寒の学園で苦しむ生徒の福祉のため、みたいな。"
2005203-24 = "[s] \"ダメ。\""
2005203-25 = "え〜どうしてですかぁ？"
2005203-26 = "[s] \"分かってるでしょう？\""
2005203-27 = "ちぇっ、憎き中立義務……。"
2005203-28 = "……じゃあ、他に何か……。"
2005203-29 = "シャーレ……D.U.……。"
2005203-30 = "キヴォトス公認の、政治的中立地帯……。"
2005203-31 = "つまりここでは、どの学園も自治権を主張できない……。"
2005203-32 = "ということは……レッドウィンター連邦学園の発言権の弱さも、シャーレでなら多少補強されて……。"
2005203-33 = "……それに今、ここに来ているレッドウィンター連邦学園の生徒は、他ではない私、[ruby=あらまき]荒槇[/ruby]ヤクモ……！"
2005203-37 = "先生。"
2005203-38 = "我がレッドウィンター連邦学園の非公式理念「平等」と「公平」のために……。"
2005203-39 = "全学園……いや、少なくとも「3大学園」に対して――"
2005203-40 = "レッドウィンターのプリン生産に力を貸すよう、「積極的に」働きかけていただけませんかねぇ？"
2005203-41 = "そしてちいさ～な文字で、出版部の協賛があったと明記していただきたいのです。"
2005203-42 = "これで慢性的なプリン供給不足を一時的にでも解消し、#n対外的にはレッドウィンターの名をあげ、内部的には――"
2005203-43 = "[s] \"却下！\""
2005203-47 = "どうしてですか！！"
2005203-48 = "……ふぅ……分かりましたよ……。"
2005203-49 = "……待て？今まで私はレッドウィンターに固執しすぎていた……？もしかすると、敗因はそこに……？"
2005203-50 = "……そうだ、シャーレの超法規的権限を存分に活用して……。"
2005203-51 = "……そんな目で見ないでくださいよ。今度こそ、みんなが得をするwin-winにしますってば。"
2005203-52 = "こういうのはどうでしょう？先生の超法規的権限は応急的に使われることが多かったと思いますが。"
2005203-53 = "この場合は、やはり「公益のため」と掲げて……。"
2005203-54 = "例えば、そうですねぇ……"
2005203-58 = "具体案はあとで工夫するとして。"
2005203-59 = "非の打ち所のない公共事業をシャーレの名で進めてみては？"
2005203-60 = "そこに我々出版部との協業があった事実だけ、公表していただければ――"
2005203-61 = "[s] \"ダメだからね。\""
2005203-62 = "そんなキッパリ断らなくてもぉ……。"
2005203-63 = "[s] \"にしても、よく思いつくね。\""
2005203-64 = "まあ、事業計画書の作成は私の趣味でもございますから。"
2005203-65 = "なんというか……可能性を膨らませる過程が、楽しくてですねぇ。"
2005203-66 = "それが脈アリでもナシでも……。"
2005203-67 = "あとは、鍛えられたとでも言いましょうか。"
2005203-68 = "交渉の場とは……ありったけのネタを総動員して！ラインギリギリまで膨らませて挑むものですから！"
2005203-69 = "相手がレッドウィンター事務局なら、なおのことです。"
2005203-70 = "「この事業がうまくいけば、今月のプリン配給量は2倍にできる」#nといった具合に……。"
2005203-71 = "[s] \"それでうまくいったことは？\""
2005203-75 = "ほぼないですけどぉ……。"
2005203-77 = "（その後、結局のところ大事なのは互いの信頼では？と会話をしながら）"
2005203-78 = "（改めてヤクモは饒舌だなあと感心しつつ……）"
2005203-79 = "（それなりに楽しく（？）仕事を片付けていった）"
