[translation]
2005405-1 = "同じ星空の下"
2005405-10 = "酔い止めです。"
2005405-101 = "[wa:1370]― [log=히마리 결전]私は、[wa:2000]そんな風に思うのです。[/log]"
2005405-103 = "― [log=히마리 결전]先生は、[wa:2010]どう思われますか？[/log]"
2005405-109 = "いかがでしたか？#n今日の……車椅子体験は。"
2005405-11 = "[s1] \"ありがとう。乗り物酔いしやすいから助かるよ。\"\n[s2] \"乗り物酔いに強い方だから大丈夫だよ。\""
2005405-110 = "[s3] \"本当に印象的だったよ。\"\n[s4] \"また乗せてほしいな。\""
2005405-113 = "あっ、えっ……。"
2005405-114 = "せ、先生から誘ってくださるだなんて……。"
2005405-115 = "……こほん。"
2005405-116 = "もういい時間です。"
2005405-117 = "他の方々が心配しないうちに帰るとしましょうか。"
2005405-12 = "ふふっ。何事にも万全を期す――それがライフスタッフたる私の役目ですから。"
2005405-120 = "（帰り道は安全運転そのものだった）"
2005405-13 = "もっと私を頼ってくださって良いのですよ？"
2005405-14 = "それでも「万が一」はありますから。"
2005405-15 = "せっかくの機会なのです。もしも具合を悪くされたらもったいないでしょう？"
2005405-2 = "[ns] \"どうにか今日も乗り切ったね……。\""
2005405-21 = "……それでは。"
2005405-22 = "性能体験テストを始めてもよろしいですか？"
2005405-23 = "[ns] \"いつでも！\""
2005405-26 = "[ns] \"うわああああ！\""
2005405-28 = "先生、いかがですか？"
2005405-29 = "[ns] \"このバイクとっても速いね！\""
2005405-30 = "車椅子です！"
2005405-31 = "[ns] \"この車椅子、バイクよりもずっと速い！！\""
2005405-32 = "さあ飛ばしますよ！#nもっと強く私の腰に掴まってください！"
2005405-33 = "先生が落ちて怪我でもしたら、私も困りますから！"
2005405-34 = "[ns] \"分かった！！！\""
2005405-41 = "すぅ……はぁ……。#nふふっ、すっきりしました。"
2005405-42 = "車椅子の乗り心地はいかがでしたか？"
2005405-43 = "ガタつきは少なく、急加速も急ブレーキもお手の物。"
2005405-44 = "全てのリミッターを解除すれば、時速100kmに到達するまで0.956秒しかかかりません。"
2005405-45 = "……とはいえ先生を乗せていますから。そこまで無茶な運転はしませんけれどね。"
2005405-46 = "[s] \"絶対に安全運転でお願いします！\""
2005405-47 = "もちろんです。挑戦的な運転は、夜な夜なテストのほうで行っていますので。"
2005405-48 = "……はい？夜遊びもほどほどに、と？"
2005405-49 = "……。"
2005405-5 = "ええ。もう夕食は召し上がりましたか？"
2005405-50 = "これはその……あれです。"
2005405-51 = "車椅子の性能テストを兼ねてはいますが……[ruby=・]偵[/ruby][ruby=・]察[/ruby]ということで、ここはひとつ。"
2005405-52 = "……いえ、先生の仰りたいことは理解しております。#nそれはトキやエイミの役割で、ドローンでもカバーできるものである、と。"
2005405-53 = "……。"
2005405-54 = "その……現場に任せきりだと感覚がズレてしまうのではありませんか？"
2005405-55 = "現場チームと分析チームの齟齬――それこそが誤った判断の温床なのですよ！"
2005405-56 = "[s] \"そっか……。\""
2005405-57 = "……などと言いましたが。"
2005405-58 = "ここでしか見られないものが、この場所、この時間帯にはあるのです。"
2005405-59 = "それはおそらく、ここの管理者が意識すらしていない副産物。"
2005405-6 = "[s] \"さっきね。そろそろ普通のご飯が恋しいかな……。\""
2005405-60 = "……いたって自然的なもの。世界の在り方とでも言いましょうか。"
2005405-61 = "何事にも明確な意図と結果がある……その考え方では、この世界をはかることはできません。"
2005405-62 = "だからこそ、占星術や数秘術、象徴主義は面白いのです。"
2005405-63 = "さりげなく、さりとて密やかに「世界の断片」を私たちに伝えてくれている――#nのかもしれませんから。"
2005405-64 = "とはいえこの場所では、私が研究してきた知識は通用しないでしょうけれど。"
2005405-65 = "[s] \"それはどうして？\""
2005405-66 = "「天の法則」が根本的に違うのです。"
2005405-67 = "星の位置も、動きも、それらが絡み合う数式も……。"
2005405-68 = "私たちにとっては、真新しい「空と大地」とでも言うべき場所ですから。"
2005405-69 = "もちろん、1から新しい占星術理論を構築するというのも良いでしょう。"
2005405-7 = "冷凍保存食をローテーションで食べていれば、さすがに飽きもきますよね……。"
2005405-70 = "白紙から始める理論づくりほど楽しいこともありませんし。"
2005405-71 = "ただ……そこまでの時間は与えられそうにないのが残念です。"
2005405-75 = "[wa:500]― [log=히마리 결전]不思議ですよね。[/log]"
2005405-77 = "― [log=히마리 결전]ミレニアムと変わらず、[wa:2080]ここでも夜空を見上げることはできるのに。[/log]"
2005405-8 = "不味くはないけれど、特別美味しくもない。そんなところでしょうか。"
2005405-80 = "[wa:2020]― [log=히마리 결전]瞬く星は、[wa:1890]私たちの知るものとは異なっていて。[/log]"
2005405-82 = "― [log=히마리 결전]どうにも言語化が難しい……[wa:3400]形容しがたい感覚です。[/log]"
2005405-85 = "[ns] \"でも私にはヒマリの方がずっと神秘的に見えるよ？\""
2005405-86 = "[wa:440]― [log=히마리 결전]はい……！？[/log]"
2005405-88 = "― [log=히마리 결전]あ、[wa:1480]ありがとうございます。[wa:2500]その……[wa:2330]褒め言葉として受け取っておきます。[/log]"
2005405-9 = "なんにせよ、すでに食事をされた後ということは、こちらを。"
2005405-91 = "[wa:1060]― [log=히마리 결전]……同じ夜空の下にいても。[/log]"
2005405-93 = "― [log=히마리 결전]互いが互いを理解できるとは限りません。[/log]"
2005405-96 = "[wa:520]― [log=히마리 결전]ですが少なくとも、[wa:2200]「同じ」夜空の下にいるのですから。[/log]"
2005405-98 = "― [log=히마리 결전]互いを理解するきっかけくらいには、[wa:2990]なるのではないでしょうか。[/log]"
