[translation]
2005003-1 = "こっちのほうが早いよ！"
2005003-2 = "シャーレ・オフィス"
2005003-3 = "（いつものように、仕事と格闘していたある日……）"
2005003-7 = "（誰か来た……？）"
2005003-8 = "[ns] \"開いてますよ～\""
2005003-10 = "[ns1] \"あれ、この音……。\"\n[ns2] \"ドアからじゃない……？\""
2005003-13 = "（窓のほうに視線を向けると……）"
2005003-14 = "[ns] \"……んん？\""
2005003-15 = "（リツが、窓の外にぶら下がっていた）"
2005003-16 = "[ns] \"リツ！？\""
2005003-17 = "先生先生！"
2005003-18 = "ここ閉まってる！割って入ってもいい？"
2005003-19 = "[s3] \"それ、防弾ガラスだから！\"\n[s4] \"待って！今開ける！\""
2005003-26 = "（急いで窓を開け、リツを中に入れた）"
2005003-28 = "じゃじゃーん！"
2005003-29 = "[ns] \"もしかして……壁を登ってきたの……？\""
2005003-30 = "うん！#nエレベーター来るの遅くてさ！"
2005003-31 = "[s] \"一応、階段もあるんだけど……。\""
2005003-32 = "うーん……？"
2005003-33 = "でも、壁を登ったほうが近くない？"
2005003-34 = "[s] \"そ、そうかもしれないけど……！\""
2005003-38 = "[ns] \"あれ、今日は当番じゃないよね？外出許可取ってきたの？\""
2005003-39 = "そそ！#n彫刻に使う大理石がなくて……って言ったらいけたんだ！"
2005003-40 = "ワイルドハントって、外出にすっごく厳しいけど……。"
2005003-41 = "芸術のことになると、#nちょっとだけオッケーをもらいやすいんだ！"
2005003-42 = "それで、大理石を買った帰りに、シャーレに寄ったの！"
2005003-43 = "[s] \"大理石って持ち帰れるんだ……。\""
2005003-44 = "うん！#n1階に置いといたよ。先生も見たい？持ってくる？"
2005003-45 = "[s] \"あ、あとで見に行くよ……！\""
2005003-46 = "あ！そうだそうだ！"
2005003-47 = "はい先生！これ！"
2005003-51 = "[ns] \"……シャツ？\""
2005003-52 = "こないだの彫刻のとき、先生粉だらけになっちゃったでしょ？"
2005003-53 = "そのせいで服も汚れちゃってたからさ……。"
2005003-54 = "衣装デザイン専攻の友達に、作ってもらったんだ！"
2005003-55 = "[s] \"ああ、それで好きな色の話を！\""
2005003-56 = "そそ！最初は先生の好きな色にしようかなーって#n思ったんだけど……。"
2005003-57 = "専門家におまかせもアリかなって！"
2005003-58 = "[s] \"透明とか言わなくてよかった……。\""
2005003-59 = "あ、スケスケがよかったの？"
2005003-60 = "[s5] \"いやいや！\"\n[s6] \"とにかくありがとう、リツ！\""
2005003-63 = "どういたしまして！ねね、いま着てみてよ！"
2005003-64 = "[s] \"わかった！じゃあ隣の部屋で着替えてく……。\""
2005003-73 = "[ns] \"……えっと、どうしたのリツ？\""
2005003-74 = "うん？何が～？"
2005003-75 = "[s] \"ついて来られると……脱げないのですが……。\""
2005003-76 = "……。"
2005003-77 = "あ、もしかして恥ずかしい？"
2005003-78 = "じゃ、ボクも作業服に着替えるよ！#n一緒に脱げば――"
2005003-79 = "[s] \"やめてください！\""
2005003-81 = "（その後、なんとか着替え終わって……）"
2005003-83 = "おお～"
2005003-84 = "どうかな？いい感じ？#n気に入ってくれた？"
2005003-85 = "[s] \"ピッタリだよ！さすがワイルドハント……！\""
2005003-86 = "うーん……。"
2005003-90 = "ちょっとイマイチかも！"
2005003-91 = "[s] \"そ、そんな……！\""
2005003-92 = "あ、先生にはよく似合ってるよ？"
2005003-93 = "ただ、今着てる服だと、ちょっとバランス悪いかも！"
2005003-94 = "[s] \"あ、ああ、そういうことね……！\""
2005003-95 = "まあ大丈夫大丈夫！"
2005003-96 = "今度一緒に、似合うやつ買いにいこ！"
