[translation]
2005302-1 = "忍者少女は治療を求む！"
2005302-2 = "百鬼夜行・第38旧校舎のとある教室"
2005302-3 = "（心配になって、ミチルの元へ向かった）"
2005302-6 = "せ、先生殿……！？"
2005302-7 = "本当に来たの！？"
2005302-8 = "[s] \"ミチル、大丈夫！？\""
2005302-9 = "あっ、い、いや～……。"
2005302-10 = "怪我って言っちゃったんだけどー……。"
2005302-11 = "……その、私じゃなくってぇ。"
2005302-12 = "[s] \"……？\""
2005302-13 = "えっと……私の服が、「怪我」しちゃったっていうか。"
2005302-14 = "……正確には、私のドレスが。"
2005302-15 = "こんな感じで、結構派手に……。"
2005302-16 = "[s] \"うわぁ……何があったの？\""
2005302-17 = "えっとぉ……。"
2005302-18 = "忍法「クヌギよじよじの術」を練習してたら、木から落っこちて……。"
2005302-19 = "[s1] \"つまり……。\"\n[s2] \"木登りしてたら、服をダメにしちゃったと。\""
2005302-22 = "まとめ方ぁ！？"
2005302-23 = "それじゃ私がはしゃぎすぎて、服を破っちゃったみたいじゃん！？"
2005302-24 = "……ま、間違ってはいないけどさぁ。"
2005302-25 = "……あ、遊んでたわけじゃないからね！？#nあくまで訓練！"
2005302-26 = "むぅぅ……。"
2005302-27 = "……先生殿はやっぱり、まだちょーっと忍者への理解が浅いかも！"
2005302-28 = "というわけで！"
2005302-29 = "お直し屋さんに向かいながら、忍者講義をして進ぜよう！"
2005302-31 = "（こうしてミチルと、お直し屋さんへ向かうことになった）"
2005302-33 = "百鬼夜行商店街"
2005302-35 = "……つまり忍者は、黒以外の服も着るってこと！"
2005302-36 = "顔まで覆う黒い装束は、あくまで夜に使うやつでー。"
2005302-37 = "昼は逆に目立つから、普通の服を着ることが多いってわけ。"
2005302-38 = "忍者の基本は、「目立たないこと」……。"
2005302-39 = "その場その場に、ふさわしい格好をすべし！"
2005302-40 = "例えばー、パーティ会場での任務だったら、こんな風にドレスを着たり……。"
2005302-41 = "もちろん、それが夜だったら黒でも良いんだけどねー。"
2005302-42 = "ある忍者はカモフラージュのために、服を着ず、墨を身体に塗ったこともあったとか……。"
2005302-43 = "あと最近は、光学迷彩忍者服なーんてものまで――"
2005302-53 = "[ns] \"あれ、ここじゃない？\""
2005302-54 = "……おっと！"
2005302-55 = "いらっしゃいませ～"
2005302-56 = "えぇっと、破れたドレスのお直しをお願いしたくってぇ……。"
2005302-57 = "はい、分かりました。#nお預かりしてもよろしいですか？"
2005302-58 = "はーい……。"
2005302-62 = "……あっ。"
2005302-64 = "今、まさに着ちゃってるじゃん！？"
2005302-66 = "えっと、お着替えはお持ちですか？"
2005302-67 = "……持ってない、です。"
2005302-68 = "あの、服を着たまま直す方法とかはー……。"
2005302-69 = "ミシンなので、シンプルに危ないですね……。"
2005302-70 = "ですよねぇ……。"
2005302-71 = "もうっ、せっかくここまで来たのにぃ……！"
2005302-72 = "うう、一応、方法がないわけでは……。"
2005302-73 = "忍者服に着替えれば……！"
2005302-74 = "[s] \"着替えはないって言ってなかった？\" "
2005302-75 = "大丈夫大丈夫！"
2005302-76 = "伝承の中のある忍者みたいに、墨を塗ればいいんだよ！"
2005302-77 = "[s] \"……それ、大丈夫なの？\" "
2005302-78 = "ふふ、忍者だからその程度……。"
2005302-79 = "……。"
2005302-83 = "だ、ダメだよそんなの！ "
2005302-84 = "絶対にダメ！ "
2005302-85 = "せ……。"
2005302-86 = "先生殿の変態！！"
2005302-87 = "[s3] \"えっ私！？\" \n[s4] \"濡れ衣だ……！\""
2005302-91 = "（その後ミチルは近くで買った運動着に着替え、ドレスを預けたのだった）"
2005302-92 = "（……代金は私が支払った）"
