[translation]
2005106-1 = "偉いね、レイサ"
2005106-3 = "先生、ここです！"
2005106-4 = "[s] \"いらっしゃい、レイサ！\""
2005106-5 = "ふっふっふっ……「[ruby=うざわ]宇沢[/ruby]レイサ」……。"
2005106-6 = "たしかに、そう名乗っていた頃もありましたね……。"
2005106-7 = "[s] \"えっ？\""
2005106-8 = "今の私は……「テルミットピンク」！です！"
2005106-9 = "[s] \"ついに……覚醒したのか！？\""
2005106-10 = "わっはっはっは！"
2005106-14 = "……くぅ。"
2005106-15 = "二度も服に閉じ込められるなんて……。"
2005106-16 = "自分に呆れました……。"
2005106-17 = "[s] \"せっかくだし、魔法少女を楽しもうよ！\""
2005106-18 = "たしかに、好きな服を着られるのは、嬉しいです！"
2005106-19 = "でも、もうパトロールの時間なんですよ！"
2005106-20 = "出かける前の、ちょっとした気分転換のつもりが……。"
2005106-21 = "こんなことになるなんて……！"
2005106-22 = "早く着替えて、パトロールに行かなきゃ……。"
2005106-27 = "おいてめぇどうしてくれんだァ？ああん？"
2005106-28 = "いってぇぇ！あー、こりゃ肩外れてんなぁ！"
2005106-29 = "そ、そんな！少しぶつかっただけじゃないですか！"
2005106-30 = "ケガさせといてなんだその態度は！？"
2005106-31 = "入院費はてめぇの財布からもらってくからな～"
2005106-32 = "や、やめてください！"
2005106-37 = "そこまでです！"
2005106-42 = "あん？なんだその服？"
2005106-43 = "お姫様ごっこか？"
2005106-49 = "それとも妖精さんごっこか？"
2005106-55 = "今取り込み中なんだよ！あっち行きな！"
2005106-61 = "うああっ！か、肩がぁ！！"
2005106-62 = "本当に折れたかもしれねぇ！！"
2005106-64 = "今すぐ謝ってください！"
2005106-66 = "ぐ、ぐうぅ……。#nご、ごめんなさい！当たり屋でごめんなさい！"
2005106-67 = "あ、ええと……は、はい……。"
2005106-69 = "もう二つ、謝ってください！#nお姫様とか妖精さんって言ったことも！"
2005106-70 = "そ、そっちも！？"
2005106-72 = "ああ……！うちのふわ助が！"
2005106-73 = "うちの可愛いふわ助が、木の上に……！"
2005106-74 = "なるほど！"
2005106-75 = "今度は木から降りられなくなった猫ちゃんですね！"
2005106-76 = "出動です！"
2005106-82 = "よいしょ！"
2005106-83 = "猫ちゃんじゃなくて、ドローンが枝に引っかかってました。"
2005106-84 = "ああ、ふわ助！怖かったよな……！"
2005106-85 = "ふわ助を助けてくださり、ありがとうございます！"
2005106-86 = "？？？"
2005106-88 = "誰か！助けてください！"
2005106-89 = "参ります！"
2005106-91 = "今日は立て続けに事件が起きましたね。"
2005106-92 = "着替える暇もありませんでした。"
2005106-93 = "[s] \"やっと落ち着いたね、お疲れ様。\""
2005106-94 = "ふふ、私は自警団のエースですから！"
2005106-95 = "では、そろそろ帰り――"
2005106-100 = "うわぁ～ん！私の凧が～！"
2005106-101 = "川に落ちちゃう～！"
2005106-102 = "工作の宿題で頑張ってつくったのに～！うわぁ～ん！"
2005106-103 = "！！"
2005106-104 = "あの子の努力の結晶を守らないと！"
2005106-105 = "いきます！！！！！"
2005106-112 = "[wa:1950]― [log=레이사 매지컬]セーフッ！[/log]"
2005106-115 = "― [log=레이사 매지컬]ふふ……[wa:1500]凧の平和は[wa:928]守られました！[/log]"
2005106-117 = "― [log=레이사 매지컬]水に落ちる寸前に！[wa:1930]こうやって捕まえられたのですから！[/log]"
2005106-120 = "[ns] \"レイサ、大丈夫？\""
2005106-122 = "[wa:540]― [log=레이사 매지컬]みんなのためでしたら、[wa:1280]自警団は[wa:720]迷いません！[/log]"
2005106-125 = "― [log=레이사 매지컬]火の中だろうと、[wa:1270]水の中だろうと！[/log]"
2005106-127 = "― [log=레이사 매지컬]どこだって[wa:760]飛び込んでみせますから！[wa:1690]にへへ……っ！[/log]"
2005106-130 = "[ns] \"早くあがって！風邪ひいちゃう！\""
2005106-131 = "[wa:570]― [log=레이사 매지컬]ヒーローの[wa:630]衣装というのは――[/log]"
2005106-133 = "― [log=레이사 매지컬]ヒーローとしての[wa:650]仕事をするときにこそ[wa:1800]輝くものっ！[/log]"
2005106-136 = "― [log=레이사 매지컬]あと、[wa:730]これは洗濯機オッケーなので[wa:1560]大丈夫です！[/log]"
2005106-139 = "[wa:1736]― [log=레이사 매지컬]それに……[wa:1675]先生に、[wa:400]教わりましたから。[/log]"
2005106-141 = "― [log=레이사 매지컬]迷わない者こそ――[wa:1780]みんなを守ることができる、[wa:1530]と！[wa:1030]えへへっ！[/log]"
2005106-144 = "[wa:380]― [log=레이사 매지컬]へへ、[wa:790]え、[wa:290]へえっ……。[/log]"
2005106-146 = "― [log=레이사 매지컬]へくしょん！！[/log]"
2005106-149 = "― [log=레이사 매지컬]ううぅ……。[/log]"
2005106-152 = "（その後、頑張ったレイサをシャーレに連れて戻り……）"
2005106-153 = "（シャワーを使ってもらい、ゆっくり休ませた）"
