[translation]
2005002-1 = "岩がしゃべった！"
2005002-2 = "シャーレ・オフィス"
2005002-3 = "（翌日）"
2005002-7 = "（約束の時間から30分経っても……）"
2005002-8 = "（リツが来る気配はなく……）"
2005002-9 = "[ns] \"電話にも出ない……。\""
2005002-10 = "（心配で、ソワソワしていると……）"
2005002-14 = "[ns] \"……リツ？\""
2005002-15 = "（窓の外にリツの姿があった）"
2005002-16 = "（庭の岩の前でリツが何かしている……？）"
2005002-17 = "[ns] \"……何してるんだろう？\""
2005002-20 = "シャーレ・前庭"
2005002-21 = "（1階に降りた瞬間、目に入ったのは……）"
2005002-22 = "（リツが、自分の身体よりも大きな岩をノミとハンマーで削っていた）"
2005002-23 = "[ns] \"えっと、これは……？\""
2005002-25 = "あっ！先生！"
2005002-26 = "やっほ～！"
2005002-27 = "……あっ、そうだ！#nボク、今日当番だったね！"
2005002-28 = "[ns1] \"心配したよ、リツ！\"\n[ns2] \"それは彫刻をしてる……の？\""
2005002-31 = "うんっ！#nこの岩にお願いされたんだ！"
2005002-32 = "[s] \"岩がお願い……？\""
2005002-33 = "そう！岩の中には、いろんな形をした子が隠れててさ――"
2005002-34 = "この岩は「ボクの中にはキレイな子が隠れてるんだよ～」って教えてくれたんだ。"
2005002-35 = "だから……。"
2005002-36 = "壊してるんだ！"
2005002-37 = "[s] \"なんで！？\""
2005002-38 = "じゃなきゃ、出してあげられないもん。"
2005002-39 = "ゴツゴツした岩の中に隠れてる、この子をね。"
2005002-40 = "[ns3] \"なるほど……！\"\n[ns4] \"そういうことか……！\""
2005002-43 = "[ns] \"ところで……これ、校則上大丈夫なの？\""
2005002-44 = "別に大丈夫じゃないよ？"
2005002-45 = "……。"
2005002-46 = "ところでね、先生！"
2005002-47 = "[s] \"誤魔化した！？\""
2005002-53 = "肩車してくれる？"
2005002-54 = "[s] \"……もう乗ってない？\""
2005002-55 = "わ、高い！"
2005002-56 = "へへ……ボク、ちっちゃいからね。#n上のほうまで手が届かなかったんだ！"
2005002-57 = "これで削れるよ！ありがとね、先生！"
2005002-60 = "（そうしてリツは肩に乗ったまま岩を削り続け……）"
2005002-61 = "（……その下には大量の岩粉が降ってきた）"
2005002-65 = "ふぅ、あともう少し！"
2005002-66 = "最後はこのへんを整えて……あれ？"
2005002-67 = "ええっ！先生大丈夫？#n顔が粉だらけ！"
2005002-68 = "[s] \"ら、らいじょうぶ……ぷはっ！\""
2005002-69 = "ど、どうしよう？"
2005002-70 = "そうだ！逆向きで肩車してもらえば――"
2005002-71 = "先生の顔に粉がつかないよね！"
2005002-72 = "[s] \"それだとリツのお腹が私の顔に……やめとこう！\""
2005002-73 = "そう？いいかなーって思ったんだけど。"
2005002-74 = "じゃ、続けるね！"
2005002-77 = "（彫刻は順調に進み……）"
2005002-79 = "よし！完成！"
2005002-80 = "[s] \"お疲れ様、リツ。\""
2005002-81 = "ありがとうございます、先生！へへっ。"
2005002-82 = "[s5] \"この彫像は……。\"\n[s6] \"なんて言えばいいんだろう……。\""
2005002-85 = "先生、感想に困ってる？"
2005002-86 = "それなら大丈夫！"
2005002-87 = "[s] \"えっ？\""
2005002-88 = "初めて見た作品の感想をその場で言うって……。"
2005002-89 = "難しくない？"
2005002-90 = "どんな角度でその作品を解釈すればいいのか分からないし……#nその言葉が本当に適切なのかも判断つかないし。"
2005002-91 = "作者の前だと、気をつかっちゃうこともあるよね。"
2005002-92 = "だからね、これからこの彫刻のことで、#nふわーって言葉が浮かんでくることがあったら……。"
2005002-93 = "そのときは聞かせてよ！"
2005002-94 = "[s] \"わかったよ。ありがとう、リツ。\""
2005002-95 = "これどうしよっか？先生の部屋まで持ってく？"
2005002-96 = "[s] \"それもいいけど……。\""
2005002-100 = "[ns7] \"たくさんの人に見てもらえるように――\"\n[ns8] \"ここに置いておきたいかな。\""
2005002-103 = "あ……。"
2005002-104 = "……ありがと、なんだか胸がいっぱい！"
2005002-105 = "先生のおかげで、とってもいい日になったよ！"
2005002-106 = "[s9] \"今日を締めくくるのは、まだ早いかな。\"\n[s10] \"これから当番の仕事が待ってるんだし……！\""
2005002-109 = "……えっ。"
2005002-110 = "[s] \"いざ、お仕事の世界へ！\""
2005002-111 = "ふえん……！"
2005002-113 = "（その後、当番のリツと仕事を片付けていき、#n夕方頃には終えることができた）"
