[translation]
2005205-1 = "タイムテーブル"
2005205-10 = "このボロボロインフラ、なんとかならないものですかねぇ……。"
2005205-101 = "どうです？駅弁ってすごいと思いませんか！"
2005205-102 = "[s] \"うん！全部買おう！\""
2005205-103 = "えっ？"
2005205-104 = "全部、ですか？"
2005205-105 = "そのために選んだんじゃないのか、って……。"
2005205-106 = "間違ってはないんですけど……。"
2005205-107 = "そんなに快く応じてくださるなんて……。"
2005205-108 = "[s] \"ヤクモはよく食べる年頃だしね。\""
2005205-109 = "……。"
2005205-11 = "学園の循環列車が定刻についたためしがないんです……。"
2005205-113 = "いくつか戻してきますねぇ。"
2005205-114 = "意外、ですか？"
2005205-115 = "まあ……。"
2005205-116 = "図々しさにも、程度というものがありますのでねぇ。"
2005205-117 = "それに、全部買ったところで食べ切れません。#n捨てることになったら、もったいないじゃないですか～"
2005205-12 = "……もう我慢の限界です、先生。"
2005205-13 = "私[ruby=あらまき]荒槇[/ruby]ヤクモ、決心がつきました。"
2005205-139 = "[ns] \"列車の旅、どうだった？\""
2005205-14 = "[s] \"その決心、怖いよ……。\""
2005205-140 = "そうですねぇ……まだ夢のなかにいるような気持ちですが……一つ、確実に言えることは――"
2005205-141 = "レッドウィンターは枕木から見直さなければなりませんねぇ。"
2005205-142 = "[s] \"それは大事だよね。\""
2005205-143 = "枕木が不安定ですと振動も騒音も酷くなりますし、"
2005205-144 = "何より、列車がちゃんとスピードを出せなくなりますから。"
2005205-145 = "しかし枕木の交換となると結局、線路も再整備することになって……。"
2005205-146 = "レッドウィンターの広さを考えたとき……。"
2005205-147 = "敷地の果てから果てまでの横断鉄道は……。"
2005205-15 = "なんですかその反応。別にとって食べたりしませんよぉ？"
2005205-151 = "……。"
2005205-152 = "はぁ。"
2005205-153 = "大変な事業になりそうですが、それでも私はいつか、レッドウィンターにまともな路線が敷かれるところが見たいです。"
2005205-154 = "[s5] \"鉄道路線に興味あるんだね。\"\n[s6] \"運行図表とか作ってみたら？\""
2005205-157 = "えっ、つまりはダイヤ作成ですよね？それは勘弁です。"
2005205-158 = "そんなの、引き受けた暁には色んなところからこき使われることになりますよ？"
2005205-159 = "出版事業ができなくなるじゃないですか！"
2005205-16 = "すべての変化には、「ビジョン」が必要。"
2005205-160 = "興味あるのは路線の分析だけです！できれば受け身で！"
2005205-161 = "そもそも興味をもったキッカケと言えば、本を鉄道輸送することになったからですし。"
2005205-162 = "[s] \"そっか。常に出版部のことを思ってるんだね。\""
2005205-163 = "ええ。伊達に出版部部長、やってませんから。"
2005205-164 = "ムフフ。"
2005205-17 = "レッドウィンターの鉄道インフラを変えるためには、#n模範となるような鉄道運営……。"
2005205-18 = "少なくとも、定時に到着し定時に発車するという事例を、身をもって学ばなければなりません！"
2005205-19 = "[s] \"まともな話だ！\""
2005205-20 = "ムフフ。"
2005205-21 = "それで、これから何をするかと言いますと……。"
2005205-22 = "私はレッドウィンターの外――"
2005205-23 = "D.U.の鉄道を中心に乗車体験をし、路線と時刻表を分析します！"
2005205-24 = "先生も調査顧問として、同行お願いしますねぇ～"
2005205-25 = "[s] \"そうなるのか……。\""
2005205-26 = "おっと？これは生徒の教育に関わる業務ですよ～？"
2005205-27 = "経緯書さえちゃんと出せば、予算だって下りるはずです。"
2005205-28 = "ああ、「その手」の書類が必要でしたらお気軽にご相談ください。いつでもお手伝いしますのでぇ。"
2005205-29 = "ムフフフ。"
2005205-31 = "（……書類のことはさておき、）"
2005205-32 = "（鉄道の調査は必要な気がして、1日乗車券を2枚購入した）"
2005205-35 = "なるほど、まずは地下鉄からですか……。"
2005205-36 = "地下鉄というのは定時到着、定時出発が確立してますよねぇ。"
2005205-37 = "まあ、これもこれで趣があるし良いでしょう。"
2005205-4 = "[ns] \"……。\""
2005205-41 = "では今日の列車ツアー、よろしくお願いします～"
2005205-42 = "ムフフ。"
2005205-49 = "……規則的な揺れにレールの音。防音設備のおかげで、比較的穏やかに聞こえるというか……心地良いですねぇ……。"
2005205-5 = "……。"
2005205-50 = "地下鉄に乗ると眠くなる人の気持ちが……#nとても分かります……。"
2005205-51 = "……。"
2005205-52 = "すやぁ……。"
2005205-57 = "おお、立派な駅ですねぇ。#nきれいな設備に、利用客がこんなに大勢いて……！"
2005205-58 = "ほぉ、キヴォトス各地に繋がる高速鉄道の路線もここを通る、と。線路だけで32線……なるほどなるほどぉ。"
2005205-59 = "ここで問題です先生。主要駅と呼ばれる駅に来たとき、私たちが取るべき行動はなんでしょう～？"
2005205-6 = "[s1] \"列車……全然こないね……。\"\n[s2] \"もう1時間くらい待ったけど……。\""
2005205-60 = "[s3] \"えっと……路線を間違えないようにする？\"\n[s4] \"時刻表をしっかり確認する？\""
2005205-63 = "それも大事ですが……。"
2005205-64 = "正解は列車の旅の花！駅弁選びです！"
2005205-65 = "[s] \"そ、そっか……。\""
2005205-66 = "リアクションが薄いですねぇ。花より団子って言うじゃないですか。"
2005205-67 = "時刻表通りであれば、発車まであと40分あります。"
2005205-68 = "ムフフ。ゆっくり駅弁が選べそうですねぇ、行きましょう。"
2005205-73 = "おお、これは名物のタコ壺弁当ですねぇ。"
2005205-74 = "アナゴの煮つけ、野菜を添えたご飯、それからタコの天ぷら……。"
2005205-75 = "お弁当容器が本物の壺、というのがポイントなんです。"
2005205-76 = "おかげで少し重くはありますが、そこは仕方ないとして。"
2005205-77 = "タコ漁に使う壺に商品性を与えたところは、実に見事ですねぇ。"
2005205-81 = "牛丼弁当ですか。"
2005205-82 = "定番メニューには、そこでしか味わえない風情があるのです。"
2005205-83 = "醤油で味付けした牛肉と、野菜の煮物に卵焼き。紅生姜も欠かせませんよね。"
2005205-84 = "車内で食べることを考慮して、紅生姜には消臭処理をしてあるようです。"
2005205-85 = "こういった細やかな心配りこそ、売り上げに一番寄与していると思いませんか？"
2005205-89 = "これは列車型の弁当！"
2005205-9 = "身内を悪く言うのはよくないんですが。"
2005205-90 = "弁当容器が列車の形になってるんです。"
2005205-91 = "中身はおにぎりに唐揚げ、ソーセージといったシンプルなラインナップですが……。"
2005205-92 = "容器までお土産にできるなんて、得しかないですねぇ～"
2005205-95 = "こちらのアイスも有名ですよ。"
2005205-96 = "有名になったわけ？それは……。"
2005205-97 = "……カチカチに凍りすぎて、数分間は食べれないことで有名だとか。"
2005205-98 = "硬さのあまりスプーンでは到底すくえず、振り下ろしたハンマーが跳ね返ったという伝説もあるみたいですねぇ……。"
