[translation]
2005005-1 = "ひとりはダメ！"
2005005-2 = "シャーレ・正門"
2005005-3 = "わっ！はやーい！"
2005005-4 = "[s] \"こんにちは、リツ！\""
2005005-5 = "でも先生、忙しいんじゃないの？"
2005005-6 = "[s1] \"……大人はね。\"\n[s2] \"仕事から逃げるチャンスを、見逃がさないんだ。\""
2005005-9 = "あっ！ボク、それ知ってる！"
2005005-10 = "えーっと、「職務怠慢」って言うんじゃない？"
2005005-11 = "[s] \"うぐぅ……！\""
2005005-12 = "でも、ボクと出かけてくれるんだよね？"
2005005-13 = "なら、職務怠慢の先生でもおっけー！"
2005005-14 = "んじゃ、しゅっぱーつ！ボクの「シマ」に案内するよ！"
2005005-19 = "（リツに手を引かれ、商店街へ向かった）"
2005005-21 = "洋服商店街"
2005005-22 = "とうちゃーく！"
2005005-23 = "普段着から勝負服まで、ぜ～んぶここに揃ってるんだ！"
2005005-24 = "[s] \"ファッションの街なんだね！\""
2005005-25 = "あそこの角のお店はね、先生の好きなスケスケのやつも売ってるから！"
2005005-26 = "[s3] \"好きじゃないってば！\"\n[s4] \"あと、需要あるの！？\""
2005005-29 = "あはは！じゃあこっちから回ろっか！"
2005005-30 = "お買い得な服、見つけに行こ～！"
2005005-38 = "（そうして、リツと服屋を見て回った）"
2005005-39 = "（時々、リツは尖ったデザインの服を勧めてきたけど……）"
2005005-40 = "（なんだかんだで、ちょうど良い服が手に入った）"
2005005-42 = "ブラックマーケット・入り口"
2005005-43 = "いや～、いい買い物ができたよ！"
2005005-44 = "先生はどう？"
2005005-45 = "[s] \"ふっ……私にもファッション革命が来たかも。\""
2005005-46 = "へへっ、誘ってよかった！"
2005005-47 = "ね、先生、ちょっとここで待っててくれる？"
2005005-48 = "[s] \"もしかして、「輸入」？\""
2005005-52 = "先生はなんでも分かっちゃうんだなぁ～"
2005005-53 = "ちょっと行ってくるね！"
2005005-58 = "[ns] （……待ってる間、ぶらぶらしてようかな）"
2005005-60 = "[ns] （こっちの路地は……雰囲気が違うな……）"
2005005-62 = "らっしゃい！お客さん、なんかお探し？"
2005005-63 = "[s] \"えっと、アウターを……。\""
2005005-64 = "ドンピシャのタイミング！#nちょうど今、入荷仕立てのやつがあってさ！"
2005005-68 = "これ、どう？一目ぼれしたでしょ？着てみたいよね？#nはい、試着はこちら～"
2005005-69 = "[s] \"あの……もう少し見てから……。\""
2005005-70 = "いやいや、ほかを見たって時間の無駄だよ！#nこれがピッタリ！オレたちの仲だろ？オレのこと、信じるよな？"
2005005-71 = "[s] \"……初対面です。\""
2005005-72 = "ま～着てみろって！"
2005005-76 = "くぅ～！やっぱりオレの目に狂いはない！もはやオーダーメイド！#nお客さんのために生まれた服だよ、これは！"
2005005-77 = "[s] \"……袖が長すぎますけど。\""
2005005-78 = "心配ご無用！あそこの直し屋さんです～ぐ切ってくるよ！#nちょっと待ってな！"
2005005-79 = "[s] \"いや、まだ買うと決めたわけでは……。\""
2005005-80 = "おいおい、いまさら何言ってんだよ！一期一会って言うだろ？#nここで逃したら二度と手に入らないぞ？"
2005005-81 = "何してるの？"
2005005-85 = "はっ……！あ、姉御！？"
2005005-86 = "また押し売り～？"
2005005-87 = "そ、そんな滅相もない！#nこ、この方のご希望の服がなく、次回ご案内するとお伝えしていて！"
2005005-88 = "そうだったんだ！じゃ、先生はもらってくね～"
2005005-89 = "はいっ！気をつけておかえりくださいっ！"
2005005-94 = "こっち側はちょっと危ないんだよね～"
2005005-95 = "[s] \"リツって……姉御って呼ばれてるんだ……。\""
2005005-96 = "へへ。"
2005005-97 = "ひとりにしちゃってごめんね？#nこれからはボクがちゃ～んとくっついてるから！"
2005005-98 = "それなら安心でしょ？"
