[translation]
2005406-1 = "ライフスタッフ（２）"
2005406-4 = "面目ございません……。"
2005406-5 = "[s1] \"気にしないで。すごく疲れてたんだね。\"\n[s2] \"誰だって寝坊することくらいあるよ。\""
2005406-8 = "ですが、とりわけ気を張っていなければならないこの状況で……。"
2005406-9 = "これでは先生のライフスタッフ失格です……。"
2005406-10 = "はい？あまり自分を責めないで、ですか？"
2005406-11 = "先生が私を頼りすぎていたから？いえ、そんなことは……。"
2005406-12 = "でも、それでも……。"
2005406-13 = "[s3] \"よし、分かった。\"\n[s4] \"今日は私がヒマリのライフスタッフになるよ！\""
2005406-16 = "……はい？"
2005406-17 = "先生が、私の……？"
2005406-18 = "ですがそれは……！"
2005406-19 = "え？ええ、まあ、普段から皆さんに助けてもらってはいますが……。"
2005406-20 = "エイミは言わずもがな、最近はトキにも……。"
2005406-21 = "とはいえ先生に手伝ってもらうというのは……ちょっと違うといいますか……。"
2005406-22 = "[s] \"そっか、無理強いは良くないもんね。\""
2005406-23 = "い、いえ！そんなことはありません！むしろ……！"
2005406-24 = "むしろ……。"
2005406-25 = "う、うぅぅ……。"
2005406-30 = "（言葉にできないほど嬉しいのですが……）"
2005406-31 = "（同じくらい恥ずかしくもあって……！）"
2005406-36 = "[ns5] \"ヒマリはいつも頑張ってるから、たまには甘えてもいいんだよ。\"\n[ns6] \"私でよければなんでも言って！\""
2005406-41 = "そういうことは、あまり軽々しく言わないほうがいいですよ？"
2005406-42 = "……私だから良かったですが。"
2005406-43 = "それこそリオにでも気を許したら……。"
2005406-44 = "ものすごく面倒なことになりますからね？"
2005406-45 = "[s] \"それはそれで、まぁ……。\""
2005406-46 = "はいっ！？"
2005406-47 = "先生は生徒にどれだけ迷惑をかけられても良い……ということですか？"
2005406-48 = "あなたという人は……。"
2005406-49 = "そういうことを何度も言わないでください！"
2005406-50 = "しかもそれを無自覚に……私の忍耐力を試さないでいただきたいです。"
2005406-51 = "私だって、やろうと思えば……。"
2005406-52 = "[ns] \"ヒマリ？\""
2005406-55 = "な、何でもありません！何でもないですとも！"
2005406-56 = "こほん。"
2005406-57 = "では、先生がそこまでおっしゃるなら……。"
2005406-58 = "今日は目いっぱい甘えさせていただこうかと。よろしいのですね？"
2005406-59 = "[s7] \"いいよ。いくらでもどうぞ。\"\n[s8] \"その[ruby=チャレンジ]挑戦[/ruby]、受けて立とう！\""
2005406-62 = "ふふふ……。"
2005406-63 = "覚悟してくださいね？"
2005406-64 = "（こうしてヒマリを甘やかす時間が始まった）"
2005406-67 = "手を洗いたいですね。#n洗面所はすぐそこですが――"
2005406-68 = "誰かが私を「お姫様だっこ」して連れて行ってくれたら、どれほど良いか……。"
2005406-69 = "[ns] \"へ、へいっ！\""
2005406-75 = "（その瞬間……ヒマリの温かい息が耳元をかすめた）"
2005406-76 = "[ns] \"！？！？\""
2005406-77 = "あら。そんなにびっくりすることですか？"
2005406-78 = "生きていく上で、呼吸は自然なことですよ？"
2005406-80 = "（間違ってはいないけど、と反論したい気持ちを抑えた）"
2005406-81 = "（平常心を保つ努力をしながら、ヒマリの我がままに応え続けた）"
2005406-87 = "……。"
2005406-88 = "（心臓が破裂するかと思いました……）"
2005406-89 = "（まさかこんなにも緊張するとは……）"
2005406-90 = "（これほど恥ずかしいことだったなんて……！）"
2005406-93 = "どうしましょう……腕に力が入らなくなってしまいました。"
2005406-94 = "だというのに、小腹が空いてきましたね……。"
2005406-95 = "冷蔵庫に入れてあるチョコブラウニー……誰か食べさせてくれませんかね～？"
2005406-99 = "先生、ありがとうございます。"
2005406-100 = "では……。"
2005406-104 = "[ns] \"！？！？！？\""
2005406-105 = "ふふっ。どうかしましたか、先生？"
2005406-106 = "思いのほか美味しそうだったので――"
2005406-107 = "ちょっと前のめりに「ぱくっ」と味見しただけですよ。"
2005406-108 = "[s] \"そ、そんなに食べたかったんだね……。\""
2005406-113 = "（顔から火が出そうです……！）"
2005406-114 = "（先生の顔がこんなに近くに！）"
2005406-115 = "（いえ、近づいたのは私なのですが、それでも……！）"
2005406-116 = "……。"
2005406-117 = "（それにしても……これほどの美少女が迫ったのですよ？#n先生はなんとも思わなかったのでしょうか？）"
2005406-121 = "（……もしかして、だからこそ？）"
2005406-122 = "……。"
2005406-123 = "（急に距離を詰めすぎると逆効果なのでは……？）"
2005406-124 = "（言うなれば、触媒を入れ過ぎたときのような……）"
2005406-125 = "（結果が早く出る代わりに、不要な副産物が生成されたり、全体の安定性が下がったりしますからね）"
2005406-126 = "（急いては事を仕損じる、とはよく言ったものです）"
2005406-127 = "（このようなミスをするとは……反省ですね）"
2005406-130 = "あら。いつの間にかもう夜ですね。"
2005406-131 = "[s] \"えっ？もうそんな時間！？\""
2005406-132 = "ええ。ここは昼と夜の区別がはっきりしませんから。#nどうしても時間感覚がぼやけてしまいますね。"
2005406-133 = "なにより、「特異現象」がリアルタイムで発生している場所ですし。"
2005406-134 = "そのせいで生活習慣が乱れていて……なかなか寝つけないので、隣で寝かしつけてくれる人がいると嬉しいんですけどね。"
2005406-135 = "[s] \"それって本当に効果あるの！？\""
2005406-136 = "あら？"
2005406-137 = "先生は私のことを信じてくださらないのですか？#n私は世界の誰よりも先生を信じているというのに。"
2005406-138 = "[s] \"……！！\""
2005406-140 = "[ns9] \"そっか、そうだよね。\"\n[ns10] \"ヒマリのライフスタッフとして信じるよ。\""
2005406-144 = "（ヒマリを寝かしつけるため、ベッドに連れて行った）"
2005406-145 = "（そのとき……！）"
2005406-146 = "えいっ♪"
2005406-151 = "[ns] \"ヒマリ！？\""
2005406-152 = "先生？寝かしつけてくださるんですよね？"
2005406-153 = "私はですね～寝つけない時は、誰かがそばにいてくれないとダメなんです〜"
2005406-154 = "はい？エイミやトキにもやってもらっているのか、ですか？"
2005406-158 = "（……いいえ。そこまでのことは）"
2005406-159 = "（エイミがそばにいたら熱中症になりそうですし。ですが……）"
2005406-164 = "ええ、今日みたいに全然眠くない時は、特にそうかもしれません。"
2005406-165 = "（ごめんなさい、先生）"
2005406-166 = "（もう少しだけ……甘えさせてください）"
2005406-167 = "[ns11] \"分かったよ。\"\n[ns12] \"でも、横にいるのは寝るまでだからね？\""
2005406-170 = "はい！もちろんです！"
2005406-176 = "（部屋の明かりを消して、ヒマリのベッドのそばに座った）"
2005406-177 = "（静かな部屋の中、2人分の呼吸が優しく包み込んでいる）"
2005406-178 = "（ヒマリが眠るまでって約束だったのに……）"
2005406-179 = "（先に眠くなってしまい……）"
2005406-186 = "先生……？"
2005406-187 = "寝てしまわれたのですか？"
2005406-188 = "規則正しい寝息、ほんのり下がった体温……。"
2005406-189 = "ふふっ……。"
2005406-190 = "私たちの中で一番お疲れなのは、先生なんでしょうね。"
2005406-194 = "（誰かが、頭を撫でてくれているような気がする……）"
2005406-196 = "先生。"
2005406-197 = "……先生。"
2005406-198 = "私たちの――"
2005406-199 = "今は、私だけの先生……。"
2005406-200 = "ご存知ですか？"
2005406-201 = "今の私は、本当に悪い子なんです。"
2005406-202 = "もしもまだ起きていらっしゃるのなら、そのまま全部……眠気のせいにしてくれたらいいなって。"
2005406-203 = "本当に眠っていらっしゃるのなら、できるだけ長くこのままで……。"
2005406-204 = "そんなことばかり考えているなんて……。"
2005406-205 = "ふふっ、我ながら呆れてしまいますね。"
2005406-206 = "責任を押しつけるとしたら、私をこうさせた先生にも少しは文句を言いたいところですけど……。"
2005406-207 = "でも、それはさすがに卑怯ですね。"
2005406-212 = "ごめんなさい、先生。"
2005406-213 = "でも……先生？"
2005406-214 = "先生は、この瞬間も――"
2005406-215 = "そしてきっと、これからも――"
2005406-216 = "私にとって、誰よりも、何よりも大切で……。"
2005406-217 = "かけがえのない方なのです。"
2005406-220 = "（なぜだかとても安心できて……完全に意識を手放した）"
2005406-221 = "先生、ゆっくりお休みください。"
2005406-222 = "どうかご自愛を。"
