[translation]
2005502-1 = "ロッカー恐怖症"
2005502-10 = "……。"
2005502-100 = "……。"
2005502-101 = "あ……。"
2005502-102 = "ありがとうございます、先生。"
2005502-107 = "（ロッカーの中でユズの手を握ったまま、穏やかな時間を過ごした）"
2005502-11 = "じ、実は……その。"
2005502-12 = "ロッカーの中に入っても、落ち着かなくなってしまって……。"
2005502-13 = "[s1] \"やっぱりそれは大変な事態だよ。\"\n[s2] \"ステータス異常になってるよ。\""
2005502-16 = "そ、そう言われると……そうかも、しれません。"
2005502-17 = "[s] \"いつからそうなったの？\""
2005502-18 = "えっと……たぶん、なんですけど……。"
2005502-19 = "鋼鉄大陸から戻ってきた頃くらいから、だと思います。"
2005502-20 = "[s3] \"もしかして暗いところに入ると……。\"\n[s4] \"あの時の記憶が蘇る、とか？\""
2005502-23 = "い、いえ。暗い場所自体は平気なんです。"
2005502-24 = "あの時の記憶が原因なのは間違いないんですけど……。"
2005502-25 = "……。"
2005502-26 = "その……狭い場所に入ると、床が抜けてしまうんじゃないかって……。"
2005502-27 = "[s] \"床が？\""
2005502-28 = "はい……輸送船の射出ポートに入った時のことを思い出してしまって。"
2005502-29 = "狭い場所で座ってたら、床が開いて落っこちて……#nそのまま戦闘が始まるんじゃないかって……。"
2005502-30 = "そんな不安が頭の中を埋め尽くしちゃって……ロッカーがダメになっちゃったんです。"
2005502-31 = "[s] \"それは困ったね。\""
2005502-32 = "……で、でも、先生。"
2005502-33 = "逆に……良かったのかもしれません……。"
2005502-34 = "[s] \"良かった？\""
2005502-35 = "はい。ロッカーの中に引きこもることができなくなっちゃったから……。"
2005502-36 = "これをきっかけに……他の人みたいに、もっと外へ出かけたり……。"
2005502-37 = "たくさんの人と遊んだり……できるんじゃないかなって。"
2005502-38 = "そうしたら、普通になれるんじゃないかなって……そんな気がして……。"
2005502-39 = "[s] \"本気でそう思ってるの？\""
2005502-4 = "ゲーム開発部・部室"
2005502-40 = "……。"
2005502-41 = "……先生は、どう思いますか？"
2005502-42 = "[s5] \"変わろうと思う姿勢は素敵だよ。\"\n[s6] \"でも、そのきっかけはちょっと心配かな。\""
2005502-45 = "……そうですよね。"
2005502-46 = "わたし……まだ外に出る覚悟、ちゃんとできてないのかもしれません。"
2005502-47 = "突然知らない人やユウカ先輩が部室に来た時に、隠れる場所も必要ですし……。"
2005502-48 = "[s] \"じゃあ仕方ないね。\""
2005502-5 = "[ns] \"大丈夫！？何があったの！？\""
2005502-52 = "[ns] \"逆にロッカーに入る訓練をしてみるとか？\""
2005502-53 = "えっ？く、訓練ですか……それって……。"
2005502-54 = "せ、先生！？"
2005502-6 = "先生、そんなに慌てなくても……！"
2005502-60 = "な、なんでこの格好なんですか！？"
2005502-61 = "[ns] \"やっぱこれでしょ！UZQueen臨戦モード！\""
2005502-62 = "やっぱこれでしょってなんですか！？#nただロッカーに入るだけなのに……！？"
2005502-63 = "……えっ？#nこのままロッカーに入るんですか……？"
2005502-64 = "ちょ、ちょっと、それは……！"
2005502-65 = "け、結構怖くて……。"
2005502-66 = "逆にこの格好だとあの時のことが鮮明に浮かぶんです……！"
2005502-67 = "うぅぅ……#nネオアバンギャルド君のコックピットから緊急脱出した時の記憶が……。"
2005502-7 = "本当に、大したことじゃないんです……。"
2005502-72 = "……あれ？"
2005502-74 = "（不安そうなユズの両手をしっかり握る）"
2005502-75 = "せ……先生？なんで、手を……。"
2005502-76 = "ロッカーの中に、座ればいいんですか……？"
2005502-77 = "こ、このまま……？"
2005502-8 = "うう……急に今まで大丈夫だったのがそうじゃなくなるのは大変、というのはたしかに。"
2005502-83 = "こ、これならたしかに……ちょっとは……。"
2005502-89 = "[ns] \"どうかな？\""
2005502-9 = "その通り、ですけど……。"
2005502-90 = "よ、よく分かりません……。"
2005502-91 = "ちょっとだけ安心できるような……。"
2005502-92 = "どうしてなんでしょう……さっきと状況はほとんど変わらないのに。"
2005502-93 = "なんだか、落ち着くんです……。"
2005502-94 = "[ns] \"ユズの手を握ってるからかな。\""
2005502-96 = "[ns7] \"もう床が抜けても、突然飛び出しても大丈夫。\"\n[ns8] \"ユズがどこかへ飛んでいかないように、ずっと私が掴まえてるから。\""
2005502-99 = "ずっと……わたしを……。"
