[translation]
2005305-1 = "忍者少女は秘訣が知りたい！"
2005305-10 = "ほらほら、周りをよく見て。"
2005305-100 = "それなら教えてくれたって……！"
2005305-101 = "[s] \"時には失敗も、大事な経験になるからね。\""
2005305-102 = "……？"
2005305-103 = "[s1] \"もし説明会に行かなかくても、頭のどこかで気になってただろうし。\"\n[s2] \"でも、実際に行ったおかげでスッキリしたでしょ？\""
2005305-109 = "……た、たしかに。"
2005305-11 = "ここは、選ばれし者が秘訣を伝授される場……！"
2005305-110 = "これで同じ失敗はしないだろうし……。"
2005305-111 = "うん、やっぱ先生殿には感謝しなくっちゃ！"
2005305-112 = "それに、踏ん切りがついたし。"
2005305-113 = "怪しいものには頼らず、自分の力でチャンネルを大きくしてみせる……！"
2005305-114 = "だからこれからも見守っててね、先生殿！"
2005305-116 = "（ミチルを家に送ってからシャーレに戻り……）"
2005305-117 = "（ヴァルキューレに説明会の件を通報した） "
2005305-12 = "なら、それに見合う格好で来るのが礼儀！"
2005305-13 = "だから、ドレスを引っ張り出してきたーってわけ！#nふっふっふ……！"
2005305-14 = "ほら、あの人たちもスーツとかドレスでしょー？"
2005305-15 = "[s] \"確かに……？\""
2005305-17 = "（そう簡単に、秘訣を教えてくれるとは思わないけど……）"
2005305-18 = "（ひとまず、ミチルに付いていった）"
2005305-2 = "説明会会場"
2005305-20 = "[ns] \"ところで、この説明会はどうやって知ったの？\""
2005305-21 = "えーっとね、ちょっと前に動画を見てたらー……。"
2005305-22 = "画面に広告が出てきたの。"
2005305-23 = "それが、この説明会！"
2005305-24 = "[s] \"ど、動画広告……。\""
2005305-25 = "すごいんだよー、びっくりしちゃった！"
2005305-26 = "どうしたらチャンネルが伸びるのかなーって悩んで、色々検索してたら……。"
2005305-27 = "そのすぐ後に！"
2005305-28 = "ババーンってここの広告が出てきたの！"
2005305-29 = "まるで私に、悩みの答えを教えてくれるみたいに！"
2005305-3 = "（ミチルが心配になって……）"
2005305-30 = "それでビビッと来たの！#nこれが運命なんだって！"
2005305-31 = "[s] \"や、やっぱり……。\""
2005305-32 = "あーっ、信じてない！？"
2005305-33 = "とにかく、始まるから中に入ろっ！"
2005305-38 = "会場の中"
2005305-4 = "（同席することに決めた）"
2005305-40 = "皆さん、本日はお越しいただきありがとうございます。"
2005305-41 = "ここへ来場されたということは、共通してある悩みをお抱えのことでしょう？"
2005305-42 = "どうすれば再生数が伸びるのか、どうすれば登録者を増やせるのか……。"
2005305-43 = "……その悩みは、今日ここで解決してしまいましょう！"
2005305-44 = "やっぱり……！"
2005305-45 = "全てが見抜かれている……！"
2005305-46 = "[s] \"……。\""
2005305-47 = "心配は要りません。"
2005305-48 = "皆さんが望む再生数も、登録者数も……。 "
2005305-49 = "私たちの会社が、バッチリ保証いたします！"
2005305-5 = "あっ、先生殿ーっ！#nこっちこっちー！"
2005305-50 = "……ん？"
2005305-51 = "100万円さえお支払いいただければ、#n皆さんの動画の平均再生数を100万回まで引き上げましょう！"
2005305-52 = "そしてなんと今なら、登録者数100万人のおまけ付きです！"
2005305-53 = "んん……！？"
2005305-54 = "不安に思う方もいるかもしれませんが、ご安心ください。"
2005305-55 = "我々はキヴォトスクラッカー協会に認定された、#n安全なマクロプログラムを使用しております！"
2005305-59 = "た、ただの違法ツールじゃん……！"
2005305-6 = "……ん？"
2005305-60 = "先生殿、ごめん……私が間違ってたみたい……。"
2005305-61 = "真っ当な方法で増やせると思ったのにぃ……。"
2005305-62 = "……ただの詐欺だったなんて。"
2005305-63 = "行こ、先生殿。"
2005305-69 = "……ん？"
2005305-7 = "いやいや、先に行ったりなんかしないって。"
2005305-70 = "どうされましたか？"
2005305-71 = "説明会はまだ途中ですが……。"
2005305-72 = "えっと、もう帰ろうかなーって……。"
2005305-73 = "ふむ……それは少々困りますねぇ。"
2005305-74 = "規約上、途中退室は禁止しておりまして……。"
2005305-76 = "[ns] \"すみません、少し気になったんですが……。\""
2005305-77 = "はい、何でしょう？"
2005305-8 = "……あ、これ？"
2005305-81 = "も、もしかしてあなたは、シャーレの……？"
2005305-82 = "しししし失礼しましたぁ！#n気をつけてお帰りくださいっ！"
2005305-86 = "[ns] \"行こっか、ミチル。\""
2005305-87 = "う、うんっ！"
2005305-89 = "（こうして、ミチルと会場を後にした）"
2005305-9 = "いや、ちゃんとした格好のほうが良いのかな～って……。"
2005305-91 = "近くの公園"
2005305-92 = "うぅぅ、恥ずかし～……。"
2005305-93 = "あんな詐欺に騙されるとこだったぁ……。"
2005305-94 = "というか先生殿、もしかして……。"
2005305-95 = "最初から気づいてた、とか？"
2005305-96 = "[s] \"ある程度だけどね。\""
2005305-97 = "うぅぅぅ……ひどいよぉ、先生殿……！"
2005305-98 = "[s] \"ええっ！？\""
2005305-99 = "も、もちろん釣られた私が悪いんだけどぉ……！"
