[translation]
2005506-1 = "世界の救済とゲーマー"
2005506-12 = "せ、先生？いつからいらっしゃってたんですか！？"
2005506-13 = "うぅ……！"
2005506-14 = "[s1] \"VRゲームをしてたんだね。\"\n[s2] \"さっきは、どんな話をしてたの？\""
2005506-17 = "え？あ、その……。"
2005506-18 = "……[ruby=NPC]ゲームの中の人たち[/ruby]に、ありがとうって言われてたんです。"
2005506-19 = "自分たちの世界を救ってくれて、ありがとうって。"
2005506-2 = "ゲーム開発部・部室"
2005506-20 = "[s] \"この世界を救ったんだね！\""
2005506-21 = "す、救っただなんて……！"
2005506-22 = "で、でも、久しぶりに達成感というか……誇らしい気持ちでした。"
2005506-23 = "わたし、ゲーム以外に得意なこともなくて、現実だと誰かを助けるなんてできないけど……。"
2005506-24 = "ゲームの中なら、こうして世界を救うこともできるので……。"
2005506-25 = "もちろん、ゲームの話ですし……。"
2005506-26 = "大した意味は、ないのかもしれませんけど……。"
2005506-27 = "[s] \"でも、ゲームが現実でない理由って、ないんじゃない？\""
2005506-28 = "え？一体……どういう……？"
2005506-29 = "……わたしたちが何かを体験してる時間そのものが現実である、か。"
2005506-3 = "い、いえいえ、とんでもないです。"
2005506-30 = "……。"
2005506-31 = "そうですね。たとえ、ゲームの世界が仮想だとしても――"
2005506-32 = "そこで感じた感情や経験、達成感は――"
2005506-33 = "たしかに、本物かもしれません。"
2005506-34 = "[s3] \"これからユズたちが作っていくゲームも……。\"\n[s4] \"誰かにとって、そういう意味を持つんだよ。\""
2005506-37 = "誰かにとっての……そういう意味……。"
2005506-38 = "……。"
2005506-39 = "あ、あの、先生。"
2005506-4 = "……。"
2005506-40 = "わたしが守った世界……一緒に見てくださいますか？"
2005506-42 = "（断る理由はひとつもない）"
2005506-43 = "（ユズが手渡してくれたVR機器を装着し、一緒にゲームの世界へ入った）"
2005506-47 = "[wa:3200]― [log=유즈 결전]見てください、[wa:1430]先生。[/log]"
2005506-49 = "― [log=유즈 결전]わたしが守り抜いた[wa:1150]世界です。[/log]"
2005506-5 = "あ、ありがとうございます、みなさん。"
2005506-52 = "[wa:1700]― [log=유즈 결전]……もちろん、[wa:950]分かっています。[/log]"
2005506-54 = "― [log=유즈 결전]この光景を、[wa:820]見たのは[wa:1650]わたしだけじゃない[wa:1200]って。[/log]"
2005506-57 = "[wa:810]― [log=유즈 결전]大会の時、[wa:2090]こんなことを[wa:1060]仰いましたよね。[/log]"
2005506-59 = "― [log=유즈 결전]今この瞬間が、[wa:2560]ゲームが。[wa:1840]わたしたちの現実だ[wa:1910]って。[/log]"
2005506-6 = "[ns] \"ユズ？\""
2005506-62 = "[wa:780]― [log=유즈 결전]だから、[wa:2330]たとえ[wa:1030]エンディングの決まった[wa:830]世界だとしても……。[/log]"
2005506-64 = "― [log=유즈 결전]この世界の[wa:650]みんなが、[wa:1570]同じシナリオを歩むとしても……。[/log]"
2005506-67 = "[wa:890]― [log=유즈 결전]わたしがした選択、[wa:2840]この[wa:370]感情は……。[/log]"
2005506-69 = "― [log=유즈 결전]間違いなく、[wa:2670]本物なんです。[/log]"
2005506-7 = "あ……この声は……。"
2005506-72 = "[ns] \"そういえばユズ、その服、気に入ったんだね。\""
2005506-73 = "え？服……？"
2005506-74 = "あ、ああっ……！？"
2005506-75 = "そ、そ、そういうわけでは……！#nこれは……！"
2005506-76 = "このゲームに、向いているだけで……！"
2005506-77 = "ほ、本当に、それだけなんです！"
2005506-78 = "世界を救うのに、手段は選べませんから……！"
2005506-79 = "[ns] （満足げに微笑む）"
2005506-80 = "わ、笑わないでください……！"
2005506-82 = "（その後、ユズと一緒に平和になった世界をしばらく見て回った）"
