[translation]
2005306-1 = "忍者少女は流行に敏感！"
2005306-101 = "（そうして、ミチルの動画を見てみることに）"
2005306-106 = "百鬼夜行・第38旧校舎のとある教室"
2005306-107 = "少女忍法帖、ミチルっち～！"
2005306-108 = "ドーモ。#n小生、ミチルと申す。"
2005306-109 = "さーて、本日披露する忍法は～……「早着替えの術」！ "
2005306-110 = "上手く活用すれば、複雑な衣装も一瞬で着替えられる実用的な忍法！"
2005306-111 = "百聞は一見に如かず……。"
2005306-112 = "まずはお手本を披露しよー！"
2005306-113 = "ただ、万が一に備えて……。"
2005306-114 = "はりゃっ！"
2005306-119 = "[ns] （レンズにカバーを……？）"
2005306-12 = "[ns] \"！？\""
2005306-121 = "ってわけで、じゃじゃーん！"
2005306-122 = "一瞬で着替えが終了っ！"
2005306-123 = "さっそく、種明かしを――"
2005306-124 = "（レンズにカバーがかかっていたせいで……）"
2005306-125 = "（……最後まで何も映っていなかった）"
2005306-126 = "シャーレ・オフィス"
2005306-127 = "……。"
2005306-128 = "[ns] \"……。\""
2005306-129 = "こっ、こここっ、こんな初歩的ミスを……！！"
2005306-13 = "なにその反応！？"
2005306-130 = "うにゃぁああっ！！"
2005306-136 = "（あまりにもショックだったのか、煙幕弾を使わずに姿を消してしまった）"
2005306-14 = "ミチルだよ、先生殿！？"
2005306-15 = "[s1] \"こんな丁寧にノックして入ってくるなんて……。\"\n[s2] \"私の知ってるミチルじゃない！？\""
2005306-18 = "うにゃあ！？#n私のことを何だと思ってるのさぁ！？"
2005306-19 = "……や、やっぱ言わなくて良いや。不安だし。"
2005306-20 = "とにかぁく！今日の私は一味違う！"
2005306-21 = "なんと、「ブリーフィング」なるものの準備までしてきたよ！"
2005306-22 = "[s] \"ブリーフィング……！\""
2005306-23 = "そうっ！"
2005306-24 = "「少女忍法帖ミチルっち・成長秘訣および計画プレゼンテーションブリーフィング」！"
2005306-25 = "ふふふっ、気になるでしょー？"
2005306-26 = "[s] \"モモトークで言ってたのはこれ？\""
2005306-27 = "正解っ！"
2005306-28 = "変な方法に頼らず、純度100%で考え出した秘訣……！"
2005306-29 = "それじゃあ、ブリーフィングを始めるよ！"
2005306-3 = "[ns] \"ミチルかな？\""
2005306-30 = "――まず結論！"
2005306-31 = "[s] \"結論から入った！？\""
2005306-32 = "それは――"
2005306-33 = "映像を作る時には、トレンドを反映するのがベスト！"
2005306-34 = "たとえ忍者に関する話がちょーっと減っちゃうとしても……。"
2005306-35 = "[s3] \"忍者のチャンネルなのに……？\"\n[s4] \"大丈夫？\""
2005306-38 = "10歩前進するために、1歩後退する……そういうこと！"
2005306-39 = "だってほら、その動画を見たくなる一番の理由って何だと思う？"
2005306-40 = "……それは即ち、再生数！"
2005306-41 = "[s5] \"再生数を得るためには、再生数が必要……。\"\n[s6] \"鶏か卵かみたいな……？\""
2005306-44 = "でも実際、再生数が低い動画には、みんな興味を持ってくれないもの……！"
2005306-45 = "変なツールを使うつもりはないけど、#nそれ以外の手段は問わずに、再生数を上げるっ！"
2005306-46 = "その方が、視聴者も楽しんでくれるはず！多分。"
2005306-47 = "だから今日は、最新トレンドを反映した動画を上げるの！"
2005306-48 = "[s] \"例えば、どんな内容を？\""
2005306-49 = "ふっふっふ、良い質問だね先生殿！"
2005306-50 = "今回選んだキーワードは……「ファッション」！"
2005306-51 = "[s] \"ファッション……！\""
2005306-52 = "うん、時代は「ファッション」だよ。"
2005306-53 = "「人気急上昇中動画」を分析してみたら……。"
2005306-54 = "ランキング上位は、ファッション系の内容ばっかりだったの！"
2005306-55 = "「毎日着ても飽きないTシャツ7選」とか「パーソナルカラーで分かるマイ手榴弾」とか「あの銃と相性抜群のアウター」とかー……。"
2005306-56 = "その流行りに乗って、さっそく企画してみたよ！"
2005306-57 = "[s] \"おっ、どんな内容を？\""
2005306-58 = "それは～……！ "
2005306-59 = "……じゃじゃん！#nファッションと忍術のコラボレーション！"
2005306-60 = "ファッションに関係する忍術を考案して、毎週動画をアップするの！"
2005306-61 = "このコンテンツで視聴者を引き込んで……。"
2005306-62 = "その合間に本格的な忍者コンテンツを上げれば……。"
2005306-63 = "みんな、いつの間にか忍者の虜になってるはず！"
2005306-64 = "まるで茹でガエルみたいに！"
2005306-65 = "[s] \"その例えはどうかな！？\""
2005306-66 = "とにかく、これにてブリーフィングは終了……！"
2005306-67 = "あとは結果で語ってみせるよ！"
2005306-68 = "というわけで先生殿、期待しててね！"
2005306-69 = "超有名インフルエンサーになって、先生殿をマネージャーにスカウトしちゃうから！"
2005306-70 = "ってことで、今日の話はおしまい！#nアディオス＝SAYONARA！"
2005306-76 = "（煙幕弾を使ってるのに、どこから出ていったのか丸分かりだ……）"
2005306-78 = "（数日後）"
2005306-8 = "ドーモ、先生殿。"
2005306-80 = "（今日も山積みになった書類を、ギリギリのところで整理していると……）"
2005306-81 = "先生殿……。"
2005306-85 = "助けてぇ～……。"
2005306-86 = "[s7] \"……ミチル！スターになって迎えに来てくれたの！？\"\n[s8] \"この書類地獄から、私を連れ出して……！\""
2005306-89 = "えぇっ！？#nいや、私が助けてもらおうと思って来たんだけど……！"
2005306-90 = "[s] \"……え？\""
2005306-91 = "この前、ファッションと忍術を掛け合わせた動画を上げたんだけどね……。"
2005306-92 = "おかしいくらい反応が悪くってぇ……。"
2005306-93 = "今までの動画より、低評価がすごい数に……！"
2005306-94 = "[s] \"映像とかコメントはチェックしてみた？\""
2005306-95 = "……。"
2005306-96 = "その、怖くて……。"
2005306-97 = "だからその、先生殿も一緒に見てもらえないかなーって……。"
2005306-98 = "[s] \"分かった、じゃあ確認しよう。\""
2005306-99 = "ありがとー、先生殿ぉ……。"
