[translation]
2005503-1 = "UZQueenのスランプ"
2005503-2 = "ゲーム開発部に向かう途中"
2005503-3 = "（ユズからそんな言葉が出るなんて）"
2005503-4 = "（信じられない状況に、急いでミレニアムへ向かった）"
2005503-9 = "先月リリースされたゲーム、やった？"
2005503-11 = "[ns]（あれ、ゲームの話……）"
2005503-12 = "新作格闘ゲーの――『シミュリオン・クエスト』のこと？"
2005503-13 = "サイバーパンク風の近未来が舞台で、世界観の完成度がすごいよね。#nかなり細かく作り込まれてて、モーションもめちゃくちゃ滑らかだし。"
2005503-14 = "でもさ、なんか変じゃない？"
2005503-15 = "変？バグのこと？#nそれならこの前メーカーが告知してたけど……。"
2005503-16 = "いや、そうじゃなくて……ランキングにUZQueenがいないじゃん。"
2005503-17 = "――ランキング始まって、もう1週間も経つのに。"
2005503-19 = "（UZQueen……？）"
2005503-20 = "あ、ほんとだ！格ゲーのランキングにUZQueenがいないことなんて、今までなかったのに……！"
2005503-21 = "UZQueenに何かあったのかな？"
2005503-23 = "（その会話を聞いた瞬間、気がついたら歩く速度が上がっていた）"
2005503-27 = "ゲーム開発部・部室"
2005503-28 = "[ns] \"ユズ！大丈夫！？\""
2005503-29 = "ひいっ！？先生！？"
2005503-33 = "い、一体どうしたんですか！？"
2005503-34 = "なにをそんなに慌てて……。"
2005503-35 = "[s] \"ユズ、一体何があったの？\""
2005503-36 = "えっ！？特になにもないですよ！？"
2005503-37 = "ほ、ほら、ちゃんとロッカーにも入れるようになりましたし。"
2005503-42 = "ま、まさか……#nさっきのモモトークを見てここまで……？"
2005503-43 = "ゲームが難しい、とぼやきはしましたけど……。"
2005503-44 = "わたし、そんなに変でしたか……？"
2005503-48 = "たしかに……そうですね。"
2005503-49 = "今までゲームを難しいと思うことなんてなかったのに……。"
2005503-50 = "[s1] \"そのゲームなんだけど、もしかして……。\"\n[s2] \"『シミュリオン・クエスト』？\""
2005503-53 = "ど、どうして分かったんですか！？"
2005503-55 = "（道中で聞いた話を伝えた）"
2005503-56 = "あ……な、なるほど……。"
2005503-57 = "その……わたし、まだ#n『シミュリオン・クエスト』はまともに触れていなくて……。"
2005503-58 = "その……。"
2005503-59 = "……ちょっと、見てみませんか？"
2005503-61 = "（ユズが『シミュリオン・クエスト』を起動した）"
2005503-62 = "（ゲームを始めてすぐ、ユズがこのゲームを苦手な理由が分かった気がした）"
2005503-64 = "[ns3] \"このゲーム、実際に手足を動かして戦うタイプの……。\"\n[ns4] \"……VRゲームだったんだ！\""
2005503-67 = "はい。全身を使って、攻撃したり避けたりしなきゃいけなくて……。"
2005503-68 = "でもわたし……手を動かすとかならいいんですけど、#n走ったり全身を使うのはちょっと苦手で……。"
2005503-69 = "ちゃんとプレイしたかったんですけど、チュートリアルすらできなくて……。"
2005503-70 = "えっ？先生もやってみたいんですか？"
2005503-71 = "い、一応2Pでの協力モードはありますが……。"
2005503-72 = "何か、アイデアがあるんですか……？"
2005503-77 = "ど、どうしてまたこの格好に……！？"
2005503-78 = "ゲーム内の主人公と似てるから、プレイしやすい？#nわ、分からなくはないですけど……！"
2005503-79 = "[s5] \"じゃあ、さっそく――\"\n[s6] \"肩に乗ろうか、ユズ。\""
2005503-82 = "えっ！？"
2005503-83 = "ひ、ひいっ！？"
2005503-88 = "（ユズを持ち上げて、肩車をする）"
2005503-91 = "わっ……た、高いです……！"
2005503-92 = "で、でも、2P協力モードってそういうものではないような……。"
2005503-93 = "[s7] \"ちゃんとゲームに反映されてるよ？\"\n[s8] \"見て、ユズのキャラもゲーム内で肩車されてる。\""
2005503-96 = "そ、それはそうですけど……！"
2005503-97 = "[s9] \"身体を動かすのは私がやるよ、パイロットさん。\"\n[s10] \"ユズはユズの得意なことに集中して！\""
2005503-100 = "……！"
2005503-101 = "それじゃあ、わたしが索敵とブリーフィングをやるので、先生は移動と攻撃をお願いします。"
2005503-102 = "[s] \"よし、行こうか！\""
2005503-107 = "（そうしてユズと2人で協力プレイを始めてから――）"
2005503-108 = "（トップランカー入りするまで、一日もかからなかった）"
2005503-109 = "（その後……）"
2005503-111 = "（『シミュリオン・クエスト』のネット掲示板には、肩車したままボスに挑む2人組の目撃談が、無数に寄せられるようになった）"
2005503-112 = "（……ただ、その芸当ができたのは、UZQueenだけだったとか）"
