[translation]
2005402-1 = "ライフスタッフ（１）"
2005402-8 = "[ns] \"！？！？\""
2005402-11 = "ふふっ、おはようございます、先生。"
2005402-12 = "この超天才清楚系病弱美少女ライフスタッフによるモーニングコールはいかがでしたか？"
2005402-13 = "[s] \"おかげで起きられたけど……びっくりしたよ。\""
2005402-14 = "想定通りの結果が得られるのは実に喜ばしいですね。"
2005402-15 = "それでは、朝の身支度を始めましょうか。"
2005402-19 = "[ns] \"これは……？\""
2005402-20 = "私なりの改造と改良を加えたAMASです。"
2005402-21 = "AMASはリオが開発したものですが……今は状況が状況ですから。#n少しくらい借りても怒られないでしょう。"
2005402-22 = "さあ、爽やかな1日はストレッチから始まります。#nそのAMASが補助してくれますよ。"
2005402-23 = "まずは腰をぐ～っと伸ばして――"
2005402-30 = "[ns1] \"！？！？\"\n[ns2] \"いたたたた！！\""
2005402-35 = "ふふっ。痛いくらいがちょうどいいのですよ。#nゆっくりと身体を目覚めさせていきましょう。"
2005402-39 = "洗顔もお忘れなく。私が愛用している洗顔料をご用意しました。"
2005402-40 = "朝のデリケートな肌にも優しい低刺激タイプなので、肌トラブルの心配はありません。"
2005402-41 = "寝ている間に分泌された皮脂や汗を洗い流すのにぴったりですよ。"
2005402-52 = "なるほど……やはり、今日も同じ服なのですね……。"
2005402-53 = "このような環境ですし、ファッションを楽しむ余裕まではないかもしれませんが……。"
2005402-54 = "最低限の身だしなみだけは整えておきたいところです。#nその服、しわになっていますよ。"
2005402-55 = "おおかた、洗濯して乾かしたまま着ているのでしょう？#nスチームを当てますので貸してください。"
2005402-59 = "これで身支度は終わりですね。執務スペースに移動しましょう。#n「全知」であるこの私が、最適なルートをご案内します。"
2005402-60 = "床に矢印を投影しますので、その通りについてきてくださいね？"
2005402-61 = "[s] \"……1人でも迷わないよ？\""
2005402-62 = "……。"
2005402-63 = "そういうことではありません。"
2005402-64 = "[ns] \"というと……？\""
2005402-65 = "……。"
2005402-66 = "とにかく違うんですよ！"
2005402-70 = "お待ちしておりました。無事に到着されましたね。"
2005402-71 = "ふふ。こんなに親切な超天才病弱美少女ハッカー兼ライフスタッフは、#n世界広しといえど私くらいなものですよ？"
2005402-72 = "[s] \"うん……お気持ちだけもらっておくね……。\""
2005402-73 = "遠慮なさらずとも……。"
2005402-74 = "「正直は最善の策」というではないですか。"
2005402-75 = "とにかく、引き続きお世話をさせていただくつもりですので、よろしくお願いしますね。"
2005402-76 = "[s] \"えっと、私の意思は……？\""
2005402-77 = "……。"
2005402-78 = "まさか……生徒の健気な気持ちを無下にするとおっしゃるのですか……？#n先生に快適な生活を提供するために――"
2005402-79 = "リオが独占していたシステムをハッキング……もとい、電子的交渉で奪ってまでリソースを確保したというのに……。"
2005402-80 = "いえ……それでも構いません。"
2005402-81 = "なにせこれは、私が勝手にやっていることですから……。"
2005402-82 = "伸ばした手を振り払われようとも……それをなすのが先生ならば……胸を刺すような痛みにも耐えてみせます……。"
2005402-83 = "[s] \"す、すっごく助かるよ！これからもお願いしたいな！\""
2005402-84 = "ふふっ。そうでしょうとも。"
2005402-85 = "ちなみに今日の占星術によると、しばらくは「赤」の運気が私たちを包むそうです。"
2005402-86 = "そこで、モニターの壁紙を赤一色に変えておきました！"
2005402-87 = "[ns] \"目がチカチカするから、他の方法だと嬉しいかな……。\""
