[translation]
2005006-1 = "地下で二人っきり"
2005006-10 = "これから行くところは、みんなには内緒だよ？"
2005006-11 = "……しょっと！"
2005006-16 = "[ns] \"素手で扉を外した……！？\""
2005006-17 = "行こ、先生！"
2005006-19 = "（リツについて、地下通路に入った）"
2005006-2 = "ワイルドハント・外郭城壁"
2005006-23 = "地下遺跡"
2005006-24 = "じゃじゃ～ん。#nいい感じの輸入ルートを探してたら、遺跡を見つけちゃったんだ！"
2005006-25 = "[s] \"遺跡？\""
2005006-26 = "ワイルドハントって、とっても古い学院だからね。"
2005006-27 = "発掘されてない遺跡が、まだまだたくさんあるんだってさ。"
2005006-28 = "そして……驚くのはまだ早いっ！"
2005006-29 = "ついてきて、先生！"
2005006-3 = "先生、こっちこっち！"
2005006-31 = "この通路の先に……。"
2005006-37 = "[wa:1030]― [log=리츠]あー……[/log]"
2005006-39 = "― [log=리츠]すずしー……[/log]"
2005006-4 = "（リツは城壁の下にある、小さな鉄格子の扉の前に立っていた）"
2005006-42 = "[ns] \"この場所は……。\""
2005006-43 = "[wa:1140]― [log=리츠]ここ、[wa:900]すごくない？[/log]"
2005006-45 = "― [log=리츠]むかー[wa:670]しからある[wa:700]地下貯水槽らしいんだけど……[/log]"
2005006-48 = "[wa:500]― [log=리츠]おっ[wa:680]きい穴を[wa:650]掘っ[wa:530]て、[wa:1090]いっ[wa:720]ぱい柱を立てて……[/log]"
2005006-50 = "[wa:120]― [log=리츠]一つ一つに[wa:1670]彫刻されてるんだ……[/log]"
2005006-53 = "[ns] \"まるで……神殿、だね。\""
2005006-54 = "[wa:1160]― [log=리츠]……きれいでしょ？[/log]"
2005006-56 = "― [log=리츠]どうしても先生に[wa:930]見せたかったんだ。[/log]"
2005006-59 = "[wa:790]― [log=리츠]ね、[wa:1590]こっちきて。[/log]"
2005006-61 = "― [log=리츠]ボクと同じ景色、[wa:2100]見ようよ。[/log]"
2005006-64 = "（その後、二人で水に足をつけながら……）"
2005006-65 = "（リツと一緒に楽しい時間を過ごした）"
2005006-8 = "[ns] \"この扉は……？\""
2005006-9 = "しーっ……！"
