[translation]
2005105-1 = "可愛いね、レイサ"
2005105-2 = "（モモトークの内容が気になり、レイサを探しに行った）"
2005105-5 = "[ns] \"よかった……何事もなくて……。\""
2005105-6 = "もうこの格好をしてても驚かないんですね、先生。"
2005105-7 = "実はコートのポケットに入れっぱなしにしてた焼夷手榴弾が爆発して……。"
2005105-8 = "慌てて消したんですが……。#nクローゼットと中の服がびしょ濡れになってしまって……あははっ……。"
2005105-9 = "クリーニングから戻ってきた、このコスチュームがなかったら――"
2005105-10 = "家の外に出られず、大ピンチになるところでしたよ。"
2005105-11 = "なので、今から新しい服を買いに行きます！"
2005105-12 = "[s] \"一緒に行く？\""
2005105-13 = "！！"
2005105-14 = "先生が選んでくださるんですか！？心強いです！"
2005105-15 = "行きましょう！今すぐ！"
2005105-18 = "むむ……。"
2005105-19 = "全然分かりません！"
2005105-20 = "マネキンさんが着てる服を、全部買ってしまったほうがよさそうです！"
2005105-21 = "[s] \"レイサって、あまりファッションに興味ないの？\""
2005105-22 = "私、小物をいっぱい着けるのは好きなんですが！"
2005105-23 = "流行には疎くて！"
2005105-24 = "並んでるものをまるまる買ったほうが、失敗しないかなと……。"
2005105-25 = "とりあえずこれとこれにします。では会計に――"
2005105-26 = "どういうことだコラァ！"
2005105-27 = "完全に押し売りじゃねぇか！"
2005105-32 = "お、お客様、返品交換はできかねます。#n申し訳ございません……。"
2005105-33 = "水洗い不可、と明記されていたかと思いますが……。"
2005105-34 = "てめぇ、ふざけてんのかァ？"
2005105-35 = "セーターが縮んでピチピチのへそ出しになってんだぞ！#nどう着ろってんだ！ああん！？"
2005105-36 = "ひいいっ……返品交換にはレシートが必要でして……！"
2005105-37 = "話が通じねぇヤツだなぁ！全部ぶち壊してやろうか！"
2005105-38 = "せ、先生！これは止めに入らなきゃです……！"
2005105-39 = "でも着替えてたら、間に合わない……。"
2005105-40 = "[s1] \"魔法少女は、みんなを守るヒーロー。\"\n[s2] \"ドレスコードも、バッチリだからね。\""
2005105-43 = "先生……！"
2005105-44 = "はい！行ってきます……！"
2005105-45 = "スーッ……。"
2005105-49 = "キュルルル～……ピキーン！シャキキーン！バァーン！"
2005105-54 = "自警団のスーパースター、必殺のハートエース……。"
2005105-55 = "[ruby=うざわ]宇沢[/ruby]レイサ、登場！！！"
2005105-57 = "な、なんだこいつ？"
2005105-58 = "お前も返品に来たのか？"
2005105-59 = "あんな服も売ってんのかよ。ちょっとこの店見直したわ……。"
2005105-61 = "善良な市民を脅かす不届き者……この宇沢レイサが許しません！"
2005105-62 = "あと、へそ出しでも似合っていますよ！"
2005105-63 = "何言ってんだぁ！？"
2005105-64 = "やっつけろ！"
2005105-73 = "ぐああっ……。"
2005105-74 = "つ、つえーな……。"
2005105-79 = "正義に代わって、おしおきです！"
2005105-80 = "あ、ありがとうございます！助かりました！"
2005105-85 = "あっという間に倒しちゃった……すごい！"
2005105-86 = "カッコいい！まさにヒーローだ！"
2005105-87 = "へ、へへ……そんな……照れちゃいます。"
2005105-88 = "では皆さん、ごゆっくりお買い物をお楽しみください！"
2005105-94 = "あっ、魔法少女のお客様。#n……まだお支払いが済んでないようです。"
2005105-95 = "お会計はこちらになります。"
2005105-99 = "あ……。"
2005105-101 = "は、はいぃ……！"
2005105-103 = "（顔を赤らめたレイサと一緒に服を買い、お店を後にした）"
2005105-104 = "（新しい洋服を着たレイサはとても可愛かった）"
