[translation]
2005103-1 = "頼もしいね、レイサ"
2005103-2 = "先生！こちらです！"
2005103-3 = "[s] \"こんにちは、レイサ！\""
2005103-4 = "ふふ、今日はパトロール日和ですね！"
2005103-5 = "ところで先生、その大きなリュックは……。"
2005103-6 = "[s1] \"証拠品の収集用だよ！\"\n[s2] \"これがパンパンになるまで……パトロールする！\""
2005103-9 = "やっぱり……先生は最高です！！"
2005103-10 = "早速、パトロール開始ですっ！！"
2005103-13 = "あれは「まほリバ」アクリルキーリング！"
2005103-14 = "3期11話に出た、私服バージョンですね！"
2005103-15 = "先生！"
2005103-16 = "[s] \"うむ！全種類、確保せねば！\""
2005103-17 = "らじゃー！です！"
2005103-19 = "あっ、今度はクリアファイルが！"
2005103-20 = "[s] \"勉強に必要だ！購入せよ！\""
2005103-21 = "うへへ～！"
2005103-22 = "あの、すみません～"
2005103-28 = "写真一緒に撮ってもらってもいいですか……？"
2005103-29 = "ええっ！？"
2005103-30 = "その衣装すごく似合ってて、もしよろしければ……。"
2005103-31 = "あ、う、うぅ……うあぁ……。"
2005103-35 = "！？"
2005103-36 = "[s] \"しょ、少々お待ちください……。\""
2005103-38 = "うぅ……。"
2005103-39 = "[s] \"レイサ、大丈夫？\""
2005103-40 = "へへ……私は大丈夫です、先生。"
2005103-41 = "誰かと写真を撮るのはいいんですけど……。"
2005103-42 = "自分の表情や仕草が気になっちゃって……。"
2005103-43 = "だから、体育の時間とかも怖いんです。#n動きが変じゃないか、不安で……。"
2005103-44 = "うう……でも、さっきの方にはちゃんと説明すればよかったです……。"
2005103-45 = "[s3] \"レイサはいま、魔法少女でしょ。\"\n[s4]  \"だから、レイサがとるポーズは全部魔法少女のポーズになるんだよ！\""
2005103-48 = "……！"
2005103-49 = "そうでした。#n魔法少女と正義の自警団は、どんな時にも堂々とあるべし！"
2005103-50 = "やっぱり先生はすごいです！"
2005103-51 = "[s] \"では、再出動だ！\""
2005103-52 = "はいっ！"
2005103-62 = "先生、見てください。"
2005103-63 = "夕日がすごくきれいです。"
2005103-64 = "[s] \"ああ、本当だね。\""
2005103-65 = "実は今日……パトロールを口実に遊びたかっただけで……。"
2005103-66 = "先生が来てくださって、本当に嬉しかったです。"
2005103-67 = "いつも付き合ってくださり、ありがとうございます！"
2005103-68 = "[s5] \"自警団のエースが、今日も平和を守ったんだよ！\"\n[s6] \"みんなを笑顔にしてたでしょ？\""
2005103-71 = "へへっ！それを言うなら……。#n先生だって、みんなを笑顔にするシャーレのスーパースターですよ！"
2005103-72 = "[s] \"よし！早速、シャーレに戻って証拠分析だ！\""
2005103-73 = "はい！！"
2005103-75 = "（その後、レイサとシャーレに戻り……）"
2005103-76 = "（グッズを一つずつ見ながら、イベントの余韻に浸った）"
