[translation]
2005102-1 = "また会ったね、レイサ"
2005102-13 = "こ、こんにちは、先生……！"
2005102-14 = "[s1] \"あ、あなたは！！\"\n[s2] \"テルミットピンク！\""
2005102-17 = "じょ、冗談を言ってる場合じゃないんです！"
2005102-18 = "ここに来るまで……色んなことがあったんですから……ふぅ……。"
2005102-19 = "[s] \"マスコットキャラに契約してよって言われた？\""
2005102-2 = "（ある晴れた日、シャーレの前を散歩していたところ……）"
2005102-20 = "そ、それならよかったかもしれません……。"
2005102-21 = "この服が、先日お話したコスチュームなんですけど……。"
2005102-22 = "今日届いたので、試しに着てみたんですが……。"
2005102-23 = "ブツッ！っと、ファスナーの持ち手が取れて……！"
2005102-24 = "服に閉じ込められてしまいました……。"
2005102-25 = "自分一人じゃファスナーも見えないし、困ってしまって……。#nとりあえずシャーレに来ました！"
2005102-26 = "助けてください、先生……！"
2005102-27 = "[s3] \"オフィスの備品で直せると思うよ。\"\n[s4] \"その格好でここまで……大変だったね。\""
2005102-3 = "[ns] \"いい天気だなぁ。\""
2005102-30 = "はは、もう、すごかったんですよ……。"
2005102-31 = "まるで、スーパースターになった気分でした。"
2005102-32 = "バスに乗れば子供たちに写真を撮られ……。"
2005102-33 = "イベント会場の前を通れば、キャストに間違えられ……て……。"
2005102-34 = "これが……スーパー、スター……はは……。"
2005102-35 = "[s5] \"レイサが疲れ果ててる！\"\n[s6] \"魔法少女、好きじゃなかったの？\""
2005102-38 = "大好きです！！！"
2005102-39 = "この服もサイズピッタリで、色もお気に入りです……が……！"
2005102-4 = "あ、あの……先生……。"
2005102-40 = "心の準備をする暇もなく、強制変身になってしまったので！！"
2005102-41 = "ロボットが好きでも、#nいきなり乗り込むことになったらビックリしませんか！？"
2005102-42 = "変身を解かせてください……。"
2005102-43 = "[s7] \"アニメや漫画でしか聞かないセリフだ！\"\n[s8] \"とりあえずオフィスに行こうか。\""
2005102-46 = "ありがとうございます……。"
2005102-49 = "[ns] \"よし、これで大丈夫。\""
2005102-5 = "[s] \"うん？\""
2005102-51 = "「リリース・フォーム」！……なんちゃって！"
2005102-52 = "なんだか本当に魔法少女みたいですね！"
2005102-53 = "[s] \"元の姿に戻るところを見られるなんて！\""
2005102-54 = "うまくいってよかったです。"
2005102-55 = "先生ならなんとかしてくださると信じていました！"
2005102-56 = "いつも、私の悩みを解決してくれますから！"
2005102-57 = "[s] \"変身を解く手伝いができてよかったよ！\""
2005102-58 = "あはは！さすが先生！"
2005102-59 = "それでは、この辺で失礼します！"
2005102-60 = "またお会いしましょう！"
2005102-61 = "[s9] \"待って！その格好で出るの？\"\n[s10] \"背中のファスナー、開きっぱなしだよ。\""
2005102-64 = "げっ、そ、そうでした！"
2005102-65 = "うう、着替えを持ってくればよかったです……！"
2005102-66 = "ううぅ……本当にミスばかりで……。"
2005102-67 = "[s] \"そ、そんなヘコまないで！\""
2005102-71 = "（レイサに羽織れそうな上着を貸してあげた）"
2005102-72 = "（レイサは元気を取り戻し、シャーレを出た）"
2005102-9 = "ううぅ……。"
