[translation]
2005403-1 = "規則と概念"
2005403-10 = "（ヒマリと一緒に業務をこなしていった）"
2005403-15 = "[ns] \"ふああぁぁ……。\""
2005403-16 = "大きなあくびですね。"
2005403-17 = "眠いというよりも、少し気怠い感じでしょうか？#n……ふふ、なるほど。"
2005403-18 = "それでは、ご一緒に息抜きはいかがですか？#n今から車椅子の整備をしに行こうと思っておりまして。"
2005403-19 = "[s] \"車椅子？いま乗ってるよね？\""
2005403-20 = "いえ、これではありません。"
2005403-21 = "屋外用の方です。先生もご存じのはずですよ。"
2005403-22 = "戦闘を含むあらゆる状況に対応できる、あれです。"
2005403-23 = "[s] \"あれはバイク――\""
2005403-24 = "く・る・ま・い・す、ですよ？"
2005403-25 = "[ns] \"そっか……。\""
2005403-31 = "（ヒマリは手際よく楽しそうにバイク……ではなく、車椅子の整備をしている）"
2005403-32 = "（……やっぱり車椅子ではないと思う。という言葉は飲み込んだ）"
2005403-37 = "浮遊装置の出力良好。アクセルとブレーキ……問題なし。#n補助エネルギーシールド残量確認――"
2005403-38 = "ふふ。私の車椅子は今日も完璧ですね。"
2005403-39 = "[s] \"車椅子ってなんだっけ……。\""
2005403-4 = "お昼寝……少しでも疲れは取れましたか？"
2005403-40 = "あら、先生ともあろうお方がご存じないだなんて。"
2005403-41 = "仕方ありませんね。私がご説明して差し上げましょう。"
2005403-42 = "車椅子とは、人が椅子に座ったまま移動するための「移動補助用具」です。"
2005403-43 = "その形態は様々ですが、私のものは室内用も屋外用も電動型にあたります。"
2005403-44 = "[s] \"そう……かな……？\""
2005403-45 = "まだご納得いただけていないご様子ですね。"
2005403-46 = "では先生、こう考えてみてください。#n動力で動いて、移動を補助して、生活の利便性を高めてくれる――"
2005403-47 = "それらが「車椅子」を構成する要素だとすれば、#nこれもまた間違いなく「屋外用車椅子」と言えるのではないでしょうか。"
2005403-48 = "ある種、この屋外用車椅子は到達点の1つと言っても過言ではありません。"
2005403-49 = "ずっとこのような「屋外用車椅子」を作りたいとは思っていたのです。#nそれこそ、今よりもこの両脚に力があった頃から。"
2005403-5 = "[s] \"多少はね。起こしてくれてありがとう……。\""
2005403-50 = "あの頃はあの頃で、時間や予算の問題が常につきまとっていたわけなのですが。"
2005403-51 = "それも、今ならば違います。"
2005403-52 = "あら？褒めてくださるのですか？#n前向きな姿勢として、好ましく思っていただけるのはとても嬉しいのですが……。"
2005403-53 = "ふふっ……それは今さらですよ、先生。私を誰だと思っているのですか。"
2005403-54 = "私が蘭のように優雅であることは周知の事実です。#nとはいえ……その内には雑草にも勝るとも劣らない意志を秘めています。"
2005403-55 = "簡単には挫けず、諦めない。#nそれが[ruby=あけぼし]明星[/ruby]ヒマリですもの。"
2005403-56 = "それに考えてみてください、先生。#n「移動補助用具」と一口に言っても、#n目的に応じていろいろ用意されている方が便利じゃありませんか？"
2005403-57 = "[ns] \"まあ……種類がいっぱいある道具は結構あるよね。\""
2005403-6 = "礼には及びません。#nなにせ今の私は―― "
2005403-62 = "ふふ、いかにも。"
2005403-63 = "はい？「屋外用車椅子」とバイクの違いですか？"
2005403-67 = "ふむ……このような提案をするつもりはなかったのですが……。"
2005403-68 = "この際ですから、先生にはしっかりとご理解いただくのも良いでしょう。"
2005403-69 = "基本スペックからして、私の「車椅子」はバイクとは全くの別物です。"
2005403-7 = "先生専属超天才病弱美少女ハッカー兼ライフスタッフなのですから。"
2005403-70 = "その真髄を――ご覧にいれます。"
2005403-71 = "[s] （何だか嫌な予感がする）"
2005403-72 = "というわけで、先生？"
2005403-73 = "今晩、少しお時間をいただけますか？"
2005403-8 = "それでは、午後の業務も頑張りましょう。"
