[translation]
2005505-1 = "ゲーム大会"
2005505-2 = "ゲーム開発部・部室"
2005505-3 = "まさか「バーチャルボス」がゲーム大会の賞品になっているなんて……。"
2005505-4 = "……たしかに、あの人気を考えたら賞品というのも納得です。"
2005505-5 = "ま、まさか先生が言ってた方法って……。"
2005505-6 = "大会で「バーチャルボス」を手に入れる……！？"
2005505-10 = "険しい道のり、ですね……。"
2005505-11 = "[s] \"やめとく？\""
2005505-12 = "いえ。やらせてください、先生！#nゲームなら、わたし……！"
2005505-13 = "……ってそうだ。#nどのゲームの大会なんですか？"
2005505-14 = "『シミュリオン・クエスト』……！？#n以前、先生と一緒にやったVRゲーム……！"
2005505-15 = "……たしかに、それなら勝てるかもしれません。"
2005505-16 = "でも、まだ一人で上位に入れる自信はなくて……。"
2005505-17 = "[s] \"だから協力プレイ部門でエントリーしておいたよ。\""
2005505-21 = "ええっ！？先生も一緒に出てくれるんですか？"
2005505-22 = "仲間をひとりで戦場に送り出すわけにはいかない……？"
2005505-23 = "そうですね……『シミュリオン・クエスト』は、わたしひとりじゃ予選突破も難しいですし……。"
2005505-24 = "……ありがとうございます、先生。いっしょに優勝、目指しましょう……！"
2005505-25 = "[s1] \"ところでさ、ユズ。\"\n[s2] \"シミュリオン・クエストの大会には参加条件がもう一つあるみたいなんだ。\""
2005505-28 = "参加条件……ですか……？"
2005505-30 = "（それからしばらくして、ゲーム大会当日）"
2005505-32 = "ゲーム大会会場入口"
2005505-34 = "無理です！"
2005505-35 = "先生を、信じたのに……！"
2005505-36 = "[s] \"落ち着いて、ユズ。\""
2005505-40 = "[ns3] \"みんなゲーム内の衣装を着ているだけだよ？\"\n[ns4] \"普通のコスプレ会場だと思えば平気だって。\""
2005505-43 = "そ、そう言われても……普通の格好の人もいるのに……。"
2005505-44 = "せ、先生だっていつもの服で来てるじゃないですか！"
2005505-45 = "[s5] \"ゲーム内に登場する市民NPCの服装だよ。\"\n[s6] \"スーツは大人の鎧だからね。\""
2005505-48 = "そ、それならわたしも制服がよかったです……。"
2005505-49 = "たしかに、この格好が一番VRゲームをやりやすいのはそうですけど……。"
2005505-50 = "[s] \"あ、始まるみたいだよ。行こう、ユズ！\""
2005505-51 = "ふぇぇぇん……！！"
2005505-53 = "（その後、試合中ずっとユズは私の背中にぴったりくっついていた）"
2005505-55 = "ゲーム大会会場内部"
2005505-56 = "さあ！最高に盛り上がってまいりました！"
2005505-57 = "ついに決勝戦、対戦チームをステージにお呼びしましょう！"
2005505-58 = "最短でトップ入りした伝説のデュオ――"
2005505-59 = "「UZQueen＆Thrones」！盛大な拍手でお迎えください！"
2005505-64 = "UZQueen……？いま、UZQueenって言ったよね！？"
2005505-65 = "やっぱり来てるんだ！わぁ……すごい！オーラがある！"
2005505-66 = "でも、あのポーズは一体……？"
2005505-72 = "肩車ポジションで敵を倒す2人組って……UZQueenだったの！？"
2005505-73 = "UZQueenのプレイを生で見られるチャンス……目に焼きつけないと！"
2005505-74 = "う、うぅ……先生、やっぱり人前で肩車は恥ずかしすぎます……！"
2005505-75 = "は、恥ずかしくてあんまり……。"
2005505-76 = "ゲ、ゲームに集中、できません……。"
2005505-77 = "[s] \"ユズ。\""
2005505-78 = "は、はいっ！？"
2005505-79 = "[s] \"今だけは、『シミュリオン・クエスト』の世界が現実だと思って。\""
2005505-80 = "で、でも……。"
2005505-81 = "これが現実だとしたら……#nわたしたちって、今命がけで剣を振り回してるわけで……逆に、怖いです……。"
2005505-82 = "没入感が大事、というのは知っていますが……。"
2005505-86 = "はぁ、優勝するにはUZQueenを倒すしかないのか……。"
2005505-87 = "まさかあの変な肩車の達人がUZQueenだったなんて……どうしような。"
2005505-88 = "肩車をしている相手の攻略法なんて、どこのサイトにも載ってなかったぞ！"
2005505-89 = "大丈夫、こういう時のために必勝法を調べてきたんだ。"
2005505-90 = "UZQueenじゃなくてThrones側――パートナーは普通のプレイヤーだから、あっちを先に倒せば勝機がある！"
2005505-91 = "よし……！"
2005505-93 = "せ、先生！気をつけてください！"
2005505-94 = "[ns] \"あれ、狙われてるのは私……？\""
2005505-97 = "（このゲームが現実だったら……）"
2005505-98 = "（この衣装も、みんなの視線も全然恥ずかしくなんてない……）"
2005505-99 = "（今、本当に気にしなきゃいけないのは……）"
2005505-100 = "……危ない！"
2005505-105 = "な、何が起きた……？"
2005505-106 = "私たち二人の弱点が、突かれた……？"
2005505-110 = "なんと！一瞬で勝負がつきました！#n「UZQueen&Thrones」の勝利です！"
2005505-111 = "い、今の見た？Thronesが狙われた瞬間、UZQueenがものすごい速さでふたりの弱点を……！"
2005505-112 = "速すぎて全然見えなかった……あれって現実でできる動きなの……？"
2005505-114 = "せ、先生。大丈夫ですか……？"
2005505-115 = "[s] \"私は大丈夫だよ。\""
2005505-119 = "[ns] \"今の攻撃、どうやったの？\""
2005505-120 = "わ、わたしにも分かりません……。"
2005505-121 = "先生が危ないって思ったら、手が勝手に動いちゃって……。"
2005505-122 = "気付いたら、相手の急所を狙っていました……。"
2005505-123 = "[s] \"すごい集中力だったよ……。\""
2005505-124 = "で、でも良かったです。#nこれでやっと「バーチャルボス」が手に入りますし――"
2005505-131 = "UZQueen、さっきの技をもう一度見せてくれませんか？"
2005505-132 = "……わ、私からもお願い！こんな技、実際にくらうの初めてで！"
2005505-133 = "私の身体で実践してもいいから――"
2005505-134 = "こっちもお願いします！その技を受けてみたい！"
2005505-135 = "わ、私もお願いします！"
2005505-136 = "UZQueen、私もぜひ！"
2005505-137 = "（な、なんだか変なお願いが殺到してる気が……）"
2005505-138 = "お願いです、UZQueen！"
2005505-139 = "UZQueenに殴ってもらえるなら、お金だって払いますから……！"
2005505-140 = "そ、それは困ります……！"
2005505-141 = "先生……助けてください……！"
2005505-142 = "UZQueen！UZQueen！"
2005505-147 = "せ、先生～！"
2005505-149 = "（その後、囲まれて困っているユズを抱えて、なんとか会場を抜け出した……）"
