[translation]
33190-364 = "Blue Archive"
33190-371 = "あ、雨雲が……。"
33190-378 = "[ns] \"ここに宣言する。\""
33190-380 = "[ns] \"私たちが、新しい[ruby=ETO]エデン条約機構[/ruby]。\""
33190-383 = "まさか……"
33190-397 = "……リーダー、ユスティナの統制がおかしくなってる。"
33190-411 = "こ、混乱してますね……[ruby=ETO]エデン条約機構[/ruby]を助けるというのが戒律、しかし今はETOが二つあって……。"
