[translation]
62010-1 = "第1話;名もなき奉仕活動部"
62010-3 = "救護が必要な予感を察知しましたので――#n救護騎士団一同、参りました！"
62010-8 = "どういう意味ですか！？"
62010-9 = "[s] \"言葉の通りというか……それが救護というか……。\""
62010-10 = "あの……よく分からないのですが……。"
62010-15 = "あっ、先輩！この方々は――"
62010-16 = "[s] \"ちょ、ちょっと待って！\""
62010-18 = "[ns] \"全員……集合！\""
62010-28 = "[ns] \"みんな集まったかな……？\""
62010-29 = "は、はい……。"
62010-30 = "先生、急にどうしたんだ……？"
62010-31 = "手を引っ張らずとも、言っていただければ参りますので……。"
62010-32 = "それで、どうしたの？#n先生がそんな顔するなんて、よっぽどのことだよね。"
62010-33 = "何かあったんですか？私が何か応援したら元気出ますか？"
62010-34 = "[s] \"……マイア。この子たちが誰か知ってる？\""
62010-39 = "それは、えっと……。"
62010-46 = "救護騎士団……の方々ですよね。"
62010-47 = "――トリニティの。"
62010-48 = "こんにちは。第４サンクトゥムの時ぶりだね。"
62010-49 = "あの時は何かとバタバタしていて、ご挨拶もできず……その節はお世話になりました。"
62010-50 = "すごい格好のシスターもいた気がするけど……今日は来てないんだね。"
62010-52 = "サクラコ様は救護騎士団ではなく、シスターフッドの――"
62010-57 = "い、今はちょっとお忙しくて！はい！#nえっと……試験前ですし！"
62010-59 = "あ、試験……皆さんもそうなんですね……。"
62010-63 = "……あれ？皆さんは勉強してなくていいんですか？"
62010-64 = "えっと、それは――"
62010-69 = "試験と同等に、救護の手を差し伸べることも重要事項ですので！"
62010-70 = "それに、救護騎士団の皆さんなら救護と試験を両立できると思っております。"
62010-71 = "信じること。#nそれもまた、救護の精神といえましょう。"
62010-72 = "もちろん私自身も常にトップを維持し続けております。"
62010-73 = "[s] \"すごいね！さすがミネだよ。\""
62010-77 = "そ、それほどでもありません……。"
62010-78 = "[s1] \"でも、ここではちょっとみんなにお願いがあって……。\"\n[s2] \"トリニティの救護騎士団であることを、伏せておいてほしいんだ。\""
62010-84 = "どうしてですか？"
62010-85 = "わざわざ隠す必要があるのでしょうか……？"
62010-92 = "団長、今は先生の言う通りにしましょう。"
62010-93 = "えっ？でも私たちは「救護」しに来たんですよね……？"
62010-94 = "「救護」のために、隠す必要があるんだと思います。"
62010-95 = "そう……なのですか？"
62010-96 = "えっと、経典にもあるじゃないですか。#n「右手のやることを左手に知らせてはならぬ」って。"
62010-97 = "その教えは理解しておりますが……。#n救護騎士団はシスターフッドのような秘密主義ではありません。"
62010-98 = "ですが、先生にもお考えあってのことでしょうから。#n今は従ったほうが良い気がするんです。"
62010-102 = "……そこまでおっしゃるのであれば、分かりました。#nそのようにいたしましょう。"
62010-103 = "[s] \"分かってくれて嬉しいよ。セリナも、ありがとね。\""
62010-107 = "お力になれて良かったです。"
62010-109 = "……理解はいたしました。"
62010-110 = "とはいえ、やはりこういう時にこそ救護の精神を広く伝えるべきだと思います。"
62010-111 = "なので、納得しきれない部分は多々ありますが……。"
62010-112 = "[s] \"無茶なお願いをしてごめんね。\""
62010-113 = "構いません。それが必要なことなのであれば。"
62010-117 = "トリニティや救護騎士団の呼称は使わないようにいたします。"
62010-118 = "[s] \"みんなも、それでお願いできるかな。\""
62010-128 = "わ、分かりました……。"
62010-129 = "あっ、でしたら団長に提案があるのですが……。"
62010-130 = "「団長」と呼ぶと、「救護騎士団」っぽさが出てしまうと思うんです。"
62010-131 = "なので、ここでだけは――「先輩」と呼ぶのはどうでしょうか？"
62010-132 = "それは……。"
62010-133 = "……たしかに、その通りですね。"
62010-134 = "では、そのようにお願いいたします。"
62010-135 = "はい！ミネ団――ミネ先輩！"
62010-139 = "ミネ……先輩……。"
62010-140 = "ミネ先輩……。"
62010-144 = "少し、馴れ馴れしいでしょうか……#nこ、ここだけにしますので！"
62010-145 = "いえ、大丈夫です。それに――"
62010-146 = "このほうが親しみやすくて……良いかもしれませんね。"
62010-151 = "おおよそ話はまとまったようだな。"
62010-152 = "善意のボランティア団体が、救護の精神を広めるためにアリウス分校を訪れた――"
62010-153 = "この認識で間違いないか？"
62010-154 = "はい、問題ありません。#nですが……。"
62010-155 = "スクワッドの皆さんもアリウスの方なのに……。#n私たちがご一緒して、その……大丈夫ですか……？"
62010-156 = "……うん。気にしないで大丈夫だよ。"
62010-157 = "それに、たしかにアリウス分校の生徒ではあるんだけど……。"
62010-158 = "はぐれ者だからね、今の私たちは。"
62010-160 = "……はぐれ者で済めばいいけど。"
62010-161 = "じゃあ……これで全部解決ってことですよね？よかったです！"
62010-162 = "ふふっ、ハナエさん……だっけ。これからよろしくね。"
62010-163 = "はい！！"
62010-164 = "……。"
62010-165 = "なんだかハナエさんを見てると、こっちまで元気をもらえる気がする……#nねえ、ちょっとの間、うちに来ない？"
62010-167 = "えっ？ええっ！？"
62010-168 = "！！！"
62010-169 = "……そうすると、そちらが寂しくなってしまいますよね。"
62010-170 = "よ、よろしくお願いします。セリナさん、ミネさん……。"
62010-171 = "せ、先生？これも救護……なのでしょうか……？"
62010-173 = "え？私はこれからアリウス生になるんですか？"
62010-174 = "ふふっ、冗談だよ。#nハナエちゃん、まっすぐで明るいから、つい……。"
62010-176 = "たしかに、ハナエちゃんは「元気いっぱいのアサガオ」って感じがしますもんね。#nでも、救護騎士団のなくてはならない存在なので、ごめんなさい。"
62010-177 = "えへへ……私は冗談だと分かってましたよ……！"
62010-182 = "うぅ……。"
62010-183 = "[s] \"……大丈夫？\""
62010-184 = "な、なんだかエネルギッシュな方々ですね……。"
62010-185 = "[s] \"慣れてないと大変だよね……。\""
62010-189 = "[ns] \"それで、これから何をするつもりなの？\""
62010-194 = "良い質問ですね。"
62010-195 = "活動のためには、まずは拠点が必要です。"
62010-199 = "救護騎――いえ、[ruby=・]名[/ruby][ruby=・]も[/ruby][ruby=・]な[/ruby][ruby=・]き[/ruby][ruby=・]奉[/ruby][ruby=・]仕[/ruby][ruby=・]活[/ruby][ruby=・]動[/ruby][ruby=・]部[/ruby]は、救護所の設営から始めたいと思います！"
62010-204 = "臨時救護所"
62010-206 = "完成です！"
62010-207 = "先生もミネ先輩も、お疲れ様でした。"
62010-208 = "先輩……。"
62010-212 = "え？良い手際だった……？#nもちろんです。慣れてますから！"
62010-217 = "お疲れ様です、先生。そして……。"
62010-224 = "……。"
62010-225 = "「ボランティア」の皆さん。"
62010-229 = "こんにちは。あなたは、さっきの……。"
62010-230 = "名乗るほどの者ではありませんよ。#nそれより、あなた方は何をしにアリウスまで？"
62010-231 = "す、すみません……。#n私たち、そういうのはちょっと……よく分かってなくて……。"
62010-236 = "え……？"
62010-237 = "……？"
62010-240 = "（何か言いかけた2人を、かろうじて止めた）"
62010-243 = "――つまり「救護が必要な予感」とやらを頼りに、ここまでいらした、と。"
62010-244 = "そ、それは……！"
62010-245 = "……。"
62010-246 = "何か、問題でもありましたでしょうか？"
62010-247 = "団ち――先輩……！？"
62010-248 = "いえ、問題というほどでは。#nただ……とても勇敢だな、と思いまして。"
62010-249 = "どんな危険があるかも、何が起こるかも分からない場所に――"
62010-250 = "ただ「可哀想に見えるから」と無鉄砲に入り込んでいるのですから。"
62010-251 = "何をおっしゃるかと思えば……そうですね、そうも見えるでしょう。#nですが、事情はもっと単純です。"
62010-255 = "はい？"
62010-256 = "私達の行動はすべて「救護」のために行っているのですから。"
62010-257 = "救護……？"
62010-258 = "救護の足りぬ場に救護を。#n満たすだけでなく、溢れ返るほどに注ぎ込み――"
62010-259 = "一人でも多く、悲しみと苦しみから救い出すこと。"
62010-260 = "それこそが救護活動――私達のボランティアの理念です。"
62010-261 = "そこに、危険であるかどうか、私達がどのように映るかなど関係ありません。"
62010-263 = "あ、あはは……。"
62010-264 = "さすが先輩です……！"
62010-269 = "……。"
62010-270 = "なるほど、噂に違わぬ方々ですね。"
62010-275 = "（噂……？）"
62010-279 = "トリニティの――救護騎士団の皆さん。"
62010-280 = "[s] \"！？\""
62010-281 = "は、はいっ！？あっ、いやっ、私たちは、その、あの……！"
62010-282 = "無理して取り繕わなくていいですよ。"
62010-283 = "……気づかないとでも思っているんですかね。#nトリニティの気配を。"
62010-284 = "……。"
62010-285 = "お互い、回りくどい話はやめにしましょう。#n長々と議論したところで、疲れるだけですから。"
62010-286 = "結論から申し上げますと、身分を伏せてボランティア活動に徹すると言うならば、事を構えるつもりはありません。"
62010-287 = "ただし――"
62010-288 = "あなた方が「ティーパーティー」や「シスターフッド」の回し者でなければ……#nですが。"
62010-289 = "……まぁ、トリニティの中でも特異な組織であるとは聞いていますので。"
62010-290 = "よく……ご存知なんですね。"
62010-291 = "おかしな話ではないと思いますよ。"
62010-292 = "元を辿れば……私たちは一つの学園だったじゃないですか。"
62010-293 = "……！"
62010-294 = "ともあれ、秘密は秘密のままに。#nそれであれば、とやかくは言いません。"
62010-295 = "お約束いただけますか？"
62010-301 = "……分かりました。その条件であれば。"
62010-302 = "ありがとうございます。"
62010-303 = "……それにしても、あなた方の団長さんはいらしていないようですね。"
62010-304 = "まぁ、大所帯を束ねている以上、すべての活動に顔を出す訳にもいかないのでしょう。"
62010-305 = "！？"
62010-306 = "えっ？あ、それは……。"
62010-307 = "そ、そうです！団長はお忙しいので！#nそれで今回の件を、私たちに任せてくださったんです！あはははは……！"
62010-308 = "そ、そうです、ね。#nそう、ということに……いえ、そうなのですよ。"
62010-312 = "何か事情があるようですが……これはこれで良かったのではないでしょうか。"
62010-316 = "自分が正しいと思ったら、遮るものを全て跳ねのけてでも突き進むような方だ、と聞いていますし。"
62010-317 = "この場に居合わせていたかもしれない……そう考えるだけで恐ろしいです。"
62010-321 = "……少し、誤解があるようですね。"
62010-322 = "救護騎士団の……団長、様は、救護の精神を広めるためならば、他の全てを犠牲にできる方です……！"
62010-323 = "それはつまり……石のように頑固で融通が利かない、ということでは？"
62010-324 = "言葉選びは慎重になさることをお勧めします。#n確固たる意志を、まるでただの重しかのように言うのは――"
62010-325 = "この場にいない方に対して、礼を欠いた行為かと。"
62010-326 = "救護騎士団の皆さんは互いへの信頼が厚いそうですが……#nええ、よく伝わってきます。"
62010-327 = "分かりました。この話はここまでにしておきましょう。"
62010-328 = "これ以上私がここにいたら、皆さんの「ボランティア」の邪魔になりそうですし。#nそろそろ失礼します。"
62010-329 = "ああ、何か助けが必要なときは……#nそうですね、気軽にお声がけください。"
62010-335 = "み、ミネ先輩……。"
62010-336 = "ミネ先輩……。"
62010-338 = "……。"
62010-339 = "セリナ、ハナエ。私は大丈夫です。救護活動に尽力できるのですから。#nこういう時こそ、初心を疎かにせず活動に徹するべきです。"
62010-342 = "は、はい……！"
62010-347 = "ですが……その前に少しだけ。#n申し訳ありませんが、休憩をいただいてもよろしいでしょうか……？"
62010-352 = "もちろんです！こちらのことは心配しないでください！#n……ハナエちゃん、ちょっと手伝ってくれる？"
62010-353 = "はい！任せてください！"
62010-358 = "……。"
62010-359 = "[s] \"大丈夫……？\""
62010-363 = "もちろんです。私は……。"
62010-364 = "……。"
62010-365 = "いえ……先生に隠し事をしても、きっと意味はありませんね。"
62010-369 = "……終わりが見えない。けれど[ruby=かろ]辛[/ruby]うじて抑え込まれている怒り。#nそれを前にして……果たして、私に何ができるのでしょうか。"
62010-370 = "[s] \"……そんな風に感じたんだね？\""
62010-371 = "……はい。"
62010-372 = "――これも救護である。"
62010-373 = "私はそう考えています。"
62010-374 = "……あの方々の憎しみを受け止めることも、その一つです。"
62010-381 = "ですが、その感情が留まり続ける限り、何も変わりません。"
62010-382 = "……一方的な救護は、やがて意味を失ってしまいます。"
62010-383 = "これは持論ですが……ある程度[ruby=・]説[/ruby][ruby=・]得[/ruby][ruby=・]さ[/ruby][ruby=・]れ[/ruby][ruby=・]る[/ruby][ruby=・]準[/ruby][ruby=・]備[/ruby][ruby=・]が[/ruby][ruby=・]で[/ruby][ruby=・]き[/ruby][ruby=・]て[/ruby][ruby=・]い[/ruby][ruby=・]る[/ruby]相手でなければ、説得することはできません。"
62010-384 = "誰かに止めてほしいと願いながら、けれど限界まで突き進んでしまう。#n……そんな方もいますから。"
62010-388 = "……？#n……先生？……大丈夫ですか？顔色が……。"
62010-389 = "[s3] \"あ、うん……あの時、私はしっかりできなかったから……。\"\n[s4] \"ちゃんと最後まで気を配ってあげるべきだったのに。\""
62010-392 = "……そんなことはありません。"
62010-393 = "先生は最善を尽くされました。それは私が保証します。"
62010-394 = "ですが……今、私には何ができるのか、分からなくなってしまい……。"
62010-395 = "私は、救護騎士団である以前に、トリニティの生徒です。#nアリウスのことを「理解できる」とは到底――"
62010-396 = "それを口にすれば、アリウスの皆さんの怒りを買うでしょう。"
62010-397 = "「理解」という言葉を口にすること自体、傲慢なのかもしれません。"
62010-402 = "……それでも信じたいのです。#n私たちは、互いに理解し合うことができるのだと。"
62010-403 = "そう信じて行動すれば……明日は、きっと今日より良い日になります。#nたとえ、それがほんの少しずつの変化で、僅かな可能性だったとしても。"
62010-404 = "それでも、私は……。"
62010-405 = "[s] \"ミネがそんな顔をしているの、初めて見た。\""
62010-406 = "ふふっ、そうですか？"
62010-407 = "それをいうのなら……先生もどこか、普段と違う気がします。"
62010-412 = "……一つ、お尋ねしてもいいですか？"
62010-413 = "全てに絶望しきった時……それでも自分を支えてくれるもの。#nそれは……何なのでしょうか。"
62010-414 = "[s] \"……。\""
62010-417 = "先生、あの……。"
62010-418 = "もし仮に、誰かが……。"
62010-422 = "本当に、本当に、本当に……#n自分の人生を諦めたいと願っていたら。"
62010-423 = "その人を止める術はあるのでしょうか……。"
62010-426 = "[ns] \"その人が信じているもの……かな。\""
62010-427 = "信じているもの、ですか？"
62010-428 = "ふふ……ちょっと意外でした。#n先生でしたら……そうですね。"
62010-429 = "もっと「理性的」なものを挙げられるかと思っていました。"
62010-430 = "[s5] \"人を突き動かすのは、感情であり、信念だからね。\"\n[s6] \"理屈で割り切れるとは限らないんだよ。\""
62010-435 = "[ns7] \"それが、偉大な存在への信仰でも。\"\n[ns8] \"……自身の内側にある何かへの信頼だとしても。\""
62010-438 = "……なるほど。"
62010-439 = "感情とは……人を縛る鎖ではなく、行動のトリガーとなり得るものである、と。"
62010-440 = "たしかに感情は判断に影響を与えやすいです。#n先生はそれを、深層意識に紐づいているものだからとお考えなのですね。"
62010-441 = "……そうですね。それこそ「授業」なのかもしれません。"
62010-442 = "……。"
62010-443 = "[s9] \"だからこそ、これまで歩んできた道が――\"\n[s10] \"間違っていなかったのだと思えるなら。\""
62010-446 = "……その道を信じて進めばいい、ということですか？"
62010-447 = "ですが、その道が本当に正しいかどうかは……誰にも分からないのでは？"
62010-448 = "[s11] \"それは、自分で証明していくしかないんだ。\"\n[s12] \"……私も、多少なりそうしてきたつもりだよ。\""
62010-451 = "先生が……何の証明を……？"
62010-452 = "[s13] \"助けを求める生徒の声に背を向けたら――\"\n[s14] \"教師を名乗る資格はないってこと。\""
62010-455 = "……！"
62010-456 = "ふふっ……先生はそういう方でしたね。"
62010-457 = "そんな先生に、救われた生徒はたくさんいます。"
62010-463 = "本当に……ありがとうございます。"
62010-468 = "（ミネが、静かにもたれかかってきた……）"
62010-469 = "すみません……少しだけ。"
62010-470 = "長くお時間はとらせませんので……。"
62010-471 = "……しばらくの間、こうさせてください。"
62010-475 = "（目を閉じたミネは、穏やかな表情をしていた）"
62010-476 = "（時が止まったように感じたその瞬間――）"
62010-482 = "今の音は……？#n先生にも聞こえましたか？"
62010-483 = "[s] \"うん。何の音だろう……？\""
62010-489 = "い、今のって、ラッパ……でしょうか？#nすごい音でしたね！"
62010-491 = "アリウス側の……何かの「合図」なのでしょうか？"
62010-492 = "分かりません。でも――"
62010-493 = "ちょっとだけ、嫌な感じがします……。"
62010-495 = "先輩、どうしますか……？"
62010-500 = "……。"
62010-501 = "それでも。"
62010-505 = "私たちは、やるべきことをやりましょう。"
62010-507 = "次回;ラッパの音"
