[translation]
62020-1 = "第2話;ラッパの音"
62020-100 = "そもそもまともな学園にいたら、あんな事件起こすはずないし……。"
62020-104 = "色々……あったんです。"
62020-105 = "アリウスの外で……。"
62020-11 = "いっぱいあるけど……これ、何ですか……？"
62020-110 = "……。"
62020-111 = "ひ、ひええ……やっぱり、やっぱり大人って怖いです……#n世の中は残酷ですね……。"
62020-112 = "あれ？でもよく考えたら、先生も大人ですよね……？"
62020-113 = "[s9] \"そうだね……。\"\n[s10] \"だから、一人の大人として謝るよ。\""
62020-118 = "え？せ、先生が……そこまでしなくても……。"
62020-119 = "そこまで……。"
62020-123 = "……くすん……うぅっ……。"
62020-124 = "……まぁ、あなたのせいじゃないよ、知らないけど。"
62020-125 = "外の世界は大概だから。"
62020-126 = "ミ、ミサキさん……。"
62020-127 = "大人と世界が全部悪いって思えば、楽になるかもしれないね。"
62020-128 = "そんな単純に割り切れるものでもないけど。"
62020-129 = "……。"
62020-13 = "こちらは「栄養治療食」です。"
62020-130 = "だから、無視すればいいよ。"
62020-131 = "受け入れられる部分だけ、受け入れる。#nそうじゃないと保たないし。"
62020-132 = "この世界なんてロクなものじゃないんだから。"
62020-133 = "私だって、生きなきゃいけない理由は分かんないけど……。"
62020-134 = "……。"
62020-135 = "でも、先生が「生きてみろ」って言うから。#n今、ここにいる。"
62020-141 = "……ふふっ。"
62020-142 = "え、えへへ……。"
62020-143 = "ああ。"
62020-148 = "……何？その反応。"
62020-149 = "[s] \"ミサキ……立派になって……ぐすん。\""
62020-153 = "先生は黙ってて！#n感動するフリとかもいいから。"
62020-154 = "というか先生、自覚あるの？あなたが一番問題なんだけど。"
62020-155 = "え……？そ、そうなんですか？"
62020-156 = "そう、一番[ruby=たち]質[/ruby]が悪い。"
62020-157 = "勝手に希望を見せてくるくせに、全部ウソってわけじゃないとこが厄介なの。"
62020-158 = "……全部ウソなら、諦められたのに。"
62020-159 = "気をつけてね。この人、釣った魚に餌をやらないタイプだから。"
62020-160 = "あなたも用心しておくに越したことないよ。"
62020-161 = "そ、そうなんですね……。"
62020-162 = "[s] \"え？じゃあ、一生一緒にいようか？\""
62020-165 = "なんでそういう言い方になるの！"
62020-170 = "……。"
62020-171 = "虚しい……全てはただ、虚しいだけだ……。"
62020-172 = "サッちゃん？"
62020-173 = "[s] \"……？\""
62020-174 = "耳にタコができるほど聞いた言葉だが……誤解されることも多かったと思ってな。"
62020-175 = "すべてのものはいずれ過ぎ去る……だから、無理をする必要はない。#n本来はその程度の意味なんだ。"
62020-176 = "私も、お前たちも……すべては等しく過ぎ去っていく。"
62020-177 = "けれどいつか振り返って、「あの時はそんなこともあったな」と、笑いあえる日が来るかもしれない。"
62020-178 = "もちろん……そうはならない可能性もある。"
62020-179 = "分からないから未来なんだ。#n一つの考えに固執するのは、あまり褒められたことじゃない。"
62020-18 = "メディカルチェックの結果、皆さんは全体的に栄養が不足気味であると判断しました。"
62020-180 = "……確定させるべき未来なんて、仕事の対価くらいだろう。"
62020-182 = "ふふっ。それは本当に大事だね。"
62020-183 = "えへへ……。"
62020-19 = "栄養失調というほどではありませんが、摂取するものが飽和脂肪酸と糖質に偏っている点も気になります。"
62020-190 = "！？"
62020-192 = "！！！"
62020-193 = "[s11] （この音……ラッパ……？）\n[s12] （これで……たぶん4回目……？）"
62020-198 = "す、すみません！#n今、外が……大変なことになってます！"
62020-20 = "そして、これは栄養不足を改善するために作られたものでして――"
62020-203 = "皆さん、落ち着いてください！#nパニックになると、かえって危険です！"
62020-209 = "何があったんだ？"
62020-21 = "栄養価が高く、1パックで500kcalあります。"
62020-214 = "[ruby=じょうまえ]錠前[/ruby]サオリ……。"
62020-215 = "……。"
62020-216 = "あそこを見てください。"
62020-22 = "ですので、こちらをお渡ししました。#nビタミンやミネラル、食物繊維が豊富に含まれていますので、今の皆さんに最適な食事かと。"
62020-227 = "何……あれ？"
62020-228 = "……分かりません。先ほど、突然姿を現しました。#n攻撃は通るようですが、効果は薄いです。"
62020-23 = "味についてはご心配なく。香ばしくてほんのり甘いですし、やわらかいので食べやすいですよ。"
62020-232 = "（この気配……前にラッパの音が聞こえた時に見た「アレ」と同じ……？）"
62020-233 = "（あれは、まさか……？）"
62020-234 = "なにあれ……？ラッパの後に出てきたよね？#n4体もいるんだけど……。"
62020-235 = "え？ラッパ？私には何も聞こえなかったけど……？"
62020-236 = "は？すっごい大きな音だったじゃん。"
62020-237 = "せ、先輩は？先輩は聞こえましたか？"
62020-24 = "1日2〜3個を目安に召し上がってください。"
62020-242 = "いえ、私も特には……。"
62020-244 = "ほらね！"
62020-245 = "……なんか、変じゃない？"
62020-255 = "うわああっ！？こっちに向かって来ます！"
62020-26 = "あ、ありがとうございます……。"
62020-267 = "皆さん、私たちの後ろに下がってください！！"
62020-269 = "うわっ！？"
62020-27 = "こちらは「簡易浄水ストロー」です！"
62020-275 = "大丈夫ですか？ケガをした方はいませんか？"
62020-276 = "準備はバッチリです！団ちょ――先輩！"
62020-278 = "それでは……。"
62020-279 = "……。"
62020-28 = "汚い水でも、飲める水に変えてくれるすごいアイテムなんですよ！"
62020-283 = "私たち「名もなき奉仕活動部」が、皆さんをお守りします！"
62020-285 = "私たちも行くぞ。"
62020-286 = "まぁ……そうなるよね。"
62020-287 = "母校を守ると思えばいい。あれが何であろうと関係ない。"
62020-29 = "使い方は簡単！ストローの先を水たまりに差して、そのまま吸うだけです！"
62020-292 = "……。"
62020-293 = "み、皆さん、気をつけてくださいね……！"
62020-3 = "は～い！ここから持っていってくださ～い！"
62020-30 = "ただし！注意点が2つあるので覚えておいてください。"
62020-31 = "1つ目、水はゆっくり吸って飲むこと！"
62020-32 = "2つ目、塩分やウイルスなど……取り除けないものもあるので、過信しないこと！"
62020-33 = "……って、先輩が言ってました！"
62020-35 = "これがあれば……雨が降るたびに水を集めに走ったり……水たまりの水をそのまま飲んで、お腹を壊したりしなくて済む……ってことですか！？"
62020-36 = "はい、そのとおりです。#n他にも、救急セットもありますよ。"
62020-37 = "中に、30種類の救急用品が入っています。"
62020-38 = "そんなにですか！？"
62020-39 = "消毒薬やガーゼはもちろん、小型の懐中電灯と電池、カイロ、アルミブランケットなど――"
62020-4 = "数は十分あるので、順番に並んでくださいね！"
62020-40 = "[ruby=私たち]名もなき奉仕活動部[/ruby]の[ruby=・]標[/ruby][ruby=・]準[/ruby][ruby=・]仕[/ruby][ruby=・]様[/ruby]の救急セットです！"
62020-42 = "これが標準だなんて……すごすぎる……。"
62020-45 = "驚いたな。まさかこんな所でまで授業をするとは……。"
62020-46 = "[s] \"学びの道に、終わりや制限なんてないからね。\""
62020-47 = "そ、そうか……。"
62020-48 = "でも……勉強に意味はあるんでしょうか……？"
62020-49 = "数学なんて特に……二次関数とか微積分とか……。"
62020-50 = "[s1] \"数学そのものが直接役立つことは、あまりないかもしれない。\"\n[s2] \"でも、数学的に考えるクセは、きっと助けになるよ。\""
62020-53 = "数学的に考える……？どういう意味ですか？"
62020-55 = "それ、私も気になるかも。"
62020-56 = "私は……なんとなく分かる。"
62020-57 = "……数学は、状況を数値で正確に表現しようとする。"
62020-58 = "だから数学を学ぶ人は、問題の原因と結果を明確に定義して、そのプロセスを説明できるようになる……ってことじゃないの？"
62020-59 = "そっか。そうすれば色んな根拠とか命題を組み合わせて、「だからこうなる」って筋道を立てて考える力がつくんだね。"
62020-61 = "パッと見はバラバラでも、秩序やルールを見つけられるようになったりとか……？"
62020-62 = "でも……。それって結局役に立つんですか？"
62020-63 = "[s3] \"他人を説得しやすくなるんだ。\"\n[s4] \"理屈が通ると、納得しやすいからね。\""
62020-68 = "[ns5] \"だから、数学を勉強することにも意味があるんだよ。\"\n[ns6] \"数学的思考に慣れるためにね。\""
62020-71 = "[ns7] \"しかも、それだけじゃなくて――\"\n[ns8] \"数学ができたらちょっとカッコいいよね！\""
62020-74 = "なるほど……。"
62020-75 = "……。"
62020-76 = "それは……いいですね。"
62020-77 = "あの時も……。"
62020-81 = "もし、そうやって考えられてたら……。"
62020-82 = "あんな思い、しなくて済んだのかな……。"
62020-83 = "何があったの？"
62020-87 = "そ、それは……。"
62020-97 = "アリウス？ああ、エデン条約のときに騒ぎを起こしたんだっけ？"
62020-98 = "そんな問題児が、なんでこんなところに……？ "
62020-99 = "これだから育ちの悪い子は……。"
