[translation]
62030-1 = "第3話;信じているもの"
62030-2 = "きゃあっ！"
62030-3 = "うわああんっ！？"
62030-4 = "アツコ、下がって！"
62030-8 = "くっ……！？"
62030-10 = "ミサキさんっ！？"
62030-17 = "うぐっ……！？"
62030-18 = "危険です！"
62030-26 = "ミネさんっ！？"
62030-27 = "ぐっ……！？"
62030-41 = "（これは……？）"
62030-42 = "（底知れない沼に、沈み込んでいくような……！）"
62030-47 = "――！！"
62030-54 = "それは、異なる解釈によるものだった。"
62030-55 = "見る者によっては単純で――"
62030-56 = "見る者によっては取るに足らないことだった。"
62030-59 = "彼女たちは、自分こそが「真理を解する者」だと信じていた。"
62030-60 = "「正しき者」であることの証明をしたがっていた。"
62030-61 = "しかし、それを掲げることは、他のすべてに「誤り」のレッテルを貼ることである。"
62030-64 = "公会議の決議をここに宣言する。"
62030-71 = "アリウスに、今より永劫の破門を言い渡す。"
62030-72 = "――聖なる魂の名において。"
62030-79 = "[log]それが、[/log]"
62030-81 = "[log]果てなき迫害の始まりであった。[/log]"
62030-84 = "（これは……アリウスの……）"
62030-91 = "道はなかった。故に我らは、傷だらけの手で進む先をこじ開けた。"
62030-92 = "光は我らから去り、こだまする[ruby=どうこく]慟哭[/ruby]の中に身を沈めた。"
62030-93 = "天の最も高きところから、地の最も低きところに至るまで――"
62030-94 = "[ruby=彼女たち]トリニティ[/ruby]は、私たちを「存在しなかったこと」にしようとした。"
62030-97 = "故に「生き延びる」ことが唯一の抵抗となり、崇高となった。"
62030-98 = "されど、外に向けられぬ憎しみは、自らに還る他なかった。"
62030-104 = "多くの者が消えた。"
62030-105 = "消える必要のない者が消え――"
62030-106 = "憎み合う必要のなかった者たちが、憎しみ合った。"
62030-111 = "[log]その果ては――[/log]"
62030-113 = "[log][ruby=Vanitas vanitatum et omnia vanitas]全ては虚しい。どこまで行こうとも、全てはただ虚しいものだ[/ruby]。[/log]"
62030-116 = "……！"
62030-119 = "[ruby=トリニティ]追放した者たち[/ruby]は言った――#nお前たちは、なるべくして追放されたのだ、と。"
62030-120 = "[ruby=トリニティ]追放した者たち[/ruby]は言った――#nお前たちは、自らその結果を招いたのだ、と。"
62030-121 = "[ruby=トリニティ]追放した者たち[/ruby]は言った――#nお前たちは、そうあるべくして苦しんでいるのだ、と。"
62030-123 = "だが、ここに述べる。"
62030-124 = "初めからそうあるべき者など、どこにも存在しない。"
62030-127 = "[ruby=トリニティ]追放した者たち[/ruby]は答えねばならない――#n自らの作った過去がなければ、[ruby=アリウス]追放された者たち[/ruby]はどこに立っていたのか。"
62030-128 = "[ruby=トリニティ]追放した者たち[/ruby]は答えねばならない――#n自らの紡いだ歴史がなければ、[ruby=アリウス]追放された者たち[/ruby]はどんな明日を夢見られたのか。"
62030-129 = "[ruby=トリニティ]追放した者たち[/ruby]は答えねばならない――#n自らの撒いた憎しみがなければ、[ruby=アリウス]追放された者たち[/ruby]はどんな愛を与えられたのか。"
62030-134 = "ごめんなさい……ゆるして……ごめんなさい……。"
62030-135 = "ごめんなさい……ごめんなさい……もう二度としませんから……！"
62030-136 = "……！"
62030-141 = "希望を抱くことが、罪とされる世界がある。"
62030-142 = "幸せになりたいと願う子どもが、罰を受ける世界がある。"
62030-143 = "もう二度と逆らいません……希望なんて、持ちません……。"
62030-144 = "もう二度と、幸せになりたいなんて、願いません……#nそんなこと……しませんから……。"
62030-146 = "その世界では慈悲すらも、意味を失い色褪せる。"
62030-147 = "お願いです……どうかご慈悲を……。"
62030-148 = "ご慈悲を……。"
62030-151 = "答えるがいい。"
62030-152 = "子どもたちを消し去ったその真理に、いかなる威徳が宿るというのか。"
62030-153 = "飢えをしのぐために盗みを働く子どもがいる。凍えた手足を息で温める子どもがいる。その涙の前で、いかなる正しさが標榜できるというのか。"
62030-154 = "人生とは無意味な苦痛しかない。そう語る子どもの前で――いかなる正義が、公平を語れるというのか。"
62030-155 = "それ、は……。"
62030-156 = "答えるがいい！"
62030-157 = "お前には答える義務がある。"
62030-158 = "すべての「[ruby=いま]現在[/ruby]」は、「過去」を礎にして築かれる。"
62030-160 = "それはただの「異なる解釈」だった。#n単純で、些細で、意味すらなかった。"
62030-161 = "だが、それがすべての憤怒と憎悪の導火線となった。"
62030-162 = "この地の子どもは、誰よりも死に近づいた。"
62030-163 = "[ruby=お前]追放した者[/ruby]は、何を以って生きていこうとするのか――"
62030-164 = "答えるがいい！！"
62030-169 = "私、には――"
62030-170 = "答えられ……ません。"
62030-171 = "それは、そもそも答えがあってはならない……そういう、問いですから……。"
62030-172 = "ぐすっ……。"
62030-173 = "ううっ……うううっ……。"
62030-183 = "[log]天の星も月も、[/log]"
62030-185 = "[log]己の罪に耐えきれず、その光を隠した。[/log]"
62030-188 = "[log][ruby=Quovadis,Domine.]何処へ行かれるのですか？[/ruby] [/log]"
62030-201 = "[log]……一つ、[/log]"
62030-203 = "[log]お尋ねしてもいいですか？[/log]"
62030-207 = "[log]全てに絶望しきった時……[/log]"
62030-209 = "[log]それでも自分を支えてくれるもの。[/log]"
62030-211 = "[log]それは……何なのでしょうか。[/log]"
62030-215 = "（これは……？）"
62030-216 = "（ああ……私はあのとき、先生に問いかけて……）"
62030-217 = "（そして先生は、なんと……？）"
62030-220 = "\"その人が信じているもの……かな。\""
62030-221 = "\"人を突き動かすのは、感情であり、信念だからね。\""
62030-222 = "\"理屈で割り切れるとは限らないんだよ。\""
62030-226 = "\"それが、偉大な存在への信仰でも。\""
62030-227 = "\"……自身の内側にある何かへの信頼だとしても。\""
62030-228 = "（けれど、先生）"
62030-229 = "（私は今、何を信じればよいのでしょうか）"
62030-230 = "（教えてください、先生）"
62030-231 = "（[ruby=私たち]トリニティ[/ruby]が生み出してしまった悲しみと惨禍に対して、私たちは……一体何ができるのでしょうか……？）"
62030-236 = "[log]……信じることをしなさい。[/log]"
62030-240 = "（先生……？そのようなことはおっしゃっていなかったはず……）"
62030-243 = "[ruby=・]信[/ruby][ruby=・]じ[/ruby][ruby=・]て[/ruby][ruby=・]き[/ruby][ruby=・]た[/ruby]こと。"
62030-244 = "そして、ミネを支え、歩ませ、生かしてきたもの。#nそれを信じなさい。"
62030-246 = "（いいえ……）"
62030-247 = "（先生ならきっと、こうおっしゃってくださるはず……！）"
62030-250 = "私たちは、過去を変えることはできない。"
62030-251 = "でもそれは、「現在」を生きない理由には決してならない。"
62030-254 = "その歩んできた道が、間違っていないと信じるのなら――"
62030-255 = "道を貫くことで、自分を証明しなさい。"
62030-256 = "（私が、歩んできた道）"
62030-257 = "（それは……）"
62030-262 = "[log]助けを求める声に、[/log]"
62030-264 = "[log]耳を塞ぐなら――[/log]"
62030-266 = "[log]自身は、何者であるというのか。[/log]"
62030-270 = "……！！"
62030-271 = "（……そうですね。[ruby=あなた]先生[/ruby]は、きっと……！）"
62030-275 = "……。"
62030-276 = "失礼いたしました。……あなたの問いに、お答えいたします。"
62030-277 = "ですがこれは、完璧な回答ではないかもしれません。"
62030-278 = "それでも……「何を以って生きていこうとするのか」という問いには足りるかと。"
62030-280 = "……この世界は悲しみに満ちています。#nそれは、揺るぎない事実。"
62030-281 = "現在は、過去を礎に築かれる。それもまた、疑いようもありません。"
62030-284 = "ですが……私の拙く、取るに足らない行為であっても――"
62030-285 = "その悲しみを、たとえ一匙でも減らすことができるのなら。"
62030-286 = "私は……それ以上、何も望みません。"
62030-292 = "守るべきものがある。"
62030-293 = "見返りなど望まない。"
62030-294 = "信じたことを為す。"
62030-295 = "それこそが、誇りなのだから。"
62030-299 = "誇りと信念を胸に刻み――"
62030-302 = "振り返れば、どこにでも救いを求める声があった。"
62030-303 = "けれど、その全てには応えられなかった。"
62030-304 = "なぜ身体は一つしか持てないのか。"
62030-306 = "私にできるのは……"
62030-307 = "少しでも多く、その声に耳を傾けること。"
62030-309 = "せめて、手の届く範囲だけでも――この手を差し伸べること。"
62030-310 = "その小さく、人によっては取るに足らない選択が積み重なって――"
62030-311 = "ほんのわずかでもいい。"
62030-316 = "いつか皆が、より広い世界へと歩み出せるように。"
62030-319 = "――救護が必要な場に救護を。"
62030-326 = "皆さん、私の後ろに下がってください！"
62030-331 = "団長！？"
62030-332 = "団長！！"
62030-337 = "これより救護騎士団が、皆さんをお守りします！"
