[translation]
62040-1 = "第4話;思い託して"
62040-5 = "[ns] \"ミネ！！\""
62040-6 = "だ、団長……！"
62040-7 = "うわぁぁん！"
62040-8 = "……呼吸に大きな異常はありません。#nハナエちゃん！まずは気道の確保を！"
62040-9 = "はいっ！首元と腰の服を緩めて……あっ、あと担架持ってきますね！"
62040-10 = "お願いします！"
62040-15 = "い、今の……聞こえた？"
62040-16 = "うん……たしかに、救護騎士団って……！"
62040-21 = "私たちを助けてくれてたのは、トリニティだったってこと……？"
62040-22 = "団長って呼ばれてた人、見たことあるかも！#nいつだっけ……そうだ！「マダム」がアリウスから姿を消した日の……！"
62040-23 = "そうなの？#nあの日、私いなかったから……。"
62040-24 = "それがさ……。"
62040-39 = "これから私が生み出す負傷者も、速やかに救護し治療するようお願いします。"
62040-42 = "ひ、ひぃっ……！ひいぃぃいっ……！"
62040-43 = "き、急にどうしたの！？"
62040-48 = "[log]わざわいだ[/log]"
62040-52 = "[log]わざわいだ[/log]"
62040-56 = "[log]わざわいだ[/log]"
62040-59 = "[log]地に住む人々は、わざわいだ。[/log]"
62040-63 = "[log]なお三人の御使がラッパを吹き鳴らそうとしている。[/log]"
62040-65 = "！！！"
62040-66 = "！！！"
62040-68 = "い、今の……何！？"
62040-69 = "空から聞こえた気がする……。"
62040-71 = "わざわいだ……？"
62040-72 = "三人の御使がラッパを吹き鳴らそうとしている……？"
62040-78 = "！！！"
62040-83 = "ま、まさか……[ruby=・]あ[/ruby][ruby=・]れ[/ruby]？"
62040-84 = "そんな訳ないって！あれは「黙示録」に書いてあるだけの……！"
62040-86 = "でも、黙示録だよ？私たちアリウスが一番……。"
62040-87 = "もし本当に[ruby=・]そ[/ruby][ruby=・]う[/ruby]なら……#nそれが、ここで起きてるなら……！"
62040-92 = "間違いない。あれは……。"
62040-93 = "――黙示録の天使だよ！"
62040-94 = "……「世界の終わり」が始まったんだ……！"
62040-96 = "[ns1] \"今のは……？\"\n[ns2] \"みんなは何か知ってる……？\""
62040-99 = "……。"
62040-100 = "……。"
62040-101 = "あれは、まさか……！"
62040-102 = "そんなはずは……でも……。"
62040-103 = "[s] \"アツコ？\""
62040-104 = "……。"
62040-105 = "ごめんね。私たちも、まだ推測しかできないの。#nそれに、今は……。"
62040-106 = "救護騎士団の人たちを安全な場所に移さないと。"
62040-107 = "[s] \"……セリナ！ミネは大丈夫？\""
62040-111 = "はい、命に別状はありません！ですが……。"
62040-112 = "せ、先輩？先生……？"
62040-119 = "[ns] \"スクワッド！\""
62040-121 = "……了解。#n道を開けるぞ！"
62040-122 = "チッ。"
62040-124 = "そ、そういうことなので……すみませんね……#nえへへっ……。"
62040-130 = "先輩、どうしますか……？"
62040-135 = "……。"
62040-136 = "皆さん、通してあげてください。"
62040-137 = "……少なくとも、今だけは。"
62040-143 = "……分かりました。"
62040-150 = "[ns] \"みんな、ありがとう。\""
62040-151 = "礼には及ばない。先生の役に立てたのならなによりだ。"
62040-152 = "救護騎士団のみんなも、ありがとう。"
62040-154 = "い、いえ、こちらこそ……。"
62040-155 = "本当に……もうダメかと思いました……。"
62040-159 = "[ns] \"それから……急に呼び出してごめんね。\""
62040-162 = "問題ありません。これは、救急医学部の役目ですから。"
62040-163 = "救護騎士団の皆さんとは現場を共にしたこともありますし。"
62040-167 = "それはそれとして、この方の状態は……。"
62040-168 = "セナさん……。"
62040-170 = "……。"
62040-171 = "[s] \"どうしたの……？\""
62040-172 = "どうお伝えすべきか……。"
62040-173 = "まず、バイタルに異常はありません。それだけは確かです。"
62040-174 = "昏睡状態が長いようにも思いますが、まだ想定の範囲内です。#nただ……。"
62040-175 = "……。"
62040-176 = "これは私の「直感」に近いものです。"
62040-177 = "現場に身を置く者としての……経験則とでも言いましょうか。"
62040-178 = "……あまり、良い予感がしません。"
62040-180 = "……！"
62040-181 = "だ、団長っ……！う、うえええええん……！"
62040-182 = "具体的に、ですか……？"
62040-183 = "申し訳ありませんが、私も……はっきりとは言えません。"
62040-184 = "良くない状況である……という直感だけが働いています。"
62040-185 = "……とにかく、私たちにできることを続けます。#nですので……。"
62040-186 = "はい、分かっています。我々の車で、救護騎士団本部まで搬送しましょう。"
62040-187 = "で、でも救急医学部の車は、ちょっと危ないんじゃ……？"
62040-188 = "すでに前例がありますので、問題はないでしょう。#nでは――"
62040-193 = "せんせ……い？"
62040-194 = "！"
62040-196 = "！！！"
62040-197 = "団長！？意識が戻ったんですか！？"
62040-203 = "……すみません、ハナエ。#n少しだけ、声を抑えていただけると……。"
62040-204 = "は、はいっ！あっ……！"
62040-205 = "こ、こんな感じで……大丈夫……ですか……？"
62040-207 = "ええ。ありがとうございます。#n……セナさん。"
62040-208 = "はい。何でしょう。"
62040-209 = "おそらく……長くは持ちません。#nご迷惑をおかけすることになるかと。"
62040-210 = "……困ったときにはお互い様です。お構いなく。"
62040-211 = "それから、先生。お願いしたいことがあります。"
62040-212 = "[s] \"……何でも言って。\""
62040-213 = "……ありがとうございます。"
62040-214 = "先生の言葉がなければ、私は[ruby=・]取[/ruby][ruby=・]り[/ruby][ruby=・]込[/ruby][ruby=・]ま[/ruby][ruby=・]れ[/ruby][ruby=・]た[/ruby]まま、戻ってこられなかったかもしれません。"
62040-215 = "どうか……アリウスの生徒たちの「日常」を、守っていただけませんか？"
62040-216 = "……！"
62040-217 = "突然のお願いなのは分かっています。"
62040-218 = "ですが……私自身も、いつの間にか忘れてしまっていたのです。"
62040-219 = "朝起きて、着替えて、授業を受けて、部活をして、自分の部屋に帰る……。"
62040-220 = "私の当たり前が、誰かにとっては当たり前ではなく――"
62040-221 = "日常とは、奇跡の連続なのだということを。"
62040-224 = "はい？アリウスに行け、と？"
62040-229 = "ええ。そして、先生を手伝っていただきたいのです。"
62040-230 = "先生は今――"
62040-231 = "アリウスの生徒たちに、試験勉強を教えていますので。"
62040-232 = "それは……どういう意味ですか？"
62040-233 = "言葉通りの意味ですよ。"
62040-234 = "そこがどんな場所であれ、生徒がいるなら迷わず向かう。#n先生はそういう方ですから。"
62040-235 = "安全を考慮すれば、先生が直接向かうのは止めたかったのですが……。"
62040-236 = "……なるほど。#nつまり、先生の安全を確保してほしい、という指示でしょうか。"
62040-237 = "いえ、もちろんそれも大事なことではありますが……何よりも――"
62040-242 = "アリウスに必要な「救護」を[ruby=・]お[/ruby][ruby=・]願[/ruby][ruby=・]い[/ruby][ruby=・]し[/ruby][ruby=・]た[/ruby][ruby=・]い[/ruby]のです。"
62040-243 = "……。"
62040-244 = "それが何を意味するのか、ご理解の上で、と受け取りますよ。"
62040-246 = "ミネ団長は、こういった言い回しを好まれない方でしたね。"
62040-247 = "あるいは……言い回しだけでなく、私自身についても。"
62040-248 = "それでも、そうしたすべてを承知の上で。"
62040-249 = "これは、ティーパーティーから救護騎士団への指示ではありません。"
62040-250 = "[ruby=きりふじ]桐藤[/ruby]ナギサという一人の生徒が、[ruby=あおもり]蒼森[/ruby]ミネさんにする――「お願い」です。"
62040-251 = "きっと……アリウスも救護を必要としていますから。"
62040-252 = "……トリニティにアリウスを「救う資格」などない。#nそう思われることもあるのでは？"
62040-253 = "そうですね。#nですが、ミネさんは「救護の精神」を持って、前へ進める方だと思っています。"
62040-254 = "……。"
62040-255 = "私は、ナギサ様に対して、悪感情を持っている訳ではありません。"
62040-260 = "むしろ、感謝している部分もあります。"
62040-261 = "ティーパーティーという肩書にのせられた立場と重責に縛られたくなかったがゆえに――"
62040-262 = "救護騎士団は、自らその座を手放したとも言えるのですから。"
62040-263 = "ですが、ナギサ様の話し方は……#nやはり少しだけ圧を感じますね。"
62040-265 = "……申し訳ありません。"
62040-266 = "……話は理解いたしました。"
62040-270 = "「救護が必要だという予感」に従って、アリウスへ向かいましょう。"
62040-273 = "先生が持ってきたもの。それはアリウスの生徒にとって、真新しく新鮮だったはず。"
62040-274 = "授業を体験し、勉強に触れ、くだらないことを真剣に悩んで……。"
62040-275 = "そんな風に続いていく「日常」を……。"
62040-276 = "……。"
62040-277 = "どうか、お願いします。"
62040-278 = "……彼女たちがそれを享受し続けられるようにしてあげてください。"
62040-279 = "[s] \"……うん、約束するよ。\""
62040-280 = "ありがとう……ございます。"
62040-287 = "団長！？だんちょう……。"
62040-288 = "……意識を失ったようです。"
62040-289 = "……。"
62040-290 = "一時的にでも意識が戻ったのは、いい兆候です。"
62040-291 = "あるいは、それほどまでにミネさんの精神力が強靭だ……という証左かもしれませんが。"
62040-295 = "……では、ミネさんはたしかに送り届けます。#n私はこれにて。"
62040-296 = "くれぐれも、お体にはお気をつけください。"
62040-304 = "い、行ってしまいましたね……。"
62040-305 = "……。"
62040-306 = "……。"
62040-307 = "ミネさん……大丈夫かな……。"
62040-308 = "[s] \"私は信じてるよ。\""
62040-309 = "……そっか。うん。"
62040-310 = "[s] \"……アツコに聞きたいことがあるんだ。\""
62040-314 = "あの声について、かな？"
62040-315 = "……何から話そうか。"
62040-316 = "……あれはたぶん、「黙示録の天使」だと思う。#nまだ推測に過ぎないけどね。"
62040-317 = "でも、もしもそれが正しかったなら……意味するものは、一つしかない。"
62040-318 = "……ああ。"
62040-322 = "「世界の終わり」の始まりだ。"
62040-324 = "次回;アリウス・バシリカ"
