[translation]
62050-243 = "で、でも……それ、私たちは聞いてないけど……？"
62050-247 = "（こんな中途半端なところで終わりなのは……ちょっと……）"
62050-252 = "あ、あの……トリニティや先生のせいじゃないかも……しれない、とは思いませんか……？"
62050-259 = "あの子は……。"
62050-268 = "黙示録に書かれてることが、そのまま起きるって……#n確証は、ないじゃないですか……？"
62050-272 = "そ、そんなの経典への冒涜だ……！"
62050-274 = "……どうして、そう思うんですか？"
62050-278 = "そんな気配もなかったし……。"
62050-287 = "もともとあいつら、アリウスから逃げたくせに！！！"
62050-291 = "あいつらならやれたはずなんだ！"
62050-295 = "ロイヤルブラッドって呼ばれてたくせに！！！"
62050-300 = "先輩に憧れてた子も、たくさんいたのに……！"
62050-305 = "今さら救われたみたいな顔して、一人で……一人だけ……！"
62050-315 = "私達の未来って、どうなるんだろうって……。"
62050-322 = "今とは違う道を、生きてみたかったんだ。"
62050-326 = "もう、できないから……！"
62050-335 = "わ、私はよく分からないけど……先生ならきっと、私たちが知らないことを知ってるはずです！"
62050-344 = "先生が何？あの人の言う通りにしてたら、なんでもうまくいくの？"
62050-353 = "トリニティ……！！！"
62050-357 = "その子の言うことを聞くんですか？"
62050-362 = "それは……。"
62050-365 = "[ruby=・]ア[/ruby][ruby=・]リ[/ruby][ruby=・]ウ[/ruby][ruby=・]ス[/ruby]を守ってくれるんですよね？"
62050-367 = "証明してください、先輩！！！"
62050-369 = "す、少し……時間をください。"
62050-374 = "[log]証明[/log]"
62050-377 = "[log]証明[/log]"
62050-380 = "[log]証明証明[/log]"
62050-383 = "[log]証明証明[/log]"
62050-386 = "[log]証明証明証明[/log]"
62050-389 = "[log]証明証明証明証明[/log]"
62050-392 = "[log]証明証明証明証明証明証明[/log]"
62050-396 = "[log]証明！！！[/log]"
62050-404 = "……！"
62050-409 = "は、はいっ！"
62050-414 = "ラッパの音は……聞こえましたか？"
62050-420 = "……ごめんなさい。"
62050-428 = "ごめんなさい！私、外に出たせいでおかしな考えに染まっちゃっただけなんです！だから！だから……もう一度……！やり直します、から……！"
62050-434 = "分かりました！"
62050-443 = "スバル先輩！！！"
62050-450 = "だから、お願い――"
62050-459 = "もう大丈夫です。先に戻っていてください。"
62050-461 = "分かりました、先輩！"
62050-467 = "私を――見捨てないでください！"
62050-479 = "うわああああああああああああああっ……！！！"
62050-483 = "次回;迷子の子ども"
