[translation]
62060-1 = "第6話;迷子の子ども"
62060-3 = "みんな、お疲れ様。"
62060-8 = "と、とんでもない一日でしたね……。"
62060-9 = "ああ、たしかに。"
62060-10 = "だが……あの状況下で三人ともよく動いてくれた。"
62060-11 = "逃亡生活には慣れてるからね。#n急に襲われることだってあったし。"
62060-12 = "[s] \"みんな、強くなったんだね……。\""
62060-13 = "別に、なりたくてなったわけじゃないんだけど。"
62060-14 = "……なに？環境に背中を押されて強くなるもの……？"
62060-15 = "はぁ……。#nほんと、それっぽく正論言うのやめてくれない？"
62060-16 = "で、でも……私たちって……。"
62060-17 = "……。"
62060-18 = "この先も……ずっと、逃げながら生きていくんでしょうか……？"
62060-19 = "ヒヨリ……？"
62060-23 = "い、いえっ！私、今の生活も好きですから！えへへ……。"
62060-24 = "でも、やっぱり……。"
62060-25 = "なんだか……。"
62060-26 = "久しぶりに帰ってきたからか、変なことばっか考えちゃって……。"
62060-27 = "[s1] \"……ごめんね。そんな思いをさせてしまって。\"\n[s2] \"アリウス分校のことは全部……。\"\n[s3] \"私の職務放棄のせいだから……。\""
62060-33 = "えっ？そ、それってどういう……？"
62060-34 = "先生……？"
62060-35 = "……。"
62060-40 = "ねえ、先生。なんでもかんでも、自分一人で背負い込もうとしないで。"
62060-41 = "これは私たちが、自分で選んだ道なんだから。"
62060-42 = "だから、もし……他の選択肢があるかもしれないって思うなら……。"
62060-43 = "その時は、みんなで考えよう。"
62060-44 = "今は、ミネさんからのお願いについて話さない？"
62060-45 = "[s] \"「日常」のことだね。\""
62060-46 = "うん。アリウスの日常。"
62060-47 = "たぶん……あの人が思ってるものとは、かけ離れてるんだけどね。"
62060-48 = "い、今のアリウスの子たちにとっては……初めての経験ばっかりだと思うんです……。"
62060-49 = "授業も……勉強も……校外学習も……。#n水を濾過できる道具とか、新しい医薬品だって……。"
62060-51 = "保温効果のある布団もあったな。前は破れたテントを使ってたのに。"
62060-52 = "あとは……栄養改善用の救援食も、ここじゃ見たことがなかった。"
62060-53 = "……改めて実感する。#n誰かにとっての「日常」が、別の誰かにとっては「奇跡」なのだと。"
62060-55 = "でも、ミネさんはそれを守ってほしいって言ってたよね？"
62060-56 = "「当たり前」を守ってほしい、って……。"
62060-57 = "言うほど簡単じゃないでしょ、それ。"
62060-58 = "[s4] \"そうだね。\"\n[s5] \"だからこそ、私が頑張らなきゃいけない。\""
62060-61 = "でも……やっぱり勉強はイヤです……。"
62060-62 = "[s] \"生徒の本分を忘れちゃダメだよ？\""
62060-66 = "い、今のすごく「先生」っぽかったです……！"
62060-67 = "あ、そっか……先生は元から先生でした……。"
62060-68 = "[s6] \"ふふっ。思い出させてあげよう。\"\n[s7] \"私が「先生」だということをね。\""
62060-73 = "何するつもり……？"
62060-74 = "[s8] \"明日も、授業をやるよ。\"\n[s9] \"みんなにモモトークでお知らせしておかないと。\""
62060-77 = "いい性格してるよね、先生。"
62060-78 = "……何？嫌なことを繰り返し乗り越えることで、人は強くなるって？"
62060-79 = "はぁ……その言葉、アリウスでもよく言われてたよ。#nもっと違う言い方をしてたけど。"
62060-80 = "たしかに、そうだったな……。"
62060-81 = "だが、アリウス式の訓練に比べれば、先生の授業の方がずっとマシだと思う。"
62060-82 = "私はそうだが……お前は違うのか？"
62060-83 = "……そんなこと、言った覚えないんだけど。"
62060-88 = "ふふっ。"
62060-89 = "えへへ……。"
62060-94 = "……ねぇ、なんで私ばっかり？"
62060-109 = "モモトーク……先生から？"
62060-113 = "「今日は本当にお疲れ様でした」"
62060-114 = "「色々なことがありましたが、変わらず明日も授業を行います」"
62060-115 = "「皆さん、奮ってご参加ください」"
62060-116 = "……何これ、ふざけてるの？"
62060-117 = "今がどんな状況か分かってないのかな……。"
62060-118 = "先輩が戻ってきたら伝えなきゃ……。"
62060-126 = "あっ、先輩！さっき先生からモモトークが来て……！"
62060-127 = "それで、その内容がですね――"
62060-129 = "知ってますよ。"
62060-131 = "えっ、はい？"
62060-132 = "そ、そうですか……それなら、よかったです……。"
62060-134 = "とはいえメッセージは消してしまったので、もう読めませんが。"
62060-136 = "はい……？"
62060-137 = "け、消しちゃったんですか……？"
62060-142 = "何か問題でも？"
62060-147 = "い、いえっ！何でもないです！"
62060-149 = "それでは。"
62060-150 = "もういい時間ですから、そろそろ休みましょう。"
62060-152 = "……寝る、んですか？"
62060-153 = "たしかに寝る時間だけど……。"
62060-154 = "こんな風に何も知らないふりしてモモトーク送ってくる先生とか……。"
62060-155 = "あと、一緒にいるスクワッドに……#nちょっとくらい抗議してもいいんじゃないんですか……？"
62060-156 = "……マイアだって、追い出しちゃったけど。#nそれでもせめて、毛布くらいは届けてあげたほうが……。"
62060-161 = "……。"
62060-162 = "同じことを言わせないでください。"
62060-164 = "先輩……？"
62060-165 = "え……？"
62060-172 = "さっさと――"
62060-173 = "寝なさい。"
62060-174 = "いいですね？"
62060-180 = "……！"
62060-181 = "は、はいっ！"
62060-182 = "先輩も……おやすみなさいっ！"
62060-190 = "ふぅ……。"
62060-191 = "……。"
62060-192 = "今日は[ruby=ここ]バシリカ[/ruby]で寝るとしましょうか。"
62060-193 = "……。"
62060-194 = "はぁ……この感覚は……。"
62060-199 = "死してなお、眠れないような……あの感覚ですね……。"
62060-209 = "……。"
62060-210 = "どう、しよう……これから……。"
62060-211 = "……。"
62060-212 = "いっそ、このまま……。"
62060-213 = "……このまま。"
62060-215 = "消えてしまいたい……。"
62060-221 = "モモトーク……？誰から……？"
62060-222 = "……。"
62060-226 = "授業……明日も……こんな時に？"
62060-227 = "先生は、本当に……。"
62060-228 = "……。"
62060-229 = "うぅ……。"
62060-232 = "机はあるし、イスも起こせば問題ない。"
62060-233 = "教卓も黒板もある！完璧な教室じゃないかな？"
62060-236 = "初回は短めだから大丈夫だよ。"
62060-237 = "出席を取って、軽くガイダンスをして終わりかな。"
62060-248 = "うぅっ……。"
62060-249 = "……行こう。"
62060-250 = "先生の……ところに……。"
62060-251 = "うぅ……ひっく……。"
62060-256 = "うわああああああん……！"
62060-260 = "（眠れなくて、天井を見つめていた）"
62060-261 = "（黙示録……ラッパの音……天使……言葉が頭の中を駆け巡っていく……）"
62060-269 = "[ns] \"はーい、ちょっと待ってね。\""
62060-279 = "[ns] \"マイア！？どうしたの？\""
62060-280 = "こ、こんな時間にすみません……。"
62060-281 = "本当に……本当に申し訳ないんですけど――"
62060-282 = "ひと晩だけ……泊めていただけませんか……？"
62060-283 = "明日には、ちゃんと……消えますから。"
62060-284 = "二度とご迷惑はおかけしませんから……今日だけ……どうか……。"
62060-288 = "[ns] \"いいよ。どうぞ、中に入って。\""
62060-289 = "わわっ！？"
62060-297 = "[ns] \"まずは手と顔を洗おうか。\""
62060-298 = "だ、大丈夫です！大丈……夫、です……。"
62060-303 = "（顔の腫れがひどいので、水で洗ってあげた）"
62060-304 = "（その水を飲もうとしたので、急いで飲み物をたくさん用意した）"
62060-305 = "（何があったのか聞こうかと思ったけど……）"
62060-308 = "……。"
62060-309 = "[s10] \"さ、今日はゆっくり休もう。\"\n[s11] \"寝袋は自由に使っていいからね。\""
62060-312 = "え……？"
62060-313 = "で、でもこれ、先生の……ですよね？"
62060-314 = "こ、こんなに気を遣っていただかなくても……。"
62060-315 = "って、先生！それアルミブランケットですよね……？"
62060-316 = "だ、ダメです！それはおかしいですっ！私がそのブランケットを使います！"
62060-317 = "えっ？それなら外で寝る……？それはもっとダメですけど！？"
62060-321 = "はぁ……はぁ……わ、分かりまし……た……。"
62060-322 = "寝袋、使わせてもらいます……ありがとうございます……。"
62060-323 = "お腹……？いえっ、大丈夫ですっ！全然空いてないのでっ！"
62060-328 = "[ns] \"ふふっ、お腹は正直だね。\""
62060-329 = "うぅ……すみません……。"
62060-338 = "もぐもぐ……ごくっ。"
62060-339 = "[s] \"焦らなくて大丈夫だよ。\""
62060-342 = "で、でも……でも……。"
62060-343 = "これ、美味しいです。"
62060-344 = "……本当に、美味しい……です……。"
62060-345 = "……。"
62060-346 = "うっ……。"
62060-347 = "[s] \"……。\""
62060-349 = "[ns] \"……お腹いっぱいになった？\""
62060-350 = "はい……ありがとうございます……。"
62060-351 = "えっ……先生、食べてすぐ寝るんですか……？"
62060-352 = "……。"
62060-353 = "あの……。"
62060-354 = "何があったのか、とか……聞かないんですか……？"
62060-355 = "[s12] \"今日はもう遅いしさ。\"\n[s13] \"ふわぁ……眠くなってきちゃった……。\""
62060-361 = "すみません……。"
62060-362 = "私がこんな時間に来たせいで……。"
62060-363 = "ごめんなさ……い……。"
62060-364 = "えっ？気にしないでいい、と言われても……だって……。"
62060-365 = "あの、私……明日、先生が起きるまでには……消えますから……。"
62060-366 = "……なんで、ですか。#n本当に……ここにいても……いいんですか……？"
62060-367 = "でも、私、その……。"
62060-368 = "[s14] \"なにも気にしなくていいんだよ。\"\n[s15] \"話だって、マイアが話したくなったら聞くからさ。\""
62060-371 = "……。"
62060-372 = "…………。"
62060-373 = "ありがとうございます、先生。"
62060-374 = "ありがとう、ござい……ます……。"
62060-375 = "うぅっ、うぅ……。"
62060-377 = "（よほど疲れていたのだろう。すぐに小さな寝息が聞こえてきた）"
62060-381 = "（悲しい夢を見ているのか、時折うなされていたけれど……）"
62060-382 = "（こういうのこそ、先生の役目なんだと思った）"
62060-390 = "皆さん、集まっていますね？"
62060-392 = "はい！"
62060-393 = "それでは――"
62060-394 = "ポルタパシスへ向かいます。"
62060-396 = "はい！"
62060-400 = "……本当に大丈夫かな？"
62060-401 = "まだ夜明け前だよ……？#n早く寝ろって昨日言ってたのは、このため？"
62060-402 = "なんでこんな早朝に……ポルタパシスのこともよく分かんないし……#nなんか不安かも……。"
62060-403 = "このままついて行ったら、先生の授業に出られないよね……。"
62060-404 = "というか、ポルタパシスに行って何も分からなかったらどうするの……？"
62060-405 = "しっ、聞こえちゃうって！"
62060-410 = "何か問題でも？"
62060-416 = "いえっ！なんでもありません！"
62060-424 = "――だから、目をさましていなさい。"
62060-428 = "その日その時が、あなたがたには分からないからである。"
62060-437 = "……。"
62060-438 = "……。"
62060-439 = "だ、誰も……来てないみたい……ですね？"
62060-444 = "……。"
62060-445 = "これが……いわゆる「無断欠席」か？"
62060-446 = "[s16] \"……そうだね。\"\n[s17] \"でも、全員一斉に、か……。\""
62060-449 = "先生、どうする？といっても、みんなが行きそうな場所の心当たりはないんだけど。"
62060-453 = "え？電話してみるって……誰に？"
62060-454 = "スバル……？"
62060-455 = "……分かった、お願い。"
62060-462 = "……。"
62060-463 = "出ない……ですか……？"
62060-464 = "[s18] \"授業が嫌になっちゃったのかもしれないけど……。\"\n[s19] \"黙っていなくなったら心配だよね……。\""
62060-471 = "あの、先生……。#nみんなが行った場所の心当たりが、あります。"
62060-475 = "分かるのか？"
62060-476 = "はい……たぶん、みんな――"
62060-480 = "「ポルタパシス」に向かったんだと思います……。"
62060-484 = "！！！"
62060-486 = "次回;ポルタパシス（１）"
