[translation]
62070-1 = "第7話;ポルタパシス（１）"
62070-10 = "……始まりすらも忘れ去られた内戦で、アリウスの支配者は入れ替わってきた。"
62070-102 = "ひ、ひぃっ……！怖い……怖いです……！"
62070-103 = "う、うわああ……怖い……怖すぎですよぉ……！"
62070-104 = "ひ、ヒヨリさんまで……？#nスクワッドの皆さんって、何も怖がらないと思ってました……。"
62070-105 = "わ、私たちだって怖いものは怖いんです……。#nそれに……世の中は怖いものでいっぱい、ですし……。"
62070-11 = "それでも一貫して「ポルタパシスには近づくな」という掟だけは、ずっと鉄則として守られ続けてきたんだ。"
62070-111 = "[ns1] \"ごめん……どうしてもウイの力が必要なんだ。\"\n[ns2] \"アメリカーノのクーポン20枚でどうかな。White&Masonのやつ！\""
62070-117 = "委員長！先生にはいつも助けてもらっているじゃないですか！#nお手伝いしてもいいと思います！"
62070-119 = "で、でも……。"
62070-12 = "……今にして思えば、ずいぶんと不思議なことだ。"
62070-120 = "これ以上駄々をこねるなら……#n先生のところまで無理やり「出張」させちゃいますよ？"
62070-121 = "うえぇっ！？"
62070-127 = "噂通りの子だね……。"
62070-128 = "[s] \"腕は確かな子だから。\""
62070-129 = "こんにちは。アリウス分校の[ruby=はかり]秤[/ruby]アツコです。よろしくね。"
62070-13 = "互いに争っていた連中でさえ、その掟だけは守っていた……#nあそこには、一体何が眠っているのだろうな。"
62070-130 = "[ruby=じょうまえ]錠前[/ruby]サオリだ。"
62070-131 = "……[ruby=いましの]戒野[/ruby]ミサキ。"
62070-132 = "つ、[ruby=つちなが]槌永[/ruby]ヒヨリ……です。え、えへへ……。#nあ、あの……古書館って、キヴォトスでも有名だって聞いたんですけど……。"
62070-133 = "雑誌のバックナンバーとか……あったり、しますか？"
62070-134 = "スクラップ用に電子保存してありますよ。#n後ほど、先生宛にデータをお送りしましょうか？"
62070-138 = "ほ、本当ですか？！あ、ありがとうございます！#nあっ、で、でも……特にお礼できるものなんて……。"
62070-139 = "大丈夫です。文字と知識を愛する方は、私たちの仲間ですから。"
62070-14 = "毎日を生き延びるのに精一杯で……余計なことを気にしてる余裕なんてなかったですもんね……。"
62070-140 = "うわぁぁぁぁぁぁああん！生きててよかったですぅ……！"
62070-141 = "さて……ご挨拶が遅れました。改めまして、[ruby=えんどう]円堂[/ruby]シミコです。"
62070-146 = "えっ、わ、私もですか！？#nえっと……[ruby=たちぎ]立木[/ruby]マイアって言います……。よ、よろしくお願いします……。"
62070-15 = "私は1年生なので……そういうのは知らなくていいし、知ろうとしちゃダメだって言われてました……。"
62070-151 = "……。"
62070-152 = "委員長？"
62070-156 = "え、えっと……はあ……#n[ruby=こぜき]古関[/ruby]ウイ、です……もう、さっさと本題に入りましょう……。"
62070-157 = "[s] \"事情はモモトークで伝えた通りなんだけど……。\""
62070-158 = "はい。こちらでもできる限り調べてみました。#nおそらく、先生の欲しい情報を見つけられたと思います。"
62070-159 = "そんな資料があったの！？"
62070-16 = "……。"
62070-160 = "はい、ですが……トリニティにおいて[ruby=・]準[/ruby][ruby=・]禁[/ruby][ruby=・]書[/ruby][ruby=・]扱[/ruby][ruby=・]い[/ruby]のものも含まれています。"
62070-161 = "その理由も分からなくはないのですが……。"
62070-162 = "ティーパーティーにシスターフッド……。#n変に秘密主義だから、疑わしく見えてくるんですよ……。"
62070-163 = "ここはトリニティの図書委員会――その中でも「古書館」です。#n大体のものは揃っています。"
62070-164 = "もちろん、他校の情報となると完全ではないかもしれませんが……。"
62070-165 = "……ここは、[ruby=・]ト[/ruby][ruby=・]リ[/ruby][ruby=・]ニ[/ruby][ruby=・]テ[/ruby][ruby=・]ィ[/ruby][ruby=・]の[/ruby][ruby=・]過[/ruby][ruby=・]去[/ruby]そのものでもありますので。"
62070-166 = "……権力を持つ者は、自分に都合のいい状況を作りたがる。"
62070-167 = "不都合なことは隠したり、ねじまげたりして……もっと大きな嘘で真実を覆い隠そうとする……。"
62070-168 = "……でも、私たちはそれを許しません。"
62070-169 = "……分かったことを教えてくれる？"
62070-17 = "ただ、これはあくまで聞いた話だが……。"
62070-170 = "アリウスの「元」ロイヤルブラッドとして……お願い。"
62070-174 = "ロイヤル……ブラッド？あなたが……？"
62070-175 = "[s] \"うん。本当のことだよ。\""
62070-179 = "……。"
62070-18 = "誰にも知られていない、アリウスの「過去」が眠っているという話もあったな。"
62070-180 = "分かりました。どのみち、話せることはお伝えするつもりでしたし……。"
62070-181 = "先生の保証もあるのですから、隠す必要もないでしょう。"
62070-185 = "……ポルタパシス。#n本来は、その名の通りに使われるはずの建物でした。"
62070-186 = "――「平和の門」として。"
62070-187 = "……かつて、アリウス分校とトリニティ総合学園は袂を分かった。あれは、その時に建てられたものです。"
62070-188 = "今では想像もつきませんが……トリニティもアリウスも、いずれは平和的な解決ができると考えていたみたいですね。"
62070-189 = "……でも、そうはならなかったんだよね？"
62070-19 = "[s] \"アリウスの過去？\""
62070-190 = "……はい。"
62070-191 = "ですがこの部分については、こちら側でも記録がはっきりしていません。"
62070-192 = "……権力の本当の恐ろしさは、「記録すること」ではなく「記録しないこと」にある、と言われるくらいですから。"
62070-193 = "だから、この部分は……。"
62070-194 = "……私から補足するね。"
62070-195 = "アリウスで続いてきた内戦の「引き金」は、ポルタパシスの完成を巡る争いだったんだ。"
62070-199 = "へ、平和の門なのに……！？真逆じゃないですか……！"
62070-200 = "こ、こんな話……私が聞いちゃって大丈夫なんでしょうか……。"
62070-202 = "……記念として作られた建物なのに、いつの間にか意味が逆転しちゃうことってあるよね。"
62070-203 = "「象徴」という概念の限界なのかもしれないな。#n理念を押しつけられると、かえって反発したくなるものだ。"
62070-204 = "……今すぐじゃなくても、遠い未来には平和が訪れると信じた人々がいた。"
62070-205 = "でも……「平和の門」を建てたとしても、平和なんて訪れやしないと考える人もいた。"
62070-206 = "それぞれの考えの根底には、トリニティと対話できるという意見と――"
62070-207 = "対話は成り立たないという意見があった。そして……。"
62070-209 = "それが、内戦の発端になったんですね……。"
62070-210 = "そう。外に向いていた怒りが、内側に向き始めた。"
62070-211 = "……そう聞いてるよ。"
62070-212 = "こっち側にも、ちゃんとした史料はほとんど残ってないんだけどね。"
62070-213 = "でも、そのときに生まれた怒りは……時を越えて、ずっと受け継がれてきた。"
62070-214 = "トリニティに向けた怒り。そして、自分たち自身への怒り。"
62070-215 = "……もう、ずっと昔の話なのにね。"
62070-216 = "……私達は、本来「共感」しながら生きていくもの。"
62070-217 = "長い歴史において……他者に「共感」しながら、今日まで歩んできました。"
62070-218 = "そうですね……歴史を振り返って、当時の人の感情に寄り添うこともあれば――"
62070-219 = "同じものを見て、同じものを感じ取るということもあります。"
62070-220 = "アリウスの怒りも、そうやって受け継がれてきた。#n……でも、受け継ぐための方法は、一つじゃない。"
62070-221 = "内戦に勝った側――ポルタパシスは「もはや平和の象徴たりえない」と考えた側は別の使い方をすることに決めたの。"
62070-222 = "それで……ポルタパシスの地下に、大きな「記録保管庫」が作られた。#n後の指針と、戒めを残すために。"
62070-223 = "あそこの地下に、そんなものが……！？"
62070-224 = "そう。そしてその記録保管庫は……アリウスで起きた出来事を、一つひとつ書き残していくようになった。"
62070-225 = "……まるで、トリニティの図書館みたいですね。"
62070-226 = "何かを記録して残そうとするのは……本能に近いものですからね……。#n一種の普遍的な行動といえます。"
62070-228 = "そうして「ポルタパシス」とその記録保管庫は、アリウスの図書館としての役割を担っていった。"
62070-229 = "でも、私の知る限りでは……150年以上前かな。"
62070-23 = "昔の話って……先輩から教えてもらったのとは違うんですか……？"
62070-230 = "当時のアリウスの支配者が、立入禁止区域として記録保管庫とポルタパシスを指定したの。"
62070-231 = "[s] \"それは、どうして？\""
62070-232 = "正確な理由は分からない。でも……。"
62070-233 = "きっと、もう耐えきれないと思ったから、じゃないかな。"
62070-234 = "積み重なってきた物語と、それにこびりついた黒い感情に。"
62070-235 = "[s3] \"……そっか。\"\n[s4] \"なんとなく、分かる気がする……。\""
62070-238 = "……情報統制、ですか。それはトリニティも同じことではありますが……。#nはぁ、どこも変わりませんね。"
62070-239 = "これだから権力者は……。"
62070-24 = "伝わっている歴史が正しいものとは限らないからね。"
62070-240 = "怒りの感情は、ある程度までは民衆の統制に役立ちますが、それも行き過ぎれば逆効果になりますから……。"
62070-241 = "民衆を煽って権力を掌握し……役目が終われば、焚きつけ役は闇に葬られる。#nまぁ、歴史上にいくらでもある話ですね……。"
62070-243 = "そ、そんな……。外の世界って、そんな風にできてるんですか……？#nこ、怖いですね……ヒヨリさん……怖すぎます……。"
62070-244 = "わ、私も……こんな世界、生きていける気がしないです……うわあああん……。"
62070-245 = "で、でもシミコさんが雑誌の資料をくれるって言ってたので……#nまだちょっとだけ……希望は持ってみます……。"
62070-247 = "[ruby=こっち]アリウス[/ruby]も同じようなことが起きてるって話してるんだけど……。"
62070-248 = "行き過ぎた怒りは逆効果、か……それなら、アリウスの歴史が「口伝」で語り継がれてきたことにも納得がいく。"
62070-249 = "そうだね。マダム――ベアトリーチェが完全に支配するまで、アリウスの支配者は何度も入れ替わってきたけど……。"
62070-25 = "私は直接見たわけじゃないけど……トリニティに残ってるアリウスの記録も、全然違うらしいし。"
62070-250 = "一貫して情報統制が敷かれてきたのは、それが理由だったんだと思う。"
62070-251 = "……その名を、もう呼べるようになったんだな。"
62070-252 = "うん。そういう時期だと思ってる。大丈夫だよ。"
62070-253 = "そうか……。#nだが、口伝にもデメリットはあっただろう。"
62070-254 = "……程度の差はあっても、人によって少しずつ語る内容は歪んでいくはずだ。"
62070-256 = "それはどうしようもないでしょ。"
62070-257 = "事実より大げさになるとか、そもそも省略されるとか……語り手の主観が入るからね。"
62070-258 = "私たちが聞いた歴史も正しいとは言い切れない。#n多分、かなり歪められてるだろうし。"
62070-259 = "だから、ちゃんとした記録を見直すことが、アリウスを正しい姿に戻すための、最初の一歩になるかもしれないって思うんだ。"
62070-26 = "た、たとえば……公会議の話だと……。アリウスが武力衝突を起こしたから、仕方なく破門にしたとか……。"
62070-260 = "それに、今さらポルタパシスの記録を公開しても、大したことは出てこない気もするけどね。"
62070-261 = "それなら、どうしてスバル先輩はあそこに向かおうとしてるんでしょうか……？"
62070-262 = "たぶん、スバルは「何か」を知ったんだと思う。"
62070-263 = "ベアトリーチェがいなくなった後のアリウスは、「何でも許される場所」になってしまったはずだから。"
62070-264 = "そ、それは……そうでした……。スバル先輩が秩序を取り戻すまでの間は……。"
62070-265 = "うぅっ……。"
62070-266 = "それと……ここからは、私だけが知っていることを話すね。"
62070-267 = "……もしかすると、今はスバルも知ってるかもしれないけど。"
62070-27 = "……アリウスがこの地に追いやられたのも、自業自得だったとか、そんな話も聞いたな。"
62070-272 = "それは……どんな……？"
62070-277 = "――ポルタパシスに隠された、アリウスの「秘儀」の話。"
62070-28 = "歴史は勝者の記録、とはよく言ったものだ。"
62070-281 = "次回;ポルタパシス（２）"
62070-3 = "[ns] \"ポルタパシス……？\""
62070-33 = "……。"
62070-34 = "[s] \"アツコ？\""
62070-35 = "ん？どうしたの？"
62070-36 = "……何か言いたそうに見えるって？"
62070-37 = "……。"
62070-38 = "もしもの話だけど……。"
62070-39 = "トリニティとアリウス、両方の「隠された歴史」を知っている生徒がいたとしたら……どう思う？"
62070-4 = "「ポルタパシス」って呼ばれる建物があるんですけど……すごく古いってことくらいしか、私は知らなくて……。"
62070-40 = "……ありえないでしょ。あっちの子だって、教わったことしか知らないはずだし。"
62070-41 = "それが普通だとは思うよ。でもほら、真実を自分で探そうとする人は、どこにでもいるものだから。"
62070-42 = "たとえば……トリニティの「図書委員会」とかね？"
62070-43 = "[s] \"図書委員会を知ってるの？\""
62070-44 = "一人ひとりのことは知らないけど、組織についての話はちょっとだけ聞いてるんだ。"
62070-45 = "あぁ、でも……委員長さんは色んな意味で、すごい性格してるらしいね。"
62070-46 = "[s] （間違ってはないけど……）"
62070-47 = "待ってくれ、どこでそれを知ったんだ？そんな情報、私たちは……。"
62070-48 = "ふふっ。"
62070-49 = "「ロイヤルブラッド」の特権……だったのかもね？"
62070-5 = "スクワッドの皆さんなら、分かるのかもしれませんけど……。"
62070-50 = "まぁ、「お姫様」だったからね。"
62070-51 = "そ、そうですよね……。#n私みたいなのが、お姫様と一緒にいるなんて……。"
62070-52 = "気にしないで大丈夫だよ。私はもう、そんな立場じゃないし。#n普通に「アツコ」って呼んでほしいな。"
62070-56 = "は、はいぃ！？で、でも……！"
62070-57 = "私たち、同じ1年生でしょ？ね、マイア？"
62070-58 = "そ、それはそうですけどっ！でも、でもでも……！"
62070-59 = "じゃあ練習してみようか。ア、ツ、コ。"
62070-63 = "あ、アツコ……さん。"
62070-64 = "うん、よくできました。はい、握手。"
62070-65 = "ひいいぃ……。"
62070-7 = "わ、私たちも同じですよ……。#nその名前が「平和の門」という意味ってことと……。"
62070-70 = "……話を戻すけど、私たちには見えてなかったことまで、アツコは知ってたってことでいいの？"
62070-71 = "まあ、立場ってそういうものだとは思うけど。"
62070-72 = "だ、だから……私たちには……何も、話してくれなかったんですね……。"
62070-73 = "ごめんね。でも、私が軽々しく話してたら……。"
62070-74 = "ああ。おそらく、私たちが危険に晒されていただろうな。"
62070-75 = "ひ、ひいぃ……。"
62070-76 = "アリウスを出た後なら、って思わなくもないけど……もうどうでもいい話だったってことかな。"
62070-77 = "でも、そうも言ってられなくなっちゃったみたい。"
62070-78 = "[s] \"分かった。\""
62070-8 = "……あそこの扉は、絶対に開けてはいけない、って話くらいしか知らないよ。"
62070-82 = "[ns] \"ウイには、私から連絡してみるよ。\""
62070-83 = "ウイさん、って言うんだ、その人。"
62070-88 = "よろしくお願いね、先生。"
62070-97 = "私のこと、便利な百科事典だと思ってませんか！？"
