[translation]
62080-1 = "第8話;ポルタパシス（２）"
62080-4 = "秘儀……？"
62080-5 = "あまり良いものではなさそうですね。"
62080-6 = "委員長！"
62080-7 = "う、うぅ……。"
62080-12 = "たしかに、私も聞いたことがない。"
62080-13 = "これはたぶん、私しか知らないことだと思うから。"
62080-14 = "私も最初は、怪談とか伝説の類だと思ってたんだけど……。"
62080-15 = "「エデン条約」が結ばれる少し前。#nベアトリーチェは、ポルタパシスの記録保管庫に行ってたの。"
62080-16 = "私以外の誰にも、何も言わずに、こっそりと。"
62080-21 = "！"
62080-22 = "ええぇっ！？"
62080-27 = "で、でも、あそこって……入っちゃいけないはずじゃ……。"
62080-28 = "ベアトリーチェが、そんなこと気にすると思う？"
62080-29 = "そ、それは……そうかもしれないですけど……。"
62080-30 = "ベアトリーチェには多くの秘密があった。その一つがそれ。"
62080-31 = "まさか……ユスティナ聖徒会の[ruby=ミメシス]複製[/ruby]が顕現したのも？"
62080-32 = "どうだろう。もう、その真実を知る方法はほとんどないけど……。"
62080-33 = "まったく無関係だったとは思えないかな。"
62080-34 = "だって、アリウスで異常現象が増え始めたのは、その頃からだから。"
62080-35 = "覚えています……。いつの間にか、見たことのないものがいっぱい転がってて……武器だけなら潤沢に支給されていたりして……。"
62080-36 = "あの頃は……やっぱり大人ってすごいなって、思うだけで……疑問にも思わなかったですけど……。"
62080-37 = "[s] \"……。\""
62080-38 = "ここで大事なのは「増え始めた」って部分なの。"
62080-39 = "えっ……？まさか……？"
62080-40 = "そのまさかだよ。"
62080-41 = "元々、アリウスでは変なことが起こっていたんだ。#nあまり頻度は高くないんだけどね。"
62080-43 = "どの学園にも怪談のひとつやふたつはあるものだが……#nアリウスはそのレベルを遥かに超えていた。"
62080-44 = "アリウスを出てから分かったよ。あれは「ちょっと」とかそういう次元じゃなかったって。"
62080-49 = "[ns] \"それは……どうして？\""
62080-50 = "正確な理由は、私もよく分からない。"
62080-51 = "だけど……。"
62080-52 = "アリウスは、そういう「場所」になっちゃってた気がするんだ。"
62080-53 = "ここには、もともと「何か」があった。"
62080-54 = "怒り、嘆き、恨み、絶望、諦念……そういう思念が積もり積もって、ここに集まってる。"
62080-55 = "強い想いって、何かの形で現れるって言うでしょ？"
62080-56 = "そ、それって……ただの例え話、なんじゃ……。"
62080-57 = "でも、私たちはもう見てるはずだよ。ユスティナ聖徒会とか、バルバラとか。"
62080-58 = "すべてマダム……ベアトリーチェの仕業だと思っていたが……。"
62080-59 = "いや、そう考えることで、アリウスの「裏の真実」から無意識に目を逸らしていたのかもしれないな……。"
62080-60 = "そこまで決めつけたくはないけど……でも、時々怖くなる。"
62080-61 = "積もり積もった強い想いの奥底には、何があるんだろうって。"
62080-62 = "想像するだけで……怖い。"
62080-63 = "……。"
62080-64 = "ううう……。"
62080-69 = "こほん。#n……では、黙示録の話をしましょう。"
62080-70 = "どうやら、アリウスで起きている「現象」の核心に関わるようですから。"
62080-71 = "うん、ありがとう……シミコさん。"
62080-72 = "いえ、お気になさらずアツコさん。#nそれでは、まずは概要から。"
62080-73 = "黙示録とは、トリニティとアリウスの両校に伝わる経典の最終章を指します。"
62080-74 = "二つの学園が持つ経典は、もとは同一のものでした。その解釈が異なるだけで、ルーツは同じなんです。"
62080-75 = "トリニティにおいて黙示録は、あくまで参考文献のような扱いをされています。"
62080-76 = "教訓や助言を集めた[ruby=しんげんしゅう]箴言集[/ruby]として……それ以上の重みは、ほとんどありません。"
62080-77 = "だがアリウスでは、黙示録の研究が特に重視されていた。"
62080-78 = "なにしろ……「世界の滅亡」について記されているからな。"
62080-79 = "[s] \"つまり、それって……！\""
62080-80 = "アリウスは世界の滅亡を望んでいたのか、って？"
62080-81 = "……。"
62080-82 = "その通りだよ。"
62080-83 = "み、みみみみみ、ミサキさんっ！？"
62080-84 = "驚くことじゃないでしょ。事実だし。"
62080-86 = "……理解はできる気がします。"
62080-87 = "温もりを得られなかった子どもが、温もりを得るために村を燃やす――そんな話があるくらいですから。"
62080-88 = "失うものがない人にとって……世界の終わりは「救済」なのかもしれません。"
62080-89 = "少なくとも、全てが「公平」になったような気がするのでしょう。"
62080-90 = "自分が消えることと、世界が終わること。どっちも、[ruby=・]自[/ruby][ruby=・]分[/ruby][ruby=・]に[/ruby][ruby=・]と[/ruby][ruby=・]っ[/ruby][ruby=・]て[/ruby][ruby=・]の[/ruby]結果としては同じだもんね。"
62080-91 = "……だったら、どこかの時点で、その前後が入れ替わっちゃうのも、不思議じゃないと思うな。"
62080-93 = "手段と目的を取り違えてしまうことはよくありますから……。"
62080-94 = "……。"
62080-95 = "……。"
62080-96 = "黙示録には、7人の天使が3組登場します。それを総称して、「黙示録の天使」と呼ぶんです。"
62080-98 = "まさか……実在する、というのか？"
62080-99 = "恐怖や苦痛を煽るような……あくまで、物語に過ぎないと思っていたが……。"
62080-100 = "さっきの話だけど……強い想いは、いつか形を成すってやつ？"
62080-102 = "黙示録に記されている、世界の終わりを告げる天使。"
62080-103 = "最初は「封印を解く天使」の七人。次が「ラッパを吹く天使」の七人。そして最後が「鉢を注ぐ天使」の七人。"
62080-104 = "その中でも、今回は「ラッパを吹く天使」なんだと思う。"
62080-105 = "確認されているラッパの音は、4回。"
62080-106 = "それは空から聞こえてきた声とも一致する。"
62080-107 = "「なお三人の御使がラッパを吹き鳴らそうとしている」って言葉とね。"
62080-108 = "[s] \"7人全員がラッパを吹いたら……どうなるの？\""
62080-109 = "ふふっ、どうなるんだろうね。"
62080-110 = "黙示録の内容が、そのまま現実になったとしたら……。"
62080-111 = "次は、「激しい怒りが盛られた7つの金の鉢を持つ天使」たちの番になる。"
62080-112 = "それが終わったら、今の世界は滅んで……信仰ある者のために、新しい世界が訪れる。"
62080-113 = "……って、私たちは教わった。"
62080-114 = "……うん。黙示録の通りなら、そうなるね。"
62080-115 = "でも……あれは本当に「ラッパを吹く天使」だったのかな？"
62080-116 = "……他の「何か」かもしれないということか？"
62080-120 = "うーん……今はまだ、何とも言えない。"
62080-121 = "そもそもアリウスは、何かがあって、何かが起こる場所だから。"
62080-127 = "ほ、本当に来ちゃった……。"
62080-128 = "うわ……うわあああ……。"
62080-130 = "皆さん、静かにしてください。ただの建物です。不安がる必要はありません。"
62080-132 = "は、はい……！"
62080-134 = "確認します。私たちの目的地は、ここ――ポルタパシスの地下にあるとされる記録保管庫。"
62080-135 = "そこには、アリウスの「真実」が眠っているそうです。"
62080-136 = "だとすれば、「ラッパ吹きの天使」についても、何か手がかりを得られるかもしれません。"
62080-137 = "問題は、ここが100年以上も封鎖されているということですが……。"
62080-139 = "せ、先輩？#n扉……開いてますけど……？"
62080-141 = "……本当ですか？#nまさか、誰かがすでに……？"
62080-145 = "……ふむ、むしろ好都合です。"
62080-146 = "閉ざされた扉を開く者は、何かを失うことになる――"
62080-147 = "誰かが開いてくれたのなら、これで懸念が一つ減りましたね。"
62080-149 = "それじゃあ、私たち、本当に……。"
62080-150 = "この下に……降りるんですか……？"
62080-152 = "……。"
62080-153 = "いえ、進むのは私一人です。"
62080-154 = "……恐ろしいことが起きるかもしれませんから。"
62080-156 = "……！"
62080-157 = "わ、分かりました……！"
62080-158 = "では、私たちは何をすれば……？"
62080-160 = "ここに陣地を築いてください。"
62080-162 = "陣地……ですか？"
62080-164 = "はい。作り方は分かりますよね？"
62080-165 = "ああでも、外部からの攻撃に加えて――"
62080-166 = "内部からの攻撃にも対応できる形でお願いします。"
62080-168 = "そ、それって……！"
62080-169 = "先輩に何かあった時のために……？"
62080-171 = "……二度言わせないでください。"
62080-173 = "！！！"
62080-174 = "わ、分かりました！"
62080-179 = "[ns] \"ラッパの聞こえ方に……違いがあった？\""
62080-180 = "はい。ラッパが聞こえた子と……。"
62080-181 = "……。"
62080-182 = "聞こえなかった子がいました。"
62080-183 = "理由は分かるのか？"
62080-184 = "い、いえ……そこまでは……。#nあっ、わ、私は……聞こえた側で……。"
62080-185 = "……。"
62080-186 = "スバル先輩は、たぶん……聞こえてなかったと思います……。"
62080-187 = "……うぅっ。"
62080-188 = "急に泣かないでよ……。"
62080-189 = "す、すみません……でも……。"
62080-190 = "やっぱり、昨日……何かあったんだね。"
62080-191 = "！？"
62080-192 = "あっ、ごめんね。びっくりさせるつもりはなかったの。"
62080-193 = "でも……よかったら教えてほしいな。"
62080-194 = "どうしてあなただけが先生のところに来て、他の子たちは何も言わずに姿を消してしまったのか――"
62080-195 = "どうして、あの子たちがポルタパシスに向かったって分かったのか。"
62080-196 = "[s] \"アツコ、それは……。\""
62080-197 = "うん？"
62080-198 = "……。"
62080-199 = "そっか。先生は待つつもりなんだね。"
62080-201 = "（マイアはしゃがみ込んでしまった。その体は……小さく震えていた）"
62080-202 = "（誰も、言葉をかけられずにいたが……）"
62080-204 = "あ、あの……先生には……#n話しても、きっと大丈夫だと思うんです……。"
62080-205 = "ヒヨリ……？"
62080-206 = "しーっ。"
62080-207 = "す、すみません……。私、話すのがその……あんまり得意じゃなくて……え、えへへ……。"
62080-208 = "でも、えっと……すっごく辛いこととか……苦しいことがあったときって……。"
62080-209 = "誰でもいいから……思ってることを話しちゃうんです。#nそ、そしたら……少し、楽になります……。"
62080-210 = "誰でも……？"
62080-211 = "誰でもです。だ、だけど……こういう時は、先生がおすすめですよ！#n……あっ、邪魔なら、私たちはあっちに行ってるので……！"
62080-213 = "……こちらも、しばらく通話を切りましょうか。"
62080-214 = "そうですね。"
62080-216 = "だ、大丈夫です！先生は……信頼できる人です。#n少なくとも、私にとっては……。"
62080-217 = "何を話しても、ちゃんと聞いてくれて……全力で助けてくれるんです。#n胃薬をくれたし、雑誌も買ってくれたし……。"
62080-218 = "で、でも！先生は……全部[ruby=・・・・・・]やってくれる[/ruby]訳じゃなくて……。#n自分でできることは……自分で頑張らないといけないんですけど……。"
62080-219 = "ちょっと、それは残念だなぁ……って思ったりするんですけどね。"
62080-220 = "でも……そうすることで、生徒が自立できるようになるって……先生が言うので……。"
62080-221 = "うぅ……うまく言えないんですけど……。#nとっ、とにかく！こういうのって……。"
62080-222 = "一人で抱えて悩んでも……辛いことがどんどん増えてくだけなんです……。"
62080-223 = "アリウスの子は、誰かに頼ったり、話したりするのが苦手ですから……。#n私もそうでしたし……今も、ちょっと……。"
62080-224 = "そ、それで、少しでも助けになればと思って……！え、えへへ……。"
62080-226 = "ヒヨリさん……。"
62080-232 = "じゃ、じゃあ、私たちはあっちに行ってるので……。人に聞かれたくない話って、いっぱいありますし……。"
62080-233 = "ついでに、外の様子を見てこようか。"
62080-234 = "ああ、そうしよう。それじゃ――"
62080-236 = "ちょ、ちょっと待ってください……！"
62080-238 = "え？"
62080-239 = "は、はい？"
62080-241 = "……。"
62080-242 = "皆さんにも……お話したいです……。"
62080-244 = "そ、そこまで無理しなくても……。"
62080-245 = "やっとの思いで出した勇気ですし、聞いてあげましょうよ。"
62080-246 = "わ、私なら絶対しないですけどね……。"
62080-251 = "[ns] \"……大丈夫？\""
62080-252 = "……はい。"
62080-253 = "たくさんの人の意見を聞けた方が……私も、どうすればいいのか……ちゃんと決められると思うので……！"
62080-255 = "（マイアは、ゆっくりと昨晩の出来事を語りはじめた）"
62080-256 = "（みんな、固唾をのんで聞いていた……）"
62080-258 = "……。"
62080-259 = "……。"
62080-260 = "……。"
62080-261 = "うっ、うぅっ……うわああああん！！！"
62080-266 = "ヒヨリ！？そんなに泣いちゃったら……！"
62080-267 = "でもでも！こんなのあんまりですっ！悲しすぎますよおおおっ！#nこんなの聞いて、平気でいられる訳ないじゃないですか！うわあああああああん！！"
62080-274 = "ひ、ひひひひ、ヒヨリさん！？く、苦しい……です……。"
62080-275 = "うわあああん！"
62080-276 = "わ、私、なんとか、泣かずに、いたのに……。"
62080-277 = "だからこそなんですよぉぉぉぉぉぉ〜〜〜〜〜〜っ！！！"
62080-279 = "ヒヨリって、やっぱり優しいよね。"
62080-280 = "ああ……いつもそうだった。#n……ミサキ？"
62080-281 = "なっ、なんでもないから。こっち見ないで。"
62080-282 = "ふふっ。いいんだよ、我慢しなくても。"
62080-283 = "泣いてないってば！！"
62080-285 = "[ns] \"話してくれて、ありがとう。\""
62080-286 = "えっ、いや……こっちこそ……聞いてくださって……ありがとうございます……。"
62080-287 = "でも、こうして話してみて改めて思うんです。ラッパの音……どうして私は聞こえたんでしょうか……。"
62080-288 = "……ラッパが聞こえている方には、何らかの共通項があるはずです。"
62080-289 = "得られた情報からの推論にすぎませんが……。"
62080-290 = "その共通項って……。"
62080-291 = "――おそらくは、先生の授業です。"
62080-292 = "えっ？でも、授業ならみんな一緒に……。"
62080-293 = "授業を受けただけで、すべてを理解できるとは限りませんからね……。#n本を読んでも、斜め読みでは理解できないのと同じです。"
62080-294 = "いるんですよ……斜め読みしかしてないのに、さも理解したかのように語りだす人や――"
62080-295 = "本をインテリアにしか思ってない人……！"
62080-296 = "そもそも本は、著者と読者が対話するための媒体なんですよ！#nそれを適当に読んで！通じ合えるわけないじゃないですか！"
62080-298 = "もっとこう！この子たちに敬意を払うべきで――"
62080-300 = "委員長、話が脱線しています。"
62080-302 = "えっ！？あ……うぅ……。"
62080-303 = "し、失礼しました……。とにかく……読書と同じで、授業もまたそういうものなんです。"
62080-304 = "勉強とは、自分の知識外のものを、中に取り入れる行為ですから……。"
62080-305 = "勉強を補助するために、先生が導いてくれる時間というのが授業なんです。"
62080-306 = "だから、どれだけ授業を受けたとしても……。"
62080-307 = "聞き流したり、終わった後に忘れたりするようなら……#nそれは授業を受けたとは言えません。"
62080-308 = "あ……！"
62080-309 = "なので、ラッパの音を聞いた生徒。つまり黙示録の言葉を借りるなら、「世界の終わりの兆し」を感じ取った生徒は――"
62080-310 = "「アリウスの外の知識」を、抵抗なく受け入れられた生徒だったのではないか、と考えています。"
62080-311 = "言い換えると、「新しい考え方」に対して拒否反応が少なかった生徒です。"
62080-312 = "もちろん、これはあくまで仮説です。#nそして、これを証明できるのは……あなたしかいません。"
62080-313 = "い、いかがでしょうか？"
62080-314 = "そうです！たしかにそうかもしれません！#nすごいです、ウイさん！"
62080-315 = "い、いえ……か、勝手に推測しただけなので……。"
62080-316 = "称賛は、素直に受け取ったほうがいいって、いつも言っていますよね？"
62080-317 = "う、あ、うぅ……。"
62080-318 = "そ、それに……「アリウスの外」を受け入れ始めたのだとしたら……。"
62080-319 = "きっと、「今のアリウス」に疑問を持ち始めてもいるはず……。"
62080-320 = "……知識は、人を変える力を持ってますから。"
62080-325 = "それは、つまり……。"
62080-326 = "はい。"
62080-327 = "他の子も、遅かれ早かれ……。"
62080-328 = "アリウスを変えたくないと考える生徒から――#n「敵」と見なされる可能性がある、ということです。"
62080-330 = "まさかと思うけど、ラッパ吹きの天使って……。"
62080-331 = "それは分かりません。#nもしかしたら本当に……黙示録に出てくる天使そのもの、なのかもしれませんし。"
62080-332 = "ですが、別の解釈もできると思いませんか？"
62080-333 = "「外の世界」に対するアリウスの敵意、不安、怒り……そういったものが集まって――"
62080-334 = "一つの「現象」として現れた……そんな可能性も……。"
62080-335 = "……。"
62080-336 = "たしかに、それもあり得るかも。"
62080-337 = "でも……もしも「ラッパ吹きの天使」がそういう存在だとしたら――"
62080-338 = "それは――ウイさんが想像してる以上に……。"
62080-340 = "計り知れないほど、重くて根深い存在かもしれないよ。"
62080-342 = "次回;Apocrypha"
