[translation]
62105-4 = "そんな……。#n天使は？記された終末は！？"
62105-10 = "ということは……まさか……。"
62105-11 = "この手で……。"
62105-16 = "でも……なぜ私なんですか？私はただの……。"
62105-17 = "え？私、だからこそ……？"
62105-18 = "うっ……！？"
62105-25 = "[log]地を滅ぼす者、偽りの者。[/log]"
62105-27 = "[log]その名をみだりに唱える者たちに――[/log]"
62105-29 = "[log]今、滅びの時が訪れる。[/log]"
62105-32 = "……！？"
62105-33 = "はぁっ……はっ、はぁ……。"
62105-34 = "（今のは……一体……？）"
62105-35 = "（いや、だとしたら……）"
62105-36 = "……！"
62105-38 = "先輩！"
62105-42 = "うわっ！？だっ、大丈夫ですか！？"
62105-43 = "汗びっしょりですよ……？何か、あったんですか？"
62105-44 = "い、いえ……何でもありません。"
62105-45 = "それより……今の状況は？"
62105-46 = "前線が押されています……！"
62105-47 = "ど、どうしましょう！？"
62105-48 = "……！"
62105-49 = "ひとまず、皆さんも現場の支援に向かってください。"
62105-50 = "で、でも向こうは「話がしたい」って言ってますけど……？"
62105-54 = "……。"
62105-55 = "それも作戦の一つでしょう。乗ってはいけません。"
62105-56 = "思い出してください。"
62105-58 = "すべての始まりは……先生がトリニティを、アリウスに招いたことだったのですから。"
62105-59 = "……！"
62105-60 = "そ、そうだ！あいつらを完全に追い出さなきゃ！"
62105-61 = "私たち、やれるだけやってきます！"
62105-66 = "……嘘、をついてしまいました。"
62105-67 = "後で謝らないと……。"
62105-68 = "……。"
62105-69 = "……分からなくなってきましたね。#n私は、何がしたかったんでしょう……？"
62105-70 = "……。"
62105-72 = "それでも今は……この巣を守りたいと思っています。"
62105-73 = "ここにいる小さな雛鳥たちが、ほんの少しでも。"
62105-74 = "生きててよかった、って思えるような場所にしていきたいんです。"
62105-76 = "そう。"
62105-77 = "私は巣を守りたかった。"
62105-78 = "アリウスという、小さな巣を。"
62105-83 = "先輩……。"
62105-84 = "うっ……！"
62105-94 = "[log=마이아]先輩、ここ……みんなの家を……#n巣を守るって、言ってたじゃないですか……？[/log]"
62105-97 = "……。"
62105-98 = "先生は、巣を壊しに来た人だ。"
62105-99 = "スクワッドは、巣を見捨てて去っていった人たちだ。"
62105-100 = "その背後には……おそらくトリニティがいるのだろう。"
62105-101 = "……。"
62105-102 = "ここを守らなければいけない。"
62105-103 = "そのために――"
62105-104 = "あの子を追い出してしまったのだから。"
62105-110 = "[log]責任から目を逸らしてはいけない。[/log]"
62105-113 = "[log]責任から、目を逸らしてはいけない。[/log]"
62105-117 = "[log]責任から……目を逸らしてはいけない。[/log]"
62105-120 = "この事態を招いたのが私なら、その先も……。"
62105-124 = "……。"
62105-125 = "力が――"
62105-126 = "力が必要だ。"
62105-127 = "何にも揺るがぬ力が。"
62105-128 = "世界を塗り替えられるような力が。"
62105-129 = "そうなれるのなら――"
62105-130 = "[log][FF6666][i]我らの怒りを解き放て。[/i][-][/log]"
62105-133 = "……！？"
62105-134 = "[log][FF6666][i]トリニティに報復を。ゲヘナに破滅を。[/i][-][/log]"
62105-135 = "[log][FF6666][i]裏切り者に、正当なる審判を。[/i][-][/log]"
62105-138 = "この声は……？"
62105-139 = "[log][i][FF6666]断罪の[/i][-][ruby=[FF6666]ちから[-]][FF6666][i]権能[/i][-][/ruby][FF6666][i]を授けよう。[/i][-][/log]"
62105-140 = "[log][FF6666][i]あまねく敵に、滅びのラッパを。[/i][-][/log]"
62105-143 = "！！！！！"
62105-145 = "さ、さすがスクワッド……！たった4人なのに……！"
62105-146 = "このままだと突破されちゃうよ……！？"
62105-147 = "でもさ……私たち、本当にこれでいいのかな……？"
62105-148 = "やっぱり、そう思う……？"
62105-149 = "先生、いい大人だったよね……。"
62105-150 = "うん……。"
62105-151 = "あれ……？待って。これ、まさか……！？"
62105-152 = "急にどうしたの……って、ええっ！？"
62105-159 = "ラッパの音！？！？"
62105-161 = "次回;弟子たち"
