[translation]
62100-1 = "第10話;巣"
62100-11 = "そ、そう言われても……！"
62100-12 = "どうしよう……？"
62100-13 = "でも、スバル先輩は……ここを守れって。"
62100-14 = "あれ……？でも、陣地を作っておけって言ってたよね……？"
62100-15 = "出入りさせるなって言ってたから、同じことだよね！"
62100-16 = "やっぱり引き返してください！#nそうじゃないと、私たちも発砲するしか――"
62100-21 = "だ、誰！？"
62100-22 = "あっ、ごめん……。#n発砲って言葉が聞こえたから、つい……。"
62100-27 = "……撃たれたな。"
62100-28 = "うん、撃たれたね。"
62100-29 = "なんか、そんな気はしてましたけど……。"
62100-3 = "お願いです、サオリ先輩！どうかお引き取りください！"
62100-31 = "だ、大丈夫なんですか！？相手が多すぎるんじゃ……。"
62100-32 = "心配いらないよ。"
62100-33 = "……なっ、なんでそんなに自信があるんですか！？"
62100-35 = "そんなこと言われても……。"
62100-36 = "見せた方が早いんじゃないかな。"
62100-37 = "それじゃあ、先生。お願いね。"
62100-38 = "[s] \"なんで毎回こうなっちゃうのかなぁ……。\""
62100-39 = "それは……。"
62100-4 = "私たちはここを守るよう、命令されてるんです！誰も中に入れちゃいけないって！"
62100-41 = "これがアリウス流だから、かな。"
62100-6 = "お前たちから快く思われていないことは、よく分かっている。"
62100-7 = "だが、対立してばかりでは何も変わらない……！"
62100-8 = "私たちは、スバルと話をしに来ただけなんだ！"
62100-9 = "そもそも、ここへの立ち入りは強く禁じられているはずじゃなかったのか？"
