[translation]
62110-1 = "第11話;弟子たち"
62110-13 = "うわあああああああっ！？"
62110-19 = "！！！"
62110-20 = "て、天使が……アリウスの生徒を攻撃してます……！"
62110-21 = "やっぱり……本当だったんでしょうか……？"
62110-22 = "ウイさんとシミコさんが、言ってた通りで……。"
62110-25 = "……ラッパが聞こえている方には、何らかの共通項があるはずです。"
62110-26 = "――おそらくは、先生の授業です。"
62110-28 = "なので、ラッパの音を聞いた生徒。つまり黙示録の言葉を借りるなら、「世界の終わりの兆し」を感じ取った生徒は――"
62110-29 = "「アリウスの外の知識」を、抵抗なく受け入れられた生徒だったのではないか、と考えています。"
62110-3 = "て、天使だ！"
62110-31 = "他の子も、遅かれ早かれ……。"
62110-32 = "アリウスを変えたくないと考える生徒から――#n「敵」と見なされる可能性がある、ということです。"
62110-34 = "で？そうだとして、見てるだけでいいの？"
62110-35 = "みんな、同じアリウスの生徒だもんね。"
62110-4 = "「黙示録の天使」だよ！2人もいる……！"
62110-40 = "だ、大丈夫ですかね……。前もすごく手こずったのに……。"
62110-41 = "今は……救護騎士団の方々もいませんし……。"
62110-42 = "だが、天使の数も半分だ。……始めるぞ。"
62110-5 = "ラッパの音、何回目だったっけ？"
62110-6 = "たしか……これで5回目と6回目だったような……？"
62110-7 = "じゃあ、残りって……？"
62110-8 = "……。"
62110-9 = "ちょ、ちょっと！こっちに向かってきてない！？"
