[translation]
63010-1 = "第1話;私たちの憎悪"
63010-3 = "正直……少し、驚いています。#nまさかこのポルタパシスに先生がいらっしゃるとは。"
63010-4 = "[s] \"生徒が急にいなくなったら、探しに行くものだからね。”"
63010-5 = "……随分と面倒見が良いのですね。"
63010-6 = "黙っていなくなる生徒なんて、放っておけばいいじゃないですか。"
63010-7 = "[s] \"……無断欠席の生徒がいたら、心配にもなるよ。\""
63010-8 = "……そもそも、授業なんてお願いした覚えもありませんが。"
63010-9 = "[s1] \"生徒はどうして生徒なんだと思う？\"\n[s2] \"学園に通って、勉強するから生徒なんだと思っているよ。\""
63010-14 = "[ns] \"学ぶからこそ、生徒なんだよ。\""
63010-15 = "ですがそれは……[ruby=・]先[/ruby][ruby=・]生[/ruby][ruby=・]の[/ruby][ruby=・]基[/ruby][ruby=・]準[/ruby][ruby=・]で[/ruby][ruby=・]定[/ruby][ruby=・]め[/ruby][ruby=・]ら[/ruby][ruby=・]れ[/ruby][ruby=・]た[/ruby]勉強ですよね？"
63010-16 = "アリウスには、アリウスなりのやり方があります。"
63010-17 = "私たちの意思を否定して……トリニティの勉強を押しつけるおつもりなのですか？"
63010-21 = "……「そんなつもりはない」とでも？"
63010-22 = "ふふっ。おっしゃらずとも分かりますよ、そのくらい。"
63010-23 = "今の私は、ええ……そういうことが理解できるようになったみたいでして。"
63010-24 = "少なくとも――アリウス分校での出来事については。"
63010-25 = "まぁ、それはそれとして。#nアリウス[ruby=・   ・]分校[/ruby]。私はこの呼び方があまり好きではありません。"
63010-26 = "だって……それは、どこかに属する学園であることを意味するでしょう？"
63010-27 = "ではここで、一つ質問です。"
63010-29 = "どうして、あの日――"
63010-39 = "トリニティが、何百年ぶりかに……アリウスに土足で踏み込んだ――あの日。"
63010-40 = "[ruby=みその]聖園[/ruby]ミカ、ベアトリーチェ、そして……スクワッドが、勝手に自分たちの運命を決めてしまった――あの日。"
63010-41 = "その陰で……[ruby=私たち]他のアリウス生たち[/ruby]は、自らの道すら選べなくなってしまった――あの日。"
63010-43 = "先生はどうして……[ruby=みその]聖園[/ruby]ミカやスクワッドに対しては、あれほどまで慈しんでくださったのに――"
63010-44 = "[ruby=私たち]他のアリウス生たち[/ruby]には、同じように手を差し伸べてくれなかったのですか？"
63010-46 = "[ns] \"それは……。\""
63010-48 = "（その瞬間、「あの日」の直後に交わした会話を思い出した）"
63010-50 = "このようなことを申し上げるのは、大変心苦しいのですが――"
63010-51 = "先生には、アリウス分校の件から手を引いていただきたいのです。"
63010-52 = "本来、この問題は[ruby=自分たち]トリニティ[/ruby]で解決すべきもの。"
63010-53 = "だというのに……先生の力をお借りする結果となってしまって、面目次第もございません。"
63010-54 = "パテル分派の[ruby=・]臨[/ruby][ruby=・]時[/ruby][ruby=・]代[/ruby][ruby=・]表[/ruby]として――"
63010-55 = "そして、サンクトゥス分派の[ruby=・]臨[/ruby][ruby=・]時[/ruby][ruby=・]代[/ruby][ruby=・]表[/ruby]として――"
63010-59 = "心より、お詫び申し上げます。"
63010-60 = "……重ねて、申し訳ございません。ご説明を失念しておりました。#nパテル分派の[ruby=・]代[/ruby][ruby=・]表[/ruby]は、今なおミカ様ですが――"
63010-61 = "しばらくは、第一線から退かざるを得ないでしょう。#n先生もご存知の通り、聴聞会は中断されたままですから。"
63010-62 = "セイア様についても同様です。"
63010-63 = "今回のアリウス攻防戦に参加こそされましたが、未だ全快とは言えません。#nしばらくは療養を続けられる予定です。"
63010-64 = "ですので、[ruby=・]臨[/ruby][ruby=・]時[/ruby][ruby=・]代[/ruby][ruby=・]表[/ruby]である私たちの言葉を以って、パテル分派及びサンクトゥス分派の総意だと捉えていただいて構いません。"
63010-65 = "あるいは……ナギサ様率いるフィリウス分派は、また別の意見を出されるかもしれませんが。"
63010-66 = "ですが、ティーパーティーの意思は、多数決によって決定されます。"
63010-67 = "これほどの大事ですし、少数意見も尊重されてしかるべきですが……過半数の意見を覆すには至りません。"
63010-68 = "ですから……先生。どうか、私たちの行く末を見守っていていただきたいのです。"
63010-69 = "私たちの問題を、私たち自身で解決させてください。"
63010-70 = "もちろん、先生が動いてくだされば――"
63010-71 = "ずっと早く、もっと良い形で、決着するのかもしれません。"
63010-72 = "けれど、大人に頼り切ってしまえば……生徒の成長する機会がなくなってしまいますから。"
63010-74 = "……そういうことだったのですね。"
63010-78 = "[ns] \"！？\""
63010-79 = "ふふっ、そんなに驚かないでください。"
63010-80 = "およそ分かる、と言ったではないですか。"
63010-81 = "ですが……先生は少しばかり信じすぎているのでは？#n生徒を――それも、トリニティの上層部を。"
63010-82 = "サンクトゥス分派とパテル分派、それぞれの臨時代表。"
63010-83 = "代表が職務を離れた途端、その座に収まった生徒たち。"
63010-84 = "何の後ろ盾もなく、そんなことができたとでも？"
63010-85 = "あそこは……いつ何時だって、生馬の目を抜くような場所だというのに。"
63010-87 = "ともあれ、理解はしました。そういう事情であれば、先生に大きな責任は無い――#nどころか、全く無いとさえ言えるかもしれません。"
63010-88 = "まあ、あの日以降も変わらず、アリウスは地獄の渦中だったという事実は変わりませんが。"
63010-89 = "[s] \"……。\""
63010-90 = "今後は気をつけたほうが良いかと。"
63010-91 = "先生の立場では、悪意をもって近づく生徒がいたとして……#nその罠から逃れるのは難しいでしょうから。"
63010-92 = "事実、先生は見落とされていたわけですから。"
63010-93 = "アリウスに残された子が、勇気を振り絞って踏み出した外の世界で――"
63010-94 = "どこにも馴染めず、周囲の視線に耐え切れず……結局、「[ruby=自分]アリウス[/ruby]は、[ruby=自分]アリウス[/ruby]の生き方しかできない」と挫折してしまうかもしれない。"
63010-95 = "この世界のどこにも、[ruby=自分]アリウス[/ruby]の居場所はないのだと。#n大きな傷を負って、アリウスに戻らざるをえないかもしれない。"
63010-96 = "その可能性を、見落としたんです。"
63010-97 = "あろうことか、トリニティの上層部を信じる――という選択の結果として。#n……何か間違っていますか？"
63010-98 = "それとも……他の学園に掛かりきりで、#nアリウスなんて端から気にも留めていなかったのでしょうか。"
63010-99 = "[s] \"……。\""
63010-100 = "[ruby=いま]現在[/ruby]は、過去を礎にした建築物です。#nすべての過去は、現在と無関係ではありません。"
63010-101 = "……過去は過去。過去の憎悪は、現在を生きる者には関係ない。そう言う人だっているでしょう。"
63010-102 = "ですが私は、その意見にはどうしても賛同できません。"
63010-103 = "過去の結果として、現在のアリウスがあり……#nいま現在、アリウスは雁字搦めにされているのですから。"
63010-105 = "先生は言いましたよね。"
63010-106 = "学園に通って勉強をするのが生徒だ、と。"
63010-107 = "でしたら、私はこう答えましょう。"
63010-109 = "ポルタパシス――ここに記録されているすべてが、#n私たちにとっての「勉強」です。"
63010-110 = "生徒の本分が「勉強」であるならば……私はちゃんと行動してきたと思いますよ。"
63010-111 = "その本分を守るために、ここへ来たのですから。"
63010-112 = "もしも、「これは勉強じゃない」と先生がおっしゃるのなら。"
63010-113 = "私は聞きたい。#n勉強に優劣や区別をつけることが、教育者の姿勢なのですか――と。"
63010-115 = "罰は、受け継がれていくものです。"
63010-116 = "その事実だけは――誰もが認めなければならない。"
63010-118 = "過去の「恩恵」だけを享受して、「罰」を背負わない。#n……そんなことは認められません。"
63010-119 = "「罰」を背負わないと言うのなら、過去が残したあらゆるものすべて――"
63010-120 = "知識、知恵、資産、すべての権利や権力をも――「罰」と同じように、拒むべきでしょう。"
63010-121 = "……欲しいものだけを選び取る？"
63010-122 = "[ruby=私たち]アリウス[/ruby]からすれば、吐き気をもよおすような傲慢でしかありません。"
63010-125 = "あの日、先生はトリニティのやり方を尊重することにし……#nだから、アリウスには干渉しなかった。"
63010-126 = "そんな先生を……私は許しません。#n[ruby=・]罪[/ruby][ruby=・]の[/ruby][ruby=・]無[/ruby][ruby=・]い[/ruby][ruby=・]者[/ruby]を、許すことはできませんから。"
63010-127 = "ですがその代わり……アリウスにも、「アリウスのやり方」で生きる自由を、認めてほしいのです。"
63010-128 = "トリニティには、トリニティのやり方があったように。"
63010-129 = "まさか、一方だけ尊重して、もう一方は認めないなどとは……おっしゃいませんよね？"
63010-130 = "[s] \"……。\""
63010-131 = "[ruby=私たち]アリウス[/ruby]は――馴染めないんです。"
63010-132 = "外の世界は、魅力的かもしれません。#nですが、そこに[ruby=私たち]アリウス[/ruby]の居場所はありませんでした。"
63010-133 = "実際、適応できずに戻ってきた子はたくさんいます。"
63010-134 = "だから私は、その子たちを受け入れて、アリウスのやり方で進む道を示しました。"
63010-135 = "試験も、勉強も、要りません。#n[ruby=私たち]アリウス[/ruby]は、[ruby=私たち]アリウス[/ruby]の生き方で生きていきます。"
63010-136 = "だから……お願いします。"
63010-137 = "スクワッドを連れて、アリウスから立ち去ってください。"
63010-138 = "そうしていただけるなら、先生やスクワッドに、決して危害を加えません。"
63010-139 = "「黙示録の天使」については……。"
63010-140 = "……。"
63010-141 = "こちらで、どうにかします。"
63010-142 = "少なくとも「ラッパ吹きの天使」は、私が確実に対処できますから。"
63010-143 = "[s] \"「ラッパ吹きの天使」……？\""
63010-144 = "おや、この名を聞いて、先生にも心当たりが？"
63010-145 = "さすがです。生徒のこととなれば、何であれ察しがいい。"
63010-146 = "であるならば、私たちの願いも……理解していただけると信じています。"
63010-147 = "[s] \"……。\""
63010-151 = "さあ、お帰りはあちらです。"
63010-152 = "後ろで控えているスクワッドの皆さんも、ご一緒に。"
63010-156 = "そして――"
63010-157 = "もう二度と、この地を訪れないでください。"
63010-158 = "……今まで、お疲れ様でした。"
63010-162 = "スバル。アリウスのやり方、と言っていたな。"
63010-166 = "……サオリ。"
63010-167 = "言い残したことがあるのなら、伺いましょう。"
63010-168 = "それを口実に戻ってこられても、面倒なだけですから。"
63010-169 = "言い残したこと……ではないな。一つ、聞きたいことがあるんだ。"
63010-170 = "お前の言うアリウスのやり方――"
63010-174 = "その先には……何があるんだ？"
63010-175 = "……！"
63010-177 = "次回;それでも"
