[translation]
63020-1 = "第2話;それでも"
63020-10 = "スバル。「厳格な教官と、親切な百人隊長」の話は知っているか？"
63020-102 = "[ns] \"……え！？\""
63020-103 = "他の三人とも話はついている。"
63020-107 = "……まあ、そういうこと。"
63020-108 = "えへへ……。#nサオリ姉さんが、そう決めたのなら……。"
63020-109 = "こんな生活は、いつまでも続けられるわけじゃないからね。"
63020-11 = "当然です。組織の運営には不可欠とも言える概念ですから。"
63020-110 = "先生……何も言わず決めてしまってすまない。#n話そうとは思っていたんだが、なかなかタイミングが合わなくてな。"
63020-111 = "[s1] \"それは……構わないけど。\"\n[s2] \"みんな、本当に大丈夫なの……？\""
63020-117 = "ああ。この件が終わったら、私たちは自首する。"
63020-118 = "……もう、疲れたんだ。"
63020-119 = "影を探してコソコソするのも、陽の下を堂々と歩けないのも。"
63020-12 = "……自分がその「親切な百人隊長」だった、などと言うつもりではないですよね？"
63020-120 = "忘れたんですか？あなた達はテロリストです。"
63020-121 = "「殺意」と「悪意」を持って、テロを起こした。"
63020-122 = "どれほどの刑罰が科されるか、想像もつきませんよ？"
63020-123 = "そうだろうな。#n……だが、その方がマシだ。"
63020-124 = "自分でやったことのケジメを、自分でつける。"
63020-125 = "これ以上、自分自身から逃げるのは嫌なんだ。"
63020-126 = "他のアリウス生たちについては、心配しなくていい。"
63020-127 = "すべて私が主導し、私が実行したことにする。"
63020-128 = "……まあ、全くのウソというわけでもないからな。"
63020-129 = "だから、お前も――"
63020-134 = "[log=니코 스바루][FF6666]何が言いたいの、[-][ruby=[FF6666]じょうまえ[-]][FF6666]錠前[-][/ruby][FF6666]サオリ。[-][/log]"
63020-137 = "……何？"
63020-138 = "何を言いたいのかって聞いてるの。"
63020-139 = "……いや、答えなくてもいい。あまりにも見え透いてるから。"
63020-140 = "自首する？もう逃げたくない？"
63020-141 = "今さら善人ぶるつもり？"
63020-142 = "それとも真理を悟った賢者にでもなったつもり？"
63020-143 = "世界を憐れんで、すべてを諦観しているつもり？"
63020-147 = "お前が世界のすべてを知り尽くしたとでも？"
63020-148 = "そんな風に分かった顔をして、アリウスをお前のものみたいに見下すな。"
63020-149 = "それは……トリニティの連中と何一つ変わらない……！"
63020-150 = "ふざけるのも大概にして！"
63020-151 = "目がついているの[ruby=ここ]ならアリウスを見[/ruby]ろ！#nお前が出て行ったときと、何が変わったというの？"
63020-152 = "相変わらず廃墟のまま！あの頃よりひどくなった場所だってある！"
63020-153 = "お前に……[ruby=ここ]マダムが去った後のアリウス[/ruby]の何が分かるって言うんだ！"
63020-154 = "お前たちも先生と同じだ。何も！気にかけてこなかった！"
63020-155 = "それでもずっと！[ruby=ここ]マダムが去った後のアリウス[/ruby]を守ってきたのは私だ！#n――私たちなんだよ！"
63020-159 = "[ruby=お前ら]スクワッド[/ruby]は全部放り投げて逃げ出したくせに！"
63020-16 = "まさか。その役割はお前だっただろう？#nどう考えても、私は「厳格な教官」だった。"
63020-160 = "違うんだ。そんな大それた話をするつもりはない。"
63020-161 = "真理を悟った賢者だなんて、私はそんなものを気取るつもりもないし、そんな資格もない。"
63020-162 = "私は、ただ……。"
63020-163 = "ただ――"
63020-166 = "（あの日以来、初めて見上げた空は、ただ青く澄んでいた）"
63020-167 = "（だからこそ、改めて思い知らされた）"
63020-168 = "（ああ――きっとこの世界は、ずっと前から変わらずに、そこにあったのだと）"
63020-169 = "（目は見ることに飽きることがなく、耳は聞くことに満足することがない）"
63020-17 = "人は、生きてきたようにしか生きられませんからね。"
63020-170 = "（すでにあるものは、後にもまたある）"
63020-171 = "（先になされた事は、また後にもなされる。日のもとに新しきことなし）"
63020-172 = "（幸せなこと、辛いこと。傲慢も、謙遜も。#n……怒りや憎しみさえも）"
63020-173 = "（それこそ――）"
63020-175 = "[ruby=Vanitas vanitatum et omnia vanitas]全ては虚しい。どこまで行こうとも、全てはただ虚しいものだ[/ruby]。"
63020-178 = "――自分の人生が[ruby=・]惜[/ruby][ruby=・]し[/ruby][ruby=・]い[/ruby]と、思うようになっただけだ。"
63020-179 = "……！"
63020-185 = "[log=니코 스바루]そんな風に[/log]"
63020-186 = "[log=니코 스바루]言うな。[/log]"
63020-187 = "[log=니코 스바루]裏切って[/log]"
63020-188 = "[log=니코 스바루]逃げ出したくせに、[/log]"
63020-189 = "[log=니코 스바루]どうして[/log]"
63020-19 = "そうだな。私は、学び、経験した通りにしか、周囲と接することができなかった。"
63020-190 = "[log=니코 스바루]そんなことを言うの。[/log]"
63020-193 = "[log=니코 스바루][FF6666]人生が惜しい？[-][/log]"
63020-195 = "[log=니코 스바루][FF6666]それなら、ここにいる[-][ruby=[FF6666]私たち[-]][FF6666]アリウス[-][/ruby][FF6666]は？[-][/log]"
63020-198 = "[log=니코 스바루][FF6666]……何があっても、いつか帰ってくる子供たちのために[-][/log]"
63020-20 = "スクワッドは、精鋭だったからな。#nリーダーともなれば、他よりも厳しい訓練が課されたものだ。"
63020-200 = "[log=니코 스바루][FF6666]この巣を守ろうとした私は？[-][/log]"
63020-203 = "過去は！決して消えやしない！！"
63020-204 = "スバル！？"
63020-205 = "過去はいつまでも残る！過去が現在を証明している！"
63020-206 = "これが！このポルタパシスが！#nここに絡みついたアリウス分校の過去こそ、私そのものなんだ！"
63020-207 = "結局、この世で一番大切なのは自分自身だ。#n自分が死ねば、世界だって死ぬ！"
63020-208 = "それなら……自分の生き方や在り方こそ――世界そのものだ！"
63020-209 = "誰も、人生の責任を取ってくれやしない。#nだから私は、子供たちから不安を取り除いた！"
63020-210 = "どんなことが起きても、ちゃんと生き抜けるように！"
63020-216 = "あなたは間違っていましたよ、マダム。それは変わらない事実です。"
63020-217 = "でもあなたが遺したすべてが……完全に間違いだったわけじゃない。"
63020-218 = "意味のない事は起こらない。出来事は、起きることで意味を得る。"
63020-219 = "だから――意味のない苦しみなんて、ないのでしょう。"
63020-22 = "……私は結局、自分の過去を超えることができなかった。"
63020-220 = "意味のない過去が存在しないのと、同じように。"
63020-225 = "な、なんかちょっと……変じゃないですか……？"
63020-24 = "……つくづく、情けない話だ。"
63020-241 = "先生！私たちの後ろへ！"
63020-247 = "……リーダー、ちょっと煽りすぎたね。"
63020-248 = "ち、違う……私はそんなつもりなんて――"
63020-249 = "この話は後にしよっか。"
63020-25 = "まったく……あなたを慰める羽目になるとは思いませんでしたが……卑下する必要はありませんよ。"
63020-250 = "今は――"
63020-256 = "[log]第七の御使が吹き鳴らすラッパの音がする時。[/log]"
63020-258 = "[log]地を滅ぼす者、偽りし者。[/log]"
63020-26 = "言ったでしょう？人は、生きてきたようにしか生きられないものです。"
63020-261 = "[log]その名を汚す者どもを[/log]"
63020-263 = "[log]ついに滅ぼされる時が来ました。[/log]"
63020-266 = "――目の前のことから片づけよう。"
63020-268 = "次回;ラッパ吹きの天使"
63020-27 = "ああ。私もそう思っていた。"
63020-3 = "その先には……何があるんだ？"
63020-32 = "――アリウスにいた頃まではな。"
63020-36 = "……それは、どういう意味で？"
63020-37 = "おおよそ人の考え方は、それまでの人生に左右される。#nそして、そうやって身についた考え方が、自分の人生を再生産していく。"
63020-38 = "この観点で見れば、お前の意見も間違いとは言えないだろう。"
63020-39 = "だがな。[ruby=・   ・   ・   ・   ・   ・   ・   ・   ・   ・   ・   ・]望みに任せて生きる可能性[/ruby]だって、人は持っているんだ。"
63020-4 = "……！"
63020-40 = "これは……アリウスを出てから学んだことだ。"
63020-44 = "……だからなんだと言うのですか？"
63020-45 = "お前の考えはよく理解できる、ということだ。私も同じだったからな。"
63020-46 = "道を見失った子供たちに、進むべき道を示し、生きる意志を吹き込んでやる。"
63020-47 = "それは同時に、お前自身の生きる意味や意志にもなっていたはずだ。"
63020-48 = "だが……その先には何がある？#nお前の言う「アリウスのやり方」で、その行き着く先は？"
63020-5 = "話を聞きながら、昔のことを思い出したんだ。それで、つい気になってな。"
63020-52 = "……答えなくていい。私にも分かっていることだからな。#nそこにあるのは……憎悪と怒りだけだ。"
63020-53 = "それ以外には何もない。意味なんかないんだ。何も残らない。そういうやり方だからな。"
63020-54 = "私だってアリウスに残ったまま、別の世界があるなんて知らずにいたら――"
63020-55 = "「先生」に出会えなかったら……お前と何ひとつ変わらない生き方をしていただろう。"
63020-56 = "ずっと「厳格な教官」を演じ続けて、自分の知らないことは、全部否定して。"
63020-57 = "――自分たちのものだと思い込んだ憎悪を、果てしなく胸に抱き続けながら。"
63020-58 = "このやり方が間違っていると、今さら非難するつもりですか？"
63020-59 = "そもそも正しいか否かを判断できるようなものじゃない。"
63020-6 = "……過去の思い出にしがみつくのは、老いと弱さの証だそうですよ。#n衰えたのではないですか？"
63020-60 = "ただ……「他」を知るというのも、役に立つかもしれないという話だ。"
63020-61 = "自分の知らない外の世界。#nそれを、ほんの少しでも「学んで」から、改めて考え直してはみないか？"
63020-62 = "……考え方なんてのは、思いのほか簡単に変わったり揺らいだりするからな。"
63020-63 = "これを、何も知らない連中……例えばお前の言うところの、トリニティのお嬢様が言ったなら。"
63020-64 = "それこそ偽善と欺瞞に満ちた、能天気な楽観主義者の戯言に聞こえるだろう。"
63020-65 = "だが……私やスクワッドの意見ならどうだ？"
63020-66 = "……底辺で這いずり回ったのは、私たちも同じだったはずだ。"
63020-68 = "……能天気な楽観主義者なんて、私も好きじゃなかった。"
63020-69 = "正直に言えば、嫌いだった。憎しみしか持てなかった。"
63020-7 = "そうかもしれない。昔に比べれば、鈍くなった感覚はある。"
63020-70 = "世の中の醜い部分には目もくれず。"
63020-71 = "むやみやたらに自分の主張を押し付けてくるのが、本当に嫌いだった。"
63020-72 = "だが、例外はいた。むしろ――"
63020-75 = "[log]私はサオリと、対等に話がしたい。[/log]"
63020-77 = "[log]チャンスは、なければ作り出せばいいからね。[/log]"
63020-79 = "[log]もしそれがダメでも、次のチャンスを作ればいい。[/log]"
63020-8 = "だが、それと引き換えに得たものも、確かにあったんだ。"
63020-82 = "世界のおぞましさを知りながら――"
63020-83 = "世界は元から醜いものだと認めながら――"
63020-85 = "それでも、決して諦めない人がいた。"
63020-86 = "結局、私は説得されてしまった。"
63020-87 = "「それでも」#n――この言葉は、あまり好きではなかったんだがな。"
63020-89 = "不利な状況にさらされながら、[ruby=・]そ[/ruby][ruby=・]れ[/ruby][ruby=・]で[/ruby][ruby=・]も[/ruby]と諦めず前を向く。#nこの言葉にも、意味があるのだと思うようになった。"
63020-9 = "こんなものは、先生の前でするような話じゃないが――"
63020-90 = "偉そうに語っていますが……あなただって大差ないでしょう？"
63020-91 = "コソコソ逃げ回る、お尋ね者のくせに！"
63020-96 = "ああ、その通りだ。"
63020-97 = "だから……もうやめるつもりだ。"
63020-98 = "……はい！？"
