[translation]
63035-1 = "第3話;ラッパ吹きの天使"
63035-4 = "くっ……！"
63035-5 = "[ns] \"サオリ！\""
63035-6 = "サオリ姉さん！"
63035-7 = "問題ない……かすり傷だ。"
63035-8 = "大丈夫には見えないけど……リーダーがそう言うなら……。"
63035-9 = "で、本当にどうする？#n「ああいうの」には勝てたためしがないけど……。"
63035-10 = "しかも、今回のは次元が違う。"
63035-14 = "え……？ラッパの音……？#nあっ！前に言ってたのってこれのこと……！？"
63035-15 = "そうだよ！#nでも……なんか、空が暗くなってきてない……？"
63035-17 = "まだお昼なのに……！？"
63035-18 = "何が起きてるの……？"
63035-25 = "いきなり夜になっちゃった、ってこと……！？"
63035-26 = "これ……私知ってる！経典に書いてあるやつだよ……！"
63035-27 = "太陽の三分の一と、月の三分の一と、星の三分の一とが打たれて、これらのものの三分の一は暗くなり――"
63035-28 = "昼の三分の一は明るくなくなり、夜も同じようになった。#n……って！"
63035-34 = "また……！？"
63035-35 = "これで6回目……！"
63035-36 = "でも、おかしくない？何でまた鳴ってるの……？"
63035-37 = "そうだよね……このままだと7回どころか、14回のラッパになっちゃうよ……？"
63035-41 = "き、急に暗くなりましたね……何が起こってるんですか……？"
63035-42 = "スバル！やめろ！何を考えているんだ！#nお前に……何があったんだ！"
63035-46 = "……こっちの声は聞こえてないっぽいね。"
63035-47 = "……。"
63035-48 = "せ、先輩……！"
63035-49 = "スバル先輩！！！"
63035-54 = "……。"
63035-55 = "どう、して……？"
63035-56 = "今まで……どこに……なぜ、ここに……？"
63035-58 = "この子は、ずっとここにいたよ。"
63035-59 = "この場所に、私たちと一緒に。"
63035-60 = "どうして気づけなかったのかって？それはね……。"
63035-61 = "あなたが、この子を見ようとしなかったから。"
63035-62 = "そうだよね、スバル？"
63035-63 = "ううん……今はもう、「現象」になってしまった。#n「ラッパ吹きの天使」って呼ぶべきかな？"
63035-64 = "アツコ……何か、知っているのか？"
63035-65 = "今まではただの推測だったけど……これで、確信に変わった。"
63035-66 = "ちゃんと、順番に話すね。"
63035-67 = "それと。こうなった以上、はっきり言っておくよ。"
63035-68 = "スバル。#nあなた一人だけが「アリウス」な訳じゃないんだよ。"
63035-70 = "次回;ロイヤルブラッド"
