[translation]
63040-1 = "第4話;ロイヤルブラッド"
63040-2 = "ロイヤルブラッド。"
63040-3 = "特別な血、特別な家系。"
63040-4 = "思い返せば昔から、色々な人に持ち上げられてきた。"
63040-5 = "でも……そこに、大した意味なんてなかった。"
63040-6 = "どんなに特別でも、酷い目に遭うのは同じだったから。"
63040-7 = "それどころか、できないことと、言えないことばかり増えていった。"
63040-9 = "ありがとう、サッちゃん。"
63040-10 = "サッちゃんがいてくれたから、私は耐えられたんだ。"
63040-12 = "ありがとう、[USERNAME]先生。"
63040-13 = "先生に出会って、やっと私は自分になれた気がするんだ。"
63040-15 = "ミサキも、ヒヨリも。"
63040-16 = "みんながいなかったら私は、ただの喋らない人形か、生贄として――"
63040-17 = "一生、誰かと何かの象徴として、生き続けていたんだろうね。"
63040-19 = "アリウスの秘儀に触れて、勘違いしちゃったのかな？"
63040-20 = "この地に眠るもの。その答えに近づいたからって、何でもできると思った？"
63040-24 = "――残念。"
63040-25 = "その程度のことはね、私はずっと前から知ってたんだよ。"
63040-26 = "でも、先輩のお陰で確信できたことがある。"
63040-27 = "黙示録の天使。あるいは、その現象――あれは、[ruby=・   ・   ・]先輩が[/ruby]引き起こしたんだね。"
63040-28 = "しかも、最初は無自覚に。ある意味では[ruby=・   ・   ・   ・]召喚した[/ruby]と言ってもいいのかな。"
63040-29 = "先輩にとっては不本意かもしれないけど――"
63040-30 = "あれは、経典に記された「7人のラッパ吹きの天使」なんかじゃない。"
63040-31 = "でもね、昇華する可能性はあった。#n[ruby=・   ・   ・   ・   ・   ・   ・]本物になりうる[/ruby]存在だった。"
63040-32 = "先輩が、完全無欠の審判者でいられたなら、ね。"
63040-33 = "完全無欠の……「審判者」？"
63040-34 = "何度も言ってるけど、先輩だけがアリウスなわけじゃない。"
63040-35 = "アリウスの秘儀を知ってるのは、先輩だけじゃないんだよ。"
63040-36 = "先輩にとっては初めて知ったことでも、私には「知らなきゃいけないこと」だったから。"
63040-37 = "ただ、それを口に出すのが禁じられていただけ。#n……それは今も変わらないけどね。"
63040-38 = "――アリウスのロイヤルブラッドって、そういうものだから。"
63040-39 = "でも、お礼は言わせて。"
63040-40 = "先輩が暴いてくれたおかげで、やっと話せるようになったから。"
63040-41 = "ふふっ、自分だけが知ってて……#nそれを誰にも話せないのって、すごく苦しいんだよ。"
63040-42 = "[ns] \"つまり……どういうことなの……？\""
63040-43 = "あの天使……いや、天使のようなもの。"
63040-46 = "あれはね、アリウスに積もったあらゆる感情が形を成した「現象」なんだ。"
63040-47 = "前に話したよね？アリウスは、「何か」が起こる土地になったって。"
63040-49 = "[ns] \"あ……！\""
63040-51 = "ここには、もともと「何か」があった。"
63040-52 = "怒り、嘆き、恨み、絶望、諦念……そういう思念が積もり積もって、ここに集まってる。"
63040-54 = "アリウスは世界の滅亡を望んでいたのか、って？"
63040-57 = "その通りだよ。"
63040-61 = "温もりを得られなかった子どもが、温もりを得るために村を燃やす――そんな話があるくらいですから。"
63040-62 = "失うものがない人にとって……世界の終わりは「救済」なのかもしれません。"
63040-64 = "[ns1] \"昇華する可能性があったっていうのは？\"\n[ns2] \"完全無欠の審判者なら可能だったって言ってたよね。\""
63040-67 = "そうだね。アリウスに堆積したものは、それだけの結果を導くに足る「何か」だった。"
63040-68 = "……少なくとも、トリニティに「何らかの報い」を返す程度なら、十分だった。"
63040-69 = "でもそれは、スバル先輩が「完全無欠」だった場合の話。"
63040-70 = "つまり、何かが欠けてたってこと？"
63040-71 = "そう。"
63040-72 = "それが、この子。"
63040-73 = "あ……！"
63040-77 = "わ……たし……は……。"
63040-78 = "やっと分かったみたいだね。"
63040-79 = "先輩がこの子を「捨てた」瞬間……先輩の行動は、正当性を失った。"
63040-80 = "先輩を[ruby=・]媒[/ruby][ruby=・]体[/ruby][ruby=・]に[/ruby][ruby=・]し[/ruby][ruby=・]て[/ruby]、この現象を構築していたなら、まだ良かったかもしれない。"
63040-81 = "でも先輩は、[ruby=・]自[/ruby][ruby=・]分[/ruby][ruby=・]が[/ruby]「ラッパ吹きの天使」になろうとした。"
63040-82 = "気持ちは分かるよ。先輩だけじゃなく、アリウスに残ったみんなは――どんな形であれ、審判者になりたかったはずだから。"
63040-83 = "でもね。"
63040-84 = "審判者っていうのは、本来――完全無欠じゃなきゃいけないの。"
63040-85 = "『お前が仕掛けた罠に、お前自身がかかって倒れるだろう』"
63040-86 = "先輩なら、この経典の一節……覚えてるよね？"
63040-87 = "せめてマイアが、私たちを……先生を、頼らなかったら。"
63040-88 = "まだ、先輩は審判者になれたかもしれなかった。"
63040-91 = "私を――見捨てないでください！"
63040-103 = "あ……。"
63040-104 = "あ……ああ……。"
63040-106 = "スバル？"
63040-107 = "かすかに声が聞こえた。もしかして……！"
63040-108 = "……。"
63040-116 = "ヒ、ヒヨリさん……？"
63040-117 = "い、言いたいことがあるなら……言わなきゃダメです。"
63040-121 = "わ、私たち……ちゃんと話をしようって……だからここまで来たんですよね？"
63040-123 = "……。"
63040-127 = "……そう、ですよね。ヒヨリさん……ありがとうございます。"
63040-130 = "あの、先輩……？#nその、ずっと、伝えたいことがあったんです。あの時から、ずっと……。"
63040-132 = "大丈夫ですよ、先輩。"
63040-133 = "全部……大丈夫ですから。"
63040-134 = "……！"
63040-135 = "あ、いや、全部ってわけじゃ……ないかもしれないですけど……。#n[ruby=・]そ[/ruby][ruby=・]れ[/ruby][ruby=・]で[/ruby][ruby=・]も[/ruby]、私は先輩を信じてます。"
63040-136 = "先輩も、スクワッドの皆さんも。アリウスのみんなも。"
63040-137 = "そして、[USERNAME]先生も。#n私は、みんなが大好きなんです。"
63040-138 = "私は今でも、アリウスが残っててほしいって思ってます。"
63040-139 = "そして……アリウスが、もっと良い学校に変わってほしい。"
63040-140 = "だ、だから……！"
63040-144 = "すー……はぁ……。#nすー……っ！！"
63040-145 = "助けてください、先輩！！！！"
63040-147 = "……！"
63040-148 = "私……先輩のハーモニカ、本当に大好きなんです！！！"
63040-150 = "次回;あの日のハーモニカ"
