[translation]
63050-1 = "第5話;あの日のハーモニカ"
63050-3 = "これ、ハーモニカ……。#n先輩が落としたみたいだったので、拾っておきました……。"
63050-7 = "あっ、でも、今すぐ吹いてほしいとかじゃなくて……！"
63050-8 = "今はきっと、いろいろ大変でしょうし……！"
63050-9 = "でも、いつかまた……あの時みたいに……。"
63050-10 = "先輩の演奏、聴かせてほしいです……。"
63050-11 = "あ……ああ……。"
63050-12 = "（こんな結末を望んだ訳じゃなかった）"
63050-13 = "（責任から目を背けてはいけない）"
63050-14 = "（それは、当然のことなのに）"
63050-19 = "消えた……！？"
63050-20 = "先輩！"
63050-21 = "探そう。アリウス分校の外には出られないはずだから。"
63050-29 = "[ns] \"もしもし？どうしたの？\""
63050-30 = "天使が……3体目の天使が現れました！"
63050-31 = "で、でも……なんて説明すれば……。#nえっと、えっと、3体目が現れたと思ったら、それまでいた2体は消えたんです！"
63050-32 = "3体目の天使に吸収されたようにも見えて……。"
63050-33 = "で、でもそれよりも！#n天使の中に、人みたいなのが見え隠れしてて……。"
63050-34 = "信じてもらえないかもですが……スバル先輩そっくりなんです！"
63050-35 = "先生！"
63050-36 = "[ns] \"スバルだ！\""
63050-40 = "[ns] \"ありがとう、みんな！また何かあったら連絡して！\""
63050-41 = "はい！"
63050-47 = "（……）"
63050-49 = "（ここから見える空は、こんなにも曇ってるのに）"
63050-50 = "（たしか、サオリの記憶で見た空は……）"
63050-53 = "そうか。"
63050-54 = "サオリ。"
63050-55 = "君の見ていた空は……こんな光景だったのか。"
63050-57 = "（アリウスの風景は、いつも同じだった）"
63050-58 = "（そこに生きる私たちも、やはりそうだった）"
63050-60 = "（すべてが流れ着き、堆積して、忘れ去られる場所）"
63050-61 = "（アリウスはきっと、そんな場所だったんだ）"
63050-62 = "（たとえ違ったとしても、いつの間にか、そうなってしまっていたのだろう）"
63050-64 = "（世界はアリウスを隔離し、ついには忘れることを選んだ）"
63050-65 = "（いや、それすら甘い評価かもしれない）"
63050-66 = "（世界は横柄で、勝手気ままで。予想もつかない方向へ、無遠慮に進んでいくものなのだから）"
63050-67 = "（……煩わしいものや邪魔なものを、簡単に払い捨てながら）"
63050-69 = "（それなら……。#n忘れられた者たちは、誰が覚えていてくれるのか）"
63050-70 = "（届かぬ声を、誰が覚えていてくれるのか）"
63050-72 = "先輩、先輩！ハーモニカ吹いてくださいよ！"
63050-73 = "廃墟で、ひとり感傷にひたりながらハーモニカを吹くなんて……。"
63050-74 = "それって、ちょっと……カッコつけすぎのような……。"
63050-78 = "あの、私も……。"
63050-82 = "[log=스바루]やめて……。[/log]"
63050-85 = "久しぶり、ですし……。"
63050-89 = "[log=스바루]……お願い、です。やめてください。[/log]"
63050-93 = "先輩の演奏……聴きたいです。"
63050-97 = "[log=스바루]！！！[/log]"
63050-101 = "[log=스바루]！？！？[/log]"
63050-108 = "後悔してる？"
63050-109 = "アツ……コ……。"
63050-110 = "大丈夫だよ。私たちだって、そうだったんだから。"
63050-111 = "でも、アリウスは……。"
63050-112 = "……トリニティがアリウスにしてきたことは……！"
63050-113 = "うん、そうだね。"
63050-114 = "でも、それはそれ。"
63050-115 = "そのせいで今こうして先輩が苦しんでるのって、ちょっと不公平なんじゃない？"
63050-116 = "……この言葉、覚えてる？"
63050-117 = "『とげのあるむちをければ、傷を負うだけである』"
63050-118 = "……！"
63050-119 = "一緒にやろう。"
63050-120 = "全部をひとりで背負わないで。"
63050-121 = "今……さら？"
63050-122 = "うん。#n[ruby=・]そ[/ruby][ruby=・]れ[/ruby][ruby=・]で[/ruby][ruby=・]も[/ruby]――"
63050-123 = "正直に話せば、先生はきっと助けてくれる。"
63050-124 = "……！"
63050-125 = "あ、でも私たちは、ちょっと矯正局にお世話になるかもしれないから……その間はよろしくね？"
63050-126 = "……。"
63050-127 = "いや……だめですよ。そんなのは……。"
63050-128 = "そんなの、できません。"
63050-129 = "私は。"
63050-130 = "私たちは。"
63050-131 = "アリウスは、まだ……納得していないんです。"
63050-132 = "あなたが言ったように、ここはもう「そういう場所」に成り果ててしまったのですから。"
63050-133 = "何の断罪も、裁きもないまま、すべてを葬ってしまおうだなんて、許されません。"
63050-134 = "それは、アリウスに生きたもの達への冒涜に他ならない！"
63050-135 = "そういうつもりじゃないんだけどな……。"
63050-136 = "もう自分自身に飲み込まれちゃってるんだね。#nこれじゃあ、どんな言葉も届かない。"
63050-137 = "でも大丈夫。私たちも、そうだったから。#nそして、こういう時どうすればいいか……アリウスは知ってる。"
63050-138 = "……？"
63050-139 = "さあ。"
63050-140 = "アリウス式で、お話しよっか。"
63050-143 = "アツコ？大丈夫か？#n祈るような仕草をしていたが……。"
63050-144 = "うん。ちょっと……[ruby=・]お[/ruby][ruby=・]話[/ruby]してただけ。"
63050-146 = "話……？"
63050-147 = "そ、それって……そういうこと、ですか……？"
63050-148 = "うん、そういうこと。"
63050-149 = "それじゃあ、先生。"
63050-150 = "[s] \"うん。\""
63050-151 = "夢に囚われたままの先輩を、起こしてあげよう。"
63050-152 = "アリウスらしいやり方で。"
63050-153 = "[s] \"何をすればいい？\""
63050-154 = "いつもと同じだよ。先生にしかできないこと。"
63050-155 = "マイアも、手伝ってくれる？"
63050-159 = "……もちろんです。"
63050-160 = "先輩のためなら、なんでもします！"
