[translation]
63060-1 = "第6話;低きに下られ"
63060-3 = "アリウススクワッドのリーダー。[ruby=じょうまえ]錠前[/ruby]サオリ……さんですね？お噂はかねがね。#n同じ1年生同士、今回の任務、頑張りましょう。"
63060-4 = "お前[ruby=かけはし]は梯ス[/ruby]バルだったな。案内は受けている。"
63060-5 = "これは、なんだ……？"
63060-6 = "……。"
63060-7 = "……ああ、あの時のことか。"
63060-8 = "錠前サオリと、初めて任務で顔を合わせた日。"
63060-9 = "[ruby=・]お[/ruby][ruby=・]互[/ruby][ruby=・]い[/ruby]、まだ1年生だった。"
63060-10 = "冷たくて、頑なな生徒。それが最初の印象。"
63060-11 = "任務の前に、作戦計画を擦り合わせたいのですが――"
63060-12 = "それなら終わらせてある。これが計画書だ。目を通しておいてくれ。"
63060-16 = "……はい？"
63060-17 = "どうかしたか？"
63060-18 = "あの、物事には順序があると思うのですが……。"
63060-19 = "お互いの力量の把握や、得意分野の確認、想定されるシナリオの共有、他にも――"
63060-20 = "自信がないなら、抜けてもらって構わない。この任務は、私ひとりでも十分だ。"
63060-21 = "……スクワッドでも、いつもこんな感じなんですか？"
63060-22 = "スクワッドの場合は、このやり取り自体が必要ない。#nそれぞれが自分の役割を果たすだけだからな。"
63060-23 = "まさかこれが、あなたなりの配慮だ、などとは言いませんよね？"
63060-24 = "その通りだが？"
63060-25 = "……そうですか。"
63060-33 = "説明してください！"
63060-34 = "説明も何も、任務の遂行に必要だっただけだ。"
63060-35 = "錠前サオリにとって、スクワッド以外の存在はあまり重要じゃないように見えた。"
63060-36 = "だから時々、他との協力が必要な任務では、いつもギクシャクしていた。"
63060-37 = "……思えば、あの性格を受け止められたのは、私くらいだった。"
63060-38 = "私、射線上にいましたよね！？#nなのに残存火力を全部ぶち込むなんて、どういうつもりですか！？"
63060-39 = "もう[ruby=・]私[/ruby][ruby=・]た[/ruby][ruby=・]ち[/ruby]2年生ですよ！？#nもう少し周りを見て行動しませんか！？"
63060-40 = "任務を最も早く達成できる方法を選んだだけだ。"
63060-41 = "任務の美徳は、力、勝利、速やかな完遂にある。失敗は罪だ。"
63060-42 = "……それ以外はどうなろうと関係ないと？"
63060-46 = "ようやく話が通じるようになったな。"
63060-47 = "そういう意味じゃないです！！"
63060-49 = "聞きましたよ。進級……できなかったらしいですね。"
63060-50 = "ああ、そうなったようだな。"
63060-51 = "今にして思えば、あれはマダムの意志だったのだろう。"
63060-52 = "マダムにとってはスクワッド……#nいや[ruby=はかり]、秤ア[/ruby]ツコ以外の全ては、道具も同然だった。"
63060-53 = "だからサオリを、いいように使おうとしていたのかもしれない。"
63060-54 = "……なぜだか、それがものすごく、我慢ならなかった。"
63060-55 = "アリウスで苦しんでいた、すべての子たちと同じように。"
63060-56 = "何とも思わないんですか？3年生になれないんですよ？"
63060-57 = "特には、何も。3年生になれなかっただけのことだ。"
63060-58 = "スクワッドのリーダーをもう1年続けられるわけだから、悪い話でもない。"
63060-59 = "……結局、スクワッドなんですね。"
63060-60 = "問題でもあるのか？"
63060-61 = "いえ、ありません。#nそれでは、これから私は先輩ですね。あなたはあなたで頑張ってください。"
63060-62 = "そのことだが。"
63060-63 = "……なんです？"
63060-64 = "どうも、「後輩」たちはお前を頼りにしているようだ。"
63060-65 = "……そうですか。それはどうも。"
63060-66 = "ああ。私には難しい役回りらしい。"
63060-67 = "だが、教官の役割は別だ。"
63060-68 = "……それはつまり、生徒のメンタルケアをしろと？#nあなたの訓練、メンタルを壊す生徒が多いんですよ。"
63060-69 = "さすが、察しがいい。いつも感謝している。"
63060-70 = "最初から壊すようなことしないでください！！！"
63060-72 = "でも……そうか。"
63060-73 = "どんな状況だって、錠前サオリは決して変わらなかった。"
63060-74 = "だからこそ、彼女が変わるなんて、ありえないと思っていた。"
63060-95 = "[ns] \"目が覚めた？\""
63060-97 = "ここは……どこですか？"
63060-98 = "[s] \"君がポルタパシスって呼んでた場所だよ。\""
63060-99 = "場所は変わらず、ですか。"
63060-100 = "……。"
63060-101 = "私はどのくらい気を失ってましたか？"
63060-102 = "[s] \"10秒くらいかな。\""
63060-103 = "そうですか。"
63060-104 = "全部……終わったんですか？"
63060-105 = "[s] \"それは、私も知りたいかな……。\""
63060-106 = "そうですか。"
63060-107 = "そう、ですよね……。"
63060-108 = "……。"
63060-113 = "…………。"
63060-114 = "………………。"
63060-115 = "……………………終わり、ですね。"
63060-116 = "ええ。全部……終わりました。"
63060-117 = "私は……。"
63060-118 = "結局、何もできなかった……。"
63060-119 = "自分のわがままで、みんなを……。"
63060-120 = "こんなことまで、しでかして……。"
63060-121 = "……うっ。"
63060-122 = "（スバルのすすり泣く声が聞こえてきた）"
63060-123 = "（少し辺りを見回してから、スバルの隣に腰を下ろした）"
63060-129 = "（スバルが落ち着くまで、待つことにした）"
63060-132 = "先生。……なぜ、何も言わないんですか？"
63060-133 = "……え？何を言えばいいのか、分からない……？"
63060-134 = "それ、私が言いたい台詞なんですけど……。"
63060-135 = "[s] \"大変だったよね。\""
63060-136 = "……。"
63060-137 = "私は、何がしたかったんでしょうか。"
63060-138 = "[s] \"アリウスを、懸命に守ろうとしてたよ。\""
63060-139 = "それが、この有様です。"
63060-140 = "……。"
63060-141 = "すべてが終わって。全部、無意味でした。"
63060-142 = "遮二無二やって、結果はこの通り。"
63060-143 = "傷ついた子のために、居場所がなかった子のために。#nそして……きっと、自分自身のために。"
63060-144 = "昔のように、流されるままの人生は嫌だったから……。"
63060-145 = "でも……。"
63060-146 = "こんな結末なら、何もしないほうがよかった……。"
63060-147 = "[s1] \"そんなことない。\"\n[s2] \"やってみたことに、意味があるんだよ。\""
63060-150 = "……こんな結果でも？"
63060-151 = "動機だって、純粋じゃなかった。"
63060-152 = "他の子たちの前で、虚勢を張っていただけ。"
63060-153 = "サオリの言う通りだったんです。"
63060-154 = "アリウスのやり方だなんて偉そうに言って、でもその先には……何もなかった。"
63060-155 = "[s3] \"でも、「そうだった」ってことは分かったでしょ？\"\n[s4] \"それに、生徒なんだから。「過程」だって評価されるべきだよ。\""
63060-158 = "結果だけで評価されるつらさは、大人になってからで十分……ですか？"
63060-159 = "……。"
63060-160 = "生徒であることを言い訳にしたくはないんですけど……。"
63060-164 = "はい……？#n立派な心がけだから、これからも持ち続けてほしい……？"
63060-165 = "……。"
63060-166 = "でも、そうは言っても。"
63060-167 = "底辺の人生、何が変わるっていうんですか。"
63060-168 = "どうせ私たちは、こうして生きて、こうして終わるだけなのに。"
63060-169 = "ゴミをいくら磨いたって、宝石にはなりませんよ。"
63060-170 = "……。"
63060-171 = "叶わない夢なんて見させないでください。#nそれが、一番残酷です。"
63060-172 = "頑張れば報われるなんて、一番無責任な言葉ですよね。"
63060-173 = "[s5] \"たしかに、努力しても変わらないことはある。\"\n[s6] \"失敗するかもしれない。\"\n[s7] \"今よりも悪くなるかもしれない。\""
63060-179 = "[ns8] \"でも、考えてみて？\"\n[ns9] \"今が底辺なら、上がるしかないよね？\""
63060-182 = "……それ、励ましてるつもりじゃないですよね？"
63060-184 = "だが、間違ってもいないだろう？"
63060-188 = "サオリ……？"
63060-193 = "……酷いものだった。"
63060-194 = "私たちは、本当に底辺の人生だったからな。"
63060-195 = "これ以上、落ちる場所も、逃げる場所もないくらいに。"
63060-196 = "なら、どう転ぼうと、やるしかない。"
63060-197 = "最悪な毎日だったね。ほんとに。"
63060-198 = "え、えへへ……。底辺の……さらに底辺があったとしても……。"
63060-199 = "そ、そのときは、地下室を覗いたってことで……いいんじゃないでしょうか……？"
63060-200 = "スクワッド……揃いも揃ってバカになったんですか？"
63060-201 = "処世術というらしい。"
63060-202 = "……そうでもなきゃ、やってられないよ。"
63060-203 = "け、結局、理由なんて……なんでもいいんですよ……えへへ……。"
63060-204 = "そういうこと。だから、みんなで行こう。"
63060-205 = "みんなと一緒なら、力が湧くから。#n……なんて、おとぎ話みたいな理由じゃなくて。"
63060-206 = "[ruby=私たち]アリウス[/ruby]は、みんな一緒じゃなきゃ、何もできないんだから。"
63060-207 = "そうでしょ？"
63060-216 = "先輩、そろそろ起き上がりませんか？"
63060-217 = "地面に寝転がってたら、服が泥だらけになっちゃいますよ？"
63060-222 = "……。"
63060-227 = "すでに汚れていると思いますけど。"
63060-228 = "それでも、これ以上は汚さない方がいいと思うんです。"
63060-229 = "……。"
63060-230 = "ええ。その通りですね。"
63060-248 = "団長！？"
63060-249 = "うわああぁぁぁぁん！！団長ーーーー！！"
63060-250 = "セリナ？ハナエ？#nここは……そうですか。救護騎士団の病室なんですね。"
63060-251 = "……。"
63060-252 = "試験まで……あと何日残っていますか！？"
63060-253 = "えっ！？そ、それも大事ですけど、今は療養の方が……。"
63060-254 = "試験が最重要です！！！"
63060-255 = "他の部に後れを取るなど、絶対に許されません！"
63060-256 = "……。"
63060-257 = "はいっ！団長！もちろんです！"
63060-258 = "……。"
63060-259 = "そうですね。まだ時間はありますから、落ち着いて準備しましょう。"
63060-260 = "みなさん、大丈夫ですよね？"
63060-262 = "はい！"
63060-264 = "次回;試み"
