[translation]
63070-1 = "第7話;試み"
63070-2 = "……。"
63070-3 = "慣れませんね……。"
63070-7 = "こんにちは、スバルさん！午後の検診に来ました。"
63070-11 = "ごめんなさい、午前中は授業があってどうしても……。"
63070-12 = "授業、ですか。"
63070-13 = "それが、[ruby=・]普[/ruby][ruby=・]通[/ruby]なんでしょうね。"
63070-14 = "……。"
63070-18 = "救護騎士団の病室は、ご不便ないですか？"
63070-19 = "……ええ。こんなに整った設備は見たこともありません。"
63070-20 = "おかげで、皆さんの回復も早いようです。"
63070-21 = "体がウズウズしてきたな〜"
63070-22 = "もう退院していいんじゃない……？"
63070-23 = "ダメですよ！治りかけが危ないんですから！"
63070-24 = "団長の許可が出るまでは我慢です！"
63070-25 = "ああやって言ってくれますし。"
63070-26 = "……。"
63070-30 = "あの、スバルさん？"
63070-31 = "はい？"
63070-32 = "私たちのこと……憎んでいたり、しませんか？"
63070-33 = "急にどうしたんですか？#nこうして治療をしていただいて、感謝こそすれ……。"
63070-34 = "……。"
63070-35 = "そういうこと、ですか。"
63070-36 = "はい……。"
63070-38 = "（あの日）"
63070-39 = "（天使のラッパが止まった、あの日）"
63070-40 = "（多くの生徒が、アリウス分校を訪れた）"
63070-41 = "（ゲヘナの救急医学部、トリニティの救護騎士団。その他にもたくさん）"
63070-64 = "（私たちは、救護騎士団の本館に搬送された）"
63070-65 = "（今に至るまで、ここで治療を受けながら回復を待っている）"
63070-67 = "……トリニティやゲヘナの助けを受けたという事実に、まだ戸惑っている生徒もいます。"
63070-68 = "助けてもらっておいて何を。という話ではあるのですが……。"
63070-69 = "もう少しだけ、気持ちを整理する時間をいただけるとありがたいです。#nすみません。"
63070-73 = "いえ！むしろ私たちの方こそ……。"
63070-74 = "はい……。"
63070-75 = "それはそれとして。"
63070-76 = "私たちを看てくださったことについては、感謝しています。"
63070-80 = "いえいえ！とんでもないです！"
63070-82 = "容体の方は？"
63070-83 = "私は平気です。ですがミネさんこそ……。"
63070-84 = "ご心配なく。非力ではありますが、これでも救護騎士団の団長ですので。"
63070-85 = "……あの日、ミネさんに何があったのですか？"
63070-86 = "はい？"
63070-87 = "ああ、私が倒れた日のことですね。"
63070-88 = "……。"
63070-89 = "私はただ、皆さんを守っただけです。"
63070-90 = "こうして元気にお話しできて、良かった。"
63070-91 = "スバルさんは……どうお考えですか……？#nこれまでと、これからのアリウスのことを……。"
63070-92 = "心に何の感情も湧かないかと言えば、嘘になります。"
63070-93 = "……。"
63070-94 = "ですが……この気持ちを抱えたままでも、生きていこうと思います。"
63070-95 = "この感情が膨れ上がるかもしれないし、少しずつ沈んでいくかもしれない。#nあるいは燃え尽きて、灰だけが残るかもしれない。"
63070-96 = "……それでも、生きていかなければならないのですから。"
63070-97 = "……そうですか。その強い覚悟、私も学ばせていただきます。"
63070-98 = "ええ、学び――"
63070-103 = "ここからは試験勉強の時間です！！！"
63070-104 = "はい！？"
63070-105 = "気を引き締めてください！試験まで、残された時間はわずかです！"
63070-106 = "心身が落ち着いたのなら、この機会に試験勉強に集中するべきです。#nそれこそが、生徒として正しい在り方ではありませんか！"
63070-107 = "私たち救護騎士団も、それは変わりません。"
63070-108 = "救護と学業の両立！救護騎士団の在り方を示すのです！"
63070-109 = "そうですよね、皆さん！"
63070-110 = "はい、団長！"
63070-111 = "ふふっ、良い返事です。"
63070-112 = "では、スバルさん。そしてアリウスの皆さんも。"
63070-113 = "試験、頑張ってくださいね。"
63070-117 = "良い話だったはずが……なぜこんな結論に……。"
63070-118 = "勉強かぁ……。"
63070-119 = "やっぱりやりたくないなぁ……。"
63070-120 = "……正直、私もです。"
63070-121 = "私は頑張りたいです！"
63070-122 = "やる気があるのは良いことですね……。#n今回は、私がマイアさんから学ぶ番かもしれません……。"
63070-128 = "おや？アレは……？"
63070-137 = "はい、ここま[ruby=アリウス式近接戦闘射撃術]で。CQBの基[/ruby]礎はこんなところです。"
63070-138 = "近接戦闘に持ち込まれないのが一番ですが、現場では何が起きるか分かりませんから。"
63070-139 = "す、すごい……。"
63070-140 = "かっこいい……！"
63070-144 = "えぇ……？こんなに拍手をもらえるなんて……。"
63070-145 = "アリウスじゃ、覚えて当然だったのに……。"
63070-146 = "あ、あのっ！その……近接？戦闘射撃術？私たちにも教えてもらえませんか？"
63070-147 = "えっ？でも皆さんは別に……。"
63070-148 = "おっしゃったではありませんか。何があるか分かりませんから！"
63070-150 = "私たちにだって、護身術は必須の時代だと思います！"
63070-152 = "そう！淑女たるもの――"
63070-153 = "自分の身は自分で守って、無礼な相手には礼儀を教えて差し上げませんと！"
63070-154 = "はい！その通りです！"
63070-158 = "トリニティ、大丈夫なのかな……。"
63070-159 = "もしかして、とんでもないものを目覚めさせちゃった……？"
63070-160 = "そうです！CQB研究部を創設いたしましょう！"
63070-161 = "いいですね！では、部長と副部長は……。"
63070-162 = "もちろん、専門家の方々にやってもらうべきですよね！"
63070-166 = "異議無しです！よろしくお願いします！"
63070-171 = "私たちですか！？でもそんな大役、とても……。"
63070-172 = "ひ、ひゃああ……。"
63070-173 = "大丈夫ですよ！慣れないことがあったら、何でもお手伝いしますから！"
63070-174 = "では皆さん！もう一度拍手をお願いします！"
63070-178 = "よ、よろしくお願いします……。"
63070-179 = "どうしてこんなことに……。"
63070-181 = "あの……先輩？"
63070-182 = "はい？どうかしましたか？"
63070-183 = "……。"
63070-184 = "私たちにも、できるでしょうか……？"
63070-185 = "今までとは、色んなことが違うかもしれませんが……。"
63070-190 = "新しい巣を、自分たちで作れると思いますか？"
63070-191 = "……。"
63070-192 = "やってみましょう。"
63070-194 = "私は、何がしたかったんでしょうか。"
63070-195 = "アリウスを、懸命に守ろうとしてたよ。"
63070-197 = "こんな結末なら、何もしないほうがよかった……。"
63070-198 = "そんなことない。"
63070-199 = "やってみたことに、意味があるんだよ。"
63070-201 = "たしかに、努力しても変わらないことはある。"
63070-202 = "失敗するかもしれない。今よりも悪くなるかもしれない。"
63070-203 = "でも、考えてみて？"
63070-204 = "今が底辺なら、上がるしかないよね？"
63070-206 = "結果が、どうであっても。"
63070-208 = "次回;ティータイム"
