[translation]
63080-1 = "第8話;ティータイム"
63080-103 = "先生……？"
63080-104 = "どうして……今、そんなことを……？"
63080-105 = "はい？ずっと、言えてなかったから……ですか。"
63080-106 = "せ、先生！そんなに深く頭を下げなくても……！"
63080-111 = "……あれ？"
63080-116 = "す、すみません……私……。"
63080-117 = "[s5] \"我慢しなくていいんだよ。\"\n[s6] \"悪いのは、私なんだから。\""
63080-123 = "[ns7] \"私も早く、立派な大人にならないと。\"\n[ns8] \"未熟な先生で、本当にごめんね。\""
63080-126 = "先、生……。"
63080-127 = "先生……。"
63080-128 = "……。"
63080-129 = "申し訳、ありません。"
63080-130 = "少しの間だけ……後ろを向いていて……いただけますか……？"
63080-133 = "（ナギサの頼み通り、後ろを向いた）"
63080-134 = "（そのまましばらく立っていると……）"
63080-139 = "（小さな重みが、「トン」と背中に預けられた）"
63080-14 = "何か、気にかかることでも……？"
63080-143 = "……辛かったです。"
63080-144 = "[s] \"……ごめんね。\""
63080-145 = "今まで、ずっと、ずっと……。"
63080-146 = "[s] \"うん……。\""
63080-147 = "何度も考えました。"
63080-148 = "もちろん、私のしたことは、私の責任です。"
63080-149 = "ですが……。"
63080-15 = "準備が手早くてびっくりした、と？"
63080-150 = "どうして私にだけ、あんなにも厳しかったのか、と……。"
63080-151 = "たしかに、ティーパーティーのホストとは、そういう立場です。"
63080-152 = "補習授業部の件は、もっと酷い誹りを受けても仕方ないと思います……。"
63080-153 = "それでも……。"
63080-158 = "うぅっ……。"
63080-159 = "（まるで今までの苦しみを吐き出すように……ナギサの手は、何度も私の背中を軽く叩いた）"
63080-16 = "何を仰るのかと思えば。#nすべてのものは、あるべき形で役目を果たしてこそ、光輝くものですから。"
63080-160 = "（か細いその手つきが……）"
63080-161 = "（一つひとつ、私の胸に染み入ってきた……）"
63080-164 = "[ns] \"……落ち着いた？\""
63080-165 = "はい。"
63080-166 = "……お見苦しいところをお見せしてしまって、申し訳ありません。"
63080-167 = "[s] \"改めて、本当に……ごめん。\""
63080-168 = "先生も、あまり気になさらないでくださいね。#nあんまりそう言われると、私も……。"
63080-169 = "……。"
63080-17 = "はい？試験ですか？#n当然、ティーパーティーのメンバーも受けますが……。"
63080-170 = "では、こうしましょう。"
63080-171 = "同じ轍を踏まぬよう、お互い、これからはもう少し気をつける。"
63080-172 = "そしてこの話題は、よほどのことがない限り出さない。"
63080-173 = "その約束を込めて……紅茶で乾杯いたしましょう。"
63080-174 = "[s] \"いただくよ。\""
63080-175 = "では――"
63080-176 = "[s] \"……乾杯。\""
63080-177 = "乾杯。"
63080-18 = "私たちこそ、成績が悪ければ、その資格を疑われる立場なのですよ？"
63080-182 = "[ns] \"いい香りだね……。\""
63080-185 = "当然です。そうでなければ困ります。"
63080-189 = "……ああ、そういえば。#n何か、私に話したいことがあるとおっしゃっていませんでしたか……？"
63080-19 = "ですがお二人とも優秀ですから。特に心配はしていません。"
63080-194 = "（スバルにも話した――いや、思考を覗かれた、エデン条約事件直後の出来事）"
63080-195 = "（パテル派とサンクトゥス派の、いわゆる「総意」についての話をした）"
63080-198 = "……。"
63080-199 = "…………。"
63080-2 = "まずは今回の件について、改めて心より感謝申し上げます。"
63080-20 = "……え、ミカさんの成績ですか？"
63080-200 = "………………。"
63080-201 = "[s] \"ナギサ……？\""
63080-202 = "ふっ。"
63080-203 = "[s] \"ふっ……？\""
63080-204 = "……ふふっ。"
63080-205 = "ふふふふふ……。"
63080-206 = "なるほど、そういうことでしたか。"
63080-207 = "そのお二人が誰なのか、おおよその察しはつきます。#n私のもとにも、関連報告は上がっておりましたので。"
63080-208 = "本当に……。"
63080-209 = "心から、感謝いたします。"
63080-210 = "とても、貴重な情報でした。ふふふふふ……。"
63080-211 = "[s] \"ひぃっ……。\""
63080-212 = "うまくやっておくと自分で言っておきながら、この程度の仕事ぶり。"
63080-213 = "だというのに、報告書の内容だけは[ruby=・   ・   ・]整えて[/ruby]提出していた、と。"
63080-214 = "[s] \"ナギサ……？\""
63080-215 = "ご安心ください。"
63080-216 = "この件は、[ruby=・]円[/ruby][ruby=・]満[/ruby][ruby=・]に[/ruby]処理しておきます。"
63080-217 = "ええ、先生が心配せずとも済むよう、[ruby=・]最[/ruby][ruby=・]善[/ruby][ruby=・]を[/ruby][ruby=・]尽[/ruby][ruby=・]く[/ruby][ruby=・]し[/ruby]ましょう。"
63080-218 = "政治とは、大義名分とタイミングですから。"
63080-219 = "例えば、こうした欺瞞行為を許してしまったのも……各分派の[ruby=・]代[/ruby][ruby=・]表[/ruby]の権威が回復していない証左だと見ることもできます。"
63080-220 = "特に、ミカさんの立場や待遇が悩ましいですね。"
63080-221 = "元通りは難しくとも、状況の[ruby=・]改[/ruby][ruby=・]善[/ruby]は提案するべきでしょうか……。"
63080-225 = "（そう語るナギサの笑顔は……）"
63080-226 = "（笑っているのに、笑っていなかった）"
63080-227 = "……さて、重たくて頭が痛くなるような話題は、ここまでにいたしましょう。"
63080-228 = "残りの時間は……ティータイムにお付き合いいただけませんか？"
63080-229 = "[s] \"私は構わないけど……改まってどうしたの？\""
63080-230 = "それは……。"
63080-231 = "やっと一段落ついたわけですから。"
63080-232 = "私と先生の……これまでの関係性とか……。"
63080-233 = "その距離感を生み出した様々な要因だとか。"
63080-234 = "そういうものに対する――"
63080-235 = "[ruby=・]埋[/ruby][ruby=・]め[/ruby][ruby=・]合[/ruby][ruby=・]わ[/ruby][ruby=・]せ[/ruby]があっても良いとは思いませんか？"
63080-236 = "[s] \"……！\""
63080-24 = "……。"
63080-241 = "[ns] \"その話はしないって約束したよね！？\""
63080-242 = "あら。"
63080-243 = "私は具体的に何かを申し上げたつもりはございませんが……。"
63080-244 = "[s] \"言ったようなもんじゃなかったかなぁ？\""
63080-245 = "ふふっ。それはどうでしょうね……？"
63080-246 = "それでは、先生。"
63080-247 = "あ～ん？"
63080-248 = "[s] \"なっ！？\""
63080-249 = "そんな風に拒絶されると……私のこと、お嫌いですか……？"
63080-25 = "先生。"
63080-250 = "[s] \"そういう言い方されたら……。\""
63080-251 = "ふふっ。"
63080-252 = "これも、ある意味では「政治」かもしれませんね？"
63080-254 = "（ナギサの掌の上で転がされていると認めつつ……）"
63080-255 = "（腹を決めようとした、その時――）"
63080-26 = "ミカさんは、なんと言いますか……。"
63080-260 = "やっほー☆#nナギちゃん、遊びに来たよ！"
63080-266 = "ミカさん！？#nそれにセイアさんまで……！？"
63080-27 = "「地頭は良いのに、努力をしない」の典型例でして。"
63080-270 = "あれっ、先生！？#nわわっ、知ってれば、もっと色々――！"
63080-271 = "ほう？愉快なことになりそうな予感に従って、戯れに訪れてみれば……。"
63080-272 = "まさか、これほどのものに出くわすとは。"
63080-274 = "せ、先生？どうしましょう！？#nお二人……特にミカさんには聞かれたくない話題が……！"
63080-275 = "[s] （落ち着いて。その話自体はもう終わってたから！）"
63080-276 = "！！！"
63080-277 = "……そうでしたね。"
63080-281 = "……こほん。お二人とも、ようこそ。#n次からは、せめてノックくらいしてください。#n先生という客人の前なのですよ？"
63080-282 = "はーい……というか、それならちゃんと場を用意すればいいのに。"
63080-283 = "先に教えてほしかったなぁ……。"
63080-287 = "（ナギサがウィンクして合図を送ってきた）"
63080-288 = "[ns9] \"そうだね。私からも伝えておけばよかったね。\"\n[ns10] \"ミカをびっくりさせようと思ってたんだ。\""
63080-293 = "ええっ！？ほんとに！？#nそれ、すっごく嬉しいんだけど……。"
63080-294 = "えへへ、先生ってば、もー。"
63080-299 = "……。"
63080-3 = "[s] \"ナギサも本当にお疲れ様。\""
63080-30 = "ミカさんは頭が悪いどころか、むしろその逆です。"
63080-300 = "先生は本当に……罪深いね。"
63080-301 = "[s11] \"そ、そこまで言わなくても……。\"\n[s12] \"ええっ？なんでそうなるの！？\""
63080-302 = "君は少々、自覚が足りないからな。"
63080-303 = "それは、自分の胸に手を当てて考えてみたらどうだい？"
63080-304 = "はぁ……こうなった以上、久しぶりに……皆さんそろっての「ティータイム」にいたしましょう。"
63080-305 = "せっかく先生がいらしていることですし。"
63080-306 = "うん！賛成！"
63080-307 = "あれ？もしかして……4人一緒のティータイムって初めてかも？"
63080-308 = "いや、違ったっけ？"
63080-309 = "どちらだって構わないさ。"
63080-31 = "ただ……それを進んで使おうとはしないだけで。"
63080-310 = "肝要たるは、こうして一堂に会している。その事実だけだ。"
63080-311 = "もっとも、ミカには、おそらく世のほとんどの出来事がいつだって新鮮に映るのだろうけれど。"
63080-312 = "せ～い～あ～ちゃ～ん？#nそれ、私が忘れっぽいって言いたいのかなぁ？"
63080-313 = "君がそう思うのなら、そうなのだろうね。"
63080-314 = "あんまりひねくれたことばっかり言ってたら、そのうちみんなに距離置かれちゃうかもよ？"
63080-315 = "実際にその状況に陥ってから、方策を検討するとしよう。"
63080-316 = "私自身、未来を読むことは叶わなくなった身だからね。"
63080-317 = "ほんっと、屁理屈ばっかり！"
63080-318 = "……ふふっ。"
63080-32 = "私の推測ですが……細かいことを考えるのが面倒なのでしょうね……。"
63080-320 = "はぁ……お二人とも。先生もご一緒だということ、お忘れじゃないですか？"
63080-332 = "[ns13] \"仲良くやってるみたいで嬉しいよ。\"\n[ns14] \"喧嘩するほど仲が良いって言うもんね。\""
63080-335 = "そう言っていただけると……本当に、申し訳ありません……。"
63080-337 = "次回;試験勉強"
63080-35 = "まぁ、ですので。試験は大丈夫です……いつもそうでしたから……。#nはあ……。"
63080-36 = "そもそも成績が悪かったら、ティーパーティーに選ばれるはずがないじゃないですか。"
63080-37 = "[s] \"ナギサも苦労してるんだね……。\""
63080-38 = "そのお言葉だけでも救われます……。"
63080-39 = "さて、前置きはこのくらいにいたしましょう。"
63080-4 = "とんでもありません。私は……。"
63080-40 = "今回の顛末ですが……トリニティとアリウスの問題は、両校の歴史そのものと言っても過言ではありません。"
63080-41 = "同じ事象を基にしながら、それぞれがまったく異なる解釈で、歴史を受け継いできました。"
63080-42 = "歴史とは、起きた事実の積み重ねですが、それを記録するのは人ですから。"
63080-43 = "……。"
63080-44 = "問題は、異なる解釈が存在していること。"
63080-45 = "だからこそ、お互いの歴史を一つひとつ照合していこうと思っています。#n最終的には、誰もが閲覧できる状態にまで取りまとめようかと。"
63080-46 = "[s] \"上手くいくかな……。\""
63080-47 = "もちろん、両者は大きく食い違っているでしょうし……すり合わせる過程で、摩擦や衝突も一時的には増えるはずです。"
63080-48 = "ですが過去を乗り越えるとは、それを曇りなく見つめようとする、勇気ある眼差しのことですから。"
63080-49 = "それに、専門家の視点も借りるつもりです。"
63080-5 = "……いえ、今は先生のお言葉をありがたく受け取っておきますね。"
63080-50 = "記録の照合や研究であれば……喜んで引き受けてくださる方もいますので。"
63080-55 = "きっとこれから、色々なことが変わっていきます。#nですが……それを乗り越えていけると、私は信じています。"
63080-56 = "私の知るトリニティは、それほど脆くはありませんから。"
63080-57 = "その過程で、内部での政治的ないざこざは起きるかもしれませんが……。"
63080-58 = "……。"
63080-59 = "ティーパーティーのホストにとっては、得意分野とも言えますし。"
63080-6 = "アリウスの生徒たちが勉強して、試験を受ける場所については……#nどうかご心配なく。"
63080-60 = "[s] \"……。\""
63080-61 = "政治とは、そういうものです。"
63080-62 = "誰かから何かを得るために、自分が持っている何かを差し出す。"
63080-63 = "そうして妥協と交換を繰り返しながら――"
63080-64 = "自分が[ruby=・]本[/ruby][ruby=・]当[/ruby][ruby=・]に[/ruby][ruby=・]守[/ruby][ruby=・]り[/ruby][ruby=・]た[/ruby][ruby=・]い[/ruby][ruby=・]も[/ruby][ruby=・]の[/ruby]だけは、最後まで手放さない。"
63080-65 = "ですが往々にして、初心を見失いがちです。"
63080-66 = "自分が何者で、何を為そうとしていたのかすら、忘れてしまいます。"
63080-67 = "[s] \"ナギサが守りたいものは、何？\""
63080-7 = "トリニティに、今は使われていない旧校舎がありますので。"
63080-71 = "私は……。"
63080-72 = "トリニティが、最高の学園であってほしいと思っています。"
63080-73 = "生徒たちが、自分の通う学園を誇らしいと思える……そんな学園であってほしい。"
63080-74 = "そしていつか、トリニティでの学園生活を振り返ったとき――"
63080-75 = "かけがえのない大切な時間だったと、笑って思い出せるように。"
63080-8 = "そちらを、無償でお貸しできるよう手配させていただきます。"
63080-84 = "ここで得た経験が、大切な宝物になってくれたらいいなと願っています。"
63080-85 = "まだまだ道のりは遠いですけどね。"
63080-86 = "斯くいう私自身……少しくらいは、宝物が欲しいのですが……。"
63080-87 = "そのためには、やはり……。"
63080-88 = "自分たちを取り巻くすべてを、より冷静な目で見つめることが必要なのだと思います。"
63080-89 = "これは、先生が教えてくれたことですけどね。"
63080-9 = "[s1] \"使われていない旧校舎……。\"\n[s2] \"無償で貸す……。\""
63080-90 = "[s] \"……ナギサ。\""
63080-91 = "はい？"
63080-92 = "[s] \"あの時は、ごめん。\""
63080-93 = "……え？"
63080-94 = "[s] \"ナギサを、なかなか信じようとしなかったこと。\""
63080-97 = "[ns] \"そして……ナギサに、酷いことを言ってしまったこと。\""
63080-99 = "[ns3] \"私は……。\"\n[ns4] \"あんな言い方をするべきじゃなかった。\""
