[translation]
63090-1 = "第9話;試験勉強"
63090-4 = "ちわーっす。うちでの暮らしはどうっすか？"
63090-9 = "ああ、それなりにやっている。#nお前は……コノカ副局長、だったか？"
63090-10 = "かたいかたい。コノカでいいっすよ。"
63090-11 = "サオリさんの方が一つ年上っしょ？学年は同じだけど。"
63090-12 = "そうか……分かった。#n……だが、コノカ。"
63090-13 = "今さら尋問室に呼ぶなんて……何かあったのか？#nもう私の刑は確定しているだろう？"
63090-14 = "言った通り、どう過ごしてるかなって思って。#nヴァルキューレじゃ、それなりに有名人っすから。"
63090-15 = "……あまり良いことではないように思うが。"
63090-16 = "キヴォトス中で有名よりかはマシじゃないっすかね。"
63090-17 = "まぁ、それだと今より苦労することも多そうだ。"
63090-18 = "さて、と。前置きはこんくらいにしておいて。それじゃ、こっからが本題。"
63090-19 = "アリウススクワッドについて、情報が更新されました。"
63090-20 = "余罪でも見つかったか？#nそれなら、私たちの刑期に関することでもあるのだろうが。"
63090-21 = "うーん、似たようなもんっすかね。"
63090-22 = "そうか。何であれ、受け入れる覚悟はできている。"
63090-23 = "普通は逆なんだけどなー。"
63090-24 = "……アリウス分校の生徒は、よく言う「普通」からは少しズレた奴が多いからな。"
63090-25 = "ああ、アリウス分校といえば。連邦生徒会で、今後の扱いが決まりそうって喜んでましたよ。あんまし関係ない話っすけど。"
63090-26 = "いや、聞かせてくれてよかった。母校の話なら、何でも構わないさ。"
63090-27 = "最悪のテロリストを養成した学園だと扱われたとしても、その事実を否定するつもりはない。"
63090-28 = "過去を受け入れなければ、前には進めないからな。"
63090-29 = "おー、良いこと言うー。"
63090-35 = "でも……後悔、してます？"
63090-36 = "あのテロのことか？"
63090-37 = "他に何があるんすか。"
63090-43 = "ふっ……。"
63090-47 = "どうかしたんすか？"
63090-48 = "ああ、いや、すまない。"
63090-49 = "前にも、誰かと同じ話をしたな、と思い出したんだ。"
63090-50 = "後悔しているかと聞いたな？答えは明白だ。"
63090-54 = "一日だって、後悔しなかった日はない。"
63090-57 = "あの頃はまだ未熟だった、って感じっすか。"
63090-58 = "あぁ。今の私なら、絶対にしない。"
63090-59 = "だが、昔の私も、私であることに違いはないからな。"
63090-60 = "……。"
63090-61 = "よし、やっぱり思った通り。"
63090-65 = "何がだ？"
63090-66 = "まぁまぁ、そう焦らずに。"
63090-67 = "形式的な決まり文句なわけですが――"
63090-71 = "おめでとうございます、サオリさん。そして他のスクワッドの皆さんも。"
63090-72 = "仮釈放っす。荷物をまとめといてください。"
63090-77 = "……？"
63090-78 = "どういうことだ。これは新手の冗談か？"
63090-79 = "まぁ、そういう反応になりますよね……。"
63090-80 = "じゃ、ちゃっちゃと説明しますよ。"
63090-81 = "あなたを含む、アリウススクワッド全員に仮釈放が決まりました。"
63090-82 = "だが、私たちはテロを起こして……。"
63090-83 = "罪状と刑期に変わりはないっすよ。"
63090-84 = "でも、爆発したり、建物が壊れるのなんて、よくあることじゃないっすか。"
63090-85 = "だから建築業はキヴォトスの花形業界な訳だし……。"
63090-86 = "あ、ああ……。"
63090-87 = "キヴォトスの犯罪で、一番重視されるものが何か、ご存知ですか？#nそれは、「殺意」とか「悪意」なんですよ。"
63090-88 = "初めて聞く話だ。だがそれなら、なおさら私たちは……。"
63090-89 = "そうっすね。あのテロにはたしかに殺意も悪意もあった。"
63090-90 = "ですが話を聞いてみれば、皆さん反省してるみたいですし。"
63090-91 = "……？"
63090-92 = "しかも皆さん、自首までしたんすよ？#n問題児が自首するとか、副局長やってきて初めて見たっす！"
63090-93 = "自分の罪を認めて、罰を望んだ生徒がいる……キヴォトスの未来も捨てたもんじゃないっすね！"
63090-94 = "あ、ありがとう……？"
63090-95 = "（本当に、これでいいのだろうか……）"
63090-96 = "何より――嘆願書が届いたんですよ。#nそれも、皆さんが「殺意」と「悪意」を向けたはずの相手から。"
63090-97 = "先生、トリニティ、そして――"
63090-102 = "――ゲヘナからも。"
63090-103 = "気になるでしょうから、一部、ご紹介しますよ。"
63090-105 = "嘆願書……ええ。書いたのは私よ。間違いないわ。"
63090-106 = "自分がケガしたのは、どうでもよかったの。#nでも、先生にまで被害が及んだことには、腹が立った。"
63090-107 = "それなのに、嘆願書を書いた理由？#nそうね……。"
63090-108 = "許してあげてほしい、って。先生が直々に頭を下げるのだもの。#nそんなことをされたら、私にはこうするしかないじゃない。"
63090-109 = "残るのは……マコトの美容室代くらいだけど……。"
63090-110 = "……。"
63090-111 = "気にしないでいいわ。その話は、本当にどうでもいいことだから。"
63090-114 = "……これで、いいのか？"
63090-115 = "いいみたいっすよ。"
63090-116 = "これだけの声が集まったら、うちとしても黙ってるわけにはいきませんし。"
63090-117 = "それにほら、ヴァルキューレって、更生と矯正を目的にした学園ですから。"
63090-118 = "……矯正局の維持費もバカにならないし。"
63090-119 = "まぁ、先生が責任を持つって言ったのが決め手っぽいすけど。#n先生を失望させないでくださいね。"
63090-120 = "ああ、肝に銘じよう。"
63090-121 = "あと、誤解されがちですけど、仮釈放って無罪じゃないですからね？#nこの期間に何かやらかしたら、次はありません。"
63090-122 = "誓おう。万が一の時には、私のヘイローを壊してくれて構わない。"
63090-123 = "ちょ、やめてくださいよそういう言い方！ホント、アリウス式は怖いっすよ！"
63090-124 = "す、すまない……。"
63090-125 = "……私たち、本当に……仮釈放なんだな……？"
63090-126 = "はい。"
63090-127 = "さて……こうなったからには、試験の準備をしたらどうです？#nそろそろでしょう？"
63090-131 = "試験……！そうだな！"
63090-146 = "よ、ようこそ！"
63090-147 = "……。"
63090-148 = "えっと、みなさん！"
63090-149 = "ちょっと設備は物足りなく感じるかもしれませんが……。"
63090-150 = "みんなで一緒に勉強して、模擬試験を乗り越えましょう！"
63090-155 = "わぁ……すごい教室……。"
63090-156 = "こういう場所なら、たしかに勉強する気になるかも……。"
63090-161 = "あ、あれ……？"
63090-162 = "あの反応になるのも理解できる。"
63090-163 = "アリウスの教室と比べれば、何だってそう思えるからな。"
63090-164 = "そ、そうなんですか。あはは……。"
63090-165 = "ありがとう、ヒフミ。それにみんなも。"
63090-166 = "この子たちの「補習」を、快く手伝ってくれて。"
63090-172 = "水臭いじゃないですか。私たちの仲なんですから。"
63090-174 = "でも……学園名と部活名を言わないのって、思ったより大変ですね……。#n気を抜いたら、つい言っちゃいそうです……。"
63090-175 = "[s] \"それは私も同じだよ……。\""
63090-179 = "……。"
63090-180 = "……。"
63090-181 = "お、お久しぶりです……アズサさん。"
63090-182 = "ああ。久しぶりだな、マイア。"
63090-183 = "こんなことを言うのはどうかと思うけど……。"
63090-184 = "あなたに再会できて嬉しい。"
63090-185 = "そ、その口調は相変わらずですね……。"
63090-186 = "元気……そうで、よかったです……。"
63090-187 = "……。"
63090-188 = "うん。"
63090-189 = "あなた達も、きっと元気に過ごせる。"
63090-190 = "そうなれるようにすればいいだけだからな。"
63090-196 = "私にできることがあれば、何でも言ってほしい。"
63090-200 = "じゃあ代わりに試験受けてくれますか！？"
63090-201 = "それは無理だ。"
63090-202 = "うわぁぁん……。"
63090-206 = "あなたは、コハルさん……でしたよね？#nたしかエリート、って……。"
63090-210 = "ふ、ふん！人を見る目あるじゃん！そうよ！私がせいぎ――"
63090-214 = "とにかく！エリートだから！何でも頼っていいわよ！"
63090-215 = "じゃあ……この問題……教えてほしいです。"
63090-216 = "え、えっと……？"
63090-220 = "（あれ？これ、分かるはずなんだけど……？）"
63090-221 = "（なんで思い出せないのよ！？ちゃんとメモも取ったのに！）"
63090-222 = "そ、そうね！これは、その……！"
63090-223 = "はい、はい！"
63090-224 = "う、うぅ……。"
63090-225 = "試験範囲じゃないから、まだ覚えなくていいわ！"
63090-227 = "えっ！？そうなんですか！？"
63090-228 = "それは違いますよ、コハルちゃん。#n試験範囲外だからといって、勉強しなくていいという考え方は甘すぎます。"
63090-229 = "コハルちゃんだって……試験範囲外なのに「大人の知識」を先行学習していますよね？"
63090-231 = "ぴゃっ！？"
63090-232 = "な、なに言ってるのよ！そんなの死刑だし！絶対誤解だからっ！"
63090-234 = "ふふっ。そうですか？"
63090-235 = "それより、その問題はたしかに試験範囲外ですが、試験範囲を理解するには知っておいた方がいい内容ですね。"
63090-236 = "では、ここはこう解いてみましょうか。"
63090-242 = "[ruby=うらわ]浦和[/ruby]ハナコ……やはり只者ではないな。"
63090-243 = "……あの人、色んな意味で予測不能だったからね。"
63090-244 = "ハナコさんって、知らないことあるんでしょうか……。"
63090-250 = "まさか。全部は知りませんよ。"
63090-251 = "うわぁぁぁん！？き、聞こえてたんですか！？ごめんなさあぁぁぁぁいっ！"
63090-252 = "大丈夫ですよ。[ruby=つちなが]槌永[/ruby]ヒヨリさん……でしたっけ？ヒヨリちゃんと呼ばせていただいても？"
63090-253 = "えっ？は、ははははいっ！こ、光栄……です……。"
63090-254 = "それで、あなたはたしか…[ruby=はかり]…秤ア[/ruby]ツコさん。#n……あら？"
63090-258 = "どうしたの？"
63090-259 = "……？"
63090-260 = "……。"
63090-261 = "……。"
63090-265 = "ふふっ。"
63090-266 = "ふふ。"
63090-267 = "面白い方に出会えた気がします。#nこれからは、よろしくお願いしますね、アツコ[ruby=・]ち[/ruby][ruby=・]ゃ[/ruby][ruby=・]ん[/ruby]？"
63090-268 = "こちらこそ。よろしくね、ハナコ[ruby=・]ち[/ruby][ruby=・]ゃ[/ruby][ruby=・]ん[/ruby]。"
63090-269 = "あらあら。"
63090-270 = "ふふふ。"
63090-272 = "……前から知り合いだったのか？"
63090-273 = "ううん、違うよ。ただ……なんとなく、話が通じそうな気がしただけ。"
63090-274 = "多分、ハナコちゃんもそう感じてたんじゃないかな？"
63090-275 = "……さっぱり分からないんだけど。"
63090-276 = "うん。今はそれでいいと思うよ。"
63090-277 = "やっぱりよく分かりませんが、はい……。"
63090-278 = "さて、それじゃあ勉強再開しようか。授業、お願いしてもいい？先生？"
63090-279 = "[s] \"任せて！\""
63090-294 = "ところで……この変な綿の塊みたいなものは何ですか？"
63090-298 = "良い質問ですね！これは――"
63090-303 = "成績が良かった方に差し上げる、モモフレンズグッズです！"
63090-305 = "またそれ……？"
63090-307 = "モモ……フレンズ……？"
63090-308 = "はい！最近流行っているモモフレンズです！#nみんなに……って訳ではないのですが、特定の層に変わった人気があるんですよ！"
63090-310 = "「みんなに人気」って言わなかっただけでも、大きな進歩ね……。"
63090-311 = "モモフレンズは最高だ。私はスカルマンをお勧めする。#nこの報酬なら、みんな間違いなく本気を出すはずだ。"
63090-312 = "それ……どういう理屈ですか？"
63090-313 = "でも、前の補習授業では、かなりの効果があったんですよ？"
63090-314 = "……本当ですか？#nまさか……何か不思議な現象が関わっているとか……？"
63090-316 = "え？いえ、そういうのじゃなくて……ただ可愛いから、それ欲しさにみんな頑張っているだけで……。"
63090-317 = "そうだな。これには本気を出す価値がある。"
63090-322 = "……。"
63090-323 = "（アズサさん、外の空気に触れたことで、#n趣味がちょっと変わってしまったのでは……）"
63090-326 = "つまり、みなさん！私たちも、もともと勉強が得意だったわけじゃないんです！"
63090-327 = "でも、勉強っていうのは一種の「システム」ですから、それをちゃんと繰り返し学習すれば――"
63090-328 = "一定のレベルまでは、必ず到達できるようになるんです！"
63090-329 = "何より、こんなに平凡で個性のない私だって、補習を乗り越えられたんですから！"
63090-333 = "……。"
63090-334 = "……。"
63090-335 = "あの、アズサさん……？"
63090-336 = "どうした、マイア？"
63090-337 = "ヒフミさんって、本当に平凡なんですか……？"
63090-338 = "……。"
63090-339 = "私の観察によれば、「平凡」には二種類あるらしい。"
63090-340 = "一つは自称の平凡。もう一つは他人から見た平凡。"
63090-341 = "ヒフミさんは……どっちなんですか？"
63090-342 = "……。"
63090-343 = "それは……ノーコメントだ。"
63090-344 = "それだけで、もう答えたようなものじゃないですか……。"
63090-348 = "頑張って覚えようとしてるのに！全然覚えられない！！"
63090-349 = "私、試験期間の真理にたどり着いた気がする……。"
63090-350 = "どんなの？"
63090-351 = "勉強以外のすべてが面白く見えてくる期間ってこと……。"
63090-356 = "おおおお！勉強しようって気持ちが燃え上がってきた！"
63090-357 = "本当に？"
63090-358 = "うん。燃え過ぎて、灰になっちゃった。"
63090-362 = "先生……病気になった気がするんですけど、休んでいいですか？"
63090-363 = "[s] \"どんな症状があるの？\""
63090-364 = "勉強すると壊れちゃうんです。"
63090-365 = "[s] \"それなら次は……治るまで勉強しよっか。\""
63090-369 = "全然優しくない……。"
63090-370 = "[s] \"これも、みんなにいい成績を取ってもらうためだよ。\""
63090-373 = "わっ！この問題すっごく綺麗！"
63090-374 = "え、そう？"
63090-375 = "うん！この問題を傷つけたくないから、解きたくないレベル！"
63090-376 = "勉強しすぎておかしくなっちゃったか……。"
63090-379 = "（こうして、みんなの努力と、もがきと、絶叫と――それらすべてをぐちゃぐちゃにかき混ぜながら……）"
63090-380 = "（アリウスの生徒たちは、初めての試験に向けて、毎日一歩ずつ前に進んでいった……）"
63090-383 = "次回;遺された未来のためのエクレシア"
