[translation]
63100-1 = "第10話;遺された未来のためのエクレシア"
63100-5 = "[log]総合試験当日[/log]"
63100-9 = "……どう？"
63100-10 = "うん。"
63100-11 = "分かんないけどさ。"
63100-12 = "すっごい自信あるんだよね。"
63100-13 = "まぁ、根拠は無いんだけど。"
63100-17 = "それってつまり、全然勉強してないってことじゃん……。"
63100-19 = "でもさ。"
63100-20 = "ん？"
63100-21 = "教科書って、勉強のための本でしょ？"
63100-22 = "そうだね。"
63100-23 = "ってことは、私たちの教科書は失敗作なんだよ。"
63100-24 = "だって、私を教えるのに失敗してるからさ。"
63100-25 = "わぁ、斬新な発想……。"
63100-26 = "とにかく、試験頑張ろうね……。"
63100-27 = "そっちもね……。"
63100-28 = "……みんながケアレスミスしますように。"
63100-29 = "お互いに頑張るんじゃなかったの……？"
63100-34 = "[ns] \"みんな！ちゃんと勉強してきたかな？\""
63100-35 = "あ、先生！"
63100-36 = "先生……。"
63100-37 = "どう考えても赤点取りそうな時って……どうしたらいいですか……？"
63100-38 = "[s1] \"心配しなくても大丈夫。\"\n[s2] \"やってみなきゃ分からないよ。\"\n[s3] \"だって、結果が出るまでは赤点じゃないからね。\""
63100-42 = "わあ……すっごい励まされる一言だ……。"
63100-43 = "[s] \"とにかく、みんな頑張ってね！\""
63100-44 = "はい……。"
63100-49 = "先生、おはよう。もしかして、見送りに来てくれたの？"
63100-50 = "心配しなくても、試験はちゃんと受けるよ。これまでの苦労がもったいないし。"
63100-55 = "ん？先生は応援しに来てくれたんだと思ったが……。"
63100-56 = "あ……。み、ミサキさんも、それは分かってて……#nあ、あえてそう言ったんじゃ……。"
63100-57 = "そうだったのか？すまない、気づけなくて……。"
63100-59 = "いや、そうじゃなくて……！"
63100-60 = "はあ……もういいよ。"
63100-61 = "それじゃあ、行ってきます。"
63100-62 = "が、頑張ってきますね……。"
63100-71 = "おはようございます、先生。"
63100-72 = "お、おはようございます……。#n……あれ？今日はお休み……なんですか？"
63100-73 = "[s4] \"今日はここで仕事があるんだ。\"\n[s5] \"みんなの応援っていう仕事がね。\""
63100-76 = "そ、そうなんですね……。"
63100-80 = "……先生、なんですか？私のことをじっと見て。"
63100-81 = "はい？試験を受けることに抵抗があるか、ですか……。"
63100-82 = "……正直、ないとは言えません。"
63100-83 = "でも……信じてみることにしました。"
63100-84 = "もう一度やってみようと声を上げた、[ruby=あの子たち]アリウス[/ruby]の声を。"
63100-85 = "……そして、先生を。"
63100-86 = "[s] \"……ありがとう。\""
63100-90 = "な、なんですか急に！？"
63100-91 = "[s] \"私を信じてくれて、ありがとう。\""
63100-92 = "そ、れは……。"
63100-93 = "え？先生だって、生徒に信じてもらえなきゃ、実は不安になってブレることもある……？"
63100-94 = "……。"
63100-95 = "それはちょっと……想定外の答えですね……。"
63100-97 = "それじゃ私も、先生の役に立ててますか！？"
63100-98 = "[s] \"もちろん。マイアも、ありがとう。\""
63100-105 = "（マイアの頭を撫でた）"
63100-106 = "えへへ……。なんか……嬉しいです……。ありがとうございます、先生。"
63100-111 = "……。"
63100-112 = "私も――"
63100-118 = "あ、先輩！もう時間みたいです！急ぎましょう！"
63100-119 = "えっ、あ、あぁ……。"
63100-120 = "はい、行きましょう……。"
63100-125 = "[ns] \"そろそろ……トリニティの方も、試験が始まってる頃かな……。\""
63100-126 = "（大人でよかったと思えることが一つあるとすれば）"
63100-127 = "（試験を受けなくていいということかもしれない。なんてことを考えながら）"
63100-128 = "（近くのカフェで仕事をして、試験が終わるのを待つことにした）"
63100-135 = "あぁ……これで終わりなんだね……。"
63100-136 = "どうだった？"
63100-142 = "……。"
63100-143 = "……。"
63100-144 = "……全滅。"
63100-148 = "まだ自己採点もしてないのに！？"
63100-149 = "なんていうか……感覚ってあるじゃん。"
63100-151 = "まぁ……実は、私もそんな感じなんだけど……。"
63100-152 = "心の友よ……。"
63100-157 = "[ns] \"みんな、おかえり！\""
63100-159 = "先生……。"
63100-160 = "うぅ……。"
63100-161 = "試験……ダメでしたぁぁぁぁ！"
63100-162 = "[s6] \"言ったでしょ？結果が出るまでは赤点じゃないって。\"\n[s7] \"だから今は、試験が終わった後の伝統行事をやりに行こう！\""
63100-165 = "試験が終わった後の……伝統行事？"
63100-166 = "何ですか、それ？"
63100-167 = "[s8] \"それはね……「テストの打ち上げ」だよ！\"\n[s9] \"美味しいものを食べて、思いっきり遊ぶ！\"\n[s10] \"絶対に守り抜くべき、伝統なんだ！\""
63100-174 = "そんな素敵な伝統があったなんて……！"
63100-175 = "試験も、意外と悪くないかもしれませんね！"
63100-177 = "いや、それはちょっと考え直したほうが……#n準備、あんなに大変だったじゃん……。"
63100-178 = "でもそれはもう終わったこと！#nつまり――！"
63100-179 = "喉元過ぎれば熱さ忘れる！"
63100-180 = "……！"
63100-181 = "これこそアリウス流だね！"
63100-183 = "だね！"
63100-184 = "先生！たくさん食べても……いいですか？"
63100-185 = "[s11] \"もちろん！\"\n[s12] \"じゃあ、他の子たちも呼んでおいで！\""
63100-189 = "はい！"
63100-195 = "（こうして、アリウスの子たちにとって初めての試験は）"
63100-196 = "（派手な打ち上げで、幕を閉じたのだった……）"
63100-208 = "こんにちは、スバル。マイアも、どうぞ座って。"
63100-210 = "こんにちは、アツコさん。"
63100-211 = "あ、こ、こんにちは……アツコ、姫様……。"
63100-213 = "ふふっ。もっと気軽に呼んでくれていいのに。"
63100-214 = "そう決めたでしょ？二人で。"
63100-215 = "そ、そうは言っても……！でも、でも……うぅ……。"
63100-216 = "あ……アツコ、さん……。"
63100-217 = "うん。ありがとう。"
63100-219 = "それで……今日は、どういうご用件ですか？"
63100-221 = "「外」では普通、試験が終わったらこうするって聞いたから。"
63100-222 = "さ、まずは食べよう？このカフェ、ペカンパイが有名なんだって。"
63100-223 = "は、はい……いただきます……。"
63100-224 = "ふふっ、後はね、こうやってお茶をしながら、試験の感想を言い合うらしいんだけど……二人はどうだった？"
63100-225 = "分かるところは全部書きました！"
63100-226 = "分からないことの方が多かったですけど……。"
63100-227 = "スバルは？"
63100-229 = "これが3年生なのか、と。少しギャップを感じましたね。"
63100-230 = "ふふ。でも、自分の実力を知るための模試だからね。"
63100-231 = "ペナルティとか処分もないし、気楽に結果を受け止めればいいと思うよ。"
63100-235 = "えっ？ほ、本当の試験だと処分とかあるんですか！？"
63100-236 = "結果が悪かったら補習が入ったり――"
63100-237 = "ずっと成績が低いと……留年とか、卒業できなくなることもあるみたい。"
63100-238 = "あ……処分って、そういう……。"
63100-239 = "……うん。"
63100-240 = "ある意味、優しい世界とも言えるかな。"
63100-241 = "……。"
63100-242 = "……。"
63100-243 = "これから……スクワッドはどうするんですか？"
63100-244 = "やっぱり気になるよね。まぁ、当然かな。"
63100-245 = "……。"
63100-250 = "アリウスへの責任を取ろうと思ってるよ。"
63100-251 = "……具体的には？"
63100-252 = "アリウスにも生徒会ができるまで、私たちは臨時生徒会の役割を担いたいと思ってる。"
63100-257 = "スクワッドが……生徒会に？じゃ、じゃあ――！"
63100-258 = "私たちの学園も……やっと……ちゃんとした学園に戻れるんですか！？"
63100-259 = "何百年ぶりに！？"
63100-260 = "そうなれるように、精一杯頑張るよ。"
63100-261 = "――アリウスの臨時生徒会長として。"
63100-262 = "生徒会長！？"
63100-263 = "マイア、声が大きいですよ。"
63100-264 = "あ、す、すみません……。"
63100-265 = "……実際、アリウスの伝統に則れば、その役目はあなたを置いて他にいません。"
63100-266 = "それで、他のメンバーは？"
63100-267 = "多分、ミサキが会計をやることになると思う。"
63100-268 = "「なんで私が……はぁ、やればいいんでしょ……」って本人は言ってたけど。"
63100-269 = "言い換えれば、「やるからには、ちゃんと頑張る」って意味だから。"
63100-270 = "そうなんですか……？"
63100-271 = "ミサキは素直じゃないからね。#nあ、これ本人に言うとすっごく怒るから、内緒にしてね。"
63100-272 = "……はぁ。"
63100-273 = "あとは……サッちゃんが総務兼副会長。"
63100-274 = "妥当ですね。"
63100-275 = "学校の運営方針で、こういう提案も出してたよ。 「みんなできるだけアルバイトをしよう」って。"
63100-276 = "なんでまた……？"
63100-277 = "社会のことを学べるし、お小遣いも稼げる。#nそれがアリウスの復興にもつながる、って言ってたかな。"
63100-278 = "みんなが慣れるまでは、契約書は全部目を通させろ、とも言ってたね。"
63100-279 = "……自分の経験を押し付けてるだけじゃないですか。"
63100-280 = "ほら、人は経験から学ぶ生き物だから。#nでも、それ以外の提案もあったんだ。"
63100-281 = "というと？"
63100-282 = "……。"
63100-286 = "これで、おおよその方向性は見えてきたな。"
63100-287 = "部活動設立の申請については、予算と妥当性を勘案して#n許可する必要はあるが……。"
63100-288 = "それは実際の状況を見ながら進めればいいだろう。"
63100-289 = "……ん？アツコ、もっと個人的な希望を聞きたい……とはどういう意味だ？"
63100-290 = "私たちは今、学園のことについて話をしているはずだ。"
63100-291 = "生徒会長としてのお願い……？"
63100-292 = "……。"
63100-293 = "そういうことなら……。#nいや、これは聞き流してもらって構わないのだが……。"
63100-297 = "制服を……作ってもいいんじゃないか……と。"
63100-298 = "可愛くて、お洒落だったら……いいなって……。"
63100-299 = "ありがとう、サッちゃん。そういうのを聞きたかったんだ。"
63100-302 = "ごめん、これはもう少し整理してから話すね。"
63100-303 = "え？あ……そうですか。"
63100-304 = "えっと、それで……あとはヒヨリだね。"
63100-305 = "ヒヨリは……。"
63100-306 = "……書記？"
63100-307 = "まさに、記録係としての書記でしょうね。それは……。"
63100-308 = "うん……本人もそれを自覚してたのか、最初は「うわあぁぁん」って泣いちゃってさ。"
63100-309 = "でもすぐに気を取り直して、本気で頑張るってやる気を見せてくれて。"
63100-310 = "ヒヨリがやる気出すのはいいことだから、私も嬉しかったな。"
63100-311 = "わ、私にはよく分かりませんけど……でも、いいですね……ヒヨリさん、優しいですし……。"
63100-312 = "そうですね……まあ、あなたがそう思うなら……。"
63100-313 = "それでね、「ニコメディアトゥループ」にもお願いしたいことがあるの。"
63100-314 = "……私たちに？"
63100-315 = "風紀委員としての役割を引き受けてもらえないかな。"
63100-316 = "風紀……委員、ですか……？"
63100-317 = "うん。学園の治安や風紀を守るお仕事だね。"
63100-318 = "これは、スバルじゃなきゃ頼めないと思うんだ。"
63100-319 = "……もし私が断ったら？"
63100-320 = "断るの？"
63100-321 = "……。"
63100-323 = "せ、先輩……？"
63100-328 = "……はぁ。"
63100-329 = "そういう言い方はどうかと思いますよ。"
63100-330 = "そうかな？でも、臨時とはいえ生徒会長だし。"
63100-331 = "はぁ、構いませんよ。"
63100-332 = "（なんだかんだ人がついて行くのは……才能ですね）"
63100-333 = "……。"
63100-334 = "で、最終的にはどうするつもりですか？"
63100-340 = "アリウスを素敵な学園にしたい。"
63100-341 = "……その点は、意見が一致しているようですね。"
63100-342 = "アリウスに残った生徒なら、みんな似たような気持ちなんじゃないかな。"
63100-343 = "……それはそうかもしれません。#nただ……実現するためには、やるべきことが山積みでは？"
63100-344 = "分かってる。だからこそ、今度は責任を放棄したくないの。#n……この話、前にもしたよね。"
63100-345 = "自信はあるんですか？"
63100-346 = "全然。私1人じゃ、できないと思うんだ。#nだから、手を貸してほしいの。"
63100-347 = "手を取り合って、みんなで転ぶことになったら……？"
63100-348 = "逆に、転んだ誰かを起こしてあげられるかもしれない。"
63100-349 = "どうせ未来は分からないし、悪い方にばかり考えたくないんだ。"
63100-350 = "それこそ、根拠のない楽観主義では？"
63100-351 = "でも、[ruby=・]動[/ruby][ruby=・]く[/ruby][ruby=・]こ[/ruby][ruby=・]と[/ruby]に意味があるんじゃないかな。"
63100-352 = "私は、それが一番大事だと思ってる。"
63100-353 = "そのためには、未来への漠然とした希望が必要でしょ？"
63100-358 = "みんなと一緒に、前へ進みたいんだ。"
63100-359 = "……。"
63100-360 = "……分かりました。"
63100-361 = "私も、最大限協力しましょう。"
63100-362 = "何が起こるか、何が待っているかなんて、私たちには分かりませんから。"
63100-363 = "……試験を受けることになるとすら、思いもしませんでしたし。"
63100-364 = "ふふっ。私もびっくりだったな。"
63100-365 = "そ、そういえば……トリニティの団長さん、ですけど……。"
63100-366 = "ミネさん？そっか、その話もしないとだね。"
63100-367 = "き、聞いた話だと、あの日は意識が戻らなかったって……。"
63100-368 = "うん、そうだったみたい。"
63100-369 = "でも心配しないで。もう完全に回復したって。"
63100-373 = "ほ、本当ですか！？よかった……！"
63100-374 = "しかも、その間は試験勉強できてなかったのに、大きな影響は無いらしいよ。"
63100-375 = "そうですか……それは何よりですね。"
63100-376 = "すごいよね。「黙示録の天使」4人分の力を、自分の中に封じ込めてるようなものだったのに。"
63100-377 = "はい！？"
63100-378 = "ミネさんは4人の天使を倒して、自分も気を失ったでしょ？"
63100-379 = "そのおかげで、7人の天使が全て調和して力を解放する――なんてことにはならずに済んだの。"
63100-380 = "じゃあ……天使を4人も抱えたまま耐えてたってことですか！？"
63100-382 = "す、スバル先輩……？"
63100-387 = "あ、すみません。取り乱しました……。"
63100-388 = "スバルが最後の天使として撃退されたとき、ほぼ同時にミネさんも目を覚ましたみたい。"
63100-389 = "そんな、まさか……。1人分でも意識を持ってかれかけたのに……ミネさんの精神力はどうなってるんですか……？"
63100-390 = "……それが、信念とか、実直さなんじゃないかな？"
63100-391 = "どんな状況でも、どんな苦しみがあっても。"
63100-392 = "それでも、耐えて進んでいく姿。"
63100-393 = "それって……本当にすごいことだと思う。"
63100-395 = "そうですね……。"
63100-396 = "ただ……1つ理解できないことがあるんです。"
63100-397 = "何？"
63100-398 = "人を救うと言いながら、なぜ人をボロボロにするんですか、あの方は。"
63100-399 = "……。"
63100-403 = "アツコさん……？"
63100-404 = "なぜいきなり仮面を……？#nそれだと喋りにくいと言ってませんでしたか？"
63100-405 = "（スッ、ススッ……）"
63100-406 = "私たち、手話は分かりませんからね！？"
63100-410 = "なっ、逃げるんですか！？"
63100-414 = "あ……でも、会計は済ませてあるんですね……。"
63100-415 = "先輩！私、1つ学びました！"
63100-416 = "いざという時のために逃げ道を作っておくのって、すごく大切なんですね！"
63100-417 = "こんなことから学ばなくていいです……。"
63100-418 = "そもそも、そんな状況にならないようにするのが一番です……。"
63100-430 = "あ、先生。いらっしゃい。"
63100-431 = "[s13] \"みんな元気そうだね！\"\n[s14] \"復旧作業は順調？\""
63100-434 = "今のところは、まだこの場所だけだよ。"
63100-435 = "でも、ここは出発点だから。"
63100-436 = "これからアリウスを、少しずつ変えていきたいんだ。"
63100-437 = "……校舎がちゃんとしてないと、通う気にもならないし。"
63100-438 = "そのうち、新入生とか転校生も受け入れることになるのかな。"
63100-439 = "で、でも……アリウスに通いたい人なんて、いるんでしょうか……。"
63100-440 = "それが、意外といるみたいなんだ。"
63100-441 = "アリウスならではの……あまり口に出しにくい技術を学びたいって人が……。"
63100-442 = "で、できれば無くなったほうがいい技術なんじゃ……！？"
63100-443 = "力に憧れる人間は、いつの時代も、どこにでもいるからな……。"
63100-445 = "実態を知ったら、どうせすぐ逃げるんだし。心配ないでしょ。"
63100-446 = "[s] \"そ、そういえば、みんな試験はどうだった？\""
63100-447 = "私は平均して90点くらいだったよ。初めてにしては、悪くなかったかも？"
63100-448 = "……赤点が何個か。"
63100-449 = "国語……作者の意見とか聞かれても分かんないんだけど。"
63100-450 = "私は赤点ギリギリでした……。うわぁぁぁん。"
63100-451 = "[s15] \"いやいや、すごいと思うよ！\"\n[s16] \"赤点を回避しただけでも立派だよ！\""
63100-454 = "うわぁぁぁん～！#nその優しさがかえって胸に刺さりますぅ……。"
63100-455 = "[s] \"次はもっと頑張ればいいだけだよ！\""
63100-463 = "巡回報告に戻りました……あ、先生。いらしてたんですか。"
63100-464 = "あっ、こんにちは。アリウスへ……ようこそ！"
63100-465 = "そ、それで……ご用件は何でしょう？"
63100-466 = "……え？試験の結果を聞きに……？"
63100-467 = "……。"
63100-468 = "ごめんなさい、先生……私、赤点ギリギリの点数しか取れませんでした……。#nうわあああん～"
63100-469 = "え？ま、マイアさんもですか？"
63100-470 = "ひ、ヒヨリさんも？"
63100-471 = "……。"
63100-472 = "……。"
63100-476 = "わ、私たち……赤点回避仲間ですね……！"
63100-477 = "ですね……！"
63100-478 = "次は、もっと頑張りましょうね……！"
63100-479 = "はい……！"
63100-484 = "うわぁぁぁん～！"
63100-487 = "[ns] \"スバルはどうだった？\""
63100-489 = "……え？"
63100-490 = "[s] \"他のみんなは教えてくれたよ？\""
63100-491 = "……。"
63100-492 = "先生、実はすでに知ってるんですよね？"
63100-493 = "[s] \"……。\""
63100-497 = "[ns] \"平均点くらいだったんだってね。\""
63100-498 = "……はい。"
63100-499 = "[s] \"よく頑張ったね。\""
63100-500 = "……頑張ったと言えるのでしょうか。"
63100-509 = "[wa:1850]― [log=스바루]……本当に、[wa:2000]色々なことが[wa:700]ありましたね。[/log]"
63100-512 = "[wa:600]― [log=스바루]今振り返ると、[/log]"
63100-514 = "― [log=스바루]全てが夢だったんじゃないかと[wa:1100]思うほどですが……。[/log]"
63100-517 = "[wa:250]― [log=스바루]でも、[wa:1600]すべてのことに[/log]"
63100-519 = "― [log=스바루]改めて感謝の気持ちを[wa:1050]伝えたいと思っています。[/log]"
63100-522 = "[wa:350]― [log=스바루]――これだけは、[wa:1900]私の本心です。[/log]"
63100-528 = "ん？私の成績か？"
63100-529 = "うーん……。"
63100-530 = "ちょっと……自慢っぽく聞こえたら悪いが……。"
63100-531 = "そうだな、これも全部先生のおかげだ。"
63100-535 = "満点……だった。"
63100-536 = "ありがとう、先生。"
63100-537 = "先生は本当に……私の人生の、恩人だ。"
