[translation]
70009010-1 = "されど寮監隊は走り続ける（１）"
70009010-3 = "鳥はさえずり、花は咲き乱れる……なんて素晴らしい日なんだ。"
70009010-7 = "こんな日は――"
70009010-10 = "カフェテラスでエスプレッソを一杯やれたら、最高だろうなあ。"
70009010-15 = "まあ、現実は……丸一日検問所の中だけど。"
70009010-22 = "……感傷に浸るのも贅沢、か。"
70009010-23 = "はいはい、分かりました。#nこれより、検問所を開放します。"
70009010-30 = "外出証をご提示ください。"
70009010-31 = "はい。"
70009010-33 = "申告した物は……ないですね。#nでは、ボディチェックにご協力ください。"
70009010-34 = "またやるの？#n制服のどこに隠すっていうの……。"
70009010-35 = "こちらも仕事ですので。"
70009010-43 = "ちょ、ちょっと！どこ触ってるのよ！？"
70009010-44 = "最近、禁制品の持ち込みが多発していまして。#nボディチェックをより厳しくするよう、上からの指示です。"
70009010-49 = "うわっ……く、くすぐったい！#nも、もうやめてぇ！"
70009010-50 = "……問題なさそうですね。#nご協力ありがとうございました。"
70009010-51 = "最初からそう言ってるでしょ！"
70009010-55 = "これだから、寮監隊は……！"
70009010-56 = "真面目に仕事してるだけなんだけどなぁ……。"
70009010-57 = "はぁ……愚痴ってもしょうがないか……。"
70009010-58 = "次の方、どうぞ。"
70009010-62 = "はい、外出証とカバン。"
70009010-63 = "では、中身を確認させていただきます。"
70009010-70 = "これは……明太子ポテチですか。"
70009010-72 = "そうだよ？"
70009010-76 = "没収です。"
70009010-77 = "嘘でしょ！？"
70009010-78 = "学院の食品安全基準を満たしていません。"
70009010-82 = "あんぜん……何？"
70009010-83 = "袋内の窒素が少なく、#n輸送中に破れる恐れがあるため……とのことです。"
70009010-84 = "で、でもっ……。#n食べる分には平気でしょ！？"
70009010-85 = "ルールはルールですので。"
70009010-89 = "えっと、人形ですね。これもたしか……。"
70009010-90 = "ああ、リストにありました。#nモモフレンズのペロロ人形……はい、没収です。"
70009010-91 = "……これはなんで？"
70009010-92 = "ええと、最新エピソードで公式がキャラブレを起こしたため、外交的抗議があり……。#n……ってなにこれ？"
70009010-93 = "……とりあえず、モモフレンズのグッズは当面の間、#n持ち込み禁止です。"
70009010-94 = "あんたもピンと来てないじゃん！"
70009010-99 = "え、これって……。"
70009010-100 = "パイナップルですか？"
70009010-101 = "そうだけど？"
70009010-102 = "……いえ、カバンから出てくるとは、と。#nこれも没収します。"
70009010-103 = "なんでよ！ただの果物だよ！？"
70009010-104 = "パイナップルピザ根絶のため、全面禁止にしています。"
70009010-105 = "誰が決めてるの、それ……？"
70009010-106 = "私です。#nパイナップルピザ、嫌いなので。"
70009010-108 = "自分の都合じゃん！"
70009010-109 = "犯罪に使用される可能性の高い物品は、#n検問官の判断で没収できるんですよ。"
70009010-110 = "パイナップルピザのどこが犯罪なのよ……。"
70009010-114 = "最後に……こちらは？"
70009010-115 = "あ、ゲヘナの生徒会長の自伝……だったかな？#n派手な本なのに、投げ売りされてたから、逆に面白そうだなって。"
70009010-116 = "未登録の書籍ですね。没収します。"
70009010-117 = "これ、めっちゃ重かったんだよ！？#n苦労して持ってきたのに！"
70009010-118 = "正式に調査し、問題がなければ告知されるかと。#nその後、正式に書類手続きをしてお受け取りください。"
70009010-119 = "これで全部ですね。どうぞお入りください。"
70009010-124 = "全部没収じゃん！どういう基準なの！？#n他校じゃ全然みんな持ってるのに！"
70009010-125 = "禁制品はルールブックに全て記載してありますよ？"
70009010-127 = "そんなの、あんたらしか読まないでしょ！"
70009010-132 = "はぁ、それが問題なんだよ……。"
70009010-133 = "押収品は倉庫行き、と……はい、次の方。"
70009010-137 = "よいしょっ……と。"
70009010-138 = "多いですね。では、中身を確認します。"
70009010-139 = "はい！申告通りのはずですよ！"
70009010-145 = "どれどれ……レッドフラワーの筆6本入りが50セット、クルーガーSBの4号から8号が50セット、キャンバスは3号が100枚に4号が100枚、あとは塗膜剥離剤が1缶と……。"
70009010-146 = "ん？キャンバスの裏に何か……。"
70009010-147 = "あっ……！"
70009010-154 = "……こちらは？"
70009010-155 = "ご覧の通り……ミレニアム製のナパーム弾です。"
70009010-156 = "SMGに手榴弾……未申告のものばかりですが。"
70009010-157 = "あ～……私物でして。#nどうせなら一緒に運ぼうかなと。"
70009010-161 = "でも、こんなものまで申告がいるんですか？"
70009010-165 = "……たしかに、銃までいちいち申告していてはキリがないですね。#n衣服まですべてチェックするようなものです。"
70009010-166 = "はい、問題ありません。お進みください。"
70009010-167 = "どうもありがとうございます～"
70009010-172 = "全員、今のような感じなら、この仕事も楽なのに。#n……はぁ、次の方どうぞ。"
70009010-176 = "ほら！外出証と今回の搬入品だ！早くしてくれ！#n今、インスピレーションが湧いてきたところなんだ！"
70009010-177 = "は、はい。少々お待ちください……。"
70009010-182 = "これは……一体何でしょう？"
70009010-183 = "トリニティから持ってきた彫像だよ！#nこれをすりつぶして絵の具にすれば、繊細で柔らかい白色になるんだ！"
70009010-184 = "あの……持ち主の許可は取っていますか？"
70009010-185 = "え？置いてあったから貰ったんだよ。#nどう見ても骨董品だろ？"
70009010-186 = "たしかに古いもののようですが。"
70009010-187 = "作ったやつなんて、どこにいるやら……。"
70009010-188 = "ひとまず没収します。#n色々とお聞きしたいことがあるので、こちらでお待ち――"
70009010-189 = "は、はあ！？#nインスピレーションは待ってくれないんだぞ！"
70009010-193 = "……さては、私のアイデアを盗むつもりだな！？  "
70009010-194 = "盗んでるのはあなたの方でしょう。#n制裁の対象になりますよ。"
70009010-195 = "制裁……？芸術を弾圧する気か！！"
70009010-196 = "いや、ですから……これは犯罪で……。"
70009010-198 = "私は権力に屈しない！#n芸術は、世界との終わりなき闘争から生まれるんだ！！"
70009010-203 = "あっ！#nこちら検問所！不法侵入者です！"
70009010-207 = "なに！？どこだ！？"
70009010-208 = "すぐ追いかけろ！"
70009010-210 = "なんだ？騒がしいね。"
70009010-211 = "あの子は持ち込んでいいの？#nじゃ、私のも返してよ！"
70009010-212 = "今のうちにこっそり入っちゃえ……！"
70009010-214 = "な、なんだ、こいつら！？下がれ！！"
70009010-215 = "こちら検問所！非常事態です！#n生徒が集団で検問を突破しようと……！増援を求めます！"
70009010-217 = "今だ！自由を弾圧する寮監隊を追い出せ！"
70009010-218 = "ビバ！ワイルドハント！我々は奴隷にはならない！  "
70009010-229 = "あ……。"
70009010-236 = "鳩だ。"
