[translation]
70010010-1 = "手動期の終り（１）"
70010010-10 = "そして今月の最優秀プリン試食家兼、レッドウィンター科学アカデミーの議長であるチェリノ様だ！"
70010010-100 = "ほ、本当ですか！？"
70010010-101 = "今度、レッドウィンター連邦学園に招待しようじゃないか。#n我々の技術力を見せてやる！"
70010010-103 = "では、来週の月曜日に行きますね！"
70010010-104 = "……え？"
70010010-105 = "ちょうど、近くまで行く用事がありますので！"
70010010-106 = "ベールに包まれた、レッドウィンターの最先端技術……！#nそれを見せていただけるなんて本当に光栄です！当日はよろしくお願いします！"
70010010-11 = "最先端をゆくレッドウィンター連邦学園の科学技術に更なる進歩をもたらすべく、ミレニアム[ruby=エキスポ]EXPO[/ruby]に足を運んだのだ。期待しているぞ。"
70010010-110 = "あ、ああ！来週の月曜日だな！"
70010010-111 = "レッドウィンター連邦学園の偉大さを、その目に焼きつけるといい！！"
70010010-114 = "どうしよう……？"
70010010-115 = "来週の月曜って……スーパーコンピューターなんて無いぞ……。"
70010010-116 = "訪問時期に合わせて、不穏分子のクーデターを誘導するのはいかがでしょう？"
70010010-117 = "良い案だが……この前はクーデターが成功しすぎて、復権までが面倒だった。しばらくは嫌だな。"
70010010-118 = "うーん……よく探せば1つくらい、誰かが持ってたりしないか……？#nそれとも、いっそ作らせるとか――"
70010010-12 = "……チェリノ会長、ありがとうございました。それではさっそくご紹介します！#nミレニアムの力作……スーパーコンピューター「SEN9000」です！"
70010010-122 = "チェリノ会長、183号特別クラスに依頼していた制作見積書が届きました。"
70010010-123 = "技術の理論研究および、コンピューターの設計まで完了したとのことです。"
70010010-124 = "本当か！？でかしたぞ、トモエ！"
70010010-125 = "今すぐ制作に取り掛からせろ！#n事務局の権限で、あらゆる資材と労働力を総動員しよう！"
70010010-126 = "それで、見積書の内訳ですが……#nレッドウィンター連邦学園の電子工学技術を踏まえると――"
70010010-127 = "真空管を1600億本。"
70010010-128 = "電力供給用の発電所を27カ所。"
70010010-129 = "常駐スタッフの居住用に新都市を3つ用意する必要があります。#nそして……。"
70010010-131 = "……ん？"
70010010-132 = "施設用地を確保するために、山8つを崩さなければなりません。"
70010010-133 = "えぇ……。"
70010010-134 = "1日16時間の週7日労働、交代勤務により全労働力を投入した場合――"
70010010-135 = "完成まで約6世紀かかる見込みです。"
70010010-136 = "……。"
70010010-137 = "取り掛かりますか？"
70010010-139 = "ミレニアムが来るのは来週だぞ！？間に合わないではないか！！！"
70010010-143 = "はっ……はくしょん！"
70010010-145 = "（緊張で喉が渇いたな……お茶を一杯もらおう……)"
70010010-149 = "（それにしても……トモエ秘書室長、大変そうだ……保安委員会が絡んでなくてよか――）"
70010010-153 = "（……！？お茶が変なところに……！むせてしまう……！）"
70010010-154 = "く、くふっ！"
70010010-159 = "……マリナ、何がおかしい？"
70010010-160 = "おいらが困っているのはそんなに面白いか？"
70010010-162 = "ち、違います！く、くはっ、そんなことは……！"
70010010-163 = "それなら……ヒゲが取れたおいらを見下しているのか？"
70010010-164 = "そ、そうではなくて、お、ちゃ――"
70010010-165 = "茶番？この状況を茶番だと言いたいのか？"
70010010-167 = "（ま、マズい！このままでは粛清されてしまう……！！）"
70010010-168 = "ちゃ……。"
70010010-17 = "ん？これがスーパーコンピューター？#nモニターもキーボードも無いじゃないか。"
70010010-172 = "着手しています……！#nそう！保安委員会は、既にスーパーコンピューターの準備に着手しています！"
70010010-173 = "なに？それは本当か？"
70010010-174 = "当然です！不肖マリナ、期日までに責任をもってご用意します！"
70010010-175 = "マリナ。"
70010010-176 = "は、はいっ！"
70010010-18 = "それは、私が画像と音声を用いて、情報の入出力を行うからです！"
70010010-181 = "お前のような忠臣が傍にいて、おいらは果報者だ。"
70010010-182 = "レッドウィンターとおいらのために尽くすその献身的な姿……称賛に値する。"
70010010-183 = "……分かった。この件はお前に任せる。#n無事に終われば「第一級髭労働章」を――"
70010010-184 = "いいや！それでは小さすぎる！"
70010010-185 = "「レッドウィンター連邦英雄」の勲章を授与するとしよう！"
70010010-186 = "はい！お任せください！"
70010010-192 = "どうする……？"
70010010-193 = "来週までに……？#nスーパーコンピューターなんて作って無いぞ……。"
70010010-198 = "どうしよう、とはなんだ。"
70010010-199 = "圧政者のくせに、あたしたち勤労大衆に助けを求めるのか？"
70010010-2 = "ミレニアムエキスポコンピューター工学館"
70010010-200 = "わはは！崖っぷちじゃん！"
70010010-201 = "この話、漫画のネタに使ってもいい？#nあ～笑いすぎてしんどい！"
70010010-202 = "その前に、今の原稿をあげてもらえますか？#n締切が守れなかった先輩だって、崖っぷちですからね。"
70010010-203 = "しゅん……。"
70010010-207 = "ムフフ。このままじゃ赤っ恥ですねぇ？#n事前にインタビューでも取っておきましょうか。"
70010010-208 = "お茶が原因で粛清された保安委員長……次号の「レッドベア」の表紙はこれでいきましょう。"
70010010-209 = "ノンフィクションとはいえ、あまりの愚かさに文学的価値を感じませんね。"
70010010-210 = "10点中2点、差し上げますわ。"
70010010-212 = "なんで点数？"
70010010-213 = "ふつうの評論では皆さんに響かないようでしたので、昨日から点数制を導入いたしまして。"
70010010-214 = "ああ、メルリーさんの現在の原稿は0点です。#n完成していなければ、作品とは呼べませんから。"
70010010-215 = "えっと……私より評論しがいのある人が目の前にいるんだし、そっちの話しない？"
70010010-217 = "……いくらでも笑ってくれ。#n何とか、手を貸してもらえないだろうか……？"
70010010-218 = "断る。圧政者に提供する労働力はない。"
70010010-219 = "どうしてあたしが――いや、我々があなたに協力しなければならないんだ？"
70010010-220 = "その、これには理由があるんだ……。"
70010010-221 = "実は……誰と一緒に作っているのか、と会長に聞かれて――"
70010010-222 = "思いつくまま、お前たちの名前を言ってしまったんだ……。"
70010010-223 = "皆で、力をあわせる、と……。"
70010010-230 = "な、なんだってー！？！？"
70010010-231 = "1点です、1点！！あなた、気はたしかですか！？"
70010010-232 = "どうして私たちを巻き込むのさ！？"
70010010-233 = "ひぇ……み、みんな粛清されてしまいますよ！"
70010010-235 = "圧政だけでは飽き足りず、失策の責任まで民衆に背負わせるのか？"
70010010-236 = "関係者を増やして、責任の所在を曖昧にするという手口です？#n私たち、何か恨まれるようなことしましたかねぇ？"
70010010-238 = "ち、違う！慌てて、つい言ってしまったんだ。#n悪気はなかったんだ……本当だ。"
70010010-239 = "皆とは顔見知りだから……私が勝手に、友達だと……思い込んでいただけで……。"
70010010-24 = "はじめまして！#nレッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、掃除部部長兼、運動部代表兼、[ruby=・   ・   ・   ・]生徒会長[/ruby]兼、風紀委員長兼、給食部長兼――"
70010010-241 = "友達……？"
70010010-242 = "おん？"
70010010-244 = "わ、忘れて……ごめん、名前を出しちゃったことは、本当に……。"
70010010-245 = "……会長に白状する。#nお前たちが濡れ衣を着せられないよう責任を取ろう。"
70010010-246 = "私がもっと慎重になるべきだった……友達なら、なおのこと……。#n本当に、ごめん。"
70010010-25 = "そして今月の最優秀プリン試食家兼、レッドウィンター科学アカデミーの議長であるチェリノ様！ミレニアムサイエンススクールへようこそ！"
70010010-250 = "9点……です。"
70010010-251 = "ちょっと！！なんでそんな高評価なの！？#n私の漫画はボロクソ言うのに！"
70010010-252 = "リアルなヒューマンストーリーの感動に比べたら、#nメルリーさんはまだまだですわ。"
70010010-253 = "友達だと思ったから頼りたかった……今のは心に響きました。"
70010010-255 = "友達……あの保安委員長がそんなことを言うなんて……。"
70010010-256 = "これは……スクープ級の特大ネタですねぇ。ムフフフ。"
70010010-258 = "やはり、友達ではなかったんだな……私の思い込みか……。"
70010010-26 = "こ、これはどういうことだ！？いきなり話しかけてきたぞ！？"
70010010-260 = "い、いやいや、そういう話じゃなくってさ！"
70010010-261 = "手伝うったって、どうすればいいか分からないなあ～って、ね？みんな？"
70010010-262 = "そうですよ……#nレッドウィンターの労働力を総動員しても600年かかるんですよね？#n私たち5人が手伝ったところで……。"
70010010-263 = "いや……4人でしたね。#nメル先輩はこんなことしてる場合じゃないですよね？"
70010010-264 = "あとちょっとであがるってば！"
70010010-266 = "[ruby=いけくら]池倉[/ruby]マリナ。レッドウィンターの事務局員であり、保安委員長……。"
70010010-267 = "圧制者の走狗に「友達」だと思われていたのか……。"
70010010-27 = "しかも、おいらの肩書きを全部覚えたのか！？たった一度聞いただけなのに！？"
70010010-273 = "我々の同志となることを歓迎するぞ！"
70010010-274 = "ど、同志！？"
70010010-276 = "ミノリさん！？"
70010010-277 = "おっと……これは意外な展開。"
70010010-278 = "もう少し粘って保安委員会との取引に持ち込もうと思ったのですが……そうきましたか……。"
70010010-279 = "部長、ビジネスチャンスを狙うにしてもTPOを弁えて欲しいですわ。"
70010010-28 = "（会長の[ruby=・   ・   ・   ・   ・]言い間違い[/ruby]まで模倣していた……）"
70010010-280 = "これは失敬。ムフフ。"
70010010-282 = "……マリナよ、圧政者の暴政に怯え、民衆の階級意識に目覚めたのだな。"
70010010-283 = "闘争の戦線に合流せよ！悩みなき明日は、我々の手で勝ち取るのだ！"
70010010-284 = "気持ちはありがたいが、どう考えても方法がないんだ……。"
70010010-285 = "あれほど大がかりな工事……たとえ工務部総出でも不可能だろう……。"
70010010-286 = "いっそのこと、クーデターを準備したほうが現実的な気がするのだが……。"
70010010-287 = "具体的には何なんです？チェリノ会長の欲しいものって。#n複雑な機械なのは分かりましたけど。"
70010010-288 = "ミレニアム[ruby=エキスポ]EXPO[/ruby]の視察で見たコンピューターだ。"
70010010-289 = "どんな質問にも答えてくれていた。"
70010010-29 = "（それができるのは私だけだと思っていたのに！）"
70010010-291 = "質問に答えてくれる機械？"
70010010-292 = "なんだ、簡単じゃないか。"
70010010-297 = "……簡単だと！？"
70010010-299 = "[log]ミレニアム演算科学研究部 訪問1日前[/log]"
70010010-3 = "これより、デモンストレーションを始めます！"
70010010-301 = "マリナ委員長、いよいよ明日に迫ったわけだが。"
70010010-302 = "用意できなかった……などと腑抜けた報告をするつもりではないだろうな？"
70010010-303 = "とんでもございません！"
70010010-304 = "すでに、デモンストレーションの準備は完璧に整っております！"
70010010-305 = "同志よ！#nレッドウィンターの技術を結集して作り上げたスーパーコンピューターをここに！"
70010010-31 = "ふふっ、私が言う間もなくSEN9000が答えてしまいましたね。"
70010010-311 = "これこそがチェリノ会長の指導で生まれた、#n最先端のスーパーコンピューター……。"
70010010-312 = "「RFC9001」です！"
70010010-314 = "RFC……？"
70010010-315 = "「[ruby=Redwinter Federal Computer]レッドウィンター連邦コンピューター[/ruby]」の略で、ミレニアムの「9000」より一歩進んだという意味の「9001」です！"
70010010-316 = "マリナ……！信じていたぞ！"
70010010-32 = "このSEN9000は対話型モデルを搭載しています。そのため、文字入力なしで言葉を理解し、命令に応えることができるんです。例えば、こんな風に――"
70010010-323 = "よくやった！！"
70010010-324 = "（チェリノ会長の称賛……！いつぶりだろうか！）"
70010010-325 = "ご、ゴホン！セキュリティを考慮し、情報の入力は記入方式にしました。#n質問を書いた紙をこちらの投入口にお入れください。"
70010010-327 = "こいつもミレニアムのアレみたいに、何でも答えてくれるのだな？"
70010010-328 = "それでは……。#n『レッドウィンター連邦学園の最高指導者は誰だ？』"
70010010-33 = "SEN9000、得意分野を教えてくれる？"
70010010-334 = "なんだ？こんなことも答えられないのか？"
70010010-336 = "て、丁寧な言葉を使うよう設定されているので、少々お時間をいただきます！"
70010010-337 = "しばらくお待ちいただければ……。"
70010010-34 = "はい！私は数学の演算と、質問に対して正確に回答するのが得意です！"
70010010-342 = "出た！"
70010010-343 = "『レッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、掃除部部長兼、運動部代表兼、風紀委員長兼、給食部長兼――』"
70010010-344 = "『そして今月の最優秀プリン試食家兼、レッドウィンター科学アカデミーの議長であるチェリノ様です』"
70010010-345 = "おお！おいらの肩書きを完璧に把握しているな！"
70010010-347 = "これくらいは序の口です！"
70010010-348 = "人間同様に学習した、超高性能のスーパーコンピューターですから！"
70010010-349 = "（「人間同様」……当然のことだ。なにせ――）"
70010010-35 = "じゃあ、数学からやってみよう。この問題を解いてくれるかな？"
70010010-351 = "ボックスの内"
70010010-352 = "これでいいんだな？"
70010010-354 = "あら、よく覚えてますわね、あんな長いもの。"
70010010-355 = "出版部ではいちいち打ち込むのが面倒で、肩書きの印刷版を作りましたけどねぇ。"
70010010-356 = "バンクシーン的な？"
70010010-358 = "敵を知り己を知れば、百戦危うからず。#n圧政者の肩書きを正確に把握するのは、革命の基本だ！"
70010010-359 = "し、しーっ……！あまり騒がないでください！#n箱の中に私たちがいるってバレちゃいますよ！？"
70010010-360 = "安心しろ！これは183号製の特別防音ボックスだ。#n音が漏れないよう設計されている。"
70010010-361 = "あたしたちは外側のマイクとのぞき穴で、外の様子を確認すれば良い。"
70010010-362 = "いくらなんでも無茶ですよ！#nもしバレたら……卒業までこの中で暮らすことになるかも……。"
70010010-364 = "それなりに居心地良いですけどねぇ……だんだん眠くなってきて……ムフ……。"
70010010-365 = "……フ……。"
70010010-366 = "ただの酸素不足じゃないですか！"
70010010-367 = "そもそも、全員で入る必要ありましたか？"
70010010-369 = "一人が答えられるものには限界があるからな。"
70010010-37 = "あれは……数学なのか？数字はほとんど無いが……。"
70010010-370 = "それに、同志が困っているのに、見て見ぬふりをするわけにはいかないだろう？"
70010010-371 = "惨劇を放っておけなかった……のほうが正しいかと。"
70010010-372 = "こんな2点にもならない計画だと分かっていたら、#n最初から協力しませんでしたわ！"
70010010-374 = "なるほど。タカネさんが惻隠の情を抱きました、と。"
70010010-375 = "ネタ探しを口実に遊びに来ている締切破りの作家さん、何か言いましたか？"
70010010-376 = "うっ……！目の前の締切も大事だけど、今後のためのネタ集めも重要で――"
70010010-378 = "次の質問がくるぞ！"
70010010-38 = "それに手書きですね。あれを理解できるのでしょうか？"
70010010-380 = "（中の皆は大丈夫だろうか……）"
70010010-381 = "（バレたら……私まで箱に入れられるかもしれない……！）"
70010010-383 = "今度は難しいやつにしよう！数学の問題を用意してきたんだ！"
70010010-384 = "アカデミーに薦められた問題だからな。半端な性能では答えられないはずだ！"
70010010-386 = "（アカデミー級の問題！？ま、マズい！）"
70010010-388 = "解説書ももらってある。よし、早速試そうではないか！"
70010010-393 = "か、会長！そ、その、もちろん自信はありますが……！"
70010010-394 = "うん？何か問題でもあるのか？"
70010010-395 = "あの、実は……！"
70010010-396 = "（やっぱり無茶だったんだ……バレる前に白状したほうが……！）"
70010010-397 = "大変申し訳ございませんでした！どうかお許し――"
70010010-4 = "開始に先立ち、特別にお越しいただいたレッドウィンター事務局の皆様から、お言葉を頂戴します。"
70010010-40 = "……。"
70010010-402 = "お！答えが出たな！"
70010010-404 = "――を……って、あれ？"
70010010-406 = "どれどれ……。"
70010010-407 = "内容はよく分からんが、模範解答と同じだな。"
70010010-408 = "マリナ！素晴らしいぞ！"
70010010-409 = "それで……何か言いかけなかったか？"
70010010-41 = "ふんっ、答えられるはずがない。"
70010010-411 = "（……正解？こんなに早く！？）"
70010010-412 = "い、いえ！問題をご用意いただき、ありがとうございます！"
70010010-413 = "うむ。検証もまた、会長としての重要な仕事。これくらい当然だ！はっはっは！"
70010010-414 = "あ、あはは！はははっ！"
70010010-416 = "い、今の問題！ミノリさんが解いたんですか！？"
70010010-417 = "記号のほうが多かった気がするんだけど！？"
70010010-418 = "紙が入ってくる途中から解き始めてましたよねぇ？"
70010010-42 = "我がレッドウィンター連邦学園に存在しない技術が、他校にあるわけ――"
70010010-420 = "謙遜するつもりはないが、普通の問題だったぞ？"
70010010-422 = "しかも正解だなんて……10点満点の活躍ですわ！"
70010010-423 = "ムフフ、大絶賛ですねぇ。"
70010010-425 = "ミノリ部長、勉強できたんですね……すごいです……。"
70010010-426 = "圧政の鎖は、鋼鉄のような意志と、炎のような知性で断ち切るものだからな！"
70010010-427 = "さすがはレッドウィンターでも随一の要注意人物。言うことが違いますねぇ。ムフフフ。"
70010010-429 = "質問、またくるよ！"
70010010-43 = "……すみません！私としたことが！#nミュートになっていると気づかず、一人でしゃべっちゃってました！"
70010010-44 = "それにしても、デモンストレーションだからって、こんな簡単な問題出さなくてもいいんですよ？答えは42です！"
70010010-443 = "（ここまではなんとか誤魔化せているが……）"
70010010-444 = "（どうしてだろう……嫌な予感がする……）"
70010010-50 = "正解！#n言語モデルの学習能力もあるので、最近は冗談も言えるようになったんです。"
70010010-51 = "次は質問に答えてもらいましょう。#nせっかくですし会長、何か質問してみませんか？"
70010010-52 = "お、おいらか！？"
70010010-53 = "そうだな……レッドウィンター連邦学園内にあるおいらの銅像は、全部で何個だ？"
70010010-54 = "ふっふっふ。どうだ？さすがに答えられないだろう！"
70010010-56 = "合計199個で、さらに1個、来月上旬に公開される予定です。"
70010010-57 = "この情報は公式SNSおよび電子版「レッドベア」、#n報道発表資料を参照したため、誤差が含まれている可能性があります。"
70010010-58 = "なお統計上、翌週には10個以上の銅像が破壊されることでしょう。"
70010010-59 = "お役に立ちましたか？"
70010010-60 = "迷わず答えた、だと……？"
70010010-61 = "情報も……正確、ですね……。"
70010010-63 = "これらの他にも様々な機能があります。#n次はこちら――"
70010010-64 = "うぅ……。"
70010010-72 = "これをもちまして、デモンストレーションを終了させていただきます！"
70010010-74 = "すごかったね！なんでもできちゃうんじゃない！？"
70010010-75 = "これがミレニアムの技術力……想像以上だよ……。"
70010010-77 = "そしてレッドウィンター連邦学園の皆様！#n改めて、本日はお越しいただきありがとうございました！"
70010010-78 = "う、うぅ……。"
70010010-8 = "うむ。おいらに相応しい歓待、ご苦労だった。"
70010010-84 = "く、くだらん！！"
70010010-9 = "私は……レッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、掃除部部長兼、運動部代表兼、[ruby=・   ・   ・   ・]生徒会長[/ruby]兼、風紀委員長兼、給食部長兼――"
70010010-90 = "なかなか面白いものを見せてもらった！#nだが！そ、そんなもの、偉大なるレッドウィンター連邦学園にも存在する！"
70010010-91 = "しかも、もっと大きくて温かいんだぞ！"
70010010-92 = "（会長、それはコンピューターの自慢にはなりません……）"
70010010-96 = "なんと！#nレッドウィンターもスーパーコンピューターを運用していたんですね……！"
70010010-97 = "不勉強ですみません……コンピューター研究学会ではお見かけしたことがなかったので……。"
70010010-98 = "そ、それは性能が良すぎて、ずっと秘匿していたからだ！"
70010010-99 = "しかし今日の発表をみるに、ミレニアムの技術はようやく我々に追いついてきたようだからな。これなら教えてやっても問題ないだろう！"
