[translation]
70010020-1 = "手動期の終り（２）"
70010020-10 = "えっ！そんなことして、バレたらどうすんの！？"
70010020-100 = "あったまきたっ！！"
70010020-102 = "先輩！落ち着いてください！#n外まで聞こえちゃいますよ！？"
70010020-103 = "印刷したかのようなきれいな線が引けていた、という意味ですわ、きっと！"
70010020-105 = "放して！！一発殴らせてよ！！"
70010020-107 = "会長、新作プリン試食会のお時間です。"
70010020-108 = "もうそんな時間か！検証に夢中になってしまっていた。"
70010020-109 = "マリナ委員長、ご苦労だった。"
70010020-11 = "バレる心配か。ならば聞かせてもらうが、「質問」の定義は何だ？"
70010020-110 = "今月の「レッドウィンター連邦英雄」の正式候補に推薦しておこう！"
70010020-112 = "あ、ありがとうございます、会長！"
70010020-113 = "最後に……レッドウィンターの未来に関わる重大な質問を一つ、#n聞こうではないか。"
70010020-114 = "質問事項は極秘にせねばならん。全員、部屋から出ろ！"
70010020-115 = "い、一同、退室せよ！"
70010020-116 = "はい！承知しました！"
70010020-126 = "ふむ……。"
70010020-127 = "あんれまぁ……レッドウィンターの極秘情報がラクラク入手できちゃいますねぇ～"
70010020-128 = "ありがたき幸せ～ムフフ～"
70010020-129 = "圧政者自ら極秘情報を漏えい……革命の大義名分としては十分だな。"
70010020-13 = "「自分の分からない事実を相手に問いただすこと」――"
70010020-131 = "私たちが知ったとバレたら、粛清3回じゃ済まないよ！？"
70010020-135 = "紙が入ってきました。"
70010020-137 = "どれ……。"
70010020-138 = "『カムラッドに、もっとたくさんレッドウィンターに来てもらいたい』"
70010020-14 = "ですが？"
70010020-142 = "『あと、いっぱい遊んでほしい。どうしたらいいかな？』"
70010020-143 = "……。"
70010020-145 = "あっ……。"
70010020-146 = "これは……9点ですね……。"
70010020-148 = "バレたら粛清9回でも済まないんじゃ……！？"
70010020-149 = "たしかにネタは探してたけど、これは重すぎるって！"
70010020-15 = "そう。[ruby=・   ・   ・   ・   ・   ・   ・]分からないから[/ruby]聞く。それが質問だ。"
70010020-150 = "何か！良い答えはないのか！みんな、知恵を絞るんだ！"
70010020-152 = "このふわふわとした手紙にどう答えろと言うのです！？"
70010020-153 = "何でもいいから早く！各自、思いつくものを書け！！"
70010020-156 = "出た！"
70010020-157 = "どれどれ……。"
70010020-159 = "『いい質問ですね、同志！では次の事項を実践してください！』"
70010020-16 = "分からないなら、[ruby=・   ・   ・   ・   ・]返答の是非[/ruby]も分からないだろう？"
70010020-160 = "『週2日労働の導入、出版部の予算3倍増額、同人活動のための予算編成』"
70010020-161 = "『……以上を実践すれば、先生ともっとたくさん遊べるようになります！』"
70010020-164 = "なんだ！簡単なことじゃないか！"
70010020-165 = "ありがとう、スーパーコンピューター！"
70010020-17 = "……答えただけ、ということですね。"
70010020-171 = "セーフ……。"
70010020-177 = "戸締まりは私がする。先に戻れ。"
70010020-178 = "承知しました！では、失礼いたします！"
70010020-18 = "「メルリーさん、この場面は何を意味していますの？」の答えみたいな感じだね。"
70010020-186 = "もう出てきて大丈夫だ。"
70010020-187 = "くはああーっ！シャバの空気！"
70010020-189 = "タカネは眠ってますねぇ。まあ、もう夜ですし。"
70010020-19 = "先輩、その場合は分からないから聞いてるわけじゃないと思いますよ？"
70010020-190 = "なんとか生き延びられました……。"
70010020-192 = "皆、すまなかった！この借りはいつか必ず返す！私の名誉にかけて約束しよう！"
70010020-193 = "明日もう一日だけ耐えてくれ、頼む！"
70010020-194 = "その必要はない。我々の革命は今夜、実りを果たすのだから！"
70010020-195 = "ああ！革命は今夜――"
70010020-199 = "――今、なんと？"
70010020-2 = "うーん、次は何を聞くか……。"
70010020-200 = "苦しみ続けた同志を救う、最後のピースが揃ったのだ。"
70010020-201 = "即ち、元凶たるチェリノ会長を引きずり下ろせば良いだけの話。"
70010020-202 = "なぜそんな話に！？"
70010020-203 = "同志マリナが事務局にこの「コンピューター」を運び入れてくれたおかげだ。"
70010020-204 = "今回の革命は外からでなく……内からはじめる！"
70010020-206 = "解放の時間だ、同志マリナ！"
70010020-207 = "そ、そんなこと――！！"
70010020-21 = "どのみち、バレる心配はない。知っていることだけ答えれば十分だ。"
70010020-214 = "進もう！解放は目前だ！！"
70010020-219 = "……結局、こうなっちゃいましたね。"
70010020-220 = "うああ！締切！どうしよう！！"
70010020-224 = "なんの騒ぎですか？私が寝ている間に何が……。"
70010020-225 = "これはアレですねぇ……#nコンピューターから飛び出てきたウィルスのような存在……。"
70010020-227 = "なんとかの……木馬、みたいな？"
70010020-229 = "やっと着いた！レッドウィンター！"
70010020-23 = "ふむ……聞きたいことは、あらかた聞きつくしてしまったな。"
70010020-230 = "レッドウィンターのスーパーコンピューター……楽しみだなぁ。"
70010020-231 = "どんな性能なのかな？早く見た――"
70010020-239 = "スーパーコンピューター革命軍よ、事務局を打倒せよ！！"
70010020-240 = "スーパーコンピューターの力で、勝利を掴もうではないか！！"
70010020-245 = "スーパーコンピューターめ、おいらを裏切ったな！？"
70010020-246 = "粛清だ、粛清！！！！！！"
70010020-25 = "ご満足いただけたようで何よりです！#nそれでは、明日に備えて電源をオフに――"
70010020-259 = "スーパーコンピューター革命……軍？裏切り……？"
70010020-263 = "うちの子……性能落としとこ……。"
70010020-264 = "手動期の終り"
70010020-27 = "そうだ！絵を描いてもらおう！"
70010020-29 = "はい！？"
70010020-3 = "（皆、そろそろ疲れが出る頃じゃ……）"
70010020-31 = "たしかミレニアムのアレは、絵を描くこともできたはずだ。"
70010020-32 = "ではさっそく……『威厳のあるおいらの肖像画を描け！』#nうむ、楽しみだな！"
70010020-33 = "『威厳のあるおいらの肖像画を描け！』だと……？"
70010020-34 = "あたしは設計図しか描いたことがないんだが……。"
70010020-35 = "うーん……。"
70010020-41 = "……え？"
70010020-42 = "なんでこっちみるのさ。#n……私が描けってこと！？"
70010020-43 = "この中だと、適任なのは大作家メルリーさんですわ。"
70010020-44 = "先輩、どうせ脱稿は無理です。#nここに入ってから一枚も進んでないじゃないですか。"
70010020-45 = "よかったですねぇ、大作家メルさんに活躍の場が与えられて。ムフフ。"
70010020-47 = "イヤだ！"
70010020-48 = "漫画家だからって、言えばホイホイ絵を描くと思ったら大間違いなんだから！"
70010020-49 = "絵はタダじゃないし！そもそも絵を描くのって簡単じゃないんだよ！"
70010020-5 = "ボックスの内"
70010020-51 = "先輩！今は目の前の危機をなんとかしましょう！#nというかネタ探しにきたんですよね！？"
70010020-52 = "イヤだイヤだイヤだ！！そんな機能はない！ないって言っといて！"
70010020-53 = "ふむ、反応がないな。"
70010020-55 = "おそらく……機能にないからだと思いますが……#n少しお待ちいただければ……。"
70010020-57 = "機能がない？つまりは、ミレニアムのアレより劣っているということか？"
70010020-58 = "それでは使いものにならないではないか。"
70010020-6 = "質問が多すぎますわ！これではキリがありません！"
70010020-60 = "……溶鉱炉にでも入れて、リサイクルするか。"
70010020-61 = "はい！？"
70010020-63 = "ちょうど出版部から、活字用の金属が足りないと聞いていてな。"
70010020-64 = "もう少し待って、それでも反応が無ければ溶かすとしよう！"
70010020-68 = "メルリーさん！いや、メルリー様！！"
70010020-69 = "いやはや、文人は活字を残す、と言われていますが……#n身体ごと活字になってしまいそうですねぇ……ぐぇぇ……。"
70010020-7 = "それはそれとして……ミノリさん、全ての質問に答えていませんか！？"
70010020-70 = "大ピンチの前では、ヤクモ部長も取り乱すんですね……。"
70010020-72 = "あーもう、分かったよ！ミノリ、ペン貸して！早く！！"
70010020-73 = "あたしは大丈夫だ。革命家には、毅然とした最期こそ相応しい。"
70010020-74 = "意志を貫いた同志メルと歩みを共にでき……光栄だった。"
70010020-75 = "なに受け入れてんの！！早く！！ペン渡しなって！！！"
70010020-78 = "おおっ！出た！"
70010020-8 = "うん？あたしか？"
70010020-82 = "なっ……素晴らしい出来ではないか！"
70010020-84 = "（[ruby=ひめき]姫木[/ruby]メル……絵の代金は、後払いで必ず……）"
70010020-85 = "（本当に……ありがとう……！）"
70010020-86 = "ふむ……ちょっと不自然な感じもするが……#nこれがコンピューターの限界なのだろうか。"
70010020-9 = "分からないものは適当に答えているが。"
70010020-90 = "まあ、所詮はこんなもの――"
70010020-96 = "ドーン！！ドーン！！"
70010020-97 = "なんだ？"
70010020-98 = "でぃ、ディスクを読み込む音です！"
