[translation]
80000126-1 = "三種の神器"
80000126-4 = "こんにちは、先生っ！"
80000126-5 = "[s] \"や、レイ。どうしたの？\""
80000126-6 = "それはですね、えっと……。"
80000126-7 = "…………。"
80000126-10 = "（うぅっ……覚悟したはずなのに！何度もトレーニングしてきたのに……！）"
80000126-11 = "（先生の前だと、勇気がっ……！！）"
80000126-12 = "（やっぱりイメトレじゃ……今日はもう、挨拶だけして帰――）"
80000126-13 = "（いやいや！いくら何でもそれは！）"
80000126-16 = "[ns] \"レイ？\""
80000126-17 = "っ……！"
80000126-18 = "えっと、その……あ、アレですよ、アレ。今日はその、アレじゃないですか？"
80000126-19 = "[s] \"アレ……？\""
80000126-20 = "っ、ば、バっ……！"
80000126-21 = "バレンタインデー、ですっ！"
80000126-22 = "ご、ごめんなさいっ！#nつい声が……うぅ。"
80000126-23 = "そ、それで……こ、こちらを、作ってみたんですが……。"
80000126-24 = "受け取ってもらえると、嬉しいですっ！"
80000126-25 = "（チョコレートでできたグローブ？を受け取った）"
80000126-30 = "ど、どうにかやりました……。"
80000126-31 = "[s1] \"すごい、グローブの形だ！\"\n[s2] \"ありがとう、大切に食べるね。\""
80000126-36 = "！！！"
80000126-37 = "いえ、こちらこそありがとうございます！"
80000126-38 = "……？#nあ、このチョコ、ですか……？"
80000126-39 = "それは何と言いますか……。"
80000126-40 = " 自分で作ったと、言えなくもないような……？"
80000126-42 = "（気になるので、詳しく聞いてみることにする）"
80000126-45 = "このグローブ……私が前に使ってたものと、同じ型なんです。"
80000126-46 = "それをスキャンして、処理をしたデータを……。"
80000126-47 = "プリンターで出力したんです。"
80000126-48 = "つまりその、型を自分で作ったわけでは、ないのですが……。"
80000126-49 = "一応……あとの処理は、自分で。"
80000126-50 = "あ、でもチョコを溶かしたのと、ちゃんとピカピカに磨いたのは自分です……！"
80000126-51 = "まぁ、それだけと言えばそれだけで……。"
80000126-52 = "これで手作りと言えるのか……。"
80000126-53 = "[s3] \"そこまで手の込んだチョコ、本当にありがとね。\"\n[s4] \"れっきとした「手」作りだよ。\""
80000126-56 = "そう、ですか……？"
80000126-57 = "へへっ……。"
80000126-58 = "あ、実はそれから、こういうものもありまして！"
80000126-63 = "[ns] \"バットに、ボールまで……！\""
80000126-64 = "野球における、三種の神器ですから！"
80000126-65 = "実際に野球……とはいかずとも、これで雰囲気はバッチリです！"
80000126-66 = "さぁ先生、ピッチャーをお願いします……！"
80000126-67 = "野正レイ選手、大振りの構えから……ヒット！#n打球はショートの上を越えていきました！！"
80000126-68 = "野正選手、速い！二塁まで行けるかっ！？#nおぉっと、ピッチャーの先生が迫りくる！"
80000126-70 = "（その後二人で、三種の神器を美味しく食べた）"
80000126-71 = "（チョコを頬張るレイは、ずっと目を輝かせながら野球の話をしてくれた）"
