[translation]
80000128-1 = "意外なプレゼント"
80000128-2 = "（いつも通り、作業をしていた時……）"
80000128-3 = "[ns] \"疲れたな……。\""
80000128-5 = "先生、いるー？"
80000128-10 = "お、いるじゃーん。"
80000128-11 = "[s] \"あっ、ノゾミ……。\""
80000128-12 = "パヒャヒャッ、なんか死にかけ？"
80000128-13 = "ま、どうせそんなことだろうと思ったけど。"
80000128-14 = "というわけで……。"
80000128-15 = "はい、これ。"
80000128-20 = "大したものじゃないけど、疲労回復に効くらしいよ。"
80000128-21 = "チョコはもうもらってるだろうし、どうせ仕事で忙しくしてるんじゃないかなって……。"
80000128-22 = "それならグミの方が食べやすいよね、パヒャ！"
80000128-23 = "[ns] \"ノゾミ……っ！\""
80000128-25 = "うわっ、何その顔。"
80000128-26 = "感動したーって、顔に書いてあるよ？"
80000128-27 = "別にそれ、私の手作りとかじゃないんだけど？"
80000128-28 = "パヒャッ！#n先生って、意外とこういうのに弱いよね。"
80000128-29 = "じゃ、ちゃんと食べてよ？"
80000128-30 = "ついでにちょっと寄っただけだし、もう行くね。"
80000128-31 = "もう少しサボってもいいかなーって思ったけど、今日も忙しそうだし。"
80000128-32 = "え？まだいていいの？"
80000128-36 = "なに？#n一緒に遊んでくれる感じ？"
80000128-37 = "[s] \"仕事なら、いつでもできるからね！\""
80000128-38 = "パヒャヒャッ！そうこなくっちゃ！"
80000128-43 = "よーし、それじゃ……。"
80000128-44 = "……何して遊ぼっか？"
80000128-46 = "（仕事のことは忘れて、ノゾミと全力で遊んだ）"
80000128-47 = "（ノゾミはその後ストレス解消のお礼に、遅くまで仕事を手伝ってくれた）"
