[translation]
80000127-1 = "ガール・アンド・スナック"
80000127-4 = "シャーレにとーちゃーく。"
80000127-5 = "[s] \"あれ。ヒカリ、今日の当番だっけ？\""
80000127-6 = "のんのん。"
80000127-7 = "今日は、大好きな人にお菓子をあげる日ー。"
80000127-8 = "だから会いに来たー。"
80000127-9 = "[s] \"涙で前が見えない……。\""
80000127-14 = "はい、これー。"
80000127-15 = "ちょー最新、フレーミングコンポジションC型chocoボール。"
80000127-16 = "すごいでしょー？#n気になってたやつ見つけたの、ラッキー。"
80000127-17 = "これで今日のヒカリは、無敵モード。"
80000127-18 = "とにかく食べてみてー、はい。"
80000127-22 = "[ns1] \"カッコイイ……ヒカリ、ありがとう！\"\n[ns2] （chocoボールを受け取った）"
80000127-31 = "[ns] \"……。\""
80000127-33 = "[ns3] \"ひとりで食べるのは勿体ないし……。\"\n[ns4] \"誰か一緒に食べてほしいなぁ。\""
80000127-37 = "[ns] \"ヒカリ、手伝ってくれる？\""
80000127-38 = "えっ……！？"
80000127-43 = "うん！"
80000127-45 = "（ヒカリと一緒に、新商品のチョコレートを食べた）"
80000127-46 = "（あまりの酸味に顔をしかめていると、それを見たヒカリはとても楽しそうに笑ってくれたのだった）"
