[translation]
80000131-1 = "少女は箱を開けぬまま"
80000131-103 = "……一つだけ、お願いしても？"
80000131-104 = "そのチョコの味、忘れないでいてもらえます？"
80000131-108 = "[ns] \"……うん、分かったよ。\""
80000131-110 = "[ns9] \"確か、陰陽部にはキッチンがあるよね？\"\n[ns10] \"少し借りてもいい？\""
80000131-113 = "それは構いませんが……いったい何を？"
80000131-114 = "[s11] \"ニヤの考えは分かったけど……。\"\n[s12] \"それはそうとして、このチョコレート……。\""
80000131-120 = "[ns] \"ニヤにも食べてもらおうかな！！\""
80000131-121 = "そんなぁっ！？"
80000131-123 = "（残っていたヨモギを見つけて、ニヤのためにチョコレートを作った）"
80000131-124 = "（しかし分量を間違えて作り過ぎてしまい、結局は二人で食べることに）"
80000131-125 = "（そのチョコはやはり、とても苦かった……）"
80000131-13 = "[log=니야]陰陽部部長、天地ニヤより[/log]"
80000131-20 = "――という連絡から、1日と経っていないのに。"
80000131-21 = "こんなに早くお越しいただけるなんて。"
80000131-22 = "やっぱり、先生は頼りになりますねぇ。"
80000131-23 = "……実は私に会いたくて仕方なかったから、とか？"
80000131-24 = "…………。"
80000131-25 = "にゃはっ、閑話休題。"
80000131-26 = "私たちの間柄で、今さら探り合いをしてもねぇ。"
80000131-27 = "言わずとも分かってるでしょう？#n安心してください、それで正解ですから。"
80000131-28 = "では、どうぞ……気持ちばかりですが。"
80000131-29 = "[s1] \"す、すごく高そうな……！？\"\n[s2] \"これが粗品……！？\""
80000131-3 = "[log=니야]親愛なる先生へ[/log]"
80000131-32 = "まぁまぁ、それはお約束というやつで。"
80000131-33 = "日頃のお礼だと思ってもらえればと。"
80000131-34 = "バレンタインを口実にしたかっただけですよ。"
80000131-35 = "あぁ、中身はしっかりチョコレートですよ？"
80000131-36 = "そうですねぇ……せっかくですし、ここで開けてみては？"
80000131-37 = "よし、そうしましょ。さあさあさあ♪"
80000131-42 = "……どうです？"
80000131-43 = "本当に、ただのチョコレートだったでしょう？"
80000131-44 = "……もしかして、ガッカリしました？"
80000131-48 = "[ns3] \"大事な生徒からの贈り物で、ガッカリなんてしないよ。\"\n[ns4] \"こういうの、ニヤらしいなと思って。\""
80000131-5 = "[log=니야]ご無沙汰しております[/log]"
80000131-51 = "にゃはっ！#nそれはそれは、素敵な心意気ですねぇ。"
80000131-52 = "せっかくですし、お味の評価も頂いても？"
80000131-53 = "……今、ここで。"
80000131-54 = "先生なら、可愛い生徒のお願いをまさか……ねぇ？"
80000131-55 = "[s5] \"それはもちろん。\"\n[s6] チョコレートを口に運ぶ。"
80000131-61 = "あら……一切の躊躇なしと。"
80000131-62 = "ちなみにそれ、実は手作りなんですよぉ？"
80000131-63 = "可愛い生徒の、手作りチョコレート。"
80000131-64 = "お気に召しましたか？"
80000131-68 = "……にゃは。到底嬉しそうには見えませんねぇ。"
80000131-69 = "まぁ、さもありなん。#nダークチョコレートにヨモギをた～っぷり入れましたから、#n相当苦いでしょうねぇ。"
80000131-7 = "[log=니야]この度はお伝えしたいことがあり、ご連絡いたしました[/log]"
80000131-70 = "[s7] \"ちゃんと説明してほしいんだけど……。\"\n[s8] \"な、何でこんなことを……！？\""
80000131-73 = "きっちりしっかりご説明しましょう。"
80000131-74 = "それは先生が……とても良い方だからですよ。 "
80000131-78 = "おや……納得いかないご様子。"
80000131-79 = "では、直截に聞くとしましょう。"
80000131-80 = "生徒からどう思われているのか、先生は考えたことがおありですか？"
80000131-81 = "私以外からもきっと、たくさんチョコレートをもらいましたよねぇ？"
80000131-82 = "……先生ほどの方なら、それはもう。"
80000131-87 = "誰にでも優しく、気さくで、どんな問題も解決してくれる。"
80000131-88 = "――まるで、このチョコレートボックスのように。"
80000131-89 = "しかし、本当にそうでしょうか？#n生徒からの期待に対し、先生は永久に完璧に、応え続けられるのでしょうか？"
80000131-9 = "[log=니야]いつも通り、陰陽部の部室でお待ちしております[/log]"
80000131-90 = "にゃはっ……いくら何でも、難しいのでは？#n先生とはいえ、所詮はひとりの人間に過ぎません。"
80000131-91 = "ですがうら若き少女たちは、ついつい忘れてしまうもの。#n表面だけを見て勘違いを重ね、期待をしてしまうもの……。"
80000131-92 = "チョコレートを手に取り、甘い夢を見ることでしょう。"
80000131-93 = "……その果てに、どれだけ苦い経験があるとも知らずに。"
80000131-94 = "……いえ、責めるつもりなど毛頭ありませんよ？"
80000131-95 = "先生は、とっても良い方ですから。#n私と違って、裏など無いでしょうし？"
80000131-96 = "ですが、私はこういう生徒なので。"
80000131-97 = "苦いチョコは好みません、っと……にゃはは。"
