[translation]
80000136-1 = "ボクの！"
80000136-11 = "（あれは、もしかして……）"
80000136-12 = "[ns] \"……リツ？\""
80000136-13 = "だいせいかーい！"
80000136-14 = "先生のために、サプライズチョコレート！"
80000136-15 = "ハッピーバレンタインだよっ、先生！"
80000136-16 = "[s] \"ありがとう、リツ。\""
80000136-17 = "へへっ。"
80000136-18 = "っていうか、よく分かったね？"
80000136-19 = "どうしてボクのだと思ったの？"
80000136-2 = "シャーレ・オフィス"
80000136-20 = "[ns] \"なんたって私は、先生だからね。\""
80000136-25 = "[ns] \"……あのチョコレート、どうやって保管しよう。\""
80000136-26 = "それについては大丈夫！"
80000136-27 = "心配ご無用だよ、先生！"
80000136-28 = "[s] \"どういうこと？\""
80000136-29 = "冷蔵庫に入れなくても良いの。"
80000136-3 = "（シャーレに戻ると、見慣れないオブジェが目に飛び込んで来た）"
80000136-30 = "たとえどれだけ暑い夏が来てもOK！"
80000136-31 = "なにせあのチョコ――"
80000136-32 = "絶対に溶けないから！"
80000136-33 = "[s1] \"どういうこと！？\"\n[s2] \"謎技術……！？\""
80000136-36 = "触ってみればわかるよ！ほら、先生！"
80000136-37 = "（促されるまま、慎重に触れてみると……）"
80000136-38 = "[ns] \"こ、これは……！\""
80000136-39 = "ふふっ……そういうこと！"
80000136-40 = "[s] \"なるほど、そりゃ溶けないわけだ。\""
80000136-44 = "[ns] \"石で作ったチョコレー……ト？\""
80000136-45 = "そう！#n茶色の大理石で作ったの！"
80000136-46 = "どうどう？びっくりした？"
80000136-47 = "[s3] \"二重にびっくりしたよ……。\"\n[s4] \"見た目じゃ石だって分からなかったし……。\""
80000136-50 = "へへ、褒められちゃった！"
80000136-51 = "……？あ、作り方？"
80000136-52 = "仕方ないなー、先生にだけ特別だよ？"
80000136-53 = "一から十まで説明してあげる！"
80000136-55 = "（こうして、チョコ（？）を観察しながら彫刻について教えてもらうことに）"
80000136-56 = "（それにしても……）"
80000136-59 = "[ns5] \"ここまでどうやって入ってきたの、リツ？\"\n[ns6] \"普通はセキュリティが作動するはずだけど……。\""
80000136-62 = "え？#n通気口から！"
80000136-67 = "（……リツが帰ってから、セキュリティを見直した）"
80000136-7 = "（……巨大なチョコレート、と思わしきものが）"
