[translation]
80000132-1 = "マスターのためにマナチャージ"
80000132-100 = "……マスターは、いつも忙しいですから。"
80000132-101 = "食事すら取れずに、遅くまで仕事する日も多いと聞き……。"
80000132-102 = "うぅ、考えるだけで何だか悲しく……。"
80000132-103 = "なのでそういう夜には……#n私のことを思い出しながら、このチョコを食べてください！"
80000132-104 = "きっと、マナが湧き出るはずですから！"
80000132-105 = "[s1] \"エリの気持ちが染みていく……。\"\n[s2] \"今すぐ全部食べたい！\""
80000132-108 = "た、食べ過ぎはダメですよ！？"
80000132-109 = "マナの補給も、過剰になると良くないですから。"
80000132-110 = "[ns] \"確かに、気をつけるね。\""
80000132-112 = "[ns] \"エリも一緒に食べない？\""
80000132-115 = "ま、マスターからの逆マナ供給……！？"
80000132-116 = "確かに相互チャージをすれば、結果として倍以上の効果があるはず！"
80000132-117 = "では……お願いします、マスター！"
80000132-119 = "（その後もエリと一緒に、魔力に満ちた時間を過ごした）"
80000132-12 = "ひと気のない空き地"
80000132-14 = "あっ、マスター！#n早かったですね！"
80000132-15 = "[s] \"こんな場所に呼んで、どうしたの？\""
80000132-16 = "……ここなら、マナの共鳴を最大化できますから。"
80000132-17 = "人がいる場所では、その……魔力が干渉してしまいますし……。"
80000132-18 = "[s] \"……？二人きりで会いたかったってこと？\""
80000132-19 = "そ、そうです！"
80000132-2 = "（今朝、エリから連絡があり――）"
80000132-20 = "流石はマスター、鋭いですね。"
80000132-21 = "というわけで、二人っきりですし……！"
80000132-22 = "……脱いでも、良いですよね？"
80000132-23 = "[s] \"……んん！？\" "
80000132-24 = "私の覚悟、マスターに見てほしいんです。"
80000132-25 = "……ええいっ！！！"
80000132-30 = "ひゃあぁぁっ……！"
80000132-39 = "い、いくらマスターのためとはいえ、外でだなんて……や、やっぱり恥ずかしいですね。"
80000132-40 = "[s] \"……え？\""
80000132-41 = "す、すみません、変ですよね！分かってはいるのですが……！"
80000132-42 = "私にとっては、裸になるのとあまり変わらないので……。"
80000132-43 = "オカ研のみんなの前で練習した時は、平気だったんですけど……。"
80000132-44 = "[s] \"み、みんなの前なら恥ずかしくないの？\""
80000132-45 = "まぁ、一緒にお風呂入ったりしますし……。"
80000132-46 = "なので、帽子を取っても別に……。"
80000132-47 = "同じこと、と、言いますか……。"
80000132-48 = "……！？#nあ、いえ、だからと言ってどうこうという意味ではなく！"
80000132-49 = "[s] \"む、無理しないで！もう被って大丈夫だよ。\""
80000132-5 = "マスター！今日、学院に来るんですよね？"
80000132-50 = "で、ですが私も、覚悟を決めてきたんです……！"
80000132-51 = "効率の良いマナ共有には、この格好が最適……。"
80000132-52 = "……。"
80000132-53 = "だ、大丈夫です、ちゃんとできますので……！"
80000132-54 = "ふぅ……。"
80000132-55 = "で、では、マスター！"
80000132-6 = "実はお伝えしたいことがありまして！"
80000132-60 = "私のマナ……たっぷり込めました。"
80000132-61 = "今回は帽子に頼らず、自分の力で作ってみたので……。"
80000132-62 = "なので、帽子を被ったままでは良くないかもと思い……！"
80000132-63 = "……ま、マスター？"
80000132-64 = "[s] \"すごい、見てるだけで力が湧いてくるチョコだ……！\""
80000132-65 = "ほ、本当ですか？"
80000132-66 = "で、では、その……。"
80000132-67 = "「あーん」をしても、良いでしょうか……！？ "
80000132-68 = "[s] \"……なるほど、マナチャージだね！\""
80000132-69 = "は、はいっ！"
80000132-7 = "にゅふふっ！では、秘密の場所でお会いしましょう！"
80000132-70 = "この理解力……やっぱり、マスターはすごいです！"
80000132-71 = "ぼ、帽子無しで近づくのは、覚悟が要りますが……。"
80000132-72 = "すぅー……はぁー……#nい、いきますよ？"
80000132-73 = "[s] \"いつでも！\""
80000132-74 = "ではっ……！"
80000132-75 = "まずは、星のチョコレートを……！"
80000132-80 = "ど、どう……ですか？"
80000132-85 = "[ns] \"すごい、パチパチ弾けてる！\""
80000132-86 = "えへへっ……ポッピングキャンディを入れてみたんです！"
80000132-87 = "眠い時に食べると、目がパッチリするはずです！"
80000132-88 = "[s] \"ハートのチョコは何の味？\""
80000132-89 = "それは……食べてからのお楽しみ、です。"
80000132-9 = "（……そうしてワイルドハント芸術学院の、空き地へとやってきた）"
80000132-90 = "で、ではどうぞ……！"
80000132-94 = "[ns] \"こ、これは……！？\""
80000132-95 = "（甘くて……ちょっとだけ、酸味がある？）"
80000132-96 = "（まるで、マナが回復していくかのような感覚……！）"
80000132-97 = "ど、どうでしょうか？"
80000132-98 = "色々とビタミンを入れてみました。"
80000132-99 = "チョコでもあり、栄養剤でもあるわけです。"
