[translation]
80000129-1 = "I hate cheap chocolate"
80000129-7 = "……。"
80000129-8 = "先生～……いません、よね……？"
80000129-9 = "それならそれで、良かった、かも……。"
80000129-14 = "うぅ……こんなので、本当に大丈夫かな……。"
80000129-15 = "でも、きっと先生なら……。"
80000129-20 = "[ns] \"こんにちは、アオバ。\""
80000129-22 = "うわあっ！？#nせ、先生！？"
80000129-23 = "い、いつからそこに……！？"
80000129-24 = "え、最初から……？"
80000129-25 = "あ、ソファで横に……。#n全然気づきませんでした……。"
80000129-26 = "う、うぅ。#nそ、それではこれで……。"
80000129-27 = "[s1] \"もう行っちゃうの？\"\n[s2] \"もしかして、これって……。\""
80000129-34 = "あ、あぁっ……！"
80000129-38 = "えっと、その……。"
80000129-39 = "せ、先生には普段から、お世話になってるので……！"
80000129-40 = "今日はその、お礼をしなくてはと……！"
80000129-41 = "ただ、そんなもので良いのか不安になってしまい……。"
80000129-42 = "ほんとなら、自分で作ったり……#nもう少し手が込んだものを、差し上げたかったんですけど……。"
80000129-43 = "毎日残業で……帰る頃には、お店が閉まってまして……。"
80000129-44 = "すみません、結局こんな、安いお菓子に……。"
80000129-45 = "[ns] \"嬉しいよ、アオバ。\""
80000129-48 = "へっ！？"
80000129-49 = "こ、こんな、どこでも買えるようなやつですけど……！？"
80000129-50 = "[s3] \"それでも、アオバが用意してくれたものだから。\"\n[s4] \"その気持ちが嬉しいよ。\""
80000129-53 = "……。"
80000129-54 = "そ、そうですか……。"
80000129-55 = "……。"
80000129-56 = "……あ、ありがとうございます。"
80000129-57 = "[ns] \"ん……これ、手紙？\""
80000129-58 = "ひゃぁぁっ！！！"
80000129-59 = "そ、それは！#nダメです！今は！絶対！！"
80000129-60 = "後にしてください！！！"
80000129-61 = "[s] \"ご、ごめん……。\""
80000129-62 = "はぁ、はぁ……。"
80000129-69 = "で、では私は、これで……。"
80000129-70 = "ま、また……！"
80000129-75 = "[ns] \"アオバ。\""
80000129-79 = "ど、どうかしましたか！？"
80000129-80 = "[s] \"せっかくだし、ちょっと休んでいかない？\""
80000129-81 = "えっ……えっ！？"
80000129-82 = "……あ、いえ。#n別に、忙しいわけじゃない、ですけど……。"
80000129-83 = "ほ、本当に良いんですか……？"
80000129-84 = "「休める時に休むのも、仕事のうち」……？"
80000129-85 = "[s5] \"何だか疲れてるように見えたから。\"\n[s6] \"見てこのソファ、フカフカだよ！\""
80000129-88 = "う、うぅ……。"
80000129-89 = "確かに、ここ最近激務でしたが……。"
80000129-90 = "うーん…………。"
80000129-97 = "……ちょっとだけ、し、失礼します。"
80000129-99 = "（そうしてアオバは、遅くまでゆっくりしていった）"
80000129-100 = "い、いつも気にかけてくださって、ありがとうございます。"
80000129-101 = "おかげさまで……。"
80000129-102 = "明日も、明後日も頑張れるかもしれません。"
80000129-106 = "……その先も、きっと、ずっと。"
