[translation]
80000139-1 = "評論家のチョコケーキ"
80000139-2 = "バレンタインデーに関する、世間の評価をご存じですか？"
80000139-3 = "[s] \"色んな捉え方があるよね。\""
80000139-4 = "ええ。#n有名なのは、チョコレート会社の策略……という見方でしょう。"
80000139-5 = "感情や愛ですらも、資本主義の波には抗えないことの証明――#nそんな話もあります、が。"
80000139-6 = "[s] \"が……？\""
80000139-10 = "もう聞き飽きましたわっ！"
80000139-11 = "ありきたり過ぎて何とも思えません、もはやその言葉が形骸化しています！"
80000139-12 = "そもそも、思惑なんてどうでも良いのです。#n今日という日を楽しみ、チョコレートを分け合い……。"
80000139-13 = "日常の中に、つかの間の幸せを見出す――それこそが大切なのですから。"
80000139-14 = "[s1] \"なるほどね。\"\n[s2] \"慣習よりも寛容、なんだね。\""
80000139-17 = "当然ですわ。"
80000139-18 = "評論家は時代に寄り添うべき、ですから。"
80000139-19 = "人々が今、何を考え、何を求めているのか……。"
80000139-20 = "その感覚を研ぎ澄ませてこそ、#n評論家としての地盤が固まるのですもの。"
80000139-21 = "さて、アイスブレイクはこの辺にして……。"
80000139-22 = "どうぞ、こちらを。"
80000139-23 = "……実は作ってみたのです、私も。"
80000139-29 = "バレンタインの贈り物、ですわ。"
80000139-30 = "何を込め、どのように作るかによって、#n様々な解釈が可能となる象徴的なもの――"
80000139-31 = "全てが不確かでグレーゾーン、曖昧さの中にあるそれは……。"
80000139-32 = "……なればこそ、気持ちを再確認できるものなのでしょう。"
80000139-33 = "どうぞ、お受け取りください。#n人生とはまるでチョコレートの箱のよう、という言葉を添えて。"
80000139-34 = "[s3] \"様々な解釈が可能……。\"\n[s4] \"……タカネの本音は、教えてもらえないってこと？\""
80000139-37 = "……っ！"
80000139-38 = "せ、先生はいつもそうやって！"
80000139-39 = "そうやって、曖昧さを……曖昧な言葉で。"
80000139-40 = "……皆さんが本音を隠すのも、分かってしまいます。"
80000139-41 = "ですから……私のことはいっそ、誤解してくださった方が……！"
80000139-42 = "[s] \"……ん？あ、ごめん、ずっとチョコ見てた……。\""
80000139-43 = "好きに見れば良いではないですかっ！"
80000139-46 = "[ns] \"チョコレートケーキ……かな？\""
80000139-47 = "はい。カルトーシュカと呼ばれる、チョコレートケーキです。"
80000139-48 = "ご覧になるのは初めてですか？"
80000139-49 = "それも不思議ではありません。#nレッドウィンター以外ではあまり見られませんから。"
80000139-50 = "どのケーキにも支持者はいるものですが……#n私は、カルトーシュカこそ至高だと思っているのです。"
80000139-51 = "糖蜜を使ったお菓子を、粉末状に細かく砕き……。"
80000139-52 = "レッドウィンターではその上に、練乳や砂糖、カカオ、シナモンなどを混ぜて作ります。"
80000139-53 = "[s] \"すごく手が込んでるんだね。\""
80000139-54 = "大したことではありません。"
80000139-55 = "作ってみたら、意外と簡単でしたわ。"
80000139-56 = "偶然お店でカルトーシュカを見かけて……先生のことを、思い出したのです。"
80000139-57 = "[s] \"私を……？\""
80000139-58 = "ええ。それが何故なのかと考えながら、作ってみようかと。"
80000139-59 = "……。"
80000139-60 = "糖蜜とは、砂糖を作る時に生まれる副産物です。"
80000139-61 = "黒くてどろっとしていますし、砂糖ほどの甘さは残っていません。"
80000139-62 = "なので、砂糖ほどの需要はありません。#n当然、使い方にも工夫が必要になってきます。"
80000139-63 = "しかし、そんな糖蜜も……。"
80000139-64 = "こうして素敵なお菓子へと、生まれ変わることができるのです。"
80000139-65 = "作っている途中……先生のことを思い出した理由が、分かりましたわ。"
80000139-66 = "……。"
80000139-67 = "先生もまた、生徒のあらゆる可能性を見出してくださいますから。"
80000139-68 = "[ns5] （すごく嬉しいけど……）\n[ns6] （買い被り過ぎのような！？）"
80000139-71 = "そんな神妙な顔をして、どうされましたか？"
80000139-72 = "……。"
80000139-73 = "……あ。"
80000139-74 = "ああもうっ、申し訳ありませんっ！#nいつも長くて回りくどくて返事に困るような話ばっかりでっ！"
80000139-75 = "うぅ……気を付けていたのに……。#nどうして私はこう……。"
80000139-76 = "[s7] \"だ、大丈夫！そんなこと思ってないから！\"\n[s8] \"評論家のタカネらしくて良いと思うよ！\""
80000139-79 = "……本当、ですか？"
80000139-80 = "[s9] \"うん、興味深い考察だったよ。\"\n[s10] \"タカネが私を理解しようとしてくれてることも、すごく嬉しい。\""
80000139-83 = "……。"
80000139-84 = "ふふっ。"
80000139-85 = "ありがとうございます、先生。"
80000139-86 = "では、私と一緒に食べていただけませんか？"
80000139-87 = "せっかくですから、お茶もご用意してきますね。"
80000139-89 = "（タカネと一緒にカルトーシュカを食べた）"
80000139-90 = "（ふんわりとした、独特な香りが感じられる絶品のケーキだった）"
