[translation]
80000135-1 = "それは甘くてハードな"
80000135-103 = "……よし、帰ろう！今すぐ帰ろう！鉢合わせる前に！"
80000135-15 = "（そうしてフユは鞄の中を見せてくれた）"
80000135-16 = "（怪しげな球状のブツが、個包装でぎっしり入っている）"
80000135-17 = "[ns] \"これは……？\""
80000135-18 = "ふふっ、見ての通り……。"
80000135-19 = "[s] \"爆弾？\""
80000135-2 = "シャーレ・オフィス"
80000135-20 = "はい、その通――"
80000135-21 = "じゃなくて！#nキャンディですよ、キャンディ！"
80000135-22 = "特殊交易部を何だと思ってるんですか！？"
80000135-23 = "……そもそも、爆発物は儲からないんですよ。#n依頼件数も少ないですし。"
80000135-24 = "[s] \"そうなんだ……。\""
80000135-25 = "ええ。家庭用の弾薬と手榴弾さえあれば、簡単に作れますし。"
80000135-26 = "[s] \"ところで、このキャンディは一体……？\""
80000135-27 = "これはゴブストッパーと言いまして。 "
80000135-28 = "99%が砂糖で作られている、ただのキャンディ……。"
80000135-29 = "しかし、とても「ハード」なことで知られてます。"
80000135-30 = "溶かした砂糖を何層にも重ねているため、とても硬いんですよ。"
80000135-31 = "……それが理由で、取引が禁止されるくらいに。"
80000135-32 = "[s] \"それまたどうして……？\""
80000135-33 = "ええ。キャンディを噛んで食べた生徒の歯が折れてしまった、という例が。"
80000135-34 = "それで寮監隊は、取り扱いを禁止に。"
80000135-35 = "[s] \"なるほど……。\""
80000135-36 = "ですが、舐める分には長時間楽しめるキャンディです。何かに集中したい時なんかにピッタリで、需要があるんですよ。"
80000135-37 = "おかげで我々も懐が暖かく……っと、そうじゃなくて……。"
80000135-4 = "お久しぶりですね、先生！"
80000135-42 = "……先生、こちらをどうぞ。"
80000135-44 = "（一番大きなキャンディをくれた）"
80000135-45 = "（……野球ボールくらいある）"
80000135-47 = "[ns] \"これは……？\""
80000135-48 = "最初に言ったでしょう？#n良いモノを持ってきた、と。 "
80000135-49 = "限定版で特大サイズになっている、チョコのゴブストッパーです。"
80000135-5 = "ところで今日は、良いモノをお持ちしまして！"
80000135-50 = "その、今日は……バレンタインデー、ですし？"
80000135-51 = "[s] \"ありがとう、フユ……！\""
80000135-52 = "……ふふっ。"
80000135-53 = "[s1] \"それにしてもこの大きさ……。\"\n[s2] \"ハンマーか何かで……。\""
80000135-56 = "いえ、それには及びません。"
80000135-6 = "[s] \"もしかして、取引の帰り……？\""
80000135-60 = "[ns] \"銃……？\""
80000135-62 = "バァン！"
80000135-66 = "さあ、どうぞお召し上がりください！"
80000135-67 = "[s] \"あ、ありがとう……。\""
80000135-69 = "（ひとつ、口に含んでみると……）"
80000135-7 = "取引と言いますか、依頼品の手配に行ってきまして。"
80000135-70 = "（想像以上の味だった）"
80000135-71 = "[ns] \"美味しい……！\""
80000135-72 = "そうでしょう？"
80000135-73 = "限定版なので、いつも以上に力を入れてるそうです！"
80000135-74 = "[s] \"フユも一緒に食べない？\""
80000135-79 = "っ……！は、はい！"
80000135-8 = "ですが、今日は楽な方です。1種類だけでしたから。 "
80000135-81 = "……なるほど。確かに、これは美味しいですね。"
80000135-82 = "[s] \"なかなか食べ終わらずに済みそうだね。\""
80000135-83 = "ええ、甘い時間がずっと続くでしょう。"
80000135-84 = "……その間は。私のこと、考えててくれますよね？"
80000135-88 = "おっと、もうこんな時間に！では、失礼します！"
80000135-9 = "さぁ先生、ご覧ください。"
80000135-95 = "……。"
80000135-96 = "うあぁぁぁぁぁ……！"
80000135-97 = "我ながら、なんて恥ずかしい台詞を……！"
80000135-98 = "……うぅ。"
80000135-99 = "まぁ、やらない後悔よりは……。"
