[translation]
80000130-1 = "冷たい指先は"
80000130-6 = "あ、先生。 "
80000130-7 = "シャーレにいたんだ、良かった。"
80000130-8 = "[s1] \"こんにちは、ナグサ。\"\n[s2] \"今日は当番じゃなかった気がするけど、どうかした？\""
80000130-11 = "今日はバレンタインデー。"
80000130-12 = "見回りをしていたら、自然と情報が入ってきた。"
80000130-13 = "はい、チョコレート。#nこれを渡したくて。"
80000130-14 = "[s3] \"ナグサのチョコレート……！\"\n[s4] \"わざわざ来てくれてありがとう、嬉しいよ。\""
80000130-17 = "そんな……大したものじゃないし。"
80000130-18 = "先生には助けてもらってばかりだから、#nずっとお礼がしたかった。"
80000130-19 = "けど、何でもない日に気持ちを伝えるのは、どこか面映ゆいから……。"
80000130-20 = "だからこそ、こういう日はありがたい。"
80000130-21 = "[s] \"確かに、そうだね。\""
80000130-25 = "[ns] \"あれ、何だか見覚えがあるような……。\""
80000130-28 = "百鬼夜行自治区限定の、特製チョコクッキー。#nどこかのお店で、見たことあるかも。"
80000130-29 = "エビス産の乳製品を使った、甘くて優しいホワイトチョコでコーティングされてるの。"
80000130-30 = "一番好きなお菓子なんだけど、何故か[ruby=みんな]百花繚乱[/ruby]はあまり食べなくて。"
80000130-31 = "買っておいても、いつも私が一人で食べてる。"
80000130-32 = "[s] \"そうなの？じゃあ、一口……。\""
80000130-37 = "[ns5] \"美味しい！\"\n[ns6] \"口に入れた瞬間チョコが溶けて、濃厚な味がする。\""
80000130-40 = "そう、私もそういうところが好き。"
80000130-41 = "良かったら、もっと食べて。"
80000130-42 = "[s] \"えっと、その前にちょっと……。\""
80000130-46 = "あっ……。"
80000130-47 = "あんまり、好きじゃなかった？"
80000130-48 = "ごめんなさい……#nみんなが食べない時点で、気づくべきだった。"
80000130-49 = "私はやっぱり、みんなと違うから……。"
80000130-50 = "[ns] \"ち、違うよ！そういう意味じゃなくて……！\""
80000130-52 = "[ns] \"その、書類を汚しちゃう前に、と思って……。\""
80000130-53 = "あっ……確かにこの「白い乙女」は、一瞬で溶けるようなチョコだから……。"
80000130-54 = "あれ……でも私は、今まで……。"
80000130-58 = "……あぁ、体温のせいかな。"
80000130-59 = "[s] \"体温？\""
80000130-60 = "うん……私、平熱が低いの。#nそのせいか手足が冷たいって、よく言われて。"
80000130-61 = "……だからみんなと違って、手が汚れなかったんだと思う。"
80000130-62 = "[s7] \"なるほど……。\"\n[s8] \"それはちょっと羨ましいかも。\""
80000130-65 = "ふふっ……。"
80000130-66 = "こういう時くらいしか、役に立たないけどね……。"
80000130-67 = "暑さにも弱いし……隣にいる誰かに、上手く熱も伝わらない。"
80000130-68 = "……けど、知らなかった。良いところもあったんだね。"
80000130-69 = "[s9] \"もしナグサが良ければ……。\"\n[s10] \"それ、食べさせてくれない？\""
80000130-72 = "わ、私の手で、ってこと……？"
80000130-73 = "せ、先生が、気にしないなら……。"
80000130-78 = "はい、先生……あーん。"
80000130-83 = "[ns11] \"美味しい……。\"\n[ns12] \"脳が癒されていく……。\""
80000130-86 = "ふふっ、そう？"
80000130-87 = "……新しい長所、見つかった。"
80000130-89 = "（その後もナグサに手ずから食べさせてもらいながら、楽しい時間を過ごした）"
