[translation]
80000134-1 = "お預けティラミス"
80000134-2 = "（ミヨに招待されて、ワイルドハントの寮を訪ねた）"
80000134-3 = "（寮監隊の検問が緩くなるタイミングを事前に聞いていたため、いつもよりスムーズに入れた）"
80000134-4 = "特殊交易部の寮"
80000134-7 = "こんにちは、先生。"
80000134-8 = "[s] \"や、元気にしてた？\""
80000134-9 = "はい……小説の執筆は、あまり進んでいませんが……。"
80000134-10 = "密輸の作戦なら、すらすら浮かぶんですけどね……。"
80000134-11 = "[s] \"……？\""
80000134-12 = "あ、いえ……それより、すみません。 "
80000134-13 = "一時的だとは思うのですが、外出ルールが厳しくなってしまい……私から会いに行くのが、難しくて。"
80000134-14 = "[s] \"ううん。ミヨと会えるなら、いつでも来るよ！\""
80000134-15 = "ほ、本当ですか？#nふふっ……。 "
80000134-16 = "[s] \"断ったら、攫われるかもしれないし……。\""
80000134-17 = "なっ……！#nそ、そんな物騒なことはしません！"
80000134-18 = "確かにやろうと思えば可能ですが……いざそうなったら、まず色々な変数を計算して……。"
80000134-22 = "……じゃなくて！#n私はそんなことしませんから！"
80000134-23 = "うぅ……。"
80000134-24 = "[s] \"ところで、それは……？\""
80000134-25 = "あっ、これは……。"
80000134-26 = "……ティラミス、です。"
80000134-27 = "[s] \"もしかして……作ってる途中、だった？\""
80000134-28 = "お、お恥ずかしいです……。"
80000134-29 = "本当なら、この時間には完成してるはずだったのですが……。"
80000134-30 = "初めての手作り、ということもあり……。"
80000134-31 = "[s] \"じゃあ、一緒に作る？\""
80000134-32 = "そ、そういうわけには……！ "
80000134-33 = "それに、もうほとんど完成してますし！"
80000134-34 = "もうあとは、ココアパウダーを振れば……！"
80000134-35 = "それで完、成……。"
80000134-38 = "[greeting][greeting][サッサッと何かを振るようなSFX]"
80000134-40 = "[…]"
80000134-41 = "……なんだか。"
80000134-42 = "[s] \"ん？\""
80000134-43 = "こうして真っ白なマスカルポーネに、黒いココアパウダーを振っていると……。"
80000134-44 = "まるで原稿用紙に、文章を書いてるようだな、と……。"
80000134-45 = "[s] \"確かに、そうかもね。\""
80000134-46 = "……時々、思うんです。"
80000134-47 = "執筆とは、紙を塗り潰していくことなのでは――と。それなら、私も……。"
80000134-48 = "……すみません、気にしないでください。 "
80000134-53 = "とにかく、これで……。"
80000134-57 = "完成です、先生！"
80000134-60 = "[ns] \"美味しそう！\""
80000134-61 = "ふふっ……ありがとうございます。"
80000134-62 = "あっ、えっと、その……。"
80000134-63 = "[s] \"どうかしたの？\""
80000134-69 = "ついさっき知ったのですが……#nティラミスは冷蔵庫で2時間ほど冷やすと、より美味しくなるそうです。"
80000134-70 = "そ、それで……。"
80000134-71 = "もし、先生さえよろしければ……。"
80000134-72 = "[s] \"2時間くらい余裕で待つよ！\""
80000134-73 = "ほ、本当ですか！？#nありがとうございます！"
80000134-74 = "では、すぐにお茶を入れてきますね。"
80000134-75 = "今日は、カモミールティーにしましょうか。"
80000134-77 = "（ミヨと話していたら、あっという間に2時間が経っていた）"
80000134-78 = "（積み重ねた時間の分、ティラミスはより美味しく感じられた）"
