[translation]
80000138-1 = "チョコメレンゲクッキー"
80000138-10 = "噂の正体が、少しずつ分かってきました……。"
80000138-11 = "ふふっ、そんな顔しても無駄です。#n私は騙されませんから。"
80000138-12 = "それで、今日お呼び立てしたのは……。"
80000138-13 = "その……。"
80000138-14 = "……。"
80000138-15 = "お世話に、なっていますから。"
80000138-16 = "つまり……！"
80000138-17 = "[ns] \"ここ、良いカフェだね。\""
80000138-18 = "えっ？"
80000138-19 = "ああ、はい。そう、ですね。#n最近はこういうところにも慣れてきました。"
80000138-2 = "（待ち合わせの時間よりも、早めに到着した）"
80000138-20 = "アルバイトを頑張っているからなのか……。"
80000138-21 = "……言わなくても、分かってますよ。"
80000138-22 = "勉強も大事、でしょう？#nそういうところは先生なんですから。"
80000138-23 = "……とにかく！"
80000138-24 = "……。"
80000138-25 = "アルバイト中に聞いたんです。#n「外の世界」には、メレンゲクッキーというものがあると……。"
80000138-26 = "……ああ。また、つい。"
80000138-27 = "とにかく、卵白に砂糖を混ぜて、クリームのような泡を作り……。"
80000138-28 = "それを100℃くらいで熱したお菓子のようなのですが。"
80000138-29 = "……許せません！！！"
80000138-3 = "（何となく周囲を見回していると――）"
80000138-30 = "[s] \"な、なんで！？メレンゲに罪は……！\""
80000138-31 = "だって、残った卵黄は捨てると言うんですよ！#n罰当たりだと思いませんか！？"
80000138-32 = "[s] \"あー……。\""
80000138-33 = "ブランシールと呼ばれる卵黄を使う手法もあるそうですが、メレンゲに比べると使いどころが限られます。"
80000138-34 = "それに、卵白よりも早く傷んでしまうので……#n結局は使い切れず、捨てることになりやすいとか。"
80000138-35 = "卵黄にどんな罪があるというんですか……！#nそんな身勝手さ、許されてはいけません！"
80000138-36 = "たとえ食べ物の神様が許そうとも、私は許しませんから！！"
80000138-37 = "というわけで……廃棄されるはずの卵黄を貰っているんです。"
80000138-38 = "砂糖と醤油に漬けて、アリウスの子たちに食べてもらったり……色々と試していまして。"
80000138-39 = "にしても、酷いとは思いませんか？#n食べ物を粗末にするなんて、全く世も末です……！"
80000138-4 = "こんにちは、先生。"
80000138-40 = "[s] \"ま、まぁまぁ……！確かに食べ物は大事だよね！\""
80000138-41 = "ご理解いただき、ありがとうございます……#nあれ、何の話でしたっけ？"
80000138-42 = "……あぁ、メレンゲクッキーでしたね。"
80000138-43 = "……先生。"
80000138-47 = "「外の世界」……いえ。世間には、バレンタインデーというものがあると聞きました。"
80000138-48 = "その日は……。"
80000138-49 = "えっと……。"
80000138-5 = "……もしかして、待たせてしまいましたか？"
80000138-50 = "普段、お世話になっている人や……。"
80000138-51 = "自分の気持ちを伝えたい人に……。"
80000138-52 = "チョコレートを、プレゼントするんだとか。"
80000138-53 = "それで、その……私も、用意してみたんです……！"
80000138-58 = "[ns] \"すごい、こんなメレンゲクッキーが……！？\""
80000138-59 = "メレンゲを作る時に、パウダーなどを混ぜるんです。"
80000138-6 = "[s] \"ううん、今来たばっかりだから。\""
80000138-60 = "結局のところ私は、身体を使うほうが得意と言いますか……#nメレンゲを作るだけなら、ちょっとしたコツと、腕力さえあればいいので。"
80000138-61 = "私にもできるかな、と思い……。"
80000138-62 = "……もちろん、オーブンはアルバイト先から借りました。"
80000138-63 = "口に出してみると、なんとも情けない話ですが。"
80000138-64 = "……。"
80000138-65 = "やはりよくよく考えてみると……こんなものを、先生にお出しするわけには……！"
80000138-66 = "き、聞かなかったことにしてください！#nこれは、やはり……！"
80000138-7 = "「今」も何も……待ち合わせよりずいぶん早いですよ。"
80000138-73 = "（クッキーを手に取ろうとしたスバルを、急いで止めた）"
80000138-75 = "[ns1] \"「こんなもの」じゃないよ！\"\n[ns2] \"私はすごく嬉しい！\""
80000138-78 = "……本当、ですか？"
80000138-79 = "[s] \"本心だよ。\""
80000138-8 = "[s] \"その分スバルに、早く会えるかもなって思って！\""
80000138-80 = "食べた後で、文句なんて言わないでくださいよ？"
80000138-81 = "[s] \"言わないよ、絶対。\""
80000138-84 = "……分かりました。"
80000138-85 = "信じます。"
80000138-86 = "……ふふっ。"
80000138-88 = "（そうしてスバルとメレンゲクッキーを一緒に食べながら、#n優しい時間を過ごした）"
80000138-9 = "またそういうことを……。"
