[translation]
80000141-1 = "完璧な計画（仮）"
80000141-2 = "[ns] \"おはよう、ケイちゃん！\""
80000141-3 = "はぁ……。"
80000141-4 = "[s1] \"ため息！？\"\n[s2] \"そんなケイちゃんも良いね！\""
80000141-9 = "全く……。"
80000141-10 = "……。"
80000141-11 = "どうして私は……。"
80000141-12 = "……。"
80000141-13 = "……とにかく用事を済ませて、すぐ帰りますから。"
80000141-14 = "はい、どうぞ。"
80000141-20 = "[ns] \"こ、これは……！？\""
80000141-21 = "……さっき、その辺で拾いました。"
80000141-22 = "そして偶然シャーレが近かったので。"
80000141-23 = "バレンタインだからってまさか、手作りや高級チョコなんてものを期待してはいませんよね？"
80000141-24 = "あり得ません。#n先生には、拾った市販のチョコで十分です。"
80000141-25 = "（それでも嬉しいよ！と言おうとしたものの）"
80000141-26 = "（それでも嬉しいよ！と言おうとしたものの）"
80000141-27 = "（よく見てみると……）"
80000141-29 = "[ns] \"……ん？\""
80000141-30 = "ど、どうかしましたか？#nただの安いチョコなんですから、早く食べてしまってください。"
80000141-31 = "[ns] \"これ……。\""
80000141-33 = "[ns3] （お店の包装には見えないような？）\n[ns4] （チョコレートの形が、量産品とは思えないような……）\n[ns5] （市販品とはどこか違った香りが感じられる）"
80000141-39 = "（とにかく、チョコを口に入れてみた）"
80000141-43 = "……な、なんですか？"
80000141-44 = "[s] \"ありがとね、ケイちゃん。\""
80000141-45 = "い、いったい何の話でしょう。"
80000141-46 = "[ns] \"わざわざ作ってくれたんだ。\"\n[ns] \"すごく塩の主張が強くて……これはこれで美味しいね！\""
80000141-49 = "……？"
80000141-50 = "……！？！？"
80000141-51 = "はっ！？！？！？！？"
80000141-57 = "（ケイはダッシュして飛び込み、ソファのクッションに顔をうずめた）"
80000141-58 = "（何だかダチョウの動きみたいで可愛い）"
80000141-68 = "わ～っ！！！#nうわああああ～～～～っ！！！"
80000141-69 = "あ、あり得ませんあり得ません、あり得てはいけません！#nせめて味見さえしていれば……っ！！！"
80000141-70 = "と、途中まで完璧なっ！#n完璧な計画だったのにっ！！！"
80000141-72 = "[ns] \"えーっと……今からでも味見、してみる？\""
80000141-73 = "ちょっと黙っててください！！！"
80000141-80 = "（ケイは　ぜんりょくで　クッションを　なげた！）"
80000141-86 = "（せんせいは　ひっしに　よけた！）"
80000141-93 = "……返してください。"
80000141-94 = "[s] \"せっかくの手作りチョコなのに……。\""
80000141-95 = "良いから返しなさい！#n今度ちゃんとしたのをあげますから！！"
80000141-96 = "な、何でそれに固執するんですか、絶対美味しくないのに……。"
80000141-97 = "世界に一つだけ、だから……？"
80000141-101 = "！！！"
80000141-102 = "～～～～～っっ！！！"
80000141-109 = "（必死にケイから逃げつつ、もう一口食べた）"
80000141-111 = "[ns] \"勘違いしないで、ケイちゃん。本当に美味しいんだよ。\""
80000141-112 = "えっ……？"
80000141-113 = "[s] \"……塩は効いてるけど、それがまた良い。\""
80000141-114 = "今度こそ、先生を殺して――"
80000141-115 = "[s] \"まさか――\""
80000141-116 = "私も死にます！！！！！！"
80000141-129 = "もう話しかけないでください、嫌いです。"
80000141-130 = "……？"
80000141-131 = "違う、使い道……？"
80000141-132 = "それはどういう……。"
80000141-133 = "甘いものと食べると無限ループする……？"
80000141-134 = "外が暑いと塩分補給もできて一石二鳥……？"
80000141-135 = "……。"
80000141-136 = "それで慰めてるつもりですか！？！？"
80000141-137 = "……はぁ。"
80000141-141 = "……いえ、これは私のミスです。"
80000141-142 = "とにもかくにも、味見さえしていれば……！！"
80000141-143 = "[s] \"ありがとね、ケイ。\""
80000141-144 = "……何がですか。しょっぱいことがですか。"
80000141-145 = "[s] \"嬉しかったのは本当だから。\""
80000141-150 = "なら、許します……。"
80000141-151 = "……ふふっ。"
80000141-153 = "（隠していた甘いお菓子を取り出し、ケイと一緒に味わった）"
80000141-154 = "（予想以上の相性で、あっという間に平らげてしまった）"
80000141-160 = "（チョコはもちろんのこと……）"
80000141-166 = "（ケイの色んな表情を見られたことも、嬉しかった）"
