[translation]
80000140-1 = "チョコレートメドヴィク"
80000140-2 = "交渉の三原則、というものがあります。"
80000140-3 = "[s] \"一つ目は？\""
80000140-4 = "話を急ぎますねぇ。#nそういうところも好きなのですが……ムフフ。"
80000140-5 = "まず一つ目、それは「傾聴」です。"
80000140-6 = "[s] \"確かに、それは大切だよね。\""
80000140-7 = "はい、自分の言うことを聞いてもらえるように脅……#n誘導することは、重要ですからね。"
80000140-8 = "[s] \"……ん？\""
80000140-9 = "そして二つ目は「利益」です。#nこれもまた、常に大事なものでしょう？ "
80000140-10 = "「相互に利益がある」と、相手に思わせることはとても重要です。"
80000140-11 = "最後の三つ目は、「信頼」。 "
80000140-12 = "従わなくては、大変なことになる――そんな雰囲気作りが必要です。#nもし何かあっても、逃げられないように。"
80000140-13 = "[s] \"間違ってないかもだけど、それ「信頼」かなぁ！？\""
80000140-14 = "間違ってないなら、それはほとんど正解も同然なんですよ？"
80000140-15 = "ともかく、交渉には技術が求められるのです。"
80000140-16 = "常にギブアンドテイクのスタンスで接しなくては。"
80000140-17 = "というわけで、こちらをお持ちしました。"
80000140-23 = "[ns] \"チョコレートケーキ……？\""
80000140-24 = "チョコはチョコでも、メドヴィクと呼ばれるものです。 "
80000140-25 = "薄いスポンジの上にハチミツとクリームを塗り、スポンジを重ね……。"
80000140-26 = "それを何度も繰り返して作られる、レッドウィンターでは有名な一品です。"
80000140-27 = "これはスポンジもクリームも、チョコ味にしたものですが。"
80000140-28 = "ちなみに手作りですよぉ？#n商売の経験がある人なら、お察しの通りです……。"
80000140-29 = "バレンタインデーに、手作りチョコ。"
80000140-30 = "この意味、もちろん先生なら分かりますよねぇ……？#nムフフフフッ。"
80000140-31 = "[s] \"なるほど……。\""
80000140-32 = "余談ですが、私はこのメドヴィクが大好きです。"
80000140-33 = "いくつも重なっている層が、積まれた本のように見えるんですよねぇ。"
80000140-34 = "[s] \"ロマンチックな理由だね。\""
80000140-35 = "……あと、札束のようにも見えますしぃ？"
80000140-36 = "[s] \"……ヤクモっぽい理由だね。\""
80000140-37 = "とにかく。メドヴィクは私にとって、見ているだけで心を豊かにしてくれるケーキなのです。"
80000140-38 = "それに何度も言いますが、「手作り」ですよぉ？"
80000140-39 = "こんな日に、わざわざ大好きなケーキを……#nそれも私にとって戦場でもある、この印刷所で渡すなんて。"
80000140-40 = "どういう意味か、分からないとは言わせませんよぉ！#nムフフフ！"
80000140-41 = "[s] \"一つだけ質問なんだけど……。\""
80000140-42 = "はい～♪"
80000140-43 = "[s] \"「手作り」って……誰の手作り？\""
80000140-44 = "な、何のことですか……！？"
80000140-45 = "……え、普段の行い？"
80000140-46 = "まったく、ひどいですねぇ。#n何もそこまで……！"
80000140-47 = "そこまで……。"
80000140-48 = "……。"
80000140-49 = "先生……過去は忘れて、明るい未来を見ませんか？"
80000140-50 = "[s] \"ヤクモさん？多分あっちの方向に未来は無いよ？\""
80000140-51 = "……仕方ありませんねぇ。"
80000140-52 = "とはいえ、気持ちに偽りはなかったのですが……。"
80000140-53 = "それに嘘も、一切ついていません！"
80000140-54 = "言ったでしょう、「信頼」が大切だと？"
80000140-55 = "カフェのケーキも、手作りなことには変わりありませんし。"
80000140-56 = "実は最近……#n事務局の近くに新しくできたカフェが、広告を出したかったらしく……。"
80000140-57 = "それで、交渉をしたのですよ。"
80000140-58 = "――広告を安くする代わりに、サンプルをもらえないか、と。"
80000140-59 = "……私なりに、先生のことを思って動いたのですが。"
80000140-60 = "[s] \"なるほどね……ありがとう、ヤクモ。\""
80000140-61 = "ええ、そもそもバレンタインデーにチョコレートメドヴィクですよ？#nかなりの[ruby=利益]好感度[/ruby]が得られると思ったんです。"
80000140-62 = "[s] \"そこまで正直に話してくれてありがとう……。\""
80000140-63 = "もちろん、どこまで本心かは分かりませんが……？"
80000140-64 = "では、ゆっくりお楽しみください。#n狙いもバレてしまったことですし、邪魔な商売人はお暇させていただきます……ムフフ。"
80000140-69 = "せ、先生？#nなぜ帰してくれないんですか……！？"
80000140-70 = "い、一緒にと言われましても、これは先生のために用意したもので……。"
80000140-71 = "……まぁ、確かに。"
80000140-72 = "ここは私にとって、意味のある場所ですが……。"
80000140-73 = "そうは言っても、ムム……。"
80000140-74 = "……ほら、アレですよ。"
80000140-75 = "私にとってここは、お茶をする場所ではなく……。"
80000140-76 = "[s] \"場所を移せば良いってこと？\""
80000140-77 = "……えっ？"
80000140-78 = "あ、いえ、それはー……。"
80000140-79 = "……。"
80000140-80 = "はいはい、私の負けです。"
80000140-81 = "ご一緒するからにはしっかり、良いものをご馳走になりますからねぇ？#nムフフ。"
80000140-83 = "（そうしてヤクモと、新しいカフェへ向かった）"
80000140-88 = "（今日も愉快で元気の良いヤクモと……）"
80000140-89 = "（今日も愉快で元気の良いヤクモと……）"
80000140-90 = "（まったく退屈しない時間を過ごした）"
