[translation]
80000137-1 = "ラブ博物館に行かなくちゃ！"
80000137-10 = "……ん、良し。"
80000137-100 = "さてと……自販機でも探しに行こうかしら。"
80000137-106 = "あれ？#nチョコは……。"
80000137-11 = "あ、でもその前に髪の毛を……。"
80000137-110 = "さっきまで、たしか先生が……。"
80000137-111 = "……ぜ、全部持ってっちゃった！？"
80000137-12 = "[ns1] \"ラブ！\"\n[ns2] \"ラブだーーーーっ！\""
80000137-18 = "うわあっ！？#nビックリしたぁ！！"
80000137-19 = "やめてよね！#n奇襲かと思ったじゃない！？"
80000137-2 = "（シャーレで仕事をしていると、ラブの気配を感じた）"
80000137-20 = "って、何してんのよこんなとこで。仕事は？"
80000137-21 = "[s] \"ラブの気配を感じたから！\""
80000137-22 = "何それどうい……やっぱり良いわ、聞かない方が良さそう。#nというか、喜びすぎじゃない？"
80000137-23 = "まぁ、ちょうど良かったわ。"
80000137-24 = "こっちも渡したいものがあったから。"
80000137-25 = "[s3] \"手編みの帽子とか？\"\n[s4] \"交換日記とか？\"\n[s5] \"中学の卒業アルバムとか？\""
80000137-29 = "なんでそんな物を欲しがるのよ！？"
80000137-3 = "（あそこへ行ってみよう）"
80000137-30 = "今日が何の日か知らないわけ……？#nったく、どれだけ忙しいのよ。"
80000137-34 = "心配させな……じゃなくてはい、これ！"
80000137-35 = "コンビニで買ったやつだけど我慢して。"
80000137-36 = "手作りを渡すほどの余裕も、自信もなかったし……。"
80000137-37 = "さっき買った先生の分は、っと……これは私のだから……あむ……。"
80000137-41 = "んむっ、んん……ぇー、ろこにいっはおはひら……。"
80000137-46 = "……ん、はふぇっ？"
80000137-47 = "[s6] \"どこか痛めた！？\"\n[s7] \"熱！？\"\n[s8] \"お腹空いた！？\" "
80000137-5 = "シャーレ付近の路地裏"
80000137-51 = "あふぁっ、あふぉっ！！#nっ、チョコ咥えてんだから、返事できるわけないでしょ！"
80000137-52 = "二つ買ったはずなんだけど、見つからないのよ。"
80000137-53 = "さっき絡まれた時に、落としちゃったとか……？"
80000137-54 = "[s] \"大丈夫、気持ちだけでも嬉しいよ！\""
80000137-55 = "ダメよ、せっかくのバレンタインデーだもの。"
80000137-56 = "んー……。"
80000137-60 = "噛んじゃったけど、これ分けっこする感じでも良い？"
80000137-65 = "あっ、ちょっとうち手が汚れてるから、お願いできる？"
80000137-66 = "簡単にパキッと割れるはずだから。"
80000137-70 = "[ns] \"任せて！\""
80000137-71 = "あーあ……ちゃんと渡したかったのに。"
80000137-72 = "はい、てきとうに半分に割っ――"
80000137-78 = "……。"
80000137-79 = "仕事の連絡じゃないの？"
80000137-80 = "[s] \"あっ……本当だ。\""
80000137-84 = "ほら、早く行きなさいよ。"
80000137-85 = "誰かが困ってるんでしょう？"
80000137-86 = "[s] \"ごめんね、ラブ……また絶対、遊びに来て！\""
80000137-90 = "ああもう分かったから！#nちゃんと前向いて走りなさい！危ないでしょ！？"
80000137-97 = "……まったくもう。"
80000137-98 = "……次、か。"
80000137-99 = "まぁ、また時間ができた時にでも……。"
