[translation]
80000133-1 = "思い出す時まで"
80000133-10 = "私が連絡した理由……先生なら分かるよねぇ？"
80000133-100 = "さぁ、言ってみて……私はだぁれ？"
80000133-101 = "先生にとって……前世の私は、どんな存在？"
80000133-102 = "[ns5] \"か、可愛い子猫……！\"\n[ns6] \"お、お利口なカラス……！\""
80000133-106 = "……足りなかったかなぁ？"
80000133-107 = "それなら、思い出すまで食べてもらえば良いか……。"
80000133-108 = "こういうこともあると思って、たくさん作っておいたからぁ。"
80000133-11 = "先生と私は……運命の赤い糸で結ばれてるんだから……。"
80000133-110 = "（そうしてカノエとチョコマフィンを食べながら、楽しい時間を過ごしたが……）"
80000133-111 = "（……前世の記憶は思い出せなかった）"
80000133-117 = "大丈夫……。"
80000133-118 = "もう少し、もう少しで……。"
80000133-119 = "イヒッ……イヒヒヒッ！"
80000133-12 = "[s] \"もしかして……チョコレート？\""
80000133-13 = "……正解。"
80000133-14 = "それも普通のチョコレートじゃない、すごく可愛いチョコマフィンだよぉ……。"
80000133-15 = "特別な材料と、私の愛をたっぷり込めながら……釜で煮込んだの。"
80000133-16 = "どう、食べてみる……？"
80000133-17 = "[s] \"もちろん！カノエの手料理は美味しいからね。\""
80000133-18 = "……やっぱりその返事。"
80000133-19 = "イヒッ、イヒヒヒッ……！"
80000133-2 = "（シャーレで仕事をしていると……）"
80000133-20 = "[s1] \"あっ……でもこの後、外回りの仕事があって。\"\n[s2] \"戻る頃に合流して、ゆっくり食べても良いかな？\""
80000133-23 = "……今がいい。"
80000133-24 = "[s] \"30分くらいならあるけど、今から会いに行くと――\""
80000133-25 = "心配しないでぇ。"
80000133-26 = "そうだと思って……。"
80000133-27 = "ガァッ！ガァァッ……！"
80000133-28 = "[ns] \"こ、この音は……！？\""
80000133-34 = "……こうなるかと思って。"
80000133-35 = "イヒッ……これでも私、できる女だから。"
80000133-36 = "[s] \"い、いつの間に！？\""
80000133-37 = "そんなことより、今重要なのは……。"
80000133-38 = "……私と先生が、ここにいるってこと。"
80000133-39 = "さぁ、目を閉じて……？"
80000133-40 = "（その表情を前にして、カノエの言うことには抗えず……）"
80000133-41 = "（静かに目を閉じる）"
80000133-46 = "イヒッ、少し待っててぇ……。"
80000133-50 = "ガァッ！ガァァッ！"
80000133-53 = "ニャーオ！ンニャーオ！"
80000133-54 = "[ns] \"……鳴き声が増えたような。\""
80000133-55 = "匂いで集まっちゃったの……？"
80000133-56 = "これは特別な、先生にあげるマフィンだから……。"
80000133-57 = "今は出ていってねぇ……君たちの分は、また今度。"
80000133-63 = "どうぞぉ、先生。目、開けてみて？"
80000133-68 = "先生……。"
80000133-69 = "[ns3] \"な、何だか雰囲気が……。\"\n[ns4] \"可愛いカノエちゃんモード！？\""
80000133-7 = "ねぇ、先生……。"
80000133-72 = "はい……これ、私の気持ち。"
80000133-77 = "カノエ……どうしても先生に、チョコをあげたかったの。"
80000133-78 = "こうしていれば、きっと前世の記憶を思い出すはず。"
80000133-79 = "チョコを分け合った、あの思い出も……。"
80000133-8 = "[s] \"カノエ、どうしたの？\""
80000133-80 = "だから、早く食べて。"
80000133-81 = "私の、特別なマフィン……！"
80000133-82 = "[s] \"……！！\""
80000133-83 = "（何かに取り憑かれたかのように、カノエのチョコマフィンを頬張った）"
80000133-88 = "どう、美味しい……？"
80000133-89 = "[s] \"お、美味しすぎる……！\""
80000133-9 = "イヒヒ……。"
80000133-90 = "イヒッ……！"
80000133-91 = "流石は先生……喜んでくれると思った。"
80000133-96 = "……。"
80000133-97 = "……イヒ、イヒヒヒッ。"
80000133-98 = "私のを、取り込んでくれた……これで儀式は完了。"
80000133-99 = "これで先生は、ずっと私のもの……イヒヒヒッ！"
