[translation]
90002260-1 = "第26話;エピローグ（２）"
90002260-104 = "それで、これはいつから正式にプレイできますか？"
90002260-105 = "トキ……あなたはまた……。"
90002260-106 = "なにか問題でも？"
90002260-107 = "あなた、特異現象捜査部とC&Cの所属でしょう……？#n何でここにいるんですか……？"
90002260-108 = "ミレニアムは能力さえあれば、複数の部活を掛け持ちすることができますので。"
90002260-109 = "それに、ここは私の遊び場でもあります。"
90002260-111 = "遊び場……私たちはゲームを開発する部活なのに……。"
90002260-112 = "お姉ちゃんが言うと説得力あるね……。"
90002260-113 = "良いゲームを作るには、ゲームをたくさんプレイするべきなんだよ！"
90002260-114 = "はいはい。それもう100回は聞いたから……。"
90002260-116 = "そもそもトキ、あなたは趣味がなかったのでは？"
90002260-117 = "ないわけではありません。探しているだけです。"
90002260-118 = "それに最近はゲームやマンガ、ネット配信に[ruby=・]少[/ruby][ruby=・]し[/ruby]興味を持つようになりました。"
90002260-119 = "少し？その割には入り浸っているような……。"
90002260-12 = "ケイちゃん……ど、どうかな……。#n新作の『アークティック・アドベンチャー・ファイナル』……。"
90002260-125 = "（トキは自身の胸元をトントンと叩いた）"
90002260-127 = "鋼のメンタルには自信があります。ぶいっ。"
90002260-128 = "バカですか！？"
90002260-13 = "当然神ゲーだよね！なんてったって今回の経験を活かしたシナリオなんだから！"
90002260-130 = "バカではなく、メンタルです。"
90002260-131 = "ああもう――っ！"
90002260-133 = "け、ケイ！？倒れちゃダメです！"
90002260-134 = "今の話！次のシナリオにしよう！"
90002260-135 = "モモイ――！！！"
90002260-14 = "うん。アートリソースも十分確保できた。"
90002260-141 = "……。"
90002260-142 = "みんな楽しく過ごせて、アリスは嬉しいです！"
90002260-149 = "ここも久しぶりです。あ、リオは初めてですよね？"
90002260-150 = "ええ。ここで……すべての事をやっていたのね。"
90002260-151 = "様々な事件を経て、またここに戻ってきました。"
90002260-152 = "……ありがとう、ヒマリ。"
90002260-153 = "本当に。"
90002260-154 = "……ええ。"
90002260-155 = "と、とにかく！これで特異現象捜査部もお役御免ですね。"
90002260-157 = "あー、また部長と会長が変な仕事を押し付けてきた……って最初は思ってたなぁ。"
90002260-158 = "そんなわけないでしょう。私はリオとは違いますよ。"
90002260-159 = "気遣いができて、柔軟な思考を持ち、包容力もあり、常識人である私が――"
90002260-16 = "アリスも頑張ってコーティングしました！"
90002260-160 = "無茶な頼みごとをするわけがありません。"
90002260-161 = "（……そうだったかしら？）"
90002260-162 = "図々しさに拍車がかかっているのでは……？"
90002260-163 = "もともとこんなもんだったと思うよ。"
90002260-164 = "はい。リオ会長とヒマリ部長は、まさにどんぐりの背比べです。"
90002260-165 = "僅差でどちらに軍配が上がるかは……言及しないでおきます。ピース、ピース。"
90002260-166 = "失礼ですね！？全然違います！"
90002260-167 = "同じ変人でも計画性が有ると無いとでは、雲泥の差なのですよ！？！？"
90002260-168 = "[s] \"……変人ってところは認めるんだね。\""
90002260-169 = "先生まで！？"
90002260-170 = "（……私の認識が大きく外れてはいないようね）"
90002260-171 = "あなたはなんでホッとした顔をしているんですか！？"
90002260-172 = "[s] \"ほらほら、みんな仲良くね……。\""
90002260-173 = "こほん……。"
90002260-174 = "あれほどの事件で、数多くの成果を上げたのはよかったものの……。"
90002260-175 = "世間に公表できないのは少し残念ですね。"
90002260-176 = "キヴォトスに広まっている怪談――ライブラリー・オブ・ロアに、せめて1行くらい追加できそうだったのに。"
90002260-178 = "危険を排除したのだから、それでいいのではなくて？#nこれ以上、望むものがあるかしら。"
90002260-179 = "そこで正論を言われると私の立場がないじゃないですか……。"
90002260-180 = "だって貴女の望みを叶えるには、特異現象捜査部の存在を公表するところから始めなければならないのよ？"
90002260-181 = "ということは貴女が姿を消していた理由を説明する必要が出てきて――"
90002260-182 = "その前に特異現象……デカグラマトンという存在を説明する過程が必要ね。#nそうなれば貴女のポジションが――"
90002260-183 = "分かってます！分かってますから！ちょっと言ってみただけですっ！！！！"
90002260-185 = "今回はリオが正しいと思いますよ……。"
90002260-187 = "ありがとう。"
90002260-188 = "では……戻って早々なのだけれど、私はまたここを離れることにするわ。#n久々にミレニアムの様子が見られて良かった。"
90002260-192 = "はい？"
90002260-194 = "うん？"
90002260-195 = "リオ様？"
90002260-196 = "はぁ……先生、どうにかしてください。"
90002260-197 = "[s] \"いくらなんでもそれは違うんじゃないかな！\""
90002260-198 = "わ、私また何か変なことを言ったのかしら……？#nだって、いつまたキヴォトスに危機が訪れるか分からないのだから――"
90002260-199 = "合理的かつ効率的に備えるためには、裏で動いた方が効果的だとでも？"
90002260-200 = "……っ！？"
90002260-202 = "ここからは少し真面目な話をしましょう。"
90002260-203 = "まず、ミレニアムに残っていても暗躍することはできます。"
90002260-204 = "他でもない私がそうしているので、保証できます。"
90002260-205 = "それはただ貴女の性格が少し歪んでいるだけでは……。"
90002260-206 = "ぷふっ！？"
90002260-207 = "エイミ……？私……今ちょっと生きる意志を失ってしまいました。"
90002260-208 = "大丈夫だよ。部長はちょっとやそっとじゃへこたれないくらい図々――いや、図太い人なんだから。"
90002260-209 = "そうです。私の知っているヒマリ部長は、どんなにつらいことがあろうと自分を見失わない人です。"
90002260-210 = "最近、皆さんからの評価が怪しくなっている気がするのですが……。"
90002260-213 = "なんにせよ、あなたが再び姿を隠そうとするのは、ミレニアムの生徒を避けているようにしか思えません。"
90002260-214 = "大方、コミュニケーションが苦手だからとか、そんなところですか？"
90002260-215 = "……。"
90002260-216 = "もちろん、あなたの対人能力に難があるのは分かっています。#nとはいえ手探りでも、最近は他人を理解しようとし始めたことも。"
90002260-217 = "……ですから。"
90002260-218 = "あなたが根本的に間違った人だとは思っていません。"
90002260-219 = "つまり何が言いたいのかしら？"
90002260-22 = "……あの。"
90002260-220 = "私の口から言わせるつもりなのですね……！"
90002260-221 = "いいですか。1回しか言わないのでちゃんと聞いてください。#nつまり――"
90002260-222 = "アリスに酷いことをしようとしたこととか！"
90002260-223 = "感情的になって、トキに酷いことをしたこととか！"
90002260-224 = "あなたが偏狭的かつ偏執的で、人の言うことは聞かない意地っ張りでも！"
90002260-225 = "性根が曲がっているわけではないのですから。#n結果的に私たちは、幾度と無くあなたに助けられてきました。"
90002260-227 = "でも……私は……。"
90002260-228 = "何か気がかりでも？#n罪悪感があるなら、ちゃんと面と向かって話をしてください！"
90002260-229 = "とにかく、私が言いたいことは――！"
90002260-23 = "なんですか、これ……？"
90002260-230 = "あなたは！ここに居てもいいんです！分かりますか！？"
90002260-231 = "いえ、ここに居なさい！人知れず問題を起こさないように！"
90002260-237 = "部長……。"
90002260-238 = "なるほど。"
90002260-239 = "……ふん。"
90002260-24 = "ゲームだよ？"
90002260-243 = "皆さん、どうかしましたか……？"
90002260-245 = "部長もそんなことが言えるんだなって思って、少し感動した。#n涙を流すシーンだから目薬入れておくね。"
90002260-246 = "私のをお貸しします。私は完璧なメイドでエージェントですから、備えが良いのです。"
90002260-247 = "今のセリフ、全部録音しておいたので。後でアリスにも共有しておきます。"
90002260-248 = "……！"
90002260-249 = "やはり慣れないことは言うべきじゃなかったです……。"
90002260-25 = "これをゲームだと言い張る勇気は認めます。"
90002260-250 = "[s1] \"でもヒマリの言う通りだよ。\"\n[s2] \"……もうユウカにはたくさん怒られたでしょ？\""
90002260-253 = "……！！！"
90002260-254 = "え、ええ……もう、繰り返さないようにするわ……。"
90002260-255 = "よろしい。"
90002260-258 = "デカグラマトンによるハッキングの危険はもう無いとみていいでしょうね。"
90002260-259 = "それでもこの部室に戻ったのには理由がありまして。"
90002260-26 = "ですが、もう少し客観的な視点を持った方がいいのではないでしょうか。"
90002260-260 = "マルクトの存在をキヴォトスの生徒から隠すためね。そうでしょう？"
90002260-265 = "このまま忘れられてしまうのかと思っていました。"
90002260-266 = "いえ、そうなったとしても構わないのですが。"
90002260-267 = "[s] \"ごめん……怒った？\""
90002260-268 = "質問の意図が理解できません。「怒った」という単語に、まだ我が認知できていない意味があるかを検索します……。"
90002260-269 = "……やはり分かりません。先生、それはどういう質問でしょうか。"
90002260-27 = "なにっ！？"
90002260-270 = "知らなければそれでいい……？さらに意味が分からないのですが……。"
90002260-271 = "[s3] \"そ、それより！\"\n[s4] \"マルクトはこれから何がしたい？\""
90002260-274 = "ふふっ、これはただの提案なのですが――"
90002260-275 = "ご希望であれば、特異現象捜査部に席を用意することもできますよ？"
90002260-276 = "あくまであなたがそう思うのなら、ですが。"
90002260-277 = "あの……。"
90002260-278 = "（もしかして、この話は……）"
90002260-280 = "つまり、これから仲良くしたいから一緒に過ごそうよって話だよ。"
90002260-281 = "はい。ヒマリ部長はたまに素直になれない時があるので。"
90002260-282 = "面白い研究対象だから傍に置きたい……という思惑じゃないといいですが……。"
90002260-284 = "（案の定、ね……）"
90002260-285 = "私を何だと思っているんですか！？"
90002260-29 = "どうして……？"
90002260-290 = "言葉の真意とは難しいものですね……。"
90002260-291 = "……。"
90002260-292 = "お気遣いありがとうございます。"
90002260-293 = "ですが我は、しばらく身を隠そうと思っています。"
90002260-294 = "[s] \"それはどうして？\""
90002260-295 = "……。"
90002260-296 = "我は今まで「自分の人生」が何なのか分かっていませんでした。"
90002260-297 = "考えなくてもいいし、考える必要もなかったのです。"
90002260-30 = "う、うぅ……。"
90002260-302 = "アイン、ソフ、オウル……。"
90002260-303 = "妹たちは我に生きてほしいと言ってくれました。#nだからそうしようとは思うのですが……。"
90002260-304 = "やはり我には、人生を定義し、整理して規定する時間が必要です。"
90002260-305 = "どうしてこのような考えに至ったのか、実はそれもよくは分かりません。"
90002260-306 = "あなた達の表現を借りるなら、そうしないといけない「直感」がしたのです。"
90002260-307 = "……。"
90002260-308 = "それがあなたの意志なら、これ以上言うことはありません。"
90002260-309 = "ただ、また何かトラブルを起こすようなことがあれば。"
90002260-310 = "今度こそ全力で以って、ミレニアムに入学させますからね。"
90002260-316 = "……ふふっ。"
90002260-317 = "はい。その程度の分別は、たしかに「学習」しています。"
90002260-32 = "うわーん！"
90002260-322 = "……やはり、引き留めておけばよかったでしょうか。"
90002260-323 = "でも……マルクトの気持ちも、ほんの少し理解できるわ。"
90002260-324 = "会長はずっと行方をくらませてたもんね。"
90002260-325 = "はい。リオ様は行方不明に音信不通、裏工作が得意な方ですので。"
90002260-326 = "……言葉選びには気をつけようって言われません？"
90002260-327 = "そこに気づくとは。まさか常に私を監視していたのですか？"
90002260-328 = "するわけないでしょう！？見ていなくとも分かります！！"
90002260-329 = "落ち着きなさい、ケイ。トキは事実を言っただけよ。"
90002260-330 = "あなた達の仲が良いのも分かる気がします……。"
90002260-333 = "どこへ行くのでしょうね。"
90002260-334 = "[s] \"今は時間が必要なんだと思うよ。\""
90002260-335 = "己を顧み、自分自身を知っていく時間……ですか。"
90002260-336 = "ですがそれは、ここでもできるのに……。"
90002260-337 = "やはり寂しいのね。"
90002260-338 = "……違います。"
90002260-34 = "まず世界観がおかしいです。これ、ファンタジーですよね？#nなのになぜ雪原から突然、巨大怪獣ロボットが出てくるんですか？"
90002260-340 = "うん。これは寂しいって意味だね。"
90002260-341 = "そのキャラ付け、ちょっと古くないですか……？"
90002260-343 = "……。"
90002260-344 = "（そういうことだったのね……）"
90002260-347 = "でも、1人だから分かることもあるわ。"
90002260-348 = "あの子もいつか、進むべき道を決められる日が来るのではないかしら。"
90002260-35 = "ふっふっふっ……。まだロマンというものが分かっていないようだね……。"
90002260-352 = "驚きました。リオがそんなことを言うだなんて。"
90002260-353 = "そう？"
90002260-354 = "[s] \"そうだね。感心感心。\""
90002260-355 = "あまりからかわないでちょうだい……。"
90002260-356 = "部長が褒めるなんて珍しいこともあるんだね。"
90002260-357 = "はい。加えて、私ですらこれほど褒められたことはありません。"
90002260-358 = "ですから先生に褒めてもらいます。何もしていませんが、早く私を褒めてください。"
90002260-359 = "[s] \"えっと、その……。\""
90002260-36 = "いえ、ロマンにも限度があります。"
90002260-360 = "ぴょんぴょん？"
90002260-361 = "[s] \"トキ……？\""
90002260-362 = "トキ……あなたの精神年齢はいくつなんですか……？"
90002260-365 = "ちょっと素敵ですよね。"
90002260-366 = "何の話かしら。"
90002260-367 = "そうですね……自由に空を飛ぶ鳥を見て羨ましいと思うような感覚でしょうか。"
90002260-368 = "鳥もいずれは地上に降りてくるものよ。"
90002260-369 = "水を飲み、餌を食べ、羽を休ませるために。"
90002260-37 = "何でも好き勝手やっていたら、それはロマンではなく自己満足です。"
90002260-370 = "それでも飛んでいる間、空は鳥のものです。"
90002260-371 = "何もない空を、独りで飛ぶことになったとしても。"
90002260-372 = "……そうね。でも、孤独ではないと思うわ。"
90002260-373 = "あら、それはどうして？"
90002260-377 = "きっとどこかで……見守っている人がいるはずだもの。"
90002260-378 = "……ええ、そうですね。"
90002260-383 = "[ns] \"みんな、お疲れ様。\""
90002260-386 = "はい。"
90002260-387 = "――特異現象捜査、完了です。"
90002260-41 = "それに、巨大怪獣ロボットだけならまだマシです。"
90002260-43 = "なんで急に虚数空間に入るんですか！？しかも操作性が最悪！！"
90002260-44 = "きょ、巨大怪獣ロボットだから操作しやすいわけないじゃん？#nそこも含めてロマンなの！"
90002260-45 = "ロマンとは、時代錯誤だからロマンなんだよ！"
90002260-46 = "だからそんなのただの自己満足ですって！！"
90002260-47 = "そんなー！"
90002260-48 = "この敵は何ですか？虚数空間に入ってからエビだけで7匹目ですよね？"
90002260-49 = "で、でも色は全部違うし……。"
90002260-50 = "結局エビじゃないですか！"
90002260-51 = "こ、これはカラーバリエーションって技なんだよ！#nリソースの削減とか、投資される資源を最適化するためで……！"
90002260-52 = "だからといって7種類も色違いが必要なんですか？"
90002260-53 = "カラバリにだって限度があるでしょう！"
90002260-54 = "序盤でペンギンを描くのに集中しすぎたせいで、時間が……。"
90002260-55 = "エビより、ペンギンのほうがかわいいから……。"
90002260-60 = "結局は私情だということですね！？"
90002260-61 = "う、うぅっ……！"
90002260-62 = "あと虚数空間に入る前の地上パートですが……。"
90002260-63 = "なんで戦闘で「ダッシュ」と「ローリング」、「ジャンプ」が同じボタンなんですか！？"
90002260-64 = "そ、それは押してすぐ外すと「ローリング」で……#n3フレームくらい押すと「ジャンプ」だよ。"
90002260-65 = "そこからまた3フレーム押すと、「ダッシュ」になって……。"
90002260-66 = "ぜ、全部回避の動作だから……。#n1つのボタンにまとめたほうが、わ、わたしは便利で……。"
90002260-67 = "ち、ちなみに、まだあるんだよ。"
90002260-68 = "ローリングの瞬間にパリィをして……1フレームのジャストパリィに成功すれば……。"
90002260-69 = "ぼ、ボスの後ろに回って……大ダメージを与えられるから、練習してみてね……。"
90002260-70 = "ゲームの操作性をあなた基準に合わせてどうするんですか！"
90002260-71 = "私はそんなに細かく操作できません！いえ、ほとんどの人が無理ですよ！"
90002260-72 = "け、ケイちゃんも頑張ればできるよ……！たぶん……。"
90002260-73 = "ユズ……この世の全員があなたみたいなゲーマーにはなれません……。"
90002260-74 = "それにさっきの中間ボス、あれ酷すぎませんか？#n最悪な操作性を我慢してようやく倒したのに復活ギミックですか！？"
90002260-75 = "いえ、1回ならまだ分かります。でも2回も3回も繰り返すのはやりすぎでしょう！？"
90002260-76 = "お、面白くなかった……？"
90002260-81 = "苦行かと思いましたよ！"
90002260-82 = "うぅぅ……。"
90002260-83 = "最後に……ここの画面、なんだかチカチカしません？バグですか？"
90002260-84 = "あの黄色の虚数空間エビ……が投げてくる隕石にやられるところでしたよ！"
90002260-85 = "そこのコーティングはアリスがやりました。ごめんなさい……。"
90002260-89 = "なるほど、それなら仕方ありません。まだ慣れないところもあるでしょうし。"
90002260-95 = "むしろここまで出来たことを褒めるべきですね。さすがはアリスです。"
90002260-97 = "ちょっとちょっと！アリスにだけ甘すぎるんじゃないの！"
90002260-98 = "日頃の行いの差でしょう。#nあなたはまず、巨大怪獣ロボットと虚数空間について悔い改めてください。"
90002260-99 = "ぐえっ……。"
