[translation]
90002190-1 = "第19話;神を落とした日"
90002190-100 = "振り返るな！"
90002190-101 = "！？！？！？"
90002190-104 = "[ns] \"！？！？！？\""
90002190-106 = "神を殺すんだ！これくらい覚悟してる！"
90002190-107 = "げほっ、げほっ！そ、そうです……。私たちのことは、気にしないでください……！"
90002190-108 = "何のためにここまで来たのか忘れたんですか。#n世界が鋼鉄大陸に覆われるのを阻止するためでしょう？"
90002190-110 = "チャンスは今だけです！#nそれとも、私たちの選択を無意味にさせるつもりですか？"
90002190-114 = "で、ですが……！"
90002190-115 = "アイン？ソフ？オウル？"
90002190-116 = "一体、どうして……？"
90002190-117 = "え、えへへ。それはですね。"
90002190-118 = "これが正しくて……こうすべきだったんだ。#n最後にお姉様と会えて、嬉しかった。あははっ……。"
90002190-119 = "……ずっと言いたかったことが、あります。"
90002190-12 = "第二の聖痕が消える。#nこれは誕生のごとく、すなわち「産声」なり。"
90002190-121 = "「頑張ったね」と言ってくれた人がいました。"
90002190-124 = "友達になってくれとか、望みがあれば抗うべきとか、好き勝手言ってくれちゃって。"
90002190-127 = "正しいから行うのではありません。これ以外、他にできることがないのです。#n……これが、私たちの闘いです。"
90002190-130 = "わ、私たちは、お姉様に生きてほしいんです。"
90002190-133 = "何があっても、お姉様だけは生き残って。"
90002190-136 = "もっと多くのものを見て、多くの人と出会って、多くを経験してください。"
90002190-139 = "私たちより、もっともっと――"
90002190-142 = "たくさん、色んなことを経験してね。"
90002190-145 = "どうか最後まで、生き抜いてください。"
90002190-147 = "あ……ああ……あああああああ……！"
90002190-148 = "だから言ったのに。振り返るなって。"
90002190-149 = "勘弁してくださいよ。恥ずかしいじゃないですか。"
90002190-150 = "えへへ……。ありがとうございます。友達になりたいと言ってくれて……。"
90002190-151 = "止まらず進んでください。最後まで。"
90002190-152 = "そ、そうです……！先人の後を継いで道を開くこと……それが、皆さんの生きる方法なんですよね……？"
90002190-153 = "あっ！あと、自己実現にこだわってる人には気をつけなよ！あははっ！"
90002190-155 = "あなた達の[ruby=キヴォトス]世界[/ruby]を壊そうとして、ごめんなさい。"
90002190-156 = "ずっと勝手なことをして、ごめんなさい。"
90002190-157 = "それでも。"
90002190-158 = "あなた達の[ruby=先生]世界[/ruby]に、ほんの少しだけでも……。"
90002190-159 = "お姉様の、居場所があれば――"
90002190-160 = "私たちのお姉様を……よろしくお願いします。"
90002190-164 = "[ns] \"……！\""
90002190-165 = "アイン……？ソフ……？オウル……！？"
90002190-166 = "あ、ああ……ああああああああ……！！"
90002190-167 = "ああああああああああああああ！！！"
90002190-17 = "最後の聖痕が消える。#nこれは解氷のごとく、すなわち「萌芽」なり。"
90002190-171 = "……器の限界か。"
90002190-177 = "げほっ、げほっ……！"
90002190-178 = "[ns] \"マルクト……！\""
90002190-182 = "[ns] \"誰か、手を貸して！\""
90002190-183 = "……。"
90002190-187 = "アリスがお助けします！"
90002190-188 = "私も。"
90002190-189 = "力仕事なら任せて。"
90002190-192 = "[ns] \"大丈夫？\""
90002190-193 = "我は……アイン……ソフ……オウル……。"
90002190-194 = "[s3] \"立って、マルクト。\"\n[s4] \"一緒に[ruby=生きよう]戦おう[/ruby]。\""
90002190-197 = "で、ですが……。"
90002190-198 = "[s5] \"いまの君にとってはつらいかもしれないけど。\"\n[s6] \"妹たちの意志を、忘れないでほしい。\""
90002190-2 = "反抗期をやってみよっか。"
90002190-201 = "……！"
90002190-202 = "う、ううっ……！"
90002190-207 = "[ns] \"リオ！ヒマリ！状況分析をお願い！\""
90002190-208 = "ええ、分かりました！"
90002190-213 = "……マルクトの身体から、デカグラマトンの信号は完全に消えています！"
90002190-214 = "では、デカグラマトンはどこに……？"
90002190-220 = "あちらに、何かが現れたようです。"
90002190-228 = "次回;形を成したもの"
90002190-24 = "こ、れは……！"
90002190-29 = "燔祭の剣が……抜かれた……！？"
90002190-30 = "くっ、うううっ……！"
90002190-35 = "……？"
90002190-36 = "我は……どうして、また……？"
90002190-37 = "……！？"
90002190-38 = "……あれ？"
90002190-39 = "ソフ、オウル！これって……！？"
90002190-4 = "第一の聖痕が消える。"
90002190-40 = "うん！まさか……本当に……！"
90002190-41 = "お姉様が――"
90002190-43 = "帰ってきました！！！！"
90002190-44 = "消えたわけじゃなかった！生き残っていたんです！！奇跡ですよ！！！"
90002190-45 = "アイン？ソフ？オウル？#n我は……どうして？どうやって……？"
90002190-46 = "お姉様！！！！"
90002190-5 = "！？"
90002190-53 = "身体が、動かせる……？"
90002190-54 = "皆さん！しっかりしてください！"
90002190-58 = "うぅん……？ケイ……？アリスは……。"
90002190-59 = "……あ！デカグラマトンと戦わなければ！#n……あれ？"
90002190-60 = "先生、大丈夫？"
90002190-61 = "[s] \"うん……なんとか。\""
90002190-62 = "ご無事で何よりです……。"
90002190-64 = "お姉様！"
90002190-66 = "アイン、ソフ、オウル……。"
90002190-67 = "……。"
90002190-7 = "これは羽化のごとく、すなわち「解放」なり。"
90002190-71 = "先生に……皆さんも。"
90002190-72 = "これってさ……昨日の敵は今日の友ってやつじゃない？"
90002190-88 = "……え？"
90002190-89 = "うぇっ……？"
90002190-90 = "なに……？"
90002190-91 = "……！"
90002190-92 = "そん、な……？"
90002190-93 = "アイン……？ソフ……？オウル……？"
90002190-97 = "あ、ああ……ああああああああああああああ――！？！？！？！？"
90002190-98 = "[ns] \"……！！\""
90002190-99 = "い、嫌です……こんなの……あんまりです――！！"
