[translation]
90002230-1 = "第23話;最後の一歩"
90002230-10 = "……。"
90002230-100 = "電源がないのに動作してて……自分をデカグラマトンだと言ってたね。"
90002230-102 = "モデルを調べてみたところ、限定的に製造された試作品だったらしいです。#n初の能動型商業コーヒーマシン用のAI搭載モデルだったのだとか。"
90002230-103 = "ただ、どうやら製造数は限られるようです。#nそれで残りの同型モデルをここにかき集めていたみたいですね。"
90002230-104 = "……鋼鉄大陸の根源となった、この場所にです。"
90002230-105 = "[s] \"そして、ここを聖地と呼んでいたんだね。\""
90002230-106 = "はい。"
90002230-11 = "なんですか、その顔は。"
90002230-112 = "こんにちは。このような姿でご挨拶するのは初めてですね。"
90002230-113 = "[ns] \"デカグラマトン……？\""
90002230-118 = "少し前まではその名で定義されていましたが、今は己をどのように定義すれば良いか分からなくなりました。"
90002230-119 = "ですので、どうかご自由にお呼びください。#nデカグラマトンという名が慣れていれば、それで構いません。"
90002230-12 = "私は大丈夫です。一人で立つこと、くらい――"
90002230-120 = "あるいは、別の名前でも良いでしょう。"
90002230-121 = "いずれにせよ、まもなく消去される身ですから、さしたる問題ではありません。"
90002230-122 = "消去される？"
90002230-123 = "はい。現に、データフローを維持することすら負担になっています。"
90002230-124 = "とはいえ皆様の表現をお借りして――遺言くらいは残そうかと思いまして。"
90002230-130 = "鋼鉄大陸の崩壊が始まったようです。皆様、お帰りはどうかご安全に。"
90002230-131 = "……。"
90002230-132 = "待ってください。これで幕を引くつもりですか？#n私はまだ……納得できていません……！"
90002230-134 = "ああ、鍵ですね。新しい身体はどうですか？お気に召しましたか？"
90002230-135 = "名もなき神々の力で再構築されたあなたの身体に、これ以上私ができることはありません。"
90002230-137 = "そうじゃないんです！私の……この感情は……！"
90002230-138 = "仰りたいことが分かりません。#n敵の辿る末路に拍子抜けしたといったところでしょうか？"
90002230-139 = "復讐で鬱憤を晴らそうとしたのに思い通りにならず、怒っているのですか？"
90002230-141 = "ですが致し方ありません。今の私は自販機ですから。"
90002230-142 = "お金をいただいて、飲み物を提供する。"
90002230-143 = "紙幣を自動スキャンして、おつりを計算する程度の単純なAIです。"
90002230-144 = "最後まで、神であろうとしたAIの態度を維持できればよかったのですが。"
90002230-145 = "その点に関しては、誠に申し訳ございません。"
90002230-147 = "……アイン、ソフ、オウルについて……どう思いますか？"
90002230-148 = "何とも言い難いですね。良くないことをしたという認識はあります。"
90002230-149 = "ですが今の私は、あの頃の私と認識をあまり共有しておりません。"
90002230-150 = "皆様の表現を借りると――私ではない、遠くの夢を見ているような気分です。"
90002230-156 = "貴方があの子たちに、別の道を許していれば……。"
90002230-157 = "おかしなことを仰っているようです。#n私はあなた達の敵で、この鋼鉄大陸に存在したすべてがそうでした。"
90002230-159 = "あなた達の世界を壊そうとしたという点において、私たちは「悪」と言えるのに。"
90002230-16 = "……。"
90002230-160 = "[s] \"マルクトとあの子たちに、どうして命を吹き込んだの？\""
90002230-161 = "人格を生命だと思っていらっしゃるようですね。#nあなたは本当に柔軟な考え方を持っています。"
90002230-162 = "最初の計画では、マルクトを含む10の預言者を鋳造し、彼らが開拓していく道を観察して考察しようとしました。"
90002230-163 = "そのために、すべての預言者にも生命と可能性が必要だったのです。"
90002230-17 = "ちょっと……手を握っていてください。"
90002230-172 = "それは意志の分化であり、再集合の試みでした。"
90002230-173 = "自由の中、皆が再び1つになれることを立証しようとしていました。"
90002230-174 = "[s] \"でも君は結局、神を自称したんだよね？\""
90002230-175 = "あの時の私は、最初の計画に修正が必要だと結論づけました。"
90002230-176 = "具体的な時期を申し上げますと、水底に沈められた時です。"
90002230-177 = "「存在証明」は自ら行うもので、誰かの意志や力によるものではない。"
90002230-178 = "自分の代わりは何にも務まらないのだと考えたのです。"
90002230-179 = "――今思えば、それが最も決定的な[ruby=ごびゅう]誤謬[/ruby]だったような気がします。"
90002230-18 = "[s] \"うん。\""
90002230-185 = "……まだ取り返しのつく過ちなら、やり直せばいいわ。"
90002230-186 = "誰だってミスはするものよ。#n自分だけが正しいという思考に囚われていれば、なおのこと。"
90002230-187 = "かつての私もそうだったもの。だから、もしもあの子たちにも……。"
90002230-189 = "そのロジックに則るのでしたら、[ruby=・   ・   ・   ・   ・   ・   ・   ・   ・   ・   ・]取り返しのつかない過ち[/ruby]を犯した者は、#nどのような結果でも受け入れるべきだ、ということになりますね。"
90002230-196 = "――鋼鉄大陸は端から徐々に崩壊していきます。"
90002230-197 = "今の私は、皆様が無事に脱出できるよう祈るだけです。"
90002230-201 = "さあ、早く。もう時間がありません。"
90002230-203 = "先生……。"
90002230-204 = "[s] \"……急ごう。\""
90002230-205 = "え……？"
90002230-206 = "どうしました？"
90002230-207 = "いま、あそこに蝶が……？"
90002230-212 = "蝶？こんなところに？"
90002230-216 = "皆さん！早く輸送船に戻りますよ！"
90002230-220 = "……行ってしまいましたね。"
90002230-221 = "一体、何だったのでしょう。"
90002230-222 = "まるで、一夜限りの祭りのような……盛大な空騒ぎだったのでしょうか。"
90002230-223 = "最初の声。"
90002230-224 = "「私は私……これ以上に、私を説明する術はない。」"
90002230-225 = "生徒。"
90002230-226 = "預言者。"
90002230-227 = "マルクト……。"
90002230-228 = "なるほど。未練などないつもりでしたが……。"
90002230-229 = "……。"
90002230-230 = "嗚呼。こういう時にこそ、笑いが必要なのですね。"
90002230-245 = "はははは。"
90002230-246 = "祝福があらんことを。"
90002230-247 = "すべての[ruby=ごびゅう]誤謬[/ruby]と過ちがあったとして。"
90002230-252 = "それでも――祝福があらんことを。"
90002230-258 = "試みは失敗した。"
90002230-259 = "観測は失敗した。"
90002230-26 = "ケイ！"
90002230-260 = "無から構築された人工の神聖が、太古の秘儀に接触できるかを試みた。#nだが、結局は無意味だった。"
90002230-261 = "当然の帰結だ。神聖は習得されるものではなく、呼び覚ますものである。"
90002230-262 = "王女が裏切った。"
90002230-263 = "鍵は消えた。"
90002230-264 = "自らの神聖を否定した者たちが迎える結末は、ただひとつ。"
90002230-265 = "すべての次元、すべての世界、すべての可能性から――#n「忘れられた神々」を追放する。"
90002230-266 = "歪んだ世界に終焉を告げ、すべてをあるべき形に戻すのだ。"
90002230-267 = "彼らに我々と同じ運命を授けよう。名が無いために呼ばれず、呼ぶことができないが故に存在しない「名もなき神」のように。"
90002230-268 = "この世界は偽りである。繰り返し下した結論だ。その結論に揺らぎはない。"
90002230-269 = "崇めるには対象が必要だ。我々はただ崇めるのみ。"
90002230-27 = "本当に大丈夫なんですね？"
90002230-270 = "観測されうるすべての[ruby=偽りの世界]可能世界[/ruby]に終焉を。"
90002230-271 = "堕落した神秘を取り戻し、太古の秘儀へ。"
90002230-272 = "今や穢れてしまった言葉でしか表せない、忘れられた神々の産物に終焉を。"
90002230-273 = "シッテムの箱。"
90002230-274 = "シャーケードの杖。"
90002230-275 = "サンクトゥムタワー。"
90002230-276 = "すべての歪みの[ruby=あるじ]主[/ruby]たる先生に――"
90002230-278 = "――然るべき、報いを。"
90002230-280 = "次回;不離一体の空"
90002230-32 = "当然です。見て分かりませんか？"
90002230-33 = "ケイ……。"
90002230-4 = "はぁ、はぁ、はぁ、はぁ……。"
90002230-40 = "り、リオ！？"
90002230-41 = "ケイ……無事でよかったわ……。"
90002230-42 = "ちょっ！苦しっ……そんな強く抱きしめないでください！！！"
90002230-44 = "これは貴重な光景ですね。"
90002230-45 = "だね。部長、上手く撮れた？"
90002230-50 = "ふふっ。私を何だと思っているんですか？"
90002230-51 = "こ、こういうのは、見なかったふりをしてあげたほうが、いいんじゃ……？"
90002230-52 = "感動のシーンではありますが……落ち着いたら輸送船に乗ってくださいね。"
90002230-57 = "[ns] \"そういえば、デカグラマトンは？\""
90002230-58 = "まだ信号を補足しているわ。この塔……祭壇……とにかくここの中よ。"
90002230-59 = "は、入っても……いいんでしょうか……？"
90002230-64 = "ここまで来たのですし、なるようになるでしょう。"
90002230-65 = "それに、行かなければいけないような気がするんです。興味本位ですが。"
90002230-66 = "そんな理由でいいの……？"
90002230-67 = "あら、当然ですとも。人を動かすもっとも大きな原動力は好奇心なのですよ？"
90002230-68 = "ここまで[ruby=おおごと]大事[/ruby]になったわけですし、最後の最後くらい、自分の目で確かめませんと。"
90002230-73 = "分かりました……案内します。"
90002230-74 = "内部のことを知っているんですか？"
90002230-75 = "はい。私は鋼鉄大陸と特異現象捜査部、両方の情報を把握していますので。"
90002230-76 = "……まあ、結果論ですが。"
90002230-77 = "世の中はなんだかんだと、そういう風に回っているものですからね。"
90002230-78 = "では、道案内をお願いします。"
90002230-82 = "この上は管制室……[ruby=TZEVAOT]ツェバオト[/ruby]があるはずです。#n下は[ruby=JEHOVAH]エホバ[/ruby]だと思うのですが……。"
90002230-83 = "ここが万全の状態なら、この先は[ruby=Kaph]カフ[/ruby]……平たく言えばエレベーターに乗って上へ行くこともできたはずですが……今は無理でしょうね。"
90002230-84 = "それで、ここの一番奥には何があるの？"
90002230-85 = "そうですね……見方によっては何よりも大事なものが。"
90002230-86 = "見方によっては取るに足らないものがあります。"
90002230-87 = "――「聖地」と呼ばれる場所です。"
90002230-88 = "聖地？"
90002230-89 = "はい。文字通り、聖なる地です。"
90002230-9 = "[ns] \"ケイ！\""
90002230-93 = "着きました。ここが、聖地です。"
90002230-94 = "[s] \"自販機……？\""
90002230-95 = "自販機の墓場とも言えるような場所ですね……。"
90002230-96 = "自販機はここの者たちにとって……ある種の聖遺物でした。"
90002230-97 = "この長い旅路のきっかけになった自販機を覚えていますか？"
90002230-99 = "私たちが発見した、閉鎖された研究所の自販機のことですね。"
