[translation]
90002060-1 = "第6話;マルクト"
90002060-9 = "先生！レイバーとデカグラマトンの兵がそっちに向かってる！"
90002060-10 = "[s] \"こっちでも把握したよ！エイミの意見を聞かせて。\""
90002060-11 = "防衛線を張って。私もなるべく早く復帰するから。"
90002060-16 = "……あ、今のなし。別動隊を発見。たぶん偵察かな。#nそっちを倒してから戻るね。"
90002060-17 = "[s] \"怪我しちゃダメだからね……？\""
90002060-18 = "心配してくれるの？嬉しいな。"
90002060-19 = "仕方ありません。私も現場に向かって、先生に気にかけてもらいます。"
90002060-20 = "……いや、トキは先生を守らないとでしょ？先生に何かあったらどうするの。"
90002060-21 = "それもそうですね。では、より長く先生と一緒にいられる案を選ぶことにします。"
90002060-22 = "アリスたちは何をすれば……？"
90002060-23 = "……エイミを信じましょう。私たちはここの占領を進めるのが得策だと思います。"
90002060-24 = "私も、そのほうが合理的だと思うわ。"
90002060-25 = "幸い、システムの構築はほぼ終わりました。"
90002060-26 = "……おや？"
90002060-27 = "[s] \"ケイ？\""
90002060-28 = "私たち……このエリアを分析していたんですよね？"
90002060-29 = "何か、問題でも？"
90002060-30 = "ここから遠くない場所に、構造物……何かの施設があるみたいです。"
90002060-34 = "構造物、ですか？"
90002060-35 = "何の施設なんでしょうか？"
90002060-36 = "遠い昔に放棄された遺跡とか？"
90002060-37 = "鋼鉄大陸ができたのはつい最近だということをお忘れですか？"
90002060-38 = "あれがなんであるにせよ、「構造物」であることが重要だと思います。#nもしかすると、防衛拠点として活用できるかもしれません。"
90002060-39 = "四方が開けているここよりは安全だと思うわ。調査に向かいましょう。"
90002060-46 = "……。"
90002060-47 = "……。"
90002060-48 = "こ、ここは……？"
90002060-49 = "アリス……知っています。#nこういう場所にはレアアイテムが隠されているんですよね……！"
90002060-53 = "[ns] \"なにかの……研究所なのかな。\""
90002060-54 = "……私も同意見です。"
90002060-55 = "ひとまず、エイミにここの座標を送っておきます。"
90002060-60 = "……あれは？"
90002060-64 = "これ……あの子たちに似ていませんか？"
90002060-65 = "それも、こんな数……。"
90002060-66 = "まるで標本を見ているような……。うぅ、気持ち悪い……。"
90002060-67 = "このガラス管……何か書かれています。"
90002060-72 = "「DEFECTED」……？#n文字通りの意味なら、「欠陥品」ですね。"
90002060-73 = "……。"
90002060-74 = "違うと思うわ。"
90002060-75 = "と言いますと？"
90002060-76 = "おそらく――"
90002060-77 = "「欠陥あり」がより正確なはずよ。"
90002060-78 = "欠陥あり……？"
90002060-89 = "まだ分析を始めたばかりですが、いくつか分かった事があります。"
90002060-90 = "まず、稼働には問題ありません。#n何かしらの意識回路を移植すれば、すぐにでも動ける状態にあります。"
90002060-91 = "欠陥あり……という「烙印」を押された割には、状態は良好だということね。"
90002060-92 = "ただ、問題は素体のセキュリティです。"
90002060-93 = "ケイが確認したところ……いわば[ruby=・]古[/ruby][ruby=・]代[/ruby][ruby=・]方[/ruby][ruby=・]式[/ruby]のプロテクトで守られています。"
90002060-94 = "厄介ではありますが、私にとって未知の技術ではありません。"
90002060-95 = "時間さえあれば、突破できるとは思いますが……。"
90002060-100 = "やっほー、みんな無事？#n言われた通り来たけど、何する場所なの？"
90002060-101 = "エイミ！無事でよかったです！えっと、ここは――"
90002060-106 = "……何なのでしょう？"
90002060-107 = "アリス！？"
90002060-108 = "アリスちゃん！？"
90002060-109 = "見た感じ、それを調査中ってところかな？"
90002060-110 = "施設の外に、AMASで防衛線を張っておいたわ。"
90002060-111 = "うん、確認したよ。敵の偵察部隊は倒しておいたから、しばらくは安全だと思う。"
90002060-116 = "[ns] \"なに！？\""
90002060-122 = "外よ！AMASの防衛線が……崩された！？"
90002060-123 = "どうして……？近くの敵は倒したはずなのに……。"
90002060-124 = "考えるよりも、確認を急ぎましょう！"
90002060-129 = "う、うわああああっ！？"
90002060-130 = "お姉ちゃん、大丈夫？"
90002060-131 = "せ、先生、あっち……！"
90002060-133 = "[ns] \"え……？\""
90002060-134 = "あれは……？"
90002060-141 = "（初めて見る個体。でも、あの特徴は間違いなくデカグラマトン……まさか？）"
90002060-142 = "……マルクト？"
90002060-143 = "マルクト！？"
90002060-146 = "やはり、我々について最も詳しいのはあなたですか。"
90002060-147 = "星を追う者――[ruby=つかつき]調月[/ruby]リオ。"
90002060-148 = "！？"
90002060-149 = "[ruby=あけぼし]明星[/ruby]ヒマリ。 "
90002060-150 = "[ruby=いずみもと]和泉元[/ruby]エイミ、[ruby=あすま]飛鳥馬[/ruby]トキ。"
90002060-151 = "名もなき神々の鍵。"
90002060-152 = "……あのですね、私の名前は――"
90002060-153 = "生まれ持ったものは変えられない。そう思いませんか？[ruby=・]ケ[/ruby][ruby=・]イ[/ruby]。"
90002060-154 = "……！！！"
90002060-155 = "そして、先生。"
90002060-162 = "[ns] \"君が、マルクト？\""
90002060-163 = "こういう時は……お初にお目にかかります……と、挨拶するのですよね？"
90002060-167 = "皆さん、初めまして。#nアイン、ソフ、オウルからのご挨拶を。"
90002060-168 = "我は御旗の下に創造されし一つの意志。#n世界の果てに到達せし王国の巡礼者。"
90002060-169 = "[ruby=Malkuth]マルクト[/ruby]と申します。"
90002060-173 = "それでは……おやすみなさい。"
90002060-174 = "先生――！"
90002060-180 = "あああああああっ！！"
90002060-184 = "[ns] \"トキ！\""
90002060-185 = "アビ・エシュフ状態のトキを、一撃で……！？"
90002060-186 = "（馬鹿げているわ。こんな火力、私たちでは相手にすらならない……）"
90002060-190 = "……先生？何を――！？"
90002060-191 = "[ns] 前へ走る。"
90002060-195 = "[ns] 生徒たちを庇う。"
90002060-196 = "先生！何をやっているんですか！"
90002060-197 = "……思っていた通りの方で、安心しました。"
90002060-198 = "自分を犠牲にする代わり、生徒には手を出すな、と？"
90002060-199 = "[s] \"……！\""
90002060-200 = "大丈夫です。その必要はありません。"
90002060-201 = "……困惑されていますね。ええ、分かります。"
90002060-202 = "ですが、これだけは明確にお伝えします。"
90002060-203 = "我々は、誰の命も奪うつもりはありません。"
90002060-204 = "飛鳥馬トキも、致命傷にならない程度に、適度な衝撃を与えただけです。"
90002060-211 = "先……生……。"
90002060-213 = "下がって、ください……私が、お守り、します……。"
90002060-217 = "なにがあっても、先生を守ってみせると……エイミと……私自身に……！"
90002060-221 = "お、お姉様！もう時間が……！い、急いでください……！"
90002060-222 = "……。"
90002060-223 = "すべてが終わり、転換の時が訪れれば、やがて皆さんも理解するでしょう。"
90002060-224 = "我々が、皆さんのすべての罪と苦痛を、取り払おうとしているのだということを。"
90002060-225 = "[s] \"それは、どうやって？\""
90002060-226 = "煤けた箇所に触れれば、煤が付きます。"
90002060-227 = "であれば、そもそも焼け跡に近づかなければいいだけのこと。"
90002060-228 = "[s] \"それはちょっと違うんじゃない？\""
90002060-229 = "我々はあなた達の同意を求めているわけではありません。"
90002060-230 = "[ruby=・]す[/ruby][ruby=・]べ[/ruby][ruby=・]て[/ruby][ruby=・]は[/ruby][ruby=・]そ[/ruby][ruby=・]う[/ruby][ruby=・]な[/ruby][ruby=・]る[/ruby]と宣言するために、我はこの場に来たのですから。"
90002060-231 = "お姉様！福音を伝えるのもいいけど、今は本来の目的を優先してほしい！"
90002060-232 = "――時は来ました。"
90002060-233 = "皆さんの巡礼の終わりを、喜んでお見送りします。"
90002060-240 = "っ……くっ……！"
90002060-244 = "トキ？"
90002060-245 = "トキ！"
90002060-247 = "（眩しい閃光が視界を遮った）"
90002060-248 = "（反射的に、目を閉じてしまった）"
90002060-252 = "先生！大丈夫です！私たちがいます！"
90002060-254 = "[ns] \"アロナ？プラナ？\""
90002060-255 = "苦戦。出力不足です。エネルギーの流れが不利に働いています。#nですが、引き下がるわけにはいきません。"
90002060-256 = "出し惜しみは無しです！先生も生徒の皆さんも、みんな大切ですから！"
90002060-257 = "肯定。最善を尽くさなければ、皆さんに顔向けできません。"
90002060-259 = "うっ……！うぅぅっ……！"
90002060-260 = "……くぅっ。"
90002060-261 = "おねがい……あと、すこし……！"
90002060-265 = "残存エネルギー……不そ……。"
90002060-270 = "プラナちゃん！？し、しっかりしてください！うぅ、私だけでも……！"
90002060-274 = "うああああっ！！"
90002060-278 = "……。"
90002060-279 = "あれ……？マルクトの出力が急に弱まりました！#nでも、どうして……？"
90002060-280 = "！！！"
90002060-281 = "先生！ケイさんです！"
90002060-286 = "[ns] \"ケイ！下がって！\""
90002060-287 = "こんな状況でもそれですか。ほんと、飽きない大人ですね。"
90002060-288 = "……まあ、だからこそ、アリスを任せていられるのですが。"
90002060-289 = "[s] \"何をするつもり……？\""
90002060-290 = "心配いりません。ここは、名もなき神々の力で満ちています。"
90002060-291 = "そしてこの場において、力の扱いに最も長けているのは私です。"
90002060-292 = "……なにやら勝手にアレンジされていて、いつもとは感覚が異なりますが。"
90002060-293 = "とにかく、あのマルクトとかいう自称預言者も、戸惑っているはずです。"
90002060-295 = "意外ですね。この変数は想定外です。"
90002060-296 = "お姉様……その……。"
90002060-297 = "時間切れ……です……。"
90002060-298 = "あっ、でも、あと数秒くらいならなんとか稼げます！#nそれ以上はさすがに無理ですが……。"
90002060-299 = "分かりました。手加減無しでいきます。"
90002060-304 = "なっ、まだ出力が上がるなんて……バケモノですか……！？"
90002060-305 = "せ、先生！？私は大丈夫です！#nアリスがいるのに、倒れるわけないじゃないですか！"
90002060-306 = "エネルギーを……受けてから、整えなおして……。"
90002060-307 = "うああぁぁぁーっ！！！"
90002060-312 = "くっ――！！"
90002060-314 = "ふざけ……ないでくださいよ……！"
90002060-315 = "この力を使っておいて――"
90002060-316 = "私を誰だと思っているのですか！！"
90002060-320 = "お、お姉様……！"
90002060-321 = "もう限界だよ！早く戻ってきて！"
90002060-322 = "お姉様！無理しないでください！結果なんて、どうでもいいんですから！！"
90002060-323 = "……。"
90002060-324 = "分かりました。アイン、ソフ、オウル。"
90002060-332 = "マルクトが……撤退していく……？"
90002060-333 = "先生はご無事ですか！？"
90002060-334 = "先生！"
90002060-335 = "大丈夫ですか、先生！？トキにケイ、ヒマリ先輩にリオ先輩も……！"
90002060-336 = "け、ケイちゃん……？"
90002060-337 = "ケイ！？"
90002060-345 = "ケイ？起きてください、ケイ！#nこんなの、嫌です……アリスを、独りにしないでください！"
90002060-347 = "ケイ！！！！"
90002060-349 = "次回;ケイ"
