[translation]
90002170-1 = "第17話;人間の答え"
90002170-3 = "[ns] \"それは、答えにならない。\""
90002170-4 = "……どういう意味だ。"
90002170-5 = "[s] \"人間の答えにはなるけど、神の答えにはならない。\""
90002170-9 = "[ns] \"それは、自己証明じゃない。\""
90002170-10 = "……！"
90002170-11 = "[ns] \"私たちの悲しみを無くす必要はない。\""
90002170-13 = "[ns1] \"過去は過去だ。\"\n[ns2] \"過ぎ去った出来事を覆す方法はない。\""
90002170-16 = "だが、これからは違う。私がそれを是正する。"
90002170-17 = "[s] \"それはできないよ。\""
90002170-18 = "何故そう思う？"
90002170-19 = "[s3] \"だって、そのすべてが私なんだから。\"\n[s4] \"[ruby=罪]悲しみ[/ruby]を無くして他人を理解する方法は、存在しないよ。\""
90002170-22 = "……！"
90002170-23 = "[ns5] \"何より私がそんなふうに逃げてしまったら。\"\n[ns6] \"生徒たちに顔向けできないでしょ？\""
90002170-28 = "……！"
90002170-29 = "なるほど……そういう、ことか……。"
90002170-30 = "……。"
90002170-31 = "……えへへ。"
90002170-32 = "羨ましい、ですね。"
90002170-33 = "はい……？何がですか？"
90002170-34 = "み、皆さんの先生が、あのような方で。えへへ。"
90002170-35 = "……ふふっ、少し訂正させてください。"
90002170-36 = "なにを？"
90002170-41 = "[ruby=・]私[/ruby][ruby=・]た[/ruby][ruby=・]ち[/ruby]の先生ですよ。"
90002170-42 = "ええ、これからは。"
90002170-43 = "……！"
90002170-45 = "……この期に及んでまだ生徒か。実に愚かだな。"
90002170-46 = "[s] \"そうかもしれないね。\""
90002170-47 = "汝ならば少しはマシな選択をするものと思ったが。"
90002170-48 = "[s] \"私は最初から何でもない人間だからね。\""
90002170-49 = "誰も汝を責めはしない。ここにいるのは私と汝、2人だけなのだから。"
90002170-50 = "たとえ自分の心から目を逸らそうとも、それを咎める者は誰もいない。"
90002170-54 = "[ns] \"そういう考えもあるかもね。\""
90002170-56 = "……先生は、アリスの仲間です。"
90002170-58 = "先生が生徒を助けるのが当たり前なら、生徒が先生の力になりたいって思うのも、当然じゃない？"
90002170-60 = "ここはモモイとミドリを信じましょう。"
90002170-62 = "ですから、きっとこれからもその狭間を行き来しながら、何度も挫けてはまた立ち直り……。"
90002170-63 = "いつかは、道を探すだろうと思います。"
90002170-77 = "[ns] \"それでもやっぱりダメ。\""
90002170-79 = "[ns7] \"先生が「先生」じゃなくなったら。\"\n[ns8] \"生徒が「生徒」ではいられなくなっちゃうから。\""
90002170-82 = "誰一人、見届ける者がいなくとも？"
90002170-85 = "[ns9] \"……そうだね。\"\n[ns10] \"「自分」が自分を見てるから。\""
90002170-90 = "……。"
90002170-91 = "そうか。"
90002170-92 = "神に成る者として、汝の選択を尊重しよう。"
90002170-93 = "しかしそれは許容を意味しない。"
90002170-94 = "生徒の元へ帰るが良い。汝の意志で、汝の古き世界へ。"
90002170-98 = "[ns] \"……？\""
90002170-99 = "何を用いても構わぬ。"
90002170-100 = "シッテムの箱も、大人のカードも、汝の生徒が持つ力も。"
90002170-101 = "だが……汝と汝の生徒らが本気で私に逆らうのであれば――"
90002170-102 = "その先に待ち受けるのは絶滅であることを心せよ。"
90002170-103 = "これは私の言葉だ。その場にいるお前たちにも同様である。"
90002170-104 = "耳のある者は聞け。これは私の怒りであり警告だ。"
90002170-111 = "うげっ！？バレてた……！？"
90002170-112 = "そ、それより……あれっ！"
90002170-113 = "皆さん！先生が降りてきます！"
90002170-116 = "（体が宙に浮いたまま、ゆっくりと地上へ降ろされた）"
90002170-117 = "（見方によっては、神の権能、慈悲、恩恵……のように見えるかもしれないが）"
90002170-118 = "（この先に待ち構えているのは、決してそういうものじゃない）"
90002170-122 = "先生！"
90002170-123 = "先生、大丈夫ですか？"
90002170-124 = "[s] \"私は大丈夫！それより今……。\""
90002170-129 = "あ……。"
90002170-130 = "えっと……。"
90002170-131 = "こ、こんにちは……また、お会いしましたね……。"
90002170-132 = "[USERNAME]先生。"
90002170-133 = "[s] \"……うん。みんな元気だった？\""
90002170-134 = "う、うん……。"
90002170-135 = "今はそんな話をしている場合ではないのでは？"
90002170-136 = "[s] \"そうだね。まずはこの話をしないと。\""
90002170-138 = "（要点に絞って、みんなに状況を説明した）"
90002170-140 = "……なるほど。"
90002170-141 = "理解しました。モモイの表現を借りると――"
90002170-142 = "ラスボスの魔王と、ついに戦うときが来たのですね。"
90002170-147 = "ひ、ひぃぃ……ゲームだったなら、まだなんとかなりそうなのに……。"
90002170-148 = "ここまで来て、もう引き返すことはできませんよね。"
90002170-149 = "大丈夫だよ、先生。ある程度は私たちも知ってるから。"
90002170-150 = "どうして分かったのかって？それはね――"
90002170-151 = "ま、待って！それは言わないほうがいいんじゃない……？"
90002170-152 = "どうして？"
90002170-156 = "だって人間の言う「盗聴」でしょ？あれ……。"
90002170-157 = "それがどうかしたの？#nシャーレのオフィスを盗聴してる先輩もいるよ？"
90002170-163 = "……あなた達、本当に大丈夫ですか？"
90002170-165 = "わ、私たちはどうすればいいでしょうか……？"
90002170-166 = "[s] \"君たちは休んでて大丈夫だよ。\""
90002170-167 = "で、でも……。"
90002170-168 = "お気になさらず。あなた達は立場が曖昧でしょうし。"
90002170-169 = "力を貸してくださるのなら、それはまたの機会に取っておきましょう。"
90002170-173 = "……あ、ごめんなさい。今のはなしで。"
90002170-174 = "は、はい……？"
90002170-175 = "あなた達はどこかに隠れていてください。"
90002170-176 = "え……？"
90002170-178 = "ご立派な[ruby=・]神[/ruby][ruby=・]様[/ruby]のお出ましです。"
90002170-186 = "あ、あわわわ……！"
90002170-190 = "さあ、早く。"
90002170-191 = "わ、分かりましたよ……！"
90002170-196 = "先生、アリスは準備できています。"
90002170-197 = "大丈夫です。謝らないでください。"
90002170-198 = "もしかするとアリスは……この瞬間、この時のために名前を定めたのかもしれません。"
90002170-202 = "お願いします、先生！やるからには元気よく！"
90002170-204 = "先生！私たちも最善を尽くします！"
90002170-205 = "シッテムの箱、プロセス最適化完了。#n――先生、ご指示を。"
90002170-208 = "[ns] \"よし、やってみよう！\""
90002170-218 = "はい！！！"
90002170-220 = "次回;あなたのための物語"
