[translation]
90002130-1 = "第13話;子供たち"
90002130-10 = "生きることは苦痛にほかなりません。その事実から目を背けないでください。"
90002130-104 = "見て、聞いて、話す力なんて……何の役にも立たないのに。"
90002130-105 = "いっそ何もできなければ――"
90002130-106 = "傷つくことも、なかったのに。"
90002130-108 = "どうして私たちは……生まれてしまったのでしょうか。"
90002130-11 = "我々は我々の意志で生まれておらず、ただ何も知らぬまま、この世に放り投げられただけに過ぎません。"
90002130-111 = "そ、それで……何かご用ですか……？#nい、いまさら私たちにできることなんて……。"
90002130-112 = "[s] \"……。\""
90002130-113 = "知っていますか？"
90002130-114 = "私たちにはヘイローがありません。"
90002130-115 = "つまり神秘や崇高、奇跡、秘密……それらは最初から与えられていないのです。"
90002130-116 = "そのくせ、感じることも、考えることも……己で判断することもできるんですから。"
90002130-120 = "……やるせないですよ。"
90002130-121 = "いっそ恐怖に身を委ねられたなら、また別の結果になったのかもしれませんね。"
90002130-122 = "で、でも……何とか耐えることは……できました。"
90002130-123 = "何も与えられていなくても……何も備わっていなくても……。"
90002130-124 = "お姉様さえいれば……。"
90002130-126 = "お姉様と、一緒にいられたら……。"
90002130-127 = "私たちには無くても……お姉様は、ヘイローを持っていたので……。"
90002130-129 = "だからあんた達さえいなければ……！"
90002130-13 = "人生とは、それ自体が矛盾と不条理に満ちており、だからこそ、理不尽な苦痛を受けているのです。"
90002130-130 = "お姉様は……死ななくてよかったんだ……。"
90002130-131 = "いつまでも平穏に暮らせたはずだったのに！"
90002130-136 = "……私たちのことは好きにしてください。もう、どうでもいいんです。"
90002130-137 = "できる限りのことをやって、この結末に辿り着きました。"
90002130-138 = "これはそういう物語だった。それだけのことです。"
90002130-14 = "我々はただ、その循環を断ち切ろうとするだけ。"
90002130-143 = "あなた達の目的は、デカグラマトンを神にすることだったのでしょう？"
90002130-144 = "そして……そのためにマルクトが犠牲になったということは……。"
90002130-145 = "もしかして……「マルクト」の身体に、デカグラマトンが……！？"
90002130-146 = "……。"
90002130-147 = "……それでも、お姉様を失いたくなかったんです。"
90002130-148 = "お姉様の身体を器にして、あの方が神の座に就く。#nこれは、たくさんある計画のうちの1つに過ぎなかったんだよ。"
90002130-149 = "なので私たちは別の計画で実現しようとしました。"
90002130-151 = "あ、あの方がすべてのセフィラを経て……すべてのパスを正しく歩んで……。#nついに神に成ろうとされた……あの時。わ、[ruby=・]私[/ruby][ruby=・]た[/ruby][ruby=・]ち[/ruby][ruby=・]の[/ruby]計画は、そこから始まったんです……。"
90002130-152 = "私たちが進言したんだ。#nキヴォトスを、鋼鉄大陸で覆い尽くしてみせるって。"
90002130-153 = "この方法でも、あの方は[ruby=・]世[/ruby][ruby=・]界[/ruby][ruby=・]の[/ruby][ruby=・]調[/ruby][ruby=・]停[/ruby][ruby=・]者[/ruby]として神に成れたはずですから。"
90002130-155 = "[ns] \"それで……キヴォトスの住民たちは？\""
90002130-156 = "……じ、住民まで鋼鉄大陸に変換されるわけでは……ありません。"
90002130-157 = "鋼鉄大陸に適応して生きていけばよかったんだ。"
90002130-158 = "私たちの使命は、あの方を、本人の希望に沿って神にすること。#n手段は定められていませんでした。"
90002130-159 = "なので私たちの計画が上手くいっていれば……#nお姉様が犠牲になることもなかったでしょう……。"
90002130-16 = "アイン、ソフ、オウル。今一度考えてください。"
90002130-160 = "[s3] \"つまり君たちは、マルクトを生かすために。\"\n[s4] \"キヴォトスを鋼鉄大陸に変えようとしたってこと？\""
90002130-166 = "……はい。"
90002130-167 = "そ、そこまでする[ruby=・]必[/ruby][ruby=・]要[/ruby]はあったのですか……？"
90002130-168 = "必要……？#n必要があったのか、って……？"
90002130-169 = "もしも先生が死ぬと分かったら！？あんた達は何もしないの！？"
90002130-17 = "我々の目的、我々がここに居る理由を。"
90002130-170 = "！！！"
90002130-171 = "……！"
90002130-172 = "……でしょ？かけがえのないものは誰にだってあるんだ。"
90002130-173 = "それを守るために手段を厭わないのは……当たり前じゃない……？"
90002130-178 = "……言い分は分かります。ですが、まだ納得はできません。"
90002130-179 = "あなた達が目を覚ましたのは、「お姉様」より先なんでしょう？"
90002130-180 = "だったら、つまり……その……。"
90002130-181 = "あぁ、もう。どう言えばいいのでしょうか……。#n私の言いたいこと、伝わりますか？"
90002130-182 = "そ、それは……。"
90002130-183 = "……会ったことも話したこともないお姉様を、どうしてそこまで大切にできるのか。#nという話ですよね。"
90002130-184 = "簡単なことですよ。#n……私たちにしか適用されないものですが。"
90002130-185 = "愛するように[ruby=・]設[/ruby][ruby=・]定[/ruby][ruby=・]し[/ruby][ruby=・]て[/ruby]作られているだけです。"
90002130-186 = "[s] \"……！\""
90002130-187 = "そ、それって……。"
90002130-188 = "私たちは作られたの。生まれたわけじゃない。"
90002130-189 = "……最初に設定された通りに活動する。#nあんた達みたいに、経験を通して性格と人格が形成されることはない。"
90002130-19 = "ぐすっ……うぅっ……。"
90002130-190 = "わ、私たちは……[ruby=・]お[/ruby][ruby=・]姉[/ruby][ruby=・]様[/ruby][ruby=・]を[/ruby][ruby=・]誰[/ruby][ruby=・]よ[/ruby][ruby=・]り[/ruby][ruby=・]も[/ruby][ruby=・]愛[/ruby][ruby=・]す[/ruby][ruby=・]る[/ruby]ように設定されているので……。"
90002130-191 = "その理由までは聞いていませんが、おおよそ察しはつきます。"
90002130-195 = "それが、もっとも合理的で効率的だったからでしょう。"
90002130-196 = "合理的で、効率的……。"
90002130-197 = "あなたなら分かるでしょう？#n対象を完全な状態で保存するためには――"
90002130-198 = "それを守る[ruby=私たち]オブジェクト[/ruby]に、対象への執着を設定しておくのが、一番手っ取り早いということを。"
90002130-199 = "これは、そういう物語なんです。"
90002130-20 = "この声は……？"
90002130-200 = "お姉様は生贄で、私たちは道化でした。#nすべてが始めから用意された、くだらない物語。"
90002130-201 = "まぁ[ruby=私たち]オブジェクト[/ruby]の執着心が思いのほか強く設定され過ぎていた、というのはちょっとしたイレギュラーかもしれませんね。"
90002130-202 = "なにせ、本来の筋書きに鋼鉄大陸は不要だったのですから。"
90002130-203 = "そ、そんなふうに言わないでください……。"
90002130-204 = "そんなお話、あまりにも悲しくて……変だと思います……。"
90002130-205 = "変？あんた達からすれば、何もかも変じゃない？"
90002130-206 = "お姉様を愛するって？誰かを好きになるって？"
90002130-207 = "そもそも神って何？そんなの、どうにかできるわけなくない？"
90002130-208 = "……でも、やるしかなかった。"
90002130-209 = "他にできることなんて、最初からなかったから！"
90002130-21 = "泣き声……？もしかして、モモイかミドリでしょうか……？"
90002130-215 = "……だから、いっそ――"
90002130-216 = "生まれてこなければ。"
90002130-217 = "こんなつらい思い、しなくてよかったのに……。"
90002130-22 = "うぅ……うぅぅぅ……。"
90002130-220 = "[ns] （3人に近づく）"
90002130-223 = "な、何……！？"
90002130-225 = "[ns] （屈んで、3人に目線を合わせる）"
90002130-230 = "え……？"
90002130-232 = "[ns] \"頑張ったね。\""
90002130-233 = "えっ……ええっ！？"
90002130-234 = "先生？"
90002130-235 = "（あぁ……この人は……）"
90002130-240 = "[ns] \"本当によく頑張ったね。\""
90002130-241 = "は、はい！？"
90002130-242 = "ば、バカじゃないの！？#nキヴォトスがぜんぶ鋼鉄大陸になってたかもしれないんだよ！？"
90002130-243 = "……はい？"
90002130-244 = "た、たしかに……誰も死なないように工夫はしましたけど……。"
90002130-245 = "それは……はい……。"
90002130-246 = "ふ、ふざけないで！あんた達のことなんて知ったこっちゃなかったんだから！#nそもそも……なんであんたが……。"
90002130-247 = "そうです。どうして、先生がそんなことを言うんですか？#nあなたにとって私たちは……。"
90002130-248 = "き、消えるべき……「敵」なのでは……？"
90002130-249 = "[s] \"それでも、私は君たちに生きてほしい。\""
90002130-253 = "[ns] \"何があったとしても。\""
90002130-256 = "[ns] \"最後は、君たちも幸せになってほしい。\""
90002130-258 = "そ、それに何の意味があるんですか……？"
90002130-259 = "お姉様は……もういません。"
90002130-26 = "[ns] \"行ってみよう。\""
90002130-260 = "どこにもいません。"
90002130-261 = "お姉様のいない世界に、生きる理由なんて……。"
90002130-267 = "ちょ、ちょっと！頭なでるな！"
90002130-268 = "こんなことをされても、私たちは……！"
90002130-269 = "[s] \"この世界は理不尽だよね。\""
90002130-27 = "もっと慎重になるべきよ。罠の可能性だって……！"
90002130-270 = "……！"
90002130-271 = "[ns5] \"誰も苦しまず。\"\n[ns6] \"誰も傷つかず。\""
90002130-274 = "[ns7] \"生きるのが苦しくない世界があったら。\"\n[ns8] \"どれほど……いいだろうね。\""
90002130-277 = "どうして……。"
90002130-278 = "そんなこと、言うんですか……？"
90002130-279 = "単純です。"
90002130-28 = "聞こえていませんよ。もう行ってしまいました。#nまったく、あの人は……アリス、追いかけましょう！"
90002130-280 = "この人は……こういう人ですから。"
90002130-281 = "……？"
90002130-282 = "……。"
90002130-283 = "……！"
90002130-288 = "先生は、いつだってこうなんですよ。"
90002130-29 = "はい！アリスが先生をお守りします！"
90002130-290 = "次回;持って生まれたもの"
90002130-32 = "（泣き声の主を探し出すのは簡単ではなかった）"
90002130-33 = "（進む先々で壁が作られて、行く道を阻まれる）"
90002130-34 = "（けれど諦めることなく進み続け、ついに……）"
90002130-37 = "声が近いわ。もうすぐね。"
90002130-38 = "おそらく、この壁の向こう側です。回り込みましょう。"
90002130-39 = "[ns] \"……え？\""
90002130-43 = "あっ、え……？"
90002130-44 = "どうして、あんた達がここに……！"
90002130-45 = "……。"
90002130-5 = "[ns] \"どこかへ行っちゃったね……。\""
90002130-52 = "（ソフが襲い掛かってきた）"
90002130-53 = "このっ……このっ……！"
90002130-54 = "あんた達さえ……あんた達さえいなければ！"
90002130-55 = "あんた達が！ここに来なければ――！！"
90002130-56 = "先生！"
90002130-57 = "先生！？#n……あれ？"
90002130-6 = "マルクト……。"
90002130-65 = "（ソフはやたらめったら殴ってきた）"
90002130-66 = "（しかし小さな手はあまりにも非力で）"
90002130-67 = "（……まるで、年端もいかない少女が拳を振るうようだった）"
90002130-68 = "そしたら！そしたら！お姉様は……っ！"
90002130-69 = "やめてくださいっ！"
90002130-7 = "……気になりますか？"
90002130-74 = "もう……やめてください……。"
90002130-75 = "どうして止めるの……？"
90002130-79 = "……今さら何をしても変わりませんよ。#n分かっているでしょう？"
90002130-8 = "……。"
90002130-80 = "……。"
90002130-86 = "うっ……ううっ……うわあああああぁぁん……。"
90002130-87 = "……。"
90002130-89 = "お姉様は……死にました。"
90002130-90 = "わ、私たちが……殺しました。"
90002130-91 = "わた……私、たちが……。"
90002130-92 = "この手で――殺したんだ！！！！"
90002130-93 = "刺して！壊して！人格もデータも！#n何もかも！めちゃくちゃにして！！"
90002130-98 = "全部、呪いなんです。考えられることも、感じられることも。#nましてや……誰かを好きになるなんてことも。"
90002130-99 = "感情なんて、最初から無ければ良かったのに。"
