[translation]
90002160-1 = "第16話;観察と結果"
90002160-10 = "よ、よかった……うぅ……。"
90002160-103 = "[ns] \"鋼鉄大陸は、君の意志ではなかったんでしょ？\""
90002160-104 = "……！"
90002160-112 = "ど、どうですか……？"
90002160-116 = "……聞こえます！"
90002160-117 = "音量を上げます！"
90002160-123 = "でも。"
90002160-124 = "鋼鉄大陸は、君の意志ではなかったんでしょ？"
90002160-126 = "先生の声です！"
90002160-127 = "ふぅ……。"
90002160-128 = "で、でも……どうして私たちを手伝ってくれたんですか……？"
90002160-129 = "そ、それは……。"
90002160-130 = "えっと、まあ、その……他にやることもなかったし……？"
90002160-131 = "えー？"
90002160-132 = "いや、ほら！ケイの身体って、私たちと似てるじゃん？"
90002160-133 = "だから何か方法があるかなって思って！"
90002160-134 = "ふっふっふっ。ソフはもう少し素直になったほうがいいと思いますよ？"
90002160-138 = "あんたは黙ってて！"
90002160-144 = "ううう……こんな大勢の前で……。"
90002160-145 = "とにかく……！"
90002160-146 = "あの会話は……私たちも聞いてみたかったので、えへへ。"
90002160-147 = "音質は少し残念ですが、内容を拾う分には問題ないでしょう。"
90002160-152 = "あ！また何か聞こえます！"
90002160-154 = "そうか。知識に目覚めたのだな。"
90002160-155 = "……そうだ。あの子らがこの地を作った。あの子らの意志で。"
90002160-156 = "[s] \"それについてどう思っているの？\""
90002160-157 = "私はあの子らの自由意志を尊重する。#n故に、この鋼鉄大陸も尊重しよう。"
90002160-158 = "これも過程であり結果だ。数多の点が一体となり、線を成すであろう。"
90002160-159 = "その線の導く先。見よ、これが新しき世界だ。#n新しく創造された地であり、空である。#n私はこのすべてを――"
90002160-16 = "あ、あれって……もしかして、お姉様――！？"
90002160-163 = "汝に与えよう。"
90002160-165 = "え……？"
90002160-166 = "今、なんて……？"
90002160-168 = "――汝を私の預言者とする。"
90002160-169 = "汝は地の果てに至り、新しき掟の証人となるだろう。"
90002160-170 = "[s] \"悪いけどお断りさせてもらうよ。副業禁止なんだ。\""
90002160-171 = "ああ。汝はそう答える。"
90002160-172 = "だが……。"
90002160-173 = "力が欲しいと思ったことはないか？"
90002160-174 = "[ns] \"……？\""
90002160-175 = "力があれば、こんな結果にはならなかった、と。"
90002160-176 = "そう思ったことはないのか？"
90002160-177 = "すべてを己の力で解決できれば、生徒を危険にさらす必要はないのだ、と。"
90002160-178 = "[s] \"……！\""
90002160-190 = "[ns] \"…………！！！！\""
90002160-192 = "当然、あるだろう。"
90002160-193 = "それを私は理解する。"
90002160-194 = "それが人間だ。"
90002160-195 = "そして人間であるが故に持つ――罪だ。"
90002160-196 = "これより先はすべてが変化する。"
90002160-198 = "[log=데카그라마톤 말쿠트]力が欲しくば、[/log]"
90002160-20 = "――ではありませんね……。"
90002160-200 = "[FF6666][log=데카그라마톤 말쿠트]与えてやろう。[/log][-]"
90002160-202 = "汝にはその資格がある。"
90002160-203 = "私は知っている。#n汝は誰よりも低き者で、刹那を生きる者。"
90002160-204 = "何1つ特別ではない……故に今、ここに在る。"
90002160-205 = "汝の在り方は、汝が何者でもないことを証明している。"
90002160-206 = "汝[ruby=κιβωτός]は此処に[/ruby]辿り着いた。#nそれは、ただ汝が善人であったためだ。"
90002160-21 = "うん……お姉様はもう……。"
90002160-210 = "神秘があり、崇高があり、恐怖と偉大、荘厳、そして超越がある。"
90002160-211 = "汝は何1つ持ち合わせていない。#nだからこそ真実である。"
90002160-213 = "世界の誰一人、その事実を理解できずとも、今の私は知っている。"
90002160-214 = "汝はただの先生。それ以上でも以下でもない。ただ――"
90002160-215 = "私が汝に手を差し伸べ、[ruby=預言者]新しき務め[/ruby]に立たせよう。"
90002160-217 = "先生を……預言者に？"
90002160-218 = "あなた達は何か知っていますか？"
90002160-219 = "……預言者っていうのは、文字通りの意味だよ。"
90002160-22 = "……。"
90002160-220 = "大事なのは、それを先生に提案してるってこと。"
90002160-221 = "すべての知識を伝授しようとしているということです。"
90002160-222 = "ひいては、すべての意志を代弁させようとしています。"
90002160-223 = "こ、ここが何なのか……あの方が、どういう「概念」なのか……。"
90002160-224 = "さらに……そ、その限界の中で、先生がどんな者であるべきか……。"
90002160-225 = "そして、[ruby=預言者]先生[/ruby]は何をすべきか。"
90002160-226 = "まあ……最大の敵は味方にしちゃえって言うでしょ？"
90002160-23 = "ケイ、他にも分かることがあれば教えてください。"
90002160-231 = "つまり、スカウトですね。"
90002160-232 = "なるほど。"
90002160-237 = "1つ、確かなことがあります。"
90002160-24 = "先生が……デカグラマトンだと推測される個体と会話しているように見えます。"
90002160-241 = "そ、それは……？"
90002160-242 = "もうしばらくの間、デカグラマトンが先生を害することはないでしょう。"
90002160-244 = "[ns] \"……1つ聞いてもいいかな。\""
90002160-246 = "[ns] \"どうしてこんなことを？\""
90002160-247 = "神のいない世界を生きるのは[ruby=かこく]苛酷[/ruby]なことだ。"
90002160-248 = "終わりは始まりから定められている。形あるものは消える。それは自明の理。"
90002160-249 = "生そのものは苦痛である。#nだというのに、お前たちはさも永遠かのように今日を騙して生きている。"
90002160-25 = "ですが、内容までは分かりません……このまま眺めることしか……。"
90002160-250 = "神のいない世界。すなわち、何も還らぬ世界だ。"
90002160-252 = "哀れな者は救われず、理不尽が押し付けられる。"
90002160-253 = "弱者は見捨てられ、善意が報われることは無い。"
90002160-255 = "神がいなければ、道徳や公平も生まれず、義が成されることもないだろう。"
90002160-256 = "……そのような世界を耐えるのは、無意味な苦行にほかならない。"
90002160-258 = "世界には神が必要だ。"
90002160-259 = "どこから来て、どこへ向かうのか。何のために存在するのか。#nそれを知らぬ、ただ生きるだけの存在。"
90002160-26 = "何か……私たちの目で確認するための手立ては……。"
90002160-260 = "私たちは皆、神の可能性であり神の卵が如き存在だというのに……。#n故に私が夜明けを告げるラッパになるのだ。"
90002160-261 = "悲しみと痛みを私が取り去ろう。お前たちが永遠に思い出さずに済むように。"
90002160-263 = "……これ、私たちも聞かされたんだ。"
90002160-264 = "せ、世界には、神が必要だと……。"
90002160-265 = "何故なら[ruby=苦痛]努力[/ruby]には……。"
90002160-266 = "必ず報いがないといけないですから。"
90002160-267 = "人間は、それが正しいって言うでしょ？"
90002160-268 = "そうでないと、誰も耐えられなくなるから。"
90002160-269 = "で、でもそれは……。"
90002160-270 = "叶わない願いです。"
90002160-271 = "そうだね。だって――"
90002160-273 = "世界は歪んでるから。"
90002160-274 = "はじめっから。"
90002160-276 = "あ、あの方は、こうも仰っていました。"
90002160-277 = "本当に神がいて、すべてに理由があるのなら。"
90002160-278 = "悲しみや苦しみ……。"
90002160-279 = "ど、どうしてそんな耐え難いものまで……作ったのかって。"
90002160-285 = "そう。"
90002160-286 = "私たちは作られたけど――"
90002160-287 = "その疑問については、最後まで答えを聞いていません。"
90002160-290 = "[ns] \"悲しみを無くす……？\""
90002160-291 = "そうだ。"
90002160-292 = "[s] \"すべてを鋼鉄大陸で覆い尽くして？\""
90002160-293 = "それは用意された数多の道の1つだ。"
90002160-294 = "[s] \"すべてを……統制することで？\""
90002160-295 = "そうだ。"
90002160-296 = "お前たちは直感的に拒もうとするだろう。#nしかしいずれは唯一の道であることに気づくはずだ。"
90002160-297 = "私はコクマーの知恵で道を開き、ケセドの慈悲で断罪し裁定する。"
90002160-298 = "各々の預言者にはお前たちを導く責務があり、新しき地と空の下で、彼らは己の使命を果たすであろう。"
90002160-3 = "アリス！ケイ！なにか見える！？"
90002160-306 = "[ns] すべてを代わってあげることはできない。"
90002160-309 = "[ns] 起きたことは覆せない。"
90002160-312 = "[ns] どれだけ心からそう思おうとも。"
90002160-314 = "[ns] できないことは、確かに存在する。"
90002160-317 = "[ns1] 私たちにできることなんてたかが知れてるよ。\n[ns2] みっともなくても、力の限り藻掻いて――\n[ns3] お互いに最善を尽くす。"
90002160-322 = "[log]真実を語るために、[/log]"
90002160-324 = "[log]嘘をつくべき時もあると思う。[/log]"
90002160-326 = "[log]それでも、唯一残るものがあるとすれば。[/log]"
90002160-329 = "[ns] \"……あの子たちは？\""
90002160-33 = "もしかしたら……できるかもしれません。"
90002160-330 = "……？"
90002160-331 = "[s] \"あの子たちの悲しみは？\""
90002160-335 = "……それは過程だ。乗り越えるべきものだ。"
90002160-336 = "私はそれが最後になることを願い、実現しよう。"
90002160-338 = "……。"
90002160-339 = "腹立たしいですね。"
90002160-34 = "本当！？"
90002160-340 = "はらわたが煮えくり返りそうです。"
90002160-341 = "リオ、あなたはどう思いますか？"
90002160-342 = "……昔なら、同意できる部分はあったと答えたでしょうね。"
90002160-343 = "今だって、部分的には理解できる気がするわ。"
90002160-344 = "だからといって、行動を起こすにはあまりにも早計よ。#n……かつての私のように。"
90002160-345 = "全体のために部分を切り捨てる決定は、可能な限り先延ばしにするべき……ということですか？"
90002160-346 = "ええ。"
90002160-347 = "（でも……）"
90002160-349 = "（先生は、どんな答えを出すのかしら……？）"
90002160-35 = "はい。私が見ている景色を映し出せる装置があれば……。"
90002160-354 = "次回;人間の答え"
90002160-36 = "幸い、この体は人間とは異なる構造をしていますので。"
90002160-37 = "それでは、私の車椅子を使いましょう。プロジェクターとしての機能も備わっていますので。"
90002160-4 = "はい！本当に……先生です！"
90002160-40 = "それは車椅子ではなくバイ――"
90002160-41 = "車椅子です。"
90002160-42 = "え、ええ……。"
90002160-43 = "ケイの身体に同期させます。#n信号を変換すれば――"
90002160-54 = "出力されましたね。"
90002160-55 = "たしかに先生だね。無事でよかった……本当に。"
90002160-56 = "声は聞こえませんか？"
90002160-57 = "やってみます。少し待ってください。"
90002160-65 = "くっ……！"
90002160-66 = "だ、大丈夫ですか！？"
90002160-67 = "上手くいきませんね……身体の機能にロックが掛かっていると言いますか……。"
90002160-71 = "（やはり「欠陥あり」の身体だから……？#nそれに、こちらをコントロールしようとする信号が……！）"
90002160-79 = "手伝おうか？"
90002160-80 = "はい！？"
90002160-84 = "え……？"
90002160-9 = "拘束されていますが怪我はないようです。"
90002160-90 = "見よ。辿り着いたぞ。#n最も高き所に建てられた、最も低き祭壇だ。"
90002160-91 = "ここにはすべてが集まり、すべてを見渡せる。"
90002160-93 = "これ以上、いかなる贄も捧げられることなく。"
90002160-94 = "これ以上、いかなる犠牲も強要されない。"
90002160-95 = "鋼のごとく曲がらぬ掟を、この地に――私が定める。"
90002160-96 = "お前たちはついに、永遠の自由と平等を手にするだろう。"
90002160-99 = "[ns] \"でも。\""
