[translation]
90002240-1 = "第24話;不離一体の空"
90002240-10 = "はい。離陸します。"
90002240-102 = "……。"
90002240-103 = "うっ……。"
90002240-104 = "うぅっ……こんなの、納得できないよ……。"
90002240-105 = "どうして……どうして……！"
90002240-106 = "[s] \"……。\""
90002240-111 = "[ns] \"君は、これから何がしたい？\""
90002240-112 = "……分かりません。"
90002240-113 = "これまで、考えたこともありませんでした。"
90002240-114 = "ですが――"
90002240-116 = "[log=아인]わ、私たちは、お姉様に生きてほしいんです。[/log]"
90002240-117 = "[log=소프]何があっても、お姉様だけは生き残って。[/log]"
90002240-120 = "[log=오르]もっと多くのものを見て、多くの人と出会って。[/log]"
90002240-121 = "[log=오르]多くを経験してください。[/log]"
90002240-124 = "[log=아인]私たちより、もっともっと――[/log]"
90002240-127 = "生きてほしいと、言われました。"
90002240-128 = "それが何なのか、どういう意味かは、まだよく分かりません。"
90002240-129 = "ですがアイン、ソフ、オウルが残した最後の言葉であれば……。"
90002240-130 = "そうすべきだと思うのです。"
90002240-131 = "作られて、目的を果たすこともできず、最後はこのように捨てられましたが……。"
90002240-132 = "そういうの、もういいんじゃないでしょうか。"
90002240-133 = "……？"
90002240-134 = "作られたのは、私も同じです。"
90002240-135 = "私も目的を失って、忘れて……最初からやり直すしかないと考えていますが――"
90002240-136 = "生きていけないことはないと思います。"
90002240-138 = "そ、そうです！自分が誰なのかは結局……自分で決めるしかないんです！"
90002240-139 = "……。"
90002240-140 = "あなた達にとっては、それほど難しくない問題なのかもしれませんが……。"
90002240-145 = "いいえ。私たちだって同じです。"
90002240-146 = "そうそう。簡単なら誰も苦労しないって。"
90002240-151 = "……。"
90002240-152 = "それより、そろそろ「あなた達」とか「我々」とかって区別するのやめない……？"
90002240-154 = "はい？ですが我とあなた達の間には……。"
90002240-156 = "そうじゃないですよ。"
90002240-157 = "どのように目を覚まして、生まれたかは関係ありません。#nみんな、同じだと思うんです。"
90002240-162 = "……。"
90002240-163 = "それでも、いい……のですか？"
90002240-164 = "[s] \"私はいいと思うけど……みんなはどう？\""
90002240-177 = "……。"
90002240-179 = "ありがとうございます。"
90002240-18 = "……。"
90002240-181 = "……。"
90002240-182 = "……。"
90002240-183 = "ミドリ？大丈夫？"
90002240-184 = "え？うん、大丈夫……だよ。全部無事に終わったんだし。"
90002240-185 = "……そうは見えないけど。"
90002240-186 = "……うん。"
90002240-187 = "やっぱりマルクトのこと？"
90002240-188 = "うん……マルクトさんに、アイン、ソフ、オウル……。"
90002240-189 = "……。"
90002240-19 = "なぜ、我を助けたのですか？"
90002240-190 = "私、ちょっと考えてみたんだけどさ。"
90002240-191 = "なんかすっごい事が起きるとするじゃん？"
90002240-192 = "だけど脱出ポッドが1つしか残ってない！"
90002240-193 = "私たちは……どうすればいいかな？"
90002240-194 = "だ、脱出ポッドが1つだけ……。"
90002240-195 = "お姉ちゃんなら……どうするの？"
90002240-196 = "うーん。"
90002240-197 = "うーーん……！"
90002240-198 = "うーーーん……！！！"
90002240-20 = "[s] \"そうすべきかなと思って。\""
90002240-202 = "なんか考えるの面倒になっちゃった！あとで考えるー！あははっ！"
90002240-203 = "お姉ちゃん！？"
90002240-207 = "なんだったの……もう……。"
90002240-21 = "我は、あなた達の敵でした。"
90002240-212 = "……。"
90002240-213 = "もちろん、ミドリに譲るんだよ。"
90002240-214 = "お姉ちゃんだからね。"
90002240-218 = "（これまでの疲れが出たのか、みんなぐっすりと眠っていた）"
90002240-219 = "（疲れはあったものの……目を閉じると何かを思い出してしまいそうで眠れなかった）"
90002240-22 = "[s] \"でも今は違う。\""
90002240-228 = "先生……。"
90002240-229 = "先生……。"
90002240-23 = "いつかまた敵になるかもしれません。"
90002240-231 = "[ns] \"どうしたの？無事に終わったのに……ちょっと元気ない？\""
90002240-232 = "無事に終わった……はい、そうかもしれませんけど……。"
90002240-233 = "いえ！やっぱり違います！だって、先生はそう思っていないじゃないですか！"
90002240-234 = "肯定。先生のバイタルも、表情も、まったくそう思っていないことを表しています。"
90002240-235 = "[s] \"……そんなに顔に出てた？\""
90002240-236 = "はい……その、見ている私すら……うぅっ……。"
90002240-237 = "肯定。私も……。"
90002240-238 = "[s6] \"そっか。\"\n[s7] \"それでも、2人が泣かなくたっていいんだよ。\""
90002240-24 = "[s] \"そうなの？\""
90002240-241 = "違うんです！これは仕方ないんです……！だって……。"
90002240-242 = "先生が泣かないから……大丈夫なふりをしているから……！"
90002240-243 = "[s8] \"そう思ってくれてありがとう。\"\n[s9] \"でも……こうすべきだと思うんだ。\""
90002240-246 = "どうして……ですか？"
90002240-247 = "[s10] \"起きたことを元には戻せない。\"\n[s11] \"後悔も言い訳も、許されないから。\""
90002240-250 = "……。"
90002240-251 = "……。"
90002240-252 = "それでは私たちには、何ができるのでしょうか？"
90002240-253 = "[s12] \"生きていくんだ。\"\n[s13] \"どんなにつらくても、苦しくても。\""
90002240-256 = "全部覚えて、背負っていくというのですか……？"
90002240-257 = "取りこぼしたものと、見落としたもののために……。"
90002240-258 = "[s14] \"うん。その先に何があるか分からなくても。\"\n[s15] \"……最後に、何1つ得られなかったとしても。\""
90002240-263 = "……。"
90002240-264 = "……。"
90002240-265 = "私たちが、一緒にいます。"
90002240-266 = "どんなことが起きようとも……。"
90002240-267 = "ですから、先生……。"
90002240-268 = "諦めないでください。"
90002240-269 = "先生が諦めない限り、私たちも、最後まで力を振り絞れますから。"
90002240-271 = "[ns] \"……うん。\""
90002240-277 = "[ns] \"ありがとう。\""
90002240-279 = "（たくさんの事があった）"
90002240-28 = "……。"
90002240-288 = "（思い返せば、一瞬だった）"
90002240-29 = "よく、分かりません。"
90002240-297 = "（それでも、語りつくせないほどの経験をした）"
90002240-3 = "全員乗りましたか？#nマルクトも乗っていますよね？"
90002240-30 = "鋼鉄大陸は、我のすべてでした。"
90002240-302 = "（そのすべてを後にして）"
90002240-309 = "（1人の新しい生徒と共に）"
90002240-31 = "あそこで目覚め、アイン、ソフ、オウルに出会いました。"
90002240-315 = "（ミレニアムサイエンススクールに帰った）"
90002240-35 = "……。"
90002240-36 = "もう、会えないのですね。"
90002240-37 = "もう……。"
90002240-38 = "……あぁ。"
90002240-39 = "もっと抱きしめてあげるべきでした。"
90002240-4 = "もちろん。いつでも出発できるよ。"
90002240-40 = "もっと頭を撫でて、もっと話をするべきでした。"
90002240-41 = "このような結末が分かっていれば……。"
90002240-42 = "もっと、たくさん……。"
90002240-43 = "[s] \"……。\""
90002240-48 = "先生？"
90002240-50 = "[ns1] \"本当に、もしもの話なんだけど……。\"\n[ns2] \"私が何もしなければ、あの子たちは生きていられたのかな。\""
90002240-54 = "……。"
90002240-55 = "結果は同じだったと思います。"
90002240-56 = "[s3] \"それでも、私が手を出さなければ。\"\n[s4] \"あの子たちは……。\"\n[s5] \"1秒でも長く生きていられたんじゃないかな。\""
90002240-60 = "責任を感じているのかしら？"
90002240-61 = "それも……背負うことのできない責任を。"
90002240-62 = "……。"
90002240-63 = "私は……冷たいことしか言えないわ。これが私の性なのでしょうね。"
90002240-64 = "だから、あえて言わせてもらうのだけれど――"
90002240-65 = "あの子たちは結局、キヴォトスを好き勝手に変えようとしていた。"
90002240-66 = "それには事情なり理由があって……あの子たちの思惑があった。"
90002240-67 = "けれど、鋼鉄大陸に変容したキヴォトスで生きるとは、どういうことだと思う？#nはたして……キヴォトスを生きる人々が耐えられるかしら。"
90002240-68 = "あの子たちは……過ちを犯したわ。かつての私のように。"
90002240-69 = "でもそれが、このような結果を迎えるほどのことかと言われると……。"
90002240-70 = "ごめんなさい……そこまでは、私もよく分からないわ。"
90002240-72 = "……。"
90002240-77 = "[ns] \"……リオの本心を聞きたいな。\""
90002240-79 = "……。"
90002240-80 = "これ以上失敗したくないと言ったことがあったわね。"
90002240-81 = "言い換えれば……後悔したくないという意味だったの。"
90002240-82 = "いま思えば、それが原因だったのでしょうね。#nすべての変数を統制しようとしたのも、すべての可能性に備えようとしたのも……。"
90002240-83 = "でも、結局……。"
90002240-84 = "リオ先輩……。"
90002240-85 = "ありがとうございます。"
90002240-86 = "え……？"
90002240-87 = "[ruby=つかつき]調月[/ruby]リオ……ありがとうございます。"
90002240-88 = "我の妹たちのために……悲しんでくれて。"
90002240-89 = "私はただ、納得できないことが……。"
90002240-9 = "ではトキ、お願い。"
90002240-90 = "そうですか。"
90002240-91 = "それならそれで、今は十分です。"
90002240-95 = "ケイも、先生も。"
90002240-96 = "ここにいる皆さんも。"
90002240-97 = "本当に……ありがとうございます。"
