[translation]
90002100-1 = "第10話;000、00、０"
90002100-2 = "鋼鉄大陸ー！"
90002100-3 = "こ、攻略戦……！#n……うぅ。"
90002100-4 = "せっかく新装備になったんだよ？もっと気合入れないと！"
90002100-5 = "で、でも……。"
90002100-6 = "お姉ちゃん、だる絡みしないで。ユズちゃんが困ってるでしょ。"
90002100-7 = "人聞きが悪い！#n私は、ユズを勇気づけるために言っているのに！"
90002100-11 = "そうです！勇気こそ、勇者にとって一番大事な武器なのです！"
90002100-12 = "あなたまで乗ってどうするんですか……。"
90002100-14 = "[ns] \"まずはビナーのエリアに向かうんだよね？\""
90002100-15 = "ええ。あのエリアには、鋼鉄大陸を守るファイアウォールが設置されているわ。#n突破に成功すれば、その先の攻略が幾分か容易になるはず。"
90002100-16 = "最初の目標は、ビナーのコアを確保して、鋼鉄大陸のネットワークへのアクセス権を得ること。#nそこから先は、先生の判断に任せるわ。"
90002100-17 = "その際は、2組に分かれて行動するのが良いかと。#nこの輸送船であれば、機動力は申し分ないですから。"
90002100-18 = "チームの編成は、その都度柔軟に変更していきましょう。"
90002100-19 = "でも、エリアを占領したあとは、必ずケイを呼ばないといけないんだよね？"
90002100-20 = "はい。そうすればケイが預言者のコアから情報を取り出して、#n私たちの戦力に換えてくれるはずです。"
90002100-21 = "……敵の能力を利用する生命体みたく言わないでもらえますか。"
90002100-22 = "あっ、ケイもそのゲームを知っているのですね！#nあれは本当に神ゲーです！"
90002100-24 = "[ns] \"ケイもゲーム好きなの？\""
90002100-25 = "そんなわけありません！#nこれはただ、アリスと同期した時の記憶と経験が残っているだけで――！"
90002100-26 = "そうでしたか……。ケイにとって、アリスの記憶は余計なものだったんですね……。"
90002100-27 = "ち、違います！#nえっと、私が言いたいのは、その……！"
90002100-28 = "大丈夫です……アリスは、そんなケイも大事にしたいです……#nケイが、アリスのことをどう思っていても……。"
90002100-29 = "だから違いますって！アリス、話を聞いてください！！"
90002100-30 = "ケイ、気にしないでください。アリスは大丈夫ですから……。"
90002100-31 = "アリス――！！"
90002100-37 = "（慌てるケイとは反対に、アリスはこちらを振り向くと――）"
90002100-38 = "（いたずらっぽく笑った……！）"
90002100-40 = "[ns] \"アリス、からかうのはそれくらいにしようね。\""
90002100-41 = "えへへ、ごめんなさい、ケイ。"
90002100-42 = "はい？からかう……？"
90002100-43 = "[ns] \"ケイって反応が大きいもんね……。\""
90002100-44 = "えへへ、そうなんです。"
90002100-45 = "……。"
90002100-46 = "…………。"
90002100-47 = "………………。"
90002100-48 = "先生――っ！！！"
90002100-50 = "では、いきましょうか。#nこの[ruby=あすま]飛鳥馬[/ruby]トキが、完璧なメイドとして先生を補佐いたします。"
90002100-51 = "その格好だとあんまりメイドと言えないような……？"
90002100-52 = "……完璧なエージェントとして先生を補佐いたします。"
90002100-53 = "切り替え早いね……。"
90002100-54 = "状況に応じて機敏に対応する。まさに優秀なエージェントだと思いませんか？"
90002100-55 = "ぶい。"
90002100-56 = "[s] \"そ、そうだね……。\""
90002100-57 = "あの、そろそろ始めますよ？"
90002100-58 = "全員、持ち場に戻ってちょうだい。"
90002100-59 = "では、先生に指揮権をお返しします。"
90002100-60 = "[s] \"緊張するね。\""
90002100-61 = "あら、指揮は手慣れているのでは？"
90002100-62 = "[s] \"それもそうだね。いつも通りやっていこう。\""
90002100-67 = "[ns] \"じゃあ、ビナー攻略戦を始めようか！\""
