[translation]
90002210-1 = "第21話;闘争"
90002210-102 = "……不敬な。"
90002210-13 = "枝打ちなんて望んじゃいない！！"
90002210-14 = "切り落とすべき矛盾なんて、絶対に納得できない！！！"
90002210-2 = "偽物の神風情が――！！！"
90002210-30 = "幸せになる。"
90002210-31 = "何があっても！必ず！"
90002210-32 = "矛盾の中でさ迷おうとも、どんな妨害があろうとも！"
90002210-33 = "愚かな。"
90002210-34 = "罪の対価は死だ。その結末はすでに決まっている。"
90002210-35 = "それがお前の考える結末なら――"
90002210-40 = "[log]自分たちで選んで、その結果自滅するなら……。[/log]"
90002210-43 = "[log]誰かに選択を委ねて守ってもらうより、ずっといい。[/log]"
90002210-46 = "どうなろうと、私は私の結末を求め続ける！！"
90002210-47 = "！？"
90002210-48 = "なぜ……動ける？ありえない。"
90002210-49 = "くぅっ、うぅっ……！"
90002210-56 = "せん、せい……？"
90002210-57 = "[ns1] \"……消えたものには追悼を。\"\n[ns2] \"悲しいことだけど、それが私たちの限界だよ。\""
90002210-60 = "危ないじゃないですか……下がっていてください……。"
90002210-61 = "[s] \"今回だけ、見逃してくれない？\""
90002210-62 = "……はぁ、言って聞くような人じゃないですよね、あなたは。"
90002210-63 = "なにゆえ自らの限界を試すのか。"
90002210-64 = "先生……！"
90002210-65 = "闘争は苦痛だ。それはやがて罪を犯す。"
90002210-66 = "[s3] \"知ってるよ。でもそれを奪わないでほしい。\"\n[s4] \"私たちから、可能性を消し去ろうとしないで。\""
90002210-69 = "……！"
90002210-7 = "お前が殺した！"
90002210-70 = "[s5] \"生きている以上、苦痛から抜け出す方法はないかもしれない。\"\n[s6] \"でも私は、それを肩代わりして欲しいとは思わない。\""
90002210-73 = "虫のように藻掻き、地べたを這いずることになってもか？"
90002210-77 = "[log]そうだね。[/log]"
90002210-8 = "お前が殺したんだ！"
90002210-80 = "[log]それでも私は、この道を選ぶよ。[/log]"
90002210-83 = "[log]転んで、藻掻いて、地べたを這いずることしかできなくても。[/log]"
90002210-86 = "[log]私たちは最後、必ず立ち上がるから。[/log]"
90002210-89 = "[ns] \"そうだよね、アリス？\""
90002210-9 = "その分際で神を自称するな！！"
90002210-90 = "……。"
90002210-91 = "はい。そうです、先生。"
90002210-92 = "ケイ、覚えていますか？#n勇者とは「みんなと一緒に進む職業」だとアリスが話したことを。"
90002210-93 = "もちろん覚えています。"
90002210-95 = "勇者はそうすることで――"
90002210-96 = "一人の力では届かない場所にも、みんなと一緒なら進める、と。"
