[translation]
90002140-1 = "第14話;持って生まれたもの"
90002140-3 = "で、でも私たちは結局……プログラムされた通りに動いているだけ、ですよ……？"
90002140-4 = "[s1] \"それを言うなら私たちも同じだよ。\"\n[s2] \"人間は、愛するようにプログラムされているからね。\""
90002140-7 = "えぇっ！？"
90002140-8 = "人間も同じ……そ、そうなんですか……？"
90002140-10 = "[log]親が子を愛するように。[/log]"
90002140-12 = "[log]子が親を愛するように。[/log]"
90002140-15 = "[log]ひいては――個が個を愛するように。[/log]"
90002140-18 = "でも、全員がそうとは限らないんじゃない……？"
90002140-19 = "[s] \"もちろん程度の差はあると思うよ。例外だって。\""
90002140-23 = "[ns3] \"だけど私たちも、[ruby=作られた時]生まれた時[/ruby]から行動をプログラムされている。\"\n[ns4] \"それを「遺伝子」と呼んでるだけだよ。\""
90002140-26 = "[ruby=プログラム]遺伝子[/ruby]……。"
90002140-27 = "でもそれって……そうだよね。淘汰された個体もたくさんいて……。"
90002140-28 = "そっか……[ruby=生命]人間[/ruby]はそうやって繋いできたんだね……。"
90002140-30 = "[log]だから大事なのは[/log]"
90002140-32 = "[log]愛すること。[/log]"
90002140-37 = "[log]君たちがマルクトを愛したという事実だと思うよ。[/log]"
90002140-40 = "その「愛」が最初から偽りだったとしてもですか……？"
90002140-41 = "どうせ世の中なんて嘘だらけって……あなたがそれを言うんですか？"
90002140-42 = "私たちが鋼鉄大陸をつくった理由は、全部、お姉様のためでした。"
90002140-43 = "ですがこの気持ちはもともと設定されていたもので……。"
90002140-44 = "……はい？「行動」に意味がある？"
90002140-45 = "理由が偽りだとしても……「やったこと」は揺るがない事実だ、と……？"
90002140-46 = "[s5] \"マルクトのために鋼鉄大陸を作ったんだよね？\"\n[s6] \"だったらその「行動」が、君たちを証明してくれるよ。\""
90002140-52 = "だ、大丈夫だと……言ってくれるんですか……？"
90002140-56 = "私たちは世界を敵に回したんだよ……？"
90002140-57 = "私たちは……頑張りました。ですがそれは[ruby=・]私[/ruby][ruby=・]た[/ruby][ruby=・]ち[/ruby][ruby=・]の[/ruby][ruby=・]た[/ruby][ruby=・]め[/ruby]です。"
90002140-58 = "先生からすれば、色々なことをめちゃくちゃにされたのではありませんか……？"
90002140-59 = "[s7] \"私は腹黒い大人だからね！\"\n[s8] \"前に言われたことをそのまま返すのが好きなんだけど――\""
90002140-63 = "[log]それはただ、[wa:500]情報が足りなかっただけ。[/log]"
90002140-66 = "[log]だから、[wa:1000]やり直せばいい。[/log]"
90002140-69 = "！！！"
90002140-74 = "……ええ。まだ間に合うわ。"
90002140-75 = "だから、手遅れになってしまう前に……。"
90002140-80 = "……。"
90002140-81 = "泣かないでください、と……それを言う資格がアリスにないのは分かっています。"
90002140-82 = "あなた達の悲しみを、アリスが完全に理解することはできないと思います。"
90002140-83 = "でも、一緒に悲しむことはできると思います。"
90002140-84 = "アリスも、先生を――"
90002140-86 = "ケイやモモイ、ミドリ、ユズ、エイミ、トキ、ヒマリ先輩にリオ先輩……。"
90002140-87 = "誰かを失うことになったら、耐えられないくらい悲しいですから。"
90002140-89 = "はぁ……知った風なことを言うじゃないですか。"
90002140-90 = "いいえ。アリスは何も知りません。"
90002140-91 = "おそらく……アリスにはできないと思います。"
90002140-92 = "……誰かの悲しみを、まったく同じように理解することは。"
90002140-93 = "だって、アリスには[ruby=・]設[/ruby][ruby=・]定[/ruby][ruby=・]さ[/ruby][ruby=・]れ[/ruby][ruby=・]て[/ruby][ruby=・]い[/ruby][ruby=・]な[/ruby][ruby=・]い[/ruby][/ruby]機能ですから。"
90002140-94 = "だからアリスは――アリスにできることをしようと思います。"
90002140-95 = "できること、ですか……？"
90002140-96 = "はい。"
90002140-101 = "アイン、ソフ、オウル。"
90002140-106 = "アリスと、友達になってください。"
90002140-110 = "と、友達！？"
90002140-111 = "！？！？"
90002140-112 = "……！"
90002140-113 = "はい。アリスは、みなさんと友達になりたいです。"
90002140-114 = "そして……アリスにも、一緒に悲しませてほしいです。"
90002140-115 = "うっ……！"
90002140-116 = "前に、先生が教えてくれました。"
90002140-117 = "悲しみに暮れている時。#n隣で一緒に泣いてくれる人がいると、悲しみに打ち勝つ力を得られるのだと。"
90002140-118 = "でも、お姉様は……。"
90002140-119 = "はい。"
90002140-120 = "もしもそれでも足りなければ……。"
90002140-121 = "どうしてもアリスたちが憎いのであれば……。"
90002140-122 = "その時は、そうだと言ってください。"
90002140-127 = "（ああ……）"
90002140-129 = "みなさんが何を感じても――"
90002140-130 = "アリスは頑張って……それを受け止めます。"
90002140-131 = "……アリスは覚えています。"
90002140-133 = "生きるのは苦痛だと話していたことを、鮮明に覚えています。"
90002140-134 = "その話には、正しい部分もあるのだと思います。#nなぜならこれも……先生が教えてくれましたから。"
90002140-136 = "……。"
90002140-137 = "明日はおそらく何かを失う日で、良いことなんて、そうそう起きない――"
90002140-138 = "人々が話すのは漠然とした希望であって、[ruby=明日]静かに迫る未来[/ruby]ではありません。"
90002140-142 = "そうね。未来は「期待」という錯覚を伴って、楽観視される傾向が強いものね。"
90002140-143 = "逆に過去は思い出として美化されていくわ。#nけれど、過ぎ去ったものは戻ってこない。"
90002140-144 = "そして現在とは、過去と未来の狭間に辛うじて存在する刹那。#n希薄すぎるあまり、知覚するのは限りなく難しい。"
90002140-145 = "曖昧模糊としたものに包み隠され続けているから……#nいざ現実を直視した時、人生に残るのは苦痛だけなのかもしれないわね。#n……貴女たちが言った通りに。"
90002140-146 = "ですが、先生は教えてくれました。"
90002140-147 = "それを放っておいてはいけないと。"
90002140-148 = "私たちはみんな幸せになるべきだと。"
90002140-149 = "幸せになることで……闘い続けるべきだと。"
90002140-150 = "まるで、ケイのように。"
90002140-151 = "はい！？！？"
90002140-152 = "ケイは、アリスの自慢の友達です。"
90002140-153 = "直面する理不尽に怒りを覚えて、どうにか解決しようと努力しています。"
90002140-154 = "その姿勢をアリスも見習いたいと思っています！"
90002140-155 = "……たまに小言を言ってくるのは怖いですが。"
90002140-156 = "いえ、それは全部アリスのためであって……。"
90002140-157 = "それでも怖いものは怖いです！"
90002140-158 = "はぁ……。"
90002140-162 = "そして……リオ先輩。"
90002140-163 = "私……？"
90002140-164 = "リオ先輩はいつだって、自分にできることを探しています。"
90002140-165 = "予想できるすべての可能性と、予想できない他の可能性に備えて、#nいつも入念に準備をしています。"
90002140-166 = "その途中で何かが失敗しても、絶対に挫けません。"
90002140-167 = "時には自分自身を投げ打ってでも、最悪を回避しようとします。"
90002140-168 = "アリスは……そういう人たちが一緒にいてくれて、本当に良かったと思います。"
90002140-169 = "ケイも、リオ先輩も、そしてアリスが知っているみんなも。"
90002140-170 = "もちろん、先生もです。"
90002140-171 = "だから――アリスは、絶対に諦めません。 "
90002140-172 = "絶対に諦めないことの大切さをアリスは学びました。"
90002140-173 = "アリスは何があっても、[ruby=闘い]幸せ[/ruby]を諦めません。"
90002140-174 = "……そして、それと同じくらいに、アリスはあなた達と友達になりたいです。"
90002140-175 = "とも、だち……。"
90002140-176 = "アリスはまだ見習い勇者です。"
90002140-177 = "未熟で、弱くて、自分でも悲しくなるときがあります。"
90002140-178 = "でも……隣にいるみんなに手を伸ばすことだけは、諦めません。"
90002140-179 = "それが――今のアリスにできる最善ですから。"
90002140-180 = "先生、覚えていますか？#n人生には大きな意味や目的は必要ないと、アリスに言ってくれたことを。"
90002140-184 = "[ns] \"うん……覚えてるよ。\""
90002140-185 = "それは、どうして……？"
90002140-186 = "なぜなら、もしも絶対に必要だったなら……#n意味や目的を見つけられなかった人生は価値がないことになってしまうからです。"
90002140-187 = "……。"
90002140-188 = "そんなの間違っていると思います。あまりにも悲しいです。"
90002140-189 = "ジョブや育成ルートが1つしかないゲームは、ただのクソゲーです。#n企画段階から失敗しています。"
90002140-190 = "アリスは悲しい気持ちになりたくないからこそ、他の誰かが悲しんでいる姿も見たくありません。"
90002140-192 = "人は誰かの幸せな姿を見て、自分も同じ気持ちになれます。"
90002140-197 = "誰かの苦しむ姿を見て、自分もそれに共感できるのです。"
90002140-199 = "……そんなの偽善だよ。錯覚にすぎない。"
90002140-201 = "他人の気持ちなんて、理解できるはずがない。"
90002140-202 = "たしかに、そうかもしれません。"
90002140-203 = "でも、お互いに支え合って生きていけると、アリスは思っています。"
90002140-204 = "先生が、アリスやケイ、リオ先輩、そして他のみんなに出会えてよかったと――"
90002140-205 = "――幸せだと、話してくれたように。"
90002140-206 = "アリスは、あなた達と話ができたこと自体、嬉しく思っています。#nだから――"
90002140-207 = "アリスと、友達になってください。"
90002140-208 = "この手を取ってくれたら……アリスはとても嬉しいです。"
90002140-209 = "そして、アリスが幸せなのと同じくらい、あなた達にも幸せになってほしいです。"
90002140-210 = "[ruby=闘い]幸せ[/ruby]こそ、私たちが絶対に諦めてはいけない、#n私たちにとって一番大事なものの1つですから。"
90002140-215 = "……これが[ruby=・]王[/ruby][ruby=・]女[/ruby][ruby=・]の[/ruby][ruby=・]言[/ruby][ruby=・]葉[/ruby]なんですね。"
90002140-216 = "はい！？#nそれは違います！アリスは王女なんかじゃありません！アリスはただのアリスです……！"
90002140-220 = "は、はい。それは分かってます……。#nわ、分かっているんですが、えっと……。"
90002140-221 = "私たちが言ってるのは、言葉そのものが力を持ってるってことだよ。"
90002140-222 = "聞く側が、自然と耳を傾けちゃうような……。"
90002140-223 = "外から与えられたものじゃなくて、内から生まれる権威のこと。"
90002140-224 = "それゆえに、絶対的な力を持っているとも言えます。"
90002140-225 = "で、でも……幸せ、ですか……。#nそ、それが何なのか……私たちにはまだ、よく分かりません……。"
90002140-226 = "……幸せがまだ残ってるかすら怪しいんだよね。"
90002140-227 = "それが果たして、私たちに手を差し伸べてくれるでしょうか。"
90002140-228 = "で、でも……。"
90002140-232 = "ありがとう、ございます。"
90002140-233 = "本当に……。"
90002140-240 = "あぅっ！？"
90002140-244 = "アイン！？"
90002140-250 = "くっ、脚が……！"
90002140-257 = "（倒れそうだった3人をなんとか支えた）"
90002140-262 = "せん、せい……？"
90002140-263 = "あーあ……搾りカスまで持っていこうとするんだ。"
90002140-264 = "ええ。役目を終えた道具は捨てられるものですから。#nははっ……。"
90002140-265 = "……どういう意味ですか？"
90002140-266 = "た、単純な話です。ただ――"
90002140-267 = "預言者も私たちも、このための道具に過ぎなかったんだよ。"
90002140-268 = "そして、目的が達成されたから……。"
90002140-269 = "貴女たちに……何が起きるの？"
90002140-270 = "あ、あの方が神としてキヴォトスに降臨したら……私たちは用済みで……。"
90002140-271 = "あ、あれ……？この話、しましたっけ……？"
90002140-272 = "どのみち、すぐに分かるでしょ。"
90002140-273 = "このまま機能を止められるか、吸収されて分解されるか……そんなところじゃないですかね。"
90002140-277 = "……。"
90002140-278 = "その、先生。やっぱり……。"
90002140-279 = "先生と皆さんだけでも……逃げるのはどうですか……？"
90002140-280 = "[s] \"え……？\""
90002140-281 = "はい……？"
90002140-282 = "わ、私たちがこんなことを言うのもあれですけど……。"
90002140-286 = "――ありがとうございます。"
90002140-288 = "頑張ったねと言ってくれて……嬉しかったです。"
90002140-289 = "私たちのことを見ていてくれて、嬉しかったです。"
90002140-291 = "……幸せになってほしいと言ってくれて……本当に、嬉しかったです。"
90002140-296 = "まあ……そうだね。"
90002140-297 = "そう難しく考えなくていいですよ。#nキヴォトスをめちゃくちゃにしようとした悪党は、墓穴を掘ってそのまま終わり！"
90002140-298 = "多分もっと大きな問題が差し迫ってますが……それはそのとき考えてください！#nワハハハ！"
90002140-299 = "ハハ、ハ……。"
90002140-303 = "……噓つき。"
90002140-304 = "わざわざ指摘しなくていいですから。"
90002140-305 = "まあ……よっぽどのことじゃない限り、そうしていたでしょうね……。"
90002140-306 = "でも――！"
90002140-310 = "どうしても腹が立って仕方ないんです！#nあなた達、人を馬鹿にするのも大概にしてください！"
90002140-311 = "えっ、ええ？ど、どうしてですか！？"
90002140-312 = "どうしても何も！全っ然平気じゃないくせに平気なふりをして！#n見え見えなんですよ！"
90002140-313 = "なのに逃げろですって！？#nアリスの言ったことを聞いてなかったんですか！？"
90002140-314 = "ふざけないでください！#n生きているんでしょう！？足搔いて、闘ってください！"
90002140-315 = "何度言わせれば気が済むんですか！#n待っていたって幸せは訪れません！"
90002140-316 = "望みがあるのなら！そして……それが何より切実な願いなのであれば！"
90002140-317 = "すべてを賭けて[ruby=闘え]行動しろ[/ruby]！"
90002140-322 = "望み……。"
90002140-323 = "そんなの……。"
90002140-324 = "……。"
90002140-329 = "ぐすっ……。"
90002140-330 = "お姉様に……会いたいです。"
90002140-331 = "何があっても……どんなことがあってもいいから……。"
90002140-332 = "もう一度、お姉様に会いたいです……。"
90002140-334 = "もっとお話したかったこと、たくさんあるのに……。"
90002140-335 = "もっと遊びたいことも、たくさんあるのに……。"
90002140-337 = "なのに……こんなお別れは……イヤです……。"
90002140-338 = "……。"
90002140-339 = "……。"
90002140-346 = "あっ……！"
90002140-347 = "うわっ！？"
90002140-351 = "気をつけてください！"
90002140-355 = "[ns] \"え……？\""
90002140-356 = "（その瞬間、足元の地面が文字通り[ruby=・]消[/ruby][ruby=・]え[/ruby][ruby=・]て[/ruby]しまった）"
90002140-360 = "先生！？"
90002140-361 = "せ、先生――！！！"
90002140-366 = "次回;新しき空、新しき地"
