[translation]
90002045-13 = "うわああっ！？"
90002045-14 = "きゃあっ！？"
90002045-16 = "モモイ、ミドリ、あっち見て。"
90002045-18 = "うあぁ……み、耳がぁ……って、あっち？"
90002045-19 = "鋼鉄大陸を隔てていた壁が……？"
90002045-2 = "[ns] \"よっし！\""
90002045-25 = "うん、消えたよ。"
90002045-26 = "……。"
90002045-27 = "ありがとう、先生。おかげで助かったよ。"
90002045-3 = "イェソドの信号、極限まで弱まっています！"
90002045-30 = "イェソド攻撃組、早く帰還してください！"
90002045-31 = "すでに回収を進めています。格納庫、聞こえますか？"
90002045-35 = "パンパカパーン！アリス、無事帰還しました！大きな壁をやっつけました！"
90002045-36 = "はい、よくやりました。"
90002045-38 = "ハッチの閉鎖を確認。エイミからも無事との連絡が届いているわ。これで――"
90002045-4 = "[s] \"やったか！？\""
90002045-43 = "！？"
90002045-44 = "リオ？どうかしましたか？"
90002045-45 = "壁のほうを見てちょうだい！"
90002045-46 = "イェソドの壁が……再生成され始めているわ！"
90002045-47 = "！！！"
90002045-52 = "今度はなに！？"
90002045-53 = "え……？#n壁が……内側から生成され始めて……このままじゃ……！"
90002045-55 = "走って！"
90002045-57 = "また！？"
90002045-58 = "お姉ちゃん早く！壁ができたら中に入れなくなっちゃう！"
90002045-63 = "ぜぇ、ぜぇ……！"
90002045-64 = "はぁ、はぁ……！"
90002045-65 = "ジャンプして！"
90002045-74 = "二人とも、大丈夫？"
90002045-8 = "ちょっ、そのセリフは――！！"
90002045-80 = "いたたた……なんとか入れた？"
90002045-84 = "わあぁ……。"
90002045-88 = "す、すごい……。"
90002045-89 = "夢の中みたい……。"
90002045-95 = "[ruby=いずみもと]和泉元[/ruby]エイミ、現場より報告。"
90002045-96 = "鋼鉄大陸の壁内に進入したよ。"
90002045-98 = "次回;前進基地"
