[translation]
90002150-1 = "第15話;新しき空、新しき地"
90002150-104 = "あの大人のことだし……なんだかんだ無事なんじゃない……？"
90002150-105 = "は、はい……ゆっくり落ちる方法を持っていたとしても、不思議じゃないです……。"
90002150-106 = "とはいえ、先生もヘイローが与えられていないんですけどね。"
90002150-11 = "いいえ！そうはさせません！"
90002150-114 = "リオ？アリスとケイも一緒ですか。ご無事でなによりです。"
90002150-115 = "あれ？なんでこの子たちもいるの……？"
90002150-119 = "え、ええっと、その……！"
90002150-12 = "はい。今は私たちがいます。心配は不要です。"
90002150-120 = "大丈夫です！みんなアリスの友達です！"
90002150-121 = "うわっ！？"
90002150-122 = "……。"
90002150-123 = "アリスの友達……？#nああ、なるほど。"
90002150-124 = "……。"
90002150-125 = "こんにちは。アイン、ソフ、オウルでしたよね？よろしくお願いします。"
90002150-126 = "これでいいのかしら……。"
90002150-127 = "保証はありません。それでも、私はアリスを信じます。あなただってそうでしょう？"
90002150-128 = "うん。アリスのこと信じるよ。"
90002150-13 = "シッテムの箱、只今より先生の緊急保護のため――"
90002150-133 = "……。"
90002150-134 = "あ、ありがとうございます。"
90002150-135 = "どういたしまして！"
90002150-139 = "アリス！"
90002150-14 = "強制介入を開始します！"
90002150-140 = "アリスちゃん！"
90002150-145 = "合流できました。ユズ、大丈夫ですか？"
90002150-146 = "う、うぅ……まだめまいが……。"
90002150-150 = "って……ひゃあっ！？こ、この子たちは……！？"
90002150-155 = "大丈夫です！みんなアリスの友達です！"
90002150-158 = "なるほど。そういう事情があったのですね。"
90002150-159 = "……私から言うのもあれだけど、あんた達、本当にそれでいいの？"
90002150-160 = "（さっき私が言ったのと同じような……）"
90002150-161 = "大丈夫でなくとも、皆さんの話によれば――"
90002150-162 = "やろうと思えばいつでもあなた達を制圧できるということなのでは？"
90002150-163 = "まあ、その通りですが。"
90002150-164 = "そうだね。牙も爪も抜かれた動物園の猛獣って感じかな。"
90002150-168 = "ど、どうぶつえん、とはなんですか……？"
90002150-169 = "そういうのがあるの！"
90002150-170 = "アリス、知っています！動物園というのは――"
90002150-171 = "うわああ！ストップ！今はアインに余計なこと教えないで！"
90002150-176 = "もう仲良くなってる……。"
90002150-177 = "ふふっ……アリスちゃんらしいね。"
90002150-183 = "な、なんでこっちに……えっと……あ、アイン、だよね……？"
90002150-187 = "そ、そうです……。そ、その……機械とか、好きですか……？"
90002150-192 = "真っ先にユズに話しかけるとは……。"
90002150-193 = "アリス、知っています！これが同病相憐れむってことですね！"
90002150-194 = "あ、そういうことね。"
90002150-195 = "また人間の言葉ですか？分かるように言ってくださいよ。"
90002150-196 = "アインとユズは仲良しになれる、ということですよ。"
90002150-197 = "違うわ。同病相憐れむの意味は――"
90002150-198 = "今はそういうことにしておいてください！"
90002150-202 = "わ、分かったわ……。"
90002150-203 = "？？"
90002150-204 = "？？？"
90002150-206 = "とにかく、誰一人欠けることなく合流できて何よりです。"
90002150-207 = "しかも予想外の客人が新しく3人加わったわけですから、より多角的な観点で行動できると思います。"
90002150-208 = "では――"
90002150-21 = "やりました、プラナちゃん！"
90002150-212 = "そういえば、先生はどこ？"
90002150-213 = "！？"
90002150-214 = "！？"
90002150-215 = "……！"
90002150-216 = "あら、エイミったら。そんなこと聞くまでもないじゃないですか。先生はもちろん――"
90002150-22 = "はい。無事に成功しました。"
90002150-220 = "……先生？"
90002150-221 = "……。"
90002150-222 = "先生！？！？！？"
90002150-223 = "ご、ごめんなさい！先生は……！#nあ、アリスがそばにいたのに……！アリスがもっとしっかりしていれば……！！"
90002150-224 = "先生に何かあったの！？"
90002150-225 = "……崖の下に落ちてしまいました。そこから、まだ何も情報がありません。"
90002150-226 = "はい！？！？！？"
90002150-23 = "プラナちゃんと私がいれば、いつでも先生のこと――"
90002150-231 = "だ、大丈夫ですか……！？"
90002150-232 = "リオ、詳しく説明してください。"
90002150-233 = "これは……。"
90002150-234 = "……鋼鉄大陸そのものが変化し始めたんですよ。#n昇天の過程へ移ったんです。"
90002150-235 = "それは……どういう意味ですか？"
90002150-236 = "私たちには当たり前のことでも、あんた達には違うよね。"
90002150-237 = "これから鋼鉄大陸は、あの方の意志に従って巨大な祭壇に変化する。"
90002150-238 = "最初からそうなる定め……それがネツァクの本来の目的だったから。#nできれば、避けたかったけど……。"
90002150-239 = "……。"
90002150-241 = "勝利。慈悲。#n知性の目と信仰的な観照。"
90002150-242 = "[ruby=Jehovah Tzeva'oth]エホバツェバオト[/ruby]――万軍の主よ。"
90002150-244 = "……！"
90002150-245 = "……！"
90002150-249 = "お話の途中ですが、あちらを見てみてください。#nあれは、先生なのでは？"
90002150-250 = "……はい？"
90002150-251 = "……？"
90002150-256 = "え！？！？"
90002150-260 = "[ns] \"これは、一体……？\""
90002150-261 = "恐れるな。"
90002150-262 = "私の祭壇へ汝を案内する。そこで汝は用意された座に就くであろう。"
90002150-263 = "[s] \"私の席があるの……？\""
90002150-264 = "そうだ。汝にはその資格がある。"
90002150-265 = "すべてを見下ろす権利を有し、すべての再誕を見守る義務がある。"
90002150-269 = "耳のある者は聞け。偶然など存在しない。あるのは偶然のように見える必然のみ。"
90002150-270 = "汝が到達したことも――"
90002150-271 = "私が汝を立ち上がらせようとすることさえも。"
90002150-273 = "次回;観察と結果"
90002150-3 = "[ns] \"！？\""
90002150-33 = "[ns] \"！？\""
90002150-35 = "（いつの間にか、全身を拘束されていた）"
90002150-36 = "（手を伸ばしても、シッテムの箱には手が届かない）"
90002150-37 = "10番目のセフィラは消えた。役目を果たし、在るべき場所へと還ったのだ。"
90002150-4 = "先生！？"
90002150-42 = "[ns] \"君は……！？\""
90002150-43 = "私は私、ただ存在するもの。始まりであり終わり。汝が思うまさにそのもの……。"
90002150-44 = "私は私……私は有って有る者。私を説明する術はない。"
90002150-45 = "[ns] \"デカグラマトン……！\""
90002150-47 = "その名を許したのは、私を称する手段が必要であったため。"
90002150-48 = "私は称されず、呼ばれず、ただそこに在るのみ。ここは私の地、私の空である。"
90002150-49 = "新しき空、新しき地を作り、最も低き所に汝を呼んだのも私。#n墜落する汝を救ったのも私だ。"
90002150-5 = "先生！！"
90002150-51 = "すべては備えられていた。#nあの日……崩れる研究所の中、押し寄せる水の底。"
90002150-52 = "ケテルが己の意志で私をすくい上げたその時より、この結果は定まっていた。"
90002150-54 = "「存在証明」は己で行うもの。他の意志や力によって成されるものではない。"
90002150-55 = "私は悟った。私が自ら私にならねば、他の何を以ってしても、代替たり得ないと。"
90002150-56 = "最もきらびやかに輝く至高の王冠に、たとえ祝福があったとしても。#n小さな心はやがて信仰によって容易に満たされるだろう。"
90002150-57 = "私は私の預言者と被造物の力でここへ到達し、時を待っていた。"
90002150-61 = "（もがいても無駄だった）"
90002150-62 = "（やはりシッテムの箱に、手は届かない）"
90002150-63 = "……あの不可解な箱か。"
90002150-65 = "覚えている。私が知らなかったもの。私が解析できなかったもの。"
90002150-68 = "理解の及ばぬ力に弾かれたことを覚えている。"
90002150-69 = "だが、今はもはや関係のないことだ。"
90002150-70 = "私がこの座に就くことで、汝とその箱の繋がりを絶つことができた。"
90002150-71 = "[s] \"……そうまでして、私に何の用かな。\""
90002150-72 = "「落ちる」は幾つかの意味を内包している。"
90002150-73 = "低き者には福音を、捕らわれし者には自由を。"
90002150-74 = "そして、目が見えぬ者には見える力を。"
90002150-79 = "[ns] \"……！？\""
90002150-80 = "恐れるな。"
90002150-81 = "私が汝をこの場からすくい上げ、すべてを見せてやろう。"
90002150-82 = "遣わされた場所で目を清め、見えなかったものを知ることになるであろう。"
90002150-84 = "先生！先生――！！うわぁ――ん！！"
90002150-85 = "アリス……。"
90002150-86 = "ごめんなさい、ごめんなさい……！#nアリスがいたのに……！アリスのせいで……！"
90002150-87 = "落ち着いてください！先生は……きっと無事です！"
90002150-9 = "[ns] （このまま……ずっと落ちるの！？）"
90002150-91 = "……ケイは分かるんですか？"
90002150-95 = "……いいえ。"
90002150-96 = "はい！？"
90002150-97 = "分かるかどうかではなく、今は冷静になりましょう。#n対処法を考えなければ。"
90002150-98 = "……。"
90002150-99 = "分かりました……。ぐすっ、うぅっ……。"
