[translation]
90002050-1 = "第5話;前進基地"
90002050-4 = "これが最後のノートパソコンです。こちらに置きますか？"
90002050-5 = "ええ、お願い。"
90002050-11 = "ここの風景って……。"
90002050-12 = "うん。デザインのインスピレーションになる……。"
90002050-13 = "[s] \"文字通り、鋼鉄でできた大陸だね。\""
90002050-15 = "あの子たち、案外いいネーミングセンスを持っていると思うわ。"
90002050-16 = "（いい……？）"
90002050-17 = "（センス……？）"
90002050-18 = "そ、それより……どうして外で準備しないといけないんですか……？"
90002050-19 = "鋼鉄大陸の特殊性が原因よ。"
90002050-20 = "特殊性、ですか？"
90002050-21 = "分析した限り……#nこの瞬間にも、私たちの位置や情報は、リアルタイムで把握されています。"
90002050-23 = "えっ、ハッキングされてるってこと！？誰に！？"
90002050-24 = "もちろん――"
90002050-25 = "鋼鉄大陸そのものによ。"
90002050-26 = "そんなことができるんですか……？"
90002050-27 = "ここの地面――いえ、そもそも地面かどうか怪しいですが。"
90002050-28 = "鋼鉄大陸の地面は、巨大な回路や機械装置、コンピューターで構成されています。"
90002050-29 = "そのため、私たちは一挙手一投足を監視されていると言っても#n過言ではありません。"
90002050-30 = "じゃあ……この床とか、あっちの壁とか、ビルみたいに見えるあれとかも……#n全部が私たちを見てるってこと？"
90002050-31 = "そういうことです。"
90002050-32 = "何か、対抗する方法はないんですか……？"
90002050-33 = "もちろんあります。ちょうど、ヒマリとリオが対応しているところです。"
90002050-39 = "簡潔に言えば……この場所を[ruby=・]占[/ruby][ruby=・]領[/ruby]するわ。"
90002050-40 = "この辺りの主導権を少し、あの子たちから電子的に借りるのです。"
90002050-41 = "半永久的な権限の移動、とでも言いますか。"
90002050-42 = "[s] \"どれくらいかかりそう？\""
90002050-44 = "やってみないと分からない。"
90002050-45 = "でも、占領中はむやみに移動できないと思う。#n完了するまで、輸送船のリソースを演算装置に割り当てなきゃいけないから。"
90002050-46 = "つまり、ここでしばらく足止めということですね。"
90002050-47 = "足場を固めるために。"
90002050-48 = "ええ、その通りよ。"
90002050-53 = "分かりました。では最大限の警戒態勢で、ここをお守りします。"
90002050-54 = "はい！アリスもついていきます！"
90002050-55 = "ありがとうございます。皆さん頼もしいですね。"
90002050-56 = "じゃあ、私は辺りを探索してみるね。#nデカグラマトンの兵とかレイバーみたいなのが襲ってくるかもしれないし。"
90002050-57 = "あまり遠くまでは行かないでちょうだい。戦力が分散するわ。"
90002050-58 = "うん、分かった。"
90002050-61 = "イェソドが……突破されました。"
90002050-68 = "……一応、この場合のシナリオも想定してはいましたが、その方向に進めますか？"
90002050-69 = "……ソフ？"
90002050-79 = "こんにちは、ソフ。今回は1人ですか？"
90002050-80 = "……。"
90002050-81 = "なにか、言いたいことがあるのですね？"
90002050-82 = "お姉様……。"
90002050-83 = "念のため、聞かせてください。"
90002050-84 = "イェソドは、どうなりましたか？"
90002050-85 = "……！！！"
90002050-86 = "大丈夫ですよ。"
90002050-87 = "で、でも……もう……！"
90002050-88 = "大丈夫です。心配しないでください。"
90002050-89 = "私の……ぜんぶ、私の、せいで……。"
90002050-95 = "お、お姉様！？#nそんな……強く抱きしめたら、息が……！"
90002050-96 = "しーっ。少しだけ、このままで。"
90002050-97 = "うっ……ううっ……！"
90002050-98 = "よしよし。"
90002050-101 = "……落ち着きましたか？"
90002050-102 = "うん……。"
90002050-103 = "では、問題解決に移りましょう。"
90002050-104 = "我にできることはありますか？"
90002050-105 = "……！"
90002050-106 = "驚かなくていいのですよ。"
90002050-107 = "ソフが何を望んでいるのか、我には分かります。#n我は、ソフの姉なのですから。"
90002050-108 = "そして、なぜソフが何も言ってくれないのかも分かります。#nソフは、我の妹ですから。"
90002050-109 = "ですから、大丈夫です。我もまた、我にできることをしますので。"
90002050-115 = "私たちは――お姉様を失いたくない！"
90002050-120 = "お姉様を失うのは……嫌だよ。"
90002050-121 = "ええ、分かっています。"
90002050-122 = "アイン、ソフ、オウル。#nあなた達が、ゾーハルの依代に我を案内したのも、それが理由でしょう？"
90002050-123 = "我にはもう、これ以上のメンテナンスなど要らないというのに。"
90002050-124 = "うぅっ……！"
90002050-125 = "優しいソフ。悲しまないでください。"
90002050-126 = "我は知っています。そして、何をすることが「次善の策」なのかも。"
90002050-127 = "ですから、心配しないでください。すべて上手くいきます。"
90002050-128 = "速やかに、終わらせてきますので。"
90002050-129 = "お姉様……。"
90002050-131 = "うーん、本当にそれで足りますかね？"
90002050-132 = "！？"
90002050-133 = "……。"
90002050-138 = "……どうして、ここに。"
90002050-139 = "なにを今更。私たちが行く場所なんて、限られているでしょう？"
90002050-140 = "確率や変数を計算して、最も可能性の高い場所に来ただけですよ。"
90002050-141 = "そんなことより……ソフ。私たちが最初に交わした約束、まだ覚えていますか？"
90002050-142 = "なにがあっても、「その時」が訪れるより前には、お姉様を外に出さない。#n――そうでしたよね？"
90002050-143 = "……。"
90002050-144 = "そして、私たちが今こうしているのは、「その時」の到来を望まないからだったはずですが。"
90002050-145 = "……。"
90002050-146 = "考えてもみてください。#nこのことを他の預言者たちに知られたら、どう言い訳するつもりですか？"
90002050-150 = "……ごめん。ぜんぶ私のせい。"
90002050-151 = "でも……あの人たちを止めないと。"
90002050-152 = "イェソドが突破された。あんたもその意味は分かってるでしょ？"
90002050-153 = "……ええ。アインなんて気絶したくらいですし。"
90002050-154 = "あんたの言う通りだよ。私たちはお姉様に頼っちゃダメ。"
90002050-155 = "でもここで何もしなかったら、結局、もっとお姉様に頼ることになっちゃう。"
90002050-156 = "もしそうなれば……私たちは、「その時」の到来を阻止できなくなる……。"
90002050-157 = "……。"
90002050-159 = "オウル。ソフは――"
90002050-161 = "分かっていますとも。私だって、別に問い詰めるつもりはありません。#nただ――"
90002050-162 = "ソフをからかってみたかっただけです！"
90002050-163 = "ちょっと！"
90002050-165 = "やはり、オウルは優しいのですね。"
90002050-167 = "ソフ、その拳は一旦下ろしておいてください！#n大事な話があってきたんですから。"
90002050-168 = "また変なこと言ったら本当にぶつからね……。"
90002050-169 = "では、本題に入りましょう。お姉様の出撃には、いくつかの難点があります。"
90002050-170 = "まず大前提ですが、お姉様の出撃を、他の預言者に悟られてはいけません。"
90002050-171 = "うん……。"
90002050-172 = "ですが出撃のためには、鋼鉄大陸の全エネルギーをお姉様に集約させる必要があります。"
90002050-173 = "この時点で矛盾する以上、両立は不可能です。"
90002050-174 = "そう……だね。"
90002050-175 = "状況は理解できましたか？"
90002050-176 = "分かってるって……。それで？"
90002050-177 = "即ち――ここからは私の出番というわけです！"
90002050-178 = "何か方法があるの？"
90002050-179 = "ちょっとだけ、預言者たちを[ruby=・]ご[/ruby][ruby=・]ま[/ruby][ruby=・]か[/ruby][ruby=・]し[/ruby][ruby=・]て[/ruby]おきますよ。#nこういうの、得意分野ですし？"
90002050-180 = "それ……味方を騙すってこと！？"
90002050-181 = "どうせ、人間のことわざか何かで、似たようなものがあるのでは？"
90002050-182 = "まぁ……「敵を欺くにはまず味方から」とか……。"
90002050-183 = "やっぱりあるんですね。#nとはいえ、時間厳守です。ごまかしておくのにも、限界がありますので。"
90002050-184 = "もしオーバーすれば、もう取り繕うことはできません。"
90002050-186 = "オウルもこう言っています。ソフ、よろしいですね？"
90002050-191 = "……ありがとう。"
90002050-197 = "な、なんですか？急に手を差し出して……。"
90002050-198 = "この手を握って上下に揺らせば、握手になる。#n大事な約束とか決意を固めたとき、人間はこれをするらしいよ。"
90002050-199 = "……またそれですか。まあ、いいでしょう。"
90002050-200 = "では、我もしていいですか？その「握手」というものを。"
90002050-201 = "えっ……う、うん……。"
90002050-202 = "……良いですね。#nソフもオウルも、より距離が縮まった気がします。"
90002050-207 = "あ、あの……ネツァクちゃん……鋼鉄大陸のことは、どうするつもりですか……？"
90002050-208 = "わっ！？"
90002050-209 = "アイン！？"
90002050-210 = "身体はもう大丈夫ですか？"
90002050-215 = "えへへ、はい！ちょっとめまいがしただけで……もう大丈夫です！"
90002050-216 = "それより、さっきの話ですが……他のみんなには隠し通せても……#nネツァクちゃんには無理だと、思います。"
90002050-217 = "ネツァクちゃんは……鋼鉄大陸そのもの、ですから……#n気づかないわけがないので……。"
90002050-219 = "言われてみれば……。"
90002050-220 = "どうにかならないの？"
90002050-221 = "合理的に考えてくださいよ。できると思いますか？"
90002050-222 = "うっ、今回ばかりは言い返せない……。"
90002050-224 = "えへへ……だ、大丈夫です！#nネツァクちゃん……今回だけは見逃すって言ってくれました！"
90002050-225 = "え、本当？"
90002050-226 = "はい！でも次は難しいかもって……。"
90002050-227 = "1回あれば十分、ですよね？"
90002050-229 = "……！"
90002050-230 = "もちろん！"
90002050-232 = "では、アイン、ソフ、オウル。"
90002050-236 = "我の初出撃を、見届けてください。"
90002050-239 = "はい！"
90002050-241 = "次回;マルクト"
