[translation]
90002040-1 = "第4話;イェソド"
90002040-104 = "か、間一髪……。"
90002040-105 = "ありがとうございます、エイミさん。"
90002040-107 = "ううん。こちらこそ。"
90002040-108 = "じゃあ、先生。"
90002040-109 = "しっかりやってよね。"
90002040-114 = "これで最高速度ですか！？"
90002040-115 = "はい。これ以上回転数を上げればエンジンが爆発してしまいます。"
90002040-116 = "オーグメンターはダメですか？"
90002040-117 = "もって数秒ですが……いいんですか？"
90002040-118 = "許可します！"
90002040-119 = "分かりました。ゲートを開きます！"
90002040-126 = "では皆さん、イェソドの上でお会いしましょう。"
90002040-127 = "アリス、出撃します！"
90002040-133 = "イェソド攻撃組、降下開始しました。"
90002040-134 = "先生に指揮権をお返しします。よろしくお願いします。"
90002040-135 = "[s] \"エイミたちが無事なうちにケリをつけるよ！\""
90002040-16 = "これで1回……。"
90002040-17 = "うっ！？"
90002040-22 = "脚が……！"
90002040-23 = "瓦礫に、挟まって……！"
90002040-27 = "ふっ、んっ、ふうぅっ……！"
90002040-28 = "ちょっと抜けそうにないね……。"
90002040-3 = "こういうのは相手しやすいんだけど。"
90002040-37 = "……！！！"
90002040-38 = "（イェソドが、また腕を上げた）"
90002040-39 = "（包囲して退路を断って……味方ごと押し潰すつもりか）"
90002040-4 = "……あの腕、大きすぎるんだよね。"
90002040-40 = "（効率的ではあるね。また作ればいいわけだし）"
90002040-41 = "（でも、私は……）"
90002040-42 = "ちょっとの怪我は覚悟してでも――！"
90002040-54 = "……え？"
90002040-59 = "大丈夫！？"
90002040-60 = "お姉ちゃん！3で動かすよ……！"
90002040-61 = "いち、に――"
90002040-66 = "――さんっ！！！"
90002040-72 = "……モモイ？ミドリ？"
90002040-74 = "へっへん！助けに来たよ！先生に頼まれてね！"
90002040-75 = "大丈夫ですか？"
90002040-77 = "うん。ありがとう、二人とも。"
90002040-78 = "それと……。"
90002040-83 = "うん？"
90002040-84 = "はい？"
90002040-86 = "いますぐ、振り向かずに右側へ全速力で走って。"
90002040-88 = "どうして――えっ！？"
90002040-96 = "きゃあああっ！？"
