[translation]
90002090-1 = "第9話;Dress Up"
90002090-10 = "えへへ。ありがとうございます。よかったです……。"
90002090-100 = "ありがとう。おかげで助かったよ。"
90002090-101 = "……。"
90002090-102 = "そういえば、元々こういう人でしたよね……忘れていた私の落ち度です……。"
90002090-103 = "それはさておき、エイミもメイン武装を変更しました。#nバッテリーを使うエネルギー武器という点では、トキと共通しています。"
90002090-104 = "もちろん、出力やバッテリーの容量は全然違いますが。"
90002090-105 = "エイミ用のバイザーは、手早く支援ポイントを見極められるように追加した#n[ruby=HUD]ヘッドアップディスプレイ[/ruby]です。"
90002090-106 = "バイザーも武器と同じバッテリーで駆動するため、バックパックがトキのものより大型になっています。"
90002090-108 = "先生から見て、どうかな。"
90002090-109 = "え？効率的に見える？#nそっか、うーん……。"
90002090-110 = "……。"
90002090-111 = "[s] \"あれ、どうしたの？\""
90002090-112 = "うーん、今までなら最高の褒め言葉だったのに……。"
90002090-113 = "自分でも不思議なんだけど……ちょっと別のが聞きたいな。"
90002090-114 = "例えば……。"
90002090-118 = "……。"
90002090-119 = "かわいい……とか？"
90002090-121 = "！？"
90002090-122 = "！？"
90002090-127 = "[ns] \"よく似合ってるし、とってもかわいいよ。\""
90002090-128 = "うん。"
90002090-129 = "ありがとう、先生。"
90002090-131 = "ミドリ。私いま、ものすごく恐ろしい光景を目にした気がします……。"
90002090-132 = "そ、そんな風に言っちゃダメだよ！"
90002090-133 = "分かっていますが……。"
90002090-137 = "……。"
90002090-138 = "ぐああー！次！次です！#n待ちきれなくてルンルンしている人。出番ですよ。"
90002090-141 = "ふふふ。いかがですか？"
90002090-142 = "[s] \"えっと……これは失礼かもだけど……。\""
90002090-143 = "はい？"
90002090-144 = "[s] \"寒くない……？\""
90002090-145 = "あら、何をおっしゃるのかと思いきや。"
90002090-146 = "この超天才戦闘系万能病弱美少女ハッカーが対策を講じないわけがありません。"
90002090-147 = "防寒や防水を始めとした、環境への適応性はもちろんのこと……#nか弱さに清楚さまで兼ね備えた、現場支援型の万能スーツなんですよ。"
90002090-15 = "アリスの言葉を借りると、全員分の新しい鎧と武具を作りました。"
90002090-151 = "[ns3] \"か弱さ……。\"\n[ns4] \"清楚さ……。\""
90002090-157 = "その、前から気になっていたんですけど……#n自分でそんなこと言って、恥ずかしくないんですか……？"
90002090-158 = "事実を明確に示すことは、科学的方法の基礎ですよ。"
90002090-159 = "事実を、明確に、示す……そう、ですね……。"
90002090-16 = "ミドリが着ている防護服もその一種です。"
90002090-160 = "そうは言ったものの……このように純白のスーツを着ていると……。"
90002090-161 = "ぐすっ……。"
90002090-162 = "[s] \"どうしたの？急に泣いて……。\""
90002090-163 = "どうしましょう……自分の美しさと可愛さのあまり、感激の涙が――"
90002090-164 = "ごめん、部長のことは私が責任もって何とかしておくね。"
90002090-169 = "ちょっ、エイミ！？#nまだ話は終わっていな――！？"
90002090-17 = "[s1] \"全員分？\"\n[s2] \"8人分も？\""
90002090-172 = "[ns] \"なんだか、嵐が通り過ぎたような気分だね……。\""
90002090-173 = "まったくその通りです……。"
90002090-174 = "（早く空気を入れ替えないと……！）"
90002090-178 = "で、では！次はリオ会長の番です！"
90002090-185 = "[ns] \"リオ……？\""
90002090-186 = "なにかしら。"
90002090-187 = "[s] \"いや、その……。\""
90002090-188 = "その反応の理由は分からないけれど、こうなったわ。"
90002090-189 = "現場対応、施設活用、状況分析……あらゆるシーンに対応できる、汎用性重視の戦闘スーツよ。"
90002090-190 = "文字通り、合理的ね。"
90002090-191 = "スーツの色は、ヒマリ先輩との対比を狙いました。#nなんとなく、そうするべきかなと思いまして……。"
90002090-192 = "あのデザイン、やはり問題があると思います！"
90002090-193 = "部長、落ち着いて。また無理やり部屋に閉じ込められたい？"
90002090-194 = "うぅぅ……。"
90002090-195 = "これはデザイナーのプライドがかかった問題……！どうしても譲れませんでした！"
90002090-197 = "この選択に……悔いはありません！"
90002090-20 = "はい。"
90002090-202 = "私からのコメントは控えておきます……。"
90002090-203 = "なので、淡々と説明を。#nリオのスーツは、防御力アップのほか、電子戦に対応できる仕様になっています。"
90002090-204 = "現場で技術支援をできるように、というリオの要望を反映しました。"
90002090-205 = "[s] \"リオが？危ないんじゃないかな……？\""
90002090-206 = "ヒマリが出張るよりは合理的よ。"
90002090-207 = "何より、ここは鋼鉄大陸だもの。電子戦も想定しておくべきだと思うわ。"
90002090-208 = "[s5] \"そっか。\"\n[s6] \"よろしくね。\""
90002090-21 = "それくらい簡単です。"
90002090-211 = "ええ。"
90002090-212 = "任せてちょうだい。"
90002090-213 = "あと、最後は……。"
90002090-219 = "ユズ？"
90002090-22 = "デザインはミドリが準備してくれました。"
90002090-220 = "隠れてないで……出てきてください。"
90002090-221 = "ユズちゃん、大丈夫だよ。"
90002090-229 = "うぅぅ……。"
90002090-23 = "機能面は私とトキでチェックしています。"
90002090-230 = "[s] \"あれ？モモイとミドリとはだいぶ違うね。\""
90002090-231 = "そ、それが……。"
90002090-232 = "私が依頼したの。"
90002090-233 = "元々は私たちと同じデザインにしようとしてたんですけど……。"
90002090-234 = "[s] \"それはどうして？\""
90002090-235 = "……。"
90002090-236 = "今は伏せておきたいのだけれど、いいかしら。"
90002090-237 = "万全は期しているけれど、この会話が盗聴されている可能性も、完全には否定できないから。"
90002090-238 = "……このスーツは、ある意味で秘密兵器なのよ。"
90002090-239 = "[s] \"切り札は味方にも秘密ってことだね？\""
90002090-24 = "今回のために、ケイちゃんがデザインを起こすための設備も作ってくれたんです。#nおかげで、すごく作業しやすかったです。"
90002090-240 = "……ごめんなさい。悪いとは思っているわ。"
90002090-241 = "みんなを信じてこそ乗り越えられる……それは、もう分かっているつもりよ。#nでも……。"
90002090-242 = "[s] \"大丈夫。リオを信じるよ。\""
90002090-243 = "先生……。"
90002090-245 = "いいんですか、それで？"
90002090-246 = "はい？今までリオが本当の意味で悪巧みをしたことはないからいい？"
90002090-247 = "まあ、それはそうですが……。"
90002090-248 = "はい！アリスもそう思います！"
90002090-249 = "アリス！？"
90002090-25 = "待ってくれ、妹よ。お姉ちゃんは言いたいことがあるのだ。"
90002090-250 = "アリスちゃん！？"
90002090-251 = "あ、アリスちゃん……？"
90002090-256 = "……。"
90002090-257 = "信じて、くれるの……？"
90002090-258 = "はい。だってリオ先輩は、アリスのアビ・エシュフとケイの銃を、最後まで頑張って調整してくれました！"
90002090-259 = "もしリオ先輩が悪いことを考えているなら、絶対ここまでしてくれなかったと思います！"
90002090-26 = "私たち2人だけ、なんかデザイン違くない！？"
90002090-260 = "私も手伝いましたよ！？"
90002090-261 = "そうです！ヒマリ先輩も一緒でした！"
90002090-262 = "ふふっ……アリスの顔に免じて、今回は見逃してあげましょう。"
90002090-263 = "あ、そうそう。隠し機能もあるので、乞うご期待ですよ。"
90002090-268 = "[ns] \"あれ？さっき、ケイの銃って言った？\""
90002090-269 = "はい？"
90002090-270 = "あ、ええ、まあ、一応……。"
90002090-271 = "キヴォトスで銃を持たずに歩くのは、裸で歩くよりおかしいと言われているらしいので……。"
90002090-272 = "名は「エアレンデル：ルミナス・ノヴァ」。エネルギー武器よ。"
90002090-273 = "うぅぅ……やっぱりまだ分かりません。#nこの服……わたしに似合っているんでしょうか……？"
90002090-274 = "そ、そもそも、本当にわたしでいいんですか……？"
90002090-275 = "[s7] \"大丈夫、よく似合ってるよ。\"\n[s8] \"私たちには……ユズの力が必要なんだ！\""
90002090-278 = "は、はい！？"
90002090-279 = "それは、えっと……。"
90002090-28 = "実際の動きには問題ありません。見た目はちょっと、鈍そうですが。"
90002090-280 = "せ、先生が、おっしゃるのでしたら……。"
90002090-281 = "が、頑張り、ます……。"
90002090-282 = "[s] \"よっし、じゃあ最後の点検を始めよう！\""
90002090-294 = "ケイ、ちょっといいかしら？"
90002090-295 = "どうしました？"
90002090-296 = "貴女にだけ、話しておきたいことがあるの。"
90002090-297 = "私にだけ？先生も含めずに、ですか？"
90002090-298 = "それが……。"
90002090-299 = "前々から推測していたのだけれど……。"
90002090-30 = "見た目も大事なの！"
90002090-300 = "貴女は……どんな情報を、鋼鉄大陸とあの3人から隠せるのかしら？"
90002090-301 = "……。"
90002090-302 = "よく気づきましたね。どうしてそれを？"
90002090-303 = "ティファレトのところに着くまで、あの3人は貴女とアリスの存在に気づかなかったからよ。"
90002090-304 = "私になら、さっきの秘密――切り札とやらを共有できると判断したんですね？"
90002090-305 = "……いいでしょう。#nただし、ファイアウォールは長くても30秒しか持ちません。ご留意を。"
90002090-306 = "ええ、問題ないわ。"
90002090-309 = "……。"
90002090-31 = "痛いのは嫌だってお姉ちゃんが言うから、安全性重視のデザインにしたんだよ？"
90002090-310 = "…………。"
90002090-311 = "………………。"
90002090-312 = "ケイ……？"
90002090-313 = "あなた……。"
90002090-314 = "はい？"
90002090-315 = "正気ですか？"
90002090-316 = "え、ええ……。これくらい普通だと思うのだけれど……。"
90002090-317 = "普通？これがですか？"
90002090-318 = "……いえ、備えが多いに越したことはありません。"
90002090-319 = "とは言っても、そんな……。"
90002090-32 = "た、たしかに言ったけどさ……。"
90002090-320 = "変、かしら……？"
90002090-321 = "別の状況なら、そう思っていたのかもしれません。"
90002090-322 = "でも、今は……。"
90002090-323 = "……。"
90002090-324 = "あなたが居てくれて良かった、と思っています。"
90002090-325 = "そ、そう……？"
90002090-326 = "ユズのスーツについても、これで合点がいきました。"
90002090-327 = "そう。"
90002090-328 = "それと、さっき話した第二段階だけれど……。"
90002090-329 = "できないことはないと思います。#n前例があるので……案外、容易いかもしれません。"
90002090-33 = "でもほら、もっとこう、主人公っぽく！カッコいいデザインがよかったのに！"
90002090-330 = "あなたの言うように、使わずに済むのが一番ですが。"
90002090-331 = "ええ。切り札は、切り札であるうちが最も強力だものね。"
90002090-332 = "[s] \"うん？切り札？\""
90002090-333 = "先生！？"
90002090-334 = "えっと、これは、その……！"
90002090-335 = "……。"
90002090-336 = "打ち上げでは、どんなメニューが切り札になるかを話していました。"
90002090-337 = "[s] \"打ち上げ？\""
90002090-338 = "はい。"
90002090-339 = "私たちは、勝つのでしょう？"
90002090-34 = "[s] \"私は十分カッコいいと思うよ？\""
90002090-340 = "[s] \"なるほど、そういう話ね。\""
90002090-341 = "はい。"
90002090-342 = "ですよね、リオ？"
90002090-343 = "……。"
90002090-344 = "ええ、そうよ。"
90002090-345 = "先生、ここで何をしているのですか？あ、リオ先輩に、ケイも！"
90002090-346 = "はい？終わったあとの打ち上げについてですか？いいですね！"
90002090-347 = "アリスは先生と一緒なら何でも嬉しいです！"
90002090-348 = "[s9] \"うん！私もだよ！\"\n[s10] \"そのためには……みんな、無事に帰ろうね。\""
90002090-35 = "そ、そう？まあ、先生が言うなら……。"
90002090-351 = "……はい。"
90002090-352 = "さて……勝つために、もう少し具体的な作戦をお話します。"
90002090-353 = "というと？"
90002090-354 = "各預言者の撃退およびエリアの占領に、特定の順番はありません。#n先生の指揮に従って進んでいいと思います。"
90002090-355 = "ですが、「ビナー」のエリアだけは、最初に占領する必要があります。"
90002090-356 = "[s] \"それはどうして？\""
90002090-357 = "ちょうど、ビナーの居場所を突き止めました。"
90002090-358 = "[s] \"さすがケイちゃん！\""
90002090-359 = "誰がケイちゃんですか！！"
90002090-360 = "こほん……それと、別の理由もあります。"
90002090-361 = "先ほどもお話しましたが、鋼鉄大陸は、全体がネットワークで覆われています。"
90002090-362 = "ビナーのエリアには、それを守るためのファイアウォールが#n設置されているんです。"
90002090-363 = "私たちが先に進むためには、ファイアウォールを物理的であれ電子的であれ解除する必要があります。"
90002090-364 = "突破に成功すれば、残りの預言者の位置も分かりやすくなるはずです。"
90002090-365 = "逆にファイアウォールを放っておいたら……アリスの言葉を借りると――"
90002090-366 = "いくらレベルを上げても、鋼鉄大陸に命令を下すことができません。"
90002090-367 = "[s] \"なる、ほど？\""
90002090-368 = "つまり、作戦遂行のためには――"
90002090-369 = "はい。ビナーの情報コアを、いち早く確保しなければなりません。"
90002090-37 = "モモイとミドリのは、この中で一番防御力が高いです。"
90002090-370 = "[s] \"じゃあ、これで決まりだね。\""
90002090-371 = "最初のターゲットは、デカグラマトンの3番目の預言者。"
90002090-372 = "「違いを痛感する静観の理解者」を自称する――"
90002090-374 = "「ビナー」です。"
90002090-376 = "次回;000, 00, 0"
90002090-38 = "何かあったとしても……#n最後まで生き延びて、みんなの後片づけくらいはできるでしょう。"
90002090-39 = "け、ケイちゃん！？#n作ってるときは、そんな話してなかったよね……？"
90002090-40 = "言ってみただけです。"
90002090-41 = "それで、次は――"
90002090-45 = "過去の重武装から一転して、軽量化と最適化を遂げた機動型の[ruby=あすま]飛鳥馬[/ruby]トキです。#nぴょんぴょん。"
90002090-46 = "片時もじっとしていられないんですね……。"
90002090-47 = "新しい装いは、いの一番に先生に見てほしいですよね？"
90002090-48 = "みんながみんなそう思うわけではないんですよ……。"
90002090-49 = "でも私はそうです。"
90002090-50 = "そうですか……。"
90002090-51 = "[s] \"あっ、そっか。アビ・エシュフをアリスに引き継いだから……。\""
90002090-52 = "はい。この機会にコンセプトと雰囲気を一新しました。#nこれからはスピードを武器に機動捜査隊として活躍する予定です。"
90002090-53 = "なにより、優れた保温性を持っていることには大変満足しています。#n既存のメイド服は体温低下の問題があったので。"
90002090-57 = "[ns] \"……もしかして、ずっと寒かったの？\""
90002090-58 = "はい。"
90002090-59 = "[s] \"なのに、メイド服を着てたの？\""
90002090-6 = "お待たせしました、先生！"
90002090-60 = "はい。"
90002090-61 = "なぜかって？"
90002090-62 = "……。"
90002090-63 = "先生。人には、根性を見せるべき時があります。"
90002090-64 = "それはなぜか？"
90002090-66 = "……エイミには負けられないからです。"
90002090-67 = "[s] \"トキのこと、たまに分からなくなっちゃうんだよね……。\""
90002090-68 = "大丈夫です。私はちゃんと分かっていますので。"
90002090-7 = "[s] \"ミドリ……？\""
90002090-73 = "と、トキさん……。"
90002090-74 = "はぁ……。"
90002090-75 = "防寒の話もいいですが……二丁のエネルギー銃がメイン武装です。#n充電が切れたバッテリーは、エジェクターで後方に排出されます。"
90002090-76 = "カラーリングは私がやりました！#nトキさんのパーソナルカラーはやっぱり白と青だと思うので！"
90002090-77 = "そしてこのジャケットを脱ぐと、私のナイスでパーフェクトなボディが露わになります。ご覧になりますか？"
90002090-78 = "えぇっ！？"
90002090-79 = "[s] \"今はダメ！大変なことになっちゃうから！\""
90002090-8 = "へ、変じゃないでしょうか……？"
90002090-80 = "[ruby=・   ・]今は[/ruby]。なるほど。ではいつか、2人だけの特別な時間にお見せするとしましょう。"
90002090-81 = "トキさん！？"
90002090-82 = "……いちいち反応していては、日が暮れてしまいますよ。"
90002090-83 = "それで、次はエイミなのですが……エイミ？はい？もう暑い？"
90002090-84 = "少しは我慢してください……。あなたの体質はどうなっているんですか……。"
90002090-9 = "[s] \"すごくかわいい……！\""
90002090-90 = "ふぅ……。"
90002090-91 = "上着は！？"
90002090-92 = "暑くて脱いだけど。"
90002090-93 = "それは見れば分かりますが……。"
90002090-94 = "今回、エイミは主に後方支援担当なんでしょう？#nであれば、上着を被って擬装するのが「効率的」だと思いませんか？"
90002090-95 = "でもあんなのずっと被ってたら、先に熱中症で倒れちゃうよ？"
90002090-96 = "暑さのせいで支援できなくなると、それこそ非効率的じゃない？"
90002090-98 = "はい……だと思って、エイミさんの上着は腰に巻きやすいデザインにしておきました。"
