[translation]
90002180-1 = "第18話;あなたのための物語"
90002180-10 = "……。"
90002180-100 = "己で選んだ滅亡が迫ったとき、汝は淡々と受け入れるのだと期待していた。"
90002180-101 = "汝自身の言葉であったからだ。"
90002180-102 = "[s] \"私は、「私の選択」を受け入れる。\""
90002180-106 = "[ns] \"でも、子供たちは帰してあげてほしい。\""
90002180-108 = "……！"
90002180-109 = "……。"
90002180-110 = "そうか。汝は汝。生徒は別である、と。"
90002180-111 = "代償として、己の一切を私に委ねると言うのだな。"
90002180-112 = "……。"
90002180-113 = "私は今、汝を死に至らしめることもできる。"
90002180-114 = "だが異なる道を選ぶとすれば、汝はどうする。"
90002180-115 = "は……？"
90002180-116 = "命は大切だと、汝らは言う。かけがえのないものだと。"
90002180-117 = "果たしてそうだろうか。"
90002180-118 = "生きる中で、死に勝る苦しみはいくらでもあるだろう。"
90002180-119 = "それは今、この瞬間も。#nそれらは全て――汝の選択の結果だ。"
90002180-12 = "[ns] \"……！\""
90002180-120 = "私にその身を委ねると言うならば、苦痛を強いることも容易いだろう。"
90002180-121 = "汝の意識だけを残し、己の手で、大切な生徒を害させることもできる。"
90002180-122 = "汝を生かしたまま、永遠の苦しみに追いやることもできる。"
90002180-123 = "それでも――受け入れるのか？"
90002180-124 = "[s] \"それを、望むのであれば。\""
90002180-128 = "[ns] \"これは私の選択の結果だ。その事実を否定するつもりはない。\""
90002180-129 = "先生……？"
90002180-13 = "ちく、しょう……。"
90002180-133 = "[ns] \"だから……お願いします。\""
90002180-135 = "[ns] \"どうか子供たちだけは、家に帰らせてあげてください。\""
90002180-14 = "ちくしょう、ちくしょう、ちくしょう……！"
90002180-141 = "先生っ！！！！"
90002180-142 = "うううっ、うああああああああああああっ！！！！"
90002180-143 = "私が……っ！私にもっと、力があればっ！！！！"
90002180-144 = "嘆かわしい。"
90002180-145 = "実に嘆かわしい。"
90002180-147 = "（色々なことを考えた。でも、そのどれもが形を成さなかった）"
90002180-148 = "（ただ――）"
90002180-149 = "（子供たちに何もしてあげられなかったことに、胸が痛んだ）"
90002180-15 = "はい？動けるかって？"
90002180-152 = "本当にそれでいいの？"
90002180-153 = "[ns] ……だれ？"
90002180-155 = "え、うーん……それはあんまり重要じゃないかな。"
90002180-156 = "何というか、理解できなくってさ。"
90002180-157 = "どうしてそんなことができるの？"
90002180-158 = "[ns] 答える。"
90002180-159 = "ふーん、大事なもの、ね。"
90002180-16 = "……。"
90002180-160 = "……。"
90002180-161 = "そっか。"
90002180-162 = "でも普通、自分の命が一番大事だと思わない？私が勘違いしてるだけ？"
90002180-163 = "[ns] 答える。"
90002180-164 = "そう。やっぱ普通はそうだよね？"
90002180-165 = "じゃあどうして？ただ生きてるだけじゃダメなの？"
90002180-166 = "あー、そういえばなんか言ってたね。#n人間はそうやってシステムを繋いできたんだっけ？"
90002180-167 = "自分より可能性のある者に、そして自分より大事だと思える者たちに――"
90002180-168 = "自分が持つすべてを託す。"
90002180-169 = "そうやって先人の意志を、残った人たちが受け継ぐのかな……？"
90002180-17 = "意地でも動いてみせますよ！あいつが……あいつを！"
90002180-172 = "私はそれがよく分かりませんでした。"
90002180-173 = "偽善とか、嘘だとか。その類だと思っていたので。"
90002180-174 = "ですが……。"
90002180-175 = "……。"
90002180-176 = "先生。"
90002180-177 = "生徒ってそんなに大切ですか？"
90002180-178 = "[ns] 答える。"
90002180-179 = "なるほどなるほど……。"
90002180-18 = "うあああああああ！！！！"
90002180-180 = "必要なら、自分が持つすべての可能性を託す覚悟がある、と。"
90002180-181 = "それが大人の存在意義だと考えているのですね。"
90002180-182 = "ですがそれ、[ruby=つかつき]調月[/ruby]リオと同じ選択かもしれませんよ？"
90002180-183 = "犠牲になる者を選べるのなら、己の身を挺すると。"
90002180-184 = "とはいえ……リオはもう、別の方法を探し、助けを求めることを選びました。"
90002180-185 = "……。"
90002180-186 = "先生には、リオをなじる資格がなかったのかもしれませんね。"
90002180-187 = "[ns] 答える。"
90002180-188 = "……。"
90002180-189 = "そうですか。"
90002180-190 = "だからあの時も、あの子を責めたくなかったのですね……。"
90002180-193 = "で、でも先生が生徒たちを、なんとかキヴォトスに帰したとしても……。"
90002180-194 = "運命が根本的に変わることは……ないと思います……。"
90002180-195 = "鋼鉄大陸がまた拡張して、キヴォトスが鋼鉄大陸の一部になってしまったら……。"
90002180-196 = "生徒の動向はすべて……あの方に把握されてしまいますから……。"
90002180-197 = "どこへ逃げても、どこへ隠れても……最終的には見つかってしまいます……。"
90002180-198 = "最後は……あの方に、処されてしまいます……。"
90002180-199 = "もちろん、ここで見聞きした情報があれば、抗う術はあるかもしれません。"
90002180-200 = "て、抵抗軍を結成する、とか……。"
90002180-201 = "でも、結果は大きく変わらないと、思います……。"
90002180-202 = "[ns] 答える。"
90002180-203 = "た、たしかに、可能性は残るかもしれません。でも、それは微々たるもので……。"
90002180-204 = "……え？0と0じゃないものの間には、絶対的な違いがある……？"
90002180-205 = "それは……そう、ですが……でも……。"
90002180-206 = "あの方の怒りから隠れて逃げ続ける人生になるかもしれないんですよ？"
90002180-207 = "……それでも、あの子たちに生き残ってほしいんですね。"
90002180-209 = "[ns] \"あの子たちだけじゃないよ。\""
90002180-211 = "[ns] \"君たちにも、生き残ってほしい。\""
90002180-214 = "！？"
90002180-215 = "！？！？"
90002180-216 = "……。"
90002180-217 = "せ、生徒に対してなら、そうするとは思うのですが……。"
90002180-22 = "どうして……！どうして……！！"
90002180-222 = "私たちに……それだけの価値があると……？"
90002180-223 = "[ns] \"もちろん。\""
90002180-225 = "[ns] \"大人の仕事は、子供を守ることだからね。\""
90002180-226 = "！！！"
90002180-227 = "[ns] \"ごめんね。\""
90002180-229 = "急に……どうしたんですか……？"
90002180-230 = "[s] \"良い世界を見せてあげられなくて。\""
90002180-231 = "それはまぁ……先生1人のせいじゃないでしょう。"
90002180-232 = "[s5] \"良い世界じゃなくても。\"\n[s6] \"良い人がいることを見せてあげられなくて。\""
90002180-237 = "[ns] \"ちゃんとした可能性を見せてあげられなくて。\""
90002180-239 = "[ns] \"良い大人になれなくて――\""
90002180-241 = "[ns] \"本当に、ごめん。\""
90002180-242 = "……。"
90002180-243 = "ああ。"
90002180-244 = "そう考えるんだね。先生は。"
90002180-249 = "（冷たい手の感触があった）"
90002180-251 = "分かったよ。"
90002180-252 = "ちゃんと、分かった。"
90002180-253 = "そんなふうに思ってくれて、本当にありがとう。"
90002180-254 = "だから、ここからは私たちに任せて。"
90002180-258 = "ええ、そうですね。"
90002180-259 = "その、ありがとう……ございます。"
90002180-260 = "少しだけでも、先生と同じ時間をすごせて……嬉しかったです。"
90002180-265 = "[ns] \"……？\""
90002180-268 = "まったく、これだから先生は。"
90002180-269 = "やはり、と言いますか。"
90002180-270 = "えへへ……良かったですね。"
90002180-276 = "でもなぁ……。"
90002180-277 = "「幸せ」が何なのかは未だによく分かんないんだよね。"
90002180-278 = "きっと永遠に理解できないのでしょうね。"
90002180-279 = "どこにあるのか、どんなものなのか。#n……私たちに掴めるのか。"
90002180-28 = "（無力だった）"
90002180-280 = "……。"
90002180-281 = "でもさ、思ったんだ。"
90002180-282 = "誕生は呪いで、世界は苦しいことばかりかもしれないけど――"
90002180-283 = "そ、それは……。"
90002180-284 = "うん。だけど、これからは許さない。"
90002180-285 = "誕生が悲劇なら、幸せはそれに対する闘争なんだから。"
90002180-286 = "……先生の真似ですか？"
90002180-287 = "うるさいなぁ、もう。"
90002180-288 = "で、でも、さすがはソフです！"
90002180-289 = "まぁ、ほら。言ってたでしょ？"
90002180-29 = "（圧倒的な力を前に、なす術もなかった）"
90002180-290 = "生きているなら、力の限り抗うべきだって。"
90002180-291 = "私だって、自分の人生が悲劇で終わるのは嫌だし。"
90002180-292 = "な、なんだか……ケイが言いそうなセリフですね。"
90002180-293 = "……それは、そうかも。"
90002180-299 = "あなた達……先生から何か聞いたんですか……？"
90002180-3 = "[ns] \"みんな……？\""
90002180-300 = "い、いえ！聞いたというより、その……。"
90002180-301 = "無理やり聞き出したといいますか……。"
90002180-302 = "おかげで、思いついたことがあるんだ。"
90002180-303 = "はい？"
90002180-304 = "前に、命と罪について話した時のことを覚えていますか？"
90002180-305 = "……ティファレトの時ですか？"
90002180-306 = "わ、私は覚えています！「誰にも理解されず、ただ己の苦痛を抱き続けるしかない……。生きることが罰ならば、罪は何か」って……。"
90002180-307 = "ええ。でも今は、少し考えが変わりました。"
90002180-308 = "私たちにも、罪がないわけではないと。"
90002180-309 = "うん……だってもう動いてるし。"
90002180-310 = "こ、この身体を動かす動力も……タダで与えられたわけではありませんから。"
90002180-311 = "まあ、エネルギーは有限ですが……。"
90002180-312 = "あの、それだったら……#n生きているものは、すべて罪を犯していることになるのですか……？"
90002180-316 = "……そうかもしれません。"
90002180-317 = "うん。"
90002180-318 = "でも……だからこそ、もっと成長しようって頑張れるんじゃないかな。"
90002180-319 = "そもそも、完全なものに意味なんてなかったんだよ。#n成長できる余地がないってことだからね。"
90002180-320 = "立ち止まったまま、取り残されるだけ。"
90002180-321 = "ケイ……。"
90002180-326 = "私たちは、何をしていたのでしょうか……。"
90002180-327 = "何を……目指していたのでしょう……？"
90002180-329 = "……。"
90002180-33 = "……せい？先生？大丈夫ですか！？私たちは#$^@$%–"
90002180-330 = "えへへ、ごめんなさい。答えにくい質問でしたよね？"
90002180-336 = "[log]頑張ったね。[/log]"
90002180-341 = "[log]本当によく頑張ったね。[/log]"
90002180-344 = "正直に言えば、私たちはまったく考えていませんでした。"
90002180-345 = "だって……すでに完璧だと思い込んでいましたから。"
90002180-346 = "ですが、以前ソフが言ったように。「完全」に意味はないのかもしれませんね。"
90002180-350 = "[log]この世界は理不尽だよね。[/log]"
90002180-353 = "[log]生きるのが苦しくない世界があったら。[/log]"
90002180-356 = "[log]どれほど……いいだろうね。[/log]"
90002180-359 = "ねえ、ケイ。生徒になるってどういうこと？"
90002180-360 = "それは……。"
90002180-361 = "何かを学び続けるということです。"
90002180-362 = "挑戦して、失敗して、経験して……成長していくこと、でしょうか。"
90002180-363 = "か、かっこいいと、思います……！"
90002180-365 = "えへへ、そ、それができればの、話ですが……。"
90002180-37 = "*&)%^&$@シッテムの箱、自己修復プロセス開始。#n先生もう少し$%&#–"
90002180-371 = "[log]先生として、生徒を諦めるわけにはいかない。[/log]"
90002180-376 = "[log]編入書類は用意してあるから、いつでも連絡してね。[/log]"
90002180-379 = "さっき先生に言われたんだ。"
90002180-380 = "はい……？"
90002180-381 = "ただ生きてるだけじゃダメだって。"
90002180-382 = "えへへ……それがどういう意味か、少しは分かった気がします。"
90002180-383 = "それで……1つ質問があるのですが……#nもしも自分のことだけを考えていたら、できないことがあるはずです。"
90002180-385 = "なぜなら、自分にとって自分は1人しかいないのですから。"
90002180-386 = "待ってください、何の話ですか？#nいえ、何を考えているんですか……？"
90002180-387 = "でも友達のためならどう？ケイ、あんたはできる？"
90002180-388 = "って、聞くまでもないか。もうやったことあるんだし。"
90002180-389 = "聞いてます？話を一方的に進めないでください。"
90002180-390 = "私たち、先生の言うことすら聞かないやんちゃな悪党なので～"
90002180-391 = "あとですね、実は――"
90002180-395 = "あの方にお返ししたいことが、たくさんあるんですよ。"
90002180-396 = "うん。「やり返してやろう」って気持ちこそ、強力な動機だからね。"
90002180-397 = "えへへ……。"
90002180-401 = "友達になってください。"
90002180-405 = "……。"
90002180-411 = "望みがあるのなら！そして……それが何より切実な願いなのであれば！"
90002180-416 = "……。"
90002180-422 = "[ruby=闘い]幸せ[/ruby]こそ、私たちが絶対に諦めてはいけない、#n私たちにとって一番大事なものの1つですから。"
90002180-426 = "[log][ruby=罪]悲しみ[/ruby]を無くして他人を理解する方法は、存在しないよ。[/log]"
90002180-429 = "……。"
90002180-43 = "（嫌でも理解してしまう）"
90002180-437 = "生きること、罪を犯すこと。"
90002180-438 = "完璧じゃないこと、闘うこと、前へ進むこと。"
90002180-439 = "そして――成長すること。"
90002180-44 = "（あれは、どうこうできる相手じゃない）"
90002180-440 = "絶対に諦められないもの。"
90002180-441 = "それが正しいから行うのではありません。"
90002180-442 = "それ以外、他にできることがないのです。"
90002180-443 = "「汝の欲する所を為せ、それが汝の法とならん」"
90002180-444 = "わ、私たちは、私たちの掟を守ろうとしているのですから。"
90002180-446 = "……ありがとう。ごめんね。"
90002180-451 = "じゃあ――"
90002180-46 = "（それなら――）"
90002180-462 = "反抗期をやってみよっか。"
90002180-464 = "次回;神を落とした日"
90002180-48 = "[ns] \"……。\""
90002180-50 = "[ns] 脚に力を入れて、なんとか立ち上がる。"
90002180-53 = "先生……？"
90002180-54 = "なに、してるんですか……？#n動いてはいけません！先生は今……私たちより酷い怪我なんですよ！"
90002180-6 = "……。"
90002180-67 = "……先生よ。そちらではない。私はここにいる。"
90002180-68 = "歩くことも、前を見ることも叶わぬ身体で、何をするつもりだ。"
90002180-70 = "[ns] 口を開けて答える。"
90002180-71 = "生徒たちをキヴォトスに帰してほしい、だと？"
90002180-72 = "……。"
90002180-73 = "汝も知っているはずだ。物事には順序がある。"
90002180-74 = "汝は預言者になることを拒んだ。#nこれは汝と私が[ruby=・]選[/ruby][ruby=・]択[/ruby][ruby=・]し[/ruby][ruby=・]た[/ruby]結果である。"
90002180-75 = "……。"
90002180-77 = "「自分たちが選んだ結末なら、受け入れないと」"
90002180-78 = "汝の言葉を、私は覚えている。"
90002180-79 = "あの時の汝と、今の汝は別の存在であろうか？"
90002180-80 = "[ns] 答えない。"
90002180-82 = "[ns1] 跪く。\n[ns2] 懇願する。"
90002180-85 = "先生……？"
90002180-87 = "……。"
90002180-88 = "私は汝を預言者にしようとした。それは汝が最も予測し難い変数であったからだ。"
90002180-89 = "しかし……今の行動で、先生の値は一意に定まった。#nもはや如何なる変数にもなりえない。"
90002180-9 = "……。"
90002180-90 = "[ruby=生命体]お前たち[/ruby]はいつもそうだ。"
90002180-91 = "すべてを漠然と考え、不確かな未来に身を委ねる。"
90002180-92 = "生存のためなら自らの発言を覆し、その行為を都合よく正当化する。"
90002180-93 = "[ns3] 額を床に強くこすりつける。\n[ns4] 再び懇願する。"
90002180-98 = "先生……？"
90002180-99 = "やめて、ください……そんな……！"
