[translation]
90002030-1 = "第3話;出撃"
90002030-2 = "では、状況を整理するわ。"
90002030-3 = "「分かった事」と「やるべき事」がありますが、どちらから聞きたいですか？"
90002030-5 = "では、分かった事から話してください。"
90002030-7 = "私たちを襲撃してきた個体の詳細が見えてきたわ。"
90002030-8 = "モデル名は、[ruby=Labor]レイバー[/ruby]。"
90002030-10 = "れいばー……？"
90002030-15 = "労働者という意味よ。このモデルの役割からして、適切な名前とも言えるわね。"
90002030-16 = "レイバーの種類は、私たちが把握した限りで3種類あるようです。"
90002030-17 = "現場で見たのだと……装甲みたいなのを纏った直方体のモデルがいたね。"
90002030-18 = "とても頑丈でした！"
90002030-19 = "そのモデルは「防御型レイバー」と名づけていいと思います。"
90002030-20 = "次は、一目で分かるほど大きな砲を搭載したモデル。"
90002030-22 = "デザインは惜しいですけど……「砲塔型レイバー」と呼べそうです。"
90002030-23 = "あ、あとは……2つのプロトタイプみたいな……#nちょっと小さいモデルもいました……。"
90002030-25 = "では、そのモデルは「基本型レイバー」と呼びましょう。"
90002030-26 = "一般的に、小さければ可愛く見えるものですが……#nこれはどうにもクモにしか思えなくて……。"
90002030-27 = "クモが可愛くないと言うの？"
90002030-28 = "もちろん、美学は主観によるものです。あなたの美的センスが変わっていることも理解していますが……。"
90002030-30 = "部長も会長も、今はそれを話してる場合じゃないから。"
90002030-31 = "[s] \"他にも分かった事はある？\""
90002030-35 = "ええ。これが最も重要だと思うわ。"
90002030-36 = "レイバーは周囲の無機物を、鋼鉄大陸に変化させることができるの。"
90002030-37 = "それは、つまり……？"
90002030-38 = "じゃあ、レイバーが鋼鉄大陸を広げてたってこと？"
90002030-39 = "間違いではないと思います。"
90002030-40 = "レイバーの量産が始まったのは、ある程度まで鋼鉄大陸が構築されてから、と考えるのが妥当でしょう。"
90002030-41 = "レイバーが輸送船に近づいたのも、鋼鉄大陸に取り込もうとしていた可能性が高いと思われます。"
90002030-42 = "すべてのレイバーを調べたわけじゃないから、可能性の域はでないのだけれど。#nただ、そもそも全部調べるなんて、現実的ではないわ。"
90002030-43 = "気になるのは……#n鋼鉄大陸の内部構造をレイバーが再整備しているように見える点ね。"
90002030-44 = "再整備……？"
90002030-45 = "構造物の建築や、損傷した箇所の修復――"
90002030-46 = "鋼鉄大陸の拡張過程で混入した無機物に対する同化作業などよ。"
90002030-47 = "あ、だから輸送船を……。"
90002030-49 = "うん、「分かったこと」は理解したよ。じゃあ、「やるべき事」は？"
90002030-50 = "口にするだけなら簡単ですが――"
90002030-54 = "――イェソドを突破する必要があります。"
90002030-55 = "[s] \"……。\""
90002030-56 = "現時点で判明している、9番目の預言者「イェソド」に関する情報を共有するわ。"
90002030-57 = "不思議なことに、イェソドには原型となるものが存在しない。"
90002030-58 = "それはどういう意味ですか？"
90002030-59 = "例えばホドの場合、元々はミレニアムの通信ユニットAI「ハブ」だった。"
90002030-60 = "コクマーは工作船で、ゲブラは無人探査機だったわね。"
90002030-61 = "このように、AIシステムを基盤とする構造体が、そのAIごとデカグラマトンによってハッキングされることで、預言者に成ってきた。"
90002030-62 = "唯一の例外と言えるのがビナーね。#n初めて目撃されたのは、数十年前のアビドス砂漠だったから。"
90002030-63 = "イェソドも、例外だと？"
90002030-64 = "ええ。これは推測なのだけれど――"
90002030-65 = "イェソドは、鋼鉄大陸がある程度構築された後に[ruby=・]作[/ruby][ruby=・]ら[/ruby][ruby=・]れ[/ruby][ruby=・]た[/ruby]のだと考えているわ。"
90002030-68 = "そうでなければ、あれほど巨大なイェソドの信号を、今まで把握できなかった説明がつかないの。"
90002030-69 = "妥当な推理だと思います。"
90002030-71 = "そしてそれを真と置くならば……#nイェソドはとても純粋である、ということになります。"
90002030-72 = "目的のためだけに作られた、「最適化」された預言者……ですか。"
90002030-73 = "……おそらくは。"
90002030-74 = "あの巨大さと威力もまた、最適化の結果でしょうね。"
90002030-76 = "議論を深めるほど、打開策がなくなっていくような気がしますが……。"
90002030-77 = "あ、アリスは……みんなは！きっと大丈夫です！"
90002030-78 = "勇者は……冒険に出る前から怖気づきません……うわーん！"
90002030-79 = "[s] （すでに怖がっているように見えるけど……）"
90002030-81 = "でも、弱点はあると思うよ。"
90002030-82 = "そうなんですか……？"
90002030-83 = "あれ、壁の上からは動けないんじゃないかな。"
90002030-84 = "た、たしかに……#nゲームでも、超大型ボスは……簡単に移動できない、ものですから……。"
90002030-85 = "ゲームに例えるつもりはなかったけど……。"
90002030-87 = "ふふっ、今のは的を射ているかもしれませんよ。"
90002030-88 = "なんであれ質量がある以上、避けられないものがあります。"
90002030-89 = "避けられないもの？#n……なるほど。"
90002030-90 = "速度と耐久性の問題ね。"
90002030-91 = "そうです。#n質量の大きい物を動かすには、その分多くのエネルギーが必要となります。"
90002030-92 = "エネルギーさえあれば、素早く動かすこともできますが、動くより先に耐久性に限界がくるはずです。"
90002030-93 = "もちろん、謎の物質の強度や耐久性については、まだ不可解なことが多いです。"
90002030-94 = "とはいえ物質であるからには、必ず限界があると思います。"
90002030-95 = "[s] \"つまり……？\""
90002030-96 = "要するに、こういうことです。"
90002030-97 = "イェソドの攻撃には、動きに制約があると予想されます。"
90002030-98 = "それを基に作戦を考えると――"
90002030-99 = "――陽動を用いた短期決戦になるわね。"
90002030-100 = "……その通りです。"
90002030-101 = "イェソドの攻撃……より厳密に言えば「腕を振るう攻撃」は、脅威そのものです。"
90002030-102 = "とはいえ予想通りなら、動きは鈍いはず。"
90002030-103 = "回避に専念すれば、チャンスを作ることができるかもしれない。"
90002030-104 = "大きさに物を言わせた、[ruby=・]面[/ruby]への影響力はいったん無視します。"
90002030-105 = "少なくとも、数回イェソドの注意を逸らすには十分かと。"
90002030-106 = "そして、その隙に本隊は輸送船で移動し――"
90002030-107 = "壁の上から、イェソドを奇襲するのです。"
90002030-113 = "ヒマリ……この作戦を、[ruby=・]貴[/ruby][ruby=・]女[/ruby]が提案するのね。"
90002030-114 = "……[ruby=・]以[/ruby][ruby=・]前[/ruby][ruby=・]の[/ruby]あなたなら、相談もなく強行していたのでは？"
90002030-115 = "今の貴女は、こんな作戦を私より先に提示するくらい――"
90002030-116 = "――違うわね。それだけ、私たちが窮地に追い込まれているということ……。"
90002030-117 = "……時間がありません。"
90002030-118 = "ええ……。"
90002030-119 = "[s1] \"みんな、ちょっと待って。\"\n[s2] \"その作戦って……。\""
90002030-122 = "……。"
90002030-123 = "そうよ。"
90002030-124 = "これは、誰かを囮にしてイェソドを倒す作戦。"
90002030-125 = "しかも囮の安全を保証できない上に、イェソドを必ず仕留められる確証もない。"
90002030-126 = "つまり、極めて危険な作戦になる……ということよ。"
90002030-127 = "[s3] \"私は……賛成できない。\"\n[s4] \"みんなの……先生として。\""
90002030-130 = "でも、これ以上の手段が思いつかないの。"
90002030-132 = "で、では……！アリスが……！"
90002030-133 = "……。"
90002030-135 = "ダメよ、アリス。"
90002030-136 = "どうしてですか？まだ見習いですが、アリスは勇者です！#nだから、みんなを――"
90002030-137 = "そう。貴女が、勇者だからよ。"
90002030-138 = "貴女はきっと、[ruby=・]切[/ruby][ruby=・]り[/ruby][ruby=・]札[/ruby]になる。"
90002030-139 = "……それには、私も含まれるのですよね？"
90002030-140 = "……ええ。"
90002030-141 = "相変わらず、あなたは冷たく振舞うのですね。"
90002030-142 = "……慣れているわ、こんなこと。"
90002030-143 = "私は、あなたのそういうところが嫌いです。"
90002030-147 = "我慢できないくらい……怒りが込み上げてくるんです……！"
90002030-148 = "ケイはいつも怒っていませんか？"
90002030-149 = "それはそうですが……ああもう！そういう意味じゃないでしょう！"
90002030-150 = "これは別のベクトルで怒っているんです！火に油を注がないでください！！"
90002030-151 = "[s] \"本当に……他の方法はないの？\""
90002030-153 = "……。"
90002030-154 = "……。"
90002030-155 = "（場の空気が重く沈み込んだ）"
90002030-156 = "（それでも時間は容赦なく過ぎていく……）"
90002030-161 = "じゃあ、私がやるよ。"
90002030-165 = "[ns] \"！？\""
90002030-166 = "エイミ！？"
90002030-171 = "要は、注意を引けばいいんだよね？"
90002030-173 = "で、でも……！"
90002030-174 = "エイミさん！先生も心配したように……！"
90002030-176 = "大丈夫。これが一番効率的だよ。#n「たぶん」なんて言葉が要らないくらい、明確に。"
90002030-177 = "現場のことは慣れてるし、私、結構頑丈で素早いんだ。"
90002030-178 = "で、でも……もしも上手くいかなかったら……！"
90002030-179 = "[s5] \"エイミ、もう一度考え直してくれない……？\"\n[s6] \"私は……君たちが怪我するのを見たくないんだ……。\""
90002030-182 = "……。"
90002030-190 = "！？"
90002030-191 = "！？"
90002030-192 = "（そっと、エイミが抱きしめてきた）"
90002030-193 = "[s] \"え、エイミ……？\""
90002030-196 = "やっぱり先生の身体……ぬるくていいね。"
90002030-197 = "大丈夫だよ、先生。"
90002030-198 = "[s] \"でも……！\""
90002030-199 = "うん。分かってるよ。"
90002030-200 = "でも、大丈夫。#n私たちのことを考えてくれるなら――"
90002030-201 = "私たちを、信じて。"
90002030-202 = "先生が生徒を助けるのが当たり前なら、生徒が先生の力になりたいって思うのも、当然じゃない？"
90002030-203 = "そうだなぁ……私にもしものことがあったら――"
90002030-204 = "思いっきり先生のこと恨むから。一生責任とってね。"
90002030-205 = "じゃあ、行ってくる。"
90002030-210 = "[ns] \"エイミ！\""
90002030-213 = "……作戦開始です。"
90002030-214 = "ええ、取りかかりましょう。"
90002030-215 = "エイミを無事に帰らせるために、私たちも覚悟を決めるべきだわ。"
90002030-216 = "そうでしょう、先生？"
90002030-217 = "[s] \"……やるべきことを、教えてほしい。\""
90002030-224 = "[ns] \"では、各自持ち場へ。\""
90002030-225 = "エンジンの修理状況を報告します。#n緊急離陸および緊急着陸、いずれも可能な状態です。"
90002030-226 = "これより私は、格納庫へ移動し降下準備に入ります。"
90002030-228 = "はい！アリスもトキについていきます！"
90002030-229 = "が、頑張ります……！"
90002030-231 = "ヒマリ、あとは頼んだわ。"
90002030-232 = "……トキとアリスは、私たちの最大戦力であり切り札です。"
90002030-233 = "ユズは、こういった任務で意外な活躍を見せる可能性があります。"
90002030-234 = "ですが……リオ、あなたまで行く必要があるのですか？"
90002030-235 = "……現場にも、戦術の指揮官が必要よ。"
90002030-236 = "それは、あなたの責任感や負い目からくる感情的な行動では？"
90002030-237 = "……行ってくるわね。"
90002030-244 = "はぁ……#n最近、私の人望が失われているような気がするのですが、どう思いますか？"
90002030-245 = "[s] \"みんな、ヒマリを信頼してるからだと思うよ。\""
90002030-246 = "ふふっ、そういうことにしておきましょう。"
90002030-247 = "さて、おしゃべりはこのくらいにして……始めましょうか。"
90002030-248 = "では、先生？"
90002030-249 = "[s] \"作戦開始！\""
90002030-250 = "格納庫、聞こえますか？状況を教えてください。"
90002030-256 = "ただいま格納庫に到着しました。ポッドに搭乗します。"
90002030-257 = "アリス、手順は分かっていますね？"
90002030-259 = "はい！もちろんです！"
90002030-260 = "えっと……何から始めるんでしたっけ……？"
90002030-261 = "わ、わたしが教えてあげるね、アリスちゃん……。#nこれは、ゲームのマニュアルみたいなもので……。"
90002030-263 = "ではユズ、アリスを頼みます。"
90002030-266 = "降下準備完了。いつでもどうぞ。"
90002030-267 = "では――"
90002030-268 = "発進！"
90002030-278 = "本当、あり得ない大きさだね。"
90002030-279 = "さて。"
90002030-280 = "効率的にいこっか。"
90002030-281 = "まずは――"
90002030-293 = "――目の前の敵から。"
