[translation]
90002025-2 = "やった！"
90002025-3 = "敵が撤退していきます！"
90002025-4 = "ど、どうにかなったぁ……ふぅ……。"
90002025-6 = "ありがとうございます、エイミ！"
90002025-7 = "こういうのは慣れてるからね。"
90002025-8 = "なにより、私をここに配置した先生の判断が良かったんだよ。"
90002025-12 = "先生、聞こえるかしら？エンジンの緊急修理が完了したわ。"
90002025-13 = "私もいます。先生は迅速に褒めてください。"
90002025-14 = "[s] \"リオもトキも偉い！お疲れ様！\""
90002025-15 = "ありがとうございます。これでまだまだ戦えます。"
90002025-17 = "――エンジンの修復が確認できました。#nケイ、輸送船の状態をどうみますか？"
90002025-18 = "再飛行は可能だと思います。ただ、これ以上ダメージを負うと……。"
90002025-25 = "アリスです！こちらは終わりました！みんな無事です！"
90002025-26 = "お見事です。ゲーム開発部の皆さん、エイミ。"
90002025-27 = "お疲れのところ申し訳ないのですが、戻ってくるついでに、敵の残骸を回収していただけますか？"
90002025-28 = "今回は持って帰れそう。どれくらい必要？20体？"
90002025-29 = "多すぎても、船内に収納できませんので……。"
90002025-31 = "船外カメラ、再起動。モニターに映します。"
90002025-37 = "これは……。"
90002025-38 = "……。"
90002025-39 = "[s] \"……。\""
90002025-41 = "[ns] \"あれが、鋼鉄大陸……。\""
90002025-44 = "次回;出撃"
