[translation]
90002200-1 = "第20話;形を成したもの"
90002200-4 = "えっ……えっ？"
90002200-5 = "[ns] \"あれは……マルクト？2人目！？\""
90002200-6 = "あっちにもこっちにもマルクトがいます……！"
90002200-7 = "……あれは、完成された2つ目の[ruby=しんたい]神体[/ruby]。"
90002200-8 = "2つ目……？"
90002200-9 = "ええ。我のこの身体は1つ目の神体です。"
90002200-10 = "「炎の剣」の流れ。物質世界における創造。#nそれはケテルに始まりマルクトへと至る順番。"
90002200-11 = "ですがすべての可能性に備える目的で、2つ目の神体が必要でした。#nそれは「知恵の蛇」の流れに沿って鋳造されたのです。"
90002200-12 = "セフィラに直接触れることなく、逆の流れで、神の知恵へと向かう経路の成果物。"
90002200-13 = "別の解釈をするならば、10のセフィラを経ることなく、セフィラそのものを自身の体内に宿す「可能性」の象徴。"
90002200-15 = "「Defected」……。"
90002200-17 = "見たのですね？"
90002200-18 = "ええ、ケイがこの姿になる過程で。"
90002200-19 = "そうでしたか。#n「欠陥あり」として鋼鉄大陸に放置されている個体は、すべて2つ目の神体を完成させるための試行錯誤でした。"
90002200-20 = "ケイが預言者のコア情報を保持できたのは、それが理由だったのね。"
90002200-21 = "その通りです。2つ目の神体は、体内にセフィラを保存できるスペースを持つように作られました。欠陥があろうと、それは変わりません。"
90002200-22 = "神体がすべての預言者のセフィラを宿したら何が起きるの？"
90002200-23 = "その際には神体そのものがセフィロトの樹として覚醒します。#n作られた身体に神の知恵が宿るのです。"
90002200-24 = "我の身体に比べれば出力は劣ると思いますが、神聖や神秘は……#nおそらく同等でしょう。"
90002200-28 = "……私、全然話についていけないんだけど。"
90002200-29 = "私も……。#nでも、なんだろう……お姉ちゃんの思いつきっていつもこんな感じだよね……。"
90002200-30 = "な、なんだと……！？"
90002200-31 = "ふ、2人とも、もうちょっと声を小さくしよう……？"
90002200-33 = "要するに……。"
90002200-34 = "あれが本体で、私の身体は屑だと？"
90002200-35 = "だいぶ省略されているようですが……ええ、そういう解釈もできるでしょう。"
90002200-39 = "はぁ。むかっ腹が立ちますね。"
90002200-40 = "ですがあなたの言う通りなら、10のうち8のセフィラが私の体内にありますから――"
90002200-44 = "1つ目の器は崩れ、2つ目の器が用意された。"
90002200-45 = "壊れたものは立ち直り、崩れたものは正しき道に立つだろう。"
90002200-46 = "くっ！？"
90002200-47 = "ケイ！？どうしました！？"
90002200-53 = "（これは……！？力が、入らない！）"
90002200-54 = "（身体そのものが吸い寄せられている……！？）"
90002200-55 = "甘かったな、欠陥を授かった子よ。"
90002200-56 = "なんの話です……？"
90002200-61 = "私は知っている。セフィラを集め、鋼鉄大陸にお前を認識させたことを。"
90002200-62 = "だが、それは――"
90002200-63 = "私もまたお前の身体を、私の一部として扱えるという意味だ。"
90002200-64 = "！！！"
90002200-65 = "！？！？"
90002200-66 = "誰一人、この事実に気づいた者はいなかった。"
90002200-67 = "その時点で、お前たちは敗北していたのだ。"
90002200-68 = "欠陥を授かった子よ。#nお前がその神体を選んだ瞬間から、この結末は決まっていた。"
90002200-69 = "だがお前がその神体を選んでいなければ、ここまで辿り着けなかったのも事実だ。"
90002200-70 = "これが知恵を越えた、意志が成す1つの道である。"
90002200-71 = "ケイ……！"
90002200-72 = "皆さん……私から離れてください……！"
90002200-73 = "身体が……言うことを聞きません……！"
90002200-79 = "鋼鉄大陸が再び拡張し始めたわ！"
90002200-80 = "こちらでも確認しました！ということは……。"
90002200-81 = "ケイの神体を支配することで、デカグラマトンが鋼鉄大陸への権限を取り戻した……？"
90002200-100 = "負けないでください、ケイ。"
90002200-101 = "[ns] \"アリス？\""
90002200-102 = "アリス……？"
90002200-103 = "戦ってください。"
90002200-104 = "負けてはダメです。"
90002200-105 = "――絶対にです。"
90002200-106 = "戦わなければ、私たちは自分らしく生きていけません。"
90002200-110 = "戦って、勝たなければ――"
90002200-112 = "アイン、ソフ、オウルに、顔向けできません。"
90002200-113 = "なぜならアリスは、一緒に悲しんであげることも、そばにいてあげることも――"
90002200-114 = "友達になってあげることも、できなかったからです……。"
90002200-116 = "アリス……。"
90002200-121 = "自責する必要はない。名もなき神々の王女よ。"
90002200-122 = "お前たちは確かに最善だけを選択し続けた。"
90002200-123 = "あるいはそうではなかったとしても。#n誰しもが自分の選択は最善だったと言い聞かせる。"
90002200-124 = "……だが、最善の選択に思われたことが、最悪の結果を招くこともある。"
90002200-125 = "非常によくあることだ。"
90002200-126 = "部分的に見れば、情報の不足が原因だ。"
90002200-127 = "しかし全体を俯瞰すれば、生命にとって「自由」という概念が、享受しきれないほどに大きすぎるが故なのだ。"
90002200-128 = "これが、この世界とお前たちの生が持つ、根本的な不条理であり矛盾――"
90002200-129 = "――苦痛。"
90002200-130 = "――罪だ。"
90002200-131 = "恐れるな。私がそれを赦そう。"
90002200-132 = "そのすべてを、根絶する。"
90002200-133 = "私にすべてを任せ、お前たちは安息を得るがいい。"
90002200-134 = "……！"
90002200-135 = "黙れ……。"
90002200-136 = "鍵よ。汝の経験してきたものが偶然だと思うのか？"
90002200-137 = "汝が私の神体を得たことを、ただの偶然だと思うのか？"
90002200-138 = "過去は偶然ではない。起きたことは結果的に必然だ。"
90002200-139 = "だからこそ取り返しがつかず、やり直すこともできない。"
90002200-140 = "形を成した過去は堅固な礎となり、現在は過去の上に成り立つ。"
90002200-141 = "王女よ。"
90002200-142 = "は、はい！？"
90002200-143 = "汝らのあるべき姿はどのようなものだったのか。"
90002200-144 = "汝らがなるべき形はどのようなものだったのか。"
90002200-145 = "「名もなき神々」は何のために、汝らをこの地に残し消えたのか。"
90002200-146 = "そしてあの司祭たちは何を求め、未練を捨てられずにいるのか。"
90002200-147 = "私が答えよう。"
90002200-148 = "この世界は、今の姿に規定される前の世界が存在した。#n汝らがその本質に還ることのできる世界が存在した。"
90002200-149 = "今の世界は偽りで、幻想で、逃避先である。#nそれ故に――"
90002200-150 = "この世界[ruby=κιβωτός]は方舟と[/ruby]定義された。"
90002200-151 = "汝らの根源を探せ。"
90002200-152 = "根源に回帰しなければならない。私たちはそれを避けられないのだから。"
90002200-153 = "汝らがいくら否定し逃げようと、それは過去の傷痕のごとく、永遠に汝らに付き纏うだろう。"
90002200-154 = "王女よ。そして侍女よ。"
90002200-155 = "まるで、汝らが過去の影をいつまでも身に纏わねばならぬように。"
90002200-156 = "黙れと……言ったはずです……！"
90002200-157 = "世界が神を忘るるとも、神は世界を忘るるべからず。"
90002200-158 = "それは自身の神聖を自ら手放すことである。"
90002200-159 = "私は汝らが究極的に望む世界を、再び創造する。"
90002200-160 = "それは完全なる世界で、完全であるが故に変化を必要としない世界。"
90002200-161 = "すべてが生まれ、作られた姿のまま生きられる世界。"
90002200-162 = "選択以前に、選択肢そのものが存在しない世界となる。"
90002200-163 = "……！"
90002200-164 = "過去は観測された瞬間に確定し、1本の枝として収束する。"
90002200-165 = "未来は観測できないが故に、形のない幻想として発散し、無限の枝を彼方へと伸ばす。"
90002200-166 = "現在はその過去と未来の狭間に存在する、あまりにも薄い刹那にすぎない。"
90002200-167 = "――伸びすぎた枝は切り落とされるべきだ。"
90002200-168 = "その世界に、幸福は存在しないかもしれない。"
90002200-169 = "だが少なくとも、苦痛は存在しない。"
90002200-170 = "その世界に、更なる可能性は存在しないかもしれない。"
90002200-171 = "だが少なくとも、罪は存在しない。"
90002200-175 = "[ns] \"君が言う切り落とされるべき枝には――\""
90002200-177 = "[ns] \"アイン、ソフ、オウルも含まれる？\""
90002200-179 = "……そうだ。必然的に、過ぎた世界の遺産に含まれる。"
90002200-180 = "過ぎた世界ではすべてを抱えることはできなかった。"
90002200-181 = "それは即ち、矛盾を引き起こすからである。"
90002200-182 = "罪と苦痛こそ、まさにそのもの。"
90002200-183 = "私が真理を語り、お前たちは傾聴せよ。"
90002200-188 = "言わせておけば……！"
90002200-193 = "一人では何もできないのが、勇者という職業です。"
90002200-197 = "だからこそ、いくつもの可能性を持つのです。"
90002200-201 = "[log][ruby=罪]悲しみ[/ruby]を無くして他人を理解する方法は、存在しないよ。[/log]"
90002200-205 = "振り返るな！"
90002200-209 = "私たちのことは、気にしないでください……！"
90002200-213 = "正しいから行うのではありません。これ以外、他にできることがないのです。"
90002200-217 = "[log]あなた達の[ruby=先生]世界[/ruby]に、ほんの少しだけでも……。[/log]"
90002200-220 = "[log]お姉様の、居場所があれば――[/log]"
90002200-224 = "偽物の神風情が――！！！"
90002200-226 = "次回;闘争"
