[translation]
90002070-1 = "第6話;ケイ"
90002070-100 = "懸念しているのは、大幅な時間のロスよ。"
90002070-101 = "新しい素体に意識を移す時間と、セキュリティを分析する時間――"
90002070-102 = "一刻の猶予も無い中で、それが無駄になるかもしれない。"
90002070-103 = "[s] \"……。\""
90002070-107 = "[ns] \"それでも、やってみよう！\""
90002070-108 = "先生、本気で言っているの！？"
90002070-109 = "いえ、言いたいことは理解しているわ。#n成功のリターンは大きいし、失敗したとしてもケイを失うことはない。でも……。"
90002070-110 = "あまりにも、変数が多すぎるのよ……。"
90002070-111 = "え……？お願いを聞いてあげたい……？#n先生、貴方ね……。"
90002070-112 = "……。"
90002070-116 = "分かったわ……。"
90002070-117 = "先生がそこまで言うのですから、仕方ありませんよ。#n可愛い後輩の[ruby=・]お[/ruby][ruby=・]願[/ruby][ruby=・]い[/ruby]でもありますし。"
90002070-118 = "ケイ、やりましたね！みんなが力を貸してくれます！"
90002070-119 = "ふふ、ふふふ……やはり、必死に訴えかけていけば……#n通じるものなんですね……。"
90002070-12 = "ケイ！？アリスはここにいます！どうか……！"
90002070-120 = "そっか！じゃあ、今度ユウカに試してみよっと！"
90002070-121 = "たぶん、ダメだと思うよ……。"
90002070-123 = "3で同時に入力するわよ。いち、に――"
90002070-124 = "――さん！"
90002070-13 = "すみません、落ち着いてください……。"
90002070-131 = "……ケイ？"
90002070-132 = "私も！私も見る！#nおぉ……！"
90002070-136 = "素体の正常な稼働が確認できました。あとは……。"
90002070-137 = "ケイ。私たちのこと、分かるかしら？"
90002070-14 = "え……？"
90002070-140 = "[ns] \"……ケイ？\""
90002070-143 = "……先生？"
90002070-144 = "アリス？"
90002070-146 = "ケイ！！！"
90002070-15 = "はぁぁ……疲れました……。"
90002070-152 = "さすがはケイです！アリス、信じていました！"
90002070-153 = "……言ったでしょう。大丈夫だって。皆さん大袈裟すぎるんですよ……。"
90002070-154 = "[s] \"それくらい大事なことだったからね。\""
90002070-155 = "みんなが冷静だったら、それはそれで寂しかったかもしれないよ？"
90002070-156 = "仕方ありません。私だけでも平静を装うことにします。"
90002070-157 = "いえ、結構です……。"
90002070-159 = "えっと……改めまして、ケイです。"
90002070-16 = "大丈夫……なんですか？"
90002070-160 = "ケイです！"
90002070-161 = "おぉ、これでようやく美少女アンドロイドって感じになったね！"
90002070-162 = "うん。良いデザインだと思う。"
90002070-163 = "よ、よかったね……ケイちゃん。"
90002070-164 = "（前のデザインも、悪くなかったと思うのだけれど……）"
90002070-169 = "……二足で歩けるし、喉がスピーカーじゃない。"
90002070-17 = "問題ありません。身体のあちこちが壊れているだけです。"
90002070-170 = "髪の毛に、手、指まで……。"
90002070-174 = "……う、うぅっ。"
90002070-175 = "ケイ、おめでとうございます。#n感動に水を差すようで申し訳ないのですが……何か、分かったことはありますか？"
90002070-176 = "何もなかったとしても、ケイが喜んでいますし、十分だとは思いますが。"
90002070-180 = "あれほど駄々をこねて何も無かったら、皆さんに顔向けできませんよね。"
90002070-181 = "幸い、お話しできることがたくさんあります。"
90002070-182 = "一旦、輸送船に戻りましょう。"
90002070-184 = "次回;可能性"
90002070-2 = "ケイ？起きてください、ケイ！#nこんなの、嫌です……アリスを、独りにしないでください！"
90002070-20 = "私が診るわ。アリス、ちょっといいかしら。"
90002070-21 = "は、はい……！"
90002070-24 = "ケイの意識……生命に異常はないわ。"
90002070-25 = "本当ですか！？ケイ……よかったです……！"
90002070-26 = "ただ、ケイの身体はほぼ限界に達しています。"
90002070-27 = "そ、それはどうすればいいんですか……？"
90002070-28 = "なんら難しいことではないわ。身体をオーバーホールすれば解決することよ。"
90002070-29 = "問題が生じているのは、あくまでハード面だけのようね。"
90002070-3 = "ケイ！！！！"
90002070-30 = "よ、よかったね、ケイちゃん……。"
90002070-31 = "待ってください。つまり、この身体を整備して使い続けるという意味ですか？"
90002070-32 = "そのつもりだけれど……何か問題あるかしら？"
90002070-36 = "……。"
90002070-37 = "これは提案なのですが……。"
90002070-38 = "これを機に、他の身体に変えてくれませんか？"
90002070-39 = "といっても、使えそうな素体が……。"
90002070-40 = "あるじゃないですか！そこに！"
90002070-41 = "そこ……？"
90002070-43 = "もしかして、ここにあるやつ？"
90002070-44 = "でもこれ、デカグラマトン側が作ったものなんだよね……？"
90002070-45 = "分析をして、問題ないと判明したはずです。"
90002070-46 = "それは違うわ。[ruby=・]稼[/ruby][ruby=・]働[/ruby][ruby=・]に[/ruby][ruby=・]は[/ruby]問題がないという話だったでしょう？"
90002070-47 = "そうです。意識回路を移植すれば、すぐ動けるとは言いましたけど……。"
90002070-48 = "だから！私を！使ってください！"
90002070-49 = "賛成できないわ。何が起きるか予測すらできないもの。あまりにも危険よ……。"
90002070-50 = "なにより、素体内部のセキュリティを、私たちで突破できるか確信が持てないわ。"
90002070-51 = "それは私がやってみます。#nさっきも言いましたが、時間があれば突破できるはずですから。"
90002070-52 = "[s] \"あんまり時間は残されてないんじゃないかな……。\""
90002070-53 = "うーん……可能性がない、とは言い切れませんが、やはりリスクを考えると――"
90002070-57 = "なぜやる前から諦めるんですか！"
90002070-58 = "やってみないと分からないんでしょう！？"
90002070-59 = "お、いつもの調子が戻ってきたみたい。"
90002070-60 = "この素体、鋼鉄大陸の素材で作ったものですよね？"
90002070-61 = "上手くいけば、何か手掛かりを掴める可能性だってあるじゃないですか！"
90002070-62 = "でも、失敗すれば……。"
90002070-64 = "だから、ネガティブなことばかり言わないでください！"
90002070-65 = "まずはやってみる！それでダメだったら、そのとき考えればいいじゃないですか！"
90002070-66 = "なんだか、いつにも増して感情的になっていませんか……？"
90002070-67 = "意識を移すこと自体は、既に成功しています。#nだって私、元々キーホルダーの中にいたんですよ？"
90002070-73 = "はい！アリス、まだ思い出として持っています！"
90002070-74 = "あ、はい。ありがとうございます。#nとにかく、私が言いたいのは――"
90002070-75 = "前回成功したのだから、今回も大丈夫だということです！"
90002070-76 = "もう何度目か分かりませんが……#nダメだったら、そのとき考えればいいでしょう！？"
90002070-77 = "もしかして……そんなに、今の身体が嫌なのかしら……？"
90002070-78 = "もし言うことを聞いてくれないのなら――"
90002070-79 = "私はもう一歩も動きませんから！！！"
90002070-8 = "……アリス。"
90002070-88 = "ケイ！？"
90002070-89 = "くっ……つい興奮して身体が……。"
90002070-91 = "[ns] \"……ケイの言うとおりにしてみない？\""
90002070-92 = "でも……。"
90002070-93 = "え？不可能なのか、って？#n違うと、思うわ……でも、やはり……リスクは伴うものよ。"
90002070-94 = "できれば、これ以上の変数は増やしたくないの。"
90002070-95 = "[s] \"成功すれば、得るものもあると思うよ？\""
90002070-96 = "希望的観測ではありますが……何にせよ、あの素体はデカグラマトンのエンジニアたちが作った可能性が高いです。"
90002070-97 = "加えて、セキュリティのシステムは、ほぼ間違いなくケイに関係がある。#n解析できれば、きっと大きな手がかりになるはずです。"
90002070-98 = "追加の補助記憶装置をつなげておくことで、失敗に備えることも可能です。"
90002070-99 = "ケイの意識を保存させることに、大きなリスクはないと考えられますが……。"
