[translation]
90002110-1 = "第11話;燔祭 "
90002110-10 = "（な……）"
90002110-100 = "ひぃっ……！？"
90002110-101 = "燔祭の剣が……。"
90002110-102 = "この時が……訪れてしまったんですね。"
90002110-103 = "お願いします。"
90002110-104 = "我が義務を果たすために――手を貸してください。"
90002110-106 = "……。"
90002110-107 = "う、ううう、ううううぅぅぅっ……！"
90002110-108 = "あああああああああああああ――！！！"
90002110-11 = "（何かが始まろうとしている……？これは一体……？）"
90002110-110 = "アイン、ソフ、オウル。ありがとうございます。#n……ごめんなさい。"
90002110-114 = "……さようなら。"
90002110-116 = "……。"
90002110-117 = "…………。"
90002110-118 = "………………。"
90002110-12 = "（この体内にある預言者の情報が……）"
90002110-122 = "第一の聖痕をここに刻まん。"
90002110-123 = "これは、「掟」となるもの。"
90002110-128 = "第二の聖痕をここに刻まん。"
90002110-129 = "これは、「証」となるもの。"
90002110-13 = "（急に自我を持ったかのような……！）"
90002110-134 = "最後の聖痕をここに刻まん。"
90002110-135 = "これは、「契約」となるもの。"
90002110-137 = "汝の意のままに為し給へ。"
90002110-138 = "我らはそれを喜ばむ。"
90002110-142 = "その思し召しが天にも地にも行われ――"
90002110-143 = "ここに、汝の王国が訪れる。"
90002110-144 = "器は用意された。"
90002110-145 = "やがて盃は満たされる。"
90002110-151 = "次回;消えたもの"
90002110-16 = "ダメ――！！！"
90002110-17 = "……？"
90002110-18 = "これは……？"
90002110-21 = "お姉様！！お姉様ぁ――！！！"
90002110-22 = "あぁ……もう、ダメだ……！"
90002110-23 = "私たちが……お姉様を……。"
90002110-25 = "[log][FF6666]ここに器は成った[-][/log]"
90002110-27 = "[log][FF6666]やがて盃は満たされる[-][/log]"
90002110-3 = "これは……！"
90002110-30 = "どうか、お願いします！もう少し時間をください！"
90002110-31 = "お姉様は最後のセフィラなんです！#nすべてのパスを正しく歩めば――"
90002110-32 = "10分……いや、1分で構わないから……。"
90002110-33 = "その望みは分かっています。私たちはそのために造られたのですから。#nですが……。"
90002110-40 = "[ns] \"あれは、一体……？\""
90002110-41 = "儀式のためにつくられた構造物のように見えますが……#n祭壇、とでも言うべきでしょうか？"
90002110-42 = "どうしてあんなものが……？#nそれに、鋼鉄大陸が……。"
90002110-44 = "これは……。"
90002110-45 = "なるほど。ですが、我の身体は……。"
90002110-46 = "いえ、だからこそ……でしょうか？"
90002110-47 = "……嗚呼。"
90002110-48 = "我は最後のセフィラ。#n祈る者の門――生命の樹の土台。"
90002110-49 = "すべてのパスを経て、□□□□へ成るための被造物。"
90002110-5 = "まさか……！"
90002110-50 = "これが定められた道であるのなら――"
90002110-52 = "嫌、嫌、嫌！！！"
90002110-53 = "あぁ、あぁぁ……。"
90002110-54 = "うっ、ううっ……。"
90002110-56 = "アイン、ソフ、オウル。"
90002110-57 = "為すべき事を為してください。"
90002110-58 = "！？"
90002110-59 = "為すべき事って……。"
90002110-60 = "そ、それは……。"
90002110-61 = "お願いします！お願いします！#nどうか……お姉さまを奪わないでください！！"
90002110-62 = "アイン！"
90002110-63 = "落ち着いてください！"
90002110-69 = "誰かが犠牲になる定めなら、私が代わりになるから――っ！！！！"
90002110-7 = "！？"
90002110-70 = "！？"
90002110-71 = "ケイ……？"
90002110-8 = "……？"
90002110-82 = "アイン、ソフ、オウル、ありがとうございます。#n……ですが、それは不可能です。"
90002110-83 = "どうしてですか？#nお姉様のためなら、私は――！"
90002110-84 = "アイン、思い出してください。"
90002110-86 = "[log][FF6666]それは能わず[-][/log]"
90002110-88 = "[log][FF6666]汝らには神秘が与えられていない[-][/log]"
90002110-9 = "ケイ？大丈夫ですか……？"
90002110-91 = "！！！！"
90002110-92 = "じゃあ、私たちをこのように造ったのは……。"
90002110-93 = "最初から、ぜんぶ……。"
90002110-94 = "アイン、ソフ、オウル。今一度考えてください。"
90002110-95 = "我々の目的、我々がここに居る理由を。"
