[translation]
90002250-1 = "第25話;エピローグ（１）"
90002250-10 = "一昨日のシャーレ当番、私だったんですよ？#n待ちぼうけの責任とってください！"
90002250-102 = "あ、いえ……ごめんなさい……そういうのではなくて……その……。"
90002250-103 = "ふふっ。#n……トキさんも、ご報告ありがとうございました。#nあれは要約版という理解でよろしいのでしょうか？"
90002250-107 = "は、はい……詳細については後ほど……。"
90002250-108 = "[s] （あのトキが怯えている……！）"
90002250-109 = "2人とも、本当によく頑張りましたね。"
90002250-11 = "[s] \"ごめんごめん。来週に埋め合わせさせてほしいな。\""
90002250-110 = "ただ……もう少しお話を伺いたい方が他にいまして――"
90002250-114 = "まずはケイちゃん。はじめまして。[ruby=うしお]生塩[/ruby]ノアです。#n直接お会いするのは初めてですね。"
90002250-118 = "ここでもケイちゃん呼ばわりですか……。[ruby=てんどう]天童[/ruby]ケイです。#nお会いできて嬉しいですよ。"
90002250-119 = "ええ、本当に。これからよろしくお願いしますね。"
90002250-12 = "本当ですか？約束ですよ！"
90002250-120 = "それと――"
90002250-127 = "うぅっ……！"
90002250-128 = "……。"
90002250-129 = "……。"
90002250-130 = "本当に……お久しぶりです、リオ会長。"
90002250-131 = "ま、待ってちょうだい。ちゃんと……説明できるわ。"
90002250-132 = "この場で焦って説明しなくていいですよ。"
90002250-133 = "そ、そう……？"
90002250-134 = "はい。話を聞きたがっている人は、別にいますから。"
90002250-135 = "それは、つまり……。"
90002250-136 = "ええ。ずっと待っていました。"
90002250-140 = "ユウカちゃんは、ずっと。"
90002250-141 = "！？！？"
90002250-142 = "中へどうぞ。"
90002250-148 = "わ、分かったわ……。"
90002250-149 = "……先生、なんだか私まで怖くなってきました……。"
90002250-150 = "[s] \"私も……。\""
90002250-151 = "ところで、会長？"
90002250-152 = "な、なにかしら……。"
90002250-153 = "ユウカちゃんは、怒ることもあれば拗ねることもあります。"
90002250-154 = "それでも、なんだかんだとお願いを聞いてくれる……私の優しい友達です。"
90002250-155 = "そんなユウカちゃんが、もしも本気で怒ったら――"
90002250-156 = "私にはどうしようもありませんので。"
90002250-157 = "！？！？！？"
90002250-158 = "せ、先生……！"
90002250-159 = "[s] \"リオ。\""
90002250-161 = "[ns] \"人には……覚悟を決めなきゃいけない時があるんだよ……！\""
90002250-162 = "……分かったわ。"
90002250-163 = "これが、私が背負うべきことなら……。"
90002250-172 = "あら、会長。すごく大変だったみたいですね。"
90002250-173 = "まずはミレニアムに戻ってきたことを歓迎するべきかしら？"
90002250-174 = "私たちが知らない間に、キヴォトスを救ったらしいですし。"
90002250-175 = "そこは感謝すべきよね。"
90002250-176 = "ええ、認めるものはちゃんと認めるわ。でないと次の話に進めないでしょう？"
90002250-180 = "その……話を聞いてちょうだい。全て説明するから――"
90002250-181 = "会長？"
90002250-182 = "その言い方だとまるで私が……。"
90002250-183 = "前々から会長が隠ぺいしていた横領の件から、その他にも諸々の話まで――"
90002250-184 = "必死に耐えているみたいじゃないですか。"
90002250-185 = "う、うぅっ……！"
90002250-186 = "……では。"
90002250-188 = "これからたっぷりとお話したいんですけど――"
90002250-189 = "いいですよね？"
90002250-190 = "ひぃっ……！"
90002250-197 = "う、うわーん！アリスは怖いです！"
90002250-198 = "これが……噂の……。"
90002250-20 = "あれ？いま、何か……。"
90002250-200 = "先生、私たちはどうすれば……！"
90002250-201 = "[s] \"た、耐えるんだ……！\""
90002250-208 = "ふふっ。"
90002250-209 = "ふふふっ。"
90002250-215 = "り、リオ先輩……？"
90002250-216 = "大丈夫ですか？いえ、聞くまでもないですが……。"
90002250-22 = "！？！？"
90002250-225 = "[ns] \"あれ？コユキ？どうして……？\""
90002250-227 = "……。"
90002250-228 = "何か、怒られるようなことでもやらかしたのでしょう。"
90002250-229 = "[s] \"そっかぁ……。\""
90002250-23 = "い、いえ！何も通りませんでしたよ！ですよね、トキ！？"
90002250-231 = "[ns] \"リオは……無事……？\""
90002250-236 = "……。"
90002250-237 = "大丈夫、よ。"
90002250-238 = "ええ……だい……じょう、ぶ。"
90002250-239 = "先生が言った通り、覚悟はできていたから……。"
90002250-24 = "は、はい。そう……です。"
90002250-240 = "その割にはダメージを負っているように見えますが……？"
90002250-241 = "……。"
90002250-242 = "1つ……。"
90002250-243 = "はっきり分かったことがあるわ。"
90002250-244 = "真実は……時に……。"
90002250-245 = "人の精神を刈り取るのだと……いうことを……。"
90002250-250 = "[ns5] \"リオ！？リオ――！！\"\n[ns6] \"リオ……うぅ……リオ……しくしく……。\""
90002250-255 = "かわいそうではありますが……。"
90002250-256 = "自業自得なのは、紛れもない事実ですから……。"
90002250-257 = "ある種の禊だと思って、見守るしかありませんね。"
90002250-263 = "はぁ……まったくもう……。"
90002250-264 = "[s7] \"や、やあ、ユウカ……。\"\n[s8] \"久しぶり……だね。\""
90002250-267 = "……。"
90002250-268 = "そうですね。アリスちゃんも、トキも。"
90002250-269 = "……！"
90002250-270 = "こ、こんにちは。"
90002250-271 = "ネル先輩……いえ、今回はヒマリ先輩ね。#nあとでそっちにもお話しに行かないと。"
90002250-272 = "……はい。"
90002250-273 = "それと……。"
90002250-277 = "あなたがケイちゃんね？"
90002250-278 = "……。"
90002250-279 = "ゆ、ユウカ！ケイは大丈夫です！安全です！"
90002250-280 = "な、なにか問題があったら……あ、アリスが絶対になんとかします！"
90002250-281 = "[s9] \"そうそう！私も責任とるから！\"\n[s10] \"だからとりあえず落ち着いて……ゆっくり話そう……？\""
90002250-287 = "そんなに慌てられると逆に怪しいんですけど……。"
90002250-288 = "……。"
90002250-289 = "まぁ、それでしたら先生はこの後にシャーレでお話しましょう。"
90002250-29 = "……？"
90002250-290 = "……！"
90002250-291 = "それで、アリスちゃんとケイちゃんについてなんだけど。"
90002250-292 = "うわーん……。"
90002250-293 = "そう怖がらないで。私だって大体の事情は知っているわ。"
90002250-294 = "はい……？"
90002250-295 = "え……？"
90002250-296 = "そ、そうなのですか……？でも、そしたらケイは……。"
90002250-297 = "あなたの場合と同じよ。"
90002250-298 = "はい……？"
90002250-3 = "あ、先生！"
90002250-30 = "そうかなぁ……？"
90002250-303 = "ケイちゃんの編入手続きを進めないとね。"
90002250-305 = "……？"
90002250-307 = "……！"
90002250-308 = "ありがとうございます！"
90002250-309 = "うんうん、素直にお礼を言えて偉いわね。"
90002250-31 = "[s1] \"そ、そうだよ！\"\n[s2] \"わ、私は気づかなかったなぁ！？\""
90002250-313 = "じゃあ先生。約束通り、ちょっとお時間いただきますよ。"
90002250-314 = "[s] \"は、はいっ！\""
90002250-321 = "そーれーで！昔からそうでしたけどリオ会長はですね！"
90002250-322 = "他人のことなんて気にもしないで、終わり良ければすべて良しって感じで！"
90002250-324 = "最後は補填してお金の帳尻をつける予定だった……って、コユキじゃないんですから！"
90002250-325 = "もちろん悪気がないことは分かってますけど！"
90002250-326 = "そもそも気の弱い人だし、そんなのできるはずないですし。"
90002250-327 = "[s11] \"ほ、ほら！ユウカ！甘いものどうぞ！\"\n[s12] \"こ、こっちにはゼロカロリーのやつもあるよ！\""
90002250-332 = "いただきます。もぐもぐ……。"
90002250-333 = "ふぅ……。"
90002250-334 = "[s13] （数時間お話して……）\n[s14] （ユウカの機嫌を直すことには成功した……）"
90002250-337 = "はぁ……悩ましいんですよね……。"
90002250-338 = "通常であれば、役職者の[ruby=・]不[/ruby][ruby=・]在[/ruby][ruby=・]で[/ruby][ruby=・]生[/ruby][ruby=・]じ[/ruby][ruby=・]た[/ruby]損害について、責任を取らせないといけないのですが……。"
90002250-339 = "そこに問題がありまして……。"
90002250-34 = "う～ん？いや、でも……。"
90002250-340 = "ミレニアムは別に、損害らしい損害を被っていないんです。"
90002250-341 = "今回の件だって、ミレニアムに実害があったかと言えば微々たるものですし……。"
90002250-342 = "[s15] \"となると……。\"\n[s16] \"リオを会長から解任させる、とか……？\""
90002250-347 = "いいえ？リオ会長以外、適任者なんていませんよ？"
90002250-348 = "意外そうな顔をされましても……。"
90002250-349 = "そもそもミレニアムは能力主義の学園です。#n実力だけを見れば、リオ会長に及ぶ生徒はいません。"
90002250-35 = "先生……何か隠してません？"
90002250-350 = "それに今回の件も、会長の成果にとやかく言うことはできません。"
90002250-351 = "まだ概要しか把握していませんが――"
90002250-352 = "世界を、キヴォトスを救ったのですから。"
90002250-353 = "[s17] \"そう思ってくれてありがとう。\"\n[s18] \"でも別の心配があって……。\""
90002250-356 = "はい？リオ会長が生活していけるか、ですか……？"
90002250-357 = "それはどういう……。"
90002250-358 = "はぁ……そうですね……。"
90002250-359 = "何事も、やってみないと分かりませんよ。"
90002250-36 = "あ～や～し～い～"
90002250-360 = "先生というお目付け役もいることですし！"
90002250-361 = "[s] \"そうだね。リオもたくさん学んでいたと思うし。\""
90002250-363 = "[ns] \"大丈夫……多分……。\""
90002250-364 = "ええ、まずは信じてみましょう。#n……気持ちは分かりますが。"
90002250-365 = "あとは……ケイちゃんの編入手続きの件ですね。"
90002250-366 = "手続きの進捗は……。"
90002250-367 = "……。"
90002250-368 = "ルール的に曖昧な部分がありまして。"
90002250-371 = "なにせ、生徒がいきなりミレニアムに現れたようなものですから。"
90002250-372 = "……あまり好きな表現ではありませんが、「魔法」のように現れた生徒です。"
90002250-373 = "その場合の対応については、ミレニアムの校則に載っていないんですよ。"
90002250-376 = "[ns] \"普通は想定しないもんね……。\""
90002250-377 = "はい。なので特例ということにして、最終決定権を持つ方に決めてもらいました。"
90002250-378 = "リオ会長が復帰していて助かりましたよ。"
90002250-379 = "もしも会長がいなかったら……誰が決定し、どのように責任をとり、どう状況を観察していくか等々……。"
90002250-38 = "うわーん！トキ、どうしましょう！"
90002250-380 = "最低3泊4日の会議コースでしたね。"
90002250-381 = "おかげでその事態は免れました。"
90002250-382 = "[s] \"結果は予想できるけど……リオは何て？\""
90002250-383 = "……こほん。"
90002250-384 = "どんな生徒であれ、学ぶ意志ある者を受け入れるのが、ミレニアムの建学理念よ。"
90002250-388 = "ケイも例外なく、ミレニアムサイエンススクールの生徒として歓迎するわ。#n……と。"
90002250-389 = "[s] \"話早くない！？\""
90002250-39 = "いざとなったら、修復したアビ・エシュフで物理的に記憶消去を……！"
90002250-390 = "手続き自体はアリスちゃんの時にやっていますから。"
90002250-391 = "ルールとして明文化されていないなりに、前例があると楽なんですよ。"
90002250-392 = "それから、ずっと他人の話ばっかりですけど……#n私がここに来ている理由は、他にもありますからね？"
90002250-393 = "[s] \"と言うと……？\""
90002250-394 = "……。"
90002250-399 = "どれだけ心配したか……！分かってますか！？"
90002250-4 = "こんにちは！アリスとトキも、やっほー！"
90002250-40 = "そ、それはいけないと思います！！"
90002250-400 = "あの時だって！ようやく居場所を特定できたと思ったら！凍原地帯ですよ！？"
90002250-401 = "こっちの気も知らずに、何とかするってだけ答えて……事情も説明してくれませんでしたよね……。"
90002250-402 = "そういう状況じゃなかったのは理解しています。#nそれに……先生のおかげで、鋼鉄大陸という危機も解決できました。"
90002250-403 = "でも……。"
90002250-405 = "心配、したんですよ……。"
90002250-406 = "[s] \"……ごめん。\""
90002250-407 = "もう知りません……。"
90002250-408 = "[s] \"2度としないから。\""
90002250-409 = "また似たようなことが起きれば、同じことを繰り返しますよね……？"
90002250-410 = "[s19] \"それは……否定できないけど……。\"\n[s20] \"でも、黙っていなくならないように……努力する。\""
90002250-413 = "……本当に？"
90002250-414 = "[s] \"う、うん！\""
90002250-415 = "……分かりました。"
90002250-418 = "その代わり、全部話してください。鋼鉄大陸であったことを。#nそれで……許してあげます。"
90002250-419 = "……はい？ああ、たしかに、もう報告は受けているのですが……「ミレニアム式」の報告書でしたから。"
90002250-42 = "あ！防犯カメラの映像見ればいいじゃん！#nできるよね？"
90002250-420 = "可能な限り修飾語を省き……事実だけを述べ……原因と結果だけを記したもの……。"
90002250-421 = "言葉は資源で、資源は合理的で効率的に消費されるべきだという――"
90002250-422 = "まさに、ミレニアムらしい報告書だったんですよ。"
90002250-423 = "[s] \"分かった。……でも、長くなるよ？\""
90002250-424 = "ふふっ、いくらでも。"
90002250-428 = "[ns] \"それじゃあ……何から話そうか。\""
90002250-43 = "余裕。"
90002250-430 = "（ユウカは笑ったり、感動したり、時には疑ったり……時には、涙を流していた）"
90002250-431 = "（ユウカに、すべての出来事を話した）"
90002250-44 = "[s] \"できるの！？\""
90002250-448 = "（鋼鉄大陸、デカグラマトン、アイン、ソフ、オウル）"
90002250-449 = "（そして、ケイのこと）"
90002250-45 = "もちろんです。私たちだってミレニアムの生徒なんですから。#n……どう？何か映ってた？"
90002250-453 = "……先生。"
90002250-454 = "[s] \"うん？\""
90002250-455 = "寝てます？"
90002250-456 = "[s] \"ちょっと眠いけど……まだ……。\""
90002250-457 = "そうですか。"
90002250-458 = "今日はもう休んでください。"
90002250-459 = "……心配しなくて大丈夫です。"
90002250-466 = "ケイちゃんは、何があっても……どんな手を使ってでも。"
90002250-467 = "必ず、ミレニアムでの居場所を作ってみせますから。アリスちゃんと一緒に。"
90002250-468 = "先生、本当にお疲れ様でした。それと……。"
90002250-472 = "ありがとうございました。"
90002250-474 = "次回;エピローグ（２）"
90002250-49 = "いや……特には何も……。"
90002250-5 = "こんにちは！"
90002250-50 = "なーんだ。つまんないの。"
90002250-51 = "[s] \"ほ、ほら。何にもなかったでしょ？\""
90002250-52 = "ですね。私たちの勘違いだったみたいです。"
90002250-53 = "じゃあ先生、私たちはこれで。アリスとトキもまたね～"
90002250-6 = "こんにちは！"
90002250-60 = "た、助かりました……。"
90002250-61 = "なんとかなりましたね。リオ様、ケイ。もう出てきていいですよ。"
90002250-67 = "ふぅ……。"
90002250-68 = "勢いで一緒に隠れましたけど、どうして私まで……。"
90002250-7 = "やっほー、です。"
90002250-70 = "これもある種のチームプレイかと。"
90002250-71 = "また適当なこと言って……。"
90002250-78 = "……。"
90002250-79 = "リオ？"
90002250-80 = "ついにここまで来てしまったのね……。"
90002250-81 = "大丈夫です、リオ先輩。#nアリスも一緒に勇気を出します！きっとうまく――"
90002250-87 = "あら、先生。こんにちは。アリスちゃんにトキさんも。"
90002250-88 = "う、うわーん！？"
90002250-9 = "そういえば、何かあったんですか？#nここ数日連絡つかなかったですけど……。"
90002250-94 = "[ns3] \"勇気を出すって言ってなかった！？\"\n[ns4] \"急に私の後ろに隠れても……！\""
90002250-97 = "どうかしましたか？まるで怖いものでも見たかのように。"
