[translation]
90002010-1 = "第1話;Phase Shift"
90002010-4 = "ソフ！何度も言いましたよね？#nお、お姉ちゃんも、そろそろ怒りますよ？"
90002010-5 = "ごめんなさい、アインお姉ちゃん！#nもうしないから許してください……。"
90002010-6 = "こ、今回だけですからね？#nえへへ、ソフはいい子だって、お姉ちゃんは知ってますから。"
90002010-7 = "それとオウル！あんまりソフをいじめちゃダメです。#nオウルもやりすぎですよ！"
90002010-8 = "ですが、先にソフが……。"
90002010-9 = "オウル！"
90002010-10 = "わ、分かりましたよ……。#nごめんなさい……。これでいいですか？"
90002010-11 = "うーん……ま、まだ反省の色が薄いですけど……。"
90002010-12 = "オウルにしては頑張りましたね！えらいえらい。"
90002010-18 = "アイン？何をしているのですか？"
90002010-19 = "ひゃあああぁっ！？マルクトお姉様！？"
90002010-22 = "なるほど。人間がよくやる「おままごと」ですか。"
90002010-23 = "そして、この機械人形はそれぞれソフとオウルなのですね。"
90002010-24 = "は、はい……。ごめんなさい、マルクトお姉様……。"
90002010-25 = "謝らないでください。アインが楽しんでいたのなら、我も嬉しいです。"
90002010-26 = "それで……こちらの機械人形は？"
90002010-27 = "はい！その子たちは……えっと……。"
90002010-28 = "わ、私の妹です！"
90002010-29 = "なるほど……？"
90002010-30 = "だ、だから、マルクトお姉さまの妹でもあります！"
90002010-31 = "ふむ……？"
90002010-32 = "えっと……この子たちは私の妹で……わ、私はマルクトお姉様の妹ですから……。"
90002010-33 = "知っています、アイン。我は「長女」ということですね？"
90002010-34 = "は、はい！そうです！"
90002010-35 = "では……。#n初めまして。我はマルクトと言います。"
90002010-36 = "お、お姉様が、妹たちに挨拶を……！#nど、どうしましょう……幸せ過ぎて、回路がショートしてしまいそうです……！"
90002010-37 = "ところで、アイン？"
90002010-38 = "はい！"
90002010-39 = "我の人形は、無いのですか？"
90002010-45 = "ご、ごごごご、ごめんなさい、お姉様！ま、まさかこんなことになるとは思ってなかったので……。す、すぐに作ります！"
90002010-46 = "大丈夫ですよ。"
90002010-47 = "我々は今、「最後の時」を待っているのですから。"
90002010-48 = "緊張を緩めるくらいがちょうどいいのだと、我は思います。"
90002010-49 = "で、ですが……鋼鉄大陸に流れる「名もなき神々の力」の[ruby=Phase]位相[/ruby]を、急いで変更しないといけなくなって……。"
90002010-50 = "うぅ……。お、王女と侍女さえいなければ……。"
90002010-51 = "我はアインを信じています。全く心配していませんよ。"
90002010-52 = "それに「マルクト機械人形」だって、アインが作ってくれるのですよね？"
90002010-53 = "……！"
90002010-54 = "も、もちろんです！お姉様！"
90002010-55 = "ですがそうなれば……マルクト機械人形は、アインのもう一人の妹になりますね。"
90002010-56 = "――こんにちは、アインお姉ちゃん。"
90002010-57 = "きゃ、きゃぁああああっ！？"
90002010-58 = "マルクトお姉様が、わ、私を、お姉ちゃんと……。"
90002010-63 = "少々、冗談がすぎたでしょうか……。"
90002010-65 = "……。"
90002010-66 = "はぁ……どうしよう……。"
90002010-67 = "……。"
90002010-68 = "ティファレト……。"
90002010-75 = "ソフ？何をしているのですか？"
90002010-76 = "うわっ！？マルクトお姉様！？"
90002010-77 = "え、えっと……。"
90002010-78 = "手に持っているのは……何かを密閉する箱ですか？"
90002010-79 = "少し割れているようですが……それは？"
90002010-80 = "これは……その……。"
90002010-81 = "……種子が入ってる箱。#nティファレトが送ってくれたうちの1つだよ。"
90002010-82 = "お姉様も知ってるよね？#nティファレトは、自分より種子を優先したって……。"
90002010-83 = "はい。そして我々は、その選択を尊重することにしました。"
90002010-84 = "でも、保管状態のよくない箱がいくつかあったんだ。"
90002010-85 = "……これは、その中でも一番ひどいやつ。"
90002010-86 = "[ruby=・]保[/ruby][ruby=・]管[/ruby][ruby=・]状[/ruby][ruby=・]態[/ruby][ruby=・]が[/ruby][ruby=・]よ[/ruby][ruby=・]く[/ruby][ruby=・]な[/ruby][ruby=・]い[/ruby]とは、何を意味しますか？"
90002010-87 = "……すぐにでも発芽する状態になっちゃってるの。"
90002010-88 = "だからって、鋼鉄大陸で芽を出しても……。"
90002010-89 = "あっ、こ、こんなことで悩むのは私らしくない、ってのは分かってるよ！"
90002010-90 = "だけど、ティファレトは……。"
90002010-91 = "……。"
90002010-92 = "ソフ。#nティファレトは今この瞬間も、[ruby=・]確[/ruby][ruby=・]か[/ruby][ruby=・]に[/ruby]我々と共にいます。"
90002010-93 = "うん……。"
90002010-94 = "そして、「ティファレト」の意志を大事にしたい、というソフの気持ちも、我は理解します。"
90002010-95 = "ですので、こうするのはどうでしょう？"
90002010-101 = "こっそり……種子を聖地に植えてみるというのは。"
90002010-102 = "お、お姉様！？でも、それは……！"
90002010-104 = "ええ、分かっています。#nそれは、我々の掟に反する可能性がある行為です。"
90002010-105 = "ですが聖地は、鋼鉄大陸の始まりであり、今なお「土壌」が残っている唯一の場所でもあります。"
90002010-106 = "それはあそこにだけ、ネツァクの能力を使わなかったからで……。"
90002010-107 = "聖地には、あの方の意志が……。"
90002010-108 = "ではこう考えてみるのはどうでしょうか。"
90002010-109 = "あらゆる苦難を乗り越えて、種子が根を下ろすのであれば……#nそれこそ、ティファレトの残した自由意志が、実を結ぶ瞬間だ、と。"
90002010-110 = "自由意志は人間のみならず我々にも、ひいてはあの方にも大事な要素ですから。"
90002010-111 = "たとえ、それらすべてが、突き詰めれば錯覚による嘘だとしても、です。"
90002010-112 = "でも……本当に、良いのかな……？"
90002010-113 = "もちろん、良いことではありません。"
90002010-114 = "お姉様！？"
90002010-115 = "これは我と共にやる、「悪いこと」です。"
90002010-116 = "悪い、こと……！"
90002010-117 = "そして悪いことは、なぜか「楽しいこと」らしいですね。"
90002010-118 = "うん。背徳感って言うんだって……。"
90002010-119 = "ですから今回だけ、一緒に悪いことをしてみましょう。"
90002010-120 = "ティファレトは、今も我々と共にあります。"
90002010-121 = "ですが……[ruby=・]テ[/ruby][ruby=・]ィ[/ruby][ruby=・]フ[/ruby][ruby=・]ァ[/ruby][ruby=・]レ[/ruby][ruby=・]ト[/ruby]のことを忘れたくないから、悩んでいるのでしょう？"
90002010-122 = "それに何より、我々は「最後の時」を待っているのですから。"
90002010-123 = "先に言ったのは、お姉様だからね……？"
90002010-124 = "ええ。姉妹仲良く、イタズラをしてみましょう。"
90002010-125 = "うん！"
90002010-130 = "それはそれとして……。"
90002010-131 = "「名もなき神々の力」の位相変換は順調ですか？"
90002010-132 = "あ、それ？お姉様は心配しなくていいよ。あの二人が鋼鉄大陸に着いたとしても、エネルギーを自由に扱うことはできないはずだから。"
90002010-133 = "……根っこから完全に変換できなかったのは残念だけど。"
90002010-134 = "でも下手すれば、あの力で構築してる鋼鉄大陸も、#n使えなくなるかもしれないし……。"
90002010-135 = "そうでしたか。では足りないところは、我々が補っていくとしましょう。"
90002010-136 = "うん……。"
90002010-140 = "オウル？何をしているのですか？"
90002010-141 = "……。"
90002010-142 = "……？"
90002010-143 = "なるほど、自分の世界に入っているのですね。"
90002010-144 = "では、失礼します。"
90002010-152 = "むにゃむにゃ……。"
90002010-157 = "こほん。オウル？何をしているのですか？"
90002010-158 = "ふにゃ……？"
90002010-162 = "うぇっ！？マルクトお姉様！？どうしてここに……！？"
90002010-163 = "驚くことはありません。"
90002010-164 = "我は原則として、この鋼鉄大陸のどこにだって行けるのですから。"
90002010-165 = "たしかに、そうですが……。"
90002010-166 = "ふむ……これはすごく……「自然的な」世界ですね。"
90002010-167 = "……お姉さまもそう思いますか？"
90002010-168 = "私たちは意識回路の領域に「ブラックボックス」と呼べるような部分が存在しますよね？"
90002010-169 = "はい。人間の表現を借りれば、無意識の領域とも言えますね。"
90002010-170 = "それがどんな風になっているのか気になって、意識回路の一部をビッグデータとして抽出してみたんです。"
90002010-171 = "それだけでこのような心象世界が再現されたのですか？"
90002010-172 = "そうなんですよ。#n生命だの自然だのってソフが言うから、私も影響されてしまったみたいです。"
90002010-173 = "その割には、大したことない風景ですけどね。"
90002010-174 = "でも、まあ……。"
90002010-175 = "ただ……。"
90002010-176 = "ここにいると、思考回路のノイズが静まる気がして……。"
90002010-177 = "我もそのように感じます。"
90002010-178 = "ところで、アインとソフから聞いたのですが、「名もなき神々の力」の位相を変換しているそうですね。"
90002010-179 = "え？あ、はい……。#nはぁ、最後の最後に、こんなことをする羽目になるなんて……。"
90002010-180 = "お姉様の身体を再調整しないといけなくなりましたし……。#nまぁ、長くはかかりませんが。"
90002010-181 = "これも全部、あの[USERNAME]先生とかいう人間のせいです。まったくもう！"
90002010-182 = "どうどう、そんなに怒らないでください。"
90002010-183 = "真摯に話し合えば、[USERNAME]先生も、我々のことを理解してくれるはずです。"
90002010-184 = "というわけですから、一緒に日光浴をしませんか？"
90002010-185 = "日光浴、ですか？"
90002010-186 = "横になって、何もせず日光を浴びる行為です。"
90002010-187 = "電気信号として与えられる「光を浴びているという感覚」に過ぎず――"
90002010-188 = "その信号を受け取った感覚回路が、「満足した」というフィードバック信号を返しているだけの話ですが。"
90002010-189 = "とはいえ、オウルと一緒に時間を過ごせるだけで、我はじゅうぶん有意義な行為だと思います。"
90002010-193 = "はい！もちろんです、お姉様！"
90002010-194 = "では、そうしましょう。"
90002010-198 = "我々は、「最後の時」を待つ身ですから。"
90002010-201 = "次回;風雲急を告げる"
