[translation]
90002080-1 = "第8話;可能性"
90002080-10 = "問題ですか？"
90002080-100 = "……この身体は、鋼鉄大陸で作られたものですから。"
90002080-101 = "それにどんなメリットがあるのかしら。"
90002080-102 = "情報コアを吸収すればするほど、鋼鉄大陸は私を――"
90002080-103 = "預言者の集合体や、その上位存在として認識するはずです。"
90002080-104 = "すべての情報コアを集めれば、鋼鉄大陸に命令を下すこともできると思います。"
90002080-105 = "たとえば、「拡張中止」や「稼働停止」の命令とか。"
90002080-106 = "[s] \"それじゃあ、この事態も……！\""
90002080-107 = "はい。根本的に解決できるかもしれません。"
90002080-11 = "預言者たちは、それぞれが割り当てられたエリアを守っているようなのですが……#n現状では、その位置を特定できていません。"
90002080-111 = "……。"
90002080-112 = "なるほど！エリアを占領してボスを倒すと、ケイがレベルアップするということですね！"
90002080-113 = "レベルカンストになって資格を得たケイが、鋼鉄大陸を止める！#nそれでゲームクリアです！"
90002080-114 = "良い例えだと思います。ですが……。"
90002080-115 = "違うのですか……？"
90002080-116 = "今の私たちが戦える預言者は、10体ではなく8体です。"
90002080-117 = "つまり……レベル100ではなく、80までしか上げられないということです。"
90002080-119 = "そういえば……たしかに？"
90002080-12 = "やはり、情報が高度に隠ぺいされているのですか？"
90002080-120 = "ネツァクとマルクトは、今のところ倒す手だてがないから……。"
90002080-122 = "それでも、これが唯一ともいえる方法です。"
90002080-123 = "なにより、多少なり鋼鉄大陸の活動を阻害できるはずです。"
90002080-124 = "[s] \"じゃあ、これからの目標は……。\""
90002080-129 = "ええ。エリアを占領し、預言者を倒したあと――"
90002080-13 = "はい。もっとかみ砕いて言えば――"
90002080-130 = "コアの情報を回収して、ケイに保存させる。"
90002080-131 = "すべてが上手くいけば、これで鋼鉄大陸を止められる。"
90002080-132 = "決まりだね。"
90002080-133 = "でしたら、相応の準備が必要かと。"
90002080-134 = "[s] \"というと？\""
90002080-135 = "アビ・エシュフが使用不能になっています。"
90002080-136 = "マルクトとの戦闘で、外部パーツがすべて破壊されてしまいましたので。#n損傷は内部のフレームにまで及んでいます。"
90002080-137 = "ただ、まだ生きているパーツを取り出せば、リサイクルすることは可能です。#nこれらの条件をすべて踏まえると――"
90002080-138 = "可愛いアリスに、アビ・エシュフを引き継がせるのが最善だと思います。"
90002080-14 = "かくれんぼが上手、という感じでしょうか。"
90002080-140 = "はい！？アビ・エシュフをアリスに、ですか！？"
90002080-141 = "できることは何でも試してみるべきです。"
90002080-142 = "とはいえ、問題になるのは時間です。"
90002080-143 = "今のアビ・エシュフからパーツを取り出して、再整備したあと、アリスの身体に合うよう改造する。これだけの作業をする時間は……。"
90002080-144 = "再武装は、私たち全体として必要ですよ。"
90002080-145 = "でも、今はこの地域を維持するだけでも精一杯で……。"
90002080-149 = "……。"
90002080-15 = "とはいえ、預言者についての情報は把握できました。"
90002080-150 = "具体的には何が必要ですか？"
90002080-152 = "はい？"
90002080-153 = "大きく分けて2種類。[ruby=・   ・   ・   ・   ・   ・   ・   ・   ・]直接的に必要なもの[/ruby]と、#n[ruby=・   ・   ・   ・   ・   ・   ・   ・   ・   ・   ・   ・]それを用意するためのもの[/ruby]が必要よ。"
90002080-154 = "人手が圧倒的に足りない上に、AMASはほぼ壊滅状態。#n加えて、自動化を補助する色んな設備を含むと――"
90002080-16 = "これまでの預言者については、#n「生命の樹」の調査データに情報があるので、ここでは割愛します。"
90002080-160 = "[ns] \"えっと……。\""
90002080-162 = "そ、それって新しく工場を建てるようなことなんじゃ……。"
90002080-167 = "非現実的ではあります。それでも、なんとか方法を探すしかありません……。"
90002080-169 = "それらが揃えば、なんとかなるんですよね？"
90002080-17 = "まず、鋼鉄大陸そのものである「[ruby=Netzach]ネツァク[/ruby]」。#nその異名は「勝利を証明する無限の大地」、[ruby=Path]パス[/ruby]は「遂に到達せし勝利」です。"
90002080-171 = "！？"
90002080-172 = "！？"
90002080-174 = "け、ケイ？アリスにはよく分かりませんが、用意するのは難しいのでは……。"
90002080-175 = "いえ、できます。"
90002080-176 = "アリスと私なら、いくらでも。"
90002080-177 = "ケイとアリスで、ですか……？"
90002080-178 = "はい。物質の再構築は、名もなき神々の力でも代表的なものです。"
90002080-179 = "そして鋼鉄大陸は、その力を使って[ruby=・   ・   ・]再構築[/ruby]されています。"
90002080-180 = "たしか、出発前に聞いた話ではありますが……はっ、まさか！？"
90002080-181 = "そのまさかです。"
90002080-182 = "可能なのですか！？"
90002080-183 = "アリスと一緒なら。"
90002080-184 = "でも、アリスはどうすればいいか、分かりません……。"
90002080-185 = "大丈夫です、アリス。あの時と同じです。"
90002080-190 = "ここは、どこよりも名もなき神々の力で満ちた場所。#nそれは、マルクトとの戦いで実感しました。"
90002080-191 = "色々とアレンジされてはいますが……使えないことはないと思います。"
90002080-192 = "それに、この身体を得たのであの時より精密にエネルギーを整えられるはずです。"
90002080-193 = "ですから、ここで見せてやりましょう。"
90002080-194 = "私たちに何ができるのか。私がどういう存在だったのか。"
90002080-200 = "私たちが本来――何で在るべきだったのかを。"
90002080-201 = "アリスは……何をすればいいですか？"
90002080-216 = "簡単です。私の目を見てください。あの時と同じように。"
90002080-217 = "アリス――手を。これが、私とあなたをつなぐ道になります。"
90002080-218 = "さあ、想像してください。"
90002080-22 = "分かりやすい異名ね。"
90002080-23 = "次に、行方をくらませた「[ruby=Yesod]イェソド[/ruby]」。#n異名は「礎を御する力の浄化者」。"
90002080-233 = "想像、ですか……？"
90002080-234 = "はい。みんなに必要なもの。先ほどリオが話したこと。#nアビ・エシュフのフレームと、それをベースにしたもの。"
90002080-235 = "……あなたが、成そうとすることを。"
90002080-236 = "大まかで十分です。詳細は私が補います。#nアリスは……ただ想像すればいいのです。"
90002080-24 = "[ruby=Path]パス[/ruby]は、「完成に向かい進む真理」だそうです。"
90002080-240 = "怖がらなくて大丈夫です。"
90002080-241 = "オーロラが舞い降りたあの夜のように。"
90002080-255 = "あなたのすべてが、まだ見ぬ可能性で満たされますように――"
90002080-260 = "アリスちゃん……ケイちゃん……。"
90002080-262 = "すごい……ゲームみたい……。"
90002080-263 = "うん……今回はお姉ちゃんの例えが合ってるかも……。"
90002080-264 = "アリス……？"
90002080-269 = "……？"
90002080-270 = "えっ、えぇっ！？アリス、すごく強そうな鎧を獲得しました！#nこれは、いったい……！？"
90002080-272 = "「私たち」が到達した、一つの可能性です。"
90002080-273 = "これが……[ruby=・   ・   ・]アリス[/ruby]のアビ・エシュフなのですね。"
90002080-274 = "どう？部長。#n「特異現象」を目にした感想は？"
90002080-275 = "ここに来てから、あらゆるものが特異現象ではありました。#nですが、これはその中で最も印象的で――"
90002080-277 = "感動的な特異現象です。"
90002080-279 = "次回;Dress Up"
90002080-29 = "あ、ちょっとごめん。前から気になってたんだけど、異名とかパスって何なの？#nそれがあると効率が上がったりする？"
90002080-3 = "この鋼鉄大陸は、7番目の預言者「ネツァク」を極限状態まで[ruby=・   ・]進化[/ruby]させ、存在を拡張させたものです。"
90002080-30 = "私も詳細までは分かりません。#nただ、どうやらパスをもとにして、エネルギーの流れを調整しているようです。"
90002080-31 = "その目的は、新しい可能性に到達するため、なんだとか。"
90002080-32 = "新しい可能性って？"
90002080-33 = "……私にも分かりません。"
90002080-34 = "なーんだ。ケイも知らないこと多いんだね！"
90002080-35 = "はい！？"
90002080-36 = "お姉ちゃん！なんでそういうこと言うの！#nケイちゃん、ごめんね……。"
90002080-37 = "ふぅ……大丈夫です、ミドリ。気にするほどのことではありませんから。"
90002080-38 = "へー？否定はしないんだー？"
90002080-39 = "モーモーイー！！！！"
90002080-4 = "その過程で、ネツァクは原形を留めなくなりました。"
90002080-43 = "あはははっ！ケイが怒った！"
90002080-44 = "はぁ……。"
90002080-45 = "付き合っていられませんし、話を戻しましょう。#n最後は「[ruby=Malkuth]マルクト[/ruby]」です。異名は「世界の果てに到達せし王国の巡礼者」。"
90002080-46 = "[ruby=Path]パス[/ruby]は……「御旗の下に創造されし一つの意志」。"
90002080-5 = "そして、ここにはすべてのデカグラマトンの預言者が集められています。"
90002080-54 = "おおっ？なんかいい感じじゃん。次のゲームの参考にしよっかな。"
90002080-55 = "いっそ、そのほうがいいかもしれませんね。"
90002080-56 = "あれ？今度は怒らないの？"
90002080-57 = "どうでもいい言葉遊びやら、内輪ネタで増やされた設定なんて――"
90002080-58 = "モモイのシナリオにでも使われたほうが、収まりが良いと思いまして。"
90002080-59 = "け、ケイちゃん……そこまで言うのは……。"
90002080-6 = "厳密に言えば、複製体であるようですが……だからと言って、オリジナルとの違いはありません。"
90002080-60 = "……そうですね、少し言い過ぎたかもしれません。#nモモイ、ごめんなさい。"
90002080-61 = "え？"
90002080-62 = "なんで謝られてるの？私。"
90002080-63 = "……まあ、いいです。モモイは元々こうでしたし……。"
90002080-64 = "よ、よかったの……かな……？"
90002080-65 = "とにかく、一番の問題はマルクトです。"
90002080-66 = "今の私たちでは、太刀打ちできません。"
90002080-67 = "さっきだって、全滅させられていてもおかしくありませんでした。#nこうしていられるのも、なぜかマルクトが撤退したから。"
90002080-68 = "……まるで、何かに追われていたかのように。"
90002080-69 = "[s] \"あれはどうしてだと思う？\""
90002080-7 = "複製体でしたか、どうりで。"
90002080-70 = "そうですね……#nまず考えられるのは、マルクトの稼働時間は極端に短いのかもしれません。"
90002080-75 = "短期決戦のみを想定している、ということでしょうか？"
90002080-76 = "実戦向きじゃないね。規格化と標準化が大事なのに。"
90002080-77 = "戦闘は、物量だからね。"
90002080-8 = "キヴォトスを鋼鉄大陸で覆ってしまえば、いつでもオリジナルに統合できるという算段なのでしょう。"
90002080-83 = "……あるいは、戦闘以外の用途も想定されているのかしら。"
90002080-84 = "何か別の役割があるって話？"
90002080-86 = "あいにく、ここで議論をするのは時間が惜しいです。"
90002080-87 = "情報を整理すると……#n鋼鉄大陸は、預言者の担当ごとに分割されていることは確かです。"
90002080-88 = "そして各エリアを「占領」して、私たちの支配下に置くことも可能なはずです。"
90002080-89 = "……そういえば、あれ以来敵が襲ってきませんね。"
90002080-9 = "さて……ここで問題があります。"
90002080-90 = "言うタイミングを逃していたのだけれど、この周辺は占領が完了したわ。　"
90002080-91 = "具体的には、マルクトの襲撃があった時点でね。"
90002080-92 = "占領してからは、デカグラマトンの兵とレイバーが活動を見せなくなった。"
90002080-93 = "予想通りですね。#n電子的に占領すれば、その地域への敵の支援を止めることができる。"
90002080-98 = "そして、エリアの占領に成功すれば……#n預言者を引きずり出すこともできるはずです。"
90002080-99 = "最後に、重要なことを。預言者は「情報コア」というものを有しているようです。#n倒して回収すれば、私の身体に吸収できるかと。"
