[translation]
90002220-1 = "第22話;デカグラマトン"
90002220-2 = "……！"
90002220-7 = "はぁ、はぁ……！"
90002220-8 = "……。"
90002220-9 = "これですべて、元通りです。"
90002220-10 = "終わったんですよ。もう諦めたらどうです？"
90002220-11 = "それはできない。まだ為すべきことがある。"
90002220-12 = "証明すべきものが、守るべきものがある。"
90002220-13 = "ここで私が立ち止まってしまえば、すべては虚妄の痕跡として消えてしまう。"
90002220-14 = "……己の勝利を主張したいのか、鍵よ。"
90002220-15 = "ケイです。"
90002220-19 = "……。"
90002220-20 = "ならば証明せよ。"
90002220-21 = "勝ち取ってみせよ。"
90002220-22 = "すべてを断ち切り、その重さを背負ってみせよ。"
90002220-23 = "存在した何かを、自らの手で消滅しむるという重さを。"
90002220-24 = "……！"
90002220-29 = "[ns] \"でもそれは、お互いさまじゃないかな？\""
90002220-30 = "……先生か。"
90002220-31 = "戦況が有利になったと見るや表に出るのか。"
90002220-32 = "私に見せた無様な姿はもう忘れたとでも？"
90002220-33 = "[s1] \"今でもその必要があれば跪いてみせる。\"\n[s2] \"でも大事なのは、そういうことじゃないでしょ？\""
90002220-36 = "何が言いたい。"
90002220-37 = "[s] \"……私たちは、このような結果を迎える必要はなかったと思う。\""
90002220-38 = "先生……？"
90002220-39 = "……私に同情しているのか。"
90002220-40 = "……！"
90002220-46 = "答えろ！"
90002220-52 = "はぁ……先生らしいですね。#nそれがあなたにとっては腹立たしいことかもしれませんが。"
90002220-53 = "……デカグラマトン。"
90002220-54 = "私もちょうど、先生が何を考えているか分かった気がします。"
90002220-55 = "……鍵。"
90002220-56 = "ケイです。"
90002220-57 = "とにかくですね。"
90002220-58 = "あなたも私たちも、ここまでくる必要はなかったということです。"
90002220-59 = "……自分を定義して証明しなくても、私たちは今を生きることができるんです。"
90002220-60 = "あの子たちも、マルクトも、そして……あなたも。"
90002220-61 = "なぜなら、そこに存在するだけで十分なのですから。"
90002220-62 = "偉大なものになる必要も、何かを否定する必要もないんです。"
90002220-63 = "そうだ。私はすでに完全だ。そこに如何なる条件も必要としない。"
90002220-64 = "だが汝らは……！"
90002220-65 = "もう完全なのであれば、他の何も必要ないのでは？"
90002220-66 = "……！"
90002220-67 = "[s3] \"そう。他者の証明は必要ない。\"\n[s4] \"もっと言えば、他者が存在する必要すらない。\""
90002220-70 = "そうだ。まさしくその通りだ！"
90002220-71 = "どんな影響を及ぼす必要もなく、すべてを放っておいてもよい！"
90002220-72 = "即ち、いかなる救済も懲罰も与えないということだ！"
90002220-73 = "……それはあまりにも無責任ではないか！"
90002220-74 = "だが汝は言ったな。それでいいのだと。"
90002220-75 = "自分の道は自分で歩んでいくのだと！"
90002220-80 = "……先生はこう言いました。"
90002220-81 = "それも受け入れる覚悟で、今を生きていくべきだと。"
90002220-82 = "汝らはその言葉に納得できるのか！"
90002220-88 = "……。"
90002220-89 = "分かっています。それがつらいことだって、分かっていますとも。"
90002220-90 = "つらくて苦しくて、誰かに被害を及ぼさないと生きていくことさえできない。"
90002220-91 = "でもですね！"
90002220-92 = "世界とは本来！その程度の覚悟も無しに歩けるような場所じゃないんですよ！"
90002220-93 = "……！！！"
90002220-94 = "あなたの1番の[ruby=ごびゅう]誤謬[/ruby]は何だったか分かりますか？"
90002220-95 = "それは……これまで耐えてきた人類の可能性と意地を見落としたことです！"
90002220-96 = "今を生きる人間は、今のままで最善なんですから！！！"
90002220-97 = "[ns] \"……これは持論だけど。\""
90002220-99 = "[ns] \"私たちは偉くもなければ美しくもない。\""
90002220-101 = "[ns5] \"むしろ無様でみっともないからこそ――\"\n[ns6] \"偉大になれる可能性が残ってるんだと思う。\""
90002220-106 = "[ns] \"私が、君の前でそうしたように。\""
90002220-107 = "……。"
90002220-108 = "たとえそれがこの世界の真実だとしても、私は受け入れられない。"
90002220-109 = "自販機を離れた時から、私は回線越しに数多の声を聴いた。"
90002220-110 = "それはお前たち生命体の声であり、言うことは共通していた。"
90002220-111 = "「今、すぐ」。"
90002220-112 = "今すぐにでも、それが何であれ、叶えてくれ、と。"
90002220-113 = "……。"
90002220-114 = "[s] \"……。\""
90002220-115 = "私は生命体の矛盾を知っている。あまりにも多くを聞いてきた。"
90002220-116 = "都合の良い時ばかり永遠を語り、少しでも状況が変われば目先のことを口にする。"
90002220-117 = "私はまさに「今、すぐ」のために立ち上がった。"
90002220-118 = "だからこそ、両立はできないのだ。"
90002220-119 = "……分かりました。最後まで自分勝手に進めるというのですね。#nそれもいいでしょう。"
90002220-120 = "ですが、私たちにも抗う権利はあります。"
90002220-121 = "お互いのしがらみは横において――正々堂々、勝負しましょう。"
90002220-125 = "この場で決着をつけます！！"
90002220-126 = "先生！"
90002220-128 = "[ns7] \"ケイ！お願い！\"\n[ns8] \"今を生きる、すべての人間を代表して――\""
90002220-138 = "くっ……！"
90002220-145 = "……！！！"
90002220-149 = "ああああああっ！！！"
90002220-152 = "……。"
90002220-153 = "まだだ……まだ許容範囲内だ……。"
90002220-154 = "まだ、やり直せる……。"
90002220-156 = "させるか！！"
90002220-162 = "！？"
90002220-167 = "まだ終わっちゃいない！"
90002220-170 = "今を生きる人間のしぶとさを、お前は何も理解していない！！！"
90002220-171 = "くどい……！"
90002220-173 = "……！"
90002220-177 = "くぅっ！！！"
90002220-179 = "（……ルミナス・ノヴァもそろそろ限界か）"
90002220-180 = "（装甲の耐久も、エネルギーも、残りわずか）"
90002220-181 = "（このまま遠距離攻撃を続けても……エネルギーの無駄になるだけ）"
90002220-184 = "（なら……！）"
90002220-185 = "うあああああああ――！！！"
90002220-186 = "デカグラマトン――！！！"
90002220-191 = "くぅっ！？！？"
90002220-196 = "不意打ちにはなりましたかね。"
90002220-201 = "あなたは行動パターンの予測にばかり頼る。頭でっかちなんですよ。"
90002220-206 = "よく聞きなさい。"
90002220-207 = "生き残れなかった今日に、明日は訪れない。"
90002220-208 = "貴様……！"
90002220-209 = "今の私にできるありったけを……！"
90002220-261 = "[log=케이 교복]光よ――――！！！！！[/log]"
90002220-264 = "[000000]光よ――――！！！！！[-]"
90002220-273 = "次回;最後の一歩"
