[translation]
90002120-1 = "第12話;消えたもの"
90002120-101 = "[ns1] \"何があっても――\"\n[ns2] \"ケイは生き残って帰るべきだよ。\""
90002120-104 = "……ちゃんと理解しているんですか？"
90002120-109 = "私が言っているのは、ここにいる全員です！私1人が帰ってどうするんですか！"
90002120-11 = "たしかに不可解ですね。#nあの3人の反応を見るに、計画通りであるとは考えにくいですが……。"
90002120-113 = "[ns] \"うん。\""
90002120-114 = "はぁ……なんですか、その笑顔は……。"
90002120-116 = "[ns] \"よっし。それじゃあ行こうか。\""
90002120-117 = "当てはあるのかしら？"
90002120-118 = "どこへだろうと、ここに留まっているよりはマシでしょう？#n周りを歩いて少しでも情報を集めなければ。"
90002120-119 = "早くヒマリたちとも合流しなければいけませんし。"
90002120-120 = "はい！アリスは勇者なので先頭に立ちます！"
90002120-121 = "頼もしいかぎりです。"
90002120-127 = "……待ってちょうだい。あれは……何？"
90002120-128 = "え……？"
90002120-130 = "（リオが指差す先を眺めた）"
90002120-131 = "（壁の向こう、遠くにいたのは――）"
90002120-135 = "（少し前までマルクトと呼ばれていた、「何か」の姿だった……）"
90002120-137 = "次回;子供たち"
90002120-16 = "あれは……何らかの儀式なのでしょうか……？#n目的は一体……。"
90002120-17 = "事実だけを述べるのなら、マルクトに収束していたエネルギーの流れが安定化したわ。#n鋼鉄大陸の変容も収まったようね。"
90002120-18 = "ケイ、貴女なら分かるかしら？"
90002120-23 = "いいえ。ずいぶんと狂信的だなという感想くらいしか。#nそれより……。"
90002120-25 = "お願いします！お願いします！#nどうか……お姉さまを奪わないでください！！"
90002120-26 = "誰かが犠牲になる定めなら、私が代わりになるから――っ！！！！"
90002120-30 = "（あの言葉の真意は……？）"
90002120-35 = "先生！"
90002120-36 = "危ないっ！"
90002120-41 = "[ns] \"うわっ！？\""
90002120-43 = "（ケイとアリス、リオに突き飛ばされた）"
90002120-44 = "先生！大丈夫ですか！？"
90002120-45 = "[s] \"何があったの！？\""
90002120-46 = "足元です！まだ終わっていません！"
90002120-5 = "どうなってるの……？"
90002120-53 = "[ns] \"壁が――地面から！？\""
90002120-54 = "っ……！？"
90002120-55 = "リオ！"
90002120-6 = "さっきまでは助け合ってたのに……仲間割れ？"
90002120-60 = "ありがとう……。"
90002120-68 = "ひとまず揺れは収まりましたが……この一瞬で壁がこんなに……。"
90002120-69 = "仲間同士が分断される……まるであの時のようですね。"
90002120-74 = "あの時？"
90002120-75 = "ケイ？"
90002120-76 = "「エリドゥ」でのことです。#nあの時は隔壁を作動させてC&Cの皆さんを分断したんでしたっけ。"
90002120-77 = "そうだったわね……。"
90002120-78 = "その時の記憶は……アリスにも残っています。"
90002120-79 = "昔の夢を見ているような、ぼやけた感じではありますが……。"
90002120-80 = "……それもそうですよね。#nあの時のアリスは……ケイと1つでしたから。"
90002120-81 = "……。"
90002120-82 = "……。"
90002120-83 = "ケイ。もしも私が――"
90002120-84 = "自分のせいだとか、自分がもっと上手くやっていればとか……#nそんなことを言おうとしているのなら、直ちにやめてください。"
90002120-85 = "け、ケイ？"
90002120-86 = "ケイ！？"
90002120-87 = "物事は[ruby=・]起[/ruby][ruby=・]こ[/ruby][ruby=・]る[/ruby][ruby=・]も[/ruby][ruby=・]の[/ruby]です。そこに理由なんてありません。#nなので、[ruby=・]そ[/ruby][ruby=・]う[/ruby][ruby=・]い[/ruby][ruby=・]う[/ruby][ruby=・]も[/ruby][ruby=・]の[/ruby]として受け入れるしかありません。"
90002120-88 = "それに、すでに起きたことをとやかく言っても仕方ないので。#nそれが自分と関係のないことなら、尚更です。"
90002120-89 = "そもそも、大事なのはそんなことではないんです！"
90002120-90 = "つまり……？"
90002120-91 = "どうすればこの状況から脱却できるか。#nそして無事に帰れるか。それだけが大切なんですよ！"
90002120-92 = "いいですか？私は生きて帰ります。何があっても――帰るんです！"
90002120-93 = "どんな事があろうと、最後まで生き残りたいんです！"
90002120-94 = "……！"
90002120-95 = "はい！ケイの言う通りです！"
90002120-96 = "[s] \"うん。私も賛成。\""
