[translation]
90002020-1 = "第2話;風雲急を告げる"
90002020-10 = "では私も――#nオペレーションおよび運航アシストを担当している[ruby=あけぼし]明星[/ruby]ヒマリと申します♪"
90002020-100 = "……私たちも、肉眼で鋼鉄大陸を視認するのは難しいけどね。"
90002020-102 = "能動的にネツァクを探知することはできませんか？"
90002020-104 = "そのためには、こちらから電波を発する必要があります。#nすぐに逆探知されてしまうかと。"
90002020-105 = "それに、信号が強すぎるせいで別の問題も起きてるよ。"
90002020-106 = "どんな信号を検知しても、結局は1つに収束しちゃう。#nもう分析する意味もないくらい。"
90002020-107 = "[s] \"つまり……どうすればいいの？\""
90002020-108 = "……。"
90002020-11 = "現時点では、定刻通りの到着となる見通しです。"
90002020-110 = "……。"
90002020-111 = "このまま進むほかありません。"
90002020-112 = "もう少し言い方というものが……。"
90002020-113 = "なにか問題でも？"
90002020-114 = "……いいえ。"
90002020-115 = "いずれにせよ、まもなく到着します。"
90002020-12 = "さて、空の旅であるわけですが……皆さん、[ruby=・]あ[/ruby][ruby=・]の[/ruby][ruby=・]時[/ruby]と比べていかがですか？"
90002020-121 = "これより、高度を下げ――"
90002020-133 = "きゃぁっ！？"
90002020-134 = "トキ、何が起きているんですか！？"
90002020-135 = "緊急事態です！巨大な……反応を検知しました！"
90002020-136 = "あれは……機械の腕？"
90002020-137 = "信号分析、完了――9番目の預言者「イェソド」です！"
90002020-139 = "イェソド！？"
90002020-145 = "うわああっ！？"
90002020-146 = "うわーん！？"
90002020-152 = "あわわわわ……！"
90002020-153 = "な、なにあれぇぇ！！"
90002020-154 = "ひ、ひぃっ……！"
90002020-156 = "皆、なんでもいいから掴まりなさい！#nエイミ！被害の状況は？"
90002020-159 = "エンジンに損傷。でも、メインエンジンは出力維持できてる。#nサブエンジンはもうダメかな……。"
90002020-160 = "エンジンから火災発生！消火システムを稼働します！"
90002020-165 = "高度と機体バランスを維持できない……。会長！このままだと――！"
90002020-166 = "墜落します！"
90002020-171 = "火災の状況は！？"
90002020-172 = "エンジン火災は鎮火しました！ただ、機体の外壁が延焼しています！"
90002020-173 = "臨界点まで、エンジンを逆噴射！"
90002020-177 = "臨界点まで、エンジンを逆噴射！#n緊急着陸シーケンス稼働！衝撃に備えて――！"
90002020-18 = "あの時は高すぎるところにいたので、実感が湧かなかったんですが……。"
90002020-19 = "い、今は、ちゃんと空を飛んでいる気分です、えへへ……。"
90002020-191 = "[ns] \"みんな、大丈夫！？\""
90002020-192 = "いたたた……目がグルグルしてるよぉ……。"
90002020-193 = "シートベルトって大切なんですね……。"
90002020-194 = "車輪1つであることを、こんなに恨んだことはありません……。"
90002020-195 = "そ、それより……ここは、どこですか……？#n説明で聞いてた、鋼鉄大陸のようには見えないですけど……。"
90002020-196 = "鋼鉄大陸の端……辛うじて残っていた土地のようね。"
90002020-197 = "私たちは、イェソドの巨大な腕に攻撃されて――"
90002020-199 = "その結果、ここに不時着したのですね。"
90002020-21 = "ねえ、会長。#n一応、言われたとおり副操縦席に座ってるけど、ここまでする必要あった？"
90002020-212 = "ま、また！？"
90002020-213 = "レーダーに敵性反応多数！#nトキ、外のカメラにつなげて！"
90002020-214 = "映します。"
90002020-22 = "ちょっと非効率的じゃない？"
90002020-229 = "あれは……[ruby=シード・ボルト]種子貯蔵庫[/ruby]で襲ってきた個体ですね。"
90002020-23 = "いいえ、このほうが合理的よ。"
90002020-230 = "包囲されているわね。このままでは……！"
90002020-231 = "大丈夫です、リオ先輩！ここはアリスがみんなを守ります！"
90002020-236 = "あっ、あ……！"
90002020-237 = "アリスちゃん！？"
90002020-24 = "人員の増加に比例して、気を使うべきことも多くなっているわ。#nその分、トキの負担を減らす必要があったのよ。"
90002020-242 = "……。"
90002020-243 = "ゲーム開発部！出動だよ！"
90002020-245 = "お姉ちゃん！？"
90002020-246 = "わ、わたし達が……？"
90002020-248 = "そう！アリスにだけ任せるわけにはいかないでしょ？#n先生、行ってくる！"
90002020-25 = "私は完璧なメイドですので、一人でも何の問題もなかったと思います。"
90002020-254 = "お、お姉ちゃん！……私も！"
90002020-255 = "一人は……みんなのために……みんなは……一人のために……。"
90002020-26 = "万が一を考慮すべきよ。#nあらゆる変数に備えておかなければならないもの。"
90002020-260 = "皆さん、待ってください！"
90002020-261 = "[s] \"……。\""
90002020-263 = "[ns] \"エイミ、ゲーム開発部のみんなを頼めるかな。\""
90002020-264 = "私？"
90002020-265 = "……。"
90002020-266 = "うん、任せて。"
90002020-27 = "リオ様がそこまで仰るのでしたら。"
90002020-272 = "[ns] \"リオとトキは、可能な限り輸送船の修理をお願い。\""
90002020-273 = "ええ……分かったわ。"
90002020-274 = "行きましょう、リオ様。まずはエンジンからです。"
90002020-276 = "私たちは何をしましょうか。"
90002020-277 = "[s] \"ケイとヒマリは……一旦待機で。\""
90002020-278 = "あら、頼られないというのも寂しいものですね……。"
90002020-279 = "いえ、分かっております。状況の全体把握はお任せください。"
90002020-287 = "あーもう！キリがない！"
90002020-288 = "ですが、ここで引くわけにはいきません！先生とみんなを守るために！"
90002020-29 = "それにしても、この輸送船……とってもすごいです！"
90002020-293 = "みんな、ちょっと後ろへ下がろうか。モモイは私についてきて。"
90002020-297 = "え……？"
90002020-298 = "この声は……エイミさん！"
90002020-299 = "助けに来たよ。#n最前線は私とモモイに任せて。"
90002020-3 = "ご搭乗の皆様、おはようございます。#n当機の機長を務めております[ruby=あすま]飛鳥馬[/ruby]トキでございます。"
90002020-300 = "アリスは後方から火力支援をお願い。"
90002020-301 = "ミドリとユズは隊列の中間を埋めてほしいな。"
90002020-302 = "はい！お願いします、エイミ！"
90002020-303 = "うん。やれるとこまでやってみよう。"
90002020-305 = "だ、大丈夫かな……？"
90002020-31 = "わ、わたしも……船の中をちゃんと見るのは初めてで……。"
90002020-313 = "まあ。"
90002020-314 = "これくらい、どうとでもなるよ。"
90002020-32 = "うーん、どうせならもっと探検しておけばよかったね。"
90002020-33 = "仕方ないでしょ、状況が状況なんだし。"
90002020-39 = "今は、記憶を辿るに留めましょう。#nコックピットを出ると、すぐそこがロビーでしたね。"
90002020-4 = "当機はただいま、高度8000メートルを飛行しており、航路上の問題は予測されておりません。"
90002020-43 = "正直、私の部屋より綺麗だった……。"
90002020-44 = "……どれだけ散らかっているんですか。ちゃんと掃除してください。"
90002020-45 = "ええ……掃除は大事だと、改めて感じたわ。"
90002020-46 = "ぷふっ！？"
90002020-47 = "あなたがそれを言うんですか……。"
90002020-5 = "間もなく目的地の鋼鉄大陸に到着いたします。#n予期せぬ揺れに備え、シートベルトをご着用ください。"
90002020-50 = "輸送船の中で最も脆弱で、最も重要なスペースが格納庫ね。"
90002020-51 = "はい。外に繋がるハッチと、降下用のポッドもありますので。"
90002020-52 = "持ってきたAMASもすべて格納庫にありますよね？#nそういえば、なにか……円錐型のものを見かけたような？"
90002020-53 = "それは……。"
90002020-54 = "……気にしなくていいわ。"
90002020-55 = "ふむ？"
90002020-56 = "格納庫だとエンジンの音がほとんど聞こえなくてびっくりしました。"
90002020-57 = "はい……い、いざという時、安心して隠れられそうって思うくらい……。"
90002020-58 = "有事の際には最も危険な場所ですから、やめてくださいね……？"
90002020-6 = "また安全のため、テーブルを元の位置にお戻しいただきますよう#nお願いいたします。"
90002020-65 = "[ns1] \"改めてすごいと思うけど……。\"\n[ns2] \"どうやって準備したの？\""
90002020-68 = "別に大したことはないわ。ミレニアムが培ってきた技術を応用しただけよ。"
90002020-69 = "想像できる分野を研究し、具現化するのは……そう難しいことではないわ。"
90002020-7 = "え？テーブルなんて無くない？"
90002020-70 = "問題は、想像すらできない分野を研究する場合。"
90002020-71 = "ええ。想像できるということは、それだけで糸口が見えている証拠ですから。"
90002020-72 = "不意に、想像もしないような事実だけを突きつけられた時の絶望感たるや……。"
90002020-73 = "[s] \"そんなこともあったの？\""
90002020-74 = "研究をしていると、時々あるんですよ。"
90002020-75 = "重力がいい例ね。#n私たちは皆、重力に縛られて生きているけれど、その根源といえる重力子は――"
90002020-76 = "スト～ップ！いきなり専門的なこと言い出すの、リオ会長の悪い癖だよ！#nそんなんじゃ、みんなに嫌われちゃうんだから！"
90002020-77 = "そ、そうかしら……。"
90002020-78 = "でも……嫌われるのは、もう慣れているから……。"
90002020-8 = "はい。言ってみただけです。"
90002020-80 = "ここでその返し方はちょっと……。"
90002020-85 = "……話を変えましょうか。#nトキ、飛行状況はいかがですか？"
90002020-87 = "航路に異常はありません。鋼鉄大陸の信号がどんどん強くなっています。"
90002020-88 = "強いて言えば、信号が強すぎるかな。着陸地点を決めるのが難しいかも。"
90002020-9 = "ふふっ。トキ機長は意外と茶目っ気があるんですね。"
90002020-90 = "着陸なんてどこでもいいんじゃないの？"
90002020-92 = "そうはいきません。#n万が一、防空システムが整った場所に向かった場合は、一巻の終わりです。"
90002020-93 = "この輸送船は「輸送」と「研究」に重点を置いてるからね。#nその分、防御力は少し低いんだよ。"
90002020-95 = "それに相手が鋼鉄大陸……つまり、7番目の預言者「ネツァク」である以上――"
90002020-96 = "私たちの常識は、通用しない可能性が高いわ。"
90002020-97 = "その通りです。実際、すでに飛行高度の判断すら難しくなっています。"
90002020-99 = "現在は雲の中に隠れながら、可視光線や赤外線、レーダーぐらいは撹乱できるように飛行しています。"
